### ISSUE TITLE
Todo: Life Modules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chummer5a/chummer5a#1]
```
Run Faster's Life Modules are another method of character generation.
```

Original issue reported on code.google.com by `richard....@gmail.com` on 31 Jan 2015 at 8:12

**Comment by chummer5a** [comment]
Current Status: Basic Save/Load methods work, but values are not loaded if the lifestyle is edited.

**Comment by joha4270** [comment]
Still contains growing pains but is in a mostly complete stage.
