### ISSUE TITLE
Infected template issues: Reduction of Essence/Magic

### ISSUE THREAD

**Issue by Luciferos** [chummer5a/chummer5a#1006]
### Environment

Chummer Version: 5.182.0
Environment: Windows 8.1
Runtime: .NET 4.5.1
### Expected behaviour

~~Infected: Banshee quality should prompt to pick statistics/immunities. ~~
~~Infected: Vampire (non-human) template shouldn't cause Chummer to crash after picking options.~~
Infected qualities should subtract 1 from Essence/Magic.
~~Infected qualities should raise the minimum and maximum attributes due to the Improved Physical Attribute.~~
### Actual behaviour

~~Infected: Banshee quality doesn't prompt to pick Improved Attributes, and appears to do nothing.~~
~~Infected: Vampire (non-human) quality causes Chummer5 to crash once attributes/options are complete. Tested on multiple non-human metatypes and mundane/non-mundane, Prime and Standard, -Priority and Sum to 10.~~
Infected qualities do not subtract essence or magic.
~~Infected qualities show as augmentations, rather than raising the base and maximum attribute values.~~

**Comment by chummer5a** [comment]
Yeah, they're kinda janky. I thought I'd hidden them away, infected pretty
much need a ground-up rebuild.

**Comment by chummer5a** [comment]
Most of this is fixed. The Magic/Essence thing is going to be a minor nightmare to implement properly,

**Comment by Hood281** [comment]
Well remember it's just strain 2 and 3 that lose an essence (max drops from 6 to 5) but strain 1 don't. They begin to fluctuate, so it's a lot weirder for them.
