### ISSUE TITLE
FBR Issues

### ISSUE THREAD

**Issue by Nitsuj83** [chummer5a/chummer5a#1007]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.182.0)
Environment: (Windows 7 and Windows 10) 
Runtime: (4.5.1) 

### Expected behaviour
(Cybersingularity adding 1 willpower for every pair of cyberlimbs.  AGI and STR reflecting augmented cyberlimb AGI and STR via customized STR and AGI and Ehanced AGi and STR)

### Actual behaviour
(Only receiving +1 will from having 2 complete pairs of cyberlimbs.  Even with full custimized AGI +STR and enhanced AGI + STR the augmented values are only showing 3 instead of 9 )

### Steps to reproduce the behaviour
(Add cybersingulariy seeker, also had Biocombatiability(Cyberware) added 4 cyberlimbs with armor, customized AGI and STR and enhanced )

### Link to affected character file
(https://drive.google.com/file/d/0B9yh10-OHufncWdrYUFDU3pDeVU/view?usp=sharing
[FBR test.zip](https://github.com/chummer5a/chummer5a/files/362290/FBR.test.zip)
)

**Comment by OLStefan** [comment]
Both works fine for me.

But these are two issue, if you can still replicate them open a new issue for each of them.
