### ISSUE TITLE
Cybersingularity Issue

### ISSUE THREAD

**Issue by Nitsuj83** [chummer5a/chummer5a#1008]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.182.0)
Environment: (Windows 7 and Windows 10)
Runtime: (4.5.1)

### Expected behaviour
(Cybersingularity adding 1 willpower for every pair of cyberlimbs. Thus if I have two full arms and two full legs I should get +2 WILL. )

### Actual behaviour
(Only receiving +1 will from having 2 complete pairs of cyberlimbs.)

### Steps to reproduce the behaviour
(Added the Cybersingularity quality and then 4 full cyberlimbs)

### Link to affected character file
(
[FBR test.zip](https://github.com/chummer5a/chummer5a/files/362338/FBR.test.zip)
)

**Comment by chummer5a** [comment]
Lower legs don't quality for Redliner or Cybersingularity Seeker, as they're not full limbs.
