### ISSUE TITLE
All existing characters fail - Nightly-v5.182.9

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#1010]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Windows 10: Nightly-v5.182.9

### Expected behaviour
characters open

### Actual behaviour
All fail. All created in previous versions

### Steps to reproduce the behaviour
Upgraded to Nightly-v5.182.9. Open existing characters

### Link to affected character folder
https://www.dropbox.com/sh/urt1cky26p0zfbc/AABaUn8Elvh6D5tXbvPmA63va?dl=0

**Comment by chummer5a** [comment]
Fixed in the latest commit, builds were a bit broken for a little bit.
