### ISSUE TITLE
Trust Fund Quality Missing from Qualities list.

### ISSUE THREAD

**Issue by SerMagikarp** [chummer5a/chummer5a#1011]
### Environment
Chummer Version: 5.182.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
Add "Trust fund" (pg. 151 Run Faster) quality to character sheet.

### Actual behaviour
Trust Fund missing from qualities list.

### Steps to reproduce the behaviour
Still not there.

**Comment by OLStefan** [comment]
You need the national or  corporate sinner quality as described in the Trust fund quality.
