### ISSUE TITLE
Changelog version does not match program version

### ISSUE THREAD

**Issue by vizax** [chummer5a/chummer5a#1013]
The Changelog shows version 5.183, but the program still shows version 5.182.0 (titlebar and help screen)

![image](https://cloud.githubusercontent.com/assets/1894549/16954696/6796bab6-4d97-11e6-80bd-0ca7fe3578ae.png)

**Comment by chummer5a** [comment]
Yeah, things got a bit messed up a while back. Short version is that nightlies increment above the current standard build, and the changelog for the updater is pulled from Github directly.  I may have to do some shenanigans with tags to make it work otherwise.
