### ISSUE TITLE
some values in /data don´t appear in /data/de_data.xml

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#1017]
### Environment
Chummer Version: Latest pull from GitHub
Environment: Win10 64 Bit

### Expected behaviour
In de.xml and de_data.xml should be a complete list of values that can translated so that the german Translation of chummer can be complete.

### Actual behaviour
chummer5 has some untranslated text in german that is not even translatable because I cannot find values for it in the datafiles. See screenshot. 

It would be great if someone could compare the .XML-files in /data and pull the values that don´t appear there in the .XML-files in /lang/$lang_data.xml so that they can be translated. For example lifemodules.xml does not appear in de_data.xml.
In Addition: How do we handle life modules that are language-specific in the translations? There are for example some ADL-specific life modules in "Schattenläufer" that don´t appear in "Run Faster" 

![1 - chummer5_rating_translations](https://cloud.githubusercontent.com/assets/4673925/17052504/07eece82-4ffe-11e6-987d-99bb0d809ec6.png)

**Comment by joha4270** [comment]
The strings are now mapped to the following keys

- Skill_SortAlphabetical
- Skill_SortRating
- Skill_SortDicepool
- Skill_SortLowerDicepool
- Skill_SortAttributeValue
- Skill_SortAttributeName
- Skill_SortGroupName
- Skill_SortGroupRating
- Skill_SortCategory
