### ISSUE TITLE
Cyber-snob not useable at creation, does not allow beta ware

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#1019]
Chummer version 5.182.0.0.

The Flavour text for cyber-snob (Chrome Flesh page 57ish?) states that to be eligible for this handycap, the character has to have at least one point of essence spent for beta grade 'wares.  

This is not possible, because Chummer does not allow beta 'wares to be used at character creation (or, to be more precise, at the transition to career mode).

The expected behaviour was that Cyber-snob would allow for beta 'ware to be implanted at creation. Otherwise this option can never be used.

An option to ignore ineligible character warnings would also be VERY welcome.

**Comment by chummer5a** [comment]
Why would Cyber-Snob allow you to take betaware? It doesn't say that in the
rules, it's just a really terribly-written quality that has an unattainable
requirement.

**Comment by chummer5a** [comment]
Selectively permitting rules violations is actually already on the cards, for whatever that's worth.

**Comment by Haekel** [comment]
> Why would Cyber-Snob allow you to take betaware?

If I have to meet certain requirements, the ability to do so is implied, in my opinion.

I agree on the terribly worded, though.

**Comment by Iridios** [comment]
I would have to agree with Haekel.  The quality as written requires the character to have at least 1 Essence worth of Betware augmentations.  This would bypass the usual limit of no augmentation over Alphaware at creation, but should not change the Availability limit.

![cybersnob](https://cloud.githubusercontent.com/assets/13158215/17096373/fe46173e-5226-11e6-8a0d-c6e54a1c33af.JPG)

**Comment by joha4270** [comment]
I'm going to disagree with that. 
It is explicitly possible to get qualities after character creation.
As i see it, this quality is simply only taken after character creation.

Unfortunately i'm afraid no one can answer really answer this except by asking catalyst for the intention behind this quality, something that don't have the best success rate.

**Comment by chummer5a** [comment]
Right, so actionable items for this are adding a <requires> node for alpha/betaware and selectively permitting rules violations.

**Comment by Lochabar** [comment]
I asked the SRM FAQ Committee this question, with this response:
"Cyber-Snob will be added to the disallowed qualities in SRM FAQ ver 0.7"
