### ISSUE TITLE
House rule request: Suprathyroid gland stacking

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1020]
Seeing as Chummer now disallows stacking of muscle stuff with suprathyroid gland, this leaves this particular piece of ware in an odd spot. A 140k 20R .7 essence ware that gets a point in body and (sometimes) REA is awkward as heck. As such, a houserule that would let the gland stack with other wares (namely muscle stuff) would be much appreciated.

**Comment by chummer5a** [comment]
Dump this into your data folder, it'll remove the precedence value for the STR and REA improvements.
[override_suprathyroid_bioware.zip](https://github.com/chummer5a/chummer5a/files/381279/override_suprathyroid_bioware.zip)
