### ISSUE TITLE
Contacts Interface Problem

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#1021]
I just found a problem with the interface. I couldn't find anything about it on a search so here it is.

I just got a 10" tablet to game on using Chummer. The interface won't let me see my contacts because it's to short and there is no way to scroll down that part of the interface. Even if I rotate the display so I get the longer view it still sets the bottom of the contacts box at the same place and won't let me enlarge that part of the interface.

There needs to be a way to scroll that part of the interface or be allowed to enlarge it some how. Otherwise there is no way to view or edit contacts. For now I will have to have a window of the character sheet printout open just so I can see the contacts. Then anytime I have to change, add, or delete a contact I will have to write notes about it and then add it once I get back to me desktop.

**Comment by SeanPGorman** [comment]
I was thinking of doing the same thing. What Tablet did you buy?

**Comment by Nightghaunt** [comment]
I got the Nextbook Flexx 10.1  Got it online at Walmart, just over $100 Great deal! Runs Windows 10 and is a 2n1 with a detachable keyboard. I got the extended warranty to so mine ended up at $150 but now if anything goes wrong I can just get a replacement. 

If you get it make sure you do ALL the maintenance updates before installing ANYTHING. Space is limited and there is a big update that you want to install and it will need all the space to do the update. Won't use it all just needs it to process the update. I made the mistake of installing a couple of things before the updates where done and had to reinitialize it and start over. lol.

**Comment by chummer5a** [comment]
That's a vertical resolution of less than 700 pixels... Um. There's a lot of bottom-anchoring and such that's currently involved that'd need to be changed. Chummer really wasn't developed with the idea of having a usable workspace below 1024x768 though, I'd be a bit worried about other stuff breaking.

**Comment by Nightghaunt** [comment]
I just realized something with this issue, you said Chummer wasn't designed for less than 1024x768 res... the res on my tablet is 1280x800.

If I set my taskbar to autohide I CAN see the first 2 contacts but its a major pain to deal with the taskbar this way when using a touch screen. You can't "bump" the edge to get the taskbar to popup so what happens is you have to touch the bottom edge and this activates what ever button/app that happens to be there then autohides again. It would be better if it worked without having to autohide the taskbar.

But there is still another issue with this. Even with it set this way I still can't see the Regain/Spend Edge buttons on the right Condition Monitor panel. It's just below the edge of the screen. I can see the "Regain/Spend Edge" text but not the text or buttons below that. 

Plus you can't see the right side of the "Other Info" tab completely so you end up seeing half of the numbers. I've tried to drag the left edge of that panel to the left to enlarge it but it won't go far enough. On my Initiative entry I see 9(11  instead of 9(11)+3d6.

**Comment by StarWeaver** [comment]
#2044 would probably solve this
