### ISSUE TITLE
Uneducated Issues

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#1025]
### Environment
Chummer Version: 182.27
Environment: Windows 7 Home Premium SP 1
Runtime: Don't know.

### Expected behaviour
Uneducated should double karma cost of several skill types and make them not defaultable.

### Actual behaviour
Uneducated doubles skill point cost of ranks and specialties for technical skills and only doubles the cost for the first rank of any affected skill purchased with karma.

### Steps to reproduce the behaviour
Assign Uneductated to character. Buy ranks in Computer or other Technical skill both with ranks and with karma. Notice effects.

### Link to affected character file
None. Noticed during math checking.

**Comment by chummer5a** [comment]
Unable to replicate. Could you please upload your character file somewhere
so I can take a look at it? If you compress the file into a zip you can
upload it here directly.

**Comment by AriMatt2** [comment]
Put a rank into computers using skill points (as an example of the first) and chemistry (might have misinterpreted Chummer math because of time I made the original post.)

[AsABrick.zip](https://github.com/chummer5a/chummer5a/files/390112/AsABrick.zip)

Drive link can be provided if that don't work.

**Comment by chummer5a** [comment]
This seems to be working properly in 5.183, unless I'm blind and/or my math is wrong.
