### ISSUE TITLE
Aspected Magician Skills not showing, please help

### ISSUE THREAD

**Issue by FenixDargon** [chummer5a/chummer5a#1026]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182
Environment: windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
being able to increase or even see the magic skill group selected at character creation with priority build or sum to ten. Have not tried karma or life modual build

### Actual behaviour
Does not show or let me increase the  selected magic skill group when creating aspected mage
### Steps to reproduce the behaviour
create aspected mage, try to increase or see Magic skill group selected. does not appear.

### Link to affected character file
(Enter text here)

**Comment by FenixDargon** [comment]
[aspected mage.pdf](https://github.com/chummer5a/chummer5a/files/389557/aspected.mage.pdf)

**Comment by FenixDargon** [comment]
cant figure out how to put up the chummer file itself, so put in the pdf of the print out of it, No magic skills, not even the group I selected at chargen.

**Comment by chummer5a** [comment]
Can't replicate it. Magic 8-ball suggests you might have used the menu
option to change your priority selection? That's currently causing the
issue you've reported,

**Comment by FenixDargon** [comment]
I wish that was the case. Havent changed the prioritys, fresh new character.

**Comment by FenixDargon** [comment]
Ok, I did some more stuffs, and its only not working when you select enchanting group at the character gen page

**Comment by chummer5a** [comment]
Aha, found the problem. I'll have it fixed in the next commit.

**Comment by FenixDargon** [comment]
Thank you!
