### ISSUE TITLE
Mounted Weapon for Vehicle/Drone uses wrong skills/stats for dice pool

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#103]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday Mar 17, 2015 at 08:56 GMT_
_Originally opened as https://github.com/chummer5a/chummer5/issues/29_

---

```
What steps will reproduce the problem?
1. Human. Set Agility to 6, Logic to 3, Pistols to 1, Gunnery to 2
2. Add Vehicle > MCT-Nissan Roto-drone
3. Right click Roto-drone > Add Modification > Weapon Mount
4. Right click Weapon Mount > Weapons > Add Weapon > Ares Predator V
5. Right click Roto-drone > Gear > Add Gear > Autosoft Rating 5

What is the expected output? What do you see instead?
There are lots of things that are not being properly reflected. The main issue 
is that the dice pool for the mounted Ares Predator V is using AGILITY + 
PISTOLS instead of AGILITY + GUNNERY

So here all the relevant rules that are missing:
Vehicle mounted guns can be operated by four different dice pools.

MANUAL MOUNT OPERATION or COMMAND DEVICE: GUNNERY + AGILITY [ACCURACY]
COMMAND DEVICE and SENSORS: GUNNERY + LOGIC [SENSOR]
DOG BRAIN via send message: TARGETING AUTOSOFT (GUN) + VEHICLE PILOT [ACCURACY]
DOG BRAIN and SENSORS via send message: TARGETING AUTOSOFT (WEAPON) + VEHICLE 
PILOT [SENSOR]

A rigger uses either of the first two options while dived. The rules aren't 
different for them, except they get all their rigger bonuses to limits and 
what-not.

What version of the product are you using? On what operating system?
Chummer5 Version 0.0.5.139 on Windows 7.

Please provide any additional information below.

If you are only going to show a single dice pool, I'd seriously think about 
only showing the drone's dice pools.
TARGETING AUTOSOFT (WEAPON) + VEHICLE PILOT [ACCURACY] 
If a gun is mounted, I'd look at the vehicle for a "Autosoft" added with 
description that contains "targeting" and the gun name, matching exactly, 
individually. If both matches succeed then use those stats, otherwise show a 
dice pool of 0. Because if a guy is going to operate it, it's the same dice 
pool no matter the gun, because it's based off gunnery, not the individual 
weapon skill.
```

Original issue reported on code.google.com by `Brad.J.L...@gmail.com` on 18 Dec 2014 at 12:17

**Comment by digitalpacman** [comment]
I think I submitted this on the old forum.
Ran into this issue again. It still uses weapon skill + agility, the only dice pool that would never be used with a weapon mount.

+1

**Comment by chummer5a** [comment]
Probably, name rings a bell. It's currently on the backlog, but I should be able to get something mocked up.

**Comment by digitalpacman** [comment]
Do you accept pull requests?

On Sun, Jan 3, 2016 at 7:04 PM, Chummer 5 Is Alive <notifications@github.com

**Comment by chummer5a** [comment]
Subject to testing, yup. Generally I fork pull requests into a local branch
and make sure everything works before pulling it into master, but I don't
have any particular objections to people contributing code. Fair warning
the code's a bit of an adventure; currently the code assumes that all
weapons are considered to be fired by the character and autosofts have no
actual functionality, so you'll need a method for finding the vehicle and
parsing any autosofts that are attached to it. You'll want to look at
clsEquipment.cs in the Weapon class. If you've got any further questions
you can email me directly at chummer5isalive@gmail.com or via google chat
at the same.

**Comment by joha4270** [comment]
If you take up the adventure, you might look into the newskills  branch, as
you are undoubtedly going to interact with skills and the code is a little
bit cleaner. It also have facilities to use another attributes than the
original already (but no autosofts)

**Comment by Atsuga** [comment]
Hi, any news on that request ?  It would be pretty usefull for my new campaign.

**Comment by joha4270** [comment]
@Atsuga Latest release allows you to click on the attribute of a skill (during career mode) and calculate the dicepool from a different attribute. 

Changing the display at vehicle page to use logic should be somewhat simple, but nobody have made the change yet. I'm a little irritated on the dice pool displays, so i'm probably going to take a crack at it once exams are out of the way.
