### ISSUE TITLE
Cannot export character to plain text

### ISSUE THREAD

**Issue by rmmonster** [chummer5a/chummer5a#1030]
### Environment
Chummer Version: 5.182
Environment: Windows 7 64bit
Runtime: 4.6.1

### Expected behaviour
printing with Text-only allows to export as Text-only to a file.

### Actual behaviour
exporting results in a html/xml file which also contains the text, but is not readable in an editor

### Steps to reproduce the behaviour
Load a Character
select print
select Text-only as Character-Sheet
export to any html/xml
get html/xml, but not a plain text file

**Comment by chummer5a** [comment]
Right-click select all, right-click copy, ctrl-v? Character sheets are all formatted XML, it's kind of expected that the HTML export isn't plaintext.
