### ISSUE TITLE
Feature Request: Exotic Skills

### ISSUE THREAD

**Issue by guruscott-meyer** [chummer5a/chummer5a#1033]
Not a defect but a feature request.  Right now only two kinds of exotic skills are available: exotic weapon and exotic ranged weapon.  My GM is requiring me to take an exotic piloting skill to control a snake type drone.  A generic exotic skill type would be useful to have in this and similar cases.

**Comment by chummer5a** [comment]
Hrm. The easiest way to do this would be to create a custom skills file.
The snake drone from Rigger 5 just uses pilot groundcraft though.

**Comment by prismatic-mind** [comment]
There is at least one drone with exotic pilot skill. Festo Pigeon 2.0.

**Comment by chummer5a** [comment]
Well, shit. Still, should be fixable.
