### ISSUE TITLE
Add Martial Art button under Martial Arts tab causes program crash

### ISSUE THREAD

**Issue by Ender289** [chummer5a/chummer5a#1036]
### Environment
Chummer Version: 5a - 5.182.0
Environment: Windows 10
Runtime:  .NET 4.5.1? Not sure.

### Expected behaviour
I'd expect a window to open with a list of martial arts to choose from, much like the behavior for adding qualities, exotic skills, or adept powers.

### Actual behaviour
As a window opens to choose a martial art, instead of a list being shown a second window quickly opens up and states the program is crashing.

### Steps to reproduce the behaviour
Open the program, open a saved character or create a new one, go to the Martial Arts tab and try to Add a martial art. For me, the program crashes at this point.

### Link to affected character file
I do not know how to link a specific character file, nor does it seem character specific. I can create a new character and the problem still persists.

**Comment by chummer5a** [comment]
Can't reproduce the error; you should receive some kind of error message
when it crashes, either a prompt to send us a notification or a more
generic crash alert.  I'd need to know what's in the crash alert to figure
it out.

**Comment by jwfitt** [comment]
I'm having the same problem. Just downloaded the latest Nightly Build, then tried to last Release build (5.183.0).
The moment I click the Add Martial Arts button it hard crashes.

![image](https://cloud.githubusercontent.com/assets/3819172/17954231/50e13a5e-6a2e-11e6-90ca-66b65727db83.png)

No character file was saved yet.
Here is the chummerlog.txt file where it seems to have a lot of issues with 32 bit vs 64 bit?
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/436037/chummerlog.txt)

**Comment by jwfitt** [comment]
Heh... I went back to the Nightly Build, and in the Tools -> Options I enables every sourcebook with the button at the bottom and it's working now! :)

![image](https://cloud.githubusercontent.com/assets/3819172/17954299/d6914e1e-6a2e-11e6-8a9b-7fdf01e00e98.png)
