### ISSUE TITLE
Magical Skills on Mundanes

### ISSUE THREAD

**Issue by Meissa** [chummer5a/chummer5a#1037]
As per Street Grimoire (pg 126, "Arcana and the Mundane"), mundane characters are capable of taking the Arcana skill.

Furthermore, the exact text is worded as follows:

> Arcana is the only magic skill not tied to the Magic attribute.
> As such, the gamemaster can optionally allow a mundane to
> acquire this skill to represent their limited understanding of the
> arcane documentation available to anyone. 

 This statement is untrue in the fact that Astral Combat and Assensing are also not linked to the magic attribute (SR5 142). Following the logic given in the text, that non-magic-linked skills are able to be taken by mundanes, and that Shade (CF 187) did not exist at the time of writing of the Street Grimoire, it follows that a mundane may also optionally be allowed by the gamemaster to take points in those skills as well.
### Environment

Chummer Version: 5.182.33
Environment: Windows 8.1, Arch Linux
Runtime: .NET 4.5.1 (Windows), Mono (whatever version is in the Arch repos)
### Expected behaviour

Mundane characters should have the Arcana skill available for purchase.
### Actual behaviour

Mundane characters do not have the Arcana skill available for purchase. There is no option to optionally allow the purchase of these skills on mundane characters.
### Steps to reproduce the behaviour
1. Create mundane character
2. Go to skills tab
3. Look for non-magic-linked magical skills

**Comment by chummer5a** [comment]
Hrm. The easiest way to implement this is just to rename the category for Arcana to something else; there's a pile of logic that's based on the category name that isn't super easy to work around. If all of the non-magic linked skills are expected to be available, then that's simple enough to fix. I'd need an official reference that indicates things like assensing and astral combat should be available to mundanes, we'll be golden.

**Comment by Meissa** [comment]
>I'd need an official reference that indicates things like assensing and astral combat should be available to mundanes, we'll be golden.

No reference for that part. It's not officially clarified, and thus I was mainly suggesting it as a house rule option, based on the ruling for Arcana.

The ruling for Arcana being available to mundanes is on Street Grimoire, page 126, as stated in the OP.

**Comment by joha4270** [comment]
It would be possible that the way to interpreting this should be that Arcana is the only magical skill that mundanes can realistically get. Astral combat and assessing requires the ability to astrally perceive, something that requires a magic attribute. 

If you interpret it that way, the statement on SG126 is true and Arcana is the only magical skill available to mundanes.

Still iffy tho. (and shade screws that over, even if its easy to conjure up an explanation about drug overdose before learning it or something)

**Comment by Lochabar** [comment]
I asked the SRM FAQ Committee this question, with this response:
"For Shadowrun Missions, Arcana is the only skill listed under Magical Skills, pgs. 142-143, SR5 a mundane may take."

**Comment by FlowersoftheKnight** [comment]
Which is interesting, considering the Background suggests differently - at least as of Runner Havens (4th Edition book), possibilities are described for mundane characters being able to Assense, and describes for the Writeup of Hongkong even schools that teach it.
(Under the influence of an astral passage everyone can Assense, regardless of how magically inclined they are.)
While I highly doubt that it will come up often, it is a technical possibility, and I would love a houserule enabler on that - if at all possible to implement.
