### ISSUE TITLE
Chummer crashes when Reapply Improvements selected

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#1038]
Loaded older character that used to fail. Character created in previous version .180 (I think)
Opened Fine in this version. Saved after making small improvement. Selected to Reapply Improvements as I think the Available Karma looks too high

### Environment
Crash followup id = 559da69b-1f2d-4e9c-8ea5-402941871409
Windows 10. Chummer 5.182.33.
Runtime: .NET 4.5.1

### Expected behaviour
Either nothing or a reduction in Available Karma

### Actual behaviour
rrrrrrrrrgh crssssshhhhhhhh (Crash)

### Steps to reproduce the behaviour
Open Char
Click Reapply Improvements
Cry - drink heavily.

### Link to affected character file
https://www.dropbox.com/s/0nzi3q34wy11cbw/Nev-yn.chum5?dl=0

**Comment by joha4270** [comment]
I haven't looked at it yet, but i just wanted to inform you that i laughed when i saw your reproduction steps.

**Comment by chummer5a** [comment]
Seems to be something janky with the metagenetic improvement for strength,
not sure what causes it.
