### ISSUE TITLE
Insert Chars without generation

### ISSUE THREAD

**Issue by salztorte** [chummer5a/chummer5a#1040]
I think is a good idea to write a function for insert a char without chargeneration. 
My group already have chars but we played a few times and dont want create the chars again.
We are happy if you can make it possible.
Thanks-

**Comment by chummer5a** [comment]
There is literally zero chance this could ever be done. The simplest way you could do this would be to create a karma-gen character and ignore the creation rules.

**Comment by salztorte** [comment]
Thanks for the quick response. And can life with this Solution.
