### ISSUE TITLE
Availability Settings

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1041]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182.41
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
When setting availability in character creation, it uses that variable instead of the default. 

### Actual behaviour
It uses default 12 and not what you set it as.

### Steps to reproduce the behaviour
Mark character as finished and save. Watch it show all items that you have purchased that are above 12 get marked as not acceptable. 

### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
Unable to reproduce with either weapons, gear, armor or cyberware on build 5.182.41

**Comment by captroberts** [comment]
Why was this closed without me given a chance to respond? I having this issue still with a saved character. I check the finish character box and go to save it and I get the  message that gear is over the limit.

**Comment by joha4270** [comment]
Well, it was closed not locked so you can respond all you want.

**But** your reproduction steps leaves me unable to reproduce the problem. If i cannot reproduce it, i cannot fix it.

**Comment by captroberts** [comment]
How do I send the file to you?

**Comment by joha4270** [comment]
I recommend https://mixtape.moe if you have to upload it, but i would much prefer _detailed_ reproduction instructions

by detailed i mean
1. Open Chummer v5.something
2. Press file->new character
3. ect

**Comment by captroberts** [comment]
1) Open chummer5a and generate character with availability set to 16.
2) Save character.
3) Get up early in the morning and rework saved character in new version of chummer5a.
4) Feel good about your character design and mark as finished.
5) Then get message that gear is over availability 12.
That is pretty much how it all happened. Hope it helps shows what I am getting on my end.

**Comment by joha4270** [comment]
This little detail about it happening after loading is just slightly important.

**Comment by captroberts** [comment]
I will take a look at that. Thanks for the tip. This is still a way better system then Lone Wolf makes.

**Comment by chummer5a** [comment]
Hrm. What item's going over the availability cap, out of curiousity?

**Comment by captroberts** [comment]
EX Ammo and Terra Cotta Sniper Rifle. Both are at availability 14.

**Comment by captroberts** [comment]
Your idea was exactly what happen. Thank you very much for that tip.
