### ISSUE TITLE
Rigger 5.0 - Life Skills not implemented. 

### ISSUE THREAD

**Issue by solaris187** [chummer5a/chummer5a#1042]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 
5.182.0

Environment: (Operating system here. If it persists over multiple OS's list them all)
Windows 10

Runtime: (If you don't know this, it is probably .NET 4.5.1)
.NET 4.5.1

### Expected behaviour
Rigger 5.0 Life Modules should selectable in the life module lists. 

### Actual behaviour
Rigger 5.0 Life Modules are not currently implemented in Chummer

### Steps to reproduce the behaviour
Select Life modules for building a character and have Rigger 5.0 selected under options

**Comment by SeanPGorman** [comment]
They are- you need to get a more recent nightly upgrade. I did this a few weeks ago and Chummer updated them.

Minor Wheelman and shop kid are present

**Comment by SeanPGorman** [comment]
This is a link to the most recent nightly build that I have seen: https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.182.41
