### ISSUE TITLE
Armor In Career Mode

### ISSUE THREAD

**Issue by MedievalBunny** [chummer5a/chummer5a#1043]
### Environment
Chummer Version: 5.182
Environment: Windows 10 Pro x64

### Expected behavior
Equipping armor in Career mode should increase the Armor rating under the Condition Monitor. 

### Actual behaviour
Armor has no effect. Armor rating is always at 0. 

### Steps to reproduce the behaviour
Create any new character, purchase armor, save in Career Mode, verify that armor is checked as equipped. 

Armor is showing correctly in the Other Info tab. Is there a difference between those two fields? Why do they both exist?

**Comment by chummer5a** [comment]
Small vestige from me being an idiot. Fixed in the next build.
