### ISSUE TITLE
Cyberlimbs aren't limited correctly for drones

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#1044]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Current (5.182.30, present in all versions)

### Expected behaviour
When installed on vehicles, cyberlimbs should have their strength and agility limited by the base device rating of the drone. Ie a directionsekrettar should be able to get 8 STR/AGI through enhancements and customisations.

### Actual behaviour
Stats are limited by the character's stats.

**Comment by joha4270** [comment]
Okay, i can understand when other people do it, but you of all people putting version as current...

**Comment by chummer5a** [comment]
That's because I know it's never worked :P
