### ISSUE TITLE
Bone Lacing

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1045]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182.44
Environment: Windows 10
Runtime:  .NET 4.5.1)

### Expected behaviour
Bone Lacing adds bonus to Body stat and Armor.

### Actual behaviour
Do not see the modified Body stat.

### Steps to reproduce the behaviour
1) Generate character with Bone Lacing (matters not which one).
2) Look at Body attribute and see no stat in parentheses'.
3) Use a No 2 pencil to correct the stat. 

### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
Re-read the description of bone lacing in the core rulebook at page 454.

"It gives you extra Body **for resisting physical damage**" (emphasis mine). It does not raise your body stat in general

**Comment by captroberts** [comment]
Very confusing with that one. Body is only used for damage resistance. Also, the chart on page 455 shows Body Boost. I will see what the forums say on it.

**Comment by joha4270** [comment]
Body is also used for physical boxes, Adept drain, Physical Addiction and there is at least one skill that is based off body.

**Comment by captroberts** [comment]
Got it. Yeah, the forums say the same thing. I will tell my players to just put it in their notes for the ware.
