### ISSUE TITLE
Chummer Characters constantly crash

### ISSUE THREAD

**Issue by upwardthinking** [chummer5a/chummer5a#1051]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Multiple but most recently 5.182.0
Environment: Windows 10 x64
Runtime: NET 4.5.1

### Expected behaviour
Change karma or nuyen or create new character

### Actual behaviour
Windows informs me the program has encountered an error and must close
### Steps to reproduce the behaviour
Create a new character or attempt to update karma or nuyen
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/416899/chummerlog.txt)

This is an issue that apparently came out of nowhere but nothing I try has worked and I now have character sheets I cannot use nor can I work around it by creating new ones

**Comment by chummer5a** [comment]
Looks like the application crashed while trying to update your character's armour rating, but I can't reproduce it. Could you upload your character file? Are you in an en-US region?

**Comment by upwardthinking** [comment]
I am in a en-US region though I'm not what problems that would cause but welcome any input or a possible work around for the time being, here's the chummer file I'm trying to update (the site won't let me do a direct upload so here's a google drive link to the file): https://drive.google.com/open?id=0ByoEuSU41RYhbVdyVmpZWjk5RGc

**Comment by chummer5a** [comment]
Hrm, still can't reproduce it. Can you please try in 5.183.0 and let me know how you go?

**Comment by upwardthinking** [comment]
The new build seems to have resolved it, that being said the crash I was seeing was from Windows not from chummer so something about how chummer was interacting with windows was causing the crash in case this is something you want to look into.
