### ISSUE TITLE
Custom Fit (Stack) does not work after reopening character

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1052]
### Environment
Chummer Version: 5.182.0
Environment: Windows 10 Pro, Windows 7 Home Premium
Runtime: probably .NET 4.5.1

### Expected behaviour
Custom Fit (Stack), Add armor value to other armor by the same fitter and display total armor in Other Info

### Actual behaviour
Auto-populates Custom Fit (Stack) on purchase but when the character sheet is reloaded selecting the Custom Fit (Stack) generates a dialog that requests a stack target but regardless of selection armor value in Other Info tab shows highest equip armor not stacked armor

### Steps to reproduce the behaviour
1. Add any Custom Fit (Stack) armor
2. Add any Custom Fit armor from the same maker
3. Save Character
4. Close Character
5. Reopen Character

**Comment by chummer5a** [comment]
Should be working properly in the latest nightlies.
