### ISSUE TITLE
Enhancement: Simulate/Validate

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#1053]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Expected behaviour
Is there a way that we can simulate the character generation or add a validation button.

I know most of us take a copy of the character file but it would be easier to click a button to test the current build is legal. I'm working on a complicated changeling and he is proving hard to validate

**Comment by chummer5a** [comment]
It's been on my to-do list for a while to highlight things that are invalid, but as an interim we can definitely just add a button to confirm the character's valid.

**Comment by SeanPGorman** [comment]
Thank you. Perfect.
