### ISSUE TITLE
will not run in windows 10 this anniversary update

### ISSUE THREAD

**Issue by gwilymwarne** [chummer5a/chummer5a#1054]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer5.182.0
Environment: windows 10 with Anniversary update
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
open new character, edit existing character set up chummer with new install
### Actual behaviour
crash with no crash report

### Steps to reproduce the behaviour
inistalled and re installed both Chummer5.182.0 and 180 still does not work

**Comment by chummer5a** [comment]
Can't replicate, would need to see the error.
