### ISSUE TITLE
Crashing on opening skills tab

### ISSUE THREAD

**Issue by CJHGuvna** [chummer5a/chummer5a#1055]
### Environment
Chummer Version: 5.182.0-5.183.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Opening my Skills menu displaying my skills and allowing me to add to them (In career mode and during creation.)

### Actual behaviour
Crashes the program on all characters including freshly created in these versions, created but out of career and in career (including characters from previous versions). Within my group I am the only person having these issues. 

### Steps to reproduce the behaviour
Happens every time on 5.182.0 and all of the nightlys leading up to and including 5.183.0 

### Link to affected character file
Any character sheet created in this version and previous versions.

**Comment by joha4270** [comment]
Try reinstalling. Updates should work, but depending on version something might have gone wrong it it might be a combination of settings making chummer act up.

>Within my group I am the only person having these issues.

What is unique about you in your group? This post doesn't really give any starting point to troubleshoot from. Unless i have more information, i don't have a way of fixing it.

Did it provide a crash id? if yes, please put it here (or crash it again and put it here)

**Comment by CJHGuvna** [comment]
I was the only one with the group I roleplay with that was facing the issue. I moved my old directory of Chummer and 5.183.0 now works other then having broken skills groups.

**Comment by joha4270** [comment]
Broken like this?

![image](https://cloud.githubusercontent.com/assets/4454884/17674260/14f7e4da-6325-11e6-8946-5bf16444ca18.png)

It just means that the skill group is broken and you cannot increment it.

**Comment by CJHGuvna** [comment]
That is correct. I didnt realise it meant that. Thanks for the help. And after further testing with Administrator on and adding an exception to my anti-virus it wont crash. However if I stop running as administrator it still crashes.

**Comment by joha4270** [comment]
Seems that it does something your anti virus and/or windows finds disagreeable. Does your anti virus have any kind of log that could provide a clue?

Also, what directory is chummer located in?

**Comment by CJHGuvna** [comment]
I cant find a log for it. I use Avast and before I added an exception it would scan the file and then refuse to open it saying it could be dangerous (I assume because it shows up as no publisher and it hasn't encountered the file commonly since on older version it scans and then just lets me open it) 

E:\Character Sheets and Shadowrun Books\Chummer5.183.0\Release

**Comment by CJHGuvna** [comment]
Yeah its non-ideal but I can work with it. Previous version have got cleared before so I can hope. I had been running on .178.2 (last update I didn't have an issue for my character) so its nice to update to something new.

**Comment by chummer5a** [comment]
179+ did some shenanigans with the update mechanisms that are probably
what's triggering avast. Could probably force it to disable that stuff and
resolve your issue.

**Comment by CJHGuvna** [comment]
Skills crash still exists outside of running Admin. Also got notifications pop this morning that Avast now thinks the files are fine.

**Comment by chummer5a** [comment]
Can you upload your chummerlog file?

**Comment by CJHGuvna** [comment]
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/420128/chummerlog.txt)

**Comment by chummer5a** [comment]
That's... interesting. @joha4270, any ideas? Looks like it's failing to load omae stuff or something.

**Comment by drseltsam83** [comment]
I have the same problem as well.
[Jimmy Hill _last_final_version.zip](https://github.com/chummer5a/chummer5a/files/467826/Jimmy.Hill._last_final_version.zip)
I'm using chummer 5.183.26. There is no crash but those broken links at the groups.
![chummer_screenshot_broken_groups](https://cloud.githubusercontent.com/assets/19826108/18444251/b950f9c8-7918-11e6-85f7-a944a631dd09.png)

**Comment by CJHGuvna** [comment]
Broken just means you have broken the skill group. So in your screen shot say for example you spent 2 on computer, 5 on hardware and 4 on Software. Since they are not brought in the group and they are all different the group is "broken". I didnt understand that be initially but it made sense once someone explained that to me.

**Comment by joha4270** [comment]
Except that its the thing with most confusion in recent development, so that would imply does *not* work. 

Not sure how to change it, though

**Comment by drseltsam83** [comment]
@CJHGuvna You're right. I missunderstood the term broken (I got confused by crashes in earlier version in the same section, but now it works). Anyway, still I can't raise the _unbroken_ groups...

**Comment by joha4270** [comment]
@drseltsam83 Sure you have enough karma? If that isn't the case, upload it somewhere. Just guessing form a picture of the UI is not really a way of debugging

On the other hand, you should create your own issue for it. This thread is related to another error. (even if i broke that too)

**Comment by chummer5a** [comment]
Does this crash still exist in current builds?

**Comment by CJHGuvna** [comment]
It does not exist on 5.184.0 as I no longer need to run it as Admin. Have yet to try 5.185.0

**Comment by chummer5a** [comment]
Good enough for me!
