### ISSUE TITLE
Can't add Power Points to Improved Ability.

### ISSUE THREAD

**Issue by boongeebee** [chummer5a/chummer5a#1057]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182.44
Environment: Windows 7 and 8
Runtime:  .NET 4.5.1

### Expected behaviour
After adding the adept power "Improved Ability (skill)" or gaining it from the Seducer mentor spirit, I should be able to put more power points in the skill.

### Actual behaviour
After adding the adept power "Improved Ability (skill)" or gaining it from the Seducer mentor spirit, I can't more power points in the skill. It stays at 1.  I have 6 ranks in the skill and maxed my Cha, so that is not the problem.  Is there a specific order that I need to use in character creation? I thought I could jump around.

### Steps to reproduce the behaviour
Hit "New Character" button.  Pick any character creation method. Add adept power "Improved Ability (skill)" or the "Seducer" "Mentor Spirit". Go to the adept powers tab and try to add power points to the power.

### Link to affected character file
Happens multiple times in the early stages of Character Creation, so I don't think it's the file.
https://drive.google.com/file/d/0Bw29unDKxWJjQ083VzNjU2pRZHM/view?usp=sharing

**Comment by chummer5a** [comment]
I can't replicate the issue in 5.183, could you please try again with the latest build? Generally speaking, the only things that should be preventing you from increasing the powers for Improved Ability should be your MAG or skill level.

**Comment by boongeebee** [comment]
Tried the latest Nightly. I still can't add any power points to the free level of Improved Ability the Seducer mentor spirit grants.  I have tried raising my MAG score and have maxed my ranks in the appropriate skill.
I can add another Improved Ability power targeting the same skill and have them stack, but then if I max out the second one I end up with a total of one over my MAG stat.
![capture](https://cloud.githubusercontent.com/assets/21060822/17856648/c2cc8f78-683b-11e6-8228-b5135f565ba8.PNG)

**Comment by chummer5a** [comment]
Hmmm. It could be not updating the bounds properly, though i have no idea why it wouldn't be doing that. Does it change anything if you click the down arrow to reduce the rating?

**Comment by boongeebee** [comment]
When I have done that it does allow me to then add more points, but it does not reduce the number of available points.  It still won't let me go above my MAG score though.
![capture1](https://cloud.githubusercontent.com/assets/21060822/17860668/6f86193c-684b-11e6-8e49-205dbde151c6.PNG)
