### ISSUE TITLE
Redliner

### ISSUE THREAD

**Issue by skachm** [chummer5a/chummer5a#1066]
### Environment
Chummer Version: 183

### Expected behaviour
Redliner quality applies to base stats and limbs stats. 

Rules clarification here: https://www.reddit.com/r/Shadowrun/comments/4a99px/rule_clarification_redlinecyber_singularity/d0z7nqu

### Actual behaviour
Redliner applies to base stats only.

**Comment by chummer5a** [comment]
Can't replicate the problem as of Nightly-v5.183.8.

**Comment by skachm** [comment]
Ok, the new way 5.183.10 nightly reports augmented attributes cleared it up... It's confusing that a cyberskull is added in when averaging limbs for the augmented value.

**Comment by chummer5a** [comment]
*Shrug* RAW says to treat it that way. You can change what counts as a limb
in the Options under Character and Printing.
