### ISSUE TITLE
Crashing when adding metamagics

### ISSUE THREAD

**Issue by EiraHaexa** [chummer5a/chummer5a#1067]
Chummer crashes in both create mode and career mode when attempting to add metamagic abilities to initiation grades

### Environment
Chummer Version: 5.183.o
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Window to select metamagics appears and allows selection of metamagic ability 

### Actual behaviour
Window to select metamagics loads partially, then causes program to crash. 

### Steps to reproduce the behaviour
Attempt to add metamagic to an initiation grade 

### Link to affected character file
Wolf Queen.chum5

**Comment by chummer5a** [comment]
No file linked? If you compress it into a zip you can upload it directly to here.
