### ISSUE TITLE
German translation of sourcebooks

### ISSUE THREAD

**Issue by Letschi** [chummer5a/chummer5a#1068]
Hey, no issue here, I just found no other way of contacting you.

I saw that there are a few of the sourcebooks available in german in the options menu. I have the german versions of the books Chrome Flesh, Data Trails, Rigger 5.0 and Run and Gun. Is there a way I could help out  or fully translate these, so you can include those as well in the options?

**Comment by joha4270** [comment]
The (german) books in options don't refer to translations, but to content
that exists in the German translations but not the English versions.

You are welcome to check if you can find anything in the German versions
that don't exist in the English versions, but i believe we are up to date.

Keyword here is believe.

This is a fine location to contact us.
