### ISSUE TITLE
Crashing when deleting/removing any objects

### ISSUE THREAD

**Issue by kaysic** [chummer5a/chummer5a#1069]
### Environment
Chummer Version: 5.183.0
Environment: Windows 7 Enterprise
Runtime: NET 4.5.1

### Expected behaviour
When removing an item from any category, pressing "Delete" (the key or in-UI button) will remove that item, recalculate related statistics that item affected, and (if in character generation) refund the cost of that item's karma or nuyen. 

### Actual behaviour
Removing any item, in any menu, will crash Chummer immediately after removal.

### Steps to reproduce the behaviour
1. Open any character
2. Go to any menu in which Chummer has an object list with removable objects (Common, Martial Arts, Cyberware, Street Gear and its submenus, etc).
3. Attempt to delete/remove any object (if none present, adding one does not change behavior of bug)
4. If Chummer doesn't immediately crash, click anywhere once.

### Link to affected character file
N/A; affects all tested character files from multiple versions.

**Comment by chummer5a** [comment]
Unable to replicate; I'd suspect that it's something to do with an object refresh, but unless I can see where it's crashing out I won't be able to do much. When it crashes, Chummer should give you a prompt to send us a log of what happened. Clicking no should show the standard error log.

**Comment by chummer5a** [comment]
This *may* be fixed in https://github.com/chummer5a/chummer5a/commit/6f058ec948d5c484a0aa7d46b7628b4c9008ea21. Could you please try the latest nightly build and see if it still crashes?
