### ISSUE TITLE
Mnemonic Ehancer knowleadge skill bonus not being applied

### ISSUE THREAD

**Issue by CrimsonSurge** [chummer5a/chummer5a#1073]
### Environment
Chummer Version: 5.183
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Mnemonic enhancers adds it's rating to dice for memory, mental limit, knowledge and language skills.

### Actual behaviour
Adds it's rating to only memory and mental limit.

### Steps to reproduce the behaviour
Add Mnemonic Enhancer cultured bioware.

### Link to affected character file
N / A

**Comment by chummer5a** [comment]
Can't replicate it in current builds; are you putting points or karma into the skill to activate it? per RAW, defaulting skills can't benefit from gear bonuses.

**Comment by CrimsonSurge** [comment]
Putting either points or karma into knowledge skills makes no difference. I put a point into any knowledge skill i.e adding biology  by using either karma or knowledge skill point, and then add mnemonic enhancer and the rating of the enhancer isn't added onto the dice for that skill. Turns out once you add or subtract a rank after you add the mnemonic enhancer onto the character to it then the number of dice changes to reflect the added mnemonic, it doesn't change automatically and has to be done for each individual knowledge skill.

**Comment by chummer5a** [comment]
Aha, that's the missing bit! Okay, easy fix. Will be in the next nightly build.
