### ISSUE TITLE
Smartskin not applying rating as armour

### ISSUE THREAD

**Issue by Icarusdave** [chummer5a/chummer5a#1074]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.0
Environment: Win 10 Home (x64)
Runtime: .NET 4.5.1

### Expected behaviour
Nanocyberware Smartskin armour rating shown in other info and on printout

### Actual behaviour
No armour is displayed either when applied on it's own or in concert with bone lacing (NB bone lacing armour is shown correctly)

### Steps to reproduce the behaviour
Add smartskin nanocyberware

### Link to affected character file
attached rusty.chum5
[Rusty.zip](https://github.com/chummer5a/chummer5a/files/442214/Rusty.zip)

**Comment by chummer5a** [comment]
Technically working as intended, as smartskin isn't on all the time.

**Comment by chummer5a** [comment]
If you'd like this to be enabled permanently, I'd suggest just creating a custom improvement for it once you hit career mode. Once we get around to managing wireless bonuses this sort of thing will be easy to manage, but as is it's not really on the roadmap.
