### ISSUE TITLE
Adding certain Mentor Spirits crashes chummer

### ISSUE THREAD

**Issue by CrimsonSurge** [chummer5a/chummer5a#1075]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.12
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Add quality Mentor Spirit, select any of them and click ok and it gets added with whatever bonuses you receive.

### Actual behaviour
Add quality Mentor Spirit, select any of these ones (Bear, Berserker, Boar, Cat, Dolphin, Dragonslayer, Eagle, Giraffe, , Great Mother, Monkey, Mountain, Mutation, Peacemaker, Rat, Raven, Sea, Snake, Spider, The Adversary, Whale, Wolf) click ok, then after making any choices that you may need to make for certain spirits and then chummer proceeds to crash.

### Steps to reproduce the behaviour
Add quality mentor spirit, select any of the ones listed above and click ok.

### Link to affected character file
N / A

**Comment by chummer5a** [comment]
Can't replicate it; what kind of awakened are you making?

**Comment by CrimsonSurge** [comment]
Just checked, only seems to happens with Adepts

**Comment by chummer5a** [comment]
Hmm. Still can't replicate it; are you using a non-English language file? Are you in career mode or character creation? Build method? If you make a new character does it still do it?

**Comment by CrimsonSurge** [comment]
Attempted in both career and character creation and made no difference, also tried different build methods and same thing, I'm using the English language file. The crash only happens when using the nightly builds 5.183.10 and onwards, so guessing the bug got introduced on that version, doesn't happen on any nightly before then or the latest normal release build.

**Comment by chummer5a** [comment]
Fgsfds. Found the problem, I'm an idiot. Will be fixed shortly.

**Comment by CrimsonSurge** [comment]
Checked the new 5.183.15 nightly and it's fixed :) Gonna close the issue now, thankyou for fixing it.
