### ISSUE TITLE
Pressing cancel when choosing a skill to select a tool kit for, causes Chummer to crash

### ISSUE THREAD

**Issue by CrimsonSurge** [chummer5a/chummer5a#1076]
### Environment
Chummer Version: 5.183.15
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Goto add gear tool kit, press cancel when given drop down menu to choose skill for it and should go back to your gear list.

### Actual behaviour
Goto add gear tool kit, when presented with drop down menu press cancel and Chummer crashes.

### Steps to reproduce the behaviour
Goto add gear tool kit, press cancel when given list of skills to choose the tool kit for. This is present in both 5.183.14 and 5.183.15 versions of Chummer.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Fixed via https://github.com/chummer5a/chummer5a/commit/6f058ec948d5c484a0aa7d46b7628b4c9008ea21.
