### ISSUE TITLE
Vehicle Weapon Mount: visibility, Flexibility and Controll Type as Modififications of the Weapon Mount Type

### ISSUE THREAD

**Issue by darkmeadow** [chummer5a/chummer5a#1077]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
### Environment

Chummer Version: 5.183.0
Environment: all
Runtime: all
### Expected behaviour

It would be good for the oversight if the weapon mount modifications (visibility, flexibility and control type) 
were modifications of the actual Weapon Mount Type (light, Standard or heavy).
### Actual behaviour

All weapon mount modifications are on the same level in the vehicle tree.

**Comment by Maxis010** [comment]
Good idea, but with how the mod slots are currently implimented it can't be done

**Comment by chummer5a** [comment]
Mmm, we'd probably have to do something shenanigansy with making weapon mounts into a new class or adding a form that prompted you for those details on first addition.

**Comment by darkmeadow** [comment]
thanks for looking into it, maybe you can use a simular system like you already have for cyberimplants.
