### ISSUE TITLE
Enhancement: Scalable Options UI

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1080]
### Expected behaviour

~~1) Size and location of main window saved and restored when Chummer starts.
2) Able to clear list of character files shown in File Menu.
3) Restart option on File Menu.~~
4) Options window resizable.
### Actual behaviour

~~1) Chummer starts with a specific size that unfortunately is larger than the display being used and has to be resized.
2) List of characters builds. Only way to tidy it up is to edit the registry.
Can a menu item be added to delete the list of characters that are notchecked as favourites?
3) Have to Exit and restart Chummer to pick up changed Options.~~
4) The options window is slightly larger than my display, making it difficult to save.
Can this window be made resizable, with drag bars?

**Comment by joha4270** [comment]
Good god, what kind of monitor are you using?

The options window is 700px + borders high.

**Comment by Lochabar** [comment]
It's a virtual Windows 7 machine running on a Mac. The display is limited with the two o/s's.

**Comment by chummer5a** [comment]
I think we'd have to look into using something like Jot to manage this, but the size issue is generally indicative of a larger problem. A large chunk of the UI has been written with an expectation of a workspace that's at least 800 or so pixels high; anchoring for things like the quality lists and such is a large culprit behind why we can't just make it scrollable.

**Comment by chummer5a** [comment]
![image](https://cloud.githubusercontent.com/assets/11448441/18436986/48f671e6-793e-11e6-8a60-b6ed99f24ee5.png)
Early stages of a refactor on the UI. Will hopefully be quite customisable by the time I'm done with it.

**Comment by Lochabar** [comment]
Point 3, restart option on File Menu, has been struck out. I know you've added some code for offering a restart. However a Restart option on the menu would be very helpful - especially switching between supported languages.

**Comment by chummer5a** [comment]
Strictly speaking the restart button shouldn't be needed anymore, but there's a slim possibility it might be helpful in case of memory bloat or somesuch. Resizable options menu will happen as part of the Options Rewrite milestone.
