### ISSUE TITLE
Agility not calculating correctly with Muscle Toner and Suprathyroid Gland

### ISSUE THREAD

**Issue by magid23** [chummer5a/chummer5a#1082]
### Environment
Chummer Version: 5.182.0.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
I have a character (Oni), with a max base agility (7) and a metatype max agility of 11.  With a muscle toner rank 3 and a suprathyroid gland I should have an agility of 11.

### Actual behaviour
With the above situation, the bonus between the muscle toner and suprathyroid gland are overlapping and my character's agility is 10.

I tested this with muscle augmentations (bioware str instead of agl) and suprathyroid gland, it functioned as expected.

### Steps to reproduce the behaviour
1. Create new character (I used Oni with priority)
2. Max agility (7)
3. Add Muscle Toner 3
4. Add Suprathyroid Gland

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Muscle toner explicitly states that it doesn't stack with augmentations that increase Agility.

**Comment by magid23** [comment]
Ah, I should've read that, but then there is a different problem: Muscle augmentations also explicitly states it doesn't stack with augmentations that increase strength, but it did stack with the suprathyroid gland in the above example.,

**Comment by chummer5a** [comment]
That's resolved in 5.183, which should be available through the update
system or via https://github.com/chummer5a/chummer5a/releases/latest

**Comment by magid23** [comment]
Ah, ok, thank you very much and I apologize for my early error.
