### ISSUE TITLE
Add Enemy Crash, Negative Quality Karma bypass

### ISSUE THREAD

**Issue by AxDeath** [chummer5a/chummer5a#1088]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.28 DEBUG BUILD
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Clicking ADD ENEMY will let you bypass the set limit of 25 Karma from Negative Qualities, until you hit 70 gained, and then trigger a warning message. Modifying the connection of any Enemy beyond 25 Karma will trigger the 25 Karma warning, and then crash the program.

### Steps to reproduce the behaviour
Add Negative qualities to about 23 Karma gained. Click ADD ENEMY a couple times.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Fixed in the latest nightly.
