### ISSUE TITLE
Enhancement: Optional rule to allow Betaware by taking the Restricted Gear quality

### ISSUE THREAD

**Issue by AxDeath** [chummer5a/chummer5a#1089]
### Environment

Chummer Version: (What version of chummer are you running?
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)
### Expected behaviour

Looking for an option to toggle Restricted Gear to bypass Betaware+ restrictions.
### Actual behaviour

Restricted Gear currently allows availability to be bypassed correctly, but character creation still breaks if the item is a piece of cyberware that breaks the limit on Ware by being Beta or Deltaware etc.

The purpose of the Restricted Gear quality is under debate. It seems reasonable that because it allows a bypass of up to 24 availability, not allowing a bypass on 'ware levels, puts yet another onus on people who own a copy of Chrome Flesh and want to use it.
### Steps to reproduce the behaviour

Snap on a Deltaware Torso, acquire the Restricted Gear quality, and hit the Create Character or Check Creation to get a fail marking the Torso as the trouble.
### Link to affected character file

(Enter text here)

**Comment by chummer5a** [comment]
I'm not aware of any adjustments to the Restricted Gear quality in Chrome Flesh that would allow starting with betaware, save for that argument about cyber-snob. Page reference?

**Comment by AxDeath** [comment]
By RAW, Restricted Gear does not allow betaware, only bypass of Availability limit. That's why I was requesting an option to be toggled on or off. I, and others, would argue the spirit of Restricted Gear is to access gear not normally available. The gain from equipping Beta or Delta ware is statistically much less than the Panther Canon or Heavy Milspec you could get with Restricted Gear. It's not high priority.

**Comment by chummer5a** [comment]
Right, I get what you're after. Shouldn't be hard to implement, might get it done over the weekend.
