### ISSUE TITLE
Fail To Open Newest Version

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1090]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.33
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behavior
Should be able to double click on application and the program start.

### Actual behaviour
Double click the app, and nothing happens.

### Steps to reproduce the behaviour
1] Download program and unzip into folder.
2] Open folder and double click on app.
3] Watch as nothing happens.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
What was the last working version you used?  Are you overwriting the
existing folder or extracting it somewhere else? Does it crash?

**Comment by captroberts** [comment]
I use the same folder, but delete everything in it. Have done that on every version so far. It gives no Crash window. The program does nothing when I try to open it.

**Comment by captroberts** [comment]
Just downloaded 34. Still doing the same thing.

**Comment by Lochabar** [comment]
I am having the sane problem, versions 30-34.
I export from the zip file and use a new folder.

**Comment by Iridios** [comment]
I have a similar problem.  With both .30 and .34.  I downloaded .30 the other night and unzipped it into my main Chummer folder (after moving the older version to a backup folder) and initially it worked.  Changed some settings then closed the Character Roster.  Then I closed Chummer to move some custom files into the data folder.

When I tried to restart Chummer I got a sort of crash report.  It said I could find info about the crash in the following files:   WERDEAC.tmp.WERInternalMetadata.xml, WERE274.tmp.appcompat.txt, and WERE295.tmp.mdmp.  I removed the customs and tried again with the same result.  I deleted all the chummer files and extracted 'clean' files with the same result.  I extracted to a new folder, again with the same result.  I restored the older version (183.4) and it works fine.

I dug into the Windows Application logs and find the following two errors for each time I try to open Chummer.

First, a .Net error:
Exception Info: System.ArgumentException
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   at System.IO.Directory.GetFiles(System.String)
   at Chummer.frmCharacterRoster.LoadCharacters()
   at Chummer.frmCharacterRoster..ctor()
   at Chummer.frmMain..ctor()
   at Chummer.Program.Main()

Then an Application error:
Faulting application name: Chummer5.exe, version: 5.183.34.0, time stamp: 0x57d18de1
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23418, time stamp: 0x5708a7e4
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x1628
Faulting application start time: 0x01d20a1f03909086
Faulting application path: C:\Users\t\Documents\RPG\Shadowrun\SR5e\Chummer.183.34\Chummer5.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 42db4ad5-7612-11e6-a909-2c27d7b0b091

**Comment by chummer5a** [comment]
Hmmm. Okay,

**Comment by Iridios** [comment]
On initial extraction and opening.  It works!  I even closed the roster, then closed Chummer and reopened it.  I will play with it deeper.  I will make settings changes and add my custom files.  Will report shortly.

**Comment by captroberts** [comment]
Just downloaded version 35. It opened just fine. I did nothing different then I normally do. It opened up and is working perfectly. Don't know what you did in this, but thank you.

**Comment by chummer5a** [comment]
Basically the problem was that if you didn't have a watch folder set up for your character roster, it would try and get all files in a directory that didn't exist, so it'd return an error. Not sure why it wasn't erroring on my dev box, but eh. It's more robust now.
