### ISSUE TITLE
Minor, Text / Correction, Sparring Drone Large / Medium, Multiple Type Drones

### ISSUE THREAD

**Issue by AxDeath** [chummer5a/chummer5a#1091]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.35

### Expected behaviour
(Enter text here)

### Actual behaviour
Sparring Drone listed as Medium, According to Hard Targets, page 190 it is a Large drone.

I've never wondered before, but can an item show up on more than one list? There is an Anthro drone listed under Large Drones category (Modified Renraku Manservant). 
When trying to find drones for an aesthetic it might be nice to have them listed under multiple categories. Large, Flying. Micro, Anthro. etc.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Technically, allowing multiple categories wouldn't really be a problem. My personal preference would be to separate the chassis types and such into their own fields though, so you'd have a [Large] [Anthro] drone. Hrm. I'll have a think about it.
