### ISSUE TITLE
Lifestyle : Free Grid Susbcriptions lp cost while editing advanced lifestyle

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1094]
### Environment
Chummer Version: 1.183.41
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When creating advanced lifestyle, matrix subscription are added with a 0 lp cost. It's fine.
When editing this lifestyle, lp point should not change and free grid subscriptions should keep 0 lp.

### Actual behaviour
But when editing this lifestyle, the free grid subscriptions decrease the number of lp points.

### Steps to reproduce the behaviour
Create advanced lifestyle with free grid subscription, for exemple high level lifestyle, check number of lp points remaining and add it to character.
Edit the lifestyle and check lp points remanings

**Comment by chummer5a** [comment]
Hrm, I can't replicate this. Can you upload an affected character file? Compressing it to a zip or renaming the extension to .txt should allow you to upload directly here.

**Comment by prismatic-mind** [comment]
My bad, it appear that i made the test with a lifestyle created with an older version edited with the version 5.183.41

With newly created lifestyle, no bug.

If you still want the file tell me, i'll take time to make it.

**Comment by chummer5a** [comment]
No worries, happens quite a bit! If the matrix grid qualities that still have LP are being stored in the Free Matrix grids node I'd like to see the character to see what's what, but otherwise there won't be much to learn from it.

**Comment by prismatic-mind** [comment]
[campagne hk - Tseung Ni Na.txt](https://github.com/chummer5a/chummer5a/files/478796/campagne.hk.-.Tseung.Ni.Na.txt)
.zip renamed .txt
Check the lifestyle : "Nouveau logement à prospecter"

**Comment by chummer5a** [comment]
Yup, old file from before I fixed the issue.
