### ISSUE TITLE
Not able to buy points in skill groups

### ISSUE THREAD

**Issue by drseltsam83** [chummer5a/chummer5a#1096]
As already discussed in #1055 in career mode there is no button to improve the skill groups even though there would be enough karma to buy it. THere are no buttons for skill groups at all. The layout seems to be missaligned in general. Maybe the button are not visible.

### Environment
Chummer Version: 5.183.26
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
(+) Button next to group to improve the skill group.

### Actual behaviour
No buttons at all.
![chummer_screenshot_groups](https://cloud.githubusercontent.com/assets/19826108/18445172/8ecb79b8-791c-11e6-8326-e29f57efcb50.png)

### Steps to reproduce the behaviour
Load char, switch to skill groups tab.

### Link to affected character file
[Jimmy Hill _last_final_version_chummer_issue.zip](https://github.com/chummer5a/chummer5a/files/467907/Jimmy.Hill._last_final_version_chummer_issue.zip)

**Comment by chummer5a** [comment]
Okay, I see what the problem is. Might be an easy fix, there's some shenanigans with widths I need to look into.
