### ISSUE TITLE
Post-Specialisation Karma not deducted

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#1097]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.0
Environment: Windows 10
Runtime: .NET 4.5.1)

### Expected behaviour
Karma is always charged

### Actual behaviour
in a karma guild, When adding a specialisation at char gen editing the skill afterwards sometimes wont charge for karma

### Steps to reproduce the behaviour
Add spec, raise skill, see lack of karma taken

**Comment by chummer5a** [comment]
Can't replicate the issue in 5.184; there's a slim chance that it's just not updating the values properly at the time, but I'd need to see a before-after version of the character files to confirm. Could you please test in the latest version and provide a little more detail to reproduce it consistently?

**Comment by Gamingharry** [comment]
This issue seems to have stopped on 5.184 :) thanks all the same I will let you know if it reoccurs
