### ISSUE TITLE
Changing Priority on Magical Char removes magic skills

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#1098]
### Environment
Chummer Version: (What version of chummer are you running?
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Chummer Version: 5.183.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Actual behaviour
When priority is changed Magic skills are not changeable

### Steps to reproduce the behaviour
create magical char - edit priority but remain magical

**Comment by chummer5a** [comment]
It's a known issue; if you hit Reapply Improvements in the Special menu
it'll fix itself.

**Comment by chummer5a** [comment]
This was fixed in https://github.com/chummer5a/chummer5a/commit/0da2294e47ac06ee88ddb4d0485e5b8f731a3685. Please try using the Nightly builds for now: https://github.com/chummer5a/chummer5a/releases, and I'll hopefully have a new Release build prepared this weekend.
