### ISSUE TITLE
Lifestyle Qualities are not displayed in character viewer

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1100]
### Environment
Chummer Version: 5.183.41
Environment: Windows 7
Runtime: .NET 4.6.1

### Expected behaviour
Lifestyle qualities displayed in character viewer.

### Actual behaviour
They do not appear.

### Steps to reproduce the behaviour
Build a lifestyle with positive and/or negative qualities.

**Comment by chummer5a** [comment]
Can you give me a screenshot of what you're referring to? I can't replicate what I think the issue is.

**Comment by Lochabar** [comment]
Couldn't upload files directly to this area.

https://www.dropbox.com/s/c3cj9q8imnp4xn5/1100.zip?dl=0
