### ISSUE TITLE
Character Rooster is confusing

### ISSUE THREAD

**Issue by joha4270** [chummer5a/chummer5a#1108]
### Environment

Chummer Version: 5.184.0
Environment: Windows 10 by virtualbox
Runtime: dotNET 4.5.1
### Expected behaviour

Some kind of info on Character rooster when opening chummer first time.
### Actual behaviour

Nothing to really do but stare at an empty interface. Gets confusing on how its to be used.
### Steps to reproduce the behaviour

Open chummer (fresh install? or just after update)

**Comment by Maxis010** [comment]
Create or open a character, it gets added to the recent files list and the roster
Can be pinned to both by right clicking the entry on the list under the File dropdown
