### ISSUE TITLE
Adding Custom Knowledge Skills Impossible in Career Mode

### ISSUE THREAD

**Issue by JohnBlack687** [chummer5a/chummer5a#1117]
### Environment
Chummer Version: 5.184.0
Environment: Windows 8
Runtime: probably .NET 4.5.1

### Expected behaviour
When I add a custom knowledge skill (for example: Area Knowledge: Colombia) in Career Mode, it should prompt me if it's a Language, Street, Interest, Professional, or Academic skill. Then it can use the appropriate attribute.

### Actual behaviour
There is no prompt, and it defaults to LOG.

### Steps to reproduce the behaviour
In Career Mode, add a new skill. Type in gibberish, and create it. No prompt.

### Link to affected character file
https://drive.google.com/file/d/0B-HGcB8h9mISQkF0d0JHZFBpX2s/view?usp=sharing

**Comment by JohnBlack687** [comment]
And this is not a "suggestion", this is a bug. It's a very important part of shadowrun.

**Comment by chummer5a** [comment]
It's also a duplicate issue that we're already looking into.

**Comment by caelian** [comment]
i don't like necro-ing old threads (especially since this one appears to be about 1.5 years old now) but i am seeing this exact behaviour in the latest nightly release build (5.200.2)

**Comment by StarWeaver** [comment]
Probably better to open a new issue and link this one, since this one is already referenced as closed in a certain commit. You can link stuff just by typing in the issue number with a #.
