### ISSUE TITLE
Issues with Customizing Vehicles

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#1118]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.184
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
A) When using the "Add and More" button to add modifications, it opens in the subcategory you were previously in, i.e. Body, Cosmetic, etc. 

B) When adding Smuggling Compartment Shielding a dialogue box should open with either a choice of sensor type or a box to name the kind of Shielding it provided.

### Actual behaviour
A) When using the "Add and More" button in the Add Modification menu, it directs you to the All category. 

B) When adding Smuggling Compartment Shielding, it adds directly to the vehicle without setting what kind of shielding it provides.

### Steps to reproduce the behaviour
A) Add a modification to your vehicle using a subcategory using the Add and More button.

B) Add Smuggling Compartment Shielding to a vehicle

**Comment by chummer5a** [comment]
Hrm, the Add Again behaviour is standard across the application currently, but there's no particular reason for it to be that way.

**Comment by schultlp** [comment]
That's odd then....When I go to add a weapon and press Add & More, it stays in that weapon category. Same with cyberware categories, different kinds of gear, and types of vehicles. I assumed this was intentional.

**Comment by chummer5a** [comment]
Disregard that, I'm an idiot. Fixed now.
