### ISSUE TITLE
Infected attribute adjustment errors

### ISSUE THREAD

**Issue by Hood281** [chummer5a/chummer5a#1119]
### Environment

Chummer Version: 5.184.x (observed in 0, 4, and 10)
Environment: Win 10
Runtime: .NET 4.5.1
### Expected behaviour

When adding the Banshee quality, attribute values should not change.
### Actual behaviour

When adding the Banshee quality, charisma minimum changes to 1 (this follows the book) but the charisma value drops by 2 
### Steps to reproduce the behaviour

Create an Elf: Note that CHA is 3
Add Quality Banshee: Note that CHA is now 1
### Link to affected character file

Easily reproduced with any new character

**Comment by chummer5a** [comment]
Vampire lists a specific stat-block, unlike Ghoul. Absent of any other clarifications, all vampires replace their statblock with the list stats.

**Comment by Hood281** [comment]
Huh. Interesting. Guess becoming a Vampire is a terrible idea for a Troll. The part of this that still is questionable is the CHA on Banshees. I realize that in the book Banshees do have 1/9 listed (which I assume is a typo and should be 3/9) but even if that's accurate I would assume that the character isn't supposed to lose 2 points of CHA in the transformation, which is currently what happens in chummer. I'll edit the issue to reflect only this.

**Comment by chummer5a** [comment]
Behaving per RAW in current builds. If there's ever an official errata on it it can be updated easily enough.
