### ISSUE TITLE
Functionality enhancement: Replace qualities with other qualities

### ISSUE THREAD

**Issue by anonymussme** [chummer5a/chummer5a#1122]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.184.0
Environment: Windows 8
Runtime: .NET 4.5.1

### Expected behaviour
When applying mutaqua quality while already an adept, no adept quality added

### Actual behaviour
When I add Mutaqua quality, it comes with Mystic Adept packaged in, and deducts 35 more karma, even though character was already an adept, not a mage

### Steps to reproduce the behaviour
Select adept through priority table with a troll metavariant, purchase mutaqua quality

### Link to affected character file
https://drive.google.com/file/d/0Bx965pblMnH5bVhqdUE4dXIyRzg/view?usp=sharing

**Comment by chummer5a** [comment]
Right, the contribution problem is fixed, the part where it replaces magician/adept with mystic adept will need a fair chunk of finagling to manage properly.
