### ISSUE TITLE
PDF Links Don't Open

### ISSUE THREAD

**Issue by TW3ET** [chummer5a/chummer5a#1123]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.184.7
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When clicking the page number of something, to open the correct book to the correct page using my selected tool, in this case Google Chrome.

### Actual behaviour
Clicking the page number draws no result of any kind

**Comment by chummer5a** [comment]
I made some destructive changes to how the PDF output link is generated in one of the earlier patches; just to confirm, you've selected Web Browser in the PDF Parameters dropdown and pointed the PDF Application to your browser in (probably) c:\Program Files (x86)\Google\Chrome\Application\chrome.exe?

**Comment by TW3ET** [comment]
That is correct exactly.

**Comment by OLStefan** [comment]
Same Problem on my side, but with non-browser PDF-Reader and Acrobat style selected in the options. entering the options menu fixes the problem until chummer is closed.

**Comment by HaikenEdge** [comment]
I'm having the same thing happen as OLStefan.

**Comment by OLStefan** [comment]
Latest nightly fixed the problem for me
