### ISSUE TITLE
Knowledge skills cost

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1127]
### Environment
Chummer Version: 5.184.11
Environment: Windows 10
Runtime: NET 4.5.1)

### Expected behaviour
Raising a knowledge skill should cost 1+2+3+4 not 0+1+2+3 in career mode

### Actual behaviour
Getting a new knowledge skill costs 0 karma. 
Raising a knowledge skill costs 1 fewer karma than it should.

### Steps to reproduce the behaviour
Buy knowledge skill in career mode

**Comment by chummer5a** [comment]
Knowledge skills in career mode start at rank 0 in order to facilitate changing the category and linked attribute. I can't see any way this is actually an issue.

**Comment by drakir75** [comment]
Problem is the cost of raising knowledge skills.  It cost 1 karma to get a knowledge skill to rating 0, (which I missed at first). Because of this, raising it to rating one cost 0 karma. So long so good. But this is a problem when raising skills above rating 1. To raise it to rating two cost 1 karma. To raise a skill to rating 3 cost 2 karma and so on. That is cheaper than in the rules. (Not saying it's too cheap, I seldom raise knowledge skill beyond rating 1 in career mode)

**Comment by drakir75** [comment]
My bad. tested on a character with jack of all trades. Remove.
