### ISSUE TITLE
Names Feature request

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1128]
### Request 1
In the Character Roster all character go by their name. I would much prefer if they are named by their saved name. I often have different versions of the same character (I.E Whale 1.0 and Whale 2.1 and so on) in the rooster and cannot differentiate. 
(I also see no point to the roster at all, but I guess some do?)

### Request 2
A printed character has their real name in the upper left corner of every page. Could this instead be the alias? All characters (both mine and others) go by their aliases and that is what should be on the top. Not a name that often is unknown by others.

### Thank you
For all the work on this fantastic program.

**Comment by joha4270** [comment]
This is 2 issues and should be created as such.
Closing this one. 

(Might be annoying for you, but it makes bookkeeping a nightmare for us)
