### ISSUE TITLE
Ammo in spare clips not printed

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1129]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.184.11
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Either show the total ammo (loaded and not loaded) in the "gears" block, or add the loaded ammo to the "weapon" block.
As I'm usually using german print outs, I would like/prefer to see these data on the german print outs too ...

### Actual behaviour
My character owns a Ares Predator V with 3 spare clips. I added 50 shots of standard ammo thru the equipment/gear tab (not via the buy ammo button on the weapon page).
In carreer mode, I loaded one of the ammo slots of the Ares with 15 rounds of standard ammo.
The Chummer5 UI now shows 35 rounds of ammo on the equipment/gear tab and 15 rounds in the weapon's clip. So far correct.
On the print outs (using "Showdowrun 5" for this test), 35 rounds are shown in the "gear" block. But the loaded 15 rounds are not shown in the "weapon" block.
So, looking at the printed paper only, I could assume that the character has only 35 rounds. But he has 35+15 = 50 rounds.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by Lochabar** [comment]
The character files do contain the amount of ammo loaded in a weapon; weapon/clips/clip/count. However when I tried to print this field in an XSL stylesheet, I only get blank.

Could someone check the code and see if the field from the character file is passed to the XSL?

**Comment by chummer5a** [comment]
Right, loaded clips should be accessible via weapon\clips\clip, with name and count as accessible attributes.

**Comment by Lochabar** [comment]
Here are the English and German Shadowrun Base.xslt files.
I have tested the English version.

I duplicated the changes in the German version (with help from Google Translator), but could not test them. I switched Chummer to use German. But it crashed opening an existing (English) character.

https://www.dropbox.com/s/8tki0f2yasxz8hy/Shadowrun%205%20Base.xslt%20%28english%29.txt?dl=0

https://www.dropbox.com/s/dfdgm8tjx58ubc3/Shadowrun%205%20Base.xslt%20%28german%29.txt?dl=0



Ian Kirk
daimio@juno.com
