### ISSUE TITLE
Problem with German and an existing character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1135]
### Environment
Chummer Version: 5.184.20
Environment: Windows 7
Runtime: .NET 4.6.1

### Expected behaviour
Change language to German, restart Chummer, and be able to open an existing character (that was created in English).

Note: this appears to be a repeat of issue 935.

### Actual behaviour
Chummer crashes with a Windows error (no Chummer dump).

### Steps to reproduce the behaviour
Change the language to German.
Restart Chummer.
Try to open a character created in English.
Windows error.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Chummer5.exe
  Problem Signature 02:	5.184.20.0
  Problem Signature 03:	57f26e47
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1085.0
  Problem Signature 06:	57a4fbb5
  Problem Signature 07:	37a0
  Problem Signature 08:	8
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

### Link to affected character file
https://www.dropbox.com/s/o782gno1ibbtvo6/Beltane2.chum5?dl=0

**Comment by Lochabar** [comment]
Chummer log:

Info      Program.cs.Main:68 Application Chummer5a build 5.184.20.0 started at 2016-10-03 7:36:05 PM with command line arguments "C:\Program-Files\Chummer5a\Nightly-v5.184.20\Chummer5.exe" 
Info      clsTimekeeper.cs.Finish:67 Task "cache_load" finished in 00:00:00.7877621
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
Info      Program.cs.Main:106 
		22 - C:\projects\chummer5a

**Comment by chummer5a** [comment]
Well, this is interesting. I was able to get it to crash the first time around, but then restarted my debugging session and now it works properly. Looks like it was choking on the Area Knowledge: Chicago skill, but I have zero idea why.

**Comment by chummer5a** [comment]
Do you have any other characters that are affected by this issue?

**Comment by Lochabar** [comment]
Here's a couple more:
https://www.dropbox.com/s/7js7vlicqhq3ryr/Fawkes.chum5?dl=0
https://www.dropbox.com/s/7f9e9pb0gn2r5gi/Rakash.chum5?dl=0

and the log:
https://www.dropbox.com/s/a6zmyjx35rmove4/chummerlog.txt?dl=0

**Comment by chummer5a** [comment]
Still can't reproduce it in current builds, unfortunately. Still reproducible for you, I assume?

**Comment by Lochabar** [comment]
Yes it is. Happens with the older characters I've provided, and with characters created on more recent releases (5.184.24 for example).

Could it be some sort of configuration problem?
After all I do not get Chummer dumps.

**Comment by chummer5a** [comment]
Well, that error indicates it's choking on a dictionary string, but there aren't a lot of reasons why that would only crash an existing character. Hrm.

**Comment by chummer5a** [comment]
Are crash dumps working for you in recent nightlies?

**Comment by Lochabar** [comment]
Yes they are. Although I still can't upload them from the virtual machine (unrelated to Chummer5) so here is the dump:

https://www.dropbox.com/s/wt4wi5sswur9px5/chummer_crash_131218795235349491.zip?dl=0

And here is the custom file I am using:

https://www.dropbox.com/s/aae1j38im02oac0/custom_skills.xml?dl=0

Which gives me an idea: obviously the custom skills are not in the de_data file - is this the problem?

**Comment by chummer5a** [comment]
Aha, circle gets the square! Okay, that's what I needed to figure this out. It's definitely failing to initiate the knowledge skills. Will look into why.
