### ISSUE TITLE
Use alias on printed character sheet

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1140]
I'll go ahead and split #1128 Names Feature request

### Actual behaviour (Request 2)
A printed character has their real name in the upper left corner of every page. Could this instead be the alias? All characters (both mine and others) go by their aliases and that is what should be on the top. Not a name that often is unknown by others.

### Fix
This is a simple fix; the "real name" is defined as the Title field in the XSLT. Instead I can add a check for Alias being present, otherwise use the real name.

How do you want me to provide the XSLT changes?
Pull request? Attach files?

**Comment by Lochabar** [comment]
I have modified the XSLT files to use alias name as the file name.
How should I send them?

**Comment by chummer5a** [comment]
Hrm, I'd kind of prefer to make it a user-accessible change in the options menu or somesuch, but that can wait. If you're comfortable with making pull requests I'd prefer it that way, otherwise just upload the file and i'll overwrite it.

**Comment by Lochabar** [comment]
When you have the time, send a switch. The changes are simple.

I've never made a pull request. Can you send me the instructions?

**Comment by chummer5a** [comment]
Assuming you don't have access to visual studio or git or something on your desktop, you would edit the page directly (https://github.com/chummer5a/chummer5a/tree/master/Chummer/sheets) by clicking the Edit button to make your own branch, saving the changes, then pushing. https://help.github.com/articles/creating-a-pull-request/

**Comment by Lochabar** [comment]
I think I have completed the pull request. Now what?

**Comment by chummer5a** [comment]
Hrm, I can't see any edits on your fork. Generally you'd edit my version of the file and save it to your fork, then create a pull request to add it back to here. I'm not super familiar with the web interface for this though, I generally do all my work in visual studio and push/pull from there.

**Comment by Lochabar** [comment]
I loaded the complete versions I created. Is there no way to compare them with the original code?

**Comment by chummer5a** [comment]
Well, your version of Chummer's sheets is here: https://github.com/Lochabar/chummer5a/tree/master/Chummer/sheets. If you edit that file, you should be able to push it back to me. if it's too much of a hassle just flick it to me and I'll sort it out.

**Comment by Lochabar** [comment]
I tried working with the GitHub Desktop. Not easy to figure out given the lack of help regarding downloading code and editing it! 

So here are the xsl/xslt mebers for the sheets.
[#1140.zip](https://github.com/chummer5a/chummer5a/files/545537/1140.zip)
