### ISSUE TITLE
Metavariants and Non-Mundane Type Showing List Item in Priority and Sum Of X creation

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#1143]
### Environment
Chummer Version: 5.185.0
Environment: Windows 7 64 bit
Runtime: Probably .NET 4.5.1, since I don't know.

### Expected behaviour
Drop-down menu for non-mundane type (Adept, Mystic Adept, Aspected Magician, Technomancer, etc) and drop-down menu for Metavariant (Goblin, etc for Orks) should display appropriate menu items when using Priority or Sum of X character creation methods.

### Actual behaviour
Drop-down menu for non-mundane type shows "Chummer.ListItem" in multiple entries, and drop-down menu for Metavariants show "Chummer.ListItem" for Elves, Orks and Trolls.

### Steps to reproduce the behaviour
Attempt to create a new character using Priority or Sum of Ten.

**Comment by chummer5a** [comment]
I can't replicate this in my test environments; any further detail you can provide?

**Comment by HaikenEdge** [comment]
It was a problem in the full release, but has since been repaired in the nightly releases. I just thought it was worth mentioning at the time because a broken full release is kind of problematic.

**Comment by Bellum45** [comment]
When the update to the latest version this bug is still there, but when you download a new version it's working, probaly.
The settings can be used from the old version.
Testet with 5.185.2
