### ISSUE TITLE
More Books!

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#1144]
Hello Again,

Seems I did some stuff wrong on my last batch of XML's as the Crystal Leviathan Cyberdeck asks for a rating when it shouldn't and I forgot to put the Books code in for the Lockdown stuff. 
I've also stated up the alternate Colt Manhunter from Shadows in Focus: San Francisco Metroplex along with the Cyberterminals, Alternate Cyberdecks and Cyberdeck mods from the Hong Kong Sourcebook that kickstarter backers got.
Either way its all in here:
[Chummer XML's.zip](https://github.com/chummer5a/chummer5a/files/520394/Chummer.XML.s.zip)

**Comment by Gamingharry** [comment]
Found a translation of some of the German guns from the German handbooks. Have stated. Unfortunately don't know the direct page refs. 

[Custom_German_weapons.zip](https://github.com/chummer5a/chummer5a/files/520548/Custom_German_weapons.zip)

**Comment by chummer5a** [comment]
Righto, added those. Will have to add the German weapons as well.
