### ISSUE TITLE
Cyberlimb Attributes Not Properly Averaging

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#1145]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running?
5.185.0
Environment: (Operating system here. If it persists over multiple OS's list them all)
Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
.NET 4.5.1 (probably)

### Expected behaviour
Cyberlimb Agility/Strength should be mathematically averaged with base Agility/Strength and displayed in parenthesis next to the base attributes in this style:

Base Attribute (Cyberlimb Modified Attribute).

For example, a character with 2 base agility, 6 agility on a cyberarm, and 9 agility on a pair of cyberlegs should have a cyberlimb modified agility of 5, that would be displayed like so:

Agility    2    (5)

### Actual behaviour
Cyberlimb attributes are not being factored in at all. Other augmentations are being correctly factored in (Reaction and Logic work fine). Please view the screenshots below:

http://imgur.com/a/ZG0VU

### Steps to reproduce the behaviour
1.) Open the file linked below in Chummer 5.185.0

2.) Make sure that the options are set up to average cyberlimb attributes

3.) View the attributes on the 'Common' tab. View the attributes in the print-preview.

### Link to affected character file

https://drive.google.com/open?id=0B4E-MRu4QUJ7dS1zT3A0R29WQm8

**Comment by chummer5a** [comment]
[10_10_Staples.zip](https://github.com/chummer5a/chummer5a/files/523581/10_10_Staples.zip)
Your limbs didn't have slots assigned, so Chummer didn't think they were actually limbs. Not sure how that happened.
