### ISSUE TITLE
Cannot spend karma for contacts

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1146]
### Environment
Chummer Version: Release 5.185.0
Environment: Windows 7
Runtime: .NET 4.6.1

### Expected behaviour
From core rule book p98

Contacts - 1 Karma for each point of Connections Rating, 1 Karma for each Loyalty Rating
(minimum Karma requirement = 2). A single contact may not have more than 7 Karma spent on them at character creation.

### Actual behaviour
Unlike the skills, there is no counter box to spend karma.

### Steps to reproduce the behaviour
Using a character in create mode, add a contact. There is nowhere to spend karma.

### Link to affected character file
https://www.dropbox.com/s/scwte3duepgpk51/Contacts.png?dl=0

**Comment by drakir75** [comment]
Just raise Loyalty or Connection. Chummer spends your free contact points first (3xCha) then spends karma. If you don't see where, click the "arrows" to the right of "delete" contacts.

**Comment by chummer5a** [comment]
Yeah, this is more or less intentional.
