### ISSUE TITLE
Adding spare clip shows unarmed as a weapon

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1147]
### Environment
Chummer Version: Release 5.185.0
Environment: Windows 7
Runtime: .NET 4.6.1

### Expected behaviour
Only weapons that can have a spare clip be shown.

### Actual behaviour
Unarmed attack is also shown

### Steps to reproduce the behaviour
Add spare clip to gear. "Unarmed attack" is also listed.

### Link to affected character file
https://www.dropbox.com/s/66a5phctuexb3j1/Spare%20clip.png?dl=0

**Comment by chummer5a** [comment]
You should only get that behaviour if you have no other weapon.

**Comment by Lochabar** [comment]
Sorry, but the character has 7 ranged weapons and 3 melee weapons.

**Comment by chummer5a** [comment]
Oh, ALSO listed. Yeah, I see the problem. Easyfix, will be sorted shortly.

**Comment by Lochabar** [comment]
Checking this out with a different character I realized that other weapons that don't have a clip also show in the list, specifically shurikens and throwing knives. (And grappling gun is debatable.)

Weapons: https://www.dropbox.com/s/4zip0twfvevwkt5/Weapons1.png?dl=0
Add clip: https://www.dropbox.com/s/2r696fra0wa5qxg/Weapons2.png?dl=0
