### ISSUE TITLE
Extraneous field on "Other Info" tab

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1149]
### Environment
Chummer Version: Release 5.185.0
Environment: Windows 7
Runtime: .NET 4.6.1

### Actual behaviour
There is a field on the "Other Info" tab of a career-mode character.

### Steps to reproduce the behaviour
Using a career-mode character, expand the "Other Info" tab to the right. There is a "Name" field. From the tip text, it is the Armor name field that is now show on the "Condition Modifier" tab.

### Link to affected character file
https://www.dropbox.com/s/swh73bus08yhn8k/Other%20info.png?dl=0

**Comment by chummer5a** [comment]
Well isn't that a sneaky little bugger? Removed in the next commit.
