### ISSUE TITLE
Karma-gen returns erroneous results.

### ISSUE THREAD

**Issue by jeoc42** [chummer5a/chummer5a#1153]
### Environment
Chummer Version: 5.182.0
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: .NET 4.5.1

### Expected behaviour
levels of a special attribute granted by a magic quality are included in the price of the quality.

### Actual behaviour
Charged 5 karma for Level 1 in magic or resonance in karmagen

**Comment by chummer5a** [comment]
Please update to [a current build](https://github.com/chummer5a/chummer5a/releases), 5.182 is three major releases behind at this point.
