### ISSUE TITLE
Argentum Coat / Berwick Suit / Stacking / Custom Fit

### ISSUE THREAD

**Issue by AxDeath** [chummer5a/chummer5a#1154]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.184.0
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Total armor is coming up is 12, instead of 9+4.

### Actual behaviour
Berwick Suit is 9, Argentum Coat is custom fit 12/+4 by erratta

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate the issue in 5.185. Please update and test again. If you're still having issues, please link a copy of the affected character.

**Comment by AxDeath** [comment]
I was messing with the program trying to reproduce the effect. It appears if you purchase the coat first, and then the suit, it adds incorrectly, even if you unequip and re-equip the coat. It's true of all the Custom(Stack) coat types. 
You need to purchase the suit first, and then the addon coat, and select the Stack choice. Minor.

**Comment by chummer5a** [comment]
Well, I've MOSTLY fixed it, with exception of the fact that I've currently go no way to exclusively filter on the company, so you get some rather curly results.. 
![image](https://cloud.githubusercontent.com/assets/11448441/19417847/9bf37db0-9402-11e6-9fc0-61c50d216c0a.png)
