### ISSUE TITLE
Cant load Character

### ISSUE THREAD

**Issue by Len1991** [chummer5a/chummer5a#1155]
### Environment
Chummer Version: Run over it in 5.185 and then found the same in 183
Environment: Win 7
Runtime: .NET 4.5.1

### Expected behaviour
Loading the Character without Problems
### Actual behaviour
Its kinda weird, i load the Character and it says i have 400 of 400 Karma, shows me my augmented abilitys in Fat and erased my Magic Attribute, i also send it to a friend of mine who is using Version 184 and the char just crashed for him

### Steps to reproduce the behaviour
I seriously dont know where it went wrong

### Link to affected character file
https://drive.google.com/open?id=0BxHEUFt20bInOWdENUhUd1A3UGc

**Comment by chummer5a** [comment]
[Social.zip](https://github.com/chummer5a/chummer5a/files/525934/Social.zip)
Character had more karma invested into magic than was allowed by Essence loss. Should've been caught by Save, so not sure what happened there. Anyway, fixed.
