### ISSUE TITLE
Knowledge skills cost

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1157]
### Environment
Chummer Version: 5.185.4
Environment: Windows 10
Runtime: .NET 4.5.1)

### Expected behaviour
That karma expenditure on new knowledge skills will appear on "karma spent"
(karma is lowered but there is no log)

### Actual behaviour
I see new active skill costs and if I raise a knowledge skill above rating one, the "karma spent list" shows that. Getting a new knowledge skill will lower karma but it is not recorded.

### Steps to reproduce the behaviour
Have a character in career mode. Give him/her a new knowledge skill. Check the karma gained/spent list.

**Comment by chummer5a** [comment]
Should be fixed in 5.185.5.
