### ISSUE TITLE
Not Able To Label Autosofts

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1159]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.185.8
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Label the Autosoft program (Targeting, ClearSight, etc.)

### Actual behaviour
Unable to label.

### Steps to reproduce the behaviour
I am putting it in notes, but it would be nice to have it as a re-name or request for a label.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Que? You should be prompted for the name of the item on purchase.

**Comment by captroberts** [comment]
Nope. I put it in as notes notes, but it would be nice to have it que you and ask what it is.

**Comment by chummer5a** [comment]
So you buy the autosoft gear item and you don't get a message box that says 'Enter a value for Autosoft'? The only reason it should be doing that is if a value was already specified by the gear item itself.

**Comment by captroberts** [comment]
No it does not. There is a numerical value, but nothing allows you to label it as [Weapon] Targeting, Clearsight, [Model] Evasion, etc.

**Comment by Iridios** [comment]
Just some quick testing shows that if you buy the Autosoft through the Gear tab it does ask for what type.  However, when you use the  'Add Gear' function to add the Autosoft to a vehicle/drone it does not ask for a value and merely says "Autosoft (Rating X)" where X is the rating.

**Comment by captroberts** [comment]
Can you add it to a Drone through the Gear Tab?

**Comment by Iridios** [comment]
Not anyway that I can find.

**Comment by captroberts** [comment]
OK. For now, I will have runners add it as a note.

**Comment by chummer5a** [comment]
Ahhhh, that's what I needed. Okay, so the problem is that when we're adding
improvements, we check to see if we're adding the improvements to a
character. If we're NOT, then we fail out early, which prevents the
selecttext improvement from firing. Um. If you're in career mode you should
be able to add it to the character file through the gear menu, then use the
Send to Vehicle button to shunt it over.

**Comment by Iridios** [comment]
That does work.  I forgot about that function because I currently don't have any riggers in my group.

**Comment by captroberts** [comment]
The one I am using it on is in Create Mode. Still, I put it in as a note on the drone.
