### ISSUE TITLE
Crashes upon loading character in Career mode

### ISSUE THREAD

**Issue by RPGManoWar** [chummer5a/chummer5a#1160]
### Environment
Chummer Version: 5.182 and 5.185 - Both show the same problem
Environment: Windows 8
Runtime: .NET 4.5.1

### Expected behaviour
Character sheet opens

### Actual behaviour
Crashes upon load 

### Steps to reproduce the behaviour
Unknown - No idea what caused the issue

### Link to affected character file
Tried compressing it into a ZIP, but the file will not send

**Comment by RPGManoWar** [comment]
![image](https://cloud.githubusercontent.com/assets/22848063/19407476/f5dc34fe-9257-11e6-8efa-84bd3294a704.png)

Finally got the crash report. Hope this helps

**Comment by chummer5a** [comment]
It's choking while trying to load the limit bonus from Improved Physical
Attribute. I'll need to see the file, that should be fixed.

**Comment by RPGManoWar** [comment]
I tried compressing it into a ZIP folder, but Github still says that it can't send

**Comment by RPGManoWar** [comment]
Nevermind, a friend fixed it for me
