### ISSUE TITLE
Default Character Creation Mode - LifeModule/Karma only?

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#1163]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.179.765
Environment: Windows Vista
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
To be able to set default chargen mode to Priority, as was possible with older version.

### Actual behaviour
Ability to select Priority character creation is completely absent.

**Comment by chummer5a** [comment]
Well for one thing I'd suggest you update to a build that's not from March.

**Comment by Verecoth** [comment]
Funny, I tried to have it update right before I started using it again. Got the newest version now, working fine and can indeed default to priority.

**Comment by chummer5a** [comment]
We changed update methods around then, the old Dropbox links expired. Anyway, glad to hear it's working for you!
