### ISSUE TITLE
Suggestion: Contacts, Notes / Details Space

### ISSUE THREAD

**Issue by AxDeath** [chummer5a/chummer5a#1164]
### Environment
Chummer Version: 5.185
Environment: Windows 7 x64
Runtime: 

### Expected behaviour
I suggest a note space for each contact, with room to give them much greater detail, and possibly an option to print a Contacts page separate with these details. Contacts in SR4 were minor NPCs with full skill lists, and backgrounds. A good contact should be more than "Fixer" or "Tailor" or "Mechanic" with some numbers, especially because the assumption is that a Fixer can put you in touch with a Tailor or Mechanic.

### Actual behaviour
Currently Contacts are limited to Loyalty, Connection, a job name, location, and a real name.

The following link shows several examples of fully developed contacts, which add to the character and game.
http://forums.shadowruntabletop.com/index.php?topic=6062.0

**Comment by chummer5a** [comment]
Expand the contact control and click the Notes button?
