### ISSUE TITLE
chummer crashing upon opening

### ISSUE THREAD

**Issue by swirrly** [chummer5a/chummer5a#1165]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.185.0
Environment: Windows 10
Runtime: 4.6.1
### Expected behaviour
Click to open chummer and use it

### Actual behaviour
crashes and the crash reporter comes up saying "Unexpected end of file has occurred. The following elements are not closed: mugshot, character. Line 28, position 31801"

### Steps to reproduce the behaviour
I have Downloaded the latest releases and even earlier releases to see if just my end, but it either wouldn't even open or I would get the same crash

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
If the error is directly on opening (ie, you haven't tried to open a character), it's most likely one of the characters in your history that didn't save properly. In which case you'd want to open regedit, navigate to HKCU\Software\Chummer5 and delete all the keys starting with mru. If it's on loading a character, I'll need to see the file but it's probably busted.

**Comment by swirrly** [comment]
Ty that seemed to do it
