### ISSUE TITLE
Character roster bugs

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1166]
### Environment
Chummer Version: 5.185.22 (and earlier)
Environment: w7
Runtime: .NET 4.6.1

### Expected behaviour
Background tab.
Character notes are shown.

### Actual behaviour
1) There are two "concept" tabs - the second one should be the background.
- I think the problem is actually in the language file:
		<string>
			<key>Tab_Roster_**Background**</key>
			<text>**Concept**</text>
		</string>

2) The character notes tab does not actually show the notes present for the character.

### Link to affected character file
![roster](https://cloud.githubusercontent.com/assets/17562417/19462753/982b53c6-94b4-11e6-8109-62736a2ba48c.png)

**Comment by chummer5a** [comment]
That would do it, yes. Whoops.
