### ISSUE TITLE
Cyberskulls and Cybertorsos not providing willpower bonus for Cyber Singularity Seeker

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#1168]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
### Environment

Chummer Version: 5.185.0
Environment: Windows 10
Runtime: probably .NET 4.5.1
### Expected behaviour

Characters with Cyber Singularity Seeker (CSS) should receive bonuses for cybertorsos and cyberskulls. For example, a person with CSS, a cyberskull, and a cybertorso should be at +1 willpower.
### Actual behaviour

Cyberskulls and torsos are disregarded for the purposes of CSS. Only full cyberarms and cyberlegs are counted for the willpower bonus.

This might be by design, but it would be nice if there was an option that allowed for cyberskulls and torsos to be counted via the houserules menu.
### Steps to reproduce the behaviour

Make a character with CSS and put a cybertorso+skull on them. Observe that there is no willpower bonus.

**Comment by chummer5a** [comment]
Kinda need an errata on whether they count as limbs or not to make it a default option, I'll have a think about an easy way to implement it as a house rule.
