### ISSUE TITLE
Crashes when trying to restart program after updating options.

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#1169]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.185.0
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When changing options, the program asks to restart after saving. It's expected to restart normally.

### Actual behaviour
Instead of restarting, it crashes every time.

### Steps to reproduce the behaviour
Any time I change options, I click okay. It saves the changes, then asks to restart. If I allow it to restart, it crashes.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Could you please try with the latest nightly build? The release build had some issues with character paths that contained spaces.

**Comment by NorsemanJosh** [comment]
I'm not sure where to get the latest nightly build. I do know I was having the same problem with 5.184.0.

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.185.28/Chummer.Nightly.zip

**Comment by NorsemanJosh** [comment]
I just tried the nightly build, and it had the same problem.

**Comment by chummer5a** [comment]
Okay, does it give you an error message? If it's sending you straight to the error reporter, try clicking on the 'What does this report contain' link and open the exception.txt, if it's there. I'd like to see what's in that file.

**Comment by NorsemanJosh** [comment]
I just found out the problem was on my end. I had it set to ask me before opening the program. That caused it to crash instead of restarting.
