### ISSUE TITLE
Code of Honor quality missing

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#1172]
### Environment
Chummer Version: 5.185
Environment: Windows Vista
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Able to select Code of Honor quality when creating new character.

### Actual behaviour
Code of Honor quality is missing from the menu under "Negative" when "Add Quality" is selected.

### Steps to reproduce the behaviour
Add the quality back in? It was there in previous versions.

**Comment by chummer5a** [comment]
Code of Honour is banned in Missions, you've probably got that option enabled.

**Comment by Verecoth** [comment]
Right. Got it. Thanks for that.

**Comment by chummer5a** [comment]
No worries, happy to help.
