### ISSUE TITLE
Technomancers/mages can't raise resonance/magic in chargen

### ISSUE THREAD

**Issue by ArtOfCombat** [chummer5a/chummer5a#1181]
### Environment
Chummer Version: 5.186.0
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
When you buy the technomancer or magician or mystic adept qualities, the relevant stats should become purchasable with karma.

### Actual behaviour
Upon buying the aforementioned qualities, the stats remain greyed out. I was creating a dwarf technomancer; I also tested the magician quality.

### Steps to reproduce the behaviour
Attempt to buy resonance after buying the Technomancer trait, or magic after buying the mage or mystic adept trait.

### Link to affected character file
All my files are affected thus far.

**Comment by chummer5a** [comment]
This issue is resolved in the latest nightlies. Please install  [5.186.10](https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.186.10 ).
