### ISSUE TITLE
Exceptional Attribute misses the magic attribute

### ISSUE THREAD

**Issue by Bellum45** [chummer5a/chummer5a#1186]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.186.17
Environment: Windows 7 64bit
Runtime: .NET 4.6.1

### Expected behaviour
When adding the quality "Exceptional Attribute" you can selected all attribute but edge.

### Actual behaviour
When adding the quality "Exceptional Attribute" you can selected all attribute but edge and magic.

### Steps to reproduce the behaviour
Create a new character over the sum of ten or the priority system with magic. Add the quality "Exceptional Attribute".

**Comment by chummer5a** [comment]
Can't replicate the issue. Could you upload an affected character file? If you compress it to a zip file you'll be able to upload it directly.

**Comment by Bellum45** [comment]
I have redownloaded Chummer5a and now it's running.
I doesn't know why.
