### ISSUE TITLE
Skills page not displaying properly

### ISSUE THREAD

**Issue by nickschurch** [chummer5a/chummer5a#1187]
On the kskills game the columns headers don't align with the columns properly for Active Skills, the names of the active skills are cut off and don't become visible even on a resize, the specializations box is too big.

### Environment
Chummer Version: (What version of chummer are you running? 5.186.17
Environment: (Operating system here. If it persists over multiple OS's list them all) Windows 7 Enterprise
Runtime: (If you don't know this, it is probably .NET 4.5.1) NET 4.5.1

### Expected behaviour
All skills text (names, column headers etc) to be readable and division of columns to behave nicely on resize

### Actual behaviour
None of the above

### Steps to reproduce the behaviour
make a new character

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can you provide a screenshot? I suspect I know what's going on, but it'll be easier if I can see it.

**Comment by nickschurch** [comment]
Sure, you can see it here:

https://www.dropbox.com/s/o22d96wxdzms31p/Screenshot%202016-11-02%2013.02.18.png?dl=0

**Comment by chummer5a** [comment]
Bleahhhh, DPI settings. I hoped we'd fixed that. If you drop your text size down it should work properly again; as is it's part of several other issues that we need to resolve.

**Comment by nickschurch** [comment]
how do I do that? I can't see an option for setting the font or text size in options and ctrl+/- don't work.

**Comment by chummer5a** [comment]
It's not a Chummer setting, it's your Windows DPI setting. Right-click on the Chummer exe, select Properties, select the Compatibility tab, and tick **Disable display scaling on high DPI settings**. That should sort it out until we get DPI scaling working properly.

**Comment by nickschurch** [comment]
I tried disabling display scaling on high DPI settings and this didn't work for me, the skills list is still unreadable. :(

**Comment by nickschurch** [comment]
This is still an issue in the latest nightly and disabling the display scaling isn't working. Is there another work-around because I'd love to use this program but it's essentially making it impossible to use. Is this an issue for others?

**Comment by chummer5a** [comment]
It's been reported before, but I've never been able to replicate it on any of my test machines. If I can't replicate it, the best I can do is make shots in the dark. The issue, as far as I can see, is that the font size is adjusted by *something* in a way that doesn't caused PreferredWidth to trigger properly.

**Comment by Iridios** [comment]
Are you able to open the Display applet in the Windows Control Panel?  Does it have the option to change the size of text on the screen with the options of 100%, 125% and 150%?  If that is not on 100% then change it to 100%.

**Comment by nickschurch** [comment]
yey! That has successfully fixed the problem - it was previously set to 125%. Thanks for your help and for making such an awesome tool!

**Comment by xanderio** [comment]
I'm still having this issue with wine on the latest nightly version. ![Screenshot](https://user-images.githubusercontent.com/6298052/58487164-6fded580-8167-11e9-9d32-76642855b308.png)

wine version: 4.0-rc1
