### ISSUE TITLE
Problem with Magic and the KARMA build

### ISSUE THREAD

**Issue by Mddd2009** [chummer5a/chummer5a#1188]
Chummer Version 5.186.0
Windows 10. I would assume its not a windows issue.

When you create a character in the KARMA build option, it will not allow you to change the magic, or resonance score. Normally it wouldn't be available until you select the proper quality, but no matter which quality you are using adept, aspected magician, magician, or mystic adept or even technomancer it doesn't allow you to change your magic or resonance score. They are greyed out. 

I have tried several build options including ignore creation rules, but it doesn't allow you to change the magic or resonance score no matter what. Please assist.

**Comment by chummer5a** [comment]
Fixed in nightly builds, I haven't updated the release build yet. Download it from https://github.com/chummer5a/chummer5a/releases.
