### ISSUE TITLE
Issue with character creation for the shapeshifters. 

### ISSUE THREAD

**Issue by Mddd2009** [chummer5a/chummer5a#1189]
I know this is really a problem tracker, but I have a proposed solution to this issue. If you add the shapeshifter as a race, you can add each meta available. It autoadds a quality. Quality would be shapeshifter shift, which then you would need to select a race to shift into. Keep in mind, all the work you do in character creation is mostly for the form you chose. The only thing that it needs to do is put the basic stats and then add the points we added to each. It doesn't have to be a side by side creation. All of the qualities you select are the same on both. You would need to create a mirror character sheet with the other race using the stats you entered for this character. I'm not sure that's easy, lol.

**Comment by chummer5a** [comment]
Making a clone of a character is easy; keeping that clone in sync with the 'main' file is not, and is at best a hack.

**Comment by Mddd2009** [comment]
No i understand and in main character mode it probably wont work but to
create a character it would work pretty good

**Comment by chummer5a** [comment]
Resolving this in the [databoundattributes](https://github.com/chummer5a/chummer5a/tree/databoundattributes) branch.

**Comment by Mddd2009** [comment]
Hey Just by change, can you add the Races on there with the appropriate costs and attributes. I can just build a troll and a second character and assign them karma each. Im working with my GM on this, and we are trying to find a work around.

**Comment by chummer5a** [comment]
Put these files inside your data folder. They're somewhat functional.
[Custom_Shapechanger_XMLs.zip](https://github.com/chummer5a/chummer5a/files/590590/Custom_Shapechanger_XMLs.zip)
