### ISSUE TITLE
No way to buy adept powers?

### ISSUE THREAD

**Issue by GeminixKross** [chummer5a/chummer5a#1190]
### Environment
Chummer Version: 5.186.0
Environment: windows 7
Runtime: Unsure

### Expected behavior
Adepts have the ability to buy powers.

### Actual behavior
Adepts don't have the ability to buy powers.

### Steps to reproduce the behavior
Just make a character that's an adept. At least, that's all I do. Maybe I'm missing something obvious.

**Comment by chummer5a** [comment]
Was resolved in nightlies, but please update to 5.187 to resolve it.
