### ISSUE TITLE
Issues with Armor (especially High-Fashion)

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1192]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 
Chummer5a 5.187.2 (Nightly), not relevant
Environment: (Operating system here. If it persists over multiple OS's list them all) 
Windows 8.1
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
ARES Victory:
all Sets: selectable custom protection (i.e. Fire/Chem/Nonconduct/Insulation/...)
Globetrotter Clothing should have Gear Access

Vashon Island:
Synergist Business Line should have Holster
Sleeping Tiger should have a Holster pre-installed

all:
Longcoats/Coats/... can stack for +X armor and be worn alone for Y armor

### Actual behaviour
ARES Victory:
all Sets: custom protection (...) not selectable or even mentioned
Globetrotter Clothing has no Gear Access
Vashon Island:
Synergist Business Line has Concealable Holster
Sleeping Tiger has no Holster at all
all:
Longcoats/Coats/... always stack for +X armor

### Steps to reproduce the behaviour
simply add any of the above mentioned armors to any character and compare the displayed inherent mods to the ones they should have according to Run & Gun

### Additional notes
Hope this helps improving the software, as I really enjoy using it and you are all doing a great job with updates and functions

**Comment by chummer5a** [comment]
The longcoats should only stack with an equipped suit that matches the Custom Fit that was selected. So you pick the Synergist longcoat, it prompts you to select the armour, and then switches to the override value as long as that armour is equipped.
