### ISSUE TITLE
Negative Qualities in Advanced Lifestyle causes crash

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#1194]
## Environment
Chummer Version: 5.187.2
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When Negative is selected in drop menu, expecting the list of qualities to show.

### Actual behaviour
When Negative is selected in drop menu, Chummer crashes, regardless of lifestyle.

**Comment by chummer5a** [comment]
Can't replicate the issue; could you please show me the exception.txt file generated by Chummer? There should be a blue link on the crash reporter that includes the file.
