### ISSUE TITLE
Lifestyle - Missing data - Merchandise (run faster)

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1196]
Missing data for these advanced lifestyle options (Run Faster p.222) :

MERCHANDISE: PAWN SHOP/THRIFT STORE
Point Cost: 2
Type: Service
Monthly Nuyen Cost: 10,000¥
Minimum Lifestyle: Commercial

MERCHANDISE: USED GOODS (SPECIFIC ITEM)
Point Cost: 2
Type: Service
Monthly Nuyen Cost: 10,000¥
Minimum Lifestyle: Commercial

**Comment by chummer5a** [comment]
Eh? They're in Entertainment - Service.

**Comment by prismatic-mind** [comment]
Ha ok, 
Just change Merchandise: Goods (Specific Item) to "Service" then :)
(sorry i missed that)
