### ISSUE TITLE
Missing Positive Quality: Latent Dracomorphosis [-5 Karma]

### ISSUE THREAD

**Issue by sigmareaver** [chummer5a/chummer5a#1197]

**Comment by sigmareaver** [comment]
Howling Shadows pg. 164

**Comment by chummer5a** [comment]
Crap, I was hoping nobody was ever going to want to take that clusterfuck of a quality.

**Comment by sigmareaver** [comment]
Sorry? lol. I guess it had to happen eventually. I'd offer to help you, but I am not familiar with the source code.

**Comment by chummer5a** [comment]
All good, it's just not going to be able to happen for a while. I can make the quality easily enough, but there's no simple way to manage all the stuff that goes on.
