### ISSUE TITLE
Negative Quality - Pie Iesu Domine. Dona Eis Requiem. - Incorrect Karma Calculation 

### ISSUE THREAD

**Issue by dresdenreader** [chummer5a/chummer5a#120]
Issue Type - Bug
Chummer Version: 0.5.158.0
Number of Issues - 2
Domain - Qualities
Pie Iesu Domine. Dona Eis Requiem. RF pg 158

When you add Pie Iesu Domine. Dona Eis Requiem. to your character, both Negative Quality and Positive Quality karma values are being calculated incorrectly.

1. Open Chummer.
2. Start a Prime Runner and choose priorities.
3. Select Pie Iesu Domine. Dona Eis Requiem from the Negative Qualities dropdown.
4. ---> 7 Bonus Karma is being awarded, this should only be 2.
5. ---> 7 Karma is added to the Positive Qualities tracking in the Build Summary from High Pain Tolerance (Rating 1).

The first ---> Should be an easy XML fix.
The second ---> will be trickier since it requires a specific edge case for High Pain Tolerance (Rating 1) in this specific circumstance. Likely you'll have to add the ability for High Pain Tolerance (Rating 1) to be grayed out on the character sheet, much like qualities given for metatype variants at char creation.

**Comment by chummer5a** [comment]
Quality is an attempt at a workaround from shadowruntabletop forums prior to chummer5a. Easy fix.

**Comment by chummer5a** [comment]
Resolved in 5.159.
