### ISSUE TITLE
Selecting Magician quality can't raise Magic value (greyed out)

### ISSUE THREAD

**Issue by copernicvs** [chummer5a/chummer5a#1205]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.187.11.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Raising the Magic level after selecting the Magician quality at character creation.

### Actual behaviour
Magic is still greyed out and is inactive, Spells tab also doesn't appear.

### Steps to reproduce the behaviour
Create new character -> Add quality -> Positive -> Magician -> Add

### Link to affected character file
https://1drv.ms/u/s!Auxx98z38pqHhppLRFULVhG2fIOo1Q

**Comment by chummer5a** [comment]
Well, the character's definitely missing the relevant improvements, not sure why though. Could you please hit the Reapply Improvements menu option in the Tools dropdown menu? That should force the improvements to re-create themselves.

**Comment by copernicvs** [comment]
I tried re-applying, but then Chummer crashed. I sent a bug report with the ID 360cefec-c38a-46b9-b145-3abb1391ccd8

**Comment by chummer5a** [comment]
Hrm. I can't replicate the issue in current nightlies. I know what the problem is likely to be, but eh. No repro. Anyway, fixed version of your character: [FixedMage.zip](https://github.com/chummer5a/chummer5a/files/580664/FixedMage.zip)

**Comment by copernicvs** [comment]
Thanks, at least this file works fine now :) If it's not persistent in future builds, then i guess it is not a big issue.
