### ISSUE TITLE
Issue with Magician's Way

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1210]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.187.11
Environment: Win 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Magician's Way (Street Grimoire) allows access to all Metamagics (if other prerequisites are met) for Mystic Adepts

### Actual behaviour
Magician's Way allows only Power Points, Adept Centering, Infusion & Qi Sculpt (basically the Metamagics that any Adept can take even without following a way)

### Steps to reproduce the behaviour
Create a Mystic Adept, let him initiate (houserule for chargen or during career), right click on the grade and select add Metamagic. List should be as it is if "Show only Metamagics I can take" is turned off (only that it should not produce an error like "You do not meet the requirements for this Metamagic" [...])

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
You need to add an Art first, unless the house rule to ignore Art requirements is enabled.

**Comment by Sturmkind** [comment]
For the Magician's Metamagics that might be true, but what Art would I have to choose to pick a metamagic from another Adept's Way?
I.e. if I wanted to take the Fae-Touched Metamagic from the Speaker's Way?

**Comment by Sturmkind** [comment]
And thanks for the quick reply ^^ don't want to sound ungrateful, but this only solved half of my problem

**Comment by chummer5a** [comment]
As is there's no way to do it, since those metamagics require the appropriate quality. So Fae-Touched requires the Speaker's Way quality. 

You could make an override file to remove the quality requirement I suppose, but as is Chummer's just following RAW.
