### ISSUE TITLE
Aspected Magician - Must select a skill/skill group to move on.

### ISSUE THREAD

**Issue by GMChimiboy** [chummer5a/chummer5a#1211]
### Environment
Chummer Version: 5.182.0
Environment: Windows 7 and 8.1, both x64
Runtime: probably .NET 4.5.1

### Expected behaviour
It is supposed to give me skill/skill groups options when selecting aspected magician . "Sorcery, conjuring or enchanting"
Rules can be found on page 69, SR5

### Actual behaviour
Gives me a blank dropdown, unable to click on anything. Can't move on with the char-gen. It tells me "You must select a Skill / Skill Group before continuing."

### Steps to reproduce the behaviour
Create a new character, use the standard priority, 12 availability, in Magic or Resonance select priority level D, now a dropdown bar appears which is empty with empty choices.

### Link to affected character file
Can't give a link cause it won't let me continue char-gen if/when I get to this problem point. This is a screenshot of the issue
![chummer5_aspectedmagician](https://cloud.githubusercontent.com/assets/23406928/20227167/76502538-a84b-11e6-9e7e-66e10bafe472.png)

**Comment by chummer5a** [comment]
Please update to a current version of Chummer. You're five major releases behind, at this point. https://github.com/chummer5a/chummer5a/releases/
