### ISSUE TITLE
Infected Critter Powers need restrictions

### ISSUE THREAD

**Issue by ghost** [chummer5a/chummer5a#1212]
### Environment
Chummer Version: 5.187.22
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When selecting banshee quality: Fear, Mist Form, Paralyzing Howl, and Regeneration should be available for selection according to page 137 in Run Faster. (Same goes for other Infected).

When Selecting an infected quality(any), Primary Attribute total stays the same

### Actual behaviour
Fear, Mist Form, Paralyzing Howl, and Regeneration powers are not one of the abilities to pick from.

When Selecting an infected quality(any), Primary Attribute total with drop by total of gained attributes from infected divided by 2.

### Additional Issues
In Select Quality, Infected Banshee states source is RF80, when in fact it us RF136-137
When selecting the Vampire quality, Infection appears twice in the Critter powers.

Mystic Adepts should be able to buy Power points for 2 Karma each according to CHARACTER CREATION CHECKLIST on Page 101 of fifth edition core rulebook

It seems that the majority of the Infected characters have countless issues.

### Steps to reproduce the behaviour
Create any character (I used an elf), in the priority system, with any priorities set.

### Link to affected character file
All character files

**Comment by chummer5a** [comment]
Your primary attribute points are dropping because your minimums have dropped. Mystic Adepts were errata'd to have their power points cost 5 Karma.

**Comment by DalianNox** [comment]
I guess I don't quite understand. No attributes drop when becoming a banshee, so why would would I lose points? In-fact the Meta-type limit increases. This issue doesn't occur when using the Karma system; no extra karma is spend anywhere.

Also, yup, just say the errata'd version, my mistake.

**Comment by chummer5a** [comment]
Fgsfds, never mind about the attributes, I found the problem.
