### ISSUE TITLE
Weapon foci cancel crash

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1214]
### Environment
Chummer Version: 5.187.0
Environment: Windows 10
Runtime: NET 4.5.1)

### Expected behaviour
No crash when canceling the buying of a  weapon focus.

### Actual behaviour
Chummer crashes when canceling a weapon focus.

### Steps to reproduce the behaviour
Chargen. Make a mage or adept. Begin Buy a weapon focus. Cancel when chummer asks: "Enter a Value for weapon focus". 
Chummer will crash. It does not matter if you have a weapon or not. If trying to send a crash report, an error will prevent that.

I have heard of more users with the same problem.

**Comment by chummer5a** [comment]
I can't replicate it. On the crash report window, you should see a blue link that opens a folder in your Temp directory. Can you open up the exception.txt file inside it and paste the contents?

**Comment by drakir75** [comment]
Chummer.Classes.AbortedException: Ett undantagsfel av typen Chummer.Classes.AbortedException inträffade.
   vid Chummer.ImprovementManager.CreateImprovements(ImprovementSource objImprovementSource, String strSourceName, XmlNode nodBonus, Boolean blnConcatSelectedValue, Int32 intRating, String strFriendlyName, Object fCreate) i D:\Coding\chummer5a\Chummer\Classes\clsImprovement.cs:rad 977
   vid Chummer.Backend.Equipment.Gear.Create(XmlNode objXmlGear, Character objCharacter, TreeNode objNode, Int32 intRating, List`1 objWeapons, List`1 objWeaponNodes, String strForceValue, Boolean blnHacked, Boolean blnInherent, Boolean blnAddImprovements, Boolean blnCreateChildren, Boolean blnAerodynamic) i D:\Coding\chummer5a\Chummer\Backend\Equipment\Gear.cs:rad 280
   vid Chummer.frmCreate.PickGear() i D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:rad 17081
   vid Chummer.frmCreate.cmdAddGear_Click(Object sender, EventArgs e) i D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:rad 5705
   vid System.Windows.Forms.Control.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnClick(EventArgs e)
   vid SplitButton.OnMouseUp(MouseEventArgs mevent) i D:\Coding\chummer5a\Chummer\SplitButton.cs:rad 316
   vid System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   vid System.Windows.Forms.Control.WndProc(Message& m)
   vid System.Windows.Forms.ButtonBase.WndProc(Message& m)
   vid System.Windows.Forms.Button.WndProc(Message& m)
   vid SplitButton.WndProc(Message& m) i D:\Coding\chummer5a\Chummer\SplitButton.cs:rad 823
   vid System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   vid System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   vid System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   vid System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   vid System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   vid System.Windows.Forms.Application.Run(Form mainForm)
   vid Chummer.Program.Main() i D:\Coding\chummer5a\Chummer\Program.cs:rad 98
