### ISSUE TITLE
More Knowledge skills 

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1215]
### Environment
Chummer Version: 5.187.0

### Wish
Not a bug, just feature request. (And I know I can easily fix for my characters)
It irks me a bit "Tacoma" is not among the choices for specializations on the "Area Knowledge: Seattle" knowledge skill.

I would also like to have 
"Police Procedures" with specializations as in the Core rules (Professional). 
"Astronomy" (Mars, Moon, Comets, Stars)(Academic)
"Radical Groups" (TerraFirst!, Alamos 20K, Seed, Logos, etc) (Street)
"Forensics" (Thaumaturgic)(Professional)
"Vehicles" (Cars, Bikes, Aircraft, Boats, Drones)(Interest)

**Comment by evilspiral** [comment]
Are you referring that there needs to be a "Area Knowledge: Tacoma" or that there needs to be a sub skill of Seattle for Tacoma. The latter wouldn't make sense geographically since Tacoma is it's own city, and is a good distance from Seattle, also they are separated by SeaTac. just FYI.

**Comment by drakir75** [comment]
Puyallup is south of Tacoma and are among the specs to "Area Knowledge: Seattle". Tacoma is part of UCAS and not Salish-Shidhe. IMO therefore a part of "the greater Seattle Area" and a valid specialization to that knowledge skill. I would argue Fort Lewis also should be there. 

I am not a Seattle resident so I have no knowledge of todays situation, but apparently some 60 years from now the situation has changed some. :-)

**Comment by Lochabar** [comment]
There are a number of knowledge skills from SRM Season 5 contacts that could be included:
- Famous Shadowrunners
- Runner Hangouts
- Music (Modern Punk)
- Armor Repair
- Firearm Repair
- Vehicle Repair
- Dwarven Porn (and by extension Ork, Troll, Elven?)
- Safehouses
- Aztlaner Cuisine
- Aztlaner Sports (ollamaliztli)
- Corporate Finances
- Corporate Rumors (Aztechnology) (and by extension the rest of the corps?)
- Corporate Security (Aztechnology) (and by extension the rest of the corps?)
- History (Central American) (and by extension all other skills that are broken down by North and South America)
- Spanish (Aztlaner)
- Art (Classical)
- Music (Classical) / maybe separate  skill of "Classical Music" with specialists of, say, (19)60's (19)70's, Glam Rock, Punk, Motown, then the true (as of today) classicals, etc.
- Elven Wines
- Magical Artifacts
- Spirit Theory
- Vintage Cars
- SOTA Technology (State of the Art) (Bleeding Edge?)
- Corporate Politics (Horizon) (separate out Politics (Corporate) with specializations by corp)
- Cyberware Design
- Local Drug Dealers (with the area knowledge locations as specializations?)
- Medical Advances
- Music (Opera)
- Organleggers (by location?)
- Smugglers (by location?)
- Boxing
- Metahuman Bone Breaking Points
- Chicago Area (Containment Zone)
- Dwarven Punkbilly (music specialization?)
- Underground Fighting
- Crime Syndicates
- Illegal Goods
- Police Procedures
- Street Rumors
- Black Market Pipeline
- Local Runners
- Matrix Host Design
- Matrix Hot Spots (Chicago Grid)
- Matrix Host Networking
- Organized Crime (Chicago)
- City Speak (and appropriate specializations)
- Law (Contracts)
- Gambling (Sports)
- Sports (Underground Fighting)
- Street Rumors
- Kaiju Monster Movies
- Neo-Anarchist Movement

**Comment by chummer5a** [comment]
I really hate doing data entry; I'll get around to it at one point or another, but if someone feels like doing the copy-paste work and upload it, I'll be able to just vet and approve it. Format is like this:

```
    <skill>
      <id>e216aad1-15fa-48c5-9d0e-0c6a92e819e0</id>
      <name>Yakuza</name>
      <attribute>INT</attribute>
      <category>Street</category>
      <default>No</default>
      <skillgroup />
      <specs>
        <spec>Turf</spec>
        <spec>Politics</spec>
        <spec>Signs</spec>
        <spec>History</spec>
        <spec>Organizations</spec>
        <spec>Safe Houses</spec>
      </specs>
    </skill>
```

You can either generate your own ID using https://www.guidgenerator.com, or leave it blank and I'll batch-process it.

**Comment by Lochabar** [comment]
Regarding Tacoma and Fort Lewis; they are both listed in the "Seattle at a Glance"  section of the Seattle 2072 source book. And should therefore be included as specializations of "Area Knowledge: Seattle".

Seattle in 2075 is a state of UCAS, referred to as Seattle State or sometimes the Seattle Metroplex). Individual districts have their own mayors and local government, and that would cover Tacoma.

**Comment by Lochabar** [comment]
Here is my first attempt at modified/added skills and specialities.

[skills.zip](https://github.com/chummer5a/chummer5a/files/602758/skills.zip)

Need some advice about Corporate Politics/Rumors/Security. I've created a new skill for each one, with a list of Corps as specializations. Listed are the AAA corps, and the corps in the Seattle  2072 sourcebook.

I've also created a Corporation skill, specifically for Ares in this case, that includes Corporate Politics/Rumors/Security.

Now my needed advice; do I leave the individual skills, with an arbitrary list of corporations? Or would it be better to have a few corporations as individual skills, each with a specific list of customizations?

**Comment by chummer5a** [comment]
Up to you, really. Personally, I'd be somewhat worried that we're giving the impression that the ONLY knowledge skills you can take are the ones filled out in the lists, but that's more of a user education worry than anything else.

**Comment by Lochabar** [comment]
I decided to with corporations as individual skills, with specific list of customizations such as politics, rumors, security. My thinking is that you should have to be familiar with a corporation before you can know specific things about the corporation.

I included the AAA corporations and a number of the more familiar AA corporations, mainly those listed in the Seattle 2072 sourcebook.

[skills_2.zip](https://github.com/chummer5a/chummer5a/files/605244/skills_2.zip)
