### ISSUE TITLE
"Root Element is missing" and failure to create crash report

### ISSUE THREAD

**Issue by TheDefective** [chummer5a/chummer5a#1216]
### Environment
Chummer Version: 5.187
Environment: Windows 10
Runtime: .NET 4.5.1?

### Expected behaviour
Chummer should startup

### Actual behaviour
Both Chummer 5.186 and 5.187 crash and give an error that reads "Root element is missing"
### Steps to reproduce the behaviour
Unknown

### Link to affected character file
All of them

**Comment by TheDefective** [comment]
This is a different error I get when I try and run chummer by opening a character sheet

![screenshot 2](https://cloud.githubusercontent.com/assets/8505716/20250698/8597266e-a9df-11e6-9773-17a13fb4d5e1.png)

**Comment by chummer5a** [comment]
Missing root element indicates that you've got a character file in your recent used list that it can't process. I've never been able to replicate the problem; please open regedit, navigate to HKCU\Software\Chummer5 and delete all the keys starting with mru. That should sort you out.

**Comment by TheDefective** [comment]
Thank you this worked perfectly
