### ISSUE TITLE
Issue with Adept Orks and Wendigo Infection

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1218]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.187.23
Environment: Win 8.1
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adept Ork who is infected with Type I of HHMVV "Wendigo" becomes a Mystic Adept

### Actual behaviour
Adept Ork who becomes a Wendigo doesn't gain the Magician parts of the Mystic Adept and "stays" an Adept

### Steps to reproduce the behaviour
create an Ork Adept and add Infected: Wendigo (Adept) quality

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
You shouldn't be seeing a Wendigo (adept) quality any more, you should be seeing Wendigo (Mundane) or (Awakened).

**Comment by Sturmkind** [comment]
sadly only half-fixed. Still doesn't unlock magical skills (such as binding/spellcasting/...)

**Comment by chummer5a** [comment]
Shiiiit. Yes. Easyfix, but new problem, if a magician takes it, it'll double up on skills. Hrm.
