### ISSUE TITLE
Missions Filter

### ISSUE THREAD

**Issue by RedLion0** [chummer5a/chummer5a#122]
Requesting a button that filters things out that aren't legal for Shadowrun Missions. chiefly, this would be things like certain qualities and metasapients at character creation.

Documentation of what is availible in Missions play can be found here.

https://dl.dropboxusercontent.com/u/12034805/Shadowrun%20Missions%20Chicago%20FAQ%20Update%20v1.3.pdf

**Comment by chummer5a** [comment]
This shouldn't be difficult; effectively speaking, add a new key <allowedinmissions> for qualities and metatypes that are forbidden in Missions. If  the key isn't null and is false, ignore the item when populating lists. Add a standard boolean for enabling/disabling missions restrictions, and bob's your mother's brother.

**Comment by joha4270** [comment]
Implemented in 173
