### ISSUE TITLE
Double currency decrement when selecting shield

### ISSUE THREAD

**Issue by scotthaskin** [chummer5a/chummer5a#1221]
### Environment
Chummer Version: 5.187.22.0 (nightly build, looking at help/about for version #)
Environment: Running Windows10
Runtime: Not Sure

### Expected behaviour
When adding a Riot Shield or Ballistic Shield to Gear/Armor the cost ($1200 or $1500) is subtracted from the total left ONCE.

### Actual behaviour
When adding a Riot Shield or Ballistic Shield to Gear/Armor the cost ($1200 or $1500) is subtracted from the total left TWICE. I think this maybe because the items are added as both Armor and as a Weapon.

### Steps to reproduce the behaviour
Create a new character go to the "Street Gear" tab then the "Clothing and Armor" sub tab. Press Add Armor and select "Ballistic Shield" from  "Armor". $2400 will be removed from the total instead of $1200.

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
This should be resolved in 5.178.26.

**Comment by scotthaskin** [comment]
Confirmed the fix in 5.178.26
