### ISSUE TITLE
Drone Weapon Mounts

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1226]
### Environment
Chummer Version: 5.187.29
Environment: Windows 10
Runtime: NET 4.5.1)

### Expected behaviour
Able to find Drone weapon mounts as per page 124 of Rigger 5.0

### Actual behaviour
I can only find Vehicle weapon mounts (p 162 R5) and weapon mounts from SR5 page 461.

### Steps to reproduce the behaviour
Buy a drone.  "Add modification" and try to find Micro or Mini (or any other) _drone_ weapon mount.

Sorry if it's user error and I'm just blind. R5 separates drone weapon mounts (p124) and vehicle weapon mounts (p162) for some reason I can not understand. But the rules are there. 

A big difference is that the smallest drone weapon mounts are only restricted, making them legal (with a fake illegal license)  

### Thanks
Thanks for working on this program. Most of my characters couldn't have been done without it.

**Comment by chummer5a** [comment]
You need to enable the rule 'Use Drone Modification Rules' in Options\Optional Rules.

**Comment by drakir75** [comment]
Thank you.
