### ISSUE TITLE
(Minor) Issue with Troll Natural Armor

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1228]
### Environment
Chummer Version: 5.187.28
Environment: Win 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Skin augmentations (Dermal Plating, Orthoskin, ...) removes/replaces Trolls natural armor

### Actual behaviour
Skin augmentations (Dermal Plating, ...) stack with Trolls natural armor

### Steps to reproduce the behaviour
create a Troll character and add Dermal Plating -> Armor = 1 + Rating of Dermal Plating

**Comment by chummer5a** [comment]
Mmm, I'd need to see an errata or RAW quote that dermal plating removes their natural armour. Things like the metatype reduction call it out, but dermal plating doesn't.

**Comment by Sturmkind** [comment]
you're right, I just checked the english Core Rulebook and there it is not stated.
I just went with what my german copy said. There the last sentence of Dermal Plating and Orthoskin reads something like "By implanting Orthoskin/Dermal Plating, Trolls loose the natural bone plates in their skin and thus their armor bonus of +1".
I also couldn't find something similar in any english rulebook/errata.
This can be closed... sorry for not cross-referencing ;)

**Comment by Iridios** [comment]
I know this was closed but page 94 says Orthoskin removes the +1 Troll armor.
"Note that if a character takes cyberware or bioware,
it may remove a particular racial bonus. For example, if
a player who has an elf character buys cybereyes, their
natural low-light vision is removed and replaced with
the cybereyes and whatever attributes it possesses. If
the player still wants low-light vision, she’ll have to select
the low-light modification for the cybereyes. Similarly,
orthoskin replaces the natural dermal deposits of a
troll so he would no longer receive the +1 dermal armor
from his natural skin hardness."

**Comment by chummer5a** [comment]
Well, crap. That's not going to be fun to fix.
