### ISSUE TITLE
Change Priority Selection Crash

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1229]
### Environment
Chummer Version: Nightly 5.187.31
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Switching around the Special (Magic/Resonance) priority in Priority Gen using Change Priority Selection from the menu works as intended.

### Actual behaviour
Switching around the Special (Magic/Resonance) priority in Priority Gen using Change Priority Selection causes the programme to crash.

### Steps to reproduce the behaviour
Create character using Priority Generation.
Click on Special > Change Priority Selection
Change the Magic or Resonance to a different priority.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
I can't replicate this unfortunately, so it may be something specific with your character. Could you please upload an affected character file by compressing it into a zip and dropping it into the comment field, and provide the exact changes you make that cause the crash? Ie you load the priority selection window, change your magic priority to A, and it crashes.

**Comment by victorypuppet** [comment]
[burnout blade troll.zip](https://github.com/chummer5a/chummer5a/files/601554/burnout.blade.troll.zip)

I load the priority selction window, change magic priority from D Adept to C Adept, choose Computers as the 2 point skill for being C Adept, click OK, and it crashes.

**Comment by DelnarErsike** [comment]
Found the issue (metatype maximums for magic and resonance weren't properly taking essence loss into account when updating priorities), the fix will be packaged with my next pull request.
