### ISSUE TITLE
Cyber/Bioware not improving skills.

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#1236]
### Environment
Chummer Version: 187.46
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding qualities like TETRACHROMACY or Active Hardwires should improve the relevant skills.

### Actual behaviour
No effect.

**Comment by chummer5a** [comment]
Can't replicate the issue with hardwires. The tetrachromacy bioware only increases visual perception tests, and the current implementation logic for improvements is that we only add bonuses that apply constantly.
