### ISSUE TITLE
Cancelling when adding a Negative Quality crashes

### ISSUE THREAD

**Issue by tomservaux** [chummer5a/chummer5a#1240]
### Environment
Chummer Version: 5.187.0
Environment: Windows 10
Runtime: I assume it is 4.5.1 or higher

### Expected behaviour
When you select a negative quality that requires the user to enter a value the "Select A Value" dialog is displayed. Clicking cancel on this dialog should close the dialog and bring the user back to either the Qualities Dialog or the Character sheet depending on whether the user clicked Add & More or OK respectively.

### Actual behaviour
Clicking Cancel on the "Select a Value" dialog crashes the app every time I tried it.

### Steps to reproduce the behaviour
1. Click Add Quality 
2. Select Negative
3. Select Addiction (any)
4. Click Ok
5. Dialog "Select a Value" is displayed and asks you to enter a Value for the selected Quality
6. Click Cancel

### Link to affected character file
(Enter text here)

**Comment by Sturmkind** [comment]
try the latest nightly builds. IIRC this issue has already been fixed

**Comment by chummer5a** [comment]
Yeah, this should be fixed in current nightlies. I'll be updating the release version over the weekend though.
