### ISSUE TITLE
Raising drone sensor with mods lowers armor

### ISSUE THREAD

**Issue by boongeebee** [chummer5a/chummer5a#1241]
Chummer Version: 5.187.48
Environment: Win 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
When using the optional drone modifications to raise the Sensor attribute of a drone the Armor attribute would remain the same.

### Actual behaviour
When using the optional drone modifications to raise the Sensor attribute of a drone the Armor attribute drops to 0.

### Steps to reproduce the behaviour
Use dropdown to add modification, then pick Sensor (Drone), pick a senor rating, then purchase.  Look at Armor attribute of the same drone. It will be 0

### Link to affected character file
https://1drv.ms/u/s!AjwKUhiHhBpK7Cz01Dk0WW1QrJcw

**Comment by chummer5a** [comment]
Hrm. Code seems to think that using the drone modification rules forces the armour to start at zero. Will have an internal chat and sort it out.

**Comment by boongeebee** [comment]
Thanks. This program has made my introduction to Shadowrun a whole lot easier.

Sent from Windows Mail
