### ISSUE TITLE
Vehicles missing standard Mods

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1244]
### Environment
Chummer Version: 5.187.47
Environment: Win 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Vehicles from Rigger 5.0 having their standard equipment/mods installed

### Actual behaviour
Vehicles having only the bare minimum (most times Sensor Array) installed

### Steps to reproduce the behaviour
Add i.e. BMW Teufelskatze and look at the pre-installed mods, check with Rigger 5.0 (here missing flashtech, signature dampening & Flamer in the english version or flashtech, signature dampening 2 & Anti-Theft system 3 in the german version)

**Comment by chummer5a** [comment]
Well, the Teufelkatze has none of those items because there's no stats for them. As a general rule, we only add mods that exist in the tables.

**Comment by OLStefan** [comment]
But there are some vehicle mods added in chummer with page reference R5 ? which refer to mods that are mentioned as pre-installed, but never mentioned elsewhere in Rigger 5.0
