### ISSUE TITLE
Crash on creating a new character

### ISSUE THREAD

**Issue by EmperorJon** [chummer5a/chummer5a#1248]
### Environment
Chummer Version: 5.188.0
Environment: Win7
Runtime: .NET 4.5.1

### Expected behaviour
Creating a new character fine.

### Actual behaviour
Crashed upon clicking OK.

### Steps to reproduce the behaviour
Create a new character of any sort of method. Once you complete the priority or metatype form, it will crash on OK. Seems to be intermittent on Karma and I can't work out why. 100% otherwise.

### Link to affected character file
N/A

Exception attached.

[exception.txt](https://github.com/chummer5a/chummer5a/files/614834/exception.txt)

**Comment by drakir75** [comment]
Got the same crash on 188.0 but seems to be working with 188.3.

**Comment by EmperorJon** [comment]
Just updated to .3 and it didn't seem to change anything.

**Comment by chummer5a** [comment]
Same error? Is it failing to load a character, or create one?

**Comment by EmperorJon** [comment]
Now on .5, problem still occurring. 

[exception.txt](https://github.com/chummer5a/chummer5a/files/616112/exception.txt)


Definitely seems to only be occurring under certain circumstances now but I can't work out what's causing it.

**Comment by chummer5a** [comment]
Is it consistent to a single metatype or priority selection?

**Comment by EmperorJon** [comment]
Updated again to .6 for the record. It seems to be occurring in standard priority, sum to ten, and karma build for any character which is _not_ human.

**Comment by chummer5a** [comment]
Well, that's infuriating. The issue is most likely to be the depth attributes not being populated, but that should be resolved in everything after .3. Um. Try saving https://raw.githubusercontent.com/chummer5a/chummer5a/master/Chummer/data/metatypes.xml into your data folder, overwriting the existing file.

**Comment by EmperorJon** [comment]
That did the trick.
