### ISSUE TITLE
Dog Adepts only receive one Improved Sense power

### ISSUE THREAD

**Issue by iaingalloway** [chummer5a/chummer5a#1253]
### Environment
Chummer Version: 5.188.3
Environment: Windows 10
Runtime: Tested on both 4.5.1 and 4.6.2

### Expected behaviour
Adepts with the "Dog" mentor spirit should receive two "Improved Sense" powers.

### Actual behaviour
Only one Improved Sense power is added to the powers list.

### Steps to reproduce the behaviour
1. Create a new character (using Karma method here, but tested with both)
  * File -> New Character
  * Click "OK"
  * In the left-hand panel, click "Human"
  * Click "OK"
2. Add the "Adept" positive quality
  * Click "Add Quality" in the top-left
  * Ensure that the "Category:" drop-down is set to "Positive"
  * In the panel, click "Adept"
  * Click "OK"
3. Add the "Mentor Spirit" positive quality and select Dog
  * Click "Add Quality" in the top-left
  * Ensure that the "Category:" drop-down is set to "Positive"
  * In the panel, scroll down and click "Mentor Spirit"
  * Click "OK"
  * In the panel, select "Dog"
  * Ensure that the "Choose one:" drop-down on the right reads "Adept: 2 free Improved Sense powers"
  * Click "OK"
  * In the textbox "Enter a value for Mentor Spirit", enter any string (e.g. "Vision Magnification")
  * Click "OK"
  * In the textbox "Enter a value for Improved Sense", enter any string (e.g. "Flare Compensation")
  * Click "OK"
4. Check Adept powers, and observe that only one has been added
  * Click the "Adept Powers" tab
  * Only one power is present (using the second value entered during step 3)

### Other info
The mentor definition in mentors.xml appears to be correct. I tested using a custom mentor spirit too, and was unable to create a definition that would allow two Improved Sense powers to be added.

**Comment by chummer5a** [comment]
The tl;dr explanation is that the improvement manager is adding the first instance of the power, checking if that power exists for the second one, and marking it as free (again). Shouldn't be too difficult to fix.
