### ISSUE TITLE
Cannot add fractional power points or directly add adept powers using the Improvements Manager

### ISSUE THREAD

**Issue by iaingalloway** [chummer5a/chummer5a#1254]
### Environment
Chummer Version: 5.188.3
Environment: Windows 10
Runtime: Tested on both 4.5.1 and 4.6.2

### Expected behaviour
Entering a fraction into the "Create Improvement" window with "Power Points, Adept" selected should result in the addition of fractional power points on the "Adept Powers" tab.

### Actual behaviour
Chummer crashes with "Exception has been thrown by the target of an invocation."

### Steps to reproduce the behaviour
1. Create a new character (using Karma method here, but tested with both)
  * File -> New Character
  * Click "OK"
  * In the left-hand panel, click "Human"
  * Click "OK"
2. Add the "Adept" positive quality
  * Click "Add Quality" in the top-left
  * Ensure that the "Category:" drop-down is set to "Positive"
  * In the panel, click "Adept"
  * Click "OK"
3. Put the character into career mode
  * Click the "Character Info" tab
  * Check the "Mark character as created" checkbox
  * File -> Save
  * Click "Yes"
  * Click "Yes"
  * Click "OK"
  * Enter a name in the "File name" textbox
  * Click "Save"
4. Try to add 0.25pp via the Improvements tab
  * Click the "Improvements" tab
  * Click "Add Improvement"
  * In the "Improvement Type" dropdown, select "Power Points, Adept"
  * In the "Name:" textbox, enter any string (e.g. Improved Sense)
  * In the "Value:" numeric box, enter "0.25"
  * Click "OK"
  * Observe that Chummer crashes with "Exception has been thrown by the target of an invocation."

### Other info
The crash itself is caused by a loophole in the validation logic for the form (if e.g. you tab out of the textbox after entering 0.25, the value is converted to 0, presumably as the modelbinding framework binds it to the view model). It looks like it shouldn't be possible to enter a decimal value here at all, except that being able to do so for adept power points (which are used in increments of 0.25) would be useful.

Alternately for my use-case, it would be handy if the improvements window could add the "specificpower" bonus used by other parts of Chummer (e.g. mentor spirits) so that adept powers could be added directly by improvements.

**Comment by chummer5a** [comment]
Short version, Improvement Manager doesn't do decimals. Easiest workaround for that would be having 1 Rating = 0.25 PP, but that would likely break a bunch of existing functionality. Like you said, it'll be simpler just to add the specificpower improvement to the available custom improvements.
