### ISSUE TITLE
Can't add Underbarrel Shotgun, Laser, or Grenade Launcher

### ISSUE THREAD

**Issue by Zanctmao** [chummer5a/chummer5a#1255]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.188.3
Environment: Windows OS 10 (or whatever is newest)
Runtime:  (probably .NET 4.5.1)

### Expected behaviour
That you could add an Underbarrel Shotgun/laser (Hard target P. 182) or any of the weapons from Run & Gun p. 53 to an Assault Rifle for example. 

### Actual behaviour
If you add a weapon, say an AK97, and then click on it to add an underbarrel weapon the window opens, but it does not populate, and if you click on it it crashes Chummer.

### Steps to reproduce the behaviour
Create a new character, try a Troll Face. Use Build to 10 and take race and skills at "A" and Magic at "C" - everything else at "E".  Max out charisma, use the magic skill on etiquette. beyond that the world is your oyster. 

Once you're ready to buy gear,  to the "street gear" tab. Click on it. Go then to the "weapons" sub-tab and click on that.  Go to assault rifles and add an AK97.  ("not a good weapon for a troll face" you say? "Of course it is" I retort). Once the AK97 appears in the "selected weapons" field on the left. right click on it to bring up the menu that allows you to "add underbarrel weapon"  - woohoo almost there!

Then when the window pops up, scroll down to underbarrel weapons.  Nothing populates the field. No underbarrel shotgun or grenade launcher or bolas or lasers or anything. ("Who wants an underbarrel Bola launcher?" You ask quizzically.  "Thought you'd never ask - the Argentine gaucho Troll Face we were discussing earlier - Now with backstory!")

If you right click in the field nothing happens, but if you left click it causes Chummer to crash. 

### Link to affected character file
I don't have one, but here's an example of a character I cannot add such an AK97 to.  Hilariously it turns out that github doesn't support files of that type. Ha.

**Comment by chummer5a** [comment]
Bah, I thought I'd hidden that functionality. The underbarrel weapons are treated as Accessories; use the Add Accessory button to fix it. I can't replicate the crash, but I imagine it's trying to refresh a null weapon and not getting caught. I'll need to review the population method to make it hide empty categories.

**Comment by Zanctmao** [comment]
BTW thanks for what you do. 

I did that before, and I thought I was doing it wrong. The problem is when you do it that way it treats it as an accessory. No statistics populate the character sheet, it's no different from a concealed quick draw holster or any thing else.  it's just listed along with the shock pad and the external smartgun system.

**Comment by chummer5a** [comment]
Right, I see the problem. Um. There's a quick way to implement it where we just apply an addweapon node to the underbarrel mount, but you'll get a double-up of names. We could alter the Weapon class so that they can consume mount points, I guess. That's probably the best approach.
