### ISSUE TITLE
Chummer Crashes when creating dwarf characters

### ISSUE THREAD

**Issue by themucher** [chummer5a/chummer5a#1258]
Updated Chummer to 5.188.3. Chumer crashed when i attempted to make a dwarf character using Sum to 10.

### Environment
Chummer Version: 5.188.3
Environment: Windows 10
Runtime: Unknown

**Comment by chummer5a** [comment]
I can't replicate it it in 5.188.3 or current builds. Can you please try updating from [this build](https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.188.15/Chummer.Nightly.zip)?
