### ISSUE TITLE
Enhancement : New Active Skill Filters

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1260]
Would be really usefull to add some filters on active skills :
 - Show All Active Skills not attached to a skill group
 - Show all active skills Rating > 0  not in a group (skills in broken skill group should be displayed)

The purpose is to make the list much more readable :
 - Isolate lonesome skills to find them faster 
 - Isolate all skills with rating > 0 not in groupe, skills groups are already displayed

**Comment by chummer5a** [comment]
Hrmmm. So you want it to only show the broken skills that aren't equal to the skill group's rating, (Ie one has had more karma spent on it than the others, so only show that one)?

**Comment by prismatic-mind** [comment]
The idea "1" is to show all skills that are not in any group (like perception, armorer, free-fall etc.)

The idea "2" is to show all skills with a rating > 0 that are not currently in a valid group.
 - All skills rating > 0 in the list of idea "1"
 - All skills rating > 0 in a broken group

If we select the idea 2 in the sort list, it show all skills the character have with a rating > 0. Skills are in the skill group panel or in the skill list, but there is no skill in the skill list that is already in the skill group panel -> faster reading.

If the group Firearms is broken (it should be prompted on the left), show all skills in it (Automatics, Longarms, Pistols) if their rating is > 0.
Exemples :
Automatics = 2, Longarms = 1, Pistols = 1 --> Show Automatics, Longarms and Pistols
Automatics = 0, Longarms = 1, Pistols = 1 --> Show Longarms and Pistols
Automatics = 1, Longarms = 1, Pistols = 1 (with a specialization)--> Show Automatics, Longarms and Pistols
Automatics = 1, Longarms = 1, Pistols = 1  --> Show nothing because the group is not broken

Note, now that i think about it, we could add the Idea "3", identical to idea 2, but including rating 0 skills. It can be usefull too.
