### ISSUE TITLE
Default Drones mod points count

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1263]
Version 5.188.9

Rigger 5.0 state that default mod point count is equal to drone body (Page 122).

(Drone list in rigger 5.0 p 188 to 190 can help)

**Comment by OLStefan** [comment]
It also states that some drones have a different mod point count witten in brackets behind the drone's body.

Are there any specific drones which have a wrong amount of mod points?

**Comment by prismatic-mind** [comment]
Most of them :
Crawler is 0 instead of 3
Criado Juan is 0 instead of 2
Fly spy is 0 instead of 1
etc.

I'll check the entire list if you want but later.

**Comment by OLStefan** [comment]
I think you just missunderstand the notation there. Mod Slots: 0/1 means 0 slots out of 1 is spent for modifiacations.

**Comment by prismatic-mind** [comment]
Nope.
It should be 3/3 and it is reduced to 0/3 when we  add mods.
Maybe it's just a bug in mod point spent count then ?

**Comment by OLStefan** [comment]
Right now 0/3 means 0 points spent. If you add a mod for 1 point, it will show 1/3 Mod Count.

**Comment by prismatic-mind** [comment]
ok, my bad.
It seems drone pilot mod don't count mod points :)

Maybe it should cost some mod points since it's listed as attribute in attribute modification p123
, rigger 5

**Comment by chummer5a** [comment]
Pilot mod doesn't cost mod points because it's not described as costing mod points. Also, pilot is a Program.

As for the mod slots, our standard UX is to count down; we should probably stick with that for the sake of consistency.

**Comment by prismatic-mind** [comment]
Not really a problem in my opinion to count down or up. I should not make this mistake, but i think i was mistaken by an old behavior.

Considering Mod Points and Pilot, i d'ont agree.

If we read "ADDING UPGRADES" P.122
"ATTRIBUTE MODIFICATIONS" P.123
We can consider that increase pilot need to add memory or better electronic gear.

Pilot is an attribute listed in attribute modification.

So i dont consider it's only a matter of program, but no need to fix it in my opinion since o think most users don't think th same way.
And adding this with optional rule is not really worth :)

I think you can just close this issue that was not an issue :)
Sorry for that :)
