### ISSUE TITLE
Adept, Magician etc. does not fall under Qualities anymore

### ISSUE THREAD

**Issue by shayhulut** [chummer5a/chummer5a#1266]
### Environment
Chummer Version: Nightly-v5.188.20
Environment: Win7

### Expected behaviour
The Options 'Adept', 'mystic Adept', 'Magician', 'aspected Magigicans' and 'Technomancer' are no Qualities anymore. This is a change to SR4. So, they do also not count against the Max Number of Qualities you can buy at the beginning. 

### Actual behaviour
This Qualities are still listed as Qualities and still count against the Maximum

### Steps to reproduce the behaviour
- generate a new Character
- go to Qualities
- select Adept

**Comment by chummer5a** [comment]
Those qualities have a flag that prevents them from contributing to your quality limit.
