### ISSUE TITLE
Item from Enhanced Fiction: Nothing Personal, 

### ISSUE THREAD

**Issue by RedLion0** [chummer5a/chummer5a#127]
Please add in the F-B Bumblebee drone. It is found on page 23 of the Enhanced Fiction "Nothing Personal" and is one of the best drones available to Riggers right now. Stats copied below.

Handling : 3  Speed : 2  Accel : 1  Bod : 4  Arm : 14  Pilot : 3  Sensors : 3  Seats -  Availability : 12F

Standard Accessories: Stoner-Ares M202 [Machine
Gun, Acc 5, DV 10P, AP –3, FA, RC —, 100(belt), w/ tracer
rounds]
Stoner-Ares M202 Targeting Autosoft (The book doesn't specify a rating on it, but it seems like drones that come with autosofts all come with them at rating 3)

It's described in the book as a heavily armored standard Roto-Drone, so I'd assume medium size.

Cost : 24,000 Nuyen

**Comment by chummer5a** [comment]
Included in 5.159.
