### ISSUE TITLE
Entries from Chrome Flesh Source book appear when the book is disabled in the options.

### ISSUE THREAD

**Issue by cskwrd** [chummer5a/chummer5a#1273]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Within 10 days of latest debug build
Environment: Windows
Runtime: Whatever the csproj is set to

### Expected behaviour
Chrome flesh source book entries don't show up in Lifestyle selections if the book isn't enabled in the options.

### Actual behaviour
CF selections do show up.

### Steps to reproduce the behaviour
create new character, (I used priority mode, but doubt it matters) navigate to lifestyles, click "Add new Lifestyle. Notice CF entries are mixed in with the SR5 entries even though the book isn't active in the options.

### Link to affected character file
create a new character

**Comment by DelnarErsike** [comment]
Fixed in latest pull request.
