### ISSUE TITLE
Life Module cost calculation error

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#1276]
### Environment
Chummer Version: Encountered in 5.188.* nightlies, likely originates with skills refresh.

### Issue
Karma costs are incorrect for life modules with certain skill choices, not properly receiving 'free' karma. 

### Steps to reproduce the behaviour
Create a character with a life module that confers a SkillGroupLevel improvement (ie Electronics) and a SkillLevel improvement targeting a skill in that group, such as Computer. Note the Build Summary for Active Skills increases. 

Issue is most likely due to miscalculation of RangeCost in Skill.Core.cs CurrentKarmaCost().

### Link to affected character file
[20161207.Test.LM.KarmaCalculation.chum5.zip](https://github.com/chummer5a/chummer5a/files/634039/20161207.Test.LM.KarmaCalculation.chum5.zip)

**Comment by OLStefan** [comment]
Part of #2000.
