### ISSUE TITLE
last knowledge skill of the file not showing in chummer (maybe character file inconsistency)

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1277]
### Environment
Chummer Version: 5.188.47
Environment: win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
All knowldedge skills are displayed

### Actual behaviour
I have a character with the last knowledege skill of the file not showing. But with sort options it show up after some changes.

### Steps to reproduce the behaviour
Don't really know how to. It may be a cause of bugs on knowledge skills with older versions of chummer

### Link to affected character file
[chummer_character.zip.txt](https://github.com/chummer5a/chummer5a/files/635384/chummer_character.zip.txt)

**Comment by chummer5a** [comment]
This is probably related to #1195.
