### ISSUE TITLE
Issues with adding Weapon Mount Modifications to the Weapon Mounts themselves

### ISSUE THREAD

**Issue by GIn-German** [chummer5a/chummer5a#1279]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? (**Version 5.188.3**)
Environment: (Operating system here. If it persists over multiple OS's list them all) (**Windows 7 Ultimate 64-Bit**)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Able to add the modifiers for Visibility, Flexibility and Control to a Weapon Mount on a vehicle in a drop-down menu similar to gear added to weapons/armor

### Actual behaviour
Weapon Mount Modifications are not able to be "inserted" into a drop-down list under the specific weapon mount, instead listing them as separate entities on the list for the other (vehicle) modifications. When Right-Clicking a Weapon Mount to add any modification to it the program instead switches to the vehicle itself, adding the modification as a separate listing instead of adding it to the Weapon Mount in a drop-down list.

### Steps to reproduce the behaviour
Right-Clicking the Weapon Mount and selecting "Add Modification". Instead of keeping the Weapon Mount selected the program instantly switches to the Vehicle (the one the mount is installed in). Thus the modification added will be made a separate listing instead of being added to the Mount in question.

### Additional Notes
Despite not being inserted into a Drop-Down list within the Weapon Mount, each Modification DOES subtract the correct "Weapon" Value from the Total of the Vehicle!

### Link to affected character file
Attached to the Post

[Speedy - Gnome Rigger.zip](https://github.com/chummer5a/chummer5a/files/637245/Speedy.-.Gnome.Rigger.zip)

**Comment by chummer5a** [comment]
Known issue, will be fixed as part of #1077.
