### ISSUE TITLE
When adding modifications to a drone, and clicking the free checkbox, the cost of the mod is still subtracted from ¥

### ISSUE THREAD

**Issue by 415DomSmith** [chummer5a/chummer5a#1281]
### Environment
Chummer Version: 5.188.3
Environment: OSX running Windows 10 in VM

### Expected behaviour
When clicking the free box while adding drone modifications, it should not subtract cost of item from nuyen total

### Actual behaviour
it subtracts cost of item from nuyen total

### Steps to reproduce the behaviour
Add a retrans modification to a GTS tower drone, and clicking the free checkbox when adding it.

**Comment by DelnarErsike** [comment]
Fixed in latest nightly.
