### ISSUE TITLE
Learning a martial art makes chummer automatically spec the character in it.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1289]
### Environment

Chummer Version: 5.188.22, tested quite a few builds post late 187s
Environment: win10
Runtime: it is probably .NET 4.5.1

### Expected behaviour

Learning a martial art is not supposed to have any effect on skills unless you spec into one for normal speccing costs

'Martial arts styles may also be selected as specializations for the normal cost of 7 Karma—selecting that specialization provides a +2 bonus when using that technique'; 'Buying a new style costs 7 Karma, and when you buy that style you may then choose a technique to go with it.' p.128, Run&Gun

### Actual behaviour

Learning a martial art autospecs the relevant skill to the martial art learned. The spec cannot be removed and consumes a skillpoint

### Steps to reproduce the behaviour

Add a martial art to a character in gen, observe chummer assign a spec

Additionally, the One Trick Pony quality triggers the chargen limit of only 1 martial art known. This should not happen, as OTP does not provide an actual martial art.

**Comment by chummer5a** [comment]
I had a suspicion that code was wrong when I added it, couldn't find a RAW against it at the time.
