### ISSUE TITLE
PACKS generally not working

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#129]
Just looking at them funny causes errors.

They seem to contain the appropriate things but show up as Chummer.list in the name field and clicking on them causes errors.

**Comment by chummer5a** [comment]
Compare the chummer4 code for frmSelectPACKS to chummer5a's. I'll lay odds
there's some divergences in there that are causing the issue.

**Comment by chummer5a** [comment]
Okay, so PACKs work, but there's a huge pile of bad items in there that don't exist anymore. I've included a couple of basic wrappers that should catch most errors, but packs.xml is gonna have to be rewritten from scratch.
