### ISSUE TITLE
Can't Add Skills

### ISSUE THREAD

**Issue by biscuitWizard** [chummer5a/chummer5a#1290]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.188.3
Environment: Windows 7, Windows 8.1
Runtime: 4.5.1

### Expected behaviour
Added skills in skills files should show new skills in Chummer or if there's an error to the XML format, report that error.

### Actual behaviour
No visual indication of that skill being added or errors reported.

### Steps to reproduce the behaviour
Create a file called custom_lazarus_skills.xml with the content:
`<?xml version="1.0" encoding="utf-8"?>
<chummer>
	<categories>
		<category type="active">Custom Active</category>
	</categories>
	<skills>
		<skill>
			<name>Bikes</name>
			<attribute>REA</attribute>
			<category>Custom Active</category>
			<default>Yes</default>
			<skillgroup></skillgroup>
			<specs>
				<spec>Racing</spec>
			</specs>
			<source>SR5</source>
			<page>147</page>
		</skill>
   </skills>
</chummer>`
Add that file to the data directory of chummer.
Start chummer.
Check the skills page

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Add  <id>e8c6ee49-ca6f-4414-9c55-89db11f8529a</id> to the skill node. All skills and objects need to have a GUID for internal use.
