### ISSUE TITLE
Crash on 5.188.63 'Add Lifestyle'

### ISSUE THREAD

**Issue by jjl254** [chummer5a/chummer5a#1296]
### Environment
Chummer Version: 5.188.63
Environment: Win 10 Pro
Runtime: 4.6.01586

### Expected behaviour
Clicked "Add Lifestyle"

### Actual behaviour
Crash

### Steps to reproduce the behaviour
 Crash report: f07adeb8-95bb-4c22-93ad-875c4a140583

### Link to affected character file
https://drive.google.com/file/d/0B4YzVtOYqDPINm1JWHBzZm5Bdzg/view?usp=sharing

**Comment by chummer5a** [comment]
This should be fixed in 5.188.68: https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.188.68/Chummer.Nightly.zip
