### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by twtse** [chummer5a/chummer5a#1300]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 1.888.3
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Chummer should update, restart, and launch without crashing

### Actual behaviour
Chummer updates and crashes upon restart

### Steps to reproduce the behaviour
Redownloading files and updating fresh download causes crash.

Exception.txt:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Chummer.LanguageManager.GetString(String strKey)
   at Chummer.frmCharacterRoster.LoadCharacters()
   at Chummer.frmCharacterRoster..ctor()
   at Chummer.frmMain..ctor()
   at Chummer.Program.Main()

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
Try updating to the latest nightly, looks like you're missing a dictionary string.
