### ISSUE TITLE
Mentor spirit crash

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1301]
### Environment
Chummer Version: 5.188.78 and 5.188.18. (guessing earlier too)
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
No crash when choosing a mentor spirit that gives an adept power with rating two when attribute Magic is only one.

### Actual behaviour
If Magic attribute is one for an adept and a mentor spirit like "Spider" or "Berserker" is chosen Chummer will crash instead of decreasing the adept power.

### Steps to reproduce the behaviour
Create mode. Magic priority D. Buy some cyber/bioware. Get Mentor Spirit with a power with rating 2. If Magic is one, Chummer will complain and crash.

**Comment by drakir75** [comment]
Seems to work when Magic is 0. Should a PC be able to choose a Mentor Spirit with a Magic score of 0?

**Comment by chummer5a** [comment]
Burnout only happens when you hit 0 Maximum MAG, so there's no technical reason for it not to work. Adept Powers need a rework, they're a mess as is.
