### ISSUE TITLE
Chummer crashes upon launch after update

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#1305]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Updater said build 189. Can't launch, though, so I can't verify.
Environment: Windows Vista
Runtime: Unknown

### Expected behaviour
I expect for chummer to launch without crashing?

### Actual behaviour
Crashed immediately upon launch, every time.

### Steps to reproduce the behaviour
Launch the program. It crashes.

![9yfhyq7 1](https://cloud.githubusercontent.com/assets/13134139/21296572/a59ff770-c5a9-11e6-9226-1a35949d79f4.jpg)

**Comment by chummer5a** [comment]
That's... interesting. What was the last version you were using? Does it work if you download the latest release manually from github.com/chummer5a/chummer5a/releases/latest?

**Comment by Verecoth** [comment]
Previous version was 188 according to the changelog. About to download and install from scratch. Will update upon completion.
