### ISSUE TITLE
Crash on Character Load

### ISSUE THREAD

**Issue by FynnGerring** [chummer5a/chummer5a#1306]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.188.3 and 5.189.0
Environment: Windows 10, Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Chummer does not crash on loading an existing character

### Actual behaviour
Chummer crashes on loading an existing character

### Steps to reproduce the behaviour
Start Chummer
Click the Open File button
Select the linked character
Observe crash

### Link to affected character file
https://drive.google.com/file/d/0B-LV5L_rucqvY2tmRXFtX2lGVDg/view?usp=sharing

**Comment by chummer5a** [comment]
Bad file, entire thing is null. Got a backup copy somewhere?

**Comment by FynnGerring** [comment]
Yeah but some work has gone into it since the update. There's no way to recover? Any advice for how to prevent this in the future?

Thanks for the quick reply though!

**Comment by chummer5a** [comment]
No idea what caused it; I don't *think* it's on Chummer's end, but I can't be sure.

**Comment by FynnGerring** [comment]
What tool do you use to see the contents of the file without crashing Chummer? Is it possible it was caused by some interaction with virtualbox? This particular character was made on a macbook.

**Comment by chummer5a** [comment]
A .chum5 file is just UTF-8 formatted XML. You should be able to open it up in any txt editor, but I use notepad++ personally.
