### ISSUE TITLE
Crash with Custom Tradition Option

### ISSUE THREAD

**Issue by relentlessimp** [chummer5a/chummer5a#1309]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.189.0
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1) .NET 4.5

### Expected behaviour
File->Print causes a Window to pop up with options to select what format is printed in.

### Actual behaviour
Print with a Custom Tradition causes Chummer to crash.

### Steps to reproduce the behaviour
1: Create character with Magician or Mystic Adept traits
2: On the Spells & Spirits screen, under Tradition, select Custom, input options
3: File->Print
4: Crash.

### Link to affected character file
https://www.dropbox.com/s/1y01zmik4mswhse/Rapsumsi.chum5?dl=0
This is just the character I was working on at the time, but I've attempted it with various options back and forth with different metatypes and spirit choices. It happens every single time.

**Comment by chummer5a** [comment]
This is fixed in https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.189.4.
