### ISSUE TITLE
Cyber-Snob Quality

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1311]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Nightly-v5.189.4
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Cyber-Snob quality under Negative Qualities from Chrome Flesh page 57 giving a bonus of 12 Karma.

### Actual behaviour
Cyber-Snob is not a listed Negative Quality.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by OLStefan** [comment]
Cyber-snob is propably not visible because you don't have the required 1 essence in betaware augmentations. To check that please uncheck the 'Show only qualities I can take' box and see if it is there.

**Comment by victorypuppet** [comment]
Ah, oops. Thanks for pointing that out. Is there any way to house rule that quality? The community I play with has the following House Rule in effect for Cyber-Snob: The bonus for this quality is 6 Karma, and the required augmentation grade is Alphaware.

**Comment by dluxcru** [comment]
I think there are ways to add a custom quality? That might help you, victorypuppet.

**Comment by chummer5a** [comment]
You can use a custom or override file to change the quality to do what you want. [Check the Wiki](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files) for a brief overview of how to go about creating a custom or override file. 

In most cases other people won't need a copy of your custom/override file UNLESS they hit the Reapply Improvements button in the Special menu.
