### ISSUE TITLE
Missions Errata 

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1313]
Chummer doesn't take into account the following errata from the current Missions errata:

Does the custom fit (stack) bonus ( ​Run & Gun, pg. 59) count as a “+” armor item for encumbrance
​ ( ​SR5, pg. 169)?
Yes, each stack piece counts against your encumbrance.

Does the custom fit (stack) count toward my armor accessory limit?
Yes. All that the custom fit rule does is allow an item that would normally be its own individual
piece of armor (and thus would not normally stack) become an armor accessory when worn as part of a
set

Bio-weapon claws grant a bonus to Reach (+1) when used in pairs, does this apply to cyber melee
​ ​ weapons ( ​SR5, pg. 458) as well? ( ​Chrome Flesh, pg. 120)
Yes, as long as they are purchased and used in pairs. This does not increase damage and your
hands must be free to be able to use both hands, i.e. not holding anything.

If used in pairs, do biospikes (bone spurs) grant a +1 bonus to Reach? ​( ​Hard Targets, pg. 185)
Yes, as long as they are purchased and used in pairs. This does not increase damage and your
hands must be free to be able to use both hands, i.e. not holding anything.

**Comment by chummer5a** [comment]
The encumbrance thing was an overlooked error, just me being terrible at testing. As for the claws and spikes, I'm not sure I can or want to implement that as an automatically calculated value, since Chummer can't know which weapons you're using for any particular attack.
