### ISSUE TITLE
GUI cuts skill names off

### ISSUE THREAD

**Issue by Techkid86** [chummer5a/chummer5a#1318]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.189.0
Environment: Windows 7 Pro
Runtime:  probably .NET 4.5.1

### Expected behavior
Skills and skill groups appear fully visible and readable

### Actual behavior
Skills appear cut off, and shifted, no matter window size or screen resolution. 
![image](https://cloud.githubusercontent.com/assets/6530530/21448404/4ab6f94e-c8b0-11e6-8eab-00ab2e0ea697.png)

### Steps to reproduce the behavior
Make a new character with default settings. (Human or elf tested)

### Link to affected character file
Any new character file

EDIT: Even moving the side window off to the right, (Shrinking it's width) does not fix the problem, it only makes the specialization drop down longer)

**Comment by chummer5a** [comment]
Font size is greater than 100%, it's a known issue. Only fix for now is to drop your font size back down.
