### ISSUE TITLE
Error looking for qualities

### ISSUE THREAD

**Issue by dluxcru** [chummer5a/chummer5a#1319]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 1.88.3, 1.189.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Searching for a quality in the quality window and adding a minimum value for karma cost to a value where a match does not exist. 

### Actual behaviour

Searching for a quality in the quality window and adding a minimum value for karma cost causes a crash to the program (likely occurs when no matches for both term and cost must be found - error message read something about "Expression must evaluate to a node set" - I'm guessing that this could be an error in LINQ to XML?).

### Steps to reproduce the behavior
Searched for "pho" for phobia quality, and then clicked the arrow on minimum karma value. 

On a side note, please remove the "u" from behavior on your bug report forms. It's not the right spelling.

### Link to affected character file
(Enter text here)

**Comment by jthibs** [comment]
Just a note on the spelling of the word. Behavior is the preferred spelling in American English. Behaviour is preferred everywhere else.

**Comment by dluxcru** [comment]
Ah. That makes sense, my spell check just screams.

**Comment by chummer5a** [comment]
Fixed in latest commits.
