### ISSUE TITLE
Point Buy: Knowledge skill specialization subtracts free Knowledge Skill Points.

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#132]
Reproduce:  Create a new char, choose point buy, add some Logic and Intuition, choose a knowledge skill and give it a specialization. 

Every specialization subtracts 7 from the available free points granted through your attributes (are those even a thing in Point Buy anymore?  No one seems to know for certain.), which makes it hard to use specializations.

**Comment by Haekel** [comment]
Yeah, it's late, I can't type. It's supposed to be "substracts from free Knowledge Skill Points" in the title.

**Comment by Haekel** [comment]
Maybe related:  

The houserule for "Karma Build: Free Knowledge Skills like Karma Build" (which is supposed to read Priority Build, I assume? :P) does not "stick". Checking it and leaving the screen leaves the box unchecked at reentering the screen.   Every other house rule works just fine.

I assume the feature is just not done yet, but wanted to bring it to your attention anyway.

**Comment by chummer5a** [comment]
Resolved in 5.160. Also fixed a few more of those tedious BP entries.
