### ISSUE TITLE
Enhancement: Add option to prevent Chummer actions for an "Enemy"

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1325]
At present, during create, if you add an Enemy it deducts contact points as a regular contact, unless you check the "free" box. Additionally, in career mode, having enemies automatically increases Notoriety.

Can you add a house rule to prevent Chummer performing any actions for an "Enemy" contact.

**Comment by dluxcru** [comment]
Needed, I don't use the enemy fields for this reason.

**Comment by chummer5a** [comment]
Can't replicate the use of contact points, the code certainly suggests it shouldn't be possible. 

Notoriety is easy enough to fix in CalculatedNotoriety, would just need a characteroption rule as a wrapper. Will most likely get done when we switch to the new options system.

**Comment by Lochabar** [comment]
Sorry my fault; its not contact points - it's points added to negative qualities that are added:
![creating enemy](https://cloud.githubusercontent.com/assets/17562417/21476098/e810320a-caf9-11e6-817a-54b4aac77749.png)

**Comment by joha4270** [comment]
That is intended behavior. Enemies are a 4th edition quality kept due popular demand.

See page 104 of _Runner's Companion_ for the quality and  page 132 for additional details.

**Comment by Lochabar** [comment]
That's why I'm asking for an option to switch off the effects of the quality, not get rid of enemies.

**Comment by Lochabar** [comment]
I saw this in the release notes for 196.0:
Removed the increase to Notoriety that Enemies provide, as it's not a relevant rule in SR5.

What about the count added to negative qualities shown above?

**Comment by Lochabar** [comment]
The house rule setting is not working. I unchecked the option (but was not asked if I wanted to save the options)
![setting](https://user-images.githubusercontent.com/17562417/34635938-9cf4c5ac-f28e-11e7-9835-ea91022ca01b.png)

Here is the build summary before adding an Enemy
![before](https://user-images.githubusercontent.com/17562417/34635949-b216fc2a-f28e-11e7-8618-8e0febfa7652.png)

And after. Note that the Enemy total has gone negative, and the negative karma total has increased.
![after](https://user-images.githubusercontent.com/17562417/34635958-d175fb66-f28e-11e7-912c-ff330eed5d00.png)

**Comment by chummer5a** [comment]
Oh, I'm an idiot and forgot to bind the event that flags that we need to change the options. As an interim, if you toggle another option off and on it should save properly.

**Comment by Lochabar** [comment]
Just checked with 5.196.35; the option is now saved.

But it does not work. Repeated the above test and karma and negative qualities are still changed when the flag is unchecked.

**Comment by chummer5a** [comment]
They still charge karma with that rule, it just doesn't count towards your negative quality limit. I was lazy and didn't update or replace the karma label to represent that. If you'd like to completely remove the karma bonus, just set the spinner for Enemies on the Karma Costs tab of Options to 0.
