### ISSUE TITLE
Commlinks Character Viewer does not display Linked SIN

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1326]
### Environment
Chummer Version: 5.189.7 (but problem existed in many prior versions)
Environment: win7
Runtime: .NET 4.6.1

### Expected behaviour
The Commlinks character viewer/print field "Linked SIN" shows the name of the SIN the commlink contains.

### Actual behaviour
The Linked SIN field is blank. The XSLT show the field should be populated with the "extra" field from the XML:
	<td width="25%" class="tableborder">
		<strong>Linked SIN</strong>
	</td>
	<td width="75%" class="tableborder" colspan="3">
		<xsl:value-of select="children/gear[issin = 'True']/extra" />&#160;
	</td>
This issin flag is set and the extra field is populated on the XML file.

### Steps to reproduce the behaviour
Allocate a SIN to a commlink and use the character viewer->commlinks.

**Comment by chummer5a** [comment]
Can't replicate it in create or career mode; care to upload a file so I can rule out user error on my part?

**Comment by Lochabar** [comment]
Character file:
[Rakash.chum5.zip](https://github.com/chummer5a/chummer5a/files/672539/Rakash.chum5.zip)

The code:
![commlinks xsl](https://cloud.githubusercontent.com/assets/17562417/21475726/f96dde6c-caf4-11e6-90d2-13979183aacf.png)

The character viewer:
![linked sin](https://cloud.githubusercontent.com/assets/17562417/21475740/39fc0788-caf5-11e6-9192-247404721847.png)

The XML:
![xml](https://cloud.githubusercontent.com/assets/17562417/21475782/2470756a-caf6-11e6-95a4-fefae540ca1a.png)

And looking at the XML the "extra" field is not populated - which indicate my original issue is likely not a problem. In which case, how do I populate the "extra" field?

**Comment by chummer5a** [comment]
Drag your Fake SIN item onto the commlink. The XSL is looking for a child item that has the issin property set to true, which is currently only enabled by having a Name value of Fake SIN. At some point when I get around to implementing identity management that section will get an overhaul, but for the moment, the expectation is that you attach a fake sin to the commlink, which the character sheet then picks up.

**Comment by Lochabar** [comment]
Got this to work. Thx.
