### ISSUE TITLE
Mystic Adept cannot receive more than 1 power point. 

### ISSUE THREAD

**Issue by dluxcru** [chummer5a/chummer5a#1329]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 1.89.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
One should be able to use karma to provide power points to mystic adepts. 
### Actual behaviour
Cannot receive more than one power point. Regardless of weather one tries to input manual values or uses arrows to increment doesn't work. Reapply improvements doesn't fix it either. 

### Steps to reproduce the behaviour
Try and add power points to a mystic adept. 

### Link to affected character file
http://pastebin.com/LGnE1A66

**Comment by chummer5a** [comment]
Can't replicate it in current nightly builds, but we haven't touched mystic adepts in a while. Could you try with the latest build?

**Comment by dluxcru** [comment]
Seems like this was a one-time thing - I rebooted chummer and that fixed it. So I can't replicate either. Maybe it had something to do with a Mentor Spirit (Cat in paticular) that grants free levels getting assigned before I tried to assign powerpoints causing the bug? Other than that can't think of anything.
