### ISSUE TITLE
Point Buy: Mark as created is denied, "1 over allotted Active Skill Point limit"

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#133]
Not sure what happens here, to be honest. Chummer won't allow me to save my character as created, giving me the above error as a reason.   I tried lowering my active skills to see if I had crossed some limit I wasn't aware of, but that changed nothing.

**Comment by chummer5a** [comment]
Can you upload your character somewhere for me to take a look? http://pomf.se/ is an easy-to-use filedropper.

**Comment by Haekel** [comment]
http://a.pomf.se/qzgkuu.chum5  Here you go, man.

**Comment by Haekel** [comment]
Oh, never mind.   I'm just stupid.  Forgot to check the "Buy with Karma" box for my vehicles specialization.

**Comment by chummer5a** [comment]
Resolved in 5.160, the checkbox is checked and disabled by default, need to have the optional rule enabled to turn it off.
