### ISSUE TITLE
HMHVV Character issues

### ISSUE THREAD

**Issue by rtngtom** [chummer5a/chummer5a#1330]
### Environment
Chummer Version: 1.589.14
Environment: Windows 10

### Expected behaviour
Selecting a HMHVV quality will allow selecting of perks based off of the quality(5.189.14) and will provide a discount if the character is awakened(Since 5.188).

### Actual behaviour
Selecting a HMHVV Quality will allow you to pick the first benefit, usually a heightened sense, and then softlock, causing the user to force close the application, and since 5.188 there is no discount based on awakened status, similar to #1314

### Steps to reproduce the behaviour
5.189.14: Create a character, take a HMHVV quality, start selecting "perks".
5.188.0+: Create a character, take a HMHVV quailty, select "perks". Karma discount will not be applied.

**Comment by chummer5a** [comment]
Blah. The selecttext improvement will be the death of me, I swear. No current fix, short of rolling back to 5.189.13. Shouldn't be too hard to resolve.
