### ISSUE TITLE
Chummer takes a long time when changing Damage

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1332]
### Environment
Chummer Version: 5.189.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Apply Damage

### Actual behaviour
Apply Damage
Freeze for 2-3 minutes

### Steps to reproduce the behaviour
Apply Damage

**Comment by chummer5a** [comment]
Can't replicate it. There's not much going on with that segment of code aside from a call to updatecharacterinfo; is it specific to a particular character? If you watch your process monitor, is there any spike in memory or CPU usage?

**Comment by Maxis010** [comment]
I was not character specific
I've just retested it on all of the characters I have and I don't have chummer freezing like before
Going to put this down to a 3rd party issue and monitor my machine if it occurs again
