### ISSUE TITLE
issues with change priority settings in sum to 10

### ISSUE THREAD

**Issue by FynnGerring** [chummer5a/chummer5a#1336]
### Environment
Chummer Version: 5.189.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Change priority works as normal.

### Actual behaviour
When using change priority option in "special" menu the default option for each dropdown menu is selected. This means that adepts only take aeronautics mechanic, magicians only take alchemy and arcana etc. Also after changing priority settings when all magic based skills stopped appearing in the skills menu

### Steps to reproduce the behaviour
Start a new character in sum to ten and then immediately change it's priority settings.

### Link to affected character file
all characters I have tried do this

**Comment by DelnarErsike** [comment]
Fixed in one of the more recent pull requests. The resetting is not entirely removed, but it's largely gone unless you swap between metatypes with different talent restrictions.
