### ISSUE TITLE
If you enable optional drone rules, Chummer will crash on launch, perists even if Chummer is reinstalled

### ISSUE THREAD

**Issue by litehound** [chummer5a/chummer5a#1337]
### Environment
Chummer Version: 5.189.24
Environment: Windows 10 64-bit
Runtime: .NET 4.5.1

### Expected behaviour
Chummer will launch with new settings enabled.

### Actual behaviour
Chummer immediately brings up the crash report tool instead of launching normally.

### Steps to reproduce the behaviour
Enable optional drone rules

### Link to affected character file
Program will not reach character files.

**Comment by chummer5a** [comment]
I can't replicate this in any current builds. The setting for drone mods aren't written to the registry, so there's no reason it should be persisting across completely new installs.

**Comment by litehound** [comment]
Don't know root cause then, but deleting the folder in regedit worked.
