### ISSUE TITLE
Custom Items show as "Custom Item" instead the custom items name, german language version.

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#134]
Not sure if this is a problem with the language version or the programs interaction with it.

When I add and name a custom item, it shows as "custom item" ("Eigener Gegenstand") instead of the name I gave it. 

I switched to the US English language version to look up something for another issue report, and noticed that this actually works in english.

**Comment by chummer5a** [comment]
Somewhere in the code there's a handler for name translations. I need to
hunt it down, but could you provide a copy of the item in question?

**Comment by Haekel** [comment]
Have you done some updates to the language files or the program in the last few hours?  The problem seems to have vanished over night, and I am now questioning my sanity... <ancient-aliens-hair-dude.jpg>

If the .chum5 file has any indications to this issue, it's the same download as in issue #133

**Comment by chummer5a** [comment]
Haven't made any major item changes since 5.188, so.... I dunno. Witchcraft.

**Comment by chummer5a** [comment]
Unable to reproduce.
