### ISSUE TITLE
Special Skills after Change priority

### ISSUE THREAD

**Issue by DBuckLee** [chummer5a/chummer5a#1340]
### Environment
Chummer Version: 5.189.2
Environment: Windows 7, Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Awakened characters and technomancers should be able to see relevant skills, even after priority selection.

### Actual behaviour
When changing any of the priorities after the original character gen, the special attribute-related skills (Mag and Res) are not included on the skills list.

### Steps to reproduce the behaviour
Create character.  Change Priorities.  View skills.

**Comment by chummer5a** [comment]
Known issue with the way we have to manage the skill settings. Hitting Reapply Improvements should sort it out.

**Comment by DBuckLee** [comment]
Thank you!
