### ISSUE TITLE
Improvements tab: Skills

### ISSUE THREAD

**Issue by reyjinn** [chummer5a/chummer5a#1341]
### Environment
Chummer Version: 5.189.0
Environment: WIN10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Toggling the skill improvement Active/Inactive changes the dicepool numbers in the skills tab.

### Actual behaviour
The skill improvement adds to the skill in the skills tab, but toggling Active off has no effect.

Been tried on several different older character sheets as well as a new one created with version 5.189.0.

**Comment by chummer5a** [comment]
Clicking on the attribute will force the skill to refresh. Won't affect the tooltip unfortunately, but it will force the rating label to update. Will have to look into how to force a call to refresh the skills without resorting to calling UpdateCharacterInfo again.
