### ISSUE TITLE
Drone moding - mod points don't work with some attributes modifications

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1342]
### Environment
Chummer Version: 5.189.35
Environment: win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding a drone modification with mod points option should count the mod points and modify drone stats.

Adding a +3 Speed (drone) modification should cost 2 mod points and adding 3 to the drone speed attribute (if drone base speed is 3+)

### Actual behaviour
Adding a +3 Speed (Drone) Modification cost 0 mod points and don't modify drone speed attribute.

### Steps to reproduce the behaviour
(drone mod points options must be activated)

Add a drone, for exemple a nissan roto-drone.
Add a level 3 "Speed (drone)" modification to this drone.

Check drone "Mod Slots" count and drone "Speed" attribute.

**Comment by chummer5a** [comment]
Drone Modification rules are for the Total Attribute. Since the modified rating is lower than your base rating, the Speed doesn't drop. In most cases, the minimum rating is expected to be the Speed + 1, but it's not refreshing for some reason. I'll look into it.
