### ISSUE TITLE
Things in cyberarms/legs.

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1346]
### Environment
Chummer Version: 5.189.35
Environment: Win 10
Runtime: probably .NET 4.5.1)

### Expected behaviour
To be able to put things like a cyberdeck (and other headgear) in my cyberarm.

### Actual behaviour
I can't, If it's possible I haven't figured it out. 

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
You have to add the Cyberdeck headware, then add the cyberdeck as gear to that cyberdeck cyberware. If you can't do that, you may have to hit Reapply Improvements to force the character to reload the gear from the template.

**Comment by drakir75** [comment]
Was able to do it on a new character. Then the option for headware in limbs
is there. Not so when I load an old character. Then the option for headware
is simply not there. Guess I can recreate him.

Thanks for the help.

**Comment by chummer5a** [comment]
Removing and re-adding the gear will work, you don't need to recreate the character entirely.
