### ISSUE TITLE
Text-Only Printout not displaying locations

### ISSUE THREAD

**Issue by dluxcru** [chummer5a/chummer5a#1347]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.189.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Text-Only Printout not displaying locations

### Actual behaviour
Text-Only printout not dipslaying locations, though still displaying associated gear
### Steps to reproduce the behaviour
Add locations with gear and run a text-only printout.

### Link to affected character file
(Enter text here)

Semi-related - you may have observed my dissatisfaction with the print features. If I wanted to add some where would I find that in the code?

**Comment by chummer5a** [comment]
There's not much real code attached to the sheets themselves. Each property type has an associated Print method, which provides the formatted data the sheets use. Name, skills, etc. 

From there,  we call the sheets in the \sheets folder. Each .XSL file is its own sheet, though some of them also call the .XSLT templates. XSL itself is essentially just a HTML wrapper for XML. If you save a sheet as HTML and view the source side-by-side with the XSL sheet, you should be able to follow along with what it' doing.

**Comment by dluxcru** [comment]
Got it. I've started work on Markdown-based version of text-only (since that's what I want). What's with the XSL for loops on derived attributes in text-only? If they aren't needed for some reason then I'd take them off. 

Might be a while before I finish the Markdown version cause I have other things to deal with given my college classes, but I hope some people find it helpful.

**Comment by chummer5a** [comment]
Looks like that's for the minimum line spacing. If you look at the template, you'll see that it adds text with the unicode `&#160;`, which is a space. So it loops through the given number until it reaches the limit, adding a space to that line each time. 

Atrocious naming convention but it's descriptive enough for internal use I suppose.

**Comment by dluxcru** [comment]
So it's making sure each line is the same length? Sounds like I can remove that and it will make the code easier to read.

**Comment by chummer5a** [comment]
Not exactly; see how the Hong-Kong skill is wider than the other text, but all the other dicepool values start earlier? That's what it's doing. if you're doing a markdown version of it you'll be using tables to manage it anyway, so there's no real need for it, but the actual text-only sheet needs it for readability.
![image](https://cloud.githubusercontent.com/assets/11448441/22046678/662658b6-dd76-11e6-950f-00690d9ecb31.png)

**Comment by dluxcru** [comment]
Okay, that makes some sense, and clarifies that I can take that bit out. I'll also have to work on customizing the other templates as well, but that may be a battle for another day.

**Comment by Lochabar** [comment]
I've been working on a major change to the character viewer formats. Including:
1) Being able to use a common XSLT for every format, with the text automatically translated, invoked by the individual language formats.
2) Simplified the table definitions, removed unnecessary code.
3) Added a number of XSLT members by removing code from multiple formats.
4) Created new formats, such as a Calendar print, to allow certain sections to be removed from the main print - created a separate "Core" format that excludes notes, expenses, background, etc. in a smaller, cleaner design.
5) Reordered sections of the code, making a more logical print format, e.g. moved the calendar as the second block in the format to near the end.

I'm assuming that these format changes will be acceptable to the Chummer5a population, If so I will need some help.
1) I've reached a point where I tested the various formats with characters I currently have - I downloaded a few from the Issues list. But I could use a few more, both in create and career modes, e.g. Street Sam, AI, Aspected Magician, and various races, especially metasapients
2) I have modified the German formats, however I need the translations verifying (my school German was a long time ago, but Google Translate helped).
3) I have not yet attempted to translate code to French, Google Translate will take a heavy hit.
4) As far as Japanese translations are concerned, I'm afraid to even try.

Finally, if anyone wants to try the modified versions I will upload a zip file with instructions and the code.

**Comment by chummer5a** [comment]
@joha4270 has a cluster of test characters, I'm not sure how valid they are with existing templates. This one makes for a useful template, has lots of notes and such. Most of the notes text is in French though. 
[campagne hk - Tseung Ni Na.zip](https://github.com/chummer5a/chummer5a/files/713093/campagne.hk.-.Tseung.Ni.Na.zip)

**Comment by Tom-0169** [comment]
@Lochabar 
I would help out with the german translation work.

**Comment by Lochabar** [comment]
Can this issue be closed?

**Comment by chummer5a** [comment]
Looks to be working properly to me.
