### ISSUE TITLE
Build instructions / prerequisites

### ISSUE THREAD

**Issue by milgner** [chummer5a/chummer5a#1348]
I encountered many crashes while trying to build my character and wanted to do some debugging. But since my VS2015 subscription license has run out, I don't have access to a current Visual Studio. What exactly is required to build Chummer? Is it possible with VS Code and the .NET SDK?

Some kind of build instruction would really facilitate getting developers creating pull requests. (Disclaimer: I have no prior experience with C# but have worked professionally with both C++ and Java in the past)

Also, is there some kind of developer forum / mailing list / chat, to get in touch?

**Comment by chummer5a** [comment]
Oh right, I keep forgetting to make a contributing.md file. Chummer's codebase is exclusively C# .Net and XML, targeted to .Net 4.5.1. I'm personally using Visual Studio 2015 Community edition, but there's no reason VS Code shouldn't work. 

As far as build requirements go, you'll need to make sure your local project automatically builds T4 templates, but if you run into any trouble with that I can just forward you a copy; it builds a contributor list from git commits, but it isn't actually used anywhere in the project yet. 

The dev team uses [Slack ](https://chummer-slackin.herokuapp.com)to keep in touch mostly.
