### ISSUE TITLE
Enhancement: Commlink/cyberdeck property enhancements, PAN management

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#1349]
- [ ] Commlinks should only contribute to VR initiative if  they have a sim module, with differentiation based on presence of sim/hotsim. 
- [ ] Existing references to 'Active Commlink' should be changed to 'Commlink/Cyberdeck/RCC'. Switch text based on category?
- [ ]  Provide a defence pool tooltip for other devices using the commlink's attributes.
- [ ] Provide functionality for managing the user's PAN. Would ideally tie in to #633.

**Comment by prismatic-mind** [comment]
May be we should put commlinks in a dedicated tab ? (like vehicules, weapons etc.)
