### ISSUE TITLE
Adept power: Commanding Voice

### ISSUE THREAD

**Issue by Cthullik** [chummer5a/chummer5a#1350]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version:5.189.0
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
There are 2 different abilities named "Commanding Voice", the ability from Street Grimoire is not given.

### Actual behaviour
Only the ability from Stolen Souls is in list.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by bodison** [comment]
There are errata for street grimoire. "Commanding Voice" from Stolen Souls stands, "Commanding Voice from SG is renamed "Authoritative Tone".

**Comment by chummer5a** [comment]
Yup. Not a chummer issue.
