### ISSUE TITLE
[Update BUG] Crash when clic on Add Power Button (adept tab)

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1351]
### Environment
Chummer Version: 5.189.47
Environment: win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Clic on "Add Power" button in the adept tab result in a crash

### Steps to reproduce the behaviour
Create a new character
Add Adept Quality
Go to Adept powers tab
Clic on "Add Power" button

This occur on a updated version from 35 (not sure) to 45 and then 47.

**Comment by chummer5a** [comment]
Can't replicate it. In the crash handler window you should see a blue link; can you paste the contents of the exception.txt in the folder that opens when you click it?

**Comment by prismatic-mind** [comment]
I did overwrite my chummer folder with new release, i've no longer the issue, i'll try to reinstall an old release and then update to try to replicate, but if you don't i'll probably won't be able to replicate.
I can tell some new files from latest release were not added trough the update process.
