### ISSUE TITLE
'Body Sculpt' adept power not adding a +2 mod bonus to disguise

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#1352]
### Environment
Chummer Version:  5.189.0
Environment: Windows 10

### Expected behaviour
The adept power 'Body Sculp' should add +2 disguise to characters as a mod. This +2 mod should fully stack with the mod from 'Facial Sculpt'. https://i.imgur.com/p1zhtPF.png

### Actual behaviour
There is no +2 mod for having the 'Body Sculpt' power.

### Steps to reproduce the behaviour
Add 'Body Sculpt' to an adept character. Observe that there is no +2 mod.

**Comment by chummer5a** [comment]
It's an activated power. Chummer currently doesn't display bonuses for things that have to be turned on.
