### ISSUE TITLE
Life modules not showing when clicked

### ISSUE THREAD

**Issue by desiani** [chummer5a/chummer5a#1355]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 1.90
Environment: (Operating system here. If it persists over multiple OS's list them all) 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
(Enter text here)
when i click the life module ticker the life modules supposed to show
### Actual behaviour
(Enter text here)
Life module button not showing up
### Steps to reproduce the behaviour
(Enter text here)
DL fresh zip, unpack, Run, Click all supplements and Use Life modules Button, Restart the program using the prompt, Run, New char No Life module button is shown
### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
And the character was created with the Life Module creation option?
![image](https://cloud.githubusercontent.com/assets/11448441/22181470/6cd1439c-e0e1-11e6-87e6-a11bd256d0a7.png)

**Comment by desiani** [comment]
I am having the issue when selecting a life module that has a This or That
selection. For example, Community college Magic has Magic theory OR
Metaplanes... Chummer doesn't let you pick one.  Is this intentional or is
there a way to pick and I am just missing it?

**Comment by chummer5a** [comment]
Life modules are currently in beta, which is why they're not enabled by default. You should find that you've received 5 extra free knowledge skill points from taking that option.

**Comment by desiani** [comment]
Ok. Thank you for the help :D I'll try to fiddle around with it a bit and
post if night have anymore questions/problems
