### ISSUE TITLE
Limit modifiers without source can't be deleted. Limits show up multiple times on char-sheet.

### ISSUE THREAD

**Issue by claptraptam** [chummer5a/chummer5a#1356]
### Environment
Chummer Version: 5.189.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
1) Show Limits only once on character sheet (printed PDF). 
2) Delete Limits without apparent source.

### Actual behaviour
Limits (+1 sight) of an Ork shows up 5 Times instead of 1 time.
Limits without origin cannot be deleted, because the source is not given.

### Steps to reproduce the behaviour
create a new Character (Ork). 

### Link to affected character file
https://drive.google.com/open?id=0BzqkX_cg71XfUzFXTTQ5ZDBJUlU

**Comment by chummer5a** [comment]
[Luciano_Panucci.zip](https://github.com/chummer5a/chummer5a/files/723438/Luciano_Panucci.zip)

Well, I can't figure out what caused the problem, but I've removed the improvements from the file. Something to do with removing cyberware during creation might have descynced the improvement removal, I guess?
