### ISSUE TITLE
Unable to load characters in latest Nightly.

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1359]
I downloaded the most recent Nightly (5.189.54) and when I attempt to load a character I get the following error message:

This save file was created in a later version of Chummer (5.190.0) than your current version of Chummer (5.189.54).
This file may not load properly, and it is strongly suggested you update to the latest version of Chummer.

It is confusing because I'm pretty sure the latest Nightly was uploaded 17 hours ago and 5.190.0 was uploaded 2 days ago. I 100% sure it's because of the 189 in the Nightly file name.

**Comment by chummer5a** [comment]
Ack. Sorry about that, sometimes the build server resets the naming convention. I've pushed an updated build request, should come through in a couple of minutes.
