### ISSUE TITLE
Add condition monitor boxes for all devices

### ISSUE THREAD

**Issue by BodieSullivan** [chummer5a/chummer5a#136]
It would be nice to have condition monitors for all devices, especially guns.

**Comment by chummer5a** [comment]
Devices need condition monitors?

**Comment by cjrt** [comment]
You can hack a gun and do matrix damage to it. When you fill it's monitor
it stops working. Same for all devices. I believe that's what's he's
referencing. I think they have (Device Rating) boxes?

**Comment by BodieSullivan** [comment]
Yes that is exactly what I am referencing. You can actually do matrix damage to any device like a gun, cyberware, or cyberdecks/commlinks. I don't know if all devices actually need a condition monitor but at least a calculated value. The most important ones are guns and cyberdecks... Those take damage pretty often when combating deckers and technomancers.

**Comment by chummer5a** [comment]
Matrix Condition Monitor enabled for Weapons, Drones, Vehicles and Cyberware. Cyberdecks and commlinks already have their condition monitor exposed to the print methods, but I'll need to do a bit more tweaking to make it show up in the application. Anyway, 90% complete as of 5.177.
