### ISSUE TITLE
Chummer crashes upon launch

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#1362]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.19
Environment: Windows Vista
Runtime: Don't know

### Expected behaviour
To open as normal.

### Actual behaviour
It immediately opens a crash window with this in it: http://i.imgur.com/nbr2CSZ.jpg

Then it says chummer has stopped responding, then it says it can't solve the problem, then it closes.

### Steps to reproduce the behaviour
I just open chummer and this is what happens.

**Comment by chummer5a** [comment]
Well, that's an intriguingly unique crash. Try downloading and updating manually, maybe?

**Comment by Verecoth** [comment]
Nope, new install does the same thing.

**Comment by Verecoth** [comment]
Updating to the newest nightly build seems to have fixed the problem.
