### ISSUE TITLE
Contacts & Enemies cost wrong

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#137]
Contacts cost 2 karma per level Con/Loy and you gain 2 karma per level for enemies. Should be 1?
In priority the Contacts cost is correct but enemies wrong. In Karma buy both are incorrect.
Was right in 5.158 but in 5.159.1 it's wrong.

Minor issue: Why is it called BP when it's karma? (The 25 karma + qualities karma for a priority character at the bottom) 

Thanks for a wonderful character Creation Help.
 /drakir75

**Comment by BodieSullivan** [comment]
There is an option that sets the contact karma cost multiplier. If you change it to one, then it will only cost 1 karma per level of con or loyalty. I am not sure if the default for that setting changed between the two versions you described or not.

You can find the option under: Tools > Options > Karma Costs

**Comment by drakir75** [comment]
Thank you, The default cost had been changed. Default cost for a skill Group also changed to 10 from 5. Wonder why? Sounds like old 4e costs.

**Comment by chummer5a** [comment]
Accidental revert from old values. Patched in 5.160.
