### ISSUE TITLE
Lifestyle bug

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1375]
### Environment
Chummer Version: 5.190.24
Environment: win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Lifestyles are not working properly.
 - Roommates number are not recorded.
 - LP are not correctly counted
 - Name is not recorded (replaced by lifestyle type)

### Steps to reproduce the behaviour
Add a custom lifestyle
Add some options
add some rommates
Confirm
Check lifestyle or edit and confirm.
Problem occurs

**Comment by chummer5a** [comment]
I can't replicate any of that behaviour with advanced lifestyles; I found a couple of the problems with basic ones. If you're still experiencing this issue, please provide a bit more detail and an affected character file.
