### ISSUE TITLE
Cannot add weapon accessories

### ISSUE THREAD

**Issue by lostdave0** [chummer5a/chummer5a#1377]
### Environment
Chummer Version: >=5.190.17
Environment: Win10 x64
Runtime: .NET 4.6.2

### Expected behaviour
Right click Weapon > Add Accessory or (with weapon selected) Add Accessory from drop-down opens "Select a Weapon Accessory" menu
Working as expected <= 190.9

### Actual behaviour
Opens "You must first select a Weapon...." dialog, as if from drop-down with no weapon selected.

### Steps to reproduce the behaviour
As described with any build >=190.17.

Builds 11-16 untested due to Mugshot/Options crash bugs.

### Link to affected character file
All characters tested

**Comment by DelnarErsike** [comment]
Unable to reproduce as of latest Nightly.

**Comment by chummer5a** [comment]
You should only see that message if the selected treenode is null, or you're on the root level of the treenode, but in either of those cases the contextmenu isn't visible. I'd suggest it's something specific to your environment; have you tested the current build, 190.23?

**Comment by MerGatto** [comment]
Created a pull request that adresses this issue, chummer was checking for the wrong treenode
