### ISSUE TITLE
Lifestyle Crash

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1378]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.25
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Add Lifestyle
Choose any Lifestyle
Click add
Lifestyle is added

### Actual behaviour
Add Lifestyle
Choose any Lifestyle
Click add
Chummer5a crashes

### Details
Crash followup id = 1e8e3cb3-3231-47f9-acb3-509d48fedf23
Input string was not in a correct format.

http://puu.sh/tFPsf/8695a87b32.png

**Comment by DelnarErsike** [comment]
Fixed in latest build.
