### ISSUE TITLE
Point Buy: Adding a Martial Art costs 7500 Nuyen, in addition to the karma.

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#138]
Spamming you with another one. Just trying to help here, bear with me! :P 

Okay, added a Martial Art to my char, noticed my nuyen went into the negative.  Did the math, it costs 7500 nuyen (in addition to the 7 Karma) to learn a Martial Art, which, according to Run and Gun, is the cost of learning a Martial Art + 4 extra techniques AFTER creation. What did I do wrong this time? ;)

**Comment by chummer5a** [comment]
That would be me being an idiot and assuming that Instruction Cost meant that was just what it cost for you to acquire a martial art. I'll pull it out in the next version.

**Comment by Haekel** [comment]
Thumbs up, mate. Thanks for your work.  My gaming group apprechiates it!

**Comment by chummer5a** [comment]
Resolved in 5.160.
