### ISSUE TITLE
Mutants are unavailable in Create Critter

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1380]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190
Environment: Windows 8
Runtime: .NET 4.5.1

### Expected behaviour
Create Critter should have a section in the "Select Metatype" section of critters for Mutant and Toxic Critters.

### Actual behaviour
These options are missing, and are unable to be accessed or made use of.  They do not exist in Paranormal Critters either.

### Steps to reproduce the behavior
![image](https://cloud.githubusercontent.com/assets/2096384/22410393/654540f4-e64c-11e6-8111-a36be4f0e02a.png)

**Comment by chummer5a** [comment]
The categories are only populated if there are critters that exist with your rulebook selections. Since all the toxic and mutant critters are still locked to Running Wild (RW book code), the category isn't available. I didn't think there were any rules for making them in Howling Shadows or anything, did I miss a book?

**Comment by Reshy** [comment]
![image](https://cloud.githubusercontent.com/assets/2096384/22410500/e8bc8ea0-e64d-11e6-80fc-4c8e85f3fb0b.png)


Howling Shadows possesses an entire section on Mutant and Toxic critters.

Also side note, there's no way to add Chimeric or Warform to critters.

**Comment by chummer5a** [comment]
Oh, bleah. Easy fix, but will need a bunch of data entry to complete. Chimerics and warforms will need some new code support.

**Comment by Maxis010** [comment]
I'm going through Howling Shadows and proofing critters.xml right now as per request on the Shadowrun General (4chan)
I'll get a pull request up ASAP

**Comment by chummer5a** [comment]
Cool beans; you can use the Chummer Text-Block Converter exe in Utils to auto-convert entries. It'll need some basic proof-reading to make sure everything matches up, but it'll save a lot of tedious typing.

**Comment by cnschu** [comment]
Reshy, you are not forgotten

**Comment by chummer5a** [comment]
I think this is completed?
