### ISSUE TITLE
Essence loss for Cyber and Bioware is off

### ISSUE THREAD

**Issue by MerGatto** [chummer5a/chummer5a#1382]
### Environment
Chummer Version: 5.190.27
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
The essence loss should be calculated and displayed correctly for cyber and bioware

### Actual behaviour
The essence loss gets calculated wrong for cyber and bioware

### Steps to reproduce the behaviour
 - Create a new charakter
 - Add any Cyberware, for example Image Link
 - Essence loss should be 0.1 but shows 1

Tested with every version since 5.190.25 until now (5.190.32)
Bug first appeared in 5.190.27 (5.190.25 was working properly)

![image](https://cloud.githubusercontent.com/assets/2557018/22422980/c0d5bd92-e6ef-11e6-99da-67a9fefdcbc8.png)

[essencelosstest.zip](https://github.com/chummer5a/chummer5a/files/738878/essencelosstest.zip)

**Comment by chummer5a** [comment]
I can't replicate this in my build. I have a suspicion though: what's your computer's region set to? We removed some culture references that could be causing that behaviour, and it looks like your Essence loss is recorded with commas for the decimals there.

**Comment by MerGatto** [comment]
My region is set to german. Setting my region to English(US) "fixed" the issue

**Comment by DelnarErsike** [comment]
Could you give it a shot with the newest Nightly? I made some changes that may have fixed the issue, but I don't have the proper setup to test it.
