### ISSUE TITLE
Not able to buy Regular Job 

### ISSUE THREAD

**Issue by Kadrack** [chummer5a/chummer5a#1385]
### Environment
Chummer Version: 5.190.34
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Regular Job Life Module should be buy

### Actual behaviour
Cannot buy the Regular Job Life Module.  when you try to buy it, Nothing append

### Steps to reproduce the behaviour
I've spend the karma following the steps below :
Adept Mystic
Consil Salish Shidhe
Fugitive
Isolated Rural Upbringing
Magic from Community College
Regular Job (not working)

### Link to affected character file
[Regular Job Missing.zip](https://github.com/chummer5a/chummer5a/files/740247/Regular.Job.Missing.zip)

**Comment by Kadrack** [comment]
After some investigations, this module can be buy if the comment "" is not present.

**Comment by chummer5a** [comment]
This is accidentally intentional, since there's currently no code support for providing free active skill points in the life module point buy. It'll get fixed properly when we do the refactor, but I don't have an ETA on that as yet.
