### ISSUE TITLE
Will Not Allow Option Change In Windows 7

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1391]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.45
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Set options to desired settings. Click "Yes" to each pop up window and watch it restart aplication.

### Actual behaviour
Set options to desired settings. Click "Yes" to each pop up window and watch it send up a crash warning.

### Steps to reproduce the behaviour
1) Download 5.190.45. 2) Unzip to desired folder. 3) Open options menu and set to desired settings. 4) Click "OK" and then click "Yes" to each pop up window that appears. 5) At this point it will bring up a crash warning.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate it. What's the crash error?

**Comment by Pommanthebrit** [comment]
there is no crash it just forgets the locations of the books and thus i cant use the source function to go to the rules in the books from chummer
