### ISSUE TITLE
No free Points for Conntacts and Knowledge Skills in Point Buy

### ISSUE THREAD

**Issue by HKSarge** [chummer5a/chummer5a#1393]
First off all thanks for the awesome char-generator

There is no calculation for the actual free points for connections and knowledge skill.
especially the german rulebook points out that these are still available when using "point buy" character generation. I even tried the houserule option.

### Environment
Chummer Version: 5a 5.190.0
Environment: Windows 7
Runtime:  .NET 4.5.1)

**Comment by chummer5a** [comment]
Update to current nightly builds, Run Faster's errata that clarifies this was implemented earlier this week.
