### ISSUE TITLE
Throwing Syringe Exotic Ranged Weapon Skill missing

### ISSUE THREAD

**Issue by khokkanen** [chummer5a/chummer5a#1395]
### Environment
Chummer Version: 5.190.48
Environment: Windows 10
Runtime: .NET 4.6.1

### Expected behaviour
Choose Throwing Syringes from Exotic Ranged Weapons list when adding Exotic Weapon Skill.

### Actual behaviour
No entry for Throwing Syringes on the list.

### Steps to reproduce the behaviour
Check the list.

### Link to affected character file
Irrelevant.

**Comment by DelnarErsike** [comment]
Does the program still recognize the Throwing Syringe Exotic Ranged Weapon Skill if you type "Throwing Syringe" into the Exotic Ranged Weapon Skill field?

**Comment by khokkanen** [comment]
I actually solved this but my git on my Windows needs some reconfiguring and I can't make a pull request. The problem is that Chummer/data/weapons.xml has <useskill>-rows with extra s in Exotic Ranged Weapon Skill. It affects throwing syringes and several Ares laser weapons. Removing the s makes autopopulation of the Exotic Ranged Weapon Skill list work, and presumably links the weapon to the said skill.

**Comment by khokkanen** [comment]
useskill-xml tag rows, that is.
