### ISSUE TITLE
Accessories counting as Weapon's availability, interfering with Restricted Gear

### ISSUE THREAD

**Issue by BitterLies** [chummer5a/chummer5a#1396]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190
Environment: Win 10
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Purchasing Accessories has their own Availability Validation, with the exception of Internal Smartlinks, which increases the Item's availability by +2R.  Restricted Gear allows one item with a Max Availability of 24.  Purchasing an Availability 18F Weapon, then adding accessories under the Cap (In this case 15 for Prime Runner) should pass validation, as only the weapon (even after internal smartlink) is over Availability 15.

### Actual behaviour
All accessories count as individual items at the Availability of the weapon they're attached to.  Checking Validation lists a number of errors (Each with the weapon's name, not the accessory) as over Availability Limit.  Restricted Gear ignores one instance of this Error.  (For example, buying an FN-MAG 5 [Availability 18F], then adding a Bayonet, Gas Vent 3, Hip Pad Bracing System, Gyro Mount, Smartgun System Internal, Melee Hardening, Personalized Grip, and Improved Rangefinder gives a total of 8 Errors with Restricted Gear, and 9 Errors without.)

### Steps to reproduce the behaviour
Buy a weapon above availability maximum, add accessories, validate.

### Link to affected character file
Can send if need be.

**Comment by chummer5a** [comment]
Fixed in 5.191.1, I'd suggest downloading the latest release from the releases page (http://get.chummer.net, select the first Chummer.Nightly.zip file) and overwriting your existing Chummer install.
