### ISSUE TITLE
Re-apply Improvements lowers Attributes with Metagenic Improvement - Career Mode

### ISSUE THREAD

**Issue by whistlermadre** [chummer5a/chummer5a#1399]
### Environment
Chummer Version:  5.190.52
Environment: Win7 Home Premium, Win 10 Home
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
As per normal.

### Actual behaviour
With Metagenic Improvement and (possible) either Exceptional Attribute and/or Genetic Optimization, when using this function, and selecting the proper attributes from the dropdown, the (Aug) line goes down by 1 for the affected stats.

### Steps to reproduce the behaviour
I tried two changeling characters with Metagenic Improvement in this verson on two different OSes with the same results.

### Link to affected character file
Will upload somewhere if needed.

**Comment by whistlermadre** [comment]
This could be due to Genetic Optimization Geneware rather than Metagenic Improvement, by the way.  In the same file where this happens, if I choose Re-apply again, and subsequently pick two different attributes for metagenic improvement and the same ones for Genetic Optimization, the stats originally picked during Create Mode still each go down by 1.

**Comment by whistlermadre** [comment]
I made a test character just now in version 190.56, and this issue persists with Metagenetic Improvement.  It appears to be removing the point from the attribute(s) they were originally assigned to and then failing to add them to the 'current' rating, but they are being applied to the 'maximum' value rating.  

I've attached the file for ease of reference.  Let me know if you need anything else about this.


[Uploading test.zip…]()

**Comment by chummer5a** [comment]
Makes sense, attributes don't behave quite the same once you're in career mode. The new attribute system should manage this in a more logical manner (Value becomes TotalMinimum + Free + Karma instead of its own discrete value), but that's all bound up in an attempt to make shapeshifters work at present.

**Comment by chummer5a** [comment]
This should be resolved in current nightly builds; can you please test and let me know if it's still broken?
