### ISSUE TITLE
Adding a martial art crashes chummer. 

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1400]
Adding a martial art to a character crashes chummer. Both in career and create modes. Clicking on a martial art on an existing character with one also crashes chummer.

### Environment
Chummer Version: Nightly-v5.190.52
Environment: W10
Runtime: probably .NET 4.5.1

### Expected behaviour
not crashing

**Comment by Rinnolk** [comment]
Still happening with One Trick Pony :v

**Comment by Rinnolk** [comment]
Nightly-v5.190.59

Still happening :v 

https://drive.google.com/open?id=0B71WLpuGA0X4QlZuNVhFaTJsRFk

Char files for both create and career modes

**Comment by chummer5a** [comment]
Sorry about that, not sure how I missed that. Should be fixed in the next build.
