### ISSUE TITLE
Add Additional Lifestyle - Additional cost could be percentage or fixed

### ISSUE THREAD

**Issue by michaeljesse73** [chummer5a/chummer5a#1402]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 8.8.20
Environment: Win7
Runtime:

### Expected behaviour
There is already an option to use Percentage increase, but there is one scenario we have where it would be better to have a fixed cost.

### Actual behaviour
The percentage works as expected so we are using that right now.

### Steps to reproduce the behaviour
Change Percentage from 100% to 108%.  But would like to have a Textbox for the amount and a dropdown that controls Addition versus Multiplier.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Why not just make a custom lifestyle quality using the [Custom Data Files](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files) capability?

**Comment by prismatic-mind** [comment]
Add a fix amount field would be nice, and it could be a solution for the "Run Faster" p.140 rule :
"I RAN OUT OF POINTS, BUT WANT MORE STUFF"

**Comment by DelnarErsike** [comment]
Closing this issue as it can be fully implemented by using a Custom Data Directory and custom data files. Add custom lifestyle qualities that have a flat cost (ones added to the "Contracts" section will ignore other lifestyle multipliers, negative values for costs also work if you want to reduce lifestyle cost by a flat amount), plus whatever effects you want to associate with that flat cost adjustment.
