### ISSUE TITLE
Exotic Ranged Weapons

### ISSUE THREAD

**Issue by DBuckLee** [chummer5a/chummer5a#1405]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.190.3
Environment:  Windows 10

### Expected behaviour
Printing when Exotic ranged weapons are added to the character

### Actual behaviour
When there is an exotic ranged weapon the characters are not able to be printed.  An error is produced and chummer crashes when I click on "print"

### Steps to reproduce the behaviour
Add exotic ranged weapon to character and click print.

**Comment by chummer5a** [comment]
Assuming that this is related to your previous issue, this should be resolved. I was unable to replicate it though. If you still experience this problem, please let us know and provide a copy of your character to try and replicate it with.
