### ISSUE TITLE
PDF "Print"

### ISSUE THREAD

**Issue by DBuckLee** [chummer5a/chummer5a#1406]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.3
Environment: Windows 7

### Expected behaviour
Printing full character sheet

### Actual behaviour
When saving as a pdf using print -> save as pdf, the character sheet does not print in its entirety.  When opened the pdf creates an error that reads "An error exists on this page.  Acrobat may  not display the page correctly.  Please contact the person who created the PDF document to correct the problem."

### Steps to reproduce the behaviour
Print -> save as PDF -> open created PDF

**Comment by chummer5a** [comment]
Egh, this is why I didn't want to integrate that stuff. Does it work if you print it to cutepdf or something? Can you upload the character so that I can test it?

**Comment by chummer5a** [comment]
Should be fixed in current nightlies.

**Comment by DBuckLee** [comment]
Thank you

On Tue, Feb 7, 2017 at 9:14 AM, Chummer 5 Is Alive <notifications@github.com
