### ISSUE TITLE
Chummer crashes when trying to add "Pirate Captain" Real Life life module.

### ISSUE THREAD

**Issue by SpellBinder-883** [chummer5a/chummer5a#1407]
### Environment
Crash ID: fa6dfe7c-9812-4538-8f05-41dead5dfc74
Chummer Version: 5.190.0
Environment: Windows 8.1 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
Able to choose life module without crashing.

### Actual behaviour
Chummer5 crashes whenever this module is chosen, an "Exception has been thrown by the target of an invocation."

### Steps to reproduce the behaviour
Simply adding the module causes this to happen at any time.

### Steps to correct the behaviour
The life module is calling upon a quality that doesn't exist.  Pirate Captain is trying to apply "Fame (Local)", but the actual quality is "Fame: Local".  Changing the life module resolves the issue.

**Comment by Thanael0** [comment]
Cool! Solution already provided.

**Comment by chummer5a** [comment]
Was already fixed in #1358, actually. Current nightlies will have it, stable update won't be for another week or so.

**Comment by SpellBinder-883** [comment]
Right, so I didn't look back for this one.
