### ISSUE TITLE
Critters CM does not match rulebooks

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1410]
### Environment
Chummer Version: 5.190.0
Environment: Windows 10 Pro
Runtime: .NET 4.5.1

### Expected behaviour
Critter CM matches rulebook

### Actual behaviour
Critter CM is auto-calculated based on character rules

### Steps to reproduce the behaviour
File->New Critter
Paranormal Critters
Fenrir Wolf
Compare CM from Rulebook to Chummer
Chummer: 12/11
HS: 2/11

Recommend check for overriding entry in critters.xml then fall back to auto-calc

**Comment by chummer5a** [comment]
Honestly in the absence of a Fragile quality, I'm tempted to deviate from my raw-only policy and consider that a typo.

**Comment by Maxis010** [comment]
I'm proofing the critters.xml against Howling Shadows right now so I'll see if more entries deviating from standard and get back to you

**Comment by Maxis010** [comment]
I've only found 1 entry besides the Fenrir Wolf that deviates from standard, it's one page earlier and is also off by 10 so going to agree and assume typo
