### ISSUE TITLE
Restricted Gear isn't allowing character to move into career mode with one item over 12 availability

### ISSUE THREAD

**Issue by boongeebee** [chummer5a/chummer5a#1412]
### Environment
Chummer Version: (5.190362)
Environment: (Win 10)
Runtime: (Probably .NET 4.5.1)

### Expected behaviour
After selecting the Restricted Gear quality it would ask which piece of gear it is applying to or something like that.  At least allow one piece of gear over the 12 availability limit to pass through to Career mode.

### Actual behaviour
When I select the quality it is added to my list of qualities but the character is still invalid to move to career mode because of the availability restriction

### Steps to reproduce the behaviour
Select the Restricted Gear quality
Add any piece of gear with an availability over 12
Try to move character to career mode

### Link to affected character file
https://drive.google.com/file/d/0Bw29unDKxWJjbWpvY1FDSDVnd00/view?usp=sharing

**Comment by chummer5a** [comment]
Gauss Ammo is 18F.

**Comment by boongeebee** [comment]
Thanks. I should have dug deeper before I posted an issue.


________________________________
