### ISSUE TITLE
Free does not function in Lifestyles

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1415]
### Environment
Chummer Version: 5.190
Environment: Win 8
Runtime: .NET 4.5.1

### Expected behaviour
When used, no nuyen cost should be applied to the lifestyle.

### Actual behaviour
Cost is added anyway.

### Steps to reproduce the behaviour
Choose a lifestyle option, in this case "Contracts" and choose Free! then OK.

**Comment by chummer5a** [comment]
Fixed in nightlies.
