### ISSUE TITLE
Paint Minigrenades

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1416]
Would it be possible to add this as an ammo type as there isn't an option listed for paint minigrenades in the current list of ammo types.

Thank you.

**Comment by chummer5a** [comment]
There's no paint minigrenade in the rules, and generally speaking I dislike adding custom content to Chummer's data. You could add it as a custom object for yourself using the [Custom Datafiles](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files).
