### ISSUE TITLE
Feature Request:  Free Spells

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1417]
Hello, I was wondering but is it possible that we can get a "Free!" section for spells known?  Currently there's no way to get karma free spells, and afiak according to the rules your ritual metamagic spells shouldn't cost any karma on top of the initiation cost.

**Comment by chummer5a** [comment]
RITUALS (p139, SG)
These rituals are only available for those who have initiated into this particular school of magic. They cost the same amount of Karma and time to learn as other rituals (5 Karma, see p. 299, SR5); no additional initiation grade is needed.

**Comment by prismatic-mind** [comment]
I suggest for "free karma" stuff (not in the rules), we just add karma in the regular way but without forgeting the check box to don't count karma in total carrier karma.
It's made for that :)

I have concerns about add a "free" check box on karma buy.

**Comment by chummer5a** [comment]
Can be done with the freespells custom improvement. Will be in next nightly.
