### ISSUE TITLE
 Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by nw2372** [chummer5a/chummer5a#1419]
### Environment
Crash ID: 7209f89d-0a46-42f4-be39-e357ba3cb4cd
Chummer Version: 5.190.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Character loaded

### Actual behaviour
Crash

### Steps to reproduce the behaviour
Load the selected Character

[Ray Twitchy Vaughn.zip](https://github.com/chummer5a/chummer5a/files/764501/Ray.Twitchy.Vaughn.zip)

Cannot even upload the Crash, since that crashes as well.

**Comment by nw2372** [comment]
I should add, that this character was built and is loadable with the Chummer.Nightly version of 30th of June 2016.

**Comment by chummer5a** [comment]
[Ray Twitchy Vaughn.zip](https://github.com/chummer5a/chummer5a/files/764703/Ray.Twitchy.Vaughn.zip)

Knew that'd bite us in the ass eventually; the character file didn't have a depth attribute stored. Should work now.
