### ISSUE TITLE
Feature Request:  Ability to 'Equip' and 'Unequip' Cyberware without selling it.

### ISSUE THREAD

**Issue by BitterLies** [chummer5a/chummer5a#1427]
It's very possible for a character, over time, to acquire multiple Cyberlimbs, Implants, and Systems that - with an NPC or Party Member - can be swapped in and out.

Modular Cyberware makes it possible right off the bat.

Unfortunately, any cyberware purchased automatically reduces the Essence without the ability to 'store' the Cyberware outside of the body.

Can there be an "Implanted" check box like there is for Armor (Armor has "Equipped") that would allow a Character Sheet to track multiple Cyberlimbs and systems that are owned but not implanted?

Thank you!

**Comment by chummer5a** [comment]
Part of #900; tricky to implement due to the way Essence is managed.

**Comment by BitterLies** [comment]
Is it still planned to be implemented?  My GM is giving me a shite of a time about tracking all my limbs, since he requires us to Validate via Chummer.  I'm also confused on what an "Essence Anti-Hole" is.

**Comment by chummer5a** [comment]
Chummer's development process tends to work in a way similar to House; you try a bunch of stuff that doesn't work, engage in something else for a while, have a Eureka moment and come back to fix it. It will get implemented at some point, I just haven't come up with a clever way to resolve it yet. 

The Essence Anti-Hole cyberware is a work-around for weird stuff like this. Each rating of the object will 'restore' 0.1 Essence.

**Comment by BitterLies** [comment]
Excellent!  Thank yo.

**Comment by chummer5a** [comment]
This has been implemented in current nightly builds. Any modular limbs that are not children of a modular connector will have zero Essence cost, and otherwise have no impact on the user. There are some minor double-ups of the tooltip text to show how modified agility and strength are calculated, but the raw functionality's there. Big thanks to @DelnarErsike for implementing all that.
