### ISSUE TITLE
Critters Knowledge Skills

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1432]
### Environment
Chummer Version: 5.190.0 (w/ modified critters.xml)
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Chummer creates critter as normal

### Actual behaviour
Chummer crashs if critter has a knowledge skill

### Steps to reproduce the behaviour
New Critter
Select either of the following critters
- Paranormal > Sasquatch
- Infected > Bandersnatch

I found this while working on #1413 as the Jabberwock has Knowledge Animal Calls (Professional)
I copied the knowledge skill node from the critters mentioned above
`<knowledge rating="8" category="Professional">Animal Calls</knowledge>`

**Comment by chummer5a** [comment]
Implemented by https://github.com/chummer5a/chummer5a/commit/430791c668dea1f7700538b284daaaf6a2255b61.
