### ISSUE TITLE
Character viewer "Save as ..." not working

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1433]
### Environment
Chummer Version: 5.190.81
Environment: Windows 7 64-bit
Runtime: .NET 4.6.1

### Expected behaviour
To be able to save character from viewer as XML or to a PDF.

### Actual behaviour
Right-click on "Save as HTML" provides the two options:
1) Save as XML - this does nothing
2) Save to PDF - this saves as HTML

**Comment by Lochabar** [comment]
Saving as XML works. However saving as PDF you have to add ".pdf" to the file name, otherwise the default is html, even though the file type box shows pdf.

**Comment by chummer5a** [comment]
I can't replicate that behaviour, seems to work fine on my test boxes.
