### ISSUE TITLE
Cant have Curiosity Killed the Cat quality for unspecified reason

### ISSUE THREAD

**Issue by josh8010** [chummer5a/chummer5a#1435]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.0
Environment:windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
want to enter curiosity killed the cat

### Actual behaviour
says you do not meet the requirements for this quality. you must meet at least one of the following criteria: 
one of:

and thats it. no criteria listed

### Steps to reproduce the behaviour
try adding the negative quality curiosity killed the cat.

### Link to affected character file

[Daemon.chum5.txt](https://github.com/chummer5a/chummer5a/files/774821/Daemon.chum5.txt)

**Comment by TDW89** [comment]
Can't help with getting it to list criteria but if you just want the quality added `Curiosity Killed the Cat` has a minimum hacking skill of 3 requirement. Add three levels in the skill then try taking it and you should be fine.

**Comment by chummer5a** [comment]
Visibility of what's blocking you from taking a quality should be fixed in the latest commits.
