### ISSUE TITLE
Broken skill groups prevent skills from being increased

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#144]
After breaking a skill group and increasing an individual skill, the skill's new value reverts to the value of the skill group. Issue caused by Skillcontrol.cs, line 492 being commented out. Fixed in 5.160.

**Comment by Riadran** [comment]
This bug is still occuring in 161. Just tested with a fresh sheet after restarting, issue reproduces exactly as you've described.

**Comment by chummer5a** [comment]
Ha! I knew I uncommented that for a reason. Okay, this is going to need a proper look. Will investigate tonight.

**Comment by chummer5a** [comment]
Resolved in 5.162.
