### ISSUE TITLE
Bug - Lifestyles problems - Name not recorded after edit

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1441]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.93
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Lifestyle problems.
Name is not recorded after editing a lifestyle -> Lifestyle is used instead of name.

See "Lifestyle bug #1375"

### Steps to reproduce the behaviour
Create a character (i use point mode and my ui is in french)
Create a "advanced lifestyle"
Select "High" lifestyle.
Add a name
Clic OK.
Edit this lifestyle (just open the edit window)
Clic OK
-> The name switch from the name to the lifestyle level.

It seems that problem don't occur with medium lifestyle for exemple but with squatter and high yes (didn't test all).

### Link to affected character file
[test lifestyle.txt](https://github.com/chummer5a/chummer5a/files/781776/test.lifestyle.txt)

**Comment by chummer5a** [comment]
I can't replicate this issue in current builds.

**Comment by prismatic-mind** [comment]
Did you try to exactly reproduce it step by step ?
I just tested on a fresh install and i replicate under la build 5.190.94

**Comment by prismatic-mind** [comment]
Just to be sure, the name of the lifestyle not correctly displayed is the one in the character lifestyle tab list.

**Comment by chummer5a** [comment]
![image](https://cloud.githubusercontent.com/assets/11448441/23061050/689b6c80-f554-11e6-927a-27016f6c59da.png)

**Comment by prismatic-mind** [comment]
I just tested it in english, and i didn't replicate.
Probably a translation problem

**Comment by prismatic-mind** [comment]
![bug lifestyle french](https://cloud.githubusercontent.com/assets/20904428/23061422/15aeae62-f502-11e6-94fa-6f9ec66914c7.png)
