### ISSUE TITLE
Crash upon printing

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1443]
### Environment
Chummer Version: 5.190
Environment: Windows 8
Runtime: .NET 4.5.1

### Expected behaviour
Able to print character sheets.

### Actual behaviour
Crash with this as the error report:
![image](https://cloud.githubusercontent.com/assets/2096384/23055184/4fc9de3c-f499-11e6-8c78-51a8b842f1ff.png)

### Steps to reproduce the behaviour
Pressing print, and sometimes requiring the print HTML command.

### Link to affected character file
https://cdn.discordapp.com/attachments/282032674074525697/282039509317713921/Audrie_2.0.chum5

**Comment by chummer5a** [comment]
Can't replicate the issue with your character, but can you try the latest nightly builds from get.chummer.net?
