### ISSUE TITLE
Simple UI enhancement - add a button to expand or reduce all gear groups 

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1444]
For big lists of gear, a simple buton to expand or reduce all gear groups would e really usefull.

The only way to move a piece of gear to a gear group is to reduce lots of them in order to reach the good one in the bottom in the list, it's quite painfull :)
And it would be easier to read the list / find something.

Tabs : Clothing and Armor, Weapons, Gear, Vehicles & Drones
May be Cyberware and Bioware too

**Comment by prismatic-mind** [comment]
The "ctrl"+"clic" to collapse all treenodes bellow it is nice.

But we need a way to collapse all treenodes on the same level, main exemple are the "gear groups" under the gear tab.

I join a file to show a quite big gear list sorted with some gear groups.
[campagne hk - Tseung Ni Na.txt](https://github.com/chummer5a/chummer5a/files/784002/campagne.hk.-.Tseung.Ni.Na.txt)

**Comment by chummer5a** [comment]
If you collapse the main node with ctrl-click and then expand it again without ctrl-clicking , the nodes below should be collapsed. I guess I could code it to collapse all nodes of the same level if you ctrl-click it?

**Comment by prismatic-mind** [comment]
Yup it would be nice !
reduce sub-nodes is a good idea, but i think we need reduce same level node much more :)
