### ISSUE TITLE
Alchemical preparation spells cannot be learned if you have the regular version

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#145]
In character gen the character cannot gain an alchemical version of a spell they have already added the regular version of.

**Comment by BodieSullivan** [comment]
I was unable to reproduce this issue. I was able to first add a regular spell, then add an alchemical version of it without issue. I tested this on Version 0.5.158.0

![image](https://cloud.githubusercontent.com/assets/5205317/7103276/52a8156e-e065-11e4-8bc0-45228805c258.png)

**Comment by Neocyberman** [comment]
I should have said: Im working with version 1.159.1

**Comment by BodieSullivan** [comment]
Hmm... just tried it on version 5.159.1 and still not able to reproduce. 

Perhaps there is something going on with a particular spell? If you email me the .chum file I can run it through the code and see what is going on.  bodiesullivan [at] gmail.com

![image](https://cloud.githubusercontent.com/assets/5205317/7103364/2689b2c2-e069-11e4-8dfa-7a5bf59c4765.png)

**Comment by chummer5a** [comment]
Tested with all spells currently in Chummer, can't reproduce. The test for
uniqueness with spells is in their name; the Alchemical checkbox appends
the (Alchemical) descriptor. Only way I could think of it causing an issue
would be if a language file contains the key
for String_DescAlchemicalPreparation, but the value is blank.

So, idk. More detail or a reproducible error needed.
