### ISSUE TITLE
Inconsistency in the german book names

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#1452]
### Environment
Chummer Version: 5.190.101
Environment: Windows 10 64 Bit

### Expected behaviour
Consistent names for the books (see actual behavior). In detail: When I switch my language to german, don´t display the english book titles. Only the german ones. Same for every other language.

### Actual behaviour
Books appear multiple times in the settings list. For example:

- "Asphaltkrieger" and "Rigger 5.0 German" appear both in the list. But Rigger 5.0 in german is called "Asphaltkrieger" - so the distinction makes no sense because it´s the same book.
- "Straßengrimmoire (German)" and "Street Grimmoire" have distinct names while "Kreuzfeuer" (German translation) for "Run & Gun") does appear in the german translation without the english name. Same for "Gestohlene Seelen" (German for "Stolen Souls"). "Run faster (German)" Should be named "Schattenläufer" (because that´s the name of the german translation). Also "Hard Targets2 has a german translation: "Harte Ziele"
![chummer_german_books](https://cloud.githubusercontent.com/assets/4673925/23130101/7aa20fb4-f785-11e6-9bc4-b03093bdf38d.png)

- On the other hand "Bodyshop" (which is the book´s name in english and german) only appears once. Not as "Bodyshop (Deutsch)" and "bodyshop". Are the page numbers I get from the activated book the page numbers for the english book or for the german book?

### Steps to reproduce the behaviour
Run Chummer, set language to german, open settings.

**Comment by OLStefan** [comment]
'Bodyshop' is the german Chrome Flesh

I think there is a 4th Edition book with the same name in english, but in this case it is the german Chrome Flesh.

**Comment by chummer5a** [comment]
Those books are for German content that aren't otherwise present in the book, that English users would want to use. Chummer currently doesn't handle differentiation between translated books very well, so a division like that is necessary.

**Comment by Noraser** [comment]
hi chummer5a,
This means for German users, they have allways to check both books? means "Street Grimoire" and "Strassengrimoire" to have all content of the book? Pages are never translated, so they are allways from english original?

Still there is a bug in the De_data.xml.
In Line 1221 the name of the book "Run Faster" is missing the Brakets, thats why it is not translated correctly.
Wrong: `name>Run Faster German</name>`
Correct: `name>Run Faster (German)</name>`
For the translation of "Hard Target" ad to the book sektion:
`                        <book>
				<id>B6642AC0-7E72-44C4-B954-3E224EBB2E64</id>
				<name>Hard Targets</name>
				<translate>Harte Ziele</translate>
			</book>`
then it should lock like the rigth one:
![grafik](https://cloud.githubusercontent.com/assets/25962078/23227468/55cd772c-f939-11e6-812d-05beb78002fd.png)
[de_data.zip](https://github.com/chummer5a/chummer5a/files/794539/de_data.zip)
My modified de_data is attached, if someone like it (goes in the Folder "lang")
Tested with 190.112
hope thats helps
Noraser

**Comment by chummer5a** [comment]
Strictly speaking, if a book has the appropriate altcode set, you should only need to use the book that has that code. The problem is that the translator exe isn't set up to provide that functionality (yet), so you'd have to go into the de_data.xml file and manually add all the codes for it to work.

**Comment by Noraser** [comment]
As I guess, we have some German readers here: I need some help. I translated all Qualitys from Run Faster (Schattenläufer) to German including the page transformation to the german books. 
It would be nice if some people would have a look at the attached screenshoots for any misspelling or wrong Bookpage.
Don't be affraid, as I made screenshoots from the transformer program, you don't need to go to a few thousend code lines ;-)
If you like the work, you can simple exchange the included de_data.xml with yours, found in the 'lang'  Folder. (should be working with all newer Versions)
Thanks to help us all.
Noraser
[Deutsche Übersetzung Vor und Nachteile.zip](https://github.com/chummer5a/chummer5a/files/819632/Deutsche.Ubersetzung.Vor.und.Nachteile.zip)

**Comment by chummer5a** [comment]
Is there anything actionable you guys want from this? I've renamed the German-code books to indicate that they're for content rather than a book itself; if there are other data changes that are needed, I'd prefer to see a pull request.

**Comment by mer0mingian** [comment]
Also a German user, I have tested and would appreciate a pull request for the improved translation file by @Noraser

**Comment by Noraser** [comment]
Hi,
I made allready a pull request:
updated German translation #1523
but it seams to be closed.
Not sure if I did it correct, as I 'm new to this.
As I'm momentary  not in my Home country, would like that somebody else, take the file from teh pull request and create a new pull request.
thanks
Noraser

**Comment by ReallyDarkMatter** [comment]
I would like to comment on a typing mistake in line 16953 the correct Translation of Symbiosis is "Symbiose"
https://de.wikipedia.org/wiki/Symbiose
I hope this is the right way to Point to this error, otherwise please advise.
