### ISSUE TITLE
Power Focus Bonus Applying Twice?

### ISSUE THREAD

**Issue by jtveite** [chummer5a/chummer5a#1453]
### Environment
Chummer Version: 5.190.97.0

Environment: Windows 10
Runtime: Unknown, so probably .NET 4.5.1 (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
My power focus bonus should only apply once to spellcasting/alchemy/etc.

### Actual behaviour
It is applying twice.  http://i.imgur.com/eOW79oS.png

### Steps to reproduce the behaviour
As far as I can tell, just loading the file and going to the skills tab is sufficient. I did try restarting the program and the error persists.

### Link to affected character file
https://drive.google.com/file/d/0B9E1jeg-_RWCWVlFUG1BZHpfR2c/view?usp=sharing

**Comment by chummer5a** [comment]
Somehow you got multiple copies of the focus improvement. Un-equipping the gear item, refreshing your skills by changing the rating and changing them back down should sort it out. I need to redo the logic to manage that, currently it's all conditionals based on the names of the items so it's easy for things to duplicate.
