### ISSUE TITLE
Adept Power Weirdness

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1454]
### Environment
Chummer Version: Nightly-v5.190.101
Environment: Windows 8

### Expected behaviour
Attempting to assign Adept powers has caused two weird bugs to occur.  One is an adept way power being discounted into the negatives on Wall Walk.  The other is that when adding Improved Ability on a fresh (not bugged) sheet, Sneaking among other skills are not available despite possessing enough sneaking skill for the ability.

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2096384/23147847/fbde1c2e-f796-11e6-984d-5363c84380a1.png)
![image](https://cloud.githubusercontent.com/assets/2096384/23147820/c6bfa67a-f796-11e6-9078-ceef470fe4fb.png)

### Steps to reproduce the behaviour
House Rule Settings
![image](https://cloud.githubusercontent.com/assets/2096384/23147912/734cc47c-f797-11e6-8ba8-31a4b749ce9e.png)
All books enabled.

### Link to affected character file
http://www.mediafire.com/file/byueca03hd5curw/Infiltrator_Adept%281%29.chum5
http://www.mediafire.com/file/vfbhk0nci3s7d9t/Adept_Test.chum5

**Comment by chummer5a** [comment]
Adept powers are currently a mess, especially once qi foci and mentor spirit bonuses get involved. I've mostly fixed them in the DataboundPowers branch, but I haven't had time to create a shim to convert existing characters over into it yet. Once that's done this should all clear up.

**Comment by OLStefan** [comment]
That should be fixed in the latest Nightly and report if it still occurres or not.
