### ISSUE TITLE
Translator\frmMain.Designer.cs is missing

### ISSUE THREAD

**Issue by MrToboter** [chummer5a/chummer5a#1458]
### Environment
Chummer Version: Current
Environment:  WIn 10
Runtime: .NET 4.6.2

### Expected behaviour
frmMain.Designer.cs is available

### Actual behaviour
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file *\Chummer5\Translator\frmMain.Designer.cs' could not be found.	Translator	*\Chummer5\Translator\CSC	1	Active

### Steps to reproduce the behaviour
Build Chummer Tool

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
Fixed in latest commit.
