### ISSUE TITLE
Adept Powers - Multiple Issues

### ISSUE THREAD

**Issue by Nightfishy** [chummer5a/chummer5a#146]
* Adept Powers that receive Ranks from Foci and Power Points are not correctly displayed after opening a saved character. Example: Mystic Armor has 2 ranks for PP and 2 ranks from a qi focus. Upon reloading the character, chummer only shows 2 ranks (from the focus) in the Power and 1 PP is shown as unallocated. 

* The adept power "Improved Potential" is not applied after opening a character file. (Tested with a mental limit of 5, bought improved potential, limit is increased to 6, close and open character file: Mental Limit is displayed as 5)

**Comment by chummer5a** [comment]
Improved Potential just isn't enumerated in the display source. The actual Limit is being set properly, but it's not referred to properly anywhere. Easy fix.

The Powers UI doesn't seem to expect that powers can come from multiple sources, and just takes the highest value it finds. Shouldn't be hard to sort out.

**Comment by chummer5a** [comment]
Appears to only be an issue during creation mode. Works perfectly after chargen. Issue is... odd, to say the least.

**Comment by Nightfishy** [comment]
I did have these issues in career mode. Having downloaded the most recent version of chummer5a, the "Improved Potential" bug no longer occurs, though. I assumed you had fixed it. :D 

The focus + actually power points thing remains an issue for me, even in career mode. (tested on mystic armor, 2 actual ranks + force 4 qi focus = rating 2 mystic armor with 1 pp unspent each time I load the sheet.

**Comment by joha4270** [comment]
I believe everything mentioned here is fixed as of build 173
