### ISSUE TITLE
Unable to print

### ISSUE THREAD

**Issue by Kadrack** [chummer5a/chummer5a#1460]
### Environment
Chummer Version: 5.190.105
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Print is possible

### Actual behaviour
When you try to print any kind of character, the application crash

### Steps to reproduce the behaviour
Hit the print button or select print in the menu

### More information
After the crash the default character sheet is available in the application folder in a file with a name like : 36dac2e8-eec2-41b1-8734-0065de2018eb.htm

**Comment by chummer5a** [comment]
Can't replicate it. What's the crash handler say the error is?

**Comment by Kadrack** [comment]
The crash Handler says that the file is not available because allready in use.

After several try, it come from the option : Apply linux printing fix.  If this option is checked Under Windows printing is impossible.  And yes I know that this is unuseful under Windows ;)
