### ISSUE TITLE
Windows prevent app execution

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1461]
### Environment
Chummer Version: 5.190.105
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Can't launch the app, windows prevent the execution to protect the computer. (even in admin mode)
That's with a fresh install.
With the update process, i had a crash on character opening.

### Steps to reproduce the behaviour
launch program

**Comment by chummer5a** [comment]
This may be fixed in the current builds, but if it's a Windows error there's not a lot I can do to troubleshoot unless there's a crash code or something.

**Comment by prismatic-mind** [comment]
It's ok now, thanks (Had to make a fresh install and delete previous content)

**Comment by prismatic-mind** [comment]
A character file (all my chars are affected)
[War Thug.txt](https://github.com/chummer5a/chummer5a/files/794032/War.Thug.txt)

**Comment by prismatic-mind** [comment]
Can't really test right now, but it may be a translation problem.
I dl an old version (103) and character crash at opening but no problem after switching to english

**Comment by prismatic-mind** [comment]
After update to 114, same behavior.

Crash at opening with this character in french, but after switching to english, it works fine

**Comment by chummer5a** [comment]
So you're not seeing the crash handler at all? It's possible that your computer for some reason is intercepting the crash handler, but I can't imagine why it would be triggering that kind of behaviour off Chummer.

**Comment by prismatic-mind** [comment]
We can close this one since the "windiws prevent app execution" is corrected.

Crash handler is working, but it was crashing during report sending (#1463)

Should i open a new issue for the character opening crash with ui set to french ?
I've sent error report since error report no longer crash :)

**Comment by chummer5a** [comment]
I don't have access to the crash reports at the moment, what's the exception.txt say when you click on the blue link on the crash handler window?

**Comment by prismatic-mind** [comment]
System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   à System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   à System.Convert.ToInt32(String value)
   à Chummer.frmCareer.frmCareer_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Can't replicate the crash with that war thug character file, but I did find an issue with technomancers that might cause that.

**Comment by prismatic-mind** [comment]
I've tested with a fresh install with v119, same behavior.
Crash at opening char with this exception.
[attributes.txt](https://github.com/chummer5a/chummer5a/files/800939/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/800940/exception.txt)
Char :
[War Thug v2 - Copie.txt](https://github.com/chummer5a/chummer5a/files/800938/War.Thug.v2.-.Copie.txt)
Anothe with same error :
[campagne hk - Tseung Ni Na - Copie.txt](https://github.com/chummer5a/chummer5a/files/800936/campagne.hk.-.Tseung.Ni.Na.-.Copie.txt)

**Comment by prismatic-mind** [comment]
I confirm the issue is resolved.
