### ISSUE TITLE
Error while sending error report

### ISSUE THREAD

**Issue by prismatic-mind** [chummer5a/chummer5a#1463]
### Environment
Chummer Version: 5.190.112
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
Choose "send error report" when crashing result in a JSON error

### Steps to reproduce the behaviour
Chose de send error report when app crash

![error chummer send error report](https://cloud.githubusercontent.com/assets/20904428/23219522/907d4524-f91f-11e6-986b-ab3a21f9610a.png)

**Comment by joha4270** [comment]
Should be fixed now. 

Server was discarding uploads for being too big.
