### ISSUE TITLE
Mugshot Cut-off

### ISSUE THREAD

**Issue by MisterFoopy** [chummer5a/chummer5a#1465]
### Environment
Chummer Version: 5.190.0
Environment: Windows 7 - 64-bit
Runtime: .Net Framework 4.5.2

### Expected behaviour
When printing character sheet, you can see the mugshot you've assigned.

### Actual behaviour
When printing character sheet, you see a space where the mugshot would be with a broken image 'x' in the top left. Or, if you go edit the image, changing its format from .png to .jpeg or .gif, you get the top half of the mugshot with the bottom half cut off. And yes, all images were edited down to 210 x 310. It seems to work on everyone else's computers just fine, however.

Even once printed, the mugshot is cut off, so it's not just a funky display issue that goes away with the final product.

### Steps to reproduce the behaviour
Nothing outside of what's listed above.

### Link to affected character file
https://drive.google.com/open?id=0B-IbwIg97lS1M2NzbFR1NXg2UXc

**Comment by GearheadLydia** [comment]
I have found that directly editing the HTML is a possible work-around, though I will admit that it is clunky to do so and makes it difficult to print updated versions.

**Comment by chummer5a** [comment]
Character works fine on my end, can you save the file as a HTML file and upload it? In theory it should be reproducible in that context.

**Comment by DelnarErsike** [comment]
Are there still any problems in the latest nightly? If no reply is received in 72 hours, I will close the issue.
