### ISSUE TITLE
Chrash on loading old char

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#1466]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.112
Environment: WIN10 (german)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Open the char

### Actual behaviour
chrash with
"Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt."
->
"An element with the same key has already been added."

PS: the Crash reporter chrashed with #1463

### Steps to reproduce the behaviour
open attached char

### Link to affected character file
attached the crash files that are not to big (my chrash dump was 100mb, i excluded that)
and the char i tried to open

[chummer_crash_131322809859989502.zip](https://github.com/chummer5a/chummer5a/files/795178/chummer_crash_131322809859989502.zip)

![grafik](https://cloud.githubusercontent.com/assets/10605630/23238836/3107ac48-f964-11e6-8df7-0e1346e0bf0b.png)

**Comment by prismatic-mind** [comment]
May be the same problem i have with french version https://github.com/chummer5a/chummer5a/issues/1461

**Comment by Tom-0169** [comment]
No, it's not. I did not open the Char in german. I tried i english.
Now I tried the new version (5.190.115).
No Luck. Same problem. Instead to fail it should tell me the Key.
Hope you have a hunch.

**Comment by chummer5a** [comment]
It's failing to load your exotic weapons skills for undoing karma costs. Will fix it ASAP.
