### ISSUE TITLE
Changes to Character Viewer for German and French versions of Character Sheets

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1468]
Following up from the note I added to #1347. I have completed the work of creating French and German translations of the the character sheets available to the English versions.

1) Being able to use a common XSLT for every format, with the text automatically translated, invoked by the individual language formats.
2) Simplified the table definitions, removed unnecessary code.
3) Added a number of XSLT members by removing code from multiple formats.
4) Created new formats, such as a Calendar print, to allow certain sections to be removed from the main print
5) Created a separate "Core" format that excludes notes, expenses, background, etc. in a smaller, cleaner design.
6) Reordered sections of the code, making a more logical print format, e.g. moved the calendar from being the second block to near the end.

The German and French translations have been completed with the help of Google Translate, but these translations need to be verified.

Attached is a zip file containing a replacement for the "sheets" sub directory of the main Chummer5a directory. To install the replacement directory, firstly rename the existing one. And secondly extract the zip file into the main directory.

The translations are in the xz.@@.xslt file in the French (fr) and German (de) sub-directories of the sheets directory. If you spot a translation error, can you correct it in the file and load it up to this issue.

I have set up the Japanese reports, but made no attempt to make the translations. If someone would like to make the translations, and rename the character viewer files in the jp directory I would appreciate it.

**Comment by Lochabar** [comment]
[sheets.zip](https://github.com/chummer5a/chummer5a/files/795549/sheets.zip)

**Comment by Kadrack** [comment]
Here is my review for french.  It's a quick review of the file content but if I don't do it now it will not be possible before next week.

If some french translation need more review to be adapt, I'll include it in the complete review I've actually planned for the french datas.

[sheets.zip](https://github.com/chummer5a/chummer5a/files/796197/sheets.zip)
