### ISSUE TITLE
 Issue: Clicking add accessory with a weapon accessory selected crashes application

### ISSUE THREAD

**Issue by Sammmmm** [chummer5a/chummer5a#1470]
### Environment
Crash ID: 785a2b2c-ea16-4d7d-af7a-8bf0e549aff6
Chummer Version: 5.190.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
Clicking add accessory with a weapon accessory selected crashes app

### Steps to reproduce the behaviour
- add an ares desert strike
- click on imaging scope
- click add accessory

**Comment by chummer5a** [comment]
Can't replicate the issue in current nightlies.
