### ISSUE TITLE
Enhancement: Working for the People/Man functionality

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1472]
While there is a way to convert karma into nuyen, there's no way to convert nuyen into karma as per the Shadowrun Missions FAQ.

> Is there a Cash for Karma (or Karma for Cash) option?
>Yes! Once between each Missions adventure you may choose to Work For The Man or Work For The People.
>If you are Working for the Man, you can trade 1 Karma for 2,000¥. This represents your character going out and doing the dirty, sleazy, or simply boring grunt work for a company or corporation. It pays well, but eats away at your soul.
>If you Work for the People, you can trade 2,000¥ for 1 Karma. This represents you going out and doing some pro-bono runner work, helping out at a local soup kitchen, or doing some volunteer work. It costs you a little something, but you feel better about yourself afterward.
>In either case, you may only trade away or gain a maximum of 5 Karma each time you Work for the Man or the People, and it takes up one week of downtime during which you can do nothing else. You cannot do this again until after you pull another Shadowrun.

**Comment by chummer5a** [comment]
Nuyen Gained, Karma Spent?

**Comment by Reshy** [comment]
Nuyen spent, karma gained.

**Comment by chummer5a** [comment]
I can't see any existing code for that either way, unless I'm blind. I guess I could put in a method to do it, it'd basically just be linked expense entries.

**Comment by Reshy** [comment]
Yes, it's a feature request.  Thank you.
