### ISSUE TITLE
Will not launch

### ISSUE THREAD

**Issue by Illuminati-sama** [chummer5a/chummer5a#1484]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.191.0
Environment: Win7 ult (64bit) win10
Runtime: .NET 4.6.2 (win7) Unknown but newer than 4.5.1 (win10)

### Expected behaviour
to launch

### Actual behaviour
(win7) immediate crash with appcrash error (same when launched as admin)
  Problem Event Name:	APPCRASH
  Application Name:	Chummer5.exe
  Application Version:	5.191.0.0
  Application Timestamp:	58b146c7
  Fault Module Name:	ntdll.dll (note, this has been clr.dll as well as KERNELBASE.dll)
  Fault Module Version:	6.1.7601.19135
  Fault Module Timestamp:	56a1c6fa
  Exception Code:	c00000fd
  Exception Offset:	0005bbd2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	211d
  Additional Information 2:	211d141bac531df18afd9061a787091f
  Additional Information 3:	fe32
  Additional Information 4:	fe3278d63f0d322d8c659af19d795fd2

(win10) nothing, will not lauch at all (same as admin)
### Steps to reproduce the behaviour
Unknown

**Comment by captroberts** [comment]
I am having the same issue, Only I am on Windows 10 64 byte.

**Comment by joha4270** [comment]
I have been poking a little with my debugger, but i cannot find what went wrong. 
I would like you to produce a dump file for me.

Open chummer. Wait for it to crash, then leave it open.
Open task manager. To to _Processes_ tab. Find Chummer5.exe and right click it. Select _Create dump file_. Wait for it to compleete and take notice of the file path in the popup. Upload that file somewhere and post the link here.

**Comment by captroberts** [comment]
If I could get it to crash, I would get the dump file for you. The damn thing will not do anything. It will not open for nothing.

**Comment by aldurljon** [comment]
I have the exact same problem of it not opening at all. The program shows up in background processes for a few seconds before exiting. I grabbed the dump file during that time, though I don't know if it actually has anything. 
[https://www.dropbox.com/s/g4h1y2td6b3i12n/Chummer5.DMP?dl=0](url)

**Comment by joha4270** [comment]
@aldurljon as far as i can see, it is trying to log that logging failed. This fails, so it tries to log it...

Try open the registry, navigate to HKEY_CURRENT_USER\SOFTWARE\Chummer5 and change "uselogging" to "False"

_prays..._

**Comment by aldurljon** [comment]
I opened the location in regedit. I don't see any place I can change uselogging.

**Comment by joha4270** [comment]
Huh?

Is the HKEY_CURRENT_USER\SOFTWARE\Chummer5 key present at all?

**Comment by aldurljon** [comment]
Yes. But it only has the default value in it.

**Comment by captroberts** [comment]
I cannot even find the H_KEY at all. Sorry, computer idiot here.

**Comment by joha4270** [comment]
Okay, i think i divined the real issue from aldurljon's crashdump. A new nightly that should solve the problems are going to be uploaded in a few minutes at https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.191.27

I hope this fixes it, otherwise i have to start just counting how many lines it passes and see where it blows up, not something i'm looking forward to.

**Comment by captroberts** [comment]
I am now praying to the Dev Gods that it does the trick. If need be I will sacrifice a mother board to them.

**Comment by aldurljon** [comment]
Just downloaded. It works for now! Thank you!

**Comment by joha4270** [comment]
>works for now!
_shh, don't jinx it_

@captroberts any luck for you?

**Comment by captroberts** [comment]
Ok, now it is saying,"Windows cannot access the specific file. You may not have permission to use it."
It did open for 10 seconds before it shutdown and gave me that message.

**Comment by captroberts** [comment]
It worked for 5 seconds. Then it gave me a message, "Windows cannot access the specific file. You may not have permission to use it.

**Comment by joha4270** [comment]
Either try running as admin, or create a dump during those 10 seconds as described above. 

Can't guess what exactly happened.

**Comment by captroberts** [comment]
Tried admin. All I get is the windows message now. Cannot get it to run at all now.

**Comment by captroberts** [comment]
Found the problem. My Anti-Virus is causing it to fail. Going to see if I can get to stop it.

**Comment by Illuminati-sama** [comment]
I dont know what magic you did ser, but it works now. Thank you so much.

**Comment by joha4270** [comment]
Confirmed working by 3 people including the orginal submitter. A hotfix might be released
