### ISSUE TITLE
Exceptions in Translator.exe

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1485]
### Environment
Chummer Version: 5.191.19
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
No exceptions :)

### Actual behaviour
Selecting a data file and category causes an exception:

- Launch translator.exe
- Choose language german (DE) and click "Edit"
- Select "armor.xml" in the first combobox.

- Select "armors" in the second combobox and the following exception is shown:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Translator.frmTranslate.LoadSection()
   bei Translator.frmTranslate.cboSection_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

- If you select "mods" in the second combobox (instead of "armors"), the following exception is shown:
System.ArgumentException: Die Spalte sectionEnglish kann nicht gefunden werden.
Parametername: columnName
   bei System.Windows.Forms.DataGridViewCellCollection.get_Item(String columnName)
   bei Translator.frmTranslate.LoadSection()
   bei Translator.frmTranslate.cboSection_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### Steps to reproduce the behaviour
See Actual behaviour.

**Comment by chummer5a** [comment]
Can't replicate it.

**Comment by chummer5a** [comment]
This should be sorted out in the ACTUAL translator.exe file, now that it's properly being included in the builds.
