### ISSUE TITLE
Simple encoding patch for de_data.xml

### ISSUE THREAD

**Issue by UrsZeidler** [chummer5a/chummer5a#149]
diff --git a/Chummer/lang/de_data.xml b/Chummer/lang/de_data.xml
    index 2bc7eec..8606f63 100644
    --- a/Chummer/lang/de_data.xml
    +++ b/Chummer/lang/de_data.xml
    @@ -8182,7 +8182,7 @@
           <gear translated="True">
             <id>0e9a4de8-c78e-498e-8f3b-8e581bc73e43</id>
             <name>Configurator</name>
    -        <translate>Kon&#x1F;figurator</translate>
    +        <translate>Konfigurator</translate>
             <page>242</page>
           </gear>
           <gear translated="True">

**Comment by chummer5a** [comment]
Included in 5.160.
