### ISSUE TITLE
Translator still not loading german String (#1486)

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1491]
Sorry that I have to create another ticket, but the issue #1486 / #1490 is still not solved.
I downloaded the latest version (5.191.26) which should fix the bug.
It did not.

I compared the unpacked directories of the versions 5.191.23 and 5.191.26 and detected that the file Translator.exe is binary identical. So your last "patch" did not change the executable at all. And thus could not fix the bug.

If there is any way I can help to detect the problem (like creating some form of debug logging), just ask.

### Environment
Chummer Version: 5.191.26
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The translator should show the texts from the selected language file.

### Actual behaviour
The translator shows the texts from the english base file only. In both columns "english" and "text".

I've checked in the "en-us.xml" and "de.xml" file. A german value for the key "String_BuyWithKarma" exists.
But Translator still shows the english text in the column "text".

Looks like that the german file ("de.xml") is not loaded at all.

### Steps to reproduce the behaviour
Launch translator.exe
Choose language german (DE) and click "Edit"
Look at the "text" column, for example for the key "String_BuyWithKarma".

**Comment by chummer5a** [comment]
Figured out the problem, I was overwriting the new exe with an old one. Quirk of the build process.
