### ISSUE TITLE
Lifestyles are not properly named

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1493]
### Environment
Chummer Version: 191.27
Environment: W10
Runtime: probably .NET 4.5.1

### Expected behaviour
Lifestyle be named as you name it.

### Actual behaviour
Is named the same as the 'level' of the lifestyle. Like "High", or "Low" 

### Steps to reproduce the behaviour
Add a new lifestyle. Name it something. Complete the purchase, observe it being named differently. http://i.imgur.com/XpQrrYI.png

**Comment by prismatic-mind** [comment]
linked to #1441 ?

**Comment by Rinnolk** [comment]
Works properly in 190.67. The same file when loaded into current nightly build has the name default to the level of lifestyle, 

So it shows the correct name when opened in an older version, but not when opened in the newer nightly.
