### ISSUE TITLE
[Feature Request] House Rule to allow Spider Mages to Summon Spider Spirits

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1503]
In Aetherology the book goes over the geometry of the metaplanes.  One of these planes is the Metabeles (Aka the Web), and it has spider spirits in it called the Anansi and the Tsuchigumo.  Now, as you know there's also a spider mentor spirit that's linked to these spirits and metaplane.  So is it possible we could get a house rule which amends the spider mage's list of spirits to include those two?

![image](https://cloud.githubusercontent.com/assets/2096384/23439742/07586960-fdcd-11e6-9911-810cdc243373.png)
![image](https://cloud.githubusercontent.com/assets/2096384/23439756/159a0132-fdcd-11e6-8122-830b47b73c14.png)

**Comment by chummer5a** [comment]
There isn't a Spider tradition in Chummer currently, and Mentors don't generally change your tradition's list of spells. I'd suggest just using a custom tradition patterned on whatever currently exists.

**Comment by Reshy** [comment]
The problem with that is that you cannot add spirits in excess of 5.

**Comment by chummer5a** [comment]
Which is why you'd normally use the Calling ritual from Street Grimoire; I'm not seeing anything that indicates that spirits can be summoned as though they're spirits from your tradition.

**Comment by Reshy** [comment]
Even if you were to replace some of the spirits, those spirits aren't actually listed as spirits you can choose.

**Comment by chummer5a** [comment]
What you'd need to do to fix that is add a custom_traditions.xml file that has the relevant spirit type as an entry in the <spirits> node group. Should just be a matter of creating a new file, copying an existing spirit and making the appropriate changes to the stats (including creating a new GUID from guidgenerator.net) and dropping it in your data folder. 

Relevant wiki links: 
[Traditions](https://github.com/chummer5a/chummer5a/wiki/Traditions-and-Streams)
[Custom Data Files](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files)
