### ISSUE TITLE
Skill point house rule

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1507]
### Environment
Chummer Version: 5.191
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
To be able to specialize a karma bought skill with a skill point as a house rule.

### Actual behaviour
I can't. In 5.190 and earlier I could.

### Thank you
Thank you again for a very good character generator, essential for many of my characters. They would not be if not for Chummer.

**Comment by reyjinn** [comment]
Not even sure that this should be a house rule, as far as I can tell it should be default behavior but having it as a house rule would be better than nothing.

**Comment by DelnarErsike** [comment]
This is now an optional house rule present in the latest nightly.
