### ISSUE TITLE
Print to pdf issue

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1508]
### Environment
Chummer Version: 5.191.39
Environment: Windows 10, Foxit Reader
Runtime:  probably .NET 4.5.1

### Expected behaviour
That the pdf should look as the preview, with every other row/object shaded. No red lines.

### Actual behaviour
There are red lines instead of the shaded rows. On Qualities, Armor and Contacts. Skills and Gear does not have either shaded rows or the red lines.

### Steps to reproduce the behaviour
Take any character. Print to pdf. Have tested Foxit reader and Microsoft print to pdf.

**Comment by Lochabar** [comment]
Sorry about the red lines - put in some testing code and forgot it was there!

[#1508.zip](https://github.com/chummer5a/chummer5a/files/817048/1508.zip)

I've also included corrections to the French translations - thanks to Kadrack (in issue #1468 )

**Comment by Lochabar** [comment]
As far as the alternating shading, I don't recall that these were ever carried over to the printed/PDF sheets - I didn't find any code in the sheets when I revised them to make this happen. Does anyone have any suggestions?

**Comment by chummer5a** [comment]
Alternated shading is done by the `tr:nth-child(odd)` property, Fancy Blocks is the only one that uses it. No particular reason it shouldn't come across unless the PDF library we're using doesn't understand it.
