### ISSUE TITLE
[Feature Request] Support for Spirit Fettering

### ISSUE THREAD

**Issue by Idayn** [chummer5a/chummer5a#1509]
Please add support for Spirit Fettering (p. 192 SG) in the "Spells and Spirits" tab (and the "Karma and Nuyen" tab for the karma expanse). 

Thanks for all the work you do :-)

**Comment by Idayn** [comment]
Wow that was quick, thank you :-)
Follow-Up request: The interaction beetween the Spririt Whisperer Quaility and Fettering is not working correctly. If you have Sprit Whisperer, and summon a Force 6 Spirit, it shows up as force 7, but counts as force 6, so the karma cost is acutally 18, not 21 for Fettering.

**Comment by chummer5a** [comment]
Ehhhhh. I'd want to see an errata comment on that from CGL; the way I read it, fettering and binding are performed against the actual force of the spirit, so no discount would apply.

**Comment by Idayn** [comment]
Hmm interesting. I'll get ont that :-)

**Comment by Lochabar** [comment]
Spirit Whisperer Quality (RF p150) states "For all purposes, the character is considered to have summoned the spirit at the declared Force". Does this not mean binding is at the declared force not the actual force?

**Comment by chummer5a** [comment]
Missions FAQ says binding and fettering happen at whatever the actual force of the spirit is; RAW indicates that the declared Force of the spirit is used exclusively for reagent costs and resisting/determining the type of drain.

**Comment by Idayn** [comment]
Ok, I misread the part with "For all purposes,
the character is considered to have summoned the spirit
at the declared Force..." and thought it would apply to binding and fettering as well. 

At least I can now manage it with chummer, thanks again.
I was looking at the source code to maybe implememt it myself, but you were faster :-)
