### ISSUE TITLE
Karma costs for Connections and skillgroups still borked.

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#151]
Fresh download of the new version shows karma cost of 10 for Skillgroups and 2 for connections.

**Comment by chummer5a** [comment]
...God damn it. Okay, so the initial values aren't called as the DEFAULT
values, because why would you ever do things in a reasonable manner. If you
hit the Restore Defaults button it will be fixed. I'll properly fix it
later.

**Comment by chummer5a** [comment]
Fixed in 5.161.
