### ISSUE TITLE
AI and Autosofts And Programs

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1511]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.191.31
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Should be able to purchase each in Advanced Programs at different ratings.

### Actual behaviour
Nothing gives you the ability to change the rating.

### Steps to reproduce the behaviour
Create an AI in any of the new character creations modes. Go to Advanced Programs and purchase an Autosoft.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
As far as I'm aware, all AI programs and autosofts automatically equal the rating of the AI's Depth, but Data Trails is so abominally laid out that I'm having trouble finding the proper rules for it.

**Comment by oyster450** [comment]
I am experiencing a crash whenever I try to add a Program to an AI character. Might this be a result of devs working on fixing this issue, or should I file a separate Issue report?
