### ISSUE TITLE
Inconsistent calculation of initiative with enhancements

### ISSUE THREAD

**Issue by McDie** [chummer5a/chummer5a#1515]
### Note
If the actual behavior is intentional, I apologize. I just do not see a reason for it, right now.

### Environment
Chummer Version: 189.32 and above
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Until 189.31 and earlier versions, wired reflexes 1 resulted in an displayed initiative score of "6 (7) + 2d6". 
The reaction bonus was noted in brackets, but the additional d6 was already added.

### Actual behaviour
From 189.32 and above, the initiative with wired reflexes 1 is displayed as "7 + 1d6", which means the reaction bonus is already included (and not conditionally in brackets) but the additional d6 is not. 

### Options for desired behaviour
Either only the basic initiative is displayed (example "6 + 1d6") or the complete bonus is already included ("7 + 2d6"). Maybe there is a way to display both (  "6 + 1d6 (7 + 2d6)" or "6 (7) + 1d6 (2d6)"   ). For practical reasons, I would like to see the complete bonus included. Maybe that would be the quickest fix, too.

### Steps to reproduce the behaviour
Create a character with wired reflexes 1.

**Comment by chummer5a** [comment]
Hmm, I can't replicate the issue with it not showing the correct values. I can definitely lash up a tooltip displaying the breakdown of the stats, though.

**Comment by McDie** [comment]
My bad! You are right. With new characters everything works fine. My old character files seem to be incompatible. Made by a version 181.x they do not show the correct initiative anymore. 
With a fresh test character everything works fine. I beg your pardon, that I did not do it before. Sorry, for wasting your time. Now to the fix for old character files:

I compared the files OLD.chum5 and NEW.chum5 and found a difference in the cyberware section "wired reflexes".
OLD:
<initiativepass precedence="1">Rating</initiativepass><specificattribute><name precedence="1">REA</name>
vs
NEW:
<initiativepass precedence="0">Rating</initiativepass><specificattribute><name precedence="0">REA</name>

Also the guid of wired reflexes was different, which I assume is normal.

In the improvement section of the character files, I found regarding the guid of wired reflexes two entries, one for the reaction bonus, one for the dice bonus. While the reaction bonus entry was similar in OLD and NEW (I had no problem with the inclusion of the reaction bonus anyway), the entry about the dice bonus was different.

OLD:
<unique>initiativepass</unique>
....
<improvementttype>InitiativePass</improvementttype>
vs.
NEW:
<unique>precedence0</unique>
....
<improvementttype>InitiativeDice</improvementttype>

By changing OLD to 
<unique>precedence1</unique>
....
<improvementttype>InitiativeDice</improvementttype>

I could fix it.

Sorry, for wasting your time! Of course, the issue is closed.
If you have any advice, how I can update legacy character files in a better way, I will appreciate it very much!

Thanks, chummer5a, for all your work! Love that tool!

**Comment by chummer5a** [comment]
If you notice something weird happening with your character, the best bet is generally to use the Reapply Improvement menu option in the Special menu to rebuild it; that strips all your character's existing improvements and rebuilds them from scratch.
