### ISSUE TITLE
Negative Qualities not removed in career mode

### ISSUE THREAD

**Issue by Monzill82** [chummer5a/chummer5a#1517]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running?
5.191.27
Environment: (Operating system here. If it persists over multiple OS's list them all)
Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
No clue
### Expected behaviour
[about_blank.pdf](https://github.com/chummer5a/chummer5a/files/821394/about_blank.pdf)

Highlighting a negative qualities  (Limited Corp SIN), then clicking "Delete" in  Career mode, spending 2x Karma to remove said quality (karma needed is  there)

### Actual behaviour
Nothing

### Steps to reproduce the behaviour
Highlight  quality  (single click),single click delete button

### Link to affected character file
https://drive.google.com/drive/folders/0B0hmNAwxBuhHV09NR2JfeFBQdVk?usp=sharing

**Comment by chummer5a** [comment]
Fixed in current nightlies.
