### ISSUE TITLE
Printing Crash with 5.191.27

### ISSUE THREAD

**Issue by rabiesray** [chummer5a/chummer5a#1518]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer5.191.27
Environment: win 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
Print

### Actual behaviour
crash as page appears on screen

### Steps to reproduce the behaviour
using file, go to print

### Link to affected character file
https://drive.google.com/open?id=0B-HMqa1yKEHIMUZ1UzRsLXVIREE

**Comment by chummer5a** [comment]
I can't replicate the crash. Please confirm with a current nightly build and post the error you get, if any.

**Comment by rabiesray** [comment]
Hey

I am trying on my desktop hoping for different results. Thank you for your
attention on this.

Ray

On Tue, Mar 7, 2017 at 7:24 PM, Chummer 5 Is Alive <notifications@github.com

**Comment by rabiesray** [comment]
windows 8. Now I cannot get it to work at all on my desktop. (original problem was on laptop widows 10

**Comment by chummer5a** [comment]
Got an error message or anything?

**Comment by rabiesray** [comment]
Unfortunately, no. Once you choose "print" there is a slight pause, the
character sheet pops up on screen for a moment (1 second and a half) then
the program closes and must be reinstalled.

Ray

Ps. thank you for caring to fix this.

**Comment by rabiesray** [comment]
I am unable to run as a previous version of Windows as well as a solution.

**Comment by chummer5a** [comment]
What do you mean by must be reinstalled? If Chummer crashes you should see SOME kind of error message, either from Windows or Chummer itself.

**Comment by rabiesray** [comment]
It gives no message. And it must be reinstalled each time it crashes like
this. I have looked at the installed programs, it is missing each time this
happens.

**Comment by chummer5a** [comment]
There's no installer for Chummer. You extract it into a folder and run it from that location. 

The only thing I can think of that could cause a crash of the print method is if you've got the Linux Printing fix option enabled, which would cause an error about the file being in use if you're in Windows, or you're missing the DLLs for the PDF converter.

**Comment by rabiesray** [comment]
Sorry, so it closes and I have to re-extract it.

Unsure how to fix from here. Printing works for all else.

Is it stable in Windows 8?

On Mar 14, 2017 1:52 AM, "Chummer 5 Is Alive" <notifications@github.com>
wrote:

There's no installer for Chummer. You extract it into a folder and run it
from that location.

The only thing I can think of that could cause a crash of the print method
is if you've got the Linux Printing fix option enabled, which would cause
an error about the file being in use if you're in Windows, or you're
missing the DLLs for the PDF converter.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chummer5a/chummer5a/issues/1518#issuecomment-286328936>,
or mute the thread

**Comment by chummer5a** [comment]
I'm sorry, I don't understand; what happens to the Chummer exe that you need to re-extract it from the archive? Is your antivirus quarantining it or something?

**Comment by rabiesray** [comment]
Re-extracting works normally. The print function causes the same error.

**Comment by chummer5a** [comment]
I'm really not sure I can help with this if there's no error shown. I've never seen behaviour that prevents Chummer from opening some form of error window if it crashes, and without that it'd be blind guesses about what might be happening.

**Comment by rabiesray** [comment]
No sadly. I worry that I am unable to use the program. I suggested it to
numerous people and they all are enjoying it.

Thanks for your thorough help. Sorry I cannot be more help in my end.

R

**Comment by chummer5a** [comment]
Does the current patch change anything with the behaviour?
