### ISSUE TITLE
When picking the 'Chaos' mentor spirit, it is impossible to add both levels of the free 'Improved Potential' power to the same limit.

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#1519]
### Environment
Chummer Version: 5.191.43
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When selecting the 'Chaos' mentor spirit, I should be able to raise the same limit twice by selecting the same limit from the two popups that follows.

Edit: After reading the description for the Chaos Mentor Spirit (SG 299) and the Improved Potential power (Core 309) it appears that the Improved Potential granted by the Chaos mentor spirit is different from the version from core. The version from core only allows each limit to be boosted once, whereas the bonus from the Chaos mentor spirit explicitly allows the same limit to be boosted twice. Apparently, it is a qualitatively different power.

### Actual behaviour
When selecting the 'Chaos' mentor spirit, I tried to raise the same limit (physical) twice by selecting it twice from the two popups that follow. However, only one level of the power is applied. This is visible in both the 'Adept Powers' tab and the 'Limits' tab

### Steps to reproduce the behaviour
Create an Adept or Mysad, and assign them the quality for the 'Chaos' mentor spirit. When prompted to select which limits to apply the 'Improved Potential' power, pick the same limit twice.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Known issue, part of the adept power rebuild.
