### ISSUE TITLE
Point Buy: Karma costs for Skills broken / Skill Ratings are applied twice

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#152]
Odd one here. 

If you buy skills with karma, save the char, then reopen it, the character will have twice the skill-rating.

Example:  Buy a skill with a rating of 3 with karma, close, reopen, char now has a rating of 6 in the skill, 3 of which are shown.

**Comment by chummer5a** [comment]
Urghhh. Found and resolved in 5.161.
