### ISSUE TITLE
 Issue: - Update Problem

### ISSUE THREAD

**Issue by Holly-Buteau** [chummer5a/chummer5a#1527]
### Environment
Crash ID: 90c929c4-2f3c-4de0-a197-e1c336d39eb0
Chummer Version: 5.191.27
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer gets updated.

### Actual behaviour
I was trying to update Chummer. It crashed and when I try to reopen my character, it only comes up with the crash report.

### Steps to reproduce the behaviour
Attempt to update Chummer.

**Comment by chummer5a** [comment]
The updater has issues for some people that I've never really managed to find the root cause of; does the character still load properly if you download the latest nightly.zip file from get.chummer.net?

**Comment by Holly-Buteau** [comment]
My character loads in the latest nightly.zip file, but now the character isn't correct. For example, I have synaptic booster at rating 2, but I'm not getting any extra dice for having it.

**Comment by chummer5a** [comment]
Hmmm. Could you send me a copy of your character and try hitting the Reapply Improvements menu option in the Special menu? I expect it's not loading the ImprovementType properly after I renamed it, but I can't be sure without seeing the file.
