### ISSUE TITLE
(Mystic) Adept with astral sight cannot take Blind at 5 Karma

### ISSUE THREAD

**Issue by Esurnir** [chummer5a/chummer5a#153]
An Adept or Mystic Adept with the Astral Sight Power cannot take the 5 Karma Version of Blind.

**Comment by chummer5a** [comment]
Hrm. Making qualities available based on powers isn't currently supported.
Would need to add code to the <required> check in frmquality. Shouldn't be
a major problem.

**Comment by chummer5a** [comment]
Resolved in 5.162. Expected release 18/4/15.
