### ISSUE TITLE
Enhancement: Hide items over Max Availability

### ISSUE THREAD

**Issue by BetaVirus** [chummer5a/chummer5a#1538]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 9.191.27 (Build 192)
Environment: WIN 10 PRO x64; WIN 10 ENT x64, WIN 7 HOME x64
Runtime: (If you don't know this, it is probably .NET 4.5.1) 4.6.1

### Expected behaviour
Creation mode has max availability option set to 10 or 8. Should only be showing gear and other things with x rating or lower. 

### Actual behaviour
Shows all availability regardless of setting. 

### Steps to reproduce the behaviour
Open app, select any character build option, set max avail, click ok. verify gear list as avail limits or not.
Tested by downloading the Latest Nightly and Master version of the Chummer files, issue exhibited on both

### Link to affected character file
N/A - Issues with character creation of any new character.

**Comment by chummer5a** [comment]
Strictly speaking this is working as intended, but it shouldn't be a problem to build in a filter for it.

**Comment by BetaVirus** [comment]
That is a little confusing then. I thought that is what it was ment limit what items you see during creation?

What is the point in having a max availability on the select build method, if they did not want the filter?

**Comment by chummer5a** [comment]
When you try to complete the character, it will warn you that the items are over the availability limit; generally this is to support things like Restricted Gear.

**Comment by BetaVirus** [comment]
ah. makes sense. I did notice that there was no limit indication for restricted and other items. That would be a feature i would like to see for sure.

You know, for when GM does not want R or F items during creation or the players is looking for things that does not risk being taken, for not having a LIC to own it.

**Comment by BetaVirus** [comment]
So just wondering, but does this project have a donation feature?

**Comment by chummer5a** [comment]
Short version, no. If I ever find an implementation of it that allows for fair distribution to the various contributors without adding to my administrative overhead I'll consider it, but as is we don't accept donations.
