### ISSUE TITLE
requesting an additional houserule

### ISSUE THREAD

**Issue by seppestuyck** [chummer5a/chummer5a#154]
Our group gets 5x int+log for knowledge skills.
Perhaps it can be done with a number that has to be put in a box,
so people with a similar houserule can use it too

**Comment by drakir75** [comment]
some groups do 3x as in SR4. Maybe some choices.

**Comment by chummer5a** [comment]
I'll assign it as a number item, same as karma cost variables. May as well do the same thing for contacts while I'm at it.

**Comment by br3wm45t3r** [comment]
Could I also suggest one more house rule?

A check box to remove quality cap?

**Comment by chummer5a** [comment]
Included in 5.164.
