### ISSUE TITLE
Problem with member names in French and German

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1541]
When I revised the sheets folder to simplify maintenance with French and German versions, I created the French/German sheet names in those languages - perhaps that is my mistake.

For example, English "Vehicles" as French "Véhicules", and English "Game Master Summary" as German "Spielleiter Überblick".

However these member are now downloaded with incorrect names; "Véhicules" as "VÇhicules" and "Spielleiter Überblick" as "Spielleiter öberblick". Somewhere along the lines the language specific letters are being wrongly coded.

Do you know of a problem with Github as far as foreign letters are concerned?
Is there a setting I should be using?
Should I actually use the English name to avoid problems?

**Comment by chummer5a** [comment]
Not sure off the top of my head, strictly speaking there's no reason it shouldn't work. Might be better if I build in some code to store the name in the XML itself to prevent that issue.
