### ISSUE TITLE
Lightning Reflexes not what the book describes.

### ISSUE THREAD

**Issue by jwood292** [chummer5a/chummer5a#1545]
In the book, Run Faster, page 148, Lightning Reflexes is detailed as giving a +1 to initiative as well as a bonus initiative die, as well as only costing 20 karma. However, Chummer has it costing 40 karma, and while is does give the +1, it does not calculate the bonus initiative die.

### Environment
Chummer Version: 5.191.21
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: .NET 4.5.1

### Expected behaviour
Spend 20 for +1 to initiative plus a bonus initiative die.

### Actual behaviour
Spend 40 karma for +1 to initiative.

### Steps to reproduce the behaviour
Just click the quality.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Doubled karma cost probably indicates you're in career mode. Lightning Reflexes doesn't stack with any other sources of initiative dice.

**Comment by jwood292** [comment]
Is there a book with that reference just so I can double check? Run Faster doesn't say it doesn't stack.

**Comment by chummer5a** [comment]
This quality is not cumulative with any other Initiative enhancement, be it technological, chemical, or magical.
