### ISSUE TITLE
Heavy Weapon Mount Crash - 5.191.84

### ISSUE THREAD

**Issue by Sercalerc** [chummer5a/chummer5a#1548]
-Add a weapon to a heavy weapon mount
-Select the "Laser Weapons" category from the dropdown menu
While initially stable, the list view doesn't display any weapons for the weapon category and if you click on the list view window, the program crashes. This only effects list view, and you can add weapons through the browse window just fine.

Pictured here:
https://puu.sh/uZy0B/aca46939e3.png

**Comment by chummer5a** [comment]
The empty list is due to the availability filter; by default, items that exceed the Max Avail Limit aren't shown by default in create mode. There's an option to disable that behaviour in the Miscellaneous tab of the Options.

**Comment by Sercalerc** [comment]
Ah, understandably so. Thank you!
