### ISSUE TITLE
 Issue: - error when adding zoe second skin armor, attempts to force stacking to specific armor

### ISSUE THREAD

**Issue by dhyde79** [chummer5a/chummer5a#1550]
### Environment
Crash ID: 539bd298-29a5-47c2-a7c7-ff6572b3a4ad
Chummer Version: 5.191.87
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
tried to add Zoe: Second Skin

### Actual behaviour
It Attempts to force you to assign an armor for it to be stackable with (should not be required)

### Steps to reproduce the behaviour
add Zoe: Second Skin armor to a character, when it asks what to stack it with, hit cancel, click anything else, app crashes

**Comment by chummer5a** [comment]
It has Custom Fit (Stack), why would it not need an armour to be selected?

**Comment by dhyde79** [comment]
the description of the item is that it's custom fitted to the person (not a different set of armor) and that it's stackable as an under layer (such as wearing long johns or something similar underneath other clothes)

**Comment by dhyde79** [comment]
(copy and pasted from the book, delete if not allowed) 
" Each piece of the Second Skin line is custom tailored for the user, which means that a shift in weight of as little as one or two kilos will make the armor lose its most amazing benefit. That benefit is the fact that it is, for all intents and purposes, invisible."

The flavor text then goes on to suggest that it was protecting someone totally nude, thus reinforcing the point that the armor isn't meant to fit to a specific other style of armor, but rather that it's for the character, and stackable with whatever they may be wearing (also why its rating is expressed as a 6/+2 rather than just the 6 that Chummer currently lists it as)

**Comment by dhyde79** [comment]
I see where the problem is coming in....the Custom Fit (Stack) can be used two ways, either as Custom Fit allowing it to be a standalone piece of armor (armor rating 6), or, Custom Fitted specifically stacking to a specific armor, which then adds the +2 modifier to the other armor...

as for how to solve it...perhaps by adding the second skin as an armor mod when using it in "stacking" mode?

**Comment by chummer5a** [comment]
Description is not mechanics. Rules state it has Custom Fit (Stack), so it behaves the same way as other Custom Fit (Stack) items, and only switches to the bonus armour if the appropriate armour is equipped. if that's not a behaviour you like, it's simple enough to make an [override file](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files#override-data-files) to change that behaviour. As is, it's working as intended.

**Comment by dhyde79** [comment]
Right, the problem is, that if I don't select an armor, for it to stack with, (so that it's a standalone custom fit item with an armor rating of 6), the app crashes.  so, the only way it's functional is if I choose the other armor...and even at that, it's got a very small list of options (it only has one of the ares armors listed from the high fashion section, and nothing from outside of that section)

**Comment by chummer5a** [comment]
That's becase that's how Custom Fit (Stack) works. The list limitation for the armour is based on the category (High-Fashion Armor Clothing) and whether the item has the Custom Fit modification. Since the Ares Victory has the Custom Fit modification, it's included in the list.

**Comment by dhyde79** [comment]
ok....so...the clothes that're meant to be survival oriented hunting clothes can stack with the fancy underlayer, but the business suits in the same catagory can't...got it....

aside from that, adding the ruthenium cloak also generates an insta-crash

**Comment by dhyde79** [comment]
oh, and none of the data on any gear in the armor section populates on the right side while picking stuff anymore after the newest update....

**Comment by dhyde79** [comment]
(newest update also removed names from lifestyles, they're no longer displayed)
