### ISSUE TITLE
College Education.RF quality not applying Academic skill discount

### ISSUE THREAD

**Issue by GearheadLydia** [chummer5a/chummer5a#1552]
### Environment
Chummer Version: 5.190.51 through 5.191.89
Environment: Windows 7 SP1
Runtime: .NET 4.5.1

### Expected behaviour
The positive quality "College Education.RF" should reduce skill point costs for all Academic skills by half. Chummer 5.190 behaves this way.

Moreover, Knowledge skills - when selected from the drop-down menu - should apply types (Academic, Interest, Language, Profession, Street) automatically. Again, Chummer 5.190 behaves this way.

### Actual behaviour
Characters with the positive quality "College Education.RF", both loaded from files and newly created, pay normal costs for purchasing Academic skills and do not receive the bonus.

Moreover, Knowledge skills selected from the drop-down do not automatically get assigned types. This may be a related issue, as it would make sense that the skills are not getting discounted if the software does not recognize what kind of skills they are.

Both behaviors seem to have been present since at least 5.190.51, and are present in the current version as of writing this (5.191.89).

### Steps to reproduce the behaviour
In Chummer 5.191.27: Create a new character. Purchase "College Education.RF" positive quality. Go to Skills tab, add new skill, select a Knowledge skill (e.g. Biology), attempt to add points to it.

Alternatively: Create a character in 5.190, purchase "College Education.RF", spend some Karma or free skill points on Academic skills. Note the Karma remaining. Then save the character and open it in 5.191.27. Note that the Karma remaining will have decreased.

### Link to affected character file
Character file created in 5.191.27.
[BugDemo.zip](https://github.com/chummer5a/chummer5a/files/874385/BugDemo.zip)

**Comment by chummer5a** [comment]
There's an optional rule for whether the Education qualities apply to Karma costs, as the rules are a bit vague. It's disabled by default, that should sort you out.
