### ISSUE TITLE
Knowledge skills getting assigned incorrect types from previous selection

### ISSUE THREAD

**Issue by GearheadLydia** [chummer5a/chummer5a#1556]
Related to #1554.

### Environment
Chummer Version: 5.191.97
Environment: Windows 7 SP1
Runtime: .NET 4.5.1

### Expected behaviour
Knowledge skills selected from the drop-down should automatically add the appropriate type (Academic, Interest, Language, Profession, Street) to the skill.

### Actual behaviour
Selecting a Knowledge skill from the drop-down initially adds no type, and then adds the type from the previous skill selected - for example adding a new skill and selecting Bengali from the drop-down does not assign it a type, while selecting Biology instead of Bengali assigns it the type Language (corresponding to Bengali, rather than Biology).

### Steps to reproduce the behaviour
Create a new character, add a Knowledge skill, use the drop-down to select which skill it is, then use the drop-down again to select the skill immediately above or below it.

**Comment by chummer5a** [comment]
It should update properly when you tab out of the combobox.

**Comment by GearheadLydia** [comment]
Alright, thanks, good to know. I'll see if that behavior works.

(Again, sorry for being super picky about this. As an aside, I am trying to get Visual Studio working so I can contribute more actively, in terms of suggesting code edits and such.)
