### ISSUE TITLE
Chummer crash when any window is open

### ISSUE THREAD

**Issue by joaocorr** [chummer5a/chummer5a#1557]
Chummer Version: 5.191.27;
Environment: Windows 7 64 Bits;
Runtime: .NET 4.6.2

The program works fine. But, everytime when I try to create a new character on Chummer 5, it's crash. When it open a new window on the program to continue with the creation (the priority window or the configuration window, for example), it's crash. Can anyone help me, please?

**Comment by chummer5a** [comment]
Without knowing what the actual crash is, not really.

**Comment by joaocorr** [comment]
Sorry, but I don't know how to discover what crash is that, how can I do this? Everytime when I try to create a new character, the priority window appears, so the program stop working and gave me two options: "close the program" or "depurate", always like that. In my other PC that have the same configurations, it's working fine. I don't understand what happened whit this one.

**Comment by chummer5a** [comment]
If the application is crashing without showing the Crash Handler that could be an indicator that you don't have the correct version of .Net installed, but I don't see how the application would launch properly without it. 

Um. I guess you could use procdump to generate the crash report and then I can investigate that? https://www.codeproject.com/articles/707488/part-1-windows-debugging-techniques-debugging-appl
