### ISSUE TITLE
Chummer for Linux will not run with Wine and Mono

### ISSUE THREAD

**Issue by sbeadc** [chummer5a/chummer5a#1558]
### Environment
Chummer Version: Trying to use 192.0
Environment: Ubuntu Xenial, with Unity desktop, running off of Crouton (chromeOS/Linux dual-boot)
Runtime: Not sure, likely .NET 4.5.1

### Expected behaviour
Expected Chummer to start by running `mono Chummer5.exe` for install, then `wine Chummer5.exe` to start the application.

### Actual behaviour
When I ran `mono Chummer5.exe` , I got: 
`Unhandled Exception:`
`System.TypeLoadException: Could not resolve type with token 01000222`
`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000222`

Then, when I ran 'wine Chummer5.exe' , I got: 

`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 1`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"sectionGroup" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 3`
`fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5.2" not implemented`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"system.serviceModel" in state 1`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindings" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"basicHttpBinding" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"binding" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"readerQuotas" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"security" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"transport" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"message" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"binding" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"readerQuotas" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"security" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"transport" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"message" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"client" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"endpoint" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"endpoint" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"userSettings" in state 1`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"Chummer.Properties.Settings" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"setting" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"value" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"setting" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"value" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"setting" in state 3`
`fixme:mscoree:ConfigFileHandler_startElement Unknown element L"value" in state 3`
`fixme:mscoree:CLRMetaHost_GetRuntime Unrecognized version L"v4.0"`
`Missing method SetProfileRoot in assembly F:\home\rybeatty\Downloads\Chummer.192\Chummer5.exe, type System.Runtime.ProfileOptimization`

`Unhandled Exception:
System.TypeLoadException: Could not load type 'System.Runtime.ProfileOptimization' from assembly 'Chummer5'.`
`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.ProfileOptimization' from assembly 'Chummer5'.`

### Steps to reproduce the behaviour
I've run these commands multiple times in the terminal, and have gotten the same result every try.

### Link to affected character file
N/A - Affected application, not character

**Comment by chummer5a** [comment]
I believe you need winetricks as well; is this a new thing, or did old versions work for you?

**Comment by ryan5w4** [comment]
Ah, sorry, forgot to specify. I have Winetricks as well. And this is my
first time using Chummer on linux; it's worked well for me on Windows
before but I've never tried linux until now.

On Apr 4, 2017 9:42 AM, "Chummer 5 Is Alive" <notifications@github.com>
wrote:

I believe you need winetricks as well; is this a new thing, or did old
versions work for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chummer5a/chummer5a/issues/1558#issuecomment-291503295>,
or mute the thread

**Comment by chummer5a** [comment]
Hm. So you've followed the instructions to install the relevant winetricks profiles?

```
$ export WINEARCH="win32"
$ wineboot -u
$ winetricks dotnet40
$ winetricks dotnet45
$ winetricks dotnet451
```

**Comment by ryan5w4** [comment]
Sorry for the long response! I haven't gotten a chance to get to this computer in a little while. And yes, I tried that again, and it seemed to work the first time, but now it gives this on `winetricks dotnet40` and all subsequent commands:

`/usr/bin/winetricks: 2201: /usr/bin/winetricks: cannot create /tmp/early_wine.err.txt: Permission denied`
`------------------------------------------------------`
`wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message 'wine: /home/rybeatty/.wine is not owned by you'`

This seems to be a problem with Wine, and I'll have to see what I can do with that, but I'll leave the issue open for now just so I don't have to start a new issue if whatever fixes I can try don't work. Thank you for your help so far!

**Comment by chummer5a** [comment]
If you get stuck, you can come back to this issue and just reopen it.

**Comment by fxthomas** [comment]
I can confirm the Mono issue :

```
> mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Mon Feb 27 08:30:18 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

> mono Chummer5.exe 

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000222
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000222
```

**Comment by fxthomas** [comment]
I am quite unfamiliar with C#, but their [http://www.mono-project.com/docs/about-mono/compatibility/](doc) states that they don't support WPF/WWF/WCF. I wasn't able to make Mono start at all, in any case.

Current Wine/Winetricks versions need winetricks/winetricks#757 to fix .NET installation issues, but other than that the wiki instructions were correct.

**Comment by Sceptically** [comment]
Just a note that with mono 4.6.2 on Debian unstable, chummer v5.190.9 works while v5.190.11 doesn't. I tried a few random releases from v5.195.100 back, and all the ones I tried more recent than v5.190.9 failed with the System.TypeLoadException unhandled exception error.

**Comment by Pirat90pl** [comment]
So, I tryed #757 and it didnt work for me [tho i think it is already in stable winetrics but im just a noob] and old versions [v5.190.0] works. The rest Returns with error loading framework .NET

**Comment by chummer5a** [comment]
Closing as stale; unable to replicate using https://github.com/chummer5a/chummer5a/wiki#using-wine
