### ISSUE TITLE
RIG Cost and Capacity Error

### ISSUE THREAD

**Issue by Morcleon** [chummer5a/chummer5a#1561]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.0
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
The Responsive Interface Gear (RIG) should require Capacity 2 in armor and Capacity 1 in helmet, costing a total of 2500 nuyen.

### Actual behaviour
It lists Capacity 4 in armor and Capacity 2 in helmet, with each modification costing 2500 nuyen for a total of 5000.

### Steps to reproduce the behaviour
Add the Responsive Interface Gear: Armor or Helmet to any armor or helmet.

### Link to affected character file
https://www.dropbox.com/s/nxmwvm5czdy61p5/Cerise%20Belrose%20-%20Gun%20Adept.chum5?dl=0

**Comment by chummer5a** [comment]
Capacity was errata'd in 2014. There's no indication that the cost is shared between the two items, so I'd prefer to see an errata comment on it.

**Comment by Morcleon** [comment]
The indication of cost sharing is from the original entry, where capacity is written as "[2] + [1]", which indicates that the entire package costs 2500 nuyen. Additionally, having only one of the helmet or armor RIGs is useless, as they need to be installed and worn together.

**Comment by cnschu** [comment]
Hi there,

i can't check the capcity, but the rulebook clearly states that both parts are neccessary for the RIG to work.

> This system takes up 2 Capacity slots in the armor and 1 Capacity slot in the helmet; a RIG must be installed in both armor and helmet to work, and it only operates while all the armor is worn.
