### ISSUE TITLE
Every time I try to open Chummer it crashes

### ISSUE THREAD

**Issue by Stigmus** [chummer5a/chummer5a#1571]
### Environment
Crash ID: a0bb5f75-83cc-4089-b8ce-a332c7802bc7
Chummer Version: 5.192.8
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer opens

### Actual behaviour
It crashes straight away

### Steps to reproduce the behaviour
Try to open Chummer

**Comment by chummer5a** [comment]
Anything you can do to be a bit more helpful there? Some kind of error message? Have you tried downloading a fresh version of Chummer and/or deleting your settings file?

**Comment by Stigmus** [comment]
It says that "the 'armoroverride' start tag on line 1155 position 5 doesn't match the end tag of 'armoro' line 1155 position 22."
I have tried it with different versions and it always happens

**Comment by chummer5a** [comment]
Okay, I think what's happened here is that you have a character that didn't save properly in your recent items list. When the character roster tries to load it to cache, it hits the mismatched tag and crashes. I thought I'd coded around that already, but I might have missed that behaviour. Easiest workaround would be to clear your recent items list by opening the registry and clearing HKEY_CURRENT_USER\Software\Chummer5's MRU entries. 

![image](https://cloud.githubusercontent.com/assets/11448441/24836477/41c17c4c-1d60-11e7-81bc-be14cfe7a575.png)

**Comment by Stigmus** [comment]
It works now. Thanks.
