### ISSUE TITLE
Bone Lacing (Titanium)

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1573]
### Environment
Chummer Version: 5.192.0 and 5.192.13
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
Be able to find and buy Bone Lacing (Titanium)
(Or is there some errata I'm not aware of that has removed it?)

### Actual behaviour
Can only find Bone Lacings in Plastic and Aluminium

### Steps to reproduce the behaviour
Create any character. Add cyberware. Search for titanium

**Comment by chummer5a** [comment]
Titanium Bone Lacing is 16R; by default, Chummer only lets you view items that are within your maximum availability settings unless you already have the Restricted Gear quality.

**Comment by drakir75** [comment]
Ok. But you are able to buy a used Titanium Bone Lacing without Restricted
Gear. I will just make it not default hiding now that I know where to look.

Thank you for your work on Chummer!

**Comment by chummer5a** [comment]
If you change the grade to used then change the category to force a refresh, it should show the lacing.
