### ISSUE TITLE
Some Cyberware lost between 5.190.96 & 5.192.14

### ISSUE THREAD

**Issue by Akogooth** [chummer5a/chummer5a#1575]
### Environment
Chummer Version: error is in 5.192.14 and some versions prior to it (but not in 5.190.96)
Both in english language and german language
Only Base Rulebook enabled.
Environment: Win7 SP2
Runtime: 4.0 i think

### Expected behaviour & actual behaviour
Char creation, opening cyberware/bioware tab, adding cyberware.
Cyberlimbs => Cyberskull is missing (also obvious Cyberskull is missing)

Char creation, opening cyberware/bioware tab, adding bioware.
Standard => Suprathyroid gland is missing

In 5.190.96 the skull and gland is found.
Opening an existing char with cyberskull works fine. But still doesn't show up in the selection list in cyberlimbs selector (in add cyberware).

### Steps to reproduce the behaviour
see above

### Link to affected character file
every char file i create with 5.192.14
if its a general issue, you should be able to reproduce on your end.

**Comment by chummer5a** [comment]
Availability over maximum chargen limit, most likely. If you change the grade to Used and then the category to force a refresh you should be golden though.
