### ISSUE TITLE
Books without IDs?

### ISSUE THREAD

**Issue by dashifen** [chummer5a/chummer5a#1576]
This isn't so much about the application but rather the books.xml data file.  Some of the books lack an id, for example: Run Faster.  This seems like it might simply be an oversight, but is there a reason?  I ask simply because I'm parsing the files into my own system for game mastering data look-up and the lack of id values in the books.xml killed my update process.

**Comment by GearheadLydia** [comment]
I am reasonably sure that the IDs are pretty much arbitrary. Maybe download the generator someone made - I don't know where it was - or otherwise come up with a way of generating arbitrary hexadecimal digits, and assign one yourself until this is resolved in Chummer itself?

**Comment by dashifen** [comment]
@GearheadLydia They are, indeed, likely arbitrary, but if I choose my own and then, later, the app specifies a canonical id for a book (or whatever), then my app will want to re-insert the new information rather than update the old information identified by the canonical id.  Thanks!
