### ISSUE TITLE
Removing Cyberware Options that is fitted with Capacity creates an Essence Hole.

### ISSUE THREAD

**Issue by BitterLies** [chummer5a/chummer5a#1577]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.14
Environment: Win10
Runtime: .NET 4.5.1

### Expected behaviour
I have an Obvious Cyberskull with 4 Capacity.  It's fitted with a Commlink (2 Capacity Required).  When I remove the Commlink, I free up 2 Capacity to implant another upgrade that uses Capacity (a Math SPU for example).

### Actual behaviour
When I delete the Commlink, it frees up the Capacity in the Cyberskull (2 free of 4 total), but it also adds an Essence Hole.  As I am a magic user, this lowers my Essence and drops my Magic Rating.  I have no way of overriding the Essence Hit, or Deleting the Essence Hole, or restoring my Magic Rating.

### Steps to reproduce the behaviour
Create a character, set availability maximum to 16 (Cyberskull doesn't show up below that), then add a Cyberskull to the character.  Add a Commlink to the Cyberskull.  Save the character as created, ignoring warnings of unspent karma and such.  Once in career mode, remove the Commlink from the Cyberskull.  Assuming no talents and no special grades, the Skull costs .75 essence, and the commlink costs 0 essence (2 capacity).  With the commlink installed, it shows you as having 5.25 Essence.  When you remove the commlink, you gain a .2 Essence hole, and your total essence goes down to 5.05.

Thank you!

**Comment by BitterLies** [comment]
I did find a complex way of making it work with Anti-holes, though this feels like a backwards way to manage this.  If this is the correct step, then disregard and let me know.

**Comment by BitterLies** [comment]
I see how the anti-hole functions now, and will close this ticket!  Thank you!

**Comment by chummer5a** [comment]
That's actually not intended behaviour, I'll sort it out.
