### ISSUE TITLE
Some Qualities are missing

### ISSUE THREAD

**Issue by Cedar1974** [chummer5a/chummer5a#1578]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: NEwest version of 5a
Environment: WIN 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

There are some qualities missing, like Flashback and Quality of life.  Will these be added any time soon?

**Comment by chummer5a** [comment]
Which books are they from?

**Comment by chummer5a** [comment]
Flashbacks exists in the data, but it's filtered by the optional rule to prohibit qualities prohibted by missions. Disable that and you should see them. As far as I'm aware though, every existing book has pretty much all the content available. Reopen the issue if you can provide a page reference for any other qualities that aren't available.
