### ISSUE TITLE
Incorrect Essence / Magic enforement

### ISSUE THREAD

**Issue by cjnolen** [chummer5a/chummer5a#1579]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Build 192
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
If a character takes any loss in essence, he takes a loss in magic or resonance.  So if a character with a magic score of 5 takes an minor essence loss from 6 to 5.8, his magic score should drop to 4.  (Page 278 of the rulebook.)

### Actual behaviour
Essence appears to be enforced as an upper limit for magic, which works fine when a character starts with Magic 6.  But if a character starts with a Magic score of 4, they can take 2 full points of essence hits without affecting their magic ability.  

### Steps to reproduce the behaviour
- Create an adept with a magic rating of 4.
- Add multiple cybernetic components to drop the essence.
- No magic penalties will be enforced.

**Comment by chummer5a** [comment]
In create mode, Chummer automatically spends Karma or Priority Points to preserve your current attribute value. Once you're in Career mode, further Essence penalties will lead to a reduction in maximum and current rating.
