### ISSUE TITLE
Invalid damage of flash-bang grenade shown

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1582]
### Environment
Chummer Version: 5.192.16
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Grenade damage shown correctly.

### Actual behaviour
Damage of Flash-Bang grenades not shown properly.
Damage is shown as "0S" (or "0G" in german), but it should be "10S" ("10G" in german).

### Steps to reproduce the behaviour
Create a new character and add a Flash-Bang grenade.
Go to the weapons tab and select that grenade.

I added an frag grenade as a second test, but that worked and showed the correct damage. Its just the flash-bang grenade that does not work.

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/2f9670475e9932a883b53e53e9d4fac3ddd27312
