### ISSUE TITLE
Essence Calculations w/ Essence Reducing upgrades

### ISSUE THREAD

**Issue by mccrapshot** [chummer5a/chummer5a#1585]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.25
Environment: Windows 7 x64 and Windows 10 x64
Runtime: 4.6.2

### Expected behaviour
Adding Adapsin and a Betaware cyberarm should make the Essence cost of the arm 0.6

### Actual behaviour
When adding a betaware cyberarm the cost in the pop-up window is shown as 0.6, but when the limb is actually added the cost is 0.63.

### Steps to reproduce the behaviour
Create a character. Add Adapsin or biocompatibility cyberware. Add a betware cyberarm. You will see the correct essence cost in the pop-up but the actual essence cost after adding will be higher.

### Link to affected character file
(Enter text here)

**Comment by Rinnolk** [comment]
the cost seems right, since adapsin is not a grade multiplier, but a flat -10% after grades. So you are getting to .7 with grades and biocomp and then -10% from that brings it to .63

**Comment by Rinnolk** [comment]
Actually, scratch that, I'm blind and biocomp actually works wrong.

It's supposed to stack with grade multipliers (unlike adapsin) but doesn't.

**Comment by chummer5a** [comment]
I think the argument that the freelancers were making a while back is that stuff like adapsin or biocomp actually just reduces the grade by 0.1, but I've never gotten an official statement on how it's supposed to all interact.

**Comment by mccrapshot** [comment]
The rules read like it reduces the grade by 0.1, like you just said. 

"This rebate is cumulative with the reduction offered by the chosen ’ware’s grade, if any (e.g., the reduction for alphaware of 0.8 is reduced by ten percent, or 0.08, to become 0.72, and is rounded down to 0.7)." (CF 54) 

That's saying it reduces the grade multiplier by 10%, not the 'wares actual essence cost, and then rounds the multiplier down to the nearest tenth. I feel like a lot of confusion about this comes from people thinking you apply the 10% reduction directly to the essence cost of the 'ware, which, when combined with rounding down to the nearest tenth, would allow you to get some 'ware for 0 essence. However, RAW pretty clearly reads that it's a modifier to the grade multiplier, not the essence cost, which also means it would not allow you to get 'ware for 0 essence.

As for Adapsin, it does seem like it might work differently, and is just a 10% multiplier (at least according to RAW). The sentence, "This reduction is in addition to reductions from alpha-, beta- or delta-grade cyberware." could be argued to mean it's the same as Biocomp though. And Biocomp is earlier in the book so they could just expect you to mimic the more detailed rules there (they do have a tendency to do that).

As a side note, they were both acting as grade multipliers before version 5.192.17. That update altered it, which unfortunately has broken a character in our games. Been having to keep that character on 5.192.16. If you decide to have Biocomp be a grade multiplier and Adapsin be a straight essence cost multiplier, could you include an option for people to have Adapsin act as a grade multiplier? House rule maybe?

Thanks

**Comment by Rinnolk** [comment]
thanks for the version heads up, now I know what to go back to. :v

**Comment by Rinnolk** [comment]
with the lack of proper errata, writer's intent is the best we can go on :v 
http://i.imgur.com/wI7lFJ5.png
http://forums.shadowruntabletop.com/index.php?topic=21061.90

Also, with the way it's worded, an argument for biocomp to just be a flat .1 improvement to grade reductions can be made. 

http://i.imgur.com/z7GtoXh.png

since it always rounds down to the tenth, and applies to grade reductions, it effectively improves the multiplier by .1. 

.8 -10% and rounded down to the tenth would be .7, 
.7 -10% and rounded down to the tenth would be .6
.5 -10% and rounded down to the tenth would be .4

so it is in practice always a .1 grade improvement, regardless of the math involved to get to that point.

Except used, I guess. 1.25 -10% rounded down to 1 tenth would get you 1.1, a 1.5 improvement.
