### ISSUE TITLE
Karmagen: Spirit Bane

### ISSUE THREAD

**Issue by reyjinn** [chummer5a/chummer5a#1586]
### Environment
Chummer Version: 5.192
Environment: WIN10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
After having selected the adept quality and getting a magic rating I should be able to select the spirit bane negative quality.

### Actual behaviour
Am unable to select the Spirit Bane negative quality.

Upon further testing it appears that chummer does not allow adepts to take the Spirit Bane quality at all. Quote from pg85 of core:

> This quality may only be taken by magic users. Magic users may possess this quality for a type of spirit that is not a part of their magical tradition.

I posit that adepts are magic users.

**Comment by chummer5a** [comment]
Adepts have magical traditions? 

I'd prefer to see an errata on it before I make any changes, but as an interim you can just make an override file that adds Adept to the required list.

**Comment by reyjinn** [comment]
"Magic users may possess this quality for a type of spirit that is not a part of their magical tradition."

The tradition doesn't matter. Furthermore, Street Grimoire makes several mentions of adepts in the Magical Tradition chapter, examples include:
> They can be potent spellcasters and adepts. (from the christian theurge tradition)
>  primarily supported by adepts and mystic adepts (from hindu tradition)
> There are also a large amount of Muslim adepts (islamic tradition)

I'm sure there are more but I think this should be enough to make my point.

**Comment by chummer5a** [comment]
Implemented in current builds.
