### ISSUE TITLE
Optional Drone Modification Calculations not working properly / at all

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#1587]
Under the optional drone modification rules (page 128 Rigger5) upgrading drone armor by 3 or any attribute by 1 does not cost any modification points.

### Environment
Chummer Version: 5.129.17
Environment: Win7
Runtime: .NET 4.5.1

### Expected behaviour
Upgrading armor or any drone attribute under the optional rules to not consume a mod point when only raised 1 (3 for armor).

### Actual behaviour
Any increase costs mod slots, and armor actually costs 1 point per increase instead of 1 point per 3.

### Steps to reproduce the behaviour
Just try to use the specific drone modifications when the drone modification rules are activated under the optional rules.

**Comment by chummer5a** [comment]
Can't replicate the behaviour. You are using the modifications tagged with (Drone), yes?

**Comment by MaraFaye** [comment]
Well, I upgraded to the latest Nightly build and now I can't replicate it anymore either so I guess it got fixed between me posting this and the new update. Only thing that is still left that if you use the dropdown menu you can select any modification but the informational panel on the right won't update anymore.

**Comment by chummer5a** [comment]
Can't replicate that either, but at a guess you're somehow silently trapping an exception from one of the modifications. Is it from/to all categories, or is there a specific one that causes it to happen?

**Comment by rhockett94** [comment]
Trying to modify drone arms with cyberware throws up errors too
