### ISSUE TITLE
House Rule Request: Spend Karma on Skills before Priority Points

### ISSUE THREAD

**Issue by blogg10** [chummer5a/chummer5a#1588]
Essentially what it says in the title; I find it odd that there is an option for spending karma before priority points on Attributes, but not on skills.

**Comment by chummer5a** [comment]
Honestly I find both rules offensively munchkin so I didn't put a large amount of diligence into it in the first place. Shouldn't be particularly difficult to implement though.

**Comment by DelnarErsike** [comment]
This was implemented in the nightly a few commits ago.
