### ISSUE TITLE
Lots of items from multiple books are missing

### ISSUE THREAD

**Issue by swordmania** [chummer5a/chummer5a#1589]
Like the title says, there seems to be lots of items missing form multiple books. For example, there are cyberdecks that shows in the gear.xml but not in chummer itself. Same thing happens with vehicle.xml. I Don't know exactly what else is missing but I think its something worth looking into.

**Comment by chummer5a** [comment]
Availability is probably over the default limit. If you don't have restricted gear, those items aren't shown.
