### ISSUE TITLE
Trying to open the Skills Tab spits out an exception error message

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#159]
Maybe related to #157 ?

Details of the error give me this (sorry for the german parts, I guess it takes that from the system language):

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Wert 0 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei Chummer.SkillControl.SkillControl_Load(Object sender, EventArgs e) in m:\Coding\chummer5a\Chummer\SkillControl.cs:Zeile 65.
   bei System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   bei System.Windows.Forms.UserControl.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   bei System.Windows.Forms.TabPage.set_Visible(Boolean value)
   bei System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   bei System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.TabControl.WmSelChange()
   bei System.Windows.Forms.TabControl.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18444 built by: FX451RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
Chummer5
    Assembly-Version: 0.5.162.0.
    Win32-Version: 0.5.162.
    CodeBase: file:///C:/Users/Haekel/Desktop/Release/Chummer5.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408 built by: FX451RTMGREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408 built by: FX451RTMGREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34238 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34234 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408 built by: FX451RTMGREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408 built by: FX451RTMGREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408 built by: FX451RTMGREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll.
----------------------------------------
System.Windows.Forms.DataVisualization.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.18408.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization.resources/v4.0_4.0.0.0_de_31bf3856ad364e35/System.Windows.Forms.DataVisualization.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle Ausnahmefehler an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by chummer5a** [comment]
Hrm. Yeah, looks like the same fault. 5.163 will be finished shortly,
should clear it right up.

2015-04-20 22:06 GMT+10:00 Haekel <notifications@github.com>:

**Comment by Haekel** [comment]
I still get that error, btw.

http://pastebin.com/12KpztKM

**Comment by chummer5a** [comment]
Nuts. Can you upload your character file somewhere?

**Comment by Haekel** [comment]
http://a.pomf.se/nyqypn.chum5 

That's the char in question.  He's been through most of your updates since Run Faster, maybe something got stuck somewhere in the gears?

**Comment by chummer5a** [comment]
More than likely. I'll take a look first chance I get.

**Comment by Haekel** [comment]
Played around a bit.   Recreated the char from an earlier version (outside of career-mode), saved as carrer-mode, worked fine.  Until I spent some karma on skills and saved again.  On reopening the char, the error is back, hurrah. 

I'm back to pencil and paper for the time being, I'm afraid.

**Comment by Haekel** [comment]
Okay.  Wasted another two hours, recreated the char from scratch, no data from the old one, using only the most recent version of Chummer.  I still get the same error after I put the char into career mode. This is not some remnant of porting the char through too many versions.

http://a.pomf.se/uxrqql.zip (.chum5 files before and after switch to career mode)

**Comment by chummer5a** [comment]
Okay, found the problem. Part of the cleanup code for skill points if
you're in karma build didn't have a wrapper for not being in career mode.
Fixed in the next build. Sorry for the delay.

**Comment by chummer5a** [comment]
Resolved in 5.166.
