### ISSUE TITLE
Links to pdf books in settings

### ISSUE THREAD

**Issue by amoeban** [chummer5a/chummer5a#1590]
Most of the qualities, skills etc have book and page reference.

So if the user can add the path to the selected books he have in pdf format, you could have quicklinks from the quality/skill and open the right pdf at the specific page.

**Comment by chummer5a** [comment]
Already does. Set the path to the book by selecting it in the options menu, set your pdf parameters, then click on the source label of the item. Should open the pdf up in whatever application you prefer at the appropriate page.

**Comment by amoeban** [comment]
Damn it, I have totally missed this! Sorry, found it!

**Comment by Sephyr** [comment]
not wanting to add unnecessary issues and this seemed to be in the closest category regarding this;

when one has set up their PDF reader and rulebook PDF location, clicks on a pagelink in chummer the PDF viewer (Acrobat Reader DC in this case) opens nicely on the proper page.
However, when clicking on a different or same page-link in chummer the application "thinks" for a second and nothing happens (one would expect the reader application to either jump to the linked page or open a new document on linked page).

Is this related in some way to the Reader DC settings/application? (tested in both nightly 5.192.27 and stable 5.192.0)
What am i missing here :(

I can make a new issue if this is not how its intended to work.
