### ISSUE TITLE
Character Handedness Request

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#1591]
It would be nice if the handedness drop-down on the character info page included ambidextrous.

**Comment by chummer5a** [comment]
From memory, if you have the ambidextrous quality it already removes the offhand penalty in the weapon dicepool logic

**Comment by Nightghaunt** [comment]
This isn't about the the dice pool mod. It's about the drop-down listing. It has left handed and right handed but not ambidextrous. If you character has the ambidextrous quality or the bilateral coordination co-processor and are effectively ambidextrous it would be nice to have it show the correct handedness and not left or right handed when they aren't.
