### ISSUE TITLE
Differing Statlines?

### ISSUE THREAD

**Issue by menonaa** [chummer5a/chummer5a#1592]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.190.0
Environment: Windows
Runtime: .NET 4.5.1

### Expected behaviour
Two sheets with the same build have the same stats

### Actual behaviour
one has about 4 more dice than the other

### Steps to reproduce the behaviour
Create a Nocturn in priority mode, with attributes A metatype B magic C resources D skills E
take the exeptional attribute(AGI) quality and max out agility
take the adept powers improved attribute agi(3) and improved ability (Blades)(4)
take the bioware reflex recorder (blades) and muscle toner(used)(R1)
take a Qi focus, force 3, with improved ability(blades) and a weapon focus force 3 on a horizon flynn rapier with personalized grip
### Link to affected character file
(Enter text here)

[New Compressed (zipped) Folder.zip](https://github.com/chummer5a/chummer5a/files/947885/New.Compressed.zipped.Folder.zip)

**Comment by chummer5a** [comment]
Ther current foci setup has some issues with discarding power-based improvements properly when you change the rating on a focus; the new power and focus system will amend this behaviour, but for now the simplest fix will be to remove the improvements manually.

**Comment by OLStefan** [comment]
This may be fixed in the latest Nightly, please check if that still occurres or not.
