### ISSUE TITLE
Activating "run faster" breaks negative qualities

### ISSUE THREAD

**Issue by M-marshall** [chummer5a/chummer5a#160]
While the "Run faster" source book is activated attempting to add negative qualities produces an error message and closes the window
![capture](https://cloud.githubusercontent.com/assets/9201428/7242665/7cda1f40-e7bc-11e4-8efa-26ff05e58bfd.PNG)

**Comment by chummer5a** [comment]
Can you expand the details window? 

Also, if you have any of those custom files from the shadowruntabletop boards, remove them. They tend to cause crashes. Everything from there has either been merged into the core files or is currently irrelevant.

**Comment by M-marshall** [comment]
http://pastebin.com/0jBCRFT5

That's the output from the details window, not using any extra's just core files enabled in the menu.

**Comment by chummer5a** [comment]
Okay, it's the Blind (Mage) quality. I need to add a try-catch for whether the character has access to adept powers before trying to enumerate powers.

**Comment by chummer5a** [comment]
Resolved in 5.163.
