### ISSUE TITLE
Missing Weapon Accessory Ammo Skip

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1603]
### Environment
Chummer Version: 5.192.34
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Ammo Skip being available for all weapons with drum or cylinder magazine (i.e. many Pistols (Revolver), SMG (Ares SIGMA 3), Assault Rifle (Krupp Arms Kriegfaust), Shotguns (Enfield AS-7, ...))

### Actual behaviour
Ammo Skip only available for Assault Rifle (Kriegfaust) and Shotguns

**Comment by chummer5a** [comment]
Ammo Skip requires an Under mount slot. Revolvers and SMGs don't have an Under slot, so no ammo skip. Working as intended, yell at CGL for forcing it into a slot that the bulk of the weapons don't have. 

If you'd like to change that behaviour, I'd suggest creating an [Override File](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files), finding and copying the Ammo Skip mod, and changing its mount slot to Internal or empty (`<mount />` or `<mount></mount>`).

**Comment by Sturmkind** [comment]
I honestly didn't know that. Just looked it up and found both the table in Hard Targets for the slots used and re-read the entries in Core as to what weapons have what slots.

You never stop learning, I guess ;) 

Sorry I opened an issue for something that arose from my lack of knowledge and not from a bug in the software. And thanks  for the suggested modification to still enable it. I don't think I will use it, as I try to stay as close to the rules as possible, but nice gesture nevertheless.
