### ISSUE TITLE
Cyber limb customisation cost with grade and small avail bug

### ISSUE THREAD

**Issue by HiddenBoss** [chummer5a/chummer5a#1607]
### Environment
Chummer Version: 5.192.0
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
adding a Cyber limb to character then using add as plugin to customized stats, costs of the arm goes up by 5000y per Stat and avail +1 per stat

### Actual behaviour
adding a Cyber limb to character then using add as plugin to customized stats, costs of the arm goes up by 5000y*grade per Stat and avail +1 per stat but showing as (grade+1 per stat) untill you add it then just +1 per stat
### Steps to reproduce the behaviour
same as Actual behaviour.
### Link to affected character file
found it just playing about with cyber limb costs, not saved it to a character, can save if needed.

**Comment by chummer5a** [comment]
I'm not sure I see the problem, can you provide a screenshot to explain the problem as you can see it? As far as I can see the math all checks out properly.

**Comment by HiddenBoss** [comment]
It looks like i wrong about this, had some people tell me that chummer was wrong but a lot more people tell me that chummer doing it right, sorry.
