### ISSUE TITLE
Updating Street Grimoire spells with errata

### ISSUE THREAD

**Issue by Limette23** [chummer5a/chummer5a#161]
http://cdn.shadowruntabletop.com/wp-content/uploads/2014/09/E-CAT27003E_SG-Errata.pdf?4713c7 - Errata link

1)The Street Grimoire errata came out and there were a lot of changes to drain values and ranges:

DRAIN:

Corrode [Object] - F – 5
[Critter] Form - F – 4
Melt [Object] - F – 3
Pulse - F + 3
Slaughter [Metatype/species] F – 2
Slow Vehicle - F + 1
Sludge [Object] -  F – 1
Turn to Goo - F + 3

Range:

Catalog - T (A)
Chaff- LOS (A)
Fashion - T (A)
Increase/Decrease Noise - LOS (A)
Insecticide [insect spirit] - LOS (A)
Mass [Sense] Removal - LOS (A)
Spatial Sense  - T (A)
Spatial Sense, Extended - T (A)
Stench - LOS (A)

2) "Pollutant Wave" should be "Indirect, Area, Elemental" instead of "Indirect Elemental"
3) DESTROY [VEHICLE] TYPE CORRECTION - The spell type should be changed from M to P
4) INSECTICIDE TYPE CORRECTION - The spell type should be changed from P to M.
5) RADIATION BEAM - Change “(Direct, Area)” to “(Indirect, Elemental)”
6) RADIATION BURST - Change “(Indirect, Elemental)” to “(Indirect, Area, Elemental).”
7) HYSICAL CAMOUFLAGE - Change the spell type from M to P.

**Comment by chummer5a** [comment]
Resolved in 5.163.
