### ISSUE TITLE
Adding Qi Foci crashes and/or miscalculates

### ISSUE THREAD

**Issue by cjnolen** [chummer5a/chummer5a#1610]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.37
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Adding a Qi Focus should reflect appropriately in the Adept Powers tab by adding Power Points (without comparing them to the MAG score) or by adding/modifying powers for free.  Or whatever.

### Actual behaviour
Bonding to a Qi Foci almost always crashes the system, and when it doesn't the Power Point calculations are often wrong. Adding a Force 1 Foci should only gain me .25PP, but when I added an Adrenaline Boost foci is gave me .5PP.  Worse, when I unbound, it left me with that .5PP.  If I add a Focus 6 Foci and bind it to Improved Reflexes 1, it crashes.  I choose this one because it's explicitly stated on page 319 of the core rulebook that Improved Reflexes 1 should require a Force 6 if you have no points already in it.

### Steps to reproduce the behaviour
- Add a Qi Focus rating 6
- Bing the Foci
- Select Improved Reflexes 1
- Kaboom goes Chummer

**Comment by chummer5a** [comment]
Qi Foci are currently a mess, I've started burning down the whole current system for it but it's still got a bunch of teething troubles. Do hope to have it fixed soon, but no firm ETA as yet.
