### ISSUE TITLE
Inconsistent Spell Ranges and Durations

### ISSUE THREAD

**Issue by dashifen** [chummer5a/chummer5a#1612]
Hey all!

Within the spells.xml file, there are a variety of inconsistencies in the range and duration.  For example, there's both a range of T and of Touch.  Similarly, there's both LOS (A) and LOS(A).  With respect to duration, there's a single spell with a duration of 1 which it should be an I.  

Shall I fork the project and submit pull requests to clean up this sort of stuff as I find it (I'll be analyzing most of the XML files over the course of the coming weeks)?  Would changing these have an adverse effect on Chummer and I should just make my app flexible enough to handle them?

Thanks,
Dash

**Comment by chummer5a** [comment]
No adverse affects from our end, but the Touch range should definitely be changed to T. Spacing between the LOS isn't a big deal from our perspective, but a more consistent look is best, I'd probably lean towards LOS (A) over having it concatenated.

**Comment by dashifen** [comment]
What about spells that lack GUIDs?  Looks like the SSp spells don't have 'em.  Do you all need to generate those, of if I find ones with missing GUIDs, shall I add them in to create canonical IDs for them?

**Comment by chummer5a** [comment]
That's interesting, the XSD should have been screaming about that. Technically they're not necessary, but at some point I intend to shift everything to use ID pointers instead of names, I still don't trust using the names in that way, Anyhoo, if you want to do it feel free, otherwise I'll attack it with a rake in a bit.

**Comment by dashifen** [comment]
I'm on it.

**Comment by dashifen** [comment]
https://github.com/chummer5a/chummer5a/pull/1613

**Comment by chummer5a** [comment]
Cheers, thanks.
