### ISSUE TITLE
Chummer5 fails to open in existing monitors after removing a monitor, becoming inaccesible

### ISSUE THREAD

**Issue by Espherjan** [chummer5a/chummer5a#1615]
### Environment
Chummer Version: 5.192.0
Environment: Windows 10
Runtime:.NET 4.5.1

### Expected behavior
When opening Chummer5, it opens in an existing/available monitor

### Actual behavior
If Chummer5 was last closed in a monitor that is no longer plugged in, Chummer5 becomes inaccessible until you install a new instance (no clue which particular file in chummer dictates this behavior and failed to find it), or you reconnect to the disconnected monitor. This is particularly an issue with those using laptops with external monitors, or laptop docks (with external monitors), that are not always attached. This issue is not reproducible in any other program (that I have installed), so I assume it is a Chummer5 issue. Manually attempting to "Move" the screen (using shift+rclick on the taskbar icon), does not allow you to move it on screen.

### Steps to reproduce the behavior
Connect a monitor. Open Chummer5, move it to this monitor. Close Chummer5. Disconnect the monitor. Open Chummer5, you should see it open off screen.

### Link to affected character file
No character file was affected by this issue.

**Comment by chummer5a** [comment]
Hrm. That's interesting, I didn't think I ever coded in sticky positioning. You should be able to use the Win-Left/Right key combinations to move it around, but I'll take a look and see what's causing it.

**Comment by Espherjan** [comment]
I just tried using the Win-Left/Right combo, does not work either. I have searched all over online and have tried every suggestion I can find. If I don't move it to my laptop before disconnecting the monitors, it is entirely inaccessible, aside from the taskbar icon.
