### ISSUE TITLE
Possible Incorrect Minotaur Attribute

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#1618]
I don't know if this is right or wrong but here's what I am seeing. I have a Minotaur character I made awhile back on an earlier version (don't know which) and I am currently remaking him in version 5.192.13

In the earlier version it shows his base body at 6
In the new version it shows it at base 5

The Run Faster I have shows it at 6 and I can't find any errata that says different. Is 5 or 6 the correct base value?

**Comment by chummer5a** [comment]
It's working properly as 6/11(15) in the latest nightlies, could you please try with that?

**Comment by Nightghaunt** [comment]
Looks good. Thanks!
