### ISSUE TITLE
Issue viewing adept powers with pre .162 chum file

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#162]
Adept with warriors way that was created before .162 cannot have its adept powers viewed.

When tab is clicked it results in a small window that displays "0" and nothing else.

When that window is closed it reappears, the program cannot be accessed or closed when in this state.

**Comment by Neocyberman** [comment]
Oh strange new development!

I waited a bit with the program in that state then closed the dialog box and the program went back to normal.

**Comment by chummer5a** [comment]
Left a debug value in from testing the focus level stacking issue. Closing
it shouldn't stop the program from validating though. Will investigate
later.

**Comment by chummer5a** [comment]
Should be resolved in 5.163.
