### ISSUE TITLE
Ammo Skip system cannot be put onto certain guns

### ISSUE THREAD

**Issue by RayleonardArhka** [chummer5a/chummer5a#1622]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Tried to put Ammo Skip System on a weapon- Accessory is supposed to be usable on anything with a cylinder or drum magazine.

### Actual behaviour
Ammo Skip does not show up as an accessory that could be put on it. Weapon already has smartgun system.

### Steps to reproduce the behaviour
Tried to add accessory by right clicking a bought Ares Sigma 3, option does not pop up.

**Comment by chummer5a** [comment]
Sigma 3 doesn't have a Bottom slot, which the ammo skip system occupies. This largely makes ammo skip completely useless, but eh. It's RAW.
