### ISSUE TITLE
Custom Knowledge Skill Types Not Saving

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#1624]
When I add a custom skill and set its type it doesn't save the type. For example I added Greek knowledge skill and set the type to Language. When I saved the file and reopened it the type was blank. If I reset it to Language, save it and reopen it. Blank again. I set a custom Knowledge skill for Area Knowledge: New Orleans and set it to Street. Saved and reopened. Blank.

**Comment by chummer5a** [comment]
Can't replicate it. Can you please provide a copy of the save file?

**Comment by Nightghaunt** [comment]
Sure. 
[Bullseye 2.0 Revised.chum5.zip](https://github.com/chummer5a/chummer5a/files/986107/Bullseye.2.0.Revised.chum5.zip)
