### ISSUE TITLE
Martial Art Weirdness

### ISSUE THREAD

**Issue by upwardthinking** [chummer5a/chummer5a#1625]
### Environment
Chummer Version: 5.192.0
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
Marital Arts Two Weapon Style Attack technique should per Run & Gun p. 141 add 1 accuracy and DV to the blades used

### Actual behaviour
Martial Arts Technique Two Weapon Style Attack has no effect on accuracy and DV of sword damage listed on character sheet

### Steps to reproduce the behaviour
Take martial arts with this technique (Fiore Dei Liberi e.g.) and add two weapon style attack technique

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Chummer doesn't generally do conditional bonuses; since we currently can't know when you are or are not using multiple weapons at once or which ones, we don't create a bonus for it.

**Comment by upwardthinking** [comment]
Can we add a note next to it, indicating what the technique does for conditional bonuses like this? Is that too labor intensive?

**Comment by chummer5a** [comment]
It's more that there's a line I'm hesitant to cross with regards to how much content I can provide directly from the books. The simplest method from our perspective is either to use the Notes function or that you set up your PDFs in Chummer's options and then click the Source button to open the PDF directly to that page, but we're putting some thought into how we could pull that data directly from the PDF, which gets around the legal issues of providing copyrighted content.
