### ISSUE TITLE
Critical Strike Adept Power not affecting DV

### ISSUE THREAD

**Issue by upwardthinking** [chummer5a/chummer5a#1626]
### Environment
Chummer Version: 5.192.0
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
Critical Strike should increase DV of weapons using the skill by 1

### Actual behaviour
Taking Critical Strike has no effect on the DV of the weapon that I can see

### Steps to reproduce the behaviour
Make Adept Character, buy a sword and take critical strike power for the Blades skill

**Comment by chummer5a** [comment]
It seems to be increasing the DV of the weapons by 1 properly, so far as I can see. Can you upload a character that should have the DV increase, but doesn't?

**Comment by upwardthinking** [comment]
I double checks my math and my math was wrong, please disregard.
