### ISSUE TITLE
Add Quality causing crashes

### ISSUE THREAD

**Issue by PeanutBudderBabe** [chummer5a/chummer5a#1627]
### Environment
Chummer Version: 5.192.64
Environment: Windows 10
Runtime: I dont know, it is probably .NET 4.5.1

### Expected behaviour
Open a way to add quality's. 

### Actual behaviour
So I'm trying to build a new character right? And that means I need karma right? So I click the 'Add Quality' button and then WABBAMM it crashes.

### Steps to reproduce the behaviour
Click the  'Add Quality' button in the 'create a character' stage of things.

Crash followup id = e2a1fb10-2206-4db1-b18a-90c3ddc17add

Note: do have the character sheet saved if yall need it, just let me know what format yall want it in 'cos github wont let me add it in .chum5

**Comment by chummer5a** [comment]
You should be able to upload it as a zip archive; I haven't been able to replicate the issue in current nightlies, could you test with 5.192.70 from get.chummer.net?
