### ISSUE TITLE
 Issue: Adding Plug-Ins to Custom Items Causes Crash

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#1629]
### Environment
Crash ID: d10727d2-20dc-403a-91fb-55a1bde55bfd
Chummer Version: 5.192.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Adding Plug-Ins to Custom Items to bring up standard Plug-In menu

### Actual behaviour
Causes Immedeate Crash

### Steps to reproduce the behaviour
Right click on a custom item and select "Add Plugin"

**Comment by chummer5a** [comment]
Fixed in latest commit.
