### ISSUE TITLE
Possible Character Roster Issue or Enhancement

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#1632]
I don't know if this is the intended behavior but its really annoying. You can set the Character Roster watch folder which is great. I like having the watch folder list on the Roster. But the problem is that after you open a character file the watch list goes away and all you see is the Recent Characters list. If you want to open another character from the watch folder that's not on the Recent Characters list you have to go back and use the open file dialogue window. It would be nice if the Watch Folder list stayed there and didn't go away after opening a file.

**Comment by chummer5a** [comment]
Oops, I broke that a while back. Will fix.

**Comment by Nightghaunt** [comment]
Ah, cool. Ok thanks!
