### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1634]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 192.84
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Page number to be the exact page the Vehicle Mod is on.

### Actual behaviour
All are set to page 154. This is the beginning page for the Vehicle Mods.

### Steps to reproduce the behaviour
1) Start a new character or use old one.
2) Purchase a vehicle for the character,
3) Modify the vehicle and notice the page is not the exact page.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
I suspect this resolved in the latest commit, the data is accurate. Could you please try with 5.192.87 when it's available? Should be in the next couple of minutes.
