### ISSUE TITLE
Issue with Lifestyle Quality

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1637]
### Environment
Chummer Version: 5.193.0
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Extra Secure adding 20% to Lifestyle cost

### Actual behaviour
Extra Secure adding nothing to Lifestyle cost

### Solution
In Livestyles.xml, in the code for the quality Extra Secure, change 
< multiplierbaseonly >20< / multiplierbaseonly > to
< multiplier >20< / multiplier >

**Comment by chummer5a** [comment]
I can't replicate this issue; multiplierbaseonly applies to the base cost of the lifestyle, while multiplier also affects quality costs.

**Comment by Sturmkind** [comment]
Strange. For me this issue only comes from this one quality. All others seem to work properly and only have the < multipler> tag instead of the baseonly addition. 

Does the quality add the 20% additional lifestyle cost for you? For me, I can add the quality, but the monthly costs stay the same as before adding it (so no +20%)
