### ISSUE TITLE
No Code Of Honor Apart From Avenging Angel

### ISSUE THREAD

**Issue by ChopperSniper** [chummer5a/chummer5a#1638]
### Environment
Chummer Version: 5.193.0
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Expected the Codes of Honor to be available in the Negative Qualities list

### Actual behaviour
Only Code of Honor: Avenging Angel is available

### Steps to reproduce the behaviour
Just check the Negative Qualities list, it's not there.

### Link to affected character file
It's not a singular file, it's every file, it's not showing up for any.

**Comment by chummer5a** [comment]
Code of Honor uses a selecttext value to allow the user to enter their own value. Avenging Angel and Like a Boss have different prerequisites and cost values, so they're included as separate files. There's no reason the base quality should be missing though.
