### ISSUE TITLE
No skill point values in Karmagen

### ISSUE THREAD

**Issue by Limette23** [chummer5a/chummer5a#164]
After loading up a pre .163 chum-file, I can't access the skillpoint value anymore and only see the skill karma value. But in the final dice calculation chummer recognizes the old values. 

Like: Skill Rating (1) + INT (5) = 6

Also the karma is correctly calculated in the sidebar.

**Comment by chummer5a** [comment]
Cleaned up in 5.164. Since there aren't any skill points per RAW in point buy, the options were disabled. It was intended that suppressed values would be set to zero to clean this up. The cleanup-code isn't the cleanest however, and doesn't remove points from active skills.
