### ISSUE TITLE
Metatype Maximum Magic parsing error

### ISSUE THREAD

**Issue by TesserWreck** [chummer5a/chummer5a#1647]
### Environment
Chummer Version: 5.193.0
Environment: Windows 10

### Problem
When making a custom metatype with a magic/resonance maximum score and the character takes a magic priority that sets it above the maximum, the character creator will set said character's magic/resonance score above the maximum. This becomes a major problem when opening a character file as it causes the program to crash stating "Value of '<lower maximum value>' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'."

### Steps to reproduce the behaviour
I discovered this bug when making custom metatypes for Shapeshifters.

### Affected data files
[shifter.zip](https://github.com/chummer5a/chummer5a/files/1015765/shifter.zip)

**Comment by chummer5a** [comment]
Well it shouldn't be doing that, but why're you setting their MAG maximum to 5?

**Comment by TesserWreck** [comment]
In Run Faster on page 105 it shows that shapeshifter's MAG stat as either 1/5 or 1/4 depending on the animal chosen.

**Comment by chummer5a** [comment]
![image](https://cloud.githubusercontent.com/assets/11448441/26277530/ec8d7cfc-3dcc-11e7-94fe-c5738083031e.png)

Nah, that's their Edge stat. It got errata'd in the PDFs.

**Comment by TesserWreck** [comment]
Reworked the stats to match up with the second printing and it seems to be fixed; however, characters that were created using the old stats still have their stats show as such.

P.S. It would be nice if there was a way to change a character's initiative dice.

**Comment by chummer5a** [comment]
You can use the initiativedice improvement type to add extra dice. 

As for the stats, those are assigned when the character is made. Reapply Improvements *might* work, but I doubt it.

**Comment by TesserWreck** [comment]
Just found a bug related to the files used. Attempting to change the priority settings of a character using the custom metatypes will result in a crash stating "Object reference not set to an instance of an object."

**Comment by chummer5a** [comment]
I can't replicate the issue with the custom metatypes file; can you upload your file for me to take a look at?
