### ISSUE TITLE
Skilljack cost is wrong

### ISSUE THREAD

**Issue by goofdad** [chummer5a/chummer5a#1648]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0.0
Environment: Linux, Windows 10
Runtime: ???

### Expected behaviour
RAW: Table->Shadowrun Core p453 states Skilljack costs at Rating x 20,000 nuyen.

### Actual behaviour
Chummer data/cyberware.xml lists cost at Rating x 10,000 nuyen

### Steps to reproduce the behaviour
Create a character with Skilljacks

**Comment by chummer5a** [comment]
Chrome Flesh stealth-errata'd it.

**Comment by goofdad** [comment]
Can we change the page reference (or add a reference) to Chrome Flesh to keep this from coming up again?
