### ISSUE TITLE
 Issue: Rituals for Adepts

### ISSUE THREAD

**Issue by Wordster** [chummer5a/chummer5a#1652]
### Environment
Crash ID: 6f62b26c-2202-4572-960e-aa38b0304372
Chummer Version: 5.193.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Er. Please edit this so there's some actual detail and reopen it.
