### ISSUE TITLE
Bugged Improved Reflexes Adept Power

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1658]
### Environment
Chummer Version: 5.193.35
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Improved Reflexes 3 costs 3.5 PP and removes its bonus to Initiative and Reaction when deleted

### Actual behaviour
Improved Reflexes 3 costs 8 PP upon closing and re-opening a character with the power and doesn't delete its bonuses when removed (leaving behind things like REA 1 + (3)), which stacks to something like Reaction 1 (10) = REA (1) +  (3) +  (3) + Improved Reflexes (3)

### Steps to reproduce the behaviour
Create an adept, give him the improved Reflexes 3, close the character tab, open the character again, look at adept powers. Delete Improved Reflexes 3, look at Reaction value and initiative

**Comment by chummer5a** [comment]
Can't replicate it. Can you please save your character file to a zip file and upload it here?

**Comment by Sturmkind** [comment]
sure, although I somehow can't upload a .zip file, here is a link:

https://www.dropbox.com/s/28ci39fnh745lxw/Test.zip?dl=0

**Comment by chummer5a** [comment]
[Test Adept.zip](https://github.com/chummer5a/chummer5a/files/1018095/Test.Adept.zip)

Fixed version of the file for you as well without the extra improvements.

**Comment by Sturmkind** [comment]
sadly I am still experiencing half of the bug in that the Improved Reflexes Power seems to use up 6 Power Points for the first level, but only after you close Chummer and Reopen it.

So if you make an adept and give him Improved Reflexes 1, it shows as taking up 1.5 Power Points, but after closing the Tab for the character (or Chummer as whole) and re-opening the character after that, it shows Improved Reflexes taking up 6 Power Points. I'll attach an image of that.

![imp reflexes takes 6](https://cloud.githubusercontent.com/assets/23245979/26341066/0d1d530e-3f92-11e7-8626-6960dde8172a.JPG)

**Comment by chummer5a** [comment]
Hm. That's odd. If you change the rating up and down, does it go back down?

**Comment by Sturmkind** [comment]
nope. The base stays 6 for rating one and then goes up to 8 for rating 3 and back to 6 for rating 1

**Comment by OLStefan** [comment]
Problem is while loading a saved file, the saved extracost of "0,5" (strongly assume german user here) is read as "5". The problem is in the TryGetDecFieldQuickly-method which reads it as 5, even while the GlobalOptions.InvariantCultureInfo is used.

**Comment by Sturmkind** [comment]
Your assumption would be right ;). Is this a problem that happens primarily for german users?

**Comment by OLStefan** [comment]
The problem is that english system use a decimal point ('.') while german uses commas (',') which causes problems when reading decimal numbers from files. English just recognise the point as a marker for decimals, german (and other) systems need a comma for that.

**Comment by Sturmkind** [comment]
seems to work properly as of the latest Nightly build (5.193.43)
