### ISSUE TITLE
crash on crystal qualities

### ISSUE THREAD

**Issue by khadgar567** [chummer5a/chummer5a#1659]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: nightly last version
Environment: windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
added quality

### Actual behaviour
crashes the program

**Comment by chummer5a** [comment]
Can't replicate it. What's the error say?

**Comment by khadgar567** [comment]
I send a normal crash report to about two or three hours ago

**Comment by chummer5a** [comment]
I don't have access to the crash reports at the moment unfortunately. @joha4270, got it handy?

**Comment by joha4270** [comment]
Only crash on latest nightly references synthetic cyberlimbs. If we widen the range to anything uploaded recently that isn't 193 it gets to large to manually check.

I _need_ that CrashID to find it

**Comment by khadgar567** [comment]
arcane armorist quality never adding to positive qualities by the way

**Comment by chummer5a** [comment]
That's not from any book I'm aware of. Can you please also provide something so that we can reproduce or trace the error with the crystal qualities?

**Comment by khadgar567** [comment]
forbidden arcana but i thing crystal quality problem is gone cuz i never test in 193 build cuz i cant find in the book
