### ISSUE TITLE
Crash on closing character tabs

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1660]
### Environment
Chummer Version: 5.193.36
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
after closing a character tab, the roster is shown

### Actual behaviour
after closing a character tab, sometimes the roster is shown and chummer continues to work properly, sometimes a crash happens

### Link to affected character file
sorry for german parts, I can help translate if necessary

![crash](https://cloud.githubusercontent.com/assets/23245979/26341151/7ad8a79a-3f92-11e7-8c47-4067a53f4c8a.JPG)

**Comment by OLStefan** [comment]
After changing Levels on Adept Power and closing the character, a last UpdateCharacterInfo() is called, while the character object is already set to null.

**Comment by OLStefan** [comment]
Another interesting thing that happens and i think might be related to this:

When changing Adept powers and saving manually, without further changes Chummer still tells me I have unsaved changes when closing the character/Chummer.
