### ISSUE TITLE
Cannot load all books

### ISSUE THREAD

**Issue by henryhiggins** [chummer5a/chummer5a#1666]
### Environment
Chummer Version: 5.193
Environment: Windows 10
Runtime: Not sure so probably NET 4.5.1

### Expected behaviour
Restarting chummer when loading all source books

### Actual behaviour
Program crashes and does not add books

### Steps to reproduce the behaviour
Open Chummer, Tools>Options, toggle on/off source books, ok

### Link to affected character file
(Enter text here)

**Comment by Calivan** [comment]
Same issue occurring local Winddows 10 64-bit computer, .NET 4.6.1. I've had to revert back to version 5.182.0.

**Comment by chummer5a** [comment]
I can't replicate this behaviour; does it still do it if you do it one by one? What's the crash error message?

**Comment by Calivan** [comment]
Yes, issue occurs when selecting one book at a time. Steps used on my end:

1. Tools -> Options
2. Check Data Trails
3. Click "Ok" button
4. Click "Yes" button on "Close Forms" dialog box
4.1. Dialog box text reads "Would you like to save changes made to your options?
5. Click "Yes" button on "Close Forms" dialog box
5.1. Dialog box text reads "Options are only enumerated on character load. Should we restart the application?
6. Chummer error dialog box appears, click "Close program" button.
6.1. Dialog box text reads "Chummer has stoped working" "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."
7. Behind step 6. dialog box "Open File - Security Warning" dialog box appears. "The publisher cannot be verified. Are you sure you want to run this software?
7.1. Software trying to run is \Chummer\CrashHandler.exe
7.2. This dialog box is closed when "Close program" button is clicked on step one.

Workaround discovered while reviewing.
On step 5 click "No" button, the book will be saved, but you have to manually restart Chummer.

**Comment by chummer5a** [comment]
Okay, so it only happens when you tell it to restart the application? Hrm. Well that definitely narrows it down, but I still can't replicate it. How do you launch Chummer? Directly from the exe, by opening a .chum5 file that's set to open in Chummer, etc.?
