### ISSUE TITLE
Magical tradition not translated in printouts

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1669]
### Environment
Chummer Version: 5.193.45
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The tradition name and the spirit types should be printed in the selected language.
For example, it should show "Schamanisch" instead of "Shamanic" or "Luftgeist" instead of "Spirit of Air".

### Actual behaviour
I created a schaman character with Chummer5a set to ui language German.
On the printout, the tradition name and the five ghost types for the tradition are shown in English.
I checked the de_data.xml file and it contains valid translations for the tradition names and the spirit types.

### Steps to reproduce the behaviour
Create a new character with language set to german
Make it a magican and select a trandition (I used "Schamanisch").
Open a printout.

**Comment by chummer5a** [comment]
Traditions aren't currently set to use the localised content. Will probably need a refactor to make Traditions into an actual class, currently everything just runs off the character class.

**Comment by holgerschlegel** [comment]
In the Chummer5a UI on the Spells and Spirits tab, the tradition is shown in german. Only the printout uses the english texts.
