### ISSUE TITLE
Overall bugginess of the latest Version(s?)

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1673]
### Environment
Chummer Version: 5.193.52 (all worked fine in 5.193.47, didn't test versions in between)
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Allocating Attributes reduces maximum attributes
Cyberware (...) changes augmented Attributes
Only 1 Attribute at maximum in character generation
displaying Special Attribute Points (for Edge/Magic/...)

### Actual behaviour
Allocating Attribute points doesn't reduce the maximum (i.e. always 20 of 20)
Cyberware does nothing for Val (Aug)
Every Attribute can be at 6/6 (Humans)
Special Attribute points not showing at all
corrupts any (previously working) files loaded into it nearly irreparably (thank god for the autosave feature)
many more

### Steps to reproduce the behaviour
Create new character, add attribute points or add special points or add Cyberware that augments attributes, ...

Example of the Common Tab of a new Character I just made (only for testing), who has Muscle Replacement 4 (Cyberware):
![test](https://cloud.githubusercontent.com/assets/23245979/26529025/56f62b34-43b8-11e7-9df0-7d89ce0b1280.jpg)
only things changed from a fresh download of the latest Chummer5a was enabling all source books

**Comment by Sturmkind** [comment]
narrowed it down to the 5.193.49 update where things started to be really wonky

**Comment by chummer5a** [comment]
Yeah, I got a bit impatient and pulled in the databoundattributes branch a bit earlier than I should have. Still needs a bit of extra work.

**Comment by Sturmkind** [comment]
still bugged, only not as much anymore ;)

Problems: 
- Special attributes still not recognized/used/...
- You can circumvent the attribute maximum by adding up to normal maximum of points via Karma (i.e. Troll with 10 Strength from attribute points can get another 10 from karma for total of 20), this only affects the natural rating, augmented still works fine (i.e. if above mentioned troll got muscle replacement 2 it would read STR 20(12))
- Raising attributes with Karma only costs Karma if the attribute is Physical (not for Mental or Special)
- Essence loss doesn't affect Magic/Resonance

**Comment by Sturmkind** [comment]
sorry to bring this up again ;)

Again many things now work properly, but 4 problems remain (as far as I see):
- Essence loss still doesn't affect magic
- Special Attribute points still aren't displayed anywhere (used to be on the side between the attribute points tracker and the positive qualities tracker)
- when maxing out an attribute first (i.e. Intuition) and then trying to get maximum Magic/Edge it opens a popup notification (only one attribute at maximum in character generation), the other way around (first Edge/Magic, then normal attributes works fine)

**Comment by chummer5a** [comment]
Most of it should be behaving now, but I haven't build the value labels to update dynamically when character attributes change yet.

**Comment by Sturmkind** [comment]
the issue with the maximum attribute applying to edge/magic still exists, as in if you have an attribute at maximum at chargen (i.e. Logic) you can't have another at maximum (i.e. Body, this is RAW). But if you try to get maximum Edge afterwards (as in, with already maxed Logic), the program doesn't allow it stating that only one attribute can be at maximum at chargen (when per RAW this doesn't apply to special attributes).
On the other hand this works fine if you max out Edge/Magic first and then Logic second

**Comment by Sturmkind** [comment]
making this into a new issue instead of always reviving an old one ;)
