### ISSUE TITLE
In Kama mode Attributes not charging karma

### ISSUE THREAD

**Issue by Pommanthebrit** [chummer5a/chummer5a#1675]
As said in the title as far as I can tell is all Attributes are not charging karma

### Environment
Chummer Version: (5.193.54
Environment: (Windows 10)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
(well I expect that there should be a cost)

### Actual behaviour
(there is no cost)

### Steps to reproduce the behaviour
(as far as I know just have the 5.193.54 version of chummer and try and go into the karma mode and try and increase attributes)

### Link to affected character file
(
[monger.zip](https://github.com/chummer5a/chummer5a/files/1034446/monger.zip)

)

**Comment by chummer5a** [comment]
I can't reproduce this in the latest nightlies. Could you please test with .56 or higher?

**Comment by Pommanthebrit** [comment]
I tried it with the new version of chummer it still happened so I checked my settings again and they were all  the defaults I then decided to reset them to defaults just in case and its just fixed it idk what did it but it worked
