### ISSUE TITLE
Sprites cannot have more than 10 services

### ISSUE THREAD

**Issue by cjrt** [chummer5a/chummer5a#168]
Post chargen, add a sprite and add services, it cannot go above 10

**Comment by chummer5a** [comment]
Fixed in 5.164. New maximum value: 79,228,162,514,264,337,593,543,950,335 because why not.

**Comment by DeastinY** [comment]
Q_Q just skip check on post gen :D

**Comment by chummer5a** [comment]
There isn't a check, it's just using the default numericupdown maximum. Go big or go home, basically
