### ISSUE TITLE
Chummer crashes trying to open a character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1682]
### Environment
Crash ID: 6eb5bcea-dbd0-4375-8c9e-844a006f630c
Chummer Version: 5.193.65
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Double clicking character on roster opens character.

### Actual behaviour
Chummer crashes and submission of crash fails.
Chummer also fails trying to open the chum5 file directly.

Other characters files do open.

### Steps to reproduce the behaviour
Try opening attached character either from roster or directly.

### Attached files
1) windows abend trying to open chum5 file
![screenshot - 2017-05-30 1_36_17 pm](https://cloud.githubusercontent.com/assets/17562417/26600006/1680f41a-4540-11e7-8892-dea2f73aa4e2.png)

2) Character file
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1039403/Character.file.zip)

3) Chummer dump file
fails because zipped crash file is 43mb - unzipped crashdump.dmp file alone is 119,525kb

**Comment by Lochabar** [comment]
The character file opens in version 5.193.19 (but not by 5.193.45)

**Comment by chummer5a** [comment]
It's choking while attempting to load an 'Excalibur Phaeton' vehicle which doesn't have an id field in the saved node or the vehicles.xml data node. Custom content, I assume?

**Comment by Lochabar** [comment]
It is.

So what do I need to add and where?
Do I need a customs_vehicle.xml file?

**Comment by chummer5a** [comment]
Either add an id field to the vehicle stored in your character file, or add the id field to the vehicle stored in the custom_vehicles.xml file. Either way will populate the appropriate id into the vehicle object, but that custom file is effectively invalid as it is right now, so it should be amended.

**Comment by Lochabar** [comment]
I added an id field to the character file and it can now be opened.
