### ISSUE TITLE
Issue: Exceptional Attribute quality doesn't increase attribute maximum

### ISSUE THREAD

**Issue by flowerygrackle** [chummer5a/chummer5a#1685]
### Environment
Crash ID: 7dcdc17d-7946-4aec-b21c-058f5732b4f3
Chummer Version: 5.193.65
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Selecting the Exceptional Attribute quality should increase the maximum of the selected attribute.

### Actual behaviour
It doesn't.

### Steps to reproduce the behaviour
1. Make a new character, generation stuff doesn't seem to matter.
2. Add the Exceptional Attribute quality.

**Comment by flowerygrackle** [comment]
Still not fixed as of 5.193.70 - you have to be able to increase or decrease the attribute selected with Exceptional Attribute for it to update and register the new maximum, but that is impossible to do if your character starts with Magic 6 and you select Exceptional Attribute (Magic).

**Comment by chummer5a** [comment]
Crap, yes. Sorry, see the problem. Will be fixed shortly.

**Comment by chummer5a** [comment]
Should be resolved in the latest commits.
