### ISSUE TITLE
Foci removed when opening character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1687]
### Environment
Chummer Version: 5.193.65
Environment: Windows 7 Home Premium
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Open character and existing foci are present

### Actual behaviour
Open character, presented with an error window, most foci removed.

### Steps to reproduce the behaviour
Open the attached character file.

### Link to affected character file
Foci list from earlier version - notice the total of bonded foci is 17.

![1 foci list 5 193 19](https://cloud.githubusercontent.com/assets/17562417/26638335/7fc9cc9c-45e7-11e7-8dc8-1e4ee5db2c8b.png)

Error window when opening character in latest nightly
![2 error message](https://cloud.githubusercontent.com/assets/17562417/26638376/952f7726-45e7-11e7-8cd1-906dcc2db715.png)

Foci list in latest nightly
![3 foci list 5 193 67](https://cloud.githubusercontent.com/assets/17562417/26638410/a697cc02-45e7-11e7-860c-3d2f9221d7f1.png)

Character file
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1041952/Character.file.zip)

**Comment by Lochabar** [comment]
Problem is not fixed in 5.193.68; Upon opening foci are not removed, but one is unchecked and cannot check it. Same error, MAGIC *5 is 30, foci total is still 17.
![foci list 5 193 68](https://cloud.githubusercontent.com/assets/17562417/26644936/0c7a2966-45fc-11e7-9821-d3232b925e38.png)

**Comment by chummer5a** [comment]
I can't replicate this in the latest build; still an issue for you?

**Comment by Lochabar** [comment]
Still happens in 5.193.76

**Comment by Lochabar** [comment]
This seems to be related to #1695 - Magic and Edge are been reduced to 1 when opened.
![attriutes changed](https://cloud.githubusercontent.com/assets/17562417/26766074/8d99e17a-494f-11e7-80e0-4fadc17890eb.png)

**Comment by Lochabar** [comment]
I checked the character file and the MAG and EDG attributes were missing. I edited them back and the character now opens correctly with the Foci list correct.

Not sure what happened with the character, but an earlier version not only had MAG and EDG but also had RES present.

Has anything been changed in Chummer that could caused attributes to be deleted?

**Comment by OLStefan** [comment]
There was an issue that Special attributes wouldn't be saved. Is that still the case for on the latest Nightly or was it just an old save file already affected by it?

**Comment by chummer5a** [comment]
One of the nightly versions didn't save special attributes properly. Fixed it quickly, but if your character was saved on that version it'd reload with a new MAG attribute.

**Comment by Lochabar** [comment]
It was a recent save file. Once I added the attributes back, I made a change using Chummer and saved the character. The attributes are still present.

**Comment by OLStefan** [comment]
So, this issue can be closed, right?

**Comment by Lochabar** [comment]
Okay.
