### ISSUE TITLE
Not all lifestyle details are printed

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1688]
### Environment
Chummer Version: 5.193.68 (and prior versions)
Environment: Windows 7 Home Premium
Runtime: (probably .NET 4.5.1)

### Expected behaviour
All lifestyle details printed

### Actual behaviour
Name of lifestyle, qualities, and notes are not printed

I've identified the problem with the qualities - the node name has been changed from "Quality" to "Lifestylequality"

### Steps to reproduce the behaviour
Print a character with lifestyle details

### Link to affected character file
This is from the printed character
![printed](https://cloud.githubusercontent.com/assets/17562417/26644309/e899d89a-45f9-11e7-8aa0-8689db7cb0ce.png)

This is the XML for the character
![xml content](https://cloud.githubusercontent.com/assets/17562417/26644330/fb30eff2-45f9-11e7-9cad-4be8fc0acf9f.png)

This is the XSL file with the node name changed
![xt lifestyles xslt](https://cloud.githubusercontent.com/assets/17562417/26644354/090800ac-45fa-11e7-939d-77360a3396cc.png)

**Comment by flowerygrackle** [comment]
I've noticed the names for the lifestyles aren't printed correctly, either. In Chummer it might be 'Medium ("High rise apartment")' but on the printed sheet it'll be 'Medium ("Medium")'.

**Comment by jonovotny** [comment]
Might be a similar issue, currently the standard output sheet does not list the sensor array of any vehicles. (It does in the Fancy Blocks sheet)

**Comment by Lochabar** [comment]
I see that the node names have been changed back to "qualities/lifestylequality".

The name field on the print now shows 'Medium ("High rise apartment")'.

The field "lifestylename" always appears blank, at least on the XML. Could you format it with just the name, i.e. containing: High rise apartment (no quotes or parentheses).
