### ISSUE TITLE
Is the translator working ?

### ISSUE THREAD

**Issue by DeastinY** [chummer5a/chummer5a#169]
Entered some values, there is no safe-button when editing - it does not safe anything :)

**Comment by chummer5a** [comment]
Changes are automatically saved into your language file, as far as I know. I've never had occasion to use it. Best bet is probably to make a change and see if it updates.

**Comment by DeastinY** [comment]
I tried it and nothing worked ):
So I assume it's broken, didn't see any code to it as well - so I'm using the pure XML files right now
(doing German btw)

**Comment by chummer5a** [comment]
I did a couple of tests and it's working for me. Not sure what could be wrong on your end.

**Comment by chummer5a** [comment]
Unable to reproduce any errors.  Assume it's working fine until I hear otherwise.
