### ISSUE TITLE
Enhancement Request: Spirit Reputation

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1692]
It occurs to me that Spirit Reputation is introduced as a mechanic in Forbidden Arcana, and I was wondering if including a 'ticker' similar to whats currently done with Street Cred/Notoriety (possibly able to display both positive and negative integers) for campaigns that choose to use it?  

Perhaps this might go better on the 'spells' tab, if it becomes desirable to track specific reputations based on individual spirit type, but I personally think that might be a bit much, unless the creation of a 'Spirit tab' is in the works somewhere.  
-Which, honestly, might be a really good idea to implement at a later time, as this could offer a lot more options for displaying spirit rules.

**Comment by OLStefan** [comment]
Small differentiation:

There is the Astral reputation from Street Grimoire, which influences normal Spirit Summoning.

And there is the new Wild Reputation from Forbidden Arcana, which influences interactions with Wild Spirits.

**Comment by chummer5hasanerror** [comment]
I was unaware that 2 forms existed.

Could both of these possibly be implemented in this fashion then?

**Comment by OLStefan** [comment]
That's why i made the differentiation.^^

I don't see why it won't be implemented, but there is a long list on things that need to be done.

**Comment by Teksura** [comment]
This would be really handy, either on the Spells and Spirits tab, or Character Info, along with Street Rep and the like (since mundanes can actually gain that, too.

**Comment by chummer5a** [comment]
Duplicated by #4042. Mostly finished in the AstralReputation branch.
