### ISSUE TITLE
Chummer 5.193.72 is messing up the Attributes

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#1695]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.72
Environment: Windows 10 Pro x64 1703 Build 15063.332
Runtime: .NET 4.7

### Expected behaviour
Open char and find everything like the last time i opened it

### Actual behaviour
open Char and find all Attribute are messed up.
it seems that the racial Minimum was added to the basevalue

### Steps to reproduce the behaviour
Open char im Chummer 5.193.71 - Attribute OK
Update to 5.193.72
Open same char, find messed up Attribute
downgrade to 5.193.71
everythings fine again
tested it on 2 computers

### Link to affected character file
[Moonlight-TEST.zip](https://github.com/chummer5a/chummer5a/files/1047967/Moonlight-TEST.zip)

**Comment by ReallyDarkMatter** [comment]
Just checked it with the .73 release, error is still there

**Comment by chummer5a** [comment]
Strictly speaking .71's the one that's screwy, it's not supposed to be storing your Base value as including the metatype minimum. I'll build in a shim to sort it out.

**Comment by ReallyDarkMatter** [comment]
The shim works for the normal Atribute, but not for Edge and Magic. Tested in .74
