### ISSUE TITLE
Undoing Expense causes Exception

### ISSUE THREAD

**Issue by cjrt** [chummer5a/chummer5a#170]
If you undo an expense, but have already removed the item it will throw an exception, as the object it was pointing to no longer exists.

Object reference not set to instance of object.

System.NullRefference.Exception: Object reference not set to instance of object
  at Chummer.frmCareer.tsUndoNuyenExpense_Click(Object sender, EventArgs e) in m:\Coding\chummer5a\Chummer\frmCareer.cs:line 13820

If I knew enough C# to trivially add check for null I would make a pull request, but I have already wasted today playing Shadowrun when I have exams coming up.

Plus, if the object has already been removed should they be able to undo the expense? Or can we assume that if they're trying to refund the expense they have fair reason? Perhaps a pop up to say the item has already been removed, do they want to just revert the expense? These are design decisions I am less confident in making.

**Comment by chummer5a** [comment]
Removing an item is already supposed to remove the improvement. That's a
bit weird.

**Comment by cjrt** [comment]
Oh is it? How do I remove something without refunding it then? i.e. I buy a
cyber deck, it gets trashed/I lose it, I don't want that to be refunded
when I remove it from inventory?

**Comment by DeastinY** [comment]
As far as I understood that's the default behavior. You delete the items and don't get the money - you delete the expense and you get the money back. At least that's what I'd expect (and what I verified so far). When removing expenses you always refund, as this is what removing an expense does. And if you just delete your cyberdeck from the geartab it's that you simply don't have the thing anymore (you still bought it once, so the expense is still there)

**Comment by chummer5a** [comment]
Yeah, I had a brainfart there, was thinking of improvements. I'm having trouble replicating the problem in the first place though. No particular reason not to merge in the null check as Chummer does tend to be rather fragile in that regard, but we could be suppressing a larger issue.

**Comment by cjrt** [comment]
That's what I expected. I thought he was saying that deleting the item
should delete the expense.

**Comment by DeastinY** [comment]
ah okay

**Comment by chummer5a** [comment]
Unable to reproduce the issue in current version. Closed, pending something breaking.
