### ISSUE TITLE
Hide awakened qualities based on priority selection/career mode

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1706]
### Environment
Chummer Version: 5.193.78
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
To only be shown qualities I can take when I have "Show only qualities I can take" toggled.

### Actual behaviour
I can still choose negative metagenetic qualities, even without being Surged.
(Positive metagenetic qualities are hidden). 
Qualities that makes you awakened (magician, adept and the like) are also shown and are choosable, even if priority E for Magic have been chosen.

### Steps to reproduce the behaviour
Choose Priority or Sum2Ten. Create any character with prio E for Magic. 
Toggle "Show only qualities I can take". Don't choose Surge.
Choose to be a magician and maybe Cyclopean Eye + Cephalopod Skull.

### Thanks
Thanks for all your work on this fantastic program! 
This is not a high priority issue (very low impact), but hopefully easy to fix.

**Comment by chummer5a** [comment]
Negative metagenetic qualities are always available, per RAW. 
Filtering qualities based on build method is something I'll have to implement, as is they're visible in order to support point buy and life modules.
