### ISSUE TITLE
Error finding string for key - Message_DuplicateGuidWarning

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#1707]
Chummer Version: 5.193

Every time I open up chummer, and often when I try to perform any action such as opening a new character a box pops up with the error message written in the title. Not sure what's causing it. Chummer doesn't actually crash, I just get this error message about a dozen times and have to click "OK" for each one and then it lets me continue. Until another one pops up, anyway.

**Comment by Verecoth** [comment]
This started happening after having updated. It had been a little over a year since the previous update.

Performing a fresh install has solved the issue. Not sure what was happening.

**Comment by chummer5a** [comment]
I have a suspicion that the update mechanism isn't properly updating all the files, it likely failed to copy your en-us.xml language file. 

That error indicates that your data files have a duplicate ID; if you were updating from an old enough version, it might not have picked up all the right files. I'll be looking into the update mechanism again soon, it's a bit too fragile for my liking.
