### ISSUE TITLE
Switching Metatypes in Life Modules

### ISSUE THREAD

**Issue by Trollgre** [chummer5a/chummer5a#1709]
### Environment
Crash ID: 2eede115-d900-4adf-939c-c0206609ffa1
Chummer Version: 5.193.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Resetting character metatype, resets everything.

or

Raising an attribute above maximum with a module should simply do nothing.

### Actual behaviour
Life Modules: Attributes are still not resetting...entirely, some do, others don't. Which ones is not even consistent. Switching metatype does not work anymore to relieve artificially high attributes.

Then chummer spontaneously crashes.

And/or raising an attribute over max with a module produces warning window, then chummer crashes.

These might be two separate bugs.

### Steps to reproduce the behaviour
Maybe(?): Have a module elevate an attribute above maximum

**Comment by chummer5a** [comment]
I can't replicate this behaviour in current nightly builds. Can you please try with the latest build from get.chummer.net and see if it still does it?

**Comment by OLStefan** [comment]
Part of #2000.
