### ISSUE TITLE
(Improvement) Ability to drag items added as plugins into another item

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#171]
Runner buys a comlink, installs his fake SIN.

Buys a new better comlink, cant drag and drop SIN into new comlink, or programs

**Comment by cjrt** [comment]
Agreed. Currently I do a strange wrangling of selling and re-buying.

**Comment by chummer5a** [comment]
Tonight, on Features I Didn't Know Chummer Had: If you drag-and-drop with the right mouse button, you can move items onto other ones and create plugins.

I really need to get a user manual done for Chummer.
