### ISSUE TITLE
Extended Clip Stacking

### ISSUE THREAD

**Issue by VVelox** [chummer5a/chummer5a#1710]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.80.0
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
It stops adding +1 or +2 concealability modifier after the fist one as only one can be loaded at a time.

### Actual behaviour
It adds +1 or +2 for each clip.

### Steps to reproduce the behaviour
Add multiple extended clips to a weapon.

### Link to affected character file
https://vvelox.net/shadowrun/Bubba.chum5

**Comment by chummer5hasanerror** [comment]
The 'extended clip' item (weapon modifications) is intended to only increase the concealability modifier of a weapon based on the largest 'clip' modification, not each individual clip.

If you install the maximum extended clip, then you would only use the concealability modifier for that singular clip, not for each extension.  It becomes a grand total concealability modifier of +2.

It is NOT +1 per clip in the inventory (as your posting implies) as that would indicate that: 
Each clip in the character's inventory lowers concealability 
OR 
You are misreading rules and are under the incorrect impression that multiple/unlimited amounts of extended clips can be installed on the same weapon simultaneously (implying enough money can make any gun able 100 rounds, which is incorrect RAW)

**Comment by VVelox** [comment]
Nah, was not misreading the rules, just forgot about the installed checkbox for clips.

Post unchecking all the clips it sets it as expected.
