### ISSUE TITLE
Adept Powers Mis-Counting Power Ranks

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1711]
### Environment
Chummer Version: 193.81
Environment: WIN 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adept Powers (when given via Mentor Spirits or Qi Foci) to:

A) Provide the correct Ranks in a Power (Mentor Spirits currently only give 1 rank)

* My **_assumption_** is the Bonus Ranks of a Power Given by a mentor spirit, whenever a mentor spirit is taken (_including if_  the current magic rating is only 1) then a character will still receive the full bonus, per wording of Mentor Spirit quality.  If my assumption is inaccurate, please provide source (as I don't know of any but that doesnt mean its not out there)

* Affected Mentors include:
Arcana
Berserker
Boar (quality cannot be removed/altered in client, causes crash due to deletion of mentor spirit not automatically removing the Home Ground Quality)
Cat
Dog (attempts to fill out 2 pop-up dialogs for separate powers but only lists one in Powers tab)
Dolphin
Giraffe
Green Man
Lion
Monkey
Moon 
Mutation 
Oak
PeaceMaker
Raccoon
Rat
Raven (Alt)
Snake
Spider
Stag
Sun
Whale
Wolf
Wolf (Alt)

* Not Affected Mentors (which still provide 2 ranks include)
Chaos (which shouldn't be on this list as RAW one cannot take the Improved Potential power on the same limit more than once)

B) Be adjustable in the same singular power; If I receive 2 ranks of Light Body from a mentor spirit or qi focus then I should be able to increase the rating of that power (via PP expenditure) on the same instance/power listing on the same Chummer5 entry

C) To be able to take multiple instances of Elemental (Strike/Weapon/Body) as separate, potentially discountable powers.

D) To be able to take multiple instances of Attribute Boost (Str/Bod/Rea/Agi) as separate, potentially discountable powers 

E) Flexibility/Authoritative Tone to NOT be able to be taken at more than 3 ranks 

F) Death Mentor to provide a dropdown menu to select from the 4 available knowledge bonus skills (requires programming in 4 additional knowledge skills as none are in program by default) and provide the actual bonus ranks (which is _ranks,_ not a static bonus per the wording of the mentor)

### Actual behaviour
A) Mentor Spirits only give one rank of a power even when RAW says they get 2

B) Must create a separate entry; Get light body at 1 rank via mentor (see above), then must add the entire power to the sheet again to have any control in adjusting ranks, which is then _not_ 'tracked' under the magic rating (meaning a 6 magic adept + Mentor that gives light body = 2 entries, one a 1, one at 6)

C) Can only select Elemental ( X ) power once.

D) Can only select Attribute Boost (X ) power once.

E) Can take up to Magic Rating in ranks

F) Only provides the Adept Power.

### Steps to reproduce the behaviour
Make New Character (Adept)

Give Qi Focus (any adept power with ranks)
Give Mentor Spirit (any that provide 2 ranks of a power)
Go to Adept power Tab
*
Attempt to up rating of Qi Focus/Mentor Spirit given power to current character magic rating
Attempt to add more than one instance of mentioned (and assumed multi-instance) power like Elemental (X)
Attempt to raise Flexibility to 4 or higher
Attempt to add Death as a Mentor Spirit

### Link to affected character file
Available on Request

**Comment by OLStefan** [comment]
Can't replicate A-D in newest Nightly.

E) Those Powers can have 3 ranks max RAW.

**Comment by chummer5hasanerror** [comment]
correct those powers are supposed to cap at 3 ranks max
they do not

**Comment by chummer5a** [comment]
I can't replicate the issue with Flexibility or Authoritative Tone. Can you upload a character file so that I can see if I'm missing something?

**Comment by chummer5hasanerror** [comment]
Updated to current version, results as followed:

A) Still not working correctly:
Unless magic rating= 0, Mentor Spirits are expected to provide +2 ranks in a power.
Magic 1 + cat mentor = Light Body ranks 2

B) Corrected as of 193.86

C) Corrected as of 193.86

D) Cannot select multiple instances of Attribute Boost (Agi/Str/Bod/Rea) as of 193.86
Program only allows selecting 1 attribute, will not display the power afterwards.

E)  Corrected as of 193.86

F) Not implemented yet

**Comment by chummer5a** [comment]
Well, SR5 308 says:
> The maximum number of levels you can have of any one power is equal to your Magic Rating, or up to a limit listed by the power, whichever is less. 

I don't see anything in the mentor spirit descriptions that says the free levels dodge around that limit. Same problem as #1519, really.

**Comment by chummer5a** [comment]
#1743 contains the only segment of this issue that's still open.
