### ISSUE TITLE
Request for Use

### ISSUE THREAD

**Issue by hgehlhausen** [chummer5a/chummer5a#1715]
Hello,

It has been brought to my attention that this project is using the GPL3 license while my project is using the MIT license.

I would like to formally request to use your code / data files as a reference while building my web-based version of Chummer5a.

I would be open to changing the license on my project if this is any sort of problem - I'm a little new on the licenses themselves, but I really just want to make an awesome program like this available to everyone who wants to play Shadowrun ( which I'm new to but love already )

I'm still designing my project, chummer-js, so it would do no harm if you said "No", but I would enjoy the help.

Thanks and keep up the great work!

**Comment by chummer5a** [comment]
Chummer and Chummer 5 were originally distributed under the GPL; as I'm not the original developer, I can't alter the core licence. 

You could dual-licence it; MIT for your own code, GPL for anything you port across from us.
