### ISSUE TITLE
Crashing when trying to add negative qualities, Redliner doesn't apply to limbs.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1716]
### Environment
Chummer Version: .86, .85 
Environment: w10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Not crashing when trying to add negquals.

Getting +2 agi/str to limbs (assuming 4 limbs).

### Actual behaviour
In chargen when clicking Add qualities>selecting negative from the drop-down menu causes chummer to crash. (Prime gen was used, if it matters)

Redliner applies to meat, but not limbs. Adding redliner through improvements tab fixes the issue, but doesn't persist when loading the character again.  Redliner was added at gen, if that matters any.

**Comment by chummer5a** [comment]
I can't replicate either issue in the current nightlies, unfortunately. What error message do you get when selecting the negative qualities? Where are you not seeing the redliner bonus apply?

**Comment by Rinnolk** [comment]
For redliner http://i.imgur.com/i2Xz2Gd.png

Limits are not affected either. Skills however get proper pools somehow (averaged agi)
http://i.imgur.com/kZMzXwq.png

What I get for the crash http://i.imgur.com/MrbIPxQ.png

https://drive.google.com/open?id=0B71WLpuGA0X4cGl4cHhLZng3eDA file

**Comment by chummer5a** [comment]
The redliner thing is essentially a quirk of how the attributes are rendered. If it didn't show the cyberlimbs but still had the redliner bonus, it would be showing 1(3). It instead shows the highest attribute value, which is your averaged cyberlimb attributes.

**Comment by chummer5a** [comment]
I believe this is working properly in current nightly builds?
