### ISSUE TITLE
Improved Reflexes not shown when Chummer is German

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#1717]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.86
Environment: Windows 10 x64 Pro
Runtime: .NET 4.7

### Expected behaviour
Switch Chummer to German, expect to see all Adept Powers.

### Actual behaviour
Gesteigerte Reflexe is not displayed, see screenshots.
Switch back to English and it back

### Steps to reproduce the behaviour
Chummer set zo German
New Char, build an Adept
go to Adeptpowers
add Power
select Improved Reflex

### Link to affected character file
![deutsch](https://user-images.githubusercontent.com/12108972/27013370-a646bc50-4ee2-11e7-94e2-ff460d6a3996.JPG)
![english](https://user-images.githubusercontent.com/12108972/27013367-a6406242-4ee2-11e7-92ab-ced5acc4718f.JPG)

**Comment by OLStefan** [comment]
it seems an update went wrong with your version of Chummer Improved Reflex 3 shouldn't exist anymore, it should just be Improved reflexes and you should be able to set a rank for that power.

Please download a complete new version of chummer and try again.

**Comment by ReallyDarkMatter** [comment]
Just d'loaded a fresh Chummer and the error still exists.

Even with a new char the error exists
This char is created with the newly loaded chummer
[test troll.zip](https://github.com/chummer5a/chummer5a/files/1066784/test.troll.zip)
.
