### ISSUE TITLE
Incorrect Plugins are shown for Anthro drone arms/legs

### ISSUE THREAD

**Issue by TheOneDoc** [chummer5a/chummer5a#1719]
### Environment
Chummer Version: 5.193.86
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
Being able to add Cyberware Plugins to Anthro drones in Create and Career mode

### Actual behaviour
See Screenshots

Additionally a lot of Cyberlimb Enhancements that are not valid for Drone Arms/Legs are shown in Create mode

### Steps to reproduce the behaviour
See screenshots:
![c1](https://user-images.githubusercontent.com/29359215/27014673-c0ec2c1e-4efd-11e7-9eff-9cf5dbba45c4.png)
![c2](https://user-images.githubusercontent.com/29359215/27014676-c0f6bbca-4efd-11e7-81b0-6dd5b2977389.png)
![c3](https://user-images.githubusercontent.com/29359215/27014674-c0f597f4-4efd-11e7-85d5-fd84ceb18a7c.png)
![c4](https://user-images.githubusercontent.com/29359215/27014677-c0f9df94-4efd-11e7-8a69-bea23c35c4a7.png)
![c5](https://user-images.githubusercontent.com/29359215/27014675-c0f6bed6-4efd-11e7-9100-01df86f9902d.png)
![c6](https://user-images.githubusercontent.com/29359215/27014678-c0fe45f2-4efd-11e7-90f0-6f5cada9e018.png)
![c7](https://user-images.githubusercontent.com/29359215/27014679-c103cca2-4efd-11e7-8d5a-66c065f833cc.png)
![c8](https://user-images.githubusercontent.com/29359215/27014680-c1100f3a-4efd-11e7-96a8-9e2ecb9d7c9a.png)
![c9](https://user-images.githubusercontent.com/29359215/27014681-c113ff5a-4efd-11e7-939a-b31abb828166.png)

**Comment by chummer5a** [comment]
I can't reproduce it in current nightlies; the fact that you're only seeing the Essence Anti/Hole shows that something weird has happened though. Is it still happening?

**Comment by TheOneDoc** [comment]
It's still the same with 5.193.93

[AI Test Characters.zip](https://github.com/chummer5a/chummer5a/files/1071236/AI.Test.Characters.zip)
