### ISSUE TITLE
 Issue: - Can't add spells

### ISSUE THREAD

**Issue by KCKitsune** [chummer5a/chummer5a#1727]
### Environment
Crash ID: 4233896b-7e80-4370-a3ac-8a5dae3111c1
Chummer Version: 5.193.87
Environment: Windows 8.1 Pro
Runtime: 4.0.30319.36366

### Expected behaviour
When I click on "Add Spell" the selection screen should open

### Actual behaviour
The program crashes

### Steps to reproduce the behaviour
Created a new character and went to the "Spell" tab, clicked on "Add Spell" and the program crashed again.

**Comment by chummer5a** [comment]
Can't reproduce it. What's the error message?
