### ISSUE TITLE
 Issue: Crash on add modification to sensor array

### ISSUE THREAD

**Issue by drseltsam83** [chummer5a/chummer5a#1729]
### Environment
Crash ID: f4f9d316-bbe9-459c-a6bc-5775a8dde548
Chummer Version: 5.193.96
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Add modification opens dialog

### Actual behaviour
App crashes

### Steps to reproduce the behaviour
Select drone's sensor array, click on add modification

**Comment by chummer5a** [comment]
I can't replicate this; can you provide a little more detail, upload a sample character or something?

**Comment by drseltsam83** [comment]
load the following character
[Jimmy Hill _last_final_version_nachAB5_vergleich_2.zip](https://github.com/chummer5a/chummer5a/files/1082634/Jimmy.Hill._last_final_version_nachAB5_vergleich_2.zip)
click vehicles tab
look for first MCT roto drone in list,
select first (or second) camera (under sensor array)
open "add vehicle" submenu, click on "add modification" (in order to add vision megnification). Clicking add gear opens the dialog, but the chummer will crash one step beyond.
