### ISSUE TITLE
Buying ammo via gun in career mode does not update gear listing.

### ISSUE THREAD

**Issue by cjrt** [chummer5a/chummer5a#173]
* Go to career mode
* Buy ammuntion
* Put ammuntion in a location
* Press the button next to a gun to buy ammuntion, buy the same type again
* Press reload, ammunition shows up
* Check "Gear" ammuntion does not show up
* Drag ammunition that does show up to the main listing, suddenly you have all the ammuntion you should.

If you have the same ammunition in 2 locations, only one of those stacks will update when you move it.
If it is not in a location then it works normally.

I ran into this issue as I was using a "Ammunition" location to keep my inventory organised. I think it's being added to a stack, but not updating the quantity shown?

EDIT: No, simply clicking the stack will refresh it and cause the correct number to be displayed.

**Comment by chummer5a** [comment]
Partially fixed in the current dev build, will be fixed for 5.176.
