### ISSUE TITLE
#223 still an issue (again?)

### ISSUE THREAD

**Issue by drseltsam83** [chummer5a/chummer5a#1730]
Chummer Version: 5.193.96
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
I can select, what kind of fire mode I perform

### Actual behaviour
all sub entries of fire button greyed out

### Steps to reproduce the behaviour
Select german language, select drone with loaded weapon, click fire submenu

**Comment by drseltsam83** [comment]
Same behaviour as in #223

**Comment by drseltsam83** [comment]
This is still an issue. I referenced #223 just for information not for being a duplicate to it as it has been closed 2 years ago.

**Comment by chummer5a** [comment]
Should've been fixed in the latest commit, I forgot to reference the issue id in the commit message.
