### ISSUE TITLE
Crash when opening character file under French

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1733]
### Environment
Crash ID: e641baa0-6b63-437e-9597-b3e63faf48d6
Chummer Version: 5.193.97
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Having changed to French, be able to open character file

### Actual behaviour
With Chummer under French tried to open character file and Chummer dumped.

Note: Chummer could not upload the chummer crash report. Zipped the crash report and tried to append separately but the crash dump file has made the zip file too large. Excluded the crash dump to produce this file:
[chummer_crash_131423084583120845.zip](https://github.com/chummer5a/chummer5a/files/1083559/chummer_crash_131423084583120845.zip)
.

### Steps to reproduce the behaviour
In options, change to French. Try opening a character file.

Note: Chummer works correctly when using German.

**Comment by chummer5a** [comment]
Fixed in https://github.com/chummer5a/chummer5a/commit/83852f535d283b99bfaae13704a275a706b5811e
