### ISSUE TITLE
Crash trying to print under French

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1734]
### Environment
Crash ID: 5638d089-59fe-4726-a002-b35aa67cd60b
Chummer Version: 5.193.101
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Under French, click "Print" and Character Viewer displayed.

### Actual behaviour
Click "Print" and Chummer crashes.

### Steps to reproduce the behaviour
With language set to French, click "Imprimer" button.

### Link to file
Chummer unable to upload crash report because crashdump.dmp over 128MB. Attached is a zip of the crash folder without the crash dump file.
[chummer_crash_131423546653133284.zip](https://github.com/chummer5a/chummer5a/files/1085336/chummer_crash_131423546653133284.zip)

**Comment by chummer5a** [comment]
Might be fixed in ed1db161?
