### ISSUE TITLE
 Issue: - Crash on Search

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1737]
### Environment
Crash ID: 98bbc42e-0799-4f35-ba8c-4b6b608fedc8
Chummer Version: 5.193.106
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Entering something in the search box (happened in add weapon tab) filtering the gear to display only the items fitting the search criteria

### Actual behaviour
Upon entering the first letter chummer crashes with the crash ID seen above

### Steps to reproduce the behaviour
Create/Load Character, go to street gear, go to weapons tab, click add weapon, write anything in search-box

**Comment by Rinnolk** [comment]
Seen this happen when typing "combat" and "grapple"

Also, the base grapple gun from the crb appears to be missing.

**Comment by chummer5a** [comment]
Grapple Gun is a gear item that will automagically add the weapon object.
