### ISSUE TITLE
Complete character loss when loading .109

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1747]
### Environment
Chummer Version: .109
Environment:win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
character to remain unchanged when loaded from a save faile

### Actual behaviour
complete character loss:
all attributes removed
all improvements removed
all character advancemnt (tracked via the karma/nuyen tab) has been deleted.
In its place is an incorrect lump sum of cash and karma

### Steps to reproduce the behaviour
load existing character in .109

### Link to affected character file
will PM upon request

**Comment by chummer5a** [comment]
Sounds like the application crashed on load but failed to exit. I'd need to see the character.

**Comment by chummer5hasanerror** [comment]
error corrected as of .113
