### ISSUE TITLE
Redliner weirdness

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1749]
### Environment
Chummer Version: .112
Environment: w10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding Redliner to add to cyberlimb attributes.

### Actual behaviour
Removing Redliner adds to cyberlimb attributes.
http://i.imgur.com/Yw5sHJa.png - With redliner.
http://i.imgur.com/qsRCxzM.png - Without redliner.

### Steps to reproduce the behaviour
On a character with cyberlimbs add Redliner. Stats do not change.
Remove Redliner. Stats go up.
Adding and removing redliner basically.
Tried doing this on a new character and on an older one. Tried doing the reapply improvements thing.

### Link to affected character file
If needed?

**Comment by chummer5a** [comment]
Seems to be working properly in the latest build; could you please test and confirm?

**Comment by Rinnolk** [comment]
Yep, works fine on my end now :v
... super late >_>
