### ISSUE TITLE
Essence loss affects all attributes

### ISSUE THREAD

**Issue by MachineMuse** [chummer5a/chummer5a#1754]
### Environment
Chummer Version: Nightly 5.193.119 (Tested with a bunch of versions, it didn't happen with .118)
Environment: Windows 10 Home
Runtime: .NET 4.5.2

### Expected behaviour
Essence loss reduces MAG attribute by 1 per point of essence lost

### Actual behaviour
Essence loss reduces all attributes (including EDG) by 3, to a minimum of metatype minimums, but only after the Common form is loaded (thus Common pane shows correct values while other panes such as Skills and Print show incorrect derived values).

### Steps to reproduce the behaviour
1. Create a character who is a magician. Add some skills, attributes, edge, and a tradition.
2. Save into career mode.
3. Reopen in career mode.
4. Open Skills pane, print, etc. Observe that skills are calculated using the correct attributes.
5. Switch to Cyberware and Bioware pane. Add a datajack or whatever.
6. Save and reload.
7. Observe that Common panel still shows correct values, but Skills pane now shows skills calculated with reduced attributes, and Print pane shows reduced Augmented attributes (Base attributes are fine)

### Link to affected character file
https://puu.sh/wutIR/118057e422.chum5

**Comment by MachineMuse** [comment]
I've been informed that this is an old issue which had been fixed, and the changelog for .119 is very innocuous, so I'm thinking maybe something happened to the branching/CI

**Comment by chummer5a** [comment]
Yeah, I've been a bit lazy with commit messages lately.

**Comment by MachineMuse** [comment]
Noo. By 'changelog' I mean I looked at the commit that was linked for that build!

https://github.com/chummer5a/chummer5a/commit/1e29bb5f5255f2b7688de3d49bc3fdd74e69dc80

I can't imagine how this could cause the issue, which is why I suspect an issue with the branching or build system instead.

**Comment by chummer5a** [comment]
More likely it was https://github.com/chummer5a/chummer5a/commit/a2c5284c9c37d1a264737d6e362ff6cd3c411301 actually, that was committed at the same time.

**Comment by MachineMuse** [comment]
You were right! I made a PR to fix it here:
https://github.com/chummer5a/chummer5a/pull/1755/commits/e182dc806bc69392e93b75f5d3a0fc5144f0b3b9
