### ISSUE TITLE
Essence multiplier for Used ware while biocompatible does not follow the text of the quality.

### ISSUE THREAD

**Issue by litehound** [chummer5a/chummer5a#1757]
### Environment
Chummer Version: 5.193.102
Environment: Windows 10 64-bit
Runtime: .NET 4.5.1

### Expected behaviour
Text of the quality: 
"Something about the character’s body is exceptionally
accepting of either bioware or cyberware implants
(choose one). Not only are the implants not rejected,
but they seamlessly fit within the body, having less impact
on its holistic integrity. In game terms, the Essence
cost of implants of the particular chosen type are reduced
by ten percent, rounded down to the tenth. This
rebate is cumulative with the reduction offered by the
chosen ’ware’s grade, if any (e.g., the reduction for alphaware
of 0.8 is reduced by ten percent, or 0.08, to
become 0.72, and is rounded down to 0.7). This quality
can only be chosen for bioware or cyberware. This
quality may only be taken once."

Based on the text the multiplier should be reduced from 1.25 by .125 to 1.125, then rounded down to 1.1

### Actual behaviour
The multiplier is instead just reduced by .1 like all the other grades are, becoming 1.15

### Steps to reproduce the behaviour
Take biocompatibility on a character, select a piece of used 'ware(Most easily seen on 1-essence cost ware)

**Comment by Rinnolk** [comment]
https://github.com/chummer5a/chummer5a/issues/1585

**Comment by chummer5a** [comment]
Should be working correctly in the current builds.
