### ISSUE TITLE
Updating Chummer via update function causes Exception Error

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#176]
Just downloaded the actual release (0.5163) and let the update function loose (manual start).( only for chummer itself)
This alone causes an update loop.. it's loading the file again and again.
Being fed up after 5min i quit the process, and startet chummer to see what's going to happen.
upon trying to create a new char or clicking on options following occurs:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.CharacterOptions.Load(String strFileName)
   bei Chummer.CharacterOptions..ctor()
   bei Chummer.Character..ctor()
   bei Chummer.frmMain.ShowNewForm(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Complete data [at pastebin](http://pastebin.com/MFaGJaFN).

**Comment by chummer5a** [comment]
There seems to be an issue with the german language file and auto-update.
That error code indicates that it can't find the filename for the chum5
file you want to load, though. That's a bit weird. Do you get the
same/similar error if you try to make a new character?

**Comment by Tom-0169** [comment]
I'm running the english version and only try to make a new character

**Comment by Tom-0169** [comment]
Here is a [paste of chummerlog.txt](http://pastebin.com/a0E0Ttkp) from the update.
Perhaps this helps.

**Comment by chummer5a** [comment]
Hrm. Looks like it's failed to transfer the chummer executable. How odd.

**Comment by Tom-0169** [comment]
It's getinng more weird. After closing the updater & restarting chummer the infobox tells me that I've got Chummer 0.5164...
And then I get this "nice" System.NullReferenceException, when I try to load a char, create a char or even try to open the options ! The Tools-Section (Omae & Update) works.
The 0.5163 version behaves ...
Btw.running Win7 x64 Pro. Getting this error on two different W7x64Pro-PC's.

**Comment by chummer5a** [comment]
Should be resolved now.
