### ISSUE TITLE
Missing chummer5a.exe?

### ISSUE THREAD

**Issue by rsimmerm** [chummer5a/chummer5a#1760]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? chummer5a
Environment: (Operating system here. If it persists over multiple OS's list them all): Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Downloaded recent chummer5a master, extracted files, no chummer5a.exe  ?  How do I make the program run so I can use it?

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Download the Chummer.Nightly.zip file from get.chummer.net or Chummer.5.193.0.zip from stable.chummer.net.
