### ISSUE TITLE
Attributes error

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#1762]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.119
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Correct calculation of stats derived from attributes (skill pools, damage, limits, etc.)

### Actual behaviour
All attributes have a (X) after the attribute on the character sheet and also reflected in derived stats, that is 2 points higher than your actual attribute. I have no cyberware or otherwise that would increase all my attributes by 2.

### Steps to reproduce the behaviour
made several characters with same issue

### Link to affected character file
(Enter text here)

**Comment by Johnny8-0** [comment]
[chum.pdf](https://github.com/chummer5a/chummer5a/files/1114512/chum.pdf)

**Comment by chummer5a** [comment]
I can't reproduce it, I need to see the original chum5 file.

**Comment by Johnny8-0** [comment]
Attached.

**Comment by Johnny8-0** [comment]
Also, I can't deselect a Specialization once selected. The dropdown menu is
missing a "None" option. And if I check off the "Buy with karma" box, I
can't always uncheck it.

Other than that, amazing job! =)

**Comment by chummer5a** [comment]
Github doesn't play nice with attachments unfortunately, particularly via email. You may need to compress it to a zip file or upload it to a file-sharing service like https://www.file.io or mediafire or something.

**Comment by Johnny8-0** [comment]
Try this, or give me a regular email account I can send it to or share to.

**Comment by chummer5a** [comment]
Nope, no dice. Flick it to chummer5isalive@gmail.com.

**Comment by chummer5a** [comment]
Still can't reproduce it with your file in 5.193.130. Try updating and see if it's still doing it, I guess?

**Comment by Johnny8-0** [comment]
Did you try and print to PDF? Then it shows all the attributes with a parenthesis after with all attributes being two higher. And all skill pools are also two higher than they should be. As is unarmed dmg.

I have the latest version but will try updating. 

Sent from Valhalla

On Jul 1, 2017, at 08:36, Chummer 5 Is Alive <notifications@github.com> wrote:

Still can't reproduce it with your file in 5.193.130. Try updating and see if it's still doing it, I guess?

**Comment by Johnny8-0** [comment]
Updating worked. Thanks.
