### ISSUE TITLE
technomancer priority level A

### ISSUE THREAD

**Issue by macleod1976** [chummer5a/chummer5a#1763]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0
Environment: win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Allow for level A priority to be used for Technomancers and mages

### Actual behaviour
only mage skills can be selected on popup window for setting priorities

### Steps to reproduce the behaviour
kept trying to start new technomancer with A priority

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't reproduce it in current nightly builds.
