### ISSUE TITLE
Hanuman in Priority creation causing unhandled exception

### ISSUE THREAD

**Issue by chronometric** [chummer5a/chummer5a#177]
When building a new character with the Priority system, standard settings, **selecting Hanuman in the Metavariant dropdown menu causes an unhandled exception**. This occurs after selecting other character options, or if it's the first thing I click. Doesn't happen with other metavariants.

This appears to be the result of a typo. In the Metavariants dropdown, the species is misspelled Ha**r**uman, as a result of the same typo on **line 541 of metatypes.xml**. Correcting this typo in that xml file seems to have resolved the problem.

This might be a partial holdover from the way it was spelled in previous editions, but the 5e spelling was used in SumToTen.xml and priorities.xml (and indeed, there was no error using the karma system).

**Comment by chummer5a** [comment]
Fixed in 5.165.

**Comment by chronometric** [comment]
In v5.166, this misspelling is in the Common tab where the metatype is listed.

![example screenshot](http://i.imgur.com/bhxYnYb.jpg)

Might be worth doing a larger find/replace in the code to get all the instances of this?

**Comment by chummer5a** [comment]
Blahhh. Fixed in 5.167.
