### ISSUE TITLE
Notes printed

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1770]
### Environment
Chummer Version: 5.193.136
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Wished behaviour
In career mode there is a "Notes" tab. In previous versions what was written here did not get printed. I would like this tab to not get printed even if "print notes" is toggled. Maybe a choice somewhere to print or not.

There's  Notes in the "Character Info" tab to write notes you want printed.

### Actual behaviour
The "Notes" tab is printed under "Character Info" notes.

### Steps to reproduce the behaviour
Have a character in career mode and put text in both "Notes"

### Thank You

Thanks for all the work on this character generator.

**Comment by drakir75** [comment]
All notes (both places) are still printed even if "Print Notes" is NOT toggled.

(Version 5.195.22)

**Comment by chummer5a** [comment]
Unable to replicate in current builds.
