### ISSUE TITLE
Enhancement request: Permit free skill ranks 

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1771]
Not a usual occurrence, but our Gamemaster has provided several free skill ranks (in career mode). But there is no method to indicate the new rank is free.

Would it be possible to add a checkbox to the "Spend Karma" window to indicate the rank is free?

**Comment by Hood281** [comment]
A workaround is to record a Karma award for the amount needed for the increase that does not count towards career Karma and note its purpose, then raise the skill.

**Comment by Stexinator** [comment]
@Lochabar why is Hoods solution not good enough?

**Comment by Lochabar** [comment]
When I first opened this problem three and a half years ago, I didn't realize you could use a refund and mark it not to be counted towards Career Karma. Playing around with a character gave me the result I wanted.
