### ISSUE TITLE
Skills list is not sorted

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1772]
### Environment
Chummer Version: 5.193.137
Environment: Win7
Runtime: (probably .NET 4.5.1)

### Expected behaviour
When adding a new skill the list is in alphabetical order.

### Actual behaviour
After "Yakuza" another set of skills start.

### Steps to reproduce the behaviour
Click "Add skill". Scroll down to "Yakuza" next skill is "Astronomy".

![skills list](https://user-images.githubusercontent.com/17562417/27932065-ee6d8800-6261-11e7-83f9-18e56466d53a.png)

**Comment by joha4270** [comment]
Interesting, it is sorted for me.

Its too late for me to try debugging, but i have 2 hunches.  
1. Have you modified skills.xml in any way? It is entirely possible that it is sorted in that file and just copied verbatim.

2. It might be some strange with locale. To have a chance of debugging that, i need your system and input locale. To find those
* Press [Win] + R 
* type cmd
* press enter
* write systeminfo
* Wait a few seconds until some text appears. You are looking for "System Locale" and "Input Locale". Write them down.

**Comment by Lochabar** [comment]
Using the skills.xml file as supplied. There is no custom_skills file.

![systeminfo](https://user-images.githubusercontent.com/17562417/27934785-03c58634-626d-11e7-8fb5-5e4e26754ce1.png)

**Comment by joha4270** [comment]
Forced it to sort, hopefully this will fix it. No large changes in skills.xml, I'm honestly blank on why it happened.

**Comment by Lochabar** [comment]
This certainly seemed to be fixed in Nightly 5.193.140.
Is there a reason why nightlies 141, 143, 146, and 149 all also say "Hopefully fix #1772" ?

**Comment by chummer5a** [comment]
Fiddling with the build system, I missed a few commits before they got released and it's a hassle to remove them
