### ISSUE TITLE
Modifications to Cybereyes Basic System not using correct Capacity

### ISSUE THREAD

**Issue by Ceness** [chummer5a/chummer5a#1774]
### Environment
Chummer Version: 5.193.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Capacity for Modifications done to a Cybereyes Basic System should have varying Capacity costs

### Actual behaviour
All Capacity costs are [1] unless you increase the rating of Vision Enhancement where it acts as it should

### Steps to reproduce the behaviour
1.Create a character
2. Give them a Cybereyes Basic System
3. Right-click and "Add Gear"
### Link to affected character file
[Ryle.zip](https://github.com/chummer5a/chummer5a/files/1129862/Ryle.zip)

**Comment by chummer5a** [comment]
I don't see the problem. SR5, 444. Each Enhancement listed there costs 1 Capacity, with exception of the Vision Enhancement, which costs [Rating].
