### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by ChrisChinchilla** [chummer5a/chummer5a#1777]
Hey @chummer5a I wondered if you had made any attempt to make this work on macOS at all? I cloned the code and tried running it in JetBrains Rider (.Net core) might also work and hot a few errors, but before I dive into them I wondered if anyone had tried anything similar before and what might be potential pitfalls.

**Comment by joha4270** [comment]
Chummer have worked on both WINE and Mono. Not sure if it currently does, I broke my setup at home and have not yet investigated.

For specific pitfalls i can think of on top of my head...

* Last time i checked, .NET Core don't implement a version of WinForms
* Mono don't implement all WinForm components we use, at least the graphing displays on the Karma/Nuyen history tab in career mode.
* Chummer has a foundation that is very Windows only. In particular it assumes the Registry will be available, which is used to store options. The newoptions branch replaces registry with an .xml file on *nix systems, but it is unfinished and rather messy.
* UI and business logic is not very separated so adding a native UI will be a nightmare. We are slowly working on seperating it, but current timeline is "probably before commercial fusion power"
* There is a contributors.tt file that generates a contributors.cs file, which won't run automatically (or at all?) (The relevant google keyword is "T4 template")

Futhermore, https://chummer.slack.com is also a thing. You are more likely to quickly receive answers there.

**Comment by chummer5a** [comment]
I haven't put any effort into it personally, as I don't use a Mac. I don't personally have a problem with using .Net Core provided everything works but there's a catch-22 involved, as UWP is only available for Windows 10. So with one hand we're opening Chummer up to Mac/Linux users, with the other we're closing it off for Windows 7/8 users. I don't have any metrics to know just how broad that gap is.

It might be possible to multi-target to Framework 4.5.1 and Core as individual projects, but it'd likely require fragmenting the codebase quite heavily. Honestly, Chummer's not in a state where it'd be an easy migration. If you're interested in helping out with development, join our Slack via http://join.chummer.net.

**Comment by Lochabar** [comment]
Hope you aren't planning to close off Chummer to Windows 7/8 before Microsoft stops supporting them. There's an awful lot of Windows 7/8 users who didn't/wouldn't/will not transfer to Windows 10.

**Comment by Lochabar** [comment]
Here's an article about Windows 7 usage:

http://www.computerworld.com/article/3199373/windows-pcs/mays-windows-numbers-windows-7-digs-in.html

**Comment by ChrisChinchilla** [comment]
Sorry, GitHub notifications struck again, didn't get alerted to any follow up comments. :(

OK, I will dig further and let you know :)

**Comment by chummer5a** [comment]
No worries. Not much reason to keep this issue open then, nothing really actionable from it. Feel free to toss me an email at chummer5isalive@gmail.com or our slack via join.chummer.net if you've got any further questions.

**Comment by bryanletcher** [comment]
Any update on Mac/Linux support?  This is such an important app and I would love for everyone to be able to use it without having to boot into Windows.  Qt perhaps?  Thanks!  Keep up the great work!!

**Comment by ChrisChinchilla** [comment]
@bryanletcher No sorry, I've had a busy few months at work, and I don't know C# that well. The second half of 2018 I will have a little more time though, and I'm doing some docs work for a C# product, so I have a little more exposure to the ecosystem now.

Watch this space… Slowly.

**Comment by bryanletcher** [comment]
Thanks for the update.  Sounds like we need an open call to the community to assist ;)

https://docs.microsoft.com/en-us/xamarin/mac/
http://www.mono-project.com/docs/gui/gtksharp/
