### ISSUE TITLE
Foci karma cost in creation mode

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1779]
### Environment
Chummer Version: 5.193.146
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Correct foci binding cost.

### Actual behaviour
The spell foci (maybe others too) karma cost for binding are calculated wrong.
A new character that is still in creation mode has a spell foci of rating 4.
If I check the checkbox to bind it, only 4 karma is subtracted from the character remaining karma.
In the (german) core rulebook, the spell foci binding cost is given as rating * 2 karma.
So binding that rating 4 foci should cost 8 karma (not 4).

As a test, I saved the character with the unbound foci in career mode. Binding the foci in career mode correctly subtracts 8 karma. So the calculation is wrong in creation mode only.

### Steps to reproduce the behaviour
Create a character that can use/bind a weapon spell foci.
Buy a spell foci and check the checkbox to bind it.
Observe the remaining character karma.

**Comment by chummer5a** [comment]
Can't replicate it with standard foci; are you using the 2050 book's content, maybe? I noticed an error with that stemming from the names not matching.

**Comment by holgerschlegel** [comment]
I've created a simple test character that you can download from the following URL:
https://drive.google.com/open?id=0B2zReRE6W6hSdXZBMHhZRk9mMzA

Open it and navigate to the equipments tab.
The page should show unbound rating 4 foci. The status bar shows a remaining karma of 770.

Check the checkbox in front of the foci to bind it. The status bar now shows a remaining karma of 766.
But binding a rating 4 spell foci costs 8 karma. So the status bar should show 762 remaining karma.
