### ISSUE TITLE
5.164 knowledge skill issue still present

### ISSUE THREAD

**Issue by silvermistshadow** [chummer5a/chummer5a#178]
There was an issue in 5.163 where, in priority builds with free knowledge points, karma was being spent for knowledge skills without using the free points. I looked up the issue here and it's apparently fixed, but the problem still appears to be there.

Now, it just spends a karma point whenever I raise the rating of a knowledge skill, as well as a point of the free knowledge skill points. At this point, I should have 9 karma left, but after putting in two knowledge skills and raising them to rating 1, I have 7 karma instead. 

On an entirely different note, the bottom part of the interface is confused and thinks karma is 'BP', which according to my sources is leftover from Shadowrun 4.

Image included for reasons.

![knowledgeskills](https://cloud.githubusercontent.com/assets/5914011/7355722/8ee3bdb0-ecd8-11e4-892e-177ccf434e35.jpg)

**Comment by chummer5a** [comment]
Yeah, I don't know why I thought the code I'd released actually fixed the
issue. I blame 2am coding.

**Comment by chummer5a** [comment]
Resolved in 5.165.
