### ISSUE TITLE
Essence Not Printing to HTML

### ISSUE THREAD

**Issue by Meissa** [chummer5a/chummer5a#1781]
### Environment
Chummer Version: 5.193.149
Environment: Windows 8.1

### Expected behaviour
"Essence" field in HTML character sheet should show the character's essence.

### Actual behaviour
"Essence" field is blank in exported HTML character sheets

### Steps to reproduce the behaviour
- Open Chummer, default settings
- Create a new character of any metatype, using any build system
- Hit Print
- Essence field is blank:

![capture](https://user-images.githubusercontent.com/10284121/27997015-a59619b4-64bc-11e7-8fd4-9c61f571367c.PNG)

**Comment by Lochabar** [comment]
The ESS node is once again missing from the .chum5 file.
I tried editing the file to add the ESS node, but it was removed when I opened the file in Chummer.

**Comment by michaeljesse73** [comment]
This should be resolved now.

**Comment by OLStefan** [comment]
It prints the Essence now, but any value for Essence in the chum5 file is off. Therefore it prints a wrong essence value on the sheet.
![chummer](https://user-images.githubusercontent.com/3206519/28457963-4c1470fc-6e08-11e7-8a62-ac82ee841210.PNG)
