### ISSUE TITLE
 Issue: Crash when pressing "Add Spell" in Career Mode

### ISSUE THREAD

**Issue by TheMalle** [chummer5a/chummer5a#1782]
### Environment
Crash ID: 5dd65d51-fcd9-459e-9e92-fe88425d6e56
Chummer Version: 5.193.0
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Get a list of spells to add.

### Actual behaviour
Application crashes, with the message "Sequence contains no elements"

### Steps to reproduce the behaviour
Unclear.
May be restricted to race (Dryad), type of awakened (aspected magician), magical tradition (vodou) or other parameters. See below an example character file for which the bug occurs:
[Grant.zip](https://github.com/chummer5a/chummer5a/files/1134001/Grant.zip)

**Comment by Meissa** [comment]
Do you have the Dedicated Spellslinger quality from Forbidden Arcana? If so, this may be the same issue that I am reporting [here](https://github.com/chummer5a/chummer5a/issues/1784).

**Comment by TheMalle** [comment]
I do not. See screenshot for reference
![image](https://user-images.githubusercontent.com/22431531/27997927-4d062384-6502-11e7-998c-a4d8cd983d8b.png)

I also do not have Forbidden Arcana enabled. See below.
![image](https://user-images.githubusercontent.com/22431531/27997930-6856e056-6502-11e7-82e1-09e7aac18f3d.png)

**Comment by chummer5a** [comment]
It's because you don't have spellcasting or ritual spellcasting and I'm a nonce. Will be fixed in the next commit.
