### ISSUE TITLE
Dedicated Spellslinger discount for Aspected Magicians disappears after re-opening creation mode save file

### ISSUE THREAD

**Issue by Meissa** [chummer5a/chummer5a#1783]
### Environment
Chummer Version: 5.193.149
Environment: Windows 8.1

### Expected behaviour
The Dedicated Spellslinger quality from Forbidden Arcana costs 5 karma for Aspected Mages rather than 10, and the discount is persistent after reloading the save file while still in creation mode.

### Actual behaviour
Dedicated Spellslinger costs 5 karma for Aspected Mages rather than 10, but the discount disappears (reverting the karma cost back to 10) if the save file is closed and re-opened while still in creation mode.

- Note that there is a simple workaround to this by deleting and re-adding the quality after reloading a save file, causing the discount to be applied once more
- Note that this issue does **NOT** affect Dedicated Conjurer, the sister quality to Dedicated Spellslinger. The discount remains persistent even after save file reloads with that quality.

### Steps to reproduce the behaviour
- Open Chummer and enable Forbidden Arcana as a sourcebook
- Create a new character in either priogen or karmagen, it doesn't matter
- Make the character an Aspected Mage with their spec in sorcery
- Add the Dedicated Spellslinger quality
- Save the file
- Note down how much karma you have available for spending
- Close Chummer
- Open Chummer and load the file you just saved
- You will notice that there is no longer a discount on the quality and you have five less karma than you should have upon reloading the save file

**Comment by chummer5a** [comment]
You'll need to remove and re-add the quality again for it to work; the bonus for cost discounts wasn't being saved properly.
