### ISSUE TITLE
Application Crash upon adding spells to Aspected Mage with Dedicated Spellslinger

### ISSUE THREAD

**Issue by Meissa** [chummer5a/chummer5a#1784]
### Environment
Chummer Version: 5.193.149
Environment: Windows 8.1

### Expected behaviour
User should be able to add free spells from Dedicated Spellslinger using the spell selection menu.

### Actual behaviour
Application crashes upon clicking "Add Spell" with Dedicated Spellslinger added on character.

### Steps to reproduce the behaviour
- Open chummer and enable Forbidden Arcana
- Make a character in any build mode, priogen or karmagen, it doesn't matter
- Make the character an Aspected Magician with their spec in sorcery
- Add the **Dedicated Spellslinger** quality
- Flip to the **Spells and Spirits** tab and click **Add Spell**
- The application will crash

**Comment by Lochabar** [comment]
Application version 5.193.169 also crashes trying to add a spell to a regular magician.

**Comment by DenStoreFrelser** [comment]
While the application does crash upon finalizing adding a new spell for any type of spellcaster in 169, this is a different bug that occurs immediately upon hitting the "Add Spell" button, before even selecting what spell to add.
