### ISSUE TITLE
Chummer added a point of resonance (not a technomancer) to my character and i cannot remove it

### ISSUE THREAD

**Issue by drinkeecrow** [chummer5a/chummer5a#1785]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.193.0
Environment: (Operating system here. If it persists over multiple OS's list them all) Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1) unknown

### Expected behaviour
(Enter text here) No points were ever put into the resonance skill at character gen

### Actual behaviour
(Enter text here) After saving at some point there is a point added into resonance

### Steps to reproduce the behaviour
(Enter text here) unknown

### Link to affected character file
(Enter text here) 
[Crow - Copy.zip](https://github.com/chummer5a/chummer5a/files/1134171/Crow.-.Copy.zip)

**Comment by chummer5a** [comment]
It's irrelevant in current nightly builds as we changed the attributes system, but is it showing multiple points spent in Base, or just one? It shouldn't be costing you anything if you're not RES-enabled anyway.

**Comment by drinkeecrow** [comment]
its just showing one point spent in base. and I noticed when I opened a new char it's always ther.  BUT I only assigned the 4 Specialty points from my Meta type, and the sheet is treating it as if I assigned 5 points and is showing a -1 in the special attribs

**Comment by drinkeecrow** [comment]
Closing this as it was my misunderstanding of rules that caused the issue.  Chummer is working as intended.
