### ISSUE TITLE
Crashing every 5 minutes

### ISSUE THREAD

**Issue by Wayauyehi** [chummer5a/chummer5a#1786]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0
Environment: Windows 10 64 bit
Runtime: .NET Framework 4.6.2

### Expected behaviour
Not crashing.  

### Actual behaviour
The app is crashing at every attempt to add anything to the character sheet.  It crashes on the Skills tab, Cyberware tab, Vehicles tab, all of them.  I have sent you at least 5 reports via the app tonight.

### Steps to reproduce the behaviour
It seems to be happening when I try to actually add something to the character sheet.

### Link to affected character file
Nothing I am doing is linking to this document.  I will recreate the error and cut and paste the error to here.

Crash followup id = f07a69e1-d285-43e8-beb7-fa95d7db4a2f

Can't cut and paste this:
System.ArgumentException: Process with an Id of -20300 is not running at system.Diagnostics.Process.GetProcessByld(Int32 processId, String machineName) at System.Diagnostics.Process.GetProcessByld(Int32 processId) at
CrashHandler.CrashDumper.WorkerEntryPoint() in C:\projects\chummer5a\CrashHandler\CrashDumper.cs:line103

**Comment by Wayauyehi** [comment]
Cool.  I really appreciate the help.  I'll just delete the program, thanks.

**Comment by chummer5a** [comment]
I don't have access to the crash reports at the moment, so I don't have a lot to go on here. 

What was the last version of Chummer that worked for you? 
Have you tried the nightly builds? 
Have you tried deleting your settings file? 
Does the application crash if you leave it idling, or is it only after you do something? Does it crash if you make a change and save the file, then leave it alone? 

The only thing that actually runs every five minutes is the autosave method which essentially just calls the Save method and dumps a copy of the character into \saves\autosave.

Does that folder path exist? If you create that folder path, does it still crash?
