### ISSUE TITLE
PDF application cannot be used

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1789]
### Environment
Chummer Version: 5.193.149 (and earlier)
Environment: Win7
Runtime: (probably .NET 4.5.1)

### Expected behaviour
In the Options Window, having selected a PDF reader, be able to select the location of a sourcebook and test the reader works. (Using FoxItReader and not Adobe Reader.)

### Actual behaviour
The Selected Sourcebook location and the test button remain "greyed" out.

![pdf reader](https://user-images.githubusercontent.com/17562417/28023657-157e1b4a-6554-11e7-9eb1-0c4c2aac7304.png)

**Comment by chummer5a** [comment]
Seems fine to me, try reselecting a book treenode?

**Comment by Lochabar** [comment]
Tried again with 5.193.178, reselected the Foxit Reader application, and the PDF Location is still greyed out - I cannot select the PDF Location.

**Comment by chummer5a** [comment]
And you've clicked on a book on the left? It should only enable those options when you've got a book selected.

**Comment by Lochabar** [comment]
I did not realize I actually had to select a specific book to be ale to select a location.

We definitely need a user manual :)

**Comment by chummer5a** [comment]
The new options form is a lot more intuitive thankfully, but yeah, definitely need to work on UX a bit at some point.
