### ISSUE TITLE
Spending SP on Knowledge Skills causes false negative validation.

### ISSUE THREAD

**Issue by Xenryusho** [chummer5a/chummer5a#1792]
### Summary

Issue is one of design. Assumptions made in $(git rev-parse --show-toplevel)/Backend/Skills/SkillsSection.cs - public int KnowledgeSkillPointsUsed (Line 428)

`get { return KnowledgeSkills.Sum(x => x.CurrentSpCost()); }`

States that the number of Knowledge Skill Points that have been used are equivalent to the number of Knowledge Skill Ranks total, which is untrue. This problem is further exacerbated by the fact that public int SkillPoints (line 436) is doing too much work with:

`if (KnowledgeSkillPointsUsed > KnowledgeSkillPoints)
			work -= KnowledgeSkillPoints - KnowledgeSkillPointsUsed;`

Perhaps calls should be made to in place of this calculation as well as 

`KnowledgeSkills.Sum(x => x.CurrentSpCost());` 

in order to make their results accessible separately such that KnowledgeSkillPointsUsed could accurately reflect that the number of knowledge skillpoints used as being the sum of knowledge ranks sans the number of skill points used to buy knowledge skillpoints. 

### Environment
Chummer Version: 5.193.0 (If that's incorrect it's whatever the latest is, I pulled and built from source).
Environment: Windows 10, 64 bit.
Runtime: .NET 4.5.2 / Also tested with 4.5.1

### Expected behavior
Upon spending SP on Knowledge Skills it decrements SP but not Knowledge Skills (Ex: I have 0 knowledge skill points and 1 skill point, I rank up a knowledge skill. It removes one SP and I'm left with 0, knowledge skill points remains at zero).

### Actual behavior
Spending SP on Knowledge Skills decrements both SP and Knowledge Skill Points (Ex: I have 0 knowledge skill points and 1 skill point, I rank up a knowledge skill. It removes one SP and I'm left with 0, knowledge skill points go to -1 which causes a fail in validation).

### Steps to reproduce the behavior
1. Create a new character.
2. Spend all Knowledge Skill Points.
3. Attempt to buy more Knowledge Skills. 
4. Click Special -> Validate character.

### Link to affected character file
Test Character File provided in attachments

[Knowledge Skill Bug Sheet.zip](https://github.com/chummer5a/chummer5a/files/1137730/Knowledge.Skill.Bug.Sheet.zip)

**Comment by Xenryusho** [comment]
I could work it too.

**Comment by chummer5a** [comment]
Always happy to see a pull request come through, otherwise I'll have a proper look at it first chance I get.

**Comment by Xenryusho** [comment]
Sounds good. I sent one in for this issue. Though it says an appveyor check failed because it didn't generate the t4. My first time attempting a pull request so if it didn't go through I'll give it another look.

**Comment by chummer5a** [comment]
Not an issue on your end, Appveyor's currently a bit broken (Project file got munged) so it doesn't know it needs to build the t4 template.
