### ISSUE TITLE
 Issue: - Cannot create Satyr

### ISSUE THREAD

**Issue by Detroct** [chummer5a/chummer5a#1798]
### Environment
Crash ID: e69f5141-705d-424c-8974-915724c0128c
Chummer Version: 5.193.149
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Creating Character as a Satyr (Ork Metavarient)

### Actual behaviour
Chummer Crashes

### Steps to reproduce the behaviour
Create a new character and select Ork -> Metavarient: Satyr and create character.

**Comment by Detroct** [comment]
Note, this does still work on the latest stable release (5.193.0)

**Comment by chummer5a** [comment]
Can't replicate it, what's the error say?

**Comment by DenStoreFrelser** [comment]
I'm getting this error as well, and it seems to be tied to the Satyr Legs quality. Same build, Win10. All other metatypes and -variants seem to work fine, but satyrs crash the application like in the description. Adding Satyr Legs to created characters also causes this crash, but if I remove the "movementreplace" parts of that quality (the only quality that has movementreplace) I can create Satyrs without crashing.

The error message appears in my OS's language, but translates to something like "The target caused an exception during activation.".

**Comment by chummer5a** [comment]
Should be working properly as of 169.
