### ISSUE TITLE
 Issue: - Chummer crashes when trying to change the metatype

### ISSUE THREAD

**Issue by Soermi** [chummer5a/chummer5a#1799]
### Environment
Crash ID: 9c928497-6de9-41b6-91cd-50d21890490b
Chummer Version: 5.193.0
Environment: Windows 8.1 Pro N
Runtime: 4.0.30319.42000

### Expected behaviour
Trying to change the metatype of a new character after initial creation

### Actual behaviour
Chummer crashes after selecting the "Change Metatype" button

### Steps to reproduce the behaviour
Create a new character with "Priority" as build method. Select any combination of settings and click "Ok". Now click the "Change metatype" and Chummer crashes

**Comment by Soermi** [comment]
Note: this behaviour only happens in the german translation

**Comment by chummer5a** [comment]
Should be fixed in the latest commit.

**Comment by Soermi** [comment]
With the Nightly .169 it now crashes after changing the metatype and clicking "Ok", even if nothing in the dialog was changed.
