### ISSUE TITLE
Throwing weapons largely functionless as ammo or to be used

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#180]
I had been going through it and throwing weapons cant be reloaded with ammo of their type. Hitting reload returns a window that says no more ammo exists for that type.

Throwing knives cant be fired, bolas cant be thrown. Same for grenades.

Bolas can be added as a weapon or as ammo but neither function.

**Comment by chummer5a** [comment]
Issue resolved in 5.165; weapons.xml did not have a category for Gear.
