### ISSUE TITLE
Enhancement: Karma Cost for Special Attributes is Not Reduced by Essence Loss

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1808]
### Environment
Chummer Version: 5.193.0 and 5.193.169 and 5.193.136
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
There's a choice in options ->General -> Misc to make karma costs for Magic be the same in priority as in karma build (cost not reduced by essence loss). Expected behaviour is that this option stays toggled after the required restart.

### Actual behaviour
You can toggle the option but it does not stay toggled.

### Steps to reproduce the behaviour
Go to options. Toggle the "Karma cost for special attributes is not reduced with essence loss"
Restart as required. Check the option.

**Comment by GearheadLydia** [comment]
Without looking at the code in question, my assumption was that this was going to be related to either saving it to the option file correctly or loading it from the option file. That said, it also looks like the option is not working when it is set and the program restarted, which means that it is actually affecting the real option and not just the checkbox.

**Comment by chummer5a** [comment]
That rule doesn't actually do anything, it's a holdover from 4th I think. I can build it back in without too much hassle, but where are you getting the idea that the costs are different between priority and karmagen?

**Comment by GearheadLydia** [comment]
Point taken! Never mind.

I did notice that the Karma spent on one particular character dropped drastically, by about 15 points, between versions 5.190.0 and 5.193.1xx. This was definitely related to changes in how the calculations for the costs of increasing MAG were handled, as listed in the change-log; I wondered if this flag was somehow implicated, but clearly it isn't.

**Comment by drakir75** [comment]
The costs are different for burnouts. Take Magic prio D. Get augmentation for 2 essence. Lower Magic score to 0 if not already there. Buy up to 2 again with karma. This will cost 15 karma in priority (as in career mode)  but 35 karma in karmagen. The difference will be even higher if more essence are lost to augmentations.

**Comment by drakir75** [comment]
It's also possible to start with an awakened character at Magic 0 in priority, but not in karmagen.

**Comment by drakir75** [comment]
Karma costs for Magic in burnouts has changed to career mode costs in karmagen. But the original error is still there.

**Comment by chummer5a** [comment]
Can't replicate this in the latest build.

**Comment by drakir75** [comment]
Just tried. (version 5.193.207). When I toggle the option Chummer wants to restart. After restarting the option is still not toggled and not in effect.

**Comment by chummer5a** [comment]
Yeah, the option still doesn't do anything, I meant that the prices are the same in both cases, where the Karma costs are reduced by Essence Loss, which is RAW. I'll have to put some more work into implementing that rule.

**Comment by drakir75** [comment]
I know the price is the same. That was changed as I have said above.

Say I want to to an adept. Choosing Magic D (Magic 2). If I want to raise that it costs 15 karma from 2->3. 

If that option is toggled, and I have bought "Muscle Replacement rating 2 (Magic now 0) the option is to make it cost 15 karma to raise Magic to 1. This does not work.
