### ISSUE TITLE
Magic/Ressonance value problem and Initiation automaticly raising the attribute

### ISSUE THREAD

**Issue by Valgryn** [chummer5a/chummer5a#1809]
### Environment
Chummer Version: 5.193.169 and about every version to 5.193.00
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When buying cyberware as Technomancer, Mage or Adept that depending on essence loss the magic or ressonance metatype limit gets reduced by the number of full essence lost. So for getting an essence loss of 0.99 or anything above reducing the limit by 1 which will result in an 6 (5) value for the attribute.
__
When initiating the limit for the special attribute should be raised by one, giving the option to buy one point for the attribute.

### Actual behaviour
During chargen it will set the whole attribute to 5 (5) after taking one point of essence loss. In career mode it will also reduce the limit by one so it ends up as 5 (4). This only happens to characters created after .193.00
__
when initiating the whole special attribute will be raised. So the 5 (4) becomes immediately 6 (5) without buying the attribute point first.

### Steps to reproduce the behaviour
Simply build a mage, adept or technomancer and buy cyber or bioware. The attribute will change the wrong way and after chargen will always reduce itself further.
__
Initiating at any grade will make the change on the attribute, not the limit

**Comment by chummer5a** [comment]
Looks fine to me, the 5(5) thing is because it's an augmented value, can't replicate the issue with it deducting from essence twice.

**Comment by Valgryn** [comment]
The 5(5) would be just fine but once I put the character into career mode it ends up as 5(4) which basically steals a whole magic point from the character as the new actual attribute will be 4.
I can put a link for google drive for the file in career and create mode if it helps to find the problem.

**Comment by chummer5a** [comment]
Sure, that'd be helpful. All my test characters are loading properly so far

**Comment by Valgryn** [comment]
ok, here is the link for the character in career mode : 
https://drive.google.com/file/d/0B_sD1-9zJG8bWlllTFZMNEUyc1E/view?usp=sharing

and here for create: 
https://drive.google.com/file/d/0B_sD1-9zJG8bWlllTFZMNEUyc1E/view?usp=sharing

i found a solution to not loose the one extra point of magic by raising the limit to 7 in the file. That way it ends up as 6 (5) as it is supposed to be. The other problem with the magic increasing every time I let the character initiate seems to have solved itself after i remade the character with a newer version than i used before so at least that's gone.
Hope you can find a solution to my problem though with the magic attribute.
