### ISSUE TITLE
(Improvement) Functionality for clips

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#181]
Now, clips are something of an issue.

So I have say, an HK 227 and I purchase 2 clips on the weapons tab as modifications. These are in no way connected to the gear tab. They as is are designated by the weapon you choose when purchased but dont allow you to place and remove ammo of the amount listed on the weapon.

What I have been doing in play is purchasing spare clips for the gun, then purchasing the same amount free in the gear tab and then separating the ammo into the two clips. This works pretty well as it allows me to keep my head straight about what ammo is were but its not quite complete.

So some functionality that you might consider after you are done with the larger issues:
-Ability to load ammo into modification-attached magazines
-Gear added magazines are automatically added as weapons modifications for the weapon they are specified
-Ability to reload by swapping magazines, IE de-loading current shots held in weapon and adding shots in new magazine.

**Comment by cjrt** [comment]
I take it the idea behind this is to switch between different ammo a)
quickly in terms of in-game time b) to do this without fully refiling the
ammo each time you switch. Which is currently an issue when you switch ammo.

You would then reload each clip individually? And select a clip to be
present in the gun?

**Comment by Neocyberman** [comment]
Yes to the first portion

I've, in doing further testing found out that in .164 (which doesnt have its changelog.txt for some reason) firing and reloading causes item duplication to occur on the ammo.

**Comment by chummer5a** [comment]
This actually wouldn't be that difficult to implement, thinking about it. You'd change Spare Clip to use the SelectItem form instead, automatically inheriting the maximum ammunition count from the parent weapon. Add a context menu for Refill Ammunition that prompts you to select the ammunition type, generates a new GUID, takes one of the spare clips and converts it to the new GUID. Ammunition would automatically be filtered for the weapon category. Weapons would look for spare clips with their name attached, then count down the ammunition from there.
