### ISSUE TITLE
Xslt compilation error

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1812]
### Environment
Chummer Version: 5.193.178
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
...

### Actual behaviour
Opening the print view shows a popup message "xslt compilation error" for all sheets.

### Steps to reproduce the behaviour
Create a new character and open the print view.
No need to add anything to the character.

**Comment by Lochabar** [comment]
This is because the sheets folder was not completely REPLACED by the contents of the zip file I provided for #1810 and so files are missing. As a work around download the zip file, rename the sheets folder in the Chummer base folder, then extract the zip file to the base folder.

**Comment by holgerschlegel** [comment]
I wanted to test if the Spell Category problem has been fixed in that version.
Due to other open bugs I just keep using an older version (5.193.47) for "productive characters".

**Comment by Lochabar** [comment]
It has been fixed but not added to Chummer correctly. You can install the sheets.zip folder into 5.193.147 in the same way I described above.
