### ISSUE TITLE
 Issue: - Chummer crashes when changing options

### ISSUE THREAD

**Issue by galvorbak99** [chummer5a/chummer5a#1814]
### Environment
Crash ID: 6f750440-ead4-48f5-bc03-f2428a4d5e32
Chummer Version: 5.193.179
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer to restart after changing options

### Actual behaviour
Chummer Crashes

### Steps to reproduce the behaviour
Change sourcebooks used or housrules

**Comment by chummer5a** [comment]
Yup, it's not loading the sheets. Will be fixed in the next commit.

**Comment by chummer5a** [comment]
Should be resolved in the latest commit. Next scheduled build is at 00:00 UTC.
