### ISSUE TITLE
Crashing when trying to checkbox Sourcebooks

### ISSUE THREAD

**Issue by WhyDoINeedANameToReport** [chummer5a/chummer5a#1816]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Nightly-v5.193.179
Win7 64bit, all important updates
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I try to checkbox sourcebooks

### Actual behaviour
I checkbox all books I want, and no matter what I do, Chummer crashes

### Steps to reproduce the behaviour
Trying to checkbox books, then when it ask to restart the application (which would lead to crash) deny the restart. It crashes nontheless.  Crash Report fails to be created every time. Only thing i caught before the thing was killed by my system as something with line 118 in the CrashHandler.

### Link to affected character file
Not linked to a specific Character File

**Comment by WhyDoINeedANameToReport** [comment]
![screenyweeny](https://user-images.githubusercontent.com/30326910/28437986-e422e50c-6d9c-11e7-93f6-2648ef468369.jpg)

Managed to catch the well, crash-crash report. Hopefully it something on my end.

**Comment by OLStefan** [comment]
Please try to select an entry on the 'Default Character Sheet' Dropdown. That should solve the problem.
![chummer](https://user-images.githubusercontent.com/3206519/28439002-6ff02d08-6da0-11e7-9296-d38c11de3bc3.PNG)

**Comment by WhyDoINeedANameToReport** [comment]
The drop down menu at that point doesn't offer me any possible options

**Comment by OLStefan** [comment]
Okay, that seems to be a problem with change for the character sheets, should be fixed in the next nightly, which should be available at 12AM UTC (about 2.5 hours from now).

Please test it again with the new Nightly.

**Comment by WhyDoINeedANameToReport** [comment]
Version .180 apparently fixed it. Thanks.
