### ISSUE TITLE
Free Karma for Contacts

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#182]
The Contacts point shwon are calculated correctly (CHA * 3), but no points get subtracted from them until i already spent the whole amount of points.
![contacts1](https://cloud.githubusercontent.com/assets/3206519/7415228/ab6c7036-ef57-11e4-8625-73eb0f37ab02.png)
![contacts2](https://cloud.githubusercontent.com/assets/3206519/7415229/ab6daffa-ef57-11e4-85d6-b80801e32db7.png)

**Comment by OLStefan** [comment]
If i check "Check_Box_Options_ContactMultiplier" the points are calculated correctly.

**Comment by chummer5a** [comment]
Resolved in 5.166.
