### ISSUE TITLE
Attribute error in Life Module Character Creation

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#1820]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 193.180
Environment: Win 10
Runtime: 4.0.30319.42000

### Expected behaviour
Stats pay attention to LifeModule increases

### Actual behaviour
Increases by LifeModules do no take any effect on Stats.

### Steps to reproduce the behaviour
New Char, up to 765. Select Elf, Nocturna.
Attribute base and aug values are 1,3,1,1,2,1,1,1,1
Add + 1 to each:
Attribute aug values are now 2,4,2,2,3,2,2,2,2 (base is unchanged)

New Char, up to 765. Select Elf, Nocturna.
Attribute base values are 1,3,1,1,2,1,1,1,1
Add LifeModules: Aleut, Isolated Rural, Test Subject (Bio), Skip F/Ed, Terrorist (Saeder-Krupp)
Attribute base values are 3,3,1,2,2,1,3,2,1
Attribute aug values are 1,3,1,1,2,1,1,1,1
Add + 1 to each:
Attribute values are now 2,4,2,2,3,2,2,2,2

### Link to affected character file
Look at Lumena char file. (this is the same as Lumens file but made in 180 https://www.dropbox.com/sh/urt1cky26p0zfbc/AABaUn8Elvh6D5tXbvPmA63va?dl=0

**Comment by chummer5a** [comment]
Fixed in the latest commit.
