### ISSUE TITLE
Spell duration and damage not printed correctly

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1822]
### Environment
Chummer Version: 5.193.181
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Show the correct spell duration.

### Actual behaviour
In the printouts, spell duration and damaga are not shown correctly on languages other than english.

Reason:
The xml file for printing already contains the translated duration and damage abbreviations.
For example "A" for duration "Aufrechterhaltend" (sustained) and duration "S" for "Sofort" (instantaneous). Or the damage "K" für "Körperlich" (physical).

The xslt compares the values from the xml files with the english abbreviations. "I", "S" and "P" for duration,  "P" and "S" for damage.
So, it is the same problem that we had with the spell categories a few days ago.

Question:
Why show longer names for duration and damage at all?
For me, the transated abbreviations are enouph. There are also used in the spell descriptions of the rulebooks and thus should be known by all players with a magic character anyway.

### Steps to reproduce the behaviour
Set Chummer5a to language german.
Create a new character and add a spell with duration "Instantaneous" spell like "Feuerball" / "Fireball".
Open the printout.
The spell duration is shown as "Aufrechterhaltend", which translates to "Sustained".
The spell damage is shown as "K", but should be "Körperlich".

**Comment by holgerschlegel** [comment]
It is not a data file error. The values are shown correctly in the UI.
For printing the program generated translated values but the sheet xslt assumes english not translated values.
So, either add duration_english and damage_english to the print xml file and change the sheet to use that.
Or change the sheet to simply output the translated values as-is.

**Comment by Lochabar** [comment]
I'll modify the sheets to cater for the translations in the XML file.

**Comment by Lochabar** [comment]
Here is a complete replacement of the sheets folder
[sheets.zip](https://github.com/chummer5a/chummer5a/files/1167722/sheets.zip)
