### ISSUE TITLE
Free spells from Dedicated Spellslinger not used

### ISSUE THREAD

**Issue by DenStoreFrelser** [chummer5a/chummer5a#1823]
### Environment
Chummer Version: 5.193.181
Environment: Win10
Runtime: Probably .NET 4.5.1

### Expected behaviour
When a character has Dedicated Spellslinger, they should get a(n additional) number of free spells equal to their Spellcasting.

### Actual behaviour
The displayed number of free spells is updated correctly, but attempting to go over the free spells from priority will still use karma (Mage with Magic B, Spellcasting 4 and 8 spells: "7 of 11: 4 Karma".).

### Steps to reproduce the behaviour
Create a character with Dedicated Spellslinger and add more spells than the character gets from priority.

**Comment by chummer5a** [comment]
That would be because I'm a nonce and didn't think to code it that way. Current behaviour requires that you select the Free! checkbox on the spell selector window. I'll sort it out.
