### ISSUE TITLE
Search broken for Add Complex Forms

### ISSUE THREAD

**Issue by DenStoreFrelser** [chummer5a/chummer5a#1824]
### Environment
Chummer Version: 5.193.181
Environment: Win10
Runtime: Probably .NET 4.5.1

### Expected behaviour
Entering text into the search box when selecting complex forms should narrow the list of available complex forms down to ones matching the search text.

### Actual behaviour
The list is emptied when any text is entered into the search field.

### Steps to reproduce the behaviour
Create a technomancer, select Add Complex Form and enter any text into the search field.

**Comment by DenStoreFrelser** [comment]
The window containing the list of complex forms is titled "Select a Program". That should probably be "Select a Complex Form".

**Comment by DenStoreFrelser** [comment]
This issue is still present in 182. The value of a functional search for a single, alphabetically sorted page is questionable, but it's still technically an open bug.

**Comment by chummer5a** [comment]
Pfft, that's what I get for assuming they ran off the same form. Will be fixed in the next commit.
