### ISSUE TITLE
Armour prints out missing gear plugins

### ISSUE THREAD

**Issue by KagedShadow** [chummer5a/chummer5a#1826]
### Environment
Chummer Version: 5.193.0.0
Environment: Win7
Runtime: .Net Framework 4.6.1 

### Expected behaviour
Armour print outs should contain both Armour Mods and gear plugins

### Actual behaviour
Gear plugins are not printed in, nor are they present in the print preview

### Steps to reproduce the behaviour
Create character with armour inc. gear plugins and print.

### Link to affected character file
https://www.dropbox.com/s/dic2cmtk7i16ntp/SR5%20Kage%20Bug%20report.chum5?dl=0

**Comment by Lochabar** [comment]
There are plugins missing in the prints produced by the current release (5.193.0). 

It looks like all plugins are printed by the latest nightly (5.193.181)
![armor](https://user-images.githubusercontent.com/17562417/28494789-39163458-6efe-11e7-81b5-b0a2a8fb3f83.png)

Can you download and use the latest nightly?

**Comment by KagedShadow** [comment]
Yes, that works - thanks
