### ISSUE TITLE
cybered attributes

### ISSUE THREAD

**Issue by madmarvin** [chummer5a/chummer5a#1828]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running?Chummer5.193.0
Environment: (Operating system here. If it persists over multiple OS's list them all) win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
added syprathyriod, and muscle toner3 anc muscle aug3 expected strength adn reaction to be +4
### Actual behaviour
 but only list as +3, its only adding one piece of bioware to any given attribute, not the multiple it should be

### Steps to reproduce the behaviour
in career mod added delta syprathyroid, delta, muscle aug 3, delta muscle toner 3, delta synaptic booster 3 and only one piece is being added to each. in this case the highest

### Link to affected character file
https://drive.google.com/open?id=0B5XwgkgB7J3vLUtSeUNkQzRlRHc

**Comment by OLStefan** [comment]
Muscle Toner and Muscle Augmentation are both "incompatible with augmentations that increase Strength/Agility" (SR5 459)

**Comment by chummer5a** [comment]
Working as intended, those don't stack with each other per RAW. If you'd like to alter that behaviour, you could use an [override file](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files) to remove the precedence attribute.
