### ISSUE TITLE
Crashing deleting license on fake sin and deleting initation.

### ISSUE THREAD

**Issue by oddmage** [chummer5a/chummer5a#1830]
### Environment
Crash ID: b1f5b72f-f850-44ef-bc35-a0de8380d683
Chummer Version: 5.193.181
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Can delete things without crashing

### Actual behaviour
Initation or SIN is deleted.

### Steps to reproduce the behaviour
When I add a community pack (Usually Runnerhub's) then go to delete one of the three licenses I don't need it crashes.  It will usually (but not always) crash when you dete the fake sin.

In addition I added a 4 initation, then went to delete it and it crashed.

**Comment by chummer5a** [comment]
Can't replicate either one. What's the error message say?

**Comment by oddmage** [comment]
I'll try and get you the info later about what it says.  I did realize though that I missed a step with the packs.  Both the other guy and I got it after hitting escape/cancel for one of the licenses.

Another note is the 3 or 4 times I try to send the crash report, that program crashes...

**Comment by chummer5a** [comment]
Oh. Yeah, Chummer has some issues with trying to roll back from cancelling out of windows called up by the improvement system, that makes sense.

**Comment by oddmage** [comment]
Attached are the two screen shots (hopefully names come through to
differentiate them, but if they don't the blue one is the intiate crash).

Steps for Initate, open Tomatoes in career mode and delete his last
initiation.

Steps for SIN:Add Runner Hub pack, pick name, pick 2 licenses and escape
the other, click on the empty one.

If you need anything else, or have tips on how to make my guy better, let
me know!

[image: Inline image 1][image: Inline image 2]
