### ISSUE TITLE
Oni/Hobgoblin Priority C 

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#1831]
Run Faster 2nd Printing has Oni as costing 4 karma and Hobgoblin costing 5 karma at Priority C. Keeping them in line with Oni and Hobgoblin at the other priority levels.

![ss 2017-07-24 at 08 38 37](https://user-images.githubusercontent.com/18119437/28550619-2e0445ce-70b0-11e7-8077-c1f4b46f32ff.jpg)

Chummer5 still isn't up to date with RF 2nd Printing.

**Comment by chummer5a** [comment]
No, it's RAW. All other costs are presented without a negative or positive sign. Ergo, Oni and Hobgoblin at priority C are different to the other costs, which means that they have to grant karma.
