### ISSUE TITLE
Voice Control not adding to social limit

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#1834]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: latest build from source
Environment: Win10
Runtime:  .NET 4.5.1

### Expected behaviour
Having a level of Voice Control adept power should raise social limit by 1

### Actual behaviour
Voice control is not being added into the social limit calculation
   When hovering the mouse over the social limit in the limits tab, it says "...Voice Control (0)" -- so it knows the character has the power, but is not adding a bonus for it.
   Comment: when loading an older version of this character where Voice Control was not being correctly credited as a Mentor Spirit adept power, the social limit gets correctly calculated -- so something is going wonky related to that.

### Steps to reproduce the behaviour
load character, look at the limits.

### Link to affected character file
https://drive.google.com/open?id=0B16_Tk8Lw7gneWhKYlFINnpIeHc

**Comment by chummer5a** [comment]
[Echo - Career.zip](https://github.com/chummer5a/chummer5a/files/1187776/Echo.-.Career.zip)

I have a rough idea what the problem is, trying to sort out the root cause. In the interim, this should be a fixed character sheet.
