### ISSUE TITLE
Special Attributes miscalculated during character generation

### ISSUE THREAD

**Issue by Idayn** [chummer5a/chummer5a#1837]
### Environment
Chummer Version: 5.193.185
Environment: Windows 10
Runtime: .NET 4.6.1

I created a character with Magic Priority A, (Magic 6, Edge 1, 0 Special Attribute Points from Race), and the Karma Summary Tab on the right is displaying Special Attributes : -6 of 0

**Comment by chummer5a** [comment]
Can't replicate it, could you provide a copy of the character file?

**Comment by Idayn** [comment]
https://www.dropbox.com/s/3k7ab95qozydnx1/sundance.chum5?dl=0
