### ISSUE TITLE
Duplicate GUIDs

### ISSUE THREAD

**Issue by Thelinil** [chummer5a/chummer5a#1838]
vehicles.xml has duplicate GUIDs for the BMW Trollhammer and the Ford Titan, and duplicate GUIDs for the Yerz Kit and Yerzed Out

gear.xml has duplicate GUIDs for Reinforced Microwire and Microwire, Reinforced Standard Rope and Standard Rope, and Reinforced Stealth Rope and Stealth Rope

Looks like whoever added the Trog book's new equipment forgot to generate new GUIDs for some of them

### Environment
Chummer Version: 5.181.193.186
Environment: Windows 8.1
Runtime: probably .NET 4.5.1

**Comment by chummer5a** [comment]
Fixed in the latest commit. Whups.
