### ISSUE TITLE
Chummer crashes if you open a char that has a Technique added to Aikido if Chummer is running in German

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#1839]
### Environment
Crash ID: 363fcf00-c7d1-41df-89e3-b2cf1e3c6d3e
Chummer Version: 5.193.187
Environment: Windows 10 Enterprise Insider Preview
Runtime: 4.0.30319.42000

### Expected behaviour
Char is in carreer mode
Chummer 5.193.187 open char like 5.193.134 does.
Be able to add a Technique to  Martial Arts

### Actual behaviour
Chummer 5.193.187 crashes with open a Char with Aikido and a selected Technique
And it crashes if you try to add a Technique
Also tried it with Teakwondo

It works wwithin Chummer 9.193.134, i didn´t test other versions

Crash followup id = 6634cf9e-9af4-47e8-9724-4de15ce73a25

### Steps to reproduce the behaviour
Try to open char with MA and Technique
Add MA and then a Technique

**Comment by chummer5a** [comment]
Fixed in 729c021
