### ISSUE TITLE
Submersion ...

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#1841]
seems still to be not wirking, as i can choose no echo after choosing a submersion grade.

Additionaly ... the Handling Modifiers for different Tires or Vehicle Empathy is not calculated

**Comment by chummer5a** [comment]
Can't replicate the issue with submersion. Click Add Grade, right-click on the Submersion Grade treenode, click Add Echo. Handling modifiers for tires have been implemented, vehicle empathy needs a new improvement to be created.
