### ISSUE TITLE
multiple social limit improvements added

### ISSUE THREAD

**Issue by rabidlama704** [chummer5a/chummer5a#1845]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.193.182)
Environment: (win10)
Runtime: (NET 4.5.1)

### Expected behaviour
only improvements that correspond to character equipment are listed

### Actual behaviour
several improvements from various high fashion armor items are listed

### Steps to reproduce the behaviour
unknown, suspected;
1. launch chummer
2. open character
3. go to the gear section and add armor
4. use drop down to move to 'high fashion armor'
5. change to 'browse' tab within armor window
6. popup appears
7. select ok on popup until it goes away

### Link to affected character file
https://drive.google.com/open?id=0B7qiduIO6sMfMTdfZFZtYVhQX2M
![highfashion_improvements_bug](https://user-images.githubusercontent.com/28424536/28810264-06b9fe5a-7646-11e7-93d6-f93088b0ba82.png)
![highfashion_armor_bug](https://user-images.githubusercontent.com/28424536/28810263-06b8f2e4-7646-11e7-9eaf-a40b05424d55.png)

**Comment by chummer5a** [comment]
Well, that's interesting. Um. In theory if you buy an appropriate bit of gear first it should automatically pick it and not show that window. Will have to investigate further beyond that.
