### ISSUE TITLE
Enhancement to Character Roster

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#1846]
Is it possible to allow a single character to be cleared from the character roster

![roster](https://user-images.githubusercontent.com/17562417/28828718-2b325c86-7697-11e7-9da0-e521a92c47de.png)

Maybe right-click on a character that presents "Clear" option, or "Clear selected character" on the File menu?

**Comment by GearheadLydia** [comment]
Try deleting that character from the recent characters list by right-clicking?
