### ISSUE TITLE
[Feature Request]  Ignore Modification Restrictions

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1847]
Hello, I'd like to request a House Rule feature to remove the modification restrictions on gear.  What do I mean by this?  I mean things like 'mutually exclusive' weapon and vehicle mods excluding other similar mods.  I'd like that it be allowed for you to add the excluded mods when this house rule is in play so that players can use more mix and match equipment, since I have found some of the limitations disagreeable.  Like the inability to use Electronic Firing with a Suppressor, even though a Suppressor is something you screw onto the end of the barrel, since both are considered "barrel mods".

**Comment by OLStefan** [comment]
With weapon mods, you can already do this. Just change the slot to 'none' while adding a mod.

**Comment by Reshy** [comment]
What about for weapon mods that are considered "mutually exclusive" beyond just slots?  Plaststeel Components, for instance.

**Comment by OLStefan** [comment]
Not with those, but at least with slot-specific one, like in your last example.

**Comment by Reshy** [comment]
I'd like the option for the latter then, it's more of an edge case, but still.  Shadowrun is supposed to be Optoelectronic, so the conflict about how the components are incompatible with Smartlinks doesn't make sense.  At least to me, so a house rule to fix that would be appreciated.

**Comment by chummer5a** [comment]
It's doable, but I don't like creating houserules for things that can be managed through [override files](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files). Blanket ignoring requirements and forbiddens could cause additional problems.

**Comment by DelnarErsike** [comment]
I'm closing this issue because it can be performed using a combination of the Custom Data Directory system and the amend system. You can create amends for the items whose restrictions you'd want to remove, then package them into a custom data directory that you can enable and/or distribute to others to enable.
