### ISSUE TITLE
Redliner is weird again

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1852]
### Environment
Chummer Version: 199
Environment: w10
Runtime: (If you don't know this, it is probably .NET 4.5.1

https://github.com/chummer5a/chummer5a/issues/1749

it's back again, but the skillpools seem to be correct (with +2 stats)

Having poked at it more, seems like a display issue. Limits are correct, skillpools are correct, etc. Adding things to limbs or removing things from them seems to force an update. But reloading the character shows the wrong stats on the atts table

**Comment by chummer5a** [comment]
Whups, wrong issue.

Seems to be working properly in the latest build; could you please test and confirm?
