### ISSUE TITLE
Combat Sense not adding to Dodge

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1856]
### Environment
Chummer Version: 5.193.199
Environment: Windows 8
Runtime: .NET 4.5.1

### Expected behaviour
Combat sense adds it's rating to your dodge pool.

### Actual behaviour
Combat sense doesn't appear to add it's rating to the existing dodge pool "Indirect Dodge".

**Comment by DelnarErsike** [comment]
Hmm, nevermind on that, looks like Dodge as a bonus-receiving stat isn't tracked. This also affects the Reakt genemod. Should be a straightforward fix.
