### ISSUE TITLE
[powers.xml] Some Adept Ways seems over populated

### ISSUE THREAD

**Issue by dashifen** [chummer5a/chummer5a#1863]
Specifically, the Athlete, Magician, and Spiritual way seem to be overused.  Beast, for example, is listed with 10 powers and note that one more power could be chosen in Street Grimoire but it's linked to 36 in powers.xml (once of which is Improved Potential which is listed once per limit).  Is there a reason for this?  Is it to try and cover for the "choose an additional power" option?  If so, how did you determine which you'd allow?

Thanks,
Dash

**Comment by chummer5a** [comment]
Hrm. Actually according to the errata document, that sentence for beast should've been removed. Oops, not sure how that one stuck around.

**Comment by dashifen** [comment]
So it is the "pick another power" option for some Ways that results in a few dozen marked as options in Chummer?

**Comment by chummer5a** [comment]
Yup. Magician's and Spiritual can both cannibalise from other lists. There's probably a better way I could implement it.

**Comment by dashifen** [comment]
Nope, that makes perfect sense.  Interestingly, I never interpreted that to mean that Magician and Spiritual could cannibalize from other lists, but rather they could choose *any* other power.  Regardless, that's what I needed to know.  As for Chummer, you do you; I'm just trying to consume your XML for a different purpose and was confused when some Ways had so many Powers.  Thanks!
