### ISSUE TITLE
Adept with bio/cyber essense/magic loss has incorrect MAG stat calculation

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#1866]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: latest source
Environment: Win10
Runtime:  .NET 4.5.1

### Expected behaviour
Adept magic value correctly calculated

### Actual behaviour
Essense loss due to bio/cyber is being added twice.

### Steps to reproduce the behaviour
Load attached character.  She has Magic 6(5) -- it was bought up to 6, then 1 point of bio/cyber was installed -- but it is displaying as 5(5).  So far not too big a deal.  She can correctly choose 5 points of adept powers and buy up to 5 ranks in a single power.

Move her to career mode.  Her magic now displays as 4(4).  She is also listed as having -1 adept points, and a limit on adept powers of 4 ranks.

### Link to affected character file
https://drive.google.com/open?id=0B16_Tk8Lw7gnU3c4cGUwdThrNFE

**Comment by cfresquet** [comment]
Further testing indicates this became broken with Nightly-v5.193.207.  Nightly-v5.193.206 works correctly.

**Comment by chummer5a** [comment]
I can't replicate this in the latest nightly build. Could you please re-test and confirm?

**Comment by cfresquet** [comment]
Checked out latest source and retested, it's working now. Thanks.
