### ISSUE TITLE
 Issue: adding improved reflexes adept power crashes the programme

### ISSUE THREAD

**Issue by LukasdeWit** [chummer5a/chummer5a#1868]
### Environment
Crash ID: 781b5a4f-4b03-4601-b76f-29048020c7f8
Chummer Version: 5.194.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
improved reflexes is added to the adept power list at lvl 1

### Actual behaviour
the application crashes

### Steps to reproduce the behaviour
create an adept with cat mentor spirit (not sure if mentor spirit is relevant), go to adept powers tab, click add power button, select improved reflexes, click ok button. then the program crashes

**Comment by drakir75** [comment]
Cat mentor is not relevant. Crashes without mentor spirit.

**Comment by Leonard03** [comment]
Can confirm that it crashes even on a completely blank character, as in, adding that adept power is the first thing done after the initial gen screen, Chummer still crashes.

**Comment by chummer5a** [comment]
Should be working properly in the latest build: https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.194.1

**Comment by Leonard03** [comment]
Yep, works for me now.
Cheers!
