### ISSUE TITLE
Options for karma costs are not initialized and not saved

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1870]
### Environment
Chummer Version: 5.194.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The karma costs should automatically be set to the values given by the rule books.
And the set values should be saved.

### Actual behaviour
For a new "installation", the karma costs in the options are not automatically set according to the rules. Especially the karma costs for binding foci are all set to 0 by default.
You have to click the button to "reset" the karma costs to the default values given by the rule books.
After the next restart of Chummer5a, the karma costs for binding foci are again set to 0.

### Steps to reproduce the behaviour
Unpack the Chummer5a zip file to a new empty directory.
Start Chummer5a.
Open the options dialog and go to the tab for the karma costs.

**Comment by chummer5a** [comment]
Fixed in latest commit.
