### ISSUE TITLE
Table view for adding weapons and armor not using all available translations

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1871]
### Environment
Chummer Version: 5.194.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Show table column titles and content in the selected user language.

### Actual behaviour
The column titles of the table view in the dialogs to add weapons or armor are in English.
On the first tab (single item display), the corresponding labels are shown in German.

In the table view (weapons and armor), the availability is shown in English. On the single item view, it is shown translated to German. For example the table shows "3R" and the single item view shows "3E" (which is the correct translation).
In the weapons dialog, additionally the ammo data is shown in English in the table view and shown in German in the single item view. For example the table shows "16(c)" and the single item view shows "16(s)" (which is the correct translation).

### Steps to reproduce the behaviour
Set Chummer5a to a language other than English - German in my case.
Open any character and go to the dialog to add a weapon or an armor.

**Comment by chummer5a** [comment]
Fixed in the latest commit.
