### ISSUE TITLE
Gear List below bottom of chummer window, resizing does nothing

### ISSUE THREAD

**Issue by JetstreamGW** [chummer5a/chummer5a#1872]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.194.6
Environment: Windows 10, 64 bit
Runtime: probably .NET 4.5.1

### Expected behaviour
I should be able to scroll to the bottom of the gear list. 

### Actual behaviour
I can't do that. The bottom of the gear list is below the bottom of the chummer window, and even if I resize it, it doesn't move that. I put an image up on gyazo

https://gyazo.com/650486ee446d9140c65c34e10cdeca1c

If you see there, you can't even see the bottom arrow, and I've resized chummer, but the bottom of chummer's usable area seems to be ... unchangable?

### Steps to reproduce the behaviour
It happened when I put the character into career mode.

### Link to affected character file
http://www.angelfire.com/scifi2/jetstream/Drake_Shadowbane_-_Sum.chum5

Hopefully this works. I don't really have a place to put files other than this ancient web service.

**Comment by chummer5a** [comment]
Oh thank god, someone else actually has this issue. I was convinced it was limited to me. It might be linked to Windows 10, but I haven't had a chance to properly look into it.

**Comment by chummer5a** [comment]
Unable to reproduce in current builds.
