### ISSUE TITLE
Bugged Essence Holes in Career mode

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1876]
### Environment
Chummer Version: 5.194.8
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
In career mode: Essence holes are created by removing/selling implanted 'ware and stay until filled with new 'ware

### Actual behaviour
In career mode: Essence holes are created by removing/selling implanted 'ware.
They are deleted (better said absorbed) into the regular essence once closing a character (and maybe Chummer) and re-opening

### Steps to reproduce the behaviour
Create a character with (extensive?) cyber-/bioware. Move to career mode. Sell/Delete/Remove some 'ware. Essence hole should be created. Close character window, close Chummer.
Open Chummer anew, open character, go to "Cyberware and Bioware" tab, Essence hole should be gone.
Also, look at essence: It should be increased by the value of the (now removed) essence hole (which should not be possible without extensive, expensive and time-consuming treatments, according to Chrome Flesh)

**Comment by chummer5a** [comment]
I can't replicate this in current builds, is it still an issue for you?
