### ISSUE TITLE
Suggestion: version number in nightly archive names?

### ISSUE THREAD

**Issue by WeaverThree** [chummer5a/chummer5a#1877]
I just realized that every binary download on the site is named Chummer.Nightly.zip, but the source files have the version number embedded in the filename. Is it possible to add that version number to the binary archive also? It gets a little confusing having e.g. Chummer.Nightly(7).zip and so when keeping up to date :3

**Comment by chummer5a** [comment]
That naming convention was just because it's easier to manage the updater that way. I need to review and update that method anyway, it's rather fragile.
