### ISSUE TITLE
chummer5a 5.194.0 :  Issue: - Adept Power Improved reflexes crashes

### ISSUE THREAD

**Issue by Leadershinji** [chummer5a/chummer5a#1879]
### Environment
Crash ID: a320bd86-9b2f-4e44-ab11-8e6b1f654306
Chummer Version: 5.194.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Added adept power improved reflexes to adept dwarf metaclaass hum. After everything else was setup.
Should have added the adapt power and added the reflex / rea stats.

### Actual behaviour
It crashed... but only if i select this adept skill

### Steps to reproduce the behaviour
Like mantioned above :
Adapt dwarf metaclass hum. 450 karma avail 9 -all books exept hongkong and 2050. Setup the char rea 3, body3, edge3 magic 5 and some other stats. Give skill group stealth 1, close combat1, athletics 1. 
Adapt powers : Combat sense 2. Hang Time 3, Light Body 4 Nimble fingers 1, Wallrunning 1.
And finally add the improved reflexes... which crashes chummer...
Or use this char : 
https://drive.google.com/open?id=0ByuMf57oRRNveFRzM1A5U21wNU0

**Comment by chummer5a** [comment]
Fixed in current nightly builds. http://get.chummer.net
