### ISSUE TITLE
Knowledge Skills Using Karma Rather Than Knowledge Skill Points

### ISSUE THREAD

**Issue by rjfrankenberger** [chummer5a/chummer5a#188]
When adding knowledge skills to a character, Chummer is using 7 karma points (BP) to add the knowledge skill instead of using the character's available knowledge skill points. 

Karma points are only spent when the knowledge skill is selected from the dropdown menu or by increasing the rating from 0 to 1. Increasing the rating of the knowledge skill beyond 1 does not cost additional points (neither karma nor knowledge skill points). Additionally, the knowledge skill points do not seem to be able to be refunded when reducing the knowledge skill's rating down to 0, but the karma points WILL be refunded if the knowledge skill is deleted using the "Delete" button.

This has been tested using several different characters, but a guaranteed reproduction of the issue can be obtained by using Priority System:
A - metatype 
C - Attributes 
B - Adept, Magician, or Technomancer
D - 22 Skills/0 Skill Groups
E - 6,000
Dwarf, Adept, Metavariant=None, Free Skill = Aeronautics Mechanic

**Comment by chummer5a** [comment]
Could you confirm your application version? Sounds like you're on something
pre-165.1.

**Comment by rjfrankenberger** [comment]
Oh, yes. I apologize. It looks like I was using an older version. I've downloaded the current release and this issue seems to no longer exist.
