### ISSUE TITLE
Missing content: Focused Awakened

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#1882]
### Environment
Chummer Version: 5.194.0

Elementalist, Hedge Wizard, Null Wizard and Seer aren't implemented yet. They're apparently supposed to layer on top of other priority selections; simplest method may be to create new qualities (Updating quality requirements/forbiddens) and priority selection choices to mimic the restrictions and free stuff.

Seer and Null Wizard getting metamagics for free is slightly awkward, as there's no current code supportfor that.

**Comment by DelnarErsike** [comment]
Implemented in commit c1a1f11e8c2546d97339b9dd134451ed45382252.
