### ISSUE TITLE
 Issue: - Can't create character in career mode with customdata

### ISSUE THREAD

**Issue by oddmage** [chummer5a/chummer5a#1884]
### Environment
Crash ID: cf108403-c75e-40ab-a020-34b74a759952
Chummer Version: 5.194.11
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Character saves in career mode.

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Open up Deitritus, click create, try and save or save as.
[customdata.zip](https://github.com/chummer5a/chummer5a/files/1253718/customdata.zip)
[Deitritus.zip](https://github.com/chummer5a/chummer5a/files/1253720/Deitritus.zip)

**Comment by chummer5a** [comment]
The natural weapons are formatted wrong; change the avail for them to 0.
