### ISSUE TITLE
Chummer crashes when using screenreader

### ISSUE THREAD

**Issue by Berenion** [chummer5a/chummer5a#1888]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version:Chummer 5.149.0 (What version of chummer are you running?
Environment:Windows 7 Home Premium 64-bit (Operating system here. If it persists over multiple OS's list them all)
Runtime: .NET 4.6.1 (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Run without crashing.
### Actual behaviour
Crash after some time. Chummer crashes instantly or after no more than 30seconds.
### Steps to reproduce the behaviour
Download screenreader NVDA. Run screenreader. Run chummer. Press Tab or any of the cursor keys, or sometimes only wait.
### Link to affected character file
(Enter text here)

Hey, I'm a visually impared user. I tried chummer on more than one computers using NVDA, but every time the crash occured. I tried using JAWS, but the result was the same.
Chummer works when not running the screenreader, but that means that someone has to read everything out loud to me...
I use NVDA specifically because it's free.

**Comment by chummer5a** [comment]
Pushing a new nightly build now, see if that helps you out. Should finish building in around ten minutes. Get it from get.chummer.net, see if that helps.

**Comment by Berenion** [comment]
It seams to be working now. Thank you!
