### ISSUE TITLE
Check Validity function Issues

### ISSUE THREAD

**Issue by Zer0SumGame** [chummer5a/chummer5a#1893]
### Environment
Chummer Version: 5.194.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
I expected Chummer's Check Validity function to properly recognize Positive Quality Karma tallies

### Actual behaviour
Character at 23/25 Positive Quality Karma, Check Validity says I've used more than 25 Karma on this character

### Steps to reproduce the behaviour
Currently have Made Man, Common Sense, Restricted Gear, and Rank (5 Karma)

### Link to affected character file
https://www.dropbox.com/s/lnu7pht5q7o97ov/GunSammyLupus.chum5?dl=0

![screenshot 138](https://user-images.githubusercontent.com/31462848/29853664-a444a35e-8d17-11e7-8d09-7effb9d9c94d.jpg)

**Comment by chummer5a** [comment]
Group contacts count towards your positive quality limit, per RF p177.
