### ISSUE TITLE
Chummer hangs for several seconds after adding an item

### ISSUE THREAD

**Issue by Faldrian** [chummer5a/chummer5a#1895]
Whenever chummer seems to recalculate stats or do validation, the GUI hangs for several seconds. This is best to reproduce when adding gear.

### Environment
Chummer Version: 5.194.0 (but that also happened with the nightly from 31.08.2017)
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I want to add an item (after already adding an item, but it also happens when adding the first item) in "Street Gear -> Gear" and hit the "add & more" button and the mask immediately pops up, ready for the next selection.
Same expected behaviour when adding a lifestyle, weapons, clothing ... all other items that use the same GUI-Elements for adding them.

### Actual behaviour
The Dialog to choose the Gear pops immediately back up, but the programm is not responding for several seconds. Only when it is responding again, the "Nuyen remaining" at the bottom is updated.

This slowness also happens when changing selections in the gear item tree on the left.

### Steps to reproduce the behaviour
See: "Expected behaviour"

### Link to affected character file
Newly created character using the karma system, file: 
[Mark Meiwarts.zip](https://github.com/chummer5a/chummer5a/files/1272078/Mark.Meiwarts.zip)

**Comment by chummer5a** [comment]
This should be working properly in current nightly builds. If not, feel free to reopen the issue.
