### ISSUE TITLE
Improved Reflexes crashes the sheet

### ISSUE THREAD

**Issue by Aurora-Eluvia** [chummer5a/chummer5a#1897]
### Environment
Crash ID: df2720fc-f479-4f3d-b656-58272a21db12
Chummer Version: 5.194.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Add improved reflexes to Adept Power tab.

### Actual behaviour
Crashes application

### Steps to reproduce the behaviour
Just add Improved Reflexes.

**Comment by chummer5a** [comment]
Fixed in current nightly builds, will deploy a new release version shortly.
