### ISSUE TITLE
Print issue: Armor enhancements are missing in the printed document

### ISSUE THREAD

**Issue by Bonebreaker9** [chummer5a/chummer5a#1898]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Things like audio enhancements, gasmasks and RFID chips inside the armor should be seen on the document

### Actual behaviour
In the preview and the printed charsheet they aren't included inside the armor panel

**Comment by Lochabar** [comment]
Can you try with the latest release (5.195.0) or even the latest nightly (5.195.9)?

If the problem still exists can you upload the the character file and I will take a look at the xsl.

**Comment by Bonebreaker9** [comment]
When I tryed with the latest release, it was fixed. *thumbs up*
