### ISSUE TITLE
Unlocking Rigger 5.0 Drone Mods

### ISSUE THREAD

**Issue by HighLordTherix** [chummer5a/chummer5a#1907]
### Environment
Chummer Version: 5.195.0
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
With Rigger 5.0 enabled, should have a set of vehicle modifications and a set of drone modifications, as the options available are different and are named differently. (example, custom Pilot program for drones)

### Actual behaviour
Rigger 5.0 is enabled. Shows vehicle modifications/upgrades available, but none of the drone upgrades (specific pilot programs, modifying base stats etc). Viewing the vehicles data xml file shows a number of items listed as (Drone) matching the availability, rating and intended function of the items in question. Pilot Enhancement for vehicles available, which uses mod slots, but not the Pilot for drones from Software Solutions P.127 in Rigger 5.0. Drones also do not have the Mod Points system Rigger 5.0 intends them to use.
However, as previously stated, the vehicle modifications is available in the vehicle xml file, and are available in the chummer program. On inspection of the xml files, it appears the attribute/pilot/upgrade mods are present, with an additional 'required' and 'optionaldrone' qualifier, that I believe is what is preventing it from showing up in the program. How do I enable this, so I can make full use of the content that is clearly in the data file for the current release, but is not available when running a character?

(Excerpt from the vehicles xml shown below, with one of the inaccessible objects highlighted.)
![vehicles excerpt](https://user-images.githubusercontent.com/32111688/30615433-e06e6818-9d86-11e7-9658-add8cb02943b.png)

**Comment by daishidirewolf** [comment]
Why was this closed with no comment? I am having the same problem.

**Comment by HighLordTherix** [comment]
I was the one who opened and then closed this. Go into Options, and under
Optional Rules if Rigger 5 is enabled, there's the option to "Use Drone
Modification Rules (R5 122)". Tick that and you're good to go.

For the life of me I cannot figure out why it's not automatically enabled
with the book though, since one would think if you're using the book you
want to use its content.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
