### ISSUE TITLE
Suggestion: Metropole Sourcebook

### ISSUE THREAD

**Issue by tCut** [chummer5a/chummer5a#1914]
The Metropole book focuses on the region of Amazonia (and specifically the Metropole sprawl).  It's a book which has been out for almost a year now, and yet the gear, lifestyle modules, and tradition it adds to SR5 are not yet in Chummer.  [http://www.drivethrurpg.com/product/196456/Shadowrun-Shadows-in-Focus-City-By-Shadow-Metropole](url)

**Comment by tCut** [comment]
I am more than willing to provide a quick rundown of the additions if needed, but for obvious reasons I do not wish to go into full detail on every addition.

**Comment by chummer5a** [comment]
Implemented by 650a423.
