### ISSUE TITLE
selecting the 'add & more' button crashes the app

### ISSUE THREAD

**Issue by rabidlama704** [chummer5a/chummer5a#1915]
### Environment
Chummer Version: 5.195.20
Environment: win10
Runtime: probably .NET 4.5.1

### Expected behaviour
chummer does not crash

### Actual behaviour
chummer crashes when the user selects 'add & more' while attempting to add the 'electronic witness'm quality

### Steps to reproduce the behaviour
1. create a new character/ load an existing one
2. select 'add quality' button on the common tab
3. highlight any quality
4. select the 'add & more' button
5. chummer crashes

### Link to affected character file
https://drive.google.com/open?id=0B7qiduIO6sMfRENoVERUOVlFRGs
![chummer crash](https://user-images.githubusercontent.com/28424536/30780924-fb999e6a-a0d2-11e7-8f9b-9ea35abb2561.png)

**Comment by DelnarErsike** [comment]
Chummer5 was attempting to autosave your character to a location to which it does not have write permission. You generally need Administrator privileges to write to anywhere in Program Files, so unless you run Chummer5 as an Administrator (you shouldn't), it won't be able to write the current autosave folder you specified. We may be able to change the code so it won't crash if it cannot autosave, but in the future, make sure Chummer5 has proper permissions to its autosave folder.
