### ISSUE TITLE
Adept power "improved ability (skill)" added by mentor spirits doesn't work

### ISSUE THREAD

**Issue by cnschu** [chummer5a/chummer5a#1916]
### Environment
Chummer Version: 5.195.0.0
Environment: Windows 10

### Expected behaviour
If you create an adept and add the "mentor Spirit" quality with an mentor spirit who gifts the character with the "improved ability (skill)" adept power (like "Pig" or "Seducer"), then the power will be added to the adept powers. The dice pool of the selected skill will be increased by the level of the before mentioned power.

### Actual behaviour
If you create an adept and add the "mentor Spirit" quality with an mentor spirit who gifts the character with the "improved ability (skill)" adept power (like "Pig" or "Seducer"), then the power will be added to the adept powers. 
The dice pool of the selected skill will **not** be increased by the level of the before mentioned power.
Instead, the help tooltip of the dice pool of the affected skill shows "...+ Power source not found (0))) +..."

This bug seems to affects all mentor spirits who gift the "improved ability (skill)" adept power to the charcter.

### Steps to reproduce the behaviour
1. Create an adept character
2. add "Mentor spirit" Quality
3. select "Seducer"
4. select "Con"
5. select "Adept Powers" Tab ("improved ability (skill)" is added)
6. select "Skills" Tab
7. hover mouse over the dice pool of the Skill "Con"
8. dice pool is too low, tooltip shows "...+ Power source not found (0))) +..."

### Link to affected character file
https://1drv.ms/u/s!AqKb9IvSrj2CgcET2ow0pZglbgcLig

**Comment by DelnarErsike** [comment]
Please the try latest nightly build to see if the issue is still present.

**Comment by cnschu** [comment]
Hi there,

the buils 5.195.20 sort of resolves the problem.
if i create a new character with this build, the problem no longer exists.

But if i open an 5.195.0.0 character who has experienced this probelm before, it's still polluted with a lot of "...+ Power source not found (0))) +..." in the tooltips.

Here is a link to such an old character:
https://1drv.ms/u/s!AqKb9IvSrj2CgcJ37bJ2oqot5T5oyA

If i open this character with 5.195.20 and remove and add the mentor spirit quality again, the problem seems solved in the first place, but as the following screenshots are showing, there seems some leftover of the bug in the character file.

https://1drv.ms/i/s!AqKb9IvSrj2CgcJ5FNkPMivc4DgyrQ
https://1drv.ms/i/s!AqKb9IvSrj2CgcJ6izAiem2eB1gB_Q
https://1drv.ms/i/s!AqKb9IvSrj2CgcJ7SRMRMKEE_IDreQ

The editor should remove such leftover XML from the character file.

sincerly yours
Christian

**Comment by cnschu** [comment]
hi,

after analysing the chum5 file, i think there are leftover "improvement" tags.

sincerly yours
Christian

**Comment by DelnarErsike** [comment]
Yup, it was actually a compound problem. One of the facets was that bonuses/improvements added by free powers that were added by mentor spirits weren't actually getting deleted when the mentor spirit quality was deleted. Those "undeleted" improvements would be orphaned and never deleted, not even if you Re-apply Improvements.

The solution I'm going with in the long-term is to have the Re-apply Improvements completely wipe out all improvements including orphaned ones. This is both easier than adding code to specifically look for and wipe out orphaned improvements caused by this specific bug, and it should also future-proof Chummer against possible future issues where people might save characters with orphaned improvements.

**Comment by cnschu** [comment]
Version:  5.195.21

after "special / re-apply improvements", the improvements are correctly calculated.
but the orphaned improvements will **not** be removed.

see atached screenshot.
![image](https://user-images.githubusercontent.com/32237924/30795378-8eb3c572-a1cd-11e7-8207-d1afc23cddaa.png)

**Comment by chummer5a** [comment]
That fix wasn't included in the latest nightly build. Next scheduled run is at 00:00 UTC, about 18 hours from now.
