### ISSUE TITLE
Add Weapon Entry for Elemental Body

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#1918]
The Adept Power Elemental Body adds a weapon with DV: (Magic x 2)P and AP (Magic x 0.5). Therefore Chummer should add that as a weapon entry.

**Comment by chummer5a** [comment]
Needs modifications to the TotalAP property of Weapon.cs to support reading generic attributes. Simple enough to read in the same way as how CalculatedDamage uses it.

**Comment by SquadronROE** [comment]
Taking a look at this

**Comment by SquadronROE** [comment]
Woof - CalculatedDamage is a 400 line property, TotalAP is a 300 line property. I think going in and changing things would be risky without knowing more specifics about what should be added and where.

@OLStefan can you provide a bit more detail about where you'd expect to see the weapon entry and how I can get there in the UI? I'll need more details about this. Basically I'd like steps so I can get to the right form and see where the missing entry is. Then I can trace through the code to see how it works and make a better change.

**Comment by DelnarErsike** [comment]
Support is already in for having attributes and the like be factored into both Damage and AP. The main thing missing from this is to allow powers to add weapons. You may choose between creating the long-overdue improvement that adds a weapon (similar to `addgear`) and dealing with all the issues that can cause, or mimic the flimsy system used by gear, armor, and cyberware that adds weapons and deal with all the issues that *that* will cause.
