### ISSUE TITLE
small tweaks 

### ISSUE THREAD

**Issue by Megapulse** [chummer5a/chummer5a#1922]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.195.0
Environment: (Operating system here. If it persists over multiple OS's list them all) win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1) .net 4.5.1

### Expected behaviour
adept power commanding voice for .25/lvl
### Actual behaviour
commanding voice 1 pp (has it been updated to 5th?)
Authoriative tone? what is that and it isnt in the book listed
### Steps to reproduce the behaviour
xxx

### Link to affected character file
xxx)

**Comment by chummer5a** [comment]
[Street Grimoire Errata.](https://www.shadowruntabletop.com/wp-content/uploads/Downloads/E-CAT27003E_SG-Errata.pdf)
P. 170, COMMANDING VOICE CHANGE
The version of Commanding Voice on p. 185, Stolen Souls, stands. This power is changed to Authoritative Tone, costs 0.50 PP per level (max 3), and is described as follows: Adepts with this power can speak in a way that immediately makes people want to believe them and follow their orders. For every level of this power, an adept gains a +1 die to any Opposed Social Skill Test that they initiate (normal limits apply).
