### ISSUE TITLE
Empathetic Listener

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1927]
### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
If the positive quality "Empathic Listener" is taken, to see the skill "Etiquette" coupled to Intuition in the skills tab and calculated with Intuition when printed.

### Actual behaviour
Etiquette is still associated with Charisma.

### Steps to reproduce the behaviour
Take the quality Empathic Listener.

### Thanks
Once again, thanks for all the hard work on Chummer5.

**Comment by DelnarErsike** [comment]
Empathic Listener does not changed Etiquette into a CHA-linked skill. If you hover over the dicepool, the appropriate INT-represented pool can be seen.
