### ISSUE TITLE
New houserule request

### ISSUE THREAD

**Issue by ArtOfCombat** [chummer5a/chummer5a#1932]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: .NET 4.5.1

Can we have a houserule where restricted gear can apply to cyberware grade? My group uses this rule, but I can't complete my character in chummer because of it.

**Comment by chummer5a** [comment]
So is this rule supposed to replace the 24 limit, or be in addition to it?

**Comment by ArtOfCombat** [comment]
In addition to it! 24 points of any grade.

**Comment by chummer5a** [comment]
Hmmm. It'll take a minor refactor of the logic, but that shouldn't be a problem.

**Comment by DelnarErsike** [comment]
Duplicate of #1089.
