### ISSUE TITLE
Print Damage Resistance Pool on character sheet

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#1935]
From reddit: [Link](https://www.reddit.com/r/Shadowrun/comments/73nt70/chummer_add_damage_resistance_pools_to_print_out/)

> Hello!
Is there any way to add Damage Resistance pools to the Chummer print out? It's on the Conditional Modifiers within the Chummer window, but not on paper.

**Comment by DelnarErsike** [comment]
I've added a couple of them to the Character::PrintToStream() method, specifically all toxin resistance dice/immunities, all pathogen resistance dice/immunities, and fatigue resist.

There's still Damage Resistance (easy) and resistance against every single type of elemental attack (harder) to add.
