### ISSUE TITLE
Sensor Functions listed as 'Chummer.List Item' when adding Sensor Functions to Sensor Arrays

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#1948]
### Environment
Chummer Version: Nightly-v5.195.35
Environment: w10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Sensor functions being brought up when you try add them to a sensor (array). 

### Actual behaviour
Brings up this. https://i.imgur.com/rwDvbtS.png

But also has this https://i.imgur.com/xcM3TcX.png which works correctly.

### Steps to reproduce the behaviour
Try adding a sensor function to a sensor array. Car or gear.

Ooops. Title >_>

**Comment by DelnarErsike** [comment]
Aware of the issue, I just didn't have time to commit the fixes yesterday.

**Comment by Rinnolk** [comment]
👍

**Comment by DelnarErsike** [comment]
Issue is fixed in code and should be out with the next nightly.
