### ISSUE TITLE
No options for shapeshifters besides Equine

### ISSUE THREAD

**Issue by ArtOfCombat** [chummer5a/chummer5a#1952]
### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
You should be able to select any shapeshifting race/metahuman combination, but you can only select equine for shifter type.

### Actual behaviour
Only Equine shifters show up under the shapeshifters tab.

### Steps to reproduce the behaviour
Try creating a shapeshifter character.

### Link to affected character file
None made yet.

**Comment by chummer5a** [comment]
They're not actually supposed to be in the main data file yet; I'm still testing their implementation in the shapeshifter_attributesection branch. ETA sometime in the next two weeks, depending on how much time I have for data entry. Duplicate of #272.
