### ISSUE TITLE
Infected: Banshee corrections

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#1954]
### Environment
Chummer Version: 5.195.0
Environment: OSX (Wine)
Runtime: I don't know this, it is probably .NET 4.5.1

### Expected behaviour
Optional Power list should include: 
* Enhanced Senses (Hearing, Smell)
* Fear
* Immunity (Pathogens, Toxins)
* Mist Form
* Paralyzing Howl
* Regeneration

Additionally, Source should point to RF 136

### Actual behaviour
Optional Power list instead includes: 
* Enhanced Senses (Hearing)
* Immunity (Pathogens)
* Enhanced Senses (Smell)
* Immunity (Toxins)
Enhanced Senses and Immunity have both been split into 2 different optional powers each, Fear, Mist Form, Paralyzing Howl, and Regeneration are nowhere to be seen.

Additionally, Source incorrectly points to RF 80

### Steps to reproduce the behaviour
Create new elf, buy Infected Banshee quality. 

### Link to affected character file
[Banshee.chum5.zip](https://github.com/chummer5a/chummer5a/files/1370215/Banshee.chum5.zip)

**Comment by DelnarErsike** [comment]
Please read RF 134. All powers listed under "optional powers" can only be gained after chargen, and only once every two in-game months. However, some Infected may choose some optional powers at chargen as part of their Gained Powers list, which is why you're seeing those four under Banshee.
