### ISSUE TITLE
 Issue: - Install and Restart for update crashes program

### ISSUE THREAD

**Issue by IraJacobs** [chummer5a/chummer5a#1955]
### Environment
Crash ID: 345f22cc-57fa-43ea-b878-822c34cbbedc
Chummer Version: 5.195.0
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
install & restart

### Actual behaviour
program crash, and then failure to load subsequently

### Steps to reproduce the behaviour
try to update app

Seems to be because Chummer Version: 5.195.0 downloading "build 195" and trying to update existing files that are in use.

**Comment by DelnarErsike** [comment]
Chummer5's updater renames some files that tend to be in use during the update. In the current stable version though, there might be some in-use files that don't get renamed, and the updater can crash if it does not have the proper permissions to rename/delete a file. The next version of the nightly should solve the issue.
