### ISSUE TITLE
Character creation priority selection is broken

### ISSUE THREAD

**Issue by inund8** [chummer5a/chummer5a#1957]
### Environment
Chummer Version: 5.193.194
Environment: Win 7
Runtime: probably .NET 4.5.1

### Expected behaviour
When in character creation mode
Special>Change Priority Selection>OK
Expected all attributes to be reset zero

### Actual behaviour
Attributes go into the negative, right now my character has -16 of 24
Also changing these priority seems to also break the attributes counter, so that it counts 1 point as costing more than 1 point, seemingly linked to the number of times you've changed it

### Steps to reproduce the behaviour
When in character creation mode
Special>Change Priority Selection>OK
Expected all attributes to be reset zero

### Link to affected character file
chummer file attached as a txt (just change it to .chum5)
[broken.txt](https://github.com/chummer5a/chummer5a/files/1378198/broken.txt)

**Comment by chummer5a** [comment]
5.193.x is an outdated build. Please update to a newer build and re-test. https://github.com/chummer5a/chummer5a/releases

**Comment by inund8** [comment]
fixed in 5.195

**Comment by chummer5a** [comment]
Glad to hear it.
