### ISSUE TITLE
Missing level adjustment for adept power heightened concentration

### ISSUE THREAD

**Issue by Tingel2** [chummer5a/chummer5a#1958]
### Environment
Chummer Version: 5.195.0 set to German
Environment: Windows 10 1703
Runtime: 4.7.02046
### Expected behaviour

If I set the language to German and add the adept power heightened concentration, it should be translated to "Erhöhte Konzentration" and I should be able to raise the level.

### Actual behaviour

If I set the language to German and add the adept power heightened concentration, the level is fixed to the first and has still its English name.

### Steps to reproduce the behaviour

- Start Chummer, toggle all Sourcebooks in the options menu and change the language to German.
- restart application
- Create an adept or mystic adept and add the adept power heightened concentration

This may be because of different rules for the English version. It seems in the English book the power has no levels.
The German book changed the power to be depended on the level without a level cap.

### Link to affected character file
[Magieradept.zip](https://github.com/chummer5a/chummer5a/files/1380415/Magieradept.zip)

**Comment by chummer5a** [comment]
Language files don't override game rules. We're currently implementing some systems that will allow amending these settings in a more controllable fashion.
