### ISSUE TITLE
 Issue: - Ally Spirit Creation Failed

### ISSUE THREAD

**Issue by Tooonfish** [chummer5a/chummer5a#1959]
### Environment
Crash ID: f6a07342-48f1-4ff6-a409-6b1b680cf50c
Chummer Version: 5.190.0
Environment: Windows 10 Education N
Runtime: 4.0.30319.42000

### Expected behaviour
Editor not crashing

### Actual behaviour
Editor crashed after creating a new ally spirit critter file

### Steps to reproduce the behaviour
Chose Ally Spirit under the Spells and Spirits Tab, selected Force 4, Owed Services 4, Put in a name and clicked: link to a character file -> create critter
dialog to enter a file name for the new critter appears and after that the prompt to enter a power, either Possession, Materialization or Inhabitation
After selecting Materialization and clicking OK, the editor crashed

**Comment by DelnarErsike** [comment]
5.190 is an old version, and I am unable to find the items needed to reproduce this in the latest stable version. Could you re-check this for 5.194 (stable) and/or 5.195 (nightly)?

**Comment by Zitchas** [comment]
I recreated this issue, albeit a bit shorter than they did. Following the steps listed, Chummer (I'm running 5.195.40) crashes when I click on the "create critter" option in the pull-down menu from the link icon.

Chummer gave me a  crash report code thingy of: 63693c0b-b9b2-4c3c-9806-43395b897016. Unfortunately the crash reporter reported an error while trying to upload the crash report.
