### ISSUE TITLE
Quality: Made Man

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#196]
Oh wow, group contacts are a thing. Shit. 

Quality needs a handler in ContactControl for Made Man, which skips the first three points of Loyalty. Easy loop, but we need an indicator of which group the character is a Made Man for. 

Napkin code:
Foreach (contact in group contacts)
If user is a Made Man fetch the Extra tag
If Extra tag matches the name of contact, set the minimum Loyalty to 3 (Unless an errata confirms it's free?) but otherwise treat as normal. 
Subtract spent karma from Positive Quality limit.

**Comment by joha4270** [comment]
In QA phase, will be in next push

**Comment by joha4270** [comment]
Pushed in #227
