### ISSUE TITLE
Crash followup id = f3c0461b-67b0-4408-89d7-b8a28e65c83b

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1961]
Nightly (5.40)

Attempting to open character sheet from previous version (5. 2 or 3 something) via recient character page.
Crash
Attempt to open same character file via File\Open
Crash

Attempt to open older (3/4/5.X version) files of different characters
No problem

Crash handler info (why does it offer to send a you report if that button/option doesnt do anything?) 
Crash followup id = f3c0461b-67b0-4408-89d7-b8a28e65c83b

Unless a secure email address is provided via some sort of private messaging, I am unable to provide sheet links.

**Comment by chummer5a** [comment]
Chummer5isalive@gmail.com

**Comment by chummer5hasanerror** [comment]
issue resolved in version .43
