### ISSUE TITLE
Missing Vehicle: Proteus Lamprey, Core Rulebook

### ISSUE THREAD

**Issue by Monzill82** [chummer5a/chummer5a#1967]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.193.149
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The Vehicle Proteus Lamprey (Pg 464 Core rulebook, stats in in the table PG 465) to exist

### Actual behaviour
It does not.

### Steps to reproduce the behaviour
Open up chummer, look at vehicle section.

### Link to affected character file
No applicable characters

**Comment by chummer5a** [comment]
incorrect book code. If you open up vehicles.xml and change line 4765 to SR5, it'll load properly. It'll be in the next nightly build otherwise.
