### ISSUE TITLE
Weapon Foci Not Adding to Melee Diepool

### ISSUE THREAD

**Issue by Yiphyin** [chummer5a/chummer5a#1968]
Chummer Version: 5.195.0.0
Environment: Windows 10
Runtime: .NET 4.7 (Creators Update)

### Expected behaviour
Bound weapon foci should add their rating to the diepool of the weapon, per Core pg 320 ("When used in physical combat, it gives you its Force as a dice pool bonus on your melee Attack Test."). It's the same for Astral combat tests.

### Actual behaviour
Bound weapon foci do not add die to the die pool on the weapon in the Weapons tab. 

### Steps to reproduce the behaviour
1) Create a mystic adept or adept (not tested with magician)
2) Add a weapon to the Weapons tab and give the character at least one point in the Blades skill. Note die pool on weapon.
3) Add a Weapon Foci (any rating) in the Gear section, select the weapon from step 2, and check the box in the Bonded Foci window to bind it.
4) Check die pool on the weapon in Weapons, note no change in die pool on weapon.

I've tested this on Created and un-Created characters and both display this behavior.

**Comment by Yiphyin** [comment]
Oh, to note I was testing this with a sword so the weapon used the blade skill in the above bug reproduction method.

**Comment by Lochabar** [comment]
This covers some of issue #1848
