### ISSUE TITLE
Enhancment: Add new technomancer priority errata

### ISSUE THREAD

**Issue by StarWeaver** [chummer5a/chummer5a#1969]
### Environment
Chummer Version: 5.195.42 (I checked the otpions and house rules too)
Environment: N/A
Runtime: N/A

### Enhancment Request

New technomancer errata regarding the priority build system has been released:

> Status: Provisional
> Priority Table Clarification (P. 65, Priority Table)
> In the Magic or Resonance column for Technomancers, change the number and type of skills in each row as follows:
> Priority A: Change from "two Rating 5 Resonance skills" to "three Rating 5 skills from Resonance, Electronics, or Cracking skill groups"
> Priority B: Change from "two Rating 4 Resonance skills" to "three Rating 4 skills from Resonance, Electronics, or Cracking skill groups"
> Priority C: Change from none to "three Rating 2 skills from Resonance, Electronics, or Cracking skill groups"

Sources:

https://www.reddit.com/r/Shadowrun/comments/75pobz/new_techno_errata_starting_skill_boosts/
http://forums.shadowruntabletop.com/index.php?topic=24595.msg492902#msg492902

**Comment by DelnarErsike** [comment]
We are aware of the provisional errata. In fact, if you search those very same sources, you'll see some of us as among the very first people to respond to it.

Provisional errata is prone to changing, so we do not tend to implement errata in Chummer's official data files until it has official status. You can always make your own custom data files though to add them in yourself.

**Comment by Lochabar** [comment]
https://www.reddit.com/r/Shadowrun/comments/75pobz/new_techno_errata_starting_skill_boosts/ now shows this as "Official".

Have these changed now been implemented in Chummer5?
Or, given the Reddit comment "... we'll be providing the relevant override files as custom content", where is the custom data file that is needed to allow them?

**Comment by OLStefan** [comment]
As it is official now it is integrated in chummer.
