### ISSUE TITLE
Quality Issue (see what I did there)

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#1971]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.43
Environment: Windows 10 64byte
Runtime: NET 4.5.1

### Expected behaviour
Should be able to pick a value between 1 & 15 for the "In Debt" Quality.

### Actual behaviour
Entering a value causes the Quality to disappear.

### Steps to reproduce the behaviour
1] Start a character.
2] Choose the In Debt negative quality.
3] See that you cannot choose a value for it.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
That's not how the UI works, though admittedly it might need some redesigning. "Value" during the quality selection screen just lets you filter by the karma value of a quality. If you want to increase In Debt ranks, you first add the In Debt quality, then either add more instances of it, or increase its Quantity via the numerical up-down under the "Add Quality" button.

**Comment by chummer5a** [comment]
Does seem to be a bug with the quality rating picker, if you change the value of a quality it just increments/decrements the linked quality by one.

**Comment by DelnarErsike** [comment]
Latest commit should both clarify the UI and fix the issue recognized by chummer5a (they were two separate things).
