### ISSUE TITLE
Chummer5a won't open

### ISSUE THREAD

**Issue by Glitch-kun** [chummer5a/chummer5a#1972]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Nightly-v5.195.43, 5.195.0
Environment: Windows 10 Creator's Update
Runtime: .NET 4.5.1

### Expected behaviour
When the .exe is run, program should open

### Actual behaviour
Program doesn't open, no window ever opens

### Steps to reproduce the behaviour
Download Chummer5a, and... try to run it? I'm really sorry, this isn't helpful

### Link to affected character file
None, since program fails to ever start

**Comment by chummer5a** [comment]
I had someone report a similar problem earlier and it turned out that they hadn't extracted the whole archive properly.

**Comment by Glitch-kun** [comment]
Yeah, uh, think that was me. I dunno why it happened several times, probably a problem with 7zip though. Sorry ^.^;
