### ISSUE TITLE
Zone (drug) from CF is missing

### ISSUE THREAD

**Issue by skachm** [chummer5a/chummer5a#1974]
Version 5.195.0

Zone (CF p. 184) is missing from the gear file

**Comment by DelnarErsike** [comment]
Zone doesn't have a cost or availability entry on p. 189, nor an addiction rating or threshold on p. 188, and the data is neither in the Missions FAQ PDF nor in any of the official errata threads on any of the forums.

Until we get some sort of inclination as to what its stats are supposed to be by RAW, we cannot add it in good faith.
