### ISSUE TITLE
 Issue: - Chummer crashes when highlighting certain weapons in add weapon

### ISSUE THREAD

**Issue by BigBadShay** [chummer5a/chummer5a#1975]
### Environment
Crash ID: 9beffd41-6c42-498e-9547-1a103cf76438
Chummer Version: 5.195.43
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Clicking or moving to highlight Tactical Grapple Gun to view weapon information displays weapon information

### Actual behaviour
Chummer instead crashes, brings up crash reporter, which itself crashes.

### Steps to reproduce the behaviour
Character in career mode> Street gear tab> Weapon sub-tab> add weapon> Search for tactical grapple gun or enter exotic ranged weapon tab> Click or use arrows to highlight Tactical Grapple Gun> Crash

**Comment by chummer5a** [comment]
Should be fixed in the next scheduled nightly build, which should finish compiling in a couple of minutes. Technically it's fixed in .45 but you may as well just wait for the next one.
