### ISSUE TITLE
 Issue: - program shows an available update for the same version

### ISSUE THREAD

**Issue by IraJacobs** [chummer5a/chummer5a#1977]
Chummer 5a / tools / Check for updates
shows "Future Build 196" with a list of app changes.  It can be downloaded, and "Install and Restart"ed but then the same update is shown when you check for updates again, in an endless cycle.  

If 196 is not actually available, why do the download and install buttons work? Is it just redownloading 195 every time? 

Disregard everything below, it ceased happening after the first crash.  New problem is above.  
### Environment
Crash ID: f07144be-33e8-48d6-8be6-25d1d4623aa7
Chummer Version: 5.195.46
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
program restarts with updated version

### Actual behaviour
crashes because of write access

### Steps to reproduce the behaviour
try to update

I submitted this issue before, but someone responded saying the next nightly would fix it, and closed the thread.  Well, this is the nightly from today, and here we are again.  I would write better details but the window closes when I click to create a new issue...

Additionally - "An error happened while collecting crash information"

**Comment by chummer5a** [comment]
All nightly builds are listed in the changelog as the next release build. It's a legacy naming convention that I never really got around to changing. So when you update to 5.195.46 and check for the next build, it'll still show as 5.196.

**Comment by IraJacobs** [comment]
It doesn't seem to just be naming though - it will actually redownload and apply the [same version?] every time you try to update.
