### ISSUE TITLE
Survival Knife opens weird custom item dialogue boxes

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#1985]
### Environment
Chummer Version: 5.195.49
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Searching for Survival Knife just  brings up the survival knife, and that's all.

Likewise, double clicking on survival knife just ads a knife to the inventory.

### Actual behaviour
First situation:
When I search for "Survival Knife," when typing it in, about the time it gets to the "v" in surv, it pops up a "Select a Value" dialogue box asking "Enter a name for this custom item." I enter a value, and it gives a "Select a Number" with the text "Select a Cost for text_inputed_for_custom_item_here" and a number field. It flips back and forth between these two dialogue boxes several times before they disappear leaving me at the weapon selection screen. 

Second situation:
Find "survival knife" in the weapon selection box and double click on it. This will trigger the same behaviour as in situation 1, but ends up with the weapon select box closing and the survival knife added to the inventory.

Once the survival knife is in the inventory, it has a sub-category entitled "Survival Knife Bonuses", with five fields with the names and values previously entered listed here, and a second "Survival Knife Wireless Bonuses" wich lists the remaining two values and numbers listed.

### Steps to reproduce the behaviour
First case: Go to weapon select screen, type surv into the search field.

Second case: Go to weapon select screen, scroll down to find the suvival knife, click ad. If necessary, click ad a second time after going through all the dialogue boxes.

**Comment by DelnarErsike** [comment]
Gorrammit, I thought I fixed this yesterday.

**Comment by Zitchas** [comment]
![survival knife](https://user-images.githubusercontent.com/32169904/31866062-6408f602-b736-11e7-9532-1a3f91bf8ef8.PNG)

**Comment by DelnarErsike** [comment]
Yup, looks like it is fixed in the latest dev build, but my fix didn't make it into the current nightly. Issue shouldn't be present in 195.50.
