### ISSUE TITLE
Feature request: Allow none of the mugshots to be selected as main

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#1987]
### Current behaviour
When a picture is added to the mugshot section, it is automatically selected as "Is Main Mugshot." If more than one picture is added and the "Is Main Mugshot" option is unchecked, Chummer automatically passes that on to the second mugshot. When one unchecks that box, it gets passed back to the first one.

In short, the "Is Main Mugshot" seems to act like a radio button that insists that one of the pictures be designated as the main one.

### Desired behaviour
That it is possible to leave all the pictures without the main mugshot tag so that all the pictures get moved to the "Other Mugshot" section instead of being included in the "Main Mugshot" section.

**Comment by DelnarErsike** [comment]
So, I made some changes to the Shadowrun 5 character sheet collection that should show up in 5.195.52, and one of those includes changing how the main mugshot is handled in the Shadowrun 5 character sheet collection. Among other things, the main mugshot is now its own section that can be toggled to be shown on/off when the sheet is printed or saved to PDF.

This means this enhancement is implemented in a bit of a roundabout way: you can add one mugshot file twice, then have the main mugshot section not show up when you print/export your character sheet, and that means all of your mugshots effectively only show up in the "Other Mugshots" section.
