### ISSUE TITLE
Error on crash-report upload

### ISSUE THREAD

**Issue by YourChummer** [chummer5a/chummer5a#1988]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.50
Environment: Windows 10 Enterprise (Microsoft Windows NT 6.2.9200.0)
Runtime: what I see in ProcessExplorer looks like 4.0.30319 (installed up to 4.7)

### Expected behaviour
Upload crash report, exit silent of give some sort of "it's done" dialog.

### Actual behaviour
It shows an error after or while uploading (it transmits data, but I can't see if its done when I get the error).
Somehow I can't attach the error image, so it's uploaded here:
https://imgur.com/a/76Flx

I tried it several times, one of the IDs is e8405207-26e6-4e1d-b376-3c38546dbd19
Has it been completely uploaded?

### Steps to reproduce the behaviour
Produce an crash (I currently keep getting an crash when I click "Add Armor" and then the "Browse" tab) and try to upload it.

### Link to affected character file
independent from character

**Comment by Zitchas** [comment]
Side note, the armor browsing bug is probably related to issues #1978 and #1979 that seemed to be fixed, but I just confirmed is back

**Comment by DelnarErsike** [comment]
The Crash Reporter is crashing because the service to which it's trying to connect is defunct. I've added in some extra bit of code that should show up in the next Nightly where the Crash Reporter will instead display an error message and a prompt to submit an issue to GitHub manually.
