### ISSUE TITLE
Skills Groups house rule

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#1990]
### Environment
Chummer Version: 5.195.52.0
Environment: Mac High Sierra (Wine 2.0.2)
Runtime: .NET 4.5.1

### Feature Request
Could you add a house rule to break skill groups during character creation?

It is explicitly forbidden in the rules, but my table allows it, and this used to be a house rule in Chummer4.
In 5a, we've had to work around negative karma costs and leftover skill points - not the end of the world, but still a little messy-looking.

### Expected Behaviour

 - Add ranks to skill group : points deducted from skill group allocation from priorities A, B or C
 - Add additional ranks to individual skills within the skill group : points deducted from active skill points allocation.

For example:
 - From skills priority C:
 - Add 2 to skill group Sorcery
 - Push Spellcasting and Counterspelling to 6
 - End result is : group broken ; Spellcasting 6, Counterspelling 6, Ritual Spellcasting 2 ; total cost 2 skill group points and 8 skill points.

Thanks for looking (and thanks for Chummer generally as well).

**Comment by chummer5a** [comment]
'Strict interpretation of breaking skill groups in create mode' should do it, I believe.

**Comment by oxford-fumble** [comment]
Mmmm - It really isn't the same thing...

Effectively, I'm talking about the ability to break skill groups as early as step 5 (spend skill points), instead of step 7 (spend leftover karma).

Following your suggestion means that one is allowed (or not if the box is ticked) to break skill groups in step 7.
