### ISSUE TITLE
Forbidden Arcana - Tradition Subtypes

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#1993]
### Environment
Chummer Version: 5.195.50

Forbidden Arcana introduced subtypes for traditions with specific benefits and drawbacks. This hasn't yet been implemented in Chummer. Simplest solution from our perspective would be to introduce them as qualities and implement a forcetradition bonus type that will lock the tradition to whatever they take. 

Other helpful bonus types may be to include initiation sequencing for the Islamic Magician (i.e. must take Fixation, Quickening, Advanced Alchemy, Anchoring in order before any other initiations).

**Comment by DelnarErsike** [comment]
An additional pointer to anyone who wishes to tackle this issue: right now, Chummer5 ties identifiers of metamagics and echoes to the particular initiation or submersion that added it, so divorcing those two from each other is a good first step to implementing some of Forbidden Arcana's content that relies on metamagics.

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/a8ab4a3212e02b0302f6438afed5d5bcd56de965
