### ISSUE TITLE
Skills tab Crashes Chummer after arbitrary number of changes.

### ISSUE THREAD

**Issue by rtngtom** [chummer5a/chummer5a#1997]
Chummer Version: 5.195.52, 5.195.53

### Expected behaviour
Players are able to select skills and specializations during chargen. Tangentially related, trying to enter in specializations will shift the cursor to another entry box after a single key is entered.

### Actual behaviour
Chummer crashes after a seemingly arbitrary number of changes made to skills.

### Steps to reproduce the behaviour
Create a character, change skills around until crash.
From extended testing, the crash seems to occur when manually editing entry boxes for skill points, either build or karma points, or after the client stops incrementing skill points through the buttons.

**Comment by rtngtom** [comment]
Providing an update in regards to the newest build(5.195.54): I was unable to crash Chummer outright with an existing character file, and have not tested with a new character, but the skills tab is still freaking out and becoming unresponsive during operation for periods of time. Unsure whether to mark this as fixed or not, but leaning to not.

**Comment by DelnarErsike** [comment]
Some changes were made to the skills control display in 5.195.55, and one or more of those could have fixed the issue. Can you verify that the bug still exists?

**Comment by rtngtom** [comment]
Issue seems to be resolved in the latest nightly. Cheers to the good work.
