### ISSUE TITLE
Lightly Worn armor

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2001]
### Environment
Chummer Version: 5.195.49
Environment: Windows 10
Runtime:  probably .NET 4.5.1)

### Wanted behaviour
To be able to buy lightly worn armor. (RG 59)
Can maybe be implemented as a mod to armor? Hard bit is removing features I guess.

### Actual behaviour
I can not (or don't know how to) buy lightly worn armor.

### Thanks
I thank you for all the work on Chummer5A.

**Comment by chummer5a** [comment]
Not really anything that needs to be implemented in code here. I guess we could add a lightlyworn node type and key the mods off that. 

New base item has the reduced cost and such, possibly implement a requirescontact property. Features are implemented as mods that are forbidden to everything except that armour. 

For the most part this would just be copy-pasta, generation of new IDs. Reasonably simple to implement.

**Comment by DelnarErsike** [comment]
... except an implementation of Lightly Worn requires that the user be able to restore individual features of the armor for 10% of the armor's base cost each. This requires messing around with the bonus system and activating only parts of a larger bonus node, so I definitely would not call _that_ part of Lightly Worn easy to implement.

**Comment by chummer5a** [comment]
Mortimer line has the Custom Fit, +1 Social Limit, and -2 Concealability Features. Create new copies of that line, call them all 'Lightly Worn XXX'. Make each of those Features into a discrete mod that requires the appropriate armour type or mod and is limited to one per suit. Cost == Armor * 0.10, Bob's more or less your uncle at that point. Shouldn't require anything unusual. It'd only be if you wanted to have a checkbox for Lightly Worn in the armour select window that did fancy stuff that we'd need to get complicated with it.

**Comment by chummer5a** [comment]
Newest Model would be something of a shit to implement properly, but we could just cheat there and change the base armour values for the adjusted armour entries. 

Ideally I'd prefer to have it be done by a single armour object, but given the limited amount of items that it'll ever actually be used with I'm a bit up in the air about it.
