### ISSUE TITLE
Cannot increase knowledge skills for career mode character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2002]
### Environment
Chummer Version: 5.195.55
Environment: Win 10
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Be able to increase an existing skill.

### Actual behaviour
Any existing skills cannot be modified.
Note: A new skill can be added and increased.

### Steps to reproduce the behaviour
Open an existing character and try to improve an existing knowledge skill.

### Link to affected character file
![skills](https://user-images.githubusercontent.com/17562417/32147544-3a4aed44-bcb7-11e7-9cab-5e8d4996c5fe.png)

**Comment by DelnarErsike** [comment]
Cannot replicate it on my end. Those buttons should only be disabled if the character doesn't have enough karma to buy/upgrade a knowledge skill to begin with, and that's how it works for me in both the dev build and the latest nightly.

**Comment by Lochabar** [comment]
This career character has plenty of available karma
![skills with karma](https://user-images.githubusercontent.com/17562417/32148342-91791b34-bcc3-11e7-9420-a2c9f421e80f.png)

**Comment by DelnarErsike** [comment]
... and green pluses where grey ones were before, if my eyes don't deceive me. Could you send a character file, seeing how I can't get my own test ones to reproduce the issue?

**Comment by Lochabar** [comment]
You're right. I had to reopen the character to get the second screen print and yes the skills are now editable. Just one of those things.
