### ISSUE TITLE
Chummer crashes on opening old char

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2005]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.58
Environment: Windows 10 x64 
Runtime: 4.7

### Expected behaviour
Open Chummer, open Chummer, work on Char

### Actual behaviour
Open Chummer, open Char, Chummer crashes

Crash followup id = 847646fa-1566-44fe-a6e0-f66941996627
[attributes.txt](https://github.com/chummer5a/chummer5a/files/1426380/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/1426381/exception.txt)
[crashdump-131538242052617656.dmp.gz.001.zip](https://github.com/chummer5a/chummer5a/files/1426394/crashdump-131538242052617656.dmp.gz.001.zip)
[crashdump-131538242052617656.dmp.gz.002.zip](https://github.com/chummer5a/chummer5a/files/1426395/crashdump-131538242052617656.dmp.gz.002.zip)
[crashdump-131538242052617656.dmp.gz.003.zip](https://github.com/chummer5a/chummer5a/files/1426396/crashdump-131538242052617656.dmp.gz.003.zip)
[crashdump-131538242052617656.dmp.gz.004.zip](https://github.com/chummer5a/chummer5a/files/1426397/crashdump-131538242052617656.dmp.gz.004.zip)

Had to add .zip to the file to get github to accept the upload. Packed with 7zip in gzip Format
Just cut the .zip from the filename

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Could we get a copy of the affected character file?

**Comment by OLStefan** [comment]
I get the same problem. With all my characters edited in recent versions.

Link to affeced file: https://drive.google.com/open?id=0B_ENMVBmw33SSVpneXdubFJHT0E

**Comment by DelnarErsike** [comment]
Odd, I'm able to open Testy McTestFace just fine. I think it's a culture issue somewhere, probably something is reading an essence string-to-decimal as culture-invariant when it's culture-variant or vice versa.

**Comment by OLStefan** [comment]
Nope, just me not thinking what I'm doing. I manually added the Essence attribute to that file and didn't think about that the file I linked gets automatically updated...

I just reverted the file, that way you should get the error again

**Comment by DelnarErsike** [comment]
Got my own characters to crash, looks like the problem is actually that AttributeSection::Load() doesn't have a legacy shim, and the essence problems are just a symptom of that.

**Comment by OLStefan** [comment]
I still got the same problem.

Link to character (extra copy this time): https://drive.google.com/open?id=0B_ENMVBmw33SNm9CLXlHN05vQzg

**Comment by ReallyDarkMatter** [comment]
I just tested 9.195.57 and that release works fine.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Stefan Niewerth <notifications@github.com>
Gesendet: Monday, October 30, 2017 6:24:02 PM
An: chummer5a/chummer5a
Cc: ReallyDarkMatter; Author
Betreff: Re: [chummer5a/chummer5a] Chummer crashes on opening old char (#2005)


Reopened #2005<https://github.com/chummer5a/chummer5a/issues/2005>.
