### ISSUE TITLE
Missing augmentations?

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2006]
### Environment
Chummer Version: 5.195.57
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
To be able to find every augmentation

### Actual behaviour
Bone Lacings, Orthoskin, Dermal Plating (+all other body/armor modifiers?) are missing.

### Steps to reproduce the behaviour
Create character. Try to buy some of above mentioned.

**Comment by chummer5a** [comment]
Can't reproduce it. Got a character to test it with?

**Comment by OLStefan** [comment]
I got one: https://drive.google.com/open?id=0B_ENMVBmw33SUWdUbkRZbjFSVXM

It seems the error is somewhere in the Requiremtn checking as most ware with a requirement does not get shown. I'm trying to find the issue right now, but could use help.

Right now i'm looking into the TestNodeRequirement method in SelectionShared.

**Comment by DelnarErsike** [comment]
Looks like working as Intended for Driver McCombatFace. They already have Orthoskin, so neither Orthoskin nor Dermal Plating show up in the list. They also already have Siemens Cyberspine, which includes Bone Lacing (Plastic), which removes all Bone Lacings and Bone Density Augs from the list of available 'ware.

**Comment by OLStefan** [comment]
There is other ware missing (I'd go so far as to everything with any forbidden tag). Another way to test it is to remove the Orthoskin and try to readd it.

Also the Cyberspine Upgrade (Celestial Warrior) shouldn't be possible to add, but is right now which is the same issue.

**Comment by OLStefan** [comment]
Problem seems to be that this predicate

`objCyberware =>
                               objCyberware.Name == strNodeInnerText && string.IsNullOrEmpty(objCyberware.PlugsIntoModularMount) &&
                               string.IsNullOrEmpty(strWareNodeSelectAttribute) || strWareNodeSelectAttribute == objCyberware.Extra`

is true, wheter or not objCyberware and strNodeInnerText are the same or not.
![weirdpredicate](https://user-images.githubusercontent.com/3206519/32174817-36ee524a-bd83-11e7-8d25-41fed389c4e8.png)
