### ISSUE TITLE
 Issue: - Appears while startin Chummer

### ISSUE THREAD

**Issue by EnaShosuro** [chummer5a/chummer5a#2007]
### Environment
Crash ID: d71cd0a2-bb7e-442a-9ad2-44c8027d8df8
Chummer Version: 5.195.0
Environment: Windows 7 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
After making a double click on the Icon Chummer should start

### Actual behaviour
Immediatly crashes

### Steps to reproduce the behaviour
-

**Comment by chummer5a** [comment]
Does the crash handler show up? What's the error message that it shows?

**Comment by chummer5a** [comment]
Does it work if you try one of the latest nightly builds from get.chummer.net?

**Comment by EnaShosuro** [comment]
Crash followup id = 8ba1e070-8302-4d39-bf06-8491b86585f5

![unbenannt1](https://user-images.githubusercontent.com/33224386/32175852-65ef459c-bd86-11e7-9e39-a0b1d77911bb.PNG)

**Comment by EnaShosuro** [comment]
I did not yet try to download another versoin

**Comment by DelnarErsike** [comment]
A couple things were changed in the updater, and one of those probably fixed this crash. I'm closing this for now, please re-open if you encounter it again and can provide us with more information.
