### ISSUE TITLE
Crash on saving a character

### ISSUE THREAD

**Issue by capt10hiett** [chummer5a/chummer5a#2008]
### Environment
Crash ID: 64984b63-d8ca-4a67-af44-28ca900fbc8d
Chummer Version: 5.195.0
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)
saving a charactor as reated for the first time
### Actual behaviour
(Enter text here)
crashed
### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Can you upload the character file somewhere for me to try and replicate the issue? If you compress the file into a zip you should be able to upload it here.

**Comment by capt10hiett** [comment]
Sorry about that, first time submitting a problem.
[The problem charactor.zip](https://github.com/chummer5a/chummer5a/files/1431828/The.problem.charactor.zip)
