### ISSUE TITLE
Can't create character

### ISSUE THREAD

**Issue by cjtoddx** [chummer5a/chummer5a#2010]
### Environment
Chummer Version: Nightly Release- v5.195.59, and other older not sorted crashes
Environment: Windows 10
Runtime: .NET 4.5.1 (Although I don't know what it really is 

### Expected behaviour
base Character generation after the priorities window

### Actual behavior
Crash Reporter Initiates 
### Steps to reproduce the behavior
1. Download Nightly Build- v5.195.59
2. Extract the zip file from downloads to desktop folder
3. Start chummer
4. create character using Icon in upper left, under File
5. Set to Priorities and Standard
6. Set Priorities E Magic, D Resources, C Metatype, B Attributes, A Skills
7. Select Human and Accept
Crash without any generation of character, the Priorities screen frozen.    

### Link to affected character file
https://drive.google.com/open?id=0BzeJMdeLxBLETk9QZ2MySUxGM2M
This a link to the totality of my chummer crashes on this computer. I only have the Nightly release- v5.195.59 sorted, the others are other release.

**Comment by cjtoddx** [comment]
Also, I am able to create Critters. If that's worth anything.

**Comment by OLStefan** [comment]
That issue is already fixed in the devbuild. It will be available in Nightly 5.195.60 due today at 0:00 GMT
