### ISSUE TITLE
Chummer 3.195.14 Update Chum5 file to 5.195.60

### ISSUE THREAD

**Issue by modsec** [chummer5a/chummer5a#2011]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.60
Environment: Windows
Runtime: (Net 4.5.1.) I don't know

### Expected behaviour
I updated the program. I expected it to maintain all stats and the like as were.

### Actual behaviour
When I launched the file and then hit Re-Apply improvements as it said. Afterwards the character had one more magic than previous in one spot, and 2 more in the other. https://i.imgur.com/1bg8jJg.png

### Steps to reproduce the behaviour
Use a character from version 3.195.14 and "Re-Apply Improvements." 

### Link to affected character file
https://drive.google.com/open?id=0B5jEWeDLMiL7MldSYk5mZndLZjA <-Updated one with the stuff gone funky

 https://drive.google.com/open?id=0B5jEWeDLMiL7NXFSOENDNXVQNjg <-The most recent previous file that experiences the same issue, but is still in create mode.

**Comment by DelnarErsike** [comment]
From what I can tell, the issue appears to be with the savefile itself. For some reason, the character's metatype minimum Magic (i.e. before all other modifiers are applied, including essence loss) is set to 2, not 1.

Aside from some incompatibilities with the new way Impaired Attribute is handled (Chummer5 will warn you of this), Re-apply Improvements seems to work completely fine and as-intended in the dev build.
