### ISSUE TITLE
Automatically Add Gear Locations Based on Gear Category

### ISSUE THREAD

**Issue by AGEdger** [chummer5a/chummer5a#2012]
UPDATE:

> Would you consider making a grouping system based off the category the items are from? If that makes sense. So, all ammo would be within it's own drop menu, and all B&E tools would be in the own drop menu, etc.

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Nuyen Normally Tracked

### Actual behavior
While dividing the gear into groups, Nuyen gets spent.

### Steps to reproduce the behaviour
Add multiple items, right-click and drag them over another item.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Cannot reproduce. Are you sure you're not dragging and dropping the item into a parent that has a different quantity than its previous parent?

**Comment by AGEdger** [comment]
I think you're right. I was just trying to group up my gear. Would you
consider making a grouping system based off the category the items are
from? If that makes sense. So, all ammo would be within it's own drop menu,
and all B&E tools would be in the own drop menu, etc.
