### ISSUE TITLE
Fake license disappeared from Street gear

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#2015]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.61
Environment: Windows 10
Runtime: don't know

### Expected behaviour
fake license in the list of fake ID's

### Actual behaviour
it's disappeared

### Steps to reproduce the behaviour
select "Street Gear" -> "Gear" -> "Add Gear" -> Category "ID/Credsticks" or "Show all"

### Link to affected character file
it's happened even with new created characters
![default](https://user-images.githubusercontent.com/33343265/32364837-3c5b947e-c088-11e7-892f-9070f31024f7.JPG)
![2](https://user-images.githubusercontent.com/33343265/32364871-6266f410-c088-11e7-9097-64f51c723ba2.JPG)

**Comment by chummer5a** [comment]
Forrrr some reason, it's set to require a Fake SIN.

**Comment by ARgits** [comment]
so, if i want buy a fake license, i need at first buy fake SIN and than buy license like modification/accessory to that fake SIN?

**Comment by DelnarErsike** [comment]
Correct, as licenses should always be attached to the SIN to which they were issued.

For the sake of issuing fake licenses to genuine SINs, I've allowed them to be added to Custom Items in the latest commit. Is there some use of licenses that you'd be looking for that don't have them attached to the issuing SIN?
