### ISSUE TITLE
Special Attributes when entering career mode

### ISSUE THREAD

**Issue by VE6CPU** [chummer5a/chummer5a#2019]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0.0
Environment: Win 7 Pro, Win 10 Pro
Runtime: Not sure

### Expected behaviour
created new character and have 3 special att points.  Put all on Edge as he is non-magical human.  Finished character and when I click the tick box for career mode then save it warns me that I have 3 special att points.  Cancel out and check and I did in fact use them on edge.  If I remove them from edge it puts them back on the right hand window.

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
Make new character with extra special atts.

### Link to affected character file
https://thebitbucket.ca/nextcloud/index.php/s/Y9KGMRJeZIsINPJ

**Comment by DelnarErsike** [comment]
Is this bug still present in the latest nightly? A lot of changes have been made to the attributes system, so it may have been unwittingly fixed.

**Comment by Lochabar** [comment]
There seems to be a problem related to this issue, or maybe its the same problem.

In 5.195.61 I used the "Check Character Validity" special option and got the following:

![check character validity](https://user-images.githubusercontent.com/17562417/32388464-c5b6c34e-c095-11e7-9ae1-ecaa1b11aeaa.png)

As you can see the special attributes have been spent, so why is the error window shown?
