### ISSUE TITLE
Enhancement: Character sheet Category Name printing

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2022]
### Environment
Chummer Version: 5.195.61 (and earlier)
Environment: Windows 7 home edition
Runtime: (probably .NET 4.5.1)

### Expected behaviour
The Category Name subtitles should be consistent across translations.

### Actual behaviour
The content of the variable "skillcategory" is not consistent across translations.

For example, the category "Combat Active"
- for a German character skillcategory is translated as "Kampf-Aktionsfertigkeiten"; the 'fertigkeiten' part of the value means 'skills'.
![grouped by name german](https://user-images.githubusercontent.com/17562417/32397563-60182bd6-c0b8-11e7-8081-af6c8f637ef2.png)

- for a French character skillcategory is translated as "Competences de combat"; there is no translation of 'skills'.
![grouped by name french](https://user-images.githubusercontent.com/17562417/32397560-57d8a108-c0b8-11e7-89e0-c3c5da988663.png)

- for a English character skillcategory contains "Combat Active".
![grouped by name english](https://user-images.githubusercontent.com/17562417/32397548-46abc964-c0b8-11e7-94d8-03dbe7952fe4.png)

Because the English version does not have 'skills' as part of the Category Name it is necessary to specifically check (in xt.skills.xslt) if English is the language of the character sheet and print "skills" after the Category Name.

![category name print](https://user-images.githubusercontent.com/17562417/32397466-f3a4adda-c0b7-11e7-9c7a-ea9c4ebd582d.png)

### Enhancement request
Would it be possible to supply the English contents of skillcategory (and presumbly skillcategory_english) with "skills" as part of the name.

I don't know about the Japanese and Chinese translations. Is it possible to verify what translation is supplied?

**Comment by DelnarErsike** [comment]
This has been semi-fixed in the latest nightly, in that I removed the " Skills" part from skill category displays. It was not really required for English texts anyway (since the entire bit being in the Skills table made it clear that they were names for skill categories), while as you mentioned, localizations did not really need them anyway.
