### ISSUE TITLE
Receive error message then chummer crashes when trying to create a shifter

### ISSUE THREAD

**Issue by litehound** [chummer5a/chummer5a#2023]
### Environment
Chummer Version: 5.195.61
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
According to the changelog, at least Falconine (Which I am trying to create) shifters are complete, and it  should be possible to select a metahuman form for one and then create it.

### Actual behaviour
Upon selecting a metahuman form or pressing 'OK' without one selected, receive the error message, "This Race/Metavariant combination is incomplete and will be completed in a future release. Attempting to create a character with this combination may result in unexpected results" and then the program crashes when this error message is closed.

### Steps to reproduce the behaviour
Select a metahuman form for a shapeshifter.

**Comment by OLStefan** [comment]
Can't replicate the issue when downloading a new version on my end.

Are you sure you copy your version in an empty folder? If not could you try downloading the Nightly again and unzip it into an empty folder and try again?

**Comment by litehound** [comment]
When copied into a completely empty folder it will let me select a metahuman form once, giving the error message and graying out the OK button. If I select a metahuman form again, the issue stated in the main post occurs.

**Comment by chummer5a** [comment]
Is this in Priority mode? I haven't completed the data entry for that yet, only karma/lifemodules are supported right now.

**Comment by litehound** [comment]
That explains my issue. However, now making one in karma I can't figure out how to access the animal form's atts

**Comment by chummer5a** [comment]
Once you've switched to career mode, you'll be able to toggle between the attributes.

**Comment by litehound** [comment]
Unless something happened in the errata, shouldn't the animal form's attributes be displayed at gen instead of the meta form since your meta attributes are derived from the points in your animal attributes?

**Comment by chummer5a** [comment]
Hrm. It's not supposed to be doing that. I'll look into it.
