### ISSUE TITLE
Life Module SIN Management

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#2024]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Nightly-v5.195.63
Environment: Windows 10
Runtime: default: .NET 4.5.1

### Expected behaviour
Can select all life modules.

### Actual behaviour
Cannot select certain life modules.
Validation rule fires error message:: "You cannot select this Quality because of the following Forbidden items you have already taken.SINner (National)"

### Steps to reproduce the behaviour
Create character. Life modules method. Select Human.
Select General UCAS for 1st Module.
Example second modules that do not work: Fugitive, White Collar, Arcology Living,
Example second modules that do work: Rich Kid, Early Emergence, IRU, Street Urchin, Military Brat,

### Link to affected character file
Not generated yet and not sure it would help.

**Comment by OLStefan** [comment]
That will certainly be a while until there is anything to test, as i plan to nearly completely rework how the life modules are handled (and there is this so-called real-life stealing my free time).

As soon as enough work is finished i gladly notify you.
