### ISSUE TITLE
Chummer fails switching language

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2029]
### Environment
Chummer Version: 5.195.65 (and earlier)
Environment: Windows 7 home edition
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Change language from English to French or German, Chummer asks if it should restart with the new options, and does so.

### Actual behaviour
Windows gets involved and says Chummer has stopped working. There is no Chummer problem log.

The language change is recorded in the settings file. So when I restart Chummer it opens with the changed language.

### Steps to reproduce the behaviour
This does not always happen. It often happens after using Chummer for some time before switching language, like this time. Other times, having done very little, switching language works correctly.

### Link to affected character file
![chummer has stopped working 1](https://user-images.githubusercontent.com/17562417/32413787-8fd6f8ee-c1de-11e7-9166-9d361c59b395.png)
![chummer has stopped working 2](https://user-images.githubusercontent.com/17562417/32413788-8fef0b78-c1de-11e7-90ee-1e0ce3d1dd9e.png)

**Comment by DelnarErsike** [comment]
I think this is caused by an odd interaction between Chummer5 wanting to close itself and Chummer5 wanting to save its options when the user confirms that they want to restart after changing options. If that's the case, then this is fixed in the latest commit, but I have no way of testing to be sure.

**Comment by Lochabar** [comment]
Let's close this for now and I'll see if it reoccurs.
