### ISSUE TITLE
Ammo skip not available for revolvers (cy)

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2031]
### Environment
Chummer Version: 5.195.52.0
Environment: Win7 through Wine 2.0.2 (Mac High Sierra)
Runtime:  .NET 4.6.1

### Expected behaviour
The "Ammo Skip" weapon modification (Hard Targets p.180) can be selected for any weapon with a drum or cylinder magazine.

### Actual behaviour
Ammo skip is available for drum-fed weapons, but not for cylinder-fed weapons (revolvers) 

### Steps to reproduce the behaviour
 - Under Street "Gear > Weapons"
 - Select a revolver (eg. "Ruger Super Warhawk")
 - Click "Add Accessory" ; this opens the list of available accessories
 - "Ammo Skip" is missing from the list

### Steps to reproduce the behaviour (option available with drum-fed weapons)
 - Under Street "Gear > Weapons"
 - Select a drum-fed shotgun (eg. "Auto-Assault 16")
 - Click "Add Accessory" ; this opens the list of available accessories
 - "Ammo Skip" is at the top of the list

**Comment by chummer5a** [comment]
Ammo Skip is an _Under_ mount accessory. None of the revolvers have that mount slot available, which is why it doesn't show up. Heavy Pistols are all Barrel, Top, Stock and Side slots only.

**Comment by oxford-fumble** [comment]
Ah, yes. It's not in the description, and I missed it in the table on page 183.
Shame, really - would have made a few guns more useful.

Anyway, sorry about the hassle, thanks for the reply.
