### ISSUE TITLE
Trying to add Image Link to glasses - not present

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2033]
### Environment
Chummer Version: 5.195.65
Environment: Windows 7 home edition
Runtime: (probably .NET 4.5.1)

### Expected behaviour
Right click on audio device and click "Add as Plugin" and be able to select "Image Link" from "Vision Enhancements".

### Actual behaviour
The "Vision Enhancements" category is blank.
Searching for "Image" shows nothing.

![vision enhancements](https://user-images.githubusercontent.com/17562417/32449617-b3352316-c2d7-11e7-9e58-69c4ed66d4a8.png)

**Comment by DelnarErsike** [comment]
From what I can gather, the problem is likely with the Sunglasses item (which isn't part of the default Chummer5 dataset), not Image Link. The only restriction to Image Link is that it needs to have a parent, otherwise it can be added to anything that would allow it.

**Comment by Lochabar** [comment]
Thanks for the info. I created a custom_gear file, copying the definition for glasses from the main file. I can now add vision enhancements correctly.
