### ISSUE TITLE
Default cost for new martial arts technique 4 instead of 5?

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#204]
My book says 5, at least.

**Comment by Tom-0169** [comment]
just tested with a new char and the cost was 5 karma for every technique after the first one

**Comment by chummer5a** [comment]
Hrm. Can't reproduce, default is set to 5 in the options, it should be fine.

**Comment by Tom-0169** [comment]
Could just reproduce the error with a char in career mode.
