### ISSUE TITLE
Delete default weapon accessories

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2041]
### Environment
Chummer Version: 5.195
Environment: Win 7
Runtime: .NET 4.6.1

### Problem definition

Some weapons come pre-loaded with accessories, but a player might want to change the load-out.
Currently, this is not supported by Chummer, and we are stuck with the pre-built options.

For example, one might want to take an Ares SIGMA, remove the fore grip in the "under" mod slot, and add an ammo skip instead.

Or, one might want to add a smartgun system to a FN HAR, and remove the redundant laser sight.

### Feature request

Ability to remove built-in modifications / accessories.
Please note that some accessories (Gas-vents in particular, and they are the only one as far as I can see...) are not able to be removed once installed, and therefore should NOT be an option for removal.

Thanks for looking.

**Comment by chummer5a** [comment]
Hrm. To my knowledge all standard accessories are considered to be integral to the structure of the weapon, which is supposed to be why they don't occupy a slot in the first place.

**Comment by oxford-fumble** [comment]
I see. In this case, it could be there are just some inconsistencies that threw me off - for example, even though the Foregrip of an Ares SIGMA 3 is in the "internal" slot, there is no possibility to add an Ammo Skip System to the "under" slot.

I guess this also raises the question of whether several gas vent systems are compatible, which I understand to be controversial, so better leave that one...

In terms of enhancement, though, I still think it would be neater to be able to remove undesired accessories - which represents a character going through the extra trouble of modifying their weapon to get it just as they like... 

Do you want a separate issue to identify the SIGMA3 error?

**Comment by DelnarErsike** [comment]
The SIGMA 3 "issue" would actually be a "Requires Errata/Clarification", because Submachine Guns do not have an underbarrel slot as per CRB p. 427, and Ammo Skip requires an underbarrel slot.

**Comment by oxford-fumble** [comment]
I see - I forgot there was under barrel slot on SMGs.
It's a bit frustrating that, by raw, the ammo skip is only applicable to 3 shotguns - it does need an errata!

Thanks - closing the issue.
