### ISSUE TITLE
Missing vehicle modules for Ruhrmetall Wolf II

### ISSUE THREAD

**Issue by Ascarin93** [chummer5a/chummer5a#2042]
### Environment
Chummer Version: 5.195.65
Environment: Windows 10
Runtime: it is probably .NET 4.5.1

### Expected behaviour
Question concerning the RUHRMETALL WOLF II From Rigger 5 pg. 77 on Chargen (i have the Restricted Gear Quality)
WOLF II (GROUNDCRAFT)
HANDL SPEED ACCEL BODY ARM PILOT SENS SEATS AVAIL   COST
   3/3         3         2      24      12       2       2       6       20F  330,000¥
Std. Equipment Enviroseal: life support (60 hours), Runﬂat tires
Options
Troop Transport: Seats 6/16 (0¥); 
Air Defense: add weapon mount w/ missile launcher (¥); 
Medical transport: add 2 stabilization beds, medkit (Rating 6), Seats 6/6 (¥); 
Mobile Staff Command Post: add tacnet, Seats 6/8 (¥); 
Light Tank: add weapon mount w/cannon, weapon mount w/ machine gun, Seats 6/6 (¥)

### Actual behaviour
when i select the it for "Purchase" it only comes with standard equipment minus Runflat Tires and costs 110000 Nuyen cheaper and it is supposed to have some Standard Configurations when you purchase it listed as those listed above and i cant choose them and if i add them myself then they wont actually get close to the listed price

### Steps to reproduce the behaviour
try to purchase the vehicle

if there was an errata i cant find please link it

**Comment by Ascarin93** [comment]
as a side note im going to throw my 2 bits into the customizable vehicle turrets, id say just make a Weapon Mount option and then give it some drop down menus like Cyberdecks just with the various settings so 
Type:            Flexibility         Visibility          Control
Light            Fixed               External          Manual
Standard      Flexible            Concealed      Armored Manual (AManual?)
Heavy          Turret              Internal          Remote
SUPER OBVIOUS I KNOW BUT IM THROWING IT OUT THERE DAMMIT

**Comment by chummer5a** [comment]
Looks like that vehicle never got a sanity check, it'll need to be updated. May need to come up with shenanigans for the configuration pods.

Weapon Mounts as a separate object are being worked on in the imaginatively-named WeaponMounts branch and might make it into release builds sometime soon. Just need to plot out a shim to convert old ones.

**Comment by Ascarin93** [comment]
ok so just a bad case of no one looked at the thing for some reason


why i can understand as Standard its Forbidden but still FREAKING TANK
