### ISSUE TITLE
"Add Spell" button on "Spells and Spirits"tab do nothing

### ISSUE THREAD

**Issue by CaraLePoke** [chummer5a/chummer5a#2049]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.69 (Nightly)
Environment: Windows 10
Runtime: don't know, probably .NET 4.5.1)

### Expected behaviour
When you click on "Add Spell" in the "Spells and Spirits"tab you should have a list of spell to select one.

### Actual behaviour
When you click on "Add Spell" in the "Spells and Spirits"tab nothing happen.

### Steps to reproduce the behaviour
Create a character
Ritual spellcatsting, Spellcasting and Sumoning skills are at five
Go to "Spells and Spirits"tab
Click on "Add Spell"
No list of any spell here

### Link to affected character file
It doesn't work on any charater for me

**Comment by DelnarErsike** [comment]
I'm unable to reproduce the issue using the dev build, but I removed a seemingly unnecessary bit of code from frmSelectSpell in the latest commit that may end up fixing this issue. If the issue persists in the next Nightly version, please attach one of your affected characters to help us reproduce the issue.

**Comment by Zitchas** [comment]
Also using .69, I can't replicate it. I tried with both an older character (still in create mode) and a new character. (old character had spellcasting at 6 with a 7 magic rating, new one had it at 5 with a 5 magic rating.)

**Comment by CaraLePoke** [comment]
Forget it. I tried again and it works... -_- Don't know what happen I tried on 3 different computer
