### ISSUE TITLE
prototype trasnhuman and free bioware.

### ISSUE THREAD

**Issue by Man-Of-Many-Names** [chummer5a/chummer5a#2051]
### Environment
Chummer Version: 195
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Prototype transhuman allows for bioware to be taken, up to 1 point, without deducting from essence.

box for "free" available to be ticked during character creation.

### Actual behaviour
Once in career mode the prototype transhuman quality ceases to function as expected. Essence is deducted as "normal". 

Bioware is unable to be selected as "Free" in character creation mode.

### Steps to reproduce the behaviour
Create a character with prototype transhuman, add bioware in career mode. 

Create a character. add bioware, search for "free" box.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Not a bug. Emphasis mine:

> You were built better than a normal human, so you may pick **up to** 1 point of Essence of bioware (not cyberware). While you must pay the normal cost in nuyen of the bioware and otherwise follow all character creation rules, you do not incur any essence cost. So, essentially, you gain **up to** 1 point of free Essence to be used exclusively on bioware. These special organs were genetically grown into you from your inception—they are as much a natural part of you as your liver or heart.

When you pick Prototype Transhuman, you choose up to 1 point of Essence's worth of bioware to come with your body. If you choose less than 1 point of Essence's worth of bioware, by RAW, you do not get to choose again at some point in time after you've picked Prototype Transhuman. It makes thematic sense this way, too: the bioware you choose for Prototype Transhuman is 'ware that you were born with, so there's no way you could get extra Prototype Transhuman bioware that you didn't have before once you've already been born.
