### ISSUE TITLE
Mentor Spirit Wise Warrior

### ISSUE THREAD

**Issue by ColdEmp** [chummer5a/chummer5a#2053]
### Environment
Chummer Version: 5.15.70
Environment: Windows 10 64 bit
Runtime:  .NET 4.5.1

### Expected behaviour
One free level of Improved Ability on a combat skill.

### Actual behaviour
Allows you to pick a combat skill twice when selecting a combat skill for the free level of improved ability.

### Steps to reproduce the behaviour
Adding the Mentor Spirit (Wise Warrior) and selecting the adept option, and either of the other two options.

### Link to affected character file
[Mystic Samurai finished.zip](https://github.com/chummer5a/chummer5a/files/1473035/Mystic.Samurai.finished.zip)

**Comment by Mliekseter** [comment]
I've had a similar issue with Improved Physical Attribute. Tried to make a Zyzz mentor spirit who grants 1 Level of Improved Physical Attribute, but it adds 2 levels and asks for the attribute twice
Although in my case, the bonus from Improved Physical Attribute didn't apply itself

**Comment by DelnarErsike** [comment]
Odd, I am unable to replicate this issue with the provided character when using the latest nightly version. When going Add Quality > Mentor Spirit > Wise Warrior > Adept Bonus, the Select Skill dialogue only appears once, and the selected skill only gets one free level of Improved Ability.

Is there any more info you could provide about the issue to help us replicate it?

**Comment by ColdEmp** [comment]
Strange, I just opened chummer and tried again, with my 5.195.70 nightly build, and it worked as intended. Don't know what was causing the issue then.
