### ISSUE TITLE
program crash by edit the options

### ISSUE THREAD

**Issue by PSI1919** [chummer5a/chummer5a#2054]
### Environment
Crash ID: 660a7119-159a-40e4-8e1b-70c4a3172b3e
Chummer Version: 5.195.71
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
no crash :)

### Actual behaviour
every test to edit the options (books, rules etc) led to a program crash with press the "ok" - button

### Steps to reproduce the behaviour
edit the options and press enter

**Comment by DelnarErsike** [comment]
I was unable to replicate the issue, but following code behavior based on how you've described the crash occurring, I stumbled upon some pieces of code that could theoretically cause such a crash under rare circumstances. The fixes for those should make it into the next nightly version.

I'm closing the issue for now, please re-open if you still encounter the issue in the next nightly version. If this ends up being the case, we'd also need more info. Chummer5a should create a crash dump whenever it crashes, see if you can upload one for us to examine.
