### ISSUE TITLE
Crash on Selected Negative Quality (Life Modules)

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#2059]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Should be able to focus on a selected Negative quality

### Actual behaviour
I selected Cancel on SINner National prompt. The Negative quality went in and I decided to try to change the value. I click on the Quality. Crash happened

### Steps to reproduce the behaviour
Using Life Modules.
Troll, Miami, Farm LivingHome Tutored, Skipped Education, Urban Brawler. Cancel on the prompted SINner entry. Click on the Negative Quality SINner (National)

### Link to affected character file
Cannot create Character File
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/1484342/chummerlog.txt)

**Comment by chummer5a** [comment]
Can't replicate issue in current builds.
