### ISSUE TITLE
Essence is rounded up for calculation of Magic/Resonnance

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2060]
### Environment
Chummer Version: v5.195.74
Environment: Win 7 (through Wine / High Sierra)
Runtime: .NET 4.6.1

### Expected behaviour
 - On an Essence 6, Magic 4 awakened character :
 - add a striking callus (for .05 Essence),
 - Essence drops to 5.95,
 - Magic maximum drops to 5,
 - Magic drops to 3

### Actual behaviour
 - On an Essence 6, Magic 4 awakened character :
 - add a striking callus (for .05 Essence),
 - Essence drops to 5.95,
 - Magic maximum drops to 5,
 - Magic stays at 4

### Additional Information
 - House Rule "Essence loss only reduces MAG/RES maximum" is unticked
 - Behaviour is relevant to both awakened and Technomancers (I tested Adepts, Magicians, Mystic Adepts and Technomancers) 
 - when Essence reaches the half point (eg. 5.5 exactly), the relevant special attribute drops by one - ie. 5.50 drops Magic by 1, but 5.51 doesn't.

### Link to affected character file
https://drive.google.com/open?id=1xmGE9AQtzpGzFI_cw0ZH5SG9-tnlX3ns

**Comment by chummer5a** [comment]
Can't replicate the problem with the character you provided or in my test characters, and I'm not seeing any real issues with the backing math for it. Essence Penalty is calculated as an integer with ceiling applied, so any decimal value will automatically round it up to the next whole number.

**Comment by OLStefan** [comment]
One weird thing i noticed while testing this issue on the dev-build:

The Label to show the current magic value shows the wrong value once magic was increased to 5. If i decrease magic back down to one the label still shows 5. Reducing the maximum through essence loss result in the right number shown, removing the 'ware results in the same error as before. The calculaiton for skill dicepools uses the right value, not the one the label shows.
![weirdmagic1](https://user-images.githubusercontent.com/3206519/32982401-84d30892-cc84-11e7-886b-523f1b06bc01.PNG)
![weirdmagic2](https://user-images.githubusercontent.com/3206519/32982402-84ea1a0a-cc84-11e7-8122-1e4b160ab407.PNG)
![weirdmagic3](https://user-images.githubusercontent.com/3206519/32982403-8507f8d6-cc84-11e7-9a9d-c904a0dd66ad.PNG)
