### ISSUE TITLE
Auto-Update not working properly, files not downloading

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#207]
Chummer seems to have a problem downloading the recent updates (some german language file has been stuck in there since the auto-update release).

Restarting Chummer or manually checking for updates opens the download window, then seems to download something, but doesn't actually change the files.

**Comment by chummer5a** [comment]
Hrm. There's nothing region-specific in the code, so I'd be inclined to
guess it's something to do with dropbox. Are there any files that do
download? Does this link work:
https://www.dropbox.com/s/l8yksfl57832c65/Chummer5.exe?dl=1

**Comment by Haekel** [comment]
Worked just fine.

**Comment by chummer5a** [comment]
Seems to be something wrong with the culture settings, will dig into it.

**Comment by Tom-0169** [comment]
Just took Chummer 5.165.1 and ran manual update - it did not show that chummer has a newer version
only offered me Priorities, Qualities, Sum to Ten Priorities, Traditions for download
what it dit NOT do
[logfile update Chummer 5.165.1](http://pastebin.com/s0vhPpCA)

Tested under 5.166 same error - it DOES change the file date, but doesn't do anything to the version number inside the files.
deleting the files and letting update run again results in files with the same version number

**Comment by chummer5a** [comment]
Should be good now.
