### ISSUE TITLE
Alternative weapon ranges not printed

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2070]
### Environment
Chummer Version: 5.195.75
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Both weapon range tables should be in the sheets.

### Actual behaviour
On the weapons tab of the GUI, both range tables for shotguns (standard, flechette) are shown with a corresponding name.
On the print sheets (at least the main Shadowrun 5 sheet), only the standard range table is printed.
Taking a fast look into the saved print xml file, it looks like the range table names are not in the xml file.

### Steps to reproduce the behaviour
Create a character with a shotgun and print it.

**Comment by DelnarErsike** [comment]
Alternate ranges are exported with the Weapon::Print() method, and they do show up if you select "Save as XML" as children under the `<alternateranges>` element. However, currently, no character sheet files support parsing of this information, so they do not show up in any character sheet.

**Comment by holgerschlegel** [comment]
Yes I know that.
To allow printing it, a name or description for the range table would be needed. Just printing two rows of ranges without a title does not help.
The GUI shows a label in the range row of the weapon page. For example "Shotgun" and "Shotgun (flechette)".
Would be nice if that titles (translated into the sheet language of course) are written to the print xml so it could be added to the sheets.
