### ISSUE TITLE
Enhancement: Character Roster list

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2074]
I would like to suggest new functionality for the Character Roster tab.

1) [x] Refresh
Add an option to refresh the Roster in alphabetical within Favourite/Recent.

Needed when new entries have been added to the Recent list, or a character has added/removed as a Favourite.

Suggestion: add to File menu with "Clear Unpinned Items"

2) [x] Switch character to/from Favourite
Ability to make a character (in the Recent list) a Favourite. And vice-versa.

Suggestion: a Rt-click sub-menu on the character in the list of names

3) [x] Remove character from the list
Ability to remove a single character from the character list (even a Favourite)

Suggestion: a Rt-click sub-menu on the character in the list of names

5) [x] Close character tab
The equivalent of "Ctrl+W" (File menu Close) to allow the character tab to be closed

Suggestion: a Rt-click sub-menu on the character in the list of names

- [x] Show open characters in roster view with some kind of visual indicator (Bold text, icon, etc.)

Note: If implemented, these functions would mean the list of characters could be removed from the "File" menu.

**Comment by OLStefan** [comment]
Added Checkboxes for easier tracking
