### ISSUE TITLE
Question: What is the wiki in the GitHub repository for?

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2075]
There is a wiki in the Chummer5a GitHub repository. What is it to be used for?

It looks like a source of technical information for Chummer5a. But some of the 
content, like Custom Data Files, is also referennced in the old Chummer5 Wiki (opened 
from the Chummer5 Help menu) at http://www.chummergen.com/chummer/wiki/.

If someone wants to copy and update the old wiki, should the content be added to the 
GitHub Chummer5a wiki?
Or should it be hosted somewhere else?

**Comment by chummer5a** [comment]
Yeah, it's been an idle side-project of mine to port over content from the old wiki to the new one and update it for our various changes to the object structure.

**Comment by Lochabar** [comment]
So the GitHub wiki is to be used for technical information for developers?

**Comment by Lochabar** [comment]
In which case can anyone suggest a reliable, free, wiki host?

I'm thinking of a new wiki with user help about how to use chummer. The chummer "Help" function would open to this new wiki.

**Comment by chummer5a** [comment]
Oh, sorry! I misunderstood what you were after. Yeah, feel free to use the wiki for that purpose. Most of what's actually in there is intended for end-users to create their own content rather than being a technical overview.

**Comment by Lochabar** [comment]
The https://github.com/mcMMO-Dev/mcMMO/wiki is an example of a custom sidebar. 
As well as the list of Pages, there is an additional sidebar allowing for submenus.

https://help.github.com/articles/creating-a-sidebar/ explains how to add a custom sidebar but I'm thinking it needs to be done by an administrator. Any chance this could be added?
It would save having to scroll down a long list of pages.

**Comment by chummer5a** [comment]
Righto, if you want to make any changes you'd edit 
https://github.com/chummer5a/chummer5a/wiki/_Sidebar.md

The search pane doesn't show up in our main pages control because there aren't enough pages yet.
