### ISSUE TITLE
Slow and Unresponsive

### ISSUE THREAD

**Issue by Coolandon77** [chummer5a/chummer5a#208]
Since build 164 Chummer has been very slow and unresponsive. When switching tabs, adding gear or increasing point values several minutes may elapse before the program correctly responds. 

Windows 8.1
AMD A10-7850K 3.7 GHz
64-bit OS, x64 based processor
8 GB RAM

**Comment by Neocyberman** [comment]
I had this same issue before that version too.

Result of antivirus constantly scanning everytime the program made any changes. Check your task manager to see if your anitmalware or antiviral software jumps in resource usage every now and then when you use the program.

Additionally, try running chummer as admin or creating an exception in your antivirus for the chummer EXE file.

**Comment by BodieSullivan** [comment]
For me it was Windows Defender... Once I added an exception for the chummer.exe all was right with the universe.

**Comment by Coolandon77** [comment]
Well much of the sluggishness was addressed by running the program in administrator mode and adding the file location and process to the windows defender exception list.  I would like to point out that the program still does not respond for some time when I fist change a tab.  And is slow when choosing Cyberware or some other pieces of gear.  

Thank you for your help. Please mark this issue as resolved.
