### ISSUE TITLE
Nuyen display on character sheets

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2080]
### Environment
CChummer Version: 5.195.77
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Nuyen amounts shown without decimals.
Larger Nuyen amounts have currency separators.

### Actual behaviour
Nuyen history displays decimals. (Didn't used to until recently.)
![nuyen history](https://user-images.githubusercontent.com/17562417/33058833-7110231a-ce89-11e7-87de-e07aa1cce1c1.png)

Larger Nuyen amounts do not have currency separators. (They used to until recently).
![nuyen large](https://user-images.githubusercontent.com/17562417/33058861-9a5dd230-ce89-11e7-8835-ee746fff345e.png)

Note: One or both of these problems with decimals are present on multiple character sheets; Expenses; Fancy Blocks; Formatted Text-Only; Game Master Summary; Text-Only; Vehicles; the various Shadow 5 sheets. (Basically all of those that show Nuyen amounts.)

The amounts used to display correctly until a couple of releases back. Why was this changed?

### Steps to reproduce the behaviour
Review character sheets with Nuyen history.
Review character sheets with large Nuyen amounts.

**Comment by Lochabar** [comment]
From the Nightly-v5.195.78 release "Nuyen costs will now always display with two fixed decimal places". Why show Nuyen with decimal places? Nuyen costs are integer, there are no fractional prices.

**Comment by DelnarErsike** [comment]
Please check the Currency category in the Add Gear screen.

**Comment by Lochabar** [comment]
I'd argue that you can't actually buy a single datachip - they come in a pack of ten. Because there is no actual fraction Nuyen currency. Harks back to the old Italian Lire; if you wanted change less than 100 Lire the shopkeeper would offer you a piece of candy.

As far as currency goes, RF 174 states "All rates expressed in relationship to one nuyen", no fractional amount suggested. You can't exchange a currency for 1.27 Nuyen; round it off!

Nowhere in any of the source books have I seen any prices shown with fractions of a Nuyen - the smallest price listed is one nuyen.

I don't see a need to clutter up every Nuyen expense with ".00" when it not needed.
