### ISSUE TITLE
Enhancement: Allow all portraits to appear in "Other Portraits" section

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2083]
If there is at least portrait in a character file, Chummer requires "Is Main Mugshot" to be checked on at least one of them.

If there is only one portrait, "Is Main Mugshot" is automatically rechecked even if you try to uncheck it. When you have 2+ portraits and uncheck "Is Main Mugshot" , one of the other portraits gets checked as "Is Main Mugshot".

Could the processing be changed so that there does not have to be a main mugshot?
Then all the portraits would show in the "Other Portraits" section.

**Comment by Lochabar** [comment]
I am able to uncheck "Is Main Mugshot" and no mugshot appears on the first page of the character viewer sheet. However the "Other Portraits" section is not shown in the character viewer at all.

**Comment by DelnarErsike** [comment]
Fixed that issue in the latest commit, should show up in the next nightly.
