### ISSUE TITLE
Mission legal sourcebooks in SR Missions 1.4 Rules

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2090]
### Environment
Chummer Version: 5.195.77
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
The list of sourcebooks permitted by Missions in the SRM Chicago FAQ v1.4 matches the 
list shown in the "SR Missions 1.4 Rules" of the "Custom Data Directories".
![sourcebooks](https://user-images.githubusercontent.com/17562417/33187072-050f4100-d087-11e7-9864-c7a982846119.png)

### Actual behaviour
1) Permitted books in the FAQ are not listed
![books 1](https://user-images.githubusercontent.com/17562417/33187085-2235e5cc-d087-11e7-9d4e-cb43ffb61db3.png)

Aetherology (actually it is not listed in the full list of sourcebooks)
Coyotes (actually it is not listed in the full list of sourcebooks)
Shadows in Focus: Sioux Nation

2) Not permitted in the FAQ are listed
![books 2](https://user-images.githubusercontent.com/17562417/33187092-2c0640ba-d087-11e7-9d3a-ad6079830884.png)

Shadows in Focus: Sioux Nation: Counting Coup

Note: As I inderstand it Forbidden Arcana and The Complete Trog are permitted for 
Missions but they are not currently in the FAQ (maybe v1.5 ?).

**Comment by DelnarErsike** [comment]
Disabled Counting Coup in the custom ruleset. As for Aetherology, Coyotes, and Sioux Nation, none of those soucebooks actually have data included for use in Chummer5a to begin with, though maybe Aetherology might change if someone is willing to do data entry for all of the critters in that book.
