### ISSUE TITLE
Select a Manipulation Spell and Limited Programm-Crash  and wrong calculation from DV if a Spell Limited

### ISSUE THREAD

**Issue by WaykoAstragon** [chummer5a/chummer5a#2093]
### Environment
Chummer Version: 5.195.80
Environment:  Windows 7 Prof SP-1
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I can choose a Manipulation Spell (e.g. Mob Control) and check the option "Limited Spell".

### Actual behaviour
Programmcrash  (see picture) if i choose "Mob Control" and next "Limited Spell"
If i check first "Limited Spell" and then "Mob Control" everything is ok (But the DV is not correct calculatet it use the DV from the last selected Spell: If i select first "Limited Spell, next i select Detox (F-8) and then i choose e.g. "Mob Control" the DV is still F-8)

### Steps to reproduce the behaviour
![crash](https://user-images.githubusercontent.com/33957866/33210658-5f796ac8-d11b-11e7-9e8e-bf283afd3a14.png)

**Comment by chummer5a** [comment]
This is fixed in current nightly builds.
