### ISSUE TITLE
Enhancement: Allow Saving and Importing of Contacts from Dedicated Savefiles

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2096]
When you have multiple characters who have played in Chicago missions, they may have several of the Mission Season 5 contacts in common. Any changes to the contact information may have to be made in several character files.

Chummer allows for the creation of a New Critter. Would it be possible to provide a similar functionality to create a New Contact?
- Most of a contacts attributes (Notes, Age category, Habits, Connection, etc.) would then be stored  separately from a character file. Loyalty being an exception that would have to stay on a per-character basis.
- There would need to be an option to link a contact file to a character.
- Unique characters would still be added using the existing contact setup in Chummer.

**Comment by DelnarErsike** [comment]
Already present. There is a "link" button in each contact control that allows you to link them to a character file. It could be more obvious though, so I've modified your issue's title to represent such an enhancement.

**Comment by Lochabar** [comment]
Attaching a full character file was not what I had in mind; you have to go through, at least, the initial character creation process and add a lot more detail than required for a contact. And the data does not print in the contact list.

I was hoping for a simple file containing only the contact information, that ideally would print as if the contact had been detailed in the contact list itself.

**Comment by chummer5a** [comment]
Hrm. We could just add a file importer to point to an XML file with the necessary entries without too much problem, or generate some kind of UI frontend for it that'd look similar to the roster or something.
