### ISSUE TITLE
Trying to add Prime Datahaven Membership Quality crashes Chummer & CrashHandler

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2097]
### Environment
Chummer Version: 5.195.80
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Be able to add the Prime Datahaven Membership Quality to a character.

### Actual behaviour
CrashHandler crash
![crashhandler 1](https://user-images.githubusercontent.com/17562417/33224624-722052c0-d163-11e7-9261-19c4fea53002.png)
![crashhandler 2](https://user-images.githubusercontent.com/17562417/33224625-724586b2-d163-11e7-8155-04078ab2baf7.png)

Chummer crash
![chummer 1](https://user-images.githubusercontent.com/17562417/33224627-7746c3f6-d163-11e7-9ee1-466cc4b1483c.png)
![chummer 2](https://user-images.githubusercontent.com/17562417/33224628-77665acc-d163-11e7-93dd-2d19dc710b11.png)

### Steps to reproduce the behaviour
Try to add the quality to a character.

### Link to affected character file
[Character.zip](https://github.com/chummer5a/chummer5a/files/1502589/Character.zip)

**Comment by DelnarErsike** [comment]
Should be fixed in v5.195.81.
