### ISSUE TITLE
Existing translations not used in GUI and/or sheets

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2098]
### Environment
Chummer Version: 5.195.78
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
My Chummer5a is set to language German.

The following data is shown in German in the GUI, but in English in the print sheets:
- Value (right, left) for "Handedness"; in print xml found as "character/primaryarm"

The following texts in the GUI are shown in English even if a translated value exists in the German language file (de-de.xml). Of course, I'm not sure if the translations keys I found are the the correct ones for that GUI places:
- "Group" checkbox in contact informations: Label_Contact_Group
- Tab titles "Contacts and "Enemies" on the first tab: Label_Options_Contacts, Label_Options_Enemies
- Weapon mod slot names (like "Top") on the weapons tab: String_MountTop, String_MountUnder, String_MountBarrel, String_MountSide, String_MountInternal, String_MountStock

There might be more, but thats what I "collected" so far.

**Comment by DelnarErsike** [comment]
All of the mentioned localization issues will be fixed in the next nightly. If you find any more, please create a new issue.
