### ISSUE TITLE
Omae crashes chummer

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#210]
Omae crashes chummer when you follow this steps (unmodified 0.5.166 release)
1. select a thing to search for (enemy, critter, contact,etc)
2. select a sort order
3. hit search
4. change sort order
5. hit search
-> crash & windoze presents its "Chummer doesn't function anymore..."
[WER100B.tmp.appcompat.txt](http://pastebin.com/ZFwFiVdF)
also got dump data if needed (WER102C.tmp.mdmp, WERF53F.tmp.WERInternalMetadata.xml)
chummerlog.txt contains the chummer version number and nothing more...

for me as a user its a minor problem and one that can be easily avoided
just stating it for the sake of completeness

**Comment by chummer5a** [comment]
It's an issue in 139 Chummer as well; I suspect there's something gone wrong on Omae's end.

**Comment by chummer5a** [comment]
Issue was external, appears to be resolved now.
