### ISSUE TITLE
Enhancement: Remove or disable meta type given qualities that do no longer apply

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2101]
### Environment
Chummer Version: 5.195.78
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Either allow to remove a meta type given quality. Or add some form of "disabled" information to it.
I don't mind if it is still visible in the GUI but it would be nice if it is no longer on the print sheets.

### Actual behaviour
If a character with a natural vision enhancement (e.g. Elf with low light sight) gets cybereyes, its natural vision enhancement is still listed and printed as a positive quality.
According to the core rulebook, such qualities are list if the natural eyes are removed/replaced.

**Comment by chummer5a** [comment]
Linked to #2533
