### ISSUE TITLE
Chummer 5.195.86 fails to open the print preview window.

### ISSUE THREAD

**Issue by modsec** [chummer5a/chummer5a#2107]
### Environment
Chummer Version: 5.195.86
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When hitting the Print button the print window should appear and display a preview of your file in pdf form.

### Actual behaviour
When you hit the print button the print window starts to appear and then the program crashes it without the preview ever being shown. 

### Steps to reproduce the behaviour
Launch the attached file. Hit the print button

### Link to affected character file
[RaowRaow.zip](https://github.com/chummer5a/chummer5a/files/1508573/RaowRaow.zip)

**Comment by chummer5a** [comment]
[RaowRaow.zip](https://github.com/chummer5a/chummer5a/files/1509882/RaowRaow.zip)
There was a problem with your file (-1 Karma in LOG somehow), and a problem with the print viewer. Should be sorted now, print issue will be fixed in the next build.

**Comment by modsec** [comment]
Thanks pal
