### ISSUE TITLE
Chummer displays 'Chummer.ListItem' when trying to add weapons

### ISSUE THREAD

**Issue by MerGatto** [chummer5a/chummer5a#2108]
### Environment
Chummer Version: 5.195.86
Environment: Windows 10, German Environment
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding Weapons should work as intended

### Actual behaviour
When trying to add a new weapon for any character this pops up 
![image](https://user-images.githubusercontent.com/2557018/33340668-0a4f057a-d47d-11e7-8554-16ab8f036b2e.png)

Additionally it is not possible to add some weapons (eg Grenade Launchers) and Chummer will crash upon selecting them
![image](https://user-images.githubusercontent.com/2557018/33340724-34bf03dc-d47d-11e7-864e-cad6e323f3ae.png)

### Steps to reproduce the behaviour
Create a new character and open the 'Add Weapon' Dialog

### Link to affected character file
Happens with all characters for me

**Comment by DelnarErsike** [comment]
I cannot reproduce this. My suspicion is that you have a malformed custom weapon item or change. What custom files are you using?

**Comment by MerGatto** [comment]
I am not using any custom items at all (at least none that i am aware of). A friend of mine who notified me about this bug is having the very same problem.

I will try to reproduce the issue again with a fresh chummer installation when I'm back at home..

**Comment by MerGatto** [comment]
Reinstalling chummer seems to have fixed the issue, I also noticed that i had 2 seperate entries for the german language in the option menu (Deutsch (DE) and Deutsch (de-DE)). After the reinstall one of the 2 options was gone. This probably messed up #2109 as well
