### ISSUE TITLE
Feature Request: Custom Qualities?

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#211]
Would a "Custom Quality", not unlike the "Custom Item" in the gear section, be easily implementable? Idealy, this would be a freely nameable quality, with adjustable point values.

Some groups like to use their own qualities, and this could also be used as a placeholder for something not yet implemented.

**Comment by chummer5a** [comment]
Ehh. Qualities.xml doesn't currently have a handler for variable costs. It wouldn't be HARD to implement, but realistically it would be simpler for end-users to create a custom quality via xml.
