### ISSUE TITLE
Contacts UI: One annoyance, two enhancments

### ISSUE THREAD

**Issue by StarWeaver** [chummer5a/chummer5a#2112]
### Environment
Chummer Version: 5.195.88
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
- [x] Each column of the multi-column contact view to act like a separate container for layout.

### Actual behaviour
Rows only fold if all contacts in row are folded: https://i.imgur.com/uSPmpcN.png

### Steps to reproduce the behaviour
Make chummer screen wide :grin: 

### Desired Enhancments

- [x] Fold/unfold all button.
- [x] Some method to reorder contacts in list.

I don't think the current contacts list requests touch any of these and they're not that related.

**Comment by chummer5a** [comment]
I'd have to change the direction of the flow for the controls to stack vertically like that, so the contacts would go top to bottom then left to right instead of LR > TB as it does not. Folding and reordering should be simple enough.

**Comment by chummer5a** [comment]
You actually can drag the contact controls around, just hold your left mouse button down in any blank area.

**Comment by chummer5a** [comment]
Added a button to switch between left/right and top/down ordering.
