### ISSUE TITLE
Enhancment: Mousewheel scroll in tab bar(s)

### ISSUE THREAD

**Issue by StarWeaver** [chummer5a/chummer5a#2115]
### Environment
Chummer Version: 5.195.88
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Desired behaviour
Mousewheel in this area should scroll the tab bar: https://i.imgur.com/zrHLHFs.png

### Actual behaviour
I have to click the tiny little arrows

### Also
The roster bar and right-side-extra-stuff bar should probably also have this feature, but they haven't actually bothered me yet.

**Comment by chummer5a** [comment]
Tricky to implement properly, I'm not sure it's easily-accessible. Easier would be setting it to multiline, but I don't super like how that looks.
![image](https://user-images.githubusercontent.com/11448441/33377919-42285db2-d567-11e7-8ab5-955b6928ea5b.png)

**Comment by StarWeaver** [comment]
I don't SUPER like how it looks either but I like it better than having to
scroll, Maybe option?

 Only other thing I can think of is an option to abbreviate all the names
to three or four letters
