### ISSUE TITLE
PDF of character sheet is wrongly formatted

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2121]
### Environment
Chummer Version: 5.195.88 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
The printed character sheet reflects the display in the character viewer.

### Actual behaviour
In the attached PDF of a "Shadowrun 5" character sheet
- page 3 is blank
- page 4 contains just the Physical and Stun track (instead of them being next to Qualities)

And ever since the Ranges box was added to the Weapons list, the bottom of the box runs into the box around the weapons list (page 6).
 
### Steps to reproduce the behaviour
This does not always happen - it seems to be dependent on the (amount of) data being printed. The sheet prints correctly for other characters. In addition the "Shadowrun 5 (Core)" sheet for this character prints correctly.

### Link to affected character file
[Scarab.pdf](https://github.com/chummer5a/chummer5a/files/1519492/Scarab.pdf)

**Comment by Lochabar** [comment]
The format problems still exists in 5.195.97

**Comment by DelnarErsike** [comment]
I cannot replicate it with characters who have such large notes sections for their qualities that it would cause a page break.

**Comment by Lochabar** [comment]
This is the character currently having the problem
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1535516/Character.file.zip)

And this is page setup
![page setup](https://user-images.githubusercontent.com/17562417/33666954-7026a95e-da93-11e7-862b-22fafe9f74f2.png)

Is it possible that the Page Size being "Letter" is the cause of the formatting problem?
I'm assuming you have "A4". If I switch to A4 the extra pages go away (but I fall fowl of #2142 so I can't be certain).

**Comment by DelnarErsike** [comment]
Yup, cannot replicate in the dev build.

Here is the PDF when printed via Foxit Reader's Print-to-PDF function with a paper size of Letter and 0 margins:
[Scarab.pdf](https://github.com/chummer5a/chummer5a/files/1535588/Scarab.pdf)

And here is the PDF when saved using Chummer5's Save-to-PDF function that will naturally produce a paper size of A4 with CSS-defined margins:
[Scarab_Saved.pdf](https://github.com/chummer5a/chummer5a/files/1535591/Scarab_Saved.pdf)

Although the qualities section and the condition monitor are on different pages in the second example, they are still following their programming of avoiding page breaks wherever possible. There are also no extra, blank pages inserted on either one.

My guess is that the problem as to do with the configuration of your system and not Chummer5 itself. I am closing this issue, as I #2142 is already taking on that role.

**Comment by Lochabar** [comment]
Restarting Windows solved the Print Preview problem of #2142 however the PDF blank page and condition monitor on a separate page remain.
