### ISSUE TITLE
Stacked Foci use SR4 books

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2122]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5a
Environment: (Operating system here. If it persists over multiple OS's list them all) Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1) unknown

### Expected behaviour
toggled all sourcebooks on before creating character
Trying to save character created
### Actual behaviour
Can't save due to unknown book used in creation (SM)

### Steps to reproduce the behaviour
created sample character with same results

### Link to affected character file
(Enter text here)
tried linking file but I don't have zip, I use rar

**Comment by chummer5a** [comment]
Did you possibly create a stacked focus?

**Comment by HarleeKnight** [comment]
Actually yeah. I hadn't done one since 3rd but it came up as an option, so I figured, "Hmm, sounds like a good idea." Guess I was wrong.

**Comment by chummer5a** [comment]
They're a relic from 4E that hasn't been brought over to 5E officially yet, I keep neglecting to pull the relevant code out. Simplest fix for your case would be to open the file and find any <source>SM</source> entries and replace it with <source>SG</source> or <source>SR5</source>, then it'll load properly.
