### ISSUE TITLE
Quality "illness" does not have levels

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#2124]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.90
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When selecting quality "illness" from Bullets&bandages, may choose level of this level (5/10/15 karma)

### Actual behaviour
there is only 1 level (-5 karma) of this quality

### Steps to reproduce the behaviour
look on the negative quality list

### Link to affected character file
there is -10 karma because character already in career mode
![illness](https://user-images.githubusercontent.com/33343265/33489043-c9403588-d6c3-11e7-9989-70e32f63758a.PNG)
![default](https://user-images.githubusercontent.com/33343265/33489112-f9b3c78e-d6c3-11e7-9c51-89e456a7abb9.PNG)
also, here illness table from Bullets&Bandages
![asd](https://user-images.githubusercontent.com/33343265/33489191-3720354e-d6c4-11e7-8b05-b688aa44ff6e.PNG)

**Comment by chummer5a** [comment]
Currently you have to add a second instance of the quality. When you do that, it'll collapse into the existing one.

**Comment by DelnarErsike** [comment]
I cannot replicate this in the dev build. When Illness is added and then selected in the quality menu, the quality level numerical up-down is enabled and I can add or remove levels from it.

**Comment by chummer5a** [comment]
Hrm, odd. Wasn't working properly for me but does now. @ARgits can you please test with the latest nightly build from http://get.chummer.net or the updater and see if it works properly for you now?

**Comment by ARgits** [comment]
tested on 5.195.94. all works, thnx.
