### ISSUE TITLE
Adding Area Thought Recognition (Limited) crashes Chummer

### ISSUE THREAD

**Issue by Mliekseter** [chummer5a/chummer5a#2127]
### Environment
Chummer Version: 5.195.91
Environment: Windows 10
Runtime: Don't know

### Expected behaviour
Selecting Area Thought Recognition and checking the 'Limited Spell' checkbox should allow the spell to be added as a Limited Spell

### Actual behaviour
Attempting to do so causes Chummer to crash. The Chummer crash dialogue does not appear, instead I get the generic windows 'Chummer has stopped working' dialog

### Steps to reproduce the behaviour
Open Chummer
Create a new character with a Magic Rating
Go to the Spells & Spirits tab
Click 'Add Spell'
Open the 'Detection' dropdown
Select the 'Area Thought Recognition' spell
Check the 'Limited Spell' checkbox

I have found that you can bypass the problem by selecting another spell first, checking the Limited Spell checkbox for that spell, and then selecting Area Thought Recognition instead. 
I have not checked every spell, but thus far Area Thought Recognition is the only spell where this seems to happen

**Comment by chummer5a** [comment]
Can't replicate it in the current nightly builds.

**Comment by Zitchas** [comment]
I cannot replicate it with 5.195.92
