### ISSUE TITLE
Not Enough Weapons

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#2128]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.94
Environment: Win 10
Runtime: 

### Expected behaviour
All available weapons in the weapons add-on list for vehicle weapon mounts.

### Actual behaviour
The list is not complete. There are several weapons missing that should be on there (example: Mitsubishi MRL). There a few that should not be on there (example: Gun Cane).

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Availability filter, most likely? The MRL is 20F, you wouldn't be able to see it in create mode unless you untick the option to hide items over your availability limit. As far as the gun cane goes, it's stupid but per RAW most weapon mounts can mount exotic ranged weapons.

**Comment by captroberts** [comment]
And that is the reason I love this program. Thank you for the info.
