### ISSUE TITLE
Existing Characters missing data

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#2131]
### Environment
Chummer Version: .94
Environment: w7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Click on skills tab, see skills/knowledges and be able to edit/adjust values by spending karma
Click on Attributes tab, see character stats and be able to edit/adjust values by spending karma
Click on Karma/Nuyen, see previously acquired character progression via gains/expenses of karma/nuyen
Click on Calendar, see previously entered information

### Actual behaviour
Click on skills tab.  Fields for skills/knowledges blank
Click on Attributes tab, Field for Attributes is blank 
Click on Karma/Nuyen, all previously saved entries deleted
Click on Calendar, all previously saved entries deleted

### Steps to reproduce the behaviour
Open career mode character, click on indicated tabs

**Comment by chummer5a** [comment]
Sounds like the character failed to load but you somehow got past the error message. Can you upload a copy of the affected character(s)? Should be able to compress them to a zip and upload here.
