### ISSUE TITLE
MBW Social Limit

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2135]
### Environment
Chummer Version: 5.195.95
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Move-By-Wire should lower social limit by rating. (p 84 Chrome Flesh)

### Actual behaviour
Social Limit is not lowered. (Except by the essence going down)

### Steps to reproduce the behaviour
Create any character. Get MBW. Check social limit.

**Comment by chummer5a** [comment]
Somewhat unrelated, but we probably also need an 'Active' checkbox to selectively enable and disable improvements like MBW.
