### ISSUE TITLE
Decimals still display on Nuyen amounts when setting controls set to zero

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2136]
### Environment
Chummer Version: 5.195.96 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
When new settings to control number of Nuyen decimals to display are set to zero no decimals are displayed.

### Actual behaviour
Decimals are still shown.
![nuyen display](https://user-images.githubusercontent.com/17562417/33585328-95d8217a-d95b-11e7-89df-3f5c3c31a0ba.png)

### Steps to reproduce the behaviour
Go to options. Set the number of decimals to display to zero (two fields). Restart Chummer. Check the display of Nuyen values in Other Info tab, in status at the bottom of the page, in Nuyen history, in gear amounts.

**Comment by DelnarErsike** [comment]
Unable to replicate this in the dev build. Both increasing and decreasing decimal places in the options menu properly changes the amount of displayed decimal places in all Create mode and Career mode characters I've tried, as does setting them to 0.

Are you sure your options were applied? If you've got 2 decimal places being displayed, then when you go into the options menu, the numerical up-downs should be (re)set to 2 (we save the format itself and not the numbers, so whenever you open up the options menu, it will parse the format string and set the numerical up-down values accordingly).

**Comment by Lochabar** [comment]
I saved the options in an earlier release - the values shown are the settings as I opened the options. To make sure I set them both to 1 and saved the options, restarted Chummer; still showing two decimals. Then set them both back to zero, saved the options, restarted Chummer; still showing two decimals.

**Comment by DelnarErsike** [comment]
Does saving any/all other options still work for you? If not, then it seems like it's an issue with options in general not getting saved, not an issue with the decimal place options specifically.

**Comment by Lochabar** [comment]
I removed the saved settings file, restarted Chummer and reapplied my options. The nuyen display now works.

**Comment by DelnarErsike** [comment]
Hmm, I can't seem to replicate the circumstances where Chummer would not properly parse and/or save the settings file. I'm closing this issue for now.
