### ISSUE TITLE
Cannot open sourcebook for a complex form

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2137]
### Environment
Chummer Version: 5.195.96 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Click on the sourcebook reference for a complex form opens the PDF at the specified page.

### Actual behaviour
Nothing happens.
![complex forms](https://user-images.githubusercontent.com/17562417/33587880-0c5aae4c-d968-11e7-988d-93e234914d84.png)

### Steps to reproduce the behaviour
Open a Technomancer character with Complex Forms. Click on the sourcebook page.

**Comment by chummer5a** [comment]
Fixed in 29c0ac326c4c45d50ffa3af292f63227cbb4fd8c
