### ISSUE TITLE
Optional Rule "Allow Skills to be re-Grouped if all Ratings are the same" issue on newly Created characters

### ISSUE THREAD

**Issue by W1ld3b34st** [chummer5a/chummer5a#214]
On a newly Created character, you will not be able to raise a skill group which was set to be the same level during character creation. This is common to happen during Priority Buy to provide a use case example. You can however buy raise (re-create) the skill group once you spend Karma on any single skill.

Reproduction:
Create a new character, pick one skill group and set all skills at the same level -> Save as Created -> Confirm Optional Rules for "Allow Skills to be re-Grouped if all Ratings are the same" is checked; reload character if necessary -> The skill group which should be able to be increased will remain greyed out -> Increase any skill (not a group member skill) with Karma -> The skill groups will now be able to be bought with Karma.

**Comment by chummer5a** [comment]
Resolved in 5.167. Not super happy with it, but it's functional enough.
