### ISSUE TITLE
Incorrct cost to raise edge.

### ISSUE THREAD

**Issue by legionof1** [chummer5a/chummer5a#2140]
### Environment
Chummer Version: 5.195.96
Environment: Windows
Runtime: 4.7

### Expected behavior
In career mode raising edge to 3 should cost 15 karma.

### Actual behavior
Cost to raise is 10 on affected characters

### Steps to reproduce the behavior
Have a human in career mode.
Mouse over edge to view cost.

### Link to affected character file
[juicer.zip](https://github.com/chummer5a/chummer5a/files/1532352/juicer.zip)

### Additional comments
This error appears to affect all human characters on my install, at this time i have not had time to examine if only humans are affected, nor if it extends outside career mode.

**Comment by DelnarErsike** [comment]
Unable to replicate this on the dev build. For this character and all other characters I have tested (human or nonhuman, create mode or career mode), the tooltip shows the correct amount, the attribute increase confirmation dialog shows the correct amount, and the correct amount of karma is deducted when the attribute is increased.

Are you using the default values for all karma costs, and/or are you using the house rule that ignores metatype minima when calculating the karma cost of increasing attributes?

**Comment by legionof1** [comment]
ah thank you. It seems it got enabled at some point. How when i did nothing twixt one upgrade and the next, i haven't a foggy. But works as intended i guess. Thanks.
