### ISSUE TITLE
Life Module and SINner quality behvaiour

### ISSUE THREAD

**Issue by DarbyDay** [chummer5a/chummer5a#2141]
### Environment
Chummer Version: 5.195.97
Environment: Windows 10 Pro
Runtime: NET 4.5.1

### Expected behaviour
Chummer allows the addition of the Corporate: Security Guard life module after taking a Nationality life module that gives the SINner quality.

### Actual behaviour
[Unable to add life module due to already having the SINner quality from a previous life module](https://user-images.githubusercontent.com/34293274/33643237-ef4910ac-da91-11e7-82b0-620bf19716ee.JPG)

### Steps to reproduce the behaviour
Create character of any race using life module system, choose a nationality that gives the SINner quality, attempt to take Corporate: Security Guard, or likely any life module that gives SINner.

### Link to affected character file
[test.zip](https://github.com/chummer5a/chummer5a/files/1533798/test.zip)

**Comment by OLStefan** [comment]
Is part of #2000.
