### ISSUE TITLE
Use of Page Setup changes Print Preview (and subsequent print)

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2142]
### Environment
Chummer Version: 5.195.97 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
When using Page Setup (to modify header/footer) from Print Preview of a Character Viewer sheet the format of the page content stays the same.

### Actual behaviour
Before using Page Setup the preview shows
![print preview before page setup](https://user-images.githubusercontent.com/17562417/33666085-d6f6702c-da90-11e7-9b2b-a8ef0328bc3e.png)

After using Page Setup WITHOUT actually making any changes the preview becomes
![print preview after page setup](https://user-images.githubusercontent.com/17562417/33666125-fa263e9c-da90-11e7-9ab3-6be4f68df1a4.png)

It's great that the skills section (perhaps the most used section) is once more back on the first page. Unfortunately the sections now cover the entire width of the page and cannot be sent to a printer without the edges being cut off (unless you start playing tricks with the printer).

This used to work until print changes were made to print the main mugshot on the first page that also pushed the skills section to the second page.

### Steps to reproduce the behaviour
From Character View use the down arrow on the print button and click Print Preview. In the preview click Page Setup button, click ok (no need to make changes). On return to the preview the format has changed.

**Comment by DelnarErsike** [comment]
Unable to reproduce. However, if your page setup config is the same as the one you mentioned in #2121, then the problem is likely to do with your margins. When I enter Page Setup, all of my margin fields are populated with non-zero quantities, and so those margins remain when I save changes.

**Comment by Lochabar** [comment]
Having restarted Windows the margins now have non-zero values. When I modify the Header/Footer values they preview displays correctly. However the PDF format problems (blank page and condition monitors on separate page) reported in #2121 remain.
