### ISSUE TITLE
Chummer incorrectly calculates maximum spells known at character generation

### ISSUE THREAD

**Issue by thehuntedsnark** [chummer5a/chummer5a#2146]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: .NET 4.5.1)

### Expected behaviour
The number of spells that a mage (or aspected mage) knows at character creation is limited to MAG x 2 in each category (spells, ritual spells and alchemical preparations).

### Actual behaviour
Chummer 5 treats the maximum number of spells, preparations and rituals (MAG x 2) as reached when you have that many Spells, regardless of how many Rituals or Alchemical Preparations you have.
If you have the maximum allowed number of spells then you are unable to add further rituals or preparations up to the limit. Reducing the spell number by 1 enables you to add rituals and preparations freely up to the limit before you add the final spell.

### Steps to reproduce the behaviour
1. Create a magician at priority A for 6 Magic and 10 spells
2. Take Dedicated Spellsinger for free bonus spells equal to your spellcasting skill
3. Choose 12 spells
4. Observe Chummer disallowing any further rituals or alchemical preparations

### Link to affected character file
[MAX SPELL TEST.pdf](https://github.com/chummer5a/chummer5a/files/1542669/MAX.SPELL.TEST.pdf)

**Comment by DelnarErsike** [comment]
The issue with max rituals and max alchemical preparations getting mixed together with max spells has already been addressed and fixed in the latest nightly. The change simply has not been pushed to a stable version yet.
