### ISSUE TITLE
Free contacts

### ISSUE THREAD

**Issue by joha4270** [chummer5a/chummer5a#215]
It is currently impossible to create free contracts as code for doing so was located in the group window, a feature that was removed in the conversion from 4th to 5th edition

**Comment by chummer5a** [comment]
Technically speaking the form is still there, it's just the link to it that's missing. Not a problem to add back in. What other features need to be added back in?  Chips are the only thing I know of, since membership and such have been removed from groups.

**Comment by joha4270** [comment]
Chips are the only thing i'm aware of too. Well chips and group contracts but i'm working on the later. I felt the 4th ed gui was a bit massive for that so i was planning (well mostly done, **only** the backend calculations missing). For just that feature i tought a checkbox was better as an entire window for a checkbox was excessive. I still feel it is for 1 counter and 2 checkboxes but on the other hand that is quite a bit more space on the usercontrol compared to a single checkbox


Can it be made so that the form for free and chips comes when somebody hovers over the usercontrol? Sure it can be made, more asking if it is a totaly stupid unintuitive idea or mega cool fantastic.

**Comment by chummer5a** [comment]
Hrm. There's no technical barrier against it, it's a simple onhover with
some modifications to the instancing for contactcontrol. I tend to be more
a fan of pull-out drawers, but I'm open to suggestions. I'd rather that
Connection and Loyalty be headers as well to save some space, but it's
hardly critical.

**Comment by joha4270** [comment]
I'm not exactly sure what a pull out drawer is at present moment but i think i have an idea.  (Something you pull out?)

If i implement said pull out drawer it should be relatively trivial to move loyality and connection too. Want any of the link sheet, notes or the delete button moved?

Also, can you assign me this, made man and group contracts? I'm already working on group contract but made man is related and this is part of the same UI change required

**Comment by chummer5a** [comment]
Drawers are like when you group a row of data in Excel and minimise the
group. Expanding the group pushes the rows below that one down. So you'd go
from one line that has just the name, connection, loyalty, character link,
etc. and expand it out to reveal your notes, checkboxes for free contacts,
and so on and so forth. I'm not much for design through, so I'm happy with
whatever works.

**Comment by joha4270** [comment]
Something on hover is much easier in that case, as contact location.y is
only based on number of contacts. Might just lose my sanity if i have to
check every if it is expanded and figure out how to trigger an update.
Unless you cover the one under but that is a confusion nightmare and
something that comes out when you hover and goes away afterwards is much
clearer (i think)

I'm not a designer either in case you didn't notice :P

2015-05-20 17:36 GMT+02:00 Chummer 5 Is Alive <notifications@github.com>:
