### ISSUE TITLE
Crash: Adding internal smartgunsystem

### ISSUE THREAD

**Issue by StillesChaos** [chummer5a/chummer5a#2152]
### Environment
Chummer Version: 5.195.100 (Nightly) & 5.195.101
Environment: Windows 7 x64
Runtime: NET 4.5.1

### Expected behaviour
Adding of internal smartgunsystem (Normal, as well as 2050-Version). Weapons with internal Smartguns work fine, as well as the addition of external smartgun-systems.

### Actual behaviour
The program freezes and becomes unresponsive, forcing me to close and losing every progress. No Crashreport possible. Crashfiles on desktop contain no information.

### Steps to reproduce the behaviour
1.) Add gun
2.) Add Smartgunsystem (internal)

**Comment by DelnarErsike** [comment]
Unable to replicate on dev builds. Could you provide a savefile and/or more detailed instructions on what guns cause the issue?

**Comment by StillesChaos** [comment]
Alright, I uploaded the file here, since github wouldn't let me:
https://workupload.com/file/m9aN9fz

The weapon doesn't matter and other accesory doesn't seem to be affected after some thorough testing. It also happens on every character wether it's new or saved previously doesn't matter.
