### ISSUE TITLE
Some Nuyen values still displaying with decimals

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2157]
### Environment
Chummer Version: 5.196.0 and recent nightlies
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
All displayed Nuyen values reflect the display limit (currently zero).

### Actual behaviour
Credstick value still shows ".00"
![credstick](https://user-images.githubusercontent.com/17562417/33855340-8c121694-debc-11e7-97ef-3cfcacfe4388.png)

The gear definition in the character file does not have decimals
![gear](https://user-images.githubusercontent.com/17562417/33855381-ab619ee8-debc-11e7-95b7-e7e08e0a2034.png)

Don't know if it relevant but the credstick is the child of a Location.

**Comment by DelnarErsike** [comment]
That's actually for quantities, which have different formatting than costs. If you are using gear that is not in the Currency category, it's always minimum 0 places, maximum 2 places. If you are using gear that is in the Currency category, e.g. UCAS dollars, then it's minimum 2 places, maximum 2 places. Nuyen as a gear item is in the Currency category, so it follows those rules.

**Comment by Lochabar** [comment]
So how should the amount of Nuyen on a Credstick be tracked?
I played with adding a Location of "Credsticks" and could add Currency to it. However Nuyen is not listed as a currency so using a Location is not workable.

**Comment by chummer5a** [comment]
Currency needs to be added to a parent node such as a credstick; locations aren't treated as a parent for that sort of thing, so you'd have to add a Custom Item for your bank account or somesuch.

**Comment by Lochabar** [comment]
That's what I did and it leaves the Nuyen showing decimals (see above).
