### ISSUE TITLE
Electronics Accessories are showing as full Commlinks

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2158]
### Environment
Chummer Version: 5.196.0 and recent nightlies
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Electronics Accessories such as Subvocal Mic and Trodes are displayed as regular gear, i.e. they do not have a Matrix Condition Monitor and cannot be checked as an Active Commlink.

### Actual behaviour
Electronics Accessories are displayed as if they were Commlinks. Such as Subvocal Mic:
![subvocal mic](https://user-images.githubusercontent.com/17562417/33857790-1e29f5ee-dec5-11e7-9c03-8825cbe098ef.png)
And why would they need to be checked as an active commlink?

The only exception is when only showing only commlinks
![commlinks](https://user-images.githubusercontent.com/17562417/33857891-94c6e608-dec5-11e7-8b61-ceafc0463eeb.png)

Electronics Accessories are not Commlinks so why are they displayed as such?
And why are they listed in the Commlinks character sheet?

**Comment by DelnarErsike** [comment]
Fuck it, I'm nuking the Commlink system and merging it fully with Gear objects.
