### ISSUE TITLE
[Bug] when i try to open my naga mage chummer crashes 

### ISSUE THREAD

**Issue by DoctorM10** [chummer5a/chummer5a#2160]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.196.0)
Environment: (windows 10)
Runtime: (.NET 4.5.1) i think but i don't know for certain 

### Expected behaviour
(my character file should open in chummer and not crash the program. It opened with no trouble in version 5.195.0 and any other previous version of Chummer 5A i used)

### Actual behaviour
(the loading pinwheel spins for a few second followed by a window with a green bar that move horizontally from side to side that will quickly morph into a new window saying that chummer has stopped working with a button to close the program)

### Steps to reproduce the behaviour
(open the file in Chummer 5A version 5.196.0)

### Link to affected character file
(https://1drv.ms/u/s!AsY6JuCbE7QCgP8bgcKi0PTWsOJcYQ) if you want the file sent in a different way that onedrive tell me and i will see what i can do

Sorry i cant be more helpful with my information

**Comment by DoctorM10** [comment]
the Creator gave me the Fix over Reddit it seems that somehow one of my skills was recorded twice with 2 different numbers.

**Comment by chummer5a** [comment]
Just gonna keep this open for a while so I can fix this properly.
