### ISSUE TITLE
[Bug] Chummer crashes when adding drones or vehicles in career mode

### ISSUE THREAD

**Issue by DelinquentPanda** [chummer5a/chummer5a#2162]
Tried this a few separate times with different vehicles, including with a fresh character

### Environment
Chummer Version: Nightly-v5.196.1
Environment: Windows 7 64bit
Runtime:  .NET 4.6.1

### Expected behaviour
Trading in that hard earned nuyen for a sweet new ride

### Actual behaviour
upon hitting the okay button in the add vehicle pop up the program immediately crashes

### Steps to reproduce the behaviour
trying to add any drone/vehicle in career mode

**Comment by chummer5a** [comment]
Can't replicate it in the latest build, 5.196.2

**Comment by DelinquentPanda** [comment]
Damn that was fast lol. Thanks!

**Comment by chummer5a** [comment]
I tend to force new builds quite quickly early after a new release, helps keep away opinions about Chummer being terrible :P
