### ISSUE TITLE
Incorrect Armor Stacking Values for High-Fashion Armor

### ISSUE THREAD

**Issue by forfthemad** [chummer5a/chummer5a#2164]
### Environment
Chummer Version: 5.196.0
Environment: Windows 10 Home
Runtime: Probably .NET 4.5.1

### Expected behavior
Stacking High-Fashion Armor calculates the correct values (ex: Sleeping Tiger [13] + Synergist Longcoat [3] = 16 Total Armor)

### Actual behavior
Stacking High-Fashion Armor calculates the incorrect values (ex: Sleeping Tiger [13] + Synergist Business Line Longcoat [10] = 23 Total Armor)

- This seems to affect Vashon Island and Zoe lines.

### Steps to reproduce the behaviour
Purchase the above sets of armor.

*The Mortimer of London line seems unaffected.

**Comment by chummer5a** [comment]
Fixed in the current nightly builds. http://get.chummer.net
