### ISSUE TITLE
Roster sort order

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2168]
### Environment
Chummer Version: 5.196.2
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Be able to use the sort list option of the roster

### Actual behaviour
1) The "Recent Characters" list of the Roster is not shown in alphabetical order.
2) When I tried to use "Sort this list Alphabetically" from the rt-click menu of a character, it is greyed out and not usable
![roster](https://user-images.githubusercontent.com/17562417/33902922-774ff0fc-df6e-11e7-9e79-506496d6acc3.png)

This is the also the case for the "Favorite Characters" list.

**Comment by chummer5a** [comment]
Mm, I haven't implemented it permanently yet. Getting it to sort the treenodes themselves is easy which is why that button does right now, but it doesn't persist through restarts.
