### ISSUE TITLE
Commlink-Dongles should add Matrix Attributes

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#2169]
Right now Commlink-Dongles don't add the Attribute to the Commlink it is added to.

**Comment by DelnarErsike** [comment]
They seem to add just fine for me on the dev build if they are added as a plugin. Are you talking about having them add to attributes if they're not tied to the commlink as a plugin, and instead are equipped when they're parentless on the gear list?

**Comment by OLStefan** [comment]
Nope, stupid me just forgot to pull before testing.
