### ISSUE TITLE
in Career Mode raised skills from a broken skill group do not get saved

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#217]
Chummer 5.166
get a char with skill groups in career mode
give yourself some karma
break the group
raise one skill of the group
save the char
open it again
the skill has its level after/before group breakup, not the individual raised skill level
the karma is spent
but it seems to save that the group is broken

workaround now: undo the karma spending of the skill raise & raise the skill again

**Comment by chummer5a** [comment]
Save/load methods are fine, value is being set properly. Seems to be something in updatecharacterinfo() rather than career_load.

**Comment by chummer5a** [comment]
Fixed in 5.167; need to do some testing to make sure the fix doesn't break other functionality.
