### ISSUE TITLE
Friends in High Places

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2171]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Friends in High Places Quality is supposed to add Cha. x 4 free contact points
### Actual behaviour
Friends in High Places uses starting contact points or karma, there are no free point. This was also happening in the prior version.
### Steps to reproduce the behaviour
I tried a couple of new characters in version 5.195.0 and it wasn't working properly, so I updated to newest version 5.196.0 and it's still happening.

### Link to affected character file
Sorry, tried to link character but I use rar not zip.

**Comment by chummer5a** [comment]
Friends in High Places doesn't kick in until the contact has 8 or more Connection, per RAW.

**Comment by HarleeKnight** [comment]
Okay, Quality kicked in but now it won't let me save character as created. It says I can't have a contact with more than 7 points and none of my other contacts have more than 6 points.

**Comment by OLStefan** [comment]
Just got a second report of the 'can't mark as created' from the german Shadowrun forum.

**Comment by FieryWitherRose** [comment]
In contacts, after taking friends in high places, the app refuses to use the free contacts that come with charisma. So I'm stuck with 21/28 free contacts without anyway to use it
