### ISSUE TITLE
Adept Ways

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2172]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adept Ways are supposed to offer discounts on some adept powers and they're also supposed to cost 20 karma.

### Actual behaviour
There was no discounts on adept powers that I could see and the qualities cost only 15 karma

### Steps to reproduce the behaviour
Tried using different Way Qualities and none of them worked right.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate the discount for any of the Ways with exception of the Burnout's Way, which is explicitly discounted to 15. 

The checkbox to discount a power via the Way should become visible if you take the appropriate power. For example, Artisan's Way discounts Killing Hands, enabling the checkbox.

**Comment by HarleeKnight** [comment]
Astral Perception is an option for several and it's not giving a discount on any Way that has it. As for the karma discount, after a reload, Beast Way and Spiritual Way are costing only 15.

**Comment by HarleeKnight** [comment]
Okay... reloaded again and power discount appears to be working again.

**Comment by HarleeKnight** [comment]
Ugh... Update... It's the Magician's Way that is causing the problems with power point discount. It's supposed to allow any power except Imp. Ref. but it doesn't allow any and if you change Ways with a power active, you have to delete the power and re-choose it.
