### ISSUE TITLE
Magic Mastery Qualities

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2173]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Magic Mastery Qualities from Forbidden Arcana can be chosen at character creation and are supposed to charge Karma.

### Actual behaviour
Some of the Magic Mastery Qualities are not charging karma when chosen at character creation.

### Steps to reproduce the behaviour
I have tried a few of the easier ones to get, like Chosen Follower, Revenant Healer, and Adept Healer and no charge to karma from either. I have not tried them in career mode.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Mastery qualities will use your free spell points first, if they haven't already been used on other spells.
