### ISSUE TITLE
Reapply improvements removes cyberware enhancement

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2176]
### Environment
Chummer Version: 5.196.4
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Following use of Re-apply improvements function to update gear definitions that Cyberware enhanced attributes will be the same.

### Actual behaviour
The enhanced Reaction from Wired Reflexes Cyberware  is gone.

Before Reapply
![reaction before](https://user-images.githubusercontent.com/17562417/34009995-f51f96b4-e102-11e7-824c-57131df5800a.png)

After Reapply
![reaction after](https://user-images.githubusercontent.com/17562417/34010004-fefde366-e102-11e7-9087-0b314c13ae5c.png)

**Comment by chummer5a** [comment]
Should have been fixed by c221070d31a11e2b8205b1318e9772495e4b1b11
