### ISSUE TITLE
Reapply improvements highlight a valid quality

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2177]
### Environment
Chummer Version: 5.196.4
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Following use of Re-apply improvements existing valid qualities are not highlighted.

### Actual behaviour
The valid quality Impassive is shown as not having a data file entry
![improvements](https://user-images.githubusercontent.com/17562417/34011738-f88d1f1e-e108-11e7-9daf-6756582b5989.png)

### Steps to reproduce the behaviour
Use Reapply Improvements on a character with the Impassive Quality.

### Link to affected character file
Character file before using Reapply Improvements
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1560541/Character.file.zip)

**Comment by chummer5a** [comment]
For some reason your version of the Impassive quality has the wrong source ID (Should be 1c356f79-e4c1-4874-aed0-d7796ea35ed4), so we can't reliably fetch the right XML node to use. I believe we changed the source ID on that quality back in 5.192 and this method of validation is rather new, so it was likely just caught up in the fallout from that.
