### ISSUE TITLE
Reapply improvements inconsistent in list of foci

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2178]
### Environment
Chummer Version: 5.196.4
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Using Reapply improvements treats each type of gear consistently.

### Actual behaviour
Applying Reapply improvements to a character with this list of foci
![foci list](https://user-images.githubusercontent.com/17562417/34011978-efd85afe-e109-11e7-8007-89c113600a2c.png)

Only the Sustaining Focus requests a value. Why?
![reapply](https://user-images.githubusercontent.com/17562417/34012049-2ce352dc-e10a-11e7-8c3b-54323e6b07d3.png)

### Steps to reproduce the behaviour
Use Reapply improvements to the attached character.

### Link to affected character file
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1560563/Character.file.zip)

**Comment by chummer5a** [comment]
The Summoning Focus has a gearname, not an Extra value. Best guess, you might have clicked past the prompt originally or left it blank? The Summoning Focus is the only one of those foci that has a selecttext improvement that isn't handled.

**Comment by DelnarErsike** [comment]
It's not an error. Summoning Foci, unlike the other foci in that list, only apply to a specific category of spirit chosen when you take the focus. The value for the Summoning Focus is about selecting the spirit category, not renaming the focus.
