### ISSUE TITLE
Attribute Values, Limits not Calculating Properly

### ISSUE THREAD

**Issue by forfthemad** [chummer5a/chummer5a#2181]
[CharacterFile.zip](https://github.com/chummer5a/chummer5a/files/1561553/CharacterFile.zip)
### Environment
Chummer Version: Was working fine on 5.195.0. Issues appeared in 5.196.0
Environment: Windows 10 Home
Runtime: Probably .NET 4.5.1)

### Expected behaviour
Quality Infirm I reduces maximum Physical Attributes to 5.
Muscle Replacement Cyberware doesn't increase STR or AGI by 1 each.
Physical Limit calculated correctly using BOD 3, STR 2, and REA 2.

### Actual behaviour
Infirm I reduces maximum Physical Attributes to 4.
Muscle Replacement Cyberware doesn't increase STR or AGI.
Physical Limit calculated incorrectly using BOD 1, STR 1, and REA 2.
Thank you in advance for your assistance.

### Steps to reproduce the behaviour
Updated to 5.196.0. Using Improvements tab to increase Atts and Limits fails to resolve issue.

### Link to affected character file
Character file included above.

**Comment by DelnarErsike** [comment]
There were issues with Reapply Improvements that prevented it from working properly, but those are now fixed on the dev build, so they should show up in Nightly-v5.196.6. Once those fixes are working, Reapply Improvements immediately fixes all of the mentioned issues for the character.
