### ISSUE TITLE
Custom Fit (stack) armors not stacking

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2182]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Custom Fit (stack) armors are supposed to add a few of the coat armor points with the entire of the outfit.
(ex. Mortimer of London: Argent Coat with Zoe: Executive Suite is supposed to stack 4 + 12 for 16)

### Actual behaviour
Armor or either not stacking or combining all armor points from both coat and suit.
(ex. Mortimer of London: Argent Coat and Vashon Island: Sleeping Tiger is 12 +13 for 25 total and
Mortimer of London: Argent Coat and Zoe; Executive Suite is just 12 total)

### Steps to reproduce the behaviour
I tried several different combinations and could not get any to work correctly

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
I may have screwed up a delicate equilibrium with that armour. It wasn't coded super well originally and I thought I could pull part of it out without effect. Will investigate.
