### ISSUE TITLE
Name for alternate ranges not translated

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2185]
### Environment
Chummer Version: 5.196.5
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The name of the alternate ranges should be shown/printed in the selected language.

### Actual behaviour
Chummer5a shows and prints both, the standard and the flechette, range tables for shotguns.
The name for the standard ranges is correctly translated into the UI language (German in my case) and thus shown as "Schrotflinten".
The name of the alternate ranges is shown and printed in English as "Shotguns (flechette)". For German it should be "Schrotflinten (Flechette)".
As I did not found a corresponding entry in the translations files, I assume that the name is currently somehow hard coded.

### Steps to reproduce the behaviour
Create a character
Add a shotgun

**Comment by DelnarErsike** [comment]
Latest commit should allow Chummer to process translate nodes added to data from ranges.xml. The data's not translated into German (yet), but now should it be, it should show up.

**Comment by holgerschlegel** [comment]
The file "ranges.xml" is not selectable in the Translator.exe of version 5.196.6.
I tried to add the file manually to the de-de_data.xml file. Now the file can be selected, but it shows no strings to be translated.

Manually added translations for ranges.xml in the de-de_data.xml file are not used. I assume that I did not entered it with the correct structure / tags.

**Comment by DelnarErsike** [comment]
Bah, I messed up something in the Rebuild code that mixes Ranges up with Qualities. That should be fixed in 5.196.8.
