### ISSUE TITLE
Incorrect resistance pools in sheet

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2186]
### Environment
Chummer Version: 5.196.5
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
If both places are meant to show the same attribut, the value should be the same.
Otherwise, the labels should be different.

### Actual behaviour
The "Shadowrun 5" sheet shows the "judge intentions" value twice. Once in the player/general block (the first one in the sheet). And once in the new "resistences" block.
But the value is different.
For one of my characters, the value in the player block is 10, the value in the resistences block is 9.
For another characters, the value in the player block is 9, the value in the resistences block is 7.

**Comment by holgerschlegel** [comment]
Maybe this issue is no bug.
The value in the player block is the pool if the character uses judge intentions.
The value in the resistences block is the pool to defend against judge intentions used by another character.

If this is true, just close this issue.

**Comment by DelnarErsike** [comment]
Correct. "Judge Intentions" under the Resistances section is the dicepool to resist Judge Intentions rolls, which can be different from the dicepool to make them. E.g. one is CHA + INT, the other is CHA + WIL, and powers and qualities like Kinesics, Honest Face, and Authoritative Tone affect one but not the other.
