### ISSUE TITLE
[Bug] Augmented Str not counting towards encumbrance

### ISSUE THREAD

**Issue by legionof1** [chummer5a/chummer5a#2188]
### Environment
Chummer Version: 5.196.5
Environment: Windows
Runtime: 4.7

### Expected behavior
When calculating encumbrance a characters full Str (attribute+augmentation) should be used.

### Actual behavior
Augmentations are not being counted.

### Steps to reproduce the behavior
Acquire more +armor then base Str but not above augmented STR.
Observe encumbrance effect on stats.

### Link to affected character file
[Thunderbolt.zip](https://github.com/chummer5a/chummer5a/files/1564304/Thunderbolt.zip)

**Comment by drakir75** [comment]
196.5
Not sure if related. There is something wrong with armor/encumbrance calculation. Berwick Suit + Argentum Coat did not add up right. Tiger + Synergist Longcoat added up to right amount of armor but way too much encumbrance. (No augmented strength needed.)
