### ISSUE TITLE
Enhanced Articulation Physical Limit Improvement not saved properly

### ISSUE THREAD

**Issue by W1ld3b34st** [chummer5a/chummer5a#219]
Affects v5.166

I believe this either is the same cause, or is resolved by the fix already in v5.167 mentioned in #212, but wanted to post it for verification.

Reproduction Steps -> Create Character -> Select Enhanced Articulation and any skill (As an aside, isn't RAW this always has to be Escape Artist?) -> Check Limits -> Save Character -> Load Character -> Physical Limit should have decremented by 1.

**Comment by chummer5a** [comment]
Both issues fixed in 5.167. Improvement Manager can be a bit... interesting to understand sometimes, I assume the previous dev didn't know about specificskill and used selectskill instead. Anyway, fixed!
