### ISSUE TITLE
Reapply improvements issues

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2190]
### Environment
Chummer Version: 5.196.6
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Actual behaviour
Identified the following problems/inconsistencies with reapply improvements
- [x] 1) Every item of gear now has Matrix attributes applicable or not. 20% increase in character file size.
![matrix attributes](https://user-images.githubusercontent.com/17562417/34072139-ae318a1e-e279-11e7-8efb-7900378b32d7.png)

- [x] 2) Addiction now has Notoriety. Where did this come from?
![addiction](https://user-images.githubusercontent.com/17562417/34072144-c5899d14-e279-11e7-88f6-6a45ece1c659.png)

- [x] 3) Each Quality now has "Bonus" twice, one of them is always null. Will this cause problems?
- Quality with an applicable Bonus
![bonus](https://user-images.githubusercontent.com/17562417/34072155-fba04a24-e279-11e7-9d48-d3e571687990.png)
- Quality with double Bonus
![bonus2](https://user-images.githubusercontent.com/17562417/34072156-0c956db4-e27a-11e7-97af-3f1077163297.png)

- [ ] 4) Ammo clips have lost their name
![clips](https://user-images.githubusercontent.com/17562417/34072160-23b68938-e27a-11e7-837f-e528712ac6f8.png)

Note: The problem from #2143 was not fixed with the Reapply Improvements changes in this Nightly.

### Steps to reproduce the behaviour
Run Reapply Improvements on the "before" character attached.

### Link to affected character file
[Character files.zip](https://github.com/chummer5a/chummer5a/files/1564905/Character.files.zip)

**Comment by chummer5a** [comment]
Notoriety and Street Cred are provided by several qualities. SR5 368.

**Comment by Lochabar** [comment]
This would mean Chummer never applied the Notoriety when the character was created. Correct?

**Comment by chummer5a** [comment]
Yeah, they were overlooked originally. Since reapplying improvements completely ignores what your character had and recreates everything from the source files, they wound up getting the new notoriety values.

**Comment by DelnarErsike** [comment]
Re: Matrix Attributes, it's an extension of an overall data structure conundrum with Chummer5. Either we choose to (re)fetch values from data files every time the object is created, or we save those values once they've been fetched at least once and then we never bother with (re)fetching them. Right now, we're using the latter for Matrix attributes, which is what causes those attributes to show up in every object that belongs to a class that implements IHasMatrixAttributes. If we were to switch to the former, we could cut down on filesizes, but we'd get into a dangerous territory should the data source for a particular item not exist: e.g. the item's Guid changed, the item was part of a custom dataset that was not loaded, etc. There's also the minor issue of cyberdeck attribute array configurations not getting saved should the former be used.

A 20% filesize increase sounds bad on paper, but when most characters have sub-1MB save filesizes, I view it as a non-issue. It's not like gear attributes are even the greatest contributors to filesizes (those are usually mugshots and/or expenses). I've therefore ticked that box.
