### ISSUE TITLE
Opening character crashes Chummer

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2192]
### Environment
Chummer Version: 5.196.7
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Character files can be opened.

### Actual behaviour
Attempt to open character file crashes CrashHandler then Chummer. No dump file.
![crashhandler 1](https://user-images.githubusercontent.com/17562417/34080767-1a1d0f84-e33b-11e7-9869-897e428d3feb.png)
![crashhandler 2](https://user-images.githubusercontent.com/17562417/34080768-1a5660f4-e33b-11e7-8009-2fba2a8825d3.png)

![chummer 1](https://user-images.githubusercontent.com/17562417/34080771-2429f898-e33b-11e7-8b75-af151eeb2f8a.png)
![chummer 2](https://user-images.githubusercontent.com/17562417/34080772-244fb812-e33b-11e7-99ff-385bfa89cbe9.png)

**Comment by chummer5a** [comment]
Can't replicate it, but I just pushed the nightly build early to get some extra stuff out. Try that and see if it works?

**Comment by Lochabar** [comment]
Latest nightly works. Thank you.
