### ISSUE TITLE
[bug] Lifestyle with Multiple Roomates cost error

### ISSUE THREAD

**Issue by legionof1** [chummer5a/chummer5a#2193]
### Environment
Chummer Version: 5.196.10
Environment: Windows
Runtime: 4.7

### Expected behavior
When having multiple roommates, final cost of lifestyle should be divided by number of roommates.
### Actual behavior
Number of roommates has no effect on final cost

### Steps to reproduce the behavior
Buy any lifestyle above street.
Set X number of roommates. 
Observe final cost.

### Link to affected character file
[Saturday mage.zip](https://github.com/chummer5a/chummer5a/files/1570896/Saturday.mage.zip)

### Notes
This function was working a few days ago somewhere around 5.196.6

**Comment by chummer5a** [comment]
Mm, I need to reintroduce a proper 'Is Primary Tenant' option still. Should be able to get it done before the next nightly build.

**Comment by chummer5a** [comment]
As an interim, you can change the percentage to pay to be appropriate for your share, ie 20, 25, etc.
