### ISSUE TITLE
Enhancement Request - Lifestyle notes + Lifestyle Printing

### ISSUE THREAD

**Issue by athwargamer** [chummer5a/chummer5a#2194]
Would it be possible to attach a notes section to each lifestyle, and would it be possible to get a means of printing off the lifestyle details, similar to the way contacts are done?

**Comment by chummer5a** [comment]
Notes are accessed by right-clicking on the treenode (the list of lifestyles) for the lifestyle and typing text into the textbox. Pretty much all the relevant properties are already exposed to the print method, I just really hate fiddling with the stylesheets.

**Comment by athwargamer** [comment]
Ok, I must have missed that. thank you.
