### ISSUE TITLE
Martial arts selection is empty

### ISSUE THREAD

**Issue by Trinova313** [chummer5a/chummer5a#2196]
### Environment
Chummer Version: Chummer5a 5.196.11
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
When clicking add martial art on the martial arts tab a selection of martial arts appear in a new window.

### Actual behaviour
A selection window appears with no options.

### Steps to reproduce the behaviour
select martial art speciality under close combat and click on add martial art on the martial arts tab

### Link to affected character file
https://drive.google.com/open?id=1MonpTJ5qlRrEeuR4CINr3lgVYzdIPCRi

**Comment by DelnarErsike** [comment]
Unable to reproduce in dev build. The Martial Arts selection dialog properly populates all available Martial Arts for the character, regardless of what specialization is chosen for Unarmed Combat. I suspect that you have malformed data files.

Keep in mind that choosing a specialization in a particular Martial Art is independent from actually learning said Martial Art. The specialization just lets you get the +2 bonus whenever you use a technique from that Martial Art.

**Comment by Trinova313** [comment]
Did a fresh download and got an error box stating that the character had values from a sourcebook that wasn't available. Turns out the additional books have to be manually toggled on. My bad!
