### ISSUE TITLE
Made Man

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2198]
### Environment
Chummer Version: 5.196.10
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
"Made Man" quality to be choosable without error.

### Actual behaviour
Chummer says no contact available even when I have a suitable contact.

### Steps to reproduce the behaviour
Create character. Give him/her a contact. Add quality "Made Man".

**Comment by SeanPGorman** [comment]
Is the contact flagged as being a "Group" contact? It is a checkbox on the Contact object.

**Comment by lordblades** [comment]
I've experienced the same issue on  version 5.196.4, and I did double check the contact was flagged as 'Group'; Still didn't help
