### ISSUE TITLE
Street Cred based on Career Karma

### ISSUE THREAD

**Issue by duncanmb** [chummer5a/chummer5a#220]
It appears that the calculation for Street Cred based on Career Karma is rounding up rather than down so that a character gets a point of Street Cred as soon as they have a single point of Career Karma rather than gain a point of Street Cred with the 10th point of Career Karma,

**Comment by joha4270** [comment]
Issue found and dealt with, will be fixed in 5.167.

Next time please produce more detailed reproduction instructions as i almost discarded this as not reproducible. It doesn't round up, it just rounds (up if <5)
