### ISSUE TITLE
Missing: Motorcycle Gyrostabilizer

### ISSUE THREAD

**Issue by StillesChaos** [chummer5a/chummer5a#2203]
### Environment
Chummer Version: 5.196.0
Environment: Windows x64
Runtime: .NET 4.5.1

### Expected behaviour
Wanted to add a Gyro stabilizer to a Yamaha Nodachi.

### Actual behaviour
Gyro stabilizer wasn't listed for it. Neither in english nor german. (Item listed on PG. 162 in Rigger 5.0/Asphaltkrieger German)

Edit: I made a photo of the entry in the german sourcebook. I talked to a buddy of mine who's n posession of english supplement books. Appaerently it's nowhere mentioned as an option for motorcycles but there are several mentions of it existing, such as the Cyclops or the revolution.

https://abload.de/img/gyro63pjz.jpg

**Comment by chummer5a** [comment]
I'm not seeing it as a discrete mod.
