### ISSUE TITLE
Unable to increase attributes

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2204]
### Environment
Chummer Version: 5.196.14 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Be able to click the "+" button to increase a characters attributes.

### Actual behaviour
Most or all of the "+" buttons are greyed out.
![attributes](https://user-images.githubusercontent.com/17562417/34322849-b5ae356a-e82a-11e7-80d2-c6fc9a0158a6.png)

This happens for multiple characters but not all.

### Steps to reproduce the behaviour
Open one of the attached characters. Look at the "Common" tab.

### Link to affected character file
[Character files.zip](https://github.com/chummer5a/chummer5a/files/1584458/Character.files.zip)

**Comment by DelnarErsike** [comment]
Working as intended. All of the disabled "plus" buttons on the linked characters are on attributes whose karma costs exceed the character's current free karma.
