### ISSUE TITLE
Re-apply Improvements does not update vehicles

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2205]
### Environment
Chummer Version: 5.196.14 (and earlier)
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Running Re-apply Improvements updates vehicle definition.

### Actual behaviour
This is the current gear definition for the Toyota Gopher.
![gopher](https://user-images.githubusercontent.com/17562417/34322999-c091dd52-e82e-11e7-8ff3-3c8100e179a4.png)
Notice the two mods "Off-Road Suspension" and "Open Box Storage".

Having run Re-apply Improvements a characters vehicle has not been updated.
![gopher after](https://user-images.githubusercontent.com/17562417/34323011-14e0da5c-e82f-11e7-8376-051d22ce6317.png)

### Steps to reproduce the behaviour
Open a character with a Vehicle that has subsequently been updated. Run Re-apply Improvements. The definition has not been updated.

**Comment by DelnarErsike** [comment]
Working as intended. Those are not improvements, so they are not re-applied. Improvements are only items that are found within `<bonus>` tags or similar (e.g. `<pairbonus>`, `<wirelessbonus>`).

**Comment by Lochabar** [comment]
That would mean the only ways to bring a Vehicle in line with its data file definitions are
1) Add it again as as Free, adding in any addition gear mods.
2) Edit the character source file and copy in the changes from the Vehicle data file
Is this correct?
And does this apply to all Gear as well?

**Comment by DelnarErsike** [comment]
Correct. Re-apply improvements is only for regenerating stuff within `<bonus>` nodes. If you're looking to merge two items (and you are merging them in this case, you're merging your existing vehicle with a hypothetical new vehicle of the same model), you will need to do so manually.
