### ISSUE TITLE
SRM Missions FAQ Sensors

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2206]
### Environment
Chummer Version: 5.196.14
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### From the Missions FAQ 1.4 page 62
![faq sensors](https://user-images.githubusercontent.com/17562417/34323157-e2391b0a-e833-11e7-9dd5-786b823ecdde.png)

Are there plans to add these definitions to the Vehicles data file?

**Comment by chummer5a** [comment]
Hrm. The current system for vehicle gear can't handle child items, beyond that I'm not entirely sure the amend system can add or alter a whole root node. @DelnarErsike can you think of a way to bastardise it from

`<gear rating="2" maxrating="6">Sensor Array</gear>`

into 

```
    <gear>
      <name>Sensor Array</name>
      <rating>2</rating>
      <maxrating>6</maxrating>
      <gears>
        <gear select="Rear-Facing">Camera</gear>
        <gear>Atmosphere Sensor<gear>
      </gears>
    </gear>
```
