### ISSUE TITLE
Bug: Striking Callus Bioware Has No Effect

### ISSUE THREAD

**Issue by FableWright** [chummer5a/chummer5a#2213]
### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When purchasing any 2 Striking Callous bioware (2 hands, 2 feet, one hand one foot), the damage rating under Unarmed Attack in the Weapons tab of Street Gear should increase by 1, per CF121.

### Actual behaviour
Regardless of number of implanted Striking Callus biowares, Unarmed Attack damage does not improve.

### Steps to reproduce the behaviour
1. Create a new character.
2. Purchase two Striking Callus bioware.
3. Observe Street Gear -> Weapons -> Unarmed Attack

### Link to affected character file
[Chuck-E.txt](https://github.com/chummer5a/chummer5a/files/1589210/Chuck-E.txt)

**Comment by chummer5a** [comment]
Something's janky with the pairbonus code when it uses Locations.
