### ISSUE TITLE
Run and Gun - Custom Fit Armor only stacks

### ISSUE THREAD

**Issue by ichpunktpdf** [chummer5a/chummer5a#222]
First: I am so happy to see people working again on chummer for 5th edition! :-D

Armor with Custom Fit (Stack) only gives the stack bonus but not its base armor value if it is the sole armor:
Example: The Mortimer Argentum Coat adds its +4 stack bonus to other armor. If it is worn above simple clothing, it still gives +4 Armor instead of the correct 12.

**Comment by joha4270** [comment]
I need to take a look at the internals of Chummer to see how this item
is handled, but i fear it might not be something that is easily fixed.

Will take a look at it but i won't promise that it is fixed next release

2015-05-31 15.57 GMT+02.00, ichpunktpdf <notifications@github.com>:

**Comment by chummer5a** [comment]
Custom Fit (Stack) needs new code, yes. I've been meaning to look into it;
we more or less need a <stackable> or <outfit> tag that contains the outfit
it can stick with, at which point it treats itself as a mod for the gear.

**Comment by joha4270** [comment]
I think honestly the easiest way to do it is to instead of consider it
12/+4 consider it as 8+4. I haven't actually checked if armor goes trough
improvementmanager but if it does it should be doable to only put the
strUnique for non stacking armor on the 8.

2015-05-31 17:31 GMT+02:00 Chummer 5 Is Alive <notifications@github.com>:

> Custom Fit (Stack) needs new code, yes. I've been meaning to look into it;
> we more or less need a <stackable> or <outfit> tag that contains the outfit
> it can stick with, at which point it treats itself as a mod for the gear.
>

**Comment by chummer5a** [comment]
Okay, so the previous dev added in a key called armoroverride to sorta kinda support this. 

At clsEquipment line 1649, you'll see that it does a basic loop check to see if it has the key, and if it's the only piece of armour equipped. If it is, it uses the armoroverride key. If it's not, it uses the standard amount. The problem that the OP is reporting is that A) Clothing counts as armour and B) armoroverride stacks with everything that's equipped. So easy temporary workaround: Only equip your mortimer gear and all will be well. 

Fixing this properly should be as simple as adding <selectarmor /> (Which will need to be created. Same as <selectweapon />.) checking if the armour has the custom fit (Stack) mod, and the selectarmor'd item.  If that's the case, sweet! Stack our armour like it's 2099!

**Comment by ichpunktpdf** [comment]
Ah, I forgot to check if the bug occurs, too, when character is "naked". Then everything's fine for now.

Would it be possible to implement something like a checkbox on the armor tab to determine whether a piece of custom fit (stack) armor should stack or not instead of strictly incorporate the rules from run and gun (custom fit(stack) gives bonus only for another custom fit item of same manufacturer)? I would like to loosen the restrictions for my group a little and decide for each combination whether it is stackable or not.

Again, my thanks for you putting so much effort in pushing this awesome tool forward. Unfortunately, I don't have a single clue about code :-)

**Comment by chummer5a** [comment]
The way I've written it for now, if you add an item that has custom fit
(stack), it will prompt you to select the appropriate item that it's been
custom fitted for. It needs some additional code to actually do the value
flipping and not apply the bonus to everything that's equipped, shouldn't
take too long to sort out.

**Comment by joha4270** [comment]
I would have made that part of its properties in the xml file, but your version works too, pros and cons for both.

To allow any kind of house rules, a +Rating armor, that allows every piece of armor to be created.

>Unfortunately, I don't have a single clue about code :-)
If i read that correctly, that you would love to help but lacks the skills, look at #203 
There are a lot of packs in ?Run Faster? that we don't have that just requires a lot of data entry. On top of that there is nothing preventing packs of skills/equipment/spells/gear/ware required for a street samurai, a hacker, a magical investigator etc etc.

**Comment by ichpunktpdf** [comment]
I guess I will have a look into the wiki and see if I can be of any help. The Run Faster isn't issued in German yet and it includes errata, so it may (will) be that English and German versions differ. But after I understood how the XMLs are structured and how to create/adjust/whatever something, maybe I find another little piece of work where I am able to help. Like adding the additional ADL German Content or the German PACKs from Run Faster or something else...

**Comment by joha4270** [comment]
You don't even have to understand XML, you can export a pack from chummer
(after adding to gear/etc selection i think, but not something i have used
so i won't bet)

2015-06-01 15:59 GMT+02:00 ichpunktpdf <notifications@github.com>:

**Comment by chummer5a** [comment]
Resolved in 5.167.
