### ISSUE TITLE
Question on "Verify Data File" report

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2220]
### Environment
Chummer Version: 5.196.22
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Question
I'm currencly working on German translations of the data files.
The report generated with the button "Verify Data File" contains some entries in the following form:
```
		<noentry>
			<mod>
				<name>Additional Clip</name>
			</mod>
		</noentry>

```
Just to be sure:
Does that mean the the named element is present in the translation file but not in the base data file and thus can safely be deleted from the translation file?
I do not want to delete anything that might be used but I don't see were.

**Comment by chummer5a** [comment]
Seems so, yes. Additional Clip is a legacy object from before I merged mods and accessories into the same object.

**Comment by holgerschlegel** [comment]
Thanks.
I will fix this "issue" in the German data translation file in a soon coming pull request with some more German translation updates.
