### ISSUE TITLE
Vehicles glitch and crash in career

### ISSUE THREAD

**Issue by Jackbotian1** [chummer5a/chummer5a#2223]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding a vehical

### Actual behaviour
Crash

### Steps to reproduce the behaviour
in career mode adding a vehical

### Link to affected character file
[chummer_crash_131590568559967047.txt](https://github.com/chummer5a/chummer5a/files/1593908/chummer_crash_131590568559967047.txt)

**Comment by chummer5a** [comment]
I believe this is fixed in the current nightly builds. https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.196.24/Chummer.Nightly.zip
