### ISSUE TITLE
 Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by HelenMetzger** [chummer5a/chummer5a#2224]
### Environment
Crash ID: 4173ba4d-62f0-4f8c-b1bc-ee66852ed7c7
Chummer Version: 5.195.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Uh, kinda need some more details here, but I'd suggest updating to the most recent build for whatever's up.

**Comment by HelenMetzger** [comment]
This was sent by the crash reporter, sadly I was in the middle of a game and thought you need simple usage data.  Probably should have checked.   Anyway, here's the full report.

I attempted to open the attached chum5 files.  On my first attempt I simply double-clicked the file while I had the application open.  Windows defender opened a dialog informing me that an application had been stopped from executing.  I accepted the message and Chummer crashed.  I repeated this a second time, but allowed the application to execute through the window's defender advanced options.  That resulted in this report.

I questioned my players in regards to this event and one them informed me that they were using the most recent nightly build.  I believe that this issue can be resolved by my upgrading, and my players sticking to stable builds. 

[Grom.txt](https://github.com/chummer5a/chummer5a/files/1594650/Grom.txt)

-update  github does not support chum5 files so you will need to change the extension of this file from a .txt to a .chum5.
