### ISSUE TITLE
Question about encumberance

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2228]
### Environment
Chummer Version: 5.196.24
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Actual behaviour
After Re-apply Improvements I realized that armor encumbrance penalties had been applied to a character.
![armor encumberance](https://user-images.githubusercontent.com/17562417/34456361-097afa78-ed8c-11e7-8e6b-2d3460eed013.png)

What is Chummer using to determine encumbrance given the lack of weights for gear in the rulebooks?

**Comment by DelnarErsike** [comment]
There are rules for armor encumbrance on core rulebook p. 169, and Chummer follows those rules.

Please do not use the GitHub issues page to request that we look rules up for you, as it messes with actual issues regarding actual bugs and enhancement requests.

**Comment by Lochabar** [comment]
I looked at those pages and there is no WEIGHT associated with any item of gear. So how is Chummer calculating how much weight a character is carrying in order to determine encumbrance.

**Comment by DelnarErsike** [comment]
It does not. All that you're looking at is Chummer5a enforcing the two paragraphs of rules on p. 169 of the core rulebook.
