### ISSUE TITLE
Bullet tracking does not work with German language

### ISSUE THREAD

**Issue by ichpunktpdf** [chummer5a/chummer5a#223]
If Chummer runs with German language settings, the Fire button on the weapon tab does not work properly: You cannot choose between different modes (they are all grey) and whenever you click the button it subtracts 6 bullets.
In English everything is fine.

**Comment by chummer5a** [comment]
Button function calculation is using the name string to determine what it's
doing. Switch to language-string handler or use IDs like a sensible person.

**Comment by ichpunktpdf** [comment]
I am sorry but I don't know enough about coding to understand that. What and where is the language-string handler and what do you mean by ID?

**Comment by chummer5a** [comment]
Haha, don't worry about it. I tend to talk to myself in these comments.

**Comment by joha4270** [comment]
I don't think you are supposed to really understand it, it is a note to me or him when we get around fixing *that*  what is actually happening.

A translation to a non software person is that the the piece of computer talk that takes care of firing bullets are based on the name of the action so when it sees the german name it have no idea what it means, where a sensible person would use some kind of ID instead.

**Comment by ichpunktpdf** [comment]
:-D

**Comment by chummer5a** [comment]
Fixed in 5.167.
