### ISSUE TITLE
Bug: Soft Nanohive (Neocortical) Does Not Apply Bonus to LOG-Related Skills

### ISSUE THREAD

**Issue by FableWright** [chummer5a/chummer5a#2230]
### Environment
Chummer Version: 5.196.24
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Per Chrome Flesh 150, the presence of a Neocortical Soft Nanoware in one's bloodstream should apply a +1 bonus to all LOG-linked skills.

### Actual behaviour
No +1 bonus can be found on active or knowledge skills related to LOG.

Additionally, no Soft or Hard Nanites are available for purchase separate from a nanohive.

### Steps to reproduce the behaviour
1. Purchase a rank in Hardware.
2. Purchase a rank in an Academic knowledge skill.
3. Purchase Soft Nanohive (Neocorticol).
4. Observe: No bonus to LOG related skills.

**Comment by DelnarErsike** [comment]
Working as intended. Nanohives function independently from the nanoware they support. You'll need to buy the nanoware to get its benefits.

**Comment by FableWright** [comment]
See part 2 of 'Actual Behavior': 

Additionally, no Soft or Hard Nanites are available for purchase separate from a nanohive.

At the very least, a search in Gear does not cause anything to pop up.
