### ISSUE TITLE
The "Tasking" skill group shows up under Knowledge Skills

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#2234]
Since the last Major update, the "Tasking" skill Group is no longer listed under the "Active Skills" but below under the "Knowledge Skills". 
So far, no nightly update has fixed this

**Comment by chummer5a** [comment]
At a guess, you re-applied improvements at some point? There's currently a bug with the skill system where doing that makes it treat the skill as though you had burned out, making it into a knowledge skill.

**Comment by DecklandMulqueen** [comment]
Sir no Sir … no improvements have been applied :(

 

Von: Chummer 5 Is Alive [mailto:notifications@github.com] 
Gesendet: Sonntag, 31. Dezember 2017 11:02
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] The "Tasking" skill group shows up under Knowledge Skills (#2234)

 

At a guess, you re-applied improvements at some point? There's currently a bug with the skill system where doing that makes it treat the skill as though you had burned out, making it into a knowledge skill.

**Comment by chummer5a** [comment]
I can't replicate the problem, so best scenario I've got for you is for you to upload the sheet here (Put it into a zip or change the format to .txt) and I'll fix the affected file.

**Comment by DecklandMulqueen** [comment]
As you wish!

 

Anything else is fine, THX for your work!!!

 

Tobi

 

Von: Chummer 5 Is Alive [mailto:notifications@github.com] 
Gesendet: Dienstag, 2. Januar 2018 06:05
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] The "Tasking" skill group shows up under Knowledge Skills (#2234)

 

I can't replicate the problem, so best scenario I've got for you is for you to upload the sheet here (Put it into a zip or change the format to .txt) and I'll fix the affected file.
