### ISSUE TITLE
Adapsin doesn't work

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#2236]
### Environment
Chummer Version: 5.196.26
Environment: Windows 10

### Expected behaviour
Adapsin should apply a -10% essence cost to cyberware

### Actual behaviour
Adapsin has no effect

### Steps to reproduce the behaviour
Create a new character. Add adapsin to them, and then add a piece of cyberware. Notice that the essence cost has not been reduced in chargen.

Alternately, add adapsin to a different character and see that the cyberware cost has not been reduced for new pieces of cyberware.

Finally, per ticket 1631 there is no inclusion of adapsin to the drop-down menu for cyberware grade.

**Comment by chummer5a** [comment]
Can't replicate it, do you have the Custom Data rule enabled that changes it to be a multiplier instead of a separate grade?

**Comment by ivancraddock** [comment]
I just tried it again with the latest release, and I still couldn't get it to work. I deleted my old chummer, and did a clean re-install. Here is a screenshot of a test character:

https://imgur.com/a/K9XHE

There is no adapsin option from the drop-down menu for grade, and adapsin doesn't automatically affect the cost. Both of these issues are present regardless of whether the custom adapsin option is selected.

**Comment by chummer5a** [comment]
the only way you should be getting that is if the character itself doesn't have the adapsin improvement for some reason. Can you upload thecharacter file? You can either change the extension to .txt or compress it to a .zip and attach it.

**Comment by ivancraddock** [comment]
Sure, here's a link to the sample character file: https://drive.google.com/open?id=1W_g9YeiWck5HiWO8un2OFvyoMUKNDrrd

**Comment by chummer5a** [comment]
Aha! Okay, I found the problem. The house rule to not treat adapsin as a separate grade only removes the adapsin bonus, it's not adding the necessary other bonus. I'm pushing a new build for it now, so if you grab that and either reapply improvements or remove and re-add the adapsin bioware, it'll work properly.

**Comment by ivancraddock** [comment]
Oh wow, thanks!
