### ISSUE TITLE
Relationships crashes 

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2240]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.26
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
Chummer not to crash. :-)

### Actual behaviour
Chummer crashes when choosing relationship tab or upon loading a character with contacts.

### Steps to reproduce the behaviour
^^

### Happy New Year!
Thanks for all the hard work.

**Comment by DelnarErsike** [comment]
Already fixed in dev build, will be present in the next Nightly.
