### ISSUE TITLE
Contact/Enemy crash

### ISSUE THREAD

**Issue by Herbadableh** [chummer5a/chummer5a#2241]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.26
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Being able to add a contact(or enemy) without issue

### Actual behaviour
Creating a new contact(or enemy) crashes the program.

### Steps to reproduce the behaviour
1. Make a character.
2. Go to "Relationships"
3. Click "Add Contact"
4. Wait for a few moments
5. Crash.

### Link to affected character file
[Example Character.zip](https://github.com/chummer5a/chummer5a/files/1596306/Example.Character.zip)

**Comment by DelnarErsike** [comment]
Already fixed in dev build, so it'll be present in the next Nightly.
