### ISSUE TITLE
Enhancement request: selectparagon (recent change was a partial success)

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2243]
### Environment
Chummer Version: 5.196.26
Environment: Win 10 Home
Runtime: .NET 4.7.1

### Request
Activate the selectparagon command, so that one can create a custom quality to select a paragon.
Custom quality would be as follows (this was copied on the mentor spirit quality):
>    <quality>
      <id>b2fce135-de91-4ea4-9119-1c696eb85290</id>
      <name>Paragon</name>
      <karma>5</karma>
      <category>Positive</category>
      <bonus>
        <selectparagon />
      </bonus>
      <required>
        <oneof>
          <quality>Technomancer</quality>
        </oneof>
      </required>
      <source>CoS</source>
      <page>00</page>
    </quality>

It used to be (in 5.196.21, I think) that selectparagon would open the mentor spirit selection menu.
Now, it opens a blank screen, and does not seem to make the connection with the paragons.xml file (see screenshot enclosed)

It would be great if you could look into enabling paragons in a future build.
(I'd be happy to check the paragons.xml File to ensure it doesn't reference obsolete skills and so on)
Thanks.
<img width="1184" alt="screen shot 2018-01-01 at 19 11 05" src="https://user-images.githubusercontent.com/4921171/34470356-9a73c572-ef27-11e7-8951-f55b27864920.png">

**Comment by oxford-fumble** [comment]
Hang on - I've had an idea.
I think it might be because all the paragons are registered under the "Unwired" book, which isn't an option in Chummer5a.

I'll check and feed back.

**Comment by oxford-fumble** [comment]
So, I think the "Unwired" book must have been part of the issue, but isn't the whole thing.

I created a custom "Unwired" book, and selected it in the options menu.
Then added the "paragon" custom quality.

Previously (without the book), it would show me an empty selection screen (as per the screenshot).
Now, it just crashes my install.

Make of that what you will...

**Comment by chummer5a** [comment]
The old paragons were never given ID tags, that's why it crashes.
