### ISSUE TITLE
No Ammo Bin

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#2244]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.26
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
When creating a vehicle, should be able to install an Ammo Bin from the Weapons section in Modifications.

### Actual behaviour
Cannot find Ammo Bin in Vehicle Mods. 

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Ammo Bins need to be added to weapon mounts, as per their description in Rigger 5.0. They cannot be added as a regular vehicle mod.
