### ISSUE TITLE
Printing crash on Linux/Wine

### ISSUE THREAD

**Issue by dude-rtfm** [chummer5a/chummer5a#2246]
### Environment
Chummer Version: detailed below
Environment: Debian Linux with wine-3.0-rc1
Runtime: 4.6

I have two different but linked issues to report : 
First is a crash of the printing screen. I did tick the box in options for the linux printing fix.
Steps to reproduce : start a new character with any method, then click the print button. 
the issue is pinpointed to version v5.195.97. v5.195.96 works "fine".

![screenshot from 2018-01-02 20-17-59](https://user-images.githubusercontent.com/26977664/34498599-4daa3112-effa-11e7-93a3-15e549f31a31.png)

Second issue is that the print screen generates an empty file : 

![screenshot from 2018-01-02 20-23-31](https://user-images.githubusercontent.com/26977664/34498748-ea056950-effa-11e7-8148-445ea1a58349.png)

Steps to reproduce : start a new character with any method, then click the print button. If the save as PDF option is used, it also generates a blank PDF.
the issue is pinpointed to version v5.195.76. v5.195.75 works fine.

**Comment by dude-rtfm** [comment]
Is the fix integrated in the nightly build? The issue is still present for me.

**Comment by chummer5a** [comment]
Nightlies are automatic rollups of whatever's been commited to the master branch, so it should be. Without knowing the exact circumstances behind the crash, I was more or less just forced to test what was there and  see if it crashed in windows as well.

**Comment by dude-rtfm** [comment]
I'm available if you need to run any tests.

**Comment by chummer5a** [comment]
What do you get if you click Show Details?

**Comment by dude-rtfm** [comment]
What screen is that in?

**Comment by chummer5a** [comment]
![image](https://user-images.githubusercontent.com/11448441/34801662-f558b888-f6bd-11e7-85cd-38283a2e279e.png)

**Comment by dude-rtfm** [comment]
Ah, kept trying to find something in the options screen.

![screenshot from 2018-01-11 10-16-13](https://user-images.githubusercontent.com/26977664/34820613-f239dab0-f6b8-11e7-989e-e717bd48a44a.png)

Full text is [here](https://pastebin.com/CEgfKVdy)
