### ISSUE TITLE
Did something change with the updater around v.13 to present?

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2247]
### Environment
Chummer Version: v196.13
Environment: Windows 10 Pro
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
To be able to update Chummer via the "Check for updates" window

### Actual behaviour
displays message: Updater Status: Chummer was unable to connect to the update server. Please check your firewall and proxy settings.

Has anything changed with the updater? I could (and did) update on an almost daily basis using it up to version .13, then I was away for a week or two and now it gives this message about being unable to connect. That being said, Chummer itself can see that .28 is available (it says so in the title bar). I know none of my firewall or network settings have changed recently, since I'm the only one who has access to them and I haven't changed anything. 

(although to be fair, there's always a chance Win 10 'updated' something, or that my ISP changed something on their side of things)

**Comment by chummer5a** [comment]
Short version yes, the updater got updated to be a bit more reliable, but in some cases it'll fail out early. If you close and reopen the updater a couple of times it tends to sort itself out.

**Comment by Zitchas** [comment]
Thanks for the short version. I probably wouldn't have understood the long version. 

Closing and reopening the updater doesn't seem to have much effect. After doing so a few times it stops giving the "unable to connect" message and appears stuck with a "updater status: Checking for updates" message that doesn't change for several minutes.
