### ISSUE TITLE
character sheets buggy

### ISSUE THREAD

**Issue by ichpunktpdf** [chummer5a/chummer5a#225]

**Comment by joha4270** [comment]
Okay? 

Take a look at this
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

Then come back.

**Comment by ichpunktpdf** [comment]
I am sorry, I hit the numblock enter by accident... I am still writing on this report ;-)

**Comment by joha4270** [comment]
Makes me happy, you managed to create the worst bug report i had seen so far!

**Comment by ichpunktpdf** [comment]
Well, a dubious honor.... mea culpa ;-)

So, after cross-checking with different characters and all sheets, there are two bugs with the character sheets and limits:

1. Limits don't show up at all on German character sheets.
2. The English character sheets display limit modifiers just for mental limits. Physical and social modifiers are not visible.

**Comment by joha4270** [comment]
Well, the good news is that i know what is causing this more or less. The bad news is that it is in a technology i have no experience in at all. Afraid you won't get a fix from me in the near future, but the other guy might know more about it.

**Comment by ichpunktpdf** [comment]
At least for issue no 1, I had a look into the XSL Sheet "Shadowrun 5 Base". It seems that the whole limit code section is missing in the German sheet, among other improvements...
Skills etc. are printed in German anyway, as long as you use the German translation, even on the English character sheet. Would it then work to open the english XSL, copy it to the German folder and translate all the captions in code?
If there is no obvious reason why that shouldn't work, I would try it.

**Comment by joha4270** [comment]
It should work, and that (maybe slightly more selective copying) was/is
what i would have done to try and fix the issue.

Only problem is the limits of my experience with XSL sheets are that i have
opened one in a text editor and looked at it. My experiences stop there, so
take my words with a grain of salt. If you manage to fix it, please let us
know, as i would love to integrate your fix into the Chummer5 source code
or instruct you on how to do so yourself.

Only thing remaining, Good Luck


2015-06-04 12:46 GMT+02:00 ichpunktpdf <notifications@github.com>:

**Comment by ichpunktpdf** [comment]
I will try that and let you know!

**Comment by chummer5a** [comment]
Eughhhh, XSL. God damn it I was dreading the day that stuff would break.

**Comment by joha4270** [comment]
I'm having the feeling it was always broken and nobody realized it.

I have a dream about one day emulating the herolab sheets (they are prettier), maybe once the issue list is empty (so never)

And sorry ichpunktpdf that i turned into a chat about design.

**Comment by chummer5a** [comment]
That actually wouldn't be that HARD, per se. XSL isn't that bad once you know what you're doing with it, it's just a headfuck to look at. I don't particularly care for how much space the HeroLab sheets waste, but it's definitely doable. Rejuvenating the sheet output has been on my wishlist for a while now, as figuring out manually where you need to put your page breaks is fairly stupid.

**Comment by joha4270** [comment]
>once you know what you're doing with it

Well, here you got my problem

**Comment by rolfman** [comment]
I partially fixed the german character sheet for myself about half a year ago. I fixed only what I needed (attributes, skills, armor, weapons, gear and the compex forms) at the time but if it's helpful to anyone I can do the rest as well of course.

**Comment by chummer5a** [comment]
Hrm, is this still an issue? I'm not sure what's here that's actionable.

**Comment by ichpunktpdf** [comment]
well, the most annoying issue is still that the limit section is not included in the german character sheet. I tried to find that section, but I am not even good enough in coding to figure that out :-)

**Comment by rolfman** [comment]
If I'm not looking at the wrong character sheet it is fixed in the current version. It should be since December last year when I uploaded it, but I might have overlooked something.

Please recheck and if it's still not working post the details and I'll try to fix it ;-)

**Comment by Lochabar** [comment]
I've taken a quick look at the character sheets from release 5.178
The English sheets are in: Release\Sheets
The German sheets are in: Release\Sheets\de

The sheet that prints the character is: Shadowrun 5 Base
I am using Notepad++ as the editor for xslt members.

Copy the "LimitsBlock" (lines 627 thru 707) from the English version after line 566 of the German version. And then make the translations.

Note: Chummer5a uses Release\Sheets as the source of the print controls (at least in the English version). I assume the German versions of the sheets need to replace the the English versions (or copy them to another directory).

I hope this helps.

**Comment by ichpunktpdf** [comment]
Although updates are enabled, I had still the 5.177. Even with a manual check, I am told there were no new updates. However, this is another issue.
After downloading and installing the current version, a quick check returned the same issue. Limits are shown correctly in the english character sheet, but the whole section is missing in the german sheet.
I will try to fix it tonight the way you described, Lochabar.

**Comment by ichpunktpdf** [comment]
Ok, it seems to work now, but there were additional changes to make (and I am really proud of me that I figured it out :-D )

After copying the "LimitsBlock" that Lochabar described to the designated code positions, it returns an error. Another block that is defining templates has to be copied.

English Base sheet: lines 1983 through 2089
In the German sheet (AFTER copying the limit block): after line 1761

Actually, it seems that it doesn't matter much where templates are inserted, but again, I have no idea about coding, doing just the Frankenstein-thing here...

I did no further testing, but at least limits and social modifiers appear on the German sheet now. I will try different combinations of modifiers and characters to see if it is actually solved.

Thx Lochabar, for this is actually your work ;-)

**Comment by ichpunktpdf** [comment]
ok, I checked very quick. It seems that the German sheet works now as good as the English one with respect to limits.
But both have another bug: limitmodifiers, that add automatically in chummer with the gear, are shown correctly on the sheet(s). Manually added modifiers do not appear.
