### ISSUE TITLE
Crash on character load

### ISSUE THREAD

**Issue by Risslock** [chummer5a/chummer5a#2251]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Open a character generate in Chummer5.195.0

### Actual behaviour
Crash when trying to open it

### Steps to reproduce the behaviour
Use the load character option or double click the file if the chummer5.196.0 exe is selected as the default option for .chum5 files.

### Link to affected character file

https://drive.google.com/open?id=0B9pifAlNYamGdEdGSUVnWGV3WjQ

**Comment by chummer5a** [comment]
Can't replicate the crash in current nightly builds.
