### ISSUE TITLE
Crash on Addding Runnerhub Basic Gear PACK

### ISSUE THREAD

**Issue by boggensagg** [chummer5a/chummer5a#2252]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 196.28 nightly
Environment: Win64
Runtime: 4.7

### Expected behaviour
Add Runnerhub Basic Gear Community Pack
Get all gear added

### Actual behaviour
Causes Crash
Removing the vehicle (Nissan Jackrabbit) section from packs.xml fixed issue; all gear is added (except vehicle of course); no crash

### Steps to reproduce the behaviour
Create character
Add PACKS -> Community Packs -> Runnerhub Basic Gear
Enter any value for SIN, Licenses
Crash

### Link to affected character file
n/a

**Comment by chummer5a** [comment]
Can't replicate the crash, but did find some other quirks with the vehicle packs so there's that at least.
