### ISSUE TITLE
Thundercloud Morgan Caused Crash

### ISSUE THREAD

**Issue by oyster450** [chummer5a/chummer5a#2255]
### Environment
Chummer Version: 5.196.0
Environment: Windows 10  Version 1709 for x64-based Systems
Runtime: .NET 4.5.1 (don't know for sure)

### Expected behaviour
While in Creation Mode I tried to add a Thundercloud Morgan (Car) expecting to be able to mod it.

### Actual behaviour
Chummer Crashed (Program froze, Windows began looking for solution then closed chummer, crash report showed up on my desktop in a .txt file)

### Steps to reproduce the behaviour
I've been able to reproduce the crash in any mode
1.Open any Character file
2.Click on the "Vehicles and Drones" Tab
3.Click "Add Vehicle" Button
4. Highlight "Thundercloud Morgan [Cars]" 
5. Click either "Ok" or "Add & More"

### Link to affected character file
I will attach the crash reports
[chummer_crash_131595453693972043.txt](https://github.com/chummer5a/chummer5a/files/1603931/chummer_crash_131595453693972043.txt)
[chummer_crash_131595472904645309.txt](https://github.com/chummer5a/chummer5a/files/1603932/chummer_crash_131595472904645309.txt)
[chummer_crash_131595473549870013.txt](https://github.com/chummer5a/chummer5a/files/1603933/chummer_crash_131595473549870013.txt)
[chummer_crash_131595476670394829.txt](https://github.com/chummer5a/chummer5a/files/1603934/chummer_crash_131595476670394829.txt)
[chummer_crash_131595548743190314.txt](https://github.com/chummer5a/chummer5a/files/1603935/chummer_crash_131595548743190314.txt)
[chummer_crash_131595556955605985.txt](https://github.com/chummer5a/chummer5a/files/1603936/chummer_crash_131595556955605985.txt)
[chummer_crash_131595561551171790.txt](https://github.com/chummer5a/chummer5a/files/1603937/chummer_crash_131595561551171790.txt)

**Comment by DelnarErsike** [comment]
AFAIK, this issue has long been fixed in the Nightly builds. Do you still experience the crash in the latest Nightly?

**Comment by oyster450** [comment]
I don't think I downloaded the Nightly version. I will do that and repost with results.

**Comment by oyster450** [comment]
That did it! I experienced a crash shortly after getting that to work, but I don't know what caused it and it is running fine now. Thanks.
