### ISSUE TITLE
Adepts: Way of Unified Mana

### ISSUE THREAD

**Issue by Mudcookie** [chummer5a/chummer5a#2263]
It is not there.
Will it come?

Book: Forbidden Arcana, Page 101.

**Comment by DelnarErsike** [comment]
Hapsum-Do should be implemented in Chummer5a. Are you sure your character meets the requirements for Hapsum-Do, including the higher-than-usual karma cost required to purchase it?

**Comment by Mudcookie** [comment]
Two Traditions to build a Hybrid Tradition? Yes. If there's another requirement... i don't know? I'm from Germany and my english is not very good :(

**Comment by DelnarErsike** [comment]
Hapsum-Do has the following prerequisites, per Forbidden Arcana: 15 Karma cost, must be an adept or mystic adept. Does your character meet all those prerequisites? If they do not, then it will not be visible.
