### ISSUE TITLE
Mislabeled Quality Location

### ISSUE THREAD

**Issue by TheFenixKnight** [chummer5a/chummer5a#2265]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Win 10 64 bit
Runtime: .NET 4.5.1)

### Expected behaviour
Busted Cyberware is on pg. 30 of The Seattle Gambit

### Actual behaviour
Chummer lists it as P 188 of The Complete Trog

### Steps to reproduce the behaviour
Originally mentioned to me by another player. Confirmed it in on my version.

### Link to affected character file
https://www.dropbox.com/s/wj8lezh024jzsov/Boon%20Douggie.chum5?dl=0

**Comment by chummer5a** [comment]
Implemented in the latest commit. Existing characters will need to remove and re-add the quality for the source to update.
