### ISSUE TITLE
Starting attribute costs are wrong

### ISSUE THREAD

**Issue by Malcoth** [chummer5a/chummer5a#2266]
### Environment
Chummer Version: 5.196.0
Environment: Windows 7 Ultimate (6.1.7601)
Runtime: .NET 4.5.1

### Expected behaviour
A human has all attributes at value 1 as starting value. Category B for attributes gives 20 points, so a valid human character should end up with a total of 28 over all attributes.
Examples can be found in the core rules (p.70 in first printing English, p.68 in fourth printing German), the starting values for any race are free, all points spend are added on top.

### Actual behaviour
Chummer counts the starting value 1 as a spend point already, so to produce a legal character, you need to have an attribute point total of 20, not 28.

### Steps to reproduce the behaviour
Create a character with priorities.

**Comment by DelnarErsike** [comment]
I cannot replicate the issue in the Nightly build. Can you give it a try?

**Comment by Malcoth** [comment]
You can close this one. I've no idea how I got that knot into my brain, but I cannot even reproduce the problem with the normal version, and of course, neither with the nightly. Sorry to waste your time!
