### ISSUE TITLE
Custom Fit (stack) not working

### ISSUE THREAD

**Issue by Slightlylyons** [chummer5a/chummer5a#2276]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows 8 64bit/ Windows 10 64bit
Runtime: .NET 4.5.1

### Expected behaviour
Armor with the Custom Fit (Stack) should add to a base armor selected from a drop down box

### Actual behaviour
Chummer uses the higher of the two base armor values and ignores the other, as with armor that does not have the quality.

### Steps to reproduce the behaviour
Add armor that should stack with the Custom Fit (Stack) quality to charictor as per normal

### Link to affected character file
[spector.zip](https://github.com/chummer5a/chummer5a/files/1613212/spector.zip)

**Comment by chummer5a** [comment]
Resolved in current nightly builds.

**Comment by Slightlylyons** [comment]
Oh, thank you. I did search for a report must have missed it.
