### ISSUE TITLE
Translator Rebuild replacing already translated content

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2279]
### Environment
Chummer Version: 5.196.38

### Actual behaviour
The following translation in the main `<categories>` (not the `<modcategories>`) is always getting replaced when rebuilding:
```
      <category translate="Body">Body</category>
      <category translate="Cosmetic">Cosmetic</category>
      <category translate="Electromagnetic">Electromagnetic</category>
      <category translate="Model-Specific">Model-Specific</category>
      <category translate="Powertrain">Powertrain</category>
      <category translate="Protection">Protection</category>
      <category translate="Vehicle Weapon Mount">Vehicle Weapon Mount</category>
      <category translate="Weapons">Weapons</category>
```

Also  the `<altpage>` (that contains tootips) from the `<improvements>` is also getting replaced.

**Comment by DelnarErsike** [comment]
Fixed the issue with `vehicles.xml` modcategories strings in latest commit, but could not replicate the issue where `<altpage>` nodes in `<improvements>` translations were getting replaced on a rebuild. Could you provide an example translation where this occurs?

**Comment by luizbgomide** [comment]
I tried it again and it didn't work, it might have happened in a previous nightly. I translated those 1 month ago and just noticed that the translation disapeared when I opened this issue. This might have been corrected already.
