### ISSUE TITLE
Can't reduce MAG to zero at chargen

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#2283]
### Environment
Chummer Version: 5.196.32
Environment: Windows 10
Runtime: Unknown

### Expected behaviour
Burning out an awakened (adept) character for more essence than their magic should reduce their MAG to 0. At chargen, it should be possible to reduce the SPECIAL ATTRIBUTE points spent on MAG to 0, and then buy it back up to a positive number using karma.

### Actual behaviour
The SPECIAL ATTRIBUTE points is stuck at 1, causing unwanted behavior. See the attached picture:

https://imgur.com/a/nCrUp

### Steps to reproduce the behaviour
Create an awakened (adept) character, and reduce their essence by more than their MAG score with an essence hole. Observe that the SPECIAL ATTRIBUTE expenditure is frozen at 1 for the MAG attribute.

**Comment by chummer5a** [comment]
Known issue, looking into it.
