### ISSUE TITLE
The Magicians Way

### ISSUE THREAD

**Issue by Seeron** [chummer5a/chummer5a#2285]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0
Environment: Windows
Runtime:  .NET 4.5.1

### Expected behaviour
The Magician's Way (Street Grimoire p.178) provides a pp cost reduction for up to MAG/2 powers. That reduction can be chosen for any power except Improved Reflexes. 

### Actual behaviour
The reduction cannot be chosen for powers with a cost of 1 pp (e.g. Astral Perception) 

### Steps to reproduce the behaviour
1. Create a Adept or Mystic Adept
2. Select The Magician's Way as a positive Quality
3. Select Astral Perception as an Adept Power
4. Checkbox for Adept's Way is not there

### Link to affected character file

https://www.file-upload.net/download-12915469/MagiciansWay.chum5.html

**Comment by Seeron** [comment]
![image](https://user-images.githubusercontent.com/7631929/34828666-947c7aa6-f6de-11e7-9fad-52e4eb6b0bdf.png)

still persists in new nightly build for some powers (see screenshot)

**Comment by chummer5a** [comment]
Missing null check, will work properly in the next build.
