### ISSUE TITLE
Crash on deleting line item from Karma/Nuyen in Career Mode

### ISSUE THREAD

**Issue by voodoooodoov** [chummer5a/chummer5a#2287]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.0.0
Environment: Windows 10
Runtime:  v4 says 4.7.02556.  v4.0 says 4.0.0.0.  Both in Client.

### Expected behaviour
Career Mode: Tab "Karma and Nuyen".  Select an item in either column (Karma or Nuyen) that is not at the top, right click, select "Undo Expense". Item gets deleted, and its "cost" is positively added back to relevant total (undone).

### Actual behaviour
Attempt the above action and get a spinning mouse pointer, Chummer crashes with a generic error that it needs to be closed and (supposedly) sends an error issue to Microsoft.  Creates an error log on the desktop BUT the log is basically empty besides generic message, "This file contains information on a crash report for Chummer5A. You can safely delete this file, but a developer might want to look at it"

Restart appears fine, though item attempted to be deleted is still present.

### Steps to reproduce the behaviour
Open character (already in Career Mode).  Go to Gear and add/buy a weapon focus R2 (don't know if it has anything to do with focus...).  Check box to bond focus, accept cost.  Go to "Karma and Nuyen" tab.  Select Nuyen column item for the just purchased focus: change its date to one month prior.  Select another tab: do some function there/change something/activate something.  Return to K&N column, right click on the recently added focus item, select "Undo Expense", agree to continue the process.  Error pops up about "Chummer has stopped working" and Chummer 5a crashes.  Reopen Chummer and attempt to delete item again: crash.

### Link to affected character file
[Pandora - Missions.zip](https://github.com/chummer5a/chummer5a/files/1620486/Pandora.-.Missions.zip)

**Comment by chummer5a** [comment]
Can't replicate this in current nightly builds.
