### ISSUE TITLE
Enhanced articulation mistakenly asks for skill to affect

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#229]
1. Create a new character
2. Add bioware "Enhanced articulation".

Expected: Just adds the bioware (giving +1 dice pool modifier to your Escape Artist skill and a +1 increase to your Physical limit).
What happens: Asks for a skill to affect, giving +1 to the selected skill (but only if that skill has a rating of 2 or higher, for whatever reason). No limit modifier.

**Comment by chummer5a** [comment]
Known issue, fixed in 5.167.
