### ISSUE TITLE
Can't create a new Character

### ISSUE THREAD

**Issue by Mudcookie** [chummer5a/chummer5a#2295]
### Environment
Chummer Version: 5.196.43
Environment: Windows 10
Runtime: dunno

Actually i can't create any new Character. It's possible to save a new Character, but if i try to load it, Chummer crashes every Time.

**Comment by chummer5a** [comment]
How are you opening the character? Does it work properly if the character is a metavariant? I think you may have been affected by a bug that's been fixed in the latest commit and will be in the next nightly build.

**Comment by Mudcookie** [comment]
Shortcut on Desktop and the Roster. Metavariant doesn't matter, it crushes.

**Comment by Mudcookie** [comment]
Trying to add a Weapon... Crush. Trying to add Adept skills...Crush. Trying to add a Car....Crush.

**Comment by chummer5a** [comment]
When it crashes, the crash handler should be creating a file on your desktop that includes the exception data. If you can find that, please upload it here.

**Comment by Mudcookie** [comment]
It seems to be fixed now. Thank you. By the way, could it be that there are no throwing weapons?
