### ISSUE TITLE
Wrong category for spell from "Forbidden Arcana"

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2299]
### Environment
Chummer Version: 5.196.42
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
The spell "Growth" from the book "Forbidden Arcana" (FA) is categorized as "Manipulation" in the data files (spells.xml).
If I translated that spell name correctly to German ("Wachstum", which was the only spell left after translating all other spells from that book), it is listed with category "Health" in the German rule book.

So, either the German book is wrong or contains an errata, or the spell is assigned to the wrong category in the data file.

**Comment by chummer5a** [comment]
Says Manipulation in the English version.
