### ISSUE TITLE
Clicking the "Armor" column heading should sort by armor, not give a set of clothes

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2303]
### Environment
Chummer Version: 5.196.45
Environment: Windows 10 64bit
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When purchasing armour, if I click on the Browse tab, then click on the Armor column heading, it should sort by armour value (just like it does for capacity or special).

### Actual behaviour
 When clicking on the armor column heading, it closes that window and brings up the clothing value box as if I had just opted to get a set of clothes.

Note, the column header sorts seem to be erratic:
Clicking on the Armor column always gets a new set of clothing.
Clicking on any of the other columns usually gets a new set of clothing, but not always.
When I initially went into this screen and tried it out, the first few times I clicked on Capacity it reliably sorted by capacity, and specials did the same. But after clicking back and forth between the two a couple times, and now clicking on either one of them always gets a new set of clothing. (Secondary note: This is going back into the add armor screen repeatedly to test this. I haven't reloaded Chummer yet)

The exception to this is that sorting by cost then sorting by source reliably gives my character a form fitting shirt (2050)

### Steps to reproduce the behaviour
Create new character
Add armor, switch to the browse screen and try to sort by armor. On the off chance that does actually work (which is rare), click on a few of the other headers. Within a couple sorts it should just auto-buy a set of armor.

**Comment by Zitchas** [comment]
Possibly related to bug #1960 that was closed back in October

**Comment by chummer5a** [comment]
Huh. That's odd. Shouldn't be a problem to fix, will probably be something shenanigansy with a create method.
