### ISSUE TITLE
The components of Survival Kit, Survival Knife etc. are not correctly displayed in German

### ISSUE THREAD

**Issue by FelixDombek** [chummer5a/chummer5a#2309]
### Environment
Chummer Version: 5.196.0
Environment: Win 10
Runtime: .NET 4.7.1

### Expected behaviour
The names of sub-components of compound items are displayed as their child elements.

### Actual behaviour
The German version just says "Eigener Gegenstand" (Custom Item) for each of them.

### Steps to reproduce the behaviour
Add a Survival Kit to a character. Change to German language. 
(The order doesn't matter and the names are displayed correctly again after another change to English)

By the way, there is also a little translation error directly above the "Foci" list, in the "bound Foci" string: Foci -> Foki in German.

**Comment by FelixDombek** [comment]
Thanks for addressing this; I just wanted to note that this same issue is (still) true for most Commlink functionalities (all those which do not belong to audio or visual device class).

**Comment by DelnarErsike** [comment]
Everything either has its own gear entry now or has an entry where TranslateExtra will be able to pick it up. I can't do the translations myself, but once someone does, those items will all get translated properly.

**Comment by FelixDombek** [comment]
I just might be confused. Shouldn't the non-translated sub-items of Survival Kit, Survival Knife, Commlinks etc. just show their English name if the translation isn't available yet? Because they still all say "Eigener Gegenstand" for me in the newest version.
