### ISSUE TITLE
Advanced lifestyle with roommates cost

### ISSUE THREAD

**Issue by Bercelak** [chummer5a/chummer5a#231]
When in character creation (Priority Generation, non-troll metatype), adding an advanced lifestyle and then increasing the number of roommates (I've tested different amounts ranging from 1 to 5 and the problem persists), no matter the level of the lifestyle (bolt hole to luxury), the cost correctly increases by 10% in the "Build Lifestyle" window. All is well until I finalize and add the lifestyle to the character by clicking "OK". Chummer records the cost completely different than what was viewed in the "Build Lifestyle" window and deducts this from the character's nuyen, adding on anywhere from 50-100% more to the proper cost.

I haven't tried this with the troll metatype, since they have their own rules for lifestyles. I did attempt to dig through the code related to lifestyles in an attempt to discern whether an equation simply needed to be modified, but the equations I did find (in the frmSelectLifestyleAdvanced.cs file) looked correct. Though I don't know much about the project as a whole, I assume the calculation must err somewhere else, especially since the amount Chummer adds onto the cost varies.

**Comment by chummer5a** [comment]
Hrm. I think I know what's going on; I'll take a proper look tonight and
sort it out.

**Comment by chummer5a** [comment]
Got stealth-fixed a while back from memory, definitely working properly in 5.173.
