### ISSUE TITLE
Black Market Pipeline not functioning upon reload

### ISSUE THREAD

**Issue by Kazhel** [chummer5a/chummer5a#2313]
### Environment
Chummer Version: 5.196.0.0
Environment: Windows 8.1
Runtime: probably .NET 4.5.1

### Expected behaviour
Black Market Pipeline quality discount should stay applied upon reopening a character

### Actual behaviour
The quality only works in one continous working session on the character. Then gear can be bought with the box for the discount available (although mods and plugins are never discountable, which is probably a mistake in itself) and also reducing the Nuyen spent by the appropriate amount. After saving and reloading the character later, the quality doesn't apply anymore, gear previously bought with the discount is retroactively back to the normal price (and Nuyen difference subtracted from the funds) and upon buying new gear, the box for the discount doesn't show up anymore.

### Steps to reproduce the behaviour
Create a character with the quality, buy things while ticking the appropriate box for the discount. Save the character, close Chummer, reopen the character.

### Link to affected character file
[Fiedler.zip](https://github.com/chummer5a/chummer5a/files/1632765/Fiedler.zip)

**Comment by chummer5a** [comment]
Fixed in current nightly builds.
