### ISSUE TITLE
Chummer slow when adding new Contacts. Not running Windows Defender

### ISSUE THREAD

**Issue by kanehorus** [chummer5a/chummer5a#232]
On my desktop, there is a problem. Chumer lags immensely when I'm trying to update contacts. As in, freezes for a good 30-50 seconds when I'm trying to type in the name of a contact. There are other lags for updating karma and nuyen costs, along with raising skills.

I do not run Windows Defender (Spybot and AVG) on my computer, and I have created exceptions for Chummer 5a on both anti-virus programs. Have also attempted a fix by running as an administrator. Doesn't work either.

Hope to hear from you soon.

**Comment by joha4270** [comment]
Are you by any chance having logging enabled?

**Comment by joha4270** [comment]
Issue closed due as being non reproducible.
