### ISSUE TITLE
Note grabber doesn't work

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#2322]
### Environment
Chummer Version: 5.197.1

### Expected behaviour
When creating a quality, Chummer will fetch the relevant text from a linked PDF.

### Actual behaviour
While text from the page is fetched properly, it doesn't seem to iterate properly. Should be something in  lines 1375 - 1390 of the GetTextFromPDF method in clsCommon.cs.

**Comment by DelnarErsike** [comment]
Update on the issue: the note fetching works again, but there's something wrong with PdfTextExtractor. If you check a quality that has its description split across multiple pages (e.g. Records on File), you'll find that the PdfTextExtractor.GetTextFromPage() call actually fetches the same page as before even though intPage has increased by 1.
