### ISSUE TITLE
options window non scaleable/ fixed size on notebooks

### ISSUE THREAD

**Issue by whug** [chummer5a/chummer5a#2326]
### Environment
Chummer Version: 5.196 + 5.197
Environment: windows 7
Runtime: .NET 4.5.1

### Actual behaviour
using chummer on my acer inspire note book , i cannot confirm my options selection by clicking on the ok button, because the portion of the options window is 'off screen' on smaller screens and i cannot move the window around to access that portion of the window

### Steps to reproduce the behaviour
open options tab on chummer whilst using a notebook or other device that has a small screen.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
`frmOptions` has a minimum height of 667 pixels, which is smaller than the minimum height of the Chummer5a main window (752 pixels) and the Career and Create screens (761 pixels). The targeted minimum resolution so far has been 1024x768 pixels, which has been a "safe" minimum resolution for computer monitors for about 20 years now; it covers >99.99% of Steam users and about 99.21% of web users (the 0.79% that wouldn't be covered are almost all mobile users). How small is your screen?

Note that the options screen is getting a refresh soon-ish courtesy of joha4270. You may want to bring attention to this enhancement once that refresh gets implemented.

**Comment by chummer5a** [comment]
Duplicates #1080, mostly implemented already.
