### ISSUE TITLE
Proposal to have a string correctly identifying "talent qualities" in the book

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2329]
As it is, when checking for "qualities" like Aspected Magician or Adept using the GetTextFromPDF if fails to find the complete name as the books uses plural for those (Aspected Magicians, Adepts, etc).
I propose that those talents have another field containing the full name as used in the book (being it plural or otherwise).
This way the match would be more correct and will also accommodate translations where the plural of some words mangle the singular (this is true with composite words in Portuguese and many cases in German) making it impossible for it to be found.
I'm not sure if it is best to use another string for it, or a inner tag inside the definition (this tag being translatable also).

**Comment by DelnarErsike** [comment]
Closing this issue, as discussion of this topic is now covered by #2414.
