### ISSUE TITLE
Exception with "Net" as weapon.

### ISSUE THREAD

**Issue by angelforest** [chummer5a/chummer5a#233]
Make new character, open "Gear" tab, add "Net" from "Ammunition" category, switch to "Weapons" tab, select "Net"... Exception "Expression must evaluate to a node-set". Guess it lacks some stats expected from weapon.

**Comment by chummer5a** [comment]
Ranges method doesn't expect that you'll try to divide it by anything. Changing the math to STR*0.5 makes it process as normal. Fixed in 5.168.
