### ISSUE TITLE
Medkits have consumable charges

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#2330]
### Environment
Chummer Version: 5.197

### Expected behaviour
Bullets and Bandages provides expanded rules for medkits having limited uses before requiring restocking. Ideal behaviour would be to enhance the Gear system to support something similar to the Ammo system for weapons; you'd have a Use button that would decrement the linked object and a Purchase button to quickly purchase more.

**Comment by Mr-J** [comment]
Base rules also have rules for medkit charges. Basic rule is medkit level = number of charge before refilling needed.

**Comment by Lochabar** [comment]
It's possible to do this already.
![medkit supplies](https://user-images.githubusercontent.com/17562417/35189927-776645d4-fe4d-11e7-8271-b131cd3660fd.png)

1) In Street Gear purchase the appropriate number of medkit supplies.
2) Drag the supplies onto the medkit. (If necessary rt-click and drag.)
3) When you use the medkit click the "-" button.

**Comment by chummer5a** [comment]
Honestly the only real change here is that I need to implement something so that child items can have a quantity based on the rating of the parent.

Sent from my Windows 10 phone
