### ISSUE TITLE
No dropdown menu option to bulk-add contacts

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2340]
### Environment
Chummer Version: 5.197.2
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
From the release notes of 5.197 for enhancement request #2096 :
"Added a dropdown menu option to bulk-add contacts, enemies and pets from a given XML file. To use this, create an XML file that contains valid contacts from an existing Chummer file, or alter this template: https://pastebin.com/W9q8jEnt Note that this system is designed to import ALL valid contacts in the file, irrespective of whether you click on Contacts or Enemies."

So it should be possible to use a drop-down menu to bulk import contacts.

### Actual behaviour
There is no obvious drop down menu to do this.

**Comment by DelnarErsike** [comment]
![righthere](https://user-images.githubusercontent.com/727731/35105033-e75099ce-fc6a-11e7-807c-0ab65be30b82.png)

Admittedly, the User Experience could use some improvement, but the option is definitely there and it's definitely functional.

**Comment by Lochabar** [comment]
Is this because my character is in career mode?
Your screen print appears to be from a character in create mode (it show free contact points remaining).
