### ISSUE TITLE
Knowledge Skills

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2341]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Just updated to Build 197
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Entered my chosen Knowledge Skills

### Actual behaviour
At character generation, Knowledge Skills were added but would not add any points to raise them, it did, however, subtract a starting skill point for specializations.

### Steps to reproduce the behaviour
Rebooted program and tried another new character with same results.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
You just missed it, the issue was fixed less than an hour ago in commit 6a1e6cd35a2363db825e74417f86eeec5b160498 and it should be present in the next nightly.
