### ISSUE TITLE
Chummer crashes when moving character to career mode

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2343]
### Environment
Chummer Version: 5.197.3
Environment: Windows 10 64
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
After checking the "career mode" box and saving, it should switch to career mode.

### Actual behaviour
After checking the career mode box and saving, Chummer crashes.

### Steps to reproduce the behaviour
Create character, do the above to move to career mode. 

I've tried using brand new characters as well as older (196.47) characters.
I just tried with the blandest of boring characters (karma mode, human, max ability scores, then spend remaining karma maxing out a few skills. No gear, no qualities) and it still did the same thing.

For what it is worth, it seems to crash after saving the character, although trying to open said character crashes Chummer as well.

I have uploaded a zip file with that corrupted character file in it.

[chummer_crash_131608048877592733.txt](https://github.com/chummer5a/chummer5a/files/1645184/chummer_crash_131608048877592733.txt)

[testing crash career conversion.zip](https://github.com/chummer5a/chummer5a/files/1645185/testing.crash.career.conversion.zip)

**Comment by Zitchas** [comment]
![career mode crash](https://user-images.githubusercontent.com/32169904/35133115-afb3e43c-fc8b-11e7-8d30-829063789844.png)

**Comment by chummer5a** [comment]
I believe this was resolved in the latest commit.

**Comment by Zitchas** [comment]
Yes, this appears to be closed. I can open the characters that crashed during the transition to career mode, as well as create new characters and transfer them to career mode as well.
