### ISSUE TITLE
Can't add bioware after geneware

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2346]
### Environment
Chummer Version: 5.197.3
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
After adding geneware (bioware), i.e. Adapsin/Masque, you can add normal Bioware

### Actual behaviour
After adding geneware (bioware), i.e. Adapsin/Masque, you can no longer select a grade for further bioware and thus no longer add it
-> picture: 
![Problem](https://user-images.githubusercontent.com/23245979/35140589-1f782262-fcf8-11e7-9a70-3c0a0199c288.png)

### Steps to reproduce the behaviour
Create character, add Adapsin or Masque (the 2 I had/added), try to add "normal" Bioware, i.e. Cerebral Booster, look at grade window, try to click add

**Comment by chummer5a** [comment]
Can't reproduce it; does toggling the option for hiding banned grades change anything?

**Comment by Sturmkind** [comment]
I just downloaded a fresh version of the latest nightly build and only enabled Run Faster and Chrome Flesh as sources.
Created a new character, added Restricted Gear, added Adapsin, voilà same problem...
As soon as I delete Adapsin everything works as normal again, but once it's added...  no more bioware for you

**Comment by chummer5a** [comment]
Aha, found the problem.
