### ISSUE TITLE
Enhancement Ideas: Matrix Actions, display poolmodifier seperately & a more detailed calendar

### ISSUE THREAD

**Issue by Nobnobb** [chummer5a/chummer5a#2349]
### Environment
Chummer Version: 5.197.4
Environment: Windows 10 64 Bit
Runtime: .NET 4.5.1

### Proposal 1: Add Matrix Actions
Given that more or less all regular matrix actions, like Edit File, Change Icon, Control Device etc. are available to pretty much every commlink or similar device that's connected to the matrix it'd be amazing to have those relatively simple actions added to chummer and displayable on the character sheet. It's of course especially useful for Deckers and Technomancers, but at least those actions that come with a regular dice roll would be great to have displayed in chummer and printable for regular use; especially since you can easily manipulate the values based on bonuses which you then have to calculate yourself.

### Proposal 2: Display poolmodifiers seperately
As it is now, chummer correctly calculates by far most of the modifications you put on your character automatically, which leads to many players relying on it being correct. However, some modifications do not go in correctly or are bound to certain situations in order to happen at all (which is exactly how it should be, too): For example some cyberarms add a modifier to the usage of pistols, which is not added to the actual dice pool for that pistol, or tailored pheromones which not only adds a limit bonus, but also a modifier for social skills in general, when turned on. Same goes for pool modifications that happen through items, e.g. medkits on your First Aid skill.
It would be amazing to have a seperate list of what modifies what pool in what way somewhere in chummer, so that you can simply double-check if a certain specification is a) working or b) needs to be watched on seperately, as it does not add a bonus at all times. Just like it's already implemented for limit modifications when you hover over it, it'd be great to have it for skill and attribute pool modifiers in general to keep track of what's going on.

### Proposal 3: A more detailed calender
My group makes heavy use of calendars in order to properly keep track of everything that goes on or will go on. The built-in calender for chummer however only displays weeks and you can merely add notes. That works fine in general, as you can simply add the days itself in the note and say what happens there, however makes it harder to keep track of what's going on or will going on, as you also have to make sure you're in the correct week and don't mix up the days - or, simply said, you got to make sure your formatting is adequate.
It'd be great if this could be modified into a proper day-based calender, switchable from months to month, which each day having his own small note, where you can elaborate what happened/will happen in proper format. That'd make it a lot less bulky than squeezing everything in one week if you do a lot of stuff in that week.

Thanks for the amazing work!

**Comment by chummer5a** [comment]
Matrix Action list is a good idea, I'll see what I can do about it. 
With regard to stuff like Pheromones, I preferred to err on the side of not including things that are toggleable or don't always apply. Implementign something for Conditional dicepool bonuses shouldn't be a large problem. 
Calendar's an in-progress item that I keep procrastinating on; it mostly works, but I need to implement a bit more UI logic to make fancy stuff happen and hook up an API so that the rest of the application can access it. My major thought at the moment is how to handle the divide between player and character calendar items. Should they be separate calendars, should they just be different coloured items, should a single calendar item be linked to both calendars, etc.

**Comment by Nobnobb** [comment]
Sounds wonderful. For the toggleable stuff, might it be possible to simply add a note, similar to how it works on limit modifiers already? No need to calculate everything when it's not permanently on, but something like (adds +X if Y) or simply (sometimes +X) would already do the job to make sure people don't forget about it.

**Comment by Mezilsa** [comment]
The idea with a dedicated sheet for matrix actions sounds lovely.
