### ISSUE TITLE
Crash when trying to change priorities

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2353]
### Environment
Chummer Version: Nightly-v5.197.4

### Actual behaviour
Crash when using the menu item Change Selected Priorities

### Steps to reproduce the behaviour
Create a new character using Priority as build mode and using the default choices and  the priority. After it is done, try to the change the priorities.

**Comment by DelnarErsike** [comment]
Cannot replicate in the dev build. It's possible the issue has already been fixed in a commit since the nightly release.

**Comment by luizbgomide** [comment]
I made this compiling from the current state. From the time that I posted this.
