### ISSUE TITLE
Is the number of free Complex Forms for technomancers wrong?

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2354]
As it is on Chummer A gives 7, B gives 5 and C gives 3.
According to the core book (p65) it should be A: 5, B: 2 and C: 1.

Am I missing something or is there an errata?

**Comment by DelnarErsike** [comment]
The latest batch of official errata for the core rulebook altered Technomancer entries for Special priorities. You can check the official forums for more details.

**Comment by luizbgomide** [comment]
Thanks, didn't know that. But according to that errata the B priority should give 4 complex forms and not 5.
