### ISSUE TITLE
Cyber costs the wrong essence

### ISSUE THREAD

**Issue by modsec** [chummer5a/chummer5a#2356]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.5
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
I expect my combined, with biocompatability, Cyberware to cost 3.8 essence.

### Actual behaviour
It actually costs 4.62 Essence.

### Steps to reproduce the behaviour
Create a character with Biocompatability (Cyberware), 2 Obvious Full Arms, 4 Obvious Lower Arms, 2 Obvious Lower Legs and a Partial Cyber Skull all at Standard Grade.

### Link to affected character file
This is the effected Character File
https://drive.google.com/open?id=1h4nX8TCGqqnkyR2e-7-o4YpnpR5wi37x

**Comment by DelnarErsike** [comment]
I don't see why you're expecting your 'ware to cost 3.8 essence.

Even without taking into account weirdness about rounding, the cost of 2 obvious full arms + a partial cyberskull, all with a -10% essence reduction from biocompatibility, would definitely be 2.16. If you would expect everything to cost 3.8 essence in total, then that'd mean your 6 obvious partial cyberlimbs would need to total up to an essence cost of 1.64... however, 1.64 is not cleanly divisible by 6, so no matter how you'd consider the rounding weirdness around essence costs, there's no mathematical way for that to happen.
