### ISSUE TITLE
Some special weapons not using pistol skill (as is RAW)

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2359]
### Environment
Chummer Version: 5.197.4
Environment: Windows 7
Runtime: 4.7

### Expected behaviour
The Parashield Dart Pistol and the Ares Super Squirt should work with the normal pistol skill instead of forcing an exotic ranged weapon skill.
Same goes for the Parashield Dart Rifle using the rifles skill instead of exotic ranged weapon.

### Actual behaviour
They all force you to learn a seperate exotic ranged weapon skill which is contrary to what the base rules say.

### Steps to reproduce the behaviour
Add one to a character and look at the dice pool being 0 without the seperate exotic skill.

###Added screenshots of the german base rulebook.
![aressquirtskill](https://user-images.githubusercontent.com/27777147/35183601-3f725ce4-fde9-11e7-834c-85aa796b6dbe.PNG)
![parashieldpistolskill](https://user-images.githubusercontent.com/27777147/35183603-45841a50-fde9-11e7-9aa9-2e6def52b28f.PNG)
![parashieldrifleskill](https://user-images.githubusercontent.com/27777147/35183605-4a3e5128-fde9-11e7-9109-63ed5d4f50a0.PNG)

**Comment by chummer5a** [comment]
In the English version it just specifies that they use particular ranges; can you provide a translation of the text?

**Comment by MaraFaye** [comment]
The keywords in the german text are "Pistole" for pistols and "Gewehre" for rifles.

I don't have an english rulebook at hand, so all I can offer is self made translations.

German original: Die Super Squirt wird mit der Fertigkeit Pistolen abgefeuert, verwendet
die Reichweiten für Leichte Pistolen und kann auf- und unterlaufmontiertes
Zubehör aufnehmen.
Rough translation: The Super Squirt is fired with the pistols skill, uses the range for light pistols and can mount over- and underbarrel accessories.

Parashield Dart Pistol:
Sie wird mit der Fertigkeit Pistolen abgefeuert, verwendet die Reichweiten für Schwere Pistolen und kann aufmontiertes Zubehör aufnehmen.

It's fired with the pistol skill, uses the range for heavy pistols and can mount overbarrel accessories.

Parashield Dart Rifle:
Das Parashield Pfeilgewehr wird mit der Fertigkeit Gewehre abgefeuert, verwendet die Reichweiten für Sturmgewehre und kann auf- und unterlaufmontiertes Zubehör aufnehmen.

The Parashield DartRifle is fired with the rifle skill, uses the range for assault rifles and can mount over- and underbarrel accessories.

Translations of the last sentence in the screenshot, specifying the skill and range used for each weapon.

**Comment by MaraFaye** [comment]
Any comment or is this already forgotten?

**Comment by DelnarErsike** [comment]
The issue was closed because a pre-built custom ruleset has been added that implements this, even if it is not the default behavior of Chummer5a. You can enable it just like any custom data directory, through the Optional Rules tab in the Options screen.

**Comment by MaraFaye** [comment]
Oh, okay, thanks then,
