### ISSUE TITLE
Contacts during Chargen: Karma not being applied properly

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#236]
Basically I was checking a friend's sheet in build 166 and she is shown to be over by 4 contact points. The program does not compensate automatically by applying Karma. A quick search for Contacts didn't bring up anything relevant 

https://drive.google.com/file/d/0Bwu-ssbXNGYMb2hUZ0lUV2ViWkE/view?usp=sharing

^link to the relevent character file so you can try to replicate on your end. Perhaps its just an issue with the sheet itself or the program? I have no clue. Anyway cheers thanks for the quick response to the last issue.

**Comment by joha4270** [comment]
Probably an issue with the program, as i can replicate the issue in 166 but not the development version. Not surprising as there was some "interesting" code related to contacts before i started messing with it.
