### ISSUE TITLE
Vehicle Deletion

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2360]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Latest nightly
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Added vehicle and changed my mind about it, but...

### Actual behaviour
Can't delete vehicles or accessories to vehicles

### Steps to reproduce the behaviour
Tried on multiple characters

### Link to affected character file
(Enter text here)

**Comment by MaraFaye** [comment]
Can confirm that, I think it has to do with there suddenly being a "Selected Vehicles" rider at the top, which you can delete, getting rid of all vehicles, but at the same time crashing chummer.
![vehicledeletebug1](https://user-images.githubusercontent.com/27777147/35187533-89e441d4-fe25-11e7-97ba-fb1826cde75a.PNG)
![vehicledeletebug2](https://user-images.githubusercontent.com/27777147/35187534-8fa93eee-fe25-11e7-8558-228f67d5a251.PNG)
