### ISSUE TITLE
#Bug: Silencer not available for Shotgun

### ISSUE THREAD

**Issue by Mr-J** [chummer5a/chummer5a#2363]
### Environment
Chummer Version: 5.197.1.0
Environment: Windows 10
Runtime: .NET Framework 4.7.1

### Expected behaviour
Silencer can be added to Shotgun shooting solid Slugs

### Actual behaviour
Silencers can't be added to Shotgun

### Steps to reproduce the behaviour
1. Create Character
2. Add Enfield AS-7 Shotgun to Weapons
3. Select "Add Accessory"
-> Silencer not available in accessory list

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Not a bug, shotguns and revolvers aren't allowed to have silencers per the Silencer entry.
