### ISSUE TITLE
Wrong Weapon Stats

### ISSUE THREAD

**Issue by Mr-J** [chummer5a/chummer5a#2366]
### Environment
Chummer Version: 5.197.1.0
Environment: Windows 10
Runtime: .NET Framework 4.7.1

### Expected behaviour
Crossbows should have ammo 4(m) according to core rulebook.
Recoil compensation for HK G12A4 should be 3(4).
Ranger Silver Crossbow name has a typo (should be "Sliver" instead of "Silver").
Ranger Sliver Crossbow should have ammo 4(m) similar to other crossbows (no explicit rules for given in Run & Gun, so i assume it follows the rules for all crossbows)

### Actual behaviour
Crossbows listed with ammo 4
Recoil compensaion for HK G12A4 is listed with Base (3) which is wrong. Weapon has no base recoil compensation, only Gasvent II + Foregrip for 3 point and a folding stock for additional 1 when extended.
Ranger [Sliver] Crossbow is listed as Ranger [Silver] Crossbow
Ranger Sliver ammo is listed with 5(m)

### Steps to reproduce the behaviour
No steps needed, just number/typo errors

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
The Ranger Sliver is listed with Ammo of '-' so I'm assuming it has to be reloaded after each shot, same as bows. Probably needs an errata comment on it at some point.

**Comment by Mr-J** [comment]
Other Crossbows are also listed with Ammo of '-' in the german version of Run & Gun but are stated as having an internal magazine with 4(m) in core rulebook, so i assume the pistol crossbow follows the same rule.

**Comment by chummer5a** [comment]
I've added an amend file to provide that behaviour, you can enable it from the optional rules section of the Settings menu.
