### ISSUE TITLE
Karma can be used to raise skills above maximum during chargen

### ISSUE THREAD

**Issue by joha4270** [chummer5a/chummer5a#237]
**How to reproduce**

Make a new character with any generation method, go to skill tab, increase karma spent on a skill to above 6

Unknown if the final check disallows this or catches it.

**Suspected cause**
Karma spent on skill in SkillControl.cs not checking if it exceeds a maximum

**Suggested fix**
during OnValueChanged in either nudKarma or nudAttribute do the following
nudKarma.Max = Skill.max - nudAttribute.Value;

**Comment by chummer5a** [comment]
Fixed in 5.167.
