### ISSUE TITLE
List of selected books is ignored

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2380]
### Environment
Chummer Version: 5.197.8
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Show only the content of selected books.

### Actual behaviour
In Chummer5a only the core rulebook and the corresponding German-exclusive extension are enabled.
The dialog to select equipment shows all equipments from all books.
Same is true for dialogs to add weapons or armor.

### Steps to reproduce the behaviour
Ensure that only the core rulebook is selected.
Create a new character or open an existing one.
Open dialog to add an equipment.

**Comment by DelinquentPanda** [comment]
I'm also having a similar problem windows 7 as well
