### ISSUE TITLE
Crash on adding connection

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2381]
### Environment
Chummer Version: 5.197.8
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
No crash.

### Actual behaviour
Chummer5a crashes when trying to add a new connection.
The same happens when opening the "Relationships" tab of an existing character with connection.

### Steps to reproduce the behaviour
Create new character and try to add a new connection.

**Comment by stephanstross** [comment]
Can confirm. I get the same error on the latest nightly build.

**Comment by DelnarErsike** [comment]
The regression has been fixed in commit 48b738b03e1b762b35d373e86c83b071a9ce19a5.
