### ISSUE TITLE
Inactive rulebooks still showing their content

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2383]
### Environment
Chummer Version: 5.17.8
Environment: Win7
Runtime: 4.7

### Expected behaviour
Chummer should only show contents related to selected rulebooks under the options menu.

### Actual behaviour
It shows content from inactive rulebooks like the antenna grill under cyberware or the F-B Bumblebee when the corresponding rulebooks are not selected as active.

### Steps to reproduce the behaviour
So far, just go into a character and try to find the items while the rulebooks they belong to are disabled.

### Link to affected character file
![activebooks](https://user-images.githubusercontent.com/27777147/35278445-5c58af6c-004a-11e8-89ba-5ffed63e95b5.PNG)
![rulebug](https://user-images.githubusercontent.com/27777147/35278358-06e82eea-004a-11e8-81e2-557940008725.PNG)

**Comment by Zitchas** [comment]
Possibly related to #2380

**Comment by DelnarErsike** [comment]
Issue was fixed in a commit to the dev build, it will show up in the next nightly.
