### ISSUE TITLE
 Issue: - Relationship tab crash

### ISSUE THREAD

**Issue by lordblades** [chummer5a/chummer5a#2386]
### Environment
Crash ID: ccba6328-5d88-4aa7-a59d-3efce8b5d426
Chummer Version: 5.197.8
Environment: Windows 7 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
The Relationships tab should be accessible

### Actual behaviour
Chummer crashing when trying to open the Relationships tab

### Steps to reproduce the behaviour
Open a character, go to the Relationships tab

**Comment by DelnarErsike** [comment]
Has been fixed in the dev build, fix will be in the next nightly.
