### ISSUE TITLE
Drone Weapon Mounts

### ISSUE THREAD

**Issue by TDW89** [chummer5a/chummer5a#2389]
### Environment
Chummer Version: 5.197.10
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding drone weapon mounts to drones should be possible

### Actual behaviour
when adding a drone weapon mount to a drone the OK box is greyed out and cant be clicked.

### Steps to reproduce the behaviour
create new character, add a drone, add weapon mount, select one of the drone weapon mounts. OK box is now un-clickable.

**Comment by Zitchas** [comment]
I just confirmed this, trying to add a weapon mount to an Ares Matilda. I can add the Standard (SR5), Heavy (SR5), Light, Standard, and Heavy weapon mounts, but all the drone specific mounts are selectable, but with the OK button greyed out as described. 

As a side note, despite displaying the source reference, I can't click on it to go the source for either the drone mounts, the Matilda itself on the main vehicles page, or the Chinook I happened to buy too.
