### ISSUE TITLE
New version won't let you carry over more than 5 BP in priority mode

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#239]
BP=Karma in that mode. Book says the maximum carry over is 7. Unless I'm missing some errata, I figured that should be a chummer thing to. Didn't notice until lately cause heh, i squeeze every last bit of starting karma I can out of my dudes.

**Comment by joha4270** [comment]
For now you can change carryover amount under options

I'll look at changing this for next release, but i might not touch the main branch before that

clsOption.cs:870

**Comment by chummer5a** [comment]
Fixed in 5.168.
