### ISSUE TITLE
Cannot load Language

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2390]
### Environment
Chummer Version: Nightly-v5.197.11
Environment: windws10 64 bits
Runtime: 
Microsoft.NET Framework4.5 MultiTargeting pack
Microsoft.NET Framework4.5.1 MultiTargeting pack
Microsoft.NET Framework4.5.1MultiTargeting pack(enu)
Microsoft.NET Framework4.5.1 sdk
Microsoft.NET Framework4.6.2 sdk
Microsoft.NET Framework4.6.2 MultiTargeting pack

### Expected behaviour
software launch

### Actual behaviour
windwos with message "Cannot load Language"

### Steps to reproduce the behaviour
impossible to get out of this massage window without kill process

**Comment by Dedalios** [comment]
Chummer5.197.1.exe same problem

**Comment by DelnarErsike** [comment]
You're missing en-us.xml from the `lang` folder.

**Comment by Dedalios** [comment]
en-us.xml existe on folder from   Nightly-v5.197.11 
 en-us.xml existe on folder from   Chummer5.197.1

**Comment by Dedalios** [comment]
not proble with 0.0.5.139

**Comment by Dedalios** [comment]
use this version on another machine without any specific problem.

**Comment by Dedalios** [comment]
I have to find out why on this machine we have this problem but not on the second

**Comment by Dedalios** [comment]
The Microsoft.NET Framework version is identical on both machines

**Comment by Dedalios** [comment]
for this test i use executive version

**Comment by DelnarErsike** [comment]
If you wait for the next nightly, the error messages displayed for the language not loading properly will be more descriptive and should let you get a better idea of what's going wrong.

**Comment by Dedalios** [comment]
My goal through the information filed is to provide you with additional information.
Apart from the bug that seems to be related to the code, there is the difference between two computers that have no difference on the Microsoft.NET Framework installed but that react differently.
the difference between his 2 posts can be on 64-bit windows10 updates.
