### ISSUE TITLE
Knowlege skill rating locked at 10 at char creation

### ISSUE THREAD

**Issue by Mondlied** [chummer5a/chummer5a#2395]
### Environment
Chummer Version: 5.197.1.0
Environment: Win 10 Home 64 bit
Runtime: 4.7.1

### Expected behaviour
Initial rating of new knowlege skill should be 0/1. The user should be able to reduce rating.

### Actual behaviour
Adding a knowlege skill results in a rating 10 knowlege skill being added. Cannot reduce the rating using the Spinner (neither using the mouse nor using the keyboard to modify the text). (Free) skill points are not subtracted from the "Karma Summary" tab to the right; only adding a specialisation reduces the skill points by 1. 

### Steps to reproduce the behaviour

 1. Start Chummer
2. Open attached character file
3. Go to skills tab
4. Add new Knowlege Skill using the button
5. Try modifying the rating

### Link to affected character file
[Five vor (bug).zip](https://github.com/chummer5a/chummer5a/files/1664693/Five.vor.bug.zip)

**Comment by DelnarErsike** [comment]
I think this issue has already been fixed in the latest nightly, as I cannot replicate it on the dev build. Could you verify this for me?

**Comment by Mondlied** [comment]
In version 5.197.12.0 the issue is indeed no longer reproducable.
