### ISSUE TITLE
Several localization test could not appear as normal in zh-cn

### ISSUE THREAD

**Issue by Youneko17** [chummer5a/chummer5a#2396]
I collect some problems that I meet in Chinese Localization. Some of them are due to the lack of appropriate string, the others are much more strange that although I translated those texts, they are still in English while running chummer5.
Lack of appropriate string or data id:
· “Matrix Condition Monitor” of gears and vehicles 
· “Physical Condition Monitor” of vehicles
· "Nuyun Karma Max" when choosing Karma Buy Mode in character build window
· Title of "Choose Character Priorities" window as well as specific talents that you may choose

Could not normally appear:
· “Limits” of Tab_Limits (only in career mode)
·  The texts that should appear while mousing over Val(Aug) and Metatype Limits on common tab
· “Cancel” button in Choose a skill window
· Title of "Choose a skill" window
· All of martial arts techniques
· "Standard", "Prime Runner", "Street Level" and "Street Scum" in character build window

**Comment by Youneko17** [comment]
I noticed that there was an housecleaning 3 days ago, about martial arts and the problem about translation of martial arts techniques should have been fixed. My nightly version is a bit of out of date and I just update to the latest version. It's fixed, so plz just ignore that line.

**Comment by DelnarErsike** [comment]
From what I can tell, everything you've mentioned has now been addressed.

Both specific talent entries and options like "Standard", "Prime Runner", "Street Level" and "Street Scum" already support translation. You can refer to `pt-br_data.xml` for examples of how strings like these should be translated, or you can Rebuild using the Translator tool, which should generate the appropriate entries for those strings.
