### ISSUE TITLE
Crash after clicking on vehicle sensor array

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2398]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.12
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
To be able to click on vehicle sensor array to add sensors.

### Actual behaviour
Click on sensor array and crash handler crashes followed by Chummer.
![crash 1](https://user-images.githubusercontent.com/17562417/35404938-7cc750a6-01fc-11e8-94a8-25bae0a5a218.png)
![crash 2](https://user-images.githubusercontent.com/17562417/35404945-837fd74c-01fc-11e8-94ba-76de6c4d3bb7.png)

**Comment by DelnarErsike** [comment]
I believe this was fixed in commit 35410cac9d72e01d02e03adbe2333e965fe40c8b earlier today.
