### ISSUE TITLE
Automatically included metagenetic qualities included in Karma Spent on Positive and Negative Qualities

### ISSUE THREAD

**Issue by richard-zang** [chummer5a/chummer5a#240]
<b>How to Reproduce:</b>
1. Create a new character with Priority.
2. Select a metavariant when choosing Character Priorities.
3. Add a Positive Quality that costs more than 25 - Metagenetic Positive Qualities Cost
4. Get message that you can't spend more than 25 karma on positive qualities.

Ex. Nartaki Magician has Shiva Arms. Attempting to add Focused Concentration (Rating 6) triggers message and prevents from adding.

This is an issue for any character creation mode.

<b>Suspected Cause:</b>
When mandatory metagenetic qualities are added, ContributeToLimit bool on each quality object defaults to true.

<b>Suggested Fix:</b>
in <b>frmPriorityMetatype.cs</b>
After line ~1190: <code>objQuality.Create(objXmlQuality, _objCharacter, objSource, objNode, objWeapons, objWeaponNodes, strForceValue);</code>
Add: <code>objQuality.ContributeToLimit = false;</code>

After line ~1212: <code>objQuality.Create(objXmlQuality, _objCharacter, objSource, objNode, objWeapons, objWeaponNodes, strForceValue);</code>
Add: <code>objQuality.ContributeToLimit = false;</code>

This would fix for any metavariant. You would need to add same lines to Metatype if metatypes also have associated qualities. lines ~1138 and ~1159.

We can't change the Qualities xml because the metagenetic qualities can be manually selected for other metavariants/metatypes and would therefore contribute to the karma limit.

**Comment by joha4270** [comment]
Thanks for submitting a bug report and even more thanks for taking the time to give a suspected cause and a fix. 

Sadly, your suggested fix won't work as Quality.ContributeToLimit is readonly and calculated from a few different things. 

Fix should be simple enough (I know where the error gets thrown, just didn't knew of this case (frmCreate.cs:cmdAddQuality_Click)), but i won't have the time to look into it the next few days.

**Comment by richard-zang** [comment]
Ok cool.
I'm not sure what you mean by readonly. Do you mean the mutator method shouldn't work? Because it  definitely has an effect if I try to set it.

**Comment by joha4270** [comment]
>I'm not sure what you mean by readonly.

It means i can't read

There is one Property called "ContributeToBP"
This value can only be read from, but you can't write to it. I found that
first when looking at your fix, instead of the property you propose
changing "ContributeToLimit", that you can both read and write to


2015-06-18 20:40 GMT+02:00 richard-zang <notifications@github.com>:

**Comment by joha4270** [comment]
Fixed in #243
