### ISSUE TITLE
problem on technomencer

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2403]
A:
Magician or Mystic Adept: Magic 6, two Rating 5 Magical skills, 10 spells
Technomancer: Resonance 6, two Rating 5 Resonance skills, 5 complex forms
B:
Magician or Mystic Adept: Magic 4, two Rating 4 Magical skills, 7 spells Technomancer: Resonance 4, two Rating 4 Resonance skills, 2 complex forms Adept: Magic 6, one Rating 4 Active skill Aspected Magician: Magic 5, one Rating 4 Magical skill group
c:
Magician or Mystic Adept: Magic 3, 5 spells
Technomancer: Resonance 3, 1 complex form
Adept: Magic 4, one Rating 2 Active skill
Aspected Magician: Magic 3, one Rating 2 Magical skill group
d:
Adept: Magic 2 Aspected Magician: Magic 2

on your application
Technomancer: Resonance 6, two Rating 5 Resonance skills, 7 complex forms

**Comment by chummer5a** [comment]
http://forums.shadowruntabletop.com/index.php?topic=24595.msg488013#msg488013
Technomancers were given more complex forms in errata.
