### ISSUE TITLE
Critter power notes not available for printing

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2404]
### Environment
Chummer Version: 5.197.13
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Critter Power notes are available for printing

### Actual behaviour
They are not exposed to the character viewer
![critter power](https://user-images.githubusercontent.com/17562417/35467282-6f51f90e-0304-11e8-9582-7b06e166fe76.png)

**Comment by DelnarErsike** [comment]
Can you verify that this is still the case if the "Print Notes" checkbox is checked in Chummer5a's options?

**Comment by Lochabar** [comment]
Mark this down as a PICNIC error; **P**roblem **I**n **C**hair **N**ot **I**n **C**ode!

I've been setting up a Missions specific set of Options. I started with the default set from the latest release and that has Print Notes unchecked. Later, using a character that used the default options, I started checking that notes for Critters printed correctly ... they didn't!

There are times when I should not not be allowed near a keyboard!
