### ISSUE TITLE
 Issue: - Can't create player matatype disapear

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2406]
### Environment
Crash ID: c7e30d1c-dc5f-4951-8a45-55c1a6e27464
Chummer Version: 5.197.14
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Can't really help without some more details.

**Comment by Dedalios** [comment]
, the bug software to create this report and I assumed that the information in the report had been transmitted. We start the software, we get the starting page. we ask the creation of the character, and no more metatype anything impossible to create the character.

**Comment by DelnarErsike** [comment]
Is the `metatypes.xml` file present in the `data` folder? Is the issue encountered both under Priority and Point Buy character generation methods?

**Comment by Dedalios** [comment]
![capture](https://user-images.githubusercontent.com/35507412/35471401-ba5d5bfe-035a-11e8-8e7c-2ae543b064af.PNG)

**Comment by Dedalios** [comment]
metatypes.xml exist on data foldes
metatypes.xsd exist on data foldes
Is the issue encountered both under with all character generation methods

**Comment by DelnarErsike** [comment]
Could you check if the issue is present if you re-download Chummer5?

**Comment by Dedalios** [comment]
https://github.com/chummer5a/chummer5a/releases
load 26/01/2018 hs
reload 27/01/2018 -12h00 hs
reload 27/01/2018 -17h00 ok New menu appaear .the bug seems fixed

**Comment by Dedalios** [comment]
Martial Arts options are no longer available
![capture-artm](https://user-images.githubusercontent.com/35507412/35475018-8201106a-0397-11e8-9777-98bc7609ca67.PNG)

**Comment by DelnarErsike** [comment]
What sourcebooks do you have enabled?
