### ISSUE TITLE
Skills automatically being given skill rating points after saving the file 

### ISSUE THREAD

**Issue by Kromgar** [chummer5a/chummer5a#241]
Here's the file affected by this: 

https://drive.google.com/file/d/0B1ZXjBHo3z5mZGVkU0piaTMzRVU/view?usp=sharing

How to reproduce: 

Remove the skill point from sneaking, assensing, banishing, and sneaking. Keep the point of karma in.

Save the file. 

Reopen the file

It automatically adds a skillpoint to all three skills.

Fun fact skill ratings > 0 is excluding sneaking, banishing and assensing if you filter for [Active Skills > Rating 0]

I am on the latest version of chummer and someone else experienced the same glitch.

Images of the skill exclusion:

Pre-Saving the file where it shows I have 0 karma and 0 skillpoints left
![](http://i.imgur.com/EWvvsQ4.png)

After-Saving file and reopening
![](http://i.imgur.com/xl9Y1I3.png)

**Comment by joha4270** [comment]
I have a suspected cause, but i won't be able to confirm/deny this week.

**Comment by Lexanius** [comment]
Have the bug in the Karma System too.
Using Chummer5a 0.5.176.0

The value is write, when loading the save file in the <base> of the skill.
![chummer](https://cloud.githubusercontent.com/assets/1294835/8273956/16002024-1883-11e5-8083-c37a32c58396.png)

**Comment by chummer5a** [comment]
Fixed in 5.178.
