### ISSUE TITLE
Problem bug when loading player old version

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2410]
### Environment
Crash ID: 104a404f-2963-4522-99ca-fc431d264fc9
Chummer Version: 5.197.15
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
when you charge player created with Chummer Version: 5.197.15

### bug result
[attributes.txt](https://github.com/chummer5a/chummer5a/files/1671299/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/1671300/exception.txt)
[default.xml.txt](https://github.com/chummer5a/chummer5a/files/1671310/default.xml.txt)
### Steps to reproduce the behaviour
i dont' know
crash handle generated dump but 140mo

**Comment by Dedalios** [comment]
Other point my chummer is defined with langue parameter FR , 
When you created new player ,metatype dispear 
When you dowload old player bug 
But i have change langue on US , and in second time change US from  FR
All problem dispear.


_Das ist das Problem der Spracheinstellungen_
_That's the problem of language settings_
それは言語設定の問題です

**Comment by DelnarErsike** [comment]
How on Earth did `System.Xml.XmlElement` get added as a sourcebook in your `default.xml` file?

**Comment by Dedalios** [comment]
![sourcebook](https://user-images.githubusercontent.com/35507412/35488372-ec0c9b00-0487-11e8-8a52-e6e8e2c5f5e5.PNG)

**Comment by Dedalios** [comment]
[default.zip](https://github.com/chummer5a/chummer5a/files/1671712/default.zip)

**Comment by DelnarErsike** [comment]
PDF Parameters have nothing to do with what sourcebooks you have enabled as part of your settings file. Those get saved in the registry anyway.

Well, according to that settings file, only Shadowrun 5 is enabled. That's better in the sense that it doesn't contain any weird entries that wouldn't belong. My guess is that this is what has been causing your issues: your settings file(s) between different computers have different sourcebooks enabled, and of course Chummer5 will not populate entries from sourcebooks that you don't have enabled (e.g. it won't populate Martial Arts if you don't have Run and Gun and/or Forbidden Arcana enabled).
