### ISSUE TITLE
How to best handle `<nameonpage>` tag for qualities

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2414]
Now that we can use `<nameonpage>` to reference the correct name for the qualities as they are written on the sourcebook, how should we approach it?

- Every quality should have the tag? For now I think not.
- Should this tag be empty and filled as needed? As above, just added if needed.
- Should this appear in a column on the Translator interface empty and filled as needed? Yes

The Translator interface make it easy to work with that in other languages, now it is a matter of dealing with the original English data files.

Those would be the  tasks to be done.

- [x] Add the tag support for  `<altnameonpage>` to the Translator.
- [ ] Fill the <nameonpage> for the qualities that are broken or somehow split in the english data (Addiction, Allergy, Fame, Trust Fund, etc)

**Comment by holgerschlegel** [comment]
The value of  `<nameonpage>` should be defaulted to the translated name at runtime.
No need to enter the name twice if the quality name is exactly the same as in the book.

**Comment by luizbgomide** [comment]
@hogerschlegel, This is already handled, this is why I suggest to include the tag and leave it empty. Otherwise it could be forgotten. But if the Translator can handle that at runtime and just add the tag as needed (as it is it included `translate` and `altpage` being it used or not.

**Comment by chummer5a** [comment]
Are there any existing examples of qualities that require additional support for this to be closed out?
