### ISSUE TITLE
 Issue: - Crash upon going to Armor tab

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2419]
### Environment
Crash ID: 2acee94c-31f2-432b-8d3f-458a17047db9
Chummer Version: 5.197.17
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer not crashing

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Open up a character in career mode, go to Street Gear, then to Clothing and Armor, Chummer crashes

**Comment by Zitchas** [comment]
I just got this as well.

Chummer Version: 5.197.17
Environment: Windows 10 Pro

Crash ID: 1ee1e71b-e714-407a-9e7e-2ff8a37eb86c
"Cannot bind to property or column ArmorDegradation on the DataSource.
Parameter name: dataMember

[chummer_crash_131617915542443582.txt](https://github.com/chummer5a/chummer5a/files/1677770/chummer_crash_131617915542443582.txt)

**Comment by buriedcandarian** [comment]
same

[chummer_crash_131618474998413026.txt](https://github.com/chummer5a/chummer5a/files/1680438/chummer_crash_131618474998413026.txt)

**Comment by DelnarErsike** [comment]
Issue has been fixed in commit a76603075640d42a248e0a8f8c55901294cfc449.
