### ISSUE TITLE
Adept Power Point loss not calculating correctly against Essence loss thresholds

### ISSUE THREAD

**Issue by voodoooodoov** [chummer5a/chummer5a#2424]
### Environment
Chummer Version:  5.197.1.0
Environment:  Windows 10 Home  (10.0.16299)
Runtime:  v4 says 4.7.02556. v4.0 says 4.0.0.0. Both in Client.

### Expected behaviour
1.86 points of Essence loss on an Adept with Magic 6/6, Essence 6, PP 6 should result in Magic 4/4, Essence 4.16, PP 4 (-2 lost).

### Actual behaviour
1.86 Essence lost:  Values shown: Magic 2/2, Essence 4.22, PP 2 (-4.00 remaining)

### Steps to reproduce the behaviour
During a "what-if" character build exercise I found this:

Start with an Adept with Magic 6/6, Essence 6, Power Points 6 (buy 6PP of Adept powers)
Add 1.36 points of Bioware (only used bio so don't know if cyberware will give a different result) (Ex: Bone Density (3) Standard; Genetic Opt (STR); Striking Callus Feet x2 Alpha, Hands x2 Alpha = 1.36)
Values shown: Magic 4/4, Essence 4.64, PP 4 (-2.00 remaining)

Set to Career Mode

Add .5 points of Bio (Ex: Muscle Toner (2) Used = .50)
Values shown: Magic 2/2, Essence 4.22, PP 2 (-4.00 remaining)

SHOULD BE
Magic 4/4, Essence 4.14, PP 4 (-2.00 remaining)

Only into second "tier" of Essence loss, so should only be 2 Magic lost, 2 Magic maximum lost, and 2 PP lost (-1PP for <6 and >4.99; -1PP for <5 and >3.99 = -2PP total)

Character attached shows the final total issue described above (and is the one where the issue was discovered), though note there is another bug effecting Bioware total loss value (I'll submit a bug on that too).  Char shows 1.28 loss and it should be 1.36; Striking Callus Hands x2 not calculating correctly.  I do not believe this effects the issue described above.

### Link to affected character file

[Ton BE 3 Try Career.zip](https://github.com/chummer5a/chummer5a/files/1684942/Ton.BE.3.Try.Career.zip)

**Comment by chummer5a** [comment]
Fixed in current nightly builds. Suggest updating to 5.197.18.
