### ISSUE TITLE
Weapon mount mod crash

### ISSUE THREAD

**Issue by FastSam** [chummer5a/chummer5a#2432]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.6
Environment: Windows 8.1
Runtime: unknown .NET 4.5.1

### Expected behaviour
Selecting weapon mount modification for drone.

### Actual behaviour
Chummer5 fatal error crash

### Steps to reproduce the behaviour
Happens with all drones I've tried, but adding a modification to a weapon mount on a drone (Ammo bin/cover/etc) then trying to select it later will cause an immediate crash.

### Link to affected character file(s)
https://drive.google.com/open?id=1hKMdtdOGESUtT-jt_l61sUwgIx1F0eug
https://drive.google.com/open?id=1mYC8y2YITyW5w12xSvsv_f6fherLANsn

**Comment by chummer5a** [comment]
Should be resolved in current nightlies.
