### ISSUE TITLE
Traditions always using BOD + WIL for "resist Drain"

### ISSUE THREAD

**Issue by Remasuri3** [chummer5a/chummer5a#2433]
### Environment
Chummer Version: 5.197.19
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
When selecting Traditions it should use different attributes for calculating resist Drain depending on the traditions.

### Actual behaviour
Always uses BOD + WIL even when creating an own tradition.

### Steps to reproduce the behaviour
Just create a new mage and select a tradition.

### Link to affected character file
https://drive.google.com/file/d/18ofLBKuP4w4-LqfoY3P5d2nQ9POaRiBb/view?usp=sharing

**Comment by DelnarErsike** [comment]
Not a bug. Adepts always use BOD + WIL for their drain dice.
