### ISSUE TITLE
Printer File won't show

### ISSUE THREAD

**Issue by Swimmer117** [chummer5a/chummer5a#2434]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1
Environment: Windows 7 Professional
Runtime:  .NET 4.5.1

### Expected behaviour
Show Printer friendly version of character sheet

### Actual behaviour
Showed blank page instead of character sheet

### Steps to reproduce the behaviour
created duplicate character sheet of same character to see if it would change anything. same issue.

### Link to affected character file
https://drive.google.com/open?id=1h7U3UyR4stUCNjxqIp2df3_-Twrk6SXH

https://drive.google.com/open?id=1f5byoQDo3OnmhPvwsZTxSg-4Xtyy2be0

**Comment by DelnarErsike** [comment]
Are you sure you have a character sheet selected that would actually show something? For example, if the character is in Create mode, Calendar would not show anything.
