### ISSUE TITLE
Translator crashes

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2436]
### Environment
Chummer Version: 5.197.20
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
No crash.

### Actual behaviour
Translator.exe crashes when selecting a data file category to show.

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Translator.frmTranslate.DoLoadSection(Object sender, DoWorkEventArgs e) in C:\projects\chummer\Translator\frmTranslate.cs:Zeile 470.
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

### Steps to reproduce the behaviour
Start Translator and Edit a language file.
Select a data file to show, e.g. qualities.xml
Select a category in the data file to show, e.g. qualities

**Comment by DelnarErsike** [comment]
Fixed in commit 43831c05ec407c594709404b15cccaa39635630b.
