### ISSUE TITLE
Does chummer supports multiple specializations?

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2438]
I think I'm might be missing something obvious here, but how can I add more than one specialization to a skill?

**Comment by luizbgomide** [comment]
@holgerschlegel it might be it, I will test later. I already knew about that, so that when I tried, I used "Ignore creation rules" but found no way to add another specialization this way.

**Comment by chummer5a** [comment]
The skill controls weren't written to allow that behaviour in create mode.
