### ISSUE TITLE
New Feature: Ally Spirit

### ISSUE THREAD

**Issue by Emparawr** [chummer5a/chummer5a#244]
I have no skill in coding whatsoever so I would be less than useless in trying to do this myself but for anyone who does have the skill, I think that this would be a great addition to chummer.

**Comment by chummer5a** [comment]
One of two ways to do this. 
1: Disable Running Wild requirement, clear out the critter creation list to spirits, go from there. Not exactly hard, but 5e hasn't given creation rules to these things so it would mostly be hedging from 4th's content.

2: Add a checkbox for "Is Ally Spirit" and a dropdown for any pacts.

**Comment by Emparawr** [comment]
From my limited knowledge that sounds like a good way of going about it. If there is already programming still implemented into chummer5 leftover from chummer4 that has the system for creating critters like spirits then if it was renabled and just removed all the critters except for spirits it would probably be pretty easy to allow the creation of spirit critter sheets that could be linked to the current spirit section. Ally spirits could use the same system depending on the limitations involved. It would be great just to help keep track of them all. How much damage they have taken, skills they have or optional powers including ones that gives skills etc. Currently it looks like you can link a spirit to a character sheet but you are still creating in with character creation rules and then using the improvements section to forcefully make it represent a spirit.

**Comment by schultlp** [comment]
Ally spirits are actually built from the ground up, and their attributes are all equal to their force, and they don't have any elemental limits to their spells or abilities. So you would likely have to add a new spirit type. 

Actually, why not just implement the 4th edition rules for critters and spirits and hide them behind a checkbox like "Use 4th Edition Critter rules" in advanced settings?
