### ISSUE TITLE
GUID duplicates reported opening 5.197.22

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2443]
### Environment
Chummer Version: 5.197.22
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Chummer opens without problems

### Actual behaviour
![duplicate guid](https://user-images.githubusercontent.com/17562417/35773350-2f78f4ba-0947-11e8-8c3a-3aab2ed9aa5e.png)
![improvement xml](https://user-images.githubusercontent.com/17562417/35773351-2f9f8f6c-0947-11e8-8520-2ad968670236.png)

### Steps to reproduce the behaviour
Open nightly 197.22

**Comment by chummer5a** [comment]
Fixed by 71c0d22beea009ebf2439a04e92e65683c80a3b7
