### ISSUE TITLE
Problems with file: improvements.xml

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#2444]
### Environment
Chummer Version: Nightly-v5.197.22
Environment: Windows 10 64 Bit
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Chummer starts normally.

### Actual behaviour
Chummer displays 2 warning error windows, both concerned with the file **improvements.xml**. 
Adding Cyberware makes chummer crash.
In Nightly-v5.197.21 both worked perfectly.

### Steps to reproduce the behaviour
download the most recent nightly (Nightly-v5.197.22) and run it

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Both issues have been fixed in the dev build and will be present in the next nightly.
