### ISSUE TITLE
Spellslinger discounting rituals and alchemical preparations.

### ISSUE THREAD

**Issue by dammt** [chummer5a/chummer5a#2445]
### Environment
Chummer Version: 5.197.22.0
Environment: Win10
Runtime: .NET 4.5.1

### Expected behaviour
Spellslinger should only be discounting regular spells according to RAW.

### Actual behaviour
Spellslinger also discounts rituals and alchemical preparations

### Steps to reproduce the behaviour
Make a character with the ability to learn spells. Take Spellslinger. Learn a preparation or a ritual.

**Comment by chummer5a** [comment]
Strictly speaking they're still spells; still, shouldn't be a problem to fix. 

If someone else tackles this before I get around to it, I'd prefer that we augment the NewSpellKarmaCost improvement to take a category in the improvedname; empty improvedname should affect all spells. SpellKarmaCost improvement will probably be best split up per category as well.
