### ISSUE TITLE
GUID issues on startup

### ISSUE THREAD

**Issue by TDW89** [chummer5a/chummer5a#2447]
### Environment
Chummer Version: 5.197.22
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behavior
1st message reads:
```
2 items were found in the file improvements.xml with the same GUID. If you are using custom content, please ensure that you use a new GUID for each item you add.

Items with duplicate IDs:
Enable Spells and Spirits Tab
Enable Spells and Spirits Tab
Cyber-singularity Seeker/Redliner (Attribute)
Cyber-singularity Seeker/Redliner (Condition Moniter)
```
Not using any custom content to the best of my knowledge and tested in a fresh folder to check that it wasn't due to any left over files from older releases.

there is then a 2nd message that reads:
```
71 items were found in the file improvements.xml with IDs that are not parsable as GUIDs. If you are using custom content, please ensure that ID fields are always filled with a unique GUID and only a unique GUID.

Items with non-GUID ID fields:
[list of 71 items, I can type it out if you want but can't copy/past from the error message and hopefully isn't needed]
```
### Steps to reproduce the behaviour
Un-zip release 5.197.22 into a new folder, run `Chummer5.exe` observe messages.

**Comment by chummer5a** [comment]
Will be fixed in the next nightly.
