### ISSUE TITLE
trying to add Cyber/bioware crashes chummer

### ISSUE THREAD

**Issue by TDW89** [chummer5a/chummer5a#2448]
### Environment
Chummer Version: 5.197.22
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Clicking `Add Cyberware` or `Add Bioware` should bring up their respective lists of Cyber/bioware.

### Actual behaviour
Chummer crashes.

### Steps to reproduce the behaviour
Create new character attempt to add any cyber or bioware to that character. Chummer crashes.

**Comment by chummer5a** [comment]
Fixed, will be in the next nightly build.
