### ISSUE TITLE
Drone attribute modifications

### ISSUE THREAD

**Issue by AlyfoxLP** [chummer5a/chummer5a#2457]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.183.0.0
Environment: Windows 7 home 64bit
Runtime:  .NET 4.5.1

Rigger 5.0 page 123, "Attribute Modification"
There does not appear to be a way to due this using the Rigger 5.0 rules. 
Right click on the drone in question -> add modification ->
Handling, Acceleration, Speed, Armor, Sensor dont follow the expected rules from page 123, instead appearing to use the pricing for Vehicle upgrades rather than Drone upgrades, and use up slots.

I can't find any way to upgrade drone attributes per page 123 in the application.

**Comment by chummer5a** [comment]
Enable the Optional Drone Mod rules in the Optional Rules menu.

**Comment by AlyfoxLP** [comment]
Thanks. I found that before I read this, by a factor of a few minutes. Kinda feel stupid. Feel free to delete this!
