### ISSUE TITLE
Sensor functions of vehicles not shown

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2458]
### Environment
Chummer Version: 5.197.26
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Sensor functions should be shown in the vehicles tree.

### Actual behaviour
Sensor functions added to sensor arrays of vehicles or drones are not shown in the vehicles tree on the vehicles and drones tab.
The sensor functions are added to the sensor array and printed in the sheets, but not visible in the ui.

### Steps to reproduce the behaviour
Add a vehicle or drone.
Add sensor functions to the (automatically created) sensor array.

**Comment by DelnarErsike** [comment]
Fixed in commit f1863af4541b682a8e945e362751d79de06c0284
