### ISSUE TITLE
Chummer freezes after selection of Defiance EX Shocker

### ISSUE THREAD

**Issue by Darilon** [chummer5a/chummer5a#2461]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When I click on the Defiance EX Shocker in my characters weapon list in career mode, I would expect the program to show the wheapon and continue normally

### Actual behaviour
When I click on the Defiance EX Shocker in my characters weapon list in career mode, chummer5a freezes and i must abort it from the task manager.

### Steps to reproduce the behaviour
Create a character with a Defiance EX Shocker, put it into career mode and select the weapon.

**Comment by DelnarErsike** [comment]
Issue has been fixed in the latest nightly.
