### ISSUE TITLE
Chummer does not create a copy when I put a character into career mode

### ISSUE THREAD

**Issue by Darilon** [chummer5a/chummer5a#2462]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I enabled the check mark to create a copy of my character when putting it to career mode. When actually changing to career mode, I would expect that chummer would create a copy of the character that stays in creation mode.

### Actual behaviour
No copy was created

### Steps to reproduce the behaviour
Create character.
Set check box to create a copy on change to career mode.
Save new options and restart chummer
Put character to career mode

**Comment by DelnarErsike** [comment]
Assuming you have the "Create backup of character before moving them to Career Mode" option checked in the options menu, could you please check the `<Chummer root>/saves/backup` folder to verify that a create mode backup of the character was indeed not created when they were exported to career mode?
