### ISSUE TITLE
Sensors added to drones does not show in window.

### ISSUE THREAD

**Issue by Safaryna** [chummer5a/chummer5a#2465]
### Environment
Chummer Version: 5.197.26
Environment: win10

### Expected behavior
in create mode with priorities, right click on sensor array on a drone. add plugin. select a sensor and hit ok. expect to see item with rating under the sensor array.

### Actual behavior
senor does not display under sensor array. 

note will display in print preview also if you close the program and reopen the file

Also sensors will stay on the list after the delete button is pressed.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Fixed in f1863af4541b682a8e945e362751d79de06c0284, should be in current nightly build.
