### ISSUE TITLE
 Issue: - Chummer crashes when clicking on Karma & Nuyen in career

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2466]
### Environment
Crash ID: 462a2e83-7b76-48dd-85d2-684d876fc74b
Chummer Version: 5.197.27
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Karma & Nuyen window shows as usual

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Don't know exactly what to do to reproduce it. I recreated the character, and the error persists.
The error seems to stem from something with this specific character (others don't have this problem)

### Affected Character
-deleted-

**Comment by Sturmkind** [comment]
still an issue in 5.197.28

**Comment by chummer5a** [comment]
Same error message as before?
