### ISSUE TITLE
Translation Error in de-de_data.xml

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2468]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.27
Environment: Windows 10 Pro x64
Runtime: 4.7

### Expected behaviour
Find Health correctly translated to German as "Heilung"

### Actual behaviour
Find Health translated to German as "Kelung"

Error is found in "de-de_data.xml" in Line 29124: <spec translate="Kelung">Health</spec>

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by holgerschlegel** [comment]
I no one is faster, I'll fix this on the weekend. I want to provide a pull request with some (UI) translations updated/fixes anyway.
