### ISSUE TITLE
Fake licences missing from equipment list

### ISSUE THREAD

**Issue by Magusinvictus** [chummer5a/chummer5a#2469]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 197.27
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Create mode, fake licences should be present in "Street Gear > ID/Credsticks" menu. Were present in a prior build.

### Actual behaviour
Fake licences missing from equipment list.

### Steps to reproduce the behaviour
Create mode, attempt purchase of fake licences.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Not a bug. Fake licenses need to be attached to fake SINs. You can add them as plugins to the SIN to which you want to attach them.
