### ISSUE TITLE
Dice pools overlap Dice Roller icons

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2475]
### Environment
Chummer Version: 5.197.29
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
To see the "Open Dice Roller" icon separate from the dice pools

### Actual behaviour
Spell "Dice Pool" and the "Resist Drain with" dice pool overlap their Dice Roller icons
![dice pools](https://user-images.githubusercontent.com/17562417/36057411-96b406a2-0e05-11e8-8e75-19eb74a6d214.png)

### Steps to reproduce the behaviour
Using a magician character select the "Spells and Spirits" tab. Check the dice pools.

**Comment by Lochabar** [comment]
The same problem with the Technomancers "Resist Fading" dice pool
![fading](https://user-images.githubusercontent.com/17562417/36057460-4cbcccb8-0e06-11e8-95ec-8699c13dce90.png)

**Comment by WMarks** [comment]
+1 to this issue, the dice roller is really useful so having to deal with this makes it a bit clumsy.

**Comment by chummer5a** [comment]
Should be working as expected in current builds.
