### ISSUE TITLE
Enhancement: "Free" rating 1 languages in career mode

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2477]
### Expected behaviour
The ability to add (without spending karma) rating 1 languages during career mode after having succeeded in the required test as an Adept with the Linguistics Power (Street Grimoire, p. 172)

**Comment by chummer5a** [comment]
I'm tempted to consider this working as intended, as it's not a permanently available option. You have to succeed at the test first. While we could implement something specific for it, I'd personally prefer that users just incremented karma to pay for it.

**Comment by Sturmkind** [comment]
fair enough. Otherwise you can also simply open the character in an editor (i.e. Notepad++) and add the appropriate lines manually.

On the other hand you have the ability to modify karma/nuyen/essence cost everywhere else... why not just give a checkbox on the skills tab to allow free skills as well?
