### ISSUE TITLE
 Issue: - Chummer crashes when trying to create a non-human character

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2482]
### Environment
Crash ID: cfb136d1-c3bc-4d4a-9052-5f3c977df96e
Chummer Version: 5.197.29
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer creates a new character as usual

### Actual behaviour
Chummer crashes as soon as you click ok on the priority selection screen while having chosen a race other than human

### Steps to reproduce the behaviour
Open chummer, click create new character, use priority/Sum to 10 build method(weirdly works with karma), select race other than human, click ok

**Comment by DelnarErsike** [comment]
Was fixed in an earlier commit. Fix will be present in the next nightly.
