### ISSUE TITLE
Package chummer5 as a snap

### ISSUE THREAD

**Issue by cratliff** [chummer5a/chummer5a#2483]
I was wanting to see if packaging chummer5 as a [snap](https://snapcraft.io/) would be desired.  .net is a supported  plugin for snaps and I would really like to be able to easily run chummer5 on linux.  Packaged as a snap, installation should be as simple as `snap install chummer5` on a Linux device.  I'm not too familiar with this code base, but if packaging chummer5 as a snap would be appreciated I would like to work on an attempt to do so.  Or just as important is someone familiar with the codebase knows why this might not work before I get started I would like to know.

### Environment
Chummer Version: latest
Environment: Ubuntu 16.04

### Expected behaviour
A simple and painless linux install.

### Actual behaviour
Running chummer5 on ubuntu 16.04 didn't work for me, it looks like there are a couple open issues related to this.

**Comment by chummer5a** [comment]
Chummer on Linux requires WineTricks and/or some form of Mono, but I'm told that Mono causes crashes in career mode; I've never seen a stacktrace on what the specific problem is though.

**Comment by chummer5a** [comment]
The [wiki ](https://github.com/chummer5a/chummer5a/wiki) was recently updated with specific instructions for using WineTricks in the current build to work. I'm not familiar with the process for building a snap or docker image, but I'm happy to help out wherever required if someone's prepared to figure out what needs to be done.

**Comment by cratliff** [comment]
Yeah, I could give this another look.  I tried earlier, but I think the build at the time wasn't working on Linux at all from what I could tell.  There are some [instructions](https://forum.snapcraft.io/t/winesnap-creating-snaps-for-windows-applications/6392) and [demos ](https://forum.snapcraft.io/t/snap-wine-based-application/5267) of other people packaging WINE aplications.
