### ISSUE TITLE
Infected giving inappropriate penalties.

### ISSUE THREAD

**Issue by madpathmoth** [chummer5a/chummer5a#2487]
### Environment
Chummer Version: 5.197.31

### Expected behaviour
Some of a character's attributes have lowered maximums if they become Infected, which doesn't have any impact on how much Karma or Attribute Points it takes to improve the attribute.

### Actual behaviour
The character's attributes are treated as if they are actually reduced, somehow gaining negative augmented ratings, despite there being no reason for this.  It doesn't cost more for a Troll to raise their CHA even though it caps at four, the Infected are no different.

### Steps to reproduce the behaviour
Create any metahuman character.  Select the Infect (Ghoul) quality.  Try to spend attribute points on Charisma or Logic.

**Comment by chummer5a** [comment]
Check the Weaknesses. Ghouls get -1 CHA and LOG.
