### ISSUE TITLE
No metasapients/Infected

### ISSUE THREAD

**Issue by rhockett94** [chummer5a/chummer5a#249]
Hey guys,
Just noticed you can no longer make metasapients, ghouls/vampires/infected in general in chummer5.

Cheers!

**Comment by chummer5a** [comment]
Metasapients should work if you have Run Faster enabled, only the Banshee
is 'sort-of' working as Infected, as it doesn't do the things it needs to
do in career mode.

**Comment by chummer5a** [comment]
Fixed in 5.176.
