### ISSUE TITLE
Advanced Lifestyles crash

### ISSUE THREAD

**Issue by goldeneye71** [chummer5a/chummer5a#2490]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Version: 5.197.1
OS: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding advanced lifestyle options, such as garages, grid subscriptions, etc.

### Actual behaviour
chummer crashes when trying to add qualities

### Steps to reproduce the behaviour
1. create new character
2. create advanced lifestyle
3. add quality (any)
4. crash

### Link to affected character file
https://www.dropbox.com/s/ah61dtq4qxhlc0t/Vicegrip.chum5?dl=0

**Comment by chummer5a** [comment]
Resolved in current nightly builds.
