### ISSUE TITLE
Deleting Sprites Crashes Chummer

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#2494]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.0.0
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
During charakter creation, adding sprites for a technomancer works as expected. Dleting sprits already created should work as well.

### Actual behaviour
When trying to delete a sprite, Chummer crashes.

### Steps to reproduce the behaviour
Create a new Charakter in Karma Mode
Chose Technomancer
add sprite
delete sprite

### Link to affected character file
I found that the sprites are saved with a strange GUID. Maybe that is the problem.
    <spirit>
      <guid>00000000-0000-0000-0000-000000000000</guid>
      <name>Daten-Sprite</name>
      <crittername />
      <services>2</services>
      <force>12</force>
      <bound>True</bound>
      <fettered>False</fettered>
      <type>Sprite</type>
      <file />
      <relative />
      <notes />
      <mainmugshotindex>-1</mainmugshotindex>
      <mugshots />
    </spirit>

**Comment by bilgatus** [comment]
With nightly build it works now to delete the sprite, but creating new ones is not possible.

I have 7/7 sprites, deleted one and could not create a new one. It is against the limits.

**Comment by DelnarErsike** [comment]
As per core rulebook official errata (on their forums), a techno's complex form limit is 2x RES, whereas before it was 2x LOG at character generation and 2x RES in-game.

**Comment by bilgatus** [comment]
I am not argueing against it. :)

When I create some Sprites, and delete the top one. It disappears, after that I cannot create a new one.
When I delete some at the end, if works.
