### ISSUE TITLE
Commlink functionality is not translated

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2498]
### Environment
Chummer Version: 5.198.1
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Commlink functionality translated and displayed similar to English version
![commlink - english](https://user-images.githubusercontent.com/17562417/36266387-38ead9ac-1269-11e8-86c7-7bb61ba2ce1d.png)

### Actual behaviour
The functions are listed as "Custom Item" - here is the French version of Fancy Blocks
![commlink - french](https://user-images.githubusercontent.com/17562417/36266529-8d7b2a6c-1269-11e8-9578-152babb5d1be.png)
Notice that the page numbers are shown as in the English listing
Note: there are no translation for the commlink accessories in fr-fr_data.xml

The Portuguese language file pt-br_data.xml does have translations for the commlink accessories but they are not shown, and the page number is 1
![commlink - portugeuse](https://user-images.githubusercontent.com/17562417/36266872-7cdbd5b6-126a-11e8-874f-598aabd0807e.png)
And the same with the German de-de_data.xml, but again they are not shown
![commlink - german](https://user-images.githubusercontent.com/17562417/36266962-b5899330-126a-11e8-8458-8aa17c453438.png)

Note: these images are from the Fancy Blocks character sheets, but the same problems occur in the various Shadowrun 5 sheets.

**Comment by DelnarErsike** [comment]
Could you re-add whatever item it is that has the Commlink Functionality child? From what I can tell, the problem is caused by an older version of the Commlink Functionality item that relied on renamed custom items instead of dedicated gear entries.

**Comment by Lochabar** [comment]
I re-added the Hermes Icon commlink and the accessories now display correctly, translated if the data is on file - German and Portuguese - and, because the translations are not present, the French sheet displays them correctly in English.
