### ISSUE TITLE
 Issue: - Crash upon adding Karma/Nuyen in career mode

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2512]
### Environment
Crash ID: d5e164dd-be86-43ff-be1a-cc73893ab5ec
Chummer Version: 5.198.6
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer doesn't crash when trying to add Karma/Nuyen in career mode

### Actual behaviour
Chummer crashes when trying to add Karma/Nuyen in career mode

### Steps to reproduce the behaviour
Open character in career mode/create one and move it to career mode, go to Karma and Nuyen tab, click on either Karma gained or Nuyen gained, Chummer crashes

**Comment by chummer5a** [comment]
Fixed in latest commits; will be in the next nightly build.
