### ISSUE TITLE
Career mode crash

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#2516]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 198.6
Environment: (Operating system here. If it persists over multiple OS's list them all) Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1) yes

### Expected behaviour
(Enter text here)
Add Nuyen or Karma or edit expenses in career mode

### Actual behaviour
(Enter text here)
Crash

### Steps to reproduce the behaviour
(Enter text here)
Save character to career mode. Try to add karma or nuyen

### Link to affected character file
(Enter text here)
https://drive.google.com/open?id=1oKxBx2udywnHCO3nBAOZJeCXgKslycQ6

**Comment by chummer5a** [comment]
Resolved in Nightly 5.198.7+
