### ISSUE TITLE
Chummer crashed when entering the Karma and Nuyen tab

### ISSUE THREAD

**Issue by JEBtheGamer1** [chummer5a/chummer5a#2519]
[chummer_crash_131636555832048005.txt](https://github.com/chummer5a/chummer5a/files/1744359/chummer_crash_131636555832048005.txt)
### Environment
Chummer Version: 5.198.9, 5.198.1, 

5.198.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
Karma and nuyen screen is accessible

### Actual behaviour
Chummer crashed when entering the Karma and Nuyen screen

### Steps to reproduce the behaviour
Character is in career mode. Navigate to karma and nuyen screen. Chummer crashes. In 5.198.0 a 'failed to generate crash report' message is generated.

### Link to affected character file
[(Enter text here)](https://drive.google.com/open?id=1KQKmFOseBRU47GWmJdS0u8ZBU_crMXZy)

EDIT I have attached the latest crash report after noticing them on my desktop. Sorry for not doing this earlier. --end edit--
Sorry about the image, but I cannot copy and paste the text to the best of my knowledge.
![image](https://user-images.githubusercontent.com/16670390/36460997-19c8d1a4-1670-11e8-85c0-6a0bb9fcc6d2.png)

**Comment by DelnarErsike** [comment]
Could you see if this crash is still present in the latest nightly? I recall something similar getting fixed a few days ago.
