### ISSUE TITLE
Adept cannot select all metamagic with the magicians way

### ISSUE THREAD

**Issue by Angelofpain** [chummer5a/chummer5a#2520]
If a Adept has the magicians way selected, He cannot use the metamagic of the other ways. In the second edition of the streetgrimoire IT IS changed, So that He can learn it
### Environment
Chummer Version: 5.198.11
Environment: Windows 7
Runtime:..net 4.6

### Expected behaviour
With the magicians way IT IS possible to learn all metamagic of the other ways

### Actual behaviour
He cannot learn the other metamagics

### Steps to reproduce the behaviour
Select an adept, 
select the magicians way Qualität
Get His First Initiation
Try to get supernatural prowness

### Link to affected character file
...

**Comment by DelnarErsike** [comment]
I cannot find any reference to the rule that Magician's Way followers can take all way-specific metamagics, though I do recall something related to way requirements being present somewhere. Can you give a page reference of where I could find the rule?

**Comment by Angelofpain** [comment]
Yes for Sure, its in the Street grimoire on Page 178. But the Text have changed in the second edition of this book.

Thanks for looking

**Comment by DelnarErsike** [comment]
Is this the passage you're referring to? Emphasis mine.

> mystic adepts following this Way have access to all **non-adept** metamagic abilities for which they meet the prerequisites.
