### ISSUE TITLE
Some Skills are displayed wrong and Skillname ist cut off

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2526]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.16?
Environment: Windows 10 x64 1709
Runtime: 4.7

### Expected behaviour
Be able to read all skills

### Actual behaviour
Same Skillsnames are cut off and the sorting is wrong in same skills.
See screenshot 

![fertigkeiten deutsch](https://user-images.githubusercontent.com/12108972/36661026-61aac22a-1ada-11e8-9ece-1258dc64bec5.JPG)

### Steps to reproduce the behaviour
Open Char, does not matter if already created or still WiP, the error is in both.
Language seems not to affect the error, check german and english.

### Link to affected character file
(Enter text here)

**Comment by ReallyDarkMatter** [comment]
Just checked v5.198.19 and it seems that bug was fixed.

**Comment by ReallyDarkMatter** [comment]
Okay closed to early issue is back in 5.198.21

**Comment by ReallyDarkMatter** [comment]
Bug is back in 5.199.1

**Comment by chummer5a** [comment]
Seems to be resolved in current builds. Comment if not and I'll reopen it.

**Comment by ReallyDarkMatter** [comment]
Sorry wanted to comment last week, but to much to do.
I get this all the time on my Lenovo T420 with the Resolution of 1600 x 900.
Then i drag the bondery on the left side of Active Skills just a Little bit and then everything is renderd correct. It does not matter if i move it left or Right.
On other PCs i don't have this problem
