### ISSUE TITLE
Deleting Negative Qualitiy in Debt add Karma instead of removing it. 

### ISSUE THREAD

**Issue by Seeron** [chummer5a/chummer5a#2528]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.198
Environment: (Operating system here. If it persists over multiple OS's list them all)
Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
.NET 4.5.1

### Expected behaviour
When I delete In Debt 15, while I dont have enough Karma (30 are the costs to remove it) I expect it to either go into negative Karma or show an Error Message.

### Actual behaviour
When I delete the Quality, it adds 30 Karma instead. 

### Steps to reproduce the behaviour
Open the attached Character, select the Negative Quality in Debt and Delete it

### Link to affected character file
http://www.rapidshare.com.cn/cXHFxGW
https://www.mediafire.com/file/0jaxvfrpvsi7ium/Bj%C3%B6rn_remade.chum5

**Comment by DelnarErsike** [comment]
I believe this same issue was reported a few weeks back and was fixed in the Nightly branch. Could you see if you can reproduce the issue with the latest Nightly version?

**Comment by Seeron** [comment]
ok, tested it with the nightly build and works now. Thanks
