### ISSUE TITLE
Update Firewall Error

### ISSUE THREAD

**Issue by warderbrad** [chummer5a/chummer5a#2529]
I have the same issue which was reported in issue [2247](https://github.com/chummer5a/chummer5a/issues/2247): Did something change with the updater around v.13 to present? 

I have tried starting the updater multiple times and it does not have any new effect.  I noticed that the OP had replied to the solution saying it did not correct his issue either.  

Please advise.

**Comment by Zitchas** [comment]
I was in the midst of a flurry of character builds at the time, so I ended up just downloading the latest release and re-installing chummer. I figured that if he had in fact made changes to the updater, it was probably better to give things a clean slate so things could move forward with the new updater.

That being said, this weekend the updater has started failing to get the update again, with the same error messages as back then. 

(I'm currently on v5.198.8, and it is giving me "failed to connect to update server. Please check your firewall." messages)

**Comment by chummer5a** [comment]
The next nightly will add some additional logging to check the update method. Won't do you any good until the nightly after next, but once we push another build, if you have Use Logging enabled in options, we'll be able to get a slightly better idea of what's going wrong.
