### ISSUE TITLE
5.168 - Skill Rank / BP Issue

### ISSUE THREAD

**Issue by Shiwo** [chummer5a/chummer5a#253]
Build Mode, after save and reload : 
- BP Points added to skills became 0
- Total Rank (Skill Rating + Attribute) remained the "original saved one", even both Points and Karma are 0. So if I had Rank 3 and Attribute 3 before the reload, total will be 6, until I modify the BP or Karma rank, then it will refreshed.
- BP went to negative
- Active Skill points on Build Summary went back to the maximum
- Knowledge Skills have the same issue

**Comment by joha4270** [comment]
Not sure what BP you are talking about, BP are a build system present in 4th ed and due to chummer5a being based on chummer4 sometimes it will incorrectly report something as being BP instead of karma. 

Anything else here is fixed by 5.169
