### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by skuben** [chummer5a/chummer5a#2532]
When clicking on "Check for updates", I get the following error

"Chummer was not able to connect to the update server. Please check your firewall and proxy settings"

I don't have any firewall or proxy settings.  This happens to me on both my Win 10 Pro x64bit computers

### Environment
Chummer Version: 5.198.0
Environment: Windows 10 Pro (on 2 different computers)
Runtime: 4.7.02556

### Expected behaviour
I expect Chummer to connect to the chummer update server and look for updates

### Actual behaviour
it fails with "Chummer was not able to connect to the update server. Please check your firewall and proxy settings"

### Steps to reproduce the behaviour
The process is repeatable

### Link to affected character file
not appropriate

**Comment by Zitchas** [comment]
Reproduced using two windows 10 (64bit) machines that started out with v 5.198.8 and 5.197.0 respectively (both trying to update to latest nightly).

**Comment by skuben** [comment]
Just tried the latest nightly build 5.198.17, and it is happening with that too.  Here is the complete error message

Chummer was unable to connect to the update server.  Please check your firewall and proxy settings.

Error Message:
System.Net.WebException:  The request was aborted: Could not create SSL/TLS secure channel..

**Comment by Zitchas** [comment]
I just tried as well, and got a similar (but not identical) message.

![2018-02-27 chummer update error](https://user-images.githubusercontent.com/32169904/36762212-c6111cfe-1bdf-11e8-9d22-6a44f3abc747.PNG)

**Comment by skuben** [comment]
Why is this closed?

**Comment by chummer5a** [comment]
Because it was (presumably) fixed in https://github.com/chummer5a/chummer5a/commit/45ec19ef8e2d0dec4a82b20b69a17ec110fca89a

**Comment by Zitchas** [comment]
I re-installed Chummer when .18 was released, and then successfully updated it a day later to .19, so the update seems to be working properly again.
