### ISSUE TITLE
Incompatibility between Wakyambi and Cyberlegs

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2533]
### Environment
Chummer Version: 5.198.17
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Elf (Wakyambi) can take Cyberlegs, just looses Celerity

### Actual behaviour
Elf (Wakyambi) can't take Cyberlegs (neither Full/Lower/Feet), likely because Celerity incorrectly prevents it (should be the other way around, i.e. Cyberlegs preventing Celerity)

### Steps to reproduce the behaviour
Create a Wakyambi character, try to add Cyberlegs

**Comment by DelnarErsike** [comment]
Celerity is marked as a metatype removable quality specifically for this reason. I'm not closing the issue though, as it's still a usability issue: having to manually remove the Celerity quality, even though it's grayed out, is not something that people might realize they can even do.

**Comment by Zitchas** [comment]
Interesting. I wasn't even aware that grayed out things were removable. I kind of figured them to be permanent elements. (I only just figured out that I could add enhancements to the earbuds that come as part of commlinks/cyberdecks...) Up until now I've been adding separate earbuds just to add mods to.
