### ISSUE TITLE
Sprite Rating not editable

### ISSUE THREAD

**Issue by SmartTrigger** [chummer5a/chummer5a#2534]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.0
Environment: Win 10 x64
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When adding a sprite I'd expect the rating to be editable.

### Actual behaviour
When adding a sprite the rating is fixed at RES * 2 and the box grayed out.

### Steps to reproduce the behaviour
1. Create New Char
2. Create Technomancer
3. Add Sprite

### Link to affected character file
https://drive.google.com/file/d/1Xj_nbjO01_7msgVIDrq9RK1D2VroEO33/view?usp=sharing

**Comment by chummer5a** [comment]
It's actually RAW that Spirits and Sprites are set to MAG/RES at creation. Latest commit fixes the incorrect doubling.
