### ISSUE TITLE
Fetishes reduce drain by 4 instead of by 2

### ISSUE THREAD

**Issue by TheMalle** [chummer5a/chummer5a#2535]
Fetishes reduce drain by 4 instead of by 2, at least during character creation. The window where you select the spell correctly labels the drain while the drain shown when selecting the spell is wrong 

![image](https://user-images.githubusercontent.com/22431531/36743030-80e1f0ae-1be9-11e8-9653-54c63e2e6d77.png) 

![image](https://user-images.githubusercontent.com/22431531/36743060-94752730-1be9-11e8-9caf-de69d04d4e69.png)

### Environment
Chummer Version: 5.197.1.0
Environment: Windows 8.1
Runtime: Don't know (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Fetish reduces drain by 2
Fetish drain reduction should be listed when hovering over the DV field

### Actual behaviour
Fetish reduces drain by 4
Fetish drain reduction is not listed when hovering over the DV field

### Steps to reproduce the behaviour
Create a spellcaster (verified: magician, aspected magician).
Press the button to add a spell and mark it as limited (verified: Shape [Material]; drain F-4 including the fetish)
Add the spell and check the DV field (verified: Shape [Material], drain F-6)
Hover over the DV field to view the drain value details

### Link to affected character file
https://pastebin.com/raw/hBxJpDZa

**Comment by DelnarErsike** [comment]
I believe the issue was fixed between 5.197.1 and 5.198. Could you please update to the latest stable version of Chummer and verify this?

**Comment by TheMalle** [comment]
Yeah, it's fixed. I thought I had checked for updates, but must've misread the version here on github (and the update in chummer said it wasn't playing well with my firewall). You can close this,
