### ISSUE TITLE
Adepts & magic traditions

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2537]
### Environment
Chummer Version: 5.198.17
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Adepts can enter career mode without choosing a magic tradition

### Actual behaviour
Adepts need to choose a magic tradition before entering career mode

### Steps to reproduce the behaviour
Create an adept, don't choose a tradition, try to move to career mode

**Comment by DelnarErsike** [comment]
If I am not mistaken, this is not a bug. Foci are still prepared based on the user's tradition, so while a Physical Adept does not have access to spells or spirits from a tradition and their drain is always BOD + WIL for adept powers, they still need to choose a tradition. The core rulebook's example on tattoo Qi foci even states that they are for the Tantric tradition (though this Tradition has not been fleshed out in any book AFAIK).

**Comment by Sturmkind** [comment]
So, if I am not mistaken, Chummer offers no option to choose a Foci's tradition at all...

As such this is a "feature", that gives each adept a field on their character sheet with completely irrelevant information (drain does not match, spirit types are not used, etc.) for fluff reasons only?  
Sorry, but I don't really see the sound reasoning behind that...

If this is really as intended by all means keep it, but imho it's not necessary. Maybe as a compromise make it an optional rule?

**Comment by DelnarErsike** [comment]
Adept traditions are not just fluff reasons: adepts need to transcribe spirit formulae if they're in a different tradition from your own if you want to use them for ally spirits, adepts performing rituals must do so in a lodge aligned with their tradition, adepts get penalties if they are assisting in a ritual with someone who is in a different tradition from theirs, and they cannot use foci that do not belong to your tradition (i.e. even if the focus becomes unbound from the original owner, if it's in a different tradition from the adept, the adept cannot then bind it to themselves). All of these are mechanical effects that exist in RAW, even if people tend to forget about them... Come to think of it, the issue actually is that Chummer5 doesn't prompt the user to select a tradition when purchasing any related items.

As an aside, the optional rule you mentioned already exists: just choose a Custom tradition for your adept (or any tradition at all), then ignore it during play.

**Comment by aga9** [comment]
Not everyone play with all the sourcebooks and all the rules.

For people playing with only CRB, Adepts cannot perform rituals and have nothing to do with traditions. (The Qi focus you mentioned looks like pure fluff, since Tantric doesn't exist mechanically anyway.)

Sure, you can picking either a Custom tradition or any random tradition. But that's a workaround, not an option.

I guess the best compromise is to either:
- Have a choice in the "Optional Rules" section to allow the Adept Tradition requirement to be turned off.
- Make the validation warning more of a gentle reminder than show stopper (similar to the unused Karma/points reminders), and allowing the user to ignore this warning and proceed into Career mode.

**Comment by Zitchas** [comment]
Perhaps simply having a "none" option in the list would work, although that might confuse regular mages. 

The optional rule to allow them to disable it would probably work best.

**Comment by davidfoerster** [comment]
> For people playing with only CRB, Adepts cannot perform rituals and have nothing to do with traditions.

This is wrong. Adepts can still *participate* in rituals although they cannot *conduct* them according to the CRB. Ritual participation is influenced by the participants’ magical tradition.

> (The Qi focus you mentioned looks like pure fluff, since Tantric doesn't exist mechanically anyway.)

Wrong again. Focus binding only works on Foci created for the magical tradition to which the Adept adheres. It may seem like fluff superficially but has actual mechanical consequences:

 * A physical adept cannot bind arbitrary foci that they loot from defeated opponents.
 * The physical adept in your group can bind foci crafted by the group’s artificer if and only if they follow the same magical tradition.
