### ISSUE TITLE
Quality: Made Man

### ISSUE THREAD

**Issue by sonicstormer** [chummer5a/chummer5a#254]
My GM assigned my character the Made Man quality. Whenever I go to add it, it gives me a blank Item Selection box. It will also not allow me to add any values into the box. After hitting either Cancel or OK, an error box pops up giving instruction on how to use the error log (Which I happily did). Thought this might be especially interesting as you seem to have a problem with Prime Datahaven Membership in another issue. :P

I posted my chummerlog.txt to pastebin for your convenience. http://pastebin.com/UjVhG76S

EDIT: So I noticed when I added Jackpoint as a group contact for Prime Datahaven Membership, and I tried adding Made Man for shits and giggles, it selected it as a qualifying group contact, hilariously displaying as "Made Man (Jackpoint)" XD. So it seems this problem can be avoided by first creating a group contact and then applying the quality to that contact after the fact as opposed to selecting the quality and then creating a group contact as a result. Something to look at at least, but at least I fixed my problem.

**Comment by joha4270** [comment]
Made man requires you to select an existing group contact, it is not able to create one itself.

**Comment by chummer5a** [comment]
Actually I was fiddling with the selectcontact key a while back, it will
automatically grab a suitable contact. If you don't actually have any
contact groups it will behave like that. Doesn't seem to be doing the
update to Made Man's Loyalty either.

**Comment by sonicstormer** [comment]
No it isn't. Just reads as "M" on my screen.

**Comment by joha4270** [comment]
the small quickread text being "(connection/M)" Connection is being the contact connection?

This is intentional, it displays G for group contacts, M for made man, or the loyalty in any other case.
