### ISSUE TITLE
 Issue: - crash with linguasoft

### ISSUE THREAD

**Issue by goldeneye71** [chummer5a/chummer5a#2541]
### Environment
Crash ID: 149a1924-0a61-446d-afaf-c6f57a44f8e6
Chummer Version: 5.197.31
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
when pressing delete to remove linguasoft, or modify rating of linguasoft, expect deletion or alteration

### Actual behaviour
chummer crashes

### Steps to reproduce the behaviour
add linguasoft (mine is R5)
try to alter rating or delete linguasoft

**Comment by chummer5a** [comment]
Resolved in current nightly builds
