### ISSUE TITLE
Any change to Essence reduces special attributes

### ISSUE THREAD

**Issue by KoldunicSorcerer** [chummer5a/chummer5a#2543]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.19
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
A character with a Magic attribute of any number greater than 0 has its current and maximum Magic reduced by the amount of Essence (rounded up) lost to augmentations.
Specific example: a twice-initiated mage with Magic 8 gets a deltaware datajack, deltaware rating 1 cyber eyes, and an alphaware clean metabolism; resulting Essence 5.8, resulting current/maximum Magic 7/7. Undoing the expense on the Karma and Nuyen page reverts all changes to Magic attribute.

### Actual behaviour
A character whose Magic attribute has been raised above 6 (after initiation) has its maximum Magic reduced correctly, but loses a full point from current Magic attribute for each individual augmentation.
Specific example: a twice-initiated mage with Magic 8 gets a deltaware datajack, deltaware rating 1 cyber eyes, and an alphaware clean metabolism; resulting Essence 5.8, resulting current/maximum Magic 5/7. Undoing the expense on the Karma and Nuyen page reverts the reduction to maximum Magic, but not to current Magic.

### Steps to reproduce the behaviour
Initiated another character, raised his Magic, added cyberware; again, each individual augmentation reduced the character's current (but not maximum) magic by 1. Attempts to augment an uninitiated mage, or with a mage who has initiated but not raised his Magic attribute yet, behave as expected.

### Link to affected character file
https://drive.google.com/file/d/12m4kzrOQ8izAuLEfUrVeAk7QeiT8ZQj6/view?usp=sharing

**Comment by chummer5a** [comment]
Interesting. It's decrementing whenever essence changes at all.
