### ISSUE TITLE
Initiation applies double; character gains 2 grades per initiation

### ISSUE THREAD

**Issue by KoldunicSorcerer** [chummer5a/chummer5a#2544]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.19
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding each initiation grade raises maximum Magic by 1, and the option to add a new grade will always show one grade higher than the character currently has.

### Actual behaviour
Adding each initiation grade raises maximum Magic by 2. The first displays as "Grade 1" and is reflected in the Karma and Nuyen tab as 0 to 1 as expected. The second displays as "Grade 3" and is reflected as 2 to 3. When Schooling is selected, the nuyen expense is reflected as 1 grade higher than the karma expense; so the first initiate grade is reflected in the karma column as 0 to 1, and the nuyen column as 1 to 2, etc. Attempting to Remove Initiate Grade on the highest initiate grade gives the error, "You must delete the highest grade first."

### Steps to reproduce the behaviour
Behaves this way on every mage and mystic adept I have initiated in the current version of Chummer.

**Comment by chummer5a** [comment]
This will be fixed in the next nightly build; to fix your existing characters open it in notepad and adjust the initiation node to the correct value.

**Comment by KoldunicSorcerer** [comment]
Behaves correctly now, thank you! However, it still displays incorrectly in the Nuyen column if Schooling is selected.
