### ISSUE TITLE
Broken skill groups despite not being broken

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2547]
### Environment
Chummer Version: 5.198.19
Environment: Windows 7
Runtime: 4.7.1

### Expected behaviour
Skill groups count as their skill value when all corresponding skills are at the same rating and no specializations are present.

### Actual behaviour
Skill groups count as broken despite all corresponding skills being the same rating and no specializations are present.

### Steps to reproduce the behaviour
Not sure, but I have it on all my characters.

![brokenskills](https://user-images.githubusercontent.com/27777147/36864132-0df5686a-1d8c-11e8-8fbf-a3d2b7bf2ba7.PNG)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate it. Can you confirm that you have the optional rule 'Allow Skills to be re-Grouped if all Ratings are the same' enabled? Should be on the Optional Rules tab.

**Comment by MaraFaye** [comment]
The rule is enabled and it happens on all my chars, doesn't matter if they are from like 3 versions ago or freshly created, as soon as they are in career mode they groups are shown as broken and I can't raise it as a group anymore. Put up one of the chars as zip file in creation mode ready to get into career mode, and in career mode.

[Chars.zip](https://github.com/chummer5a/chummer5a/files/1775569/Chars.zip)

**Comment by chummer5a** [comment]
Appears to be resolved in current nightly builds.
