### ISSUE TITLE
Hacking Program: Nuke-From-Orbit

### ISSUE THREAD

**Issue by sonicstormer** [chummer5a/chummer5a#255]
The hacking program, "Nuke-From-Orbit" is listed at an availability 4R, when it should be 12F. This is given in Data Trails page 57, "This upgraded and outright illegal program.....", "Nuke-From-Orbit has an availability rating of 12F" Also the name of the program is broken up by "-"s, but that's just a nitpick.

**Comment by joha4270** [comment]
Fixed in 5.169

**Comment by sonicstormer** [comment]
Thanks dude! Keep up the great work.
