### ISSUE TITLE
Elder God Tradition

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#2552]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.17

The Elder God Tradition is supposed to give a -2 to all Drain rolls, and a +3 to all Illusion spells.

**Comment by DelnarErsike** [comment]
Fixed in commit 833db54ef30ec1edcff58e76adf56c5ea961bd1d.
