### ISSUE TITLE
String problem in Sheets

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2553]
The file `Shadowrun 5 set.xlst` has the following problematic code:

```
                <th width="25%">
                  <xsl:value-of select="$lang.Physical"/>
                  <xsl:text> </xsl:text>
                  <xsl:value-of select="$lang.Attributes"/>
                </th>
                <th width="25%">
                  <xsl:value-of select="$lang.Mental"/>
                  <xsl:text> </xsl:text>
                  <xsl:value-of select="$lang.Attributes"/>
                </th>
                <th width="25%">
                  <xsl:value-of select="$lang.Special"/>
                  <xsl:text> </xsl:text>
                  <xsl:value-of select="$lang.Attributes"/>
                </th>
```

This works in English but probably fails in other languages that write adjectives differently. For example, in Portuguese the order is switched and the adjective agrees with the plural of the noun. A solution for this is to create variables for those composite words like it already exists for limits (`lang.MentalLimit`, etc).
I propose that the following are created (and propagated to the translations) and replaced in this sheet file:
- lang.PhysicalAttributes
- lang.MentalAttributes
- lang.SpecialAttributes

**Comment by Lochabar** [comment]
If you could provide the translations I will add them to the language files.

I will double check the French and German translations using Google Translate unless someone can confirm the values.

I will create the Chinese version by combining the existing characters unless someone can provide them.

**Comment by luizbgomide** [comment]
For Portuguese they are:
```
  <xsl:variable name="lang.PhysicalAttributes" select="'Atributos Físicos'"/>
  <xsl:variable name="lang.MentalAttributes" select="'Atributos Mentais'"/>
  <xsl:variable name="lang.SpecialAttributes" select="'Atributos Especiais'"/>
```

**Comment by holgerschlegel** [comment]
For German the values would be:

```
<xsl:variable name="lang.PhysicalAttributes" select="'Körperliche Attribute'"/>
<xsl:variable name="lang.MentalAttributes" select="'Geistige Attribute'"/>
<xsl:variable name="lang.SpecialAttributes" select="'Spezialattribute'"/>
```

**Comment by luizbgomide** [comment]
A friend of mine gave me the French Translation:
```
  <xsl:variable name="lang.PhysicalAttributes" select="'Attributs physiques'"/>
  <xsl:variable name="lang.MentalAttributes" select="'Attributs Mentaux '"/>
  <xsl:variable name="lang.SpecialAttributes" select="'Attributs Spéciaux'"/>
```

**Comment by Lochabar** [comment]
Is it okay to close this issue?
