### ISSUE TITLE
Adding a Plugin to a cybernetic piece in Career mode crashing

### ISSUE THREAD

**Issue by JoeCool715** [chummer5a/chummer5a#2554]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (5.198.0)
Environment: (Windows 10 Home)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
adding a plugin can be used

### Actual behaviour
Chummer is locking up and needs to be restarted.  Still unable to add plugins into cyber gear (attempting arm)

### Steps to reproduce the behaviour
right click on cybernetic arm, click "add a plugin"

### Link to affected character file
(Enter text her
[Sledge Take 3 Career.txt](https://github.com/chummer5a/chummer5a/files/1777818/Sledge.Take.3.Career.txt)
e)

**Comment by JoeCool715** [comment]
Coudl you please advise if there is a resolution that I may be able to do on my end?

**Comment by DelnarErsike** [comment]
The fix should be present in nightly releases starting with 5.198.23. Short of compiling your own version of Chummer5a, there is nothing you can do on your end to fix it, as the issue is caused by an oversight in the C# code.

**Comment by JoeCool715** [comment]
Thank you so much for the clarity!  I am looking forward to the next download.  Thank you for all the help with making such an amazing product!
