### ISSUE TITLE
PBY Catalina 2 factory mods

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2555]
### Environment
Chummer Version: 5.198.21
Environment: Windows 7
Runtime: 4.7.1

### Expected behaviour
The Catalina 2 should have from the get go:
ECM 3
Improved Economy
1x Heavy weapon mount (external, fixed, remote controlled)
2x Heavy weapon mount (external, flexible, remote controlled)
2x Heavy weapon mount (external, fixed, remote controlled)

### Actual behaviour
Has only 3x heavy weapon mount (flexible, manual, external)
Aside from that all other stats are correct.

### Steps to reproduce the behaviour
Look into the Vehicle list after adding one.

### Link to affected character file
Screensnip from Asphaltkrieger (german Rigger5), listing the factory mods and the "similar models" for reference.
![catalina](https://user-images.githubusercontent.com/27777147/36938500-968f967c-1f22-11e8-9619-c125687ee042.PNG)

**Comment by Zitchas** [comment]
The English Rigger 5 only lists "Heavy weapon mounts (nose, right/left waist)" in the stat box, but the fluff text does mention 2 hard-points on the wings. To me a weapon hard point would mechanically translate as a remote operated fixed heavy weapons mount. I don't know if there is errata on that, though.

**Comment by MaraFaye** [comment]
Yeah, one fixed gun on the nose, 2 flexible to the sides and 1 flexible under each wing

Translation:
ECM 3, reduced consumption (Improved Economy mod), heavy weapon mount (external, fixed, remote) on the nose, one heavy weapon mount (external, flexible, remote) right and left, one heavy weapon mount (external, fixed, remote controlled) under each wing.

**Comment by MaraFaye** [comment]
Also from all what I could find there doesn't exist a formal errata. The german one is kind of errata'ed since Pegasus (german publisher) gets back on catalyst for errata and questions and includes the changes directly.
