### ISSUE TITLE
Lifestyle: Sheet will not allow you to add a new lifestyle properly

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#256]
Currently on Build 168. When adding a lifestyle, it does not give you the appropriate options such as extra secure, etc. Furthermore when adding a new lifestyle to a career mode sheet, it will not allow you to add or remove months paid. The option is greyed out. Sheet works fine in a modded version of old Chummer5 (not 5a) build 139.

**Comment by chummer5a** [comment]
Fixed in 5.177.
