### ISSUE TITLE
Weapon Mounts / Ammo Bins

### ISSUE THREAD

**Issue by Aquitanius** [chummer5a/chummer5a#2561]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The Weapon Mount slider can hold Ammo Bins and doesn't bug out the program.

### Actual behaviour
Weapon Mount sliders in Career Mode have the following issues:
1) You cannot right-click weapon mounts created in Create Mode in Career Mode to add Weapons and or the modification Ammo Bin.
2) After clicking or right-clicking the Weapon Mount slider on the Rotodrone(German), the Mod Points reset to 0 visually.
3) Trying to add new Weapon Mounts to drones/vehicles with pre-existing Weapon Mounts crashes chummer without creating an error log, but reports following errors: 
![weaponmountcrashchummer](https://user-images.githubusercontent.com/37055784/36955102-9de778c2-2026-11e8-8772-4980953a1a4a.jpg)
(Windows error window: 'Chummer funktioniert nicht mehr' error window, maybe translates to 'Chummer ceased to function'?)

### Steps to reproduce the behaviour
As in Actual Behaviour

### Link to affected character file
https://www.dropbox.com/s/wrbkhki0c0c6ltu/Maus.chum5?dl=0

**Comment by chummer5a** [comment]
Unable to replicate in current nightly builds.

**Comment by Aquitanius** [comment]
Ok. In the current nightly build (4 hours ago) issue 1 and 3 don't happen to me either.

Issue 2 is different in the nightly build. The first Rotodrone in the inventory of my file always displays correctly now, but the second Rotodrone has the same equipment but lists its Weapon Mod Points as 0/7 always.

Thanks for the quick response!
Also sorry for not trying the nightly first. I read all fix notes and didn't think it would change anything. My mistake.
