### ISSUE TITLE
Character Printing Blanks

### ISSUE THREAD

**Issue by chickenoxo** [chummer5a/chummer5a#2565]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.25
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Character generates a character sheet with my stats for me to print or keep as a PDF

### Actual behavior
Having some issues with PDF's not printing / generating just comes up blank. Newest build. Happens to all characters plus new made ones, not one specifically. All sheet versions, html and PDF

### Steps to reproduce the behavior
No idea. It works with version .22 though

### Link to the affected character file
[Vektor.zip](https://github.com/chummer5a/chummer5a/files/1787768/Vektor.zip)

**Comment by Lochabar** [comment]
Having the same problem. Printing works with .24, so something changed in the latest nightly.

**Comment by Lochabar** [comment]
Printing is working again in .26
