### ISSUE TITLE
New build (5.168) cannot make a character without breaking outright.

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#257]
http://i.imgur.com/coKaRcH.png

This is what a character sheet loaded into the current Chummer5a build looks like. You can build a character like normal but this is the result when trying to make a new character and reloading the save to tweak things. I roll backed to the previous version and things are fine.

**Comment by chummer5a** [comment]
Technically speaking, 5.166 - 5.167 is the broken one here. There was an issue that prevented skills from being saved to the character sheet properly. The Rating is preserved, but the Base and Karma values were not. It's resolved in 5.168, but the appropriate values obviously can't be loaded. I'm considering writing in a shim that would try to figure out what your rating was. Best bet aside from that, remake your character from scratch I'm afraid.

**Comment by MandozerTheGreat** [comment]
Uhh I did remake the character from scratch and it still did this.

**Comment by chummer5a** [comment]
Shit. I'll take another look.

**Comment by MandozerTheGreat** [comment]
Yeah man it's a thing. Sorry if that wasn't clear from the get go. I
wouldn't have sweat it too much as long as I could recreate sheets on the
new version fine but ya.
