### ISSUE TITLE
crash when trying export character

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#2570]
### Environment
Crash ID: bff01451-d558-450b-bff0-d2f49d215fed
Chummer Version: 5.198.25
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
character exported

### Actual behaviour
trying to export cause error

### Steps to reproduce the behaviour
click export in File menu

**Comment by chummer5a** [comment]
Can't reproduce. Please provide a sample character or the exception.txt file generated by the crash.
