### ISSUE TITLE
Enhancement: Show WiFi plus

### ISSUE THREAD

**Issue by Angelofpain** [chummer5a/chummer5a#2571]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.11
Environment: windows7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Maybe it IS possible to Show it Like this:
Skill X 8 (wifi+2w6) so i know that with WiFi active i can Roll 2 more

### Actual behaviour
WiFi plus ist Not shown in skills or items

### Steps to reproduce the behaviour
Take Smartgun on weapon

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Imnplemented in current builds.
