### ISSUE TITLE
Crash after selling gear

### ISSUE THREAD

**Issue by BCottingham** [chummer5a/chummer5a#2574]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Expected item to be sold, at requested percentage (50), and removed from my inventory and replaced by lovely, lovely nuyen.

### Actual behaviour
Using the sell function did not remove item, nor give me delicious nuyen. Instead, the cursor spun for a bit and then nothing happened. Clicking again on the gear in question, Chummer swallows its own tongue and dies.

### Steps to reproduce the behaviour
select gear to sell, in this case, armored clothing with 3 mods (nonconductivity, gel packs, and electrochromatic.
Click the arrow attached to the delete button to bring up the sell function and click it.
Click okay on the sell item, with the default percentage (50.)
Notice the item is still there.
Left click on one of the three added mods.
Crash.

### Link to affected character file
(Enter text here)
character is not online

**Comment by chummer5a** [comment]
Can't replicate it in current nightly builds.
