### ISSUE TITLE
Text error in advanced life style qualities

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2576]
### Environment
Chummer Version: 5.198.27
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
According to the German rulebook the thresholds should be "14 or less" and "15 or more".

### Actual behaviour
The title of the garage qualities for cars contain wrong car body thresholds.
One is titled "Garage (Car (Body 4 or Less))" and the other one "Garage (Car (Body 5 or More))". There are also corresponding onces for "Cramped Garage".

According to the German rule book ("Schattenläufer", table on page 226), the body thesholds should be "14 or less" and "15 or more" - not 4 or less and 5 or more.
Of course, the German data translations also missing the "1" digit in the texts.

As I do not have access to the English rulebook, I can not check the values in the original English book.

### Steps to reproduce the behaviour
Open dialog to create an advanced life style.
Open dialog to add a quality.
Look for "Garage (Car"

**Comment by OLStefan** [comment]
That is just another issue where the german version seems to be erratta'd. In the english version it the thresholds are '4 or less' and '5 or more' which don't make a lot of sense looking at the body values of cars and even bikes (there are only 4 bikes with a Body of 4 or less), but it is still what is listed in the book.

**Comment by cnschu** [comment]
it's an obvious fault, errata'd in the german edition.
what do we do?
