### ISSUE TITLE
Application Crash: Creating new character

### ISSUE THREAD

**Issue by garryman90** [chummer5a/chummer5a#2580]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.0
Environment: Win 10
Runtime: don't know

### Expected behaviour
Creatin new character

### Actual behaviour
Application crashes

### Steps to reproduce the behaviour
Create new character (loading characters works fine)

Older versions of Chummer still work.

### Link to affected character file
Any new one

Crash report: imgur.com/a/CdZVd
(My Avast alarms me that Crashhandler is harming my system, so I don't have a crash report, but only this screenshot)

**Comment by chummer5a** [comment]
Unable to replicate in current builds.
