### ISSUE TITLE
Spell list crash

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2587]
### Environment
Chummer Version: 5.198.29
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Switching very fast between spells, by keyboard scrolling, does just that.

### Actual behaviour
Keyboard scrolling keeps crashing chummer sooner or later (inconsistent).

### Steps to reproduce the behaviour
Not sure but I tried it 7 times so far and every time it crashed sooner or later, I tested it by using the Detection spells and usually it crashed at Death Replay or Detect Object.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Resolved in 5.198.30.
