### ISSUE TITLE
Lifestyle Notes Error

### ISSUE THREAD

**Issue by Battleclad** [chummer5a/chummer5a#2591]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.198.30
Environment: Windows 10

### Expected behaviour
Stored note to appear on clicking notes option of Lifestyle

### Actual behaviour
Blank note appears instead

**Comment by chummer5a** [comment]
Can't reproduce it in current builds. Anything more specific to reproduce it?

**Comment by Battleclad** [comment]
Seems to get lost when you load a save as well.
