### ISSUE TITLE
Favourite Function

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2597]
### Environment
Chummer Version: 5.198.32
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Marking character adds them to the list of favourited characters, no matter how many.

### Actual behaviour
It only adds the last 4 marked characters to the list, marking new one replaces some of the existing.

### Steps to reproduce the behaviour
Add 4 different chars to the list of favourites, close chummer, open and add a few more, close  and open again, the list should not show all of the marked chars.

### Link to affected character file
(Enter text here)

**Comment by DelnarErsike** [comment]
Currently only up to 10 characters can be stored as favorites due to the way the favorite-saving system is implemented. Did you ever exceed 10 favorite'd characters whenever you encountered this issue?

**Comment by MaraFaye** [comment]
Nope, It was 4, I fiddled around with it and solved it for now, just cleared all characters from favourite and last used section, then loaded them again and now it's fixed.
