### ISSUE TITLE
Vehicle pre-built modifications

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2598]
### Environment
Chummer Version: 5.198.32
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Vehicle and drone modifications that come with the vehicle count towards the amount of available modification points as per the red box on Rigger 5 P. 43 (near the motorcycle section if there is a difference between english and german version page numbers).

### Actual behaviour
Factory mods are not counting towards their respective categories module points, potencially allowing for much more mods then intended to be used.

### Steps to reproduce the behaviour
Look at a vehicle that comes with pre-built mods, the Toyota Gopher comes with Off-Road Suspension, so his available mod points for the category powertrain should be 2/14 instead of 0/14.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Doesn't seem to be RAW for it in in the English version that I can see, aside from possibly the rules about removing modifications.

**Comment by MaraFaye** [comment]
![default](https://user-images.githubusercontent.com/27777147/37538978-a3ec1554-2952-11e8-8bff-55fc45005391.PNG)

This box says basically that, existing mods take up mod slots as per normal, taking the Jeep Trailblazer as an example how it has only 6 mod points in the powertrain category left because of the offroad-suspension and multifuel engine it comes with.

Would love if it was different though....

**Comment by chummer5a** [comment]
https://forums.shadowruntabletop.com/index.php?topic=22807.msg496834#msg496834

Raised for query on the forums.

**Comment by MaraFaye** [comment]
Doesn't look like anyone wants to aswer there.
