### ISSUE TITLE
Casemod cannot be removed from Cyberlimbs

### ISSUE THREAD

**Issue by allpossibledogs** [chummer5a/chummer5a#260]
Once added onto a Cyberlimb (Synthetic or Obvious) the Casemod cannot be removed claiming that it is now a base feature of the Cyberware.

![image](https://cloud.githubusercontent.com/assets/7044046/8468053/9c2bfdae-2034-11e5-9afe-f489ce278506.png)

**Comment by chummer5a** [comment]
Resolved in hotfix. Please run the Updater or download https://www.dropbox.com/s/osmokerg8b0isdx/cyberware.xml?dl=1 into your Data folder.
