### ISSUE TITLE
Maximum number of Complex Forms incorrect.

### ISSUE THREAD

**Issue by IrNot1337** [chummer5a/chummer5a#2601]
### Environment
Chummer Version: 5.198.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Maximum Number of Complex Forms should be Resonance x 2. 
Per https://forums.shadowruntabletop.com/index.php?topic=24595.msg487861#msg487861

### Actual behaviour
Maximum number of Complex Forms is Logic attribute.

### Steps to reproduce the behaviour
Add Complex Forms to technomancer.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Resolved in current nightly builds.
