### ISSUE TITLE
Life module skills issues

### ISSUE THREAD

**Issue by Truebane667** [chummer5a/chummer5a#2605]
### Environment
Chummer Version: 5.198.0
Environment: Windows 10 
Runtime:  .NET ???

### Expected behaviour
When selecting a "Life Module" you get an Attribute bonus and a skill bonus.
Ex. CAS Sinless: Body +1, Knowledge: [City] +1, Etiquette +1, Knowledge: History +1, Knowledge: CAS +1

### Actual behaviour
I get the "Sinless" Quality (as I should).
I get the "Body +1" as I should.
I do not get the skills.
After trying several races and Life Modules, I have had the same problem.

### Steps to reproduce the behaviour
Start program
Create new character
Select "Life Module"
Select any Race (Dwarf, Elf, Orc and Pixie I have tried)
Select a life module
Check Skill tab
You will see a lack of skills being shown.

### Link to affected character file
None. I don't know how. :(

**Comment by Truebane667** [comment]
Addendum to problem

Things worked properly in Version 5.195.0

**Comment by Truebane667** [comment]
I'm an IDIOT!!!!!!!!!!!!!!!!

**Comment by OLStefan** [comment]
Life Modules are being reworked right now. These issue is part of #2000.
