### ISSUE TITLE
Bug in calculation of Recoil Compensation

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#2607]
### Environment
Chummer Version: 5.198.40
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
Recoil Compensation is calculated as 1 (free) + STR/3 (rounded up) + Modifiers 
(as per Core Rulebook p. 175)

### Actual behaviour
Recoil Compensation seems to be calculated as 1 (free) + STR/4 (rounded down) + Modifiers

### Steps to reproduce the behaviour
Create a character (i.e. Human) with Strength score of 3, add a Firearm and look at the RC value (should be 2 if no other modifiers apply, is currenlty 1), RC first goes up to 2 when Strength is raised to 4 whereas every character should start with at least RC 2 (1 free + 1/3 rounded up to 1)

**Comment by Sturmkind** [comment]
somehow this bug seems to extend to Encumberance calculation as well... My Troll with 12 Strength was encumbered (-2) by his +11 extra armor (Ballistic Mask, Shield, Helmet, Forarm Guards)

**Comment by DelnarErsike** [comment]
So, I could replicate the recoil compensation issue using my own characters in the dev build, but not the armor encumbrance issue, which is actually a completely separate problem. Could you upload a savefile of that troll so that I can replicate the issue and see what's causing it?

**Comment by Sturmkind** [comment]
Sure, here you go. Tested on the current build.
[Test.zip](https://github.com/chummer5a/chummer5a/files/1848086/Test.zip)
