### ISSUE TITLE
Bug with Mentor Spirit: Wolf and powerpoints in build and Career mode.

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#261]
Basically this mentor spirit gives an adept  attribute boost (AGI) at power rating 2 free. What I find is everytime I reload either the build or the career mode sheet, that it'll always say I have .5 power points free. It never saves the 2 other levels I invest in said power even if I save repeatedly. Is there a workaround? Otherwise nbd I'll live. Its really a minor thing.

**Comment by joha4270** [comment]
There have been issues before with adept from multiple sources and saving. Not currently being investigated, as other stuff are higher on the priority list, but it would be nice if you could upload the sheet for sometime in the future.

**Comment by MandozerTheGreat** [comment]
https://drive.google.com/file/d/0Bwu-ssbXNGYMSmRLeFpidEc1RDg/edit?usp=docslist_api

**Comment by joha4270** [comment]
Fixed one thing related to free power points in 173, sheet unavailable but i believe it fixed this too.
