### ISSUE TITLE
State of the Art ADL use of Phocine Shapeshifter impossible

### ISSUE THREAD

**Issue by Zeidra-Senester** [chummer5a/chummer5a#2613]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.198.41
Environment: Windows 10
Runtime: .NET 4.7.1

### Expected behaviour
Activating "State of the Art ADL" sourcebook in the options should give access to Phocine (seallike) Shapeshifter.

### Actual behaviour
It doesn't.

I double-checked, and it is fully included in the xml datafiles.

### Steps to reproduce the behaviour
Activating "State of the Art ADL" sourcebook in the options, and trying to create a new character with any method.

**Comment by chummer5a** [comment]
Unable to replicate it.

**Comment by Zeidra-Senester** [comment]
(first, sorry for my non-native english)
What do you mean you can't replicate ? You can actually create a Phocine Shapeshifter ?
If it's of any use : I activated almost all sources but : Nothing Personal, Sail Away Sweet Sister, Seattle Gambit, The Vladivostok Gauntlet and each german sourcebooks but State of Art. No optional rules, no any changes except for French language. 
I have the material content of State of the Art (BMW cars, german cyberdecks, etc…) but I only miss the Phocine metatype.
.
Actually I checked metatypes.xml and I don't have any "bonus" listed in the shapeshifter features (Critter power tab activated, Natural weapons, …), nor the shapeshifting power itself. For example, anything in metatypes.xml between line 13290 and 13313 doesn't apply to my Pantherine shapeshifter at all, nor the Shift (Metahuman Form) power line 13279. Seems like the whoooole shapeshifter system is wrecked for me. I know XML but I don't know of your software interpret it so I'm not really useful, sorry.

**Comment by chummer5a** [comment]
Hrm. Sure you're on .41? There was an issue with the shapeshifters not geting their bonuses properly, but that was resolved in .39.

**Comment by Zeidra-Senester** [comment]
![sans titre](https://user-images.githubusercontent.com/33586179/37865691-7769c2fe-2f80-11e8-9ba0-f678d84b37aa.png)
Sure I am.

**Comment by Zeidra-Senester** [comment]
But I actually have .NET 4.7.1 and lack any .NET 4.5 release. I tryna install 4.5.2 and I tell you back.
I guess I'll download .43 too.

**Comment by Zeidra-Senester** [comment]
Same with .43 by the way.
Runtime: .NET 4.7.1, and Windows doesn't allow me to install 4.5 too.

**Comment by chummer5a** [comment]
Should be resolved in the current nightly build.
