### ISSUE TITLE
Qualities: Consummate Professional, First Impression

### ISSUE THREAD

**Issue by Darklordofiniquity** [chummer5a/chummer5a#2614]
The negative quality consummate professional is supposed to divide career karma by 20 to determine street cred. Chummer is still dividing by the normal 10. 

Also 1st Impression has given me a notoriety of -1. It should just give me situational bonus dice to social interactions only.

### Environment
Chummer Version: 5.198.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
First Impression is on the list of qualities that give you a notoriety reduction. Chummer doesn't currently track conditional skill bonuses. 

Can't replicate the issue with the streetcredmultiplier bonus not applying for Consummate Professional.
