### ISSUE TITLE
Wrong book/page for "SmartSafety Bracelet"?

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2617]
### Environment
Chummer Version: 5.198.43
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
The gear item "SmartSafety Bracelet" is listet as coming from the "R5" book on page 133.
At least the German book does not contain such an item.

On the other side, the book "CF" contains a textual description for a bracelet with that price. The sentence is in the block for the "Cybersafety" bodyware. According to the Chummer5 data file, it should be in page 83 of the English book. In the German book it is on page 86.

As I do not own the English books, I can not check if it contains that description too.

**Comment by chummer5a** [comment]
They're linked to the Lone Star Castle Guard drone in Rigger 5; they would've been overlooked in CF as they weren't a discrete item.

**Comment by holgerschlegel** [comment]
Ok, now I found it in the book (on page 140 in the German book).

Looks like the bracelet mentioned in the R5 book is something different. It is related to weapon safety. And at least the German book does not contain a concrete name for that bracelet.

So this issue can be closed. I'll update the page number for the German book in a future pull request.

**Comment by chummer5a** [comment]
I think they're kinda-sorta the same thing, it's just not called out as a specific company's brand in CF or whatever. When I eventually get around to implementing multi-source items it can get a review I guess.
