### ISSUE TITLE
Tradition: Drain Attributes Frozen

### ISSUE THREAD

**Issue by Vereaux** [chummer5a/chummer5a#2624]
### Environment
Chummer Version: 5.198.47
Environment: Windows 8.1
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
From the pull list for Traditions in the "Spells and Spirits" tab, choosing a tradition should change the attributes used for Drain (Willpower + whatever). It should also calculate the result correctly by combining the two.

### Actual behaviour
It is stuck on "BOD + WIL" and the value won't change unless it is WIL. Changing BOD has no effect on it. Even does this when "Custom" is chosen. 

### Steps to reproduce the behaviour
Make a new character on default selections and go to the "Spells and Spirits" tab.

### Link to affected character file
(Enter text here)

**Comment by drakir75** [comment]
Default selection is Adept. All drain for adepts are WIL + BOD?

**Comment by Vereaux** [comment]
Yeah, but it seems to be working now >.> When I switch it to Magician (didn't realize Adept was the default), it's no longer crashing and is calculating everything correctly. It got fixed somewhere =P

Thank you for replying! Please have a wonderful day! =)

**Comment by drakir75** [comment]
Nice. The chummer team are hard workers and updates are coming nearly every day. (I'm just a user like yourself.)

If everything works, then you can close the issue. 
 Dito on having a nice day, and good luck with your mage.
