### ISSUE TITLE
Lifestyles: Changes to Lifestyle type don't update correctly

### ISSUE THREAD

**Issue by DenStoreFrelser** [chummer5a/chummer5a#2626]
### Environment
Chummer Version: 5.198.47
Environment: Win10
Runtime: Probably .NET 4.5.1

### Expected behaviour
When changing the type of a Lifestyle (Normal or Advanced), the type shown in the list of Lifestyles should automatically update to the new type.

### Actual behaviour
The type in the Lifestyles list does not update correctly after a change. Instead, it updates to the type that the edited Lifestyle had when you opened it. Changing from Street to Squatter won't change anything in the list, but changing from Squatter to Low will then update the Lifestyle in the list to show Squatter. This affects both Normal and Advanced Lifestyles.

The details part and the actual cost to the character update correctly, and reloading the character will sort out the issue.

### Steps to reproduce the behaviour
Add a Squatter Lifestyle to a character.
Open the Lifestyle and change it's type to Low, then close it.
Observe that the Lifestyle is still listed as Squatter in the list.
Open and close the Lifestyle again.
Observe that the Lifestyle is now listed as Low in the list.

Edit: Attempted to make the steps to reproduce a bit clearer.

**Comment by chummer5a** [comment]
Unable to replicate in current builds.

**Comment by DenStoreFrelser** [comment]
The bug is still present as of 5.199.30. I've updated the steps to reproduce to hopefully be more clear.

**Comment by DenStoreFrelser** [comment]
In 5.200.11 this behavior has changed for the worse: Changes made to an existing Lifestyle aren't saved at all, and opening and saving a Lifestyle twice crashes the application. This occurs for both normal and advanced Lifestyles. If you only attempt to change a Lifestyle once, it is then no longer deletable unless you save and reopen the character first.

Opening a non-advanced Lifestyle will show the correct name and Qualities of the Lifestyle you opened, but the type seems to default to Street regardless of what it was earlier. This is not the case for Advanced Lifestyles.

**Comment by chummer5a** [comment]
Seems to be working correctly in current builds, can you confirm?

**Comment by CantRushThis** [comment]
Still crashes on .50 for me, both while editing existing and new lifestyles.
