### ISSUE TITLE
Finalized Karma System Character Knowledge Issue

### ISSUE THREAD

**Issue by Shiwo** [chummer5a/chummer5a#263]
Build 169

When I create a character, using Karma system and finalize it, the ratings of the Knowledge Skills became 1.

**Comment by joha4270** [comment]
Can you please upload the sheet where this is happening?

If you have a version before the issue, please include that one too, if not we will deal.

**Comment by Shiwo** [comment]
When I select the "Mark character as Created" and push the save button.

Same issue if I open a character created with earlier Build or created with 169.

Already finalized ("created") characters and characters created with Priority system are not affected.

Only Knowledge skills affected, Active skills don't.



https://www.dropbox.com/s/jxok0ljhdyfuf3v/Before_Finalized.chum5?dl=0

https://www.dropbox.com/s/6zi88okxyyz09rj/After_Finalized.chum5?dl=0

**Comment by o8livion** [comment]
hi!

i think i have the same issue. if it is, than the trigger is not to mark char as created and save, but to go in the skills-tab of a finished char.
if you only hang around in attribute, gear, magic-tab, nothing happens and the print is okay.
if you go to the skills-tab, only the knowledge-skills are set to one, but therefore all of them.
i am using chammer5 version 0.5.172.0

**Comment by chummer5a** [comment]
I can't reproduce this in 5.175; is it still an issue for you?

**Comment by Shiwo** [comment]
seems okey now
