### ISSUE TITLE
Initiate window doesn't activate for Adept builds

### ISSUE THREAD

**Issue by Jimbomcw** [chummer5a/chummer5a#2636]
Chummer 5.199.0

Creating an Adept does not provide the Initiation window for Adept build using Karma system

**Comment by OLStefan** [comment]
Do you have the house role scribe to enable initiation during chargen?

**Comment by Jimbomcw** [comment]
wasn't at chargen

was after completing build and saving to Career mode for all priority, sum to ten, and karma...tried all 3

**Comment by chummer5a** [comment]
Fixed in current build, will be in the next nightly.
