### ISSUE TITLE
Quality: Linguist

### ISSUE THREAD

**Issue by Gurvaldt** [chummer5a/chummer5a#264]
In version 168 the knowledge points during character creation were correctly calculated as giving two points in the language for one knowledge point. In version 169 this does not work anymore.

Also, in both versions, points bought with the 25 karma you get per default in the priority build system are normally calculated. Shouldn't the quality count for those as well?

**Comment by joha4270** [comment]
Should and actual are far separated in chummer :P

For the first part, i suspect an error in the qualities file, not the application.

For the second part, yes it should. Busy with finishing life modules so no eta on fix

**Comment by chummer5a** [comment]
I'll handle it.

**Comment by chummer5a** [comment]
Resolved in 5.170.
