### ISSUE TITLE
Underbarrel Grenade Launcher is addable, but not functional as weapon.

### ISSUE THREAD

**Issue by DarkArcticDay** [chummer5a/chummer5a#2642]
### Environment
Chummer Version: 5.199.0
Environment: Windows 10 Home Edition 64-bit
Runtime: I don't know, so probably .NET 4.5.1

### Expected behaviour
Either;
1.) Underbarrel Grenade Launcher should appear in the "Add Underbarrel Weapon" menu, or
2.) Adding "Underbarrel Grenade Launcher" via weapon accessories should create a usable weapon entry for the grenade launcher.

### Actual behaviour
An Underbarrel Grenade Launcher does not appear in "Add Underbarrel Weapon" when adding to a Ruhrmetall SF-20 in career mode (though a shotgun does), and adding the weapon accessory option creates an unusable mundane variant.

### Steps to reproduce the behaviour
Add an underbarrel grenade launcher to an SF-20 machine gun in build mode or career mode.

### Link to affected character file
N/A

**Comment by DarkArcticDay** [comment]
I believe the standard ruling is that the Ares Alpha's grenade launcher is the "default" underbarrel addition.  The AK98's differs only in that it uses an internal magazine, if I recall correctly.  An option for both might be a good stopgap solution until this is clarified by errata?

**Comment by oxford-fumble** [comment]
I had the same issue, and found that the data and functionality is there in Chummer to do this - but they have disabled it so as not to create errata conflict.

If you want to enable the option to add grenade launcher as an under barrel weapon, create an override file ("override_weapons.xml"), and copy the entry from "weapons.xml" for the under barrel grenade launcher, making sure you remove the <hide /> command from the data.

**Comment by MerGatto** [comment]
According to Kreuzfeuer, the german Run & Gun, the underbarrel grenade launcher has 4 precision is single shot and has a 6(c) magazine, so basically the same as the Ares Alpha grenade launcher
