### ISSUE TITLE
Unable to add either Taboo transformer or Flesh sculptor quality missing Zoology knowledge skill

### ISSUE THREAD

**Issue by Wayfinder13** [chummer5a/chummer5a#2644]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199
Environment: Windows 7
Runtime:  .NET 4.5.1

### Expected behaviour
Add taboo transformer or flesh sculptor quality

### Actual behaviour
Get message box Quality requirements 
need Zoology5Knowledge 5 (Skills)

Zoology does not appear as a knowledge skill and typing it in as a custom does not remove restriction 

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate it. Sure you have the critter form or shapechange spells?
