### ISSUE TITLE
metatype help

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2645]
The message related to the metatype on the right of the screen is unreadable.
the display window of it is illegible. I can't see this help message.
the message appears when we fly over the number of Karma point that the majority of other messages are linked to the title so well positioned on the screen

### Environment
Chummer Version: (What version of chummer are you running? Chummer 5.199.0
Environment: (Operating system here. If it persists over multiple OS's list them all)  windows10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
probably bit i don't know
 

### Steps to reproduce the behaviour
 reproduce

**Comment by Zitchas** [comment]
Could you post a screenshot of the problem? I'm having trouble figuring out what you are referring to.

**Comment by Dedalios** [comment]
![chummercapture](https://user-images.githubusercontent.com/35507412/38232377-078a1698-3717-11e8-9dc7-e55a215a0fc2.PNG)

**Comment by Dedalios** [comment]
this probleme on write screen help message from distrtibute point presentation.if i pass on metatype not message. Mmessage appear from karma point from metype.

**Comment by chummer5a** [comment]
Can't replicate it in current builds.
