### ISSUE TITLE
Initation white screen blocking group & schooling discount options

### ISSUE THREAD

**Issue by Jimbomcw** [chummer5a/chummer5a#2646]
as the title says...in many of the builds the white screen that lists initate grades is oversized and blocking the group and schooling discount click options

**Comment by chummer5a** [comment]
Can't replicate it. Screenshot, please?

**Comment by Jimbomcw** [comment]
Capture/1st is career mode karma system build2nd is priority system specifically & sum to ten looks the same

    On Tuesday, April 3, 2018, 2:01:45 AM EDT, Chummer 5 Is Alive <notifications@github.com> wrote:  
 
 
Can't replicate it. Screenshot, please?

**Comment by Jimbomcw** [comment]
screen shot sent via e-mail

**Comment by chummer5a** [comment]
Didn't receive it. Github generally doesn't like inline images via email.

**Comment by Sturmkind** [comment]
I think this shows the problem well enough:
![test](https://user-images.githubusercontent.com/23245979/38349874-49b0c9f2-38a9-11e8-8137-aa4aa07625b4.PNG)

**Comment by chummer5a** [comment]
Yup, that'll do it. Okay, should be a simple enough fix.
