### ISSUE TITLE
Micro Drone Racks

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2648]
### Environment
Chummer Version: 5.199.3
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Prize for the Standard Micro Drone Rack: 350
Slots of the Standard Micro Drone Rack: 1

Prize of the Landing Micro Drone Rack: 750
Slots of the Landing Micro Drone Rack: 2

### Actual behaviour
Either of them have no listed cost and no listed slot cost.

### Steps to reproduce the behaviour
Look it up in the vehicle windows

### Source
Asphaltkrieger (german Rigger5) considered erratae'd

**Comment by cnschu** [comment]
made a fix
