### ISSUE TITLE
Error with free contact points in Priority Build

### ISSUE THREAD

**Issue by taiyoko** [chummer5a/chummer5a#265]
Using build 169, making a character using the priority table system only awards 1 contact point per Charisma instead of 3 x Charisma.

**Comment by chummer5a** [comment]
The default setting for contact points got defaulted back to 1 incorrectly.
If you open Tools > Options > House Rules and enable/disable the house rule
'Free Contact Points equal to Charisma X (x)' it should reset to 3 properly.

**Comment by chummer5a** [comment]
Fixed in 5.170.
