### ISSUE TITLE
Quality list overlaps accept button in metatype selection window

### ISSUE THREAD

**Issue by seppestuyck** [chummer5a/chummer5a#2652]
### Environment
Chummer Version: 5.199.5
Environment: win 10 home
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
all custom metatypes are available in all creation methods

### Actual behaviour
only one of the 2 new metas available in karma gen

(btw don't know if bug or just not finished yet but shapeshifters in carreer mode dont actualy change stats if you change from meta to shifter or back)

### Steps to reproduce the behaviour
add the custom file and try to make a character

### Link to affected character file
this is the custom file, maybe ive done something wrong

[custom_metatypes.txt](https://github.com/chummer5a/chummer5a/files/1875414/custom_metatypes.txt)

**Comment by seppestuyck** [comment]
the shapeshifter is a copy and paste, and adjust job.
it should have the same structure like the other shifters

**Comment by seppestuyck** [comment]
ive put the goblin in a seperate file, and selecting it in creation makes chummer crash

**Comment by seppestuyck** [comment]
the crash file if it helps
[chummer_crash_131673242102165721.txt](https://github.com/chummer5a/chummer5a/files/1876076/chummer_crash_131673242102165721.txt)

**Comment by chummer5a** [comment]
[amend_metatypes.txt](https://github.com/chummer5a/chummer5a/files/1876121/amend_metatypes.txt)
That should be a working amend for the goblin, shapeshifter should work in the next nightly.

**Comment by seppestuyck** [comment]
nice, thanks for all your effort

**Comment by seppestuyck** [comment]
Your file also crashes chummer when i select goblin in creation.

**Comment by chummer5a** [comment]
Can't replicate it, what's the error say?

**Comment by chummer5a** [comment]
You haven't populated options for that metavariant in priorities.xml.

**Comment by seppestuyck** [comment]
Ok i've adapted the priorities file, added the shifter too and that showed up too, but without an ok button so i couldnt get past the selection screen

**Comment by seppestuyck** [comment]
the goblin works now btw

**Comment by seppestuyck** [comment]
after some testing with other shifters, it appear that if the list of qualities is too long it will cover up the ok button.
