### ISSUE TITLE
Problems with Foci and Spirits.

### ISSUE THREAD

**Issue by superdash-attack** [chummer5a/chummer5a#2655]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer 5.199.0 and 5.199.6 nightly
Environment: Windows 10
Runtime: idk?

### Expected behaviour
When in career mode, the spells and spirits tab should have a box to added a spirit. When you buy a focus of any kind a box appears in street gear to allow you to pay karma to bond the foci. In the initiation tab, there should be options for: Group Init, init ordeal, and teaching. 

### Actual behaviour
The box for spirits is now missing entirely. Also, when buying a focus of any kind in career mode, there is no longer a box to Bond the Foci outside of char gen. When entering career mode, you can no long bond a foci. The initiation options are messed up and missing.
### Steps to reproduce the behavior

Create any magic character, check the spells and spirits tab to see a missing spirits box. Buy a focus of any kind and the box to bond foci are gone.

### Link to affected character file
https://www.dropbox.com/s/y1ggx6jibdd4zxm/GM%20File.chum5?dl=0

**Comment by chummer5a** [comment]
Should be resolved in current nightlies.
