### ISSUE TITLE
Chain Breaker Quality dose not exists 

### ISSUE THREAD

**Issue by Anfears** [chummer5a/chummer5a#2660]
### Environment
Chummer Version: 5.199.0
Environment: w10
Runtime:  .NET 4.5.1

### Expected behavior
The chain breaker quality from forbidden arcana to be selectable by those with the summoning skill 

### Actual behavior
Quality does not seem to exist or be selectable no matter what you do either because it doesn't exist in the program or is disabled  

### Steps to reproduce the behavior
create a character with the ability to summon spirits and try and find it on the quality list

**Comment by Friendbot2k** [comment]
Hmm, This is interesting because I have made several magician characters today and it shows up for me. Are you sure you have the SRC book enabled in options?

**Comment by Anfears** [comment]
@Friendbot2k I have all of the books enabled and no optional rules sets enabled that would prevent it from showing and it still dose not show up. I have even tried a fresh install of the program on my desktop with all the books enabled and it still dosen't show

**Comment by cnschu** [comment]
It works fine with version 5.199.9.
I tested it with a new character, and it works fine as long as the character has an MAG attribute of 1 or above. the only thing that doesn't seem to work is the discount for aspected magicans.

Chan Breaker costs 10 Karma for Magicians and Aspected Magicians.

**Comment by Anfears** [comment]
Figured it out I deleted my settings and and then redid them and that seemed to work. No idea what in the settings was causing that.
