### ISSUE TITLE
No option for using skill points on broken groups.

### ISSUE THREAD

**Issue by Dagurinn** [chummer5a/chummer5a#2668]
Not strictly a bug but this option seems to have been lost somewhere between version 5.178 and 5.180 and would nice to have back. Attached screenshots where the option is outlined in version 5.178 followed by the same screen with the option missing in version 5.180.

![capture1](https://user-images.githubusercontent.com/20946522/38441020-db5f51dc-39d2-11e8-8237-82416fec13c1.JPG)
![capture2](https://user-images.githubusercontent.com/20946522/38441022-db7d8f26-39d2-11e8-9607-8b9a4c524bbd.JPG)

### Environment
Chummer Version: (What version of chummer are you running?
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Implemented in current nightly builds.
