### ISSUE TITLE
Magic Stat Not Showing

### ISSUE THREAD

**Issue by Dahaste** [chummer5a/chummer5a#2669]
The Magic stat will not appear.

Not sure if it's a bug, or I'm doing something wrong.

### Environment
Chummer Version: The regular version currently up as of 04.07.18
Environment: Windows 8
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Showing the Magic stat

### Actual behaviour
Not showing Magic stat

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
This should be fixed in the current nightly build.
