### ISSUE TITLE
Karma to Nuyen not functioning (Chummer nightly.199.11

### ISSUE THREAD

**Issue by Sundaysmiles** [chummer5a/chummer5a#2678]
### Environment
Chummer Version: Nightly Build 199.11
Environment: Windows7

### Expected behaviour
When spending Karma to increase Nuyen amount, amount should be recorded as 2000 Nuyen increase and reduction of one Karma point per 2000 increase.

### Actual behaviour
No Karma points have been removed and no monetary increase is registered on the lower information bar or in the Karma Summary.  No error information recorded.   

### Steps to reproduce the behaviour
Issue occurs every time I load up a new character.

**Comment by chummer5a** [comment]
Unable to replicate in current builds.
