### ISSUE TITLE
Custom Files

### ISSUE THREAD

**Issue by Luecian** [chummer5a/chummer5a#268]
I am trying to make custom files for Chummer5a and can not seem to get the stuff I make to show up. I feel it has to do with the ID field.

**Comment by joha4270** [comment]
This would be much easier to perform diagnostics if you gave actual info about what you tried to change, such as the the lines you have written.

Probably not the id field, as that missing is more likely to crash chummer5a, but it is possible

**Comment by Luecian** [comment]
In my current rendition of this file I removed the ID field entirely, has no change. Here is some of the code written so far. 

http://pastebin.com/AWPkMuXc

**Comment by Luecian** [comment]
File is named as custom_weapons.xml, how one would have done it in Chummer 4

**Comment by chummer5a** [comment]
IDs aren't strictly necessary; if you don't have one Chummer should
generate one on the fly; it can cause some issues, but for the most part it
should be fine. I'd be immediately inclined to guess that you haven't
created an entry in books.xml for this SRI book you're referencing.

**Comment by Luecian** [comment]
Oh...ooohhhh...Yeah, as soon as I switched that to some random page in the core book...bam it worked. Thank you very much for your help.

**Comment by Luecian** [comment]
Now I can get back to editing and working on it all. Thank you for all your hard work on Chummer5A also.
