### ISSUE TITLE
Initiation tab hidden in karma build until the character is reloaded

### ISSUE THREAD

**Issue by skachm** [chummer5a/chummer5a#2680]
### Environment
Chummer Version: 5.199.0
Environment: Windows 10
Runtime: 4.5.1

### Steps to reproduce the behavior
1. In house rules, allow initiation at character creation
2. Create a new character with Karma build
3. Add a quality (eg. Magician)

### Expected behavior
Both the Spells and Spirits and Initiation tabs appear.

### Actual behaviour
The Spells and Spirits tab appears but the Initiation tab does not until the character sheet is reloaded.

**Comment by chummer5a** [comment]
Resolved in current nightly build.
