### ISSUE TITLE
Some UI elements not working/obstructed

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2681]
### Environment
Chummer Version: 5.199.11
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Availability Rating is unreadable for a lot of items, examples: Hardened Milspec armors, aconite, thermite, Messerschmidt-Kawasaki Heuschrecke 2

It's not possible to add specialisations to characters in career mode due to the button for it missing

Out of the 3 initiation options only the top most is actually visible and thus usable.

This probably isn't an exhaustive list, but that's what I bothered to look up, the availability things seems to come from the assigned space overlapping with the availability test text.

**Comment by chummer5a** [comment]
These should mostly be fixed in current nightlies, can you please confirm what else is left outstanding?

**Comment by MaraFaye** [comment]
In the latest nightly build of 5.199.30 out of the 3 available initiation opions only the trials is available, and it gives 20% for some reason instead of 10%.

At the availability side, all single digit numbers are fine, but as soon as it's double digits the letter vanishes behind the "test" text so you can only red "22 test" when you should be able to read "22V test".

Specializations are working, but for some reason you can now select and change the attributes corresponding to skills...
