### ISSUE TITLE
Mastery Qualities default to using spells available instead of karma

### ISSUE THREAD

**Issue by IrNot1337** [chummer5a/chummer5a#2682]
Available spells being consumed when building a mystic adept.

Priority Build, Race-C, Attributes-B, Magic-A, Skills-E, Resources-D
Race-Elf
Type-Mystic Adept
Skills-Counterspelling & Spellcasting

Qualities:
Positive- Healer, Pacifist Adept

In version 6.199.6 switching to the spells tab immediately lists 3 of 10.
In version 6.199.11 immediately after adding quality spell list updates to 3 of 10.

### Environment
Chummer Version: 6.199.6, 6.199.11, 6.199.12
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Mastery Qualities from Forbidden Arcana can be bought with Karma or Spells. 
"A character may exchange spells they receive from their selection on the Magic/Resonance priority chart for 5 Karma to spend on mastery qualities.."
_Expecting to see available karma reduced, and spells to remain constant._

### Actual behaviour
Chummer currently lists the qualities correctly towards positive limit, but then defaults to spell slots when added to the character and selecting the spells tab.
_Available spells counts up while available karma remains constant. Only when going over spells do the karma costs apply due to buying more spells._

### Steps to reproduce the behaviour
Create mystic adept
add cool resolve adept power
set spellcasting at 6 w. specialization in health, first aid at 6, 
add negative quality pacifist II
add positive quality pacifist adept, healer
spell count now at 3 of 10

### Link to affected character file
[5.199.11 - Pacifist Magical Adept.zip](https://github.com/chummer5a/chummer5a/files/1897256/5.199.11.-.Pacifist.Magical.Adept.zip)

**Comment by OLStefan** [comment]
Chummer uses the Spell Points first. You can just use them all for spells (before or after buying a mastery quality) and the mastery quality will use Karma instead.
