### ISSUE TITLE
College Education Disappeared

### ISSUE THREAD

**Issue by AdrianLJones** [chummer5a/chummer5a#2686]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199.0, 5.199.11
Environment: (Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Add the College Education Positive quality from Run Faster

### Actual behaviour
This quality is not in the quality list

### Steps to reproduce the behaviour
Create a new character and search for College Education, it isn't there.

### Link to affected character file
(Enter text here)

**Comment by Zitchas** [comment]
I just tried to replicate this bug, but I can't. Created a new human with priority, and searched for College and both RF and SASS versions turn up correctly.

1) Have you double checked to make sure the Run Faster source book is enabled?

2) Have you tried updating to 5.199.13?

**Comment by AdrianLJones** [comment]
I'm unable to duplicate the bug on my laptop (running windows 10)

However it still exists on my home computer after updating to 5.199.13.
Other Run Faster qualities show up (eg Technical School Education)

I'll try a clean install

**Comment by Zitchas** [comment]
So, did a clean install work?

Alternatively, when you search for College education, have you tried checking/unchecking the boxes that limit things to only the ones you can pick? There might be some kind of hidden restriction preventing them from being shown.
