### ISSUE TITLE
Collge Education from RF now blocks the one in SASS

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2687]
### Environment
Chummer Version: 5.199.13
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I should be able to add the College Education trait from both Run Faster and Sail Away Sweet Sister.

### Actual behaviour
One should be able to pick both qualities.

### Steps to reproduce the behaviour
Add one of the qualities. Then try to add the other one.

**Comment by cnschu** [comment]
you can only have one of ther qualitys.
All Rules in SASS are superseded by RF, and can no longer applied to your game if you use RF (Exept with express permission of your GM).

let me cite SASS:

> Supplemental rulebooks such as Run Faster
and Street Grimoire, which will provide more details about
these items, are coming soon. Where necessary, though,
interim rules are presented here. Any rules presented here
will be superseded by later supplemental rulebooks.

**Comment by Zitchas** [comment]
OK, then I guess this becomes a feature request to add a custom rule reverting the two college educations to the way they used to be previously.

As GM for my group, I allow both to be applied to a character since they are completely different kinds of bonuses that don't directly interact with each other. Given the different nature of the bonuses, I view the SASS college education as basically being "character was an honours student at college and/or put a lot of work into studying hard for their classes," which fits with the +1 to mental limit for academic knowledge skills. Which also makes academic skills a bit more worthwhile for characters that don't have the best mental stats.

 Whereas RF's college education is more along the lines of "enjoys / is good at learning and took a lot of classes" since it doesn't affect the mental limit at all, but gives the character access to more knowledge skills. So they were exposed to more academic skills (hence more skill points), but they didn't dive as deep into any particular topic as someone who has the SASS version.

**Comment by chummer5a** [comment]
It's not exceptionally difficult to implement it as an amend file, just needs someone to want to bother doing it.

**Comment by chummer5a** [comment]
Specifically, the issue is related to how we check for limited numbers of items, in which we use the Name of the quality for comparison purposes. If you change the name of one of the qualities, it'll be treated as a separate quality again.
