### ISSUE TITLE
Crash Handler/Advanced Lifestyles Crash

### ISSUE THREAD

**Issue by Velocikitty** [chummer5a/chummer5a#2690]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running?) Nightly
Environment: (Operating system here. If it persists over multiple OS's list them all) Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
To be able to create an advanced lifestyle

### Actual behaviour
It crashes if you scroll/view the list for Lifestyle Levels

### Steps to reproduce the behaviour
Open Program, start character, click advanced lifestyle, scroll in the Area. It adds the Public/LOcal Grid, then crashes.

### Link to affected character file
https://drive.google.com/open?id=1YS_tnN-ypa8VKM6Iy-iv-Pm3Rnaea9Le

I can't attach a log, as the crash handler is also crashing, but this is what I can get from the error: https://i.imgur.com/nwXuJKh.png

Also, it could be a PC issue, but reporting anyway, since both Release and Nightly builds are doing this to me.

**Comment by chummer5a** [comment]
Fixed in the latest commit, will be in the next nightly.

**Comment by Velocikitty** [comment]
Awesome, glad to see it was a quick fix! Guessing it was related to the meta-type crash on creation then?

**Comment by chummer5a** [comment]
Naw, caching for TrustFund was causing a null reference if no bonuses were found.

**Comment by Velocikitty** [comment]
Can confirm fixed :D
