### ISSUE TITLE
Specializations on Skills bought in Skill Group

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#2691]
### Environment
Chummer Version: 199.16
Environment: Win7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Ability to spend skill points on specializations for skills bought in a skill group.

### Actual behaviour
Though I have skill points remaining, it forces me to buy them with Karma

### Steps to reproduce the behaviour
Buy a Skill Group. Select a specialization for one of the included skills.

**Comment by chummer5a** [comment]
> Players may choose to buy a specialization for an individual skill within a skill group, but if they do so the skill group is broken from that point forward, meaning that all skills of the group must be raised separately. [...] This cannot happen in Step Five of character creation—you can only break up a skill group by buying a specialization for it in Step Seven (see p. 98 for details)
