### ISSUE TITLE
Rigger 5.0 weapon mount mod availability values seem to be incorrect

### ISSUE THREAD

**Issue by StygianSun** [chummer5a/chummer5a#2692]
### Environment
Chummer Version: 5.199.16
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Some combinations of vehicle weapon mount modifications have incorrect availability values. 
For example: A Heavy, Armored Manual, Internal, Turret mount should have an availability of 24F (12F for heavy mount, +4 for armored manual, +2 for internal, and +6 for the turret.)
Another example is a heavy, remote, internal, fixed mount with an availability of 14F (12F for heavy, +0 for remote, +2 for internal, +0 for fixed.)
I'm not sure if there are other combinations, but it seems that the value for the internal visibility modification is incorrect.
Additionally, the ammo bin modification shouldn't add its availability to the weapon mounts availability.

### Actual behaviour
In actuality, the heavy, armored manual, internal, turret mount has an availability of 26F and the heavy remote, internal, fixed mount has an availability of 16F. The ammo bin's availability of 6R seems like its being added to the weapon mounts total availability. But on pg 162 of Rigger 5.0 the table doesn't show a "+" next to the 6R.  

### Steps to reproduce the behaviour
Add a weapon mount to any vehicle and choose internal visibility to the mount. It adds 4 to the availability but should only add 2. Adding an ammo bin using the Add mod button also adds the bin's availability to the total mount availability instead of being separate.

**Comment by cnschu** [comment]
Can you please specify what do you think are the false and the correct values?

As far as i can interpret your report, you are claiming, that the "internal" visibility adds 4 insteread of 2 to the availablility of a weapon mount.

is this correct?
