### ISSUE TITLE
New Nightly Build Update Breaks the Skills Tab

### ISSUE THREAD

**Issue by Friendbot2k** [chummer5a/chummer5a#2696]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199.22
Environment: Win 10
Runtime: 4.5.1

### Expected behaviour
In Character Creation mode you should be able to raise your skills by points and karma
### Actual behaviour
The behaviors of Career Mode are on the Creation Mode Skill section. (i.e. the "plus" icon to raise a skill with Karma instead of being able to raise it via points.)
### Steps to reproduce the behavior
1. Create a new character
2. Go to the skills page

**Comment by chummer5a** [comment]
Yeah, I goofed. It's fixedish in the latest commit (There's an issue with adding specialisations not working until you've increased the karma to > 1 OR you reload the save) but it'll be in the next build. It's annoying enough that I'll just push one now, so check for an update in ~10 minutes from now.

**Comment by Friendbot2k** [comment]
Cool. Thanks man and no worries. It happens lol. I have accidentally broke production more than a couple of times at my job haha
