### ISSUE TITLE
Save PDF crash

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#2698]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.199.0
Environment: (Operating system here. If it persists over multiple OS's list them all) Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1) Yes

### Expected behaviour
Save as PDF

### Actual behaviour
Crash or just no saved file
![crash](https://user-images.githubusercontent.com/29793408/39097212-aedf3f3a-4659-11e8-8399-33f18b4eeb91.jpg)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't reproduce in current builds. I suspect it's resolved, but if not it's most likely tied to a specific character setup, so I'll need the character file.

**Comment by Johnny8-0** [comment]
Still happening on build 5.200.2. File attached.

**Comment by Johnny8-0** [comment]
[chummer_crash_131726143399416251.txt](https://github.com/chummer5a/chummer5a/files/2073226/chummer_crash_131726143399416251.txt)
[chummer_crash_131724324317801277.txt](https://github.com/chummer5a/chummer5a/files/2073227/chummer_crash_131724324317801277.txt)

**Comment by chummer5a** [comment]
This still an issue?
