### ISSUE TITLE
No Bullets and Bandages Book Checkbox

### ISSUE THREAD

**Issue by ChopperSniper** [chummer5a/chummer5a#2699]
### Environment
Chummer Version: 5.199.16 and 5.199.26
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Should have Bullets and Bandages as a book option.

### Actual behaviour
Does not have Bullets and Bandages as a book option.

### Steps to reproduce the behaviour
Check the options menu. Also, if using a file that was created using it elsewhere, still gives the "X was created using X book, do you still want to load?" box, but with no option to check the book...

### Link to affected character file
Could be any character file, really.

**Comment by chummer5a** [comment]
Are you using the Missions ruleset? That book isn't allowed in Missions.
