### ISSUE TITLE
Undo Hobgoblin changes based on house rules.

### ISSUE THREAD

**Issue by Mondlied** [chummer5a/chummer5a#2704]
Undo changes to hobgoblin done in #2100

I cannot find any indication that the source of the errata is official or based on official Errata. In fact the errata thread in the forum does not seem to contain any entry about hobgoblins https://forums.shadowruntabletop.com/index.php?topic=24596.0

The German errata don't mention any changes to hobgoblins either.

In fact the hobgoblin description indicates that those changes are invalid:

> [hobgoblins] possess a smaller frame than the standard robustus.

> The hormonal variation can also explain their enhanced scoring on EQ tests

**Comment by chummer5a** [comment]
Run Faster second printing.
