### ISSUE TITLE
Initiation Tab

### ISSUE THREAD

**Issue by Aybes** [chummer5a/chummer5a#2707]
Version 5.199.38

Check boxes for Initiation karma discount should include Ordeal, Group, and Schooling.

Check boxes Group and Schooling are missing.

**Comment by DelinquentPanda** [comment]
The button for join group is down by the side and now properly costs karma but I also can no longer see any options for schooling

**Comment by Aybes** [comment]
I have noticed the new Join Group checkbox. Clicking on it does have the 5 karma cost per Street Grimoire but it does not have any effect of Karma cost for new Initiation Grades.

**Comment by chummer5a** [comment]
Yeah, something's gone sideways with the designer code, so controls keep becoming invisible; is quite annoying.
