### ISSUE TITLE
Chummer crashes when adding gear

### ISSUE THREAD

**Issue by albertossic** [chummer5a/chummer5a#2709]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Nightly-v5.199.38
Environment: Windows 7 Home Premium
Runtime: *should* be NET4.7.1., not sure

### Expected behaviour
Adding gear then lists that item under the "street gear" tab

### Actual behaviour
chummer crashes when adding gear

### Steps to reproduce the behaviour
-Clicking on "Add Gear" and then "OK" after having chosen any gear item

### Link to affected character file
All Character files

**Comment by chummer5a** [comment]
Can't reproduce it. Anything more specific to replicate it?
