### ISSUE TITLE
Adept Power Critical Strike

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#271]
If you used the Adept Power Critical Strike, the program crashes with this error:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.Power.get_DisplayNameShort() in M:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:Zeile 6526.
   bei Chummer.Power.get_FullName() in M:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:Zeile 6541.
   bei Chummer.PowerControl.set_PowerName(String value) in M:\Coding\chummer5a\Chummer\Controls\PowerControl.cs:Zeile 147.
   bei Chummer.frmCareer.frmCareer_Load(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\frmCareer.cs:Zeile 847.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Found the issue; powers are getting their Extra values added to their name, instead of being saved separately. Will be resolved in the next version.

**Comment by McRipolo** [comment]
Thanks for the quick response. 
And thanks for work on Chummer and keep it alive!
