### ISSUE TITLE
subgear notes are not printed

### ISSUE THREAD

**Issue by ARgits** [chummer5a/chummer5a#2713]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199.40
Environment: windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

i add some mods to cybereye system and then add some notes to this mod
s, but it's printed only in "Fance Blocks" 

![default](https://user-images.githubusercontent.com/33343265/39475406-cc24bf1c-4d60-11e8-835b-8b2330640b01.PNG)

![2](https://user-images.githubusercontent.com/33343265/39475421-d86b54de-4d60-11e8-83be-ea86e4699a1e.PNG)

![3](https://user-images.githubusercontent.com/33343265/39475432-dd0cf24a-4d60-11e8-9b58-2afc42697e8c.PNG)

**Comment by DelnarErsike** [comment]
I think this was implemented in the commits that added support for printed notes for gear in a way that it prints notes from all children.
