### ISSUE TITLE
Character roster isn't immune to closing but should be.

### ISSUE THREAD

**Issue by StarWeaver** [chummer5a/chummer5a#2716]
### Environment
Chummer Version: 199.40
Environment: Windows 7
Runtime: probably .NET 4.5.1 though I do have higher

### Expected behaviour

Window->Close All should ignore character roster
The X for closing the character roster should be greyed out
Ctrl-W shouldn't close the character roster.

### Actual behaviour

Window->Close All closes the character roster, and you can't get it back.
The X for closing the character roster is active, lets you close it, and you can't get it back.
Ctrl-W is blocked properly.

**Comment by holgerschlegel** [comment]
Why should the Character Roaster tab be uncloseable?
I don't use it and usually close it right after starting the application.
An option to not automatically open that tab on start would be nice (for me).
