### ISSUE TITLE
Add Shifter options for character creation

### ISSUE THREAD

**Issue by taiyoko** [chummer5a/chummer5a#272]
From Run Faster
Karma costs on page 64, Attribute table on page 105, extended priority table listings starting page 106.

**Comment by chummer5a** [comment]
Shifters are on the backburner due to the requirement that they buy up
their stats separately. Will require a lot of annoying work to resolve.

**Comment by Atlessa** [comment]
If it helps, I soft-implemented shifters for myself  (only 'natural' shape currently, with Elf, Dwarf, Orc and Troll selectable as positive qualities.)
https://dl.dropboxusercontent.com/u/10082925/RP/Shadowrun/Shadowrun%205/Chummer5/data/Custom_shapechanger_XMLs.zip

**Comment by Verecoth** [comment]
I found a workaround using either the 'ignore character creation rules' option with a bunch of free metagenetic qualities or, alternately, building their metahuman form and then using the Improvements tab to create a set of improvements which alter their stats to that of their animal form.

It's quite easy, albeit slightly time consuming.

**Comment by chummer5a** [comment]
Implemented in current nightly builds.
