### ISSUE TITLE
Spurs in Obivous Left Arm, and Smartlink in Cybereyes not able to be chosen

### ISSUE THREAD

**Issue by JoeCool715** [chummer5a/chummer5a#2724]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.199.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
1. able to select spurs in obvious left arm
2. able to select smartlink in cybereyes
### Actual behaviour
1. both items not choosable

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)
[Sledge dont lock up - Copy.txt](https://github.com/chummer5a/chummer5a/files/1976847/Sledge.dont.lock.up.-.Copy.txt)

**Comment by chummer5a** [comment]
Unable to replicate; use Add as Plugin to add cyberware to other cyberware, possibly it was an issue that was fixed in a nightly build.
