### ISSUE TITLE
Shapeshifter canine-dwarf not possible in priority mode

### ISSUE THREAD

**Issue by TheL1ne** [chummer5a/chummer5a#2725]
### Environment
Chummer Version: 5.199.0
Environment: Windows 10 
Runtime: 4.7.1

### Expected behaviour
When I use priority A for my metatype I expect to be able to create any metatype and according to the rulebook "run faster" it should be possible.

### Actual behaviour
The "OK" button dissappears if I try to combine canine and dwarf. I can only create canine-gnome but all other subtypes of dwarfs are not possible to combine with a canine shapeshifter. (disappearing OK button)

### Steps to reproduce the behaviour
1. Open Chummer
2. Try to create a new character in priority mode
3. use priority A for metatype
4. select canine shapeshifter
5. seleft dwarf as metavariant

### Link to affected character file
not possible because character is not creatable.

**Comment by TheL1ne** [comment]
It is possible in karma mode. I checked that.

**Comment by chummer5a** [comment]
Resolved in current nightly builds. Next milestone increment is scheduled for today, if you'd prefer to wait for that.
