### ISSUE TITLE
cyberlimbs missing equipment to install

### ISSUE THREAD

**Issue by TheL1ne** [chummer5a/chummer5a#2726]
### Environment
Chummer Version: 5.199.0
Environment: Windows 10
Runtime: 4.7.1

### Expected behaviour
cyberarm should provide the possibility to implement many options like cyber implantable weapons.

### Actual behaviour
the dialogue for choosing which implant to choose only shows sensors. (single sensor and sensor array).

### Steps to reproduce the behaviour

1. Open character and choose cyber arm (e.g. obvious cyberarm)
2. Try to add equipment to that arm.

### Link to affected character file
https://www.dropbox.com/s/29q2rgkiy8mqqpa/m%C3%B6nch.chum5?dl=0

**Comment by chummer5a** [comment]
Use Add as Plugin to add cyberware to another piece of cyberware.
