### ISSUE TITLE
Initiation discounts check boxes not showing up

### ISSUE THREAD

**Issue by Jimbomcw** [chummer5a/chummer5a#2729]
<a href="http://tinypic.com?ref=15wze9t" target="_blank"><img src="http://i65.tinypic.com/15wze9t.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by chummer5a** [comment]
Fixed in https://github.com/chummer5a/chummer5a/commit/f62c9c9e2c2330ece3cffbfcfab6fc92ec842215
