### ISSUE TITLE
Buying Knowledge Skills with Karma

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#273]
For some reason whenever I try to buy knowledge skills with karma the costs are way off. First rank seems to cost 3, then each rank after that only costs 1 karma.

**Comment by chummer5a** [comment]
Hrm, I can't replicate the issue. Could you update to the new version and see whether it's still an issue?

**Comment by Verecoth** [comment]
After updating to the latest version I can't start chummer at all.

Every time I attempt to open it, my computer immediately tells me that it isn't responding, and then closes it down.

**Comment by chummer5a** [comment]
Hrm. Try deleting the settings folder.

**Comment by Verecoth** [comment]
That did not work. Every time I try to launch it the folder returns.

**Comment by chummer5a** [comment]
Issue appears to be .Net. Try updating to 4.5.1 or 4.5.2.
