### ISSUE TITLE
Attribute property bindings don't work properly on characters that have been loaded in create mode

### ISSUE THREAD

**Issue by Idayn** [chummer5a/chummer5a#2731]
Free contact points are not updated.. The amount does not change when you modify a 
characters charisma, and karma is wrongly deducted.

### Environment
Chummer Version: 5.200.0
Environment: Win, Win 7
Runtime:  NET 4.6.1

### Expected behaviour
Free contact points amount does not change when charisma is changed.

### Actual behaviour
Free contact points amount should change when charisma is changed.

### Steps to reproduce the behaviour
Change a characters charisma in the Common Tab.

**Comment by chummer5a** [comment]
Can't reproduce it.

**Comment by Idayn** [comment]
Appearantly this only happens with characters build with previous versions. When I create one with 5.200.0, I can't reproduce it either. When I try this with characters created with < 5.199.0, it is reproducible.

**Comment by chummer5a** [comment]
Hrm. Can you show me a file?

**Comment by Idayn** [comment]
other link was wrong, try https://www.dropbox.com/s/ba5i2ymqyoavj4g/Mensch%20Adapt.chum5?dl=0

**Comment by chummer5a** [comment]
Yeah, something super janky going on with the bindings. Property bindings aren't firing properly.

**Comment by MaraFaye** [comment]
Is that also the reason for the initiatoin options not showing to pre-5.200.0 chars?

**Comment by chummer5a** [comment]
Er. Shouldn't be, but it would explain some things if it is.
