### ISSUE TITLE
Fake Licence on a real SIN not applicable

### ISSUE THREAD

**Issue by Idayn** [chummer5a/chummer5a#2732]
It is currently not possible to add a Fake Licence under the Gear Tab without having a Fake SIN to add it to. Chracters with one of the SINner qualities should be able to obtain a fake licence to a real SIN. 

### Environment
Chummer Version: 5.200.0
Environment:  Win 10, Win 7
Runtime: .NET 4.6.1

### Expected behaviour
It is currently not possible to add a Fake Licence under the Gear Tab without having a Fake SIN to add it to.

### Actual behaviour
Chracters with one of the SINner qualities should be able to obtain a fake licence to a real SIN.

**Comment by chummer5a** [comment]
Working as intended; fake licences are only attachable to fake SINs per RAW.

**Comment by StarWeaver** [comment]
It would be better to have a sin item to attach them to in this case also.

Current Workaround: Give yourself a free R6 sin labeled appropriatly.

Suggested actual change pt1: Add free national/criminal/corp sin items that can be used for this.

Pt2: Make the qualitiesgive you these items automatically.

**Comment by Lochabar** [comment]
Another alternative would be add real SIN and Licenses to a custom_gear so that you can see that the SIN is for the character's legal identity.
