### ISSUE TITLE
Able to add a Fake Sin as a plugin to a Fake SIN

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2733]
### Environment
Chummer Version: 5.200.0
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Prevented from adding a Fake SIN to another SIN

### Actual behaviour
You can
![fake sin](https://user-images.githubusercontent.com/17562417/39705684-a1907d3e-51fe-11e8-8ffc-98f12e219119.png)

### Steps to reproduce the behaviour
Rt-click on a Fake SIN and click Add as Plugin. The selection list shows Fake SIN is available. Select it and you get a Fake SIN with a Fake SIN.

You can then add a Fake SIN to the Fake SIN you just added to a Fake SIN
![fake sin 2](https://user-images.githubusercontent.com/17562417/39705881-2d7e9862-51ff-11e8-83d0-41ada0747b90.png)

**Comment by JoeCool715** [comment]
Same issue when added Ex-con negative quality trait

**Comment by StarWeaver** [comment]
Chummer lets you add a lot of things to a lot of other things that should probably not be allowed, like adding cybergenetalia to an Ares Predator V...
