### ISSUE TITLE
Spirit panel still not visible in career mode after previous fix

### ISSUE THREAD

**Issue by Kcasar** [chummer5a/chummer5a#2734]
### Environment
Chummer Version: 5.200
Environment: win10
Runtime: probably .NET 4.5.1

### Expected behaviour
When going into career mode, the spirit section on the "spells and spirits" tab should be visible so spirits can be added and managed.

### Actual behaviour
The spirit section disappears. This is true for both aspected and full magicians; and is true both with an older character made on a previous version, and a new character made today on 5.200
I submitted this issue previously, and it was closed in reference to a commit, but the issue still exists on current. (but the focus-binding issue that seemed to be related is definitely working better :D )

### Steps to reproduce the behaviour
create a character with bound spirits. enter career mode.

### Link to affected character file
(Enter text here)
![image](https://user-images.githubusercontent.com/38985031/39710734-a788623c-51eb-11e8-9ced-ccc30f214372.png)
![image](https://user-images.githubusercontent.com/38985031/39710764-bb491ed8-51eb-11e8-93ec-a9a274f85e69.png)

**Comment by chummer5a** [comment]
Will be fixed in the next nightly.
