### ISSUE TITLE
"Enable Special Attribute" does not allow attribute selection

### ISSUE THREAD

**Issue by Azure-Fang** [chummer5a/chummer5a#2735]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.1
Environment: Win 7 Pro x64
Runtime: .NET 4.7.1

### Expected behaviour
Clicking "Select Value" in "Enable Special Attribute" opens selection dialogue to choose EDG, MAG, or RES.

### Actual behaviour
Selection box appears and instantly closes, selecting EDG automatically with no way to change.

### Steps to reproduce the behaviour
1) Create new character (critter in test case)
2) Open Improvements tab
3) Add Improvement
4) Select "Enable Special Attribute"
5) Click "Select Value"

**Comment by chummer5a** [comment]
The SelectSpecialAttribute improvement thingummer in frmCreateImprovement is keyed to remove the special attributes you don't have for some reason; not sure why, it's the only intended use of that field.

**Comment by Azure-Fang** [comment]
Sounds about right. Just ran a couple more test sheets and "Enable" would only ever display options for specials that are already enabled.

**Comment by Azure-Fang** [comment]
Tested in 5.200.2 - appears to be functioning properly now. Adjusting correctly with Attribute Level as well.
