### ISSUE TITLE
Newly added "Improvements" appearing without names on active list

### ISSUE THREAD

**Issue by Azure-Fang** [chummer5a/chummer5a#2736]
### Environment
Chummer Version: 5.200.1
Environment: Win 7 Pro x64
Runtime: .NET 4.7.1

### Expected behaviour
Added improvements appear with provided names.

### Actual behaviour
Added improvement names are blanked on selection list, but function normally.

### Steps to reproduce the behaviour
1) Create a new character (critter used in test)
2) Open Improvements
3) Add Improvement
4) Select and configure an Improvement (Attribute, Attribute Level, and Enable Special Attribute used in test)

![untitled](https://user-images.githubusercontent.com/30414441/39752785-56f0d90e-5271-11e8-8ac5-1dd7c3f39cf6.png)

**Comment by StarWeaver** [comment]
If you save and reload the improvement names do appear. (Was testing because my character's old improvement was showing up but the new ones were not.) So it's only the new attribute code bath that's broken.

**Comment by Azure-Fang** [comment]
Thank you. Adjusted title to reflect this.

**Comment by Azure-Fang** [comment]
Just checked newest build after close. Issue still present.

**Comment by chummer5a** [comment]
Whups, closed the wrong issue.
