### ISSUE TITLE
Skill Group UI does not convert from karma to points in priority mode character creation

### ISSUE THREAD

**Issue by Azure-Fang** [chummer5a/chummer5a#2739]
### Environment
Chummer Version: 5.200.2
Environment: Win 7 Pro x64
Runtime: .NET 4.7.1

### Expected behaviour
Right sidebar showing character creation points (active skills, knowledge points, etc.) displays "Skill Groups <avail> of <max>" on priority character creation.

### Actual behaviour
Right sidebar shows "Skill Groups 0 Karma" even while priority points are available to spend on groups.

### Steps to reproduce the behaviour
1) Create a new character with "priority" rules
2) Set skill priority to anything that provides group points
3) Read right sidebar

### Additional comments
When using priority mode, some elements such as Active Skills convert from karma to the priority-provided points and will output a negative value on overrun. I assume the Skill Groups readout is intended to do the same, but currently does not.

**Comment by StarWeaver** [comment]
I'm not getting this. Updated to 5.200.2 and made some new characters in both priority and sum to ten and they all end up looking like
![Example](https://i.imgur.com/8cbBbHL.png)

**Comment by Azure-Fang** [comment]
Scratch this. Blame user error. My mind was reading the wrong set priorities. It is indeed working as intended. My bad, and I apologize.
