### ISSUE TITLE
Dumb Question... how do I open this?

### ISSUE THREAD

**Issue by GregHM** [chummer5a/chummer5a#274]
Hi there,

I don't see an .exe or similar file named chummer, not sure where else to look. How do I open this?

Thanks,
Greg.

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/releases/latest Download the zip file from here.

**Comment by GregHM** [comment]
Still having soem trouble. I downlaoded the .zip, and ran the exe, but it's saying "a problem caused the program to stop working correctly" and crashes before it opens. I'm in windows 7.

**Comment by GregHM** [comment]
Perhaps this is better posed as a new issue?

**Comment by joha4270** [comment]
Best bet is your version of the net framework is outdated
