### ISSUE TITLE
Life Modules don't show up in dropdown menu even with Run Faster activated

### ISSUE THREAD

**Issue by JEBtheGamer1** [chummer5a/chummer5a#2740]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
When Ruun Faster book is enabled, can make a character using life modules

### Actual behaviour
Life modules does not appear in the drop down menu when making a character

### Steps to reproduce the behaviour
Open 'new character' window

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
Do you have the option enabled to activate life modules? As they're not considered production-ready, they aren't enabled by default.

**Comment by JEBtheGamer1** [comment]
Ah, yes. I feel quite foolish now. Sorry!

**Comment by chummer5a** [comment]
No worries
