### ISSUE TITLE
Smartgun camera does not have capacity

### ISSUE THREAD

**Issue by Azure-Fang** [chummer5a/chummer5a#2742]
### Environment
Chummer Version: 5.200.7
Environment: Win 7 Pro x64
Runtime: .NET 4.7.1

### Expected behaviour
SR5 p.433
"The small camera has a capacity of 1 and can be equipped with vision enhancements (p. 444)."

### Actual behaviour
Capacity is not displayed on the "Camera, Micro" attachment for any of the Smartgun Systems.

### Steps to reproduce the behaviour
1) Add a weapon to a character
2) Attach any Smartgun System

OR

1) Add a weapon with pre-attached Smartgun System to a character

**Comment by chummer5a** [comment]
They do have the expected capacity, it's just not set to show the visual element.
