### ISSUE TITLE
Dragging weapons opens their modification tree each time

### ISSUE THREAD

**Issue by WeaverThree** [chummer5a/chummer5a#2744]
### Environment
Chummer Version: 200.7
Environment: Windows 7
Runtime: probably .NET 4.5.1 though I do have higher

### Expected behaviour

![Tree is open](https://i.imgur.com/3CoFaSy.png)

### Actual behaviour

![Tree is closed](https://i.imgur.com/IVyNYbR.png)

Having each item open every time it's moved makes organizing the list tedious and annoying.

### Steps to reproduce the behaviour

![Dragging item](https://i.imgur.com/zb37C8G.png)

**Comment by chummer5a** [comment]
It's because we're not moving the treenode, we're deleting it and remaking it. When a treenode is created, if the backing object has children, it calls expand. 

For what it's worth, you can ctrl-click on a treenode to collapse all children of that node.
