### ISSUE TITLE
Multiple Screens not returning information

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2746]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.8
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

I'm not sure how to describe this:
I loaded a character into the latest version of chummer, and instead of showing me all the information as expected, most of the screen was blanks, attributes are not shown at all, all the information on the right side windows is at 0, everything under street gear is blank, vehicles, etc.

Additionally it shows me tabs the character doesn't have, like sprites and complex forms, advanced programs or critter powers, all these where previously hidden.

![wth](https://user-images.githubusercontent.com/27777147/40008558-dfa2331e-579f-11e8-919f-54bf958c52f9.PNG)

### Link to affected character file
This character is a bit older, was totally fine in the 200.7 iteration. The only reason I can imagine for this to happen was because the character was created with the "ignore character creation rules" option since it wasn't possible to apply all the options from our house rules without it.

[Gale Karriere.zip](https://github.com/chummer5a/chummer5a/files/2001579/Gale.Karriere.zip)

**Comment by chummer5a** [comment]
Best guess, the application crashed at some point and failed to load everything. Next nightly might fix it.
