### ISSUE TITLE
Drone mounts and Exotic Ranged

### ISSUE THREAD

**Issue by Sintis** [chummer5a/chummer5a#2747]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

5.200.2
Windows 7
Runtime NET 4.5.1)

### Expected behaviour
Add the Parasheild dart pistol to a Standard (Drone) weapon mount

### Actual behaviour
None of the exotic ranged weapons show up for any size (Drone) mount
I have tried on several drones and and size mounts.

### Link to affected character file
(Enter text here)

**Comment by Sintis** [comment]
A small mount holds a heavy pistol,  a Gyrojet or Parashield dart pistol should qualify but are not an option.
Large lists hunting and assault rifles but you can't select the Dart or sonic rifles.  
RAW Doesn't list any exotic at any size,  is there a house rule option to allow them?

**Comment by chummer5a** [comment]
Righto, have added the SizeCategory property for weapons. If it's present, it will effectively override the category of the weapon as far as the weapon mount is concerned, allowing it to be slotted in. Will be in the next nightly build, eta 10.5-11.5 hours.
