### ISSUE TITLE
Chummer crashing when opening characters

### ISSUE THREAD

**Issue by sulla76** [chummer5a/chummer5a#2748]
Chummer crashes when opening any character.

I've re-downloaded the current version and the problem persists. 
### Environment
Chummer Version:  5.200.9
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Open character file.

### Actual behaviour
Chummer stops working and crashes
### Steps to reproduce the behaviour
Open a character.

### Link to affected character file
Every character record I've tried.

**Comment by chummer5a** [comment]
Should be resolved in 5.200.11.
