### ISSUE TITLE
After loading all Gear is listed under the "Selected Gear" location

### ISSUE THREAD

**Issue by DaRasch** [chummer5a/chummer5a#2749]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.9
Environment: Windows 7
Runtime: Probably .NET 4.5.1

### Expected behaviour
Gear is listed under the location I put it previously.

### Actual behaviour
All gear is listed under "Selected Gear". Same goes for the Armor tab. I haven't tested it for weapons and vehicles.

### Steps to reproduce the behaviour
- Create a new location
- Add equipment to it
- Save
- Close character and open it again

### Link to affected character file
Works on any character file.

### Further notes
I looked at the xml and there the locations appear to be assigned correctly.

Also, when loading a file created with an earlier version, Locations except "Selected Gear" are shown as empty strings. This also happens for the Armor tab and the xml has them correct.

**Comment by chummer5a** [comment]
Hrm, I thought I fixed that. Can you provide a sample character with locations?
