### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GregHM** [chummer5a/chummer5a#275]
I ran the exe, but it's saying "a problem caused the program to stop working correctly" and the application crashes before it opens. I'm in windows 7.

**Comment by chummer5a** [comment]
Is Chummer installed into a fresh directory? Try deleting your settings file.

**Comment by Verecoth** [comment]
I am having the same problem on Windows Vista

**Comment by Deathedge** [comment]
I am having the same problem on Win 7 pro, new installation, tried it with the 5.170 and 5.170.1 downloads: same error:
Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	chummer5.exe
  Problemsignatur 02:	0.5.170.1
  Problemsignatur 03:	55a51438
  Problemsignatur 04:	mscorlib
  Problemsignatur 05:	4.0.0.0
  Problemsignatur 06:	53b50a71
  Problemsignatur 07:	1205
  Problemsignatur 08:	89
  Problemsignatur 09:	System.TypeLoadException
  Betriebsystemversion:	6.1.7601.2.1.0.256.4
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chummer5a** [comment]
Try updating your .Net version to 4.5.1 or *.2.
