### ISSUE TITLE
Chummer5 crashes when attempting to open .chum5 file.

### ISSUE THREAD

**Issue by forfthemad** [chummer5a/chummer5a#2751]
### Environment
Chummer Version: Nightly 5.200.12
Environment: Windows 10 Home
Runtime: Probably .NET 4.5.1

### Expected behaviour
Character .chum5 file opens in chummer.

### Actual behaviour
Chummer crashes and produces the below log.

### Steps to reproduce the behaviour
Attempt to open enclosed character file.

### Link to affected character file
[chummer_crash_131710135488223981.txt](https://github.com/chummer5a/chummer5a/files/2011966/chummer_crash_131710135488223981.txt)

Unable to upload character .chum5 file type. Google Drive download link included below.
https://drive.google.com/open?id=1AKyhIiq3f4MefvF1tzAwDyq_hYhfwJ_P

**Comment by StarWeaver** [comment]
Loads for me with 5.200.12 on Win7 with my usual config. Mind you, half the tabs are useless in .12 because of stuff that's about to be fixed (i think?), but it doesn't crash.

**Comment by chummer5a** [comment]
Can't reproduce it; still an issue in current builds?

**Comment by forfthemad** [comment]
Thank you for responding quickly.

I thought the issue might be tied to my anti-virus, but I've excluded the Chummer classpaths and am still unable to open the character file in 5.200.14. Please find the attached log below.

Cheers,
forfthemad

[chummer_crash_131712682555094478.txt](https://github.com/chummer5a/chummer5a/files/2020059/chummer_crash_131712682555094478.txt)

**Comment by forfthemad** [comment]
Greetings, @chummer5a. Apologies for the delayed response. I'm using the latest stable version and still crashing on open of the aforementioned file. Thank you for your assistance.

Cheers,
forfthemad

[chummer_crash_131730749835228489.txt](https://github.com/chummer5a/chummer5a/files/2087527/chummer_crash_131730749835228489.txt)
