### ISSUE TITLE
Availability modifier from cyberware grades stacking with itself on cyberlimbs

### ISSUE THREAD

**Issue by Ignimortis** [chummer5a/chummer5a#2752]
### Environment
Chummer Version: 5.200.2.0
Environment: Win7
Runtime: .NET 4.5.1

### Expected behaviour
Availability modifications applying only to the resultant cyberlimb, i.e. 
Obvious Full Cyberarm is 4 avail by default, customized for 6 agi (+3 to base) and 4 str (+1 to base), 2 armor (bumps the base up to 10, since 10>8), no other modifications higher than 10, thus 10 is the basic rating and making it alpha-grade cyberware add +2 to that, making the final result 12 rating.

There's a different reading of the rules, which creates the following:
Obvious Full Cyberarm is 4 avail by default, customized for 6 agi (+3 to base, +2 for grade, +5 total) and 4 str (+1 to base, +2 for grade, +3 total), 2 armor (10 base, +2 for grade), no other modifications higher than 12, thus 12 is the basic rating and making it alpha-grade cyberware add +2 to that, making the final result 14 rating.

### Actual behaviour
Grade modifiers to availability affect each part of the cyberlimb, thus as far as I understand it goes like this:
Obvious Full Cyberarm is 4 avail, customized for 6 agi and 4 str. Armor gets bumped up to 12 for grade, making that the highest base value, then that 12 gets +2 for customized agility and strength, then another bump for base limb, resulting in a 18 rating.
Not sure if this is actually a bug, but it doesn't really make sense, since these aren't high stats.

### Steps to reproduce the behaviour
Creating any customizable 'ware with subcomponents.

### Link to affected character file
Works with any character.

**Comment by chummer5a** [comment]
There's already an amend for it in the nightly build, Not super sure that it's RAW one way or the other.

**Comment by Ignimortis** [comment]
Yeah, the RAW is kinda wonky on that, I've edited the initial post with another possible interpretation. Thanks for the response!
