### ISSUE TITLE
Printing generates blanks

### ISSUE THREAD

**Issue by caelian** [chummer5a/chummer5a#2753]
### Environment
Chummer Version: 5.200.13.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Printing should show generated output to be either saved or printed

### Actual behaviour
Pages are entirely blank, regardless of selected character sheet

### Steps to reproduce the behaviour
- Load character
- Print character
- Preview and generated PDF/HTML/etc. are entirely blank

**Comment by cnschu** [comment]
i've tested this Bug a little bit.

Version 5.200.7 - Printout OK
Version 5.200.8 - crashes at character loading
Version 5.200.9 - crashes at character loading
Version 5.200.10 - all Printouts are blank
Version 5.200.11 - all Printouts are blank
Version 5.200.12 - all Printouts are blank

**Comment by OLStefan** [comment]
Does it work again in the newest Nightly?

**Comment by Zitchas** [comment]
No, it doesn't. I'm on the 5.200.23 and all the printouts I've tried are empty.

**Comment by Lochabar** [comment]
Strange thing is I'm still on 5.200.22 and the printouts work. What changed between the two versions to stop it working again?

**Comment by Zitchas** [comment]
Just tested on 5.200.24 and the printouts are still empty.
