### ISSUE TITLE
Feature Request - Armor "Transfer to Vehicle"

### ISSUE THREAD

**Issue by crmanriq** [chummer5a/chummer5a#2754]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Under Gear/Armor, I would like to be able to move people armor to an anthropomorphic drone, similar to how I can move a weapon "Transfer to Vehicle", and put it into one of the anthropomorphic drone's hands.

### Actual behaviour
There is no "Transfer to Vehicle" option for Armor

### Steps to reproduce the behaviour
Add Armor

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
That's gonna take some work to implement; as is, vehicles/drones aren't designed to interact with regular armour like that. Still, doable.
