### ISSUE TITLE
Attribute Calculation Issue for Bioware and Improved Physical Attribute

### ISSUE THREAD

**Issue by bigsudda** [chummer5a/chummer5a#2756]
### Environment
Chummer Version: 5.200.2
Environment: Win7
Runtime:  NET 4.7.1

### Expected behaviour
The attribute boosts generated by muscle toner/augmentation should stack with the adept power improved physical attribute. Both descriptions (at least in the german rules SR5) do not exclude eachother as a bonus source.

### Actual behaviour
Only the highest bonus is applied in the character "common" section

### Steps to reproduce the behaviour
generate a new character with both bonus types

**Comment by bigsudda** [comment]
added a testcase file, including stacking and cap verification at a bonus of 4

[5v200v2v0_Attribute_Stacking_Testcase_no2756.zip](https://github.com/chummer5a/chummer5a/files/2045674/5v200v2v0_Attribute_Stacking_Testcase_no2756.zip)

**Comment by WaykoAstragon** [comment]
Environment
Chummer Version: Nightly-v5.205.53
Environment: Win10
Runtime: NET 4.7.2

The Bug still exist! Added a testcase file, too with magic, cyberware and bioware augmention.

[Char-v5.205.53.zip](https://github.com/chummer5a/chummer5a/files/3124252/Char-v5.205.53.zip)

**Comment by chummer5a** [comment]
Resolved by https://github.com/chummer5a/chummer5a/commit/241f59946d80a9ab52d861e99265880eea70e7ae
