### ISSUE TITLE
SURGE metagenetic implimentation

### ISSUE THREAD

**Issue by Maull12** [chummer5a/chummer5a#2757]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.16
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
SURGE metagenetic qualities would be kept track of (positive and negative) and be a self contained result shown to the player.

### Actual behaviour
SURGE metagenetic qualities (positive and negative) impact the overall karma of the character.

### Steps to reproduce the behaviour
Create a SURGE I, II, or III character choosing metagenetic qualities.

### Link to affected character file
(Enter text here)

**Comment by StarWeaver** [comment]
After adding surge, Metagenic qualities do not affect any readout of karma on the character.

For example: I took this blank adept, and added Changeling III. Karma Remaining went to -5 and a (30) was added on positive qualities. I then added several metagenic qualities, and none of those values changed.

![Example](https://i.imgur.com/75ow1Xa.png)

Mind you, a meter for how much SURGE pos/neg karma you had spent would be useful....

**Comment by chummer5a** [comment]
Closed in https://github.com/chummer5a/chummer5a/commit/05467961c3d555548e1ae0eb05e3259dd0b512e6
