### ISSUE TITLE
Feature Request - Add more / customisable sections in Character Rooster

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#2759]
**User Story:**
As a game master I would like to organise my NPCs using either a folder-like structure or tags (advantage: one NPC can be in several "sections") in the Character rooster to quickly find the NPC I want to show up in my game. Particularly in ad-hoc kind of situation when my players say something like: "let's talk to this guy from the triads we met last year..." I need to find the correct character quickly.

**Acceptance Criteria**
**Best option:** I add arbitrary tags to several characters (e.g. <campaign name>, NPC, Player, <adventure>, <name of organisation> etc.) then all tags from all characters show up in the rooster as sections. All characters with a given tag should be grouped under that tags section. A character with more than one tag will show up several times (once under each tag).

**second best option:** I configure a number of folders and manually add each character into a folder. The drawback compared to "best option": one character can only be in one "folder". So the NPC red dragons triad member from campaign A will be either in folder NPCs or in Triads or in "red dragons" or in Campaign A. If hierarchies of folders are possible, these examples could be organised in a hierarchy, but if this character then shows up in campaign B as well ... problem...

**third best option**: one of the above options but pre-defined / not user editable tags/sections.

**Comment by StarWeaver** [comment]
I remember making a suggestion for Automatically searching subfolders of the favorite folder Which word do number 2 above based on where you save /move the files. I don't remember if I suggested it  as an issue though

**Comment by Nedorus** [comment]
oh, maybe a little misunderstanding: when I speak of folders I am NOT thinking about physical folders on disk. the folder structure on disk should be totally independent of what we see in the character rooster.

**Comment by chummer5a** [comment]
Implemented by allowing subfolders of the Watch folder.
