### ISSUE TITLE
Ambidextrous working improperly

### ISSUE THREAD

**Issue by NATURE-1** [chummer5a/chummer5a#276]
The latest release should have made ambidextrous stackable but it's still not the case. Upon trying to select it again with a Nartaki character, the quality is simply not available, like before the release.

**Comment by chummer5a** [comment]
Unable to replicate the issue; Ambidextrous is available to Nartaki, and can be taken as many times as you want.

**Comment by NATURE-1** [comment]
The issue happened with an already created Nartaki character but creating a new Nartaki, the issue continues. I'll redownload Chummer and see if it fixes it.

**Comment by chummer5a** [comment]
Ohhh. Yeah, that'll happen. Changes that are made to characters with
existing qualities tend not to work exactly properly. The Reapply
Improvements menu option should fix it up.
