### ISSUE TITLE
UI elements hidden beneath tool line

### ISSUE THREAD

**Issue by Pjokk** [chummer5a/chummer5a#2761]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
All UI elements are interactable, regardless of window size

### Actual behaviour
The OK button in the options menu is unavilable, hidden beneath the tool line. Can't access it in any way. In career mode, the Physical Condition Monitor and Matrix Condition Monitor for drones and vehicles are unavailable, hidden beneath the tool line, with lots of space available above them. 

### Steps to reproduce the behaviour
Open chummer 5.200.2 in windows 10, on a display with a 1920x1080 resolution. Try to access the options menu. For career mode, simply open a character with a vehicle or drone in career mode.

### Link to affected character file
(Enter text here)

**Comment by Nedorus** [comment]
Oh, thanks, I never knew there even was a condition monitor in the career mode for vehicles because I was never able to see it ... (^_~)
This problem also occurs on Win7 system.

**Comment by Pjokk** [comment]
Yeah, I've been stuck with a bunch of 2050 items that I don't want in the gear section, but can't remove them because I can't accept the options I change in the options menu. This is even worse since I want to try out the alternative drone upgrade method found if R.5.

**Comment by OLStefan** [comment]
Any chance you are using Windows' scaling options?

**Comment by Nedorus** [comment]
In my case yes.
I have my PC set to 125% and things work well and are visible.
I have my laptop (touch screen convertible) set to 150% and stuff isn't visble. This is necessary as the screen is pretty small and I can't read text if it's on 100% or 125%. However the portable laptop is what I use during gaming...

I'm adding screen shots from my PC with 120% and 150% settings. The PC has the same probs when in 150% scale.
![vehicle condition monitor - screen set to 150](https://user-images.githubusercontent.com/25143888/40584676-65e1bfda-61a5-11e8-8a28-105012464a62.JPG)
![vehicle condition monitor - screen set to 125](https://user-images.githubusercontent.com/25143888/40584677-66030a14-61a5-11e8-96e8-a67b3a68b61e.JPG)
![options window - screen set to 150](https://user-images.githubusercontent.com/25143888/40584678-6624d9be-61a5-11e8-87e2-3e82a7058b02.JPG)
![options window - screen set to 125](https://user-images.githubusercontent.com/25143888/40584679-664760c4-61a5-11e8-8294-fa7aa18af7d1.JPG)

Cheers and cudos for always fixing stuff so quickly! GitHub needs a Cudo-Wall ;-)

**Comment by Pjokk** [comment]
I checked the scaling option, and yes, I was at 150%. Tried 125%, everything was fine, just as it should be. It didn't even occur to me to check out the scaling. That said, would it be possible to make Chummer5a work with 150% scaling? If you want to try it, put it under misc. or something, it's not important. Thanks for the help.
