### ISSUE TITLE
Radical and Refined Reagents use outdated Shadow Spells costs

### ISSUE THREAD

**Issue by drynwyn** [chummer5a/chummer5a#2766]
### Environment
Chummer Version: 5.200.19
Environment: Windows 10
Runtime: N/A
### Expected behaviour
Should use the costs for Radical and Refined reagents published in the more recent Forbidden Arcana over Shadow Spells (page 187, "Updated Reagent Cost and Effects")
### Actual behaviour
It uses the costs for Radical and Refined reagents published in the older Shadow Spells "Reagent Cost" table (Page 24). 

### Steps to reproduce the behaviour
Look at the cost for Radical/Refined reagents, compare to the book table.

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
That table confuses and annoys me. What's 'Type' supposed to be?
