### ISSUE TITLE
Cyberware just dosen't work as they are suppose to 

### ISSUE THREAD

**Issue by Ravoos** [chummer5a/chummer5a#2767]
### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behavior
The cyberware I got installed it suppose to increase my Agility and Reaction.

### Actual behavior
It doesn't....it just doesn't. It stays on the Agility and Reaction I got naturally (7 & 5). However, my essen did go down, so it should work.

### Steps to reproduce the behavior
Not entirely sure. Might be when I began to work on my things (guns, bike, armor and things). 

### Link to affected character file
https://drive.google.com/file/d/1bMLg_kaKqKw1Ts60BSAYYCV5N6_Y3V20/view?usp=sharing

**Comment by chummer5a** [comment]
Should be working properly in the current nightly build.

**Comment by chummer5a** [comment]
Should be working properly in the current nightly build.

**Comment by Ravoos** [comment]
I'll look it up.

**Comment by Ravoos** [comment]
That one seem to crash a lot for some reason.

**Comment by chummer5a** [comment]
Most likely some stuff that I repaired in the interim commits. Try 5.200.24

**Comment by Ravoos** [comment]
I will.

**Comment by Ravoos** [comment]
It doesn't work either. However, I do think it becomes like that when I work on my armor.

**Comment by chummer5a** [comment]
Without a specific way to reproduce it, I can't be much help I'm afraid.

**Comment by Ravoos** [comment]
From what I understand. When I start putting in my armor and modifications (especially on the mask), it starts to fuck up.

**Comment by chummer5a** [comment]
Can't reproduce the issue; wired reflexes and reaction enhancers don't stack unless they're both running wireless, which Chummer doesn't currently track. Everything else seems to be correct.

**Comment by Ravoos** [comment]
I'll.....I'll try to redo my character from scratch.

**Comment by chummer5a** [comment]
That shouldn't be necessary, I'm just not sure what the problem is. What are you expecting to see that you don't?

**Comment by Ravoos** [comment]
My agility and Reaction shouldn't be my base stat with the cyber-/bioware. It should be increased.

**Comment by chummer5a** [comment]
Oh, I see the problem. The tooltip wasn't being updated properly because your attribute bonuses were equal to your penalties. You have 8 points of stacking armour but only 4 strength, which generates two points of encumbrance. Each point of encumbrance adds an equal dicepool penalty to AGI and REA. The next nightly build will properly show your attributes as calculated.
