### ISSUE TITLE
Chummer crashes when adding gear to armor or clicking on a location in the armor tab

### ISSUE THREAD

**Issue by DaRasch** [chummer5a/chummer5a#2768]
### Environment
Chummer Version: 5.200.23
Environment: Windows 7
Runtime: probably .NET 4.5.1

### Expected behaviour
Application does not crash

### Actual behaviour
Application crashes with empty crash log

### Steps to reproduce the behaviour
- Create character
- Switch to armor tab
- Add some armor
- Add gear to the armor or click on the default location

### Link to affected character file
Works on any character

**Comment by Zitchas** [comment]
Possibly related: When trying to replicate this bug, Chummer crashed at the 3rd step while trying to add some armour. (Specifically, I added Actioneer Business Clothes. While it did appear in the armour list, Chummer immediately crashed before I could do anything else. 

The crash log was also empty. Well, technically, it has the two lines about "This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it" But no additional data.

**Comment by DaRasch** [comment]
Yes, I also found that adding armor with built-in gear directly crashes. I guess that is caused by the same bug as adding gear afterwards.
