### ISSUE TITLE
[Data Inquiry] Understanding critters.xml

### ISSUE THREAD

**Issue by dashifen** [chummer5a/chummer5a#2771]
In the critters.xml, walking, running, and sprinting rates are given as a set of three numbers:  x/y/z.  If I'm understanding correctly, x is the critters movement rate on the ground, y is their movement rate in water, and z is their movement rate in the air.  But, some times, critters have "extra" information in their rates.  

For example, an eagle lists its movement rates as follows:

```
<walk>2/1/3</walk>
<run>4/0/7</run>
<sprint>4/1/6</sprint>
```

What are those 1's doing in the second "column" of this information?

**Comment by chummer5a** [comment]
Generally, unless something absolutely COULDN'T have a swim speed for some reason, I defaulted it to having 1/0/1. No particular reason for it, I just found it easier to parse the data in that way.

**Comment by dashifen** [comment]
That's sort of what I figured, but I wasn't sure, so I thought I'd ask.  Thanks!
