### ISSUE TITLE
Reopened: Switch between Attribute Sets for Shapeshifter Characters does not work as intended (?) 

### ISSUE THREAD

**Issue by HannoBoettcher** [chummer5a/chummer5a#2774]
See Issue #2763. The reported behaviour hasn't changed. Is my expectation wrong? What should happen when switching between metahuman and animal form?

### Environment
Retested with
Chummer Version: 5.200.24.0
Environment: Windows 10
Runtime: C++ 2017 x86 14.11.25325.0 bzw. C++ 2015 x64 14.0.24215

**Comment by chummer5a** [comment]
Blah, found the problem. New shapeshifters weren't getting the correct attribute defaults for metahuman form, it was just duplicating the metatype base stats. I'll set up a shim to regenerate the attributes properly.
