### ISSUE TITLE
Chummer 5a uses WPF which is not supported by mono

### ISSUE THREAD

**Issue by Myrddin42** [chummer5a/chummer5a#2777]
### Environment
Chummer Version: chummer5a-Nightly-v5.200.2
Environment: debian stretch
Runtime: Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:49:46 UTC 2018)

### Expected behaviour
The Chummer 5a source can be compiled by monodevelop

### Actual behaviour
The build process in monodevelop fails with the error "This project type is not supported by MonoDevelop."

### Steps to reproduce the behaviour
* Build a docker container from the following Dockerfile via the command: `docker build -t local/monodevelop .`
```
FROM debian:stretch

# update the packet cache since it is empty in the container
RUN apt-get update

# install basic needed packages
RUN apt install -y apt-transport-https dirmngr sudo

# install X11 and the gsettings desktop schemas (required for monodevelop)
RUN apt-get install -y xserver-xorg xorg gsettings-desktop-schemas

# add the key of the mono repo
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
# set the mono version to use
ENV MONO_VERSION 5.12.0.226
# install mono
RUN echo "deb http://download.mono-project.com/repo/debian stable-stretch/snapshots/$MONO_VERSION main" > /etc/apt/sources.list.d/mono-official-stable.list \
  && apt-get update \
  && apt-get install -y mono-runtime mono-devel

# add the monodevelop repo, update our package source, and install monodevelop
RUN echo "deb https://download.mono-project.com/repo/debian vs-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list \
  && apt-get update \
  && apt-get install -y monodevelop

# remove the apt list files since all needed packages were installed
RUN rm -rf /var/lib/apt/lists/* /tmp/*

# set up the user to use in the container
# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

# set the container user
USER developer
# set the user home directory
ENV HOME /home/developer
# set the workdir of the container
WORKDIR /home/developer


#COPY chummer /home/developer

ENTRYPOINT ["/bin/bash"]
```
* Run the container giving it access to your X server
```
docker run -it --rm --net=host -e DISPLAY -e XDG_DATA_DIR -v <path to your .Xauthority directory>:/home/developer/.Xauthority -v <path to the directory with Chummer 5a source code>:/home/developer/chummer-source local/monodevelop
```
* launch mondevelop from the container via the command (needs to be run two times; monodevelop should start on fully on the second execution): `mondevelop`
* open the Chummer 5a.sln file in monodevelop
* try to compile Chummer 5a

### Assumed cause
Monodevelop shows that the assemblies PresentationCore and PresentationFramework were not found for the .NET Framework 4.5.2 and a quick google lookup brought up [that the Presentation Framework is not supported by mono.](http://www.mono-project.com/docs/gui/wpf/)
Also analysing the project with monodevelop brought up that the namespaces System.Windows.Controls (referenced in chummer5a-Nightly-v5.200.2/Chummer/frmExport.Designer.cs) and System.Windows.Navigation (referenced in chummer5a-Nightly-v5.200.2/Chummer/Backend/Improvements/ImprovementMethods.cs) do not exist in the namespace System.Windows. I would assume that they're subject to the Presentation Framework and therefore also missing.

### Possible Solution
Switching to [Xamarin.Forms](https://www.xamarin.com/) **could** solve the issue since this framework is especially build to be cross platform. But this is only partly true because Linux as such is not *officially* supported since mono varies slightly from distro to distro (so it would still be tricky but at least it should be possible). Also I don't know how much it supports Windows since they wrote that it supports *Universal Windows Platform apps* and I've no clue what that includes or excludes.

### In the end
Chummer 5a can not be run via mono in its current state therefore please consider to remove the mention of running it via mono from your installation guide. I don't know if this issue also makes it impossible to run it via wine but from what I found [here](https://forum.winehq.org/viewtopic.php?t=14392) and [here](https://forums.dotnetfoundation.org/t/cross-platform-wpf/421?page=4) it is probably also not possible.

### Probably related issues
#2584
#1558
#2246

**Comment by Myrddin42** [comment]
Well it seems I was wrong with Xamarin being a viable alternative. I've searched the web and found no tutorial or other thing to actually use Xamarin on linux besides the mention from Xamarin developers that the linux support *should* come.

**Comment by chummer5a** [comment]
Those references are unused anyway, so I've pulled them out of the listed files. That said, linux support for Chummer is more of a nice-to-have rather than a concrete design pillar.
