### ISSUE TITLE
Bug and missing content

### ISSUE THREAD

**Issue by thordyn** [chummer5a/chummer5a#2778]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer 5
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
1. Clicking add spell button should bring up a menu 2. invocation does not exist in initiations 3. arboreal does not exist in paranormal critters
 
### Actual behaviour
1. Add spell button becomes unclickable after a little while working on the document. 2. n/a 3 n/a

### Steps to reproduce the behaviour
Tried reloading app.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't reproduce in current nightly builds.
