### ISSUE TITLE
Lifestyle inot editable

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2780]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.30
Environment: Windows 10 x64 Enterprise
Runtime: .NET 4.7

### Expected behaviour
Be able to edit Lifestyle, see the configured properties

### Actual behaviour
No editting, Nothing is Display
The same for old Lifestyles and for newly added

### Steps to reproduce the behaviour
Open Char -> Streetgear -> Lifestyle
select a Lifestyle or add a new one

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't reproduce it. Provide a character file?

**Comment by ReallyDarkMatter** [comment]
[Frank -Hardrock- Pfeiffer - Final.zip](https://github.com/chummer5a/chummer5a/files/2069778/Frank.-Hardrock-.Pfeiffer.-.Final.zip)

**Comment by chummer5a** [comment]
Seems to be fine in the  current build/can't reproduce with that file.
