### ISSUE TITLE
Armor Bundles are not working Chummer closes

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2781]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

Chummer Version: 5.200.30
Environment: Windows 10 x64 Enterprise
Runtime: .NET 4.7

### Expected behaviour
See and work with Armor Bundle.
![armor bundle](https://user-images.githubusercontent.com/12108972/40914612-2c35090e-67f9-11e8-800e-8b49cca16b5a.JPG)

### Actual behaviour
see attached pic.
Trying to delete the empty bündle, i got requestors asking if i really want do delete and then Chummer just closes

### Steps to reproduce the behaviour
Open Char, klick on "empty" Armor Bundle respond to the requestors.
Armor Bundle is not deleted and Chummer just Closes.
It is reproducable, same i had to repeat the process a few time before chummer closes

### Link to affected character file
(Enter text here)

**Comment by StarWeaver** [comment]
There was this problem with this that also applied to gear locations and similar funcitons elsewhere. Are those still working? Don't have energy to check right now.

**Comment by ReallyDarkMatter** [comment]
[Frank -Hardrock- Pfeiffer - Final.zip](https://github.com/chummer5a/chummer5a/files/2069786/Frank.-Hardrock-.Pfeiffer.-.Final.zip)
