### ISSUE TITLE
gameplayoptions.xml has 'Street Level' and 'Street Scum', duplicates?

### ISSUE THREAD

**Issue by gdelmee** [chummer5a/chummer5a#2782]
Looking at 'gameoptions.xml' file, we can find 'Street Level' and 'Street Scum' gameplay options.
Street level is referenced in the rulebook but not street scum.
Also, they both share the same values. 

### Environment
Chummer Version: 5.200
Environment: N/A
Runtime: N/A

### Expected behaviour
Having consistent options regarding the rules.

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
It's used for priorities.xml mapping.
