### ISSUE TITLE
Button to Close Options Screen Missing

### ISSUE THREAD

**Issue by duncanmb** [chummer5a/chummer5a#279]
![options menu](https://cloud.githubusercontent.com/assets/12192987/8700536/55343956-2ada-11e5-8a79-3bb36d89f0f9.jpg)

I opened the Options menu in the current build to check on something and found that the dialog box rendered without the "Ok" button to let me close it, and without the Title Bar Buttons.

**Comment by chummer5a** [comment]
That's a bit odd. Is it still happening in the current version?

**Comment by duncanmb** [comment]
Been on vacation and didn't get a chance to check whether it was still happening.  The bug is still present in 0.5.171.0, even after a clean redownload.
