### ISSUE TITLE
adept power not workin correctly in german translation

### ISSUE THREAD

**Issue by TheL1ne** [chummer5a/chummer5a#2791]
### Environment
Chummer Version: 5.200.2
Environment: Windows 10 auto updated (with Spring Update)
Runtime: 4.7.2

### Expected behaviour
Upon adding adept powers using the german translation of chummer5a I tried to add "Gebieterischer Ton" which is a power adding dice to comparing social tests initiated by the adept himself. I would expect to be able to change the level for the power costing 0,25 points per level.

### Actual behaviour
There is only one level for the power and the reference points to "SS 207" whatever that means. It is actually on page 199 of street grimoire:
![bandicam 2018-06-09 08-45-07-973](https://user-images.githubusercontent.com/16411892/41188740-8f7ac7de-6bc2-11e8-954d-0d7e8cd55c89.jpg)
I suspect something going wrong with the translation because there is the power "Befehlsstimme" which should be on page 207 of street grimmoire but that is not the case for the german translation (on page 207 are the ways of the adepts)

### Steps to reproduce the behaviour

- change language to german
- Create a new character in karma mode
- add the adept advantage
- try to find "Gebieterischer Ton" in the program

### Link to affected character file
https://www.dropbox.com/s/oj679tkok8cvebz/mike%20-%20Kopie.chum5?dl=0

**Comment by chummer5a** [comment]
The German version seems to include Commanding Voice from Stolen Souls; the powers initially had the same name and were renamed then got fixed in errata, so I've applied the rename for the Stolen Souls version and added an amend entry to pull it into Street Grimoire.
