### ISSUE TITLE
chummer 5  dont start 

### ISSUE THREAD

**Issue by RiyuDEstra** [chummer5a/chummer5a#2792]
### Environment
Chummer Version: (What version of chummer are you running?
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
the file should start

### Actual behaviour
the crashHandler give me the file ,, chummer_crash_131731000891844865  ,,

### Steps to reproduce the behaviour
start chummer exe.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Version? Operation system?

**Comment by RiyuDEstra** [comment]
chummer 5a 
windows10 ?

**Comment by RiyuDEstra** [comment]
data version 5.200.2.0

**Comment by RiyuDEstra** [comment]
ok thanks
