### ISSUE TITLE
HK XM30 configurations

### ISSUE THREAD

**Issue by SirBrick01** [chummer5a/chummer5a#2793]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2.0
Environment: Windows 10
Runtime: NET 4.5.1

### Expected behaviour
Purchasing the HX XM30 in career mode dose not give the full list of stats for each weapon configuration.

### Actual behaviour
Purchasing the HX XM30 in create mode dose give the full list of stats for each weapon configuration.

### Steps to reproduce the behaviour
Created new character and used copy of existing character. Stats for weapon configurations do carry over if converted to career after purchasing.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Fixed in current nightly builds.
