### ISSUE TITLE
Vehicle list corrupted

### ISSUE THREAD

**Issue by tnbh** [chummer5a/chummer5a#2799]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.39
Environment: Windows 10 Pro 1803
Runtime: probably .NET 4.5.1

### Expected behaviour
A list of vehicles

### Actual behaviour
A corrupted list

### Steps to reproduce the behaviour
Try to add a vehicle

### Link to affected character file
https://drive.google.com/file/d/1ylo1-XWfDGHSbmpe3zywvMOrKLXtz_CG/view?usp=sharing
![chummervehicleerror](https://user-images.githubusercontent.com/40197526/41279051-bbb23df8-6e2b-11e8-8fa9-0ee24da5d4a5.jpg)

**Comment by chummer5a** [comment]
Fixed in previous commits, will be in the next nightly.
