### ISSUE TITLE
Jack of All Trades, Master of None Quality

### ISSUE THREAD

**Issue by duncanmb** [chummer5a/chummer5a#280]
Currently, it appears that the Jack of All Trades, Master of None Positive Quality from Run Faster is being applied in the tooltip, but is not being applied within the Karma expenditure tracking.  I selected a new skill, which the Tooltip properly showed as costing 1 karma, but the confirmation popup listed the cost as 2 karma and the Karma tracking log listed a change of -2 rather than -1.

![karma expenditure](https://cloud.githubusercontent.com/assets/12192987/8700903/acf86bd8-2adc-11e5-97e0-1d710525830d.jpg)
![confirmation box](https://cloud.githubusercontent.com/assets/12192987/8700904/ad0cdd02-2adc-11e5-8abb-ddecee1833ab.jpg)
![tooltip](https://cloud.githubusercontent.com/assets/12192987/8700905/ad0e8e18-2adc-11e5-9f2e-508837ec293b.jpg)

**Comment by chummer5a** [comment]
Currently the jack of all trades trait only works in career mode. Creation Mode's CalculateBP is a whoooole other nightmare. Should be fixed in the next verison.

**Comment by chummer5a** [comment]
Fixed in 5.172.
