### ISSUE TITLE
Issue with Add Vehicles/Drones Tab

### ISSUE THREAD

**Issue by DTHatton** [chummer5a/chummer5a#2800]
### Environment
Chummer Version: 5.200.39
Environment: WIN7 Home
Runtime:  4.6.2

### Expected behaviour
When attempting to add a vehicle or drone, a new window opens with a scrolling list of all the available which you can select.

### Actual behaviour
When attempting to add a vehicle or drone, a new window opens with a scrolling list of all the available which you can select, however the list is a bunch of random alphanumeric characters and when you select one (click), it crashes.

### Link to affected character file
You can message me on Discord **Doctor Diabolical#2433**.

**Comment by chummer5a** [comment]
Already fixed, will be in the next nightly build.
