### ISSUE TITLE
German Datachanges: Heightend Concentration does not work

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2806]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.43
Environment: Windows 10 x64
Runtime: 4.7

### Expected behaviour
Add Heightend Concentration to char. Expect to set the Level of the Gift

### Actual behaviour
Heightend Concentration Costs 8 Point and i was was not asked with Level i want to have it.

### Steps to reproduce the behaviour
Create new Char and add Heightend Concentration

### Link to affected character file
(Enter text here)

**Comment by holgerschlegel** [comment]
After adding the quality, there is a spinner control above the list of qualities. Use this to add additional levels for a quality. Which, of course, costs karma.

The quality "Heightend Concentration" costs 4 karma per level during character creation, and 8 karma per level in career mode.

**Comment by ReallyDarkMatter** [comment]
Thanks a lot,
i didn't see, i added it and searched in the selection screen for the level
