### ISSUE TITLE
Enhancement: Add realistic Calender

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2807]
Would it be possible to add a realistic Calender to Chummer?

**Comment by chummer5a** [comment]
![image](https://user-images.githubusercontent.com/11448441/41505675-4f23f04e-7251-11e8-89a6-d73ebfc21143.png)

In progress, just has some quirks that need ironing out.

**Comment by chummer5a** [comment]
Duplicate of #538
