### ISSUE TITLE
Custom Data Directories to Use stored global

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2808]
### Environment
Chummer Version: 5.200.43
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The selected custom data directories should be stored in the same place as the book selection.

### Actual behaviour
It looks like the custom data directory selection is stored in a global place (registry, user home directory).
This way, it is not possible to use two different "installations" of Chummer5a with different custom data directories selected.

### Steps to reproduce the behaviour
Start an existing "installation" of Chummer5a and select at least one custom data directory.
Download and unzip Chummer5a zip file into a new empty folder.
Launch the new Chummer5a installation and check selected custom data directories.

**Comment by chummer5a** [comment]
Duplicated by #3532
