### ISSUE TITLE
Straight Magicians have no magic stat

### ISSUE THREAD

**Issue by drewikari** [chummer5a/chummer5a#2811]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.2
Environment: (Operating system here. If it persists over multiple OS's list them all)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
In both Create and Career modes should have a magic stat

### Actual behaviour
No Magic stat in either mode

### Steps to reproduce the behaviour
Redownload chummer.  Reapply stats.  Multiple characters on multiple computers

### Link to affected character file
Many different ones.  All straight mages with myself and three other friends

**Comment by Zitchas** [comment]
When you re-download Chummer, are you re-downloading 5.200.2, or are you updating it to the current 5.200.43?

If you aren't updating to .43, I highly recommend you do so. There have been a lot of fixes in the 41 versions between the one you are using and the current one. (Also, I've made several straight mages in the past week, and they've all had magic stats.

**Comment by chummer5a** [comment]
There's going to be a bump up to 5.201 sometime in the next 12-24 hours, I'm tired of waiting for Street Lethal to come out.

**Comment by drewikari** [comment]
Downloaded the .43 version from the website.  Still no Magic on any characters in either mode.
