### ISSUE TITLE
'Illusionist mastery quality' should not count towards the spells known

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#2812]
### Environment
Chummer Version: Chummer.Nightly-v5.200.43
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
On character creation, adding the 'Illusionist mastery quality' should not count towards the spells known.

### Actual behaviour
Each level of the 'Illusionist mastery quality' blocks 2 spells known. So, if you can learn 7 spells without karma and take 'Illusionist mastery quality'  level 2 there are only 3 spells left.

### Steps to reproduce the behaviour
Create a Magic Adept, take spellcraft 6, specialise illusions, add the 'Illusionist mastery quality' and look at the right side at spells known versus free spells available at character generation.

### Link to affected character file
[Ghost_MenschFK-MagieAdept - Kopie.zip](https://github.com/chummer5a/chummer5a/files/2114184/Ghost_MenschFK-MagieAdept.-.Kopie.zip)

**Comment by chummer5a** [comment]
It's a mastery quality, so you can spend spell points at a 1:5 ratio to discount qualities. It's more efficient to spend the spell points on quality, potentially freeing up karma to spend on other things, so there's no real incentive for us to implement it as a manually-toggleable option.
