### ISSUE TITLE
Feature Request: rationalise TAB order

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2814]
### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When pressing TAB key to cycle through input boxes, the order should be in a rational order: generally from left to right, top to bottom, within the same category of inputs.

### Actual behaviour
The actual TAB order seems mostly random. Making keyboard operation unnecessarily cumbersome and reducing usability.

### Steps to reproduce the behaviour
Order the input boxes to follow some kind of logical TAB order.

**Comment by chummer5a** [comment]
Should have been resolved in the big UI sweep that delnar did a while back.
