### ISSUE TITLE
updated from .198.0 to .200.50 and pdf links no longer functioning

### ISSUE THREAD

**Issue by Wyyve** [chummer5a/chummer5a#2815]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.50-5.198.0
Environment: windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behavior
when the page bookmarks are clicked they should open the pdf from the indicated location.

### Actual behavior
when page bookmark is clicked nothing happens.

### Steps to reproduce the behavior
i have tried re-entering the file locations to no avail and moving the files to another location and loading those to force the file to re-update but also to no avail. i tried changing the pdf format from sumatra to acrobat and still got nothing. 

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Does the Test button work, or is it the Source links that are failing?

**Comment by Wyyve** [comment]
test button works source link do not, tested in 200.51 aswell
