### ISSUE TITLE
Feature Request: Showing Conditional Modifiers on Character Sheet

### ISSUE THREAD

**Issue by TwistedFaith84** [chummer5a/chummer5a#2820]
I'm sure this would be mostly for Adepts/Mystic Adepts/Magicians but is it possible to show Conditional Modifiers on the character sheet for any Adept Powers/Spells (as if your selected Powers/Spells are effecting you). For example My Mystic Adept has all 4 Attribute Boost Adept Powers at rating 4 and Increase Attribute (BOD, CHA, STR) Spells; Can my character Sheet show me what my stats would be if any and all of those Powers and Spells were active on me?

**Comment by chummer5a** [comment]
The best way for you to implement that would be through the Improvements system, but chummer isn't really designed with conditional bonuses for attributes and skills in mind.

**Comment by TwistedFaith84** [comment]
Ok. As someone who doesn't know how to use Chummer that much how would I go about doing that?
