### ISSUE TITLE
No details for 'Reflex recorder' in the character sheet

### ISSUE THREAD

**Issue by gdelmee** [chummer5a/chummer5a#2821]
Adding reflex recorder to a character, it shows the affected skill in the cyberware list but not in the character sheet. Having several reflex recorders, it could be good to have the details.

### Environment
Chummer Version: 5.200.50
Environment: Windows 10 Pro 1803
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Having the affected skill in parenthesis in the character sheet.

### Actual behaviour
Only reflex recorder is shown.

### Steps to reproduce the behaviour
Create a runner, add reflex recorder in the cyberware tab and preview the print.

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
Not difficult to fix, the sheets just need to be updated to use the Extra field. Might be worth just switching everything to use the full DisplayName instead of DisplayNameShort, will need to review how the names are used.
