### ISSUE TITLE
Distributed deck in armor causes armor to crash when clicked.

### ISSUE THREAD

**Issue by inucune** [chummer5a/chummer5a#2822]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.200.23
Environment: Win 10 x64
Runtime: (If you don't know this, it is probably .NET 4.5.1) we'll go with that

### Expected behaviour
clicking armor piece in the "armor" section or the distributed deck should allow interaction (such as unequip)

additional found while trying to find reproduce path: adding armor at all causes crash

### Actual behaviour
Clicking the armor piece, or the distributed deck option causes chummer to crash.
clicking "add armor" causes crash.
clicking sub items below 'Distributed deck' does not cause crash

### Steps to reproduce the behaviour
step 1 click add armor select any (ex armored jacket)
step 2 add distributed deck option
step 3 select mct trainee

click distributed deck or host armor item... chummer crashes.

### Link to affected character file
(.Chum5 renamed to .txt to allow upload)
[Rambelon.txt](https://github.com/chummer5a/chummer5a/files/2131321/Rambelon.txt)

**Comment by chummer5a** [comment]
Can't replicate in current nightly builds. Please try again with 200.55.

**Comment by inucune** [comment]
new version does not have this issue.
thanks.
