### ISSUE TITLE
Bugged Qualities upon switching priorities

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2831]
### Environment
Chummer Version: 5.200.2
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
When using the Special>Change Priority Selection, other qualities should not be affected.

### Actual behaviour
Some metatype's (eg. Dryads, there may be others) innate qualities get corrupted when changing priorities.

### Steps to reproduce the behaviour
1. Create a Dryad character.
2. Go into Special>Change Priority Selection.
3. Change priorities without changing the matatype/metavariant.
4. The resulting character will have lost the Distinct Style quality.

Also, switching between Elf and Dryad also produces unexpected results:
1. Create a Dryad character.
2. Change it to Elf.
3. Change back to Dryad.
4. The resulting character may have multiples of Glamour and Symbiosis.

**Comment by chummer5a** [comment]
Resolved in current nightlies.
