### ISSUE TITLE
Mismatch between the text of priority yuen received, and actual amount of yuen received in sum-to-ten.

### ISSUE THREAD

**Issue by emomicrowave** [chummer5a/chummer5a#2832]
### Environment
**Chummer Version:** 5.200.2
**Environment:** Tested on both Windows 8.1 and Wine on Archlinux
**Runtime**: .NET 4.5.1

### Expected behaviour
When choosing character priorities for starting yuen, chargen resources should match the value of the textbox. 

### Actual behaviour
There is a mismatch between yuen value in text box, and actual yuen received for chargen. Example:
```
| Textbox Value | Actual amount received |
| C - 50,000    |  50,000                | 
| C - 25,000    |  25,000                | 
| C - 15,000    |  15,000                | 
| D - 15,000    |  6,000                 |  <- HERE
| E - 6,000     |  6,000                 |
```

### Steps to reproduce the behaviour
Create a new character with chargen rules:
- Sum to ten
- Street Scum
- Max Avail: 10
- Sum to ten: 8

**To reproduce:**
- In the priority selection, choose Option E for Yuen first. 
- Look at available resources. (is: 6,000, expected: 6,000)
- Change Priority Selection
- choose option D for Yuen
- Look at available resources. (is: 6,000, expected: 15,000)

### Link to affected character file
Any new character works.

**Comment by cnschu** [comment]
fixed
