### ISSUE TITLE
Carbines using inappropriate skill and have inappropriate specialization tags.

### ISSUE THREAD

**Issue by Gidoran** [chummer5a/chummer5a#2838]
### Environment
Chummer Version: 5.201.0
Environment: Windows 10 v 1803
Runtime: .NET 4.5.1

### Expected behaviour
According to Street Lethal page 36, Carbines use the Automatics skill. 

### Actual behaviour
Checking the behavior of the system, Carbines are tied to Pistols, and their entries in the data files have them using the <spec> tag to mark them as using Semi-Automatics.

### Steps to reproduce the behaviour
Create a new character, go to Street Gear, add a Carbine and hover over the dice pool calculation.
Check weapons.xml entries starting on line 13230 where the Stalwart has <spec>Semi-Automatics</spec>

**Comment by chummer5a** [comment]
Should already be fixed in 5.201.1, will definitely be in 5.201.2.
