### ISSUE TITLE
FN HAR bug

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#2847]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

Environment
Chummer Version: Chummer 5.201.0
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

Expected behaviour
FN HAR: Shock Pad and Retractable Stock shouldn't work together (recoil reduction bonus shouldn't stack) according to the rules Run&Gun table at page 53

Actual behaviour
FN HAR: Shock Pad and Retractable Stock both give +1 stacking recoil reduction

Steps to reproduce the behaviour
character generation: add gun, add both modifications, both contribute to recoil reduction

Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Can't reproduce it; both are recoil group 2, so only one should be applying.

**Comment by Gugax** [comment]
Tested it again -> it just happens with a FN HAR I added some versions ago. If I delet my old FN HAR, add a new FN HAR -> it works as intended.
