### ISSUE TITLE
Issue with Collapsible Stock (Run & Gun)

### ISSUE THREAD

**Issue by Hrallk** [chummer5a/chummer5a#285]
There seems to be a problem with this particular gun mod in Chummer 5. It is impossible to add a collapsible stock to a Pistol/Machine Pistol/SMG.

As I mentioned earlier in the thread on 4chan, I believe the problem is that the collapsible stock is encoded it as a "stock" modification and only shows up for weapons that come with a stock by default. (Shotguns/AR/Sniper Rifles).

**Comment by joha4270** [comment]
Chummer strives to RAW. As pistols to my knowledge don't have a stock slot, we don't allow it to be added to pistols. Unless you can cite catalyst saying something else this won't be added.

**Comment by Hrallk** [comment]
Well, you might want to get a look at the Beretta 201T, the Ceska Black Scorpion and all SMG's save the Ingram and Praetor from the core book. All of them have a detachable/collapsible/removable stock (which ironically is never described in said book, but that's another problem.) This tends to prove that all weapons are supposed to have a "stock" option.

Now, if you would argue that one single exception to the rules isn't enough, then by all means don't add it for pistols, but at least add it for Machinepistols and SMG's.

**Comment by chummer5a** [comment]
The only real limitations I'm seeing for accessories and modifications is that light pistols can only have top- and barrel-mount accessories, while holdouts can't have any. So machine pistols not being able to use those mounts is an oversight. Easyfix, accessory slots will be amended in 5.162.
