### ISSUE TITLE
Extend behaviour of selecttext improvement

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2850]
- [x] During character creation, allow the value of Extra to be edited. Once in career mode this should be locked.
- [ ] Extend selecttext behaviour to allow referring to a whitelisted field in XML. Something like 
```xml
<selecttest list="corporations" />
```
- [ ] Optional: if using whitelisted value, set it to a guid that matches the string's XML node. Extend TranslateExtra behaviour to, if the value is a guid attempt to fetch the string from the XML file?

**Comment by ordeiberon** [comment]
Seconding, but seems almost identical to #2582.

**Comment by chummer5a** [comment]
First thing is already provided by allowrename flag so the original issue is resolved.
