### ISSUE TITLE
Bug: Koborokuru's Celerity quality is removable

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2852]
### Environment
Chummer Version: 5.201.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Koborokuru's Celerity quality should not be removable.

### Actual behaviour
Koborokuru's Celerity quality is removable.

**Comment by chummer5a** [comment]
It's removable in order to support cyberlegs.
