### ISSUE TITLE
Bug: PROTOTYPE TRANSHUMAN has no effect

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#2853]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.201.0
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The quality PROTOTYPE TRANSHUMAN should allow 1 point of Essence of Bioware without reducing the Essence.

### Actual behaviour
Essence reduced by installing Bioware

### Steps to reproduce the behaviour
Take the quality PROTOTYPE TRANSHUMAN -> install bioware -> essence lost

### Link to affected character file
(Enter text here)

**Comment by Sturmkind** [comment]
Works properly for me. Did you remember to click the checkbox to apply the discount when adding the bioware?

![pt](https://user-images.githubusercontent.com/23245979/42410604-5b2f13dc-81ec-11e8-80d4-f2baf3d7a589.JPG)

**Comment by Gugax** [comment]
Oh sorry, thought it would apply automaticly. What's the benefit of making it a checkbox?

**Comment by Gugax** [comment]
Tried agsain, but clicking the checkbox just reduces the description, but not my Essence lost at the bottom.

**Comment by Gugax** [comment]
Closing and reloading the character actualizes the Essence count.

**Comment by chummer5a** [comment]
Checkbox is so that you can choose which bioware is affected by it, since it's not just a blanket point of essence, it's up to one essence worth of ware. Anyway, there's an issue with the dependencies preventing it from updating dynamically.
