### ISSUE TITLE
Added pictures to: Ingram Smartgun X bug

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#2854]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

Environment
Chummer Version: Chummer 5.201.0
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

Expected behaviour
adding low light vision or another enhancement to the microcamera of the internal Smartgun System of a Ingram Smartgun X should reduce the nuyen owned

Actual behaviour
Ingram Smartgun X: adding low light vision or another enhancement to the microcamera of the internal Smartgun System doesn't cost anything

Steps to reproduce the behaviour
character generation: add gun, add low light vision or another enhancement to the microcamera of the internal Smartgun System, look at nuyen

Link to affected character file
(Enter text here)
![01](https://user-images.githubusercontent.com/40381762/42410427-a75a803c-81e9-11e8-8c10-35cb4f549fb4.png)
![02](https://user-images.githubusercontent.com/40381762/42410429-a77de82e-81e9-11e8-8b01-ff785c7b826f.png)

**Comment by chummer5a** [comment]
Already fixed in https://github.com/chummer5a/chummer5a/commit/c2c19088b53f6f63c041740df6201652ea34b056

Next nightly build is scheduled for ~10 hours from now.
