### ISSUE TITLE
Some german stuff that is broken/not included

### ISSUE THREAD

**Issue by StrikerJaken** [chummer5a/chummer5a#2855]
### Environment
Chummer Version: 5.201.0.0
Environment: (Win10)
Runtime: probably .NET 4.5.1

### Expected behaviour
Content that has been added via the german releases is available and useable

### Actual behaviour
Items that had been added via german content does not work as intended or is missing

### Affected:
-  Seal Shapeshifter, SotA p. 147, is not available

- Bodytech: Siemens Cyberspine, SotA p.80, does have the Elite Athletic upgrade, but not the Elite Warrior Upgrade. Both miss their further upgrade: "Celectial Athletic" or "Celestial Warrior"

- Bodytech: Zeiss Consortium MET2000 Sturmpionier, SotA p.80, does have an upgrade called "Trench Wires" that adds Skillwires Rating 4

- Magic Traditions: "Schattenhandbuch 3" did add 2 new traditions: "Dr.-Singer-Schule" (Dr.-Singer-School) (Page 168) and "Die Sturmkinder" (The Stormchildren) (Page 169)

I got the stuff translated for private purposes, if some quick references are needed

**Comment by chummer5a** [comment]
Phocine Shapeshifter and the bodytech are in the data and seem to be working correctly. 

Need data for the traditions.

**Comment by Gugax** [comment]
Schattenhandbuch 3 is a collection of the following rulebooks:
-	Datapuls Berlin
-	Datapuls Trollrepublik & Schwarzwald 
-	Datapuls Karlsruhe (I guess that's the one with the schools);
-	Datapuls Österreich
-	Datapuls SOX 
-	plus ein exklusiver ADL-Zusatz über Fahrzeugen aus dem Nahverkehr der ADL

**Comment by StrikerJaken** [comment]
Oh yeah, there are some Vehicles as well. I need to look them up again.

The traditions are part of the Dataplus Österreich (Austria).

**Comment by Mondlied** [comment]
The vehicles except for the EMC Kommodore should already be included, see https://github.com/chummer5a/chummer5a/commit/f7d13dc86d2537341b0f7f0aa06aee20e4ba3496

**Comment by chummer5a** [comment]
Anything else missing from this, or can it be closed?

**Comment by StrikerJaken** [comment]
Should be okay then.
I have no info if the german Street Leathal has anything added Chummer related.

**Comment by chummer5a** [comment]
Works for me!
