### ISSUE TITLE
Error about disabled options, but they are enabled

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#2861]
### Environment
Chummer Version: 5.201.15 
Environment: Windows 10 x64 
Runtime: 4.7 

### Expected behaviour
![option](https://user-images.githubusercontent.com/12108972/42534810-f50a3b32-848d-11e8-9388-9ebb8a6615b8.png)

Expect that the char loads without error

### Actual behaviour 
Get this error message

![error options](https://user-images.githubusercontent.com/12108972/42534978-771c5826-848e-11e8-98b9-865ac62c22c9.png)
 
### Steps to reproduce the behaviour
Open Chummer
load char

[Dogtag v2.zip](https://github.com/chummer5a/chummer5a/files/2181958/Dogtag.v2.zip)

An other Char, got a second error message

![error options 2](https://user-images.githubusercontent.com/12108972/42536630-dff9e724-8492-11e8-935b-2a90228ee799.png)
The second char
[Frank -Hardrock- Pfeiffer - Final.zip](https://github.com/chummer5a/chummer5a/files/2182064/Frank.-Hardrock-.Pfeiffer.-.Final.zip)

**Comment by chummer5a** [comment]
I can't replicate these issues in the latest build. Can you confirm it's still a problem?

**Comment by ReallyDarkMatter** [comment]
Just tested with 5.201.24 and both Chars open without any error message
