### ISSUE TITLE
Incorrect links to Lifestyle pages

### ISSUE THREAD

**Issue by DarkTechnician** [chummer5a/chummer5a#2863]
### Environment
Chummer Version: 5.201.0 (Though it looks like this issue has been around for at LEAST 3 months already, unreported)
Environment: Windows 7 64-bit
Runtime: Unknown, assuming .NET 4.5.1

### Expected behaviour
Open correct page of associated rulebook
(I already modified/fixed the "page offset" using the 'test open page 5' button)

### Actual behaviour
Opening 4 pages before associated rulebook

### Steps to reproduce the behaviour
Open chummer, switch to Street Gear>Lifestyle>"add Lifestyle">select "Cramped [-10%]" (without clicking checkbox), click on the source text, incorrect page opens.

Fix:
lifestyle.xml
Lines 57, 70, 83, 97, 112, 127, 170, 186
From
-       <page>369</page>
to
-      <page>373</page>

Lines 887, 896, 1004
From
-      <page>370</page>
To
+      <page>374</page>

**Comment by chummer5a** [comment]
You may have a different version of the book to what I use, master index edition from drivethrurpg matches the page references that are currently in the data.
