### ISSUE TITLE
Please add source to define what restricted / alchemic spell means

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#2867]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Chummer5.201.0
Environment: Win10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
If you add a new spell, you can choose if the spell is restricted or alchemic. As a fetish restricts a spell and is an alchemic item, I don't know what I should click. Please add an information about the rulebook and page each option relates.

### Actual behaviour
Two options without further explanation.

### Steps to reproduce the behaviour
Add new Spell.

### Link to affected character file
(Enter text here)
![unbenannt2](https://user-images.githubusercontent.com/40381762/42683101-aa4e06ea-868c-11e8-8516-e751e4b0b9a6.jpg)

**Comment by chummer5a** [comment]
There should be a tooltip when you hover over it. 

> Limited Spells require a Fetish to cast but reduce the Drain Value of the spell by 2.

Alchemical spells are Preparations, indicating that they're cast with Alchemy.
