### ISSUE TITLE
 Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Terranaut** [chummer5a/chummer5a#2870]
### Environment
Crash ID: d11e74db-a7e6-438d-85c1-479ef7437b8a
Chummer Version: 5.195.0
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
Had a run. Added Karma and Nuyen. Saved. Loaded the the save file; expected it to open the normal career overview.

### Actual behaviour
It just crashed and gave me the error window / opportunity to post this.

### Steps to reproduce the behaviour
Load this file. 
[alexei.zip](https://github.com/chummer5a/chummer5a/files/2196232/alexei.zip)

**Comment by chummer5a** [comment]
Can't replicate in 5.201.0 equivalents, strongly suggest updating.

**Comment by Terranaut** [comment]
Yeah I'm a huge moron, don't mind this.
