### ISSUE TITLE
"Decrease Attribute" dice pool calculated using incorrect attributes in Spell Defense tab

### ISSUE THREAD

**Issue by WMarks** [chummer5a/chummer5a#2874]
Chummer Version: Nightly, 5.201.25
Environment: Windows 10 Enterprise
Runtime: .NET 4.5.1

In the Spell Defense tab of a character sheet, the attributes used to calculate defense dice vs. the Decrease Attribute spells are incorrect for INT, LOG and CHA.

Decrease Attribute (INT) is calculated using CHA+WIL
Decrease Attribute (LOG) is calculated using INT+WIL
Decrease Attribute (CHA) is calculated using LOG + WIL

These three defense pools should be calculated using the targeted attribute instead.

**Comment by chummer5a** [comment]
Seems to be correct in current builds.
