### ISSUE TITLE
Move-By-Wire Intiative bug

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#288]
Long story short with Move-By-Wire Rating 3, 5 base intuition and 5 base reaction (augmented to 8 by MBW R3), it should read your initiative as 22+2d6 not 20. Though the chummer help does calculate the modifiers properly, it isn't displayed.

**Comment by chummer5a** [comment]
Chummer previously set the maximum Initiative to your REA+INT's augmented maximum. Resolved in 5.172.
