### ISSUE TITLE
Data error: Bone Lacing not adding Body

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2884]
### Environment
Chummer Version: 5.201.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Bone Lacing should add Body per table on CRB p.455.

### Actual behaviour
Bone Lacing only adds Armor, no Body.

**Comment by cfresquet** [comment]
Bone lacing only gives you "extra Body for resisting physical damage" -- it isn't used in any other body calculations.  So adding it to the base Body stat as an augmentation would be incorrect.

**Comment by aga9** [comment]
Take a look at some official character stats:
- "Tank" on CRB p.120
- Chen on Boston Lockdown p.213
- "Honest" on Cutting Aces p.100

In each case, the bone lacing directly adds to Body, instead of only as a situational modifier.

There are many more examples in official scenario NPCs stats.

**Comment by chummer5a** [comment]
Rules > Description >>>>>>>>>>>>>>>> example characters.

**Comment by aga9** [comment]
Generally I'd agree. But in this case the rules wording isn't clear or explicit; it's in the ambiguous territory. This is why the fact that the sample characters _consistently_, across _all_ the samples I found in official sources, interpret Bone Lacing as adding directly to Body should be taken into account.
