### ISSUE TITLE
Selecting the Magician quality crashes to Desktop

### ISSUE THREAD

**Issue by velian** [chummer5a/chummer5a#2888]
### Environment
Chummer Version: 5.201.29
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Selecting the Magician quality should Make character a magician

### Actual behaviour
Selecting the magician quality crashes to desktop

### Steps to reproduce the behaviour
Open Chummer. Create New Character. Select Magician quality.

**Comment by chummer5a** [comment]
Can't replicate the crash. You should have a crash report file on your desktop, can you please upload it?

**Comment by velian** [comment]
[chummer_crash_131767346139818063.txt](https://github.com/chummer5a/chummer5a/files/2216985/chummer_crash_131767346139818063.txt)

Crash reports appear to be empty.

I have figured out why it did it for me: I still had all Karma costs set to 0 (for gamemastering purposes, been a while forgot I did that). Resetting it to normal values rectified this problem.
