### ISSUE TITLE
Chummer 5.201.0: Cyberlimb Availability Calculating Incorrectly

### ISSUE THREAD

**Issue by DarkArcticDay** [chummer5a/chummer5a#2889]
### Environment
Chummer Version: 5.201.0
Environment: Windows 10 Home Edition 64 Bit
Runtime: Probably .NET 4.5.1

### Expected behaviour
When adding a Cyberlimb of a grade other than standard, the Availability adjustment should calculate based on the arm itself without taking into account customizations.

### Actual behaviour
Each individual customization (such as Customized Strength or Customized Agility) has the ware grade modifier applied (for instance, if an arm with Customized Agility 6 and Customized Strength 6 is at Avail 10 at Standard grade, it would become Avail 16 at Alpha grade, because the +2 availability modifier is applied to the Arm, the Customized Agility, and the Customized Strength, for a total of +6 when it should just be an overall +2).

### Steps to reproduce the behaviour
Add a Cyberarm to a character, give that arm Customized AGI and Customized STR 6, and then play around with the ware grade and observe the availability.

### Link to affected character file
N/A

**Comment by DarkArcticDay** [comment]
Ah, wait, sorry -- I _just_ saw that this is an optional rule nested below the German data changes.

I _believe_ this is what the default behavior should be, however.  I haven't found anything to imply the grade modifier affects customizations, but I might be wrong on that.

**Comment by DarkArcticDay** [comment]
One other thing I noticed: with the optional rule in place, the customization cost appears to stay static at 5,000 per point regardless of trade.

I believe RAW, the intention is that the cost is multiplied based on grade, but not availability (since Customization is specifically "Cyberlimb + 1" per point).

**Comment by chummer5a** [comment]
Can't replicate the lack of price increase; the grade thing is more or less a legacy element as all cyberware children are forced to be of the same grade as their parent. Since we treat customisations and mods are treated as cyberware for our purposes, it applies the grade modifier. Either way I've never had a comment on it for RAW.
