### ISSUE TITLE
Character Sheets not loading

### ISSUE THREAD

**Issue by RedLion0** [chummer5a/chummer5a#289]
Was having this problem with the previous version of chummer as well. None of my character sheets are loading for some reason, all kicking back the same error (as far as I can tell). One of these characters was even made just three weeks ago.

Error: http://pastebin.com/eZU3AP9d

Sample save file for a character: https://www.dropbox.com/s/zyxsg2emg0fwj6w/Gutbeard.chum5?dl=0

**Comment by Iridios** [comment]
Open the Options dialog and make sure the "Use Debug Logging" is NOT checked.  The Chummerlog.txt is generated by this option.

**Comment by RedLion0** [comment]
Oh. Wow. Yup, that fixed it. Thank you!
