### ISSUE TITLE
No +1 or -1 qualities after update 

### ISSUE THREAD

**Issue by Thvari** [chummer5a/chummer5a#2895]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (Build 201
Environment:Windows 10 (64 bit)
Runtime: NET 4.5.1

### Expected behaviour
in positive and negative qualities there should be 1 and -1 pt qualities

### Actual behaviour
the 1 and -1 pt qualities do not show since update on new characters

### Steps to reproduce the behaviour
start new character, attempt to take record on file. use  exact match search function for qualities no 1 or -1 pt qualities exist

[Sparks 2.0.zip](https://github.com/chummer5a/chummer5a/files/2228683/Sparks.2.0.zip)

.
### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
There aren't any one-point positive qualities, and the Missions 1.4 ruleset bans Records on File. Working as intended.

**Comment by Thvari** [comment]
Thank you...I missed that the missions 1.4 was toggled on
