### ISSUE TITLE
Chummer update wiped all sheets.

### ISSUE THREAD

**Issue by Play4leftovers** [chummer5a/chummer5a#2896]
Using the Updater included in the file wipes the entire folder of everything with the exception of folders. Including all character sheets. 

### Environment
Chummer Version: (What version of chummer are you running?
Environment: Windows 10
Runtime: .NET 4.5.1

### Steps to reproduce the behaviour
Keep characters in the same folder as Chummer main file.

**Comment by chummer5a** [comment]
In theory this is kind of working as intended. There were some historic issues with old files getting cached that caused issues. Easier for us to clear everything out and start from scratch. There should be a backup zip file kept in your temp directory that would have all the old files. I'll include exceptions for .chum5 files and the saves directory.
