### ISSUE TITLE
Can't even start Chummer on Ubuntu 18.04

### ISSUE THREAD

**Issue by draxdeveloper** [chummer5a/chummer5a#2898]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: Nightly-v5.201.35
Environment: Ubuntu 18.04
Runtime: don't know, but i think its DOTNET 4.5.2

### Expected behaviour
typing mono Chummer5.exe and something happening (don't know what should happen here)

### Actual behaviour
it's returns: 
Unhandled Exception: 
System.TypeLoadException: Could not resolve type with token 0100025b (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 0100025b (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)

### Steps to reproduce the behaviour
Follow the tutorial to use Chummer on linux, using Ubuntu 18.04

**Comment by chummer5a** [comment]
I'm told mono tends to be unreliable. Try it with the winetricks instructions on the wiki.

**Comment by LueBecko** [comment]
same here. also with winetricks no success...

Another question: Why not porting the application to .NET core? Buildin multi-platform support, even better than regular .NET

**Comment by joha4270** [comment]
What did not work? I can tell you Wine works for me (even if there are some small visual issues), but a general "no success" is rather hard to help.

>Another question: Why not porting the application to .NET core? Buildin multi-platform support, even better than regular .NET

Because our GUI and several other components  we rely on does not run on .NET Core. There is a slight chance this will change for GUI and no chance at all for some other components.
