### ISSUE TITLE
Ex-Con Quality crashes program

### ISSUE THREAD

**Issue by ArtOfCombat** [chummer5a/chummer5a#2899]
### Environment
Chummer Version: 5.201.0
Environment: Windows 10 Home
Runtime: .NET 4.5.1

### Expected behaviour
Ex-Con quality creates both itself and a criminal SIN quality.

### Actual behaviour
Ex-Con quality creates a criminal SIN quality then crashes the program.

### Steps to reproduce the behaviour
Create a character with priority and all default settings and the proper books enables. Take the ex-con quality, and enter a value (In my case Tahm Mi-Hyun) for the Criminal SIN quality. The builder SHOULD crash.

### Link to affected character file
N/A

### Special Notes
Sorry for finding so many bugs, and thank you for fixing them!

**Comment by chummer5a** [comment]
Can't reproduce in current nightly builds, but there's nothing in the changelog that indicates it should've started working. Can you please try updating and see if it still crashes? There should be a chummer_crash file on your desktop when it does.
