### ISSUE TITLE
[Priority Character Creation] Prime Runner/Street Level modifications not being used. [Rls 171]

### ISSUE THREAD

**Issue by Siniq** [chummer5a/chummer5a#290]
When creating a new character using the Priority system, the modifications for character creation are always set to the Standard versions.

Max Karma: 25
Max Availability: 12
Max NuYen: 10
Contact Multiplier: 3

Steps to Reproduce
1. Create new Prime Runner/Street Level Character [Priority]
2. Convert Karma to NuYen
3. Will always allow 10 NuYen to convert, never more (Prime Runner) or less (Street Level)

**Comment by Siniq** [comment]
Was looking through the changelog in the master, and thinking this might be taken care of already when 172 is released with the gameplayoptions.xml file.

**Comment by chummer5a** [comment]
Should do, yes. I think the nuyen multiplier might be capped, but I'll fix
that up.

**Comment by Siniq** [comment]
Any thoughts on when 172 will be released?

**Comment by chummer5a** [comment]
Depends on what I feel like adding to the next build. I don't really have a
defined build&release period. Probably within the next 48 hours?

**Comment by Siniq** [comment]
Awesome.  Wasn't trying to be pushy or anything.  I was just curious.  I appreciate all you and the other devs are doing for this project.

**Comment by chummer5a** [comment]
Fixed in 5.172. ETA soonish.
