### ISSUE TITLE
Improved reflexes with Qi Focus adds extra reaction

### ISSUE THREAD

**Issue by Mandrake45** [chummer5a/chummer5a#2901]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5:201,0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Improved reflexes gained or increased through qi focus should provide the same amount of reaction as the same level of improved reflexes gained normally

### Actual behaviour
An extra point of reaction is added. This persists after the qi focus and adept power is removed

### Steps to reproduce the behaviour
Add improved reflexes adept power then add a qi focus to it

### Link to affected character file

[Qi Focus bug.zip](https://github.com/chummer5a/chummer5a/files/2241862/Qi.Focus.bug.zip)

**Comment by chummer5a** [comment]
I believe this is fixed in current nightly builds.

**Comment by chummer5a** [comment]
Orphaned improvement on that character. Hitting reapply improvements should sort it out.

**Comment by Mandrake45** [comment]
Did indeed, ty.
