### ISSUE TITLE
High Fashion Armor that includes Holsters losing capacity for said holsters

### ISSUE THREAD

**Issue by Gidoran** [chummer5a/chummer5a#2902]
### Environment
Chummer Version: 5.201.35 Nightly
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Sleeping Tiger should have a full 10 points of capacity available for use in augmentation, for example.

### Actual behaviour
Sleeping Tiger instead reports that, due to the holster consuming 3, it only has 7 available capacity out of 10. 

### Steps to reproduce the behaviour
Make a new character.
Go to Gear tab.
Add any kind of High Fashion Armor that includes a Holster (Synergist Longcoat, Sleeping Tiger, etc)
Observe that the reported available capacity is 3 less than it should be.

**Comment by chummer5a** [comment]
Fixed in d9ec6a1fa26587d4f5c9200fad5fc8fe189c6067
