### ISSUE TITLE
Burwick suit and Burwick coat stack error

### ISSUE THREAD

**Issue by BCottingham** [chummer5a/chummer5a#2906]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.201.0
Environment: Win7
Runtime: 4.5.2

### Expected behaviour
Stacking Mortimer of London Burwick Suit (9) and Mortimer of London Argentum coat (12/4)
should result in a 13 armor value (9+4=13)

### Actual behaviour
Chummer is saying armor is 12

### Steps to reproduce the behaviour
buy burwick suit, then argentum coat and set stack value to burwick suit.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Resolved in current nightly builds.
