### ISSUE TITLE
[Rls 171] Chummer.exe now requires admin privledges

### ISSUE THREAD

**Issue by taiyoko** [chummer5a/chummer5a#291]
I just updated-in-place to release 171, and now running the executable causes a request to UAC for elevation, where previous releases did not. Is this an accident or some weird quirk only on my computer?

Running Windows 7, all updates installed as of 19 Jul 2015.
![2015_07_19_21_17_58_chummer5](https://cloud.githubusercontent.com/assets/2172235/8768841/cabc49d2-2e5b-11e5-8526-494e4066623b.png)

**Comment by chummer5a** [comment]
I think there's an issue with the app manifest, it should be set to run as
user. I'll have it fixed up for the next release.

**Comment by chummer5a** [comment]
Fixed in 5.173.
