### ISSUE TITLE
Sheets ammunition name in clips not translated

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2913]
### Environment
Chummer Version: 5.201.50
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Clip ammunition name contains the translated name.

### Actual behaviour
In the print data xml file, the value in the "weapon/clips/clip/name" element contains the english ammunition name. In the GUI, the names are shown correctly translated (to German in my case).

I use a small local addition to the print sheets to show the weapon clips including the name. Thus I "need" that names translated in the print xml file.

Btw., the names has been put into the print xml on version 5.199 (which I used in the past).

**Comment by chummer5a** [comment]
Can't reproduce it in the latest build.

**Comment by holgerschlegel** [comment]
Works in the current version (5.202.4). Case closed.
