### ISSUE TITLE
Adepts can't get Commanding voice power

### ISSUE THREAD

**Issue by thingy237** [chummer5a/chummer5a#2916]
### Environment
Chummer Version: (5.201)
Environment: (Windows 10)
Runtime: (.NET 4.5.1)

### Expected behaviour
Ability to add Commanding Voice power from resource Street Grimore to Adepts

### Actual behaviour
The ability Commanding Voice from resource Street Grimore is unavailable for adepts

### Steps to reproduce the behaviour
Create an Adept with Street Grimore loaded and search for Command Voice

### Link to affected character file
Seems to be true on all character files

**Comment by Terranaut** [comment]
Commanding Voice from SG has been errata'd and is now called Authorative Tone.
Commanding Voice exists in SS.
(I can get both on a new file)

**Comment by thingy237** [comment]
Got it, thank you, yeah, I got it in SSo, just couldn't find it in SG. The more you know
