### ISSUE TITLE
Character Sheet crashes

### ISSUE THREAD

**Issue by IkariMadness** [chummer5a/chummer5a#2917]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.202.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Open character sheet of long existing character

### Actual behaviour
Crashes while loading

### Steps to reproduce the behaviour
Crashes while loading every time.  Other characters have no issues loading.  This is the only one that crashes.

### Link to affected character file
I don't know whats needed here.  Crash followup id = 64fab514-d706-4345-808c-4f113876036c
Value of '4' is not valid for 'Value'.  'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value

There's no way for me to get into the character to find the value that's causing the issue and repair it.

**Comment by chummer5a** [comment]
Can you provide the character file?
