### ISSUE TITLE
 Issue: - Crashes when attempt to open file

### ISSUE THREAD

**Issue by GenShinigami** [chummer5a/chummer5a#2919]
### Environment
Crash ID: 16cb3b81-3861-4e7f-9b71-7b2573e9acad
Chummer Version: 5.202.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
When I open Chummer and select a specific file to open, it should open the file.

### Actual behaviour
It does not.  Instead it gives me the attached error(s).

### Steps to reproduce the behaviour
I can't attach the file in question, but just attempting to open it causes the issue.

![image](https://user-images.githubusercontent.com/42360852/44063646-6b9eb0a0-9f2f-11e8-81e0-0e198a921941.png)
![image](https://user-images.githubusercontent.com/42360852/44063658-80abd78e-9f2f-11e8-845e-8da0a7612f84.png)

**Comment by chummer5a** [comment]
Kinda need the file to debug it. I suspect it's going to be something to do with the power rating panel, but I can't reproduce it. You should be able to throw it into a zip and upload it here, or you could email it to me at chummer5isalive@gmail.com.

**Comment by GenShinigami** [comment]
Sorry it took so long, I didn't know I could put it in a .zip but now I do!
[GitHub Chummer Issue File.zip](https://github.com/chummer5a/chummer5a/files/2298853/GitHub.Chummer.Issue.File.zip)
