### ISSUE TITLE
Qualities Missing from Chrome Flesh. (Attention Seeking, Sadistic)

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#292]
Attention Seeking and Sadistic are both missing. Both require no specific rules or additions to the code, they just need listing and their karma cost.

**Comment by JonJanness76** [comment]
I have Build 173: and can not find the qualities Attention Seeking and Sadistic.
![poor self](https://cloud.githubusercontent.com/assets/14168706/9722836/38d0e960-557a-11e5-8f57-0f6047b39e48.jpg)

**Comment by joha4270** [comment]
Goddammit, forgot to add their category, late, will fix tomorrow or bug to
other guy to do now


2015-09-07 23:07 GMT+02:00 JonJanness76 <notifications@github.com>:

**Comment by chummer5a** [comment]
Fixed in 5.174.
