### ISSUE TITLE
Armor Bundle Function Bugged

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2920]
### Environment
Chummer Version: 5.202.1
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Adding an armor bundle prompts the naming field, then adds the bundle in the armor list.

### Actual behaviour
The bundle is added but the name is a blank. Additionally on onecharacter, I can't delete armor bundles that existed before the current version (2 deletion prompts open but they don't have any effect) and dragging and dropping an armor into the bundle does nothing at all aside from moving it around in the armor list.

### Steps to reproduce the behaviour
Add an armor bundle, the name should be a blank.
Dunno how to reproduce the second behavior so I added the character file.

### Link to affected character file
[Red Riding Hood Karriere.zip](https://github.com/chummer5a/chummer5a/files/2287823/Red.Riding.Hood.Karriere.zip)

**Comment by chummer5a** [comment]
This should be fixed in the next nightly.
