### ISSUE TITLE
Improvement Groups Don't Work

### ISSUE THREAD

**Issue by luthengrad** [chummer5a/chummer5a#2921]
### Environment
Chummer Version: 5.202.0
Environment: Windows 10
Runtime: probably .NET 4.5.1 I guess

### Expected behaviour
Improvements can be added/placed into groups similar to the gear location system. Ability to drag and drop, right click improvement group add improvement to it, etc. 

Intending to use different improvement groups to toggle the effects of drugs on and off.

### Actual behaviour
Improvements all appear in "Selected Improvements" and can only be toggled all at once.

Looking at the character file the improvement groups are just 

`<improvementgroup>Improvement group name I set</improvementgroup>`

The improvement groups are not given a GUID. 

Attempting to include <guid> and <name> tags (or any) just results in them being stripped and the improvement group appearing named with a bunch of random hexadecimal before or after.

### Link to affected character file
[Drug Tester.txt](https://github.com/chummer5a/chummer5a/files/2290283/Drug.Tester.txt)

**Comment by chummer5a** [comment]
Should be working properly in 5.202.2, can you please try again with that?
