### ISSUE TITLE
Can't add spare clips for Narcoject One

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2922]
### Environment
Chummer Version: 5.202.2
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Buying a Spare Clip should open a prompt in which it asks you for the specified weapon.

### Actual behaviour
The prompt doesn't give the option for the NarcOne, leaving one without Spare Clips and a lot of pointy things full of sedatives in ones pockets.

### Steps to reproduce the behaviour
Try to add a Spare Clip for the NarcOne while having on in the weapon list.

**Comment by chummer5a** [comment]
Can't reproduce it. Can you show me the character file?

**Comment by MaraFaye** [comment]
I can't reproduce it anymore either, after getting 5.202.3 it seems to be gone.
