### ISSUE TITLE
Spells are not shown in Charactercreation

### ISSUE THREAD

**Issue by Althalusdlg** [chummer5a/chummer5a#293]
Hi Chummerz,

the Chummer5 is a really great work but i expected a problem for me as i wanted to creating a Magicuser. In the Prioritysystem i could pick "Magic/Resonance" to A, i picked up the two Skills i wanted and then i wanted to look at the list of Spells. But i cant found them.
Ican only see the Tabs: Common, Skills, Limit, Martial Arts, Cyberware and Bioware, Street Gear, Vehicles & Drones amd at the last Charackter Info
I activated all of the Additional Sourcebooks. But it is the same when i only have activated Core Rulebook, Shadow Spells and Street Grimoire.

Anyone a idea? I´m running Windows 7 x64 and at home (i would test it in 2 hours) i have windows 8.1 x64. .Net-Framework ist at Version 4.5.2.

So long

Althalusdlg

**Comment by joha4270** [comment]
Hi Althalusdlg

First of all, could you upload a copy of your character sheet somewhere?

Also, make  sure you selected Magican, Aspected Magican or Physad, not adept

**Comment by Althalusdlg** [comment]
I tryed to do the same with the Karmasystem... after adding the Positive Quality Magican... the Tab is shown. But for the priority System i can´t delete or ad it.

**Comment by joha4270** [comment]
1. Screenshots

2. Upload a .chum5 file where this issue is present.

**Comment by Althalusdlg** [comment]
Hello joha4270 i tryed all the time the "Aspected Magican" the i don´t see the tab, if I try a "Magician" alone it function.

**Comment by Althalusdlg** [comment]
So, here are two screenshots.
1 ist the 'Aspected Magican'
![1](https://cloud.githubusercontent.com/assets/13419333/8778575/feeb7342-2efe-11e5-942c-e31b8e276154.PNG)
2 is the 'Magician'
![2](https://cloud.githubusercontent.com/assets/13419333/8778576/feed5acc-2efe-11e5-97b5-82c1fca5c39b.PNG)

**Comment by joha4270** [comment]
Okay, can you press 

Help>About

And read out what version of chummer you have?

**Comment by Althalusdlg** [comment]
It is the newest Version( 0.5.171.0). The update that came one or two hours ago are downloaded.

**Comment by joha4270** [comment]
I think i have found the issue, but i'm unable to test at current time due my build being broken

**Comment by Althalusdlg** [comment]
No problem, maybe in the next update it is fixed. :)

**Comment by chummer5a** [comment]
Fixed in 5.172.
