### ISSUE TITLE
Protosapeint Option Gone 

### ISSUE THREAD

**Issue by niccudrat** [chummer5a/chummer5a#2934]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: ( Every edition and update I tried 
Environment: (windows 8, Inspiron laptop)
Runtime: (the past two weeks)

### Expected behaviour
(There should be three scroll down race options)

### Actual behavior
(But the category of protosapient just vanished and updates and reinstaling did nothing to help )

### Steps to reproduce the behaviour
(No idea just diapered)

### Link to affected character file
(All of them)
![i want ai damnit](https://user-images.githubusercontent.com/42557232/44370435-3aa2aa00-a4a8-11e8-9ce1-ff121688c9ad.png)

**Comment by niccudrat** [comment]
I just checked my other computer windows 10,a and it's software also is missing Proto types also!

**Comment by chummer5a** [comment]
I believe you reported this as well on the discord and the issue was that you'd enabled one of the customdata entries that blocks it like the Missions ruleset?
