### ISSUE TITLE
Lifestyle displaydoes not show all options

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#2940]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: .2020
Environment: WindBlows 10
Runtime: .NET 4.5.1
Resolution: 1900 x 1200

### Expected behaviour
Can see all my selected options in Lifestyle screen

### Actual behaviour
can see Cramped [-10], Datahost Subscription [+250], DocWagon Cc 
(that last c is most of the o but is cut off)
lifestylequalities>
        lifestylequality>
          guid>5c7196eb-316e-41d6-bf3f-7a84d8a0e5dc</guid>
          name>Cramped</name>
          extra />
          cost>0/cost>
          multiplier>-10</multiplier>
          basemultiplier>0</basemultiplier>
          lp>1</lp>
          contributetolimit>True</contributetolimit>
          print>True</print>
          lifestylequalitytype>Negative</lifestylequalitytype>
          lifestylequalitysource>Selected</lifestylequalitysource>
          source>SR5</source>
          page>370</page>
          allowed />
          bonus>
          /bonus>
          notes />
        /lifestylequality>
        lifestylequality>
          guid>c3f23fe9-fda1-437e-b8b1-d1e4e028614c</guid>
          name>Datahost Subscription</name>
          extra />
          cost>250</cost>
          multiplier>0</multiplier>
          basemultiplier>0</basemultiplier>
          lp>0</lp>
          contributetolimit>True</contributetolimit>
          print>True</print>
          lifestylequalitytype>Contracts</lifestylequalitytype>
          lifestylequalitysource>Selected</lifestylequalitysource>
          source>CF</source>
          page>80</page>
          allowed />
          bonus>
          /bonus>
          notes />
        /lifestylequality>
        lifestylequality>
          guid>8e452aca-4dcc-418e-b744-5f3a041c1f43</guid>
          name>DocWagon Contract, Gold</name>
          extra />
          cost>2084</cost>
          multiplier>0</multiplier>
          basemultiplier>0</basemultiplier>
          lp>0</lp>
          contributetolimit>True</contributetolimit>
          print>True</print>
          lifestylequalitytype>Contracts</lifestylequalitytype>
          lifestylequalitysource>Selected</lifestylequalitysource>
          source>SR5</source>
          page>450</page>
          allowed />
          bonus>
          /bonus>
          notes />
        /lifestylequality>
      /lifestylequalities>

### Steps to reproduce the behaviour
See above

**Comment by chummer5a** [comment]
Can you show me a screenshot of what you're referring to?

**Comment by SeanPGorman** [comment]
![lifestyle display issue 2940](https://user-images.githubusercontent.com/5994568/44620193-a0e74e00-a855-11e8-8a52-70d4cbcb65dd.png)
here

**Comment by SeanPGorman** [comment]
@DelnarErsike Fix checked and agreed. Thank you - formatting looks awesome.
