### ISSUE TITLE
Dialog to create custom drugs not translated

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#2947]
### Environment
Chummer Version: 5.202.13
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Support translation of the new strings.

### Actual behaviour
The dialog to create a custom drug is not translated.
The labels, buttons and the root tree nodes "Foundations", "Blocks" and "Enhancers" are shown in English (even if the UI language is set to German).
As I did not find corresponding texts in the en-us.xml file, I assume the those strings are currently hard coded and not translatable via Translator.exe.

And one improvement request:
It would be nice if the trees in that dialog would always resize to use the remaining available space in the the dialog. Especially the left tree requires scrolling even if the dialog is resized to nearly full screen.

**Comment by DelnarErsike** [comment]
frmCreateCustomDrug should now load translatable strings instead of hardcoded ones.
