### ISSUE TITLE
Cyber Singularity Seeker and some cyberware missing

### ISSUE THREAD

**Issue by sbennett117** [chummer5a/chummer5a#295]
Hey dev team,

Chummer has been a godsend so far for me, I've only just started playing Shadowrun so it's made chargen and stuff a lot easier. However, in my attempts to make a gunbunny, I discovered two items from Chrome Flesh that are missing from the latest update AFAIK.
1) Replacement Limbs can now be created from cultured bioware
2) Cyber Singularity Seeker (+1 Willpower for every two cyberlimbs) is missing from the qualities section.

If these are there, and I'm just not seeing them, any ideas why that could be?

Thanks chummers,
Stuart

**Comment by chummer5a** [comment]
Tends to take us a little while to get everything added. For what it's
worth CSS wouldn't work anyway. I'll get the replacement limbs added in for
the next build.

**Comment by joha4270** [comment]
Finally fixed in recent commits (c6173396 & bc15d6b)
