### ISSUE TITLE
Adepts should not be required choose magical tradition

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2951]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
Adepts should not have to choose magical traditions when validating character.

### Actual behaviour
Adepts without a tradition are required to choose one.

**Comment by chummer5a** [comment]
Forbidden Arcana's expanded traditions provide several examples of providing adept powers to followers of that tradition. Additionally, the use of a tradition governs the ability to participate in ritual magic and interactions with aspected background counts. 

Working as intended, really.

**Comment by aga9** [comment]
This can be seen as a compatibility issue:

In CRB adepts and traditions have nothing to do with each other. Shouldn't Chummer5 allow for CRB-only adepts who do not wish to pick a tradition?

Furthermore, ritual spellcasting requires a Ritual Spellcasting Teamwork test, which means only characters with Ritual Spellcasting skill can participate. This excludes (physical) Adepts.

**Comment by DelnarErsike** [comment]
Issue is a duplicate of #2537. You may want to check my comments in that issue for reasons why adept traditions are definitely a thing.

Note that adepts using rituals do not use Ritual Spellcasting. Check Street Grimoire p. 121 for rules on what skills adepts use for adept rituals.

**Comment by aga9** [comment]
Thanks for the heads up. I'll continue the discussion there:

https://github.com/chummer5a/chummer5a/issues/2537
