### ISSUE TITLE
Unify Silencer & Sound Suppressor

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2955]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
CRB lists a single item "Silencer/suppressor". Though it is occasionally referred to simply as "Silencer" or "Sound Suppressor" interchangeably. But there's really only 1 item that should not be listed separately.

### Actual behaviour
They are counted as two separate items.

**Comment by MaraFaye** [comment]
I think that's a carryover from SR4, there they where 2 seperate items, with different rules attached.

**Comment by aga9** [comment]
I see.
I understand there may be concerns with backwards-compatibility. I don't know if Chummer5 has a way to update obsolete items to a new item. But if that's not possible, I'd suggest handling it this way:

1. Add a new item "Silencer/suppressor".
2. Keep the existing "Silencer" and "Sound suppressor", but make it so that they can no longer be chosen from the list when adding new mods.

This way, existing files will not be bugged/obsoleted.

**Comment by chummer5a** [comment]
Names are broadly irrelevant, but it says Silencer/Suppressor in the core book, so that's what we use.

**Comment by aga9** [comment]
It's not about the name, but rather the fact that there are 2 separate items in Chummer5, while in the book there is only 1.
