### ISSUE TITLE
Request: Modifying weapon accessory layout

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2956]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

This is a request to make weapon accessories more flexible and intuitive.

I have 2 proposals:

**Proposal 1**
Add a drop-down when a weapon accessory is selected. This drop-down list allows the accessory slot to be changed.

**Proposal 2**
This one is more elaborate and requires a redesign of weapons layout:

1. Instead of weapons having slots simply as an item detail, each mod slot should be listed as a separate sub-item, similar to a weapon mount.
2. Accessories can be added to each slot, limited to accessories compatible with the slot.
3. Multiple accessories can be added to each slot. But only 1 accessory can be activated (with the "Installed" checkbox).
4. "Slide Mounts" are always activated and would allow another mod on the same slot to be activated as well.
5. Non-slot mods can be added to the weapon directly, instead of into the "slot" sub-item.

**Comment by chummer5a** [comment]
Duplicates #2040
