### ISSUE TITLE
Request: implement complete list of Action-based skill specialties

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2958]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
This is a request to add the complete list of actions for skills that can have action-specific specialties. 

This includes:
Computer, Electronic Warfare, Hardware, Software

### Actual behaviour
Only some of the actions are implemented.

*I understand there may be design reasons not to implement this. But if the request is accepted, I can provide the list of actions.

**Comment by chummer5a** [comment]
It's just a matter of data entry, wouldn't be hard for someone to do it and make a pull request.
