### ISSUE TITLE
Remove sensor function ratings

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#2959]
### Environment
Chummer Version: 5.202
Environment: Win 10
Runtime: .NET 4.5.1

### Expected behaviour
Sensor Functions' ratings are dependent on the Sensor (Single/Array) it's housed in. It doesn't need a rating on its own.

### Actual behaviour
Sensor Functions have their own ratings.

**Comment by aga9** [comment]
Think this might count as data file content bug? I'm guessing that this can be fixed purely with data file updates.

**Comment by chummer5a** [comment]
Correct per RAW. Sensor functions have a capacity equal to their rating, but they also have a maximum capacity inherent to themselves.

**Comment by aga9** [comment]
I see, I misunderstood the rule.
However, in this case there is a different bug:
The capacity of the sensor function is not reflected in the capacity of the sensor (single/array) it's attached to. Should I open a different ticket for this?

**Comment by chummer5hasanerror** [comment]
Per RAW
The amount of Active Sensors that can be used at one time is = Array Rating
(there are additional limitations involved)

If you remove the required Sensor Ratings, then you lose the ability to track things pertaining to that.

**Comment by aga9** [comment]
There remains the problem that, currently, sensor functions can have Ratings that exceed their housing.
