### ISSUE TITLE
Incorrect limit modifier condition on Enhanced Articulation bioware.

### ISSUE THREAD

**Issue by Kapten-N** [chummer5a/chummer5a#2964]
### Environment
Chummer Version: 5.202.21
### Expected behaviour
Enhanced Articulation bioware should give +1 Dice Pool for Escape Artist skill and +1 to the Physical Limit always.

### Actual behaviour
Enhanced Articulation bioware adds +1 Dice Pool for Escape Artist skill and +1 to the Physical Limit with the condition "Only for Escape Artist".

### How to fix
Remove the condition from the Physical Limit modifier given by Enhanced Articulation bioware.

### Source
https://i.imgur.com/B4QHqXL.jpg (The text is split after two rows and continues at the top of the next column, so the text may look oddly aligned after I pasted it together.)
It does not say, and does not seem to intend, that the Physical Limit increase should be exclusive to the Escape Artist skill. The great price difference between Elastic Joints and Enhanced Articulation seems to support this too (8000 nuyen + 0.2 Essence + 8 availability vs. 24000 nuyen + 0.3 Essence + 12 availability).

**Comment by ThomasN-Saab** [comment]
I commented this on the commit https://github.com/chummer5a/chummer5a/commit/e9f3f0bdef98699252a2d3d8a392b159687026ce, but I figure I might as well comment it here too.

This section:

        <limitmodifier>  
          <limit>Physical</limit>  
          <value>1</value>  
        </limitmodifier> 

can be replaced with:

        <physicallimit>1</physicallimit>

See Neo-EPO bioware for example.  
What this does is add directly to the Physical Limit instead of placing it in the modifier list. You can see the effect by holding the cursor over the Physical Limit value.

**Comment by Kapten-N** [comment]
I commented this on the commit https://github.com/chummer5a/chummer5a/commit/e9f3f0bdef98699252a2d3d8a392b159687026ce, but I figure I might as well comment it here too.

This section:

        <limitmodifier>  
          <limit>Physical</limit>  
          <value>1</value>  
        </limitmodifier> 

can be replaced with:

        <physicallimit>1</physicallimit>

See Neo-EPO bioware for example.  
What this does is add directly to the Physical Limit instead of placing it in the modifier list. You can see the effect by holding the cursor over the Physical Limit value.
