### ISSUE TITLE
Will of the Resonance echo adding wrong attribute improvement

### ISSUE THREAD

**Issue by Sevasta** [chummer5a/chummer5a#2966]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.202.18
Environment: win10
Runtime: .NET 4.5.1

### Expected behaviour
Technomancer echo 'Will of the Resonance' should add 1 to Willpower, as an augment

### Actual behaviour
Echo adds +1 to Logic as an augment

### Steps to reproduce the behaviour
put technomancer character in career mode, add karma needed to submerge, do so, add Will of the Resonance, observe att spread

**Comment by chummer5a** [comment]
Should be fixed in the next nightly build.
