### ISSUE TITLE
Manablade and Powerblade not showing in spell selection list

### ISSUE THREAD

**Issue by voodoooodoov** [chummer5a/chummer5a#2971]
### Environment
Chummer Version: 5.202.0
[Manablade MysAdept priority.zip](https://github.com/chummer5a/chummer5a/files/2358349/Manablade.MysAdept.priority.zip)

Environment: Windows 10 Home, 10.0.17134 Build 17134
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
When browsing the spell selection list, for a spellcasting character (Spells and Spirits, "Add Spell"), both Manablade and Powerblade (Hard Targets, p 192) should show up as a choice.

### Actual behaviour
Neither spell shows up in the list. (Note: the spells ARE in the spells.xml file.)

### Steps to reproduce the behaviour
Open a spellcasting character, click on the "Spells and Spirits" tab, click on the "Add Spell" button, type "Manablade" in the "Search" window, or just browse the list for "Manablade" or "Powerblade".

### Link to affected character file
Manablade MysAdept priority.chum5

**Comment by voodoooodoov** [comment]
I created a custom file for spells with just those two spells in it, generated a new GUID for each spell, saved it.  Restarted Chummer5a.  The spells now show up in the list, and are selectable.  

The custom file was the original spell.xml.  I removed all the other spells and pasted over the former GUIDs. 

I don't know the issue but this allows the spells to show in the spell selection list.  The custom_spells.xml file is attached.
[custom_spells.zip](https://github.com/chummer5a/chummer5a/files/2358420/custom_spells.zip)

**Comment by chummer5a** [comment]
Highly likely that you have the SR Missions 1.4 ruleset enabled.

**Comment by voodoooodoov** [comment]
You are correct, the SR Missions 1.4 ruleset was enabled.  That was the issue; those spells are not allowed by that ruleset.  Thanks for finding that.

This can be closed.

**Comment by voodoooodoov** [comment]
You are correct, the SR Missions 1.4 ruleset was enabled.  That was the issue; those spells are not allowed by that ruleset.  Thanks for finding that.

This can be closed.
