### ISSUE TITLE
Kill Code: One with the Matrix Quality Missing at Character Creation

### ISSUE THREAD

**Issue by Ansler** [chummer5a/chummer5a#2974]
### Environment
Chummer Version: 5.202.28

### Expected behaviour
"One with the Matrix" should be available as a positive Quality when adding Qualities at character creation for Technomancers.

### Actual behaviour
The quality appears to be missing as an option when creating a Technomancer character (or any character)

### Steps to reproduce the behaviour
1) Create new Character (Preferably Technomancer)
2) Go to add a quality
3) Search for One With the Matrix either manually or via the search bar
4) Notice the absence of One With the Matrix

If this is user error, definitely let me know.

**Comment by rabidlama704** [comment]
doesn't seem to appear in career mode either
