### ISSUE TITLE
Kill Code: Base level "Faceless" item missing

### ISSUE THREAD

**Issue by Ansler** [chummer5a/chummer5a#2977]
### Environment
Chummer Version: 5.202.29

### Expected behaviour
When adding gear to a character the base level "Faceless" item (Avail: (Rating x2)F Cost: Rating x500) from KC 57 should appear in either the Disguises or Show All drop down options.
### Actual behaviour
When adding gear to a character the base level "Faceless" item (Avail: (Rating x2)F Cost: Rating x500) from KC 57 is missing from the list. Only the higher level Faceless: Generic and Faceless: Specific Face show up.

### Steps to reproduce the behaviour
1) Attempt to find Faceless in the add gear interface.
2) Notice that only the two higher cost options are there but not the base level.

**Comment by chummer5a** [comment]
This should have already been present as Faceless - Blurred Face, but I've tweaked the availability a little. Still, should have showed up correctly anyway.

**Comment by Ansler** [comment]
Yeah it was fixed with one of the recent nightlys
