### ISSUE TITLE
Kill Code: "Trode Patch" Item missing

### ISSUE THREAD

**Issue by Ansler** [chummer5a/chummer5a#2979]
### Environment
Chummer Version: 5.202.29

### Expected behaviour
Being able to add Trode Patch to a character in the gear section

### Actual behaviour
Trode Patch is nowhere to be seen

### Steps to reproduce the behaviour
1) Try to find Trode Patch when adding gear to a character
2) See that Trode Patch isn't in the list

**Comment by Ansler** [comment]
Normal Trodes have a rating as well don't they?

**Comment by chummer5a** [comment]
Just an implied Device Rating.
