### ISSUE TITLE
Finalized characters can't awaken

### ISSUE THREAD

**Issue by mithosaurion** [chummer5a/chummer5a#298]
Hello, I am somewhat new to this whole github thing but I thought I would mention this since I didn't see it mentioned anywhere else.  When a finalized character has enough karma to purchase an awakened quality (Adept, Magician, Mystic Adept, etc.) they can purchase it, but the quality does nothing.  They don't gain the appropriate tabs (like spells for a magician) nor do they gain the ability to purchase the Magic (MAG) attribute.

**Comment by chummer5a** [comment]
Sorry for the lack of response with this one; technically speaking, you're not supposed to be able to take the adept, magician, etc. qualities without already having a MAG score. Normally that would come from a quality like Latent Awakening, but 5e doesn't have that. So what's going on is your character awakens, then the code determines that you've just burned out all your magic, so it disables your MAG score, and converts any points in active magic skills you have into knowledges.
