### ISSUE TITLE
Different skills for Parashield Dart Pistol / Rifle in German core rulebook

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#2985]
**Environment**
Chummer Version: 5.202.32

**Expected behaviour**
German core rulebook (4th printing) uses _explicit_
- pistols skill for Parashield Dart Pistol (page 432)
- rifle skill for Parashield Dart Rifle (page 433)

Instead of 'uses Heavy Pistol ranges' / 'uses sporting rifle ranges' in German core rulebook it is 'uses pistol skill, uses Heavy Pistol ranges' / 'fired with rifle skill, uses assault rifle range'. As I have not found any errata for 5th printing I guess these divergences are special rules of German core rulebook.

**Actual behaviour**
For characters created with 'German exclusive content' also exotic skills are used for calculating dice pool.

**Proposal**
If 'German exclusive content' is chosen as sourcebook, skills for Parashield Dart weapons could use 'standard' skills for calculation dice pool for Parashield Dart Pistol and Parashield Dart Rifle.

**Comment by DelnarErsike** [comment]
Issue has already been remedied through a custom ruleset called "German Data Changes - Exotic Weapons Use Standard Skills". You can activate it through the Optional Rules tab within the options menu.
