### ISSUE TITLE
Improvement Bugs

### ISSUE THREAD

**Issue by rtngtom** [chummer5a/chummer5a#2987]
**Describe the bug**
Qi Focus for Improved Ability seems to apply the bonus twice, and re-applying Improvements does not correct this.
Exceptional Attribute reacts weirdly with Re-Apply Improvements, and not entirely consistently. It has told me I have an Exceptional Attribute in Automatics, Hacking, and Etiquette, all the while applying more phantom buffs to my Automatics from the Improved Ability Qi Focus.

**To Reproduce**
Create an Apdet, get a Qi Focus R2 for Improved Ability and Exceptional Attribute, repeatedly re-apply improvements until you reach the desired rating for your skill.

**Expected behavior**
Qi Foci correctly apply their bonus, and Exceptional Attribute doesn't generate phantom Bonuses.

**Character File**

[Kerrigan.zip](https://github.com/chummer5a/chummer5a/files/2373469/Kerrigan.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.33

**Additional context**
I'm quickly coming to the conclusion I shouldn't use Chummer, as I seem to be generating these bugs out of thin air.

**Comment by chummer5a** [comment]
I suspect the issue is that when we hook the selectpower improvement to select the power that we're improving it's incorrectly applying the improvements then ditching the power, which is how we wind up with orphaned power improvements. Shouldn't be difficult to fix, just need to do some digging through the stacks.

**Comment by chummer5a** [comment]
Seems to be an issue with how the BoostedSkill property's databindings interact with the power if you already have it. It's not a super great workaround, but if you remove the power, bind the qi focus FIRST so that it generates the power, you'll be able to upgrade properly.
