### ISSUE TITLE
That issue with it setting your magic to 11 is back.

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#300]
So, I just went to make a new character and this came up.

http://i.imgur.com/ek4hXDF.jpg

**Comment by joha4270** [comment]
I believe a related bug is either open or fixed by the other guy.

Until then you can open the .chum5 in notepad and search for 11, then manually edit the value.

**Comment by Verecoth** [comment]
I tried that, but every time I open one my ork adept character the issue returns. It's something ongoing.

**Comment by chummer5a** [comment]
Hrm, maybe the fix got unfixed. I'll take a look at it tonight.

**Comment by chummer5a** [comment]
Can you upload your character somewhere? I can't replicate the issue with any of my existing test characters.

**Comment by MandozerTheGreat** [comment]
Take a look
https://drive.google.com/file/d/0Bwu-ssbXNGYMajByWmpJNldIbGM/view?usp=sharing

**Comment by Verecoth** [comment]
Here my older sheet, an attempt at patching a bear shifter into Chummer: https://drive.google.com/file/d/0B7MDGEbiDFrkYTZ3TkRvM3VLSTQ/view?usp=sharing

And here is one I just made right now: https://drive.google.com/file/d/0B7MDGEbiDFrkUFZMLW5pNXoyZXM/view?usp=sharing

**Comment by chummer5a** [comment]
Should be resolved in 5.174.
