### ISSUE TITLE
Chummer crashs when increasing the amount of spare clips with pluged-in ammo

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3003]
**Describe the bug**
When increasing the amount of spare clips with ammo as plugin Chummer crashs (but only in career mode; in create mode it works fine).

**To Reproduce**

Please save and close any characters in Chummer before trying the following steps.

1. Create a new character (with 'Karma'-method)
2. Go to 'Weapons'-tab in 'Street Gear'-tab
3. 'Add Weapon' for example 'Walther Secura II'
4. Change to 'Gear'-tab
5. 'Add Gear' 'Spare Clip' for weapon you selected in 'Weapons'-tab
6. 'Add Plugin' to 'Spare Clip' with the amount of ammo this weapon can take
7. Change 'quantity' of 'Spare Clip' by select arrows right from gears

This works so far and even cost for spare clip(s) are calculated correct with the correct costs of selected amount of ammo.

8. Now mark character as created in 'Character Info'-tab ans save character
9. Go to 'Gear'-tab in 'Street Gear'-tab
10. Increase amount of 'Spare Clip' by clicking on green 'plus'-button

Chummer crashes for me. Curiously, decreasing the amount of spare clips does not lead to a crash in my tests.

**Expected behavior**
I expect the amount of spare clips to increase but instead Chummer frozes so I could only close it via windows task manager.

**Screenshots**
To step 7 (above)
![ammo-create](https://user-images.githubusercontent.com/43168497/45594274-36c75200-b998-11e8-9241-be222f7dfc49.png)

To step 10 (above)
![ammo-career](https://user-images.githubusercontent.com/43168497/45594277-4ba3e580-b998-11e8-8cd9-833ab3afed6b.png)

**Character File**
[None]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.37
 - .Net-Framework 4.7.2

**Additional context**
I would like to use these steps in career-mode for buying used / lost spare clips with ammo like this: increase the amount (which should spent the right amount of Nuyen) and then reduce it for the used amount (without getting any Nuyen back).

As Chummer does not crash when decreasing the amount, maybe it is because of the entry for spending Nuyen?

**Comment by chummer5a** [comment]
There's some legacy reasons behind this, but gear really isn't built to act as a container for ammo and such. You're better off using the spare clip entries for the weapon in career mode on the actual weapon tab to handle that for now.

**Comment by DelnarErsike** [comment]
I cannot replicate this issue in the current dev build. Could you verify that the issue still exists in Nightly v5.202.46 or later, and if it does, could you upload a savefile of a character for which the bug triggers?

**Comment by Ramesch** [comment]
Sorry for the late response.

I created a completely new character with Chummer 5.202.47 and it does not crash anymore when increasing quantity of spare clips in career mode ...
 
[Test.zip](https://github.com/chummer5a/chummer5a/files/2421272/Test.zip)

… but Karma spent for increasing number of spare clips is 39 (when looking in 'Karma and Nuyen'-tab). As shown in 'Gear'-tab it should be 41 Nuyen.

If it can not be fixed, I will not use it anymore (as chummer5a recommended).
