### ISSUE TITLE
Troll Reduction isn't even in Chummer5 and Metatype Reduction does not increase charisma cap on trolls or orcs

### ISSUE THREAD

**Issue by Kromgar** [chummer5a/chummer5a#301]
This definitely needs to be fixed...

also RAW you can combine Metatype Reduction and Troll Reduction but we'll see if ERRATA EVER ARRIVES

**Comment by chummer5a** [comment]
Troll reduction's working, Ork reduction needs code support to automatically add the quality.

**Comment by chummer5a** [comment]
Fixed in 5.172.
