### ISSUE TITLE
Starting Karma - Life Modules

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3012]
**Describe the bug**
Screen does not pay attention to Karma defaults in Options|Character and Printing

**To Reproduce**
1. Go to Options, tab Character and Printing
2. Change default Karma to <> 750
3. Save Options, Restart Application
4. Create new Character

**Expected behavior**
If I say 775 then set it to 775

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.202.38]

**Comment by chummer5a** [comment]
I believe this should be working in current builds?
