### ISSUE TITLE
Options|Character and Printing

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3013]
**Describe the bug**
Picklist is obscured

**To Reproduce**
Open the Options|Character and Printing. See screen shot

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.202.38]
![maximum avail](https://user-images.githubusercontent.com/5994568/45653790-d66f0800-ba9e-11e8-99b2-02258ece476c.jpg)

**Comment by DelnarErsike** [comment]
Issue should be fixed in the latest Nightly after frmOptions got a design pass where it now uses TableLayoutPanels.
