### ISSUE TITLE
Life Module SIN Conflict (probable duplicate)

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3014]
**Describe the bug**
Adding Gang Warfare to new character with UCAS sin.

**To Reproduce**
Create new character. Life module General UCAS. White Collar upbringing. Add Gang Warfare. Everything goes fine but causes conflict and then resets (THIS IS AWESOME don't get me wrong - but)

**Expected behavior**
Should be able to mess up my characters life story any way I want to: 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.202.38]

PLEASE NOTE: I added Nev'yn prior to adding the Life Modules do this may not be a good test of the Black Market Pipeline.
[Emme.zip](https://github.com/chummer5a/chummer5a/files/2390567/Emme.zip)

 

![gang warfare](https://user-images.githubusercontent.com/5994568/45655290-fa354c80-baa4-11e8-88ff-086c17e8f40d.jpg)

**Comment by chummer5a** [comment]
Known issue, Life Modules are a work in progress with limited functionality.

**Comment by SeanPGorman** [comment]
I know @OLStefan is working on them - just mentioning it in case its a new re-occurence

**Comment by OLStefan** [comment]
Closing it as a duplicate, is already listed in my checklist #2000
