### ISSUE TITLE
Dark Theme (and colour theme options) (Feature Request)

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#3015]
**Is your feature request related to a problem? Please describe.**
Peripherally. One of my players often has migraines, and is sensitive to bright screens. Dark themes are much more comfortable for them. Therefore having a darker theme would enable them to use Chummer when they generally can't do much else.

**Describe the solution you'd like**
Having a pull-down menu or radio checkboxes allowing switching between the current colour scheme and a dark colour scheme. Even better would be having a third colour scheme that is about halfway between the two. 

I'm not sure how complex it is to switch a few colour schemes around, but if there's a straight forward way to switch colours, users could setup their own colour schemes. By that I mean if it comes down to swapping a few hex colours in an xml file, I could get my player to setup a few colour schemes that work and then use those to populate the list of alternative colour schemes.

**Comment by Zitchas** [comment]
In consultation with the person who has the issue with how bright Chummer is, they recommend two colour schemes:

1) white text on very dark gray (white text on black for text input boxes)

2) very pale gray on dark gray (very pale gray on very dark gray for input boxes)

They would prefer the second, but mentioned that some people do better with the first.

**Comment by chummer5a** [comment]
Off the top of my head, Chummer mostly already uses SystemColors throughout, so themes should just work. Could be deprecated in current versions though. 

WinForms is kind of awful about theming; it shouldn't be *hard* to implement it per se, but it'd be time consuming as all hell to build and bind it to the existing UI.

**Comment by chummer5a** [comment]
Duplicates #1126
