### ISSUE TITLE
Carriage return and incomplete translation in German dialog to select bioware/cyberware

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3020]
**Describe the bug**
This belongs to tab to add/select bioware or cyberware:

1. Textfield for 'Markup:' is too short for German Translation 'Preisaufschlag:'. As this text could be right-justified, there would be enough space to avoid carriage return in German translation (see screenshot).
2. German translation for "Free!" is incomplete; it should be 'Kostenlos!' and not only 'Kost'. I don't know if text field is too short or German translation is accidently shortened.

**To Reproduce**
1. Select 'Deutsch' for German surface of Chummer
2. Go to 'Cyberware und Bioware'
3. Click on 'Cyberware hinzufügen' or 'Bioware hinzufügen' (both dialogs are affected)
4. See carriage return and incomplete text on the right side

**Expected behavior**
See above

**Screenshots**
![bioware](https://user-images.githubusercontent.com/43168497/45688855-c3b60b00-bb52-11e8-942b-a5a2718c578e.png)
![cyberware](https://user-images.githubusercontent.com/43168497/45688860-c6b0fb80-bb52-11e8-9a54-cd04560f09eb.png)

**Character File**
[None]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.39

**Additional context**
[None]

**Comment by DelnarErsike** [comment]
The carriage return is sort of unavoidable due to the way table layouts work, but the "Kostenlos!" checkbox should now be displayed properly within frmCyberware.
