### ISSUE TITLE
Missing variables for translations in options-dialog

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3026]
Text / Screenshots has been changed due to adjustments made in the meantime!

**Describe the bug**
See screenshots for missing translations. As I can not find variables to translate them, maybe they are just missing and should be added?

**To Reproduce**
1. Chose 'Deutsch' as language for Chummer
2. Go to 'Zubehör' -> 'Optionen'
4. See screenshots for single translations missing

**Expected behavior**
If there are variables to translate these texts, it would be nice to have them in German.

**Screenshots**
![option1](https://user-images.githubusercontent.com/43168497/45874507-5e059100-bd95-11e8-83d0-8b5fb2ab2111.png)
![options4](https://user-images.githubusercontent.com/43168497/45801701-ee1fd980-bcb4-11e8-9253-14ee8c20907e.png)

**Character File**
[None]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.42 + commited translations

**Additional context**
[None]

**Comment by holgerschlegel** [comment]
These strings (or at least most of it) should be part of the de-de.xml translation file. So you could simply launch Translator.exe and translate that strings by yourself.

In my past pull request for German translations I did not update those because I simply to not care if the options dialog is in English or not.

**Comment by holgerschlegel** [comment]
Looks like I overreacted a bit. I don't want to attack you (or anyone working on this project).

I commit all changes I do in the branch and delete that branch after the pull request has been merged.
And create a new branch for the next translations (usually with the same name).

**Comment by Ramesch** [comment]
Everything is fine. Since I have seen how far you regularly update German translations, I don't want to interfere with your contributions.

I think Chummer5a is very good to handle character and rules, but I know only rudimentary about html and css. In order to still help, I would like to contribute something to the translations. If I should offend against customs in this context or submit strange contributions, this happens from lack of knowledge. I hope to get this under control quickly.

**Comment by Ramesch** [comment]
As keys are in en_us.xml-language-file it seems that only missing use of variables is the reason for absence of translation. Opened another issue also because missing translations have changed. So this issue is closed.
