### ISSUE TITLE
Nodachi is not recognized as a sword

### ISSUE THREAD

**Issue by YossiTamari** [chummer5a/chummer5a#3035]
Nodachi does not get the Sword specialization bonus, it seems like it should.
(It does not have `<spec>Swords</spec>` in weapons.xml)

Version 5.202.0.

**Comment by sphassan** [comment]
Lazily looked through the weapons.xml and it seems multiple that ought to have specs don't. This is edging on house ruling though (as specs always do).

Forearm Snap-Blades - Cyber Implants
Pole Arm
Mortimer of London ‘Belgrave’ Sword Cane
Lapel Dagger
Hand Razors (fixed) (2050) - Cyber Implants
Hand Razors (retractable) (2050) - Cyber Implants
Spur (fixed) (2050) - Cyber Implants
Hand Razors (retractable) (2050) - Cyber Implants
Krime Bill
Krime Reaver Axe
Krime Reaver Pick
Krime Reaver Knob
Krime Shiv
Traditional Macuahuitl
Modern Macuahuitl
Fluid-Motion Mace

**Comment by cnschu** [comment]
fixed
