### ISSUE TITLE
Vashon Island: Sleeping Tiger got just Armor Rating 3 instead of 13

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#3037]
Vashon Island: Sleeping Tiger got just Armor Rating 3 instead of 13
![swe](https://user-images.githubusercontent.com/40381762/45923732-5dccd900-beee-11e8-825f-b37a235ba924.jpg)

**Comment by chummer5a** [comment]
Looks like the label is overlapping the value.

**Comment by DelnarErsike** [comment]
Issue should be fixed by the adoption of TableLayoutPanels to contain controls in that tab screen in the latest Nightly.
