### ISSUE TITLE
Spirits will not show.

### ISSUE THREAD

**Issue by ishmail** [chummer5a/chummer5a#3039]
**Describe the bug**
Clicking the add spirit button will not have a spirit option created below it.

**To Reproduce**
1. Go to the spells and spirits tab
2. Click on Add Spirit

**Expected behavior**
Hitting add spirit should show a spirit below it when clicking on it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.44.0

**Additional context**
If you click the add spirit button a few more times, it eventually hits the error that the number of bound spirits can't exceed your cha score as if it was creating them but not showing them.

**Comment by DelnarErsike** [comment]
Cannot reproduce in the current dev build (to become Nightly v5.202.46). Can you test it with the latest nightly build after v5.202.45 to see if the bug exists?

**Comment by ishmail** [comment]
Just checked it out. It does show up fully, but only if you maximize the window to full screen. If you keep it windowed, something looks to cover up most of the bottom portion. I included a capture to show what I mean. Overall now that I know what the problem is, I don't think it's a major issue as I can just maximize the window instead of keeping it in a smaller window.
![capture](https://user-images.githubusercontent.com/12929502/45997783-c5aa2d80-c06e-11e8-87a0-a5de93d2c077.PNG)

**Comment by chummer5a** [comment]
Should be working as expected in the latest build.
