### ISSUE TITLE
Clicking on Sound Suppressor of a Smartgun X leads to crash

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#3041]
![unbenannt](https://user-images.githubusercontent.com/40381762/45927782-b32dd800-bf38-11e8-9ee8-1a6a07028775.jpg)

**Comment by chummer5a** [comment]
Hrm, can you show me the file?

**Comment by Gugax** [comment]
-- 


Freundliche Grüße
Michael Straub

 
 

Gesendet: Sonntag, 23. September 2018 um 14:53 Uhr
Von: "Chummer 5 Is Alive" <notifications@github.com>
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: Gugax <michaelstraub@web.de>, Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Clicking on Sound Suppressor of a Smartgun X leads to crash (#3041)


Hrm, can you show me the file?

**Comment by chummer5a** [comment]
Email responses strip attachments I think, upload it via https://github.com/chummer5a/chummer5a/issues/3041. You can compress the .chum5 file into a zip and upload it.

**Comment by Gugax** [comment]
[Ghost nur Adept - Erschaffung.zip](https://github.com/chummer5a/chummer5a/files/2409727/Ghost.nur.Adept.-.Erschaffung.zip)
