### ISSUE TITLE
Cyberlimb (weapons) AGI ignored (STR works)

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#3043]
Any Cyberlimb should use it's own attributes for tests involving (only) them. When calculating the DV of spurs in a cyberlimb, Chummer correctly applies the STR of the limb. But it does not take the custom AGI into account, when calculating the attack-dice-pool of the spurs, but instead uses the (default) overall AGI of the whole character.

**To Reproduce**
1. New Character -> add cyberlimb (any)
2. add custom AGI, custom STR (just different from natural AGI/STR)
3. add spurs
4. press print to see the char-sheet
5. scroll to weapons "Spurs" and compare the POOL and damage

**Expected behavior**
For implanted weapons the dice pool should use the attributs of the limb instead of the ones of the character. It's implemented for STR, but should also consider AGI.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.202]

**Comment by cnschu** [comment]
Since melee combat is a whole Body affair, the AGI of the character should be used.
the AGI of a cyberlimb only appies to Actions taken only with that limb (like sleight of hands).

**Comment by ArchonMegalon** [comment]
Ok, so just for my understanding. how does that not apply to STR then too? STR and AGI customization cost exactly the same in capacity and Nyen.

The way it is implemented now favours STR by far over body for no apparent reason. By this argument (melee - even with an implanted cyberweapon -  is a whole body affair), the STR of the whole character should be used for the calculation of the damage value.

So either change it, so that both attributes are taken either from the character, or from the limb. Either way - Chummer has a bug here, because RAW does not distinguished between WHAT attribute is customized.

**Comment by ArchonMegalon** [comment]
I checked, what HeroLab does in this case.
Herolab applies the AGI (and STR) correctly. The even apply it to the general unarmed combat skill.

![cyberlimb attributes](https://user-images.githubusercontent.com/11421547/46241306-febc0800-c3b6-11e8-9150-1e84ca1c54f8.JPG)

**Comment by cnschu** [comment]
ok, so herolab is wrong

**Comment by chummer5a** [comment]
The core issue here is that Chummer doesn't know what limbs a given weapon will use, so we just default to the whole-body average. Feeding that information into the CalculatedDamage and GetDicePool methods would enable more accurate behaviour. We're not currently using a proper paperdoll system or anything to model limbs, but it can be proxied without a massive amount of effort.
