### ISSUE TITLE
No Smartgun Wireless dice bonus?

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#3044]
Got a Smartgun X + Goggles with Smartgun + an activated Comlink but don't get the +1d bonus. Is that normal or did I something wrong?
[Ghost Adept - Karriere 1.zip](https://github.com/chummer5a/chummer5a/files/2410953/Ghost.Adept.-.Karriere.1.zip)

**Comment by chummer5a** [comment]
Wireless bonuses aren't currently implemented.
