### ISSUE TITLE
Cyber-Snob unusable for RAI

### ISSUE THREAD

**Issue by ordeiberon** [chummer5a/chummer5a#3047]
**Describe the bug**
Cyber-Snob seems written to intend that a character won't take anything lower than betaware, but it seems to be operating within chummer that ONLY betaware is acceptable to take the perk. I am building a character that currently has 2.5 points of Delta and Gammaware ware due to background story, but still can't take this perk, not even for free. I wanted to take it for character reasons as a character with Delta and gamma, it would make sense they not accept anything lower than beta.

**To Reproduce**
Choose character in career mode.
Install at least one point of Deltaware.
Attempt to add cyber-snob (must uncheck "show qualities I can take" as deltaware or gamma is not counting)
Get error stating betaware is required.

**Expected behavior**
I would expect this perk could taken at anytime character has more than 1 point of betaware OR higher, especially if taken for free (no karma bonus) for character reasons.
I realize this is probably working with rules as written, but I think that is just poor wording on the perk's part.

![cyber-snob raw](https://user-images.githubusercontent.com/43561432/45991735-3ee85700-c054-11e8-949b-d03a1f4ec224.PNG)

**Screenshots**
![cyber-snob fail 1](https://user-images.githubusercontent.com/43561432/45991618-bc5f9780-c053-11e8-80c1-2df7c9e2a697.PNG)

![cyber-snob fail 2 implants](https://user-images.githubusercontent.com/43561432/45991635-cbdee080-c053-11e8-8385-75da73cec4a4.PNG)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.40

**Additional context**
No other context, but I do want to say great work otherwise. I love this program!

**Comment by ordeiberon** [comment]
Why was this closed? No comments or reasons?

**Comment by chummer5a** [comment]
chummer5a closed this in 2a1792b 35 minutes ago

It's fixed, will be in the next nightly build.

**Comment by ordeiberon** [comment]
Ah, fantastic thanks!
