### ISSUE TITLE
Crash on adding Sourcebook PDF File

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3053]
**Describe the bug**
Chummer crashes as i add a PDF Sourcebook File, tested several different files
Chummer is set to German

**To Reproduce**
1. Go to Options / Global
2. Click on Schattenläufer in the Sourcebook Window
3. Click on PDF Location
4. Select PDF File
5. Chummer crashes on clicking "Open" 
6. Crash Reporter apears, stating that an error happend while collecting crash info
7. Windows Error Messagebox apears telling this:
```
---------------------------
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei CrashHandler.CrashDumper.CopyFiles() in C:\projects\chummer\CrashHandler\CrashDumper.cs:Zeile 283.

   bei CrashHandler.CrashDumper.CollectCrashDump(Object sender, DoWorkEventArgs e) in C:\projects\chummer\CrashHandler\CrashDumper.cs:Zeile 152.
---------------------------
OK   
---------------------------
```

Error ist there atleast in 5.202.47 and .48

**Expected behavior**
Be able to add a Sourcebook

**Screenshots**

**Character File**
No Char is loaded

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Version 1809

**Additional context**

**Comment by DelnarErsike** [comment]
Fixed in commit e028451ab6572fb7619cd269a434052d3e223b01.
