### ISSUE TITLE
Wrong book reference in metamagic.xml file?

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#3055]
The data file 'metamagic.xml' contains the following entries with book reference 'FA' (Forbidden Arcana).
	0ab2d588-34f5-4204-aee2-b944e5db411a, Essence Expansion
	2bd5228e-6698-4905-aecb-45fa5653456c, Enhanced Mist Form
At least in the German books, I did not found those in 'FA' but in 'DTR' (Dark Terrors).
And the page numbers in the data file matches those of the meta magic section in the DTR book.

Either this is an error in the Chummer5a data files or I simply overlooked the corresponding entries in the German FA book ('Verbotene Künste').
Could someone with the English books please check this.

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/c08bcd0437912ccd18804afcae9e748919533236
