### ISSUE TITLE
Aspected mage group skill

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3056]
**Describe the bug**
As is, chummer makes an aspected mage prio D choose a group skill at 0. This makes it impossible to raise those skills with ordinary skill points. 

**To Reproduce**
1. Create aspected mage prio D
2. Try to put skill points into magic skills (of the allowed group). 

3. See error

**Expected behavior**
Since they get no free group skill at prio D, they should not have it at 0 either. Just only be able to buy the skills in that group.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.201.29

**Thanks**
As always, thanks for a really great program.

**Comment by chummer5a** [comment]
Can't reproduce it; are the points greyed out for that skill group or skill?

**Comment by DelnarErsike** [comment]
I'm guessing that your MAG is 0 due to Essence loss or something similar, at which point the program disables all MAG-linked skills.

**Comment by drakir75** [comment]
Might have been. Closing.
