### ISSUE TITLE
Program Crashes on Startup

### ISSUE THREAD

**Issue by niccudrat** [chummer5a/chummer5a#3060]
### Environment
Crash ID: 441a6b5a-aad3-4bcd-9ab2-0a8f43ce68ff
Chummer Version: 5.202.49
Environment: Windows 8.1
Runtime: 4.0.30319.42000

### Expected behaviour
(open software)

### Actual behaviour
(crash always)

### Steps to reproduce the behaviour
(Restarted computer, it started happening when i tried to update the software and it now will not work )

**Comment by chummer5a** [comment]
Does it work if you download a fresh copy of the application? We've had some anecdotal reports that the manual updater can cause crashes.

**Comment by chummer5a** [comment]
You should be getting a crash report file on your desktop when it crashes, could you paste the contents here?
