### ISSUE TITLE
Menu display bug

### ISSUE THREAD

**Issue by ai-tsurugi** [chummer5a/chummer5a#3065]
![snapcrab_no-0094](https://user-images.githubusercontent.com/43719743/46255691-0a085400-c4db-11e8-9f34-a8acc5477cfe.jpg)

**Describe the bug**
This is the menu that comes out first when you create a character.
I can not operate because I can not select a menu.
キャラクター作成時、最初に出てくるメニューがこの状況です。
メニューを選ぶことが出来なくて操作することが出来ません。

**Desktop (please complete the following information):**
 - OS: [jp. Windows 10]
 - Version [ 5.202.52]

**Comment by chummer5a** [comment]
There's a small chance this might be working properly in .54, could you please test with the latest build? Do you also see this behaviour if you use the English language file?

**Comment by ai-tsurugi** [comment]
This is the test result.

English ver, Japanese ver, both have the same bug
![snapcrab_no-0097](https://user-images.githubusercontent.com/43719743/46348962-affac080-c68b-11e8-9f88-7f24cda5bc57.jpg)
![snapcrab_no-0098](https://user-images.githubusercontent.com/43719743/46348970-b4bf7480-c68b-11e8-9b6c-846d3ece7f05.jpg)
