### ISSUE TITLE
Knowledge Skill: Autocomplete changes cursor

### ISSUE THREAD

**Issue by handcraftedsource** [chummer5a/chummer5a#3067]
**Describe the bug**
The Autocomplete function for knowledge skills changes the cursor position. This will cause the input to be messed up. This seems to be a specific problem with the German version (could not reproduce it with the English version).

**To Reproduce**
1. Open Chummer5 with the German localization.
2. Switch to Skills
3. Add a new Knowledge skill
4. Type in "Militär"

**Expected behavior**
The text should be shown as typed in. The autocomplete should not replace entries automatically (like changing "Schieber" to "Fixer" without the posibillity to reverse that).

**Screenshots**
![knowledgeskillbug](https://user-images.githubusercontent.com/28440782/46303445-2627f600-c5ac-11e8-9899-b097e24a550a.gif)

**Character File**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit (German)
 - Version: 5.202.0

**Additional context**
-

**Comment by handcraftedsource** [comment]
If you are interested I would be willing to take a look at the bug and fix it.

**Comment by chummer5a** [comment]
Always happy to take pull requests, sure. I'm having trouble replicating the behaviour you're seeing anyway.

**Comment by ReallyDarkMatter** [comment]
I also see that behaviour, you type Militär, the Dropdown Menu opens and the Cursor jumps to the front of the entry and then you continue typing all text is put in front.
