### ISSUE TITLE
Overly long note on contact in relationships tab can cause issues with Desktop Window Manager in Windows 7 (at least)

### ISSUE THREAD

**Issue by Penguinizer** [chummer5a/chummer5a#3068]
What happened: I was working on a character sheet with quite a lengthy note for one of their contacts. This led to an issue where when mousing over the button for the note (which'd usually display the note in a small window) it instead led to Desktop Window Manager restarting due to error 0x88980406.

Information about my system: Windows 7 64 bit (latest patches installed), i5-3570k, 16GB ram, GTX 1060 6GB, Nvidia driver version 385.69.

The description was 340 words (2000 characters) long or so. I can't link the file itself, however moving the note into the character concept text box solved the issue.
 
EDIT: After having someone test on Windows 10, it appears it might be an issue specific to 7 or something more specific to my setup. 

The bug is not very severe as it only seems to happen with very long notes and removing the comment stops the issue. It is more of a curiosity that this is happening.

**Comment by chummer5a** [comment]
Can't replicate in a win 7 test VM; possibly 7's EOS anyway.
