### ISSUE TITLE
Bug with Made Man/Debug Logging causes chummer5a to lag like fuck

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#307]
There's a blank drop down menu when you select it in chargen. Clicking cancel or ok will give the "please post the chummerlog.txt file to github" message. So here goes.

Speaking of which, using debug logging lags the fuck out of my client 
https://drive.google.com/file/d/0Bwu-ssbXNGYMbGhGTWhXcXY0T1U/view?usp=sharing

**Comment by joha4270** [comment]
Debug logging making chummer lag? You sure it actually moves? :P Rest assured, log will be magnitudes faster next release. 

The actual bug you are experiencing is chummer asking you to select one of your group contacts, if you don't have any of those it displays the behavior you mentioned. 

Not terribly usefull as it seems made man have broken in one of the later builds, i will make sure to get some better handling of this bug in 172

**Comment by chummer5a** [comment]
Fixed in 5.172.
