### ISSUE TITLE
Incorrect Reference Page

### ISSUE THREAD

**Issue by chrisrhayward** [chummer5a/chummer5a#3073]
**Describe the bug**
The reference page for the Battle Hardened quality from Street Lethal is incorrect.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new character
2. Open the Positive Qualities menu
3. Select Battle Hardened
4. Click on the page reference to open the PDF
5. Read through referenced page to find that Battle Hardened is not listed
6. Navigate to page 181/182 of Street Lethal to find the description of the Battle Hardened quality.

**Expected behavior**
For the reference page to be correct, and for the link to navigate to that page upon clicking.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by OLStefan** [comment]
In the latest Nightly the Reference is already to page 181 where the quality is in the book.
