### ISSUE TITLE
Feature Request - Spoiler Blackout or Redaction

### ISSUE THREAD

**Issue by ordeiberon** [chummer5a/chummer5a#3074]
I love the printable character and notes features, but it occurred to me while all is open to the GM, I would love a way to share the PDF with fellow players but without giving away things their characters may not know.

For example if I take traits like Blank Slate, a hid-able meta-genetic mutation, or a corporate sin, I would like to way to mark that as spoiler, "redacted", or  (INACCESSIBLE INFORMATION) when the PDF is printed, so other players can compare characters without giving away gameplay surprises.  

Either a checkbox next to items and perhaps a "-spoiler /spoiler" tag within the notes blocks.

**Comment by Zitchas** [comment]
Definitely useful. One of my players is a shifter, and the rest of the group doesn't know what she is yet. Although they're well aware that she's... different...
