### ISSUE TITLE
Feature Request: Option to ignore quality requirements

### ISSUE THREAD

**Issue by Quintilium** [chummer5a/chummer5a#3075]
Plain and simple I want to take a quality that is normally exclusive to technomancers, but on a mundane character. It would be nice if there was an option to ignore quality requirements like these.

**Comment by DelnarErsike** [comment]
This can be done by creating an amend file where you edit the quality in question, and then add it as part of a custom ruleset that you enable for a character. You can consult many of the custom rulesets that come with the program inside the `customdata` folder. I'm closing this issue for now, but feel free to re-open it if you find a feature that you cannot solve using a custom ruleset and the amend system.
