### ISSUE TITLE
Drop-down menu of "Overclocker" quality in gear menu is invisible

### ISSUE THREAD

**Issue by MrDave** [chummer5a/chummer5a#3080]
**Bug decription**
Drop-down menu of Matrix Attribute selection in gear menu (career mode at least) becomes invisible if you add a plugin to a cyberdeck. It restores to being visible if the character is reloaded

**To Reproduce**
1. Have "Overclocker" quality and a cyberdeck
2. Go to Street Gear
3. Right-click on the deck and add a plugin (for example "hardening"
4. Overclocker selection menu becomes invisible

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/958348/46440345-ba8c8700-c76b-11e8-9ea3-55765d78d8fb.png)

**Character File**
Just in case added [character file](https://github.com/chummer5a/chummer5a/files/2443928/Bug.Test.txt) for convenient testing (works on old and characters though) 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202 and 5.202.55

**Comment by MrDave** [comment]
Found another way to reproduce the bug:

- Open character with an "Overclocker" quality and a cyberdeck
- Select the deck
- Select some other gear without Matrix attributes (ammo, binders etc)
- Select cyberdeck again. "Overclocker" drop-down is invisible

**Comment by DelnarErsike** [comment]
Made some tweaks that should show up in the Nightly branch starting with v5.202.72. Could you see if the issue is still present with/after that Nightly version?

**Comment by MrDave** [comment]
Unfortunately, the issue is still present. Tested on a previous character and on a new one

![image](https://user-images.githubusercontent.com/958348/47259222-2a5e7980-d4af-11e8-9b6e-23e7f5f5ce91.png)
Note: the "Attack:" to the right of the "Overclocker:" is not a selected option but a copy of UI from Matrix  attributes from below
