### ISSUE TITLE
Menu display bug

### ISSUE THREAD

**Issue by ai-tsurugi** [chummer5a/chummer5a#3081]
Thank you for fixing the last problem.

If you proceed with work, we have similar problems in this place.

![snapcrab_no-0102](https://user-images.githubusercontent.com/43719743/46449418-e4bf6280-c7c6-11e8-9095-89b807cadf00.jpg)
![snapcrab_no-0103](https://user-images.githubusercontent.com/43719743/46449424-f30d7e80-c7c6-11e8-9253-cdf6151f0905.jpg)
![snapcrab_no-0104](https://user-images.githubusercontent.com/43719743/46449436-091b3f00-c7c7-11e8-9417-d57321ca394e.jpg)
![snapcrab_no-0105](https://user-images.githubusercontent.com/43719743/46449456-1c2e0f00-c7c7-11e8-8bd6-0ac4254b1984.jpg)
![snapcrab_no-0106](https://user-images.githubusercontent.com/43719743/46449465-25b77700-c7c7-11e8-973c-978254d50d68.jpg)
![snapcrab_no-0107](https://user-images.githubusercontent.com/43719743/46449475-2ea84880-c7c7-11e8-8533-0497f8677e41.jpg)

OS: [jp. Windows 10]
Version [ 5.202.56]

**Comment by chummer5a** [comment]
Unable to replicate in current builds
