### ISSUE TITLE
Perceptive Postive Quality

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3084]
**Describe the bug**
Perceptivwe is 5 Karma for +1 and 10 Karma for +2

**To Reproduce**
Only 1 Perceptive Quality

**Expected behavior**
Should be 2

Source RF 148

**Comment by chummer5a** [comment]
You should be able to increase the rating of the quality.

**Comment by SeanPGorman** [comment]
Yes - I missed the option
