### ISSUE TITLE
Cannot Upgrade Agents after Chargen or add Leibesekretar

### ISSUE THREAD

**Issue by ordeiberon** [chummer5a/chummer5a#3090]
**Describe the bug**
Not sure if this is a bug, a rule I am missing, or a feature request.

I have created several characters and NPCs with various skills in programming or matrix interactions. So for story purposes several of them own the Nixdorf Sekretar w/leibesekretar commlink, and storywise can improve the programming of the installed agent. Now if I add the device at Chargen I can edit the Agent level (changing the availability) to match their programming skill or public relations requirements. However, if added after chargen, I can't change any of the agents. Now, this would not be that much of an issue as you can add extra agents, but you can't add the leibesekrater software to any of them, not even the Nixdorf. I tried replacing the agent with a higher grade, but that just adds a new one, and still can't add the leibesekretar software to it.

**To Reproduce**
Mark character as created.
Add Nixdorf w/Leibesekretar commlink
attempt to change agent grade.

**Expected Behavior**
Have function to upgrade an agent after chargen, or replace one with a new grade, or add the function to add leibesekretar software to any agent (Or at least any agent on a Nixdorf w/leibersekretar commlink).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.202.55

**Comment by chummer5a** [comment]
Strictly speaking there's no RAW that you can upgrade agents, and as the liebesekretar agent is built-in it arguably doesn't occupy a program slot anyway.

**Comment by ordeiberon** [comment]
> Strictly speaking there's no RAW that you can upgrade agents, and as the liebesekretar agent is built-in it arguably doesn't occupy a program slot anyway.

Hmm that does seem to be correct, at least in 5e. Could have sworn I did that function a lot in 3e, guess no rules yet on it in 5e.

However RAW do indicate you can procure a higher rated agent with just an increase in availability and cost. So perhaps a new agent should be able to be installed and include the Liebesekretar (Or maybe just love life management as other corps would call it something else) as a built-in option, (along with the increased cost)? 

So it would seem RAI that you could opt for a higher grade agent at time of purchase (After Chargen) since it changes the availability anyway (Just need to add increased cost and love life management options), correct?

**Comment by ordeiberon** [comment]
Elsewhere it is mentioned that equipment can upgraded by build & repair extended tests with the appropriate facilities (software in this case).
