### ISSUE TITLE
Request: Display multiple stats per cyberlimb

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3094]
**Is your feature request related to a problem? Please describe.**
It's common to have different cyberlimbs with different attributes. But Chummer5 doesn't cope with the different stats well. It's cumbersome to have to check the different cyberlimbs attributes during play.

For example, if I have base AGI/STR at 5, one cyberarm with 3 AGI and 8 STR, another cyberarm with 8 AGI and 3 STR, Chummer5 will simply display the base and average AGI and STR at 5 (5) across the board.

**Describe the solution you'd like**
Where appropriate, Chummer5 should display the multiple cyberlimb attributes, so user can choose the appropriate one to use. This should apply to all affected stats, including skills, weapon damage, etc.

For example:

With base AGI 4, one cyberlimb with AGI 8, the display should be:

AGI 4 (5/8)

This indicates the base 4, average 5, maximum 8.

Other attribute associated stats, like skill pools and STR-based weapon damage, should also show multiple values.

**Describe alternatives you've considered**
This would be the simplest way to display multiple values. But more elaborate displays (indicating which limb, etc.) would be better. But that'd probably require significant interface tweaking.

**Comment by ArchonMegalon** [comment]
Since we have the mess with modular limbs as well I would argue, implementing it this way will get confusing for users not knowing about this change as long as we don't show an actually schematic body with the location and the values of the different attributes.

This seems like a quick fix (which is still a reasonable way to at least show it).
