### ISSUE TITLE
Aspected Magician Free Spells

### ISSUE THREAD

**Issue by rtngtom** [chummer5a/chummer5a#3095]
**Describe the bug**
Aspected Magicians who take either Sorcery or Enchanting do not get their Free Spells & Rituals/Alchemical Preps in Priority/S10 as outlined on Pg 69 of the Core Rulebook

**To Reproduce**
Create new Character, take a priority rating for Aspected Magician, select Enchanting or Sorcery.

**Expected behavior**
Aspected Mages get Magic rating * 2 Free Spells & Rituals/Alchemical Preps

**Desktop (please complete the following information):**
Windows 10
5.202.59

**Additional context**
Similar to a previous issue reported by me: #2030

**Comment by chummer5a** [comment]
Away from books at the moment, but IIRC Page 69 is telling you the maximum
number of spells you can have at creation. Free spells come from your
priority choices.

**Comment by rtngtom** [comment]
You are right on this count. It's just another case of catalyst wording, then.
