### ISSUE TITLE
Life Modules aren't granting knowledge skills

### ISSUE THREAD

**Issue by darkon-turas** [chummer5a/chummer5a#3096]
After selecting my life modules (UCAS SINless and Arcology Living in my case), no skills are placed in the knowledge skills section, forcing me to pay for the skill levels that should be included in the modules.

Version 5.202.0 on Windows 10 build 1809 x64.

**Comment by chummer5a** [comment]
Because of the wide variety of skill choices available to you with life module skill choices, they currently just provide you with extra free skill points to spend. Linked to #2000.
