### ISSUE TITLE
Nuyen amounts in French have space currency separator

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3102]
**Describe the bug**
Using French, character sheets show Nuyen amounts with a space as the thousands separator.
When the character is saved as XML the amounts also have a space.

**To Reproduce**
1. Open a character
2. Click on 'Print'
3. Switch language to French

**Expected behavior**
When character sheets are shown in French the currency separator is a period, the same as German and Portuguese.

**Screenshots**
English Nuyen from xml.
![expense en](https://user-images.githubusercontent.com/17562417/46641713-c1831300-cb38-11e8-9927-441601c183b4.png)
German
![expense de](https://user-images.githubusercontent.com/17562417/46641722-cd6ed500-cb38-11e8-9572-f2a231b93dfb.png)

French
![expense fr](https://user-images.githubusercontent.com/17562417/46641735-d790d380-cb38-11e8-9520-e6ee4e52168d.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.202.61 [and prior]

**Additional context**

**Comment by DelnarErsike** [comment]
Working as intended. Chummer5a uses international standard ISO 31-0 for determining decimal and other digit separators, and the SI French standard (fr-FR) uses spaces for thousands separators under that standard.
