### ISSUE TITLE
PDF linking on steroids

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#3107]
**Is your feature request related to a problem? Please describe.**
All the information about which PDF on what page holds the actual description in chummer is fantastic. I would guess that some - if not most - of the players using chummer do have the digital versions of the rules on their computer somewhere (ie a directory with all the ShadowRun-Rulebooks.pdf). Why not open the pdf and the correct page by chummer on a click on the Source-description.

**Describe the solution you'd like**
A setting storing the path to the actual pdf in the Chummer.config could enable the project to invoke the default pdf viewer. If acrobat reader is present, it could even jump right to the correct page.

**Additional context**
This is totally a thing, that should actually not be in the Chummer main branch and a perfect example, why a plug-in framework would be a nice thing to have. If the dll handling such things is present, Chummer gets this gimmick, otherwise it's just the Source/Page as string.

**Comment by OLStefan** [comment]
That is already in Chummer. In the options you can set the path to the PDFs and to your preferred PDF-Reader (must be set, Chummer wont just use the default) and then it works exactly like you wish it would, including opening the PDF at the right page.

If you have further questions about the options for that, fell free to join the Chummer Discord and ask there. Invite-Link: https://discord.gg/SDSX8p6

**Comment by ArchonMegalon** [comment]
Wow - that is awesome! I actually do feel a bit dumb now. Maybe a new
feature could be a dialog opening at startup with a "Did you know you can
.... xyz!", thing. :D

**Comment by OLStefan** [comment]
I don't know how much those tips would really help. In my experience they are ignored all the time or ignored one time and them immediately turned off.

**Comment by SeanPGorman** [comment]
What about the long put off manual? How can we add to that?

Also - what about a Project Management app? Something to tell new developers what people have been / are working on?

**Comment by Zitchas** [comment]
This definitely is a poorly known feature, but an awesome one.

**Comment by ArchonMegalon** [comment]
Maybe new users would "stumble" on this feature more by chance, if every Source-Text would not be of type System.Windows.Forms.Label, but ...Button. If no Sourcebook is configured, it could directly open the settings-dialog with the referenzed book selected and maybe change the background colour of the Selected Sourcebook-Groupbox.

That way any curious user would by chance click that button and find himself in the options to configure it.
