### ISSUE TITLE
BP?

### ISSUE THREAD

**Issue by Atlessa** [chummer5a/chummer5a#311]
Another relic from 4th edition: Chummer uses 'BP' where it should use 'Karma'.

**Comment by joha4270** [comment]
Where outside of settings files?

**Comment by Atlessa** [comment]
Creation mode: 
https://www.dropbox.com/s/iru0hw0db1s5xq2/BP.png?dl=0

**Comment by joha4270** [comment]
Problem with this issue is that it only shows up a few times. Unless you
can provide me with a consistent way to reproduce it, i simply won't be
able to fix it as i have no idea what is causing it.

2015-07-27 0:44 GMT+02:00 Atlessa <notifications@github.com>:

**Comment by Atlessa** [comment]
All right, here's how I can consistently reproduce this problem:

1. Hit the 'new character' button
2. Switch to 'sum-to-ten'
3. Select whatever you want for priorities, metatype etc.
4. Click ok.

->  Chummer will display BP in the places I screenshot earlier.


So... at least for me, it happens when I use STT to create any character. Which is always.
