### ISSUE TITLE
Skills cut off

### ISSUE THREAD

**Issue by Krofinn** [chummer5a/chummer5a#3112]
**Describe the bug**
Unable to read the names of skills in the skill list- it's cut off on the left side.

**To Reproduce**
1. Go to 'Any character'
2. Click on 'Skills' tab
3. ?
4. See error!

**Expected behavior**
I would think resizing the window would fix it, but it just makes the drop-down menu longer.

**Screenshots**
[https://imgur.com/a/gNJw0oN](url)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 5.202.63 (Tried live version as well, same issue)

**Comment by chummer5a** [comment]
Same issue as #1900. Might work properly if you resize the knowledge skills control?

**Comment by ReallyDarkMatter** [comment]
I experienced that error my self, it looked differnt on every System that i use depending on screen Resolution
What i don't get what you mean the drop-down menu gets longer?

**Comment by Krofinn** [comment]
The drop down menu for choosing specializations. (I believe that's what that does. I haven't experimented with it much yet.)
It works fine on my laptop, so it's not a huge issue for me.

**Comment by chummer5a** [comment]
This should have been resolved in commits prior to 5.210.
