### ISSUE TITLE
Enable Unit-Tests for Chummer Solution

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#3128]
**Unit Tests are not part of Chummer**
This comes down to personal preference, but I would argue that having Unit Tests could help on the long run to have stable releases. It also it not a major change to the current code base. 

**Add a MSTest project to the solution**
There is already a function in utils, that checks if the assembly is running in Visual Studio. Checking for MSTestPlatform and changing the functions, that call StartupPath should be a reasonable small change.

**Why now?**
Why not? ;) I'm used to using Unit-Tests and it does not interfere with the way Chummer was developed until now. But it adds a lot of potential functionality for Developers. For me, it would be the benefit of being able to test the REST Client I'm currently writing for the replacement of the Omae-backend.

I already made the necessary changes and could push them to my fork and/or ask for a request to merge them to master. Of course there would be also a lot of other code (the whole REST-Client and Docker-Server) in this fork. 

So would you like me to make a new fork with only the changes for the Unit-Tests or should I just push my whole local changes to (my) gitfork? Since I'm new to git: would it be possible to just take the Unit-Test-parts and merge them into master or is this bad practice and another fork only containing these changes is more comfortably?

**Comment by chummer5a** [comment]
Honestly I've been wanting to implement unit/component testing for ages, but it's a daunting prospect. 

As far as merging in single components of your fork, the easiest would probably be to make a new branch locally via `git merge --no-ff --no-commit` on top of a new fork of my base. Should work, I don't faff about with git that much.

**Comment by ArchonMegalon** [comment]
#3129
