### ISSUE TITLE
Multiprogram Operating System - remove subitem requirement

### ISSUE THREAD

**Issue by markfvn** [chummer5a/chummer5a#3138]
**Is your feature request related to a problem? Please describe.**
The Multiprogram Operating System (MOS) item can only be purchased as a subitem of a cyberdeck but not a commlink (which it says it can work with in Kill Code).

**Describe the solution you'd like**
Remove the requirement that the MOS has to be a subitem of a cyberdeck to allow it to be its own item.  This would also allow for it to be connected to different commlinks/cyberdecks without confusion.

**Comment by chummer5a** [comment]
Works as expected in current nightlies.
