### ISSUE TITLE
Problem adding Fake SIN

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3139]
**Describe the bug**
After adding a fake SIN the box is presented to supply a name. The text box is unreadable.

**To Reproduce**
1. Go to 'Street Gear' tab
2. Click on 'Add Gear'
3. Scroll down to 'Fake SIN' and select

**Expected behavior**
Be able to see the text box.

**Screenshots**
![selected fake sin](https://user-images.githubusercontent.com/17562417/47273994-ce096180-d563-11e8-9b58-8d98640258cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - 5.202.73

**Comment by Lochabar** [comment]
Having same problem renaming a Location. So it looks like a problem with a common panel.

**Comment by chummer5a** [comment]
Yeah, should be fixed in the next nightly.
