### ISSUE TITLE
Raptor Feet not working

### ISSUE THREAD

**Issue by Trathos** [chummer5a/chummer5a#314]
When I try adding Raptor feet to a character it gives the following error

https://drive.google.com/file/d/0Byt6ryDDoqz_ZW95M1hqYWwyRDQ/view?usp=sharing

I believe it has something to do with Chummer trying to create a natural weapon and not being able to.

**Comment by chummer5a** [comment]
Yup, there's no weapon entry for the raptor feet to add. It will be fixed
in the next version, which is scheduled for sometime this weekend.

**Comment by chummer5a** [comment]
Fixed in 5.172.
