### ISSUE TITLE
PdfSharp dependent assembly redirect to dll-version, that does not exist

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#3140]
**Describe the bug**
There is a bindingRedirect in app.config for PdfSharp to a Version 1.50.4619.0 that is not referenced. Since someone specifically inserted it there I'm wondering, why is that? Because of that, I get a ReflectionTypeLoadException when trying to load this dll with the MEF framework to see if it contains exports. 

**To Reproduce**
Well, just look at app.config and on the AssemblyVersion of the pdfsharp.dll

**Expected behavior**
Just either don't make a redirect, redirect to 1.32.3057.0 or include the acutall 1.50.4619.0-dll into the project.

**Additional context**
Trying to implement MEF and of course I could specifically exclude this dll, but it seems like that would just cure the symptom, not the cause.

**Comment by chummer5a** [comment]
Odd, unused reference I believe. Stripped it out.
