### ISSUE TITLE
Gear: genuine SIN and licenses

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3141]
Please add a "SIN" gear.

Not all Shadowrunners are SINless. Runners with the SINner quality should have a genuine SIN. But unlike the Fake SIN gear, you cannot attach licenses and credsticks to a quality. As such, please add genuine SIN as a gear option.

Real SINs and licenses should have price of 0 and no rating. These are naturally gears that would only be used with GM permission.

**Comment by chummer5a** [comment]
Can't buy fake licenses for a legitimate SIN, no rules exist for purchasing legitimate licenses.

**Comment by Zitchas** [comment]
Could this be in the houserule or optional rules section? We rule that legal ones have a lower availability (but more hassles and possibly more time consuming to get)

**Comment by Lochabar** [comment]
I've been playing with this. I've used a custom gear file, and looked into using an optional rules definition. It is promising, I just need to figure out the exact XML definitions needed.

**Comment by Zolfax** [comment]
We use the house rule "use a custom item to add a legal SIN, price 0".
All additional licenses are also custom items with different prices.
(e.g. my character has a legal driving license assigned to his legal SIN)

**Comment by Lochabar** [comment]
Does the Custom Data Dictionary "Legal SIN and Licenses" provide the functionality you wanted?
If so can this issue be closed?
