### ISSUE TITLE
Can't add locations/armor bundles below Street Gear tab

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#3142]
**Describe the bug**
When I want to add a new location or a new armor bundle on the sub tabs of the Street Gear tab the dialog is not well sized. The Textbox isn't accessible and not completely viewable.

**To Reproduce**
1. Go to 'Tab Street Gear'
2. Click on 'Tab "Gear" or "Clothing And Armor" Or "Weapons"'
3. Click on button "Add location" or "Add Armor Bundle", depending on the previously selected tab.
4. See error on opened Dialog (See screenshots)

**Expected behavior**
The sown dialog should show a fully visible and completely accessible Textbox

**Screenshots**
![image](https://user-images.githubusercontent.com/42451897/47316640-eb176080-d647-11e8-98b7-98c827998261.png)
![image](https://user-images.githubusercontent.com/42451897/47316679-fd919a00-d647-11e8-8cc8-30729c4aa730.png)

![image](https://user-images.githubusercontent.com/42451897/47316718-0edaa680-d648-11e8-8650-d69c6eee32fa.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10 Pro X64
 - Version 5.202.74

**Additional context**

**Comment by chummer5a** [comment]
Identical to #3139 

Issue with the table layout panel reverting its size incorrectly.
