### ISSUE TITLE
Prototype Transhuman upgrade

### ISSUE THREAD

**Issue by Trebloc1213** [chummer5a/chummer5a#3147]
When selecting the Positive Quality "Prototype Transhuman", the PC gets 1 free Essence to spend in Bioware.  It would be nice if this had a hard cap.  Currently if I select Prototype Transhuman, and the add in Orthoskin (Used) Rating 4, this uses 1.25 Essence.  Applying Prototype Transhuman to the Orthoskin using the checkbox in teh Cyberware and bioware tab will reduce the Essence lost by the entire 1.25, instead of just reducing it to 0.25.

**Comment by chummer5a** [comment]
RAW, it allows you to pick up to 1 Essence worth of bioware. RAW on upgrading ware is that you remove the old ware (if any) and install the new ware on top and you can't stack different ratings of ware, so you couldn't start with rating 2 orthoskin and later add rating 1. If you go over that amount you'll be unable to move the character into career mode.

**Comment by Trebloc1213** [comment]
Yes, you get 1 Essence free for bioware.  However, if I purchase bioware that costs 1.25 essence and apply Prototype Transhuman, the entire 1.25 is refunded, not 1.0.  RAW does not indicate that the essence has to be spent on a single piece of bioware, or multiple pieces.  Just 1 free essence.
________________________________

**Comment by ArchonMegalon** [comment]
It also does not say, you can upgrade or basically do anything with that bioware after you "got" it at character creation. I actually think Chummer does this right for RAW.

You got that ware grown into you, but if you cut it out, it's gone.

**Comment by Trebloc1213** [comment]
Ok
________________________________

**Comment by cfresquet** [comment]
Seems like there is still a bug, though, if it is letting you get 1.25 essence worth of orthoskin for 0 essence cost.

**Comment by Trebloc1213** [comment]
I did not try to go to career mode, so am unsure if it would be caught
________________________________
