### ISSUE TITLE
Magical metasapients cannot have no magical tradition

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3148]
**Describe the bug**
It seems that all characters with a MAG attribute get a Spells and Spirits tab, and are required to have a Magical Tradition.

This should not be the case for magical metasapients like pixies and nagas. They always have the MAG attribute, even though they can still be mundane and have MAG 0.

**Expected behavior**
Mundane characters should not have the Spells/Spirits tab and should not be required to have a Magical Tradition.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 5.202

**Additional context**
This is related to, but not the same as, these reports:
https://github.com/chummer5a/chummer5a/issues/2951
https://github.com/chummer5a/chummer5a/issues/2537

IMO it's a good time to get rid of the Magical Tradition requirement for adepts as well.

**Comment by DelnarErsike** [comment]
The issue with adepts is that there are certain rules that any Magic-enabled character can interact with but that also rely on a character's tradition. The ones I remember off the top of my head are focus designs (namely, the fact that focus designs are tied to tradition), aspected background count, reagent types, rituals, and ally spirits.

The issue of needing a tradition for characters without access to magic beyond magical critter powers (or without access to even those) is a genuine bug though, I'll get to fixing it.
