### ISSUE TITLE
Enchanting Skill group is missing. And Alchemy is missing from Skill tree

### ISSUE THREAD

**Issue by 69Randomacts69** [chummer5a/chummer5a#3150]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by 69Randomacts69** [comment]
Hopefully you can see the picture.

**Comment by chummer5a** [comment]
You should be able to just drag the images into the comment box. 

Does this affect all characters, or just one? What build method?

**Comment by 69Randomacts69** [comment]
All characters new and old

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chummer5a** [comment]
Options > Optional Rules > Custom Data.

**Comment by DelnarErsike** [comment]
If the characters you're checking are all Mystic Adepts, then it's also possible that you've got RunnerHub Rules enabled, and you can disable it in the same fashion. Enchanting was stealthily removed for Mystic Adepts in Forbidden Arcana, and RunnerHub decided to abide by that change and their house rules make it so that Mystic Adepts don't enable the Enchanting skill group or any skill in it.

**Comment by 69Randomacts69** [comment]
Nothing is checked on that screen. I will try to find a way to take snippets and post them later today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chummer5a** [comment]
Is this still an issue for you?

**Comment by 69Randomacts69** [comment]
Yes, enchantment skill group isn't available

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chummer5a** [comment]
Can you upload a character file that's affected by it?
