### ISSUE TITLE
Limit modifier not loading

### ISSUE THREAD

**Issue by stuntfarmboy** [chummer5a/chummer5a#3154]
**Describe the bug**
Limits modifiers are not load, but are saved (confirmed by looking in the file that they were in)

**To Reproduce**
1. Add something with a LM (e.g. : chameleon skin, armante suit, etc.)
2. Save and quit
3. Re-open
4. See empty list on LM

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version e.g. 5.202.0

**Comment by chummer5a** [comment]
I believe this should be loading correctly in current nightly builds.
