### ISSUE TITLE
1 of 4 Charakter crash after upgrade to 5.202.0

### ISSUE THREAD

**Issue by Noraser** [chummer5a/chummer5a#3155]
**Describe the bug**
I have updated Chummer from 5.201.0  to 5.202.0
After update i can open 3 of my chatakters without problem.
If I try to open my Main Charakter, I see the page start, but than chummer crash.
[chummer_crash_131851170306935228.txt](https://github.com/chummer5a/chummer5a/files/2521749/chummer_crash_131851170306935228.txt)

Crash report didn't show any Data inside (except the general note)

Tested Charakter at 5.201 at other Computer not jet updated -> works 

**To Reproduce**
Open charakter " Din"

**Screenshots**
![chummer crash with din](https://user-images.githubusercontent.com/25962078/47604088-fc1ff300-d9f4-11e8-83c7-28ec84ec9c44.jpg)

**Character File**
[Din.zip](https://github.com/chummer5a/chummer5a/files/2521753/Din.zip)

**Desktop (please complete the following information):**
 -  Windows 10 -lates update

Would like to know, what to change on charakter, that it's open again
thanks
Noraser

**Comment by chummer5a** [comment]
Probably the adept issue, should be working as expected in current nightly
builds.

**Comment by Noraser** [comment]
thanks, used nigthly .78 and it works again!
can be closed
