### ISSUE TITLE
A placeholdier, perhaps?

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#316]
So, I've been having a few problems regarding the fact that there are things in the rules which aren't implemented in Chummer, and I was wondering if it was possible to have a custom quality and/or custom cyberware/bioware which we can use to fill in for the stuff that hasn't been implemented yet. Otherwise we're left trying to find placeholder qualities/ware which often has effects on the sheet that we don't want.

Is this something that can be done eventually?

**Comment by joha4270** [comment]
See #211

For info on how to do this, the easiest is to open up a datafile and see what it contains (AND CHANGE THE ID FIELD) while formal (but outdated) documentation can be found [here](http://www.chummergen.com/chummer/wiki/Data-File-Overview-sr5.ashx)
