### ISSUE TITLE
Request for correction of Japanese translation file

### ISSUE THREAD

**Issue by ai-tsurugi** [chummer5a/chummer5a#3162]
I translate Japanese into old Japanese ones.
With a fairly old file,
It seems that there are some original texts of English and things of the fourth edition.
I do not know how to fix the English part, so I want you to update to the latest version data.
Who can do it?

[japanese_language.zip](https://github.com/chummer5a/chummer5a/files/2529336/japanese_language.zip)

**Comment by DelnarErsike** [comment]
I've committed your files, but in the future, you should use pull requests from your own branch of chummer5a.

You should be able to create your own branch of Chummer5a under your own GitHub profile by going to the chummer5a repository and clicking the "Fork" button at the top right corner ([here](https://help.github.com/articles/fork-a-repo/) is the official GitHub help page on forking). Once you have your own branch created, you can create a local mirror of it on whatever computer you use and commit file changes to it. If any affected files are changed in the main repository, you can sync changes to your local branch fairly easily. Also, whenever you'd want to push your changes to the main branch, you'd be able to submit a Pull Request containing all of your changes, which would show up [here](https://github.com/chummer5a/chummer5a/pulls) and will let us merge your changes in a more structured fashion (e.g. you'll show up as a Contributor in the relevant lists, and others can comment on your changes before they're merged).

**Comment by ai-tsurugi** [comment]
Thank you.
I tried it as pointed out,
Is this how you use it?

**Comment by DelnarErsike** [comment]
Yes, you now have your own branch set up. Commit your changes to that branch (GitHub has [a really nice desktop program](https://desktop.github.com/) if you don't know what to use), and you should also have the opportunity to merge any changes to the main branch into your own should we make any.

Once you think you have a set of commits that you want merged into the main branch, [submit a pull request](https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/). After it is merged, your commits should show up alongside others' commits.
