### ISSUE TITLE
Concealability of collapsible weapons

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3163]
**Describe the bug**
Chummer lists Cougar Collapsible Spear, Collapsible Scythe, and Victorinox Collapsible Hatchet all as Concealability +4. This may be true in their extended form. But it's fairly obvious that people would only attempt to conceal them in collapsed form. If Chummer can list only 1 Concealability value, it should default to the collapsed Concealability rather than extended Concealability.

Per book, their collapsed Concealabilities are respectively:
- Cougar Collapsible Spear: -2 (as knife)
- Collapsible Scythe: -4
- Victorinox Collapsible Hatchet: -4

Alternatively, perhaps a better option: Auto-add both collapsed and extended forms as distinct weapons, similar to other weapons with multiple uses. This can be useful since some of these weapons also have additional different stats when collapsed/extended.

**Desktop (please complete the following information):**
 - Version 5.202

**Comment by chummer5a** [comment]
Duplicated by #3320
