### ISSUE TITLE
Make zipped chum5-save-files readable 

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#3169]
**chum5 files are plain xml files at the moment**
The size of chum5 files is not important at the moment and the xml format is sufficient. But compressing xml files normally wields great compression rates. There is no reason I can think of, why the shouldn't be compressed.

**Add the ability to read compressed files**
In a first step I would suggest to check, if a chum5 file is zip-compressed and decompress it before actually loading the file. I would - for better backwards compatibility - NOT actually compress them in the default "save" routine. That would make the transition to zipped save-files over two releases pretty transparent for users.

**Context**
It's all about the Chummerfiles repository in the cloud. When saving a lot of chum5 files in the cloud, the filesize actually starts to matter. Of course I could zip them and decompress them on the fly, but having the ability to just give the client a "DownloadUrl" that points to an actual loadable (although compressed) chum5-file seems convenient. Not only for us developers implementing the client-side, but also for simply sharing the files over links.

Is there a reason chum5 files are not compressed that I'm missing atm?

**Comment by chummer5a** [comment]
No reason for it, historically. Chummer tends to be rather you-ain't-gonna-need-it. No particular reason we couldn't make a chum5z file extension that Chummer can self-extract or iterate over when loading though.

**Comment by ArchonMegalon** [comment]
This can be closed - will implement it with the SINners-Plugin.
