### ISSUE TITLE
Drag & Drop of weapons to locations not working

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#3172]
**Describe the bug**
I'm not able to assign weapons to other locations. When left-clicking on a weapon the cursor doesn't change to 'drag mode' and assignment of weapon to the new location doesn't work.

**To Reproduce**
1. Go to 'Street Gear tab in openend Character'
2. Click on 'Subtab Weapons'
3. Select a Weapon in one location and try to move it to another location by using Drag&Drop.

**Expected behavior**
Drag&Drop of selected Weapon would work and I should be able to assign a wepon to other locations

**Screenshots**
none

**Character File**
[Hippie.zip](https://github.com/chummer5a/chummer5a/files/2545037/Hippie.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version e.g. 5.202.84

**Additional context**

**Comment by chummer5a** [comment]
Should work through right-click. IIRC, left-click dragging is intended to be used to reorder things on the current level, while right-click dragging is for moving it onto another node.

**Comment by DatenNirwana** [comment]
Neither left-, nor right-click Drag&Drop is working for Weapons. Tried it with versions 5.202.85 and 5.203.0.
