### ISSUE TITLE
Negative Karma prevents character creation

### ISSUE THREAD

**Issue by Pandasaurusrex123** [chummer5a/chummer5a#3173]
Negative quality SINer is not netting with positive karma qualities and prevents character creation.

Spent 26 karma on positive qualites; took SINer at -5 karma; chummer says I spent too much karma at creation and won't finalize character sheet.

**Comment by DelnarErsike** [comment]
I don't understand the issue. Under Standard character creation rules, you are limited to a maximum of 25 karma's worth of positive qualities and -25 karma's worth of negative qualities. If you're following Standard character creation rules, taking 26 karma's worth of positive qualities would indeed violate Rules as Written, regardless of whether or not you take some negative qualities to balance things out.

**Comment by Pandasaurusrex123** [comment]
Yea you're right; I completely misunderstood how that works.
