### ISSUE TITLE
Can't refill an ammo stack from gears inventory without facing a crash

### ISSUE THREAD

**Issue by Zeidra-Senester** [chummer5a/chummer5a#3174]
### Expected behaviour
Add ammos of the already selected type, when adding them to the existing stack.

### Actual behaviour
Prompt window asks for the weapon type (that is already defined for the stack), but no option is available. When validating, the software crashes because the weapon type was missing.

### Steps to reproduce the behaviour
In career mode, I bought normal ammos for my Ares Predator V, and reloaded. Subsequently, the ammos stack in the inventory was empty (0 ammos, not disappeared). I use the green (+) to buy more of them. It prompted the ammo window, with only the same type available. I clicked on it and validated. It then prompted the weapon type window (already defined to be Heavy Gun for the stack), but the droplist was oddly empty. I had no choice but to validate, and doing so made it crash, as Ï didn't chose anything from the empty droplist.

**Comment by chummer5a** [comment]
Can't reproduce in current builds. Is this still an issue for you? What's the crash report say?
