### ISSUE TITLE
Crash when Clicking through Erika Elite Commlink Features

### ISSUE THREAD

**Issue by W4nT4n** [chummer5a/chummer5a#3178]
### Environment
Crash ID: 1a99f4cf-11e9-4e7a-bd12-b5f6467fd012
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
Selected a commlink (Erika Elite) and started clicking through the built in features, chummer crashed then

**Comment by Tatsu-Kishi** [comment]
Just got that crash too. It happens when clicking on either "Camera, Micro" or "Earbuds". Changing their rating to "1" in the XML fixes the issue.
