### ISSUE TITLE
Life Modules: spread ranks among several skills.

### ISSUE THREAD

**Issue by angelforest** [chummer5a/chummer5a#318]
1st case:

> Academic Knowledge: [Ancient Language/Philosophy/Religion] +13 (spread out among at least three subjects, minimum three ranks per subject)

Okay, [this way](http://pastebin.com/PMCJZdGC) we can ensure that user have 3 ranks in 3 skills, but still can't check if he has 3 ranks in 4th skill, if he willing to take it instead of rising previous ones.
Also, it just looks ugly.

2nd case:

> Academic Knowledge: [Ancient Language/Philosophy/Religion] +13 (divide among all three, with no one skill having more than 7 ranks)

or even weirder variant in celebrity module:

> +6 to buy any skills you think appropriate to your field of celebrity (no more than 3 ranks in any
> individual skill; ranks in Con and Escape Artist may be purchased with these points)

In that case there is no minimum number of skills and ranks in them, just maximum. And we can't enforce maximum with only data entry.

Related stuff:

> Charisma +1, and +1 to two attributes of your choice (must be two separate attributes, other than Charisma)

Need somehow check that there two different attributes or at least put note about that.

**Comment by joha4270** [comment]
>Academic Knowledge: [Ancient Language/Philosophy/Religion] +13 (spread out among at least three subjects, minimum three ranks per subject)

This can be enforced by providing only a <name> Ancient Language</name> instead of <option>

That will force that skill to be that specific powers, he can still hack his way around, but people would have to look for it. Don't belive it is worth doing something more advanced at present time as the time to implement it would be large.

>Academic Knowledge: [Ancient Language/Philosophy/Religion] +13 (divide among all three, with no one skill having more than 7 ranks)   

Afraid we can't enforce that. Not sure (need a look) how hard it would be to add a specific max, but that is probably being per skill, not from this specific one. (Is there a path where you can get it the skill from other places or is that without worry?)

>+6 to buy any skills you think appropriate to your field of celebrity (no more than 3 ranks in any
individual skill; ranks in Con and Escape Artist may be purchased with these points)

Afraid this one can't be implemented without a few thousand lines of new code, first iteration is probably going to look for honest players, or a check when marking a character as created. (A tag about a knoskill being from life module might also solve this with @2.

>Charisma +1, and +1 to two attributes of your choice (must be two separate attributes, other than Charisma)

This should at least not be nightmarish difficult to make. Going to look at creating an <option> and <whateverNameIAapropriateWhereItRemovesStuffAsYouSelectThemNTimes>

**Comment by brennanhawkwood** [comment]
Just wanted to point out that Real Life > Postgraduate Studies is another place that has this issue as well:  "+10 to skills from your education module (no more than 4 added to any one skill)"

**Comment by Soulsheath** [comment]
Would it be possible to hard-code various selections?  Similar to the way University was done i.e. 
`<module>
			<id>1156fac7-e8d2-4599-94c3-64b8464037d7</id>
			<stage>Further Education</stage>
			<category>LifeModule</category>
			<name>Ivy League University</name>
			<karma>80</karma>
			<bonus>
				<attributelevel>
					<name>CHA</name>
				</attributelevel>
				...more happiness here
			</bonus>
			<versions>
				<version>
					<id>7581d130-4069-41c6-b225-97849752aa7e</id>
					<name>Architecture</name>
					<bonus>
						<skilllevel>
							<name>First Aid</name>
						</skilllevel>
						...lots more happiness
					</bonus>
				</version>
                                ......
                         </versions>`



And use something like:


 
`<module>
			<id>ID# Here</id>
			<stage>Teen Years</stage>
			<category>LifeModule</category>
			<name>Magical Education (Magician)</name>
			<karma>50</karma>
			<bonus>
				<attributelevel>
					<name>WIL</name>
				</attributelevel>
                                <attributelevel>
					<name>CHA</name>
				</attributelevel>
				...more happiness here
			</bonus>
			<versions>
				<version>
					<id>ID# Here</id>
					<name>Conjuring and Sorcery</name>
					<bonus>
						<skillgrouplevel>
							<name>Conjuring</name>
							<val>1</val>
						</skillgrouplevel>
                                                <skillgrouplevel>
							<name>Sorcery</name>
							<val>1</val>
						</skillgrouplevel>
						...lots more happiness
					</bonus>
				</version>
				<version>
					<id>ID# Here</id>
					<name>Conjuring and Enchanting</name>
					<bonus>
						<skillgrouplevel>
							<name>Conjuring</name>
							<val>1</val>
						</skillgrouplevel>
                                                <skillgrouplevel>
							<name>Enchanting</name>
							<val>1</val>
						</skillgrouplevel>
						...lots more happiness
					</bonus>
				</version>
				<version>
					<id>ID# Here</id>
					<name>Enchanting and Sorcery</name>
					<bonus>
						<skillgrouplevel>
							<name>Enchanting</name>
							<val>1</val>
						</skillgrouplevel>
                                                <skillgrouplevel>
							<name>Sorcery</name>
							<val>1</val>
						</skillgrouplevel>
						...lots more happiness
					</bonus>
				</version>
                                 ...more selections
                         </versions>`

**Comment by OLStefan** [comment]
Part of #2000.
