### ISSUE TITLE
Unable to add custom Skill Specializations

### ISSUE THREAD

**Issue by Gidoran** [chummer5a/chummer5a#3182]
**Describe the bug**
In the latest Stable version of Chummer, we're unable to add custom active skill specializations.

**To Reproduce**
1. Go to Skills Tab
2. Add 1 rank in any skill
3. Attempt to manually type in a value for the Skill Specialization
4. Observe that no text is entered
5. Attempt to add in an option from the dropdown selector
6. Observe that the value is entered as selected

**Expected behavior**
Typing in the field should allow for manual specializations to be entered. Not everybody wants to have to update their data files to get custom skill specs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.203.0

**Comment by emomicrowave** [comment]
I've been trying to pinpoint the bug, but I can't really.

I've noticed something funny though, when you have added only Karma points to a skill, two things happen.

1.  The `_skill.BuyWithKarma` doesn't seem to be updated, possibly the cause of 2.
2. The `cboTextChanged` event is called **twice**, once with the input string and once with an empty string, which leads me to believe something sets the Specialization to Empty.
3. The "Buy with Karma" checkbox cannot be toggled manually
