### ISSUE TITLE
No Text Entry Allowed For Active Skill Specializations 

### ISSUE THREAD

**Issue by Rephaim** [chummer5a/chummer5a#3183]
**Describe the bug**
Hi folks,
It appears that in 5.203.0 I am no longer able to enter custom specializations for Active Skills.  Is this intentional?  Is there an optional rule to re-enable this capability?

**To Reproduce**
1. Go to 'Skills tab'
2. Add a skill point to any active skill
3. Attempt to manually enter a specialization (not from the dropdown options)
4. Note the inability to enter text.

**Expected behavior**
Attempting to type into the active skill specialization field does not accept input - only dropdown options are available.

**Screenshots**
N/A

**Character File**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 5.203.00]

**Additional context**
This seems like a bug, but if this is an intentional feature, any information regarding a potential workaround or optional toggle to re-enable custom specializations would be appreciated.
Thank you!

**Comment by chummer5a** [comment]
Duplicates #3182
