### ISSUE TITLE
Option to Disable Tool Tips

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#3184]
**Problem Definition:**
I run Chummer on my Mac, using wine.
It works mostly fine, but every time a tool tip tries to load, Chummer crashes.
I've become quite good at not hovering and saving, but I still get 3 or 4 crashes per character I create.

**Possible Solution**
Disabling tool tips would be a decent fix, as it would prevent Chummer from crashing.

**Even better solution**
Fix tool tips so that they work under Wine / Mac.
This seems like it could well be "out of scope of the support contract" for you, and I'm not sure how to help you understand what is causing the issue either!

For what it's worth, tool tips under Chummer for 4th edition work fine - it's only when moving to Chummer5 that there is an issue.
It's also worth noting that only the Skill Groups tool tips used to crash Chummer (up until 5.198 or so), but now, they are all generating a crash. 

Thanks!

**Comment by Teksura** [comment]
I have this same issue, and it's been going on for several versions now. I'd be quite happy with just the option to disable the tooltips, as that would resolve the Mac/Wine crashes as we could simply turn them off.

**Comment by chummer5a** [comment]
That's interesting, tooltips use a custom class, I'd expect it to work better in Wine. Still, doable.

**Comment by oxford-fumble** [comment]
Ah - just realised I never said thanks for solving the issue.
So, thanks a bunch for solving the issue! It's made my experience of Chummer a 1000 times better!
