### ISSUE TITLE
SINner quality automatically consider taxes when adding NuYen

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3185]
Current behavior of Chummer: When clicking "NuYen Gained" as your character gains money, the NuYen Change box comes up with it set to 100% by default in all instances.

Requested Behavior: Consideration is given to the SINner quality. For a National or Criminal SINner, it defaults to 85%. For a Corporate Limited SINner, it defaults to 80%. For a Corporate SINner, it defaults to 90%.

Reason for requested change: Minor quality of life change to streamline the paying of taxes for the negative quality anytime you gain NuYen.

**Comment by drakir75** [comment]
Would not want that as default, but as an option, sure. There are sources of money that shouldn't be taxed. I.E selling ware (upgrading or not). There are probably other examples.

**Comment by Teksura** [comment]
> Would not want that as default, but as an option, sure. There are sources of money that shouldn't be taxed. I.E selling ware (upgrading or not). There are probably other examples.

If you're selling ware through the Karma and Nuyen tab, you should know that it is easier to do so (and gives better results) through the Cyberware and Bioware tab itself. Just select the ware you want to sell, and use the dropdown on the delete button to select Sell Item.
![screen shot 2018-11-11 at 6 51 28 am](https://user-images.githubusercontent.com/1766631/48314435-52a53980-e57e-11e8-8098-ba28a1cd6504.png)

**Comment by Zitchas** [comment]
Something along the lines of a "apply tax" checkbox on the "add nuyen" dialogue box of the karma & nuyen tab would probably be the best way to have it. That gives people the convenience of choosing it, but doesn't have it cluttering up things that don't need it (like selling cyberware or guns or whatnot)

**Comment by Teksura** [comment]
Wow! I feel like I'm the only one who knows about this feature! 
![screen shot 2018-11-11 at 6 57 09 am](https://user-images.githubusercontent.com/1766631/48314482-07d7f180-e57f-11e8-875b-4270f5775e0e.png)
![screen shot 2018-11-11 at 7 03 33 am](https://user-images.githubusercontent.com/1766631/48314543-ecb9b180-e57f-11e8-82c0-019dedb633b9.png)


Does nobody else know you can sell things through these tabs? And have people just been trying to sell items through the Karma and NuYen tab? Really? And have people really been trying to sell their gear for 100% of it's value without adjusting that per core rules for selling gear? I mean, even if you didn't know about the Sell Gear option as you two have described you were unaware of, selling Weapons for example still requires turning around and adjusting the % anyway. 

It's kinda weird to describe changing this default behavior:

![screen shot 2018-11-11 at 7 01 11 am](https://user-images.githubusercontent.com/1766631/48314527-ae23f700-e57f-11e8-8964-8861d237e8c0.png)
To this when you have a (National) SIN 

![screen shot 2018-11-11 at 7 01 28 am](https://user-images.githubusercontent.com/1766631/48314532-be3bd680-e57f-11e8-9e1d-fa185629a613.png)

Clutter, in an instance of selling gear when you have to turn around and change it to this either way:

![screen shot 2018-11-11 at 7 02 54 am](https://user-images.githubusercontent.com/1766631/48314538-d3b10080-e57f-11e8-8a58-774f1a3b944d.png)

**Comment by chummer5a** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/11448441/80007163-3d6d6200-8509-11ea-882c-26338822652d.png)

**Comment by Teksura** [comment]
OO, nice. Although is the 18,000 number the result after taxes? It seems a little misleading to enter 20,000¥ where you should pay 2000¥ in taxes, and have the entry say you gained 18000¥ and then paid 2000¥ in taxes. 

Maybe it should list the full amount in the positive, and then charge for the taxes,
