### ISSUE TITLE
Vehicle Attribute Modification

### ISSUE THREAD

**Issue by magid23** [chummer5a/chummer5a#3186]
**Problem Definition:**
The current interface provides for the vehicle modifications introduced in Rigger 5 in the Building the Perfect Beast chapter, but not those discussed in the Automated Army chapter.

**Detailed Description:**
Building the Perfect Beast discusses specific modifications to various drone/vehicle systems (Powertrain, Protection, etc.).  Each system has a number of modification slots equal to the drone's body.

Automated Army discusses more general modifications to the drone overall.  The drone has a number of modification points equal to its body which can be subsequently spent on the mods discussed there.  The most salient of which are additional ways to augment drone base stats.  Notably, only handling, speed, acceleration, and sensors (specific functions, not the overall sensor array) can be improved with modification points.

Some of the modifications in the Automated Army chapter are a bit confusing and seem to overlap with those discussed later in Building the Perfect Beast.  You can add a drone arm both ways, for example, but the attribute modifications are specifically discussed in different terms.

**Desired Solution:**
I'd like to see a way to add modifications as discussed in this chapter.

**Comment by chummer5a** [comment]
Enable the drone rules in the options.

**Comment by magid23** [comment]
Ah, thank you very much!  You guys respond fast and make a cool product.
