### ISSUE TITLE
Quality: Mentor Spirit "Seducer" ADVANTAGES selection of Adept

### ISSUE THREAD

**Issue by ai-tsurugi** [chummer5a/chummer5a#3187]
Problem Definition:
In Adept you can not choose when choosing the bonus you can receive.
I noticed Japanese files when creating them.
誘惑者 = Seducer
Since the Japanese version still has only Coalule,
I do not think I can check the use of other magic supplements.

![snapcrab_no-0137](https://user-images.githubusercontent.com/43719743/48178860-48592480-e35f-11e8-9d53-50466d82fb4c.jpg)
![snapcrab_no-0140](https://user-images.githubusercontent.com/43719743/48179202-60ca3e80-e361-11e8-8765-0ad15b6f9602.jpg)

When choosing a skill, the confirmation button is not displayed.
It seems that you can not choose the skill of acting.

![snapcrab_no-0138](https://user-images.githubusercontent.com/43719743/48178885-64f55c80-e35f-11e8-9979-48b0f6cda0aa.jpg)
![snapcrab_no-0139](https://user-images.githubusercontent.com/43719743/48178888-6888e380-e35f-11e8-8505-fc9a072e6eaa.jpg)

**Desktop (please complete the following information):**
Environment
Chummer Version: 5.203.89
Environment: Windows 10

**Comment by chummer5a** [comment]
I can't reproduce this in current builds; is it still an issue?
