### ISSUE TITLE
Unable to increase Skill Groups during Career Mode

### ISSUE THREAD

**Issue by W1ld3b34st** [chummer5a/chummer5a#319]
Environmental Information:
Program Build: V171
Operating System: Windows 8.1 Pro (64 bit)

Reproduction Steps:
1) Create new character and finalize completion or open existing character.
2) Increase Skill Group. Skill group will raise. Skills within that group will not. For example, raising Firearms from 5 to 6 will increase the Skill Group, and deduct karma, but will not raise Automatics, Longarms and Pistols from 5 to 6.

**Comment by Althalusdlg** [comment]
Same in the Build 172, for existing characters. Don´t want to Build it new, just for testing.

**Comment by chummer5a** [comment]
Fixed in the next build.
