### ISSUE TITLE
Martial art not undone

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3196]
**Describe the bug**
Undoing a karma spent on a Martial Art does not remove the martial art.

**To Reproduce**
1. In career mode, learn a new martial art style.
2. In the Karma log, undo the martial art.
3. The Karma is refunded, but the martial art remains.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.203

**Comment by emomicrowave** [comment]
Managed to fix the issue, however the same problem is present when removing Technique expenses.
And the code, which handles removing expenses for Martial Art Techniques is marked as LEGACY, and I'm not sure about the reason.
