### ISSUE TITLE
PDF location does not show for some Sourcebooks

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3199]
**Describe the bug**
In the list of Sourcebooks in the Global Options screen the PDF location part of the window does not show for some sourcebooks, including Battle of Manhattan, Bloody Business, Hong Kong Sourcebook, and 2050.

**To Reproduce**
1. Go to 'Options'
2. Click on 'Global Options'
3. Click on 'Battle of Manhattan'

**Expected behavior**
Be able to see the PDF location for the sourcebook.

**Screenshots**
Top of Sourcebook Info
![list](https://user-images.githubusercontent.com/17562417/48319373-d4bf4d80-e5d2-11e8-8d4f-7fe116f79b8d.png)

Assassin's Primer shows the PDF location
![assassin](https://user-images.githubusercontent.com/17562417/48319378-e43e9680-e5d2-11e8-95b3-4d344b2d467d.png)

Battle of Manhattan does not
![battle](https://user-images.githubusercontent.com/17562417/48319385-f02a5880-e5d2-11e8-99cd-07e4de8eec93.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.203.94[and prior]

**Additional context**
I don't know if it is relevant, but these sourcebooks are all hidden by the SR Missions Optional Rules (that I have active). Is something hanging around from these rules that prevents the PDF section from being displayed?

**Comment by DelnarErsike** [comment]
Could you check if this is still an issue with the current Nightlies?

**Comment by Lochabar** [comment]
I went down the full list of books and the problem no longer presents.
But because Battle of Manhattan is no longer in the list of supported books, I can't check the exact original problem.
