### ISSUE TITLE
Improper behavior of essence hole filling

### ISSUE THREAD

**Issue by Sevasta** [chummer5a/chummer5a#3206]
**Describe the bug**
When filling out an essence hole completely and beginning to fill out essence itself, an 'essence antihole' is created and an 'essence hole' remains at the value of (Starting actual essence before fillnig hole) - (Amount of actual essence consumed after hole is completely used up)

**To Reproduce**
1. Create a situation wherein there is an essence hole of .05
2. buy a piece of ware that consumes .10 essence
3. observe ware list for 'antihole' and remaining 'hole' value

**Expected behavior**
When an essence hole is filled and essence cost still remains, the actual essence score should be reduced down to what it would be, and no 'essence hole' value should exist, nor should there be an 'essence antihole'.

**Comment by skuben** [comment]
I also am having improper behaviour of essence hole filling.  For me this is happening in version 5.203.98

**Comment by chummer5a** [comment]
Can't replicate it; can you show me a file?

**Comment by DecklandMulqueen** [comment]
I bought Nanoware Cyberware that does not cost any essence, such as neural amplifiers ... and i got an essence antihole for that ... i think, thats just not correct

**Comment by Teksura** [comment]
> Can't replicate it; can you show me a file?

Not sure if this is the same issue or not, but this is what I'm seeing on 5.203.0

[Tom Cruise.chum5.zip](https://github.com/chummer5a/chummer5a/files/2660772/Tom.Cruise.chum5.zip)


To reproduce: 
1: Delete Wired Reflexes. Now have correct Essence Hole of 2.
2: Buy Move-By-Wire system Rating 1. Essence Hole incorrectly remains, current essence is now -1.40

[Tom Cruise uh oh.chum5.zip](https://github.com/chummer5a/chummer5a/files/2660773/Tom.Cruise.uh.oh.chum5.zip)

This file represents what I am seeing after following the above steps on the first file.

**Comment by chummer5a** [comment]
This should be resolved in current builds.
