### ISSUE TITLE
can't make character because window is too small

### ISSUE THREAD

**Issue by Gartral** [chummer5a/chummer5a#3213]
**Describe the bug**
while making a char the OK or Continue button isn't drawn

**To Reproduce**
Click New Character 
try to make new Character
can't Continue.

**Expected behavior**
have ability to Continue past first step.

**Screenshots**
![selection_095](https://user-images.githubusercontent.com/649782/48585683-5e388d80-e8fb-11e8-9774-6f4ff1bd8420.png)

**Character File**
could not advance to this step

**Desktop (please complete the following information):**
Ubuntu Studio 18.04, Mono Framework 5.16.0.179 
Chummer 5.203.97

**Additional context**
this is likely a formatting bug in .NET's WinForms

**Comment by emomicrowave** [comment]
Reproduced on Arch with Mono 5.16.0

A quick google search showed me that WinForms are acting weird on Mono, and that porting an application to be compatiable with Mono on linux is an extremely tedious process, so I assume this cannot be fixed. Maybe someone more knowledgeable could chime in. 

In the meantime, I recommend using wine. It might be a bit of a hassle to get it to start in the first place, but after you manage, the program works fine and there are no formatting issues.

**Comment by chummer5a** [comment]
In theory you should be able to resize that window, which should make everything snap back into view properly.

**Comment by emomicrowave** [comment]
When I tested it the window was resize-able only downwards, and not sideways. So there was no way to make the button visible.

And there are other problems with WinForms. I was looking at the options menu and there were badly formated options, missing text from checkboxes. The options to add pdf path and offset were missing. And then the program chrashed. I don't think Chummer could run properly on mono without a huge amount of effort.
