### ISSUE TITLE
Improved Ability Skill Multiplying itself

### ISSUE THREAD

**Issue by Quintilium** [chummer5a/chummer5a#3220]
plain and simple my adept power improved ability skill is doubling itself for some reason

When I hover over the skill it reads

"Skill ranks + Charisma (In this case its con) + Cool Resolve + Improved ability (2) + Improved ability (2)"

I've tried remaking the character but that didnt work

**Comment by chummer5a** [comment]
There's an annoying bug with precedence that crops up due to qi foci; it's pretty much confined to Improved Ability, but there's not many cute ways around it at present. If you add the power via the qi focus then apply any point bonuses you intend to spend, it should behave properly.
