### ISSUE TITLE
Essence holes being ignored

### ISSUE THREAD

**Issue by Sevasta** [chummer5a/chummer5a#3226]
**Ware not reducing essence hole at all**
As of 5.203.98, when a character adds 'ware while having an essence hole, the essence hole is untouched and the character's essence itself is directly impacted.

**To Reproduce**
1. Take a career mode character
2. add 'ware, then remove it to creat an essence hole (or simply observe essence hole amount if it already exists)
3. Add new 'ware once an essence hole exists

**Expected behavior**
When an essence hole exists, and 'ware is added, the value of the essence hole should be reduced (or reduced first and then the difference applied to actual essence if the new ware exceeds the value of the essence hole)

**Comment by skuben** [comment]
Did you notice the essence hole getting bigger as well?  To me it seemed like the character paid for the 'ware twice, once out of his Essence dropping, and then again as the hole gets bigger.
