### ISSUE TITLE
Chummer crashes when clicking on Healing or Illusion Spells

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3227]
### Environment
Crash ID: d6982d95-3057-499c-8eb3-9f52e0867046
Chummer Version: 5.203.98
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
click on healing  or Illusion spell and see the description
(Enter text here)

### Actual behaviour
Chummer crashes when clicking on Healing or Illusion Spells

### Steps to reproduce the behaviour
Open Chummer
Open Char
Goto "Spells and Spirits"
Click on Diagnose -> Works fine
Click on Heal - Chummer crashes
DMP File is too big to upload 281MB

(Enter text here)

**Comment by chummer5a** [comment]
Can't replicate it, what's the chummerlog.txt crash say?

**Comment by ReallyDarkMatter** [comment]
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.Spell.SetSourceDetail(Control sourceControl) in C:\projects\chummer\Chummer\Backend\Uniques\Spell.cs:Zeile 962.
   bei Chummer.frmCareer.RefreshSelectedSpell() in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 15957.
   bei Chummer.frmCareer.treSpells_AfterSelect(Object sender, TreeViewEventArgs e) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 11344.
   bei System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   bei System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   bei System.Windows.Forms.TreeView.WmNotify(Message& m)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   bei System.Windows.Forms.Control.WmNotify(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   bei System.Windows.Forms.Control.DefWndProc(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, IntPtr lparam)
   bei System.Windows.Forms.TreeView.set_SelectedNode(TreeNode value)
   bei Chummer.frmCareer.TreeView_MouseDown(Object sender, MouseEventArgs e) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 170.
   bei System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.TreeView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:Zeile 113.
Crash id is b1497f76-7db1-4c9e-8a40-ba3d4e046990
Crash working directory is C:\Users\op1291\AppData\Local\Temp\chummer_crash_131871969447823064

**Comment by ReallyDarkMatter** [comment]
Just had the time to check with another char, that do not have a Problem.
Here is the char having the Problem.
[Moonlight MK.zip](https://github.com/chummer5a/chummer5a/files/2609027/Moonlight.MK.zip)

**Comment by ReallyDarkMatter** [comment]
I manually cleaned all spell from file with Notepad++
And relearned them, for now it works.

**Comment by ReallyDarkMatter** [comment]
The error is back

Upload the Dump here: https://1drv.ms/u/s!As6nocZk96Hgn_VmLOpt-Q6u4JiQcA
