### ISSUE TITLE
Nanotech Learning Stimulus doesn't work

### ISSUE THREAD

**Issue by Youneko17** [chummer5a/chummer5a#3229]
The nanotech Learning Stimulus should reduce karma cost to improve Knowledge or Language Skills, yet even if with it, the karma cost remains unchanged.

1. buy and nanohive and install a Rating 2 Learning Stimulus.
![0001](https://user-images.githubusercontent.com/31526630/48819039-ee0d8a00-ed88-11e8-9057-32052eb29d35.png)
2. Choose the Knowledge Skill "Fashion" to improve, which is at Rating 4.
![0002](https://user-images.githubusercontent.com/31526630/48819044-f49c0180-ed88-11e8-922e-2190cab39ee8.png)
3. It shows that it would cost 5 karma.
![0003](https://user-images.githubusercontent.com/31526630/48819107-2f9e3500-ed89-11e8-8003-bb87c3048fe6.png)
4. And it does cost 5 karma, instead of 3 (2 with wireless bonus).
![0004](https://user-images.githubusercontent.com/31526630/48819165-77bd5780-ed89-11e8-881d-a5d19b0d45aa.png)

I'm using the latest version, which is 203.103. My OS is windows 7 just in case, though I think this bug has nothing to do with my OS.

**Comment by chummer5a** [comment]
There's no bonus implemented for it. The minimum 2 karma condition is a bit awkward to parse, as other qualities like Jack of All Trades can interact with it in odd ways.
