### ISSUE TITLE
Extended Clip weapon accessory does not function correctly with Hammerli Gemini heavy pistol.

### ISSUE THREAD

**Issue by cuckooman** [chummer5a/chummer5a#3233]
**Describe the bug**
Instead of changing the clip size to 16x2, adding a Rating 2 Extended Clip to the Hammerli Gemini will change the clip size to 8x4.

**To Reproduce**
1. Go to Street Gear tab, then Weapons subtab
2. Buy a Hammerli Gemini
3. Look at the clip size. Should read 8x2.
4. Add a Rating 2 Extended Clip accessory.
5. The clip size now reads 8x4.

**Expected behavior**
The clip size should read 16x2.

**Character File**
[Shi.txt](https://github.com/chummer5a/chummer5a/files/2607671/Shi.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.203.103

**Additional context**
After further testing, the Rating 1 Extended Clip also has a similar effect, changing the clip size to 8x3.

**Comment by chummer5a** [comment]
Existing code is a workaround. Need to rebuild how ammo slots work to properly have the firing method reduce ammo from both slots at once, but it's functionally accurate.
