### ISSUE TITLE
Karma Costs for Resonant Discordance

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3237]
When i search this positive Quality, i find it, when i search for a Quality, that exactly costs 13 Karma - as it is intended.
If i want to choose it then, it charges me 26 Karma, wich is wrong.

**Comment by chummer5a** [comment]
Career mode?

**Comment by DecklandMulqueen** [comment]
Sir yes sir!

 

Thats a quality that works the same way as the magic master qualities (masteries) from forbidden arcana (FA page 30+) . They have prerequisites that hinder you taking them in create mode (with this one you have to have submerged at least one time …)

The costs fort he magic „master“ qualities (masteries as they are called“ from forbidden arcana are NOT doubled in create mode, as they can only be chosen in career mode. 

I think the two masteries out of BTB should work the same 😊

 

Thanks for answering that fast!

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Sonntag, 25. November 2018 11:31
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Karma Costs for Resonant Discordance (#3237)

 

Career mode?

**Comment by chummer5a** [comment]
Oh, right. I wasn't sure whether the discount thing was permanent to all mastery qualities so it's commented out for the moment.

**Comment by DecklandMulqueen** [comment]
😉

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Sonntag, 25. November 2018 11:43
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Karma Costs for Resonant Discordance (#3237)

 

Oh, right. I wasn't sure whether the discount thing was permanent to all mastery qualities so it's commented out for the moment.
