### ISSUE TITLE
Crashing upon clicking to open

### ISSUE THREAD

**Issue by DarkWolf546** [chummer5a/chummer5a#3239]
I'm getting this error message when opening Chummer5

![aae5c7167d7612f928503e54dd983d22](https://user-images.githubusercontent.com/45340346/48984144-246b4200-f0c6-11e8-840e-f93567105918.png)

**Comment by chummer5a** [comment]
Try deleting the files stored in C:\Users\Austin\AppData\Local\Original_Chummer_for_4th_\

Looks like a user.config file got mongled.

**Comment by DarkWolf546** [comment]
Ok i'll try that, not sure how that happened because I never had chummer for 4th, I just recently downloaded this app on my computer last week

**Comment by chummer5a** [comment]
I think we never converted the appdata location from the 4e version.
