### ISSUE TITLE
Legal SIN with 203.110

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3240]
I have the SINer (National) negative Quality but there is no tab to choose the SIN as describer in the patch notes

**Comment by Lochabar** [comment]
Select the Legal SIN just like a Fake Sin using the Gear tab. Then rt-click the SIN to add notes.

**Comment by DecklandMulqueen** [comment]
Then i have a fake SIN with notes ...

**Comment by chummer5a** [comment]
Have you enabled the Legal SIN and Licenses customdata file?

**Comment by DecklandMulqueen** [comment]
I found it – ist working! Perfect, THANK YOU

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 23:48
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Legal SIN with 203.110 (#3240)

 

Have you enabled the Legal SIN and Licenses customdata file?
