### ISSUE TITLE
Issue: - crashes when adding Ares corp scrip to credsticks

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3242]
### Environment
Crash ID: e2e588f0-b0ff-4a08-8b72-22a7a5633eab
Chummer Version: 5.203.110
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Trying to add Ares corp scrip to a silver credstick.

### Actual behaviour
The app crashes and cannot generate the report properly. I also cannot remove the standard credstick.

### Steps to reproduce the behaviour
[Rudolph Beckitt.zip](https://github.com/chummer5a/chummer5a/files/2617504/Rudolph.Beckitt.zip)

See if you can add let's say 8402 Ares scrip as a plugin to a silver credstick as well as remove the standard one.

**Comment by chummer5a** [comment]
Unable to replicate in current builds; can you confirm if this is still an issue?

**Comment by KeeperM** [comment]
Still an issue for me. No clue whatsoever.

**Comment by chummer5a** [comment]
Nuts; no crash report either?

**Comment by DelnarErsike** [comment]
Can you tell us if this is still happening in the latest nightly builds? If so, maybe there is a crash report or something you could upload as well to help us hone in on the problem.
