### ISSUE TITLE
Issue: - cannot move the character into Career Mode

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3243]
### Environment
Crash ID: 3cb4e22e-6321-4de7-95d1-e810cf781a91
Chummer Version: 5.203.110
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
I'm trying to get the guy from here: https://github.com/chummer5a/chummer5a/issues/3242 to Career Mode. I can't.

### Actual behaviour
The app crashes when I try.

### Steps to reproduce the behaviour
Trying to move the file into Career Mode crashes the entire app.
[Rudolph Beckitt.zip](https://github.com/chummer5a/chummer5a/files/2617508/Rudolph.Beckitt.zip)

**Comment by DelnarErsike** [comment]
When I opened up the savefile in Chummer, I see a large, negative karma amount that would prohibit the character from being exported into Career mode. Could you confirm that this is the case for the file on your end as well?

**Comment by KeeperM** [comment]
No, for me, there's nothing like that. I also built the fellow in NPC mode, so he should let me transfer to CM with a karmic debt.

**Comment by chummer5a** [comment]
Woof, this one's lingered for a while. Can it be closed?
