### ISSUE TITLE
Instinctive Hack quality is not "I can take"

### ISSUE THREAD

**Issue by MrDave** [chummer5a/chummer5a#3245]
**Describe the bug**
Quality "Instinctive Hack" from Better than Bad isn't shown if the "Show only Qualities I can take" box is checked, though it has no prerequisites

**To Reproduce**
1. Go to "Add Quality" menu
2. Search for "Instinctive Hack"
3. It's show only if the checkbox "Show only Qualities I can take" is unchecked

**Expected behavior**
As the quality has no prerequisites it should be available.

![image](https://user-images.githubusercontent.com/958348/49073319-37575100-f243-11e8-9c81-cd02948936b3.png)
![image](https://user-images.githubusercontent.com/958348/49073329-3e7e5f00-f243-11e8-96f0-eed054fb3a78.png)

It happens in career mode if that's relevant.

 - OS: Windows 10
 - Version 5.203.110

**Comment by chummer5a** [comment]
Resolved in latest commits.
