### ISSUE TITLE
In Skills, changing base attribute does nothing (career mode)

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3246]
**Describe the bug**
In Career mode, you can change the base attribute for skills. But doing this has no effects.

**To Reproduce**
1. Open file in Career mode.
2. Go to Skills tab.
3. Select any skill and change the associated attribute.
4. The dice pool is not affected.

**Expected behavior**
The dice pool should change to reflect the selected attribute.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 5.203

**Comment by chummer5a** [comment]
Something wrong with the databindings, possibly a mismatch with the dependency graph though everything looks right at first blush. Possibly stopped working as of https://github.com/chummer5a/chummer5a/commit/e460539fa487cadba1c3fb0503a36d4c2f23f5b9

**Comment by drakir75** [comment]
This is still not working fully. Changes are not saved and are not shown on printed sheet. I'm on 5.205.13.
