### ISSUE TITLE
Non-registered sprites count against limit

### ISSUE THREAD

**Issue by sulla76** [chummer5a/chummer5a#3247]
**Describe the bug**
Chummer is counting registered and non-registered sprites against the limit of registered sprites=Logic.

**To Reproduce**
1. Go to Technomancer character record, when registered sprites + non-registered sprites = LOG.
2. Click on 'Add Sprite'
3. See error.

**Expected behavior**
Chummer should allow registered sprites equal to your Logic score, then allow one additional non-registered sprite.
![logic](https://user-images.githubusercontent.com/36398166/49165468-e739c680-f2f6-11e8-85ea-62a4a6001ece.PNG)
![sprite limit error](https://user-images.githubusercontent.com/36398166/49165475-eacd4d80-f2f6-11e8-90b4-2a134b0c5833.PNG)

See attached screenshots.

**Desktop (please complete the following information):**
 - OS Windows 10
 - Version 1709
- Os Build 16299.755

**Additional context**
I have a non-registered sprite as a workaround to Chummer not having a place to designate a sprite as a sprite pet (Technoshaman only complex form, from Kill Code.)

**Comment by DecklandMulqueen** [comment]
Yeah, being able to pay Karma and "bind" a pet to your TM as you can bind a Spirit to a mage would be great :)
But not registering a sprite and paying the relevant amount of Karma via the Karma Editor works too!

**Comment by chummer5a** [comment]
Fixed in https://github.com/chummer5a/chummer5a/commit/cc67f54984eb34569a4cb891ac1441043f59e97d

**Comment by sulla76** [comment]
Deckland, you can make a sprite now, with new rules in Kill Code. The technoshaman resonance stream gives access to a complex form, Sprite Pet, which allows a tm to make a registered sprite a pet sprite.  

Chummer 5a, thanks!

**Comment by DecklandMulqueen** [comment]
Already saw it with the .114 update !!

 

THX

 

Von: sulla76 <notifications@github.com> 
Gesendet: Freitag, 30. November 2018 17:58
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Non-registered sprites count against limit (#3247)

 

Deckland, you can make a sprite now, with new rules in Kill Code. The technoshaman resonance stream gives access to a complex form, Sprite Pet, which allows a tm to make a registered sprite a pet sprite.

Chummer 5a, thanks!
