### ISSUE TITLE
Issue: - Chummer Crashing

### ISSUE THREAD

**Issue by kiomadria** [chummer5a/chummer5a#3251]
### Environment
Crash ID: 3ca6096a-9658-42db-9f85-e08b30d01039
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Open Gear for cyberware

### Actual behaviour
Chummer Crashed

### Steps to reproduce the behaviour
Right click cyberware, add gear

**Comment by chummer5a** [comment]
Unable to reproduce it; please provide more detail.
