### ISSUE TITLE
Magic Rating Missing For Shapeshifters In Karma Build With Split Magic Attribute For Mystic Adepts House Rule

### ISSUE THREAD

**Issue by ResonantGhost** [chummer5a/chummer5a#3253]
**Describe the bug**
When the "Mystic Adepts use second MAG attribute for Adept abilities instead of special PP rules" house rule is enabled and creating a shapeshifter in karma build, if you add the magician, adept, or aspected magician quality, no magic attribute is displayed. If you add the mystic adept quality, only the Adept Magic attribute displays. Confirmed error in karma build for standard and prime runner levels. Confirmed correct behavior with priority build.

**To Reproduce**
1. Go to Tools > Options.
2. Click on House Rules tab.
3. Enable 'Mystic Adepts use second MAG attribute for Adept abilities instead of special PP rules.'
4. Click "OK."
5. Click Yes to save changes and restart Chummer.
6. Go to File > New Character.
7. Change Build Method to Karma and click "OK."
8. Change Metatype to Shapeshifter and click "OK."
9. Click Add Quality.
10. Select Magician and click "OK."
11. Observe that there is no Magic attribute.

**Expected behavior**
Magic attribute is present with a starting value of 1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.203.0 and 5.203.116

**Additional context**
Confirmed error in karma build for standard and prime runner levels. Confirmed correct behavior with priority build. Confirmed that karma build works correctly for Metahumans.

**Comment by ResonantGhost** [comment]
**Workaround**
1. Start with a metahuman or change metatype to a normal metahuman (from the Special Menu).
2. Add awakened quality (if it was already added, delete and add it again).
3. From  the Special Menu, change the metatype to Shapeshifter.
(Caution: Workaround does not remove quality when switching to A.I.)

Confirmed issue also occurs with all metasapients. House rule option appears to only work for metahumans.

**Comment by chummer5a** [comment]
Pinning it down to metasapients helps a lot, I think I know what it'll be.
