### ISSUE TITLE
Missing Street Lethal "CorpSec Arsenal" Content

### ISSUE THREAD

**Issue by guildsbounty** [chummer5a/chummer5a#3254]
A few items from the Street Lethal book are missing...

Boats: 
Maersk Shipyards Wavecutter MPAC

Weapons
Red Samurai Katana
Saeder-Krupp/Onotari Arms Silent Claw Stiletto
Wuxing-Armtech PTL-02

Ammo
MCT/Winchester-Howe Hornet Direct-Fire Mini-grenade

**Comment by Ramesch** [comment]
If everything works fine, boat and weapons should be included in the next Chummer5a-nightly. I haven't figured out how to add the ammo yet, but I'll keep trying.
