### ISSUE TITLE
Issue: - Crash when adding weapons to drone arms

### ISSUE THREAD

**Issue by Reag** [chummer5a/chummer5a#3256]
### Environment
Crash ID: 4285aa18-4bde-4145-b7fa-231d9e002aee
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behavior
The addition of the weapon to the drone arm or an error message saying that this is not intended behavior.

### Actual Behavior
Hard Crash

### To Reproduce
1. Create a new character
2. Go to the Vehicles and Drones tab and add some Drone: Anthro item
2.a Use the Ares Duelist because its the best
3. Right click on the 'Drone Arm' item under the Ares Duelist and hover over 'Weapons'
4. Click 'Add Weapon'
5. Chummer5a hard crashes with the error:

System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.

[chummer_crash_131884030171385111.txt](https://github.com/chummer5a/chummer5a/files/2644082/chummer_crash_131884030171385111.txt)

Note: Also tested with the Drone Arm modification. This leads to the same behavior as described above.

Hope this helps!

**Comment by chummer5a** [comment]
Found the issue, but for what it's worth, you can't really use duelists like that. They don't have proper hands to carry stuff or anything, what with them being swords and all.
