### ISSUE TITLE
Pull request # 3248 final enough for acceptance?

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3261]
I have submitted various changes and additions to the data files as a pull request (https://github.com/chummer5a/chummer5a/pull/3248) in the last few days and they have not been adopted since.

Therefore some translations, adaptations and additions have accumulated.

Since Chummer5a is constantly being programmed and improvements are being made, I don't know if the submitted changes are not seen or not final enough for a migration to Cummer5a (maybe the tool or app used for programming is not able to display pull-requests?).

So I'll try to ask you this way.

**Comment by chummer5a** [comment]
Naw, I'm just lazy about approving pull requests.
