### ISSUE TITLE
Be able to add additional Powers to Spirits

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3262]
**Is your feature request related to a problem? Please describe.**
Not related to Problem.
When add a Spirit at the Spells and Spirits Tab it would be nice to set the additional power that a Spirits gets for every 3 full Point of Force(e.g. 1 Power at Forcelevel 3, 2 Powers at Level 6)

Now we have to track the additional Powers elsewhere, as it is not Always possible to build a Spirit as Critter upfront. 
And in a session it is total break in the flow of the Play, as it takes to Long.

**Describe the solution you'd like**
Be able to track the additional Powers of Spirits.

**Describe alternatives you've considered**

**Additional context**

**Comment by Teksura** [comment]
There are already not 1, but 2 different places where you are able to write that down. 
![screen shot 2018-12-08 at 11 45 06 pm](https://user-images.githubusercontent.com/1766631/49694682-57401c00-fb43-11e8-95d1-280d355456a0.png)

The first is a handy text box provided, if you want it to be more visible. 

If you don't like that for whatever reason (For example, you would like to give your spirit a name and put that in this box), there is also the handy notes box right next to the delete button, where you can also keep track of their optional powers.

**Comment by Teksura** [comment]
> Basically what like to have is a kind of mini char sheet for spirits.

If we're looking for a mini character sheet, maybe something that also outputs the stats of the spirits based on the force.

**Comment by Lochabar** [comment]
Have you looked at the Spirits and Sprites character sheet?
It shows the stats, skills, possible powers.

**Comment by ReallyDarkMatter** [comment]
I have looked at it, but it didn't show much more info. It was only Ini and even imcomplete.
No skills powers, attributes, dicepools.
Just Force and Services and a part of Ini

![image](https://user-images.githubusercontent.com/12108972/49895157-0c2e4d80-fe50-11e8-8456-cac06bd819c8.png)

**Comment by Lochabar** [comment]
This is what I see when I view sprites

![sprites](https://user-images.githubusercontent.com/17562417/49897190-0e29e980-fe1b-11e8-8824-b199b4b3a05c.png)

My default language is English, but I switched the Character Viewer to German and still see the Sprite details. I'm assuming your default language is German, this would suggest there is a difference in how the XML in the character file is formatted between English and German.

**Comment by ReallyDarkMatter** [comment]
Hmm strange, now i see it like you. i don't why. Maybe it was v. 5.203.126
The language doesn't matter, it Looks the same in german and english.
But it is only a view, you can not work with, still have to use notes for additional power between sessions.
You can not click and the pdf is opened. That save a lot of time, rather than thumbing through a book.
And no Damage track
![image](https://user-images.githubusercontent.com/12108972/49898492-7bf50600-fe59-11e8-871d-25dfe9980798.png)

![image](https://user-images.githubusercontent.com/12108972/49898528-916a3000-fe59-11e8-8b4f-f503bea3370c.png)

**Comment by chummer5a** [comment]
Addition of free spirit powers when created as a critter was completed in an earlier commit. I'm not going to add it to the base spirit control, as that's already a bit too cluttered for my tastes.

**Comment by ReallyDarkMatter** [comment]
As I stated earlier, it takes quiet same time to build a spirit as a new critter, and often the decision which spirit to summon is based on situation. A lot of factors are part of that decision.
If you think that the spells & spirit tab is already to cluttered, maybe it could be an idea to separate it in two tabs.
