### ISSUE TITLE
Display Stats, Skills and Powers for Spirit

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3263]
**Is your feature request related to a problem? Please describe.**
Right now only Force and Services are displayed for a summoned Spirit.
It would be nice to see the complete stat for a Spirit, like a little Charsheet.
Also the Skills and Powers that a Spirit has should be displayed.

**Describe the solution you'd like**
A mini Charsheet for a summoned Spirit, right now i have allways to consult the rulebooks.
All within build a Spirit as Critter upfront

**Describe alternatives you've considered**

**Additional context**

**Comment by Teksura** [comment]
You might find [this spreadsheet](https://docs.google.com/spreadsheets/d/1eFF47WKRbRMISo-BH5XZ0A0R4DE9BzjG7UV94XAJQyc/edit?usp=sharing) handy in the meantime.

**Comment by chummer5a** [comment]
Accessible by creating a spirit sheet and linking it to the file. Otherwise outside of scope.
