### ISSUE TITLE
Change "Print Notes" option to allow selecting by sections, rather than all-or-nothing

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3268]
**Is your feature request related to a problem? Please describe.**
I find it very frustrating when I print my sheet as a PDF for sharing, the notes can be very obnoxious in some places. I like to use the notes to keep track of qualities and gear mechanics (especially drugs), as well as describe my contacts and keep track of my spells and everything so i don't have to stop the entire table to reference the book several times every game. However, this gets really obnoxious in the gear section in particular. Here is one of my character sheets which is a particularly bad offender in this regard. 
[Trash Panda.pdf](https://github.com/chummer5a/chummer5a/files/2660319/Trash.Panda.pdf)

As you can see, the notes in the Gear section get out of hand very quickly in this case, and create a somewhat obnoxious PDF. Presently, the only real solution to this issue is either "don't show notes" which means the GMs of my living community can't see quick reference on what my qualities are (and when they can trigger my negative qualities) or blurbs about my contacts, or the alternative solution is "don't keep track of how your drugs work".

**Describe the solution you'd like**
Ideal solution in my mind is as non-obstructive and non-intrusive as possible. When printing the PDF, headers on all sections give you options:

Gear | Show: Yes | Page Break: No

It would be good if another option was present - Notes: Yes

In the solution I propose, this option is defaulted to no on all headers when the "Print Notes" box is not checked, or defaulted to "yes" on all headers when "Print Notes" is checked. For all intents and purposes, it would function the same way for anyone who doesn't want to bother with the feature. 

**Describe alternatives you've considered**
Other thoughts considered the possible addition of a "Hidden Notes" section instead, allowing the user to put short blurbs which won't be intrusive in Notes for the PDF, and much more detailed information in Hidden Notes.

**Comment by Lochabar** [comment]
Have you tried using any of the other character sheets?

Shadowrun 5 (Core) prints without any notes.
Notes prints only the notes
Contacts prints only the contacts (with notes)

**Comment by Teksura** [comment]
None of those are even close to the desired results. Please read the post you replied to to see what I mean.

**Comment by Lochabar** [comment]
Sorry then I guess I don't understand what exactly is getting out of hand. I had thought that the Notes sheet that prints any notes added to "qualities", "spells" and "gear", and the Contacts sheet that prints notes added to "contacts" covered what you asked about, without having to make major changes to the main character sheet.

**Comment by Teksura** [comment]
I am not sure what there is to not understand. I thought my original post was very clear about what section was getting out of hand, and I even included a PDF of one such character to show the cluttered up gear section. 

Your suggestions do not produce a character sheet with the notes on everything except the gear, I am confused by your comment that you do not understand how that is the case. 

Are you perhaps talking about instead printing out *3* different sheets and handing 3 different PDFs to the GM for them to inconveniently flip back and forth through? Because that is entirely different from what was described as desirable, and creates a whole mess of other issues that I don't think you thought about.

So you're aware, most GMs aren't going to be very happy with a player who asks them to now go through 3 separate character sheets as an alternative to having undesired clutter in the gear section because of notes. Being that annoying to your GM is actually a very effective way to not get picked for runs. Speaking from experience, it can already be plenty awkward enough flipping through 3-5 sheets in different tabs while running a game.

**Comment by Lochabar** [comment]
Then I am sorry you have such difficult DMs - I have never had one that does not understand that you cannot keep everything in your head or on a single sheet of paper. The core sheet has the most important data, anything else is easy to find on the other types of sheet (and a lot faster than looking thru the books which is what the DM normally has to do).


As far as modifying the sheets to provide a way to optionally print the gear I'm not sure it is actually possible to do because of the way XSL and CSS operate (they are used to generate the character window and the printed sheets). Everything is generated in advance and although you can select if a specific block can be printed, selecting something to be excluded from a block is a different thing altogether.

I'll step out of this conversation and leave it to someone else with a better understanding of XSL/css to decide if the enhancements you requested are even possible.

**Comment by chummer5a** [comment]
LCs are weird; I think I have a way to implement it that isn't completely horrible, will need to tinker.
