### ISSUE TITLE
Unable to select Metahuman type

### ISSUE THREAD

**Issue by MarkAColes** [chummer5a/chummer5a#3275]
**Describe the bug**
While creating a new character in 5.203.0 after selecting build method, the option of which metahuman type options are blank and unable to continue with character creation.

**To Reproduce**
1. Go to create New Character
2. Click on New Character
3. Click on Ok
4. Selection area for metahuman is blank

**Expected behavior**
A list of metahuman options appear

**Screenshots**
<img width="570" alt="chummer5error" src="https://user-images.githubusercontent.com/28923848/49759423-94c6b580-fcb9-11e8-88d6-240d4c2547db.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.203.0

**Comment by chummer5a** [comment]
I've had some people report this and found that they had a lot of customdata rules enabled that caused conflicts; it's most likely that?

**Comment by MarkAColes** [comment]
Hi

I have even tried a fresh download and not changed anything and still not
working.

Regards

Mark

**Comment by chummer5a** [comment]
Please check your registry file for Enabled customdata entries and see if deleting the customdata directory helps at all.

![image](https://user-images.githubusercontent.com/11448441/49798821-59021d80-fd97-11e8-9252-62e4fa3c0f37.png)
