### ISSUE TITLE
Effects of toxins

### ISSUE THREAD

**Issue by mwberlindeu** [chummer5a/chummer5a#3276]
Currently toxins are listed in the equipment with a reference to the book/page where a description on the effects can be looked up.
![image](https://user-images.githubusercontent.com/28268113/49815978-3955ff80-fd6d-11e8-9b24-0ee8b37a9823.png)
I would rather prefer to have the effects already written on the character sheet as this makes handling of toxins easier (especially if you are handling more than one "standard" toxin).

I am willing to code such an enhancement (but I will need some time...).

Similar issue: https://github.com/chummer5a/chummer5a/issues/1858

**Comment by Ramesch** [comment]
The information on the toxin properties as a note would indeed be helpful (similar to the notes regarding qualities). If you implement this, would it be with the possibility to add translations via the language files? I would contribute German translation. 

But maybe https://github.com/chummer5a/chummer5a/issues/3268 makes the layout confusing?

**Comment by mwberlindeu** [comment]
I would add translation to German (as this is my mother tongue…)

Thanks for the layout hint. If I get it right some toxin / drug effects have been added as note to the equipment. I will think about this.

**Comment by Ramesch** [comment]
When I created my runner, there were no notes for the toxins in Chummer5a. I have added them to my gear by myself. As far as I understand it, Teksura also added the attributes of the toxins himself.

**Comment by chummer5a** [comment]
The thought process I had was to create a Toxin class, possibly derived from Drug, but there's some extra baggage there that's not necessary. Since most toxins are just DV, Power and Speed, it shouldn't be super complex to implement them. Then they can be exposed to weapons and such and added to the sheets.

**Comment by Teksura** [comment]
A short term fix might be to make use of the notes option, and simply copy/paste the text from the book in as notes.

**Comment by Ramesch** [comment]
Is it possible that translations are taken into account when notes are used? Or is it like with the qualities that these are only embedded in English?

In the second case, it really would be a temporary solution.

**Comment by chummer5a** [comment]
Not super viable, but it can be made to work. If I had to just keep it
embedded as a tooltip I'd prefer to add it as a prefix or suffix to any
other notes and compile the text separately.
