### ISSUE TITLE
5.203.130 + Cyberware

### ISSUE THREAD

**Issue by skuben** [chummer5a/chummer5a#3283]
Using the nightly version 5.203.130

A cybered character (Who has the Adapsin bioware) tries to add Flare Compensation to his cybereyes.  These are his relevant stats before adding the Flare Compensation plug in

cyberware	4.02
Bioware		0.2
Essence hole	0.66
Essence 	        1.12

And these are his stats after adding Flare Compensation

Cyberware	4.02
Bioware		0.2
Essence hole	0.62
Essence		1.16

As you can see, his Essense hole has decreased (this shouldn't happen because it is a plug in to a Cybereye).
Also his Essence has increased (by the same amount that his Essence hole decreased).

I'm happy to upload the chummer file if it is needed

Using Windows 10, build 17134

**Comment by skuben** [comment]
Also reported this in #3279

**Comment by Ramesch** [comment]
As the changes to Chummer5a will only be applied to new program versions overnight, please try the Nightly, which will be available tomorrow (probably 5.203.131). https://github.com/chummer5a/chummer5a/commit/b5e85b770d159f2418c999693fde1fc78095455f  is supposed to fix that in this version according to chummer5a.

**Comment by skuben** [comment]
Reply, I thought this Nightly version (x.x.130) had this fix?

**Comment by Ramesch** [comment]
The submitted changes to Chummer5a will always be merged into a new Nightly version once a day. Once a solution has been submitted, you have to wait for the next release for your own tests.

Can you check tomorrow if your request is fixed with the next Nightly? If you can confirm the successful solution, this issue could be closed. Good luck!

**Comment by skuben** [comment]
I sure will

**Comment by skuben** [comment]
Just downloaded x.x.131 nightly build and tested and can confirm this is now working properly :)  Many thanks
