### ISSUE TITLE
Create when create new characters201812

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#3284]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
Can you please provide more detail about the issue? The specific crash reference should be stored in a chummerlog file on your desktop.
