### ISSUE TITLE
Can't filter gear by category

### ISSUE THREAD

**Issue by Gimbalhawk** [chummer5a/chummer5a#3289]
**Describe the bug**
The select gear menu doesn't populate it's categories dropdown correctly

**To Reproduce**
1. Go to the gear tab
2. Click on Add Gear
3. Click on the Category dropdown
4. Dropdown has only "Show All" and "Ammunition" categories

Also occurs when you attempt to add gear as a plugin, but if the owning gear/cyberware has a capacity then the dropdown list is entirely empty

**Expected behavior**
All valid gear categories should be in the list

**Screenshots**
![gear menu](https://user-images.githubusercontent.com/5201499/50123318-7a428e00-021d-11e9-8b55-6d1b07e4a5bc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.203.130

**Comment by chummer5a** [comment]
Seems to be working properly in current builds.

**Comment by Gimbalhawk** [comment]
Oh, odd. It isn't working after I updated chummer to 2.203.137, but I downloaded a clean version of that nightly and it works fine. Okay, time to figure out what I've done to my local version.
