### ISSUE TITLE
Math for Essense Discounts

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#329]
Currently, if you activate the house rule for Essence Discounts and fiddle with the costs for an item, this is what happens ...

(let's use one level of muscle replacement with an essence cost of 1 as an example)
(1) Base cost is 1.0.
(2) Use the house rule to give it a 50% discount, so that it becomes 0.5 essence.  Add it to the character.
(3) Right-click on the item, and set the grade to Alphaware instead of Standard.
(4) Note that the essence cost drops to 0.3 essence (additive) rather than 0.4 essence (multiplicative).

I would argue that having the Essence Discount be additive rather than multiplicative is confusing, since once you have attached the item to the character there is no way to change it (the essence discount percentage).  It is really a change to the base essence cost of the item, and as such should probably be a multiplier on the initial base essence cost.

I can easily change the code, but I figured I should confirm we WANT the change before I make it, since this is house rule stuff and there isn't a RAW rule to fall back on as to what to do.

 - cisco

**Comment by joha4270** [comment]
Personally i think you have the right point of view but i would like to confirm with the other guy before we make any change.

**Comment by chummer5a** [comment]
Doesn't bother me either way, as long as it doesn't break functionality for
anything else.
