### ISSUE TITLE
Special Modifications weapon accessories

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#3290]
The Special Modifications quality from Better Than Bad requires some form of accessory system to allow customisation of weapon DV and AP and such. Simplest mechanism is to provide accessories that have a requirement for the quality, but there's no way to restrict the number of devices you're allowed to have. 

Linked to #3285

**Comment by Gidoran** [comment]
Suggestion: Could you reuse some of the code from Overclocker? It seems like it has some potential. Make a section for each rank of the quality that unlocks based on what rank you have on the character, and have dropdown modifiers in there which apply. You'd only need two dropdowns per section, and one of them can lock itself if the first has +DV selected.

**Comment by chummer5a** [comment]
The problem with doing it that way is that it's not user-extensible (GM wants to allow replacing the fire mode on an SS pistol, for example) without a lot of extra work on our part. Doing it through accessories means that pretty much anything that can be done with the code can be implemented by someone who wants to do it.
