### ISSUE TITLE
Issue: - Mentor Spirit Holy Text: Attempting to Choose A Holy Book Crashes the Program

### ISSUE THREAD

**Issue by l0k102468** [chummer5a/chummer5a#3292]
### Environment
Crash ID: b9f7bdc6-4051-4f91-ab09-4bf7faed47a7
Chummer Version: 5.203.134
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Holy Book chosen, appearing in Knowledge Skills

### Actual behaviour
Chummer Crashes

### Steps to reproduce the behaviour
In character creation, select Holy Text mentor spirit. No options will be given for the knowledge skills, but if ok is pressed then the program will crash

**Comment by chummer5a** [comment]
So the problem with this is that we don't have a mechanism in place for prompting for skills that might exist, but can't be guaranteed to do so. Not really a cute fix for it at present, but the immediate fix would be to make a Holy Text knowledge skill.
