### ISSUE TITLE
List of books and their code

### ISSUE THREAD

**Issue by mrjester888** [chummer5a/chummer5a#3299]
**Is your feature request related to a problem? Please describe.**
Being new to Shadowrun, I am not able to easily decipher the book codes to know the name of source book for the particular rule/ability.  There are so many books!

**Describe the solution you'd like**
Ideal solution would have a tool tip that says the full title of the book.  Short of that, a wiki page that lists the book coding.

**Describe alternatives you've considered**
As is, I have to go look at the books.xml file to figure out the cipher.

**Comment by chummer5a** [comment]
Already exists, hover over the source label.
