### ISSUE TITLE
Problem using Re-apply Improvements

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3302]
**Describe the bug**
Used Re-apply Improvements and presented with "Select an Item" window showing the (GU)ID of an item instead of the name.

**To Reproduce**
Using a character with a Tradition
1. Go to 'Special'
2. Click on 'Re-apply Imrovements'
3. See error

**Expected behavior**
Show name not ID.

**Screenshots**
Window following click on Re-apply Improvements
![reapply improvements](https://user-images.githubusercontent.com/17562417/50384084-18eb4680-0685-11e9-8e4e-c4cab5a6510e.png)

From the character file
![tradition](https://user-images.githubusercontent.com/17562417/50384088-286a8f80-0685-11e9-914c-4ab06ff6a0ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home
 - Version: 5.203.138

**Comment by chummer5a** [comment]
Can't reproduce this in current builds. I think I stealth-fixed it a while back, but I'm not sure.

**Comment by Lochabar** [comment]
Sorry I didn't realize you were waiting on a response.

I tried Re-apply Improvements with 5.205.18 and still get the problem.
