### ISSUE TITLE
Discrepancies between usage of Locations

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3303]
**Describe the bug**
I've been investigating character sheet changes for issue #2990. I've been able to group melee weapons and ranged (not thrown) weapons by Location. However thrown weapons seems to have highlighted a problem with locations.

**To Reproduce**
1. Create a brand new character
2. Go to 'Street Gear' -> 'Gear'
3. Click 'Add Location' creating "Test"
4. Click 'Add Gear' and select 'Throwing Knife' [under Ammunition] to "Test"

5. Go to 'Street Gear' -> 'Weapons'. Notice that 'Throwing Knife' is greyed-out because it is from 'Gear'
6. Click 'Add Location' creating "Test"
7. Click 'Add Weapon' and select 'Knife' to "Test" then add, say, a "Browning Ghost" light-pistol to "Test"

8. Save the character then view the character file
9. Search for <name>Knife</name>
   Scroll down and observe location contains a GUID 
10. Search for Browning
    Scroll down and observe location contains a GUID
11. Search for <name>Throwing Knife</name>
    Under the Gear entry observe location contains a GUID 
    Under the Weapon entry observe location is blank

This problem seems to affect all thrown weapons; I also observed it with grenades.

**Expected behavior**
That the Weapons definition also contains the GUID of the location the same as non-thrown ranged weapons. 

Without the weapon definition containing the actual location it will difficult (if not impossible) to implement #2990 for melee weapons.

**Screenshots**
Gear tab showing Throwing Knife
![gear](https://user-images.githubusercontent.com/17562417/50384993-f7915700-0692-11e9-9a9c-695ac34d10bc.png)

Weapons tab showing Throwing Knife, Knife and Browning
![weapons](https://user-images.githubusercontent.com/17562417/50384994-05df7300-0693-11e9-8822-d4828aaaae1c.png)

Character file showing Knife definition
![xml - knife name](https://user-images.githubusercontent.com/17562417/50385000-168fe900-0693-11e9-8f42-bf8917df7529.png)
![xml - knife location](https://user-images.githubusercontent.com/17562417/50385002-1d1e6080-0693-11e9-9607-cd0b316925d3.png)

Character file showing Browning definition
![xml - browning name](https://user-images.githubusercontent.com/17562417/50385007-30c9c700-0693-11e9-99f2-b7e7362f3686.png)
![xml - browning location](https://user-images.githubusercontent.com/17562417/50385011-36bfa800-0693-11e9-98ec-0730a1c0e75e.png)

Character file showing Throwing Knife definition (Gear)
![xml - throwing knife name under gear](https://user-images.githubusercontent.com/17562417/50385022-49d27800-0693-11e9-9f7c-762ea4713a9c.png)
![xml - throwing knife location under gear](https://user-images.githubusercontent.com/17562417/50385026-548d0d00-0693-11e9-920f-8da1e2c52e13.png)

Character file showing Throwing Knife definition (Weapon)
![xml - throwing knife name under weapon](https://user-images.githubusercontent.com/17562417/50385032-640c5600-0693-11e9-97bf-26db39c6509c.png)
![xml - throwing knife location under weapon](https://user-images.githubusercontent.com/17562417/50385033-6969a080-0693-11e9-96f5-4b6fd33d84e4.png)

**Character File**
[Unnamed Character.zip](https://github.com/chummer5a/chummer5a/files/2706070/Unnamed.Character.zip)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home
 - Version: 5.203.138 [and prior]

**Comment by chummer5a** [comment]
Locations aren't persistent across categories, broadly intentionally; you should be able to drag the throwing knife into the weapon Test location and have it show up in the sheet though.

**Comment by Lochabar** [comment]
I tried to produce the character sheet that originally highlighted the problem to attach further screenshots.
The character file has been saved since. When I reopened the file and used the character viewer the knife was correctly listed under the location. :(

I'll close this issue for now. If find the problem again, and can reproduce it reliably, I'll reopen the issue with further information.
