### ISSUE TITLE
Cancelling SelectText prompts doesn't cancel LifeModule purchases

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3305]
**Describe the bug**
Added Escort as a Life Module. When Addiction dialog box presented I pressed Cancel. Escort and Addiction were added but no message next to addiction

**To Reproduce**
Create LM character - add escort, cancel the addition dialog.

**Expected behavior**
Return to LM choice screen

**Comment by chummer5a** [comment]
Rolling into #2000
