### ISSUE TITLE
Chummer Crashing/ Can't create new characters

### ISSUE THREAD

**Issue by alilley608** [chummer5a/chummer5a#3307]
I'm new to GitHub so I'm sorry if this is unhelpful. But I tried to link two existing characters in the "relationships" tab, and now whenever I open either character, Chummer crashes. 

Also, it won't let me make any new characters after the most recent update. Not sure why either.

**Comment by chummer5a** [comment]
A crash log should be generated on your desktop that includes some reference info I need to troubleshoot it, if you're not seeing the specific crash log yourself.

**Comment by alilley608** [comment]
[chummer_crash_131901911081402375.txt](https://github.com/chummer5a/chummer5a/files/2708244/chummer_crash_131901911081402375.txt)

This is the most recent. I don't know why it won't let me make new characters. It literally just doesn't allow me to click OK.

**Comment by chummer5a** [comment]
Well, that crash indicates that we're getting a null reference when looking for the metatype of the contact. Mind uploading the files?

**Comment by chummer5a** [comment]
Also a screenshot of the build method selection not allowing you to click OK would be helpful

**Comment by alilley608** [comment]
I'm a rookie. It won't let me upload any of the file types that it saves as or exports as. Can you walk me through how to get what you need?

**Comment by chummer5a** [comment]
Save them into a zip and upload it here, that'll work.

**Comment by alilley608** [comment]
[Character Files.zip](https://github.com/chummer5a/chummer5a/files/2709068/Character.Files.zip)
![screenshot chummer](https://user-images.githubusercontent.com/46121517/50426922-e3e71b80-085f-11e9-9626-8e7a0013fd20.jpg)

That should be everything you've asked for. It literally just won't let me click OK on the character creation screen.

**Comment by chummer5a** [comment]
Can't reproduce the crashes; it did give me a hint though, looks like you have all of the customdata entries enabled on; I believe some of the ones that adjust the metatypes and priorities have a conflict. If you can't see them activated in the options menu, open up your registry, go to HKCU\Software\Chummer5 and delete the CustomDataDirectory folder.

**Comment by alilley608** [comment]
So that fixed it! I am wondering if you can tell me why some of the characters don't print the full work up?  The first image is one that works fine. The characters are completed at the same level. The second image is what happens when I try to print one of the other characters. 
![print attempt thor](https://user-images.githubusercontent.com/46121517/50460995-6f37de00-0940-11e9-9998-75db093ef0ce.jpg)

![print attempt steven](https://user-images.githubusercontent.com/46121517/50460989-562f2d00-0940-11e9-8b32-7bb902dd3f73.jpg)
