### ISSUE TITLE
Chummer crashes upon opening using Windows XP

### ISSUE THREAD

**Issue by Nephrios** [chummer5a/chummer5a#331]
The error message I get is: The application failed to initialize properly (0xc0000135), Click on OK to terminate the application.

I am using an older computer running windows XP, a recent update has caused Chummer to not work at all on my tower and netbook. If you need more information I will try and help as much as possible. 

Thank you for your time.

**Comment by joha4270** [comment]
Try downloading the latest version of chummer (172) and running chummer5.legacy.exe

If that don't work, XP is past the end of support from Microsoft and chummer requires technologies not present on XP.
