### ISSUE TITLE
Issue: - Hard Crash when reloading Multi-Barrel Weapons

### ISSUE THREAD

**Issue by Reag** [chummer5a/chummer5a#3312]
### Environment
Crash ID: 30101c68-ba31-4eb3-9d6d-3447886d4c97
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Reloading a Hammerli Gemini pistol will fill it with ammo

### Actual behaviour
Crashes

### Steps to reproduce the behaviour
Buy a Hammerli Gemini pistol in career mode. Buy Ammo (Tested with APDS). Fill pistol. Cry.
[chummer_crash_131905041687007322.txt](https://github.com/chummer5a/chummer5a/files/2715688/chummer_crash_131905041687007322.txt)

**Comment by drewikari** [comment]
I am having the same problem with gel rounds on it

**Comment by Reag** [comment]
After looking through the code, and testing with other weapons, I believe the issue is caused by multi-barrel weapons. The "x2" or "x6" is not processed correctly for determining ammo load. This issue affects all multi-barrel weapons.

**Comment by drewikari** [comment]
Still crashing when trying to load the Gemini
