### ISSUE TITLE
Issue: - Crash when opening file or saving new

### ISSUE THREAD

**Issue by definitelysmib** [chummer5a/chummer5a#3313]
### Environment
Crash ID: 07dd436f-20e4-42ec-bde0-669e3e2a4007
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Open previously saved chumm5 file via menu, save newly created character.

### Actual behaviour
Crashed immediately upon clicking 'open' or 'save'. I can drag and drop saved files and save them. This is the first time using chummer on this Windows install. It also encounters an error when collecting crash information.

![chummercrash](https://user-images.githubusercontent.com/46250775/50542466-d09fbd00-0b8b-11e9-942a-152b49a2f099.PNG)

UPDATE: I also can't save as pdf, but I can print. Save As also causes a crash.

**Comment by chummer5a** [comment]
Is this still happening in current builds?
