### ISSUE TITLE
Essence Loss calculated Wrong

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#3319]
This is an issue of Order of Operations; its been persisting across nightly/stable builds for about 4-5 months
still present on latest nightly (3.142)

Have: 
2 magic
1.21 Essence
1.37 Essence Hole

The program will, in the order listed, make adjustments to attributes.  When Upgrading wear to a higher grade the program will:
* Lower (or just actively delete) Magic score and related Tabs
* Consume essence
* Consume Essence Hole
* Replace Essence 

In that order.

The order of operations for the program should be:
* Consume Essence Hole
* Consume Essence
* Lower Magic score, (or if <1, delete) Magic score and related Tabs

If the Improvements Tab actually worked, this would be less of an issue

**Comment by chummer5hasanerror** [comment]
correct

**Comment by chummer5a** [comment]
Appears to be working correctly from my end; absent anyone else able to replicate the issue I'm not sure there's anything to be done with it.
