### ISSUE TITLE
Improvements not able to be entered

### ISSUE THREAD

**Issue by drewikari** [chummer5a/chummer5a#3323]
When trying to add initiative dice as an improvement, it is forcing you to hit a select value button that does not exist.  Using nightly build 5.203.142

To recreate click improvements tab.  Add improvement.  Select Initiative Dice.  Raise value.  ( I was adding 2).  Hit OK.  This prompts you to select a value but it is not possible to do so nor should extra dice need a value selected.  Previous versions of chummer correctly added the dice.

**Comment by chummer5a** [comment]
Should be working in the latest nightly build.
