### ISSUE TITLE
Swap Quality/Mentor's Mask

### ISSUE THREAD

**Issue by aegisflashfire** [chummer5a/chummer5a#3328]
**Describe the bug**
Swap Quality does not add Mentor's Mask Power points

**To Reproduce**
Create a Adept character
Add mentor spirit
chose Swap Quality, and swap it with a 2nd Mentor Spirit, making sure to check Use Mentor's Mask
Power point is not awarded for adding Mentor's Mask.

**Expected behavior**
Deleting the Mentor's Mask Quality, then Adding it back with Mentor's Mask does grant the power point.

**Screenshots**

**Character File**
[Stripes(career).chum5.txt](https://github.com/chummer5a/chummer5a/files/2721118/Stripes.career.chum5.txt)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by aegisflashfire** [comment]
To convert the file back just delete the .txt extension

**Comment by Teksura** [comment]
> To convert the file back just delete the .txt extension Sent from my iPhone, please excuse any typos
> […](#)
> On Jan 4, 2019, at 2:25 PM, Teksura ***@***.***> wrote: Seems to be working for me in 5.203.0 I can't check your chummer file since you converted it to a .txt and I'm not sure how to change it back. Try just compressing the .chum5 file into a .zip and uploading that. I tried it out on my Adept and it worked fine, give it a go with that file. Vasuki.chum5.zip My steps: Open Character. Note current power points are at 7 with 0.5 remaining. Select Mentor Spirit Quality Swap quality Pick Mentor Spirit from list Pick a mentor (I just picked shark again) Make sure Mentor's Mask is checked. Confirm the swap. Power Points are now properly adjusted. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Literally the first thing I tried. As you can see from my comments, I specifically mentioned that as something which I attempted, and which did not work. Also, as you can see in my comment, you'll see that in the end I did make something work. (Actually I had to create a new character, and then just copy/paste the data from the text file into the newly created save file).

**Comment by chummer5a** [comment]
Unable to reproduce the issue in current builds. Code indicates it should work as expected.
