### ISSUE TITLE
Additional Drug Stuff

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3338]
Presently, there is a fair amount of information relating to drugs which isn't listed in the gear section, and all drugs are considered the same type in spite of different options existing.

I understand that Drugs will eventually be moved into the Drugs tab, and so before that happens I'd like to throw the following on the table for consideration to be included as a part of that transition:

### Drug Grade Options
When buying drugs, RAW allows buying drugs of different grades. The tables list the default price, but there is also Pharmaceutical, Designer, and Street Cooked which adjust the price (among other things).

I've currently been taking care of this with the "Name gear" option to denote what drugs are pharma grade.

### Useful Info About Drug
Drugs in your gear section don't tell you anything about the drug itself. While weapons and vehicles list useful info to have at your fingertips, having info about the drugs would be great. with the plans to roll the Drugs into the Drug tab, this is a good chance to expand on that and include more info, much like we have available in the Weapon Tab. A small list of things that might be good to include:

- Grade (Selected at time of purchase)

- Vector (Selected at time of purchase)

- Addiction type

- Dicepool for addiction roll (Since some LCs have custom rules for addiction, this should be something that can be modified with custom rules)

- Duration

- Speed

- Crash Effects

- Notes - A lot of drugs have extra effects that aren't related to adjusting your ability scores, and would require just a text field to describe the drug effects.

Related issue: #1858

**Comment by chummer5a** [comment]
Completed in heisenberg branch, will be added into the main branch when completed.
