### ISSUE TITLE
Issue: - Don't know what happened here.

### ISSUE THREAD

**Issue by CthulhuHalo** [chummer5a/chummer5a#3340]
### Environment
Crash ID: b28cabf7-aebf-432f-9623-706809c2e29c
Chummer Version: 5.203.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Scrolling through Cyberdeck inbuilt features

### Actual behaviour
Crash
![image](https://user-images.githubusercontent.com/44953290/50787983-104e5f00-1286-11e9-8e2f-605acb4f51b0.png)

### Steps to reproduce the behaviour
I don't actually have any idea.

**Comment by chummer5a** [comment]
Can't replicate it; is there a specific deck you'd added?

**Comment by CthulhuHalo** [comment]
The Excalibur or Paladin. I was creating an NPC using the "ignore character creation rules" modifier in Karma mode. Attached is the actual error log file as far as I can tell. Maybe more information there.

I don't know if it's relevant, but the NPC I was creating was an AI. Xenosapient specifically.

[chummer_crash_131913617205453629.txt](https://github.com/chummer5a/chummer5a/files/2739291/chummer_crash_131913617205453629.txt)

**Comment by CthulhuHalo** [comment]
I imagine you need more information to figure this out? If I remember correctly, I had given the AI every program that was in the books that I have, but I don't see how that'd be relevant. I hadn't saved, so I can't send the charsheet file, though, and that's all I can think of that I had done that might have crashed it.

**Comment by CthulhuHalo** [comment]
...I think I know what happened then. Using the scrollwheel/arrow keys to tab through things while hovering over rating may lower it more than the application can keep up with.

**Comment by chummer5a** [comment]
I think this might have been fixed in current builds, but I'm not sure. Still can't replicate the issue, so /shrug

**Comment by CthulhuHalo** [comment]
It hasn't happened again since that first time, I still don't know what
happened.
