### ISSUE TITLE
Authoritative Tone

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#3341]
**Describe the bug**
Commanding Voice was renamed Authoritative Tone, but the price seems to have increased as well. Commanding Voice in SG cost 0,25 but in Chummer Authoritative Tone now costs 0,5.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
https://www.shadowruntabletop.com/wp-content/uploads/Downloads/E-CAT27003E_SG-Errata.pdf

> P. 170, COMMANDING VOICE CHANGE
> The version of Commanding Voice on p. 185, Stolen Souls, stands. This power is changed to Authoritative Tone, costs 0.50 PP per level (max 3), and is described as follows: Adepts with this power can speak in a way that immediately makes people want to believe them and follow their orders. For every level of this power, an adept gains a +1 die to any Opposed Social Skill Test that they initiate (normal limits apply).
