### ISSUE TITLE
Cannot create characters/no metatypes available to select

### ISSUE THREAD

**Issue by calyboi96** [chummer5a/chummer5a#3342]
I am unable to create the character I want as the only metatypes available to select from are Metasapients, even if I disable all the sourcebooks except for Shadowrun 5e core, I get a blank list with none of the standard metatypes available (screenshots below for convenience) This issue persists after multiple attempts to redownload chummer

![chummer error 1](https://user-images.githubusercontent.com/46484677/50827958-e48bb180-1337-11e9-8d3e-98f5f525559b.png)
![chummer error 2](https://user-images.githubusercontent.com/46484677/50827959-e5244800-1337-11e9-988f-79bb8b09a980.png)

**Comment by chummer5a** [comment]
This tends to be a bug with customdata files interacting weirdly. Best bet is to open your registry, navigate to HKCU\Software\Chummer5\CustomDataDirectory and delete the contents.
