### ISSUE TITLE
Chummer crashes when selecting specific weapon

### ISSUE THREAD

**Issue by Kyanor** [chummer5a/chummer5a#3344]
Chummer crashes completely when I select Onotari HL-13.  Happens even in the newest version.

**Comment by chummer5a** [comment]
Can't replicate it; please provide more detail and/or a character save file.

**Comment by Hubok** [comment]
Interjecting here with my own findings: I get a what seems identical issue with the Nissan Optimum II. If I disable Run and Gun, I can use browse view with all categories, so likely no issues.

The WEIRD part is I have all sourcebooks enabled, but I can't eve see the Onotari HL-13. 5.204.0 and Windows 10. Would provide crash log, but crash handler crashes.

**Comment by chummer5a** [comment]
HL-13's availability 14, it'll be filtered by your gameplay rules in create mode. Fixed the Optimum's crash, typo in the data.

**Comment by Hubok** [comment]
Checked on my side after enabling all availabilities, the HL-13 does not cause a crash. They are right next to each other though, there's potential for confusion.

**Comment by Kyanor** [comment]
Yeah, fixed here too now.  Weird, I was really specific and clicking only the HL-13 when testing on two different machines.
