### ISSUE TITLE
Improve appearance of the SelectAttribute improvements for Infected

### ISSUE THREAD

**Issue by Sercalerc** [chummer5a/chummer5a#3345]
Is Infected: Ghoul working as intended? I may be blind and/or mentally deficient, but the rules for it clearly state what stats are improved by it in the book, yet it asks what stats are affected when you add the quality. It's also the wrong number of stats, even, because it improves BOD, REA, STR, INT, and WIL in the book. This is present for both Infected: Ghoul (Human) and Infected: Ghoul (Elf), I haven't tested it with Troll, Ork, or Dwarf. Pic shown here is the window that pops up and the next one shows that I can also just select the same 4 stats to improve, too. 
![image](https://user-images.githubusercontent.com/37052216/50952614-f166ed00-147e-11e9-8db0-4f30c5ea1d27.png)
![image](https://user-images.githubusercontent.com/37052216/50952743-61757300-147f-11e9-907f-6e8b0402e3cc.png)

**Comment by Sercalerc** [comment]
Also win 10 and 5.204.0

**Comment by chummer5a** [comment]
RF 135
> Add two points to selected Physical Attributes (+1 to two or +2 to one)
> Add two points to selected Mental Attributes (+1 to two or +2 to one)

**Comment by Sercalerc** [comment]
> 
> 
> RF 135
> 
> > Add two points to selected Physical Attributes (+1 to two or +2 to one)
> > Add two points to selected Mental Attributes (+1 to two or +2 to one)

Ah okay, I'm blind and retarded.

**Comment by chummer5a** [comment]
Yeah, it's easy to overlook. I'm still not happy with how this works for infected so I'm tempted to build something new for it, but I don't like making custom forms unnecessarily and I'm not confident that making it looks like Choose One: (+2 BOD/+1 BOD, +1 STR, etc.) is neater, particular with the infected that can choose any attribute.

**Comment by Sercalerc** [comment]
Well my initial reaction, bearing in mind I probably suck at ui, would be to just copy the attributes section and put it in list form, with numeric updown boxes beside each of the options and then just leaving text at the top as something like "please choose which mental and physical stats you'd like to increase" and then maybe leaving a page reference tooltip. But yeah, it's Shadowrun being Shadowrun again
