### ISSUE TITLE
Issue: - Crash

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3347]
### Environment
Crash ID: 58c36f26-dee9-4a36-b547-ec1567615f41
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
No crash?

### Actual behaviour
Chummer crashed when I tried to buy Narco. Create mode.

### Steps to reproduce the behaviour
Haven't tried yet.
Happened while troubleshooting earlier issue. (skill pools not updated when atts changed)

**Comment by chummer5a** [comment]
Can't replicate the crash; what's the crash log say?
