### ISSUE TITLE
Issue: - Crash when adding weapon to vehicle mount.

### ISSUE THREAD

**Issue by Yellowrobe** [chummer5a/chummer5a#3348]
### Environment
Crash ID: 945f7ecf-35cd-4f10-bcf4-e17a96b0450b
Chummer Version: 5.204.0
Environment: Windows 10 Education
Runtime: 4.0.30319.42000

### Expected behaviour
Open description for the Nissan Optimum II while adding a weapon to a vehicle weapon mount.

### Actual behaviour
Crash once Nissan Optimum II was clicked in the Assault Rifles weapon list.

### Steps to reproduce the behaviour
1) Add a vehicle to the character (I was using the Rover 2072 if you want to repro exactly)
2) Add standard weapon mount. By right clicking the vehicle and selecting "Add weapon mount"
3) leave any settings in that dialog as default and press okay
4) right click the mount and click "Add weapon"
5) change sorting to "Assault Rifles"
6) Select the Nissan Optimum II
It should crash once it is clicked.

**Comment by chummer5a** [comment]
Should be working properly in nightlies. There was an issue with the underbarrel mount not being named correctly.
