### ISSUE TITLE
Values for chameleon suit and control rig

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3349]
**Is your feature request related to a problem? Please describe.**
After the 6th edition of the German core rule book is finally available as a PDF document, I have compared a few values. Before I make any adjustments to the XML files, I would like to make sure that the current English version contains this information (the English PDF document is unfortunately only available as 4th printing):

Differences between English (4th printing) and German (6th printing) rules and regulations (German data in brackets) for Chameleon suit, SR5 436 (Chamäleonanzug, SR5 440):
- Availability: 10R (12R)
- Costs: 1700 (4500)

Missing restriction for the control rig, SR5 453 (German: Riggerkontrolle, SR5 457): "(Rating x 5)**_R_**" instead of "(Rating x 5)"

Can anyone confirm this with the current English core rule book?

**Describe the solution you'd like**
If the above data is correct, I would add a German custom rule for the chamaelion suit and adjust the availability of the control rig in cyberware.xml.

**Comment by chummer5a** [comment]
Hasn't changed in the English version as best I'm aware.

**Comment by Ramesch** [comment]
Thanks, I uploaded the adjustments as a pull request
