### ISSUE TITLE
Hunter Deck: Shark

### ISSUE THREAD

**Issue by Daelmaron** [chummer5a/chummer5a#3359]
**Is your feature request related to a problem? Please describe.**
The Hunter Deck: Shark from Kill Code page 62 is missing from Chummer

**Describe the solution you'd like**
The Hunter Deck: Shark from Kill Code page 62 to be added to Chummer

**Describe alternatives you've considered**
There aren't any alternatives to this feature request.

**Additional context**
State line for the Hunter Deck is Rating 8, Attack 10, Sleaze 1, Data Proc. 8, Firewall 10, Avail 16R, Cost 1,032,000 Nuyen, Programs included are: Track, Shell, Hammer, Decryption, Hammer, Mugger, Fork

**Comment by chummer5a** [comment]
>Avail 16R
Availability filter.
