### ISSUE TITLE
Weird Issue With Windows 10

### ISSUE THREAD

**Issue by TheRealNamikaze** [chummer5a/chummer5a#336]
I just did a clean installation of Windows 10, and installed Chummer to C:\Chummer 5A.  When I attempt to open a Chummer portfolio, I tell Explorer where to find Chummer to open the file.  And nothing happens.  I can open Chummer all day long without any issues, and the icon is associated with .chum5 files.  Additionally, once Chummer is open, I can access all the .chum5 files just fine.

I suspect the issue might be somehow tied into the Windows shell?  I'm not really sure - any suggestions would be welcome.

**Comment by chummer5a** [comment]
Hrm, I can't replicate this. I've been operating on Win10 since the insider
preview came out without any issues. Something janky with the new way
Windows 10 wants you to map file associations, maybe.

**Comment by TheRealNamikaze** [comment]
Perhaps - I tried moving my Chummer installation to C:\Program Files (x86)\Chummer5 and no joy there either.  I also attempted to use Task Scheduler to start an elevated session of Chummer (without triggering UAC) and I had the same result.  I'll try a couple more things and update if I find anything else out.

**Comment by joha4270** [comment]
I have found the cause of this issue, will have fix soonish.
