### ISSUE TITLE
"Root element is missing"

### ISSUE THREAD

**Issue by StroggMakron** [chummer5a/chummer5a#3364]
I really don't know what happened here.

So I save and close my character in Chummer, right? Keep working on her for another day? Alls well. Then I load up Chummer. My character name is in red. Selecting her crashes the program. Deleting the MRA strings in regedit (which is what I was told to do) fixes it so much as making the recently used characters not show up. Okay, fair enough, I'll just load her normally then and - 

Yep. Another crash.

"This file failed to load with the following XML error: Root element is missing"

I spent a decent amount of time on this character. I'd rather not have to create her purely from scratch again, as this would mean having to re-guess what gear I gave her and what I set values to. Please help

I am using version 5.204.0

https://cdn.discordapp.com/attachments/527895453644357652/535366362764148736/Agent_762.chum5

**Comment by chummer5a** [comment]
File is null, possibly wasn't saved properly. Check your saves\autosaves directory to see if there's a copy of the file.

**Comment by StroggMakron** [comment]
![errorreprot](https://user-images.githubusercontent.com/36212644/51318263-d15b9e80-1a27-11e9-96d6-c7ba31e23c25.png)
Thanks, but now when I open any form of Chummer I get this. Doesn't matter if its a fresh download of it or not

**Comment by StroggMakron** [comment]
Fixed it. had to delete a config file in my appdata/local/Original_Chummer_for_4th/Chummer5e folder
