### ISSUE TITLE
 'Rockblood Signature Armored Shirt'

### ISSUE THREAD

**Issue by itsuperslug** [chummer5a/chummer5a#3369]
**Describe the bug**
Unable to select 'Rockblood Signature Armored Shirt', select the item from 'select armor' screen causes Chummer to crash

**To Reproduce**
1. Go to 'Street gear' > 'clothing and armor'
2. Click on 'add armor'
3. Scroll down to/ search for 'rock' and select  'Rockblood Signature Armored Shirt'
4. See error/ program crashes

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chummer Version 5.204.6

**Comment by chummer5a** [comment]
Can't replicate it, what's the crash dumper say?

**Comment by itsuperslug** [comment]
cant .zip it small enough, any other ways of getting it to you?

**Comment by chummer5a** [comment]
Should be a file on your desktop that has the relevant text, something like chummerlog_{date}.txt

**Comment by itsuperslug** [comment]
see attached
[chummer_crash_131925400558537825.txt](https://github.com/chummer5a/chummer5a/files/2778660/chummer_crash_131925400558537825.txt)

**Comment by chummer5a** [comment]
Hm, that shouldn't happen. It's basically saying that the source detail reference is null, but it's supposed to get created when the base object is. Almost seems like TCT is missing as a book or something.

**Comment by itsuperslug** [comment]
just tried a clean install with new character, same error

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/2647fd2ec777481ed0d378c4a85c8ecc3c994016
