### ISSUE TITLE
Issue: - CRASH on browse weapons

### ISSUE THREAD

**Issue by CthulhuHalo** [chummer5a/chummer5a#3371]
### Environment
Crash ID: 476dd387-0755-4d6f-99ab-cb6b59ceb13a
Chummer Version: 5.204.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Browse weapons

### Actual behaviour
Crash [chummer_crash_131925330583854922.txt](https://github.com/chummer5a/chummer5a/files/2778082/chummer_crash_131925330583854922.txt)

### Steps to reproduce the behaviour
Create a character in the karma system, add the quality

**Comment by chummer5a** [comment]
Should be working in nightlies.
