### ISSUE TITLE
Issue: - custom pack with qualities crashing

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3374]
### Environment
Crash ID: c9d6a1e1-9b73-49f1-84e7-0b664323d10c
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
I wanted to speed up generating a character through a pack.

### Actual behaviour
Adding the pack works, but crashes the app once everything's finalised.

### Steps to reproduce the behaviour
Try to add the pack called Erisychthon (once Chrysalis). It will crash.

[custom_packs.zip](https://github.com/chummer5a/chummer5a/files/2779373/custom_packs.zip)

**Comment by chummer5a** [comment]
Looks like we changed the save format for packs at some point and didn't update it properly. I'll have it fixed for the next build. 
[custom_packs.zip](https://github.com/chummer5a/chummer5a/files/2782092/custom_packs.zip)
