### ISSUE TITLE
Keep track of the overwatch score

### ISSUE THREAD

**Issue by scrato** [chummer5a/chummer5a#3378]
As a GM, I made all characters in Chummer for the players and I use it during sessions for managing the different vital stats / ammunition for the new unexperienced players. So I use it to manage and oversee the party.
What I am missing is the overwatch score of the single individual. 
I want to keep track when the player get's to 40 and it would be cool if I could do this in the same program I use to keep track of the other parameters.

**Describe the solution you'd like**
A new tab, where I can see the matrix monitor, the overwatch score, reset it and raise it.

**Describe alternatives you've considered**
If you won't to this I'm forced to keep track in onenote ;-)

**Additional context**
Thank you very much for developing this marvelous software!

**Comment by chummer5a** [comment]
Shouldn't be hard to do, would probably chuck it into the GM Dashboard but that's still not quite ready for prime time. I had a plan for a Persona tab that would list all your Matrix devices and let you group them into master-slave relationships and such, but I'm trying to avoid implementing major new functionality at present.
