### ISSUE TITLE
Data Entry: Universal Sealant - Wrong Page

### ISSUE THREAD

**Issue by mrjester888** [chummer5a/chummer5a#3379]
**Describe the bug**
Universal Sealant is listed as being on page 152.  It is actually listed on page 154

**To Reproduce**
Add Gear: Select Universal Sealant 

**Expected behavior**
Display CF154

**Screenshots**
https://i.imgur.com/QMqZRgm.png

 - Version 5.204.14

**Comment by Ramesch** [comment]
This issue can be closed as page number was fixed.
