### ISSUE TITLE
Revision History Formatting Is Lost

### ISSUE THREAD

**Issue by mrjester888** [chummer5a/chummer5a#3380]
**Describe the bug**
The revision history window does not format the content. It is one giant wall of text.

**To Reproduce**
Chummer -> Help -> Revision History: 

**Expected behavior**
Revision notes to be in a readable format.

**Screenshots**
https://i.imgur.com/g9Z3QwY.png

**Desktop (please complete the following information):**
 - OS: Win10 1809
 - Version 5.204.16

**Comment by DelnarErsike** [comment]
I am unable to replicate this issue on Windows 10 in the latest dev build. Could you check to see if the issue is still present for you in the latest nightly build?

**Comment by mrjester888** [comment]
This was fixed in the early 205 release period.  I thought I just missed this issue being closed.  Cheers.
