### ISSUE TITLE
No Zoology skill for Flesh Sculptor

### ISSUE THREAD

**Issue by Pellease** [chummer5a/chummer5a#3381]
Just downloaded the most recent Chummer 5.204 I think. When I go to take Flesh Sculptor it says I need the Zoology skill but the only skill I can find that's close is a specialization in Biology for Parazoology and that doesn't seem to work.

**Comment by OLStefan** [comment]
I think you should be able to just create a new Knowledge skill and call it Zoology.

**Comment by cfresquet** [comment]
Why not add it to the list of suggested academic knowledge skills so that other users don't wind up with the same confusion?
