### ISSUE TITLE
Options window to small

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#3386]
**Describe the bug**
The options window is to small and not resizable. The widgets to edit source book related data like path to pdf are not fully visible and thus not usable.
I have not tested if the problem depends on the selected language (German in my case).

**To Reproduce**
1. Open the options dialog
2. Select a book in the list on the global page

**Expected behavior**
Either increase the size of the dialog to fit its content, and/or make the dialog resizable.

**Screenshots**
![screenshot_20190127_083759](https://user-images.githubusercontent.com/6452504/51798225-a6cfc980-220f-11e9-9021-a7bd9b1b567e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.207.217

**Comment by Moby2kBug** [comment]
The selected language will not change this. Even in English this option is still not properly shown.
