### ISSUE TITLE
Issue: -Version .204.23 is crushing CRAP

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3387]
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.frmCareer.PickGear(IHasChildren`1 iParent, Location objLocation, Boolean blnAmmoOnly, Gear objStackGear, String strForceItemValue, IEnumerable`1 lstForceItemPrefixes) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 14540.
   bei Chummer.frmCareer.cmdAddGear_Click(Object sender, EventArgs e) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 3407.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei SplitButton.OnMouseUp(MouseEventArgs mevent) in C:\projects\chummer\Chummer\SplitButton.cs:Zeile 306.
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei SplitButton.WndProc(Message& m) in C:\projects\chummer\Chummer\SplitButton.cs:Zeile 807.
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:Zeile 113.
Crash id is f5b050c8-caf4-4b72-a15d-74930dc8704f
Crash working directory is C:\Users\media\AppData\Local\Temp\chummer_crash_131930867804439121

this asshole version crashes every time, i want to bring my character back.... fix this!

**Comment by drewikari** [comment]
creating a character and saving it then closing it causes issues.  when reopened in create or saving to career cause qualities and cyberware/bioware to be lost.  this nightly build makes chummer unusable
