### ISSUE TITLE
Nightly Build Erasing Multiple Things When Opening Characters

### ISSUE THREAD

**Issue by drewikari** [chummer5a/chummer5a#3389]
Build 5.204.23

Any character saved during this build and then reopened loses qualities, gear, cyberware, bioware, nuyen and karma tab data, lifestyles, mentor spirits, stats raised after entering career mode, and initiation grades.

This also happens when converting a character to career mode out of creation.

**Comment by chummer5a** [comment]
That's interesting. I suspect the sinners plugin is trying to do some stuff while it's deactivated; could you please try enabling the plugin and logging into it to see if it still does it? Otherwise I'll have a look in a few hours and try and replicate it.

**Comment by VIT-Boi** [comment]
Similar problem, it has also moved around skills and I tried activating the plugin, still deletes the majority of stuff.

**Comment by chummer5a** [comment]
Found the problem, fixed in the latest commit. Please provide any damaged files and I'll fix them.

**Comment by VIT-Boi** [comment]
@chummer5a Bit unsure how to get you the files. Pretty new to Github.

**Comment by VIT-Boi** [comment]
[Neural blowout broken career.zip](https://github.com/chummer5a/chummer5a/files/2810582/Neural.blowout.broken.career.zip)

Ah, thanks for that. Heres the file.

**Comment by chummer5a** [comment]
[Neural blowout fixed career.zip](https://github.com/chummer5a/chummer5a/files/2810624/Neural.blowout.fixed.career.zip)
Here you go.

**Comment by VIT-Boi** [comment]
Looks to be fine, thank you very much!

**Comment by drewikari** [comment]
[Fenrir.zip](https://github.com/chummer5a/chummer5a/files/2814453/Fenrir.zip)
[Exterminator Nein.zip](https://github.com/chummer5a/chummer5a/files/2814456/Exterminator.Nein.zip)

These are two of mine.  One of the guys in my group has a couple also

**Comment by VIT-Boi** [comment]
[Anothercharacter.zip](https://github.com/chummer5a/chummer5a/files/2823904/Anothercharacter.zip)

@chummer5a Sorry to bother again but noticed one of my other characters was buggered as well. Can you fix it as well?

**Comment by chummer5a** [comment]
[Cereal killer Career.zip](https://github.com/chummer5a/chummer5a/files/2824005/Cereal.killer.Career.zip)
[Fenrir Nein.zip](https://github.com/chummer5a/chummer5a/files/2824022/Fenrir.Nein.zip)
