### ISSUE TITLE
Crash when selecting gear

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3391]
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.frmCareer.PickGear(IHasChildren`1 iParent, Location objLocation, Boolean blnAmmoOnly, Gear objStackGear, String strForceItemValue, IEnumerable`1 lstForceItemPrefixes) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 14540.
   bei Chummer.frmCareer.cmdAddGear_Click(Object sender, EventArgs e) in C:\projects\chummer\Chummer\frmCareer.cs:Zeile 3407.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei SplitButton.OnMouseUp(MouseEventArgs mevent) in C:\projects\chummer\Chummer\SplitButton.cs:Zeile 306.
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei SplitButton.WndProc(Message& m) in C:\projects\chummer\Chummer\SplitButton.cs:Zeile 807.
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:Zeile 113.
Crash id is d7456e08-2eb0-495f-a5a4-4b3a62db2e59
Crash working directory is C:\Users\media\AppData\Local\Temp\chummer_crash_131931649322025857

I saved before this step to be able to continue after the crah, BUT:
when restarting the saved file, everything has gone wrong:
- no qualities are shown
- the timeline has vanished
- skill values are miscalculated, etc ...

**Comment by DecklandMulqueen** [comment]
Could be….. Stefan? Bist du deutsch? Wär glaub einfacher, oder…😉

 

Von: Stefan Niewerth <notifications@github.com> 
Gesendet: Montag, 28. Januar 2019 18:44
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Crash when selecting gear (#3391)

 

Seems like duplicate of #3389 <https://github.com/chummer5a/chummer5a/issues/3389>

**Comment by DecklandMulqueen** [comment]
The character file as you wished! 

 

It worked until .204.13 … and .204.17 until .204.23 was released … after .204.23 the .204.17 version produced the same error.

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Mittwoch, 30. Januar 2019 13:29
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Crash when selecting gear (#3391)

 

The PickGear issue is resolved in current builds, I'll need to see the character file to fix it.

**Comment by chummer5a** [comment]
Github eats attachements sent via email, could you upload it via the issues page or send it to chummer5isalive@gmail.com, please?
