### ISSUE TITLE
Crash on Save/Autosave in latest build

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#3392]
**Describe the bug**

latest source is crashing in line #1829 of clscharacter.cs because this.OnSaveCompleted is null, making for a callback to nothing.

Adding a null check to the previous line (changing line #1828 to be):
`if (callOnSaveCallBack && this.OnSaveCompleted != null)`
lets me not crash, but not sure if this is a hack workaround of there really needs to be a callback 
set somewhere else.

**Comment by chummer5a** [comment]
Fixed in latest commit.
