### ISSUE TITLE
Issue: - Crash on Save

### ISSUE THREAD

**Issue by mrjester888** [chummer5a/chummer5a#3394]
### Environment
Crash ID: b88cff9c-eed3-400e-ba35-da987e9892c7
Chummer Version: 5.204.17
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
Charater saved

### Actual behaviour
Chummer crashed

### Steps to reproduce the behaviour
Open character, click save.

[chummer_crash_131932406340044524.txt](https://github.com/chummer5a/chummer5a/files/2807782/chummer_crash_131932406340044524.txt)

**Comment by chummer5a** [comment]
Should be fixed in the latest nightly.
