### ISSUE TITLE
Character with exceptional attribute quality crashes on load

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#3396]
**Describe the bug**

Load a character with a stat at racial max+1 because they have the exceptional attribute quality. Boom, exception.

**To Reproduce**

Load the attached character.

Watch chummer crash on line #225 of CharacterShared.cs with objAttrib = "INT" because this character
is a human with an INT of 7.

**Expected behavior**

Not crashing.

**Character File**

[Ayatsuri.zip](https://github.com/chummer5a/chummer5a/files/2809068/Ayatsuri.zip)

**Comment by chummer5a** [comment]
Nah, it's a corrupted character from the other issue. Improvements weren't being loaded properly. 
[Ayatsuri.zip](https://github.com/chummer5a/chummer5a/files/2811565/Ayatsuri.zip)

**Comment by cfresquet** [comment]
thanks for fixing the character file!
