### ISSUE TITLE
Game Master and Group Options [1] - Share Option in Group (GM)

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3402]
I'll put this in a user story format. I'll put up other to match / extend this one
**Describe the solution you'd like**
As a Gamemaster I would like to share with my players which books, house rules, custom data files and Karma costs I'm using in my game so that they can more easily comply with the rules in my campaign when updating / changing their characters.

**Additional context**
This story matches #3403 which is the Players side of the story

**Comment by ArchonMegalon** [comment]
Ok, short question to @chummer5a here: how can I assign issues to myself? Because - that is probably somethings I could work on - in the far future...

**Comment by chummer5a** [comment]
Tossed you a collaborator invite, you'll be able to assign yourself to issues and push directly into the repo once you accept. 

Broadly this is already in the application, if you have multiple settings files you'll be prompted for which you want to use for a given character.

**Comment by ArchonMegalon** [comment]
@chummer5a Just a question: If ChummerHub learns to store a file for each group (= a collection of n SINners - nothing user related), would it be possible to store the specific setting-file there and download/apply them to the character after downloading the chum5-file?

How do these setting files get? Can I store them in the database, or should I use the GDrive-Backend for this as I do with the chum5-file?

**Comment by chummer5a** [comment]
It's mostly a collection of books and ints, it'd struggle to be more than 50kb at a guess. Might be cheaper in storage to whack it into a database and recompile when a user requests it
