### ISSUE TITLE
Game Master and Group Options [3] - Joining Groups

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3404]
Describe the solution you'd like
As a Player I want to be able to join multiple gaming groups and have a one or more characters in each group with each character complying to the specific books, house rules, custom data files and karma cost set by that group.

**Alternative Solution**
If possible I think playing one character in multiple groups (each with their own book limitations, house rules, karma costs etc.) would be great. This would mean, that gear, skills, qualities etc. need to be "removed" (or disabled) when moving to a group that disallows those. Karma cost would have to be-calculated etc... probably not easily possible.
This could be considered in a more complex "migrate to group" function...?

**Additional context**
This story builds on #3403 and #3402

**Comment by ArchonMegalon** [comment]
I'm not sure if this can be done. One character (the same file) with different rules in different groups, seems... very complicated to implement and a (probably) not very often used feature.

Currently my design aims towards a Character being member of only one group at a time. Of course you can switch groups any time you want and - if the other group has settings-files attached to it - download them to your local client. But being at the same time in multiple groups.... I don't know....

**Comment by chummer5a** [comment]
Multiple rules files on the same copy of Chummer for different characters is perfectly doable, a single character file that fits multiple rulesets is unlikely.
