### ISSUE TITLE
Dronemod points

### ISSUE THREAD

**Issue by JSteger** [chummer5a/chummer5a#3409]
Hello ! 

I recently went through the Rigger 5.0 and noticed that currently in chummer only the vehicle upgrade rules are applied to everything. Have the drone upgrade rules not been implemented yet or did I miss something?

If it has not been implemented yet it would be awesome if it could be done because the vehicle upgrade rules are simply nerfing the drones below large.

**Comment by chummer5a** [comment]
Enable the rule in options.

**Comment by chummer5a** [comment]
Specifically, Tools -> Options -> Character Options -> Use Drone Modification Rules.
