### ISSUE TITLE
Recent orphan improvement checks keep character from loading

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#3410]
**Describe the bug**

Try to load the attached character.  Get the orphaned improvement checks warning dialog that was added this morning.

Pick either option (also, this dialog is difficult to understand and is going to cause confusion).  Character fails to load.

**Expected behavior**

Character should load.

**Character File**

[Echo - Career 046.zip](https://github.com/chummer5a/chummer5a/files/2826030/Echo.-.Career.046.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: local build from latest source

**Comment by chummer5a** [comment]
Ack, thanks for catching that one!
