### ISSUE TITLE
Drone modding german version 

### ISSUE THREAD

**Issue by JSteger** [chummer5a/chummer5a#3412]
Hello !

I recently asked about the drone modification points. I was pointed towards the option where I can switch it on. Thanks for that by the way !

Now to the issue. I noticed that by switching the drone modification points, all drones will use exclusively the mod points. In the german version of the Rigger 5.0 that I bought revently, there is an additional info window in which is said that large drones can always use the vehicle or the drone point modifications. 

I am not sure if this is only vaild for the german version, as I compared this to the older english version that a friend of mine has, in which this info window is missing completely, or if it is an errataed version with additional info. 

P.S. or this feature is already implemented and I just missed it again. In which case I am sorry for wasting time.

**Comment by JSteger** [comment]
I could translate the paragraph for you if that would help. Is it normal for the german books to contain things that the english ones did not ? I just assumed that it would be also added in the new english books.

I kinda find it logical from a game perspective that the large drones can use either drone rules or vehicle rules. Since those are the only ones that can actually benefit a lot from the vehicle ones and are actually large enough to reasonably carry any of them XD

**Comment by chummer5a** [comment]
It's not uncommon; the errata process for CGL's books is famously slow. Pegasus tends to get the benefit of having the completed book in hand and an opportunity to make changes that the editing team can't or won't. /shrug

What's it actually say? Is it either or, is it both, is it specifically Large or greater, etc.

**Comment by JSteger** [comment]
I´ll write a translation here then. It is written on the perfect beast section of the Rigger 5.0 german version in a seperate info box:

Modificationrules for Vehicles and Drones

The here listed modification rules for Vehilces can also be used for (large) drones. If you decide to use the vehicle rules you may not use the dronemodifcation rules in the autmated army section. Unless you are using special houserules you must use one or the other.

translation end. 

So according to the german rulebook you can use either the vehicle rules or the drone rules depending on your preference but only one of the two. Which makes sense kinda. Large drones profit much more from the vehicle rules and they can actually use most of the things there in a somewhat realisitc fashion.

I.e. A medicart with a valkyrie module or the like I think.
