### ISSUE TITLE
Spell Jammer Incorrect Cost

### ISSUE THREAD

**Issue by dmlinch** [chummer5a/chummer5a#3413]
During Character creation- Spell Jammer Positive Quality (Forbidden Arcana pg 40) cost is incorrect. Chummer cost is 4 Spells and zero karma. Cost should be 20 karma.

**Character File**
[Okami.txt](https://github.com/chummer5a/chummer5a/files/2833183/Okami.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.204.0

**Comment by chummer5a** [comment]
Mastery Qualities preferentially consume spell points instead of karma as it's more efficient to do so from a char-op perspective. Working as intended.
