### ISSUE TITLE
Feature Request: In Career Mode, show the cost to improve on things you can't afford

### ISSUE THREAD

**Issue by alexthuth** [chummer5a/chummer5a#3414]
**Is your feature request related to a problem? Please describe.**
When working with characters in career mode, I am frustrated when I cannot quickly see what the cost of the next level of improvement is for things I can't afford and have to return to my books to validate what I am think. While purely a quality of life feature, this will remove a pain point for new Shadowrun players who do not have the improvement tables memorized and allow them to more easily use Chummer as a progression planning tool.

**Describe the solution you'd like**
In career mode, when you hover over the disabled improvement button (the grey plus-in-a-circle) used to improve a skill or attribute, show text that describes what it would cost to improve the skill or attribute from the current level to the next. The text should be visually different enough from a hover over on an improvement you do have the resources to increase to reduce the likelihood a user clicks on the disabled button believing they can increase it.

A possible example would be a user having 4 karma in the bank and the open and active character has 2 charisma. Hovering over the plus button to improve charisma would show, in red text, "Can improve from 2 to 3 for 15 karma"

**Describe alternatives you've considered**
The primary alternative is leaving it as it and not doing it. Additional options that would provide a similar functionality (albeit less convenient to the user) would be to have a link on the attributes and skills pages that shows the improvement tables from core, so a user can quickly reference in-app how to improve. While better than current state, I believe this is a suboptimal solution to the proposed hoverover.

**Additional context**
Mock-up of primary proposal attached: 
![cost to improve on hover over](https://user-images.githubusercontent.com/36005888/52319728-24b67200-2980-11e9-8c36-36180d413649.png)

**Comment by chummer5a** [comment]
Sure, easy fix.

**Comment by alexthuth** [comment]
> Sure, easy fix.

You're a gentle(wo)man and a scholar, a hero for the ages, a friend of the weak, a defender of the defenseless. Thank you!
