### ISSUE TITLE
Reaction Enhancers + Wired Reflexes

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#3417]
**Describe the bug**
Reaction bonus should stack, but it does not

**To Reproduce**
Create new character and buy Reaction Enhancers 1 and Wired Reflexes 1. 

**Expected behavior**
This should increase Reaction by 2, but it only ads 1

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
Turned the wireless bonus on for both?

**Comment by chummer5a** [comment]
Wireless bonuses are only enabled in career mode. Since you need wireless to be enabled for both cyberware, that'll be why it's not showing the bonus.

**Comment by Johnny8-0** [comment]
Thanks

Sent from Valhalla

On 9 Feb 2019, at 08.43, Chummer 5 Is Alive <notifications@github.com> wrote:

Wireless bonuses are only enabled in career mode. Since you need wireless to be enabled for both cyberware, that'll be why it's not showing the bonus.

**Comment by Johnny8-0** [comment]
Where do I turn it on?

**Comment by tcjennings** [comment]
Ditto. I've opened a character in Career Mode and can't find any kind of wireless toggle. (5.204)

**Comment by Johnny8-0** [comment]
This is still not working. I have all wireless boxes ticked and my wired reflexes and reaction enhancers still do not stack. Nor does my Smartlink apply +2dice to my dice pool under any of my smartlinked weapons.
