### ISSUE TITLE
Smartlink not added to dice pool

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#3418]
**Describe the bug**
Smartlink does not add to dice pool

**To Reproduce**
Buy gun, add smartlink, buy cybereye with smartlink

**Expected behavior**
Total dice pool +2

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
Requires that the wireless bonus be enabled on the smartlink, which isn't shown in create mode.

**Comment by Johnny8-0** [comment]
Where do I turn it on?

**Comment by chummer5a** [comment]
Presuming you're on a current nightly build, it should be visible as a checkbox that says Wireless. If you'd prefer not to use nightlies, you'll have to wait for the next milestone release for it to be available.
