### ISSUE TITLE
Breast Implants listed as plural in book, but specifically "One Breast" in chummer

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3419]
**Describe the bug**

Chrome Flesh lists Breast Implants. Plural. With an S at the end. Meaning more than one. 

![screen shot 2019-02-08 at 8 38 04 pm](https://user-images.githubusercontent.com/1766631/52516526-018afd00-2be2-11e9-9675-aad1421cf9cf.png)

However, Chummer only gives you one of the 2 implants with erroneous "(One Breast)" text added to the end.

**Comment by chummer5a** [comment]
"Sold singly, but you probably want a pair."
