### ISSUE TITLE
Right Click on Character tab, context menu to allow close

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3421]
**Is your feature request related to a problem? Please describe.**
No - just UI improvement

**Describe the solution you'd like**
In the Tabbed view, I'd like to be able to rightclick on the tab and close the character. Save option should be offered

**Describe alternatives you've considered**
I currently move the mouse up to the X to close the character. Isn't hard but standard tabbed browsing allows a right click context menu

**Comment by mrjester888** [comment]
Good call posting this. The number of times I have tried to right-click to close a tab...
