### ISSUE TITLE
Cybertorso cannot add armor

### ISSUE THREAD

**Issue by alexthuth** [chummer5a/chummer5a#3422]
**Describe the bug**
When modifying cyber torsos on a character in create mode (either obvious or synthetic), armor is not available to add to the torso. According to SR5 description of armor modification for cyberlimbs, it should be available. I am unsure if this has never been added or is a regression.

**To Reproduce**
1. Create a character in Chummer
2. Go to "Cyberware & Bioware" tab
3. Click Cyberware button
4. Add a used Synthetic Cybertorso to the character
5. Right click on the Synthetic Cybertorso entry on the left rail and click 'Add as Plugin'
6. The list of all modifications does not contain armor
7. Repeat 2-6 with Obvious Cybertorsos.
8. Advance the character to Career Mode
9. Repeat 2-6 for both Obvious and Synthetic Cybertorsos

**Expected behavior**
Armor (up to rating 3) is eligible to add to cyber torso

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.204.46

**Comment by chummer5a** [comment]
Can't reproduce it, I'm afraid. Is it possible you're using an outdated version of the RunnerHub rules? I believe they used to prohibit adding armour to torsos and skulls.
