### ISSUE TITLE
Orphaned Improvements?

### ISSUE THREAD

**Issue by CthulhuHalo** [chummer5a/chummer5a#3427]
Less an issue, more a few questions: What exactly _are_ Orphaned improvements? Is there a way to tell which improvements in a character sheet are orphaned? Is there a way to load characters with orphaned improvements? Is there a way to manually remove the orphaned improvements so I can make a list of what's being changed? If a sheet has no orphaned improvements, Would the sheet still trigger the orphaned improvements dialogue? What causes orphaned improvements? Attached sheets trigger orphaned improvements check, do they actually have any? What are the ones they have?

[OrphanedImprovements.zip](https://github.com/chummer5a/chummer5a/files/2848672/OrphanedImprovements.zip)

**Comment by chummer5a** [comment]
An orphaned improvement is one that doesn't have a source object that generated it, but isn't a custom improvement. Generally these would be created if an object is removed or changed but it didn't remove its improvements first. The issue with qi foci duplicating their stats is typical of this; both of your characters have orphaned SelectText improvements referring to Grids, indicating that a lifestyle was removed in a way that caused it to not remove its improvements properly.
