### ISSUE TITLE
Quality: Biocompatibility / Adapsin

### ISSUE THREAD

**Issue by TFHatter** [chummer5a/chummer5a#343]
The essence cost reduction for this quality is not accurately implemented.

From CF: "the reduction for alphaware of 0.8 is reduced by ten percent, or 0.08, to become 0.72, and is rounded down to 0.7"

This rounding is always down and applies to all grades. Currently, the quality is only implemented accurately for standard grade 'ware.

Adapsin is another addition from Chrome Flesh that has the same problem with its implementation.

From CF: "Adapsin reduces the Essence cost of implanting  cyberware  (but  not  bioware)  by  ten percent  (round down)"

**Comment by chummer5a** [comment]
With a test character that has Biocompability(Cyberware) and an implanted Control Rig, we have an Essence cost as follows:
Standard: 0.9, flat reduction by 0.1
Used: 1.15, only outlier in the group, likely something to do with the 125% multiplier starting point.
Alpha:0.7, original value of 0.72
Beta:0.6, original value of 0.63
Delta:0.4, original value of 0.45
Gamma: 0.3, original value of 0.36

I'm not really seeing the problem with the math?

**Comment by TFHatter** [comment]
I should probably have tested that more thoroughly. I assumed that because the values for used 'ware were wrong that it was a more general problem. In any case, the values for used 'ware are still not right.

**Comment by Malkleth** [comment]
There's no rounding involved. When the book says "lower costs by ten percent" what the mean is that Adapsin and biocompability subtract .1 from the final result.  So, Alphaware is .8, biocompatability makes this .7 and adapsin knocks this down to .6

**Comment by TFHatter** [comment]
If there's no rounding involved then why does the book explicitly mention rounding? I quoted the book in my original post.

If there's an errata for this maybe you should post a link.

**Comment by chummer5a** [comment]
It's mentioned on the official forums that the intent was that the grade is
discounted by ten, they're just terrible at wording stuff.

**Comment by HaikenEdge** [comment]
I've literally just dug through both the "Errata" and the "Rules & Such" sections of the Catalyst Shadowrun board, and I haven't found a single developer response in any of the Biocompatibility threads, so any mention of "intent" doesn't seem to be coming from the developers, or at least not in either of those subforums, which would seem to be the appropriate place for them to respond, given it's a rule and errata question.

**Comment by chummer5a** [comment]
http://forums.shadowruntabletop.com/index.php?topic=21061.msg381782#msg381782

Apparently CGL don't believe in errata these days, or they just like making
life difficult for us.

**Comment by HaikenEdge** [comment]
As far as I can tell, Wakshaani isn't part of the Catalyst Game Labs team, otherwise the user would have a Freelancer title for the member title, so that's at best somebody's house rule, and not an actual developer response.

**Comment by chummer5a** [comment]
https://www.reddit.com/r/Shadowrun/comments/3czavj/in_which_wakshaani_is_interviewed/

Wakshaani <https://www.reddit.com/user/Wakshaani> Munitions Expert
(Freelancer)[S
<https://www.reddit.com/r/Shadowrun/comments/3czavj/in_which_wakshaani_is_interviewed/>
] 2 points 3 months ago

Primarily the Codes of Honor and the gear PACKS that make shopping easier.
(Which includes the "I'd buy that for a Nuyen!" sidebar.)

.

I'm usually more of a supporting role than a primary, and Chrome Flesh is
the first time I've essentially been the lead for a project.

**Comment by chummer5a** [comment]
This is CGL we're talking about. They can't even be bothered to update the
list of books they're selling on their main page, what makes you think
they'd bother to update the title of a freelancer on their forums?

**Comment by HaikenEdge** [comment]
Bleh. Catalyst is a mess.
