### ISSUE TITLE
Character messed up from issue #3389

### ISSUE THREAD

**Issue by drewikari** [chummer5a/chummer5a#3430]
Found a character that got screwed up during that nightly build.  Could you please apply the fix you did for those others?

[Keiji.zip](https://github.com/chummer5a/chummer5a/files/2853566/Keiji.zip)

**Comment by IkariMadness** [comment]
[Richard VanRoss.zip](https://github.com/chummer5a/chummer5a/files/2853858/Richard.VanRoss.zip)
I have a few characters with the same issue.  I will attach them here.
[Conrad.zip](https://github.com/chummer5a/chummer5a/files/2853859/Conrad.zip)

**Comment by chummer5a** [comment]
[Conrad-RichardVanRossFIXED.zip](https://github.com/chummer5a/chummer5a/files/2854848/Conrad-RichardVanRossFIXED.zip)

[KeijiFIXED.zip](https://github.com/chummer5a/chummer5a/files/2854850/KeijiFIXED.zip)
