### ISSUE TITLE
Problem with Devicemodifications

### ISSUE THREAD

**Issue by JSteger** [chummer5a/chummer5a#3435]
Hello, I recently wanted to modify the matrixattributes on a commlink and noticed an issue. 
According to the rules on Datatrails page 66 The "Modify a Matrix Attribute" and "Increase a Matrix Attribute" cannot be applied to Attributes that have been added through the "Add a MAtrix attribute" modification. 
By raw and by logic this should be possible. Since a Attack attribute of 1 will not do anything most likely.

**Comment by chummer5a** [comment]
What's the problem, exactly? Is Chummer allowing you to add modifications that you shouldn't be?

**Comment by JSteger** [comment]
No its not allowing me to add modification that should be there. 
Ok let me give you an example, I want to make a commlink with some sleaze attribute for some hacking fun. 

Buy commlink, add sleaze attribute. So far so good. 
Now of course since the commlink with only sleaze 1 will do no good I would increase it by 1 or modify the other 2 attributes in favor of sleaze. But I do not get those options. It seems like the equipment adding process does not see that the commlink now has a increaseable sleaze attribute. 

Does that help ? English is not my main language so i might be writing it unclearly.

**Comment by chummer5a** [comment]
For some reason we coded it so that you add the Increase modification to the Add modification, try that.

**Comment by cfresquet** [comment]
Probably because that's literally what the book says: " The Increase a Matrix Attribute modification can later be added to this [Add a Matrix Attribute] modification."

Otherwise, you wouldn't be able to do this, since normally "Unless otherwise noted, a device can
only have one modification."

**Comment by chummer5a** [comment]
Welp, that'd do it.
