### ISSUE TITLE
Add Bioware to a Shapeshifter

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3438]
I can only add Cyberware to a Shapeshifter. Delta Grade Bioware or Geneware is not available

**Comment by chummer5a** [comment]
Chummer doesn't do anything to prevent shapeshifters from taking cyberware or bioware; Can you provide more detail about what you're trying to do?

**Comment by DecklandMulqueen** [comment]
I just want to add 2 genetech modifications. I can`t choose the whole Bioware Menu … it seems tob e hardcoded

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Freitag, 15. Februar 2019 13:03
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Add Bioware to a Shapeshifter (#3438)

 

Chummer doesn't do anything to prevent shapeshifters from taking cyberware or bioware; Can you provide more detail about what you're trying to do?

**Comment by chummer5a** [comment]
The only things that block bioware are the Sensitive System quality and the Regeneration power, unless you're using some custom rules.

**Comment by DecklandMulqueen** [comment]
Then ist Regeneration

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Freitag, 15. Februar 2019 13:28
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Add Bioware to a Shapeshifter (#3438)

 

The only things that block bioware are the Sensitive System quality and the Regeneration power, unless you're using some custom rules.
