### ISSUE TITLE
Issue: - crashing when selecting the Rockblood Signature Armoured Shirt

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3439]
### Environment
Crash ID: d57438f2-b0b3-4c35-a56d-3acf9436682f
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
I was browsing armours in Chummer, not expecting a crash in the slightest.

### Actual behaviour
Every time I click on the Rockblood Signature Armoured Shirt from "The Complete Trog", the app crashes.

### Steps to reproduce the behaviour
Try clicking on the Rockblood Signature Armoured Shirt, then accept the crash.

**Comment by chummer5a** [comment]
Fixed in nightlies, I believe.
