### ISSUE TITLE
Custom Fit (Stack) not applying Stack Armor Value

### ISSUE THREAD

**Issue by Thelinil** [chummer5a/chummer5a#344]
When equipping Custom Fit and Custom Fit (Stack) clothing, it no longer has an option to select the stack armor value. Only the highest armor value is selected.

**Comment by chummer5a** [comment]
Hrm. That's annoying. What SHOULD be happening, is the armour with Custom Fit (Stack) should evaluate whether switching to its bonus value would cause a higher value than if it was the highest armour.

**Comment by chummer5a** [comment]
Fixed in 5.173; improvement got lost in a merge.
