### ISSUE TITLE
Issue: Karma Graph is not drawing using wine on opensuse 15.0

### ISSUE THREAD

**Issue by BJoeBR** [chummer5a/chummer5a#3442]
### Environment
Crash ID: 6e5fbe5f-12c9-4f66-91b2-61d5bc07c488
Chummer Version: 5.204.0
Environment: Microsoft Windows 7 (using wine and opensuse 15.0)
Runtime: 4.0.30319.34209

### Expected behaviour
draw the karma graph per time for included save (using wine on opensuse 15.0)

### Actual behaviour
draws the entire screen except for the graph, loads for a while and then crashes saying it run out of RAM (I have a 16GB RAM Machine)

### Steps to reproduce the behaviour
simply go to the karma and nuyen screen using the included savefile. (rename Hanna (Stalker)d.txt to a chum5 file

[chummer_crash_131948546168058860.txt](https://github.com/chummer5a/chummer5a/files/2872682/chummer_crash_131948546168058860.txt)

[Hanna (Stalker)d.txt](https://github.com/chummer5a/chummer5a/files/2872688/Hanna.Stalker.d.txt)

**Comment by Teksura** [comment]
Interestingly, it works fine on Wine on my end. Likewise, using Windows 7 in Wine, although I'm doing it with Crossover. Are you using this on Linux or a Mac?

![screen shot 2019-02-21 at 11 10 45 pm](https://user-images.githubusercontent.com/1766631/53225787-f8f8e480-362d-11e9-9dd6-4f3209c4727d.png)

**Comment by BJoeBR** [comment]
it´s Linux (open suse to be exact)

**Comment by ArchonMegalon** [comment]
Actually I'm glad it doesn't flat out crash your installation. We had some reports about that as well. :/
Still no clue what causes that...

**Comment by ArchonMegalon** [comment]
Has something to do with Karma being 0 in the end - or something like that. Try adding karma (or subtracting it)

**Comment by BJoeBR** [comment]
Operating System: openSUSE Leap 15.0
Kernel: Linux 4.12.14-lp150.12.48-default
um genau zu sein.
Nein gerade versucht mit 6 Karma passiert es genauso.
configuring wine to use win 10 or win 7 makes no difference

**Comment by chummer5a** [comment]
Mitigation exists in current build to disable the graph and prevent crashes. Any further fix will depend on changing UI stack or wine team fixing the issue on their end.
