### ISSUE TITLE
Issue - Chummer crashes when using restart functions

### ISSUE THREAD

**Issue by Wenlocke** [chummer5a/chummer5a#3443]
[exception.txt](https://github.com/chummer5a/chummer5a/files/2877117/exception.txt)
[attributes.txt](https://github.com/chummer5a/chummer5a/files/2877119/attributes.txt)

### Environment
Crash ID: b68a4746-b92f-4a10-a7ca-c18a72a88f61
Chummer Version: 5.204.55
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer restarts after update
### Actual behaviour
Chummer crashes and does not restart

### Steps to reproduce the behaviour
use an "update and restart" option from chummer update.

From the error, it looks like the process is isn't properly letting go of files/isn't able to reopen them correctly.
I have a crashdump available, but can't add it to this log.

**Comment by chummer5a** [comment]
Should be fixed in https://github.com/chummer5a/chummer5a/commit/0db4550764ce7dee471cc2261891c8c5d7dc82c4
