### ISSUE TITLE
Street Level runner, ways and Validation

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3447]
**Describe the bug**
I was told that Street Level magic users cannot have a way as the Way is 20 karma and the limit for street level is 13.

My assumption is that this is correct. Making this assumption but testing on Chummer: the validation allowed the configuration to pass.
(not currently home so no file to share)

**Comment by chummer5a** [comment]
Can't reproduce it in the current nightly build.

**Comment by SeanPGorman** [comment]
@chummer5a  So you're saying it _should_ work?

I am using .204.0 and it doesn't flag on the Validation tool.

**Comment by chummer5a** [comment]
If you're using Point Priority then the karma cap is still 25; otherwise, the cap should be 13, as you said. When I try and add the quality to a new build of Chummer, I get a prompt that I can't take that quality because it goes over the cap. Can't even add it and run the validator.
