### ISSUE TITLE
The "Silence is Golden" quality from Kill Code does not appear in the list of qualities for AI Characters

### ISSUE THREAD

**Issue by Emparawr** [chummer5a/chummer5a#3450]
The "Silence is Golden" quality from Kill Code does not appear in the list of qualities for AI Characters

**To Reproduce**
1) Go to options and make sure Kill Code is checked as a source
2) Create an AI character
3) Hit the add Quality button
4) see that there is no Silence is Golden quality listed. 

**Expected behavior**
There should be a Silence is Golden quality on the list because nothing about being an AI should prevent taking it. 

**Desktop (please complete the following information):**
Windows 7

**Comment by chummer5a** [comment]
Per Data Trails, AIs have a whitelist of qualities.

**Comment by Emparawr** [comment]
But killcode was released after data trails, therefore the list is incomplete by it's nature, and nothing about the description of the quality negates it being taken by an AI. Is there a way for me to just override this that doesn't involve me going in and changing the code?

**Comment by chummer5a** [comment]
You'd need a custom file to handle it. This file should more or less work, but I haven't tested it. You'd need to add the names of any qualities you wanted to add; you'll need to remove the relevant sections if you're not adding negative or positive qualities. 
[amend_ai_metatypes.zip](https://github.com/chummer5a/chummer5a/files/2893232/amend_ai_metatypes.zip)
