### ISSUE TITLE
Shapeshifter Skills, the Perceptive Quality and Improved ability adept power

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3452]
When shifting from the animals form to the matavariant form, the skills are not calculated with the metavariants set of attributes. Limits and all other calculations are just fine.

Further: is it correct, that knowledge skills, which are purchased during creation and thus calculated with the animals attributes keep the animal attribute reference, when changeing to the metavariant form in career mode?

The "Perceptive" quality is available in a 5KP and a 10KP step, giving +1 or +2 to all relevant perception/assensing tests. Currently, there is only the 5KP version available.

The "Improved Skill" adept power adds its benefit for each level ... so a +1 skill works fine, a +2 results in a +2 +2 benefit ;) This is cool, but unfortunately not correct

**Comment by chummer5a** [comment]
I believe these issues should be fixed in the current nightlies?

**Comment by DecklandMulqueen** [comment]
Skills and Perceptive yes (THX for that!!!) but improved ability NOT

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Freitag, 22. Februar 2019 12:46
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Shapeshifter Skills, the Perceptive Quality and Improved ability adept power (#3452)

 

I believe these issues should be fixed in the current nightlies?

**Comment by chummer5a** [comment]
Probably the orphaned improvement bug; if you save the file, close it, load it again and accept the warning about orphaned improvements, does it go away?

**Comment by DecklandMulqueen** [comment]
NO

 

The improved ability bug and the one, that knowledge skills are calculated with only the animals form stay.

 

The orphaned ability bug was never in question with this charcter

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Freitag, 22. Februar 2019 13:24
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Shapeshifter Skills, the Perceptive Quality and Improved ability adept power (#3452)

 

Probably the orphaned improvement bug; if you save the file, close it, load it again and accept the warning about orphaned improvements, does it go away?

**Comment by chummer5a** [comment]
The Perceptive quality has multiple levels now, so you'll be able to purchase the second level with the Level spinner above the list of qualities.
