### ISSUE TITLE
Custom Drug Issues

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#3455]
**Describe the bug**
 * [ ] All custom Drugs have a Speed of immediate
 * [x] You can create a custom drug with no name (There is a warning to give the drug a name, but it closes the 'Create custom Drug' window and you can't give it a name)
 * [x] You can't delete custom drug after creating them
 * [ ] The Info box doesn't update the quantity

**Screenshot**

[Screenshot](https://imgur.com/UUg8Dg9)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version 5.204.63/5.204.0

**Comment by chummer5a** [comment]
Started working on it last night, including the issues from #2915 #1858 and #3338

**Comment by pan-mroku** [comment]
Also one of my players managed to create a drug that was not displaying in tab but resulted in generating blank pdfs. 
[custom_drug.txt](https://github.com/chummer5a/chummer5a/files/2928183/custom_drug.txt)

**Comment by GeertPut** [comment]
I created a custom drug. Then deleted it. However it remains in the selected drugs list. When I select it the entire application crashes 
![image](https://user-images.githubusercontent.com/16984202/55293081-731d4580-53f2-11e9-83eb-eb6037e6d083.png)
