### ISSUE TITLE
Character file with issue from #3430.  Crashing Chummer.

### ISSUE THREAD

**Issue by IkariMadness** [chummer5a/chummer5a#3458]
[Conrad-RichardVanRossFIXED.zip](https://github.com/chummer5a/chummer5a/files/2913197/Conrad-RichardVanRossFIXED.zip)
### Environment
Crash ID: acd0b489-284a-4adb-a288-3e4ec28481e8
Chummer Version: 5.204.64
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Character file repaired from issue #3430.

### Actual behaviour
Crashing chummer upon opening.

### Steps to reproduce the behaviour
Attempted to open 3 times.  Each resulted in same error and failure to open.

**Comment by chummer5a** [comment]
What's the crash say?

**Comment by ArchonMegalon** [comment]
This part in Richards file throws the error:

<attribute>
      <name>CHA</name>
      <metatypemin>1</metatypemin>
      <metatypemax>**4**</metatypemax>
      <metatypeaugmax>8</metatypeaugmax>
      <base>**5**</base>
      <karma>-1</karma>
      <metatypecategory>Standard</metatypecategory>
      <totalvalue>5</totalvalue>
</attribute>

Easy to fix (I attached the file), but question is how you managed to get it to 5 in the first place. Can you provide details about it?

[Richard VanRoss.zip](https://github.com/chummer5a/chummer5a/files/2940693/Richard.VanRoss.zip)

**Comment by ArchonMegalon** [comment]
Edit again - ok, I missed the exceptional Attribute Cha quality. Here we go again...

[Richard VanRoss.zip](https://github.com/chummer5a/chummer5a/files/2940737/Richard.VanRoss.zip)
