### ISSUE TITLE
Knowledge skills defaulting incorrectly

### ISSUE THREAD

**Issue by countsfromzero** [chummer5a/chummer5a#346]
For priority gen for sure, not certain about others. Per page 89 core, should default to (int+log)x2, currently defaults to x3

**Comment by chummer5a** [comment]
Issue with default values. Open Tools > Options > House Rules > enable and
Disable the "Free Knowledge Skills equal to X' house rule.

**Comment by chummer5a** [comment]
Fixed in 5.174.
