### ISSUE TITLE
Issue: - Chummer crashed while I was try to add assault rifles

### ISSUE THREAD

**Issue by diztracshon** [chummer5a/chummer5a#3461]
### Environment
Crash ID: 3357e4c4-5b96-483f-9439-3c214eda2d29
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Display assault rifles details tab.

### Actual behaviour
Chummer crashed

### Steps to reproduce the behaviour
With Core, Run Faster and Run and Gun loaded.
Create new character or load existing character
Add weapon, select assault rifles from the dropdown
Go to Details tab, nothing shows up and then the program crashes
It also usually crashes if I try to add an assault rifle without checking details
- Always crashes when adding an assault rifle from run and gun, usually crashes adding a different assault rifle
- I have not checked if it crashes adding other types of guns from run and gun.

This did not happen when I didn't have Run and Gun loaded and didn't happen with the other categories I used (blades, light pistols, holdouts and heavy pistols).
The issue stopped when I removed run and gun from sources.

The crash reporter thing also crashes when I try to report this issue.

**Comment by chummer5a** [comment]
Should be fixed in current nightly builds. I'll be pushing a new milestone build in the next couple of days if you'd prefer to stick with that.
