### ISSUE TITLE
Character File corrupted after saving and restarting pc

### ISSUE THREAD

**Issue by GabeDX** [chummer5a/chummer5a#3464]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version  5.204.31]

**Describe the bug**
Character file was corrupted after saving and restarting the computer.

1. Go to 'quicksave trying to open the character in Chummer'
2. Pop up with headlines "could not load" and text "the file failed to load with the following xml error: 
Das Stammelement ist nicht vorhanden.
3. reproduced 5 times

**Expected behavior**
Opening the Character in Career Mode. As I did in the last month.

[Lee Margury (night).txt](https://github.com/chummer5a/chummer5a/files/2923426/Lee.Margury.night.txt)

**Comment by chummer5a** [comment]
Well, that file is broken; can you check in chummer\saves\autosaves to see if there's an existing file to restore from?

**Comment by GabeDX** [comment]
That file was from autosaves. It´s the one I always used. 
Found an older save. 
[Lee Margury (night).txt](https://github.com/chummer5a/chummer5a/files/2927981/Lee.Margury.night.txt)

**Comment by chummer5a** [comment]
Sorry for the long radio silence on this, did it ever crop up again? Unfortunately I don't have any specific idea for why that character's file was effectively destroyed, but I'll be building some sanity checks to ensure that saves can't overwrite a file unless they conform to the XSD and validate as XML. Should prevent this from cropping up again.
