### ISSUE TITLE
The Beasts Way

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3470]
It says in the Beasts Way, that you can additionally choose one power to get the Ways benefit from. 
This random power is not displayed in chummer

**Comment by chummer5a** [comment]
Removed in errata, I believe.

**Comment by DecklandMulqueen** [comment]
If confirmed, this would be okay

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Dienstag, 5. März 2019 12:42
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] The Beasts Way (#3470)

 

Removed in errata, I believe.

**Comment by chummer5a** [comment]
P. 177, THE BEAST’S WAY POWER LIST CHANGE
The last sentence, stating that Beast’s Way adepts can choose one additional power, should be removed.

https://www.shadowruntabletop.com/wp-content/uploads/Downloads/E-CAT27003E_SG-Errata.pdf
