### ISSUE TITLE
Crash when opening Options with language created with Translator

### ISSUE THREAD

**Issue by Klajan** [chummer5a/chummer5a#3471]
### Environment
Crash ID: eeb4d27a-414f-47ca-9215-5ad65c27526b
Chummer Version: 5.204.71
Environment: Windows 10 Education
Runtime: 4.0.30319.42000

### Expected behaviour
Options are accesible without crash

### Actual behaviour
Chummer crashes when opening options

### Steps to reproduce the behaviour
Change language to own language file, save options, restart Chummer and try to open options.

###Additional Information
The language file doesn't actualy translate anything, it's merely used to change the page numbers of some rulebooks.

[lang.zip](https://github.com/chummer5a/chummer5a/files/2933495/lang.zip)

**Comment by DelnarErsike** [comment]
I was able to load the language files no problem with the latest dev build. Could you confirm that the problem is still present in the latest nightly build?
