### ISSUE TITLE
Crash: Cannot add a Weapon to an antromorph drone (holding it in its hands)

### ISSUE THREAD

**Issue by programgoblin** [chummer5a/chummer5a#3472]
### Environment
Crash ID: d04dbb1b-3199-4be9-9523-3d986a7ad2f2
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Adding a Weapon in some way to an antromorph drone is possible

### Actual behaviour
Adding a Weapon seams only be possible on a drone arm
Doing this will kill the program

### Steps to reproduce the behaviour
- Add an antromorph drone (i.e. Executive Secretary)
- Add a Weapon via right click menu  to one of the drone arms
--> Crash

- Seams to break in any stage (creation or career)

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/6232dec525be0ab4cdb1756abdf601c4af6270f4

**Comment by programgoblin** [comment]
Checked and confirmed fixed for me with 5.208.0
