### ISSUE TITLE
Crow not available in animals from Howling Shadows

### ISSUE THREAD

**Issue by adzling** [chummer5a/chummer5a#3475]
**Describe the bug**
Crow (in Howling Shadows) is not available as a "pet" in the animals section under gear.

Even if there is no cost to be applied from missions errata it should be available as a pet somehow.

**Comment by OLStefan** [comment]
That's was custom/amend files are for.

Just copy the appended file in the customdata folder in your chummer directory and activate the custom rule. I used the dog's cost/availability for the crow.

[Amend Crow.zip](https://github.com/chummer5a/chummer5a/files/2962249/Amend.Crow.zip)

**Comment by adzling** [comment]
nice one thanks


    On Wednesday, March 13, 2019, 8:43:23 AM PDT, Stefan Niewerth <notifications@github.com> wrote:  
 
 
That's was custom/amend files are for.

Just copy the appended file in the customdata folder in your chummer directory and activate the custom rule. I used the dog's cost/availability for the crow.

Amend Crow.zip
