### ISSUE TITLE
Wiki update for custom datafiles with examples.

### ISSUE THREAD

**Issue by Haplo164** [chummer5a/chummer5a#3479]
I would like some more information on custom data files, I've been able to work out some things with the stuff that comes default in the custom data directory but some things I've been unable to figure out.
Specifically I've been trying to add a custom armor. I was able to add it to the main armor file and It works but when I created a custom_armor.xml It didn't work. I was able to make an amend_weapons to add a weapon mod but amend_armor did not work for me for some reason. If I can get some help learning the details on custom files Ill be happy to update the wiki and make some examples and or templates.
[custom_armor.zip](https://github.com/chummer5a/chummer5a/files/2949205/custom_armor.zip)
[amend_weapons.zip](https://github.com/chummer5a/chummer5a/files/2949207/amend_weapons.zip)

**Comment by chummer5a** [comment]
File looks fine, it should have loaded. Pretty much all our wiki content was ported from http://chummergen.com/chummer/wiki/Data-File-Overview.ashx with changes according to our updated data schema. If you open the appropriate XSD file you'll see a moderately complicated set of rules governing how they're allowed to look.

**Comment by Haplo164** [comment]
I validated it with with the XSD file, If you could point out where in the code it parses the custom data I may be able to find what I need. I'm having a hard time finding it as reading through github is not fun and visual studio has been updating for a while. The documentation is lacking quite a bit judging from the stock custom data files, like amendoperation="addnode" and the amend file prefix.

**Comment by chummer5a** [comment]
The amend system isn't currently documented, I think @DelnarErsike had some doco lying around but most of the amend content was a bit hand-to-mouth for our specific purposes.

From the changelog we have this:

- Added support to the Amend system to be able to use operations other than the default ones. The four currently supported operations are "recurse" (perform amending recursively on children), "replace" (completely replace the target node's InnerXml), "append" (add to the target node's InnerXml), and "remove" (remove the target node). If no operation is specified, "recurse" is the default if the target node(s) have children and "replace" is the default if they do not. The 'remove="yes"' system for marking nodes for removal has been replaced by 'amendoperation="remove"'.

**Comment by Haplo164** [comment]
I found some stuff in clsXmlManager.cs the amend stuff starts around line 643. I'm going to look through the xml stuff and see what I can turn up, If I figure anything out I'll see about documenting it.
