### ISSUE TITLE
Life Modules General Issues

### ISSUE THREAD

**Issue by PinkMawile** [chummer5a/chummer5a#348]
Using Life Modules, with Ork selected as the Metatype

If NAN -> Algonkian-Manitou Council is selected, the following errors happen

1. The languages are blank, rather than being listed as language Region
2. Knowledge UCAS is being given, instead of Knowledge NAN
3. Outdoor Skillgroup is not given at +1 Rating
4. Perception, Blades, and Unarmed Combat are not given at +1 Rating

If NAN -> Athabaskan Council is selected the following errors happen

1. Langauges are blank, despite the only choices being Eskimo-Aluet as N and English as a rating 1
2. Survival doesn't get +1 rating

If NAN -> Trans-Polar Aluet Nation is selected, skills are not appropriate

1. The langauge English should be given at rank 1, not at N.
2. Knowledge UCAS is being given, instead of Knowledge NAN
3. Exotic Melee Weapon (Harpoon) is not given at +2 rating
4. Perception and Survival are not given at +1 rating

Isolated Rural Upbringing is both a Formative Years Module and a Teen Module. Under teen modules however it is listed twice, and if the Teen module is taken and "Only show Life Modules I can Take" is ticked, then the modules shown for your next module are still Teen year.
![two isolateds](https://cloud.githubusercontent.com/assets/13724499/9295945/f0febdbc-4433-11e5-824e-8294a94e7564.png)
![isolated isolated](https://cloud.githubusercontent.com/assets/13724499/9295946/f0fecbd6-4433-11e5-8fc6-d6795832622a.png)

**Comment by joha4270** [comment]
Just about everything mentioned here is fixed in the development version.
