### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by mordred9971** [chummer5a/chummer5a#3480]
### Environment
Crash ID: 8acdd16e-30ad-4da2-96af-d01c36056528
Chummer Version: 5.204.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Need some more details, but there's a new milestone release available, you might find your issue is resolved by updating?
