### ISSUE TITLE
Garage from German Data Changes - Garage Capacity can only be added once

### ISSUE THREAD

**Issue by Klajan** [chummer5a/chummer5a#3483]
**Describe the bug**
For the optional rule "German Data Changes - Garage Capacity" it should be possible to select the garage quality multiple times for a lifestyle, but this isn't possible.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 5.205.0

**Additional context**
It looks like \<allowmultiple /> is missing from the qualities.

**Comment by Klajan** [comment]
Also doesn't hide the original (English) garage qualities.

**Comment by Ramesch** [comment]
Adding 'allowmultiple' should work after merging https://github.com/chummer5a/chummer5a/pull/3492.

But hide-tag for regular garages is already written in 'German Data Changes - Garage Capacity'-rule and does not work as expected. Has anyone an idea how to hide garages '... (Body 4 or Less)' and '... (Body 5 or More)' when selecting this custom rule?

**Comment by Ramesch** [comment]
I added '<qualities>' and 'amendopertion="append"' to hide-tag and now everything should work as expected when activating this custom rule.

**Comment by Ramesch** [comment]
If this isn‘t still fixed, please give me a hint, what is missing / to do. Otherwise this could ne closed as solved.
