### ISSUE TITLE
Skill Tab visuals

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3484]
**Describe the bug**
Not a functional error, just a visual one. Sometimes the "headings" for the skill groups are in the wrong place. (Skill Groups, Points, Karma)

**To Reproduce**
1. Open Chummer in a small window (say double the width of the character rooster)
2. Create a Non-magic character. (headings align for awakened for some reason)
3. Go to the skill tab.
4. Look at the heading above the skill groups. (I see half an S, beginnings of a P, Karma, then half a p and an s (the ending of "groups")

The Points and the Karma columns have also moved to the right.

**Expected behavior**
Expectation would be for the headings to be aligned with their columns.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version  5.205.00 (and earlier)

**Additional context**
As always, thank you for a wonderful character generator.

P.S. Sometimes the skill groups Acting, Biotech and Engineering don't have a "Points" box, just the karma box. Haven't been able to reproduce this bug reliably yet and don't know if these are related. Seen it on 5.205 and earlier versions too. I think it's always those three groups.

**Comment by Ramesch** [comment]
Is it the same like described in https://github.com/chummer5a/chummer5a/issues/3001 ?

**Comment by drakir75** [comment]
Yes, exactly. Sorry for a duplicate, but it's still there.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by chummer5a** [comment]
Caused by skills tab loading before skill groups are generated in create mode. Unable to replicate following first load.
