### ISSUE TITLE
Add string for 'Enable Plugins (experimental)'

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3486]
**Describe the bug**
String for translation of 'Enable Plugins (experimental)' is missing. So this string can not be translated.

**Expected behavior**
Even if it is experimental, it would be nice if a string variable for translating 'Enable Plugins (experimental)' would be available.

**Screenshots**
![plugins](https://user-images.githubusercontent.com/43168497/54153619-57043500-4440-11e9-93ab-fa2b3c4544d2.png)

**Desktop:**
 - OS: Windows 10
 - Version 5.205.0

**Comment by ArchonMegalon** [comment]
Well, that opens a whole new front, which is the localization of plugins. Anyone has an idea how to do that easily? I never bothered with it to be honest.

**Comment by Ramesch** [comment]
I don't know how to do this in your new plugins, but at least for 'Enable PlugIns (experimental)'-string it should be the same way as the other strings in options-dialog? Sorry, if that's a stupid idea … but I have no idea how to program this.
