### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by jacx7** [chummer5a/chummer5a#3489]
### Environment
Crash ID: a511d553-9355-4e48-ba79-5633bd5c9998
Chummer Version: 5.205.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
New Character is created.

### Actual behaviour
Chummer crashes, after restart character is not created.

### Steps to reproduce the behaviour
1. Activate Sinners Plugin
2. Restart Chummer
3. Create new Character, choose settings, choose priorities
4. Create > Crash

**Comment by ArchonMegalon** [comment]
Already fixed this in the current nightly 5.205.1. #3487
