### ISSUE TITLE
Metagenic qualities being counted in Pos/Neg qualities after a save and load

### ISSUE THREAD

**Issue by SydneySedai** [chummer5a/chummer5a#349]
Not sure what causes it unfortunately, but I believe part of the issue involves saving without writing some information.
I looked into my save data and there was the same `<metagenetic />` for both Distinctive Style and Prehensile Tail; I assume there's supposed to be `<metagenetic>True</metagenetic>` or similar on the metagenetic ones that tell the program to skip its karma on load.

For now I got around the issue by just making all my metagenetic qualities cost 0, but nyeh. Bugs are bugs.

**Comment by chummer5a** [comment]
Fixed in 5.173.
