### ISSUE TITLE
Custom Active Skills

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3490]
**Is your feature request related to a problem? Please describe.**

Page 147 talks about adding custom active skills with game master approval, but chummer does not support adding custom active skills other than exotic ranged, exotic melee, and exotic vehicle.

**Describe the solution you'd like**

The button to add an exotic skill should have another option in its dropdown to simply add an Active skill. This simply creates a new skill with the appropriate name, and allows specializations.

**Comment by chummer5a** [comment]
Our general preference for custom content is to use custom files; exotics are an exception to this as they are required to work differently by definition. #2501 would feed into this as a way to make it easier to make custom files.

**Comment by chummer5a** [comment]
Doable with existing code via amend system.
