### ISSUE TITLE
Bioware Upgrade - Crash On Grade Selection

### ISSUE THREAD

**Issue by mrjester888** [chummer5a/chummer5a#3493]
**Describe the bug**
Career mode:  During bioware upgrade, selecting grade causes crash

**To Reproduce**
Career mode.
Select a bioware.  I chose Bone Density Augmentation r2
Set to upgrade.
Adjust sell price to 100% (doesn't matter what you adjust it to)
Select Alphaware from Grade drop down.  

**Expected behavior**
Set grade of "Upgraded Bioware" to Alphaware

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.205.0 and .2

**Additional context**
Automatic crash reporting failed.  

[exception.txt](https://github.com/chummer5a/chummer5a/files/2964196/exception.txt)
[userstory.txt](https://github.com/chummer5a/chummer5a/files/2964197/userstory.txt)
[attributes.txt](https://github.com/chummer5a/chummer5a/files/2964202/attributes.txt)
[Grongor-career.chum5.txt](https://github.com/chummer5a/chummer5a/files/2964200/Grongor-career.chum5.txt)

**Comment by mrjester888** [comment]
Just updated to 205.6.  The upgrade works now, but the UI didn't update the rating of the entry.

**Comment by chummer5a** [comment]
Yeah, I need to poke that a bit still; the treeviews are kinda picky about when they update.

**Comment by chummer5a** [comment]
Should be good in current builds.
