### ISSUE TITLE
No info is displayed on the printed character sheet

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#3500]
**Describe the bug**

No info is displayed on the printed character sheet.

**To Reproduce**

1.) Open the file below using chummer:
https://drive.google.com/open?id=1Ppo1XAusyLMdfrDV5b_xR5gDMb4B6eL8

2.) Try to print a character sheet using the print button. The character sheet is completely blank with no info or formatting.

**Expected behavior**

The character sheet should be full of info.

**Character File**

https://drive.google.com/open?id=1Ppo1XAusyLMdfrDV5b_xR5gDMb4B6eL8

**Desktop (please complete the following information):**
-Windows 10
-5.205.4

**Comment by DelnarErsike** [comment]
Was unable to replicate this issue in the latest dev build. Could you confirm that the issue is still present in the latest nightly build?
