### ISSUE TITLE
Trying to open new plug-ins tab after update to 205.6

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3501]
### Environment
Crash ID: 11f6f0ec-42d0-45bf-92f9-e60e4e1e642f
Chummer Version: 5.205.6
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Tab opens

### Actual behaviour
Crash

### Steps to reproduce the behaviour
hit plug-ins tab in options

**Comment by SeanPGorman** [comment]
[exception.txt](https://github.com/chummer5a/chummer5a/files/2975497/exception.txt)
[attributes.txt](https://github.com/chummer5a/chummer5a/files/2975499/attributes.txt)

**Comment by SeanPGorman** [comment]
will not accept the dmp file

**Comment by ArchonMegalon** [comment]
Hi! Will try to take a look at it tomorrow altough i'm not at home right now. Should be not so hard to miss to at least get the next nightly to work again. Currently I can only discourage you guys from using it in nightly, because it's a huge .... mess (under construction).

**Comment by ArchonMegalon** [comment]
Seems like the website will shout down for a couple of days because I hit my spending limit. Also an interesting experience. Next month I will try to tweak some settings earlier (and disable some other), so that I can sustain it with my given quota for the whole month. :(

**Comment by ArchonMegalon** [comment]
Hopefully also fixed with  #3504 - should work in the next nightly.
