### ISSUE TITLE
Metasapients should not be able to choose technomancers

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3506]
**Describe the bug**
As title: metasapients are inherently magical, with a MAG value (even if 0), and thus cannot emerge and become a technomancer. However Chummer5 allows metasapients to choose technomancy, thus allowing characters with both MAG and RES attributes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by Zitchas** [comment]
As a GM, I enjoy the opportunity to create diverse opponents, including ones that by RAW shouldn't be able to exist, so I like having this option, and have used it. That being said, I think you're right that it shouldn't be allowed by default. (Allowed via option or houserule would be great, though)

**Comment by aga9** [comment]
Personally, I agree with you 100% and support an optional rule for this. But as it stands, it's just wrong.
Even if there is an optional rule to allow metasapient technomancers, having RES should still disable MAG. It's rather fundamental to SR lore that awakening and emergence are mutually exclusive.

**Comment by SeanPGorman** [comment]
I think that it is for this reason that you can check the box "Ignore Character Creation Rules" when you create the character.

I certainly use the system for creating non-legal characters. I think the system exists to check the honest user who makes a mistake.

**Comment by chummer5a** [comment]
Hrm, this should be blocked by the forbidden entry <metatypecategory>Metasapients</metatypecategory>

From memory I never coded the priority selections to behave differently though; I'm assuming that's where the problem exists?

**Comment by Zitchas** [comment]
I think it should be separate from "ignore character creation rules." There's a difference between allowing one specific situation and throwing out the whole ruleset.
