### ISSUE TITLE
German Translation of Complex Forms

### ISSUE THREAD

**Issue by espth** [chummer5a/chummer5a#351]
The German Translation of Complex Forms is present in dialog for choosing new Forms, but in the character the English terms are used.
Easy to see with Infusion of [Matrix Attribute] - [Matrix Attribut]-Steigerung
![screenshot_2015-08-20_11-49-03](https://cloud.githubusercontent.com/assets/13884809/9380686/31147e7c-4732-11e5-9e34-f42b401eea41.png)

**Comment by chummer5a** [comment]
Treeview doesn't try to find the translated name.

**Comment by chummer5a** [comment]
Fixed in 5.175.
