### ISSUE TITLE
'collapse all' and/or 'open collapsed' option for expandable/collapsible menus

### ISSUE THREAD

**Issue by rrechtin** [chummer5a/chummer5a#3511]
Playing a drone rigger with a horde of drones, there is a lot of opportunity for improvement.  In particular, once everything has been entered, I have what feels like miles of expanded drone information under "selected vehicles" in the expandable menu, and manually collapsing 30+ items is time consuming and frustrating.

It would be great to have a 'collapse all' option.  Alternatively, a toggle-able option to start things collapsed would be great as well.

![image](https://user-images.githubusercontent.com/1199587/54649356-3c554000-4a80-11e9-8479-3f4b4216aea2.png)

**Comment by chummer5a** [comment]
Control-clicking on the root Selected Vehicles node should collapse everything below that level.

**Comment by rrechtin** [comment]
ah, i see.

that is very handy.  I don't find it intuitive but it gets the job done.  thanks!

**Comment by chummer5a** [comment]
I can finagle something better, did you have something particular in mind?

**Comment by rrechtin** [comment]
I would have expected to find either an entry in the right-click menu for expand all/collapse all or buttons at the top (or bottom) for expand all/collapse all - those were the first two places I looked for this function, and ctrl-click had never crossed my mind.

I realize it is a matter of personal preference; ctrl-click is not in my internal list of 'common ways to make an interface behave the way i expect'. now that i know that's a thing for chummer I can train myself to it for this particular application and it won't be a big deal.

**Comment by SeanPGorman** [comment]
Can you separate by type? All my bikes, truck and drones?
A
A1
A2
A3
B
B1
B2
B3
C
C1
C2
C3

compresses down to
A
B
C

Make sense?

**Comment by Lochabar** [comment]
How about consistency across tabs - the relationships tab has the "Expand/Collapse All" button.
