### ISSUE TITLE
In Skills, changing base attribute does nothing (career mode)

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3515]
This is exactly the same issue as this one: https://github.com/chummer5a/chummer5a/issues/3246

The issue was "closed" for 5.203. But it still persists in 5.205.

**Describe the bug**
In Career mode, you can change the base attribute for skills. But doing this has no effects.

**To Reproduce**
1. Open file in Career mode.
2. Go to Skills tab.
3. Select any skill and change the associated attribute.
4. The dice pool is not affected.

**Expected behavior**
The dice pool should change to reflect the selected attribute.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 5.205

**Comment by Jordan-Sanderson** [comment]
I'm seeing SwapSkillAttribute for things like EMPATHIC LISTENER.  On 5.205 as well

**Comment by drakir75** [comment]
Still does not work fully. Changes are not saved and will not show on printed sheet. I'm on 5.205.13
