### ISSUE TITLE
Some skill group points boxes gone

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3516]
**Describe the bug**
The box for group skill points in Acting, Biotech and Engineering are gone.

**To Reproduce**
Unfortunately haven't been able to reliably reproduce, but have seen it multiple times, both on 5.205 and earlier versions. It's always those three skill groups. Never fewer or more or different ones.

May have something in common with issue #3484 (#3001), but not sure.

**Expected behavior**
To always have all the boxes.

**Screenshots**
https://drive.google.com/open?id=1pU7maC3VZ51Dz8nsTxY5bFQUvFuUwvCt

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205.24 and earlier. (At least 5.205.0 and 5.204.x)

**Comment by chummer5a** [comment]
Yeah, not sure what the deal is with it. Someting to do with how skills are painted.
