### ISSUE TITLE
Foot Blade (Hard Targets 185) is missing

### ISSUE THREAD

**Issue by Maikk2** [chummer5a/chummer5a#3519]
**Describe the bug**
The Foot Blade Cyberweapon found on page 185 of Hard Targets is missing in the Add Cyberware dialoge.

**To Reproduce**
1. Go to Cyberware and Bioware
2. Click on Add Cyberware, Uncheck "Hide Items Over Avail Limit"
3. Scroll down to "F"
4. The Foot Blade is nowhere to be found

**Expected behavior**
Being able to add the Foot Blade cyberweapon.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205.12

**Comment by ResonantGhost** [comment]
Foot blade is present in the weapons section, but not the cyberware section. I attempted to check in a change for this, but must have done something wrong. When I have more time, I will try to figure out what.

The changes I made were to insert the below starting on line 7666 of cyberware.xml. I am not sure if the limit should be False or {leg}.
    <cyberware>
      <id>f05492b3-de9b-44c3-8622-89840587cc3a</id>
      <name>Foot Blade</name>
      <limit>False</limit>
      <category>Cyber Implant Weapon</category>
      <ess>0.2</ess>
      <capacity>0</capacity>
      <avail>20F</avail>
      <cost>28000</cost>
      <source>HT</source>
      <page>185</page>
      <addweapon>Foot Blade</addweapon>
      <allowsubsystems>
        <category>Cyber Implant Weapon Accessory</category>
      </allowsubsystems>
    </cyberware>
