### ISSUE TITLE
Karma & NuYen Tab causes crash when character has 0 Karma (Wine)

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3523]
**Describe the bug**
This only happens on my end, which may be related to the fact that I am running Chummer using a Wine program. 

**To Reproduce**

I reproduce this problem reliably by attempting to view the karma and nuyen tab on any character who currently has exactly 0 karma. If someone else loads the character, it seems to work fine. If additional karma is granted to the character, it works fine on my end. But if the character reaches 0 karma, the karma and nuyen tab will crash when I open the tab.

**Screenshots**

This pops up upon the crash:

![Screen_Shot_2019-03-23_at_9 15 21_PM](https://user-images.githubusercontent.com/1766631/54884590-31a7fb80-4e30-11e9-877e-d1fb576cf9de.png)

And I also get this:

[backtrace.txt](https://github.com/chummer5a/chummer5a/files/3000757/backtrace.txt)

**Character File**

Here is a small collection of affected characters, although it seems to happen with any character I attempt this with.

[Affected Characters.zip](https://github.com/chummer5a/chummer5a/files/3000765/Affected.Characters.zip)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Wine Version: Crossover 18.5
 - Bottle: Windows 7
 - Chummer Version 5.205.0

**Additional context**

Having spoken to A-r-c-h-o-n and played around with things on my end, we collectively determined the following:

* The issue only seems to happen when my character is loaded with 0 karma. 
* It's an out of memory exception that happens, when the graphic, that represents the karma remaining is drawn (probably).
* It is actually possible for me to open the .chum5 file in a text editor and grant myself 1 more carma by editing the field there, but if the character hits 0 karma again it will cause another crash.

**Comment by ArchonMegalon** [comment]
Hi @Teksura !

Can you try to download this zip, extract it, run it and try to load one of the files that previously crashed?

https://www.amazon.de/clouddrive/share/n00LvnuBswr4od1mZ8wgMc8dA5V2JcWmuzrOVT3RoJ0

Thanks!

**Comment by Teksura** [comment]
> Hi @Teksura !
> 
> Can you try to download this zip, extract it, run it and try to load one of the files that previously crashed?
> 
> https://www.amazon.de/clouddrive/share/n00LvnuBswr4od1mZ8wgMc8dA5V2JcWmuzrOVT3RoJ0
> 
> Thanks!

I've done this annnnnnnd what next? 


[backtrace.txt](https://github.com/chummer5a/chummer5a/files/3006371/backtrace.txt)

I got this when it crashed, but I'm not sure if that's what you wanted.

**Comment by chummer5a** [comment]
Might be related to #3442?
