### ISSUE TITLE
Empty List of Mentor Spirits

### ISSUE THREAD

**Issue by caelian** [chummer5a/chummer5a#3528]
**Describe the bug**
When trying to add the quality "Mentor Spirit" to an awakened character (tried with adept, magician, and mystic adept), the presented dialog to select the actual mentor spirit contains no actual mentor spirits to choose from.

**To Reproduce**
1. Create new character
2. Add one of Quality "Adept", "Magician" or "Mystic Adept"
3. Add Quality "Mentor Spirit"
4. A dialog window prompts you to select the mentor spirit, but there are no options present.
**Expected behavior**
The dialog window should contain a list of available mentor spirits to choose from.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.205.13

**Comment by Ramesch** [comment]
This was my fault / last commit. With merging https://github.com/chummer5a/chummer5a/pull/3517 this should be fixed

Sorry!!
