### ISSUE TITLE
Issue: - Application crashes and cannot open after update

### ISSUE THREAD

**Issue by ResonantGhost** [chummer5a/chummer5a#3529]
### Environment
Crash ID: 62aacc3a-d2ab-4a32-b799-88a987c68338
Chummer Version: 5.205.15
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Application reopens or at least opens after update

### Actual behaviour
Application crashes and cannot be opened.

### Steps to reproduce the behaviour
Updated from 5.205.13 to 5.205.15.
Selected yes to restart.

**Comment by ResonantGhost** [comment]
I thought more information about the crash would be attached. Message is that Access to the path  'D:\Downloads\Chummer.Nightly\customdata\Delnar Skills Remake\amend_mentors.xml.old' is denied.

I attempted to delete the specified file and access was denied. I was able to open the application by copying the folder and opening the application from the copy.

I downloaded Process Explorer from Microsoft and was able to isolate the process locking the file. It was explorer.exe. Killing the process and rerunning it allowed me to open Chummer from the folder.

I was tempted to close the issue as a Windows issue, but I was not browsing the folder or the file at the time of the upgrade.

**Comment by DelnarErsike** [comment]
I think you are correct in that this was a Windows issue, so I am closing the issue for now. Please re-open it if you encounter the problem again.
