### ISSUE TITLE
Full Body Armor: Helmets can't accept mods right now

### ISSUE THREAD

**Issue by theRubyUnicorn** [chummer5a/chummer5a#3531]
**Is your feature request related to a problem? Please describe.**
As someone who uses Full Body Armor, It was a let-down when I saw that the helmet does not allow for plugins to be added to it.

**Describe the solution you'd like**
Allow Mods on the helmet.

**Describe alternatives you've considered**
Allow buying the helmet separately.

**Additional context**
I don't think there is much more context needed, I want to softweave my helmet and put addons in it, like some vision mags and such.

**Comment by chummer5a** [comment]
Helmet doesn't have any capacity for armour mods, only vision/audio modifications.

**Comment by theRubyUnicorn** [comment]
Huh, just checked the book, and you are indeed correct. In that case, I'd like to request a houserule that makes the helm behave the same way regular helmets do, as that's how my table handles it.

**Comment by chummer5a** [comment]
Helmet can't be bought as a separate item as it's +Avail.
Allowing it to have mods requires additions to the ArmorMod class.
