### ISSUE TITLE
Vehicle modification causes change in legality

### ISSUE THREAD

**Issue by derDomino** [chummer5a/chummer5a#3533]
**Describe the bug**
Adding a forbidden modification to a restricted vehicle makes the whole vehicle be forbidden.

**To Reproduce**
1. Start creating a new character.
2. Add a restricted vehicle (Yamaha Nodachi (12R) in my case)
3. Add forbidden modification to the vehicle (e.g. Spoofing Plates(8F))
4. Select the vehicle. It now has 12F as its availability

**Expected behavior**
The vehicle's availability should stay the same as it was without the modification.

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - Version 5.204.0.0

**Additional context**
Is this behaviour intended due to a rule I am unaware of or a bug?

**Comment by chummer5a** [comment]
Honestly not sure; it's been in the changelog since 4e era, so most likely legacy code that's been allowed to propagate.

**Comment by drakir75** [comment]
Same for other equipment like weapons, armor and cybernetics. Otoh, seems fair to me. If something has illegal mods, the thing is illegal. Nothing strange about that.

**Comment by ArchonMegalon** [comment]
I actually thought this is a feature. Seems legit to me to. If I mount a Gattling Gun on my bike, I'm sure police would object me taking a ride with it.

**Comment by chummer5a** [comment]
/shrug Let's call it a feature then and bolt in an optional rule to disable it. It's not hard to do, just the bool flag and a wrapper around the child item check.
