### ISSUE TITLE
Reworked German Charakter Sheet

### ISSUE THREAD

**Issue by Demonshooter** [chummer5a/chummer5a#354]
I already left this in the /chummer5 thread

I did some work on the german print sheet but did never work with github before. How can i add it to the Repository?
Changelog:
1. Cleaned up Attributes
     i) seperated initive and special like the english sheets
     ii) Removed rigger iniative (since it is equal to normal init or cold/hot sim)
     iii) removed Matrix AR since it is equal to normal
     iv) spilted and renamed Matix Cold and Matrix hot to Cold Sim and Hot Sim
2. Contacts now equal the english one. (copied and translated)
3. Comlink now equal the english one. (copied and translated)
4. Vehicle now equal the english one. (copied and translated)

Here is a link to the new file:
https://gist.github.com/8cbb6a6b7536fb455cb3.git

Greetings Demonshooter

P.S.: Maybe we should change the Iniative in the English one too. If there are any more changes needed for the german print sheet pm me please.

**Comment by joha4270** [comment]
file gives me a 404

**Comment by Tom-0169** [comment]
Hey, found it on gist:
https://gist.github.com/Demonshooter/8cbb6a6b7536fb455cb3

**Comment by chummer5a** [comment]
Aha, cheers!
