### ISSUE TITLE
Translation for tips not available

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3540]
**Describe the bug**
Translator does not work for tips.xml (also see https://github.com/chummer5a/chummer5a/pull/3539 )

**To Reproduce**
1. Go to 'Translator'
2. Select 'German / de-de'
3. See error

**Expected behavior**
Availability to translate strings from tips.xml

**Screenshots**
![translation](https://user-images.githubusercontent.com/43168497/55376192-9689e280-550f-11e9-81d4-c4ab7a0866ec.png)

**Desktop:**
 - OS: Windows 10
 - Version 5.205.22

**Comment by Ramesch** [comment]
Hi, translation for tips.xml still doesn't work. With the function 'Verify Data File' all tips are still shown as not translated (see screenshot of 'results_de-de.xml).

Can this request be opened again or should I create a new one?

![tips](https://user-images.githubusercontent.com/43168497/61579783-dea63280-ab09-11e9-934a-83c0c3556dc2.png)

**Comment by DelnarErsike** [comment]
It's technically a separate issue (it's an issue with the Verify Data function as opposed to the loading of translations and the Translator tool functionality), but I've solved it in the latest commit (commit 301e5646f26923a234ba063c0fe034d5afa66f72).
