### ISSUE TITLE
Disabling Easter Egg causes Program Crash on Character Load

### ISSUE THREAD

**Issue by LeonardoDeQuirm** [chummer5a/chummer5a#3541]
### Environment
Crash ID: 4769aa01-f269-46c9-a50a-0dfa3c90f299
Chummer Version: 5.205.23
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Open character from character list

### Actual behaviour
Program crashes

### Steps to reproduce the behaviour
Turn off Easter Eggs, Restart Chummer, Open Chummer, select character from recent characters

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/478c3cb2428b61990b1ea1e1415b227c66f995a9
