### ISSUE TITLE
Eye rolling Snake

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3543]
Can you please remove this shit?

When the program starts, an eye rolling shadowrun snake appears .... you cannot remove it....that sucks

**Comment by Lochabar** [comment]
I agree. Features like this not be used by default. Give the user a one-time offer to start using it but do not start using if forcing the user to switch it off.

**Comment by Zitchas** [comment]
@chummer5a I thought it was amusing. I just saw this "bug" report, and updated Chummer just to see it. I'll probably turn it off fairly quickly, but it was amusing nonetheless. 

Wiz!
