### ISSUE TITLE
Mage tradition not saved

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3544]
**Describe the bug**
As title: The magic tradition for a mage is not saved. It becomes blank every time a file is loaded.

**To Reproduce**
1. Create a character.
2. Set a tradition. Save.
3. Open file again.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by chummer5a** [comment]
This should be working properly in the current nightly builds.

**Comment by theRubyUnicorn** [comment]
The slider is still cleared when loading a file, the spirit selection and drain are saved though. Minor issue, but still there.
