### ISSUE TITLE
Nuyen/Karma for packets

### ISSUE THREAD

**Issue by GMPhill** [chummer5a/chummer5a#3545]
The Nuyen Karma debt that allows you to purchase packets using nuyen only goes up to Ten. The advanced runner pack has a karma cost of 12 so there is no way to pay that off. The street samurai packet, which I can't find in any book, has a karma cost of 100. 
**To Reproduce**
1. Go to packets
2. Click on advance runner kit
3. click on nuyen karma debt
4. karma debt is only at 10 even thought it should be 12 which is even worse for the 100 cost only being 10

**Expected behavior**
The karma debt needs to exceed ten in some situations

**Comment by chummer5a** [comment]
PACKs will do their best to add nuyen from karma to cover their costs, as they were built for Point Buy/Karma generation. If you're using Priority generation, it's up to the user to choose the appropriate priority; purchasing a PACK does not let you have more karma invested into nuyen than your gameplay options setting. 

You can use the Change Priority Selection menu option to update your priority to the correct range.
