### ISSUE TITLE
Liminal Body Centaur legs interact poorly with pair-based upgrades

### ISSUE THREAD

**Issue by Dicerson** [chummer5a/chummer5a#3550]
As of 5.205 (The version I am using as I write this), Liminal Body (Centaur)'s 4 free cyberlegs do not properly interact with most pair-based leg upgrades. Notably, Skimmer and Digigrade legs. Both of these can only be added to the two "Rear" legs, however it seems fairly obvious that all 4 legs need this upgrade for them to be able to function (Since their pair-requirement is typically because most people only have 2 legs). As it stands, the only way to get around this is to add other upgrades that have the same capacity, and to buy a custom item in street gear to account for the price difference

**Comment by Silversought** [comment]
I did some searching, and it appears that Liminal Body (Centaur) is treated as being two cyberlimbs for anything being applied to the Liminal Body, like Redliner (netting only a +1 to the Liminal Body instead of a +2). I do not know if this is the reason pair-requirements are wonky though, but maybe?

**Comment by Dicerson** [comment]
Do you have a source for this? A FAQ, or Errata, or book and page number? If it's just a weird house rule or a conclusion some random guy came up with it's not exactly official XD

**Comment by chummer5a** [comment]
I think he's talking about how we handle it in code. IIRC the problem is that I didn't add an addlimb bonus to the centaur, but I never got around to testing what would happen if you did.

**Comment by Dicerson** [comment]
Hmm. I c

**Comment by Silversought** [comment]
Yeah, I was just commenting on how chummer was treating it. Couldn't find any official errata / clarification of the actual intended behavior though.

**Comment by chummer5a** [comment]
The addlimb bonus works, but has an issue if the user happens to be a centaur. I'd prefer to fix that properly before integrating the other fix, otherwise I'll forget about it.
