### ISSUE TITLE
Underbarrel weapons not listed as such

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3553]
**Describe the bug**
There are a number of underbarrel weapon add-ons that can only be added with "Add Accessory", but not "Add Underbarrel Weapon". This is pretty confusing.

Currently, only Mounted Crossbow and Underbarrel Shotgun are available via "Add Underbarrel Weapon". All other underbarrel weapons are only available via "Add Accessory".

Either all underbarrel weapons should be addable via "Add Underbarrel Weapon", or the distinction between "Accessory" and "Underbarrel Weapon" should be removed altogether.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by chummer5a** [comment]
Most of the Run and Gun stuff predates my involvement, so I'm not exceptionally surprised. Should just be a matter of removing or hiding the accessories and generating new weapon entries that have the Underbarrel Weapon category.

**Comment by cnschu** [comment]
> **Describe the bug**
> There are a number of underbarrel weapon add-ons that can only be added with "Add Accessory", but not "Add Underbarrel Weapon". This is pretty confusing.
> 
> Currently, only Mounted Crossbow and Underbarrel Shotgun are available via "Add Underbarrel Weapon". All other underbarrel weapons are only available via "Add Accessory".
> 
> Either all underbarrel weapons should be addable via "Add Underbarrel Weapon", or the distinction between "Accessory" and "Underbarrel Weapon" should be removed altogether.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Version 5.205

can you please post a list of the accessories missing in the "add underbarrel Weapon" (with rulebook reference please)?

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/commit/9b062405b1e069dbab025ed172e599b4d0d1d433 Should resolve most of it, but I haven't hidden the legacy accessories yet.
