### ISSUE TITLE
message_orphanedimprovements

### ISSUE THREAD

**Issue by jinshei** [chummer5a/chummer5a#3554]
**Describe the bug**
Opening characters causes this bug with missing skills in character file

**To Reproduce**
1. Open character file (example attached)

[Afin.zip](https://github.com/chummer5a/chummer5a/files/3051519/Afin.zip)

2. See error, including skillls

**Expected behavior**
Character file to open with details in place.

**Screenshots**

![image](https://user-images.githubusercontent.com/3616752/55683254-b23d2080-5935-11e9-9d0d-4c0e392fe626.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205.28

**Additional context**
Started to happen after upgrading the version.

**Comment by chummer5a** [comment]
[Afin.zip](https://github.com/chummer5a/chummer5a/files/3058932/Afin.zip)
That look correct? I can't see that you're missing any skills.

**Comment by jinshei** [comment]
![Capture](https://user-images.githubusercontent.com/3616752/55909980-2d703200-5bd5-11e9-841b-912bf02db2d3.PNG)
![Capture1](https://user-images.githubusercontent.com/3616752/55909981-2d703200-5bd5-11e9-8f0a-83bc40f01f23.PNG)

These are what I see when I open that file.  Probably user error but I can't see how..

**Comment by chummer5a** [comment]
Naw, it'll be me breaking stuff.

**Comment by chummer5a** [comment]
Actually, I can't see the problem. Skill groups only show their effective rank as they don't have directly linked attributes, while your skill groups are broken by having individual skills in them. What would you be expecting to see here instead?

**Comment by jinshei** [comment]
Before we saw the skill levels that were set.

**Comment by chummer5a** [comment]
More or less working as intended; since your skill group's rating is only relevant for karma costs, we figured it was better to show that you couldn't increase the group's rating than to show what the rating itself is.

**Comment by jinshei** [comment]
That makes sense. Now distinctly less worried I broke it. Thanks for
getting back to me.
