### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by azania666** [chummer5a/chummer5a#3560]
[chummer_crash_131992592352036945.txt](https://github.com/chummer5a/chummer5a/files/3057219/chummer_crash_131992592352036945.txt)
### Environment
Crash ID: 75922269-92e9-492d-a070-40ec302238cf
Chummer Version: 5.204.41
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Should be resolved in current builds.
