### ISSUE TITLE
Chummer Crash on Char Load - invalid Token

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3561]
[chummer_crash_131992581764257427.txt](https://github.com/chummer5a/chummer5a/files/3057795/chummer_crash_131992581764257427.txt)
[chummer_crash_131992612892323263.txt](https://github.com/chummer5a/chummer5a/files/3057796/chummer_crash_131992612892323263.txt)
[chummer_crash_131992622198140237.txt](https://github.com/chummer5a/chummer5a/files/3057797/chummer_crash_131992622198140237.txt)
[chummer_crash_131992705566261375.txt](https://github.com/chummer5a/chummer5a/files/3057798/chummer_crash_131992705566261375.txt)

### Environment
Crash ID: 1989ddf8-8b00-42ff-9b0d-8e8da428b8cb
Chummer Version: 5.205.30
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer loads char

### Actual behaviour
Chummer crashs on loading of Char 

### Steps to reproduce the behaviour
Tried two different chars

**Comment by chummer5a** [comment]
I'm pushing an updated build that should resolve this issue.
