### ISSUE TITLE
Exchanging Ghosts in the Traditionblock

### ISSUE THREAD

**Issue by azania666** [chummer5a/chummer5a#3563]
**Is your feature request related to a problem? Please describe.**
Exchanging Ghosts in the Traditionblock

**Describe the solution you'd like**
Could it be possible to have the possiblity to exchange ghosts in existing Traditions? 
Like using in the Streetwitches Tradition Ghosts o the beast for Comabt instead of Ghosts of Fire.

**Describe alternatives you've considered**
or have the possiblity to build an own Tradition from scratch

**Additional context**
![selectable Ghosts](https://user-images.githubusercontent.com/43959752/55787404-7d0c0c00-5ab6-11e9-84eb-95f3ee513b4b.JPG)

**Comment by chummer5a** [comment]
You should have an option to select a Custom tradition that allows you to select the spirits used for each category. There's no support for changing the spirits of a standard tradition because there's no mechanical backing for it.

**Comment by azania666** [comment]
Could you tell me what the name of the optipon is?

I could not find it.

 

Gesendet: Dienstag, 09. April 2019 um 14:17 Uhr
Von: "Chummer 5 Is Alive" <notifications@github.com>
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: azania666 <azania@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Exchanging Ghosts in the Traditionblock (#3563)


You should have an option to select a Custom tradition that allows you to select the spirits used for each category. There's no support for changing the spirits of a standard tradition because there's no mechanical backing for it.

**Comment by chummer5a** [comment]
Should be called Eigene Tradition with the German language files, otherwise it's just called Custom. 
![image](https://user-images.githubusercontent.com/11448441/55800782-d6f0ee00-5b17-11e9-812b-235eb6b625e5.png)

**Comment by azania666** [comment]
Thank you.

found it. 


Gesendet: Dienstag, 09. April 2019 um 14:36 Uhr
Von: "Chummer 5 Is Alive" <notifications@github.com>
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: azania666 <azania@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Exchanging Ghosts in the Traditionblock (#3563)


Should be called Eigene Tradition with the German language files, otherwise it's just called Custom.
