### ISSUE TITLE
Positive Qualities Disappear

### ISSUE THREAD

**Issue by David-Demma** [chummer5a/chummer5a#3567]
**Describe the bug**
Positive Qualities are replaced with the top alphabetical quality and a number.
In this case "Bilingual" covers up "College Education", "Erased", etc.
The qualities are not selectable.

**To Reproduce**
Updated to 5.205.34 but it's possibly in an earlier build too.

**Expected behavior**
To see all qualities, not just one.

**Screenshots**
![PosQualIssues](https://user-images.githubusercontent.com/12616904/55926285-55ac6080-5bd6-11e9-9c90-4c06a7d5ba16.jpg)

**Character File**
[Jinx Car.zip](https://github.com/chummer5a/chummer5a/files/3066647/Jinx.Car.zip)

**Desktop (please complete the following information):**
W10

**Additional context**
None

**Comment by chummer5a** [comment]
Ass, I thought I fixed that. Version 26 won't have that bug.

**Comment by chummer5a** [comment]
Fixed in current nightly, fixed better in the next one.
