### ISSUE TITLE
Street Scum Campaign Option - Not really an issue, more like suggestion

### ISSUE THREAD

**Issue by BetaVirus** [chummer5a/chummer5a#357]
On Page 354 of the SR5 book there is a section for alternate campaign styles. Would you be willing to add in the one for Street Scum? Here is what it looks like on the tables

![sr5 street scum - street level play](https://cloud.githubusercontent.com/assets/13993587/9513803/4da4a0ac-4c51-11e5-87b3-76fdbf52fbc3.png)

***Note***
Our tables reflect a street scum priority table, with Street level starting money as well. Please feel free to use the normal money table to reflect the normal street scum play options. 

Maybe you could make an option that shows the Street Scum play and a check box for Street level add on to reflect our chart too. we wanted a true low level start and that was the best way to do it.

Anyway thank you for your time.

~Valyn~

**Comment by joha4270** [comment]
I'm not familiar with the code for options, if it is configured with data it should be easily enough, if it is configured in code i'm afraid it is too much work right now.

Also, my SR5 p354 is about security tactics for GMs

**Comment by chummer5a** [comment]
Yeah, that's all handled in data content. Shouldn't be a problem to add.

**Comment by BetaVirus** [comment]
It is in the section for Campaigns.

My print date is 2013

**Comment by joha4270** [comment]
Ah, found it, p350 in my book

**Comment by chummer5a** [comment]
Oof. This would actually be a rather large amount of rework, now that I'm looking at it. The different attributes and skills and money aren't necessarily a problem, but the different stat selection would break the current implementation of the priority table. Quick and dirtiest method would be sum to ten.

**Comment by BetaVirus** [comment]
That sucks, but I thank you for looking in to it. The street scum tables are rather different since Table one is Choose 1 from priority B,C,D and two from E. And table 2 is pick two from Priority C and D, the 1 from E.


I was not sure if your program just pulled the info from a table or if it was programed to make the table for each set.

**Comment by joha4270** [comment]
It might be possible to create a "hack" by changing what the categories are defined as.

No difference between 2 A priorities or 1 A, 1 B with the same contents

**Comment by BetaVirus** [comment]
If  I had even the smallest understanding of code and scripting I would try, but my strengths are in a different field all together. :-(

**Comment by joha4270** [comment]
I'm going to look at it later tomorow, i think i can do this somewhat painlessly

**Comment by BetaVirus** [comment]
Cheers! Both for looking in to it.

**Comment by chummer5a** [comment]
I've just added some code support for doing this. I reeeeally don't want to do the data entry though; if you still need this, let me know and I'll show you what you need to do. Otherwise it can sit in the backlog for a while longer.

**Comment by BetaVirus** [comment]
I am happy to do a little manual work, just tell me what i need to do.

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 9, 2016 at 7:11, Chummer 5 Is Alive<notifications@github.com> wrote:   
I've just added some code support for doing this. I reeeeally don't want to do the data entry though; if you still need this, let me know and I'll show you what you need to do. Otherwise it can sit in the backlog for a while longer.

**Comment by chummer5a** [comment]
Excellent! This should be pretty easy actually; you basically just need to copy existing nodes, change their values to whatever you need them to be, and add <gameplayoption>Street Scum</gameplayoption>. So taking the A Ranked Attributes as an example:
```
		<priority>
			<id>1c4a7955-1ae1-4a5b-9ed4-5ab8525d13b0</id>
			<name>A - 24 Attributes</name>
			<value>A,4</value>
			<category>Attributes</category>
			<attributes>24</attributes>
		</priority>
```
Would become 

```
		<priority>
			<id></id>
			<name>A - 20 Attributes</name>
			<value>A,4</value>
			<gameplayoption>Street Scum</gameplayoption>
			<category>Attributes</category>
			<attributes>20</attributes>
		</priority>
```

IDs need to be unique but I can handle doing that, so just delete what's in there and leave the node empty. Make sense?

**Comment by BetaVirus** [comment]
I am sorry for the lack of feed back, I am currently without a work Pc and Have been since March, also our SR start seems to be on hold.

Either way, I just wanted to say thank you for the info. I will try to work on this when I get a working computer and we start working on the campaign again.

**Comment by BetaVirus** [comment]
Hi guys, I have been following your updates and saw that you added added the street scum and street level. Thank you. My GM has is now a full doctor and working on getting the SR5 campaign going soon. So, it is now time for me to get back to being the co-GM for helping with character gen.

Only thing is the priority tables for the Street Level shows the normal table when selecting, and you cant choose between the two table options.

Am I not selecting the right options? Do I still need to use the Sum to 10; or make the edits you mentioned before?
***Also the the newest Chummer5 seems to be 5.191.27 but if I check for updates it show one for 192. It just crashes saying the html file is in use. I am guessing that is because the app is running and it can not close the tool without closing the update, so it just crashes. Not a big deal for me.

**Comment by chummer5a** [comment]
No? Just select the Gameplay Option you want to use, then select your priorities as normal. 
![image](https://cloud.githubusercontent.com/assets/11448441/23831724/2efdb81e-077b-11e7-9f34-bda4b09f027d.png)

As far as the options go, the changelog.txt shows the most current version of changelog.txt, which includes changes from the nightly builds. Release builds are naturally behind by several versions, but I haven't bothered to code the update window into just showing a diff between current version and latest version.

**Comment by BetaVirus** [comment]
I did that but the priority table shows the normal values.
For Street Level: normal table but money should be less, but it is not.

For Street Scum: Priority table values should show bcdee or ccdde values, but they are normal.
If I try to select more than one to the same value it will just changes one of the others so that it is always using the abcde. I can try to send out the screen shots if you need any.

**Comment by chummer5a** [comment]
Oh, that. Yes, you'll need to use Sum to Ten for that. Priority's coding wouldn't handle BCDEE or whatever well at all. Simplest just to use Sum-to-X.

**Comment by BetaVirus** [comment]
Ok sounds good, thank you.

**Comment by BetaVirus** [comment]
So can i somehow modify the tables so that I remove the priority a from selection and change the resources section so that it has different values?

I am not sure where to look or what i would be editing.

**Comment by chummer5a** [comment]
The resources section should already have the correct values if you're using the appropriate gameplay-option choice. Removing or replacing priority options will generally cause a desync and crash out, as it's rather tightly bound to the ABCDE progression.

**Comment by BetaVirus** [comment]
Ok, well for the street scum, I am thinking that it will be possible to just change the A priority to the values of E. 
that I can make it think I am using the ABCDE but in reality I am using BCDEE. If that makes sense.

**Comment by BetaVirus** [comment]
Anyway, I am sure you are a busy person so I will not fret, I already made an excel version of the priority tables that other can use. Your tool is just infinitely better as I can setup gear and stuff quickly too.

**Comment by BetaVirus** [comment]
So, I know why I was having issues. When you said sum to 10, I left it at 10 because your tool does not have instruction on what the sum is calculating. 
As such i was always required to select a total of 10 which meant that the Street Scum BCDEE was having to be ABCDE anyway.
i needed it set as sum to 6, so that i would allow me to move on to the creation part with out needing the total to be 10. Now I can use the tool as you has said. 

If i may make a suggestion; adding tooltips to the different options would help people, who are not familiar or previous users, understand the tool better. I had no idea what the sum was or how it affecting my Char creation; so, I just took your word on how to use the tool.
