### ISSUE TITLE
Life Module Issues / Drifter

### ISSUE THREAD

**Issue by Karmarov** [chummer5a/chummer5a#3573]
Environment

Chummer Version: 5.250.0
Environment: Windows 10
Runtime: .NET ???

Expected behaviour

When selecting a "Life Module Drifter" you can choose betwean two Atributs and afterwards skills and the Moduls will get added to the char.

Actual behaviour

I can choose betwean the Stats i want to increase but nothing happens afterwards, just goes back to the stat it was before.

Start program
Create new character
Select "Life Module"
Select life module drifter
Nothing happens.

**Additional context**
Currently chummer isnt automatically creating the knowledge skills in my char as well 

**Char Data as Txt*
[Drifter Life Module Prob 13.04.2019 - Kopie.txt](https://github.com/chummer5a/chummer5a/files/3076158/Drifter.Life.Module.Prob.13.04.2019.-.Kopie.txt)

**Comment by CommissarMouse** [comment]
I am also experiencing this problem.  There seems to be a ticket for this very problem dated from June 1st 2016.
