### ISSUE TITLE
Optional Rule Suggestion: Allow modification of weapon mounts that come stock

### ISSUE THREAD

**Issue by efajigaloop** [chummer5a/chummer5a#3578]
**Is your feature request related to a problem? Please describe.**
Many vehicles and drones come with weapon mounts prepackaged. There are no extant rules for modifying them, and the functionality is not in chummer obviously. I would like options for this to be used, as many of these weapon mounts end up unusable in most situations due to being External, such as on the BMW I8 Interceptor.

**Describe the solution you'd like**
I would like an optional rule to exist allowing stock weapon mounts to be modified, and for any increased cost in nuyen and mod slots, or changes in the available weapon sizes as a result of this to be properly calculated.

**Describe alternatives you've considered**
Alternatives are simply not doing it, though another implementation option to consider would be whether downgrades to mounts would free up additional mod slots.

**Comment by chummer5a** [comment]
Duplicates #3429
