### ISSUE TITLE
Can't spend Karma on Nuyen Sum to Ten 5.205.0

### ISSUE THREAD

**Issue by IamAlphaGeek** [chummer5a/chummer5a#3580]
[demo_4-14-19.zip](https://github.com/chummer5a/chummer5a/files/3078499/demo_4-14-19.zip)

Two issues, 

first that various (non-attribute related) actions are triggering the "You cannot have more than one Attributes at their maximum during character creation" prompt, especially changing the rating of In Debt, and several instances of the prompt upon opening the file.

Second, and I think related issue is that, at least while  I have In Debt, it won't allow me to spend Karma on Nuyen. I can click the button but the value doesn't increase. Adding In Debt also removes any Karma previously put into Nuyen. 

Any ideas? I can't seem to find any rules about In Debt not letting you spend Karma on Nuyen.

**Comment by chummer5a** [comment]
> for every point of Karma (up to 15) spent to be In Debt, the character gets 5,000 nuyen to spend during character creation. These points are spent in place of the normal Karma for extra cash

I'll have to poke the attribute prompt thing a bit.

**Comment by chummer5a** [comment]
Can't replicate the attribute issue, I'd need to see a character file and a way to reproduce it.

**Comment by IamAlphaGeek** [comment]
File is in the original file
