### ISSUE TITLE
Nightly 5.206.39: Char List is empty

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3581]
**Describe the bug**
Direct after starting Chummer you get an Charlist that is completly empty
![image](https://user-images.githubusercontent.com/12108972/56112607-e16a1800-5f5b-11e9-8cfd-2058c276d7a8.png)

**To Reproduce**
1. Open Chummer

**Expected behavior**
See Charlist

It is possible to load Chars via File Menu

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 5.206.39

**Additi

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/a0b5361f8bcb30da0b268fbd7804007e791ddc52
