### ISSUE TITLE
Complex forms do not have names on sheet/inventory

### ISSUE THREAD

**Issue by Triskavanski** [chummer5a/chummer5a#3596]
When I added complex forms to a character, it would not let them show up as far as their names go.
![image](https://user-images.githubusercontent.com/12078140/56397773-6ffbc500-61fa-11e9-9aca-5e18ed6f2c23.png)

What should be there is Resonance Spike, resonance veil, primed charge and multithreading

**Comment by chummer5a** [comment]
Should be working properly in .43.
