### ISSUE TITLE
Version 205.43 crashes Mentor Spirits an Mentors Mask

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3599]
I really start to hate you. What have you done to Mentor Spirits?

When i load any of my Chars with Mentor Spirit/Mentor Mask it says:

Chummer encountered an error when loading this improvement. You can fix it, if you reapply it ...

Press "OK" and loose all your Karma and Money Gains, everything you have purchased and every Initiation and everything that has to do with Power Points ...

With 205.42 everything was fine

**Comment by chummer5a** [comment]
File please.

**Comment by DecklandMulqueen** [comment]
File is deleted…..could rework a version of februar this year …. Hab to remove mentor spirit in create mode…save and add it again with the additional addition of mentors mask…works now stable

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Freitag, 19. April 2019 15:32
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Version 205.43 crashes Mentor Spirits an Mentors Mask (#3599)

 

File please.

**Comment by ReallyDarkMatter** [comment]
[Moonlight MK.zip](https://github.com/chummer5a/chummer5a/files/3098574/Moonlight.MK.zip)

Also has the Problem with Mentor Spirit, Reapply Drops Spellcasting and Conjuring from 6 to 1

**Comment by theRubyUnicorn** [comment]
I have the same issue, no mentors mask present. The bug came up in at least .42, if not earlier. Any alteration to the sheet and then saving+loading loses karma and nuyen gains, increase in magic and spellcasting and summoning get lowered to 1. Possibly more that i haven't seen. 
[Light881.zip](https://github.com/chummer5a/chummer5a/files/3098966/Light881.zip)

**Comment by ReallyDarkMatter** [comment]
Just checked the Karma and NuYen Tab, it is completly empty no entries at all

**Comment by DecklandMulqueen** [comment]
I think the problem is as follows:
- you had to choose mentors mask, when selecting mentor spirit ... in one step
- with the separation of mentor spirit and mentors mask, you were able to select mentors mask again, gaining an additional PP in the process
- files with the old mentor spirit selection get corrupted now, regardless, whether you had selected mentors mask or not

i was able to overcome the bug by removing mentor spirit from an old saved file, saveing it and selecting mentor spirit anew

try it and tell us, if it works

**Comment by chummer5a** [comment]
[Light881_FixedXML.zip](https://github.com/chummer5a/chummer5a/files/3099752/Light881_FixedXML.zip)
[Moonlight MK_FixedXML.zip](https://github.com/chummer5a/chummer5a/files/3099757/Moonlight.MK_FixedXML.zip)
Characters had malformed XML; everything after vehicles was being saved inside the vehicles node. Investigating root cause now.

**Comment by chummer5a** [comment]
@DecklandMulqueen there might be an old copy of your character stored in Chummer\saves\autosaves.

**Comment by DecklandMulqueen** [comment]
Actually not, as i did a complete reinstall with deleting all corrupted files

 

Von: Chummer 5 Is Alive <notifications@github.com> 
Gesendet: Samstag, 20. April 2019 06:41
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Version 205.43 crashes Mentor Spirits an Mentors Mask (#3599)

 

@DecklandMulqueen <https://github.com/DecklandMulqueen>  there might be an old copy of your character stored in Chummer\saves\autosaves.
