### ISSUE TITLE
Helmets treated differently between FBA, Security, Mil-Spec

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3602]
**Describe the bug**
Full Body Armor has Helmet as an Armor Mod. But Security Armor and Mil-spec Armor helmets can only be added as standalone items.

One way or another, this should be unified.

IMO Security and Mil-spec armors should follow FBA's scheme; their helmets should be treated as armor add-ons that cannot be worn separately.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by Zitchas** [comment]
Why shouldn't they be added as standalone items? Helmets are headware that can easily be worn separately from the set they are technically a part of. I could see mil-spec as possibly being limited to only as a set, but not the others.

It would probably be better to change Full Body Armor to act like the others.

**Comment by aga9** [comment]
Because:
1. The way Full Body Armor Helmet is listed in CRB makes it comparable to mods like chem seal.
2. Chem seals require on the presence of Armor+Helmet to be in a matching pair.
3. It makes no sense to have only a helmet with Hardened Armor.

Anyway, the book isn't too clear about this so either interpretation is just an opinion. The best solution may be simply to make helmets addable as BOTH mods and standalones -- let each table decide their preference.

**Comment by chummer5a** [comment]
They're different because they behave differently. FBA helmet is +500¥; the other helmets are all independently purchased for some stupid reason. Far as I'm concerned it's working per RAW, but if someone wants to do the data entry for a customdata to switch that behaviour I'm happy to walk you through it and integrate it as customdata.

**Comment by aga9** [comment]
I'd be up for it if there's a guide to creating custom data.

**Comment by chummer5a** [comment]
So what you'd want to do is make an amend file for armor.xml. Generally the way we do this is by making a new folder in customdata with a descriptive name (Helmets are Armor Mods or whatever), and inside that you want a file called amend_armor.xml. Inside that, you want a structure like this:
`<chummer>
  <armors>
    <armor>
      <name>SWAT Helmet</name>
      <hide amendoperation="addnode" />
    </armor>
  </armors>
  <mods>
    <mod>
      <id>ca88bce5-b350-4869-b139-daa8dc5386b6</id>
      <name>SWAT Helmet</name>
      <category>General</category>
      <armor>+3</armor>
      <armorcapacity>8</armorcapacity>
      <required>
        <parentdetails>
          <name>SWAT Armor</name>
        </parentdetails>
      </required>
      <avail>10R</avail>
      <cost>1500</cost>
      <source>RG</source>
      <page>70</page>
    </mod>
  </mods>
</chummer>`

**Comment by aga9** [comment]
Here's the file, seems to work on my Chummer.
I only added the helmets as mods _without_ removing them as stand-alones -- don't see that as necessary.
One thing I'm not sure is the <id> tag. Is that just any random number? In this file I just reused IDs from the original helmets.
If this works, I'll also make another file that makes all helmets stand-alones.

[amend_armor.txt](https://github.com/chummer5a/chummer5a/files/3125810/amend_armor.txt)

**Comment by chummer5a** [comment]
The id is a Globally Unique IDentifier, or guid. When using the amend system to modify existing items, you would include either the id or the name to tell the amend what file you're editing. If you were making a new object, you'd use a new guid from www.guidgenerator.com or somesuch. I'd suggest doing it like this, as it prevents overwriting things that we might change at a later point:

```xml
<chummer>
  <armors>
    <armor>
      <name>SWAT Armor</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Hardened Mil-Spec Battle Armor: Light</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Hardened Mil-Spec Battle Armor: Medium</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Hardened Mil-Spec Battle Armor: Heavy</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Security Armor: Light</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Security Armor: Medium</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <name>Security Armor: Heavy</name>
      <addmodcategory>Full Body Armor Mods</addmodcategory>
    </armor>
    <armor>
      <id>403adcb1-0739-4b20-816f-7854005eb227</id>
      <addmodcategory>Urban Explorer Jumpsuit Accessories</addmodcategory>
    </armor>

  </armors>
  <mods>

    <mod>
      <id>8408b3e7-87ff-4b6e-bfdc-19433ba356da</id>
      <name>SWAT Armor: Helmet</name>
      <category>Full Body Armor Mods</category>
      <armor>+3</armor>
      <armorcapacity>8</armorcapacity>
      <required>
        <parentdetails>
          <name>SWAT Armor</name>
        </parentdetails>
      </required>
      <avail>10R</avail>
      <cost>1500</cost>
      <source>RG</source>
      <page>70</page>
    </mod>

    <mod>
      <id>eba04b96-c253-4fe0-8431-988d5a45d456</id>
      <name>Hardened Mil-Spec Battle Armor: Helmet</name>
      <category>Full Body Armor Mods</category>
      <armor>+3</armor>
      <armorcapacity>8</armorcapacity>
      <required>
        <parentdetails>
          <name>Hardened Mil-Spec Battle Armor</name>
        </parentdetails>
      </required>
      <avail>8F</avail>
      <cost>10000</cost>
      <source>RG</source>
      <page>66</page>
    </mod>

    <mod>
      <id>7270c272-fef6-4b93-ae78-aa4906d9dbd5</id>
      <name>Security Armor: Helmet</name>
      <category>Full Body Armor Mods</category>
      <armor>+3</armor>
      <armorcapacity>5</armorcapacity>
      <required>
        <parentdetails>
          <name>Security Armor</name>
        </parentdetails>
      </required>
      <avail>8R</avail>
      <cost>5000</cost>
      <source>RG</source>
      <page>67</page>
    </mod>

    <mod>
      <id>812a7926-3980-4c26-9935-5f1b66abacda</id>
      <name>Urban Explorer Jumpsuit: Helmet</name>
      <category>Urban Explorer Jumpsuit Accessories</category>
      <armor>+2</armor>
      <maxrating>1</maxrating>
      <armorcapacity>[0]</armorcapacity>
      <required>
        <parentdetails>
          <name>Urban Explorer Jumpsuit</name>
        </parentdetails>
      </required>
      <gearcapacity>6</gearcapacity>
      <avail>0</avail>
      <cost>100</cost>
      <source>SR5</source>
      <page>437</page>
    </mod>

    <mod>
      <id>7f7cfaaf-d28c-4cd2-b1c2-55ece741732f</id>
      <name>Urban Explorer Daedalus: Helmet</name>
      <category>Urban Explorer Jumpsuit Accessories</category>
      <armor>+2</armor>
      <armorcapacity>6</armorcapacity>
      <required>
        <parentdetails>
          <name>Urban Explorer Daedalus</name>
        </parentdetails>
      </required>
      <avail>0</avail>
      <cost>100</cost>
      <source>SL</source>
      <page>48</page>
    </mod>

  </mods>
</chummer>
```
