### ISSUE TITLE
Saving File Error

### ISSUE THREAD

**Issue by Desertcatkwh** [chummer5a/chummer5a#3603]
**Describe the bug**
Saving the file before or after edit results in a error dialog.

**To Reproduce**
1. Load File (Attached)
2. Add Karma (5) and Nuyen (15500)
3. Save file
4. See error (Attached)

**Expected behavior**
File should correctly save.

**Screenshots**
See attachments

**Character File**
See attachments

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.17763 Build 17763

**Additional context**
Tried using autosave file but that did not help.

Thanks for your help.
[Hunt error version_04192019.pdf](https://github.com/chummer5a/chummer5a/files/3099358/Hunt.error.version_04192019.pdf)
[Hunt error_04192019.pdf](https://github.com/chummer5a/chummer5a/files/3099359/Hunt.error_04192019.pdf)
[Zam3_04192019_1421.zip](https://github.com/chummer5a/chummer5a/files/3099362/Zam3_04192019_1421.zip)

**Comment by chummer5a** [comment]
@ArchonMegalon this might be one for you, looks like it's failing to upload the file.

**Comment by ArchonMegalon** [comment]
Will take a look at it on Wednesday

**Comment by Desertcatkwh** [comment]
Thanks.

**Comment by ArchonMegalon** [comment]
Ok, I have to rework ALL my WebService calls to return a ResultObject that contains some information in the case of errors like "you uploaded this sinner from another client" or "the guy who uploaded this sinner did not allow your user to edit it" and stuff like that.

Thats only partly connected to this particular error, but the whole errorhandling was more in the state of "working prototype", and now it needs to be stabilized. That will take a while, I will try to finish it today and tomorrow.

Actually I have still no idea what is happening here. I don't have a Joshua Snyder in the database. Lets try to improve the error handling and than come back to this.

**Comment by ArchonMegalon** [comment]
I have an idea. The Character is called Zamriel-2019 and I have it twice in the database. That's because of the Dictionary-Problem in frmCharacterRoster as I already mentioned in the dev-Discord. I will get rid of the dictionary and than hopefully this will resolve itself on it's own.

Still need to write the error handling dough... :/

**Comment by ArchonMegalon** [comment]
@Desertcatkwh Don't wonder, but I will take ownership of both characters in the database to debug this one.

**Comment by Desertcatkwh** [comment]
Thanks Archon. I am relieved I wasn't being a complete luser.

Chummer is an excellent program. Thanks to you and your Team.

-Kirk aka Desertcatkwh

**Comment by ArchonMegalon** [comment]
#3612
