### ISSUE TITLE
'Ware Attributes and Karma/Nuyen Issues

### ISSUE THREAD

**Issue by David-Demma** [chummer5a/chummer5a#3610]
**Describe the bug**
'Ware is not affecting Attributes (in this case Muscle Toner R3).
Karma and Nuyen are blank.

**To Reproduce**
Open the app.

**Expected behavior**
The karma/nuyen history and Attributes should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/12616904/56626404-2bf82e00-6607-11e9-82cf-2f9e21aa53d5.png)
![image](https://user-images.githubusercontent.com/12616904/56626414-331f3c00-6607-11e9-97de-11a82a328e51.png)
![image](https://user-images.githubusercontent.com/12616904/56626429-3d413a80-6607-11e9-983e-8a913d98b8fa.png)

**Character File**
[Jinx Car.zip](https://github.com/chummer5a/chummer5a/files/3110197/Jinx.Car.zip)

**Desktop (please complete the following information):**
W10
Chummer 5.205.51 (though it has been in earlier versions since at least .48)

**Additional context**
N/A

**Comment by chummer5a** [comment]
Seems to be loading correctly in the current nightly build.

**Comment by David-Demma** [comment]
I'll check it when I get home, will likely reply in the afternoon US Central if it works.

**Comment by David-Demma** [comment]
Just tried a few other files, they all load correctly. Seems like somewhere between the one that was a nightly that fixed my previous issue and .48 I saved the file and it became corrupted or something? Error still shows for the character, but not others.

**Comment by David-Demma** [comment]
Reloaded the uploaded file here, it works fine.

**Comment by chummer5a** [comment]
All good now then?
