### ISSUE TITLE
Career karma and nuyen

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3613]
**Describe the bug**
When you sell ware, career nuyen goes up. I don't think this is correct. It makes the money being counted twice (at least). Especially since many GMs houserule you can upgrade ware with just a small fee or none at all.

WFTP and WFTM gains also counts toward career karma/nuyen. IMO, and most others, this is also wrong. Also makes a gain being counted twice.

When I'm at it. If you've got karma left over from chargen, Chummer counts this also towards carreer karma. Is this intentional?

**Expected behavior**
Ware being sold not being counted towards career nuyen. WFTP and WFTM gains not counted towards carreer gains.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version  5.205.51 (and earlier)

**Thank you**
Thank you for still updating this program all the time.

**Comment by chummer5a** [comment]
The karma/nuyen trackers aren't really that smart. As far as we're concerned, you gained the nuyen or karma during your career, so it counts towards career nuyen/karma. Still, not really difficult to implement filters I suppose.

**Comment by drakir75** [comment]
I don't think any of the LCs count WFTP as career karma. Neither do I at home games. There's the option to choose refund instead (which I do at the moment) but it irks me somewhat.

If I want to compare two characters (or just give extra to a newly created character to be at the same level) it helps if the math is correct. Having to sift through upgrades where one sells used-buys standard, sells standard-buys alpha and so on is a bit onerous. The refund option works here to, but you have to delete ware without selling and gain the money through refund. A lot more work, and easy to forget..
