### ISSUE TITLE
Issue: - Crashed when updating from 5.204 to 5.205

### ISSUE THREAD

**Issue by luke1090** [chummer5a/chummer5a#3616]
### Environment
Crash ID: 27da444e-aa9d-475a-99fe-54176acbc669
Chummer Version: 5.204.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Was this an application crash, or a character crash?

**Comment by luke1090** [comment]
I'd just opened the app and run the update, no characters were loaded. The
app crashed and when reopened it showed the new version number
