### ISSUE TITLE
Shapeshifter Attribute Issues

### ISSUE THREAD

**Issue by ChrisVisserFee** [chummer5a/chummer5a#3622]
Once a Shapeshifter character is put into career mode, the attributes of the Metahuman form cannot be increased. Attempting to increase the attributes of the Metahuman form instead increases the attributes of the Animal form. This applies to normal attributes but not special attributes.

Once creating a Shapeshifter character and changing to career mode, the attributes of the Animal form and Metahuman form can be switched between with a drop down menu in the "Common" tab. The correct attributes are displayed, but after selecting Metahuman form and the attempting to upgrade an attribute with karma, the attribute of the Animal form increases but the attribute of the Metahuman form stays the same. Hovering over the "Improve Attribute" buttons (the green + signs) shows the correct karma cost and attribute value, but after clicking shows a window that corresponds with the Animal form attribute.

For example, if a character has Logic 2 in Metahuman form and Logic 3 in Animal form, and Metahuman form is selected, hovering over the + shows the message "Improve to 3 for 15 Karma" but clicking the button opens a "Spend Karma" window with the message "Are you sure you want to spend Karma on improving Logic (LOG) to 4 for 20 Karma?"

Whether the "Improve Attribute" button is greyed out is correct in both Metahuman and Animal form. If Logic is at 3 in animal form and 2 in Metahuman form, and the character has 15 Karma to spend, the + is grey while in Animal form but green while in Metahuman form. Clicking it while in Metahuman form opens a "Not Enough Karma" window. Also, if the Animal form is Vulpine with 4 Body, which is the max Body a Vulpine can have, while in Animal form the + is grey while in Elf form (with 6 as max Body) it is green. Clicking it here has no effect.

It should be possible to increase both a shapeshifters Animal form attributes and Metahuman form attributes separately.

[Kuro.txt](https://github.com/chummer5a/chummer5a/files/3130941/Kuro.txt)

**Comment by chummer5a** [comment]
Hrm, that's not supposed to work that way. Shouldn't be super difficult to sort out.

**Comment by DecklandMulqueen** [comment]
You fixed nearly all of the Animal/Meta issues. When you choose the Meta, you see the Metas Attributes and Skills - IN CHUMMER.
If you want to print the Metas sheet, it shows in the print sheet - Current form: Animal ... but the values for the Meta are displayed correctly, as the are selected in Chummer.
Maybe this helps with the other one.
Improvement for the Metas Attributes charges the Animals costs as described above ... same problem with my Shifter (just tried it, had not had enough karma yet ... ;))
