### ISSUE TITLE
Drone rules not correctly determining mod slots.

### ISSUE THREAD

**Issue by Suitechaoa** [chummer5a/chummer5a#3623]
**Describe the bug**
When I try to make modifications to drones after enabling drone mods the mod slots aren’t compensating for the first three armor or first attribute upgrade being free

**To Reproduce**
I’m unsure. I made the character first, added mods, and then turned the option on. Right now I can’t seem to turn the option off despite uninstalling and redone loading chummer. 

**Expected behavior**
Armor ( standard ) shouldn’t use modpoints until a rating higher than 3, and attribute upgrades shouldn’t use mod points until after the first point of upgrade. 

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
Can't replicate the issue; please show me an example file?

**Comment by Suitechaoa** [comment]
Figured out what was going on. Using the protection tab armor applies additive armor but uses armor slots at a rate of 2 points per point of armor as the vehicle rules. Going into all and using the armor ( drone ) applies armor correctly. I think a tab with all the rigger 5.0 drone mods from the drone modding system would help since you can only see them under the see all tab. Sorry to bother.
