### ISSUE TITLE
Pistol Chameleon Coating

### ISSUE THREAD

**Issue by Quintilium** [chummer5a/chummer5a#3627]
Long story short I can't add the Chameleon Coating mod to any pistol smaller than a Heavy pistol

It's not that I used the side slot, I tried it on an un-modded gun (Colt L36 if it matters) and the option wasn't there

-------

Version 5.205.48

**Comment by chummer5a** [comment]
```
      <accessorymounts>
        <mount>Barrel</mount>
        <mount>Top</mount>
      </accessorymounts>
```
