### ISSUE TITLE
Animal Empathy

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3631]
**Is your feature request related to a problem? Please describe.**
No problem, just a reminder bonus on a skill.
The quality "Animal Empathy" gives +2 dice to *all tests involving influence or control of an animal.* I see no use of the skill Animal Handling where Animal Empathy would not apply.

**Describe the solution you'd like**
A +2 modifier to the skill "Animal Handling". 

**Additional context**

**Comment by cnschu** [comment]
i've implemeted it, waiting for the merge.
