### ISSUE TITLE
Special Atts counts as normal Attribute counting maxed atts.

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3638]
**Describe the bug**
Chummer counts Magic as "normal" attribute when looking at how many atts are maxed. Edit: This is BOTH with Special att maxed with prio and not maxed with prio but with small differences.

**To Reproduce**
1. Create a magic or tecno character with a special attribute not maxed by prio choice.
2. Use Special points to max the special attribute (Magic or Resonance) and also max any other attribute.
3. Save. (You will see an error message here)
4. Load (Message here that to many atts are maxed) (Only if not maxed with prio choice)
5. See error. (Chummer has lowered the special att to "comply".

**Expected behavior**
To be able to have Special atts maxed.

**Screenshots**
Don't needed.

**Character File**
Can link if anyone wants, but probably not needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205.64 (Think versions somewhere in the early 40s don't have this bug). 5.205.0 does not.

**Thanks**
Many thanks for a wonderful product (even if some bugs creep in now and then).

**Comment by chummer5a** [comment]
Should be fixed in the current build.

**Comment by drakir75** [comment]
Issue back again since at least 205.71.
