### ISSUE TITLE
Allow manual choice to use spell points for Mastery Qualities

### ISSUE THREAD

**Issue by ProfessorOcecat** [chummer5a/chummer5a#3643]
Initially thought to be a bug, but there should be an option with all mastery qualities to purchase with Karma instead of Spell Points. Also, if Dedicated Spellslinger is purchased, deleting the quality removes 10 karma even though initial purchase didn't change karma. On a side note, due to the ambiguity of the rulings of the spell i.e whether you can take more spells at character creation with the quality, perhaps a feature that allows more spells to be optionally enabled? (I did see a post for disabling parts of chargen rules, so this probably falls in with that anyway).
(Note, this is the first time I've ever posted on GitHub, so if you need me to have more information or do anything specific/not do anything, let me know. Just trying to help.)

**Comment by chummer5a** [comment]
Why, though? 5 karma can be a contact or a spirit or an extra rank in a skill or a dozen other things, while a spell point can only ever be a spell. You can still buy the same number of spells as you could before you got it; why do you want to spend the karma first instead of spell points?

**Comment by ProfessorOcecat** [comment]
That is a good point, but the ability to choose should still be there (if its more of a 'its effort for something that may be used by a dozen people ever' type thing, fair enough - have a quality-of-life thing instead). The other part being that its not immediately obvious that Mastery Qualities in general draw from spell points first: by having it an option it can reduce confusion. I will of course defer to the people in charge/responsible for the program, it just really confused me for a while until I went to post the bug-report, saw it mentioned in another bug-report and realized it was a feature.

**Comment by chummer5a** [comment]
I've added a UI prompt that the quality will consume spell points; I'll look into enabling a manual toggle for the quality at some point.
