### ISSUE TITLE
Changing skills granted by magic/technomancer priority bugs skill points.

### ISSUE THREAD

**Issue by ProfessorOcecat** [chummer5a/chummer5a#3645]
**Describe the bug**
If after starting character creation you use the 'Change Priority' option and have been granted free skills due to your awakened/resonance selection, changing the granted skills causes the new points added to be subtracted. e.g. if you have priority C in skills (20 points) and priority A in magic (2 skills to start at 5), changing one of the skills (e.g. Arcana to Counterspelling) deducts 5 points from skills, regardless of how points were/were not arranged beforehand.

**To Reproduce**
Create a character with priority, selecting any Magic priority that gives free skills
Go to 'Options: Change Priority' and change the skills you selected
It should deduct from available skill points
Note, it doesn't matter if you had points in the skill you changed to or from or not.

**Expected behavior**
Available skill points should remain the same, with the 'free' gifted points being changed around, instead of deducting.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by DelnarErsike** [comment]
I cannot reproduce this in the dev build. Could you check if the issue is still present in the Nightly branch?
