### ISSUE TITLE
Street Cred Lowering

### ISSUE THREAD

**Issue by Luciferos** [chummer5a/chummer5a#3648]
**Is your feature request related to a problem? Please describe.**

Street Cred has many ways to be gained and lost in SR5. Chummer automatically contributes Street Cred at 1 per 10 karma and also has a slider to raise it. However, there is no way to lose Street Cred down below the base (Career Karma/10) for the myriad methods of doing so, except giving yourself notoriety and then burning Street Cred to get rid of that Notoriety. This makes bookkeeping kind of weird. The counter will not allow you to go into the negatives.

(Tough and Targeted quality, Lifestyle cost reduction, improving contacts are just some ways your char can lose street cred). 

**Describe the solution you'd like**

Either just allowing you to go negative on the Street Cred +/- counter to deduct SC from yourself, or some other mechanic of just "burning" street cred.

**Describe alternatives you've considered**

The only known alternative I am aware of is to raise your Notoriety slider and then burn street cred to lower it.

**Additional context**

N/A - Character Info tab in Career Mode on any character allows you to observe the problem with trying to lower your SC.

**Comment by chummer5a** [comment]
Somewhat linked to #3648

**Comment by Luciferos** [comment]
> Somewhat linked to #3648

Ah yes, I missed that one. This is basically a more comprehensive description of the same problem.
