### ISSUE TITLE
Crash when deleting/clicking on custom drug

### ISSUE THREAD

**Issue by Turley0815** [chummer5a/chummer5a#3652]
**Describe the bug**
Game crashes when I try to delete a custom drug from the inventory during character creation
When try to reproduce, it also crashes when clicking on a drug to see its stats

**To Reproduce**
1. Go to inventory ("Straßenausrüstung" in German)
2. Go to "Drugs"
3. Click on "BlitzDrek"
(3a. Click on "Delete", only first time today)

**Expected behavior**
See stats of drug
First crash yesterday: When deleting the drug, it did not vanish, at some point later it crashed.
Today the program crashed first time when I wanted to delete it, after that when trying to reproduce, it crashed when I tried to select the drug.

**Character File**
[CharFile.TxT](https://github.com/chummer5a/chummer5a/files/3179237/CharFile.TxT)

yesterday:
[attributes.txt](https://github.com/chummer5a/chummer5a/files/3179340/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/3179341/exception.txt)

first crash today:
[attributes.txt](https://github.com/chummer5a/chummer5a/files/3179240/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/3179241/exception.txt)

second today:
[attributes.txt](https://github.com/chummer5a/chummer5a/files/3179334/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/3179335/exception.txt)
[userstory.txt](https://github.com/chummer5a/chummer5a/files/3179336/userstory.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205.0

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/5751796fe67c5eca38571c397065d64b21d7aefc, will be in the next nightly.
