### ISSUE TITLE
Add a Defense display in the right pane, and allow Improvements

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3655]
**Is your feature request related to a problem? Please describe.**
The default Defense dice pool (REA+INT) would be handy to have displayed.

**Describe the solution you'd like**
Show the Defense pool in the right pane, either in the Condition Monitor tab or Other info tab.

**Additional context**
Additionally, it'd be good to be able to Improvements to this Defence pool as well, since there are many things that modify this pool.

Likewise, it'd be nice to also have a secondary display for the Defense pool on Full Defense, i.e. REA+INT+WIL by default, but with many possible alternatives due to quality, etc.

**Comment by chummer5a** [comment]
Implemented in https://github.com/chummer5a/chummer5a/commit/01d69a82257634cc472eecf5c4a18428c870e144
