### ISSUE TITLE
Pilot Enhancement should have rating up to 9

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3656]
**Describe the bug**
Rigger 5.0, p.168 states:
"A Pilot program can have a Rating of 1 to 9"

But Chummer caps Pilot Enhancement at 6.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.205

**Comment by Luciferos** [comment]
Preeeeeeeeetty sure that's a typo. See p.169 for the actual chart on pilot programs:

![image](https://user-images.githubusercontent.com/20429868/57884421-90697000-77f6-11e9-91c2-7eee567bd28e.png)

They're specifically broken down by tiers of availability/cost, and there's no tier for anything above 6. Note that these books are notoriously badly edited, and it's much more likely that the rating caps at 6 (like all other similar software, be it Drone pilots (drone rules, R5 p.127), Autosofts, Agents, linguisofts, knowsofts, activesofts, etc.) and there was a simple typo of just one keystroke in one entry than that vehicle pilots break the general precedent of the limitations of ALL other "dogbrain" software AND they forgot to include the rule-breaking component in the equipment table.

**Comment by chummer5a** [comment]
Pretty much, yup. Working as intended as far as RAW data goes.
