### ISSUE TITLE
Max. Nuyen Karma Build

### ISSUE THREAD

**Issue by Towid** [chummer5a/chummer5a#366]
Atm you can only spend 200 Karma for a maximium of 400k Nuyen during Karma Chargen.
It should be 235 to a max of 470k Nuyen. (20k Nuyen for 10 Karma from Step 6: Spend your Resources included).

**Comment by joha4270** [comment]
gear (at the cost of 1 Karma for every 2,000 nuyen; a maximum of 200 Karma can be spent this way),

p64, Run Faster

**Comment by joha4270** [comment]
Chummer is primarily an English piece of software, and we don't have the possibility to change depending behavior depending on the active language, so it will remain as stated in the English book, until CGL releases errata specifying otherwise

**Comment by chummer5a** [comment]
There's no particular reason we can't enable it as a house rule, though. It
won't be a high priority, but it's easily doable.

**Comment by Towid** [comment]
That would be great! But only if you find the time!
