### ISSUE TITLE
Character can't raise Resonance stat - bad tooltip

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#3664]
**Describe the bug**
When you mouseover the button to raise Resonance, the tooltip says "Improve to 2 for -1 karma" and is greyed out.

**To Reproduce**
load attached character.  Attempt to raise RES.

**Expected behavior**
tooltip should be informative and useful

**Screenshots**
![image](https://user-images.githubusercontent.com/13633603/57978748-cf9aeb00-79c7-11e9-88d1-4e71d517cc2a.png)

**Character File**
[Ayatsuri career 03.zip](https://github.com/chummer5a/chummer5a/files/3194835/Ayatsuri.career.03.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version local build from latest source

**Comment by chummer5a** [comment]
Your Resonance maximum is 1.

**Comment by cfresquet** [comment]
Ah, need to submerge first.  

In which case, we should really change that tooltip, because "-1 karma" isn't informative.
