### ISSUE TITLE
No option to disable getting Free Grids as part of lifestyles, even if not using Hard Targets 

### ISSUE THREAD

**Issue by Jutosa** [chummer5a/chummer5a#3669]
When I enable the Core  and SR5G (German exlcusive content) and I add any lifestyle I get a notification that the character has been created with rules from "Run Faster/Schattenläufer" upon re-opening the character. 

Characters created without the German exclusive content don't appear to have this problem.

The issue exists in both the current release build as well as the nightly builds.

The notification appears to be the same as in #3109.

**Comment by Jutosa** [comment]
My testing appears to be flawed. This happens without the SR5G with only the SR5 core rule book enabled as well.

Steps to reproduce:

1. Only enable SR5 CRB
2. Create a new character
3. Add a lifestyle
4. Save the character
5. Close the character (ctrl+w)
6. Re-open the character
7. Close the character (ctrl+w)
8. Open the character again and this time the notification pops up.

1.

**Comment by chummer5a** [comment]
Free grids per the rules in hard targets. I need to add a rule to toggle it off.
