### ISSUE TITLE
Technomancer issues and Lifestyle

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#367]
Submersion in Career Mode does not work. You can not choose to get it cheaper, the echoes are not available, and so on...

The Complex Form Coriolis (ChromeFlesh) is not included.

Lifestyle ... neverending Story.... yes, you can choose now the advanced mod, BUT: the Lifestyle Points and the costs are calculated mostly correct, but in the description there are wrong values. Not all qualities from Run Faster ar included. When you finish the Setup, nothig you have Chosen will Show up on the character sheet. When you try to click your Lifestyle again, chummer crashes ...

Did you remove Exotic weapons ammo? When i try to buy it for the Micro flare launcher ... chummer crashes ...

**Comment by joha4270** [comment]
>Submersion in Career Mode does not work. You can not choose to get it cheaper, the echoes are not available, and so on...

#350 

>The Complex Form Coriolis (ChromeFlesh) is not included.

New, but easy to fix, simple data entry

>Lifestyle...

Need the other guy on that, i'm scared to touch that part of chummer

>Did you remove Exotic weapons ammo? When i try to buy it for the Micro flare launcher ... chummer crashes ...

No, but i did change make some changes to what could be gotten for each weapon (No more "Light pistol assult cannon ammo"... but i see how this might have done stuff to exotic. I will look at it once i get some time

**Comment by DecklandMulqueen** [comment]
The Discount on Submersion can be found in Data Trails, p. 164 … when undergoing a submersion task, you get a discount of 20% … i think it wokrs like initiation, as they streamlines matrix and magic.

 

When you allowe submersion before career mode, it worked properly until 5.173. when you allow that option now, a technomancer can initiate … not submerge … ;-)

 

When will you include all those Chrome Fles Drugs and Nanites playthings?

 

THANKS FOR YOUR WORK !!!!

 

Tobi

 

Von: Johannes Elgaard [mailto:notifications@github.com] 
Gesendet: Donnerstag, 3. September 2015 22:55
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>
Betreff: Re: [chummer5a] Technomancer issues and Lifestyle (#367)

 

Submersion in Career Mode does not work. You can not choose to get it cheaper, the echoes are not available, and so on...

#350 <https://github.com/chummer5a/chummer5a/issues/350>  

The Complex Form Coriolis (ChromeFlesh) is not included.

New, but easy to fix, simple data entry

Lifestyle...

Need the other guy on that, i'm scared to touch that part of chummer

Did you remove Exotic weapons ammo? When i try to buy it for the Micro flare launcher ... chummer crashes ...

No, but i did change make some changes to what could be gotten for each weapon (No more "Light pistol assult cannon ammo"... but i see how this might have done stuff to exotic. I will look at it once i get some time

**Comment by chummer5a** [comment]
Lifestyles should mostly be fixed. I need to rework the character sheets to support the altered qualities. Re-enabling submersion shouldn't be a problem either.

**Comment by DecklandMulqueen** [comment]
Perfect! Thanks for all of your effort!Chummer 5 Is Alive <notifications@github.com> hat geschrieben:Lifestyles should mostly be fixed. I need to rework the character sheets to support the altered qualities. Re-enabling submersion shouldn't be a problem either.

**Comment by chummer5a** [comment]
Submersion tasks have been enabled in 5.175.

**Comment by DecklandMulqueen** [comment]
Thanks a lot. When will it be available as auto update? Or do i have to download the new version? Where can i do this?

 

Von: Chummer 5 Is Alive [mailto:notifications@github.com] 
Gesendet: Sonntag, 27. September 2015 13:51
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>
Betreff: Re: [chummer5a] Technomancer issues and Lifestyle (#367)

 

Closed #367 <https://github.com/chummer5a/chummer5a/issues/367> .
