### ISSUE TITLE
Make skills tooltips multi-line

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3670]
**Is your feature request related to a problem? Please describe.**
There can be a lot of things that modify skills.

Chummer's skills currently can have 2 tooltips:
- One from hovering over skill name, which shows the "Notes".
- One from hovering over dice pool, which shows dice pool calculation.

Both of these are one-line only tooltips, which becomes difficult to read when it gets long.

**Describe the solution you'd like**
Simply make these tooltips multi-line.

**Comment by chummer5a** [comment]
Tooltips are all supposed to be written to wrap at 100 characters, can you show me an example of one that doesn't?

**Comment by aga9** [comment]
Not sure what you mean by that. And anyway this request isn't about wrapping tooltips.

The tooltips for almost everything are shown as multi-line block text. But skills tooltips (both on the skill name and dice pool) are shown as single-line text -- meaning that they are always shown as a single-line even if you manually wrote multiple lines of notes.

I'm requesting to change the skill tooltips to behave like all the other tooltips: as multi-line block texts.

Better yet -- add note button (like for Adept Powers and Contacts) for easier one-click access to notes.
