### ISSUE TITLE
Issue: - Moving a Loaded HMG from Character inventory to Vehicle (trying to work with how to load ammo while in vehicle)

### ISSUE THREAD

**Issue by chrisl376** [chummer5a/chummer5a#3672]
### Environment
Crash ID: 78cf025f-37a3-4551-854c-f8cdd988079b
Chummer Version: 5.205.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
I am not exactly sure what was expected - move the vehicle and retain knowledge of what ammo is loaded from inventory?

### Actual behaviour
Crashed Chummer

### Steps to reproduce the behaviour
Moved weapon from vehicle to inventory.  Loaded ammo.  Moved weapon from inventory to vehicle.

**Comment by DelnarErsike** [comment]
Could you upload the affected character file? I'm having trouble reproducing the crash, maybe it has something to do with the location of the ammo being loaded or something.

**Comment by chrisl376** [comment]
I think an upgrade resolved it.  I can no longer reproduce it.
