### ISSUE TITLE
Extended clip for Ruger 101 and maybe others?

### ISSUE THREAD

**Issue by JSteger** [chummer5a/chummer5a#3673]
**Describe the bug**
Recently tried to imporve a Ruger 101 with extended clips but was not able to do so. It did not show up in the modification list. 

**To Reproduce**
Add the Ruger 101 either as equipment or to a vehicle turret.
Add modification (or addition I am using the german version). 
Extended clip is missing. 

**Expected behavior**
Since the extended clip mod uses no modification slot at all it should be available for all weapons. 

**Desktop (please complete the following information):**
 Windows 10

**Comment by chummer5a** [comment]
It's an internal magazine, how're you going to extend it?
