### ISSUE TITLE
New Old Critters: Elementals

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#3675]
**Elementals are not listed as a Critter**
They're a type of Spirit that used to be around in editions 1-2-3, only available to Hermetic Magicians.
They were re-introduced in Forbidden Arcana on page 181, but are missing from the Critter list.

**I tried custom files and failed**
I tried an amend_critters file with a metatypes amendoperation="add node" command, with a list of new spirits copied on the Air, Earth, Fire and Water spirits, but with amended mental stats.
Unfortunately, although they are visible in the list of spirits available, when I select one and click "OK", I get an error message (see screenshot).
<img width="747" alt="Screenshot 2019-05-27 at 22 28 57" src="https://user-images.githubusercontent.com/4921171/58440069-85a0bc00-80cf-11e9-9483-4022b06146d4.png">
I also enclose my amend file, in case I missed something...

**Fix**
Could you add Elementals to the list of Spirits?

**Enhancement**
Could you have a look at my file and advise if I missed something?

[amend_critters.xml.zip](https://github.com/chummer5a/chummer5a/files/3225009/amend_critters.xml.zip)

**Comment by chummer5a** [comment]
Remove the amendoperation="addnode" on line 23. What that does is create two sets of metatype nodes, and the selection method uses a slightly different method to the population method that means it only loads the first one, so we don't see the other set.

**Comment by oxford-fumble** [comment]
Awesome - thanks, it worked a treat.
