### ISSUE TITLE
'Unhandled exception error' when loading character

### ISSUE THREAD

**Issue by bart95** [chummer5a/chummer5a#368]
http://i.imgur.com/xKr8amW.png

Not only that, but when I click 'continue' the entire character creation UI is buggered. Basically everything on the right turns into 0 of 0 (And does not change when adding or taking attribute points etc), the skills menu is completely empty, impaired attribute is no longer in effect, etc.

Side note: Using Class III Surge as a quality seems to count as 25 Karma, not 30, and knowledge points seem to be calculated incorrectly? (I think a friend said it was x3 instead of x2 or some such?)

**Comment by joha4270** [comment]
I would love to know what it says when you press details

**Comment by joha4270** [comment]
>Side note: Using Class III Surge as a quality seems to count as 25 Karma, not 30

It costs 30 on my end, both in chummer and in rf103

> knowledge points seem to be calculated incorrectly? (I think a friend said it was x3 instead of x2 or some such?)

Characters receive free Knowledge and Language skills points equal to (Intuition rating + Logic rating) x 2

p89 core

**Comment by bart95** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '7' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected()
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 0.5.171.0
    Win32 Version: 0.5.171.0
    CodeBase: file:///E:/Documents%20and%20stuff/Downloads/Chummer5-2015-09-04/Chummer5/Chummer5.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34250 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by bart95** [comment]
A friend and I fiddled with our character files, turns out Chummer doesn't seem to like the changeling/Class III Surge character I was trying to make. Loading a 'normal' character works fine. And when making a changeling character from scratch there are no issues, it's just loading them.

**Comment by joha4270** [comment]
Can you upload the .chum5 file for debugging purposes somewhere?

2015-09-05 14:47 GMT+02:00 Harley <notifications@github.com>:

**Comment by bart95** [comment]
http://www.filedropper.com/john should do, I made a version without the changeling/SURGE/Metagenetic qualities and it loads fine.

**Comment by chummer5a** [comment]
Should be resolved in 5.175. Closed pending shit breaking again.
