### ISSUE TITLE
Qualities are handled differently in extracted JSON

### ISSUE THREAD

**Issue by FelodinBlutstein** [chummer5a/chummer5a#3682]
I'm using SINners to download my Groups data into a JSON for implementing the characters into MapTool. So far so good thanks to A-r-c-h-o-n.
Thing is, when it comes to qualities i see two different ways of handeling them.

a) e.g. "In Debt" (15)
This quality is in there like 15 times so handeling it is quite difficult.

b) e.g. "One with the Matrix"
This quality gives you the option to select either
One with the Matrix I
One with the Matrix II
or
One with the Matrix III

The later one is a lot more practical for later usage.

**Expected behavior**
Option B for all qualities

**Screenshots**
![Quality-Issue](https://user-images.githubusercontent.com/51225346/58686741-e8b87a00-837f-11e9-93f0-5e25808a9b9b.JPG)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Version [e.g. 5.205.93]

**Additional context**
Ask A-r-c-h-o-n. I'm working with him on this.

**Comment by ArchonMegalon** [comment]
Related to #3683 (would be solved, once the data model for the qualities supports ranks in a sane way)

**Comment by chummer5a** [comment]
That's not a JSON problem, that's how the quality works.
