### ISSUE TITLE
Allow qualities to use FixedValues to alter their cost based on level

### ISSUE THREAD

**Issue by FelodinBlutstein** [chummer5a/chummer5a#3683]
**Describe the bug**
When selecting the quality one with the Matrix you can select
One with the Matrix I, II & III
on the top of the quality section there is a option to increase the level of the quality to 3. So One with the Matrix III 3 costs 30 karma.

**To Reproduce**
1. Add Qualities
2. Select any of the One with the Matrix qualities
3. Switch quality level

**Expected behavior**
grey out the level like for other qualities e.g. Allergy

**Screenshots**
![Quality-Issue-One with the Matrix](https://user-images.githubusercontent.com/51225346/58687198-46999180-8381-11e9-873e-fd5ddefbb40e.JPG)

**Character File**
[Riley Davis.txt](https://github.com/chummer5a/chummer5a/files/3240074/Riley.Davis.txt)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Version [e.g. 5.205.93]

**Additional context**

**Comment by ArchonMegalon** [comment]
Related to #3682

**Comment by chummer5a** [comment]
Currently, we don't support FixedValues for qualities based on level. Since the quality has different costs based on the effective rank, it has to be split up like that.
