### ISSUE TITLE
Audio and Vision Enhancement shouldn't go to rating 6

### ISSUE THREAD

**Issue by dalekalpha** [chummer5a/chummer5a#3697]
This may be me not having all books, but in both the Core Rulebook (p. 454) and Crome Flesh (p. 223), it says that both Audio and Vision enhancement only goes to rating 3, yet the data/cyberware.xml has them as up to rating 6 with unexplained nuyen and essense costs. A fix for the file or a correction of my mistake would be much appreciated.

**Comment by holgerschlegel** [comment]
The book "No Future" added the audio and vision enhancement levels 4-6.

**Comment by dalekalpha** [comment]
Oh alright, so it was my mistake. I think adding a note or a secondary item would prevent others from making the same mistake. I have No Future disabled in my chummer, so I don't feel that it should give me the option of rating 4-6.

**Comment by Lochabar** [comment]
Why are ratings 4-6 being shown if No Future is not enabled?
Other items of gear are not shown if the corresponding sourcebook is not enabled. Is it a problem with it adding ratings to a piece of gear rather than an item of gear being shown or not?
