### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by MeritShu** [chummer5a/chummer5a#3698]
### Environment
Crash ID: d991246c-7e4d-41ab-bf1b-6ac4543f1688
Chummer Version: 5.205.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by Lochabar** [comment]
How about changing the error reporter so that the "submit" button is  not active until the description is changed and an explanation of what happened is added.

**Comment by MeritShu** [comment]
How about the usual error reporters I have used so far were automated and I couldn't think of any reason why a sophisticated tool like yours would not be? Besides I got the error when first starting chummer, so I'd never had a chance to change any options?

And how about an approach thats a bit more friendly, as for example in: "Hi, could you please describe the incident you were reporting? And could you change the error reporter so that the "submit" button is not active until the description is changed and an explanation of what happened is added for future use?" Wouldn't have taken more than 10 additional seconds.


Usually I don't bother with error reporters at all, I did this time because I think chummer is great and I wanted to help.


Gesendet: Montag, 10. Juni 2019 um 23:02 Uhr
Von: "Lochabar" <notifications@github.com>
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: MeritShu <mary_neu@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] Issue: - PLEASE ENTER DESCRIPTION HERE (#3698)


How about changing the error reporter so that the "submit" button is not active until the description is changed and an explanation of what happened is added.

**Comment by ArchonMegalon** [comment]
Well, we are overhauling the whole error reporting anyway at the moment. If the automatic uploading of the logs works well enough, we might just be able to ditch that old reporting feature altogether. Don't know what the other devs think about that.
