### ISSUE TITLE
Issue: - crash report DMP file over 420 MB big

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3699]
### Environment
Crash ID: 90735b86-10cf-41c2-8eee-79599a54a08f
Chummer Version: 5.205.102
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
I expected a relatively small file.

### Actual behaviour
The DMP file is way too big to work with GitHub's uploader.

### Steps to reproduce the behaviour
Testing the SINnerHub plugin under Chummer 5.205.102; trying to log into SINnerHub through the plugins tab crashed the app. The report's DMP file is too big. Picture available in the Issues room of the Discord server: https://media.discordapp.net/attachments/365227867535310858/588055347986432020/unknown.png

**Comment by ArchonMegalon** [comment]
Probably solved by #3701
