### ISSUE TITLE
How to add custom Streams, Paragons, Echoes, and Complex Forms?

### ISSUE THREAD

**Issue by TheRealNamikaze** [chummer5a/chummer5a#370]
I've done this in the past with the original Chummer code.  But since Streams and Paragons aren't included in the current version of SR yet, the new Chummer code doesn't seem to have them enabled.  I can edit the files and such without a problem, but I can't get them to activate.

Is this something that could be implemented with the current build?  Or would it require a new build to add some features?

**Comment by joha4270** [comment]
While i don't know the details without looking, based on past stuff, it should not work, but it might or might not be a simple check. Atleast some 4e code is present

**Comment by chummer5a** [comment]
Code's all there, you just need a quality that has the selectparagon bonus
and the appropriate paragon files.

**Comment by TheRealNamikaze** [comment]
Sounds good.  I'll add a quality and test it out.  I'll give feedback and close if it works.  :)
