### ISSUE TITLE
Issue: - Custom Drugs Crashes Chummer

### ISSUE THREAD

**Issue by JoeCool715** [chummer5a/chummer5a#3700]
### Environment
Crash ID: 5330c7c0-893e-4fae-b610-fe799c00f793
Chummer Version: 5.205.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
create and use custom drugs

### Actual behaviour
click on custom made drugs and chummer crashes

### Steps to reproduce the behaviour
1. go to street gear
2. click drugs
3.click already made drugs

**Comment by ArchonMegalon** [comment]
Fixed in #3705
