### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LumpyGiraffes** [chummer5a/chummer5a#3714]
### Environment
Crash ID: 90cc2177-c7a8-4f47-8228-672a93084eae
Chummer Version: 5.207.0
Environment: Windows 7 Professional
Runtime: 4.0.30319.42000

### Expected behaviour
The application starts up normally

### Actual behaviour
Crashes on startup

### Steps to reproduce the behaviour
Run the application, presumably

**Comment by chummer5a** [comment]
Not throwing any errors on my end, what's the crash report say?

**Comment by ArchonMegalon** [comment]
@LumpyGiraffes maybe you want to update to the last nightly and enable upload logs, that could help us find an issue only happening at your client.

**Comment by ArchonMegalon** [comment]
@LumpyGiraffes i'm closing this for now. If you still experience this bug, please comment!
