### ISSUE TITLE
Bug(s) in options menu of 5.207.0

### ISSUE THREAD

**Issue by Douchebag-DM** [chummer5a/chummer5a#3715]
**Describe the bug**
When you open the options menu in desktop mode there is no way to change the size of the window which in turn puts the "OK" and "Cancel" option buttons below the screen bottom meaning you can't click them, I am also unable to move the window up further to access the buttons.

**To Reproduce**
open chummer
go to the options dialogue box
look at bottom of screen and see no buttons available

**Expected behavior**
same as above but being able to change the size of the window to access the buttons

**Screenshots**

**Desktop (please complete the following information):**
current version of windows 10
![Capture](https://user-images.githubusercontent.com/51901248/59737415-6a2e5a00-9212-11e9-9608-ec88d04266af.PNG)

**Comment by chummer5a** [comment]
I was worried that might happen; looks like your resolution's set to something like 1280x800, yes? A quick and dirty fix might be to rotate your screen to Portrait mode so that the thing's visible. I'll have a poke at resizing it properly in the meantime.

**Comment by Lochabar** [comment]
FYI: this problem was originally reported in #1080 - and there's no rotating a desktop monitor.

**Comment by ArchonMegalon** [comment]
fixed with #3755
