### ISSUE TITLE
Bugged number of starting spells, rituals and alchemical preparations

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#3719]
**Describe the bug**
A preciously closed bug, dictated [here](https://github.com/chummer5a/chummer5a/issues/1662), seems to be resurfacing. The number of spells/preparations/rituls are incorrectly calculated based on Magic Score, and taking them draws from the same shared pool as opposed to three seperate ones as intended.

**To Reproduce**
1.Create a character in Priority Mode
2. Assign Magic/Resonance to Priority A and select Magician
3. Go to "Spells and Spirits"
4. Add 10 spells and 1 ritual. The ritual will be deducted from Karma rather than it's own pool.

**Expected behavior**
As stated in the core rule book:
SR5 page 69:
"At character creation, magicians who cast spells, perform rituals, or create alchemical preparations may know a maximum number of formulae from each group equal to their Magic Rating x 2 (i.e., Magic Rating of 4 allows 8 spells, 8 rituals, 8 alchemical preparations)."

**Screenshots**
https://i.imgur.com/mcEmodh.png?1

**Character File**
[LaVey.txt](https://github.com/chummer5a/chummer5a/files/3308702/LaVey.txt)

**Desktop (please complete the following information):**
 - Chummer5a: 5.207.0
 - OS: Windows 10
 - Version 1803

**Comment by Lwmons** [comment]
I'd also like to add that I can't seem to find Preparations at all, though I'm not sure if that's the program or just me not knowing where to look.

**Comment by chummer5a** [comment]
Not a bug. Priority generation gives you an amount of free spells according to the priority you select. Priority A MAG is 10 spells. You also have a hard cap on the number of spells you can learn at all, which is MAG*2.

**Comment by chummer5a** [comment]
Preparations are added by selecting the Alchemical checkbox on the spell selection screen.

**Comment by Lwmons** [comment]
Oh wait... I see what happened here. Apologies. Looks like me and the linked person both misunderstood that the section we quoted was for the maximum, not the total.

Sorry about that!

**Comment by chummer5a** [comment]
No worries, it's cropped up a few times before. Chock it up to awkward writing, I guess.
