### ISSUE TITLE
 Career Mode: Improvements Tab Issue with Adept Powers

### ISSUE THREAD

**Issue by ocorchado** [chummer5a/chummer5a#3721]
**Describe the bug**
While in career mode and using improvements tab to improve adept powers, adept powers possessed by character do not show up in the value menu as an option to pick. The only adept powers that do are ones with multiple options like Improved Ability (Skill) or Improved Physical Attribute or brand new adept powers that the character does not have yet.

**To Reproduce**
1. Go to Improvements Tab
2. Click on Add Improvement
3. Scroll down to Adept Powers
4. Try and find a power that has already been selected by character. They are being excluded for some reason.

**Expected behavior**
I should be able to select for instance, Combat Sense, which is Rating 1 and increase it to Rating 2.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.207.0

**Comment by ArchonMegalon** [comment]
Seems like the issue is still present.

**Comment by chummer5a** [comment]
Can't replicate it, seems fine as long as the checkbox to ignore restrictions is selected.
