### ISSUE TITLE
Muscle Toner/Augmentation + Improved Physical Attribute Adept Power do not stack

### ISSUE THREAD

**Issue by ocorchado** [chummer5a/chummer5a#3722]
**Describe the bug**
Muscle Toner and Improved Physical Attribute do not stack. Program is only recognizing the highest rating Augmentation. If the rating are the same it will only recognize the bioware.

**To Reproduce**
1. Select Muscle Aug or Toner in Bioware
2. Select Improved Physical Attribute (AGI) or (STR)
3. If improvements are same value (ie. Rating 1) it will only recognize Muscle Tone/Aug
 but if Improved Physical Attribute has a higher rating then the program will only add in the Adept Power.

**Expected behavior**
If I have Rating 2 Muscle Tone and Rating 2 Improved Physical Attribute (AGI) + Agility 6, the final Augmented Attribute should be 6(10) but currently it is 6(8).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.207.0 (Occurred with 5.205.0 as well)

**Comment by chummer5a** [comment]
So the problem with this is that there's weird RAW on it and it never got an errata. RAW on stacking says it's one-sided, so if one thing says it doesn't stack with another thing, the other thing doesn't need to say it doesn't stack. Missions FAQ says to treat anything that increases your attribute value as an augmentation; before my time, but it was considered to be errata for quite a while. 

The simplest fix for this would be to put in a forbidden node to prevent the cyberwares from being taken with each other, but there's weird edge cases there as well as we'd have to forbid taking the suprathyroid as well, which does more than just affect str or agi.

**Comment by ocorchado** [comment]
I have literally never seen the line that says it's not compatible. Selective sight I guess. I definitely see it now. I wonder if that line was in there for 3rd or 4th Edition? Thanks for the quick response and clearing that up.

**Comment by ocorchado** [comment]
I have literally never seen the line that says it's not compatible. Selective sight I guess. I definitely see it now. I wonder if that line was in there for 3rd or 4th Edition? Thanks for the quick response and clearing that up.
