### ISSUE TITLE
Helmets as armor mods broken in 5.207

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3726]
**Describe the bug**
https://github.com/chummer5a/chummer5a/issues/3602
^ This issue was addressed with a custom rule in 5.205. But the 5.207 seems to have broken it. Helmets do not show up as addable mods for the armors concerned.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version  5.207

**Comment by DelnarErsike** [comment]
I just tested the custom rule on the latest dev build and it appears to be working. Could you double-check to see if you aren't missing something and/or could you provide us with a savefile of the affected character?
