### ISSUE TITLE
wrong translation <license translate="Zulassung für nicht frei erhältliche Waffen">Restricted Armor License</license>

### ISSUE THREAD

**Issue by JoshuarTree** [chummer5a/chummer5a#3731]
**Describe the bug**
wrong translation
<license translate="Zulassung für nicht frei erhältliche Waffen">Restricted Armor License</license>

**To Reproduce**
-

**Expected behavior**
<license translate="Zulassung für nicht frei erhältliche Rüstungen">Restricted Armor License</license>

**Screenshots**
-

**Character File**
-

**Desktop (please complete the following information):**
-

**Additional context**
corrected language file attached
Tested with 5.207.0

[de-de_data.zip](https://github.com/chummer5a/chummer5a/files/3334634/de-de_data.zip)

**Comment by ArchonMegalon** [comment]
Fixed with #3738
