### ISSUE TITLE
Inhabitation isn't working

### ISSUE THREAD

**Issue by SentientPebble** [chummer5a/chummer5a#3740]
**Describe the bug**
If you inhabit a living vessel with a spirit, instead of accounting for the stats of the vessel, it seems to completelty reset the character, except for cyberware, bioware, and gear, giving you 800 karma and a completely blank human, without even the critter powers

**To Reproduce**
1. Create an inhabitation spirit
2. Inhabit a living vessel
3. See completely bare character

**Expected behavior**
For the attributes, skill, and magical abilities of the vessel to remain, with the critters powers being added on

[Vessel (not possessed).pdf](https://github.com/chummer5a/chummer5a/files/3363002/Vessel.not.possessed.pdf)
[vessel.pdf](https://github.com/chummer5a/chummer5a/files/3363003/vessel.pdf)
[wasp.pdf](https://github.com/chummer5a/chummer5a/files/3363004/wasp.pdf)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - 5.207

**Comment by RedRoss53** [comment]
I also cannot seem to get it to work

**Comment by chummer5a** [comment]
Seems to be fine in current nightlies. Should've been good as of 5.210 I think.
