### ISSUE TITLE
Allow "None"-grade ware to benefit from essence reduction improvements. 

### ISSUE THREAD

**Issue by davidfoerster** [chummer5a/chummer5a#3741]
### Describe the bug
I'm trying to build a critter war form (see *Running Wild*) but regular characters experience the same issue: the “[biowareessmultiplier]” and “[genetechcostmultiplier]” improvements do nothing when added through the improvements tab.

### To Reproduce
Steps to reproduce the behaviour:
 1. Create a new character and move it straight to career mode. (Lose all the creation points and karma in the process.) Add some nuyen (e. g. 1.000.000) for later purchases.
 2. Go to the improvement tab and add the bioware essence cost improvement (e. g. with 90 %) and the genetech cost improvement (e. g. with 80 %).
 3. Buy any gentech with sufficiently high essence cost to not be affected by rounding, e. g. a genetic optimization (for any attribute ). The preview lists regular essence cost (0.3) and discounted nuyen cost (37.600 ¥).
 4. Regular nuyen (47.000 ¥) and essence costs (0.3) are deducted.

### Expected behaviour
Discounted nuyen (37.600 ¥) and essence (0.27) cost are deducted. Ideally the discounted costs are displayed in the “shopping” preview.

### Sample character file
[critter war form](/chummer5a/chummer5a/files/3363771/critter-war-form.zip) that already has steps 1 and 2 done/applied.

### Desktop
 - OS: Windows 7 (both native and via Wine v4.11)
 - Version: 5.207.0

[biowareessmultiplier]: /chummer5a/chummer5a/wiki/Improvement-Manager#biowareessmultiplier
[genetechcostmultiplier]: /chummer5a/chummer5a/wiki/Improvement-Manager#genetechcostmultiplier

**Comment by DelnarErsike** [comment]
Genetech Cost Multiplier not working properly was a bug, but biowareessmultiplier is working as intended (sort of). Biowareessmultiplier is based on Biocompatibility, and therefore does not affect Genemods. A new improvement needs to be made that affects Genemods if that is the functionality you are looking for.

**Comment by davidfoerster** [comment]
Thanks for the quick fix!

> A new improvement needs to be made that affects Genemods if that is the functionality you are looking for.

Yes, that’s what I want.

**Comment by davidfoerster** [comment]
I tested the gene tech essence multiplier improvement in v5.207.29 and, unfortunately, it appears to have no effect. So I would like to reopen this issue.

**Comment by chummer5a** [comment]
Hrm. It's because we explicitly ignore essence modifiers if forcegrade="None" is used. Probably need to replace that with an actual property that stipulates whether we want to ignore improvements as well; from memory, it was built to support ignoring things like cyberlimb customisation.
