### ISSUE TITLE
Issue: - crash on multi-upload to SINnerHub (v5.207.16)

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3745]
### Environment
Crash ID: 8489a81a-0864-4935-94a6-dfedbc80e6ce
Chummer Version: 5.207.16
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: True
Installation ID: d4e5ab0b-d659-49f1-a07c-60079853fe91

### Expected behaviour
I am testing the SINnerHub plugin by attempting to upload files to the cloud. 

### Actual behaviour
The crash report attached shows, crashing Chummer. 

### Steps to reproduce the behaviour
1. Log into SINnerHub through the relevant Chummer Plugins tab.
2. Try to attach three files (starting with MCT in the name) through multi-upload; copies of said files available here: https://drive.google.com/drive/folders/1Ac2YznKRwEtRbTaRrp2aAmwxjXcZzVu9
3. Cry as the app crashes.

**Comment by ArchonMegalon** [comment]
I love myself... 

![image](https://user-images.githubusercontent.com/11421547/60871437-073d4b00-a233-11e9-9d86-8347154af161.png)

Will "fix" (= implement that for the first time) tomorrow. xD

**Comment by ArchonMegalon** [comment]
fixed with #3754
