### ISSUE TITLE
Adding Ares Sigma to new Character during Character generation

### ISSUE THREAD

**Issue by DMael** [chummer5a/chummer5a#3746]
### Environment
Crash ID: 83659e34-c648-40ca-9a39-91f112ef1ca1
Chummer Version: 5.207.0
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Adding the Ares Sigma to Inventory

### Actual behaviour
Chummer shut down

### Steps to reproduce the behaviour
create new Character, bu weapon

**Comment by DelnarErsike** [comment]
I was unable to replicate this crash on the dev build. Could you perhaps provide a savefile of the affected character, because there might be something else on the sheet that is messing with the newly added Ares SIGMA?
