### ISSUE TITLE
Error in Menu: Tools

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3749]
**Describe the bug**
Start Chummer 5.207.21, open Menu "Tools"

**To Reproduce**
1. Go to Tools

**Expected behavior**
See correct Entry

**Screenshots**
![image](https://user-images.githubusercontent.com/12108972/60865859-3057de80-a227-11e9-8088-1329066a9b96.png)
Looks the same with Language set to EN-US

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.207.21

**Additional context**

**Comment by ReallyDarkMatter** [comment]
Error went away after a Clean Reinstall

**Comment by ArchonMegalon** [comment]
Archetypes should work in the current nightly. I still haven't added the translation ...

**Comment by ArchonMegalon** [comment]
Fixed in #3768
