### ISSUE TITLE
Issue: - Crash after clicking on Plugin Tab in Options

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3750]
### Environment
Crash ID: fe2dcd1d-7f30-4dfe-bd08-108a48d599dc
Chummer Version: 5.207.21
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000
Option upload logs set: True
Installation ID: 45e9d407-bd08-475e-91e0-74c2a3b7191f

### Expected behaviour
Work

### Actual behaviour
Crash after clicking on Plugin Tab in Options

### Steps to reproduce the behaviour
Open Chummer
Open Tools Menu
Click Options
Click on Tab "Plugin"
Crash

**Comment by ArchonMegalon** [comment]
The good thing is: it's really easy to find the logs with the new Installation ID and uploading feature.
Just to try something out. Can you please copy the GroupControls.dll and .xml from the main directory into the plugin-directory and try again? Please?

**Comment by ArchonMegalon** [comment]
Please note that the Archetypes are not working in the current nightly, but should in the next (found a bug and already fixed it)

**Comment by ReallyDarkMatter** [comment]
No GroupControls.dll or .XML in the whole installation

**Comment by ArchonMegalon** [comment]
fixed with #3754
