### ISSUE TITLE
When attempting to download Chummer I get a failed-forbidden response.

### ISSUE THREAD

**Issue by Robb1990** [chummer5a/chummer5a#3751]
When attempting to download Chummer5.207.0.zip the download takes an unusual amount of time (over 20 minutes for 19.5mb) and when the download would complete, it instead comes up with failed-forbidden.

OS:  Windows 10 Pro
Version: 1803

**Additional context**
Am downloading from China, through a VPN, though this doesn't normally slow download speeds so noticeably, this issue doesn't appear for other downloads.

**Comment by Robb1990** [comment]
Should mention, I'm using Chrome primarily, though have also tried and met failure with Edge, will try Firefox tomorrow, see if the issue persists.

**Comment by ArchonMegalon** [comment]
I'm not sure how we can be of help here. Please report back if this persists.

**Comment by Robb1990** [comment]
Good news! Firefox worked! so if anyone has a similar issue, try Firefox and hopefully you get lucky!
Thanks for the reply Archon!

**Comment by chummer5a** [comment]
Glad to hear you sorted it.
