### ISSUE TITLE
Be able to sort the Character Roster

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3752]
Used to be able to right-click on the Character Roster and sort the characters. This was taken away in #3744 :(

PLEASE BRING BACK THE FEATURE :)
How about right-click on the Headings (Favorite Characters / Recent Characters) instead?

**Comment by ArchonMegalon** [comment]
Sorry, not getting this today. Will poke it tomorrow I hope.

**Comment by ArchonMegalon** [comment]
Basic (alphabetic) sort implemented in #3758
