### ISSUE TITLE
Audit and update Custom Improvements in improvements.xml

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#3756]
The improvement list in improvements.xml is largely unmaintained and needs to be updated for the current improvement list. Requires ability to understand the existing code in clsImprovement and frmCreateImprovement to determine how a given improvement type can be implemented in data. 

- [ ] Determine missing/legacy improvements.
- [ ] Implement replacements for each.

**Comment by cnschu** [comment]
the improvements.xml seems completely OK.
i can't see any need for changes.

**Comment by chummer5a** [comment]
Nah, there's a bunch of improvement types missing. Specific spell resistance improvements like DetectionSpellResist, for example. MetageneticLimit to modify custom changeling things, etc etc.

**Comment by cnschu** [comment]
I can't figure out a rulebase for these improvents, so it's quite difficult to figure out what is missing.

**Comment by chummer5a** [comment]
Broadly speaking, any of the cases in https://github.com/chummer5a/chummer5a/blob/master/Chummer/Backend/Improvements/ImprovementMethods.cs that don't have a matching internalid node in improvements.xml are improvements that can't be added through the custom improvement system.
