### ISSUE TITLE
SotA ADL Book missing

### ISSUE THREAD

**Issue by CTD1** [chummer5a/chummer5a#3759]
There is no longer a option to use SotA ADL Source Book (was working in Chummer5.205.0, is broken in Chummer5.207.0)
It is no longer in the Character Options tab. Same is true for Bullets and bandages, and if I compare the list from Global options, for much more books.

**Comment by chummer5a** [comment]
I'd guess you're using the Missions 1.4 rules customdata entry, which bans those books.

**Comment by CTD1** [comment]
Not intentionaly, but yes, the option was checked. Removing it fixed it. Thnaks for the fast answer.
