### ISSUE TITLE
Sprite Maximum / Sprite Pets / Augmented Attribute

### ISSUE THREAD

**Issue by MiraNoir** [chummer5a/chummer5a#3762]
**Describe the bug**
Maximum Sprite Amount / Possible Need of a House Rule

**To Reproduce**
Possible Bug 1: Getting the "You number of registered sprites cannot exceed your LOG score" error
Base Logic: 4
Augmented Logic: 6
Maximum Sprites Stay at 4
Possible Bug 2: Also a sprite pet is selected on one sprite, and still count toward the 4 sprites as well (KC91) "If this is done, the sprite becomes a sprite pet. This means that the sprite no longer has a limit on favors and tasks and can be active at the same time as any other sprite. It also no longer counts against the Technoshaman’s limit on registered sprites."

**Expected behavior**
Maximum Sprite should go with Augmented Attribute
Sprite Pet should not count toward maximum # of sprites

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by DecklandMulqueen** [comment]
The maximum is calculatet correct, but the sprite pet still counts toward the maximum
