### ISSUE TITLE
binding Qui Foci calculates karma costs wrong

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#3765]
i bought a lvl 4 qui focus and instead of removing 8 karma for binding i got 18 back ...not a bad idea but wrong

**Comment by DelnarErsike** [comment]
I cannot seem to replicate it on the dev branch. Could you upload the affected character's savefile to help us replicate the issue?

**Comment by DecklandMulqueen** [comment]
As you wish

 

Von: DelnarErsike <notifications@github.com> 
Gesendet: Mittwoch, 17. Juli 2019 22:21
An: chummer5a/chummer5a <chummer5a@noreply.github.com>
Cc: DecklandMulqueen <Thobbe@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [chummer5a/chummer5a] binding Qui Foci calculates karma costs wrong (#3765)

 

I cannot seem to replicate it on the dev branch. Could you upload the affected character's savefile to help us replicate the issue?

**Comment by DelnarErsike** [comment]
Uh, you did not upload a savefile. I don't think an attachment via email works, you have to attach the file directly to your GitHub comment.
