### ISSUE TITLE
Cannot select knowledge skill

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3770]
**Describe the bug**
Creating a character and trying to add a new knowledge skill. Clicked "Add Skill" and a new line appears but the skill box is locked.

**To Reproduce**
1. Go to 'Skills' -> 'Knowledge Skills'
2. Click on 'Add Skill'
3. See error

**Expected behavior**
Be able to use the drop-down to select a skill, or type in a new skill.

**Screenshots**
![Know skill](https://user-images.githubusercontent.com/17562417/61393247-33397b80-a886-11e9-8889-bbd77f3a834c.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Edition
 - Version: 5.207.29

**Comment by Lochabar** [comment]
Just realized that I cannot change the Points or Karma skill points.

**Comment by DelnarErsike** [comment]
This was fixed in commit 5680a95e8bbe99288c25fcbaf1efdac66ea5cbbc and will therefore be fixed in the next nightly.
