### ISSUE TITLE
Adept Powers being reset to 0 ranks

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#378]
So, this is a bit weird, but I was working on a character and when I added Improved Ability it worked, but then when I tried to increase it the power suddenly dropped to 0 ranks and then wouldn't change. When I saved the file and reopened, hoping this might allow me to work around it, it had also changed Improved Physical Attribute to 0, and that was similarly stuck. Link is below.

https://drive.google.com/file/d/0B7MDGEbiDFrkTzg0OU4tNWQtaUk/view?usp=sharing

**Comment by Verecoth** [comment]
I'm fairly certain there's a bug with the Improved Ability adept power, as every time I add it to a character it causes adept powers to all go bad. Any power added is added at 1 rank, but any attempt to increase its ranks causes it to drop to 0, and then it cannot be changed.

**Comment by HaikenEdge** [comment]
Have you tried putting in ranks into the related skill first? I had this problem, until I realized the max you can have for Improved Ability is 1.5 times the number of ranks you have in the skill, so having 0 ranks in the skill lets you have 0 ranks in the power.

**Comment by Verecoth** [comment]
If there are ranks in the skill when the power is added, the glitch doesn't happen. However, if you add the power when the skill has no ranks in it, it still sets the maximum rank for all other powers to 0.

**Comment by Beherrit** [comment]
Hello All,

Verecoth, thanks for that work around, I have been having one hell of a time trying to get Adept powers to work since they zero out all other powers, I was trying to find a work around, suppose I should have read the comments here.  Thanks again!
