### ISSUE TITLE
Data: Tactical Grapple Gun error

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3783]
**Describe the bug**
Tactical Grapple Gun has the same stats as normal Grapple Guns.

**Expected behavior**
It should have stats from HT 187.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.207

**Comment by Falkgeist** [comment]
Additionally, the german translation is "Enterhakenkanone" instead of (probably) "Taktische Enterhakenkanone" (don't have the german rulebook "Harte Ziele"...).
