### ISSUE TITLE
Cyber eyes max rating to high

### ISSUE THREAD

**Issue by Erkusandor** [chummer5a/chummer5a#3786]
Don't know if it is a bug, but my Google-Fu came up with nothing and i don't have the time to re-read every book cyberware related. 

The max rating of cyber eyes in Chummer is 6, but in the books it is 4.

**Comment by chummer5a** [comment]
It got updated in one of the most recent books, either No Future or Better Than Bad. We don't have a mechanism in place for allowing content of one book to override another.
