### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by TsukasaTheRed** [chummer5a/chummer5a#3789]
### Environment
Crash ID: cd3d1919-375b-410b-8b80-764ffd2dc209
Chummer Version: 5.207.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
We need actual details about what was happening when it crashed, please. Hard to troubleshoot otherwise.
