### ISSUE TITLE
Missing Books - even if all are enabled

### ISSUE THREAD

**Issue by OLRobert** [chummer5a/chummer5a#3792]
**Describe the bug**
In Chummer before 5.207.x, my group created several characters and enabled all "books" at 
Tools -> Options
Character Options & Optional Rules. 
No matter if I swith the application language to German or Englisch, the character could not get opened as there is a messag epopping up showing:
Missing Books
This character was created with the following books that are not enabled:
State of the Art ADL (German Handbook) (SAG) 
This may cause issues. Do you want to continue loading the character?
Ja / Nein (Which is Yes / No) 

In this case, the character got 
  <createdversion>5.202.0</createdversion>
  <appversion>5.207.0</appversion>
  <gameedition>SR5</gameedition>
  <settings>default.xml</settings>

Other caracters, e.g. 
  <createdversion>5.207.0</createdversion>
  <appversion>5.207.0</appversion>
  <gameedition>SR5</gameedition>
  <settings>default.xml</settings>
mention other books to be missing. 

Cleaning everything from "chummer" in the Windows 10 registry makes the tool running again, but this is some work which in no real fun :-) 

**To Reproduce**
On my systems (Two laptops and one fat client, this issue occurs easily. 
Don't know where this issue might be based on. 
I stored Chummer in my google drive but open it from the local copy of my data. 

**Expected behavior**
I'd like to open the characters without this warning as the books are enabled in the graphical configuration. 

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1903 (current / latest)

**Additional context**
I was able getting chumemr up and running cleaning all"chummer" related stuff from the windows registry but the error came up after several chummer starts.

**Comment by DelnarErsike** [comment]
Could you provide us with some of the affected character savefiles? It would help to know what part of the savefiles is causing the issue.

**Comment by OLRobert** [comment]
[NSC.zip](https://github.com/chummer5a/chummer5a/files/3460221/NSC.zip)
No problem. This is just an NSC character.

**Comment by OLRobert** [comment]
After updating to 5.207.73, the error is shown again.
![chum](https://user-images.githubusercontent.com/42408066/63880174-8813fa00-c9cd-11e9-97c8-46c731c06075.jpg)

after deleting regstry 
Computer\HKEY_CLASSES_ROOT\Chummer
Computer\HKEY_CURRENT_USER\Software\Chummer5
Computer\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION\Chummer5.exe
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched\Path2Chummer
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched\Path2Chummer5.exe
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.chum5
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.jpg\OpenWithList\h
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pdf\OpenWithList\g
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store\Shortcut2Chummer
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store}Path2Chummer5.exe 2*
Computer\HKEY_CURRENT_USER\Software\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Tracing\Chummer5_RASAPI32
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Tracing\Chummer5_RASMANCS
Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\EventLog\Application\Chummer

and re-configuring chummer plus re-loading the characters, it works...

**Comment by chummer5a** [comment]
Well, the problem is that you've got the ShadowNET rules enabled, which flag that book as hidden. We've run into this a bit before, with customdata rules being incorrectly enabled on first launch. Generally the fix is to empty out the customdata directory in the registry, after which it behaves properly. Aside from that, broadly working as intended.
