### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Tinman13** [chummer5a/chummer5a#3797]
### Environment
Crash ID: 1d34d703-0d9c-4c74-9337-4acb4977ffd5
Chummer Version: 5.207.16
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: False
Installation ID: 00000000-0000-0000-0000-000000000000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by ArchonMegalon** [comment]
Hi @Tinman13  !

We need a bit more information about the crash. If possible, could you download the latest nightly, enable upload of all logs in the options and "do again, what seems to have caused the crash" please. 

If it crashes again please provide the installtion id (it is a tooltip over the logging combo-box).
