### ISSUE TITLE
Problem with Knowledge Skills (yet again) Help me?

### ISSUE THREAD

**Issue by Haekel** [chummer5a/chummer5a#380]
Hey folks, me again.

So, recently printed a char of mine, and to my dismay, all knowledge skills are listed as rank 1.

So I opened my pre-career-mode save and, yes, the skills do have more than one level. "Okay", I think, "No problem, just edit the file in Notepad, easily done". Nope.

Basically, some arcane problem is screwing me up here.  My knowledge skills look like this (yes, Bars and Clubs is not exactly academic, I know... :P ):

			<id>00000000-0000-0000-0000-000000000000</id>
			<name>Bars und Clubs</name>
			<skillgroup />
			<skillcategory>Academic</skillcategory>
			<grouped>False</grouped>
			<default>False</default>
			<rating>4</rating>
			<base>0</base>
			<karma>4</karma>
			<freelevels>0</freelevels>
			<ratingmax>12</ratingmax>
			<knowledge>True</knowledge>
			<exotic>False</exotic>
			<spec />
			<allowdelete>True</allowdelete>
			<buywithkarma>False</buywithkarma>
			<attribute>LOG</attribute>
			<source />
			<page />
			<skillspecializations />
			<totalvalue>4</totalvalue>

"Rating", is, I assume, the total skill rating. 4 is correct, according to my old file.
"Base" is, I assume, the starting values from character creation, whereas
"Karma" is, I assume, the bought points after creation (or with leftover karma, during creation)

What Chummer shows me, though, is a total skill level of 1. Regardless of the numbers in the three values I specified above. If I change them all to 4, (including the "free levels", because I have no idea what I am doing), the skill level is now... 5?  What? Which I can raise to 6 for 0 Karma. Help folks, my brain is crashing.

The char has been created in an older version of Chummer 5a. I am using an upgraded version of Chummer 5a, and as far as I  am concerned, it is up to date. Language is set to German. Shout if you need more specifics.

**Comment by chummer5a** [comment]
Hrm. Does it only show up like that when you print it, or when you look at it in the application? Could you upload your character file?

**Comment by Haekel** [comment]
http://www.filedropper.com/brinenewcareer-kopie

Keep in mind that I fiddled with the numbers (since I was trying to find out which value did what), so they will probably look odd. 

http://www.filedropper.com/brinenewcareer

This is the unadulterated version. Should be JUST before I started fiddling. As you can see, all ratings show as 1, despite the pre-career mode having some skills at 4, so I guess something didn't carry over a few months ago. I just happened to notice the values now (tells you a lot about how often I actually use my knowledge skills, heh). Not sure if this one helps.

**Comment by Shiwo** [comment]
Greetings,

I have the same issue with 5.174

Not just in print mode but in the application as well.

When I open a charater, the Knowledge skill rating became to 1 (even if the file contain a higher rating.)
And of course it will save with the imporper value.

I found this issue with Characters created with Karma method.

Created with Priority works fine for me.

**Comment by chummer5a** [comment]
Fixed in 5.175.
