### ISSUE TITLE
Improvement: Attribute Level not working for negative values

### ISSUE THREAD

**Issue by Erkusandor** [chummer5a/chummer5a#3800]
As title. Noticed this bug because i wanted to change the way Dracoform in chummer works (as the quality augments the attribute values instantly, which is difficult as you are not always in dracoform and they are not augmentations but addjustments).

**Comment by chummer5a** [comment]
Apologies for the long delay in response. AttributeLevel is designed to act as a paid increase to the selected attribute. In that case, it doesn't support negative values. If you want to counteract Dracoform bonuses, you should be able to use the Attribute custom improvement to add negative values.
