### ISSUE TITLE
Heavy Weapon Mount gun ignores skill

### ISSUE THREAD

**Issue by Gugax** [chummer5a/chummer5a#3801]
**Describe the bug**
Heavy Weapon Mount gun ignores skill and shows 2 dice instead

**To Reproduce**
Add MCT-Nissan Roto-Drone + Heavy Weapon Mount (remote, fix, external) + add a stoner ares m202 + get heavy weapons skill 6
-> dicepool is still 2 instead of skill+attribute

**Expected behavior**
It should show a dice pool of 11

**Screenshots**
![zz](https://user-images.githubusercontent.com/40381762/62425084-5d3ccb80-b6d7-11e9-946a-78663b9f349f.jpg)
![zzz](https://user-images.githubusercontent.com/40381762/62425085-5d3ccb80-b6d7-11e9-991b-4c3ab41c892b.jpg)

**Character File**
[Etou.txt](https://github.com/chummer5a/chummer5a/files/3464994/Etou.txt)

**Desktop (please complete the following information):**
OS: Windows 10
Version: 5.207.50

**Comment by chummer5a** [comment]
Vehicle-mounted weapons in create mode use dog-brain mode, calculated off
their parent's targeting autosofts and Pilot Rating. Not a big problem to
fix, just need to add a dropdown that lists the firing mode types.

**Comment by JSteger** [comment]
Btw you do not use Heavy weapons with turrets no matter the size. For turrets you have the Gunnery skill.
