### ISSUE TITLE
Revitilisation Bioware Missing

### ISSUE THREAD

**Issue by MiraNoir** [chummer5a/chummer5a#3811]
**Is your feature request related to a problem? Please describe.**
Bioware Missing: Revitalization

**Describe the solution you'd like**
Add Bioware or Add Revitalization Function

**Describe alternatives you've considered**

**Additional context**

**Comment by cnschu** [comment]
i can see no error description here. Whats the problem? whats the expected behavior?

**Comment by chummer5a** [comment]
He's talking about the Revitilisation treatment from Chrome Flesh. It's unimplemented because it can only restore specific kinds of essence holes, which aren't implemented currently.
