### ISSUE TITLE
2050-Versions of Cyberlimb Customizations and Augmentations not working correctly

### ISSUE THREAD

**Issue by Steichelab** [chummer5a/chummer5a#3814]
Version: 5.207.0.0
OS: Win 10 pro (Version 1809; installed 05.05.2019; Build 17763.613)

**Describe the bug**
Unfortunately the 2050-Versions of Cyberlimb Customizations and Augmentations for arms and legs are not working correctly.

What I discovered:
1) The version of the limb (2050/2075 or Obvious/Synthetic) is irrelevant.

2) As you can see, the 2050 Customizations do not add their bonuses to the limb.
![Arm Custom 2050](https://user-images.githubusercontent.com/54069576/62947444-ce206980-bde2-11e9-9695-08b1e76e923b.png)

3) The 2075 Customizations work with the 2050 arm, but the 2050 Augmentations don't.
![Arm Augment 2050](https://user-images.githubusercontent.com/54069576/62947523-f5773680-bde2-11e9-8720-60a6f604062f.png)

4) Both, 2075 Customization as well as Augmentation, work with the 2075 arm.
![Arm 2075](https://user-images.githubusercontent.com/54069576/62947620-235c7b00-bde3-11e9-9d9d-812bcadd5fc2.png)

5) Exchanging the 2050-versions with the 2075-versions leads to wrong costs (125k instead of 62.25k)
![2050 full](https://user-images.githubusercontent.com/54069576/62948170-2e63db00-bde4-11e9-804e-654154e48d7b.png)

![2075 full](https://user-images.githubusercontent.com/54069576/62948171-2e63db00-bde4-11e9-94a9-cedba425ecaf.png)

I don't need the character in the near future, but I would like to finish it soon.

Thank you very much in advance

**Comment by chummer5a** [comment]
Ah, the magic strings attack again. Easy fix, will be in the next nightly.

**Comment by Steichelab** [comment]
Version: 5.207.72

Hi,
it's me again.

The Customizations work like a charm, but now the Enhancements / Augmentions don't work. 
![Enhan Aug 5-207-72](https://user-images.githubusercontent.com/54069576/63712027-1311ba80-c83d-11e9-92ba-f285431b824b.png)

Sorry for continuing to bother you.
