### ISSUE TITLE
Gear can't be added to critters.

### ISSUE THREAD

**Issue by Zeidra-Senester** [chummer5a/chummer5a#3818]
**Describe the bug**
When trying to generate a new critter which has an inventory (<gears> structure), the software crashes because of a reference to a missing item.

**To Reproduce**
Either creating a custom critter that includes a <gears> structure and try to generate it, or add Unwired as a book source and try to generate a metasapient AI (already defined in critters.xml, supposed to have programs inside its inventory).

**Expected behavior**
Using <gears> withing a <critter> metatype is supposed to add the specified <gear> items to its inventory. <gears> is recognized as a proper <metatype> subitem in critters.xsd. It is useful for AI critters, and a musthave for pre-generated brute NPCs (what I'm trying to make).

**Desktop (please complete the following information):**

    OS: Windows 10
    Version: 5.207.61 (but same with any older version)

**Log file :**
[chummer_crash_132104370311781311.txt](https://github.com/chummer5a/chummer5a/files/3510661/chummer_crash_132104370311781311.txt)

**Comment by chummer5a** [comment]
That's not a gear crash, that's a null reference in the quality. Can you show me an example of the critter you're working on?
