### ISSUE TITLE
Melee cyber weapons installed on cyberarms don't seem to use cyberarm stats

### ISSUE THREAD

**Issue by kjdawson80** [chummer5a/chummer5a#382]
I did a brief search through the issues and didn't find it (maybe my search-fu isn't that great), but when I add spurs, hand razors, or hand blades to my cyberarm, it doesn't use the cyberarm's stats. I deleted the arm, switched it to different positions (left lower vs right lower), swapped out weapons, etc.

It shows up correctly when I first add everything:
The cyberarm, with customization: 
![image](https://cloud.githubusercontent.com/assets/14282955/9863340/9940e68a-5b04-11e5-9a75-ae5c63c920c5.png)
The spurs, before saving and closing the file: 
![image](https://cloud.githubusercontent.com/assets/14282955/9863398/2322a050-5b05-11e5-83d4-2d0f0b316482.png)

But once I re-open the same file, I get this...
The spurs, under Street Gear/Weapons: 
![image](https://cloud.githubusercontent.com/assets/14282955/9863345/a0e6ac08-5b04-11e5-8f0f-61541cde11a6.png)

It's the same with synthetic and obvious cyberarms. Is there a setting I need to look at/adjust, or is this a bug of some sort?

**Comment by chummer5a** [comment]
It'll be a bug. Cyberlimb stats got broken at some point during the
previous developer's work on Chummer, and I haven't spent any time looking
into it yet.
