### ISSUE TITLE
Karma not refunding when taking "Paradigm Shift: Toxic"

### ISSUE THREAD

**Issue by 0x6a646f65** [chummer5a/chummer5a#3821]
**Describe the bug**
When taking Paradigm Shift: Toxic or Paradigm Shift: Insect Shaman, the karma cost of the initiation is not refunded

**To Reproduce**
1. Create a Magician
2. Mark as created
3. Initiate
4. Take either metamagic "Paradigm Shift: Toxic" or "Paradigm Shift: Insect Shaman"

**Expected behavior**
Per the rules in FA, when taking Paradigm Shift: Insect Shaman, or Paradigm Shift: Toxic, the magician is gifted the cost of the initiation.  The expected behavior is that the cost of initiation is refunded.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version: 5.207.53

**Additional context**

**Comment by chummer5a** [comment]
Can be worked around by just granting the karma, easiest implementation would be a prompt for an improvement type that grants karma according to the prompted value. Otherwise would have to provide metamagic-specific behaviour.
