### ISSUE TITLE
State of the Art ADL cybersets calculate wrong

### ISSUE THREAD

**Issue by JoshuarTree** [chummer5a/chummer5a#3828]
**Describe the bug**
the cybersets allow upgrades, which update the installed software.
These updates are not used for calculation.

**To Reproduce**
1. Go to cyberware
2. Add Siemens Cyberspine
3. Add Siemens Cyberspine upgrade Elite Warrior
4. See Reaction stays on 2d6

**Expected behavior**
Reaction should be 3d6

**Screenshots**
-

**Character File**
-

**Desktop (please complete the following information):**
 - OS: Windows 7/10
 - Version Chummer5.207.0

**Additional context**
- also happens with other enhancements for cybersets

**Comment by JoshuarTree** [comment]
tested in Carreer mode and also not working

**Comment by chummer5a** [comment]
Looks like you're referring to the wireless bonus not working between the reaction enhancers and wired reflexes. 

The problem with this is that the bonuses are matched against the name of the cyberware, but the matching also includes the parent name. Generally this is intended behaviour, but it doesn't interact well with subsystem cyberware. Need to have a ponder about how to handle it.

**Comment by geraltscharnweber** [comment]
i cant add siemens cyberspine at all
