### ISSUE TITLE
[Feature Request] Hide Mutagenic Qualities

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#383]
While it's nice to have a function to show only Mutagenic qualities, could a function be implemented to hide them, since they're generally only available after a player has purchased one of the Changeling qualities for the character?

**Comment by joha4270** [comment]
That should be possible easily. I don't quite remember the infected rules, it might even be possible to only show them if you have one of the changeling qualities.

**Comment by chummer5a** [comment]
Yeah, I was basically thinking we flip the bit on the hide/show metagenetic
qualities, then default it to showing them if the character has changeling.
From there you can turn on the metagenetics if you want access to the
negatives. Easy.

**Comment by chummer5a** [comment]
Included in 5.174.

**Comment by HaikenEdge** [comment]
It's back again.

**Comment by chummer5a** [comment]
Positives should only be present if you have Changeling. Negatives are intentionally available for all characters, per the rules.
