### ISSUE TITLE
No Save Button For Changes To Options

### ISSUE THREAD

**Issue by ChopperSniper** [chummer5a/chummer5a#3836]
Chummer 5.207.70 doesn't have an button to save changes to your options. Gyazo pictures for proof.

https://i.gyazo.com/3ec7810f9f7a2aa3e0629d96e4450d2c.png

https://i.gyazo.com/c3938294c0f3df1045bde92d9aa76604.png

**Comment by ArchonMegalon** [comment]
closed in #3837
