### ISSUE TITLE
Essence cost of Augmentations not showing until augmentation is chosen

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#384]
In previous versions of Chummer, while shopping for augmentations, the essence cost of the piece of ware would be shown in the dialog box while you were going through the list. Now, the Essence cost of all items are listed as 0, and only after you've selected the augmentation can you find out what the essence cost is.

**Comment by joha4270** [comment]
(CENCORED), i was sure i had that working

To the debugging table.

**Comment by HaikenEdge** [comment]
Now that I'm starting to go through the items, some of the essence costs for the augmentations themselves might be wrong; for example, when I put in a Standard Rating 3 Control Rig, which should only cost 3.0 Essence, it's coming back as costing 6.0 Essence. Likewise, Spurs, which should cost 0.3 Essence, are coming back as costing 0.6 Essence, as are Reaction Enhancers.

**Comment by joha4270** [comment]
I cannot reproduce that part, are you sure you don't change essence costs
somewhere?

2015-09-15 16:38 GMT+02:00 HaikenEdge <notifications@github.com>:

**Comment by HaikenEdge** [comment]
I just tried it on a fresh character, and it's not coming up anymore, so it might be a matter of having loaded an older character. My bad there.

**Comment by chummer5a** [comment]
Unable to replicate in current build, assuming it's fixed.
