### ISSUE TITLE
Issue: - custom_critters.xml crashes upon loading Salish Golden Boar

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3845]
### Environment
Crash ID: b3dde2f6-135b-40f3-a2c7-10c01fea6d17
Chummer Version: 5.208.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: 7498f263-dac6-46ec-996a-fa196e73d88a

### Expected behaviour
I'm trying to add some 4E critters updated to 5E. The golden boar from "Running Wild" was tackled first. I'm hoping to convert critters from dual-statted adventure books (like "Elven Blood") which offer both 4E and 5E statblocks and eventually submit them for the next stable.

### Actual behaviour
The golden boar from "Running Wild" loads if the name Golden Boar is used despite a new GUID (it's like legacy 4E code unlocks if you call a critter something from RW, and it pulls the 4E code instead of the new one). Upon changing to Salish Golden Boar, it shows the proper statblock preview as in: https://cdn.discordapp.com/attachments/523325762347073556/618456325403312149/unknown.png

However, it crashes upon an attempt to load. 

### Steps to reproduce the behaviour
Drop the XML into the data folder of Chummer, then apply New Critter => Paranormal Critters => Salish Golden Boar => Load.

[custom_critters.zip](https://github.com/chummer5a/chummer5a/files/3570073/custom_critters.zip)

**Comment by cnschu** [comment]
custom_critters.xml seems faulty.

**Comment by chummer5a** [comment]
Nah, no real problem with the XML, it's just the duplication of name. Metatype selection in the main branch is still done by name. I'm working on a fix for that in the https://github.com/chummer5a/chummer5a/tree/idbasemetatype branch, but it's a fairly chunky change.
