### ISSUE TITLE
Add Natural Recovery pool to Right Pane

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3848]
**Describe the solution you'd like**
As title: add a Natural Recovery dice pool to the right pane.
The pool is BOD+WIL by default, but can be modified by qualities, etc.
Besides being a useful quick reference, this would also allow more modifiers to be accounted for in a quick reference.

**Describe alternatives you've considered**
This pool would be a nice addition to BOTH the Other Info tab and the Condition Monitor tab.
Other Info tab: because this is one of the miscellaneous derived stats.
Condition Monitor tab: because when you roll Natural Recovery, you'll likely be dealing with the CM boxes immediately.
It wouldn't hurt to have it displayed in both tabs.

**Comment by ArchonMegalon** [comment]
I guess it should be ok, if this is only in the CM Tab...

![image](https://user-images.githubusercontent.com/11421547/65601119-c9360480-dfa1-11e9-91bb-15fff3205d1c.png)

**Comment by ArchonMegalon** [comment]
Closed with  #3890
