### ISSUE TITLE
Relationship tab not showing full details of bottom character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3852]
**Describe the bug**
When a character has sufficient contact to fill the list (collapsed), expanding the bottom contact does not show the contact details (Metatype, Sex, etc.).

**To Reproduce**
1. Add enough contacts to fill the contact list (collapsed)
2. Click on 'expand' for the lower contacts
3. Scroll down to bottom

**Expected behavior**
The lower character is expanded it shows fully.

**Screenshots**
![contacts](https://user-images.githubusercontent.com/17562417/64438157-346c7500-d08d-11e9-8d62-71f1a208b138.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.208.2

**Comment by chummer5a** [comment]
Hrm, can't replicate it on windows 10. I have a suspicion it's something to do with the resolution, but I didn't think there was a minimum size on that panel.

**Comment by DelnarErsike** [comment]
Could you double-check this to see if the issue is still in the current Nightly?

**Comment by Lochabar** [comment]
The bottom characters open correctly.
