### ISSUE TITLE
Forearm snap blades with wrong specialisation

### ISSUE THREAD

**Issue by Erkusandor** [chummer5a/chummer5a#3854]
The dice pool of forearm snap blades is correctly calculated with the blades skill (unless i'm missing some errata). Yet if you want to learn a specialisation in blades for them, there is none. On the other hand if you learn a specialisation in Unarmed Combat, there IS an option for forearm snap blades.

**Comment by chummer5a** [comment]
The only RAW specialisations for unarmed combat are Blocking, Cyber Implants, Subduing Combat, and [Martial Art]. You can type in the name and it'll match up though.
