### ISSUE TITLE
Negative metagenic qualities dis-allow movement of character to Career Mode

### ISSUE THREAD

**Issue by cuckooman** [chummer5a/chummer5a#3857]
**Describe the bug**
Creating a character with any SURGE quality and adding negative and positive Metagenic Qualities until they equal each other results in the Check Character Validity menu stating that qualities are unbalanced (in my case that Negative Metagenic Qualities is -27 instead of 26 or 27.

**To Reproduce**
1. Create a character with a SURGE quality and matching Karma amounts of Negative and Positive Metagenic Qualities
2. Click on the 'Special' tab
3. Scroll down to 'Check Character Validity'

**Expected behavior**
The character should be allowed to move to career mode (if all other requirements are met)

**Character File**
[Bleeding Edge.txt](https://github.com/chummer5a/chummer5a/files/3594674/Bleeding.Edge.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise build 1803
 - Version: 5.208.9

**Comment by chummer5a** [comment]
Whups. Sorry about that, will be fixed in next nightly.
