### ISSUE TITLE
Thrown weapons ammunition is always "1"

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3861]
**Describe the bug**
Thrown weapons listed in the Ranged Weapons block are always listed as "1" even if there are more that 1 in the gear block.

**To Reproduce**
1. Using a character with more than 1 in a particular thrown weapon
2. Print the character
3. Scroll down to 'Ranged Weapons'
4. See the "Ammo" column for all thrown weapons always contains 1
5. Scroll down to 'Gear'
6. See the Qty for the thrown weapon is more than 1

**Expected behavior**
The ammo column for thrown weapons show the quantity of the thrown weapon.

**Screenshots**
Entries from Gear
![gear](https://user-images.githubusercontent.com/17562417/64749066-dd75fe00-d4d9-11e9-81eb-5008821fec60.png)

Corresponding entries in Thrown Weapons
![ranged](https://user-images.githubusercontent.com/17562417/64749086-f088ce00-d4d9-11e9-91aa-d1d7a9cf41df.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home
 - Version: 5.201.12 [and earlier]

**Additional context**
The saved XML file has an ammo node under the thrown weapon of "1". The corresponding gear node has qty of the correct value.

**Comment by chummer5a** [comment]
Hrm. That'd be because as far as the weapon is concerned, it has a clip size of 1 and doesn't know about loose ammo. Kind of a pain to refactor it to work differently for just those. Easiest alternative would be making an 'available ammo' int.

**Comment by Lochabar** [comment]
Requested changes applied with #4308
