### ISSUE TITLE
Feature Request: Remove all Config-Items from Windows registry

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3862]
Sorry for re-creating this Feature request again but I cannot re-open the first one.
This is NOT a duplicate #3532 even though they are somewhat related. However #3532 only considers custom data files / directories for different playing groups. This request however aims at improving overall portability of Chummer across multiple installations.
I have removed from this Feature Request any reverences to sharing between playing groups with different settings etc. as that was not the main focus of this issue. Also I have removed the idea of splitting settings in any way as I understand that ALL settings should be global. But imho even global stuff should - as a general rule - not be stored in the Windows registry as that make application non-portable and less maintainable.
  
**Is your feature request related to a problem? Please describe.**
In case of using a shared installation (e.g. running Chummer from a Google Drive) options changes often need to be made across multiple machines because many option items (e.g. the enabled books) are stored in the windows registry.

**Describe the solution you'd like**
All options should be moved to the settings file, no information should be written into the windows registry as that makes settings non-portable.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/25143888/64762125-da145e00-d53d-11e9-988b-77dd694395ba.png)

**Comment by ArchonMegalon** [comment]
That is something we want to get to anyway for better portability. I wonder, if the "store all the custom data for a group" should be the next thing i implement for sinners. Not sure, how often that would actually be needed, since the use case seems rather niche.

**Comment by Nedorus** [comment]
Well improving portability would be the first step. And should be rather straight forward.

If we get the second step later on (group specific configs) that would be nice. But ... a second step 😂
