### ISSUE TITLE
Add Improvements for Matrix Attributes

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3870]
**Is your feature request related to a problem? Please describe.**
Improvement options for Matrix Attributes would be handy for things like programs.

**Describe the solution you'd like**
As above: add the option to create custom Improvements that modify Matrix attributes.

**Comment by drakir75** [comment]
That exists?

**Comment by chummer5a** [comment]
Gear items can already do this; we haven't implemented it in Chummer as there's currently no tracking of running programs, so you'd have all effects active at the same time.
