### ISSUE TITLE
Hobgoblin Karma Cost Issue

### ISSUE THREAD

**Issue by MiraNoir** [chummer5a/chummer5a#3871]
**Describe the bug**
Hobgoblin cost is -5 on Race Priority C, and +5 on Race Priority B

**To Reproduce**
1. Prime Runner
2. Click on Race B or C
3. Choose Orc
4. You will see it change from +5 to -5 and vice versa when you change over, when creating, the karma is 30 and 40 respectively

**Expected behavior**
Stay the same

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.208.2]

**Additional context**

**Comment by chummer5a** [comment]
That's what it says it costs on the table. Working as intended.
