### ISSUE TITLE
Data: Shiawase Caduceus gear missing

### ISSUE THREAD

**Issue by aga9** [chummer5a/chummer5a#3876]
**Describe the bug**
The Shiawase Caduceus "CAD" 7 anthrodrone is missing a few gears.

**Expected behavior**
As listed in B&B 23, the CAD comes with:
Mechanical arms x2, with Snake Fingers
Rigger Adaptation
Medkit (4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.208

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/ba594d80be485e1ee2b5c03e47fd6c0ff0e5dd20
