### ISSUE TITLE
Reaction enhancers do not add to REA if Level is lower or same as Wired Reflexes

### ISSUE THREAD

**Issue by JoshuarTree** [chummer5a/chummer5a#3879]
Describe the bug
Reaction Enhancers add only level minus Wired Reflexeslevel
(Wired Reflexes1 + Reaction enhancer 3 give +3 instead of +4)

To Reproduce

Go to cyberware
Add Wired Reflexes (1) (REA +1)
Add Reaction Enhancers (1) (REA does not change -> should be REA+2)
change Reaction enhancer to (2) (REA +2 ->should be REA +3)

OR

Go to cyberware
Add Wired Reflexes (3) (REA +3)
Add Reaction Enhancers (1) (REA does not change -> should be REA+4)
change Reaction enhancer to (2) (REA does not change -> should be REA+5)
change Reaction enhancer to (3) (REA does not change -> should be REA+6)

Screenshots
Character File
Desktop (please complete the following information):

OS: Windows 7/10
Version Chummer5.208.0
Additional context

**Comment by drakir75** [comment]
That's because it's conditional (wireless on only). Have to change that in improvements tab.
I guess you mean Wired Reflexes+Reaction Enhancers? No other combo can give an attribute bonus over 4.

**Comment by JoshuarTree** [comment]
You are right!
In german, wired reflexes are called reflex booster.
I modified the issue to the correct wording.

**Comment by drakir75** [comment]
Still, it's a wireless on only bonus. Chummer does not have a toggle for any wireless bonuses on anything yet. (Smartlink etc). If you want the bonus to be visible, you can do that in career mode. Under the improvements tab.

**Comment by chummer5a** [comment]
Hm? Yes it does, wireless bonuses have been a thing for a while now.

**Comment by JoshuarTree** [comment]
Tested, works in career mode with normal cyberware, but not with cybersets from SOTA ADL

**Comment by drakir75** [comment]
Does not work for me (WR rating 2, Rea Enhancers rating 1. Rea bonus only +2). 
Smartlink does not add dice. (Not working)
Attention Coprocessor does add dice. (works)
