### ISSUE TITLE
Weapon "Accessories" for Holdouts

### ISSUE THREAD

**Issue by ppaland** [chummer5a/chummer5a#388]
You can not add weapon accessories to holdouts in chummer, which is of course correct according to the rules. The problem is that pieces like spare clips and holsters can also be selected as weapon accessories and that is currently impossible to do for holdouts.

I suggest to allow adding all accessories to holdout pistols that do not need mod slots.

**Comment by chummer5a** [comment]
It's actually supposed to do that already. I need to redo the modification system to support Run and Gun's extra mod slots properly anyway..

**Comment by chummer5a** [comment]
Implemented in 5.177.
