### ISSUE TITLE
Ability Autosoft for Vehicle and Drones is bugged

### ISSUE THREAD

**Issue by JSteger** [chummer5a/chummer5a#3887]
**Describe the bug**
Currently you cannot specify the skill to which this autosoft is linked (ex. mechaniks skills for repair drones).

**To Reproduce**
1. Go to Vehicles and drones
2. Click on add equipment
3. Select the ability autosoft or the restricted ability autosoft and buy
4. normally now a dropdown field should show up to select the skills but instea the empty autosoft is added to the vehicle/drone

**Expected behavior**
just as in the streetequipment section (for example adding the ability autosoft to the riggerconsole) it should open a skill selection dropwdown

**Screenshots**

**Comment by chummer5a** [comment]
Yeah, it's a known issue that crops up due to vehicles not triggering the improvement system. If you buy the autosoft on your character directly and transfer it to the vehicle it'll work as expected.
