### ISSUE TITLE
Sleeping Tiger availability

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3888]
**Describe the bug**
Chummer does not allow Sleeping Tiger armor when saving to career mode because of the RPC.

**To Reproduce**
1. Create a legal character.
2. Buy the sleeping tiger armor
3. Try to save as created

**Expected behavior**
To be able to buy the Sleeping tiger without workarounds. 
(Buying a credstick for 13.5k or more)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.208.25

**Additional context**
Thanks for all the work done with Chummer.

**Comment by darksnakezero** [comment]
Confirmed this bug today 27.09.2019 13:44.

The Availability check should ignore all items/upgrades with the "part of base armor" option activated.
