### ISSUE TITLE
Getting really slow download times for the latest version of Chummer5 (ver. .208) 

### ISSUE THREAD

**Issue by Kyoto-Kid** [chummer5a/chummer5a#3889]
Download froze at 2.6MB (out of 19.2 MB) then failed.  Successive attempts to download resulted in same failure.

OS W7 64 SP1 Home Edition.  

I expected a smooth quick download of the latest Chummer update as occurred in past sessions. I have no issues downloading other files from other sites so it is definitely not on my end.

**Comment by ArchonMegalon** [comment]
Have you an older version installed? There is a "auto update" switch in the options. Have you tried enabling it and starting the old version, so that the in-client-update tries to download it?

**Comment by Kyoto-Kid** [comment]
...went in and checked that but nothing is happening.  I used to always download straight from GitHub with no issues.  iIt isn't my AV either or I would get a popup message.
