### ISSUE TITLE
Free Knowledge/Language Skill Points Multiplier

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#389]
Unless it's been errataed (in which case, I can't find it in the core rules errata), characters only get free Knowledge/Language skill points equal to their (LOG + INT) x2; however Chummer has this multiplier set to x3.

**Comment by chummer5a** [comment]
Legacy settings issue. If you delete your settings file or toggle the optional rule for your karma multiplier on and off it'll go back to normal.
