### ISSUE TITLE
Stun Condition amount missing from Other Info sidebar

### ISSUE THREAD

**Issue by cuckooman** [chummer5a/chummer5a#3893]
**Describe the bug**
The Other Info sidebar seems to display Stun Condition as being blank, rather than displaying the character's number of Stun Condition boxes

**To Reproduce**
1. Create a character
2. Click on 'Other Info'

**Expected behavior**
The number of Stun Condition boxes to be shown.

**Screenshots**
![stunmonitor](https://user-images.githubusercontent.com/11006657/65610716-a1e33580-dfa9-11e9-8218-af269d5103ef.png)

**Character File**
[Sandman.txt](https://github.com/chummer5a/chummer5a/files/3653013/Sandman.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise build 1803
 - Version 5.208.26

**Additional context**
The Physical Condition line seems to function perfectly.

**Comment by cuckooman** [comment]
Addendum: Upon restarting Chummer and reloading the file, the Stun Monitor now works. Very strange.
![stunmonitorkindaworking](https://user-images.githubusercontent.com/11006657/65611526-d99ead00-dfaa-11e9-8e42-5538b526233d.png)

**Comment by ArchonMegalon** [comment]
I close this for now. If it happens again please comment or ping me.
