### ISSUE TITLE
Power and combat spellcasting focus both adding to dice pools in 5e

### ISSUE THREAD

**Issue by Mlippo** [chummer5a/chummer5a#3894]
**Describe the bug**
Both Power focus and combat spellcasting focus are adding to combat dice pools

**To Reproduce**
1. Go to Gear
2. Click on Add Gear
     Add power focus rank 1
     Add Spellcasting focus, combat rank 2
     Bind both foci
3. Go to Skills, Spellcasting, see Power focus added to dice pool
4. Go to Spells and Spirits, any combat spell, see Spellcasting Focus, combat added to dice pool

**Expected behavior**
Only the highest force focus should add to the dice pool

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 5.208.0

![chummer_spellcasting](https://user-images.githubusercontent.com/44910818/65651766-78440180-dfdd-11e9-9582-eb4dc5ee01d9.png)
![chummer_manabolt](https://user-images.githubusercontent.com/44910818/65651769-7aa65b80-dfdd-11e9-9e27-09bb18db8707.png)

**Comment by MemeticContagion** [comment]
I took an (amateur) stab at fixing this: https://github.com/chummer5a/chummer5a/pull/3946
