### ISSUE TITLE
Broken character encoding in HTML export files (via Wine)

### ISSUE THREAD

**Issue by davidfoerster** [chummer5a/chummer5a#3902]
I know running Chummer via Wine is not supported officially but I feel (as a software developer myself) this would be a simple fix – maybe in my system configuration rather than Chummer itself.

**Describe the bug**
When I export a character sheet to an HTML file and open it in a web browser or text editor, the resulting file contains lots of “�” characters (U+FFFD, replacement character) where non-ASCII characters are supposed to be. The issue only occurs only when I run Chummer via Wine on Linux; on Windows (inside a virtual machine) the character encoding is fine.

 * affected templates: apparently all
 * tested templates: [“Shadowrun 5” and the game master overview](https://github.com/chummer5a/chummer5a/files/3692451/Hive.zip)
 * template language: de-DE

**To Reproduce**
1. Open any existing or create a new character
2. Open the print dialogue, select the language “de-DE” and the template “Shadowrun 5” and export to HTML.
4. Open the exported HTML file in your favourite web browser.
5. See various “�“ as early as in the personal stat block.

**Expected behavior**
Instead of “�” there should be appropriate non-ASCII characters (e. g. “Größe” instead of “Gr��e”) as in the export from Windows.

**Screenshots**
![Hive](https://user-images.githubusercontent.com/959587/66242673-57c52700-e702-11e9-915f-1bd744d4ac67.png)

**Desktop (please complete the following information):**
 - OS: Wine 4.17 (emulating Windows 7 or Windows 10 – I tested both) using `dotnet452` on Ubuntu 18.04 (occurred with earlier Wine versions too if I managed to get Chummer to work at all).
 - Version 5.208.0 (occurred in earlier versions too)

**Additional context**
It looks like some process tries to transform the data stream from one (restricted, maybe ASCII?) character encoding to another and, failing to find appropriate encodings for non-ASCII characters, replaces unknown characters with the above placeholder. No idea why this occurs on Wine/Linux but now Windows. Maybe Chummer or .NET fail to detect the default system file encoding?

The locale environment doesn’t appear to play a role. I tried `de_DE.UTF-8`, `en_US.UTF-8` and `C` to no avail.

```
$ winetricks list-installed
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-4.17 (Staging) and WINEARCH=win32
baekmuk
dotnet40
dotnet452
```

**Comment by chummer5a** [comment]
Chummer writes HTML output to a UTF8 stream, no reason it shouldn't work. Probably wine doing wine things

**Comment by Ramesch** [comment]
Could you possibly test if changing the encoding of the file './sheets/en-de/xy.language.xslt' from 'UTF-8' to 'UTF-8-BOM' (byte order mark) solves the problem?

Just use an editor with the appropriate function, open the file, convert and save it again.

This will add a character at the beginning of the file content to mark it as UTF-8 encoded (this is not mandatory for utf-8-coded files, but might help for Wine)? Under Windows, nothing changes in the output. If it helps that the output of Chummer works correctly under Wine, maybe we could resave the xslt-files accordingly.

**Comment by davidfoerster** [comment]
> Could you possibly test if changing the encoding of the file './sheets/en-de/xy.language.xslt' from 'UTF-8' to 'UTF-8-BOM' (byte order mark) solves the problem?

Thanks for the tip! Unfortunately it doesn’t change the issue.

I used `unix2dos -m …` to add the BOM and `file` now reports:
```
xz.en-us.xslt:          XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
xz.language.xslt:       XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
de/xz.de.xslt:          XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
de/xz.language.xslt:    XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
de-de/xz.language.xslt: XML 1.0 document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
```

**Comment by chummer5a** [comment]
Does it look fine in the web browser view?

**Comment by davidfoerster** [comment]
@chummer5a Yes, the preview is fine.
