### ISSUE TITLE
Search functionality in Treeviews on street gear tabs

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#3909]
**Is your feature request related to a problem? Please describe.**
When having a lot of gear it's hard to find a specific item in tree views

**Describe the solution you'd like**
Add a free text search that filters the tree view content by the given string

**Describe alternatives you've considered**
An option to find a specific item in street gear lists

**Additional context**

![grafik](https://user-images.githubusercontent.com/42451897/66603519-a6fcd300-ebac-11e9-9164-aed7a543f040.png)

**Comment by chummer5a** [comment]
Treeviews aren't really built for easy filtering. Easiest way to go about it would likely be adding a parent ID and Node ID to each treenode in a collection, stored separately in a dictionary. When a linked textbox has text entered, query the dictionary into a list of matching IDs. Loop through the list; if it's a root level node add it, if it's not and the node isn't present already in the treenodes, iterate through the list to find the new parent, add it, add the current node, then proceed to the next. Checking for uniqueness would be the big trick.

Probably easier just to do highlighting if the text matches.
