### ISSUE TITLE
Infirm negative quality is still the 4th edition version

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#391]
In 4th edition: Double the cost to learn Physical Skill, and can not learn Physical Skill Groups.

In 5th edition: For every 5 Karma, the character drops all of their Physical Attribute maximums by one. The quality can be taken up to five times, but no Attribute maximum can be dropped below 1.
Along with this natural cap, the character can never have a Physical Attribute modified beyond this maximum by any source—magic, machine or otherwise—as their body is too frail to handle the stress.

**Comment by chummer5a** [comment]
Fixed in 5.175.
