### ISSUE TITLE
Oni Negative Qualities counting towards limit

### ISSUE THREAD

**Issue by bas9** [chummer5a/chummer5a#3910]
**Describe the bug**
Unable to take 25 karma's worth of negative qualities when selecting Oni.

 

**To Reproduce**
1. File > New Character
2. Leave all options at default (Priority, Standard, 25 Starting Karma, Maximum Availability 12, Nuyen Karma Max 10, Ignore Character Creation Rules checkbox unchecked)
3. Click OK
4. Change priorities: Resources 'A', Attributes 'B', Metatype 'C', Skills 'D', Magic 'E'
5. Change Metatype to 'Ork', Change Metavariant to 'Oni'
6. Add Negative Qualities
   - first I added Code of Honor (Orks), 15 karma
   - then I added Poor Self Control (Vindictive), 5 karma (total 20 karma of negative qualities)
   - then I tried to add Big Regret (Testing) (a 5 karma negative quality). I got the error message 'You cannot gain more than 25 Karma from Negative Qualities and Metatype.'
   - next I tried to add Accident Prone (a 4 karma negative quality). I got the same error message.
   - finally I added In Debt (a 1 karma quality). This was successful. If I try to add another level of In Debt, I get the same error message.

**Expected behavior**
Expected to be able to take 25 karma worth of negative qualities for all metavariants regardless of priorities.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.
Oni that can't take 25 pts of negative qualities: [Oni Guy.txt](https://github.com/chummer5a/chummer5a/files/3714969/Oni.Guy.txt)
[Fuzzy Elf.txt](https://github.com/chummer5a/chummer5a/files/3714970/Fuzzy.Elf.txt)
[Drunk Gnome.txt](https://github.com/chummer5a/chummer5a/files/3714971/Drunk.Gnome.txt)
Oni that can take 25 pts of negative qualities: [Successful Oni.txt](https://github.com/chummer5a/chummer5a/files/3714989/Successful.Oni.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.208.0.0

**Additional context**
This was a bug supposedly fixed in https://github.com/chummer5a/chummer5a/pull/243, so I'm pretty sure it's not working as intended.

Just for giggles, I tried making another character with the default priorities, made them an Elf (Nocturna metavariant), and tried giving them negative qualities. Their racial negative qualities would add up to 17 Karma, but I was able to give this character AIPS (a 10 Karma negative quality). No error message.

I also tried making a dwarf with the priorities in step 4 (Gnome metavariant). Gnomes have Neoteny, a 6 karma negative quality. I gave them Addiction (Severe) (Booze), a 20 karma negative quality. This also worked.

Making an oni with the default priorities, I was also able to give him Code of Honor, Poor Self Control (Vindictive), and Big Regret.

**Comment by bas9** [comment]
I did some more poking around, I think I have a lead: 

1. Create new character
2. Metatype is priority 'A' by default. Select the oni Metavariant. The karma cost is listed as 4:
![ChummerBug01](https://user-images.githubusercontent.com/56416062/66621524-92233e00-ebb2-11e9-8473-cb6bd660797e.png)
3. Change Metatype priority to 'B'. Karma cost is still 4:
![ChummerBug02](https://user-images.githubusercontent.com/56416062/66621751-3e652480-ebb3-11e9-87e0-990e66dfad87.png)
4. Change Metatype priority to 'C'. Karma cost is...-4?
![ChummerBug03](https://user-images.githubusercontent.com/56416062/66621765-4e7d0400-ebb3-11e9-8900-17099e8c8c25.png)

**Comment by chummer5a** [comment]
That's actually RAW; in the table, Oni and Hobgoblins are listed as having an additional karma cost of +4 and +5 respectively, at priority C. The explanation I've been given in the past is that their negative qualities are enough of a drawback at priority C that it's worth a refund in karma.
