### ISSUE TITLE
Qualities missing from UI, but are present in datafiles

### ISSUE THREAD

**Issue by Immanius** [chummer5a/chummer5a#3912]
**Describe the bug**
Certain qualities are missing from the UI, even though others from the same source are present. The one that I have been testing with has been "Friends in High Places". I've peeked at the datafiles, and that quality is still in the data file (if I'm understanding them correctly). I've gone back through releases and the issue was not present (at least for "Friends in High Places") in 5.205, but was present in 5.206.

I'm pretty sure I've not seen others that should have been there, but "Friends" is the quality that I decided to start testing with to confirm. So, while I can't say for certain, it is probably affecting other qualities as well. Please keep in mind that certain qualities from Chrome Flesh **ARE** appearing in the list, so this is not just a "source not selected" issue, and has the potential to reach across all sources.

**To Reproduce**
0. Fresh install after ripping anything that starts with chum (case insensitive) from the registry on windows
1. Enable all sources (or just chrome flesh)
2. create a new character (seemingly any combination of starting options, but i have not been exhaustive)
3. try to add the positive quality "Friends in High Places" i've both searched the list, and searched via text with ignore ruleson and off, and/or show all qualities on/off
4. See error: Quality is missing.

**Expected behavior**
I would expect all of the qualities from the selected sources that are present in the data files to show in the quality selection screen and be able to be added to the character sheet.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version multiple

**Other**
Repeating the above steps starting with 0 for each install while working back the issue persisted until 205, after 205, i did not clear out the registry and it appears to have fixed the issues with 206 and 208 (skipped 207 due to 208 being 207 with an autobuild system update)

**Additional context**

**Comment by Zitchas** [comment]
Using 5.208.45 creating a new character "Friends in High Places" comes up as expected.

Are there any qualities missing from the most recent version (208.45 or higher when they come out)? 

I don't think it is very likely that Chummer5a will go back and fix missing things in previous versions.

**Comment by Immanius** [comment]
It was happening for me in the nightly 208 build (as of three days ago), however after working my way back to 205, I am unable to reproduce the issue. Since I don't know anything about how the program actually runs, what I am about to say is probably completely wrong, but I would like to try and help. Is it possible that there is something that gets put in the registry that is not cleared out between versions that could impact this behavior?

**Comment by chummer5a** [comment]
Some customdata rulesets (Missions, for example) ban certain qualities, which we achieve in Chummer by adding a Hide node. I'd have to guess that's what's going on.

**Comment by Immanius** [comment]
and would that affect it even if "ignore creation rules" was on?

**Comment by chummer5a** [comment]
Yup, ignoring creation rules mostly just turns off validation for nuyen and availability limits and such.
