### ISSUE TITLE
Foci not listed in bonding box

### ISSUE THREAD

**Issue by Hughmanrunner** [chummer5a/chummer5a#3914]
**Describe the bug**
Characters that are awakened or have a magic score cannot Bond new foci. The foci will appear in their inventory, but won't be listed in the "Bonded Foci" box of the Street Gear tab.

Replicated with both characters created entirely in v 5.208.0 and with ones created in earlier version. 

**To Reproduce**
1. Create new character as magician or aspected magician (possibly others)
2. Add a focus to the character, with purchase or free. 
3. Focus should be listed in the box but it isn't

**Expected behavior**
Once the focus is purchased the focus should be in the Bonding box, allowing it to be bonded (by checking the box). It's not showing at all. 

**Screenshots**
![BondedFocusFail](https://user-images.githubusercontent.com/56777827/67153545-1905a400-f2a0-11e9-8fa0-966a279f7168.JPG)

**Character File**
[focustest-4-pre.chum5.txt](https://github.com/chummer5a/chummer5a/files/3747359/focustest-4-pre.chum5.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1803

**Comment by chummer5a** [comment]
That's because that's a formula to make a focus, not a focus itself.
