### ISSUE TITLE
Infected qualities have no karma cost

### ISSUE THREAD

**Issue by lonki5767** [chummer5a/chummer5a#3917]
**Describe the bug**
Chossing any ghoul and some HMHVV I quality(rest of them not checked) don't have any kind of karma cost in KarmaGen and SumtoTen (prioirty not tested)

**To Reproduce**
Create any ghoul character in SumToTen or KarmaGen.

**Expected behavior**
It supposed have karma cost. It is not free.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
Windows
5.208.57
**Additional context**
I have not checked rest of the infected but i think they will have same problem

**Comment by chummer5a** [comment]
Should be working properly in .58.
