### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by DistantCosmos** [chummer5a/chummer5a#3919]
### Environment
Crash ID: 75bb25a8-09e6-46b2-b63b-b15cfdbc8936
Chummer Version: 5.205.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
To display details about a custom drug when it was clicked on.

### Actual behaviour
Displayed details, but them immediately crashed

### Steps to reproduce the behaviour
Make custom drugs possibly more then one and then attempt to delete one. (This also didn't work for me). Then save the character, reopen the sheet and try to click on the drug.

**Comment by chummer5a** [comment]
Please update to a newer version and re-test. This issue was resolved in a previous build.

**Comment by DistantCosmos** [comment]
Thank you. I had some problems after updating at one point and have bin dragging my feet doing it again.

**Comment by DistantCosmos** [comment]
I will add if I can that after updating I still can not delete custom drugs from the list and it also seems to display Crush (Level 2) under components when Crush Level 3 was selected, it still seems to have calculated the stats using Crush level 3 it just displays the the other one.

**Comment by chummer5a** [comment]
Yeah, that's being worked on in a separate branch. Building in improvement functionality, taking a while.
