### ISSUE TITLE
Exception when opening Critters

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3923]
**Describe the bug**
Since a few (nightly) versions ago I was no longer able to open critter-type chummer files.

**To Reproduce**
1. Create a new critter
2. save the critter
3. close the file
4. try to reopen the critter file
5. observe the crash

**Expected behavior**
both critter and character files can be opened.

**Screenshots**
n.a.

**Character File**
n.a. (any critter file)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.208.61] (possibly earlier versions)

**Additional context**
n.a.

**Comment by Nedorus** [comment]
Tried to create a pull request but I seam to lack the rights to create anything.
So here's what i found locally:
When loading critters the metatype info is read from critters.xml and the decision to read from critters.xml or metatype.xml is made before the "iscritter" value is available so we get a null pointer exception.

In clsCharacter.cs you need to move this line:

xmlCharacterNavigator.TryGetBoolFieldQuickly("iscritter", ref _blnIsCritter);

from line 2325 at least line 2160 (just before the reading the // Metatype information.)

**Comment by chummer5a** [comment]
To make a pull request, you need to make a branch on your own fork, then create the pull request from that. Thanks for pointing out the fix though, will have it committed shortly.
