### ISSUE TITLE
Full Body Armor missing?

### ISSUE THREAD

**Issue by unknown-user-prime** [chummer5a/chummer5a#3926]
Using Chummer version 5.208.0.  So last night I was doing some preplanning looking at what kind of gear I wanted to get with some sweet nuyen that I got and one of the things I was looking at was Full Body Armor.  It was there last night and when I tried to purchase it today on chummer for my character.  It disappeared.  Gone, no longer there.  Not sure if I did something or not but if I did.  Is there a way to bring Full Body Armor  The only thing I can find is Form-Fitting Armor and Full Face Mask but no Full Body Armor.  Thanks in advance.

**Comment by chummer5a** [comment]
14R, probably over availability limit.

**Comment by unknown-user-prime** [comment]
Thank you!! That was it. I just unchecked the show only 12 availability and it appeared on the list.
