### ISSUE TITLE
Can't open a saved AllySpirit Critter file

### ISSUE THREAD

**Issue by seansols** [chummer5a/chummer5a#3930]
### Environment
Crash ID: f83bae46-c9df-421c-8994-d4b70d8fdf29
Chummer Version: 5.208.72
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: f5557f26-e8ea-4581-8e28-2b1de1949996

### Expected behaviour
can open a saved Ally Spirit Critter file

### Actual behaviour
crashes and asks me to fill this out

### Steps to reproduce the behaviour
Create a New Critter -> Ally Spirit ( I chose Force 10, Materialization)
Save the file
Close the file
Open the file
Crash

### Additional information
Creating other Spirits (plant, man, air, etc) seems to work fine as I've made several and can reopen them.

**Comment by chummer5a** [comment]
Can you upload the file please?

**Comment by seansols** [comment]
[crashes.txt](https://github.com/chummer5a/chummer5a/files/3823190/crashes.txt)
the Chum5 file? I changed the extension because Git isn't accepting Chum5 types.

**Comment by chummer5a** [comment]
[crashes_fixed.txt](https://github.com/chummer5a/chummer5a/files/3827972/crashes_fixed.txt)
It'll be fixed in the next nightly, but this file should also behave as expected.
