### ISSUE TITLE
Issue: - First launch of 5.209.0 crashes

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#3937]
### Environment
Crash ID: 128b15c3-2944-42b3-9dc1-94f2d97a863e
Chummer Version: 5.209.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: d5df2560-e278-408b-9a26-233348778406

### Expected behaviour
A normal app launch.

### Actual behaviour
The app crashes with the following error:

![image](https://user-images.githubusercontent.com/38818521/69012434-0ac9a700-0976-11ea-9d37-4a18afcd5b50.png)

![image](https://user-images.githubusercontent.com/38818521/69012460-52503300-0976-11ea-94c7-0fe823bbb17a.png)

Chummer fails to compile a crash report.

### Steps to reproduce the behaviour
Try launching the stable's EXE on Windows 10.

**Comment by ArchonMegalon** [comment]
Pretty sure, this is my mess. Will take a look at it once i'm at my dev place next week.

**Comment by ArchonMegalon** [comment]
Actually I'm not sure if this is resolved. @KeeperM can you please try it again with the next nightly?

**Comment by ArchonMegalon** [comment]
...closing this for now. I guess the patch worked...
