### ISSUE TITLE
Feature Request: RunnerHub MysAd Update

### ISSUE THREAD

**Issue by darays** [chummer5a/chummer5a#3938]
As Chummer currently supports an option for Runnerhub rules, Could the files be modified to support the following ruling:

"Mystic Adepts may choose which magical skill group (Conjuring, Enchanting, or Sorcery) to lose at gen, and must mark which one in their post to /r/hubchargen. "

I was able to modify the "Choose Character Priorities" menus to add the Enchanting skills to the drop down choices.  I cannot, however, find the files that populate the Skills tab to make the Enchanting skill group, and the associated skills, appear in the lists.

**Comment by chummer5a** [comment]
Actually those rules are deprecated as of https://github.com/chummer5a/chummer5a/issues/3776. If they're still in there, it's from an old version of Chummer you've updated. It isn't in current releases. There hasn't been anyone willing to take over the responsibility of keeping the files updated in lockstep with that ruleset. That said, I'm not sure we have that level of behaviour in Chummer in general. I'd have to fab something up for it I think.

**Comment by darays** [comment]
I pulled the relevant rules directory from the master repository when the option was no longer available

On a related note, I would be willing to help with that.

**Comment by chummer5a** [comment]
```xml
<skillgroupdisablechoice amendoperation="addnode">
  <skillgroup>Conjuring</skillgroup>
  <skillgroup>Enchanting</skillgroup>
  <skillgroup>Sorcery</skillgroup>
</skillgroupdisablechoice>```
