### ISSUE TITLE
Trust Fund Quality requirement

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#394]
The Trust Fund quality requires the SINner (National) or SINner (Corporate) negative quality as a prerequisite; however, currently, Trust Fund only becomes available to characters with SINner (National) or SINner (Corporate Limited), instead of SINner (Corporate). In fact, SINner (Corporate Limited) does not quality a character for Trust Fund.

**Comment by cfresquet** [comment]
simple data fix in qualities.xml - pull request submitted.

**Comment by chummer5a** [comment]
Fixed in 5.175.
