### ISSUE TITLE
"Collapsed Frame" Weapon Accessory

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#395]
The 700 Nuyen accessory on Run and Gun's page 32, which is purported to be the "Collapsed Frame" under weapon accessory, is actually a custom silencer for the PSK-3 Collapsible Heavy Pistol.

**Comment by chummer5a** [comment]
Actually the collapsed frame is supposed to represent the box... thingy, that it collapses back into. I've removed the cost for the frame, though.
