### ISSUE TITLE
optional powers for infected from Dark Terrors

### ISSUE THREAD

**Issue by Harlekin13** [chummer5a/chummer5a#3951]
Somewhen after 5.209.0 infected characters (i can only speak for ghouls and harvesters for now) lost the ability to learn the optional powers they got in dark terrors.

In 5.209.0 it was possible to select them, in 5.209.17 (the first nightly build i tried) and 5.209.18 (the latest i have until now) not anymore.

**Comment by chummer5a** [comment]
Seems fine to me, what do they seem to be doing for you?

**Comment by Harlekin13** [comment]
Strange. There aren't any of them anymore even in the 5.209.0 version on my computer. I'm sure they were available when I first tried to build the latest batch of characters, but got to the point of issue #3949, for which i went through all combinations of metavariant and possible infected qualities. i'm sure i saw optional powers available for standard-elf-harvester and standard-human-ghoul.
But now they don't even appear in the list at all.

The new critter powers are there, but under "allowed optional powers" is nothing. But I am able to select powers which i shouldn't be allowed to take, even powers only free spirits are allowed to take, and chummer tells me the character is valid. Please take a look at the screenshots (standard-human-ghoul, nothing else than adding ghoul quality
![the problem part 1](https://user-images.githubusercontent.com/34014817/70395730-f7a07900-1a01-11ea-9ecc-5b2b4b4d9229.png)
![the problem part 2](https://user-images.githubusercontent.com/34014817/70395732-f7a07900-1a01-11ea-83a9-7264f1d7e415.png)

 done).

**Comment by Harlekin13** [comment]
btw. when i opened 5.209.20 a few minutes ago for the first tim i got this error:
![opening 5 209 20 for first time](https://user-images.githubusercontent.com/34014817/70395754-54039880-1a02-11ea-9c0d-3b62de475b08.png)

That shouldn't have anything to do with this issue, right?

**Comment by chummer5a** [comment]
The daredrenaline thing should be fixed in current nightlies. I was lazy and didn't test a data merge.
