### ISSUE TITLE
Bug: Troll Reduction Bioware interacts incorrectly with Orthoskin and Dermal Plating

### ISSUE THREAD

**Issue by MaiFlow** [chummer5a/chummer5a#3952]
**Describe the bug**
The Troll Reduction bioware modification incorrectly applies the armor penalty associated with removing the troll natural armor bonus to Orthoskin and Dermal Plating.

As a related, minor issue, Troll Reduction does not completely cancel out the Dermal Alteration (Barkskin) quality that the Giant meta-variant gets.

The Metatype Reduction(Troll) cyberware alteration does not seem to be affected, although it does not alter the natural armor in the first place, which might be a separate bug

**To Reproduce**
1. Create a new character of the Troll metatype.
2. Go to the Cyberware/Bioware tab and apply the Troll Reduction bioware modification. The rating does not seem to have any impact.
3. Hover over the armor value under "Other Info". The armor value should now be 0, and the tooltip should display "Armor (0) + Metatype(1) + Troll Reduction (-1)". This is expected behavior.
4. Apply Dermal Plating or Orthoskin at Rating 1. 
5. Armor remains at 0. The tooltip now reads "Armor (0) + Metatype(1) + Troll Reduction (-1) + [Orthoskin/Dermal Plating] (1)". The last entry will depend on what was applied in step 4.
6. Further increasing the rating of the augmentation correctly applies the increased rating, but the total armor value will remain 1 less than expected. 

**Expected behavior**
The armor for the augmentation should apply to Trolls that opt for Troll Reduction the same way it does for normal characters. Buying Dermal Plating or Orthoskin at Rating 1 after applying Troll Reduction should result in an armor rating of 1, barring other increases to armor.

**Desktop**
 - OS: Windows 10]
 - Version: 5.209.0]

**Comment by chummer5a** [comment]
Thinking out loud, the problem is that the armor bonus is grouped amongst the various skin things, but the penalty isn't. So it picks the highest available armour bonus of the group, then the penalty's applied on top. Not much of an easy way to fix it since there's currently no such creature as an improvement group like 'skin' or 'bones' or whatever. Probably need to do something along those lines.
