### ISSUE TITLE
Feature Request: Gear markup/discount in create mode

### ISSUE THREAD

**Issue by MaiFlow** [chummer5a/chummer5a#3953]
**Is your feature request related to a problem? Please describe.**
As a house rule, I sometimes want to apply discounts to prices of items during character creation. This may be because of campaign specific factors, or simply changing prices due to personal preference. This is not possible to do in Create mode.

**Describe the solution you'd like**
Implement Career style markup field to purchases in Create mode.

**Describe alternatives you've considered**
The current workaround is having players bring their money out of Create mode and make their purchases in Career mode. This is very inconvenient, as it does not give the same flexibility as Create mode in regards to point and resource allocation.

**Comment by chummer5a** [comment]
Campaign-specific changes should be done through amend files to ensure consistency for all players. Otherwise the burden is on the GM/approver to validate that all costs are accurate.

**Comment by chummer5a** [comment]
As an example, if I wanted to change the price of a datajack to 50 nuyen, I'd use a file called amend_cyberware.xml with the following structure. 
```xml
<chummer>
  <cyberwares>
    <cyberware>
      <name>Datajack</datajack>
      <cost>50</cost>
    </cyberware>
  </cyberwares>
</chummer>
```
https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files#amend-data-files
