### ISSUE TITLE
Feature request: dropdown menu for initiation

### ISSUE THREAD

**Issue by Harlekin13** [chummer5a/chummer5a#3954]
I really struggled to find the possibility to add metamagics to initiated characters, I stumbled across it when accidentialy rightclicking on the grade.
Perhaps it would be good to add a similar dropdown menu to the button "add initiate grade" as it is there on "add gear" or "add cyberware"? That way one can easily see there is more on that tab than only adding initiate grades.

**Comment by ArchonMegalon** [comment]
Closed with #3978
