### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by oceya** [chummer5a/chummer5a#3956]
### Environment
Crash ID: c3f040be-500a-4683-9443-f171ce33d6fb
Chummer Version: 5.209.26
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 6495cad4-eec2-46c1-9d83-ea6e755fa9b7

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
No log telemetry, no description. Please provide details about the issue and I'll reopen it.
