### ISSUE TITLE
Cyberware plugin essence hole interactions

### ISSUE THREAD

**Issue by Sevasta** [chummer5a/chummer5a#3959]
Chummer Version: 5.209.35

**Expected Behaviour**

An essence hole when adding a piece of cyberware that takes capacity inside another piece of ware (such as ears, eyes, or a limb)  is not changed, as there is no essence being used up

**Actual behaviour**

Putting, for example, antennae inside a cyberear while an essence hole is present refunds the essence cost of the hole directly to the character's essence. This does not repeat itself if the essence hole's value is reduced to 0 and the plugin capacity functions as designed from that ponit forward.

**Steps to reproduce the behaviour**

Make character with essence hole

Add ware that is able to have other ware installed inside it (Cyber ears, cyber eyes, limb) that has an essence cost less than that of the essence hole, leaving some essence hole behind

Add plugin to that piece of ware. Observe essence score increase and essence hole value decrease.

**Comment by chummer5a** [comment]
lel clsoes
