### ISSUE TITLE
Truncated text in the options dialog for German and French language

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3962]
**Describe the bug**
It's a bit annoying that the options dialog with French and German language constantly shows scroll bars; especially since the window enlargements made are not saved, so that the scroll bars will be back next time. Could the size of the options window possibly be changed from 1063 x 875 to 1120 x 875 (French only needs 1090 but German 1120)?

But this would again affect the options dialog with English language, so that you could (or should) use a little more space for the content there.

**To Reproduce**
1. Go to 'Tools' -> 'Options'
2. Change language to 'Deutsch (de-DE)' oder 'Français (fr-FR)'
3. See scroll bars

**Expected behavior**
Options dialog without scroll bars.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/43168497/71517980-732a7300-28a8-11ea-9fd8-7dcb10654b5b.png)

**Desktop:**
 - OS: Windows 10
 - Version 5.209.40

**Additional context**
As an alternative to enlarging the window as mentioned above, the columns for the contents could be made smaller, which might result in more line breaks. Or you could save the changes made to the window for future use.

**Comment by ArchonMegalon** [comment]
This is a constant tweaking of ... making the options bigger and bigger until another user complains, that the option dialog is to big for his resolution. Of course we can make it bigger (again), but this screams for another way to solve it. Maybe we should solve the window enlargements? Would that be a reasonable solution for you @Ramesch ?

**Comment by chummer5a** [comment]
I mean the real fix is https://github.com/chummer5a/chummer5a/tree/newoptions, but merging that beast makes my head hurt. Ghetto fix is Properties.Settings.Default.Properties, but that doesn't generally persist well across builds.

**Comment by Ramesch** [comment]
I think you're right, ArchonMegalon. Another option, a different screen resolution, a different translation will soon requires a next adjustment.

Would it be a solution to display the contents of the options - to the right of the source books - between the language settings and the PDF options in a single column only (instead of two colums) and to include a scroll bar only on the right side?

The dropdown menus for the language settings could then be a little smaller, so that the width of the whole window could remain as before or even be smaller again.

For the various options from life modules to the default settings for new characters, you could then use a kind of listing with checkboxes, which - only for the content part to the right of the source books - provides a scroll bar. Too long texts right from the checkboxes would then simply break at the right margin just in before the scroll bar and enlarge the content area downwards.

Since I cannot code, I do not know how complex such a dynamic content area within a fixes window would be.

Would this be a realisable solution?

**Comment by ArchonMegalon** [comment]
@chummer5a can I help with the merge of the newoptions somehow? Haven't took a look on it until now. I think I remember Delnar saying it's "finished". 

Or even better: can I encourage you to do it somehow, so that your brain hurts and not mine? ;D

**Comment by chummer5a** [comment]
I'll probably have to tap you on the shoulder for the reintegration of the sinners plugin with the new UI, but it compiles, so that's something. Need to fuck about with the MRU mechanisms, I just decoupled all that instead of dealing with it. Probably something else I'm missing as well. 
https://github.com/chummer5a/chummer5a/tree/newoptions_testmerge

**Comment by ArchonMegalon** [comment]
Will not be able to take a look at it till Tuesday - but I will!

**Comment by ArchonMegalon** [comment]
@chummer5a  ...hm the new options branch is... not really finished, is it? I mean the testmerge for example basically has no implementation for character options. Should I just reroute the options I think should be characteroptions through that class and still get the actual values from GlobalOptions.Instance.WhateverOption for now, so that we can at least merge this monster and then start to relocate the options one by one? Or am I working on an wrong/old branch?

**Comment by ArchonMegalon** [comment]
Commited some changes to bring the branch more up to date.

**Comment by Ramesch** [comment]
Currently, after a change in the last few days (https://github.com/chummer5a/chummer5a/commit/ce22d0258221229f00d0a027da37ed46749e66ec ?), the option window looks like this (size of the window is identical in each language):

![Unbenannt](https://user-images.githubusercontent.com/43168497/75103856-f80be180-55f8-11ea-9de2-4012dc629c08.png)

After a lot of work was put into a revision (see https://github.com/chummer5a/chummer5a/tree/newoptions): does 'it compiles' mean that you can test it in a nightly version? I mean, that's what nightly versions are for, right? 

Does this new version only affect the options menu or does it also solve other display problems such as weapon selection (see https://github.com/chummer5a/chummer5a/issues/3135)?

**Comment by chummer5a** [comment]
Newoptions still has more work that needs doing to it; no support for customdata or sinners plugin, among other issues.
