### ISSUE TITLE
Commanding Voice / Authoritative Tone

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3968]
In German rule books Authoritative Tone (SG 170) and Commanding Voice (SS 191) is translated using the same name ('Gebieterischer Ton'). 'Commanding Voice' (SG 170) has a cost of 0.25 power points per level (max 3) and 'Authoritative Tone' (SS 191) has a cost of 1 power point (see 'powers.xml').

Since German translation and German (custom) rule for this power is definitely wrong, I would like to correct this. But if there is a wrong english basis for this, I would adjust it as well.

Can anyone confirm that in the English rulebooks the two powers are different and correct with the above mentioned costs? If something is wrong in the powers.xml, could someone adjust it or tell the correct values?

**Comment by chummer5a** [comment]
It's due to the errata between Street Grimoire and Stolen Souls. 

> P. 170, COMMANDING VOICE CHANGE
> The version of Commanding Voice on p. 185, Stolen Souls, stands. This power is changed to Authoritative Tone, costs 0.50 PP per level (max 3), and is described as follows: Adepts with this power can speak in a way that immediately makes people want to believe them and follow their orders. For every level of this power, an adept gains a +1 die to any Opposed Social Skill Test that they initiate (normal limits apply).

**Comment by Ramesch** [comment]
So the English data remain unchanged. I have modified the German custom rule (https://github.com/chummer5a/chummer5a/pull/3969), so my issue is solved.

Thank you very much!
