### ISSUE TITLE
Missing Allergy Negative Quality Severities

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#397]
The Allergy Quality currently only has severity under the Common, Extreme, when it should have four: Mild, Moderate, Severe and Extreme.

**Comment by cfresquet** [comment]
The qualities.xml entries for the missing allergies have an extra data line:

   <metagenetic>yes</metagenetic>

If you delete these lines from the three problem severity entries, they will then load correctly.

**Comment by cfresquet** [comment]
Pull request submitted.
