### ISSUE TITLE
Non-selectable custom rules

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#3971]
There are several custom rules that have been created so far. However, these rules are not yet taken into account when compiling Chummer5a-package via 'Chummer.csproj' (therefore they are not available to users so far).

For the three custom rules 'German Data Changes ...' I have checked the content and added the rules for copying in 'Chummer.csproj' (see https://github.com/chummer5a/chummer5a/pull/3970).

For the extensive 'Custom Rules'
- 'Runnerhub Rules' and
- 'Shadowrunner's Hang-outs' House Rule'

I can't see for what purpose they were written. Should the last two rules also be included to Chummer5a-package?

If you want them to be added, I would do this via the file 'Chummer.csproj'. However, as I do not know the reason for the rules, I cannot verify whether they are correct.

**Comment by chummer5a** [comment]
Runnerhub rules was turned off intentionally since they requested that be done; nobody was willing to maintain it on their end or somesuch. 
Shadowrunner's Hang-outs I don't recognise?

**Comment by Ramesch** [comment]
Then I will not include both rules for now. If someone misses them, they can always be included later (as the files still exists).
