### ISSUE TITLE
Fox mentor spirit disadvantage checks WIL+CHA instead of WIL+INT

### ISSUE THREAD

**Issue by davidfoerster** [chummer5a/chummer5a#3985]
## Describe the bug
The description of the disadvantage of *Fox* mentor spirit (*State of the Art – ADL*, p. 121) contains an error and a minor translation issue (is there even an official translation?).

## Current text
> If Fox fights, it'll fight to kill. A follower of this mentor spirit must make a Willpower + *Charisma* (3) Test to spare *a bettered* foe.

(emphasis mine)

## Expected text
> If Fox fights, it'll fight to kill. A follower of this mentor spirit must make a Willpower + *Intuition* (3) Test to spare *an overpowered* foe.

(emphasis mine)

![fox-mentor-spirit](https://user-images.githubusercontent.com/959587/71991104-e632d280-3234-11ea-8808-88697e878b28.png)

## Additional context
This is likely a copy-and-paste error, as all other SAG mentor spirits have a WIL+CHA test for their disadvantage if any.

## Patch
[sota-adl-mentor-spirit-fox-fix.patch.txt](https://github.com/chummer5a/chummer5a/files/4036036/sota-adl-mentor-spirit-fox-fix.patch.txt)

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/pull/3986
