### ISSUE TITLE
Condition translations

### ISSUE THREAD

**Issue by gdelmee** [chummer5a/chummer5a#3989]
**Is your feature request related to a problem? Please describe.**
I'm not sure it's missing but I don't know if it's available and then how to do it properly.

For example, in gears or cyberwares, there are conditions applied to the use of it.
Currently printing a character sheet in French, the condition is in English.

![image](https://user-images.githubusercontent.com/17324443/72149616-d84f8f80-33a3-11ea-9399-ee7a583c00e4.png)

Looking at translation files, there are on tag to translate the condition.

For example, in gear.xml:
```
    <gear>
      <id>3f086e04-8de6-4d4e-a503-a19cba8295f5</id>
      <name>Spatial Recognizer</name>
      <category>Audio Enhancements</category>
      <rating>0</rating>
      <source>SR5</source>
      <page>445</page>
      <avail>+4</avail>
      <armorcapacity>[2]</armorcapacity>
      <bonus>
        <limitmodifier>
          <limit>Mental</limit>
          <value>2</value>
          <condition>Only for Perception to find the source of a sound</condition>
        </limitmodifier>
      </bonus>
      <capacity>[2]</capacity>
      <requireparent />
      <forbidden>
        <geardetails>
          <name>Microphone, Laser</name>
        </geardetails>
      </forbidden>
      <cost>1000</cost>
    </gear>
```

Then in fr-fr_data.xml, we have only
```
			<gear translated="True">
				<id>3f086e04-8de6-4d4e-a503-a19cba8295f5</id>
				<name>Spatial Recognizer</name>
				<translate>Reconnaissance spatiale</translate>
				<altpage>448</altpage>
			</gear>
```
How to add those additional translations?

**Comment by chummer5a** [comment]
Duplicates #2087. Long story short, we never implemented anything for translating Improvement things; the least ghetto option I've thought of so far relies on pulling the conditions into the lang files (instead of data) to translate with tags. It's doable, but irksome. I'd like to find a better solution for it than that.

**Comment by Ramesch** [comment]
That's not a great solution either: you could use a custom rule to replace all the condition entries with language specific ones. Would that be an acceptable solution (at least temporarily)?

**Comment by chummer5a** [comment]
Could do, but then the bonuses are locked at that value instead. It's broadly the same problem. Tag translation at least has the benefit of being portable across languages.
