### ISSUE TITLE
Movement and swim measurement translated in the sheet but not in the UI

### ISSUE THREAD

**Issue by gdelmee** [chummer5a/chummer5a#3992]
**Describe the bug**
Using Chummer in French, movement and swim are still in 'm/ hit' even it's properly translated in the character sheet.

I guess it's done in clsCharacter.cs:
![image](https://user-images.githubusercontent.com/17324443/72168887-5a54ae00-33ce-11ea-9c6f-17bd5e6a433f.png)

**Expected behavior**
Having the translation in the UI too.

**Screenshots**
Here in the UI:
![image](https://user-images.githubusercontent.com/17324443/72168932-6a6c8d80-33ce-11ea-8341-9d9b3784c493.png)

And where it's correct in the sheet:
![image](https://user-images.githubusercontent.com/17324443/72169287-1ada9180-33cf-11ea-8b9b-d6fab5fd0d3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.209.56

**Comment by ArchonMegalon** [comment]
That is an awesome bug report!
