### ISSUE TITLE
why not just set up lutris chummer 5e

### ISSUE THREAD

**Issue by pixiewolf9** [chummer5a/chummer5a#3994]
it uses wine as its background it setting it  one time time then it basiclly just click and install.
https://lutris.net/ lutis is big for games and regradless on what linux distro some one is running  its just one click install.

**Comment by chummer5a** [comment]
Same reason I didn't package it in a snap, ala #2483
I don't run Linux, I can't be bothered building a VM just to test it, nobody's built one to show to me.

**Comment by ArchonMegalon** [comment]
I'll take a look at that later that month if I can...
