### ISSUE TITLE
Optional rule is missing

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#3995]
**Describe the bug**
on loading my char i get this error:
![image](https://user-images.githubusercontent.com/12108972/72222822-409b9e00-3569-11ea-91e7-bd43361babb9.png)

This optional rule ist not to be found anymore
![image](https://user-images.githubusercontent.com/12108972/72222846-6c1e8880-3569-11ea-9825-42fc1f6da586.png)

**To Reproduce**
1. start chummer
2. open char
3. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by Ramesch** [comment]
That is correct and no mistake. Former rule was not complete and described only half the changes (see https://github.com/chummer5a/chummer5a/commit/52b8a08fc10a3e0dd0d19492abc86003fdde0e78). But you should get this message only once. Please press „Ja“ and save the character.

**Comment by ReallyDarkMatter** [comment]
Thanks that helped
