### ISSUE TITLE
Essence and MAG Calculation Buggy in Career Mode

### ISSUE THREAD

**Issue by Amazeroth** [chummer5a/chummer5a#4002]
Hey Chummers

Maybe i discovered a Bug within in the calculation of Essence and or MAG Attribute in The Career Mode.
When used the Upgrade Button to Upgrade lower grade of Cyberware to a higher grade, a Essence loss is shown and also a Loss at the MAG Attribute.
And when Deleting lower grade of Ware to exchange with a higher grade, than add the modification, the Essence is increasing.
And when Using the Upgrade Button The "Essencehole" is named acc. the First Item Upgraded eg.: Biomonitor.

and Maybe the MAG calcuation when lowering the essence between 3 and 2.
but I'm not sure with the rules.
I thought the essence falls only when you fall under a full number. eg.: below 3 or below 2.

I made a few tests to explain my problem and to reconstruct the Problem

The initial conditions are.

Mundane Orc Decker
Attributes and skills don't matter,
also the Equipment.

- Augmentations
 
Cyberware
- Antennae - Used	
- Cybereyes Basic System (Rating 2) - Used
   ->Flare Compensation
   ->Smartlink
   ->Low-Light Vision
   ->Thermographic Vision

- Cyberears (Rating 2) - Used
   ->Antennae
   ->Antennae 
   ->Sensor Array (Rating 8)
       ->Atmosphere Sensor
       ->Motion Sensor
       ->Olfactory Scanner
       ->Camera (Rating 8)
           ->Vision Enhancement (Rating3 )
       ->Omni-Directional Microphone (Rating 8)
           ->Audio Enhancement (Rating 3)
       ->X-Ray
       ->Ultrasound
       ->Directional Microphone (Rating 8)

- Datajack Plus (Rating 3) - Used

- Muscle Replacement (Rating 1) - Used

- Biomonitor - Used

Bioware

- Cerebellum Booster (Rating 1)
- Cerebral Booster (Rating 2)
 
 = Essence 2,94
 

![2020-01-17 22_41_10-Window](https://user-images.githubusercontent.com/60018164/72648255-e50f4d00-397a-11ea-8f43-1aae6e37c9e5.png)

Try 1 (The Upgrade Function At The Delete Button)
	1. Add Quality Mystic Adept to Add MAG Attribute Val: 1(1) Metatype Limits: 1/2(2), Essence 2,94
	2. Upgrade BioMonitor from Used To Alphaware
		now Essence Changed to 2,91; Essenchole is Named Biomonitor and Value is 0,05
		Also MAG Attribute Val Changed to 0, Metatype Limits 0/2
	3. Upgrade of Muscle Replacement
		Essence 2,59; Essence Hole named Muscle Replacement and has a Value of 0.80
		MAG Attribute Val Changed to 0, Metatype Limits 0/2
	4. Upgrade of Datajack Plus
		Essence 2,89; Essence Hole named Datajack Plus
		MAG Attribute Val Changed to 0, Metatype Limits 0/2
	5. Upgrade of Cybereyes
		Essence 2,84; Essence Hole named Cybereyes Basic System (Rating 2)
		MAG Attribute Val Changed to 0, Metatype Limits 0/2

Try2 (Delete Old Used and Add Alphaware new)
	1. Add Quality Mystic Adept to Add MAG Attribute Val: 1(1) Metatype Limits: 1/2(2), Essence 2,94
	2. Biomonitor - Used, deleted = Essence 2,94 und Essenchole 0,13; no change at the MAG Attribute
		Biomonitor - Alphaware, added = Essence 2,94 und Essenchole 0,05; no change at the MAG Attribute -> so it should be
	3. Datajack - Use, deleted = Essencehole 0,24
		Datajack Plus (Rating 3) - Alphaware , added = Essenchole 0,12; Essence und MAG no change
	4. Cybereyes -Used, deleted = Essenchole 0,5
		Cybereyes Basic System (Rating 2) in Alphaware added = Essenchole 0,26, Essence 2,94 and MAG Attribute no change.
		Modifications added 1. Flare Compensation; now Essenchole 0,18 and Essence 3,02, MAG Attribute Val: 1(1) Metatype Limits: 1/3(3)
			Essence is increased, soulden't be
		2. Thermographic Vision: Essence 3,10 und Essenchole 0,10
		3. Low-Light Vision: Essence 3,18 und Essenchole 0,02
		4. Smartlink: Essence 3,20 und Essenchole 0,00
	5. The same happens with the Cyberears

Try 3 At first Essence Drop, then ADD MAG and after this Upgrade of Items
	1. EARRS in Alphaware added; now Essence 2,34 
	2. Upgrade BioMonitor - Alphaware: now Essence 2,31 Essenchole is named Biomonitor and has a Value of 0,08
	3. Upgrade Datajcak Plus - Alphaware: now Essence 2,26 and Essenchole 0,20 still named Biomonitor
	4. Upgrade Cybereyes - Alphaware: now Essence 2,16 and Essenchole 0,44 still named Biomonitor
	5. Nanohive Soft Neocortical (Rating 3) in Alphaware added: now Essence 2,11 and Essenchole 0
	6. Quality Mystic Adept added
		now MAG Attribute Val: 1(1) Metatype Limits: 1/2(2)
	7. Upgrade Cyberears Rating 2 -> Rating 4 Alphaware; Essence drops to 2,1 und MAG Attribute Val auf 0(0) and Metatype Limits: 0/2(2)

Try 4 At first Essence Drop, then ADD MAG and after this Delete Used Items and Reinstall new Alphaware
	1. EARRS in Alphaware added; now Essence 2,34 
	2. Upgrade BioMonitor - Alphaware: now Essence 2,31 Essenchole is named Biomonitor and has a Value of 0,08
	3. Upgrade Datajcak Plus - Alphaware: now Essence 2,26 and Essenchole 0,20 still named Biomonitor
	4. Upgrade Cybereyes - Alphaware: now Essence 2,16 and Essenchole 0,44 still named Biomonitor
	5. Nanohive Soft Neocortical (Rating 3) in Alphaware added: now Essence 2,11 and Essenchole 0
	6. Quality Mystic Adept added
		now MAG Attribute Val: 1(1) Metatype Limits: 1/2(2)
	7. Cyberears (Rating 2) - Used and Antennae - Used deleted: now Essence 2,12 and Essenchole 0,51
	8. Cyberears (Rating 4) in Alphaware added: Essence 2,12 and Essenchole 0,11
		Modifications added 1st Antennae : Essence 2,20 and Essenchole 0,03
		2nd Antennae: Essence 2,23 and Essencehole 0
		3rd Antennae: Essence no change
		Sensor Array (Rating 8): no change
		Damper: no change
		Balance Augmenter: no change
	9. Muscle Replacement - Used; deleted Essence 2,23 and Essenchole 1,25
		Muscle Augmentation (Rating 1) in Alphaware: Essence 2,23 and Essenchole 1,09
		Muscle Tone (Rating 1) in Alphaware: Essence 2,23 and Essenchole 0,93
	10. Reaction Enhancers (Rating 2) in Alphaware: Essence 2,23 and Essenchole 0,45 and MAG Attribute Val still 1(1) Metatype Limits: 1/2(2)
	11. Orthoskin (Rating 3) in Alphaware: Essence 2,08 and Essenchole 0 and MAG Attribute Val auf 0(0) and Metatype Limits: 0/2(2)

Try 5 At first Essence Drop(but more), then ADD MAG and after this Delete Used Items and Reinstall new Alphaware
	1. EARRS in Alphaware added
		BioMonitor and Datajack deleted
		Biomonitor and Datajack in Alphaware added
		Nanohive(Soft) (Rating 3) Neocortical - Greyware added
			Essence dropped to 2,01
	2. Quality Mystic Adept added
		now MAG Attribute Val: 1(1) Metatype Limits: 1/2(2) 
	3. Cybereyes deleted and added new in Alphaware: now Essence 2,01 and Essenchole 0,14
		Modifications Flare Compensation : Essence 2,09 and Essenchole 0,06
		Thermographic Vision: Essence 2,15 and Essenchole = 0
		Low-Light Vision und Smartlink no mor change
	4. Cyberears und Antennae deleted and only added the Ears in Alphawar (Rating 4): Essence 2,15 and Essenchole 0,11
		Modifications 	1st Antennae: Essence 2,23 und and Essenchole 0,03
				2nd Antennae: Essence 2,26 und and Essenchole = 0
		3rd Antennae, Sensor Array (Rating 8), Damper and Balance Augmenter added; Essence 2,26 und MAG Attribute Val 1(1) Metatype Limits: 1/2(2)
	5. Muscle Replacement deleted; Essence 2,26 and Essenchole 1,25
		Muscle Augmentation (Rating 1) in Alphawar: Essence 2,26 und and Essenchole 1,09
		Muscle Tone (Rating 1) in Alphaware: Essence 2,26 und and Essenchole 0,93
	6. RReaction Enhancers (Rating 2) in Alphaware: Essence 2,26 und and Essenchole 0,45 and MAG Attribute Val still 1(1) Metatype Limits: 1/2(2)
	7. Orthoskin (Rating 3) in Alphaware: Essence 2,11 and Essenchole 0 and MAG Attribute Val 1(1) Metatype Limits: 1/2(2)
	8. Reflex Recorder Aplphaware: Essenz 2,03 and Essenchole 0 ; MAG Attribute Val 1(1) Metatype Limits: 1/2(2)

I am not sure if the MAG calculation is correct, but the Essence calculation is definitely buggy

Thanks

PS.
Using Windows 10 
CPU I5 4590

**Comment by chummer5a** [comment]
What version is this?

**Comment by Amazeroth** [comment]
ah Sorry
i Use 5.209.0
but i testet it on 5.209.56 (Nightly) also, same problem

**Comment by chummer5a** [comment]
I think this might be resolved in current nightlies due to a fix in the behaviour of esence hole ratings. Can you please test again in the current nightly build and let me know?

**Comment by Amazeroth** [comment]
Sorry for wating.
I tested it today with Nightly 5.210.96
But no change for the issue with the Essence value calculation and MAG Attribute.
The issue with the name of the Essence Hole is gone.
