### ISSUE TITLE
Books not showing up in To Use Field

### ISSUE THREAD

**Issue by goodhumor79** [chummer5a/chummer5a#4007]
Hey, so I just got a new laptop after my old one wouldnt start. I installed Chummer 5.209.0, and, in options, certain books show up in Sourcebook Info, but not in the Sourcebooks to Use tab.
All these books also don't have a "Selected Sourcebook PDF Location" field at the bottom of Global Options, while all the books that _do_ show up as options "To Use" have that field in Global Options.

Being rather limited in my technical knowledge, the only thing that I could think to do was edit the Settings.xml file to include the code abbreviations for the books that are missing (in the same format as the others), and it seems like this functionally fixed it. The books still don't show up in the "To Use" box, but when I'm adding items, the content from those books do show up.

The book abbreviations that aren't showing up are:

BLB
BB
DTD
HKS
SHB
SHB2
2050
SPS
SAG

So, I guess this isn't a big deal, but I though I'd keep it up anyway in case anybody else has this issue

**Comment by chummer5a** [comment]
That should generally only happen if you have a customdata file enabled that flags the books as hidden. None of the built-in customdata files do that, do you have any active files in the Custom Data section of the rules active?

**Comment by goodhumor79** [comment]
Thanks, looks like it was SR Missions 1.4
