### ISSUE TITLE
Issue: - Transfering loaded weapon onto a vehicle crashes

### ISSUE THREAD

**Issue by inund8** [chummer5a/chummer5a#4008]
### Environment
Crash ID: 46b182d5-598e-4a77-9e4a-aa0011a31817
Chummer Version: 5.209.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 9a6a0dc2-d217-4f62-b372-4977a550798f

### Expected behaviour
I loaded ammo into the SA Retarius XL Netgun then moved it on to a vehicle

### Actual behaviour
Crash after picking a slot to move it to

### Steps to reproduce the behaviour
Add  SA Retarius XL Netgun  to a slot on MCT Nissan Roto-drone with 2 slots, one filled

**Comment by chummer5a** [comment]
Can't replicate the crash in current nightlies; this might have been fixed?
