### ISSUE TITLE
Cannot add dependents multiple times

### ISSUE THREAD

**Issue by mudge6** [chummer5a/chummer5a#4016]
**Is your feature request related to a problem? Please describe.**
The dependents quality cannot be taken multiple times, I think this should be changed.

**Describe the solution you'd like**
We should be able to have multiple sources of dependents.

**Comment by chummer5a** [comment]
It's a single quality that doesn't say it can be taken multiple times.

**Comment by mudge6** [comment]
sure it may not explicitly say it, but what if someone wants to take it multiple times? (which is why im here)

**Comment by chummer5a** [comment]
In that case you'd use an amend file to add the allowmultiple node to the quality. For Dependents, you'd make a file called amend_qualities.xml with the below text inside it, placed inside either the data folder or a subfolder of customdata. You'll see that we have three amendoperations going on in the code. The first adds a "limit" node to the xml, which tells the XML Manager to add the node, with the internal text of the node allowing you to take the qualities unlimited times. The second removes the 'forbidden' node, which prohibits taking the qualities if you've purchased one of the others.
The last is more of a quality-of-life thing, adding a selecttext node to the bonus node. This will have the quality prompt you for text to add to it, allowing you to show which dependent is which. 

```xml
<chummer>
  <qualities>
    <quality>
      <name>Dependent (Nuisance)</name>
      <limit amendoperation="addnode">False</limit>
      <forbidden amendoperation="remove"/>
      <bonus>
        <selecttext amendoperation="addnode"/>
      </bonus>
    </quality>
    <quality>
      <name>Dependent (Inconvenience)</name>
      <limit amendoperation="addnode">False</limit>
      <forbidden amendoperation="remove"/>
      <bonus>
        <selecttext amendoperation="addnode"/>
      </bonus>
    </quality>
    <quality>
      <name>Dependent (Demanding)</name>
      <limit amendoperation="addnode">False</limit>
      <forbidden amendoperation="remove"/>
      <bonus>
        <selecttext amendoperation="addnode"/>
      </bonus>
    </quality>
  </qualities>
</chummer>
```
