### ISSUE TITLE
Genemods don't allow grades?

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#402]
Is this by RAW somewhere?  I took a careful read through the books, and I didn't find anywhere that it said the standard/alpha/beta/delta grades didn't apply to Genemods.

**Comment by chummer5a** [comment]
There's an argument about that on the forums that basically goes "Geneware is not a type of bioware, nanoware specifically calls out that it has grades available, therefore geneware cannot have grades." For what it's worth, the code is a holdover from Chummer 4. Probably a candidate for house ruling again.

**Comment by cfresquet** [comment]
Fair enough.  I'll dig into adding a house rule for it next week (fiddling on the Chummer code is my idle project at work).

**Comment by chummer5a** [comment]
Ha! And down the rabbit hole you go... It shouldn't be a particularly
difficult thing to do. Most of it's going to be in clsoptions.cs and
frmoptions.cs for the save/load methods and such. The load will need a
try-catch to stop Chummer from crashing on existing settings files. Beyond
that, it's essentially just an on-off switch.

**Comment by chummer5a** [comment]
Closed pending a pull request for house rules or an errata clarification.
