### ISSUE TITLE
Issue: Crash after trying to change priority system.

### ISSUE THREAD

**Issue by SanguTM** [chummer5a/chummer5a#4020]
After trying to change priority system, I am getting crash reports. After some testing, it looks like it only happens with draft files made by older versions of chummer. 
___________________________________________________________________________________________

### Environment
Crash ID: 2685c004-f936-43de-b065-918a5680bf24
Chummer Version: 5.210.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 9f68d8f9-f2b7-4871-9f4b-d421da01ed0d

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

![image](https://user-images.githubusercontent.com/56552478/73140414-4d4be600-4081-11ea-8abd-d175cfc96a9e.png)

**Comment by chummer5a** [comment]
Can you upload one of the old files?

**Comment by YarrikVII** [comment]
I would like to report similar crashing

![Chummer5_2020-01-27_13-41-16](https://user-images.githubusercontent.com/58294584/73168427-da874d00-410a-11ea-952a-670732ad460a.png)

**Comment by SanguTM** [comment]
Sure. Uploaded old draft. If you need more help recreating issue let me know.

[Create file.zip](https://github.com/chummer5a/chummer5a/files/4117949/Create.file.zip)
