### ISSUE TITLE
Positive Quality: Magic Sense

### ISSUE THREAD

**Issue by melodicmagpie** [chummer5a/chummer5a#4021]
In version 5.210.0, Positive Qualities includes: "Magic Sense" for 7 Karma, cited as being found on page 172 of SG (Street Grimoire) 

However this referenced Magic Sense is not a positive quality; the only Magic Sense found in SG is the adept power Magic Sense (for 0.5 PP.) 

The only Magic Sense that is a quality that I have been able to locate is found in RF (Run Faster) p. 116, which is a metagenic power already listed in Chummer as Magic Sense (Changeling) also for 7 karma

![magic sense](https://user-images.githubusercontent.com/60368875/73219832-ddd20700-4111-11ea-9196-5400da0cdc6f.PNG)

**Comment by chummer5a** [comment]
Centaurs automatically get the Magic Sense power. Since there's no support for providing free adept powers without enabling them for purchasing all adept powers, it was flagged as a quality. Not sure where the karma value came from, most likely a copypaste from changeling.

**Comment by melodicmagpie** [comment]
Centaurs get the Magic Sense Power described in Run Faster, not the adept power in Street Gimoire, so it would be the same page reference as Magic Sense (Changeling) but without the (Changeling)
