### ISSUE TITLE
Painade Grenade missing

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4023]
**Describe the bug**
The pained Grenade from Cutting Aces (p 135) is not present. I have searched the data files and cannot find the grenade.

**Expected behavior**
Be able to select the Painade granade.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.210.78 (and previous]

**Comment by chummer5a** [comment]
Statblock is busted, needs proper data.

**Comment by Teksura** [comment]
Proper Painades can be found in the german versions, but do not exist in any proper English books or errata. 

I suggest a custom data file. The stat block as presented in the German books looks like this:

> Painade
> 
> Damage: Special (Toxic, Force 8, immediate, vs BOD+WIL) 5 combatrounds
> 
> DV: -
> 
> Range: 10m radius
> 
> Avail: 12R
> 
> Price: 150 Nuyen

The specifics of what the damage code means can be found in the English text describing the Painade. again, I feel this is best suited for a custom data file stuck in the optional rules. Call it something like "Use German Stats for Painade"
