### ISSUE TITLE
Shifters don't display attributse correctly.

### ISSUE THREAD

**Issue by CarrierOriskany** [chummer5a/chummer5a#4024]
**Describe the bug**
Whenever one makes a shapeshifter with a form other than baseline human, shifting over to the metahuman form post chargen shows human statline rather than metatype specific.

**To Reproduce**
1. Make any shapeshifter
2. Give them a metahuman form that isn't human
3. Allocate a metatype adjusted stat to max

**Expected behavior**
I expected if I was to say make a shapeshifter with a troll metatype, that the adjusted body or strength would transfer over instead of showing human only attributes.

**Screenshots**
![bug report](https://user-images.githubusercontent.com/60591682/73624580-03c24480-4607-11ea-8114-1224fc5e1878.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by chummer5a** [comment]
Can't replicate in current nightly build; what version are you on?

**Comment by CarrierOriskany** [comment]
5.209.0

**Comment by chummer5a** [comment]
Fixed in 5.210
