### ISSUE TITLE
Adept power Enthralling Performance doesn't select a skill, cannot be taken multiple times

### ISSUE THREAD

**Issue by ElectronicRU** [chummer5a/chummer5a#4026]
Shadow Spells, p. 23 (emphasis mine):

> This adept power **is used in conjunction with an artistic skill,**
> such as Artisan or Gymnastics, which the adept must
> also possess. **This power can be selected multiple times,**
> with each selection pertaining to a different artistic skill. If
> the gamemaster allows, this power may also be linked to
> Unarmed Combat (Martial Arts) or Con (Impersonation).
> The power permeates the adept’s performance with
> a subtle magic aura, mesmerizing observers with the adept’s grace or skill as the performance unfolds. The adept
> makes a test of the appropriate skill + Magic. The adept’s
> hits serve as a threshold modifier for any Perception tests
> the audience might make during the performance. Audience members exposed to sudden outside stress or stimuli, such as hearing gunshot or suffering an assault, are immediately released from the entrancement.

**Comment by chummer5a** [comment]
Resolved in latest commit.
