### ISSUE TITLE
NullReferenceException clicking OK in Options menu with no Default Character Sheet selected

### ISSUE THREAD

**Issue by JoshwaSaville** [chummer5a/chummer5a#404]
Fresh install of Chummer 5 build 174 from the [dropbox link](https://www.dropbox.com/sh/p5yimzsgljq3nnn/AAAa2q6l970NAkUUtZ4CvOgpa?dl=0). I went into the Tools menu to tick the boxes for the books I had and clicked OK, and got an Unhandled Exception. Closed the program and recreated it again without even touching the checkboxes. 

Opened my Visual Studio-built version of Chummer in Debug mode and did the same thing, got NullReferenceException from line 1752 of frmOptions.cs, where ```SelectedValue``` was *null*. 

```cs
GlobalOptions.Instance.DefaultCharacterSheet = cboXSLT.SelectedValue.ToString();
```
Opened Chummer again, selected an option from the Default Character Sheet dropdown and clicked OK, no issues. Tried it in my from-dropbox version as well, and that also fixed it.

**Comment by chummer5a** [comment]
This is one of those annoying bugs that I've been aware of for ages, but never found an easy way to test for. I've added a ghetto fix for it in...whatever the latest commit was. Should be fixed in 5.175 at any rate.
