### ISSUE TITLE
Identical id for custom rule item

### ISSUE THREAD

**Issue by Ramesch** [chummer5a/chummer5a#4044]
**Describe the bug**
New custom rule 'German Data Changes - Underbarrel Weapons' adds 'Underbarrel Chainsaw' from RG 53 with id 5df8388e-9ca9-4455-9ac0-3d83ffd77d0d (see './customdata/German Data Changes - Underbarrel Weapons/amend_weapons.xml', line 46).
'Grenade Lauchner' from SR5 428 also has this identical id (see './data/weapons.xml', line 7112).

First question is: should 'Grenade Lauchner' be replaced by 'Underbarrel Chainsaw'?
If so: wouldn't it be better to hide the replaced item - if replacing it is the intention - and give the new weapon a new id?

Second question belongs to the results given in 'results_de-de.xml' when 'German language' and the new custom rule are active and 'Verify Data File' is used ('noentry' for 'Underbarrel Grenade Launcher').

**Desktop:**
 - OS: Windows 10
 - Version 5.210.101

**Comment by chummer5a** [comment]
Naw, I was just lazy and didn't update it properly. Will be fixed shortly.

**Comment by Ramesch** [comment]
Thank you!!
