### ISSUE TITLE
Group leaving popup on every action

### ISSUE THREAD

**Issue by Redjordan** [chummer5a/chummer5a#4046]
**Describe the bug**
After opening a save file of a magician that joined a group under "Initiation", everything that spends karma opens a dialog that asks me "Are you sure you want to spend 1 Karma on leaving a Group?". You need to visit the "Initiation"-Tab once after opening a file to get rid of these messages. Sometimes there are several messages you have to decline in order to continue editing the character.

**To Reproduce**
1. Create a magician/adept up to career mode
2. In career mode, join a group
3. Save the file and open it again
4. Add a skill rank/attribute rank or other things and confirm the karma spending
5. Get message "Are you sure you want to spend 1 Karma on leaving a Group?"

**Screenshots**
![Message](https://user-images.githubusercontent.com/47394807/75180789-33172d80-573d-11ea-86e9-0f3bb5546013.png)

**Character File**
[Unnamed Character.zip](https://github.com/chummer5a/chummer5a/files/4246191/Unnamed.Character.zip)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.210.0

**Comment by Johnny8-0** [comment]
What was the resolution to this issue? I'm having it also and after updating to v 5.211 my group has been un-joined.

**Comment by chummer5a** [comment]
Update to a current nightly build, basically. The checkbox gets toggled at times when it shouldn't, causing that prompt.
