### ISSUE TITLE
Perception / Wahrnehmung missing in Nightly 5.210.105.0

### ISSUE THREAD

**Issue by OLRobert** [chummer5a/chummer5a#4048]
Hoi Chummer Team. 

I don't know why, but the Characters do no longer show Perception in the "Skills" section. 
In German, it is Wahrnehmung and should be in "Fertigkeiten". 
None of the five characters in my group shows "Perception".

one of the character's XML file shows:
 <skill>
        <guid>482627d0-9405-4f79-b2d8-df8fd4d38988</guid>
        <suid>04e1eb3e-e82d-485b-a7fd-1e677df2a070</suid>
        <isknowledge>False</isknowledge>
        <skillcategory>Physical Active</skillcategory>
        <karma>0</karma>
        <base>3</base>
        <notes />
        <name>Perception</name>
      </skill>

another:
      <skill>
        <guid>bf254230-a631-4303-ac97-16593311dab5</guid>
        <suid>04e1eb3e-e82d-485b-a7fd-1e677df2a070</suid>
        <isknowledge>False</isknowledge>
        <skillcategory>Physical Active</skillcategory>
        <karma>0</karma>
        <base>0</base>
        <notes />
        <name>Perception</name>
      </skill>

Do you have any advise? 

Thank you and kind regards

Rob

**Comment by OLRobert** [comment]
**Describe the bug**
My group uses Chommer for Character handling. 
I am facing the missing "Perception" in their Characters since several nightly builds. 
So, perception is missing in five characters. 
One of my buddies uses "5.210.0", which shows "Perception". 

**To Reproduce**
Steps to reproduce the behaviour:
Create a character in Chummer 5.210.0, update your Chummer to "latest nightly" (5.210.105.0) 
and perception is gone. 
This got reproduced on two different instances of Chummer on my PC and the machine of 
one of my teammates. 

Expected behavior
Perception should remail at "Skills" / "Fertigkeiten" 

Screenshots
![Anmerkung 2020-02-26 203821](https://user-images.githubusercontent.com/42408066/75380996-414d8100-58d8-11ea-813a-0c78dadd7afa.jpg)
Shows an alphabetical order of all active skills > 0.
There should be "Wahrnehmung" / "Perception" at a rating of 3 in this list as 
the xml file of "D" shows:
![Anmerkung 2020-02-26 204218](https://user-images.githubusercontent.com/42408066/75381127-7eb20e80-58d8-11ea-8905-880997d52d30.jpg)

Character File
is attached zip file. 
[D-Final.zip](https://github.com/chummer5a/chummer5a/files/4257824/D-Final.zip)

Desktop (please complete the following information):

OS: Windows 10 Pro
Version 1909 (Build 18363.657)

**Comment by OLRobert** [comment]
I might have missed something but it does not work in 5.210.119.0

**Comment by chummer5a** [comment]
Nightlies are compiled at 0000 UTC, it'll be in the next build (about two hours from now)

**Comment by OLRobert** [comment]
Dear Chummr Team. 
It looks like 5.211.1.0 does not show Perception / Wahrnehmung. 
Did I miss something? 
Thank you and best regards

Rob

**Comment by OLRobert** [comment]
Hoi Chummer (team). 
Even 5.211.42.0 does not show perception / Wahrnehmung. 

Best regards
Rob

**Comment by OLRobert** [comment]
Hi here. 
5.211.47 does not show Wahrnehmung / Perception for the character I transferred. 
The attached char is another without perception. 

Best regards

Rob

[Secret Warrior.zip](https://github.com/chummer5a/chummer5a/files/4553397/Secret.Warrior.zip)

**Comment by chummer5a** [comment]
According to that file, you have basically all of the customdata folders enabled. Many of those folders are incompatible with each other, not least of which being the Delnar Skills Remake. I'd suggest that you open up Tools > Options > Optional Rules and untick all of the rules then re-test.
