### ISSUE TITLE
Not possible to make a Technomancer Sprite a Sprite Pet

### ISSUE THREAD

**Issue by Digioso** [chummer5a/chummer5a#4049]
**Describe the bug**
Technomancer with data stream Technoshaman can have a Sprite Pet. However when you try to mark a sprite as a sprite pet (try to check the checkbox) nothing happens. Even trying to set "Fettered" to True in the character file via text editor changes nothing.

**To Reproduce**
1. Create a technomancer
2. Add the quality Data Stream Technoshaman
3. Add complex form Sprite Pet (not sure whether this is added automatically or not)
4. Create a sprite.
5a. Mark sprite as registered
5b. Do not mark sprite as regeristed
6. Click on Sprite-Pet
7. Nothing happens.

**Expected behavior**
Checkbox should be checked when clicked. Sprite Pet shouldn't count against the maximum number of registered sprites.

**Chummer verion**
Tested with Chummer 5.210.0 and Nightly 5.210.105

**Screenshots**
Screenshot is in German. Sprite-Pet = Sprite-Haustier
![Unbenannt](https://user-images.githubusercontent.com/10660450/75382090-224fee80-58da-11ea-9553-6f380774b8f7.png)

**Character File**
[D-Final.zip](https://github.com/chummer5a/chummer5a/files/4257886/D-Final.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Comment by OLRobert** [comment]
I am facing the same situation.

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/ab16f6d5656c5fe9e36b8faabd1922189515e44e

**Comment by Digioso** [comment]
I updated to 5.210.112 . Now I cannot even click on Sprite-Pet anymore. It's not clickable anymore. So this still hasn't been solved.

**Comment by Infinitum31415** [comment]
> I updated to 5.210.112 . Now I cannot even click on Sprite-Pet anymore. It's not clickable anymore. So this still hasn't been solved.

same issue here (german version 5.211.1.0)

![image](https://user-images.githubusercontent.com/3732095/79616311-fcd6a880-8104-11ea-9749-fd9697404b4d.png)
