### ISSUE TITLE
Issue: - Crash beim Speichern eines unfertigen Charakters

### ISSUE THREAD

**Issue by jowilkes** [chummer5a/chummer5a#4050]
### Environment
Crash ID: b8804c33-1b71-4c71-ac6b-af8db5633fcd
Chummer Version: 5.210.0.0
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: f18dd9cf-21aa-43b4-a59d-fb1696eea9a1

### Expected behaviour
Auf Klick von "Speichern" hin hätte einfach nur gespeichert werden sollen.

### Actual behaviour
Chummer blieb hängen, muß abgeschossen und neugestartet werden.

### Steps to reproduce the behaviour
Nicht sicher ob's zur Reproduktion langt - neuen Charakter anlegen, Karmamodus, Namen und Beschreibung eingeben, noch kleine Änderungen bei Fertigkeiten oder dergleichen, aber Attributpunkte vergeben, "speichern" klicken. Crash.

**Comment by chummer5a** [comment]
Can't reproduce in current nightlies.
