### ISSUE TITLE
Life Style Roommate wrong calculation

### ISSUE THREAD

**Issue by guijsouza** [chummer5a/chummer5a#4054]
**BUG**
When adding roommate in Life Style, you get wrong final cost. The app divide the life style cost by the number of people and then add the 10% cost per roommate to final cost.

**To Reproduce**
Add a lifestyle and after add any number of roommates to see de bug.

**Expected behavior**
Add 10% per roommate in final Life Style cost.

**Screenshots**

![image](https://user-images.githubusercontent.com/30982040/75633641-8a0d7e80-5be5-11ea-8a63-cab4b05d07c5.png)

![image](https://user-images.githubusercontent.com/30982040/75633555-89281d00-5be4-11ea-82ad-13433ff57340.png)

![image](https://user-images.githubusercontent.com/30982040/75633567-a0ffa100-5be4-11ea-8816-42e2296a9bb8.png)

![image](https://user-images.githubusercontent.com/30982040/75633581-cbe9f500-5be4-11ea-9108-d5f22d78e547.png)

![image](https://user-images.githubusercontent.com/30982040/75633586-d73d2080-5be4-11ea-9637-12d5cdde35b7.png)

![image](https://user-images.githubusercontent.com/30982040/75633598-f20f9500-5be4-11ea-916c-3300dad09c70.png)

**Desktop **
 - OS:  Windows 10
 - Version e.g. 5.210.0

**Comment by jonathanwinter123** [comment]
This seems to be correct. It already calculates YOUR monthly rent without that of your roommates which they have to pay themselves. They can just add the same exact lifestyle as you to their character and then have to pay their part.

**Comment by chummer5a** [comment]
Basic lifestyles don't have all the details visible to show why it's doing that though.
