### ISSUE TITLE
No attribute values created when selecting "MetaVariant" for Insect Spirits.

### ISSUE THREAD

**Issue by insomniabob** [chummer5a/chummer5a#4055]
Select New Critter, then pick an insect spirit. Apply a MetaVariant (ant, locust, etc), and click OK.

The created Critter will have 0s in all attributes, skills, etc.

When creating an insect spirit without selecting a Metavariant, stats are allocated normally.

**Comment by chummer5a** [comment]
I think this is fixed in the nightlies?
