### ISSUE TITLE
Crash after character creation

### ISSUE THREAD

**Issue by lydiasoeffky** [chummer5a/chummer5a#4056]
### Environment
Crash ID: 49b7c7db-a292-4422-86d3-8948667d8acb
Chummer Version: 5.210.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: f40b527e-7342-4a00-89ba-2ec039e7e9fd

### Expected behaviour
Either creating the new character or giving an error message that a metavariant must be chosen.

### Actual behaviour
The program crashes.

### Steps to reproduce the behaviour
- starting a new charater
- choosing karma creation and a standard character 
- choosing shapeshifter ("Gestaltwandler") as metatype
- choosing no metavariant 
- finish character creation

![steps2-4](https://user-images.githubusercontent.com/18304839/75815473-c41c8300-5d93-11ea-9d39-0c570e76fd14.jpg)

**Comment by chummer5a** [comment]
Resolved in nightly builds. For what it's worth I'll be releasing a new milestone build soon.
