### ISSUE TITLE
Error Possession/Inhabit Vessel 

### ISSUE THREAD

**Issue by RedRoss53** [chummer5a/chummer5a#4057]
**Describe the bug**
![Error pocesses Plasteel Homunculus](https://user-images.githubusercontent.com/61813841/75944100-d1557280-5e64-11ea-9f76-9421badfa98a.JPG)

Tried to have a created character sheet possess a Plasteel Homunculus. I have tested it through multiple sheets. Please message me for more details or for user error on my part.

![Error step 1](https://user-images.githubusercontent.com/61813841/75944552-044c3600-5e66-11ea-9409-8720ebfbfb4b.JPG)
![Error Step 2](https://user-images.githubusercontent.com/61813841/75944574-0d3d0780-5e66-11ea-8821-613f5fdd2326.JPG)

I'm a rocket surgeon.

**Comment by chummer5a** [comment]
Should be resolved in current builds.
