### ISSUE TITLE
Chummer calls code for leaving initiation group without being told to

### ISSUE THREAD

**Issue by plesekz** [chummer5a/chummer5a#4059]
**Describe the bug**
Whenever I change anything on the character sheet, such as equip or unequip armour, buy new item or raise skill, chummer calls for code for leaving initiation group which results in:
a) pop-up saying you don't have enough karma for that, if you're at 0 karma
b) pop-up asking you whether you want to spend 1 karma to leave initiation group.
This pop-up actually appears repeatadly after being closed once.

**To Reproduce**
1. Go to any tab
2. Change anything on sheet, such as equiping or unequiping armou
3. Pop-up appears

**Expected behavior**
This pop-up should only appear if I intentionally untick the box for "joined group".

**Character File**

[White.zip](https://github.com/chummer5a/chummer5a/files/4301801/White.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Chummer 5.210.0

**Comment by chummer5a** [comment]
Fixed in nightlies
