### ISSUE TITLE
Magician: not all Rituals available

### ISSUE THREAD

**Issue by Ryu-ken** [chummer5a/chummer5a#406]
One Issue I encountered was my Magician not being able to choose all Rituals. 
Specifically in this case the Ritual "Circle of Protection" was not shown. When I enter "Protection" in the search bar it still don't show up, but when I delete the search, many more Spells and Rituals become visible (but still no Circle of Protection).

![rituals1](https://cloud.githubusercontent.com/assets/14300369/9995699/d17d950a-6083-11e5-9ac1-f953d8c0e8ad.jpg)
![rituals2](https://cloud.githubusercontent.com/assets/14300369/9995700/d17fc168-6083-11e5-99af-7e76eae6a3ff.jpg)
![rituals3](https://cloud.githubusercontent.com/assets/14300369/9995701/d183b07a-6083-11e5-92e1-59481f4b2eb0.jpg)

**Comment by joha4270** [comment]
Fat finger error, circle of protection is in no displayed category
