### ISSUE TITLE
Chummer does not calculate dicepool for shooting a weapon accurately

### ISSUE THREAD

**Issue by plesekz** [chummer5a/chummer5a#4060]
**Describe the bug**
When both specialization and smartlink are applicable, chummer includes only one of them in the dicepool calculation, though it lists them in the mouse over details of calculation.

**To Reproduce**
1. Go to "Street Gear"/"Weapons"
2. Look up "Ares Desert Strike"
3. The dicepool should be 17. 7 AGI + 6 Skill + 2 Spec + 2 Smartlink, though Chummer displays that correctly in the mouse over, the displayed dicepool is only 15.

**Expected behavior**
It should display 17.

**Character File**
[White.zip](https://github.com/chummer5a/chummer5a/files/4301803/White.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.210.00

**Comment by chummer5a** [comment]
Works in current nightlies.
