### ISSUE TITLE
Issue: Black Market Pipeline does not work

### ISSUE THREAD

**Issue by SanguTM** [chummer5a/chummer5a#4063]
**Describe the bug**
I am using latest chummer version: 5.210..119, but I noticed it on older versions as well. For my character I got Black Market Pipeline positive quality. I am going into street gear and trying to add gear. I can see checkbox for "Black market DIscouint", but checkbox does not work. I am unable to check it. And checkbox is not checked for correct group as well. For example: Black market pipeline does not work for Cyberdecks and other electronic devices. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.210..119
[Draft.zip](https://github.com/chummer5a/chummer5a/files/4313606/Draft.zip)

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/5020f3d81375fecebf322980bdf1080ce93237ca
