### ISSUE TITLE
Issue: Mentor Spirit Fire-Bringer Adds Bonus Dice to All Spell Categories

### ISSUE THREAD

**Issue by clientsi** [chummer5a/chummer5a#4064]
If you add the Mentor Spirit "Fire-Bringer" to any spell caster, you'll find that the +2 dice pool bonus is added to all spell dice pools instead of just the Manipulation dice pool as intended.

The correct behavior would be that selecting the mentor spirit Fire-Bringer would only add a +2 dice pool bonus to the Manipulation spell dice pools.

Windows 10, Chummer 5a Version 5.210.0

![FireBringer Error](https://user-images.githubusercontent.com/62074452/76450539-32aca280-638b-11ea-9005-c329aa5dd99e.png)

**Comment by chummer5a** [comment]
Fixed in nightlies.
