### ISSUE TITLE
Exotic Weapons Skill Softs

### ISSUE THREAD

**Issue by Ryu-ken** [chummer5a/chummer5a#407]
There seems to be no way to get Exotic Weapon Skill-Softs. As far as I know the rules don't forbid buying for example Exotic Ranged Weapons: Laser Weapons as an Active Soft for your Skillwire System. If they really are not for sale as Active Soft I apologize for the inconvenience.

**Comment by chummer5a** [comment]
Hrm. Does it work if you add the Exotic Weapon Skill first? Shouldn't need to put points into it, but the selectskill is based off your current skill list.

**Comment by Ryu-ken** [comment]
That did it. Thank you.
