### ISSUE TITLE
Spell list not updating to show more than just rituals on an adept turned mysad from becoming a Wendigo in character generation

### ISSUE THREAD

**Issue by Anfears** [chummer5a/chummer5a#4070]
**The Bug**
after being turned from an adept into a mysad in character generation the spell list only shows rituals like it would for a normal adept, not all the different spell categories like it should for a mysad

**How to Reproduce**
1.Start a new character 
2. Select Ork as meta-type (any priority)
3. Select adept (any priority) for magic
4. take the infected: Wendigo quality which will turn you into a mysad 
5. Look at spell tab and try to add a new spell

**Comment by DelnarErsike** [comment]
Could you double-check if the issue is still present in the current Nightly?
