### ISSUE TITLE
Tradition lost when loading customdata settings that forbid the current tradition

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4071]
**Describe the bug**
Opening a character with an existing Tradition, that Tradition is blank in the application. However it shows correctly in the Character Viewer.

**To Reproduce**
1. Open a character with a non-missions Tradition. 
2. Go to 'Spells and Spirits' tab.
3. See that Tradition is blank.
4. Click Print. Scroll down to 'Tradition'. See Tradition is printed.

**Expected behavior**
Tradition is shown correctly.

**Screenshots**
Character in chummer5a
![Chummer](https://user-images.githubusercontent.com/17562417/77224048-ebaf7180-6b2f-11ea-9ccf-611a4ab97bbe.png)

Character in viewer
![viewer](https://user-images.githubusercontent.com/17562417/77224055-ff5ad800-6b2f-11ea-80e5-47e259dd7ced.png)

Character file - tradition
![file](https://user-images.githubusercontent.com/17562417/77224059-07b31300-6b30-11ea-991f-aff44deaf7bf.png)

I think there is a problem regarding the Custom Data Directories specified in the settings file used by the character and the Optional Rules actually selected in chummer5a.

These are the custom directories in the default settings specified for the character
![default settings](https://user-images.githubusercontent.com/17562417/77224068-13063e80-6b30-11ea-86b5-9213b4cc20b0.png)

These are the custom directories in the character file
![character directories](https://user-images.githubusercontent.com/17562417/77224072-1d283d00-6b30-11ea-8202-a99c14fc14c0.png)

These are Custom Data Directories in the Options
![Custom Data Directories](https://user-images.githubusercontent.com/17562417/77224080-26b1a500-6b30-11ea-9d4b-0e2d868ced80.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.211.1 [and prior]

**Additional context**
The character is not a Missions Legal one and doesn't have the Missions FAQ selected. However I also use chummer5a for Missions characters, and have a separate settings file.

The Missions rules exclude the Santeria Tradition. So with the missions rules wrongly in effect (after all they are not specified in the settings file nor in the character file) the tradition is not actually listed and so is left blank in the application.

There seems to be a problem in Custom Data Directories processing when different directories are specified in different settings files. But it is probably more general: characters that use the same settings file but have different Custom Data Directories (in the character files) will actually have some combination of the Directories from across the characters selected in the Optional Rules tab.

**Comment by chummer5a** [comment]
Mostly a duplicate of #3532 which is being worked on in https://github.com/chummer5a/chummer5a/tree/CharacterCustomData. There's possibly an argument that the tradition could be set via a button click instead of the dropdown, as that would prevent the data source changing from affecting the character though.

**Comment by chummer5a** [comment]
Long-term solution https://github.com/chummer5a/chummer5a/tree/CharacterCustomData. Short-term solution prompt if character's saved customdata folders don't match the currently-loaded settings, in addition to checking for if character has unloaded customdata folders. 'This character does not have the following customdata rules that you have active: x/y/z
are you sure you want to continue'

**Comment by Lochabar** [comment]
Issue resolved when Character specific options was introduced.
