### ISSUE TITLE
Suprathyroid Gland does not stack with Muscle Replacement Cyberware

### ISSUE THREAD

**Issue by BKlaassen** [chummer5a/chummer5a#4073]
**Environment**

Chummer Version: 5.211.0
Environment: Win10

**Expected behaviour**

The attribute boosts generated by Muscle Replacements should stack with Suprathyroid Glands. Both descriptions do not exclude eachother (Replacements explicitely states "It cannot be combined with  other  augmentations  to  the  muscles,  including  muscle augmentation or muscle toner bioware." and suprathyroid glands do not disallow stacking at all) as bonus sources.

**Actual behaviour**

Only the highest bonus is applied in the character "common" section

**Steps to reproduce the behaviour**

generate a new character with both bonus types

**Comment by chummer5a** [comment]
Yeah, this is an awkward thing. It's a legacy interpretation from Missions errata, which says that Cyberware == Augmentation and Muscle Replacement says it doesn't stack with Augmentations. Need to sort something out with it.
