### ISSUE TITLE
Expanded Physical+Overflow & Stun Tracks For Tanks In Chummer Client

### ISSUE THREAD

**Issue by Forgoten-Null** [chummer5a/chummer5a#4074]
If you have more than 24 Physical+Overflow Damage Boxes or more than 24 Stun Damage Boxes then they will not be rendered properly as Chummer doesn't draw more than 8 rows currently.

If someone could update it so that it can draw more than 8 rows when necessary then it would be appreciated. I just wanna see all of my dumb tank's boxes in the program so that I can track into overflow without having to start counting it out in my head or somewhere else. I know that I can't be the only one who has this issue, since even having 11 Body puts you at 26 Physical+Overflow I think and you don't even need any magic or ware or drugs to get to that point.

Obviously it's not a huge game breaking thing, but it's something that I and others would appreciate being worked on whenever someone gets the chance.
![image](https://user-images.githubusercontent.com/41028122/77512359-4951ff80-6e49-11ea-96f3-c47d8ef7400f.png)

Also, in case anyone has Dejavu, yes I did request a fix for the same issue about two years ago.
https://github.com/chummer5a/chummer5a/issues/2905

**Comment by chummer5a** [comment]
What version are you on? This should be working correctly as of 5.211

**Comment by Forgoten-Null** [comment]
I'm on 5.211.0

That screenshot from the OP post here is from 5.211.0

Is there some setting I need to change?
