### ISSUE TITLE
Attribute calculation with Qi-Focus and Improved Physical Attribute bugged

### ISSUE THREAD

**Issue by FireprotectioN** [chummer5a/chummer5a#4075]
The Bug occurs in Adept characters which use Qi-Focus and the adept power Improved Physical Attribute. Improved Physical Attribute should add one Attribute level for one level of the adept power on level one of a Qi-Focus, instead chummer adds 2 Attribute levels. This was observed on every physical attribute.

**To Reproduce**
1. Create Adept Character.
2. Buy Qi-Focus (Level 4 for 1 Level of Character Power)
3. Bind Qi-Focus
4. Set Improved Physical Attribute as Power.
5. Choose a physical attribute.
6. See in Attribute Overview that the attribute was improved by 2.
In Adept Power Overview, the Power is set to level 2 by default after this and the character shows power points -1.

**Expected behavior**
Adept Power Enhanced Physical Attribute set to level 1.
Constitution set to predesignated value plus 1 from the Adept Power.

**Screenshots**
See below. In Screenshots the character is the same, this time with Constitution improved.
![ChummerBug1](https://user-images.githubusercontent.com/62674113/77590549-43622a00-6eee-11ea-91a7-52964d02a4af.JPG)
![ChummerBug2](https://user-images.githubusercontent.com/62674113/77590555-465d1a80-6eee-11ea-86a6-2b166abeec33.png)

**Character File**
See below.
[Bolt.txt](https://github.com/chummer5a/chummer5a/files/4383865/Bolt.txt)
In Character File Agility is the attribute which was improved. -> Set from 7 to 9, not 7 to 8.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.211.0
 
I am dearly sorry for the german in the screenshots.

**Comment by chummer5a** [comment]
Can't replicate this behaviour. The Rating on any power should indicate levels that have been paid for with Power Points. Chummer's written with the assumption that qi foci power points are effectively layered on top of an existing power.
