### ISSUE TITLE
Request "Twisted Way" positive quality

### ISSUE THREAD

**Issue by RichardCoffee** [chummer5a/chummer5a#4079]
I would like to request that the Positive Quality "Twisted Way" for magicians and adepts, from the Street Grimoire book, pp 84-87, be added to Chummer.

**Is your feature request related to a problem? Please describe.**
Only a problem in that I would like to create a character with this quality. :)

**Describe the solution you'd like**
I would like it added to the Positive Quality category after clicking the 'Add Quality' button.

**Describe alternatives you've considered**
Not sure there is one.

**Additional context**

**Comment by ZachSchaffer** [comment]
Added in #4084 and merged.

**Comment by RichardCoffee** [comment]
Thank you for the quick response.  I appreciate your efforts.

The pull request looked a little odd.  The first commit was the changes to add the quality, and the second commit then reverted the previous commit.  The third commit is labeled as adding it back in, but that is not what it actually did.  You may want to go back and take another look.

**Comment by ZachSchaffer** [comment]
Yeah, sorry about the weird PR. My IDE went haywire on me and wound up reverting my commit when I didn’t want to. Thought my last commit fixed it, but as it turns out, it didn’t. Luckily the chummer dev straightened things up and seemed to have put in the changes properly in the most recent commit.
