### ISSUE TITLE
"Network Submersion": Wrong name and no function

### ISSUE THREAD

**Issue by Redjordan** [chummer5a/chummer5a#4080]
When submerging as a technomancer, the "Network Submersion" has no effect on the karma cost of the submergion. I think this is a leftover from Shadowrun 4.

In Shadowrun 5 Submersion Groups were introduced in "Kill Code" p. 106. and they reduce the cost to submerge by 10%. As far as i can see there is no cost mentiond for joining a group, only for creating a new group yourself (p. 108, 5 Karma). 
![SubmersionGroups](https://user-images.githubusercontent.com/47394807/78165542-bff38c00-744b-11ea-9450-4be755d66380.png)

1. Create Techchomancer
2. Save in Career mode
3. Add enought Karma to submerge (13 Karma)
4. Check "Joined Network" and activate "Network Submersion (20%)"
5. Add Submersion grade, still costs 13 Karma

 "Joined Network" should be renamed to "Joined Submersion Group" and "Network Submersion (20%)" to "Group Submersion (10%)".
Group Submersion should reduce the Karma cost for submerging by 10% (13 -> 12) and should stack with submersion task (13 -> 11 -> 10).

![NetworkSubmersion](https://user-images.githubusercontent.com/47394807/78166127-9c7d1100-744c-11ea-8762-b8a860825be0.png)

Character file:
[Technomancer Bugreport.zip](https://github.com/chummer5a/chummer5a/files/4416650/Technomancer.Bugreport.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.211.0

**Comment by chummer5a** [comment]
Closed by 0b5379519884eab36631a0248210b05f2ea006ed
