### ISSUE TITLE
Totem

### ISSUE THREAD

**Issue by mwberlindeu** [chummer5a/chummer5a#4083]
I apologize to put a simple question in this request.

Where can I set the totem of a shaman?
If there is no possibility to set the totem shouldd't there be an option to do so?

**Comment by chummer5a** [comment]
Mentor Spirits are added via qualities, but by default shamans aren't compelled to follow any particular mentor or totem.

**Comment by mwberlindeu** [comment]
And where do I find "qualities" ?

**Comment by chummer5a** [comment]
Common tab, click Add Quality.

**Comment by mwberlindeu** [comment]
Thanks, I finally found it.
