### ISSUE TITLE
Additional drone armour capped by body

### ISSUE THREAD

**Issue by Wymar** [chummer5a/chummer5a#4085]
**Describe the bug**
When adding extra armour to a drone in excess of its base BOD+ARM, the rating of the mod gets lowered to that value.

**To Reproduce**
1. Enable R5 drone mods in the options if they're not enabled already
2. Buy a drone. It doesn't matter if it's in create mode or career mode, but the latter might bug you about not having enough nuyen. For demonstrative purposes I'll use the Doberman (B4 A4), Matilda (B8 A8), and Dassault Janitor (B10 A2).
3. Add the _Armor (Drone)_ modification to the drone. Pick a high rating, such as BODx3, which neither exceeds the mod point cap nor lowers the other attributes so it's a convenient and legal value to choose. So 12 for the Doberman, 24 for the Matilda, and 30 for the Dassault. The availability limit should be ignored if done in create mode.
4. The rating listed under the drone's mods is now equal to the drone's base BOD+ARM. 8 for the Doberman, 16 for the Matilda, and 12 for the Dassault, as if the additional armour was capped by BOD. Fortunately you don't get billed for the original rating of the mod.

**Expected behavior**
The rating of the _Armor (Drone)_ modification should be the exact rating that has been selected, unless pre-existing modifications cause the drone to not have enough mod points to allow for this much armour in the first place in which case the modification should throw an exception of sorts.

**Character File**
[drone armour.txt](https://github.com/chummer5a/chummer5a/files/4452649/drone.armour.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.211.1

**Comment by chummer5a** [comment]
Armour is capped by Armour*2.
> a drone’s attributes can never by higher than twice their starting value (so if you had a Handling of 3, it can never be modifed higher than 6).

**Comment by Wymar** [comment]
Fair, but drones where BOD != ARM still get the wrong value.
