### ISSUE TITLE
Add support for spare clips in weapons used by vehicle-mounted Drone Arms

### ISSUE THREAD

**Issue by Cebasiz** [chummer5a/chummer5a#4092]
When adding a spare clip to the gear section It only lists weapons that are present in the weapons tab. It would be nice if Weapons that were mounted / listed in the vehicle tab were also included so that clips could be made for vehicles and then transferred over. Note that no such functionality is present in the vehicle tab at all- only spare clips generated in the gear tab seem to have this function.

**Describe the solution you'd like**

Either add the functionality to spare clips generated as gear under a vehicle entry, or somehow list weapons that are included in the vehicle tab as valid choices for clips generated in the gear tab.

**Describe alternatives you've considered**
Maybe it'd be easier to just port this function over to spare clips added under the vehicle tab. 

![ex3](https://user-images.githubusercontent.com/10738550/79171341-bd842100-7dbf-11ea-9bcf-a4d029bbc035.PNG)
^the dialogue in question which doesn't exist on the vehicle screen.

**Comment by chummer5a** [comment]
I hate anthro drones. This will require finagling.
