### ISSUE TITLE
Are you sure you want to spend 1 Karma on leaving a Group?

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#4095]
In v5.210 I got this error msg regardless of what I was trying to do. To stop it I had to click the tick mark on my Initiation Group and then select no when asked if I wanted to delete it. This happened on every load of my character.
![image](https://user-images.githubusercontent.com/29793408/79537802-4d0d2680-8083-11ea-9fc1-1ecfe0f2b354.png)

Then I updated to v5.211 and now the Initiation Group tick mark has been removed (I'm no longer member of a group I paid 5 karma to join) even though the Karma expense is still listed under Karma and Nuyen.
![image](https://user-images.githubusercontent.com/29793408/79537971-ac6b3680-8083-11ea-83da-358ab8882089.png)

**Comment by chummer5a** [comment]
Fixed in nightlies.
