### ISSUE TITLE
Improve performance when opening the connections tab

### ISSUE THREAD

**Issue by RobinZergiebel** [chummer5a/chummer5a#4097]
**Is your feature request related to a problem? Please describe.**

We have been playing our characters for years and collected quite a few connections. Whenever I open the connections tab in Chummer, the entire application freezes.

**Describe the solution you'd like**

It would be great if the performance would be better.

Cheers,
Robin

**Comment by chummer5a** [comment]
Can you provide a copy of an affected character file, please? You can compress them to zip and upload here, or rename the extension to .txt and do the same.

**Comment by RobCoPKC** [comment]
Sure, here you go:
[JackChummerZip.zip](https://github.com/chummer5a/chummer5a/files/4541485/JackChummerZip.zip).
Just fyi, I'm not the only experiencing it, the entire team (with obviously similiar connections) complains about it.
I just tried it with the newest version and while it still freezes, it loads significantly faster. Did you already change anything?

Cheers,
Robin

**Comment by chummer5a** [comment]
Nope, no changes to contact stuff lately. What version did you update from?

**Comment by RobCoPKC** [comment]
Just a minor jump. From (I think) 5.211.20 to 5.211.47.

Cheers,
Robin

**Comment by RobCoPKC** [comment]
Currently on 5.212.50 and it gets worse and worse...
An option to save connections collapsed would be really useful.

Cheers,
Robin
