### ISSUE TITLE
Restericted Gear positive quality does not allow selection of associated gear.

### ISSUE THREAD

**Issue by kkragenbrink** [chummer5a/chummer5a#410]
Seems a simple oversight.

**Comment by joha4270** [comment]
Unable to reproduce

**Comment by kkragenbrink** [comment]
How is this unable to reproduce?  How do YOU select associated gear?  I picked "Restricted Gear", and then picked a Cyberskull, for example, then tried to save the character as out of chargen, and got a notice that the character had an item that was too restricted.

**Comment by chummer5a** [comment]
Looks like attached plugins and accessories cause it. Add a datajack to an
alphaware skull and it warns you that the skull is over availability.

**Comment by kkragenbrink** [comment]
Ah, yeah, I had added some Advanced Synthskin to my Cyberskull.  Good catch. Sorry for not providing more insight; I'll try and debug better in the future. Meanwhile, I am still confident this bug exists.

**Comment by chummer5a** [comment]
Yeah, it does. I can see the problem, shouldn't be hard to fix.
