### ISSUE TITLE
Add Initiate Grade math 

### ISSUE THREAD

**Issue by mordan81** [chummer5a/chummer5a#4101]
**Describe the bug**
Hi!
In Chummer5a 5.211.0 at character creation on initiation tab when I added new initiation grades the (-10%) discount is different for ordeal and different for group/schooling.
Initiation with ordeal cost 11 karma, Initiation with grp/sch cost 12 karma on grade 1.
Ini Grade 6: Ordeal costs 23 karma. Ini grade 6 normally costs 28 karma -10% => 25.2 rounded up(26) or rounded (down) (25) but not 23.
Please fix the math and rounding rules.

**To Reproduce**
1. (Create a new awakened character) Go to Initiation panel
2. See Karma Remaining (e.g. 10)
3. Click on Initiation Ordeal checkbox (True)
4. Click on Add Initiate Grade
5. See karma Remaining (e.g. -1)
6. Remove Initiate Grade (Grade 1)
7. Click on Initiation Ordeal checkbox (False)
8. Click on Initiation Schooling checkbox (True)
9. Click on Add Initiate Grade
10. See karma Remaining (e.g. -2)

**Expected behavior**
May the ten percent of the same number everywhere the same?

**Screenshots**
-

**Character File**
-

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [5.211.0]

**Additional context**
Thank You!

**Comment by chummer5a** [comment]
This should be working correctly in current nightly builds, I believe.

**Comment by mordan81** [comment]
Yes, it works.
Thank You!
