### ISSUE TITLE
Custom Vehicles, Drones, Weapons

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#4103]
I like to give my players alternative loot, like a mean car for the Rigger. I'm missing the ability to create a custom vehicle/drone/weapon/deck or at least manipulate the stats of a standard one I used as base.

**Comment by chummer5a** [comment]
Currently we only support the creation of custom content via the custom XML system as documented in https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files. If you'd like any assistance with creating new files, you can join the homebrew channel in Discord https://discord.gg/ehPcJvk.

Relates to https://github.com/chummer5a/chummer5a/issues/2501
