### ISSUE TITLE
adept initiation bug

### ISSUE THREAD

**Issue by Syrasar** [chummer5a/chummer5a#4105]
Initian Ordeal and Group Initiation for adepts is set at 20% there is no errata to be found changing it 
from the pdfs 10%

**To Reproduce**
open chummer with an adept
go to initiation tab

**Expected behavior**
all 3 discounts should as far as i am aware still be at 10%

**Desktop (please complete the following information):**
 Windows 10
Chummer 5.211.0

**Comment by chummer5a** [comment]
Fixed in current nightlies.
