### ISSUE TITLE
Request: Add ability to purchase Spare Clips modifcation in greater quantities

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#4106]
**Is your feature request related to a problem? Please describe.**
Whenever I buy a gun, the first thing I buy with it is spare clips. The issue is that having to select the spare clips mod five separate times is tedious, especially when you are buying multiple guns.

**Describe the solution you'd like**
Add a Quantity field to Spare Clips to allow them to be bought in bulk. It's a minor change but I think it's huge for quality of life.

**Describe alternatives you've considered**
The only alternative as-is is to click the mod, hit Add&More, and repeat. Which, while not difficult, is tedious at the best of times.

**Comment by Gitchum14** [comment]
Agree to this, maybe even add ammo into them? Like one magazine apds, another shocker, etc.

**Comment by Lwmons** [comment]
You can add ammo to specific clips once you leave Creation
