### ISSUE TITLE
SINners Error: Please log in

### ISSUE THREAD

**Issue by Gitchum14** [chummer5a/chummer5a#4107]
**Describe the bug**
Chummer 5.211.62
SINners Error: Please log in 

 
**To Reproduce**
1. Open chummer
2. SINners Error: Please log in 
3. See error

**Expected behavior**
Load the characters shared via SINner groups.

**Screenshots**
https://imgur.com/YCskF75
https://imgur.com/SGNQymd

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.211.62
![chummer error log in sinners](https://user-images.githubusercontent.com/65242430/81717178-836b7500-947a-11ea-88dd-09d1eac2e963.png)
![SGNQymd](https://user-images.githubusercontent.com/65242430/81717215-8d8d7380-947a-11ea-9454-c32b961a6015.png)

**Comment by ArchonMegalon** [comment]
The good thing is: I can reproduce this! Will take a look asap.

**Comment by ArchonMegalon** [comment]
@DelnarErsike comes to the rescue for me (the damsel in distress here)!

**Comment by DelnarErsike** [comment]
My bad, this was caused by me being a bit too hasty with some of my ChummerHub-related code cleaning. The funny thing is this is actually two different errors, it's just that the one regarding the connection (the HttpHandler) "hid" the other one that was caused at some point when the program was collecting characters to process. The latest commit should hopefully address both (I found a potentially crash-causing issue when looking through the code that collects those characters).

**Comment by Gitchum14** [comment]
Fixed as of 5.212.3!

However when uploading a new character, a new error occurs: 

This is NOT an exception from Chummer itself, but from the SINners WebService. This error happend "in the cloud": Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.ListExtensions.AddRange[T](IList`1 lstCollection, IEnumerable`1 lstToAdd) in C:\projects\chummer\Chummer\Backend\Extensions\ListExtensions.cs:line 63
   at ChummerHub.Client.Model.CharacterExtended.PopulateTags() in C:\projects\chummer\ChummerHub.Client\Model\CharacterExtended.cs:line 148
   at ChummerHub.Client.Model.CharacterExtended.<Upload>d__25.MoveNext() in C:\projects\chummer\ChummerHub.Client\Model\CharacterExtended.cs:line 0

New issue for this? Is this even the right github or is SINers its own one?

Thanks for everyth
![error](https://user-images.githubusercontent.com/65242430/82742178-fc13e080-9d5a-11ea-996b-d3dfd0484fa1.PNG)
![error2](https://user-images.githubusercontent.com/65242430/82742179-fcac7700-9d5a-11ea-9bd7-90b90a437881.PNG)

ing.

**Comment by ArchonMegalon** [comment]
Hi! This is the right one. I and @DelnarErsike are already on it. :) Thanks for reporting and your patience with this bug(s).

**Comment by Gitchum14** [comment]
I think it might be fixed, but another error occurs, the issue has been opened via the chummer crash report. 

Will close as soon as i can confirm
