### ISSUE TITLE
Identical stats providing different results on two seperate sheets

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#4109]
**Describe the bug**
I'm rebuilding a character made with Priority in Sum-to-10, but it's listed as having an initiative of 10+2d6 while the original, with the same stats and cyberware, has 11+2d6. I also saw it as higher, 12+2d6 earlier, and highlighting my Reaction attribute listed "Wireless Reflexes Wireless". The Rank 2 Wireless Reflexes I have on the v2 sheet seem to be inconsistently displaying their value.

**To Reproduce**
Simply check the Reaction and Intuition attributes on both characters as well as their equipped cyberware. The ones affecting initiative are both identical, yet the listed result is different

**Expected behavior**
The Initiative should be the same for both

**Screenshots**
https://imgur.com/a/NqjMTEz

**Character Files**
[Legate v2.txt](https://github.com/chummer5a/chummer5a/files/4624885/Legate.v2.txt)
[Legate.txt](https://github.com/chummer5a/chummer5a/files/4624886/Legate.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.18362

**Additional context**
Each of the sheets has been additionally manually modified in Notepad, artificially inflating the starting Karma to 50 as a homebrew rule by the GM.

**Comment by chummer5a** [comment]
Clicking Reapply Improvements fixes it, as does moving the character into career mode and toggling the wireless state off and on on. Probably comes down to which cyberware was added first, need to test it.

**Comment by Lwmons** [comment]
That seems to have done the trick. Appreciated.
