### ISSUE TITLE
Adept Improved Reflexes Power Bug

### ISSUE THREAD

**Issue by Canefritto** [chummer5a/chummer5a#4112]
**Describe the bug**
the bonus of Improved reflexes remains even after removing the power itself

**To Reproduce**
1. after creating an adept add the "Improved Reflexes" power
2. lower the grade to 0 and the bonus remains even if you remove the power itself
3. if you remove the power and add it again you can repeat this procedure to keep increasing your Initiative Bonus

**Expected behavior**
instead if you remove the power or bring it to rating 0 it's effect should disappear

**Comment by chummer5a** [comment]
Can't replicate with current nightly or release build. Powers are allowed to go down to zero to represent background counts and qi foci and such.
