### ISSUE TITLE
Upgrade to v5.212.0 Doesn't take Effect

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#4114]
**Describe the bug**
The automatic update doesn't happen BUT when you download 212 and manually copy and paste you still get prompted to update to 212 and the version stays as 5.211.0

**To Reproduce**
Download
Open zip
Copy and paste

**Expected behavior**
Update to new version

**Screenshots**
![image](https://user-images.githubusercontent.com/5994568/82275538-a7cac400-9948-11ea-8b8f-d29bb92d8381.png)

**Comment by chummer5a** [comment]
Uploading replacement binary folder now. Assembly patching didn't work properly.
