### ISSUE TITLE
Issue: - Error and then crash

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#4117]
### Environment
Crash ID: 1ce4b85e-21ed-4dc7-9fe0-37373f841b3e
Chummer Version: 5.212.7
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 15ac6617-ebff-4677-8ff2-6f083b2ed59c

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)
![image](https://user-images.githubusercontent.com/12108972/82785968-e807d600-9e63-11ea-9a7e-e542c8d30e59.png)

**Comment by chummer5a** [comment]
Resolved in latest nightly.
