### ISSUE TITLE
Issue: Update 5.212.7 crashes career mode sheets

### ISSUE THREAD

**Issue by Wymar** [chummer5a/chummer5a#4118]
### Environment
Crash ID: 7f90fe73-4d7a-4ec1-acb6-32467dfc5cea
Chummer Version: 5.212.7
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7682d522-8b06-458d-9fe1-900f4138fb36

### Expected behaviour
Character sheet gets loaded, maybe remove some orphaned improvements removed.

### Actual behaviour
Chummer crashes.

![image](https://user-images.githubusercontent.com/1291314/82831321-6c844400-9eb8-11ea-829a-bf282e311c28.png)

### Steps to reproduce the behaviour
Start up chummer. Load a character sheet in career mode.

**Comment by Wymar** [comment]
Same issue as the previous one I think but with more details added.

**Comment by chummer5a** [comment]
Resolved in latest nightly.
