### ISSUE TITLE
Issue: - move character to created

### ISSUE THREAD

**Issue by zcauld** [chummer5a/chummer5a#4119]
[chummer_crash_132349169508353797.txt](https://github.com/chummer5a/chummer5a/files/4678959/chummer_crash_132349169508353797.txt)
### Environment
Crash ID: d69ccd68-1a33-477d-801d-5efc1fddbd97
Chummer Version: 5.212.7
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 6d14a66a-6976-466c-afe2-81f872ddf6f5

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by zcauld** [comment]
[chummer_crash_132349169508353797.txt](https://github.com/chummer5a/chummer5a/files/4678960/chummer_crash_132349169508353797.txt)

**Comment by chummer5a** [comment]
Resolved in latest nightly.
