### ISSUE TITLE
'positive quality' giving bodytech bugs

### ISSUE THREAD

**Issue by Rootlord** [chummer5a/chummer5a#412]
Hello! 

Found some bugs with quality giving cyberware and bioware. 

Metatype Reduction (Orc) Cyberware.

1st If you add it during character creation, it adds the 'human looking' quality like it should, but it costs you 12 Karma (instead of 0). If you remove the Cyberware it adds 6 Karma back, if you remove the positive quality, you get the other 6 Karma back.

2nd If you add it during career mode, you pay nuyen and it adds no quality. You pay no karma though.

Neuro-Retention Amplification never adds the 'photografic memory' quality, not at character generation, nor in career mode. If you add it at generation, you pay no Karma; so all is fine here. [Not like the Metatype Reduction (Orc) bug above].

Hope that helps!

**Comment by chummer5a** [comment]
Yeah, currently the addquality bonus doesn't remove any additional qualities when it's removed. Easy fix, but won't be in the next build. Neuro-Retention Amplification has had the appropriate addquality tag added.

**Comment by chummer5a** [comment]
Fixed in 5.177.
