### ISSUE TITLE
Issue with returning to a saved character

### ISSUE THREAD

**Issue by zcauld** [chummer5a/chummer5a#4120]
**Describe the bug**
After saving a character then closing and opening the character.  Attributes are not displayed.  Karma values are wrong.  I was using the Life Modules method.  

**To Reproduce**
1. create a character using life modules
2. Click on save
3 click on print
4. close the character
5. open the character
6. see the error

**Expected behavior**
character reopens in the state it was saved.  .

**Screenshots**
![image](https://user-images.githubusercontent.com/36544657/82929725-c54fed00-9f49-11ea-8883-24c60ab6a4f2.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.
[volbar_V2.zip](https://github.com/chummer5a/chummer5a/files/4683826/volbar_V2.zip)

**Desktop (please compl

ete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.212.8]

**Additional context**

**Comment by chummer5a** [comment]
Unable to replicate in current nightlies. Errors where it fails to load the attributes panel or karma values generally indicate an error that was silently ignored, so provided the character file is still intact and correct it should be working correctly otherwise.
