### ISSUE TITLE
Issue: - crash when scrolling in the ability list

### ISSUE THREAD

**Issue by jowilkes** [chummer5a/chummer5a#4128]
### Environment
Crash ID: bd7ff411-9d2c-49ef-ab94-2487ee292335
Chummer Version: 5.212.0.0
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: f18dd9cf-21aa-43b4-a59d-fb1696eea9a1

### Expected behaviour
just showing the lower part of the ability list

### Actual behaviour
application crash

### Steps to reproduce the behaviour
trying to scroll in the ability list

**Comment by chummer5a** [comment]
Unable to replicate in current builds.
