### ISSUE TITLE
Notes Tab looses all cr/lf (line feeds)

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#4129]
**Describe the bug**
When adding line feeds etc. all these are removed when saving and reopening the character.
tabs and other white space is preserved however.

**To Reproduce**
Steps to reproduce the behaviour:
1. create new character
2. open "Notes" tab and add one word
3. hit enter twice and add another word
4. save and close character
5. re-open character
6. see error ;-)

**Expected behaviour**
all white space incl. cr/lf should be preserved
**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.10

**Additional context**
As an additional request it would be nice to have some form of  formatting like e.g.
 - boldface
 - numbered / bulleted lists
 - colour

**Comment by chummer5a** [comment]
Unable to replicate in current builds.

**Comment by cnschu** [comment]
@Nedorus can you replicate this bug in a newer build?
