### ISSUE TITLE
Amend books is no longer loaded

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#4130]
**Describe the bug**
I have a number of custom items defined / changed in custom data files.
Most revere to my house rules as source like this:

```xml
<source>Marko</source>`
<page>0</page>
```
Some revere to another document (Unoriginal SIN by Logan Z. Hill).
In order to make this work and my house rule items to show up, I packed everything into a customdata sub-folder and activated this in the "Optional Rules" section in options.
I have also created a amend_books.xml like this:

```xml
<chummer>
  <books>
    <book>
	  <id>354c88f2-acf9-477d-b335-dd48c10f580b</id>
      <name>Markos Hausregeln</name>
      <code>Marko</code>
    </book>
    <book>
	  <id>c865291e-150f-453b-9699-a4b63ff8f64a</id>
      <name>Unoriginal SIN</name>
      <code>US</code>
    </book>
  </books>
</chummer>
```

Until recently this worked fine. Now the additional books do not show up in the books section of options. Also none of my custom data items show up anymore.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Character File**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.10]

**Additional context**

**Comment by Nedorus** [comment]
Just loaded 5.212.44 (after returning to 5.212.0) and this issue is still present.

**Comment by chummer5a** [comment]
Issue with amend content not picking the correct amend operation. As an interim, you can force it by adding `amendoperation="addnode"` as an attribute for each node you need to add, OR changing the document title to custom_books.xml. Amend documents are generally only required when performing inline alterations of content. 

```xml
<chummer>
  <books>
    <book amendoperation="addnode">
	  <id>354c88f2-acf9-477d-b335-dd48c10f580b</id>
      <name>Markos Hausregeln</name>
      <code>Marko</code>
    </book>
    <book amendoperation="addnode">
	  <id>c865291e-150f-453b-9699-a4b63ff8f64a</id>
      <name>Unoriginal SIN</name>
      <code>US</code>
    </book>
  </books>
</chummer>
```

**Comment by chummer5a** [comment]
This behaviour was changed due to issues with some amend types affecting documents that they shouldn't. Intended behaviour is now that you use amendoperation="addnode" to force it to add new content, or use the existing custom_ document structure.
