### ISSUE TITLE
Prototype Transhuman Quality not reducing essence cost for bioware

### ISSUE THREAD

**Issue by MrTonic** [chummer5a/chummer5a#4132]
When creating a new character, using prototype transhuman and adding bioware does not remove from the free 1 essence pool when the check box is selected to do so.

**To Reproduce**
Create new character.  Add prototype transhuman quality, add bioware to character with "Prototype Transhuman" box selected.  Essence will be removed from normal pool and not the extra free one.

**Expected behavior**
Points should remove from the prototype transhuman pool.

**Screenshots**
[Fairly sure that the essence should be coming out of the Prototype pool here](https://imgur.com/a/Vh7Zj9G)

Desktop (please complete the following information):

OS: Windows 10
Version 5.212.10

**Comment by chummer5a** [comment]
Unable to replicate in current builds
