### ISSUE TITLE
Issue: - Unable to add Karma/Nuyen rewards to Career Mode Characters

### ISSUE THREAD

**Issue by Wyckydgrynn** [chummer5a/chummer5a#4138]
### Environment
Crash ID: 242dc88f-9aeb-46b9-a84e-0bc2e830804c
Chummer Version: 5.212.11.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: db04d60f-f247-4358-947d-29a91b929e89

### Expected behaviour
Click on the Karma/Nuyen tab and be able to enter run rewards

### Actual behaviour
Click on the Karma/Nuyen tab and Chummer Crashes AND fails to generate proper crash report.... (The popup window is unable to be scrolled or closed without using the Windows Tool Bar. Was honestly surprised I could get it to generate/report this crash...again, by hitting the button in the popup when hovering on the program in the tool bar in Windows.)
[chummer_crash_132361383310901478.txt](https://github.com/chummer5a/chummer5a/files/4749304/chummer_crash_132361383310901478.txt)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Fixed in current nightlies.
