### ISSUE TITLE
Window shrinks when I open my character

### ISSUE THREAD

**Issue by phoff** [chummer5a/chummer5a#4139]
I just updated to 5.212.11 and opened my character. On load, the UI immediately shrinks to approximately 1/5 normal size, scaling all UI elements proportionately. I can expand the window to full size, but all the UI elements remain tiny and hard to read. Screenshot and character file attached.
[Lubrik.zip](https://github.com/chummer5a/chummer5a/files/4749478/Lubrik.zip)
![chummer_shrunken_ui](https://user-images.githubusercontent.com/785286/84097821-79299180-a9ba-11ea-9185-b463fc60d226.png)

**Comment by ReallyDarkMatter** [comment]
![image](https://user-images.githubusercontent.com/12108972/84380575-d9514b00-abe7-11ea-874b-644b35e87c2f.png)
 That from 5.212.43

**Comment by Nedorus** [comment]
I would like to add to this.

1. I tested and this happens even when using only one monitor.
2. it is independent of monitor resolution (tested in HD and UHD)
3. it is independent of Windows' scaling (see screenshot)![Windows 10 scaling](https://user-images.githubusercontent.com/25143888/84488305-49230c80-aca0-11ea-8164-e73ad92bcc2d.JPG)
4. font size seems to change when opening a character (see comparison images, they are taken directly with snipping tool and show real size comparison; check the size of the window caption for comparison)
5. also character listing entries disappear (see comparison images)
![Chummer Size befor](https://user-images.githubusercontent.com/25143888/84488374-5f30cd00-aca0-11ea-9cbc-b4b43ff42d1f.JPG) 
![Chummer Size after](https://user-images.githubusercontent.com/25143888/84488386-648e1780-aca0-11ea-9cc6-a76838b8155c.JPG)

Returning to 5.212.0 as everything worked great in that version (also stopping auto-update and "prefer nightly builds)

As an additional request: Please keep in mind, that people will use chummer on laptop with small(ish) monitors as well as on home PCs with large UHD (or more) resolution. This has been an issue for a long time. I some cases the application has been practically unusable, which is a shame as It's really a great piece of work and a main tool for serious SR players ;-)

Cheers and always thank you

P.S.: Oh, and sorry for the German in the screenshots :-P

**Comment by OLRobert** [comment]
Confirmation from my side.
Font scale 100% and FHD resolution does not show this issue at all.

**Comment by ReallyDarkMatter** [comment]
just checked it on Laptop with FHD and changed scaling from 125% to 100% and the issue is gone

**Comment by phoff** [comment]
Not sure if it's related, but ever since this happened I can't see skill ranks or the button to increment them. I thought it might be something funky in the character for, so I tried opening an old one and it's the same.
![chummer_skill_ranks_bug](https://user-images.githubusercontent.com/785286/84982197-0374a280-b0eb-11ea-9a0b-8e5303cf6706.png)

**Comment by OLRobert** [comment]
Good morning.
Same for me.
I used chummed yesterday, set FHD resolution and 100% font scaling as chummed should act as usual.
Skill ranks are not shown and it looks like phoff mentioned above.
Hovering the mouse over the skill dice pool shows it's calculation which includes rank + Attribute.

**Comment by OLRobert** [comment]
Hi there. 
Issue still exists in Chummer5a 5.212.63.0.
Workaround: 
Set all screens to Full HD and font scaling 100%, 
open Chummer, 
move it to the 2nd screen which uses FHD by default,
open the characters
change resolution of the 4k sreen and keep Chummr opened on the FHD screen.

**Comment by Spookeh70** [comment]
Hello, I tried suggested font scaling suggestions in this thread. I saw improvement, but these workaround did not restore "normal" functionality (some things were still out of alignment/too small).

I use 3200x1800 with 250& scaling (default recommended by Win10).

I tried playing around with compatibility settings and have achieved "normal" display for Chummer.

1. With Chummer program closed, go to directory where Chummer is installed
2. Right click on Chummer5.exe
3. Click on Compatibility tab
4. Click on Change high DPI settings
5. Put check in "Program DPI" box
6. In the drop down field under "Use the DPI that's set for my main display when" select "I open this program"
7. Put check in "Override high DPI scaling behavior" box
8. In the drop down field under "Scaling performed by" select "System"
9. Click Ok
10. Click Apply
11. Open Chummer

I hope this works for others like it worked for me.
