### ISSUE TITLE
Crash on Karma and Nuyen Tab

### ISSUE THREAD

**Issue by Darkman309** [chummer5a/chummer5a#4144]
### Environment
Crash ID: f2b73d61-de01-474b-88a6-8e9e2d1be7d3
Chummer Version: 5.212.44
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: a8f8ceb9-afe1-4100-800f-aa57ebec86e8

- Create new character
- Go to Karma and Nuyen Screen
- Crash: Axis has an invalid range. Appears to be due to no karma entries

**Comment by chummer5a** [comment]
Fixed in current nightlies.
