### ISSUE TITLE
Karma not subtracting for awakened qualities in Karmagen

### ISSUE THREAD

**Issue by Dragonmaster1324** [chummer5a/chummer5a#4145]
**Describe the bug**
When using Karmagen to build a character, I tried to select an awakened quality (Adept, magician), however the karma was not subtracted from the overall Karma even though the quality was added. It also seems to be only on certain qualities: Adept, Aware, Explorer, Magician, and Technomancer. I've tried to use Re-apply improvements but it doesn't seem to work

**To Reproduce**
1. Go to Charcter and select Karma for Gen
2. Click on "Qualities"
3. Scroll down to either Adept, Aware, Explorer, Magician, or Technomancer and click on them
4. See Error: Karma is not subtracted, but quality is added.

**Expected behavior**
When Quality is added karma is subtracted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Comment by chummer5a** [comment]
Unable to reproduce in current nightly builds
