### ISSUE TITLE
Adding karma causes a crash that fails to generate a crash report (nightly build)

### ISSUE THREAD

**Issue by DarbyDay** [chummer5a/chummer5a#4146]
**Describe the bug**
An application crash that fails to create a crash report.

**To Reproduce**
On nightly build 5.212.47 in career mode attempt to add karma to an existing character file.

**Expected behavior**
Karma can be added to the character.

**Screenshots**
![image](https://user-images.githubusercontent.com/34293274/84717431-18e9af80-afb9-11ea-8901-ceb12a2db5df.png)

**Character File**
[Ojo De Sangre.zip](https://github.com/chummer5a/chummer5a/files/4783579/Ojo.De.Sangre.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.47

**Comment by chummer5a** [comment]
Should be fixed in current nightlies.
