### ISSUE TITLE
Fake licence problem

### ISSUE THREAD

**Issue by Piedro0** [chummer5a/chummer5a#4147]
When i add fake licenses to my SIN, i have a list of all individual restricted gear, and yet i remember them being more broad, like: "Concealed Carry", or "cyberdeck license". To make thinks weirder everybody else i know; has things normal, as i am familiar with, and we all have the same version.
I didn't edit any options. What happened?

**Comment by chummer5a** [comment]
There is an option that specifies whether to use specific restricted items or not; should be a house rule that says 'license restricted items', from memory.

**Comment by Piedro0** [comment]
i might be blind or something, because i cannot seem to find it
