### ISSUE TITLE
problem w/ Qi focus for Improved reflexes

### ISSUE THREAD

**Issue by mav-king** [chummer5a/chummer5a#4148]
As an Adept when buying a Qi focus for Improved Reflexes the power point cost is not calculated correctly
**Describe the bug**
There seems to be an problem with the program adjusting the PP, Reaction and Iniative of an Adept after buying/binding a Qi Focus forAdept power Improved reflexes. The program works as expected with other sample Adept powers as regards to PP costs.
**To Reproduce**
Chummer 5.212.0 17/06/2020
0. (Karma creation -Human - all stats 4 - other tab  )
1. Buy 1 level of Improved reflexes 1.5 PP
2 Buy a Qi focus at level 4 for Improved Reflexes to get to 2 levels of Imp reflexes
3 pay Binding costs for Qi focus
4 In adept tab the Imp reflexes have 0 PP now has 3 levels with according increase in Reaction and initiative dice

**Expected behavior**
I'd expect that the cost in PP for the adept in this situation be 1.5 for the 1st level with the Qi focus taking care of the rest; the next 1 PP from a level 4 Qi focus. Additionally the amount of initiative and reaction in the other tab should be 10 +3d6
**Screenshots**
N/A look at character file

**Character File**
[Qi focus problem.zip](https://github.com/chummer5a/chummer5a/files/4790382/Qi.focus.problem.zip)

**Desktop (please complete the following information):**
Lenovo Thinpad X230 Tablet
Windows 10 Education
OS build: 19041.329

**Additional context**

**Comment by chummer5a** [comment]
Resolved in nightlies.
