### ISSUE TITLE
Unable to Select Metamagics when "Street Grimoire" is selected as a book.

### ISSUE THREAD

**Issue by W1ld3b34st** [chummer5a/chummer5a#415]
Environmental Information:
Program Build: V174
Operating System: Windows 10 Pro (64 bit)

Steps to Reproduce:
1) Create new Character with Karma creation, or modify existing character with Magician quality. Make sure "Street Grimoire" is selected as a book.
2) Add enough Karma if needed to add an additional Grade of Initiation.
3) Add a Metamagic. You will be unable to select any Metamagic qualities, unless showing all Metamagics.
4) This does also appear to keep "Magician" metamagics from being selected for Mystic Adepts.

**Comment by chummer5a** [comment]
That'd be because the metamagics all have weird requirements for some reason. The Anchoring metamagic requires both the metamagic and art versions of quickening. That data predates my taking up Chummer, so I'll have a scrounge and see why it's all like that.

**Comment by chummer5a** [comment]
Working as intended. For some reason you need to purchase arts in order to acquire metamagics. There's an an optional rule in House Rules to ignore the Art requirement.
