### ISSUE TITLE
Gaben mit benötigten Fertigkeiten

### ISSUE THREAD

**Issue by PeterPaker2000** [chummer5a/chummer5a#4154]
**Language "Deutsch", Gabe hinzufügen, Filter "exact 10 Karma" only, select "Puppenspieler, error message:

Sie erfüllen nicht die Voraussetzungen für Gabe. Sie müssen alle der nachfolgenden Kriterien erfüllen:
Eins von:
Psychologie 5(Fertigkeiten)
Psychologie5(Fertigkeiten)
Psychologie3(Fertigkeiten)
Psychologie3(Fertigkeiten)

At "Wissensfertigkeiten" the value is 6.

Is the same with "Hautwechsler", the "Zoologie" requirement is met but with "Wissensfertigkeiten".

**Expected behavior**
The "Gabe" should be available if the "Wissensfertigkeit" has the correct value.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809

**Comment by cnschu** [comment]
do you have a chummer version and a sample character for me?
