### ISSUE TITLE
Issue: - Latest Nightly crashes upon opening karma/nuyen tab in career mode

### ISSUE THREAD

**Issue by TaCktiX** [chummer5a/chummer5a#4155]
### Environment
Crash ID: 9f54b994-2b9e-4288-9979-b564232bfe0a
Chummer Version: 5.212.68
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 8ed85bd5-755f-48e3-94f9-f12c7cd676bd

### Expected behaviour
Karma/nuyen tab does not create a crash

### Actual behaviour
It crashed after loading the tab

### Steps to reproduce the behaviour
Click the karma/nuyen tab in career mode.

**Comment by smarekp** [comment]
I am encountering the same issue with Chummer Nightly v5.212.75, also on Windows 10 Pro.

**Comment by MagnusLundberg** [comment]
Crash ID: 7078d332-a146-4dab-8d53-eacadc88cb5c
Chummer Version: 5.212.76
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 59ea8db3-0adf-4e6c-ac95-2ead2fb5cddc

Having same issue

**Comment by smarekp** [comment]
I think I figured out why it happens: If a character has no Karma expenses logged, the empty log crashes.
I fixed it on my character by opening the character in a text editor and adding the following to the `<expenses>` node:
```xml
    <expense>
      <guid>60447ad3-201d-48e9-9834-9b743f54a77f</guid>
      <date>2020-07-04T16:04:13</date>
      <amount>1</amount>
      <reason>Starting Karma</reason>
      <type>Karma</type>
      <refund>False</refund>
      <forcecareervisible>False</forcecareervisible>
      <undo>
        <karmatype>ManualAdd</karmatype>
        <nuyentype>AddCyberware</nuyentype>
        <objectid />
        <qty>0</qty>
        <extra />
      </undo>
    </expense>
```
