### ISSUE TITLE
Shapeshifter characters (once finalised) don't use the attributes of the race for their humanoid form

### ISSUE THREAD

**Issue by ProfessorOcecat** [chummer5a/chummer5a#4162]
When you finalise a shapeshifter character and have the ability to switch between statistics for one or the other, the humanoid form (when selected) doesn't have the base attributes of race: e.g. I have an Ursine(elf) shapeshifter: Elves have 3/8 normally for charisma, but when I select the humanoid form, it displays it as being 1/6: that of a human. I'm not sure if this is in all cases for shapeshifters, or just for Ursine/Elf.
Its been a while since I've posted a bug report: so if I need to add anything to this: please let me know.

**Comment by cnschu** [comment]
shapeshifters are not elfs, so they don't get elfish race modifiers if i'm not mistaken (anyone feel free to correct me with a rulebook reference).

**Comment by ProfessorOcecat** [comment]
If that's the case, why is there different karma costs for the different
races that you can transform into?
