### ISSUE TITLE
Knowledge Skill - Languages have wrong Categories, changing subtracts Points from Actionskill and Checkbox for Nativ disappears

### ISSUE THREAD

**Issue by ReallyDarkMatter** [chummer5a/chummer5a#4166]
Chummer 5.212.78

I choose Sperethiél as Language the category was shown as Professional and i see a checkbox for Native.
When change category from Professional to Language, the Native checkbox disappears.

![image](https://user-images.githubusercontent.com/12108972/87778151-0ae2b500-c82b-11ea-9e3b-13c9992bff76.png)

![image](https://user-images.githubusercontent.com/12108972/87778179-17ffa400-c82b-11ea-9a49-c180905a6c99.png)

Also when changing from Professional to Language 1 Point is substracted from Action Skills
Before
![image](https://user-images.githubusercontent.com/12108972/88475680-7c5cea80-cf32-11ea-8c60-00921950c088.png)

After changing Japanisch from Professional to Language
![image](https://user-images.githubusercontent.com/12108972/88475698-ac0bf280-cf32-11ea-9bae-e4c670ffa800.png)

After changing Mandarin to Lanuage
![image](https://user-images.githubusercontent.com/12108972/88475740-0442f480-cf33-11ea-83cd-37eb18f469a8.png)

**Comment by ReallyDarkMatter** [comment]
Also happens if changing category to academic and street

**Comment by chummer5a** [comment]
Resolved in current nightlies.

**Comment by ReallyDarkMatter** [comment]
Now it subtracts point from academic skills then changing from Professional to Lanuage
English - Professional
![image](https://user-images.githubusercontent.com/12108972/90757961-90e89480-e2de-11ea-975a-036b8b08b80c.png)

English - Language
![image](https://user-images.githubusercontent.com/12108972/90758089-c4c3ba00-e2de-11ea-94e6-8626aafe9892.png)
