### ISSUE TITLE
Issue: - Crash when creating a Mystic Adept Shifter, was adding discounts from way of the magician

### ISSUE THREAD

**Issue by PeepTheDictator** [chummer5a/chummer5a#4169]
### Environment
Crash ID: c476b613-6ed1-4aa6-8fc6-5c1ccecd3788
Chummer Version: 5.212.80
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: a2f10a89-eeab-4dfe-b79a-8a40e164baba

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment]
Unable to replicate; was this at the same time as your other crash when adding powers that added weapons?

**Comment by Wymar** [comment]
Update: it happens when purchasing weapons, period. It's unrelated to the drones.

**Comment by chummer5a** [comment]
I think this is resolved in current commits.
