### ISSUE TITLE
Cannot buy months of lifestyle during play mode

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#417]
Not sure what's causing it, but whether I try to buy months of a lifestyle for an existing lifestyle, or create a new lifestyle, the option to buy months of a lifestyle, despite having the money to do so, remains grayed out.

**Comment by chummer5a** [comment]
Career or creation?

**Comment by HaikenEdge** [comment]
Career

**Comment by chummer5a** [comment]
Hrm. Can't replicate it. Can you upload your character file somewhere?

**Comment by HaikenEdge** [comment]
[Here you go](http://www.mediafire.com/download/bcvibb52gg9hhd1/Crow.chum5)

**Comment by cfresquet** [comment]
I noticed the same problem as well.  Let me know if you need a 2nd example.

**Comment by chummer5a** [comment]
Hrm. So the issue is that your lifestyle doesn't have a baselifestyle assigned to it. Manually changing it from <baselifestyle /> to <baselifestyle>Medium</baselifestyle> makes it work. It shouldn't be misbehaving like that though.

**Comment by HaikenEdge** [comment]
I don't know what that means, but even if I try to buy a new lifestyle in Career mode, in which case I have to select a lifestyle there, I still can't buy months for this new lifestyle I bought, and it starts with 0 months.

**Comment by chummer5a** [comment]
Should be fixed in dev, will be in 5.175.
