### ISSUE TITLE
Issue: Crash when adding weapons to drone weapon mount.

### ISSUE THREAD

**Issue by Wymar** [chummer5a/chummer5a#4172]
### Environment
Crash ID: bcd7f205-5744-497a-acaa-10fa6a7829ac
Chummer Version: 5.212.81
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7682d522-8b06-458d-9fe1-900f4138fb36

### Expected behaviour
Weapon gets added as a child to the drone's weapon mount.

### Actual behaviour
Chummer crashes after the weapon's stats get displayed on the main window.

### Steps to reproduce the behaviour
1) Buy a drone.
2) Add one of the weapon mounts to the drone.
3) Add weapon to the mount.

Confirmed to crash with multiple weapons, drones, and weapon mounts.

**Comment by chummer5a** [comment]
Fixed by https://github.com/chummer5a/chummer5a/commit/77bb8a7ff0a0b6a6df9a62c2a32269900d4a9a39
