### ISSUE TITLE
Can't buy targeting autosofts

### ISSUE THREAD

**Issue by malkavianmadman** [chummer5a/chummer5a#4175]
**Describe the bug**
When selecting to buy a [weapon] Targeting autosoft after clicking ok nothing happens and it isn't added to the gear list (Nor is money taken for it)

**To Reproduce**
Go to Street Gear
Select Gear Tab
Click Add Gear
[weapon] Targeting autosoft at whatever rating
Click OK

**Expected behavior**
I would expect to have the autosoft added to my gear.

**Desktop:**
 - OS: Windows 10
 - Version 5.212.0

**Comment by chummer5a** [comment]
Fixed in current nightlies. You can fix it on the .0 build by opening gear.xml in data, finding the targeting autosoft entry and updating the selecttext entry to:
```xml
<selecttext xml="weapons.xml" xpath="/chummer/weapons/weapon[type = 'Ranged']" allowedit="True"/>
```
