### ISSUE TITLE
Basic Runnershub pack crashes Chummer

### ISSUE THREAD

**Issue by drewski346** [chummer5a/chummer5a#4179]
### Environment
Crash ID: 097c48a0-907c-4570-9674-6ddd8a1fc344
Chummer Version: 5.212.88
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7801cad3-8802-41be-bee8-8f4d1f86a140

### Expected behaviour
I expected to add Runnerhub Basic Gear Pack to my character
### Actual behaviour
It crashed
### Steps to reproduce the behaviour
Open a new Character using the karma building system, I used a human.
Click on Special, then add a Packs Kit, then the Runnerhub Basic gear pack, hit Ok, Crash.

**Comment by DelnarErsike** [comment]
Unable to replicate in the latest Nightly. Could you please check if you can replicate the crash?
