### ISSUE TITLE
Ex-Con Negative Quality Karma Amount Incorrect

### ISSUE THREAD

**Issue by Intro-** [chummer5a/chummer5a#418]
When selecting Ex-Con (Run Faster), a character gets a total of 35 bonus Karma instead of the correct 15. The Qualities list shows Ex-Con at -15, the required SINer (Criminal) at -10, and then there's -10 mystery Karma floating around. As the two qualities together should only give -15, I suspect there's a +/-10 sign issue somewhere.

It could be fixed, or possibly Ex-Con could be changed to -5 Karma since it will always be layered on top of the Criminal SIN anyway and the bonus karma removed.

**Comment by chummer5a** [comment]
Fixed in 5.175. Freepositivequalities bonus was used instead of freenegativequalities.
