### ISSUE TITLE
A Problem with the Linguist Quality

### ISSUE THREAD

**Issue by NoctemSanguis** [chummer5a/chummer5a#4190]
**What the Quality is Supposed to Do**
The positive quality Linguist (Run Faster, Page 148) is meant to increase Langue related dice pools by 1, change the purchase of langues ratio at character creation (1 Knowledge Skill point for 2 points in a Langue), and reduce the cost of Language Skill increases after character creation by 1, costing 4 Karma.

**Problem**
In Chummer, when you select the quality it tells you to select any Knowledge Skill and adds that as a Skill with 5 points in it, which can not be increased with either Skill Points or Karma. The second issue is that the quality costs 0 Karma rather than 4.

![Chummer5a - Version 5 212 0 -  Contact _ Riot - Create New Character (Default Settings)_  8_3_2020 4_25_36 PM (2)](https://user-images.githubusercontent.com/69167568/89225388-1e6e7980-d5a8-11ea-9fca-c0780de08710.png)
![Chummer5a - Version 5 212 0 -  Contact _ Riot - Create New Character (Default Settings)_  8_3_2020 4_36_33 PM](https://user-images.githubusercontent.com/69167568/89225260-ed8e4480-d5a7-11ea-8a93-452b49929ebe.png)
![Chummer5a - Version 5 212 0 -  Contact _ Riot - Create New Character (Default Settings)_  8_3_2020 4_26_37 PM](https://user-images.githubusercontent.com/69167568/89224730-fa5e6880-d5a6-11ea-8efd-4009a3423aed.png)
![Chummer5a - Version 5 212 0 -  Contact _ Riot - Create New Character (Default Settings)_  8_3_2020 4_28_37 PM](https://user-images.githubusercontent.com/69167568/89224731-faf6ff00-d5a6-11ea-9c2e-b62990ed9250.png)

**Comment by DelnarErsike** [comment]
You most likely have the Point Priority custom data directory enabled. If you consult the Google Doc describing Point Priority's changes, one of the changes it makes is that it alters all four education traits (College Education, Technical School Education, School of Hard Knocks, and Linguist), and their effects are drastically different.
