### ISSUE TITLE
Crashes upon adding Driven Quality

### ISSUE THREAD

**Issue by chrisguru** [chummer5a/chummer5a#4196]
### Environment
Crash ID: 87426ee6-c6d6-4f93-8e50-97a8a0e4c9f5
Chummer Version: 5.212.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: Crashes
Installation ID: 6f349608-cdfe-4867-b2df-5a3d87fd2f55

### Expected behaviour
Quality can be added

### Actual behaviour
chummer crashes

### Steps to reproduce the behaviour
Open chummer
Load character
Add qualities
choose "Driven"
Add it
Enter the quality detail
click okay or press enter
Crash

[attributes.txt](https://github.com/chummer5a/chummer5a/files/5059959/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/5059960/exception.txt)

cannot add dmp file

**Comment by chummer5a** [comment]
Unable to replicate; error indicates failure to parse the PDF document's output for the quality to get the notes from. Anything unusual about your copy of the book?
