### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by Nizze82** [chummer5a/chummer5a#4197]
**Describe the bug**
Colt Coral Snake is missing in the buy weapon window, but it exists in the weapons.xml 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.212.0

**Comment by chummer5a** [comment]
Unable to replicate in current nightly builds, nothing that indicates the weapon itself should be missing. Please try again with a current nightly build.
