### ISSUE TITLE
Issue: - Crashes when trying to make new character, or modify weapon

### ISSUE THREAD

**Issue by MithrilToaster** [chummer5a/chummer5a#4198]
### Environment
Crash ID: aac00545-a6e3-4cb5-be84-82a0b6c76c44
Chummer Version: 5.212.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 934e2c3c-40a0-4db6-9d57-29d8efc8c819

### Expected behaviour
Character opens, weapon modification added

### Actual behaviour
Crash. Says. invalid URI. URI could not be determined. 
### Steps to reproduce the behaviour
Go to gear tab, right click weapon, select modification, confirm. Open Chummer, select create new character. Confirm selection. 
![Chummer Crash](https://user-images.githubusercontent.com/45775660/90207664-b552e700-dd9b-11ea-802d-ba93a45d9410.PNG)

**Comment by chummer5a** [comment]
Might be fixed in current nightlies.
