### ISSUE TITLE
UI sizingproblems on 4K monitor.

### ISSUE THREAD

**Issue by Nizze82** [chummer5a/chummer5a#4199]
**Describe the bug**
The UI is not sized correctly when used on a 4K laptop. Only half of the lines are showing. 

**Expected behavior**
The UI coping with the resolution as previous  stable version

**Screenshots**
![Chummer_problem](https://user-images.githubusercontent.com/69648927/90254758-8b54ff80-de43-11ea-9805-0883b1ee6d35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.110

**Additional context**

**Comment by DelnarErsike** [comment]
A couple of key, DPI-related changes were made between 5.212.110 and 5.212.118. Could you check the latest Nightly and report back if the same sizing issues are still present?

**Comment by Nizze82** [comment]
Hi.

Tested 5.212.126 and the GUI is still misbehaving. But, what I can see,
only in the skills tab and the Common tab.

[image: Skärmbild (20).png]
 In the skill stab, the text fields are still half height.

[image: Skärmbild (22).png]
And in the Common tab, the attributes selections are gone.

The whole program feels extremely slow. Switching to the Skills tab results
in a 1-2 second loading time.

Best regards
Nizze

Den fre 28 aug. 2020 kl 15:09 skrev DelnarErsike <notifications@github.com>:

**Comment by Spelonius** [comment]
![options big](https://user-images.githubusercontent.com/71199471/93008170-67b2d100-f537-11ea-8925-66bac2c00730.PNG)
![options house](https://user-images.githubusercontent.com/71199471/93008171-684b6780-f537-11ea-8ed0-85aea6533183.PNG)
![options karma](https://user-images.githubusercontent.com/71199471/93008172-684b6780-f537-11ea-8311-3cd6d65145b9.PNG)
![options small](https://user-images.githubusercontent.com/71199471/93008173-684b6780-f537-11ea-873d-ffab288f5b6c.PNG)
![skills](https://user-images.githubusercontent.com/71199471/93008174-68e3fe00-f537-11ea-9541-83f7a5930be8.PNG)


I just updated to 5.212.141 tonight. I had to get the windows to behave as they tried expanding and shrinking on their own when I opened characters, but starting in full screen mostly fixed that. The images I've attached are my experiences with this issue. You can see in the skills and some of the options menus that don't even have a way to adjust them anymore. The most annoying part is the box for pointing to the source books in the global settings though. In the default size you can't even see the top and when expanded you have about a line and a half of vision to scroll down and look through the options.

I honestly cannot recall what version I was using before, but it went months and months without updates before I realized the automatic updates got turned off at some point. After the initial strangeness of this issue though, I did perform a clean install.

I am running an x64 version of Windows 10 Home version 2004.
