### ISSUE TITLE
German Errata regarding Technomancer sprite limit

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4205]
**Is your feature request related to a problem? Please describe.**
In the German edition of SR5 the sprite limit got changed to resonance from logic.

**Describe the solution you'd like**
 It would be great there was an option to edit either the limit or implement a option for that errata
.

**Comment by cnschu** [comment]
what clarification do you need @DelnarErsike ?

**Comment by DelnarErsike** [comment]
From the English team as to what the sprite limit should be (I remember talk of the limit being corrected to RES in a provisional errata). The application error part is just a label for where that limit is located inside the program (i.e. inside the source code instead of in one of the data files).

**Comment by JoschiGrey** [comment]
So after some research I realized, that my memory didn't served me well and I maybe should have checked my sources before posting. I'm sorry if that raised any inconvenience.

At least in the German books and erratas I can't find any changes and it seems like the Limit is still LOG.
I'm a bit unsure about where my misinformation comes from.

A side question if I may, is there a way to house rule such things with custom data changes?

@DelnarErsike

**Comment by DelnarErsike** [comment]
There is not, no. Things like sprite limit, spirit limit, spell limits, CF limits, initiation grade limits, etc. are all 100% baked into the program's source code. You're welcome to add in support for such a house rule yourself via a pull request (it's what I did with a couple of the house rules that I wanted to support), but you shouldn't expect someone else to do it for you.

**Comment by JoschiGrey** [comment]
"but you shouldn't expect someone else to do it for you"

I certainly don't, well guess I have to learn how to program than ;)

But ty for the answer anyway.
