### ISSUE TITLE
Error Printing as PDF

### ISSUE THREAD

**Issue by Quintilium** [chummer5a/chummer5a#4206]
Im getting an error when I try to print as pdf

![Error](https://user-images.githubusercontent.com/43793626/90931734-40029a00-e3cb-11ea-9bd6-8275326375aa.png)

 - OS: [Windows 10 64 bit]
 - Version [5.212.0]

**Comment by Eblackmore66** [comment]
I was getting the same error on my laptop but not my desktop. I had not added microsoft office to my laptop yet. Once I did the error went away and I was able to print to pdf.
