### ISSUE TITLE
Most books are greyed out on Options panel.

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#4207]
**Describe the bug**
When I go through the options panel, most of the books are greyed out. 

**To Reproduce**
1. Go to the options panel
2. Click on a book
3. Check to see if it is greyed out, if not, click on another one. Most of the books are greyed out.

**Expected behavior**
To be able to click on a book, then click on the field to set the book location, adjust the page numbers, and click the button to open the book to the test page.

**Screenshots**
![Greyed out selected sourcebook](https://user-images.githubusercontent.com/32169904/90969004-83830400-e4b0-11ea-8945-5863670ce09c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.120

**Additional context**
I tried doing a clean re-install via the updater, but that doesn't seem to affect the settings file.
I would like to delete the setting file to see if that fixes it, but I can't find the file.

**Comment by ArchonMegalon** [comment]
Since you don't use the automatic update option: what version are you using?

**Comment by ArchonMegalon** [comment]
Posted a dumb question already answered... ;) (hence the edit)

**Comment by chummer5a** [comment]
I believe we resolved this in previous nightlies after discussion in discord, can you confirm it's working correctly now?

**Comment by Zitchas** [comment]
Yes, I have confirmed that it is working properly on the current nightly. (Just tested on 5.212.125).

Thanks!
