### ISSUE TITLE
Keep crashing (Both in upgrading a character and making a new one)

### ISSUE THREAD

**Issue by Ralanr** [chummer5a/chummer5a#4209]
**Describe the bug**
So originally I couldn't upgrade the special modifications quality to level 2, it kept crashing. Now I cannot build any new characters. 

**To Reproduce**

**Expected behavior**
I should be able to build a character without crashing.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
What version are you on?

**Comment by Ralanr** [comment]
I’m on 5.212. I reset my computer to fix the problem.
