### ISSUE TITLE
Attribute and Skill points not decrementing during character creation.

### ISSUE THREAD

**Issue by xSpazztic** [chummer5a/chummer5a#421]
An issue with character creation using the priority system. 

Here's how I started a new character and what I saw (running Build 174):

New Character
Priority > Prime Runner
Ignore Character Creation Rules > Unchecked
Metahuman > Troll
 - Metatype     
     A - Any
 - Attributes    
     C - 16
 - Magic/Res  
     E - Mundane
 - Skills     
     D - 22
 - Resources  
     E - 325k Nuyen

The Build Summary indicates 16 of 16 Primary Attributes, but does not change as I spend points for any of the Attributes. It doesn't prevent me from spending far more points than available. The Karma Remaining indicator at the bottom does decrement as I use the Primary Attribute points. The same occurs for skills also.

Thanks!

**Comment by chummer5a** [comment]
Hmm, I can't reproduce it in the production or dev versions. What happens
if you try and move into career mode?

**Comment by xSpazztic** [comment]
I feel stupid. It seems I was adding points under the Karma column and not the Base column. I didn't even see the difference until just now.  Please accept my apology for being brain dead this morning.

**Comment by joha4270** [comment]
Your welcome, we all are sometimes, but atleast your brainfarts don't result in bugs \:P
