### ISSUE TITLE
Black Market Pipeline not working for elektronics (5.212.0/de)

### ISSUE THREAD

**Issue by dasWolle** [chummer5a/chummer5a#4212]
**Describe the bug**
Checkbox for discount is active but cant be activated.

**To Reproduce**
1. Create connection
2. add quality black market pipeline with category electronics
3. try to add any item

**Desktop (please complete the following information):**
 - Windows 10
 - Version 5.212.0

Hint: If you set Chummers language to english and set the quality it works even after switching back to german. (maybe the select returns the german ("Elektronik") while the tags are all in english ("Electronics")? )

**Comment by chummer5a** [comment]
Unable to replicate this in current nightlies, but it's possible that you have a grandfathered quality that has the old improvement. Please try reapplying your improvements or removing and re-adding the Black Market Pipeline quality. If that fails, it's a bug we've already fixed in nightlies.
