### ISSUE TITLE
Targeting autosofts not working

### ISSUE THREAD

**Issue by Cebasiz** [chummer5a/chummer5a#4213]
**Describe the bug**

Weapon autosofts, when added to the sheet silently fail to be added. no autosoft entry appears.

**To Reproduce**

1: go to gear
2: click add (or add as plugin to existing)
3: add a targeting autosoft
4: observe failure

**Expected behavior**

targeting autosofts should be addable (and were, before) 

Version: 
win10, latest chummer v. (5.212.0)

**Additional context**
Fails for multiple people including myself

**Comment by chummer5a** [comment]
This has been resolved in current nightly builds. To resolve it manually, you can open up gear.xml, find the Targeting Autosoft item and change the bonus to 
```xml
<selecttext xml="weapons.xml" xpath="/chummer/weapons/weapon[type = 'Ranged']" allowedit="True"/>
```
