### ISSUE TITLE
Issue: - Auto-increase Aged rating

### ISSUE THREAD

**Issue by rlund88** [chummer5a/chummer5a#4216]
### Environment
Crash ID: 0d410d01-3280-4d88-be14-36830932a826
Chummer Version: 5.212.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 423bf284-6a78-43e4-a6a3-3d1ceb169d32

### Expected behaviour
Nothing should happen

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
1) Have both Aged (1) and another Negative Quality with multiple levels. 
2) Have multiple physical attributes at or one below your limit.
3) Select (left click) the second Negative Quality (in my case In Debt)
4) Select (left click) Aged

This causes Chummer to - for some reason - try and increase the Aged negative to the second (and later third) rank, which spawns the error that only one Attribute can be at max, in an infinite loop until the program crashes.
Similar interaction does not happen if you first select Aged and then In Debt (but does if you *then* go back up to Aged).

**Comment by chummer5a** [comment]
Resolved in current nightly builds.
