### ISSUE TITLE
Qi-Focus calculating power wrong for improved Reflex

### ISSUE THREAD

**Issue by Noraser** [chummer5a/chummer5a#4218]
**Describe the bug**
My Mageadept has no Adeptforce improved Reflex.
his initative is correct calkulated to 8+1w6 (Res 3+Int 5 +1w6)
I bougth a class 10 Qi focus and filled it with improved reflex, this should calculate to Class 1-6 (4x1.5) for Power 1 and Class 7-10 for Power 2 (4x1), leading to Initative 10+3w6  (res3 + int5 + Mod2 + 3w6)
But Chummer calculated it to 11+4W6 (res3 + int5 + Mod3 + 4w6). 
under Adeptforces is now an entry Improved reflex power 3
(i'm playing the German version, so not all Terms will be named correct in my description) 

**To Reproduce**
1. generate a Mageadept
2. buy a Qifocus power 10
3. define improved reflex for the Qi focus
4 check under Adept forces the power of Improved reflexes

**Expected behavior**
for a power 10 Qi focus, the improved reflexe Level should increase by 2

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.
[Din copy.zip](https://github.com/chummer5a/chummer5a/files/5210719/Din.copy.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.212.0]

**Additional context**
A frend tested it on his adept charakter an see the same problem.
over power of 6, the level jumps direct to 3

**Comment by chummer5a** [comment]
This was resolved in nightlies.
