### ISSUE TITLE
Magician Cannot Join Initiation Group (but offered a submersion group in its stead)

### ISSUE THREAD

**Issue by GreatWyrmGold** [chummer5a/chummer5a#4222]
**Describe the bug**
I'm not sure if this is a bug or just something I don't know how to do properly, but it seems buggy and this seems to be the closest thing to a chummer5a community there is, so here I am.

My magician recently joined a magical group, with intent to initiate. I saw a little box under the Initiation tab, right above a box for information about that magical group, which said "Join Submersion Group". I thought that was odd and decided to look it up later, but clicked the button, agreed to spend the five karma.
Nothing visibly changed, so I started poking around. The karma expenditure was logged under the appropriate tab, but I saw nothing else that had changed. I certainly couldn't click the Group Initiation checkbox!

I saw a couple of other initiation-related issues, but most were closed and none were as basic as "Why is my mage being asked to join a Submersion Group? Isn't that a technomancer thing?" So I came to github and started typing this.

**To Reproduce**
1. Create new magician. 
2. Enter career mode.
3. Go to Initiation tab.
4. Notice that the box says "Join Submersion Group" and not "Join Initiation Group".
5. Shrug
6. Check box.
7. Click "yes".

Your karma will probably drop by five, logged as "Joined a Group" under the "Karma and Nuyen" tab, but nothing else will visibly change.

**Expected behavior**
Since I made a magician and not a technomancer, I expected the option to say "Join _Initiation_ Group," and I expected that clicking the option and paying the five karma would...do something. At the very least, that it would let me select the little Group Initiation box.

**Screenshots**
https://prnt.sc/ukrght
https://prnt.sc/ukrgr5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.0

**Comment by chummer5a** [comment]
Fixed in nightlies.
