### ISSUE TITLE
Issue: - Reload Altmayr SPX2 with SticknShock

### ISSUE THREAD

**Issue by azania666** [chummer5a/chummer5a#4223]
### Environment
Crash ID: 279d68de-b6a5-4030-9120-b3296bf448d9
Chummer Version: 5.208.0.0
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: d84469a3-6480-4aeb-b664-ae8d7929094a

### Expected behaviour
Want to reload Reload Altmayr SPX2 with SticknShock Amunition

### Actual behaviour
Programm crashes

### Steps to reproduce the behaviour
does ist every time
![crash](https://user-images.githubusercontent.com/43959752/93988233-c32b5d00-fd88-11ea-9399-c0c06860d132.PNG)
[chummer_crash_132453237717952632.txt](https://github.com/chummer5a/chummer5a/files/5266751/chummer_crash_132453237717952632.txt)
![before crash](https://user-images.githubusercontent.com/43959752/93988280-cfafb580-fd88-11ea-91bd-0b42ac8e6c19.PNG)

**Comment by chummer5a** [comment]
I suspect this has been resolved in a previous build, but I can't find anything specific about it. Please try in a more recent build than 5.208.
