### ISSUE TITLE
Bonding a Summoning Focus asks me to choose a category of spell

### ISSUE THREAD

**Issue by larryw24** [chummer5a/chummer5a#4225]
Create a Magician Character, choose Shamanic Tradition. Buy a Rating 4 Summoning Focus. Now look at the Street Gear page and see the box labelled Bonded Foci. Click the Checkbox for the Summoning Focus. A dialog box pops up and asks me to select from {Combat, Detection, Health, Illusion, Manipulation}. I expect to see a dialog box that let me choose from {Spirits of Air, Spirits of Water .... etc}

Chummer5A is great. I love it. Thank you for all you've done.

**Comment by chummer5a** [comment]
That's not how Summoning Foci work; they're specific to a category of spirit, not a named spirit. Working as intended. If you'd like to change that behaviour, you can make an amend file that alters the selecttext bonus.
 https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files
