### ISSUE TITLE
Wireless bonus not showing up/possible character generation save issues.

### ISSUE THREAD

**Issue by bob-carter** [chummer5a/chummer5a#4226]
**Describe the bug**
The wireless bonus I should be getting doesn't show up when I click the check box, I think I got a message before about improvements not saving as well, so I fear this might be an issue with improvements saving from  character generation.

**To Reproduce**
1. Go to create a runner, click on the cyberware section, add some cyberware, finish up sheet
2. Click on Save as finished runner
3. See error

**Expected behavior**
Should save normally and later be able to notice wireless bonuses under improvements

**Screenshots**
![image](https://user-images.githubusercontent.com/46971019/94319907-2e3c8580-ff7b-11ea-86bb-04d4f568a612.png)

**Character File**
[Enchanter.txt](https://github.com/chummer5a/chummer5a/files/5285582/Enchanter.txt)

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate 
 - Version: Latest

**Additional context**
I recall not having this issue on another version, not sure which one that was, sorry for not knowing.

**Comment by chummer5a** [comment]
This should be working in current nightlies, I can't replicate the issue otherwise.
