### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by OldEyesYoungMan** [chummer5a/chummer5a#4227]
### Environment
Crash ID: 92f8efe5-66bc-4702-ab2f-13f646fca45d
Chummer Version: 5.210.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7c6392c9-5e8b-46b9-9f35-e897ae4d474d

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Could you please specify the actual issue?
