### ISSUE TITLE
Cannot Save to SINner directory using "onlinemode"

### ISSUE THREAD

**Issue by ghost2501** [chummer5a/chummer5a#4229]
While in "onlinemode" using the latest Nighty, I attempt to save an edit to a character that has been previously uploaded but I get the error window (twice) showing the error below:

-----------------------
frmSINnerResponse

Response: Object reference not set to an instance of an object.

Details: ChummerHub.API.HubException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ChummerHub.Controllers.V1.SINnerController.PostSINnerInternal(UploadInfoObject uploadInfo) in /src/ChummerHub/Controllers/V1/SINnerController.cs:line 770
   --- End of inner exception stack trace ---

Installation Id: eb7547e4-6a60-495f-9916-347cea8529b6

-----------------------

If I close the character after this, I get the notice that there are unsaved changes. I click yes to save (again) and get this error:

-----------------------
Response: This is NOT an exception from Chummer itself, but from the SINners WebService. This error happend "in the cloud": Parameter is not valid.

Details: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at Chummer.ImageExtensions.ToBase64String(Image imgToConvert, ImageCodecInfo objCodecInfo, EncoderParameters lstEncoderParameters) in C:\projects\chummer\Chummer\Backend\Extensions\ImageExtensions.cs:line 117
   at Chummer.ImageExtensions.ToBase64StringAsJpeg(Image imgToConvert, Int32 intQuality) in C:\projects\chummer\Chummer\Backend\Extensions\ImageExtensions.cs:line 138
   at Chummer.GlobalOptions.ImageToBase64StringForStorage(Image objImageToSave) in C:\projects\chummer\Chummer\Classes\clsOptions.cs:line 1077
   at Chummer.Character.SaveMugshots(XmlTextWriter objWriter) in C:\projects\chummer\Chummer\Classes\clsCharacter.cs:line 6556
   at Chummer.Character.Save(String strFileName, Boolean addToMRU, Boolean callOnSaveCallBack) in C:\projects\chummer\Chummer\Classes\clsCharacter.cs:line 1210
   at ChummerHub.Client.Model.CharacterExtended.<PrepareModel>d__24.MoveNext() in C:\projects\chummer\ChummerHub.Client\Model\CharacterExtended.cs:line 582
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ChummerHub.Client.Model.CharacterExtended.<Upload>d__22.MoveNext() in C:\projects\chummer\ChummerHub.Client\Model\CharacterExtended.cs:line 262

Installation Id: eb7547e4-6a60-495f-9916-347cea8529b6

----------------------------

**To Reproduce**
1. Login to Registered mode
2. Enable "onlinemode"
3. Restart
4. Open local Character and Upload this from SINners tab
5. Go to Character Roster & Open character listed under my registered email address
6. Make an edit and save > First error window appears
7. Click Ok on error window
8. Right-click character tab and select Close > Second error windows appears

**Expected behavior**
I expect the character to be saved locally and on the SINners directory, so that Visible users and myself can see the changes on a non-local installation.

**Screenshots**
![ChummerBug](https://user-images.githubusercontent.com/377700/94717573-e1e6b080-0393-11eb-85cd-0e5e58fd65bc.png)
![ChummerBug2](https://user-images.githubusercontent.com/377700/94719683-d1840500-0396-11eb-86d2-7e9be3c11016.png)

**Character File**
[Sumisu Kami - in game.chum5.txt](https://github.com/chummer5a/chummer5a/files/5307159/Sumisu.Kami.-.in.game.chum5.txt)

**Desktop**
 - OS: Windows 10]
 - Build: 19041

**Additional context**
I fully expect this to be a local issue but I cannot seem to find a way around it.

It might be useful to know that "SINner Groups" and "Archetypes" give no response when I select them from the Tools menu.

Logging is enabled if that helps.

Thanks for your time, please let me know if there is any further information you would like.

**Comment by ArchonMegalon** [comment]
When the Azure Service comes online again at the 22.10. this should work now in the latest nightly. If not, please reopen this issue.

**Comment by ghost2501** [comment]
Thanks.

Stay safe.

**Comment by ghost2501** [comment]
Sorry, I'm not sure how to reopen this issue.

Now that the new Stable is out I thought I'd give it another go but I get a 403 error instead of the login prompt.

![image](https://user-images.githubusercontent.com/377700/99882039-a2d92b00-2c71-11eb-9fb5-505cf2005c87.png)

Followed by this.

![image](https://user-images.githubusercontent.com/377700/99882053-c56b4400-2c71-11eb-85b6-6fd0c5320a9a.png)

**Comment by ArchonMegalon** [comment]
Shit - somehow managed to delete the wrong resource in azure... will take a look at that.

**Comment by ghost2501** [comment]
Haha no worries. (sh)It happens :)

**Comment by ArchonMegalon** [comment]
Well, I accidentally deleted my databases. And there is no way to recover them so it seems... :((((((

**Comment by ghost2501** [comment]
Oh dammm :( So that means no online mode ever?

**Comment by ArchonMegalon** [comment]
Well, no. That means i have to recreate it. and (of course) everything
stored in the old database is lost. Clean new slate....

**Comment by ghost2501** [comment]
Ohhh k. Sounds like a lot of work :(

I'm sure you have a lot of other stuff to do, I can wait a while longer  :)

**Comment by ArchonMegalon** [comment]
So.... I got the databases back online ("just" had to move them to a
different subscription - had no idea that they are still "sitting around"
in the disabled account). That was something to learn. Actually I never
intended to get to know the azure architecture that well... :D

Anyway - the database for both stable and nightly is here now. I now "only"
have to set up the webservice again and connect to them. Seems like I will
be able to recovery everything after all....

But... tomorrow! Enough for today! ;)

**Comment by ghost2501** [comment]
Whoah!!! Well done! 👍 Learning is fun, and sometimes exhausting lol

I will check in tomorrow, get some rest :)

**Comment by ArchonMegalon** [comment]
Of course I couldn't let go. Chances are, it works again. Please try it out!

**Comment by ghost2501** [comment]
Hmmm, maybe get some sleep before reading further :p 

----------

In Nightly 213.1, using chummer-beta.azurewebsites.net:

- I can login and upload a character :)

-  But, when I try to save changes to an uploaded character I get this:

![image](https://user-images.githubusercontent.com/377700/99916705-c67a9f00-2d5f-11eb-80a3-8b693a30eacb.png)

- I cannot Open: Tools > SINner Groups. There is a flash of a window then nothing.

- I cannot search or create a group. When I try the fields stay blank.

- It crashes when I go to the Advanced  Sinners Tab.

---------------


In Stable 213 using chummer.azurewebsites.net:

When I try to log in it says my account is invalid, I have tried resetting the password but I am still waiting for the reset email.

If I use a new email address to register a new account I get this:

Error.
An error occurred while processing your request.
Request ID: 00-f7e47f181f0d4846a702c861820a1b2a-8c0190a2a990de48-00 

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred. 

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.


-------------

In stable 213 using chummer-beta.azurewebsites.net

- It logs in but immediately gives me this:

![image](https://user-images.githubusercontent.com/377700/99917027-f460e300-2d61-11eb-83ef-2d7b14d76eed.png)


-----------

I'm sorry, I kinda feel bad for bringing this up...

**Comment by ArchonMegalon** [comment]
First: I got my sleep - well a bit. Baby woke me up a couple of times.
Second: You should feel GOOD to bring that up! You are helping me. Yes, I only checked the login yesterday after re-publishing and configuring the webservice against the database.

Will take (another, and another after the first "another") look at it! 

Please keep the reports coming!!!!

**Comment by ghost2501** [comment]
Haha Yeh, I guess, I am trying to help and be as thorough as I can with my reports. Nothing worse than people complaining and not actually trying to contribute something useful. Just as long as you don't feel like I am being impatient :)

Maybe, if we get lucky, the Development Mode error from Stable could be a hint that there is a Development/Production switch somewhere that will fix it. *Fingers Crossed*

**Comment by ArchonMegalon** [comment]
Still had no time to get back to this. Sorry! Life is crazy right now!

**Comment by ghost2501** [comment]
Thanks for the heads up, I think everyone is having a crazy time at the moment. Don't stress :)

**Comment by ArchonMegalon** [comment]
Ouch - that hurts to get the "wontfix" tag applied to that!

**Comment by ArchonMegalon** [comment]
Maybe this is fixed in #4470. Please check with the next nightly. 

Good chance it isn't dough.

**Comment by ghost2501** [comment]
Thanks, I'll check it out later today and let you know 👍

**Comment by ArchonMegalon** [comment]
No hurry! Had some more time to work on it (far from finished) and THINK uploading may work again now as well. 

Fixing the groups is still on my todo list...

**Comment by ghost2501** [comment]
This is what happens when I try to login on the latest Nightly.

Please don't stress over it. The table game I was running has broken up so
I don't really have a reason to use it for now.

Thanks for keeping it in mind :)

### Environment
Crash ID: b2d81c63-5e1e-447f-a9b5-baff8fa94c8c
Chummer Version: 5.214.85
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 1e78805e-25bc-435a-b751-a8d32242b247

[image: image.png]

**Comment by ArchonMegalon** [comment]
Hm... can you please reupload the image or the Errortext? I can't see it here...

**Comment by ghost2501** [comment]
Sorry, I attached it to the email reply.

What would be the best way to send it to you?

**Comment by ghost2501** [comment]
![image](https://user-images.githubusercontent.com/377700/121314193-773a3b80-c94a-11eb-938f-7110f02640cd.png)

**Comment by ghost2501** [comment]
I have no idea how to code at all, I'm astounded that people can make sense of any of it lol it just looks like chaos to me!

**Comment by ArchonMegalon** [comment]
There are actually "layers" of bugs here. Wow. Well, I guess we have to try again in a couple of days... :D

**Comment by ghost2501** [comment]
No rush at all. I wish I could be of more help but breaking things seems to
be my forte :p
