### ISSUE TITLE
Life Modules do not properly add knowledge skills

### ISSUE THREAD

**Issue by 13thsyndication** [chummer5a/chummer5a#4233]
**Describe the bug**
When you add a Life Module using the Life Modules method of character creation, it does not add knowledge skills and you are required to buy those skills which deducts points/karma

**To Reproduce**
1. Make a new character
2. Select "Life Modules" character generation method
3. Add a Life Module that adds a Knowledge skill, like UCAS - SINless
4. Go to the Skills page, where all skills added by the Life Module have been added except the knowledge skill.

**Expected behavior**
Life Modules add knowledge skills to the Skills page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.163

**Additional context**
This hasn't worked properly since I started using Chummer5, though back then Life Modules were still a WIP; IDK if that's still the case, so if it is, that's fine, I just wanted to make sure you guys knew about this!

**Comment by chummer5a** [comment]
Yeah, due to the wide variety of edge cases we had to account for with knowledge skills, we just set it to add free knowledge skill points instead.

**Comment by 13thsyndication** [comment]
Oh! That's actually really cool, thank you.Guess this isn't really an issue then.
