### ISSUE TITLE
Targeting Autosoft still bugged

### ISSUE THREAD

**Issue by Erkusandor** [chummer5a/chummer5a#4236]
**Describe the bug**
When buying the targeting autosoft, it won't be added to your inventory or your drone.

**To Reproduce**
1. Buy a drone.
2. Right-Click on said drone and select "Add gear".
3. Scroll down to [Weapon] Targeting Autosoft and confirm.

**Expected behavior**
The Autosoft should be added to the drone.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.201.0

**Additional context**
Changing [Type = 'Ranged'] in gear.xml to [type = 'Ranged'] fixes the problem.

**Comment by DelnarErsike** [comment]
This was fixed in the 5.212.x Nightlies a long time ago. Closing the issue.
