### ISSUE TITLE
Adding [Weapon] Targeting Autosoft not functional

### ISSUE THREAD

**Issue by AwesomeEli** [chummer5a/chummer5a#4241]
**Describe the bug**
When attempting to add a [Weapon] Targeting Autosoft in any fashion, during character creation or after, the pop up for selecting which weapon it is for does not appear, and the Autosoft is never added.

**To Reproduce**
Create a new character or open an existing one.
Go to Street Gear
Add Gear
Select Autosofts from the drop-down
Select [Weapon] Targeting Autosoft
Add

**Expected behavior**
Upon clicking add, Chummer should display a window with a dropdown that would allow the user to select which weapon the autosoft applies to. Once chosen and stepped through, it should add the autosoft, with weapon designation, to the character.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.00

**Comment by DelnarErsike** [comment]
The issue in 5.212.0 has been known for a very long time and was fixed in the Nightlies in commit ef9e393c8bff060afd335070acd6eb58a15a6831.
