### ISSUE TITLE
Mystic Adept getting charged 5 Karma instead of 2 per Power Point during Chargen.

### ISSUE THREAD

**Issue by ednemo13** [chummer5a/chummer5a#4244]
I am probably doing this wrong, but I was using the common tab option "Mystic Adept Power Point" during character creation and it is costing 5 karma per point instead of 2 karma. 

**To Reproduce**
1. Go to the Common tab and select Mystic Adept Power Point

**Expected behavior**
This should charge 2 points.

**Screenshots**
![Chummer1](https://user-images.githubusercontent.com/33814060/96794348-069ada80-13cc-11eb-86d1-93c549972994.png)
![chummer2](https://user-images.githubusercontent.com/33814060/96794349-07337100-13cc-11eb-8f6c-763c61b54af3.png)

I have a feeling I am just doing this wrong. Please let me know if you need anything else. 

Thanks, Ed.

(I absolutely love this program!!!)

**Comment by chummer5a** [comment]
It got errata'd to 5 karma ages ago. There's a setting under Karma Costs to adjust how much it costs.
