### ISSUE TITLE
can't add plugins to modular cyberlimb

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#4248]
**Describe the bug**

Can't add plugins to modular cyberl

**To Reproduce**

Using latest nightly, create a new character.  Add a modular cyberlimb (either in a location or standalone without, doesn't matter).
Try to add a plugin; get error.  (All six types of modular limbs will error).

To confirm that I was doing what should normally work...tried with a normal cyberlimb instead, and could add plugins as expected.

**Other details**

All the modular limbs list as having zero capacity -- "Capacity: 0 (0 remaining)"  this seems likely related.

**Expected behavior**

Plugins should work on modular limbs

**Desktop (please complete the following information):**

 OS Windows 10
Version: latest nightly release

**Comment by DelnarErsike** [comment]
Cannot replicate in the Nightly build. It's possible that this is being caused by a custom ruleset. Are you running with any enabled?

**Comment by cfresquet** [comment]
i figured that was possible, so I went and grabbed the latest nightly, and unzipped it in a new folder and ran it there -- is there anything else I need to do to start from a clean state?

**Comment by chummer5a** [comment]
That doesn't affect your customdata settings; you'll have to either disable those manually or open the Computer\HKEY_CURRENT_USER\SOFTWARE\Chummer5\CustomDataDirectory registry key and delete what's in there to have a proper clean slate.
