### ISSUE TITLE
Incorrect Availability on Firewall stat for Fuchi N-Series

### ISSUE THREAD

**Issue by tirypr77** [chummer5a/chummer5a#4249]
From Kill Code, Page 60:

> **N-SERIES RULES**
> Ordering a custom setup costs the amounts below. Deck
> Rating in this case determines the maximum rating of any other
> attribute. As described above, the N-series can only store and
> run a single program, regardless of their rating. Once set, the
> attributes for any given cyberdeck cannot be changed.
> ATTRIBUTE AVAIL COST
> Deck Rating (Deck Rating x 2)R Rating x 5,000¥
> Attack — Rating^3 x 500¥
> Sleaze — Rating^2 x 500¥
> Data Processing — Rating^2 x 500¥
> Firewall — Rating^3 x 500¥

ibid page 61:

> EX-SERIES RULES
> Ordering a custom setup costs the amounts listed below.
> For the Ex-series, a deck’s Device Rating determines the
> maximum rating of every other attribute, but it can run a number
> of programs equal to the Device Rating plus two.
> ATTRIBUTE COST AVAIL
> Deck Rating (Deck Rating x 2)R Rating x 10,000¥
> Attack — Rating^3 x 500¥
> Sleaze — Rating^2 x 500¥
> Data Processing — Rating^2 x 500¥
> Firewall (Rating x 4)R Rating^3 x 500¥

Currently, plugging the Firewall attribute into the decks use only the EX-Series rules for the restricted rating (Firewall x4 R), regardless of whether adding to the EX or N deck. The Rating for the N deck should be unrestricted. Could split into two different plugins, one for each deck type.

**Comment by Stexinator** [comment]
Does this only apply to the firewall?
