### ISSUE TITLE
Mystic adepts and metamagic

### ISSUE THREAD

**Issue by charlofsweden** [chummer5a/chummer5a#425]
If you initiate a mystic adept and attempt to add metamagic to the character chummer only seems to allow you to add metamagics available to adepts. Mystic adepts should have magician metamagics available to them as well.

**Comment by cfresquet** [comment]
Just like full mages, mystic adepts need to choose an Art in order to unlock metamagics. 

You can turn off this requirement in the Tools->Options->House Rules as "Ignore Art requirements from Street Grimoire" if you don't want to use it.
