### ISSUE TITLE
Armor and Elemental Protection 

### ISSUE THREAD

**Issue by AGulyaev12** [chummer5a/chummer5a#4253]
Chummer calculates Elemetal protection as 

X + Y = Z

where X - highest equipped armor
           Y - highest armor mod 
           Z - total elemental protection

but according to the Catalyst team first you need to compare Elemental armor protections of all the equipped armors and only the highest Armor Elemental protction is applied. So if we have 

Armor Jacket - 12 
and
Lined Coat + Fire resistance mod (6) = 15

then for protection against fireball Lined Coat + Fire resistance mod is used.

**Comment by chummer5a** [comment]
Got a source for that?

**Comment by AGulyaev12** [comment]
> Got a source for that?

The topic about that has arisen here https://forums.shadowruntabletop.com/index.php?topic=18429.0

There is an quote form Xenon on that thing. 

Chummer usually calculates Elemental protction from all the sourses despite the fact that they come from different pieces of armor. For instance you can have an Armor Jacket and a Lined Coat w/ Fire Resisnace mod. Chummer will add points from Fire resistance to the Armor Jacket protection points.

**Comment by AGulyaev12** [comment]
Also there is a comment in this thread regarding armor scaling https://forums.shadowruntabletop.com/index.php?topic=31474.0
