### ISSUE TITLE
Could there be an added function to "mirror" cyberlimbs?

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#4254]
**Is your feature request related to a problem? Please describe.**
For certain character types that revolve heavily around their cyberlimbs, it's a bit of a hassle during creation to go back into the Plugins tab 20 times to add the same set of equipment to two identical limbs.

**Describe the solution you'd like**
An additional option when right clicking a limb to Mirror a Cyberlimb, so say, a modified Full Obvious Cyberleg(Right) can be duplicated, only with the descriptor of (Left) instead

**Describe alternatives you've considered**
Only other option is to go in and add everything manually. While it's not especially hard, it is a bit tedious. This feels like a nice quality of life improvement.

**Additional context**
This is a courier I've been working on. Everything you see here only covers one side. While I can duplicate it manually, an option to do so automatically would be nice.
https://i.imgur.com/ISY3LAF.png

**Comment by chummer5a** [comment]
Need to make copy-paste behave correctly with limbs.
