### ISSUE TITLE
Add to README what platform this software is for and how to obtain/install it

### ISSUE THREAD

**Issue by gene1wood** [chummer5a/chummer5a#4255]
As someone who's not familiar with what chummer5a is, coming to this repo and reading the README and visiting the releases page
* I don't see in the README what platform this software is for. Is this a mobile app? IOS/Android? An app to be run in Windows/Mac/Linux?
* The releases page contains a zip file. I'm unsure from this what platform this project is targeting
* I see that it's written in C# so I'm guessing this is maybe an IOS app

It would be great if it said what chummer5a was and if the release page or README indicated how to obtain and install it on whatever platform it's designed for.

**Comment by DelnarErsike** [comment]
Understood.

For your specific questions, Chummer targets the Windows platform and is dependent on .NET Framework 4.7.2. Unless we're talking about a Unity project, iOS apps are written almost exclusively in Swift and Objective C, and Android apps tend to be written almost exclusively in Java or C++. C# is Microsoft's baby primarily, so best guesses for the platform of a C# project would be Windows Phone or Windows.

**Comment by Stexinator** [comment]
To add to that, a section "How to contribute?" would be nice
