### ISSUE TITLE
Crash when opening character sheet, no error log

### ISSUE THREAD

**Issue by Glitch-kun** [chummer5a/chummer5a#4256]
When a chummer version past .112 is used to open certain character sheets, it crashes before it can load, and produces a blank error log. An affected character sheet is attached.
[Geodesic (HH career).zip](https://github.com/chummer5a/chummer5a/files/5571179/Geodesic.HH.career.zip)

**Comment by DelnarErsike** [comment]
Cannot replicate in the latest Nightly (5.213.12) with no custom rulesets or special house rules enabled. Could you double-check to see if you are still having this issue with the current Nightly?
