### ISSUE TITLE
life module magical education

### ISSUE THREAD

**Issue by zcauld** [chummer5a/chummer5a#4258]
**Describe the bug**
unable to select life module magical education during the Teen Years.  

**To Reproduce**
1. create character  - Life Module/Standard
2. Add quality - I tried with both Magician and Mystic Adept qualities
3. select life modules -
     Tir Tairngire Elves/Humans - click add & more
     Early Emergence - click add & more
     Magical Education (Magician) - click add & more 
4 . loops back to the Teen Years

**Expected behavior**
for the Magician - 
Expected it to ask which two of three skill groups to add a rank
add +1 to Willpower/Charisma

Mystic Adept 
Add 1 rank to any of the two groups listed for Magician or Adept.
add +1 to Willpower/Charisma

Both - 
Arcana +2, Academic
Knowledge: Magical Theory +5,
Academic Knowledge: [Any] +4,
Academic Knowledge: [Any] +4,
Academic Knowledge: [Any] +3,
Language [Any] +2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.3

**Additional context**

**Comment by chummer5a** [comment]
This happens due to you already getting a SIN from another life module. The current setup for life modules does not support the ability to gain and lose SINs.

Merging with #2000
