### ISSUE TITLE
Bunker Gear Incorrect Fire Resistance

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4259]
When buying Bunker Gear, it comes in with only R6 Fire Resistance. RAW should be R8
![Screen_Shot_2020-11-23_at_4 06 08_PM](https://user-images.githubusercontent.com/1766631/100151908-b85b7a00-2e56-11eb-83dc-63829279e95b.png)

```
<armormod>
          <guid>afabdd8e-8acb-497a-88cd-d7a9cdb49bbb</guid>
          <sourceid>dd246520-7306-40fb-88b4-c9cb031208fc</sourceid>
          <name>Fire Resistance</name>
          <category>General</category>
          <armor>0</armor>
          <armorcapacity>[0]</armorcapacity>
          <gearcapacity />
          <maxrating>6</maxrating>
          <rating>8</rating>
          <ratinglabel>String_Rating</ratinglabel>
          <avail>6</avail>
          <cost>0</cost>
          <bonus unique="fireresistance">
            <firearmor>Rating</firearmor>
          </bonus>
          <wirelessbonus />
          <wirelesson>False</wirelesson>
          <source>SR5</source>
          <page>437</page>
          <included>True</included>
          <equipped>True</equipped>
          <extra />
          <stolen>False</stolen>
          <notes>Fire resistance: Fire-retardant, nonflammable ma- terials protect the wearer against Fire damage (p. 171). Add the full rating of the Fire Resistance modification to the Armor value when resisting Fire attacks or checking if the armor catches fire.</notes>
          <discountedcost>False</discountedcost>
          <sortorder>0</sortorder>
        </armormod>
```

Think I found the problem

```
          <maxrating>6</maxrating>
          <rating>8</rating>
```

rating is set to 8, but maxrating is only 6
[4:10 PM]
yup. upping that 6 to an 8 fixed it
[4:12 PM]
hmm.... how do I submit that fix to the github...
[4:15 PM]
ahh ballocks...
[4:16 PM]
this is what it has in armor.xml

```
      <mods>
        <name rating="8">Fire Resistance</name>
        <name>Restrictive</name>
      </mods>
```

> chummer5isalive replied to TeksuraToday at 4:39 AM
Ha! Yeah, I remember implementing that and thinking that someone had fucked up. Uh, I think it's possible for existing gear to override the maxrating value when added as child items, but I just reformatted so my dev environment's dead. Raise it as an issue for me in git and I'll poke it tomorrow

**Comment by chummer5a** [comment]
Resolved in current builds.
