### ISSUE TITLE
Cannot save a newly created character if the program language is "German" and the quality is "Quick Healer"

### ISSUE THREAD

**Issue by WaykoAstragon** [chummer5a/chummer5a#4264]
**Describe the bug**
I cannot save a newly created character which has the quality  "Quick Healer" . 
If the language is set to English, it works with no problem

1. When Chummer is set to German.
2. When I create a new character, whether it's priority or karma.
3. I select "Quick Healer" (nothing else, this is the only quality.)
4. And then I want to save, I get an error.

**Expected behavior**
I expect it to be saved without errors
 
 - OS: Windows 10 1909
 - Version 5.213.13
 
![Error](https://user-images.githubusercontent.com/33957866/100953120-2f0d0d00-3512-11eb-991a-43a59f28582b.png)

**Comment by Stexinator** [comment]
Do you have linked the PDFs so it autofill notes? Do you have a lifestyle?

**Comment by DelnarErsike** [comment]
Should be fixed in the latest nightly, commit 66e1f1649ccd21699584e634a4c2c16f4b78dbbc. Please re-open if this is not the case.
