### ISSUE TITLE
Using essence hole lowers magic attribute

### ISSUE THREAD

**Issue by slowcar** [chummer5a/chummer5a#4266]
I want to replace bioware on my adept.
I have Orthoskin 3 (0.75 essence), and want to replace it with Orthoskin 4 Delta (0.5 essence), and add Adapsin (0.2 essence).
However, when i remove the old Orthoskin, and add the new one, the magic rating is lowered by 1, despite the essence hole being used.

**Comment by DelnarErsike** [comment]
Should be fixed in the next Nightly. Please re-open this issue if it is not.
