### ISSUE TITLE
Box to track sustained spells

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4267]
I would like to request in the Spells and Spirits tab a box to note how many spells are currently being sustained. Along with a checkbox to note if you're on Psyche or not, this can apply itself into an improvement to apply the appropriate dicepool penalty to actions.

**Comment by ArchonMegalon** [comment]
I second that. Great Idea! If I only would have more time!

**Comment by JoschiGrey** [comment]
Is anyone actively working on this?

If not I gonna take a look as soon as I'm finished with my recent pull request and finally managed to comprehend how improvements work / how I could add a new one.

**Comment by ArchonMegalon** [comment]
No, no one is working on this right now. It would be very much appreciated if you could take a look at that!
