### ISSUE TITLE
Suprathyroid and Other Bioware/Magic interaction

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#427]
The Suprathyroid Gland stacks with Muscle Toners, the latter which explicitly states it is incompatible with other things that augment your Agility, but fails to stack with the Improved Reflexes Adept power, which only specifies it won't stack with augmentations improving Initiative, even though the Suprathyroid Gland improves Reaction and not Initiative.

**Comment by chummer5a** [comment]
Suprathyroid just has an incorrect precedence value set, mostly coming from an attempt to make Improved Reflexes work from what I can see. Improved Reflexes itself I'm trying to wrap my head around. So it increases Reaction, but if there are other sources of Reaction bonus, the reaction bonus doesn't count for Initiative? But then wired reflexes says that it doesn't stack with other sources of REA OR INI.

I hate RAW.

**Comment by HaikenEdge** [comment]
That's not how I read it at all; to me, it reads as not stacking with anything that directly Initiative increases, whereas the Suprathyroid increases Reaction directly, and therefore Initiative indirectly, and therefore stacks with Improved Reflexes, the same way the the Cerebellum Boosters increase Intuition directly and Initiative indirectly, or Improved Physical Attribute (Reaction) increases Reaction directly and Initiative indirectly, and therefore also stacks with Improved Reflexes.
