### ISSUE TITLE
Cannot load Character after Update to 5.213.0

### ISSUE THREAD

**Issue by GermanDarkShadow** [chummer5a/chummer5a#4273]
**Describe the bug**
.Cannot load 2 of my Characters after installing the update.
Afterwards tried the nightlybuild, doesnt work either.
I am using the german language for the chummer.

The following Failures will be thrown by loading:
Diese Datei konnte aufgrund des folgenden XML-Fehlers nicht geladen werden:
", hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 1763, Position 38

An on the tab "Beschreibung" : 

System.Xml.XmlException: '', hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 1763, Position 38.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   bei System.Xml.XmlTextReaderImpl.ParseText()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei Chummer.CharacterCache..ctor(String strFile) in C:\projects\chummer\Chummer\Classes\clsCharacter.cs:Zeile 18773.

on second chraracter nearly the same:

The following Failures will be thrown by loading:
Diese Datei konnte aufgrund des folgenden XML-Fehlers nicht geladen werden:
", hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 1763, Position 38

An on the tab "Beschreibung" : 

"System.Xml.XmlException: '', hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 1763, Position 38.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   bei System.Xml.XmlTextReaderImpl.ParseText()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei Chummer.CharacterCache..ctor(String strFile) in C:\projects\chummer\Chummer\Classes\clsCharacter.cs:Zeile 18773."

**To Reproduce**
try to load the character...

**Expected behavior**
To load the character

**Desktop (please complete the following information):**

    OS: Windows 10
    Version 1909 (Build 18363.1256

**Context**
Happens after Change from previous version of chummer.

**Comment by ArchonMegalon** [comment]
Can you please upload the character files here?

**Comment by GermanDarkShadow** [comment]
Of course, here: https://drive.google.com/drive/folders/1RXbQ0hwlhYhBb_-EOS4YaKM4ihIfq6mk?usp=sharing

**Comment by Feneis42** [comment]
Moin, I have the same problem


System.Xml.XmlException: '', hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 73, Position 36.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   bei System.Xml.XmlTextReaderImpl.ParseText()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei Chummer.CharacterCache..ctor(String strFile) in M:\Coding\chummer5a\Chummer\Classes\clsCharacter.cs:Zeile 18632.
