### ISSUE TITLE
Negative Essence and Essence Hole

### ISSUE THREAD

**Issue by Gideon-Lovat** [chummer5a/chummer5a#4274]
When I was purchasing and deleting cyberware related to adapsin, I somehow ended up with negative essence. But I also have an essence hole that is greater than my negative essence. 

Not sure if there is an easy fix or not, but is there a way to make them cancel themselves out? Basically, I'm looking to apply my essence hole to raise my essence to a positive number so that my essence is calculated correctly again.

**Comment by chummer5a** [comment]
Would need to see the character, sounds like something's gone sideways with it.
