### ISSUE TITLE
Can't add addons to weapons when I use german as language after update to 5.213 also some old characters don't load correctly.

### ISSUE THREAD

**Issue by Quadrophonic** [chummer5a/chummer5a#4279]
I updated from 5.207 to 5.213 and am experiencing the following problems when I use the german language:

When I load up certain old characters I get the error message:
"Orphaned Improvements were found in your Character file. In most cases it should be safe to load this character, but you may want to make a backup or copy of this character file."

In addition to that I have another problem. I can't add improvements/attachements to weapons, as soon as I do I get the message:
"Chummer hat beim speichern des Charakters einen Fehler festgestellt."
Translation:
"Chummer has detected an error while saving the character."

This happens when I try to safe the character after I have added attachements to the weapon. This happens with most attachements, but not all of them. For Example:
1. I add an Ares Crusader II
2. Right click on it.
3. Click on "Zusatz hinzufügen".
3. I choose "Elektronisches Feuern" and press "Ok"
4. I try to safe the character and get the error message: "Chummer hat beim speichern des Charakters einen Fehler festgestellt." and it doesn't safe the character.

When I switch to english I can create a character and give addons to weapons without any problems.

**Comment by ReallyDarkMatter** [comment]
It could be ligatures, check the notes. Search for the letters "fi" missing like "nde" in "finde"
Delete all spaces before "nde"

**Comment by Quadrophonic** [comment]
> It could be ligatures, check the notes. Search for the letters "fi" missing like "nde" in "finde"
> Delete all spaces before "nde"

Sorry I am totally new to this, which notes should I search?

**Comment by Quadrophonic** [comment]
I don't know if you'll read this ReallyDarkMatter, but thanks. I finally found out what you meant and you're right. The problem lies in the notes, once I knew what you meant it was actually quite easy to find it.

For whomever with the same Problem, open the notes or "Notizen" to the item in question by right clicking on it and search for missing letters "fi". For example the "fi" in Modifikation, it will look like this "Modikation", delete the word, rewrite it and you're good to go.
