### ISSUE TITLE
Skill not raised in career mode after skill groups invested during creation.

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#428]
On a theoretical character I was working on, I noticed that, in career mode, I would raise Leadership to 6 from 2, save and exit, and then when I reopened the character, the skill would once again be at 2, even though the Karma log showed the Karma spent. The skill previously was raised to 2 ranks via the Influence skill group, which I then broke, but it seems like it's reverting back to the skill group every time I load the character.

**Comment by joha4270** [comment]
That !"#&%)"! is back?

oh dam, guess i take a look at it the weekend, but i'm starting to feel
like rewriting skill groups.

2015-10-02 18:09 GMT+02:00 HaikenEdge <notifications@github.com>:

**Comment by HaikenEdge** [comment]
I didn't know it was a thing previously, but I did notice that, when I loaded the character, despite the skill being reverted to the number in the skill group, the skill group was still considered broken.

**Comment by HaikenEdge** [comment]
I'm seeing this in Heavy Weapons as well now, and it wasn't a skill in a skill group; in fact, I took the skill up to 6 at creation, but when I put it into Career Mode, it mysteriously dropped to 4 ranks, and reverts to that after I save and exit, even though the Karma is show to have been used in the log.

**Comment by Kyoto-Kid** [comment]
...I've been seeing the same happen after saving a character in Career mode.

**Comment by HaikenEdge** [comment]
This still seems to be a problem as of 5.179.739. Any idea as to when it'll be resolved?

**Comment by joha4270** [comment]
Soon. It is fixed on the "newskills" branch, but that is still missing
features and probably won't be in time for next release.

**Comment by joha4270** [comment]
I should change that to "it is being worked on"

I honestly don't know when they are done, there always seems to be more to do...

**Comment by angelforest** [comment]
As workaround, you can open save file in text editor and manually reset all values for skillgroup to unmodified state (rating, base, karma is 0, broken is False) - skills will keep their individual levels as if you never had skillgroup in the first place.

**Comment by joha4270** [comment]
This should be fixed in the latest nightly
