### ISSUE TITLE
Skill Change in Skill Groups

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#4280]
Cybertechnology is in Electronics, but Computer who should be, isn`t.

Can you please fix this, as due to the core rulebook, p. 144, Cybertechnology belongs to the Biotech Skill Group and Coumputer to Electronics.

**Comment by chummer5a** [comment]
Correct in data. Sounds like you're using the point priority chargen customdata file or some other custom content.

**Comment by DecklandMulqueen** [comment]
i found the hoese rule THX ALOT
