### ISSUE TITLE
Reinforce spell from Street Grimoire appears to be missing from Chummer 5e

### ISSUE THREAD

**Issue by Anonymoogle** [chummer5a/chummer5a#4282]
**Describe the bug**
Cannot find the Manipulation spell **Reinforce** (Street Grimoire p118). Have tried looking on multiple new and previous spellcasting characters, not sure what else to try?

**Comment by chummer5a** [comment]
It's in the data, got the sourcebook active? Are you using a different language file than english?

**Comment by Stexinator** [comment]
@Anonymoogle
