### ISSUE TITLE
 Equipment save failed

### ISSUE THREAD

**Issue by WaykoAstragon** [chummer5a/chummer5a#4285]
**Describe the bug**
When I add the Schockpolster (shock pad in German) and save it, I get the error (see attachment)

**To Reproduce**
In my attached zip file, the saved character is simply loaded and tried to add the shock pad and then save.

**Expected behavior**

The character should be saved with the modification.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/33957866/103433266-bff90600-4bee-11eb-9e22-4f658932e396.png)

**Character File**
[SWAT-Sam.zip](https://github.com/chummer5a/chummer5a/files/5758629/SWAT-Sam.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.39

**Additional context**
Chummer is in German and have entered all of my rules Pdf.

**Comment by ReallyDarkMatter** [comment]
Must likely it is ligatures again.
Search the notes on equipment and adavantages for word with "fl" or "fi" like Reflexbooster.
Chummer pulls notes from the rolebooks

The char you uploaded opens fine with the latest nightly

**Comment by WaykoAstragon** [comment]
Ok now it works, thx.
