### ISSUE TITLE
Character Files are no longer saveable after any Lifestyle is added

### ISSUE THREAD

**Issue by Quadrophonic** [chummer5a/chummer5a#4286]
**Description**
I have problems with the german version. If I add any Lifestyle to a character, chummer is no longer able to save the file.

**To Reproduce**
- Set the Language to german
- Create a new character
- Add any Lifestyle (You'll find it under "Straßenausrüstung>Lebensstil")
- Name the Lifestyle (It doesn't seem to matter what you call it)
- Try to save the file and recieve error that the character can't be saved

**Expected Behavior**
Obviously I expect to be able to save the character :)

![image](https://user-images.githubusercontent.com/76595078/103440985-c4530c80-4c4a-11eb-8db8-0cdc7230e6fc.png)

**Desktop:**
 - OS: Windows 10
 - Version 5.213.0

**Additional context**
Is there a way to disable ligatures? It would help mitigate a similar problem, where I am no longer able to save a character because of ligatures in the notes?

**Comment by ReallyDarkMatter** [comment]
Go into the notes find the error correct it and you will be able to save the char

**Comment by Quadrophonic** [comment]
> Go into the notes find the error correct it and you will be able to save the char

In this particual case (Lifestyle) there are no notes I could delete.

**Comment by ReallyDarkMatter** [comment]
check other equipment and even advantages.
You could upload your char

**Comment by Quadrophonic** [comment]
> You could upload your char

I'll do that. As you can see the character is completely empty. Could it be that there are 'Hidden' notes in the Lifestyle for Grid Subscriptions? Because There is literally nothing else there.

When I swich to english I can add a lifestyle and save just fine.

**Comment by Silver-tri** [comment]
Hi I have the same problem
