### ISSUE TITLE
Missing Sporting Rifles by Drone Mounts

### ISSUE THREAD

**Issue by WaykoAstragon** [chummer5a/chummer5a#4287]
**Describe the bug**
The sporting rifles are missing from the drone weapons. However, they can be selected under the normal weapons.

**To Reproduce**
See image

**Expected behavior**
That the weapons are selectable.

**Screenshots**
![Drone](https://user-images.githubusercontent.com/33957866/103902245-89455300-50fa-11eb-9bde-df77c8e59544.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.46

**Comment by chummer5a** [comment]
RAW, sporting rifles are excluded from the weapon mount's allowed categories. I'll make a customdata override for it.

**Comment by WaykoAstragon** [comment]
> RAW, sporting rifles are excluded from the weapon mount's allowed categories. I'll make a customdata override for it.

May I ask where that is, or is it different in the English rules than in the German?

**Comment by chummer5a** [comment]
> Light weapon mounts can hold weapons in the following categories: Melee, Tasers, Hold-Out Pistols Light Pistols, Heavy Pistols, Machine Pistols, and Submachine Guns. Standard weapon mounts can hold Tasers, Hold-Outs, Light Pistols, Heavy Pistols, Assault Rifles, Sniper Rifles, Shotguns, Exotic Ranged Weapons, Flamethrowers, and Special Weapons. Heavy weapon mounts can hold any of the previous, as well as weapons from the following categories: Machine Guns, Cannons, Launchers, and Lasers.
