### ISSUE TITLE
Character Load error since 5.213.0 (still working with 5.212.0)

### ISSUE THREAD

**Issue by Soileat3r** [chummer5a/chummer5a#4288]
Im getting Errors when I try to laod my characerts in chummer5 5.213.0

System.Xml.XmlException: '', hexidezimaler Wert 0x1E, ist ein ungültiges Zeichen. Zeile 1349, Position 24.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   bei System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   bei System.Xml.XmlTextReaderImpl.ParseText()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei Chummer.CharacterCache..ctor(String strFile) in M:\Coding\chummer5a\Chummer\Classes\clsCharacter.cs:Zeile 18632.

thats the issue.
It just happens with some Charaters, it says Can not load Metatype
![chummererror](https://user-images.githubusercontent.com/77290769/104212624-b618a380-5435-11eb-9675-3116f81384fb.png)

**Comment by chummer5a** [comment]
Resolved in nightlies, issue with ligatures imported from pdf. If you're not comfortable using nightly builds, you can open your character file in notepad, search for "&#x1E;" and replace it with fl. If that doesn't work, please provide the file and I'll fix it for you.

**Comment by ArchonMegalon** [comment]
I thought I only implemented this "show the Exception in the Detail" in the
Sinners Plugin. Did you guys implement that for normal loading as well?
Because.... I wonder if I messed something up and wrote that code in the
wrong place....
