### ISSUE TITLE
Issue: - clicked on in the weapon list on the narco jet 

### ISSUE THREAD

**Issue by AntixUser** [chummer5a/chummer5a#4294]
### Environment
Crash ID: 380917d5-53e7-4955-a3a0-5bc90c69cf98
Chummer Version: 5.212.0.0
Environment: Windows 7 Professional
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7c3844e7-44cd-4f10-86ee-108373ed275b

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Could you please check with the latest Nightly to see if this is still an issue?
