### ISSUE TITLE
Issue: - Chummer Crashes when trying to add an Agent

### ISSUE THREAD

**Issue by Spelonius** [chummer5a/chummer5a#4295]
### Environment
Crash ID: c640b6fb-7e5b-4d41-a83e-0d5ec79a26dc
Chummer Version: 5.213.59
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: c196586e-2c03-4a07-9557-a7573eed9a4c

### Expected behaviour
Pull up info to add an agent program, whether independently or as a plugin

### Actual behaviour
Whether adding separately or as a plugin, as soon as you select Agent from the gear list, it pulls up the option to submit an error or close.

### Steps to reproduce the behaviour
In the Street Gear tab, select add gear or add as plugin, type "Agent" in search, select from the list. It crashes when it tries to load.

**Comment by DelnarErsike** [comment]
Cannot replicate, neither in Create nor in Career mode. Could you be more specific about your setup?

**Comment by Spelonius** [comment]
I apologize for not updating on this. I do not know what happened, but last weekend when I was going through my character and chummer had updated, it allowed me to add the agent properly. I was in career mode when it happened before, but I can't really think of anything more specific that would help replicate the issue. It simply crashed when the agent was selected in the menu, like it couldn't load the information on it or something.

**Comment by DelnarErsike** [comment]
What custom data do you have enabled? Maybe one of them messes with Agents?
