### ISSUE TITLE
Problem loading older characters

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4296]
**Describe the bug**
Opening older characters all attributes and skills are shown as zero, character information fields are blank. The strange thing is if I change the date attributes of the file (not the contents of the file) it opens correctly.

**To Reproduce**
1. Open attached character Breaker1. 
2. See that the character looks like a newly created one - a human.
3. Open attached character Breaker2. 
4. See that the character has correct attributes - and is a Dwarf.

**Expected behavior**
Character file opens without having to mess with file attributes.

**Screenshots**
Listed files - Breaker2 is a copy of Breaker1 with the date changed attributes modified, the contents of the two files are identical:
![Breaker - file list](https://user-images.githubusercontent.com/17562417/105120154-56567400-5a97-11eb-8eba-108d10f3423b.png)

Character display 1
![Breaker1 - original file attributes](https://user-images.githubusercontent.com/17562417/105120169-5fdfdc00-5a97-11eb-9521-ed96d3090dd5.png)

Character display 2
![Breaker2 - changed file attributes](https://user-images.githubusercontent.com/17562417/105120240-7d14aa80-5a97-11eb-90db-c849ade99870.png)

**Character File**
[Character files.zip](https://github.com/chummer5a/chummer5a/files/5839850/Character.files.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.213.61 [and prior]

**Comment by DelnarErsike** [comment]
Cannot replicate, both files load in fine and give identical characters (no custom data files enabled, but that shouldn't make a difference).

**Comment by Lochabar** [comment]
Just tried again with the latest release and the problem is still there. Maybe you don't see it because the file attributes have probably changed because of being unzipped.

**Comment by DelnarErsike** [comment]
Nope, the file attributes are the same as what you posted. Number 1 has a last modified date of sometime in June 2020, Number 2 is January 2021.

Note 1: internally, the only time Chummer pays attention to the last modified date of a file being loaded in is when it looks and prompts for autosaves. Are you sure you're not absent-mindedly clicking "Yes" on an autosave restoration prompt?

Note 2: the setup you show for number 1 is not the default selection. The default selection for Priority is ABCDE Human Adept, so you'd see the character have a lot less Nuyen and have a Magic rating if that was what was being loaded in for 1.

**Comment by Lochabar** [comment]
No autosave prompt is generated.

Here is a video of opening the file:
https://user-images.githubusercontent.com/17562417/106385151-54908880-6394-11eb-9fb3-bafcb838ffd8.mp4

This a screenshot of the roster after opening the file - notice the character is correctly shown as a dwarf:
![Breaker1 - roster](https://user-images.githubusercontent.com/17562417/106385212-ae914e00-6394-11eb-938b-c9ea9b828a53.png)

Notice that  the Character 1 screenshot above (and the video) show the character is a human.
(Also the Character 1 screenshot shows 10k have been spent to generate more Nuyen, so some things are loaded.)

**Comment by DelnarErsike** [comment]
Could you check something for me? Close Character 1 in Chummer without closing Chummer, then open Character 1 again. You can also try opening a different character in between. I remember seeing something odd when testing these saves, and I'm curious if the program's behavior is any different on your end if you try loading the character a second time.

**Comment by Lochabar** [comment]
Opening the character a second time (either using the Open->File dropdown, or from the roster) opens the character correctly.
Closing Chummer then reopening the character from the roster loads the character correctly.

Removing the character from the roster then using Open->File produces the problem. It would appear its something to do with opening a character directly that is not in the roster.

**Comment by Lochabar** [comment]
Thanks for the fix - the character (and others with this problem) now open correctly.
