### ISSUE TITLE
Add "Specializations Don't Break Skill Groups" As A House Rule

### ISSUE THREAD

**Issue by Forgoten-Null** [chummer5a/chummer5a#4298]
The long and short of it is that I play on a midsized LC where there has been debate about adding this as a house rule, but chummer to my knowledge doesn't support this feature. At the moment the biggest argument against having the rule is that it's just not supported and that it makes book-keeping a hassle if we were to implement it on the server.

It would be greatly appreciated if someone could look into potentially adding this as a house rule.

To be clear, the requested house rule would just be a house rule that would make it so that active skill specializations don't break skill groups, allowing players to have specialized skills while also maintaining a skill group.

**Comment by chummer5a** [comment]
Does some weird things in create mode. Easy enough in career mode. Personally strikes me as being excessive since specialisations are intentionally cheap.

**Comment by Forgoten-Null** [comment]
"Personally strikes me as being excessive since specializations are intentionally cheap."

The value of skillgroups on this server ends up being more focused on the training time than the actual karma cost. The reduced karma cost is nice, but the server runs in realtime so it's just significantly more painful for someone who has a character or character's who want to be skilled in a group or groups of skills to get them up over time with them. If your training time is 10 weeks, that's 10 weeks real time you have to wait. So that's the main mechanical incentive to have this rule pushed. 

There's also a general agreement that it doesn't make sense thematically, someone who's skilled in all manner of firearms, as an example, still might favor revolvers over most pistols. Someone who's good at influencing people might be just that little bit better at bargaining or haggling with people.  That sort of thing. A lot of people want to reflect this in their characters, so they will go for specializations, often at character gen, which effectively punishes you long term as you can never increase said skillgroup ever again.

Anyway, a fix for career mode at least would be fine. You can already have a specialization and still mess with skillgroups in Karmagen very freely, so people can still use that if they really want to do it. Really just introducing the option and allowing easy access to it will probably get it pushed on the server.
