### ISSUE TITLE
Karma to Nuyen and Mystic Adept Power Points selection boxes missing

### ISSUE THREAD

**Issue by jumuraa** [chummer5a/chummer5a#4300]
**Describe the bug**
When creating a new character, the Karma to Nuyen and Mystic Adept Power Point selection boxes are not available on the Common tab.

**Expected behavior**
Karma to nuyen is expected all the time. The text is present, but there is no selection box to actually assign karma to nuyen.
Mystic Adept Power Points are only expected when that option is selected from the qualities. The text is present when this is the case, but there is no selection box to assign karma to Mystic Adept Power Points.
These function fine in Chummer 5.212

**Screenshots**
![image](https://user-images.githubusercontent.com/78049254/105903385-6e714a80-5fe5-11eb-938b-d1d57fa85fe5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213

**Comment by DelnarErsike** [comment]
Could you check in the latest Nightly if they are still missing there?

**Comment by jumuraa** [comment]
They are now functioning. Great work!
