### ISSUE TITLE
Negative Quality - Stolen Gear - not adding Karma

### ISSUE THREAD

**Issue by Maehdron** [chummer5a/chummer5a#4303]
**Describe the bug**
When using the negative quality Stolen Gear it does not add karma in character creation.  It does count in the right hand side total of negative quality points used.

**To Reproduce**
1. In Common Tab
2. Click on Add Quality
3. 'Select Stolen Gear'
4. Click Add

**Expected behavior**
Negative quality had 20 levels, each providing 1 karma.  Karma Remaining should be increased by 1 per level.

**Screenshots**
With Stolen gear lvl 20 - Note karma remaining -20, and negative qualities 35/35
![Stolen1](https://user-images.githubusercontent.com/78501753/106826196-6e5ff300-6654-11eb-9296-4c69c6bd89e4.jpg)
Exact same char with stolen gear removed - Note karma remaining -20, and negative qualities 15/35
![Stolen2](https://user-images.githubusercontent.com/78501753/106826200-715ae380-6654-11eb-90da-3788144b54cd.jpg)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.213.0]

**Additional context**
It is properly adding 10k Nuyen to the character per level, just not the karma as expected.

**Comment by chummer5a** [comment]
Working as intended. Stolen Gear functionally 'spends' the bonus karma you get on the nuyen that you're buying with it. 

> [...]for each point of Karma (up to 20) spent on Stolen Gear, the character gets 10,000 nuyen (see below) to spend on gear, cyberware, and/or bioware during character creation. These points are spent instead of the normal Karma for extra cash (not in addition to), and extend the possible additional funds to 150,000¥

**Comment by Maehdron** [comment]
My bad.  Glossed over how it mentions you also spend them.
