### ISSUE TITLE
Add a House Rule that Automatics use Pistols Skill and the Automatics Skill is removed

### ISSUE THREAD

**Issue by RyanthusarMercury** [chummer5a/chummer5a#4310]
In our Shadowrun Group we use the Pistols Skill for Pistols and Automatics and at the moment chummer shows me for Automatics Weapons a lower value. It would be also good if the specializations from Automatics would be added to Pistols Skill, too.

**Comment by chummer5a** [comment]
You'd do that with the [amend system](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files#amend-data-files). Suggest reviewing Delnar Skills Remake, particularly amend_weapons.xml.

**Comment by RyanthusarMercury** [comment]
Thanks for the suggestion. The part with skill removal worked fine in amend_skills.xml
<chummer>
  <skills>
    <skill xpathfilter="contains(name,'Automatics')" amendoperation="remove" />
  </skills>
</chummer>

But i think i have overseen something that this part in amend_weapons.xml starts using the pistols skill
<chummer>
  <weapons>
    <weapon xpathfilter="category = 'Submachine Guns'">
      <useskill>Pistols</useskill>
      <spec>Submachine Guns</spec>
    </weapon>
	<weapon xpathfilter="category = 'Machine Pistols'">
      <useskill>Pistols</useskill>
      <spec>Machine Pistols</spec>
    </weapon>
  </weapons>
</chummer>

**Comment by Stexinator** [comment]
@RyanthusarMercury if I understand correctly your orignial issue is resolved. Can you close this?

**Comment by RyanthusarMercury** [comment]
@Stexinator Unfortunately not, if I don't remove the Automatics Skill, the dice pool remains unchanged, which means either something is wrong with the xpathfilter or something is wrong with the useskill. And since my only example of how I could use it is the Optional Rules Delnar Skill Remake and which at least doesn't work with the current version either, I'm unfortunately not getting anywhere

**Comment by DelnarErsike** [comment]
Alright, so the fact that Delnar Skill Remake wasn't calculating weapon dicepools properly should be fixed in Nightly v5.213.107 and later. That should hopefully clear up part of this.
I'll see about adding a dedicated "remove Automatics" ruleset later.
