### ISSUE TITLE
Viper SIlvergun not Reloading

### ISSUE THREAD

**Issue by Raeywinde** [chummer5a/chummer5a#4312]
The Viper Silvergun will not reload even if you have ammo in your gear - it keeps saying "No Heavy Pistol Ammo Available"

**To Reproduce**
Attempt to reload the Viper Silvergun

**Expected behavior**
It should allow for reload

**Screenshots**
![image](https://user-images.githubusercontent.com/78942891/107723253-bd3e0600-6cae-11eb-8ed9-770f23fb28b8.png)

![image](https://user-images.githubusercontent.com/78942891/107723269-c6c76e00-6cae-11eb-80e7-e3a534298ff1.png)

**Comment by RyanthusarMercury** [comment]
Hi,

the Ares Viper Slivergun only uses Flechette Ammunition. Then it should work with reload.

**Comment by Stexinator** [comment]
@Raeywinde is this resolved?
