### ISSUE TITLE
Autosofts stacking instead of just moving lower in the list

### ISSUE THREAD

**Issue by YourCompanionCube** [chummer5a/chummer5a#4315]
**Describe the bug**
when i try to organize the autosofts on my drone they group together instead of remaining separate and just reordering the list
**To Reproduce**
1. Go to vehicles and drones
2. Add two autosofts (had maneuvering and targeting) 
3. Try to rearange them and find on ends up "inside" the other

**Expected behavior**
To be able to just reorder the autosofts amongst my other mods

**Screenshots**
![image](https://user-images.githubusercontent.com/26364270/107879663-2f2d6f80-6ea8-11eb-86fc-8bc94d88ec5f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.0

**Comment by chummer5a** [comment]
Off the top of my head, right-click drag moves things between items, left-click drag should reorder them.

**Comment by YourCompanionCube** [comment]
yes, but left click drag is what i was doing
