### ISSUE TITLE
Error when launching. New install/setup

### ISSUE THREAD

**Issue by M2Talaroc** [chummer5a/chummer5a#4317]
### Environment
Crash ID: 7d94df6d-7b4a-44dc-bb40-d18e86ef6488
Chummer Version: 5.213.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 48a27fd6-27ca-4bd6-ab60-21b08ca8560c

### Expected behaviour
Start up

### Actual behaviour
Error when loading Master index (38/39)

### Steps to reproduce the behaviour
Kill process in Task manager and relaunch.

**Comment by DelnarErsike** [comment]
Could you test with the latest Nightly?

**Comment by M2Talaroc** [comment]
The issue has been resolved..😀
