### ISSUE TITLE
Error importing chummer JSON to Roll20 char sheet

### ISSUE THREAD

**Issue by LinasJurevicius** [chummer5a/chummer5a#4321]
**Describe the bug**

It seems error started happening with 2.13 version of chummer. After trying to import character JSON file to Roll20 character sheet, Roll20 started to give error and character import stopped working. Downgrading to previous good version does not work either. Looks like something changed in chummer character XML or generated JSON structure. Error message below:
 
"Error with Skills: ReferenceError: attr_expImport is not defined" 

**Character File**
Character file attached
[Kasumi.zip](https://github.com/chummer5a/chummer5a/files/6030838/Kasumi.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.213.95]

**Comment by DelnarErsike** [comment]
As far as we can tell, this is an issue with the Roll20 sheet, not with anything that Chummer does. Please contact the person who works on that sheet.
