### ISSUE TITLE
Restricted Gear Issue with Missiles

### ISSUE THREAD

**Issue by TravisDudley** [chummer5a/chummer5a#4322]
**Describe the bug**
Missiles seam to be counted twice when comparing to the limit of Restricted Gear.

**To Reproduce**
I have a character with the Restricted Gear Quality. If I try to add a single Anti-Vehicle Missile (availability 18F) saving the character as Created fails. If I remove the single missile from Gear, it can be saved just fine.

I suspect what is happening is that since a missile is Ammunition it needs to be added in the Gear tab. However, doing so adds a grayed out version in the Weapons tab. Are both entries being counted and so it thinks I have two missile rather than one?

**Expected behavior**
Since I am only adding a single item, I would expect this to be alowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/79547535/108919963-e1c8a500-7601-11eb-9780-b40d41b09fa7.png)
![image](https://user-images.githubusercontent.com/79547535/108920330-7c28e880-7602-11eb-9201-c75e7a6941c0.png)
![image](https://user-images.githubusercontent.com/79547535/108920038-fc028300-7601-11eb-8590-37ac24786d8e.png)

**Character File**
[Hijack Gunner.zip](https://github.com/chummer5a/chummer5a/files/6032283/Hijack.Gunner.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.95 (I was using 5.213.0, but figured I'd get the latest to make sure).
 - 
**Additional context**

**Comment by DelnarErsike** [comment]
Fixed by dd3a25729a8906a57600d95f32446210d5a35896. Please re-open if this is not the case.
