### ISSUE TITLE
Be able to delete an Exotic Weapon Skill

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4323]
**Is your feature request related to a problem? Please describe.**
Added the wrong Exotic Weapon Skill (Garrote instead of Monofilament Garrote).

**Describe the solution you'd like**
A delete function for Exotic Skills with a zero Rating.
Perhaps a "Delete" button, similar to the Knowledge skills.
Or the red minus button, see Regain/Spend Edge, positioned under the green plus signs of the regular skills.

**Additional context**
Attached is a screen shot of the Exotic Skills and a knowledge skill - I'm suggesting either the "Delete" or "Minus" for the zero rated Garrote Skill.

![Skills](https://user-images.githubusercontent.com/17562417/109383118-e7e0af00-78a9-11eb-82f0-2005da0712ad.png)

**Comment by Stexinator** [comment]
In the nightly there is a delete button

**Comment by Lochabar** [comment]
I'm actually dealing with a career character. But trying with both a crate mode and a career mode character, offing an Exotic Skill automatically adds the new skill with a rating of 1. But I've identified a problem.

Using a career mode character
1) add an exotic skill - it appears in the skill list with a rating of 1
2) Goto Karma and Nuyen tab and undo the the purchase of the Exotic Skill
3) Go back to the Skills tab - the new skill is still there with a rating of 0 and no way to get rid of it.

So my original request still stands for a Career mode character
