### ISSUE TITLE
When trying to import characters in Roll20, the message attr_expImport is not defined is returned

### ISSUE THREAD

**Issue by alpha-1983** [chummer5a/chummer5a#4324]
**Describe the bug**
When exporting a newly created career character to Roll20, through the export JSON option, the following error message is displayed by the Roll20 sheet: "attr_expImport is not defined is returned"
When checking the JSON data generated by Chummer I see that the attribute does not exist.

**To Reproduce**
1. Create a new character (both priority and sum to ten tested), then mark it as created, so it can be moved to the career mode
2. Export the character. To do so, go to File->Export. There select the JSON option. Either copy the displayed contents or save them into a JSON file
3. Copy the JSON contents into the field Chummer Import located in the Character tab of the Roll20 sheet.
4. Click import and then Accept
5. The error "Error with Skills: ReferenceError: attr_expImport is not defined" will be displayed

**Expected behavior**
The contents of the JSON file are expected to be loaded by the Roll20 character sheet.

**Screenshots**

[txema(JSON).txt](https://github.com/chummer5a/chummer5a/files/6057980/txema.JSON.txt)
[Txema (chum5).txt](https://github.com/chummer5a/chummer5a/files/6057981/Txema.chum5.txt)
![Chummer import failure](https://user-images.githubusercontent.com/32544452/109433900-fe564a00-7a12-11eb-849d-04a566fed224.PNG)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [Windows 10 1909]
 - Version [Chummer 5.213.100] but has been failing with previous nightly versions too

**Additional context**

**Comment by Stexinator** [comment]
This is already fixed in Roll20. You just have to wait until the next Roll20 rollout

**Comment by chummer5a** [comment]
Pinning this until it's implemented on roll20's end.

**Comment by Stexinator** [comment]
@chummer5a this can be closed. It is already fixed
