### ISSUE TITLE
Camera vs Micro-Camera Capacity

### ISSUE THREAD

**Issue by meins111** [chummer5a/chummer5a#4326]
Core Book page 444, Table Optical & Imaging Devices:
- Camera: Capacity = Rating
- Micro-Camera: Capacity = 1

Installing a camera as a sensor to a drone adds a Camera with variable rating.
Going with a rating 3 should allow 3 enhancements being installed in said camera, but it always stays at capacity 1 regardless of its rating. 
Thus the sanity check of the character fails.
Also (maybe linked issue): raising the rating on the so-added camera does not increase its cost.

![image](https://user-images.githubusercontent.com/15341626/109602621-c0474c00-7b20-11eb-8e69-1006d9fea531.png)
![image](https://user-images.githubusercontent.com/15341626/109602651-cdfcd180-7b20-11eb-9c90-c014ae23302d.png)

**Comment by chummer5a** [comment]
Square brackets indicate that it consumes 1 capacity of the Parent. Vision Enhancement has a capacity consumption equal to its Rating, thermographic is [1].
