### ISSUE TITLE
Adding/Removing Cybereyes Does Not Reinstate Natural Vision Qualities

### ISSUE THREAD

**Issue by JHommond** [chummer5a/chummer5a#4327]
**Describe the bug**
If you add cybereyes to a character that naturally has a positive vision quality (low-light vision, thermographic vision, etc.) and then remove the cybereyes, the natural vision quality will still have a note that the quality is being suppressed by the cybereyes. 

**To Reproduce**
1. Go to Cyberware / Bioware tab with a character with natural low-light or thermographic vision
2. Add cybereyes to your character
3. Delete cybereyes from your character
4. Go to the Common tab and see the note indicating that the Low Light or Thermographic Vision quality still has a note indicating that the quality is being suppressed by the cybereyes (which were deleted from the character)

**Expected behavior**
The note indicating that the positive vision quality being suppressed by the cybereyes should have been removed when the cybereyes were deleted from the character's Cyberware / Bioware tab

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Comment by DelnarErsike** [comment]
Is this with the Nightly or not? Because this exact issue was fixed a few days ago in db3a10c22e135ad06d4cfe7aee99bc3ebf8e003e.
