### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Dragonmaster1324** [chummer5a/chummer5a#4333]
### Environment
Crash ID: fab32188-ca08-49cf-ac88-1d0f10709fa2
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: ae577ce9-b9ea-4eeb-a0b6-09ac0241144d

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Could you provide more information about the crash?
