### ISSUE TITLE
Update to 5.214.3 successfull, but

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#4335]
... it crashes that moment, when i open the "custom data" tab in character oprions and try to choose one or more

**Comment by DelnarErsike** [comment]
Could you send me the contents of your `settings` folder?

**Comment by DecklandMulqueen** [comment]
I went back to 5.214.0 …

 

When choosing options, everything goes fine! Global options and the personalized ones exept:

 

You cannot click the options in der described folder and set your marks. It crashest hat moment but does not create a bug report … otherwise i would have sent this

 

 

Von: DelnarErsike ***@***.***> 
Gesendet: Dienstag, 16. März 2021 23:29
An: chummer5a/chummer5a ***@***.***>
Cc: DecklandMulqueen ***@***.***>; Author ***@***.***>
Betreff: Re: [chummer5a/chummer5a] Update to 5.214.3 successfull, but (#4335)

 

Could you send me the contents of your settings folder?
