### ISSUE TITLE
Closing Chummer5a with an open character locks the program

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4336]
**Describe the bug**
When closing Chummer5a with an open character the program locks up and windows shows "Not responding".

**To Reproduce**
1. Open Chumer5a
2. Open a character (no changes)
3. Click the red "X" in the top right corner to close the program

**Expected behavior**
Character is closed and Chummer5a closes.

Note: if there is not an open character (either because none was opened or the character was closed manually) the program closes correctly.

**Screenshots**
https://user-images.githubusercontent.com/17562417/111311067-c3b3fa80-862b-11eb-9e36-49289ec954a3.MP4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.214.3 (and earlier)

**Comment by DelnarErsike** [comment]
Cannot reproduce. Could you send me your save file(s) just in case this might be character-specific?

**Comment by Lochabar** [comment]
The problem still occurs in 5.214.4

It happens with all my characters - several are attached
[Characters.zip](https://github.com/chummer5a/chummer5a/files/6156812/Characters.zip)

The characters have not been updated for some time. Certainly not since the modifications to create individual character settings

Here are the settings
[settings.zip](https://github.com/chummer5a/chummer5a/files/6156817/settings.zip)

There are no save files - I haven't made any changes when I close Chummer5a

**Comment by DelnarErsike** [comment]
Hmm, cannot reproduce. This may be a machine-specific issue. Could you compile Chummer5a on your local machine, run it in Debug mode, go through your reproduction steps, and then see where the debugger breaks when the program ends up hanging?

**Comment by Lochabar** [comment]
Are there any instructions on how to do this?

**Comment by DelnarErsike** [comment]
Download and install Visual Studio Community 2019 and download Chummer5a's source code. Then, open up Chummer.sln with Visual Studio. Once it loads, go to Debug > Start Debugging (or click the green play button at the top with "Start" next to it).

**Comment by Lochabar** [comment]
I don't have the room on my windows machines to install Visual Studio.

**Comment by Lochabar** [comment]
I installed Chummer on another laptop. Closing the program with an open character worked correctly. So it must be a machine-specific issue.

**Comment by Lochabar** [comment]
Latest release on original machine now closes correctly
