### ISSUE TITLE
Chummer 5.214.3: Opening a character from a previous version strips attributesa

### ISSUE THREAD

**Issue by Areskali** [chummer5a/chummer5a#4338]
Using 5.214.3 on Windows 10

When opening a character that was created on 5.213.x, the character loads all equipment, skills, notes, qualities, cyberware, bioware.

HOWEVER, all Attributes are reset to base level.  See attached screenshot.

![Chummer Attribute Issue 5 214 3](https://user-images.githubusercontent.com/78988553/111337434-785e1400-864c-11eb-9688-3d16a9dfabb7.JPG)

**Comment by DelnarErsike** [comment]
Cannot reproduce with saves that I have. Could you attach a savefile?

**Comment by Areskali** [comment]
[Raptor.zip](https://github.com/chummer5a/chummer5a/files/6152877/Raptor.zip)

Here you go!

**Comment by DelnarErsike** [comment]
Hmm, attributes load just fine for me. Could you upload the contents of your `settings` folder?

**Comment by Areskali** [comment]
[settings.zip](https://github.com/chummer5a/chummer5a/files/6152893/settings.zip)


 Settings attached - thanks for your help!
