### ISSUE TITLE
Unable to add new critter powers to infected character

### ISSUE THREAD

**Issue by Diaphteiros** [chummer5a/chummer5a#4339]
I just downloaded the newest release (5.214.0) of Chummer and I have the following problem:

I built an infected character. During creation, everything worked fine. Now the character is in career mode and I want to grant him new critter powers (e.g. regeneration). However, if I click on "add power" in the "critter powers" tab (roughly translated from German chummer), a dialog window pops up but there aren't any powers I could choose from. I can filter for "all" or "infected", but the list is always empty.

Is this a bug or did I make a mistake somewhere?

**Comment by DelnarErsike** [comment]
Because Infected critter powers cost karma, Chummer implements them as qualities.
