### ISSUE TITLE
Enfield AS-7 Should Have the Option to Take Drums but Doesn't

### ISSUE THREAD

**Issue by Tryryke** [chummer5a/chummer5a#4349]
Chummer Version: 5.214.00
Environment: Windows 10

**Expected behavior**
Ammo Skip available on weapons with the Underbarrel mod slot

**Actual behavior**
The mod seems to be missing from a myriad of weapons with the slot available, including shotguns like the Defiance T-250 and Enfield AS-7.

**Comment by DelnarErsike** [comment]
Ammo Skip is only available for weapons with (cy) and (d) ammo capacities. It is very likely that of your "myriad" of weapons missing it, most of them are weapons with (m) or (c) ammo types. The Enfield AS-7 is a special case because it is both (c) and (d) type, so I'll have to look at that later.

**Comment by Tryryke** [comment]
Fair enough, it's kinda hard to tell what kind of capacity the weapon has, either in program or the actual books. My apologies.
