### ISSUE TITLE
Chummer crashes after clicking the Add Exotic skill button in active skills.

### ISSUE THREAD

**Issue by Vital-ire** [chummer5a/chummer5a#4354]
**Describe the bug**
Chummer crashes trying to add exotic skill.

**To Reproduce**
1. Go to skills
2. Click on add exotic skill
3. Fails to create system crash report 
4. Chummer crashes.

**Expected behavior**
I want to add an exotic skill, in this case grapple hand use.

**Screenshots**
[here](https://gyazo.com/cd9622ff9e493b63136bb4198d4d1481)

This is the message I get trying to just add an exotic skill.

 - OS: [Windows 10]
 - Version  5.214.0

[Scian-createdtest3.zip](https://github.com/chummer5a/chummer5a/files/6253940/Scian-createdtest3.zip)

**Additional context** 

(Also before reapplying improvements it applies a combat foci twice, and afterwards it removed a purchased adept powerpoint from chargen when improvements are reapplied.)

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the nightlies

**Comment by Vital-ire** [comment]
> Known issue, already fixed in the nightlies

what/where is that exactly?

**Comment by DelnarErsike** [comment]
Nightlies are builds that are published on a daily basis, assuming any changes happen on that day. They can be found in the Releases page, and they will usually be numbered something like `5.214.18` or something (as opposed to milestone builds, which end with `.0`)
