### ISSUE TITLE
[Nightly] character options with Sum to Ten blocks character load

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4359]
**Describe the bug**

**To Reproduce**
Character Options -> change karma to sum to ten-> save -> restart chummer -> try to open character

**Expected behavior**
character opens

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Win 7
 - Version: 5.214.24

**Comment by DelnarErsike** [comment]
Cannot reproduce with the built-in Sum-to-Ten option. Is there maybe something else that's necessary to reproduce?

**Comment by Stexinator** [comment]
As of 5.214.27 the issue is resolved
