### ISSUE TITLE
[Nightly] create character with Sum to Ten crashes chummer

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4360]
**Describe the bug**

**To Reproduce**
Create a new character with Sum to ten

**Expected behavior**
Character is created

**Screenshots**

**Character File**

**Desktop (please complete the following information):**
 - OS: Win 7
 - Version 5.214.24

**Additional context**
Access to "settings"(folder) is not authorized

**Comment by DelnarErsike** [comment]
I think this issue is specific to the particular way Chummer is set up on your machine since I cannot reproduce it and the Additional context definitely seems to indicate that something is different. Still, it would be good to know how to fix this, in case other people have similar setups as yours.

**Comment by Stexinator** [comment]
Any idea which information might be helpful?

**Comment by DelnarErsike** [comment]
See if Chummer crashes if:
1. You use a built-in setting (I assume you're trying with a custom one).
2. You move your Chummer Nightly installation to a different location, where your user would have full permissions to all subfolders.
3. If you have an anti-virus software that has RansomWare protection of some kind, see if turning that off (or creating an exception for Chummer) helps.
4. If you have multiple computers, see if you are able to reproduce it on the second computer and if so, how.

**Comment by Stexinator** [comment]
![grafik](https://user-images.githubusercontent.com/69796777/114177219-6d8d5b00-993c-11eb-8660-1fb2d9fc9fff.png)

AllBooks is the only custom one. With the update to 5.214.27 the issue is resolved
