### ISSUE TITLE
Issue: update crash

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#4368]
### Environment
Crash ID: d27e52e0-5eb9-4274-b16d-90ba55044a32
Chummer Version: 5.213.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 022c98d6-2e54-47e2-ae2e-05e074b12655

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by ArchonMegalon** [comment]
Can you try to download the latest stable (or nightly, if you prefer that) manually and install it?

**Comment by Johnny8-0** [comment]
After it crashed I launched Chummer again and it had updated to 5.124. So
no need to manually install. Thanks.
