### ISSUE TITLE
changeling surge quality seems to be missing 

### ISSUE THREAD

**Issue by witchslave** [chummer5a/chummer5a#4372]
**Describe the bug**
The 3 changeling surge level qualities seem to be missing from the character generator. Its listed in the master index and the metagenetic qualities that surge is required for show up but can not be selected with any of the surge qualities. 

**To Reproduce**

**Expected behavior**
Changeling surge quality should be selectable from the dropdown list/search options in the character creator.

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by DelnarErsike** [comment]
You're using quite an old Nightly version of Chummer. Could you update to a newer version to see if the issue is still present?
