### ISSUE TITLE
Sound supressor/Silencer and Gas Vent

### ISSUE THREAD

**Issue by AGulyaev12** [chummer5a/chummer5a#4374]
Both of these modifications use Barrel mount of a weapon. When you apply either of mods to the weapon the second option becomes unavailable. But that doesn't work for weapons with an integrated Sound supressor. You can still apply both of these mods to such a weapon. Maybe it's worth removing Barrel mount line from such weapons description?

**Comment by chummer5a** [comment]
Rules as written, there is no explicit incompatibility between a silencer and a gas vent. They just consume the same slot. 

> Mounts: There are several places where a weapon accessory can be attached to a firearm: underbarrel, barrel, or top-mount. Only one accessory can be attached to a particular mount.

> Integral accessories (those that come with the weapon) don’t take up mount locations.
