### ISSUE TITLE
Issue: - crash to desktop

### ISSUE THREAD

**Issue by cnschu** [chummer5a/chummer5a#4380]
### Environment
Crash ID: fd7c187c-4a63-4e1a-a4e5-3bde4e57fb07
[exception.zip](https://github.com/chummer5a/chummer5a/files/6304058/exception.zip)

Chummer Version: 5.214.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 1a401f8d-39fb-4ca6-9ec2-47af87e05969

### Expected behaviour
show chummer5a UI

### Actual behaviour
instant crash to desktop

### Steps to reproduce the behaviour
double click on chummer5a exe

**Comment by cnschu** [comment]
[attributes.zip](https://github.com/chummer5a/chummer5a/files/6304077/attributes.zip)
crashdump is available

**Comment by ArchonMegalon** [comment]
Seems like the code already has changed in the nightly. Can you download the nightly please and try if you can start the program?

**Comment by cnschu** [comment]
same issue with 5.214.30.
[exception.zip](https://github.com/chummer5a/chummer5a/files/6304530/exception.zip)

**Comment by ArchonMegalon** [comment]
Please check again tomorrow with the next nightly update.

#4381

**Comment by cnschu** [comment]
There is no nightly build after 5.214.30.
Perhaps a compiling error?

**Comment by DelnarErsike** [comment]
Unit test issues. There should definitely be ones now.

**Comment by cnschu** [comment]
same error with v5.214.58
v5.214.59 doesn't start at all

**Comment by DelnarErsike** [comment]
Try the next one, 5.214.69. Caught a really big and really stupid bug related to the same set of code that was giving you your crashes.

**Comment by cnschu** [comment]
same issue with Version 5.214.82.

crash report attached.
[chummer_crash_132670904982876974.zip](https://github.com/chummer5a/chummer5a/files/6582589/chummer_crash_132670904982876974.zip)

**Comment by DelnarErsike** [comment]
That is extremely strange. The crash report's output says that the program is doing something that is impossible for it to do. I've added a failsafe for this weird crash in d29f50220734d2e6e2d06b05494d2b7e84a4db7f. Give 5.214.83 a try and see what happens with that one.

**Comment by ArchonMegalon** [comment]
I fixed the error reporting with #4480. You should be able to find such errors now in AI.

**Comment by ArchonMegalon** [comment]
@cnschu can you please try the latest nightly? We are thinking of releasing a new milestone and an immediate crash seems like a bug we want to have fixed by than.
