### ISSUE TITLE
Issue: Cannot Add Exotic Skills, Cannot Purchase Ammo: Injection Dart

### ISSUE THREAD

**Issue by CapriciousDream** [chummer5a/chummer5a#4382]
### Environment
Crash ID: 89b9a6b9-5125-4cad-b528-a0332581ff61
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 17a0c5b1-7160-4c53-a8c8-fba1d4a615cd

### Expected behaviour
A: Clicking on "Add Exotic Skill" will bring up options for adding skills for Exotic Weapons

B: Highlighting "Ammo: Injection Dart", selecting quantity, and clicking "Add" will add the selected quantity of gear to your character's inventory and remove an appropriate amount of nuyen
### Actual behaviour
A: Clicking "Add Exotic Skill" crashes application to desktop

B: Finalizing the purchase of any amount of "Ammo: Injection Dart" crashes application to desktop

### Steps to reproduce the behaviour
See "Actual Behaviour"

**Comment by CapriciousDream** [comment]
P.S.
This behavior occurred after a fresh install of the application, and simultaneously with any or zero extra sourcebooks or errata enabled in options.

**Comment by DelnarErsike** [comment]
I believe this issue has been fixed in the Nightlies.
