### ISSUE TITLE
Rain Forest Carbine availability modifications by Custom Data Directories

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4384]
**Describe the bug**
There is a problem with the Rain Forest Carbine availabiltiy rules that modify its availability depending on the order Custom Data Directories are active.

Both the "SR Missions 1.4 Rules" and "Rainforest Carbine Missions Errata"  rulesets specifically set the Availability to 8R (from 5R).
The "SR Missions 1.4 Neotokyo" ruleset adds +6 to the Availability (as well as making it Forbidden).

As long as the Neotokyo ruleset is activated after the Missions rulesets, the net Availability is correctly 14F - Availability is specifically set to 8R by a Missions ruleset and then +6 is added by the Neotokyo ruleset.

However if either of the Missions rulesets is activated after the Neotokyo ruleset, the Availability is wrongly 8R - the Neotokyo rule adding +6 is overwritten by the Missions ruleset that specifically sets the Availability to 8R.

Can you think of a way to modify the rulesets to avoid this situation?

Alternatively is there a way to add a comment to a custom ruleset?
Perhaps a file type in the folder that Chummer5a displays when hovering the cursor over the NeoTokyo ruleset so that you see a comment saying it should be positioned after the Missions rulesets?

Displaying such a comment would also be useful for the "Rainforest Carbine Missions Errata" ruleset saying it is not required if the "SR Missions 1.4 Rules" is activated (that also contains the same setting).

**To Reproduce**
1. Go to Character Settings 'Custom Data' tab
2. Decrease Load Order of one of the Missions Directories so that it is below the NeoTokyo Directory (obviously both need to be checked)
3. Save changes and restart Chummer5a to pick up the changed order
4. Goto Gear Tab->Weapons and Add Weapon. Scroll to the Rain Forest Carbine
5. See the error

**Expected behavior**
The availability of the Rain Forest Carbine is 14F no matter the order of the Custom Data Directories.

**Screenshots**
When the NeoTokyo Directory is after the Missions Directories the availability is correct
![Rain Forest Carbine - Neo-Tokyo after Missions](https://user-images.githubusercontent.com/17562417/114808479-f60d6080-9d6d-11eb-9400-d12f7eda8c00.png)

When either of the Missions Directories are after the NeoTokyo Directory the availability is wrong
![Rain Forest Carbine - Neo-Tokyo before Missions](https://user-images.githubusercontent.com/17562417/114808546-1e955a80-9d6e-11eb-80ec-db9f099c7719.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: n/a

**Additional context**
Is there a way to add logic to the Directory definitions to set the Availability correctly?

If not, is there a way to add a comment to a custom ruleset?
Perhaps a file type in the Directory that Chummer5a will display if present so when you hover the cursor over the NeoTokyo ruleset so that you see a comment saying it should be positioned after the Missions rulesets?

**Comment by DelnarErsike** [comment]
The program is working as intended though, right? This is why load order exists, because it can matter in cases like these.

**Comment by Lochabar** [comment]
Program is working correctly. It's the load order of the Directories that produces the error.

**Comment by DelnarErsike** [comment]
But, like, the load order is working as intended, right? The custom datasets modify the base files, so if you have two datasets that modify the same thing in different ways, the one that modifies the thing last gets to have its modification stick.

**Comment by Lochabar** [comment]
Correct.

If the load order is

1. Missions rules
2. NeoTokyo rules
3. Missions Rain Forest carbine rule

then the Availability is wrong


I was wondering about a method to provide comments about a ruleset 
- for NeoTokyo it would say that it should be loaded after other Missions rules
- for the Rain Forest rule it would the say that the rule is not required if the main Missions is selected (where the rule already exists)



Ian Kirk
***@***.***

**Comment by DelnarErsike** [comment]
So... #4263.

**Comment by Lochabar** [comment]
Yes I think this would cover comments.
