### ISSUE TITLE
Issue: - Crash on 5.214.0 when choosing a karmagen setup

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#4388]
### Environment
Crash ID: 91e47a40-d27a-440f-ac73-cfedef10a41e
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: 06f36f27-b8d5-4d71-b82e-44fc58bb4102

### Expected behaviour
The plan was to start building a human in karmagen with the "Ignore Character Creation Rules" box ticked.

### Actual behaviour
However, rather than get to building, Chummer crashed, once more failing to compile the full report automatically. I took a screenshot before submitting the crash report, which I'm attaching below:

![obraz](https://user-images.githubusercontent.com/38818521/115058517-a356b480-9ee5-11eb-8e3e-bfc28a9272e5.png)

### Steps to reproduce the behaviour
1. Open 5.214.0.
2. Choose karmagen.
3. Tick "Ignore Character Creation Rules".
4. Choose the human in the pop-up menu.
5. Click OK.
6. Chummer crashes then.

**Comment by DelnarErsike** [comment]
Does this apply to the Nightly? Because the Nightly's changes to the way build methods are handled could have shadow-fixed this crash.

**Comment by KeeperM** [comment]
It doesn't happen under Nightly-v5.214.30, it just loads very slowly. And Norton is once more whining about a lot of the ZIP's contents (the EXE itself, the translator, crash handler, a lot of DLLs).

**Comment by DelnarErsike** [comment]
The slow loading I can improve on and is unrelated. If the options don't crash in the Nightly, then I'm closing this issue, since it's kind of irrelevant for Chummer going forward.
