### ISSUE TITLE
Saving a character produces message that data file en-US_data.xml could not be found

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4395]
**Describe the bug**
Clicked the save icon and got the message window "Could not find the data file en-US_data.xml"

**To Reproduce**
1. Start Chummer5a.
2. Open a character created under  en-US
3. Make a change
4. Click on 'Save'
5. See error
6. Reopen character - see that changes were saved

**Expected behavior**
Characters created under en-US should not get an error - there is no en-US_data.xml data file.

**Screenshots**
![Character save](https://user-images.githubusercontent.com/17562417/115559271-2dea3b80-a279-11eb-9ce7-275aed35e6ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.214.36

**Comment by DelnarErsike** [comment]
Cannot reproduce in the developer build. Could you check if the issue is still present in 5.214.41?

**Comment by Lochabar** [comment]
Checked with latest build 5.214.42 and problem no longer happens.
