### ISSUE TITLE
Mouse stuck in loading animation

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4398]
Permanent "Windows loading circle" in character creation

**To Reproduce**

Open Chummer
Create a new character

Everything works fine, the mouse is just stuck in the loading animation.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 5.214.39

**Comment by Lochabar** [comment]
Also happens with an existing character after opening Character Options. Closing the options (without changes) leaves the cursor circling but still functional.
Let me know if you want a recording.

**Comment by JoschiGrey** [comment]
As an addition.
This seems to now also occur in loaded career mode characters, but with weird behaviors.

The loading circle is always present, but disappears if the mouse is in/over the skills or adept power window.

**Comment by ArchonMegalon** [comment]
Problem is probably the CursorWait Class that needs a rewrite to track all other instances of CursorWait globally. No need for a recording... ;)

**Comment by DelnarErsike** [comment]
Could you check if this happens after 5.214.43? I changed some stuff about the way the loading cursor stuff is handled.

**Comment by ArchonMegalon** [comment]
Thank you!

**Comment by JoschiGrey** [comment]
Seems to be fixed, thanks!
