### ISSUE TITLE
Plus in Equipment crashes chummer

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4400]
**Describe the bug**

**To Reproduce**
1. Have Ammunition
2. Click on Ammunition
3. Add any number and click ok
4. See empty dropdown => ok => crash

**Expected behavior**
Adds ammo

**Comment by DelnarErsike** [comment]
So I can't really reproduce this? But the adding of more ammo to an existing stack via the plus button in Career mode is definitely a bit wonky. Could you maybe provide a save file where you know this always happens?

**Comment by Stexinator** [comment]
[ritualMage.txt](https://github.com/chummer5a/chummer5a/files/6408361/ritualMage.txt)

you need to change the file ending back to chum5

**Comment by SquadronROE** [comment]
Tried adding ammo to an existing weapon for both via + in that save file, still didn't duplicate a crash or empty dropdown (the default is 'holdout'. In 5.214 pulled from master as of today.

**Comment by Stexinator** [comment]
Fixed as of 5.214.57

**Comment by Stexinator** [comment]
Enforcing right category is still nice :)
