### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by jackmatioli** [chummer5a/chummer5a#4409]
### Environment
Crash ID: 6673da36-04a8-4b35-aaec-001178f2fdc4
Chummer Version: 5.214.42
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: a2eae0a5-f90a-4d17-bab9-1948498495fe

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
What exactly happened?

**Comment by jackmatioli** [comment]
When I entered the application it crashed.  But now it worked!  Thanks


Em dom., 2 de mai. de 2021 às 22:55, DelnarErsike ***@***.***>
escreveu:
