### ISSUE TITLE
Reflex Recorder

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#441]
The Reflex Recorder can only be taken for skills linked to a physical, yet Disguise (linked to INT) can currently be taken with the Reflex Recorder and Locksmith (Linked to AGI) cannot. I think it might have to do with the way skills are being excluded, but I'm not sure what would be a better way of handling it.

**Comment by joha4270** [comment]
Found the cause, Reflex recorder is limited to physical active skills instead of linked to physical attributes. Finishing a hack (i don't see another way that don't require a major rewrite...) in a hour or so time

**Comment by chummer5a** [comment]
Hrm. I could have sworn there was an isphysical limiter already enabled for
skills that was linked to the attributes.

**Comment by HaikenEdge** [comment]
If it is, it's not working, since I'm currently using the files out of the repository and, right now, Perception (INT) is showing as a possible skill while Locksmith (AGI) is not.

**Comment by chummer5a** [comment]
Nevermind, I was thinking of skillattribute.

**Comment by HaikenEdge** [comment]
This is supposed to have been fixed in the latest update, but for my version of Chummer, which is the most recent one as far as I can tell, skills like Animal Handling (CHA) and Disguise (INT) are still showing up, while Locksmith (AGI) still isn't showing up.
