### ISSUE TITLE
Chummer freezes up

### ISSUE THREAD

**Issue by RoCCommander** [chummer5a/chummer5a#4417]
**Describe the bug**
Saving a Character causes Chummer to freeze up. The mouse changes to the loading circle and one cannot change tabs in Chummer or in fact click any buttons in chummer. This includes the Close Window X in the top right or the line to minimze the Windows. 

However, there is a strange behaviour with the taskbar  of windows (the bar usually located at the buttom the screen containing all the open windows). If one right clicks on chummer after freezing it in the above manner and then selects "close window", chummer responds with the usual: You made changes, would you like to save? Yes, no, cancel. Clicking cancel resets chummer and one can continue to work. The changes that one made bevor changing are saved. So it seems that something freezes chummer after the write to disk is complete. 

**To Reproduce**
1. Open any Character or make a new character
2. Make any change to the character
3. click the save icon or press "ctrl + s", or select "save as"  or select "save" 

There is no error message. 

**Expected behavior**
The character is saved and chummer responds as normal.

**Desktop (please complete the following information):**
 - Windows 10 Pro, Version 10.0.19042 build 19042
 - Problem first appeared in Version 5.214.51 and persits into 5.214.52 

**Additional context**

**Comment by RoCCommander** [comment]
The issue also appears sometimes when changing things without saving. 

It happend to me while adding the autosoft clearsight or when changing the enhanced speed on my Bull Dog. But this problem doens't seem be consistent. Undoing everything and adding / changing the same items does not freeze Chummer up again.

**Comment by DelnarErsike** [comment]
It sounds like you have some local software that might be interfering in an unpredictable way?

**Comment by RoCCommander** [comment]
Hey, thx for the feedback. 
I don't know that kind of someware might be interfering with Chummer in such a way. I am not running any anti malware software or anti virus or fire wall besides the windows defender. And Chummer is also not running a virutal machine or such.

**Comment by DelnarErsike** [comment]
Well, it might be caused by task scheduling unpredictability then, but saving characters *should* by a synchronous task, so you shouldn't get the issue there...

**Comment by MzMouse38** [comment]
I'm also experiencing the same issue, though oddly trying to close the program and then clicking **Cancel** on the save prompt will cause Chummer to unfreeze. No such luck if it freezes with another dialog open.

**Comment by DelnarErsike** [comment]
Note to anyone working on this issue: it seems to be that for some reason, UI invokes aren't being finished properly, and so the application hangs because it's waiting for an invoke to finish that never gets run.

**Comment by RoCCommander** [comment]
Updating to Version 5.214.75 seems to fix this problem.

**Comment by ArchonMegalon** [comment]
All Hail to Delnar!
