### ISSUE TITLE
XoShiRoPRNG.Net updated to 1.5.0

### ISSUE THREAD

**Issue by pepoluan** [chummer5a/chummer5a#4421]
Hi, I'm the maintainer of [XoShiRoPRNG.Net](https://www.nuget.org/packages/XoshiroPRNG.Net/)

Just FYI, I've updated my package to 1.5.0. The main reason is that upstream (Messrs. Vigna & Blackman) apparently made a bug with their implementation of XoShiRo128**, so they released a v1.1 for that function.

I just noticed this change, and immediately updated the algorithm & package. It's just uploaded, so it might take up to one hour before the package is available on NuGet.org

(If you don't use XoShiRo128**, then you don't need to update).

Thank you for your kind attention, and apologies for any inconvenience.

**Comment by DelnarErsike** [comment]
Thanks for the notification. We do NuGet package updates semi-regularly, so we would have incorporated your update within at most a week or two, but thanks for the heads-up regardless.
