### ISSUE TITLE
Program crashes when attempting to create an exotic skill

### ISSUE THREAD

**Issue by ProfessorOcecat** [chummer5a/chummer5a#4422]
(Most recent stable release, Windows 10)
When selecting the 'Add Exotic Skill' button, the program freezes and is forced to close (no chance to cancel). Originally thought it may have had to do with having no free skill points, but upon freeing some up to attempt this it still crashed.
Can give more information/character file if required.

**Comment by JoschiGrey** [comment]
Did you try reproducing it on the newest Nightly?
I'm pretty sure it's fixed already.

**Comment by ProfessorOcecat** [comment]
I did not try the newest Nightly: only the latest stable build. I did do a
quick search for the issue and didn't see it so apologies.

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the current Nightly.
