### ISSUE TITLE
Issue: - Chummer crashed when I click Add Exotic Skill

### ISSUE THREAD

**Issue by AutonomousDev** [chummer5a/chummer5a#4423]
### Environment
Crash ID: bf981fcc-aa83-44ff-9ffb-b1b7da970ed3
Chummer Version: 5.214.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: e8d5cc8d-fea4-4c96-aa96-7b8f7e880194

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
