### ISSUE TITLE
Master index is not populated correctly

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4433]
**Describe the bug**
The master index doesn't contain all the items, but what it feels like a random selection of stuff.
The Data File Selection cbo only shows `All` or `Streams.xml`

**Additional context**
- Tested in Ger and Eng.
- The shown Items differ each time opening chummer.
- There is no obvious pattern like categories or naming present in the shown entries.

**Comment by DelnarErsike** [comment]
Is this with the 5.214.58 or `master`? Because if it's the former, commit 5994448a8447c6093ae72f147c1281624a3fd543 might have also fixed it.

**Comment by JoschiGrey** [comment]
This problem was in 5.214.58 and persisted for some Versions.
It is not fixed in 5.214.59 or while building the upstream/master in VS myself.

**Comment by DelnarErsike** [comment]
I can't seem to replicate the issue myself, no matter the language.

**Comment by JoschiGrey** [comment]
Seems to be fixed now, at least I can't reproduce it anymore on the newest nightly.
