### ISSUE TITLE
Issue: - Tryind to add an exotic skill on my B&E social adept cause chummer 5.214.0 to crash, multiple time on differents attempts

### ISSUE THREAD

**Issue by teamawesomeLEA** [chummer5a/chummer5a#4443]
### Environment
Crash ID: 17809091-e93c-4f86-bbc3-142b49cd521c
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: dab56b24-cb98-413b-8d08-08c337f67b1b

### Expected behaviour
Add a new exotic skill empty to choose from in the bottom

### Actual behaviour
Fully crashes Chummer 5.214.0

### Steps to reproduce the behaviour
Create a sum of 10 character with race, stat and skill at B, Magic at D and nuyen at E, finish caracter creation, add 2 initiation, 2 pt of magic, this list of power, 
![PP sr5](https://user-images.githubusercontent.com/48485616/118406893-fe4a0b80-b64b-11eb-983f-635186616e18.PNG)
and these active skills:
![Skill1](https://user-images.githubusercontent.com/48485616/118406922-33565e00-b64c-11eb-9b0b-c60b025ad460.PNG)
![Skill2](https://user-images.githubusercontent.com/48485616/118406923-33565e00-b64c-11eb-96ea-ccf99cf7e2e2.PNG)
And clicking on the " add exotic skill"

I don't think it's linked to the character, since adding an exotic skill on my old character produce the same result ( even tho he allready have 2) but adding ranks works just fine

**Comment by JoschiGrey** [comment]
This issue is already fixed in Nightly
