### ISSUE TITLE
Adept Powers Scrolling

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#445]
So, I was just told that there is no ability to scroll on the adept powers page if you have enough powers to drop below the bottom of the page. I can't imagine it's something that comes up often, but it might be a good idea to put one in when there's time.

**Comment by chummer5a** [comment]
Hrm. Yeah, makes sense. That's like... thirty powers though. I'm half
surprised something else didn't break first.

**Comment by Verecoth** [comment]
Me too. I also doubt it'll come up often, but better to have it and not need it, right?

**Comment by chummer5a** [comment]
Fixed in 5.177.
