### ISSUE TITLE
Unable to use free knowledge skills

### ISSUE THREAD

**Issue by bubiex2** [chummer5a/chummer5a#4459]
**Describe the bug**

**To Reproduce**
1. Go to Skills
2. Click on Add Skill under Knowledge Skills

**Expected behavior**
After adding a knowledge skill I should be able to assign my free points. Instead its making me spend karma just to add my first few points

**Screenshots**
![image](https://user-images.githubusercontent.com/84680719/119271718-b0478180-bbd0-11eb-8aaa-f25d5cd816b9.png)

**Character [File**]
[Vent.txt](https://github.com/chummer5a/chummer5a/files/6528647/Vent.txt)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by DelnarErsike** [comment]
Huh, for some reason, the program flagged your character as Created.

**Comment by DelnarErsike** [comment]
Fixed in 0200896d7599f3c957a8ce02bc9a2b106b5fae0d.
