### ISSUE TITLE
Underbarrel Grenade Launcher (and Grapple Gun) modifications have incorrect prices and availabilities

### ISSUE THREAD

**Issue by MrTonic** [chummer5a/chummer5a#4460]
**Describe the bug**
Underbarrel Grenade Launcher has no cost or availability.  As per Run and Gun (p54) it should be 3500nY at availability 10F.
Underbarrel Grapple Gun has the same issue, should be 600 nY, 8R

**To Reproduce**
Add a weapon with underbarrel slot to weapons tab.  Right click, "Add Underbarrel Weapon."  Options named above have 0nY, 0 availability as opposed to what is expected.

**Expected behavior**
These items should have prices and availabilities as per the table in RG p54.

**Context**
Believe this is an issue stemming from the Ares Alpha from core having a launcher but no associated price, and the optional modification inheriting these values.

**Comment by DelnarErsike** [comment]
Fixed in the Nightly already.
