### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Malekthi** [chummer5a/chummer5a#4468]
### Environment
Crash ID: 66695739-0dcc-4c15-a956-ff77bb1e603c
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: f345cc95-43dc-4416-a033-ed0318437d98

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Uh, could you give more details of what happened?

**Comment by ArchonMegalon** [comment]
Closing this because of no response.
