### ISSUE TITLE
Issue: - Adding an exotic skill crashes chummer

### ISSUE THREAD

**Issue by PapaNurgle** [chummer5a/chummer5a#4469]
### Environment
Crash ID: 69baad74-1a09-47f5-86d9-5e5f3bbdf67e
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 490e115c-9ada-461d-9bbe-321738d24953

### Expected behaviour
Adding an exotic skill

### Actual behaviour
Crashes instantly to desktop

### Steps to reproduce the behaviour
Just simply adding an exotic skill will crash the entirety of chummer
[chummer_crash_132667425652768120.txt](https://github.com/chummer5a/chummer5a/files/6564119/chummer_crash_132667425652768120.txt)

**Comment by DelnarErsike** [comment]
Known issue, fixed in the Nightly.
