### ISSUE TITLE
Rigger 5.0 Mounts for Core Rulebook Drones Are Missing

### ISSUE THREAD

**Issue by DelnarErsike** [chummer5a/chummer5a#4477]
Rigger 5.0 specified how the built-in weapon mounts that come with certain drones and vehicles in the core rulebook should be replaced with Rigger 5.0-specified ones. Currently, core rulebook drones and vehicles in Chummer come with core rulebook weapon mounts, even when Rigger 5.0 is enabled. Either these drones should all use Rigger 5.0 weapon mounts that are still accessible when playing without Rigger 5.0, or there should be two separate versions of each drone (one with Rigger 5.0 mounts and the other with core rulebook mounts), or each drone should show the core rulebook mount when Rigger 5.0 is disabled and the Rigger 5.0 one when it is enabled.

**Comment by JoschiGrey** [comment]
Couldn't we just do some "fancy" stuff in the `Load` Method and replace the CRB mounts with R5 mounts if R5 is activated?
