### ISSUE TITLE
Exotic Weapon Skill Refunding

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#448]
People probably don't do this often, but I've noticed that, if I take an Exotic Skill in Career Mode and put Karma into it to raise it, then decide to undo the Karma expense for whatever reason, the Karma gets refunded, but the skill rank doesn't get reduced.

**Comment by HaikenEdge** [comment]
Tried something earlier today, and notice this is applying to skill groups too; even if you refund the skill group's Karma expenditure, the skill ranks remain the same.

**Comment by chummer5a** [comment]
Seems to be working properly as of 5.179.732.
