### ISSUE TITLE
Additional Eye Mount on Cyberlimbs Bug

### ISSUE THREAD

**Issue by blackshade10** [chummer5a/chummer5a#4482]
**Describe the bug**
Additional Eye Mounts under Chrome Flesh Eyeware are described as allowing the mounts to be placed anywhere on the body, and include a Capacity cost[2] to include into a cyberlimb, currently Chummer does not permit this to happen.

**To Reproduce**
1. Go to 'Cyberware and Bioware'
2. Click on 'Any Cyberlimb'
3. Scroll down to 'Add as Plugin'
4. See error: No option for Additional Eye Mount

**Expected behavior**
For Additional Eye Mount to be a selectable upgrade.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [10.0.19042 Build 19042]

**Comment by JoschiGrey** [comment]
This is the same as #4193 isn't it?

**Comment by DelnarErsike** [comment]
It is not. #4193 is about additional eye mounts not being able to have their own plugins. This one is about additional eye mounts not being able to be added to cyberlimbs.
