### ISSUE TITLE
[Nightly-v5.214.90] Crash on selecting bike mods

### ISSUE THREAD

**Issue by SeveralGeese** [chummer5a/chummer5a#4487]
**Describe the bug**
Chummer crashes when trying to add modifications to bikes. 

**To Reproduce**
1. Go to Vehicles and drones
2. Purchase bike (tested with Harley Nightmare and Yamaha Kaburaya)
3. Right click bike and select "add modification"
4. in modification menu, select (seemingly) any mod to experience crash.
**Expected behavior**
Crash appears to be happening while trying to load the preview data for mod.

**Character File**
Character file [Jayde - Copy.zip](https://github.com/chummer5a/chummer5a/files/6627982/Jayde.-.Copy.zip)

Settings file [Default.zip](https://github.com/chummer5a/chummer5a/files/6627990/Default.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Nightly-v5.214.90 and older

**Additional context**
Does not seem to happen every time, but out of 10+ attempts, it has crashed 9+ times.

**Comment by DelnarErsike** [comment]
Fixed in commit db277e1ec008fe05e8b5013c8feb6b8fd0870227.
