### ISSUE TITLE
"Add Exotic Skill" crash

### ISSUE THREAD

**Issue by RRAMgd** [chummer5a/chummer5a#4492]
Hi!
Every time I try to add Exotic Skill (both create and career) it suddenly exits chummer. Like a crash with no crash report.

**To Reproduce**
1. Go to 'Skills'
2. Click on 'Add Exotic Skill'

**Expected behavior**
Chummer5 closes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.214.0

**Comment by JoschiGrey** [comment]
Known issue, already fixed in the nightly.

**Comment by RRAMgd** [comment]
> 
> 
> Known issue, already fixed in the nightly.

Then I might change to nightly. Two questions, will I still be able to open all my .chum5 in nightly? I'll need to relink all PDF again right?

**Comment by JoschiGrey** [comment]
Yes old .chum5 files can be opened, but newly created or edited files can't be opened in older versions.
You probably need to create a new settings file, that reflects the books you use.

No you won't have to relink all .pdfs if you update Chummer to nightly.

**Comment by RRAMgd** [comment]
Then it's all solved. Thank you very much!!
