### ISSUE TITLE
Issue: - Immediate crash when adding new exotic skill

### ISSUE THREAD

**Issue by koboldDelegate** [chummer5a/chummer5a#4494]
### Environment
Crash ID: 6e078d29-26d3-42fe-a052-0a0560dd05c9
Chummer Version: 5.214.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 9c711441-141a-4f38-86b4-f8c9dc85f51c

[Chummer.2021-06-18 01_01_24.5385.log](https://github.com/chummer5a/chummer5a/files/6674721/Chummer.2021-06-18.01_01_24.5385.log)
[Chummer.2021-06-18 00_58_59.7826.log](https://github.com/chummer5a/chummer5a/files/6674723/Chummer.2021-06-18.00_58_59.7826.log)

### Expected behaviour
Add New Exotic Skill

### Actual behaviour
Immediate Crash

### Steps to reproduce the behaviour
Load a character, or create a new one. Move to skills tab. Click "Add Exotic Skill". Crash occurs.

**Comment by ArchonMegalon** [comment]
Can you please try this with the nightly build?

**Comment by koboldDelegate** [comment]
Issue does not occur in the nightly! All is behaving as it should. Thank you.
