### ISSUE TITLE
Consistent crash-to-desktop after clicking the "Add Exotic Skill" button

### ISSUE THREAD

**Issue by Anon5342** [chummer5a/chummer5a#4495]
**Description:**
As title. This also fails to create a crash report, though it provides an error message (screenshot below).

**Steps to reproduce:**
1. Open up any character or a new character
2. Go to the skills tab
3. Click the "Add Exotic Skill" button
4. See error message before Chummer crashes.

**Expected behavior:**
Should add an entry for a new Exotic skill instead of crashing the application.

**Screenshots:**
![image](https://user-images.githubusercontent.com/86385082/123175817-6ad8d700-d450-11eb-9dbd-47e5307e7925.png)

**Desktop:**
 - Windows 10
 - Chummer Version 5.214.0

**Additional details:**
Issue was not fixed by a fresh reinstall. Discussed with other users, they have reported the same issue.

**Comment by JoschiGrey** [comment]
This is an known issue and already fixed in the nightly builds.
