### ISSUE TITLE
Magic Value Problem

### ISSUE THREAD

**Issue by JDLII49** [chummer5a/chummer5a#4497]
**Describe the bug**
I'm making a character for a Street Level-Priority campaign. When choosing Priority Level B for Magic or Resonance I'm getting 5 points for Magic as the returned value.

**Expected behavior**

6 points of Magic is called for in the Sourcebook. There is no priority level that returns 5 points. Is this a bug or have I missed something ?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.214]

Thanks 
JD Lail

**Comment by ArchonMegalon** [comment]
Is this a naked chummer install from the download or are some custom
rulesets enabled here?

**Comment by Anon5342** [comment]
Chummer looks correct for me.

Looking at the Street-level rules in the sidebar on SR5 p. 64, there should be no change in the Magic ratings. Looking at the usual rules for Magic ratings on SR5 p. 65, it looks like if you select priority B for Magic, you should get the following options:

- Magician or Mystic Adept with Magic 4
- Technomancer with Resonance 4
- Adept with Magic 6
- Aspected Magician with Magic 5

Forbidden Arcana p. 47 also adds the Apprentice as an alternative to the Aspected Magician. I see all of these options correctly represented when I try to build a new street-level runner in Chummer.

**Comment by JoschiGrey** [comment]
I can't reproduce it with the chummer given rule sets in the nightly versions.
As already mentioned aspected magicians have 5 points of magic in prio B.

**Comment by Anon5342** [comment]
Look SR5 p. 65. For priority B, an aspected magician should get 5 points in magic, not 6. If Chummer is saying 5, Chummer is correct.

**Comment by JDLII49** [comment]
I am an Adept with Magic 6, not an Aspected Magician with Magic 5.
Best RegardsD9on Lail
    On Thursday, June 24, 2021, 09:28:18 AM EDT, Anon5342 ***@***.***> wrote:  
 
 


Look SR5 p. 65. For priority B, an aspected magician should get 5 points in magic, not 6. If Chummer is saying 5, Chummer is correct.

**Comment by DelnarErsike** [comment]
Could you test to see if the issue is still present in the latest Nightly build? There have been a lot of changes to this specific aspect of character creation from 5.214.0 to the 5.214.x Nightlies.

**Comment by JDLII49** [comment]
The problem is now explained. I thought that Essence was completely separate from other limits like magic. When I addeda commlink to a build it turned out that my effective magic limit dropped a point. It somewhat irks me is that my essence is 5.8 and my magic is 5.0 rather than 5.8. Bad rule imo but YMMV.
Now I have to either find another .8's worth of essence to spend on stuff or ditch the commlink. In case it wasn't obvious this is our foray into Shadowrun.
ThanksJD Lail
    On Saturday, June 26, 2021, 07:22:09 AM EDT, DelnarErsike ***@***.***> wrote:  
 
 


Could you test to see if the issue is still present in the latest Nightly build? There have been a lot of changes to this specific aspect of character creation from 5.214.0 to the 5.214.x Nightlies.
