### ISSUE TITLE
5e Negative Karma values miscalculated when reloading a character in CREATE mode

### ISSUE THREAD

**Issue by MrZDante** [chummer5a/chummer5a#4498]
**Describe the bug**
After saving a character that is in CREATE mode (the mode before you export it to CAREER), the file will reload with a negative Karma value. This occurs when creating a Shadowrun 5th Edition character and when using negative qualities from other books. Specifically, my example character uses Phobia (Uncommon, Mild) and Poor Self Control (Vindictive) from Run Faster. The final trait is Code of Honor, which brings the Negative Karma value to 25 exactly. When reloading the sheet, the negative Karma Value shows 15/25. Removing all of the negative qualities brings the Negative Karma value to -10. This issue may also occur with other qualities however I have not done extensive testing yet. I have filled out Enemies for this character but the settings have been updated so Enemies do not count for or against Negative Karma. These incorrect calculations carry over to a character in Career mode.

**To Reproduce**
1. Create a new character in Chummer5a - Version 5.214.0
2. Add Negative Qualities from multiple sources (Specifically "Code of Honor" with the additional field filled in as "Innocent Bystanders," "Phobia (Uncommon, Mild)" and "Poor Self Control (Vindictive)"),
2. Save the character. Note: do not save as created.
3. Close character sheet and reopen it in Chummer.
5. Save character as created to see that error has been transferred as well.

**Expected behavior**
The correct Negative Karma values are calculated and Negative Karma cannot itself be in the negatives.

**Screenshots**
![image](https://user-images.githubusercontent.com/86436250/123328713-eb0f4300-d509-11eb-8093-501ea4bbecf1.png)

**Character File**
Character file has been renamed with the .txt extension for the purposes of uploading to github.
[Nyx Character File (CREATE mode).chum5.txt](https://github.com/chummer5a/chummer5a/files/6712055/Nyx.Character.File.CREATE.mode.chum5.txt)

**Desktop (please complete the following information):**
 - OS: Windows10 Home
 - Version: 20H2
 - OS build: 19042.1052
 - Experience: Windows Feature Experience Pack 120.2212.2020.0
 - Application: Chummer5a
 - Chummer Version: 5.214.0

**Additional context**
No additional context, however a lot of notes exist in this example sheet. It is a character that I am currently working on. The issue can be worked around by manually calculating the total Karma or creating the entire character sheet and saving as career mode without restarting Chummer.

**Comment by DelnarErsike** [comment]
So I think this has been fixed a while back in the Nightly, and is/was a UI updating issue. Could you double-check if the issue is still present in the current Nightly build?
