### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Vigilwake** [chummer5a/chummer5a#4500]
### Environment
Crash ID: bafcc545-688b-4428-a9d0-8785c5a9c2ae
Chummer Version: 5.209.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 00000000-0000-0000-0000-000000000000

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Uh, what is this? Try updating to a newer version of Chummer, 5.209.0 is very old.
