### ISSUE TITLE
All Custom Data Shipped with Chummer5a Should Have Manifests

### ISSUE THREAD

**Issue by DelnarErsike** [chummer5a/chummer5a#4509]
As the title says, all custom data directories that come with Chummer in `customdata` should have manifests specified for them.

**Comment by JoschiGrey** [comment]
I added a very brief wiki entry for manifests.

https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files#manifest-data

**Comment by chummer5a** [comment]
Implemented by https://github.com/chummer5a/chummer5a/commit/47f5d751a8abc49cbddc20efb4f1b5c97101254b with exception of Delnar's mods, and the ShadowHaven/RunnerHub rulesets.
