### ISSUE TITLE
Chummer5a crashes after start

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4510]
**Describe the bug**
Opening Chummer5a results in program crashing once Chummer5a starts processing Character Roster.

**To Reproduce**
Open program with an existing Character Roster.

**Expected behavior**
Program opens and Roster is shown.

**Screenshots**
[chummer_crash_132712192615334434.txt](https://github.com/chummer5a/chummer5a/files/6844973/chummer_crash_132712192615334434.txt)

Screen recording of start and crash
https://user-images.githubusercontent.com/17562417/126251312-04a323c4-3275-471c-95df-8e9869c59547.MP4

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.127

**Comment by DelnarErsike** [comment]
Should be fixed in the next Nightly
