### ISSUE TITLE
"Replace Attribute" Improvement fails to create Improvement

### ISSUE THREAD

**Issue by FidchellFete** [chummer5a/chummer5a#4512]
**Describe the bug**
The Replace Attribute Improvement does not create an improvement. 
When filled out completely for Replace Attribute, the Create Improvement dialog box closes without creating an Improvement.

**To Reproduce**
1. Go to Improvements
2. Click on add improvement 
3. Click improvement type dropdown
3. Scroll down to "Replace Attribute"
4. Enter any values in the Name field, Selected Value dropdown, Minimum, and Maximum number boxes
5. Click OK
6. No Improvement is created

**Expected behavior**
When the Improvement window is filled correctly, clicking the OK button should create an Improvement in the list of selected Improvements that overrides the Metatype limitations for an attribute on the Common page.

**Screenshots**
![image](https://user-images.githubusercontent.com/87792409/126584754-82cfa09f-3a3d-4426-b1d1-bf90ad44be1b.png)
![image](https://user-images.githubusercontent.com/87792409/126584776-1f8a8ee3-619f-4919-be29-1ff16c0c4caa.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version Unknown

**Additional context**
I am using Milestone version 5.214.0

**Comment by FidchellFete** [comment]
Is this for the nightly or the milestone version?

**Comment by DelnarErsike** [comment]
Neither until the Nightly is rebuilt with that commit, Nightly-only until a milestone version is pushed with that commit
