### ISSUE TITLE
Chummer5a crashes opening character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4521]
**Describe the bug**
Opening a character results in program crashing.

**To Reproduce**
Open program with an existing Character.

**Expected behavior**
Character opens.

**Screenshots**
[chummer_crash_132714748010769928.txt](https://github.com/chummer5a/chummer5a/files/6874206/chummer_crash_132714748010769928.txt)

Screen recording of opening character and crash:
https://user-images.githubusercontent.com/17562417/126906302-88edbf24-a29a-4422-b353-24476da67e1e.MP4

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.132

**Comment by Lochabar** [comment]
Crash still happening. Most characters open. Two do not.

[chummer_crash_132718282215320121.txt](https://github.com/chummer5a/chummer5a/files/6882388/chummer_crash_132718282215320121.txt)

[chummer_crash_132718283426358004.txt](https://github.com/chummer5a/chummer5a/files/6882389/chummer_crash_132718283426358004.txt)

**Comment by chummer5a** [comment]
Can't reproduce it. Crash indicates it's trying to load a character with two identically-named skill groups. Can you provide one of the character files to test with?

**Comment by Lochabar** [comment]
Here is the simpler of the two. (The second was cloned from this one and changed significantly.) You will see it was originally created some time ago.

[Character.zip](https://github.com/chummer5a/chummer5a/files/6885297/Character.zip)
