### ISSUE TITLE
Crashing on clicking Options Menu

### ISSUE THREAD

**Issue by Zorunel** [chummer5a/chummer5a#4527]
Clicking on Options crashing Chummer...

### Expected behaviour
not crashing

### Actual behaviour
crashs
### Steps to reproduce the behaviour
Start Chummer, click on Options, crash

[chummer_crash_132721281672620268.txt](https://github.com/chummer5a/chummer5a/files/6908077/chummer_crash_132721281672620268.txt)

**Comment by DelnarErsike** [comment]
Fixed in 403acf03170ab004fdf5937d29f42fa96b2195aa.
