### ISSUE TITLE
Issue: - Sudden crash adding custom settings.

### ISSUE THREAD

**Issue by KeeperM** [chummer5a/chummer5a#4528]
### Environment
Crash ID: 63d5a767-83a7-4c40-9cf6-45955d608c69
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: 06f36f27-b8d5-4d71-b82e-44fc58bb4102

### Expected behaviour
I was asked to create a character with custom settings (attached). I went to choose the settings from the dropdown menu.

### Actual behaviour
The application crashed after selecting the custom settings.

### Steps to reproduce the behaviour
1. Start the 5.124.0 stable.
2. Select Options.
3. Attempt to choose the custom settings provided.
4. Crash.

[MortalJourneySettings.zip](https://github.com/chummer5a/chummer5a/files/6909357/MortalJourneySettings.zip)
![obraz](https://user-images.githubusercontent.com/38818521/127695199-a0dc5ae9-1566-45be-9e90-b46b9e10c7e1.png)
![obraz](https://user-images.githubusercontent.com/38818521/127695214-10f87849-0769-4599-a7d4-2be6f0a7b57b.png)

**Comment by DelnarErsike** [comment]
Cannot replicate in the Nightly. Can you test to see if it is still a problem there?
