### ISSUE TITLE
Multiple issues with the latest release.

### ISSUE THREAD

**Issue by Kyoto-Kid** [chummer5a/chummer5a#453]
Ran into a few of issues with the latest build.

Installed Chummer5a (ver 175) onto my old XP notebook and when I tried to open it I received a windows error message": "Not a valid wIn32 application". The previous version I was using (pre Run Faster/Chrome & Flesh) worked fine. The latest release will run on my Win7 64 graphics workstation so I am wondering if XP32 is no longer supported.

When I added the Gentech augmentation "Synaptic Acceleration" it did not modify the Initiative rating or Initiative Dice.as per the description on page 162 of Chrome & Flesh. 

There seems to be no process I can find for upgrading Cyber and Bioware after moving a character into career mode. Am I missing something here?

High Fashion armour of one brand is stacking with that of another (eg Mortimer Argentum coat is showing it can stack with wither Zoe Executive Action or Vashon Sleeping Tiger). According to information on page 59 in  Run & Gun, high fashion armour should only stack with armour clothing by the same maker.

**Comment by joha4270** [comment]
>XP32 is no longer supported.    

XP is no longer supported. If you download the latest release you will find a Chummer5.Legacy.exe that might work, but this is untested and might stop working at any time

>Gentech augmentation  

Probably just a data file, taking a look later

> Am I missing something here?

Per RAW, you can only remove a piece of ware, then install another, higher rating, piece of ware

>High Fashion armour of one brand is stacking with that of another  

We know and it is going to be fixed eventually, but we can't quite keep up with catalyst

**Comment by Kyoto-Kid** [comment]
...thank you.for the quick response. 

Bugger about XP as the notebook is nine years old and it would neither be cost or time effective to install win 7 on it. C5a does run fine on my Win7 graphics workstation and I have it installed there but the portability would have been nice as I wouldn't have to print off the character for each session. I'll give the legacy version a try.

When I originally removed the current bioware I was upgrading (Orthooskin 3), it kept the .75 Essence cost and when I added Orthoskin 4 it deducted another full 1 point of Essence so the the upgrade to rating 4 cost a total of 1.75 Essence. How do I go about modifying the essence rating to set it to the correct amount?

**Comment by joha4270** [comment]
That is not supposed to happen. Can you upload the character sheet somewhere?

As place works as long as i can download without an account, but if you don't know any of those, i can recommend [this](https://mixtape.moe/)

**Comment by Kyoto-Kid** [comment]
...tried it again and this time it did create the essence hole. Not sure what I did wrong the last time.

**Comment by joha4270** [comment]
Ah, i think this is related to how it is implemented, essence holes and automatic handeling was implemented not a lot of versions ago, and it don't play nice with old ware

**Comment by Kyoto-Kid** [comment]
...now all we need is to get the improving skills with Karma issue fixed

**Comment by chummer5a** [comment]
Synaptic Acceleration's included as of 5.176. Probably earlier, but I can't remember the specific build.

The High Fashion gear doesn't currently do a lot to stop you from selecting the wrong gear. I think the best way to handle that would probably be spinning out a manufacturer tag for the data or something. Would make for a useful synergy with the Brand Loyalty, I guess?
