### ISSUE TITLE
Auto-Generated Issue from Crash: ID b2096a3e-d3f0-443c-9828-ef8d8835ee6c

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4534]
### Environment
Crash ID: b2096a3e-d3f0-443c-9828-ef8d8835ee6c
Chummer Version: 5.214.143
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: Info
Installation ID: ec115634-3b4d-4661-88f9-61cfcd831350

### Expected behaviour
Character opens

### Actual behaviour
Opening character with renamed rulesets, clicking thru changed options, Chummer5a crashes, 

### Steps to reproduce the behaviour
As above

### Crash Description
Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.

**Comment by DelnarErsike** [comment]
Does this apply to any settings that you set? The crash description seems to indicate that this is something specific to a certain combination of options within a setting.

**Comment by Lochabar** [comment]
I'm working on updating settings files for the Missions rulesets that changed names. So I opened a character that uses a settings file that was just updated, and got the crash.

Here iare the character and settings files
[Archive.zip](https://github.com/chummer5a/chummer5a/files/6941828/Archive.zip)
