### ISSUE TITLE
Changing the activated Custom Data Rules does not stick

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4535]
**Describe the bug**
Modifying character options, moving a custom ruleset and activating it, then saving the character options. Reopening the custom ruleset and the activated rulesets have changed.

**To Reproduce**
1. Go to 'Character Setting' Custom Data tab
2. Click on a ruleset and move it
3. Close the options and reopen.
3. See error - the ruleset that was in that activated is no longer.

**Expected behavior**
Activated rulesets remain as selected.

**Screenshots**
Screen recording of the problem:
https://user-images.githubusercontent.com/17562417/128427028-f3a8d13b-b231-4101-923d-8afed707b784.MP4

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.143 (and prior)

**Comment by DelnarErsike** [comment]
Also fixed in 03477856059318a466a42fa3fb4df83354c2e6ab.
