### ISSUE TITLE
Land Rover Model 2046 (SUV) don't work anymore

### ISSUE THREAD

**Issue by Zorunel** [chummer5a/chummer5a#4540]
**Describe the bug**
I want to modify my Land Rover 2046 (SUV) and Chummer crash with the info this Object don't have a category.

**To Reproduce**
1. Go to Vehicles
2. Click on Land Rover 2046 (SUV)
3. See error

**Expected behavior**
able to modify my car

**Additional context**
[chummer_crash_132728226613613714.txt](https://github.com/chummer5a/chummer5a/files/6949367/chummer_crash_132728226613613714.txt)

**Comment by DelnarErsike** [comment]
You'll need to remove and re-add the car to modify the car in the future. I can make a patch that will at least prevent Chummer from crashing when you click on it to modify it.

**Comment by Stexinator** [comment]
The vehicle was deleted in bd82741e54b3c8bbf19da31942ee73df723eb702 . Re-Adding is thus not possible

**Comment by DelnarErsike** [comment]
Ah, right, because it does not have a price. I'll give you a custom file with stats custom file to re-add it stats-wise that you can use if you don't know how to make one yourself.

**Comment by DelnarErsike** [comment]
Here you go. Put this into either your `data` folder or a custom data directory that you've enabled and you should be able to re-add the Model 2046. That said, remember, this vehicle does not have a cost mentioned for it in the Missions book that stats it out, so it technically cannot be bought by players.

[custom_LandRoverModel2046_vehicles.zip](https://github.com/chummer5a/chummer5a/files/6951671/custom_LandRoverModel2046_vehicles.zip)

**Comment by Stexinator** [comment]
So the general stance is that we should not add items without a price to the dataset in chummer? Is it possible to add these custom datas structured as missions to the default installation?

**Comment by Zorunel** [comment]
> That said, remember, this vehicle does not have a cost mentioned for it in the Missions book that stats it out, so it technically cannot be bought by players.

Thats right, but players can take it, so in this case. Players kill Flesh Mongers and take the car, the mission has GM instructions for these case how other npcs react.to the car...

**Comment by Stexinator** [comment]
@DelnarErsike this is not concluded to my satisfication

**Comment by Zorunel** [comment]
> Here you go. Put this into either your `data` folder or a custom data directory that you've enabled and you should be able to re-add the Model 2046. That said, remember, this vehicle does not have a cost mentioned for it in the Missions book that stats it out, so it technically cannot be bought by players.
> 
> [custom_LandRoverModel2046_vehicles.zip](https://github.com/chummer5a/chummer5a/files/6951671/custom_LandRoverModel2046_vehicles.zip)

this file do not work for me... 
I put the file in customdata in a folder, added it in Chummer and activated it and the car is not selectable. The same result for the data folder. Even creating a Manifest.xml for the customdata folder did not change anything.
