### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by argent6541** [chummer5a/chummer5a#4542]
### Environment
Crash ID: 53c4fef3-632a-495b-b629-c6a39dd4c634
Chummer Version: 5.214.101
Environment: Windows 10 Education
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 6827ab77-cc6d-43d4-bd44-f7d564dfdb32

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Could you please update to the current Nightly? 5.214.101 is quite an old Nightly version.

**Comment by argent6541** [comment]
Ok I will try that
