### ISSUE TITLE
Custom Data Directory "Exclude German Sourcebooks" activated but sourcebooks still listed

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4543]
**Describe the bug**
The Custom Data Directory "Exclude German Sourcebooks" is activated
![Exclude German Sourcebooks](https://user-images.githubusercontent.com/17562417/128619172-61e82a6d-8ab7-43eb-ae41-440bb2df4d08.png)

But the German Sourcebooks are still listed
![Sourcebook List](https://user-images.githubusercontent.com/17562417/128619177-1aed56fe-5ec5-4655-aa11-a5a25a71252f.png)

**To Reproduce**
1. Open a character
2. Go to 'Character Settings' Custom Data tab and activate the Exclude German Sourcebooks
3. Save the changes and restart Chummer5a
4. Open the character
5. Go to 'Character Settings' Sourcebooks to Use tab
6. See error - the German Sourcebooks are still listed.

**Expected behavior**
The German Sourcebooks are not displayed.

**Screenshots**
The xpathfilter statement does not seem to be working, but I do not see an error:
![amend_german_books](https://user-images.githubusercontent.com/17562417/128619191-5c56a325-7218-4208-8393-5822986e64e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.146

**Comment by DelnarErsike** [comment]
Cannot replicate. Books get immediately hidden for me.

**Comment by Lochabar** [comment]
Tried the steps again
1) When I opened the Character Options the rulebooks are still present
![Sourcebook List2](https://user-images.githubusercontent.com/17562417/128959251-2f99c32d-63a5-432b-8540-aaaad3077cba.png)

2) Went to the Custom Rulesets
![Ruleset](https://user-images.githubusercontent.com/17562417/128957727-d033a0a8-f9c4-487b-a4ae-13e6d44d7bf0.png)

3) Moved one ruleset and then went back to the General tab and the German books are excluded.
![Sourcebook List3](https://user-images.githubusercontent.com/17562417/128959307-c7cf3ef4-91bc-4500-9e36-d2f0d03543bb.png)

**Comment by Lochabar** [comment]
Some recent change has fixed this problem - perhaps it was happening due to the switch of using GUID instead of Directory Name for the Custom Data Directorries. Anyway the problem is no longer happening.
