### ISSUE TITLE
German range for Touch is Bouch instead of B or Berührung

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4544]
**Describe the bug**
German range for Touch is Bouch instead of B or Berührung

**Additional context**
In the translation there seems to be the correct keys and translations

**Comment by Lochabar** [comment]
The translations for the sheets are in the xz.language.xslt file in the individual language folders.
I will make the change.

**Comment by Stexinator** [comment]
It is in the export, dont know if it accesses the same file
