### ISSUE TITLE
Bloody Business Adept Power

### ISSUE THREAD

**Issue by Retlif** [chummer5a/chummer5a#455]
In the Bloody Business book is a new adept power: Body Sculpt. This should be added to the powers list.

**Comment by chummer5a** [comment]
I don't generally buy the enhanced fiction books, so I dunno what it does. Does the power do anything that Chummer would need to handle, or is it just a power cost?

**Comment by HaikenEdge** [comment]
If there's a "Body Sculpt" power, it's certainly not in *Bloody Business*. That book doesn't have a single adept powers in it. In fact, I've done a keyword search through all the PDFs I have, and I literally cannot find such a power anywhere.

Side note: *Bloody Business* isn't an enhanced fiction book, per se, but it is a GM-oriented sourcebook for generating adventures.

**Comment by Iridios** [comment]
It is there, page 160.  I tried a search on the PDF and it looks like the text isn't indexed for a search.  It is a 1PP power, with a prerequisite of "Facial Sculpt".  It gives a +2 to Disguise while active.

**Comment by HaikenEdge** [comment]
Of course it is. For some reason, when I used the keyword search in Acrobat Reader, it didn't turn up.

**Comment by joha4270** [comment]
Created in #457 by @HaikenEdge
