### ISSUE TITLE
Drone Weapon Dice Pool not correct

### ISSUE THREAD

**Issue by Zorunel** [chummer5a/chummer5a#4555]
**Describe the bug**
A Drone with pilot 5 and target acquisition autosoft 6 + smartgun (smartlink installed) 1.
Chummer calculates a dice pool of 11 for me ... so if I didn't just sleep at school, it should be 12.

**To Reproduce**
1. Get a Drone
2. if it not have pilot 5, install it
3. install the autosofts
4. install a smartgun weapon

**Expected behavior**
Dice pool 12...

**Screenshots**
![Screenshot 2021-08-16 011054](https://user-images.githubusercontent.com/86850071/129495578-5ea9d2ab-5557-4760-affa-f51c1df6e815.jpg)

**Additional context**
no big Issue for me, I only noticed it by accident ^^

**Comment by DelnarErsike** [comment]
Cannot replicate in the latest Nightly.

**Comment by Zorunel** [comment]
weird, i can repreduce it... 
apparently a unique problem ... as written it is not a big Issue for me, so I just accept that Chummer doesn't like my drone xD

**Comment by JoschiGrey** [comment]
Would your share your character and settings file?

I also assume you are using the newest nightly?

**Comment by Zorunel** [comment]
sorry for my late response
the issue stil exist for me in the newest Nightly (5.214.194)

Here my charakter
[Baron.txt](https://github.com/chummer5a/chummer5a/files/7230367/Baron.txt)

and my settings
[Stefan.xml.txt](https://github.com/chummer5a/chummer5a/files/7230372/Stefan.xml.txt)

**Comment by Stexinator** [comment]
The Smartsoft seems to be the problem. If you add it step by step it wont increase when adding smartsoft
