### ISSUE TITLE
Reapplying improvements to character with Exception Attribute shows empty dropdown

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4562]
**Describe the bug**
Reapplying Improvements to a character with the Exceptional Attribute Quality produces a window "Choose an Attribute for Exceptional Attribute to affect" with a blank dropdown list.
Why is the window even being produced - the specific attribute is identified in the quality.
If there is a reason, why is the dropdown blank?

**To Reproduce**
1. Open a character with the Exceptional Attribute Quality.
2. Click Yes to confirm the Re-apply Improvements.
3. See the window.

**Expected behavior**
If there is no reason to show the window, don't show it.
If there is a reason to show the window, only show it if there is something in the dropdown.

**Screenshots**
Screen recording of the problem:
https://user-images.githubusercontent.com/17562417/130690888-150bf759-4a2b-45c9-a319-7559d52d4301.MP4

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.161 (and prior)

**Comment by chummer5a** [comment]
Something's janky with the character, the exceptional attribute's extra value shouldn't be RES(1), it should be RES.

**Comment by Lochabar** [comment]
I edited the character file to remove " (1)" from the "extra" field and re-applied improvements again - the window did not appear. I don't know how the (1) got into the field (it has happened on another character as well).

Is removing the (1) from "extra" all that needs to be done?
Or does something else need to be modified? (I've attached the character for you to check.)
[Archive.zip](https://github.com/chummer5a/chummer5a/files/7070703/Archive.zip)

**Comment by chummer5a** [comment]
That's all that needs to be done, yes. Important question is where the number came from.

**Comment by Lochabar** [comment]
I've manually edited both characters to remove the excess " (1)" and both successfully passed the re-apply improvements.
As to where the excess text came from?
Both characters were originally created years ago, so any problem with the code could have been fixed anytime since then.
