### ISSUE TITLE
List of Favorite Characters in the Roster is replicated as the list of Recent Characters

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4565]
**Describe the bug**
The list of Favorite Characters in the Roster is replicated as the list of Recent Characters.

**To Reproduce**
Cannot reliably reproduce. It is related to opening characters and updating their options, and perhaps closing the character without saving. But it does no always happen.

**Expected behavior**
The list of Favorite Characters is not replicated as Recent Characters.

**Screenshots**
Duplicated list:
![Roster](https://user-images.githubusercontent.com/17562417/131202593-b4e399b0-f3d9-4930-864b-0ac861b0e9b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 5.214.165 (and prior)

**Comment by Lochabar** [comment]
Finally managed to get a recording of of the problem happening (it's a bit long, Chummer5a seems to have been slowed by the act of recording it). The video starts right after I opened chummer5a.

https://user-images.githubusercontent.com/17562417/131203662-cc7d712f-a0c7-4eb5-af26-f7c0d9b15081.MP4

**Comment by DelnarErsike** [comment]
Cannot reproduce. Not only that, but I don't even see any part of the code where this sort of duplication could even happen. The two lists of nodes are kept completely separate and there is no part of the code that populates those lists that would allow an element present in one list to show up in the other.

**Comment by Lochabar** [comment]
Well it's still happening in 5.214.167.
I doubt it helps but I always download and use the latest nightly, I do not update in place.
I also searched the registry and the the characters only appeared as the mru entries.

**Comment by DelnarErsike** [comment]
Could you double-check if this is still happening?

**Comment by Lochabar** [comment]
Still happening in latest nightly (5.216.32)
1) Open a character
2) Go to "Character Settings" "Custom Data" tab
3) Activate a Custom Data Directory
4) Cancel change
5) Character Roster duplicates favorites in Recent
Note: Closing the character restores the Recent Character list
