### ISSUE TITLE
Yamaha Raiden doesn't accept underbarrel laser or mounted crossbow.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4571]
**Describe the bug**
The Yamaha Raiden does not seem to accept the under barrel laser or mounted crossbow.

**To Reproduce**
create chracter
add Yamaha Raiden
right click and select add underbarrel weapon
see no laser avaliable
add fn-har
right click and select add underbarrel weapon
see laser avaliable.

**Comment by DelnarErsike** [comment]
Underbarrel Laser and Mounted Crossbow are weapon accessories, not underbarrel weapons.
