### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by thankGOD4all** [chummer5a/chummer5a#4575]
### Environment
Crash ID: aa1fa7df-7f66-43fd-95aa-95bec61ee879
Chummer Version: 5.214.83
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 3d5c1f60-fb47-450c-bafc-1e6a7454a3bc

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Can't really do anything if you didn't type anything for when and where and how the crash happened. Closing this for now, will re-open if info is added.
