### ISSUE TITLE
Issue: chummer crash when trying to add exotic skill

### ISSUE THREAD

**Issue by mcallisr** [chummer5a/chummer5a#4576]
### Environment
Crash ID: 1b40ac9f-90da-4e3b-8d55-dc33270d9481
Chummer Version: 5.214.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 3757b0cf-ddfb-4159-8bef-bb48e430d483

### Expected behaviour
add an exotic skill

### Actual behaviour
on the click of add exotic skill button on the skill tab the program crashed

### Steps to reproduce the behaviour
create new character using karmagen 900 and Fight the Night settings file. Moved to Skills Tab, Clicked add exotic skill

**Comment by JoschiGrey** [comment]
Thank you for your submission.

This is a known error and already fixed in the Nightly builds.
