### ISSUE TITLE
In the "Select a Spell" menu, there's an "Extended Spell" checkbox that makes certain spells display the wrong drain codes.

### ISSUE THREAD

**Issue by Maguillage** [chummer5a/chummer5a#4577]
Version 5.214.0
As far as I can tell, the checkbox gets force checked on existing spells with the "Extended Area" characteristic, but the end result is chummer displaying a drain code that's 2 above what it should be.

![image](https://user-images.githubusercontent.com/91387479/134780967-7cced562-b236-4d92-94a5-05ff198d9036.png)
![image](https://user-images.githubusercontent.com/91387479/134781582-c5734172-8746-494a-9d71-74d2c68e01eb.png)

In some cases it corrects the drain code when you actually learn the spell:
![image](https://user-images.githubusercontent.com/91387479/134781524-855d6fcd-a40c-4da7-8f6a-3ade8fe3a937.png)

In other cases it does not:
![image](https://user-images.githubusercontent.com/91387479/134781519-01a997b8-0b7e-4e6b-8c03-d92d4f9411ad.png)

**Comment by DelnarErsike** [comment]
Fixed in the Nightly already. Chummer wasn't properly abiding by the house rule option for if all spells could be made extended.
