### ISSUE TITLE
[Feature Request] Default Directories

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#458]
Not sure how much work it'll be, and it's less to do with the content and more to do with quality of life, but would it be possible to implement default directories into the software? It gets kind of annoying when I'm inserting images and then saving or opening files when I keep images and save files in different directories on different drives and Chummer keeps the last directory used as the one it starts in when you try to insert an image or save or load a file.

**Comment by chummer5a** [comment]
Hrm, currently Chummer is just inheriting the behaviour from Windows, using the last touched folder path. It shouldn't be particularly difficult to use the RestoreDirectory and InitialDirectory properties on OpenFileDialog to do it, I suppose. Storing a separate value for each fileopen dialogue wouldn't be particularly helpful though, but it shouldn't be a problem to separate images and chummer files out.

**Comment by HaikenEdge** [comment]
That would be absolutely beautiful. Thank you. I might be the only one, but I store my Chummer files and my image files on completely different drives, so jumping back and forth between them can be a bit of a hassle, either type in the directory or use the breadcrumbs to go back and forth.
