### ISSUE TITLE
Chummer Crash followup id = ee470931-59f5-49e9-9264-a3c58dd689cb

### ISSUE THREAD

**Issue by Skrollyx** [chummer5a/chummer5a#4580]
**Describe the bug**
When trying to open house rules after a left click on the "house rules" tab, the crash report window open and Chummer crash giving me this id :

Chummer Crash followup id = ee470931-59f5-49e9-9264-a3c58dd689cb

The problem seems to come from the version of Chummer. with the stable 5.214.0 it's working but not in 5.214.199.

![image](https://user-images.githubusercontent.com/91785097/135714261-76a88461-e780-4ef0-b38a-9ea42120d52a.png)

**Comment by DelnarErsike** [comment]
Fixed in the next Nightly.
