### ISSUE TITLE
Content Added by Erratas Should Have Working Sourcebook References

### ISSUE THREAD

**Issue by rafaellibanio** [chummer5a/chummer5a#4584]
**Describe the bug**
Wrong source of Living Focus

**To Reproduce**
1. Go to Adept Power
2. Add Power
3. Choose Living Focus power
4. Source is wrong.

**Expected behavior**
The source is wrong. Instead of **SG 1** it should be **SSP 24**.

**Screenshots**
![image](https://user-images.githubusercontent.com/4489298/136611597-757eeb4e-be30-4514-a5e9-04236864da15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.2.1000

**chummer5a**
- Version 5.214.206

**Comment by DelnarErsike** [comment]
Fixed by f621a36393329b27a441250fcb33ff586143ea97. Not elegantly, but still fixed.
