### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by ghost** [chummer5a/chummer5a#4586]
### Environment
Crash ID: 5f3cab60-bb94-4589-a347-19f197bcf994
Chummer Version: 5.213.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: a332777e-769d-4e94-b809-ac2230693f98

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
Closing this for now, please re-open if you come back with more information on how to reproduce the crash.
