### ISSUE TITLE
Missing underbarrel weapon from German sourcebook

### ISSUE THREAD

**Issue by BlitzBerlin** [chummer5a/chummer5a#4588]
Title says it. Chummer is missing the "Ontario Arms Sling-Shot" from the German State of the Art (Germany) 2080 (SHB 4, p. 153). Can you please add this one?

**Comment by JoschiGrey** [comment]
This should be added to the already existing custom data set `German Data Changes\custom_weapons.xml`.

**Comment by KoshiirRa** [comment]
Pull request #4717 has this weapon and its ammo in it.
