### ISSUE TITLE
Issue: Crash on Add Exotic Skill

### ISSUE THREAD

**Issue by ChemoCosmo** [chummer5a/chummer5a#4596]
### Environment
Crash ID: 2644f40a-b801-46e7-b11c-fff90bf71b77
Chummer Version: 5.214.0.0
Environment: Windows 10 Pro (also with **Ubuntu and Wine**)
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 7f9450cf-576f-410b-bdd5-372063a71a11

### Expected behaviour
Window for adding exotic skills

### Actual behaviour
Crash To Desktop

### Steps to reproduce the behaviour
Click at Add Exotic Skill
![crash](https://user-images.githubusercontent.com/58092307/139591259-74b4b3b5-9953-4525-a392-8f4a2477aff8.PNG)

**Comment by chummer5a** [comment]
This has been resolved in nightly builds.
