### ISSUE TITLE
Prototype posthuman not giving free essense bioware

### ISSUE THREAD

**Issue by Ganggreenkahn** [chummer5a/chummer5a#460]
I tried to make a Prototype Posthuman and when I give him the free bioware it still subtracts essense. I didn't see any options to make it the free bioware. Prototypr trans human is supposed to give you 1 free essence of bioware.

**Comment by chummer5a** [comment]
Known issue, not implemented yet.

**Comment by chummer5a** [comment]
Fixed in current builds.
