### ISSUE TITLE
Chummer crashes when creating a non-advanced lifestyle that matches a selected level of the Trust Fund quality

### ISSUE THREAD

**Issue by Maguillage** [chummer5a/chummer5a#4601]
**To Reproduce**
1. Create new character
2. Add a relevant SINner quality
3. Add a Trust Fund quality
4. Create a new lifestyle without using the optional "advanced lifestyle" dropdown
5. Use the "Comforts" dropdown to select the lifestyle that matches what your Trust Fund quality would give you for free (e.g., High lifestyle with Trust Fund III)
6. Chummer crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/91387479/140293436-3a6e61ef-5535-447b-b64d-4d7b3c520ce7.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Version 5.216.0

**Additional context**
I also got a crash for editing an existing lifestyle under the same circumstances with trust fund and a matching comfort level, but I can't seem to reproduce it.
The crash log Chummer put onto my desktop is completely empty.

**Comment by DelnarErsike** [comment]
If you want a temporary workaround, create the lifestyle first, then open it up after you've created it and set up your Trust Fund stuff afterwards. I forgot to handle cases for Trust Fund where the user is adding a brand new lifestyle instead of modifying an existing one.
