### ISSUE TITLE
Issue: - Purchasing new Exotic Weapon skill in Career mode

### ISSUE THREAD

**Issue by Wyckydgrynn** [chummer5a/chummer5a#4605]
### Environment
Crash ID: 206ad774-56ba-4719-935d-dd598c33ff17
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: db04d60f-f247-4358-947d-29a91b929e89

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by Wyckydgrynn** [comment]
Sorry...
Expected Behavior: Presented with options for exotic weapon skill to purchase.

Actual Behavior: Chummer crashed.

**Comment by chummer5a** [comment]
This has been patched in current builds. Update to 5.216.
