### ISSUE TITLE
ObjectDisposedException while closing characters

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4612]
When closing a character with unsaved changes, or trying to close an unsaved character or chummer while an unsaved character was open.

It is very inconsistent and I couldn't find a regular pattern.
![image](https://user-images.githubusercontent.com/69921261/141500634-103f69a8-2452-436b-810d-48d689c1394c.png)

**Comment by DelnarErsike** [comment]
Fixed in commit 1159695c6d1d875eea9ad0643c3ab4d09efe80e2.
