### ISSUE TITLE
Cannot find a RCC in cyberware or gear

### ISSUE THREAD

**Issue by Siver-wire** [chummer5a/chummer5a#4613]
**Describe the bug**
I am trying to build a rigger character. I have filled out skills and abilities. When I go to buy cyberware or find a control rig in gear I cannot find one. I search "rig", "rcc", and "control", but nothing comes up.

**To Reproduce**
1. Start a character
2. Go to 'cyberware and bioware'
2. Click on 'select cyberware'
3. Scroll down to 'Rigger Command Console'
4. See nothing

**Expected behavior**
I should be able to find a RCC or Rigger Command Console in Cyberware or Gear.

**Screenshots**
![image](https://user-images.githubusercontent.com/94547072/142224014-6dec88e8-ae5e-448f-8b28-88f595fc55a2.png)

**Character File**
[Oni.zip](https://github.com/chummer5a/chummer5a/files/7555562/Oni.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 5.216.0]

**Additional context**
I have made many other characters without issue. I hope I am not missing something and this is an actual code error.

**Comment by chummer5a** [comment]
For Gear, filter by the category Rigger Command Consoles. 
RCCs can't be implanted.
