### ISSUE TITLE
Changing settings file causes all non-core items to be removed from the character

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#4618]
**Describe the bug**
When a character is loaded into a copy of chummer that does not have a matching settings file (ie a user-created sumtoten.xml, while another user has sumtoten_2.xml) and it prompts for the settings file to use, the character will be loaded without any items from sources other than the core, as the character file briefly becomes set to the first settings file available, which is usually a baked-in settings file that only has SR5 enabled.

**Expected behavior**
When switching settings files, the character needs to be in a read-only state until the new file has been selected, after which a validation is performed. If the character is evaluated differently between settings files, it should prompt the user to proceed or reselect.

**Comment by DelnarErsike** [comment]
I can't seem to replicate this? I have save files with all sorts of non-CRB content in them that are set up with custom settings files from older versions of Chummer. When I load them into the current `master`, I get the prompt asking to select a setting for them, after which if I select a setting that has all those non-CRB books enabled, the character loads in fine with everything intact.
