### ISSUE TITLE
Cyberspace Designs Dragonfly Weaponpool

### ISSUE THREAD

**Issue by Zorunel** [chummer5a/chummer5a#4619]
**Describe the bug**
The Dragonfly has a pre installed weapon "Bite" with a pre installed Autosoft "Melee: Bite". However Chummer indicates a pool without Autosoft (without skill) and thus a Pool Pilot -1.

**To Reproduce**
1. add Cyberspace Designs Dragonfly
2. Click on the Weapon
3. See error

**Expected behavior**
Have a Attack Pool 6

**Screenshots**
![Screenshot 2021-11-20 231443](https://user-images.githubusercontent.com/86850071/142742680-98463e2a-6623-43f0-b7d0-5e51cc904261.jpg)
![Screenshot 2021-11-20 231541](https://user-images.githubusercontent.com/86850071/142742682-046a3535-d695-4f2a-a9ca-4dba7415ebf3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.216.17 (German Language)

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/a3eebf065c8db4e84b92d911a2ab7d74f3fcf547
