### ISSUE TITLE
Drone/Vehicle sensor modification

### ISSUE THREAD

**Issue by Turkish323** [chummer5a/chummer5a#462]
Depending on the size of the vehicle or drone, it is possible to change the sensor array rating, which would affect the sensor stat of the vehicle or drone.  The table on page 446 of the core rulebook gives examples of drone and vehicle size and the maximum sensor ratings.

There are multiple issues with this in Chummer5 that are all inter-related.  First, it will not allow the sensor rating of the drone or vehicle to be raised above what it comes with by default (instead of being limited by the table).  Second, if  the higher rated sensors are added separately, the sensor ratings of the new sensors are not factored into the sensor rating of the drone, even if the rating of the default sensors are lowered to 0 (which can cause the program to crash, incidentally).  Third, it is impossible to delete the sensors that "come" with the drone or vehicle.

I realize this is probably not a priority, but it does prevent me from being able to use Chummer to track my riggers drones and vehicles, since almost none of them are "stock".  Otherwise I did not run into any issues of note!

**Comment by chummer5a** [comment]
The sensor rules are so confusing to me that I'm not surprised they're
broken. Will investigate and curse at CGL.

**Comment by skarsol** [comment]
Current status of this is that the stock sensors can be deleted, but not raised. They can be replaced, but the vehicle doesn't take the new sensor into account. Additionally, the Sensor Enhancement and Sensor (Drone) items can't be given Sensor Functions.

**Comment by skarsol** [comment]
The FixVehicleSensors branch addresses most of this. It adjusts the rating of the Sensor Array to match the modified Sensor of the vehicle. The name "Sensor Array (Rating 2)" doesn't update until the char is saved and reloaded though. I see where the name change is being doing in other cases in frmCreate, but the variables in use there aren't available in the Vehicle class. @chummer5a you have any thoughts on this? Or do I need to move the sensor calc code from the Vehicle to frmCreate (kinda messy)?

**Comment by chummer5a** [comment]
Hrm, RefreshSelectedVehicle should be handling the brunt of that already, I'd think. If not, easiest would just be to have it iterate through mods and update the treeview text.

**Comment by skarsol** [comment]
RefreshSelectedVehicle doesn't update the DisplayName in the tree view, which is what's causing the issue. Could make it do so, but really it's something the Vehicle should be doing (since it's changing the name of a child of the Vehicle). Meh. Alternative is expose the tree view to the vehicle and it could do it. So many different messy ways. :P
