### ISSUE TITLE
Most settings not loading in character settings

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4620]
**Describe the bug**
In the new character settings window, when selecting a different settings name, most of the character creation settings don't load.  I did not look at every option but it seems like the only thing that loads in is the allowed cyber grades. Karma availability build method ect do not change.

**To Reproduce**
Open character settings window.
Change Setting name
notice that character creation settings don't fully update to match the new chosen setting.

**Expected behavior**
I would expect that selecting a setting would load all of the stored settings in the save file.

Version 5.216.0.0

**Comment by DelnarErsike** [comment]
You have no idea the absolute can of worms you've uncovered with this...
