### ISSUE TITLE
Cant add muscle enhancing bioware to Koborokuru

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4621]
**Describe the bug**
When creating a Koborokuru in char gen I am unable to add muscle toner or muscle augmentation to the character.

**To Reproduce**
create new character as dwarf Koborokuru variant.
attempt to add either of the 2 bioware muscle boosters to character in cyberware tab.
notice items are missing from list.

Version 5.216.0.0

**Comment by chummer5a** [comment]
Blocked by Celerity, from memory. Should be an open ticket about cyberspace
disabling improvements instead of blocking them.
