### ISSUE TITLE
Empty print dialog in Linux/Wine

### ISSUE THREAD

**Issue by ChemoCosmo** [chummer5a/chummer5a#4627]
#### System 1
Chummer: 5.212.0
OS: Ubuntu 20.04
Wine: wine-5.0 (Ubuntu 5.0-3ubuntu1)
Winetricks: 20200412
DotNet: 472

#### System 2
Chummer: 5.212.0
OS: Ubuntu 20.04
Wine-Version: wine-5.0 (Ubuntu 5.0-3ubuntu1)
Winetricks: 20200412
DotNet: 472

Only difference between the two Wines are Wine being installed via regular Wine package in System 1 and via Wine (development version) in System 2 in Ubuntu Software Center.

### Problem Before Version 5.216.0

When clicking at the print button, the Cursor Loading Indicator spins for 2 seconds, then stops, but the Preview stays empty.

![grafik](https://user-images.githubusercontent.com/58092307/144413599-a14ecaa1-d435-4130-ae5e-07de595281af.png)

Saving to PDF generates an all empty PDF page.

This problem occurs at every Chummer version I used until now. I always imagined that printing (resp. PDF generating) just doesn't work in Wine, however in this related issue it seemed to have worked at some point: #2246

I would be very happy if printing would work in Linux, since its the only feature missing and it would spare me booting up Windows every time I need a character sheet printed.

### Problem Since Version 5.216.0

The Cursor Loading Indicator continues spinning endlessly. The page still stays empty.

### Additional Problem Since Version 5.216.0 Only in System 2

After opening the print dialog, at the next restart of Chummer, Chummer crashes with "mscorlib recursive resource lookup bug". "Resource name: Arg_ExternalException"

![grafik](https://user-images.githubusercontent.com/58092307/144413882-9eb245d7-1517-4a40-8df7-17c5f69329e3.png)

And after "Repeat" with the following Stacktrace. Chummer startup can then only be fixed by deleting ~/.wine folder and reinstalling dotnet and allfonts.

```
0x7bcb3ea9: ret	
Modules:
Module	Address			Debug info	Name (41 modules)
PE	  400000-  a80000	Deferred        chummer5
PE	  ec0000- 15ae000	Export          clr
PE	 15b0000- 16a5000	Deferred        msvcr120_clr0400
PE	 3ed0000- 3f50000	Export          clrjit
PE	 3f60000- 4970000	Deferred        system.ni
PE	 4a40000- 4bd4000	Deferred        system.drawing.ni
PE	 4be0000- 58fd000	Deferred        system.windows.forms.ni
PE	 5900000- 5913000	Deferred        nlssorting
PE	 5c00000- 5ce8000	Deferred        diasymreader
PE	10000000-1007d000	Export          mscoreei
PE	61a00000-621e0000	Deferred        system.core.ni
PE	79000000-7904a000	Export          mscoree
PE	79720000-7aa9e000	Export          mscorlib.ni
PE	7b020000-7b023000	Deferred        kernelbase
PE	7b420000-7b5db000	Deferred        kernel32
PE	7bc30000-7bc34000	Deferred        ntdll
PE	f5780000-f5784000	Deferred        uxtheme
PE	f57c0000-f57c3000	Deferred        usp10
PE	f5830000-f58ae000	Deferred        comctl32
PE	f6000000-f6044000	Deferred        crypt32
PE	f60e0000-f60e4000	Deferred        bcrypt
PE	f6100000-f6104000	Deferred        rsaenh
PE	f6170000-f6178000	Deferred        oleaut32
PE	f6280000-f6283000	Deferred        api-ms-win-core-xstate-l2-1-0
PE	f6290000-f6293000	Deferred        combase
PE	f6360000-f636f000	Deferred        setupapi
PE	f65e0000-f65e4000	Deferred        winex11
PE	f66a0000-f66a4000	Deferred        rpcrt4
PE	f6750000-f6778000	Deferred        ole32
PE	f6890000-f6893000	Deferred        shcore
PE	f68e0000-f71b6000	Deferred        shell32
PE	f72e0000-f72e4000	Deferred        dbghelp
PE	f73a0000-f73a3000	Deferred        api-ms-win-core-quirks-l1-1-0
PE	f73b0000-f73b3000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	f73c0000-f73c4000	Deferred        imm32
PE	f7640000-f7644000	Deferred        msvcrt
PE	f7720000-f7727000	Deferred        gdi32
PE	f7880000-f7968000	Deferred        user32
PE	f7aa0000-f7aa8000	Deferred        shlwapi
PE	f7b10000-f7b14000	Deferred        advapi32
PE	f7db0000-f7db4000	Deferred        version
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\mnt\data\Programme\Chummer\Chummer5.exe
	00000031    0
	0000002c    2
	0000002b    0
	00000009    0 <==
0000000e services.exe
	00000027    0
	00000020    0
	0000001b    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000026    0
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	0000002a    0
	00000029    0
	00000028    0
	00000025    0
0000002f wineconsole.exe
	00000030    0
System information:
    Wine build: wine-5.0 (Ubuntu 5.0-3ubuntu1)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.11.0-41-generic
```

### Additional Informations:
Installation of Wine and Winetricks via regular Ubuntu Software Center. Afterwards installation of DotNet via "winetricks -q dotnet472 allfonts"

Everything besides Printing works just fine.

**Comment by ChemoCosmo** [comment]
Only realized now that the issue seems to have been abandoned with Issue #2777
That's unfortunate, since everything else seems to work just fine. :(

**Comment by SlidingHorn** [comment]
Can confirm this same issue using Arch
