### ISSUE TITLE
Add Option to Reapply Improvements of Specific Item(s)

### ISSUE THREAD

**Issue by DelnarErsike** [chummer5a/chummer5a#4628]
Reapply Improvements is currently a sort of brute force fix to all sorts of weird issues that can pop up with the improvements system. However, because it reapplies every single improvement, it can cause a lot of collateral damage when you know what troublemaker is actually in need of having its improvements reapplied.

There should be an option to not blanket Reapply Improvements to everything, but instead to filter the specific things that would need to be reapplied. This can probably be done with an extra entry in the appropriate (right-click) context menus and/or changing Reapply Improvements to bring up a separate window where users can check boxes next to the things and/or types of things they want to be subject to it.

**Comment by Lochabar** [comment]
This is similar to #2211 that I requested hoping to be able to update gear definitions that were changed in the base data file as corrections are identified.
