### ISSUE TITLE
Chummer is missing refined and radical reagents and Oricalchum

### ISSUE THREAD

**Issue by Kromgar** [chummer5a/chummer5a#463]
![image](https://cloud.githubusercontent.com/assets/6778786/10608169/e117124a-770b-11e5-9c56-e80eaec29e88.png)

Pg 24 Shadow Spells

It's probably because no one ever bothers to do fucking alchemy.

**Comment by joha4270** [comment]
Should be a quick fix

**Comment by HaikenEdge** [comment]
What do the reagents even do? All I see is the table, with no real explanation as to what it's for.

**Comment by joha4270** [comment]
You use them for some fancy spellcasting stuff and binding spirits.

No reason not to use Raw tho

Well, theoretically 30 raw weights around a kg (if memory serves), so at one point you need a truck, but that is still cheaker than buying orichalum

**Comment by Kromgar** [comment]
Okay it's actually explained in street grimoire. Radical reagents can be used to prepare an inanimate vessel and shit. Oricalchum is used in foci I guess.

**Comment by joha4270** [comment]
Orichastuff is the purest from. The measure of magical energy, drams, is
the same amount of magic contained in one (gram?) of orichastuff.

Might be used for foci as mentioned, but i honestly think it is just fancy
letters weights.

**Comment by HaikenEdge** [comment]
I guess it's because it's so spread out that it's difficult to compile a mental list of what each type of reagent is used for.

**Comment by joha4270** [comment]
Okay, wrote the actual patch, but because reasons (hit, me breaking other stuff) i can't push it right now.
