### ISSUE TITLE
Initiation only allowing metamagics for Forbidden Arcana 

### ISSUE THREAD

**Issue by kd8qdz-9** [chummer5a/chummer5a#4631]
Chummer will not allow metamagics other than those from the _Forbidden Arcana_ sourcebook to be added to an initiation grade when using the "add Metamagic" right click menu option.  Metamagics from the core book and other sourcebooks are shown when the "Show only metamagics I can take" checkbox is unchecked.  Checked in character creation (with "allow initiation at creation" house rule enabled,) and after creation.   Tradition appears to have no effect (tried Hermetic, Shamanic, and random others)

**To Reproduce**
Make magically active character.  Add initiation grade.  Attempt to add Metamagic. 

Windows 11,  Chummer5a V 5.216.0.0.

**Comment by chummer5a** [comment]
Need to add the appropriate Art first or disable the Art requirements in the options.
