### ISSUE TITLE
Encumbrance Calculations do not include armor mods that increase armor value of regular armor

### ISSUE THREAD

**Issue by Eliasar** [chummer5a/chummer5a#4633]
**Describe the bug**
Armor bonuses from armor mods are not considered for the encumbrance calculation.

**To Reproduce**
1. Load a career character with low STR (1 works best for the Full Body Armor: Helmet example below)
  a. Optional: create a new Human character and leave the STR at 1
2. Click on the "Street Gear" tab
3. Click on the "Clothing and Armor" sub tab
4. Click on the "Add Armor" button
5. Search for "Full Body Armor" in the search field
  a. Note: if the character was just created, deselect the "Hide Items Over Avail Limit (12)"
6. Select "Full Body Armor" from the list view on the left
7. Click "OK" in the bottom right
8. Right click on the "Full Body Armor" in list view on the left
9. Left click on "Add Armor Mod"
10. Search for "Full Body Armor: Helmet" in the search field
  a. Note: if the character was just created, deselect the "Hide Items Over Avail Limit (12)"

**Expected behavior**
Reaction and Agility should show "+ Armor Encumbrance (-X)"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.216.0

**Additional context**
[Shadowrun 5e forums example](https://forums.shadowruntabletop.com/index.php?topic=24148.msg449146#msg449146)
> Example. My Strength 6 character wears a Full Body Armor with an Armor Value of 15. He gets no penalty, since there is no + in the rating. Later, however, he grabs a Full Helmet and a Ballistic Shield (+3 and +6, respectively). Together, their bonuses exceed his Strength by 3, meaning he gets a -1 penalty to both Agility and Reaction.

**Comment by Eliasar** [comment]
I tested this with adding a Gel Pack to a Ballistic Shield, and the calculation was correct for the total armor of that item (now +8).

**Comment by DelnarErsike** [comment]
As far as I'm aware, armor mods that alter the armor value of regular armor should not contribute to encumbrance. Encumbrance is only imposed by armor items that give +X armor. Gel Packs on Ballistic Shields add to encumbrance because Ballistic Shields themselves add to encumbrance. FBA does not add to encumbrance because it is a normal piece of armor, and because Fully Body Armor: Helmet is defined as a modification of FBA and not its own, separate, +Armor item, it only increases the armor value of FBA, meaning it doesn't contribute to encumbrance.

**Comment by DelnarErsike** [comment]
You'll also notice that in that forum thread, there is no definitive RAW given for this should work, hence the tag. Waakshani mentions the way they play at their own table, but Waakshani's house rules are still their own house rules even if Waakshani has contributed to the official rulebooks (in fact, some of their house rules for their own Chrome Flesh content flatout collapse under any Chummer-friendly approach that requires all edge cases to have defined, consistent behavior).

**Comment by Eliasar** [comment]
> As far as I'm aware, armor mods that alter the armor value of regular armor should not contribute to encumbrance. Encumbrance is only imposed by armor items that give +X armor. Gel Packs on Ballistic Shields add to encumbrance because Ballistic Shields themselves add to encumbrance. FBA does not add to encumbrance because it is a normal piece of armor, and because Fully Body Armor: Helmet is defined as a modification of FBA and not its own, separate, +Armor item, it only increases the armor value of FBA, meaning it doesn't contribute to encumbrance.

I noticed that as well. A Ballistic Shield with a Gel Pack is marked as +8, so I assumed it would calculate accordingly.

**Comment by Eliasar** [comment]
I'm going to have to do a lot more searching. It seems like there is no consensus on if a full body armor helmet is an accessory or not.

I'm going to close this issue as it's not an issue with Chummer.
