### ISSUE TITLE
[Bug] Using the spinner when adding ammo via plus makes it vanish

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4634]
**Describe the bug**
Using the spinner when adding ammo via plus makes it vanish

**To Reproduce**
1. Go to Street gear
2. Have ammo and select it
3. click plus in details menu and use spinner

**Expected behavior**
It does not vanish

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/365227867535310858/918491042649624616/SpinnerVanishing.gif)

**Comment by JonasTrampe** [comment]
Ok found it: 
`        private void UpdateGearInfo()
        {
            string strSelectedId = lstGear.SelectedValue?.ToString();
            if (_blnLoading || string.IsNullOrEmpty(strSelectedId))
            {
                tlpRight.Visible = false;
                return;
            }`
This part is the culprit. There is nothing selected in "lstGear" if you try to add stuff. On increment of the "numUpDown" "UpdateGearInfo()" is called and removes/hides the right table layout panel.

As a workaround one may click the ammo type in the "Select Gear" window and than everything is working as expected.

**Comment by JonasTrampe** [comment]
Forgot to mention that this is from frmSelectGear.cs

**Comment by ArchonMegalon** [comment]
Cool! That's teh kind of Bug-report we love. Even more, if you could make a
push request! Wanna try?

Giving a man a fish feeds him for a day, teaching a man to fish... ;)
