### ISSUE TITLE
[Bug] - 5.216.33 - Character has lost access to the "initiation" tab

### ISSUE THREAD

**Issue by MrTonic** [chummer5a/chummer5a#4635]
**Describe the bug**
Existing magic character has lost access to the initiation tab on the 5.216.33 nightly.

**To Reproduce**
Open linked character.  The expected initiation tab is not present (the character has previously initiated twice).

**Expected behavior**
Tab should be present, I guess?

**Character File**
[20210615 - Rumble Career.zip](https://github.com/chummer5a/chummer5a/files/7685921/20210615.-.Rumble.Career.zip)

**Desktop (please complete the following information):**
WIndows 10

**Additional Information:** 
Character uses the Neon Anarchy custom dataset, but Stexinator (from the Chummer5 discord) has also seen the same issue.

**Comment by Stexinator** [comment]
The export still has the data. So I guess its just UI

**Comment by MrTonic** [comment]
Well that's reassuring, though does mean for a while there's no new initiations. Thanks for looking into it.

**Comment by Stexinator** [comment]
The tab is back, but all initiategrades were wiped
