### ISSUE TITLE
Picking Add Lifestyle After Adding Trust Fund Quality Causes CTD

### ISSUE THREAD

**Issue by panton41** [chummer5a/chummer5a#4636]
**Describe the bug**
After picking the Trust Fund Quality, opening the Add Lifestyle dialog under Street Gear/Lifestyle tab causes a crash to desktop.

**To Reproduce**
1) Add the Trust Fund Quality (And the required SINner Quality).
2) Go to Street Gear tab.
3) Go to Lifestyle tab under Street Gear.
4) Click "Add Lifestyle" button.
5) UI will flicker and then the program will crash to desktop within a few seconds.

**Expected behavior**
No crash to desktop

**Screenshots**

**Character File**
[Muffin.zip](https://github.com/chummer5a/chummer5a/files/7698448/Muffin.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21.H2 (22000.318)

**Additional context**
In the rules the various Trust Fund levels apply "free" levels of a Lifestyle based on the level taken. There is already a Trust Fund check box in the Add Lifestyle dialog.

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightlies.
