### ISSUE TITLE
Missing/faulty critter data for Howling Shadows' "Mutant & Toxic Critters" section

### ISSUE THREAD

**Issue by MrDraMaster** [chummer5a/chummer5a#4641]
stumbled upon Kokoro Cobra not being in the Master Index during play, looked through the chapter & XML to see what other critters are missing

- [x] Glow Rat (HS 95f.) has no category (probably should be Toxic as it's radioactive?), skills and powers are incomplete

seems to be SR4 data:
- [x] Neogargoyle (HS 98) (wrong source book & page [RW 165] listed)
- [x] Sea Leech (HS 102f.) (wrong source book & page [RW 166] listed)

missing:
- [x] Killdeer (HS 97f.)
- [ ] Kokoro Cobra (HS 98)
- [ ] Montauk (HS 99)
- [ ] Pandamonium (HS 100)
- [ ] Radhound (HS 100f.)
- [x] Razorcat (HS 102)
- [ ] Shardik (HS 103f.)
- [ ] Spark Salmon (HS 104f.)
- [ ] Spidermoose (HS 105)
- [ ] Souleater Leech (HS 105f.)
- [ ] Void Wasp (HS 106f.)

**Comment by Stexinator** [comment]
https://github.com/chummer5a/chummer5a/pull/4788 adds the cat

**Comment by Teksura** [comment]
I'm currently finishing off the list. Right now I just need to finish Spidermoose, Souleater Leech, and Void Wasp.


Then I get to debate with myself if I want to spend a little more effort trying to make that xml file a little bit less of a mess.
