### ISSUE TITLE
Missing Armor Upgrade Drones

### ISSUE THREAD

**Issue by wondalfo** [chummer5a/chummer5a#4642]
**Describe the bug**
In my character the german book "Asphaltkrieger" is activated. This is the riggers book with all the vehicles and drones. (I don't know the englisch name).
In version before 5.216 I could add a modification armor (drones) according to Asphaltkrieger page 129 to a drone. Now this option is missing.

**To Reproduce**
1. Add a drone
2. Right click on drone and choose Add modification
3. Search for Armor (drones) --> it is missing

**Expected behavior**
Armor (drones) should be aailable as a modification

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.216.0.0

**Comment by DelnarErsike** [comment]
I assume you are playing with a character settings file where R5's Drone Modding rules are not enabled. Please re-open the issue if you can replicate it with a settings file that has Drone Mods enabled.

**Comment by wondalfo** [comment]
Yes that was the reason. Now I can report the real issue.
