### ISSUE TITLE
Issue: - Created new character, selected Tools men > Global Options, clicked Data Trails to highlight, clicked OK and app crashed

### ISSUE THREAD

**Issue by MAKerrTech** [chummer5a/chummer5a#4646]
### Environment
Crash ID: d37c0521-d10a-4ef8-8ed0-ff507e8b73a6
Chummer Version: 5.214.26
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: e2883925-3e51-4a48-8147-9f91ad1d413e

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
You are using a fairly old Nightly build. Could you double-check if the issue is still present in the current Nightly?
