### ISSUE TITLE
Auto-Generated Issue from Crash: ID 39a61763-e170-4618-989f-667e06fba3c4

### ISSUE THREAD

**Issue by HyugAberask** [chummer5a/chummer5a#4647]
### Environment
Crash ID: 39a61763-e170-4618-989f-667e06fba3c4
Chummer Version: 5.216.48
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: c7536635-35c9-419c-ae46-cf15d5817ecf

### Expected behaviour
Character should load.

### Actual behaviour
Unable to load the character.

### Steps to reproduce the behaviour
Try to reload the character.

### Crash Description
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   bei System.Windows.Forms.Control.WndProc(Message

**Comment by HyugAberask** [comment]
I just figured that the problem was caused by the mugshot. I deleted the entry via text editor and I'm now able to load the character again.

**Comment by ArchonMegalon** [comment]
Still doesn't mean we should not fix it. Can you send me the mugshot-file?

**Comment by HyugAberask** [comment]
You're totally right. 
I added multiple mugshot-files, unfortunately I can't post them publicly. Are there any possibilities to send them to you directly?
