### ISSUE TITLE
Upgrading Ware in Career Mode Impossible - Essence Holes

### ISSUE THREAD

**Issue by JohnBlack687** [chummer5a/chummer5a#465]
(Should note that I have Biocompatibility: Bioware)

Attempting to upgrade the ratings of cyber/bioware in career mode creates undeletable essence holes.

https://gyazo.com/68b5ef81d3eb34a6389e172c9c9fb4d2

Among my ware list, I want to upgrade, say, my Standard Cerebral Boosters from 2 to 3.

So I click on add bioware and purchase Cerebral Boosters 3.

https://gyazo.com/899c114880da1028a59572821df87083

https://gyazo.com/53bc9972ea12e2f7fa648fa12360ea36

And now I just sell off my Cerebral Boosters 2 for 100% -- it's an upgrade, so I just pay the difference (at least at my table).

https://gyazo.com/bac00ce38c6de9bdb5db1250fa50e7ee

But now I have an essence hole. Instead of the 0.36 essence cost of the Rating 2 being REPLACED by the 0.54 essence cost of the Rating 3, instead both costs are ADDED together in the form of this essence hole.

The essence hole is UNDELETABLE, mind you. So at the very least, could you make it an option to delete the essence holes?

**Comment by HaikenEdge** [comment]
I feel like you misunderstand how upgrading wares work. You upgrade wares by uninstalling the old one, then buying the new one to replace it. I'm fairly certain the way you're handling it is not how the upgrading of wares is handled in 5E.

**Comment by chummer5a** [comment]
Yeah, Chummer pretty much thinks you had both installed at the same time
then removed one. I guess we could implement something for replacing gear
that would make it a bit neater though.

**Comment by JohnBlack687** [comment]
Selling it, THEN buying the ware worked perfectly! Thanks for clearing it up. 

Though neatening up the upgrade system would make it a lot easier. Something akin to the big green plus button next to skills and attributes, maybe?

**Comment by joha4270** [comment]
Just to be sure, you are asking for a button to upgrade ware to a higher rating?

In that case, no not going to happen. Chummer tries to be as close to RAW as possible, and upgrading ware is not possible by RAW, you have to remove it and put new stuff in. 

If it is something else you are asking for, please elaborate

**Comment by chummer5a** [comment]
Think of it like the swap quality button. So it removes the selected
cyberware and replaces it with something else, applying the costs as
normal. We could prefill the search text with the item we're replacing to
facilitate replacements/upgrades easily enough I'd think.

**Comment by knightaries** [comment]
I can see how the button idea would be nice but I can also see where it would be a waste of code.
The plus button on the piece of cyber/bioware  would automatically sale the item, create the essence hole, then purchase the new item all in the background which would shorten the amount of time the player spent on upgrading the implants. (which is all within RAW)
No control over the sale back price.
Would only allow an increase in rating (as requested); what if I was upgrading both rating and grade. I'd still be back to doing the change the "slow" way.

What I could see as a feasible (not saying doable) request would be to allow a rt click then swap that would bring up all purchase/sale options to allow adjustments where needed. Maybe even replacing that piece of cyber/bioware with a completely different piece (of course limited to replace cyber with cyber; bio with bio and no crossing of essence holes.)
