### ISSUE TITLE
Initiations OR specializations vanquish

### ISSUE THREAD

**Issue by DecklandMulqueen** [chummer5a/chummer5a#4650]
First with 5.216.43 my initiation grades vanquished  .... i do not know why ... i gave it back to the character .... now with 5.216.49 skill specializations have vanquished ... i do not know why ... THAT SUCKS ... when i try to update the character, it works as long as i give me the first initiation grade, then the skill specializations vanquish again .... FURTHERMORE, when i try to do the char anew from the beginning, i cannot choose skill specializations .... I HATE THAT ... what the hell changed in the options that killed skill specializations ... or initiate grades or both ...

**Comment by DelnarErsike** [comment]
Initiations are gone permanently if you saved in the version where the tab disappeared. Specializations were just a display issue and they are back in .50.
