### ISSUE TITLE
Included Weapon holder in Nissan Doberman with drones modification rules

### ISSUE THREAD

**Issue by wondalfo** [chummer5a/chummer5a#4651]
**Describe the bug**
Included weapon holder in Nissan Doberman with activated drone modification rules should be big (R5 132) not standard (R5 168)

A nissan Doberman has an included weapon holder (Waffenhalterung). SR5 473 (german)
According to core book of standard size, which is flexible and can hold up to assoult rifle. SR5 467 (german),  --> in chummer: Standard [SR5] SR5 467
By choosing R5 book in character settings it should be Standard R5 168 (german) --> in chummer: Standard R5 168 --> this works
By activating Drones modification rules it should change to Big (drones) R5 132 (german) --> in chummer: Standard R5 168 --> don't work

Reasons:
Standard [SR5] and Big (drones) have the same price: 2500N
Standard [SR5] and Big (drones) can hold up to assoult rifles

**Comment by DelnarErsike** [comment]
Why exactly should the weapon mount switch to a drone weapon mount? Even with the drone modding rules, drones can hold vehicle mods, and the only replacement specified in R5 is a Doberman should have a Standard weapon mount that is External, Flexible, and Remote. And R5's Standard weapon mounts can hold Assault Rifles. This is a non-issue AFAICT.
