### ISSUE TITLE
Custom-type Files (i.e. `custom_[something].xml`) Do Not Load Their Data Properly

### ISSUE THREAD

**Issue by Gashnakh** [chummer5a/chummer5a#4652]
The Tradition "Straßenhexe(r)" from the Street Grimoire (Straßengrimoire) is missing in the dropdown menu since i updated from 216.32 to 216.50

It seems that all additional german publication traditions are missing...

**Comment by DelnarErsike** [comment]
I've adjusted the title of the issue to match what is actually going on. For those looking to debug the issue, you can use the Master Index to switch to a ruleset that has some content in a `custom_` file to see if a particular fix works or not.
