### ISSUE TITLE
Additional Category for Genemods

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#466]
Would it be possible to create an additional category (in addition to Bioware and Cyberware) for Gene Therapy? Currently, Genetic Therapy (labeled as Genemods) is listed under Bioware, but Gene Therapy simply isn't Bioware, so having it in the Bioware section gets a little problematic when the character you're working on also has Biocompatibility (Bioware); likewise, it's not Cyberware, so it'd make no sense to put it in that.

**Comment by imariaprime** [comment]
This would also solve the "Genemods don't have grades" issue, if grades could be disabled for the whole group.

**Comment by chummer5a** [comment]
Hrm. I thought I'd already fixed this.  I'll patch it properly for 1.77; any cyberware or bioware with a category of genetech, symbionts or genemods will have it's grade locked to standard and override any essence discounts that aren't specifically for genetic mods. I can tinker with it further from there if necessary.
