### ISSUE TITLE
Extended Clip costs the same for Rating 2 as for Rating 1

### ISSUE THREAD

**Issue by RyanthusarMercury** [chummer5a/chummer5a#4661]
**Describe the bug**
The cost for Extenden Clip is the same for Rating 1 and 2

**To Reproduce**
1. Go to Street Gear - Weapons
2. Right-Click on a Weapon and choose Add Accessory
3. Scroll down to Extendend Clip
4. Change Rating to 2 and the cost stay at 35 Nuyen

**Expected behavior**
When Rating 2 is choosen the cost should change to 70 Nuyen

**Screenshots**
![Extended Clip Rating 1](https://user-images.githubusercontent.com/78557324/148112694-4478b2c5-36f9-49f1-9aa1-75486e54b9cd.png)
![Extended Clip Rating 2](https://user-images.githubusercontent.com/78557324/148112731-95ff764e-a47f-4cb4-97f5-f53f1016cff0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.216.0

**Comment by DelnarErsike** [comment]
Not an issue. Official cost entry for Extended Clip in Hard Target p.183 says it always costs a flat 35 nuyen, regardless of rating.

**Comment by RyanthusarMercury** [comment]
Could it then be added to custom data "German Data Changes"? Because in the German Version it have a cost per rating.
![Extended Clip1](https://user-images.githubusercontent.com/78557324/148117455-29707100-103d-46bf-81ec-710a8350ae08.JPG)
