### ISSUE TITLE
Ares Alpha Grenade Launcher don't get Bonus Dice from Smartlink

### ISSUE THREAD

**Issue by RyanthusarMercury** [chummer5a/chummer5a#4662]
**Describe the bug**
The Underbarrel Grenade Launcher from Ares Alpha don't profit from extra dice from Smartlink

**To Reproduce**
1. Go to Street Gear - Weapons and add Ares Alpha
2. Click on Ares Alpha and point the Mouse on the Dice Pool number, there you see the additional two Smartlink dice
3. Click on Ares Alpha Grenade Launcher and point the Mouse on the Dice Pool number, there you don't see the additional two Smartlink dice and additionaly the Accuracy is 6 instead of 4 (6)

**Expected behavior**
The Grenade Launcher should have a baseline Accuracy of 4 and profit from the Smartlink for extra dice and Accuracy increase

**Screenshots**
![Ares Alpha](https://user-images.githubusercontent.com/78557324/148114014-f88bc133-564a-4a42-acc9-79211e6011f5.png)

![Ares Alpha Grenade Launcher](https://user-images.githubusercontent.com/78557324/148113989-1c42bf03-abec-44be-9500-19b06b41aec5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.216.0

**Comment by DelnarErsike** [comment]
AFAIK, it was never clarified if underbarrel weapons to smartguns are also able to take advantage of their parent weapon's smartgun features or if they need to get their own smartgun accessory/modification added.

**Comment by RyanthusarMercury** [comment]
When you add a underbarrel weapon then i would say you need an additional smartgun or the modification should be bigger as you need additional connections. But in this case the Weapon is sold with the Grenade Launcher from the beginning and at least in the German Version of the rules the Accuracy 4 (6) is a good hint that it should work with Smartgun.
![Ares Alpha1](https://user-images.githubusercontent.com/78557324/148116751-1a892dd1-c6c5-46f2-a22e-30e8e828d9a2.png)
