### ISSUE TITLE
Adept Power Improved Potential don't have a rating and Mentor Spirit (Chaos) provide only one level

### ISSUE THREAD

**Issue by RyanthusarMercury** [chummer5a/chummer5a#4664]
**Describe the bug**
Improved Potential don't have the possibility to get a higher rating than 1.
Additional to this, when the Quality Mentor Spirit (Chaos) is choosen, it is not possible to choose two Potentials or an Potential that was allready choosen and the Potential that was choosen get only level 1

**To Reproduce**
1. Create an Adept Character and go to Adept Powers
2. Click on Add Power
3. Scroll down to Improved Potential (it dosen't matter wich one as all of them don't have the possibility to choose a rating)
4. See no rating can be choosed and even after choosing it, the rating field is greyed out and it's not possible to increase it

**Expected behavior**
It should be possible to add a Potential with a rating bigger than 1 and when Mentor Spirit (Chaos) is choosen, than it should be possible to either choose one Potential with rating 2 or two Potenitals with each rating 1 and if you allready have this Potential as Adept Power, the rating should be increased

**Screenshots**
![Improved Potential](https://user-images.githubusercontent.com/78557324/148234348-00278544-db5a-4439-a93e-f8e4349dbf38.JPG)
![Improved Potential1](https://user-images.githubusercontent.com/78557324/148234368-e33b43dd-6cb6-4a6d-b0e1-da3712ddaba9.JPG)
![Improved Potential Chaos1](https://user-images.githubusercontent.com/78557324/148234394-5348a44a-30d0-4340-b6fd-1a0299d5c6b6.png)
![Improved Potential Chaos2](https://user-images.githubusercontent.com/78557324/148234404-bfa096f9-9480-4a7b-887c-46b8907bf2d7.png)
![Improved Potential Chaos3](https://user-images.githubusercontent.com/78557324/148234425-2d856d12-86c6-4ce0-83bb-3cfc418f34d6.png)
![Improved Potential german](https://user-images.githubusercontent.com/78557324/148234917-de2bbec4-2b4a-4b5e-b0a7-2f6abba4aa54.JPG)
![Chaos](https://user-images.githubusercontent.com/78557324/148234935-9cd1fa48-02a4-447d-9d01-e62849004131.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.216.0

**Comment by DelnarErsike** [comment]
Not an issue. In both the English text and the German text, one can clearly read that the power can be bought once per limit type. This is exactly what Chummer does by having three different entries of the power instead of one entry, with each one raising a different limit. The two-ratings-to-the-same-limit part of Chaos is/was a known issue that was addressed in #1519.

**Comment by RyanthusarMercury** [comment]
I see it different, in the german version it says that you can increase a potential by 1 per level and that you can get a second and third version of this Power for a different potential.
If it would be like you said, than there would be only a 0,5 KP cost and not 0,5 KP per level like for Enhanced Accuracy.
![Enhanced Accuracy](https://user-images.githubusercontent.com/78557324/148403530-29ce3ccb-de18-47dc-aeb3-6e7f231bf340.JPG)

**Comment by DelnarErsike** [comment]
And here is how the English version looks. Guess it's another one for the German Data Changes, then.

![image](https://user-images.githubusercontent.com/727731/148406543-2140da4e-6be5-4fba-997e-232af86d6007.png)

**Comment by DoomlordSoul** [comment]
RyanthusarMercury, du hattest btw recht gehabt. Hab das Ganze selbst mal in ein etwas Größeren Text zusammengefasst in den Post #4978 und selbst den Shadowrun Line Developer Jason M. Hardy zu rate gezogen. Vielleicht willst du ja auch noch was dazu hinzufügen was Delnar darauf aufmerksam macht, dass er die Kraft falsch versteht. Der bis jetzt noch nicht geantwortet hat.
