### ISSUE TITLE
Chummer5 Issue Handling Trust Fund Lifestyle

### ISSUE THREAD

**Issue by CapriciousDream** [chummer5a/chummer5a#4665]
**Describe the bug**
Upon selecting the Trust Fund Quality, if a lifestyle is picked with the same rating as given by the Trust Fund, Chummer5 crashes with the crash being detailed as "Object reference not set to an instance of an object".

**To Reproduce**
1. Create any new character with the material from "Run Faster" enabled
2. Select any Trust Fund as a quality to apply to the character
3. Select to create a lifestyle
4. Upon selecting the lifestyle option appropriate to the Trust Fund quality, Chummr will CTD

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Milestone 5.216.0

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
