### ISSUE TITLE
List of Megacorps in Life Modules File Should Include AA Corporations

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4668]
The full list is at https://shadowrun.fandom.com/wiki/Shadowrun_corporations#AA_Megacorporations_.282078.29
AA Megacorporations (2078)
    AG Chemie Europa (NEEC)
    Aerospatiale SA
    Chalmers & Cole Associates
    Citigroup (MDC)
    Colt Manufacturing
    Cord Mutual Insurance
    DocWagon
    Eastern Tiger Corporation (PPG)
    ESUS (NEEC)
    Federated-Boeing (PPG)
    Ford Motor Company, Inc.
    Frankfurter Bankverein AG (Frankfurt Bank Association) (NEEC)
    Gaeatronics (PPG)
    Genesis Consortium
    Global Standstorm
    Hildebrandt-Kleinfort-Bernal (NEEC)
    Hyundai[1]
    Integrated Weapon Systems PLC[2]
    Index-AXA
    Korporacja Opatrznosci Bozej (Providence Corporation)
    Kolkota Integrated Talent & Technologies
    Komatsu Limited
    KondOrchid SA[3]
    Kwonshan Industries[1]
    Lockheed Corporation[4]
    Lone Star Security Services
    Lusiada (NEEC)
    Maersk Incorporated Assets (NEEC)
    Monobe International
    Nagato Corporation[5]
    NYPD, Inc. (MDC)
    Phoenix Biotechnologies
    Prometheus Engineering (MDC)
    Proteus AG (NEEC)
    Reality, Inc.
    Regency MegaMedia[6]
    Regulus Joint Industries
    Renault-Fiat-Meridional (NEEC)
    Samyung[1]
    Shibata Construction and Engineering (PPG)
    ShinSiam
    Singapore, Inc.
    Sony Corporation (MDC)
    Spinrad Industries ((MDC; NEEC)
    Tablelands Software
    Tanamyre Resources[7]
    Telestrian Industries Corporation
    Trans-Orbital (MDC)
    UOL
    Universal Omnitech (PPG)
    Vedacorp
    Virtual Reality, Inc.
    Winter Systems
    Yakashima Technologies
    Yang Su Enterprises[1]
    Yokogawa Corporation
    Zeta-ImpChem (NEEC)

**Comment by binnsr** [comment]
updated lifemodules.xml
[lifemodules.xml.txt](https://github.com/chummer5a/chummer5a/files/7841669/lifemodules.xml.txt)

**Comment by DelnarErsike** [comment]
Not strictly an issue. The fields for SINner (Corporate) and SINner (Corporate Limited) are set as editable, so people can just type in whatever corporation they want into them. I did add an empty list item just to lead people to this conclusion though, the same way empty list items exist for skill specialization fields.
