### ISSUE TITLE
Custom Cyberdeck Attack, Data Processing and Sleeze missing Availability

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4669]
When creating a Custom cyberdeck ( e.g. Fuchi Cyber-EX) and adding matrix ratings, Attack, Data Processing and Sleaze are missing Availability settings, making for broken decks.
![image](https://user-images.githubusercontent.com/26882158/149379311-47bdb89f-ea52-4360-9880-fb2b0aef2e0b.png)

![image](https://user-images.githubusercontent.com/26882158/149379490-cb49d28c-817a-4302-a6f4-a34da18e9c79.png)
![image](https://user-images.githubusercontent.com/26882158/149379520-92003650-fed8-4c14-8035-21e0bd82eec3.png)
![image](https://user-images.githubusercontent.com/26882158/149379551-3192b4c0-d85c-4cb9-889e-76a7d5cac133.png)
![image](https://user-images.githubusercontent.com/26882158/149379588-c99559b0-c670-4d8d-882d-4d8f1493c6fb.png)

**Comment by DelnarErsike** [comment]
Yes? I mean, the availabilities for all attributes other than Firewall are marked as "-", so they are zero in Chummer. Firewall is marked as (Rating x 4)R, and so it has a rating.
