### ISSUE TITLE
Specialization price in career mode is wrong

### ISSUE THREAD

**Issue by Krindi** [chummer5a/chummer5a#467]
Version 0.5.175
Create character
Enter Career Mode
Skills tab
Add a new specialization
"Add Specialization for 8 Karma"

SR5 Core book, p107, Character Improvement Table
New specialization (for Active, Knowledge, or Language) = 7 Karma Cost

**Comment by HaikenEdge** [comment]
Not sure what's causing that problem; I've put together over a dozen characters, and none of them have had this occur to them.

**Comment by joha4270** [comment]
Please reset your settings and see if this problem persists.

**Comment by Krindi** [comment]
Yes that appears to have been the problem.  New Specialization was set to 8, and Spirit was set to 2 karma per services owed rather than 1.
