### ISSUE TITLE
GMC Armadillo does not come with the options listed as standard features in R5

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4670]
Per the book, it should come with Armory, Cargo Pod, drone rack (size unspecified?) food truck mod, rigger coccoon, offroad suspension&tires, sleeper cabin, transport and workshop (type unspecified)

![image](https://user-images.githubusercontent.com/26882158/149594157-a4801dab-e61c-4708-89db-85a6dd1f64e4.png)

![image](https://user-images.githubusercontent.com/26882158/149594017-5731786a-fd4f-4126-b86d-556b35795ec1.png)

**Comment by DelnarErsike** [comment]
The actual box of stats here is incorrect. The GMC Armadillo is a pickup truck with interchangeable beds, and the list in the "Standard Equipment" box is about the types of beds the GMC Armadillo can have. However, none of these custom beds have any stats detailed for them, and so they cannot have entries in Chummer. Closing this issue, but marking it as needing Errata in case CGL somehow decides to go back and officially errata this.
