### ISSUE TITLE
Mentor Sprit skill bonus choice not provided

### ISSUE THREAD

**Issue by pda6ne** [chummer5a/chummer5a#4671]
**Describe the bug**
When creating an Adept and selecting the Mentor Spirit quality, the supposed bonus to given skills does not appear/apply.

**To Reproduce**
1. Create a new character (Adept)
2. Add the Mentor Spirit (Cat) quality
3. Go to Skills
4. See that bonus is automatically applied to Gymnastics (should be given choice between Gymnastics and Sneaking)

**Expected behavior**
There should be a popup after selecting the Mentor Spirit (Cat) quality to choose either Gymnastics or Sneaking.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by RyanthusarMercury** [comment]
There is a dropdown menu where you can choose between Gymnastics and Sneaking before you click on Ok to choose Cat
![Mentor Spirit Cat](https://user-images.githubusercontent.com/78557324/149675978-182dc168-9c28-42ba-8eb7-cd692cf8dc1c.JPG)
