### ISSUE TITLE
Power Focus

### ISSUE THREAD

**Issue by Mastaziel** [chummer5a/chummer5a#468]
Not sure if I missed something, but is a power focus rating supposed to add to Counterspelling? It says it adds to anything that requires the Magic attribute, and seems to add to everything else OK. But not Counterspelling.

Still enjoying your great work.
Thanks

Clayton

**Comment by chummer5a** [comment]
As is, the power focus is specifically set not to include counterspelling. RAW says that it increases dice pools for Sorcery, Conjuring and Enchanting. If you can give me an errata or clarification from the developers that it should be otherwise I'll be happy to amend it.
