### ISSUE TITLE
No option to purchase ammunition for mounted weapons

### ISSUE THREAD

**Issue by gabrialm** [chummer5a/chummer5a#4699]
Current version: 5.221.0
Operating System: Window 10

Issue: When mounting weapons to drones or vehicles, there is no dialogue button to purchase ammunition specifically for that weapon.

Impact: Cannot use mechanics within Chummer to automatically handle reloading and tracking of ammunition use during combat.

This functionality operates correctly with weapons in the Street Gear > Weapons tab.

**Comment by gabrialm** [comment]
Figured out a work around by purchasing a heavy machine gun under Street Gear first, purchasing ammo and loading it, then transferring the weapon to a vehicle with an open heavy weapon mount.

**Comment by DelnarErsike** [comment]
Vehicle-mounted weapons should be reloadable from ammo that is in the vehicle itself. There is no option to purchase that ammo with a single button, but you can always just manually purchase ammo yourself and select the weapon type for the ammo after you select which one to buy.
