### ISSUE TITLE
Cant buy a liscense

### ISSUE THREAD

**Issue by crimsonrebel** [chummer5a/chummer5a#4702]
In the current version 5.221.0.0 you are unable to buy a fake license under gear.  You may only buy a fake SIN.

**Comment by DelnarErsike** [comment]
Not a bug. Licenses need to be attached to SINs, as outlined by the core rulebook. So you cannot buy a standalone Fake License, you can only buy a Fake License as an addon to a Fake SIN.

**Comment by crimsonrebel** [comment]
There is no option to do an add on
