### ISSUE TITLE
Skill Groups-Related House Rules Not Working Properly

### ISSUE THREAD

**Issue by Aybes** [chummer5a/chummer5a#4707]
Compensate for higher karma cost and Allow skills to be re-grouped no longer working properly.

**Comment by DelnarErsike** [comment]
Just to double check, this is after character creation, right? Because during character creation, neither of those rules do anything because you can always freely raise or lower ratings at will.

**Comment by Aybes** [comment]
This is after character creation. I have also found that Knowledge skills are also capped to rank 6 also after character creation.

**Comment by DelnarErsike** [comment]
Could you double-check to see if this is still an issue?

**Comment by Aybes** [comment]
As of Nightly Build 5.222.73 Skill Groups do remerged now when all skills are of equal ranks. I tested with with older generated characters, 5.213.0 or older, and newer generated characters.
