### ISSUE TITLE
Life Modules and  SIN Qualities

### ISSUE THREAD

**Issue by knightaries** [chummer5a/chummer5a#471]
I was using the life modules to build a character which ended up having multiple SIN(s) of the same and different types (I think at one point I was showing 2 national and 1 corp limited). RAW/RAI if a life module has a National SIN and I get another module with a National SIN I should still only have 1 National SIN. If I then get a module with a Corp Limited SIN then it should override the National SIN with the Corp one.
For RAW:
"At the 10 Karma level, the character has a Criminal SIN (either Corporate or National); his Criminal SIN replaces any previous SIN.
The Corporate Limited SIN allows the character to be employed by the megacorp under most circumstances, and it replaces any National SIN that the character may have had previously."
For RAI:
"Steve figures that Trainwreck’s rough life keeps him out of any traditional education structures, and that instead he continues on a troubled path. He now selects the Ganger module to represent this phase of Trainwreck’s life. The Criminal SIN replaces his original SIN"  RF pg 89

A possible solution I see is maybe a type of status check under the SIN(s); If SIN = 0 then add SIN.
Or somehow have it setup to overwrite a lesser cost with a higher cost one and to not add more.

**Comment by joha4270** [comment]
I'm aware of this and need to fix it someday.
But there is a reason Life Modules are hidden behind a "beta" or whatever
the checkbox is named.

Maybe in next update, but i haven't had too much free time.

2015-10-23 22:53 GMT+02:00 knightaries <notifications@github.com>:

**Comment by OLStefan** [comment]
Part of #2000.
