### ISSUE TITLE
Mentor Spirit missing

### ISSUE THREAD

**Issue by SlyILuna** [chummer5a/chummer5a#4714]
Hi,

with the current update, a mentor spirit was removed from the German version, namely the Mondin. Is this intentional or just happened by accident, because so far I have found nothing in the update log.

When i choose a mentor spirit can't pick the Mentor Spirit Mondin (German  Rule Book "Strassengrimoire" SG PDF-Side 233) in the Chummer version 5.222.0 cant find them.

**Comment by DelnarErsike** [comment]
Are you sure you have the German Data Changes custom dataset enabled for your character? All of the content differences between the German and English books have been collected there, including mentor spirits that appear in the German books but not in the English ones ("Mondin" would be "Luna" in the English translation).

**Comment by Stexinator** [comment]
I can find the Mondin

**Comment by Stexinator** [comment]
@SlyILuna

**Comment by SlyILuna** [comment]
I found the option and now i have the mentor spirit.
