### ISSUE TITLE
Overclocked Weapon Mod

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#472]
Two things I noticed:
Firstly, Overclocked is supposed to decrease the DV of a weapon that deals electrical damage by 2. That's a basic data entry thing should be pretty simple to handle, but when I tried adding a dicepool function to my local weapons.xml under the Overclocked mod, nothing really happened, so I'm not sure how to fix what should be a simple data entry problem.

Secondly, Overclocked changes the weapon's damage code from S(e) to P(e). Not sure how that is supposed to be handled.

**Comment by chummer5a** [comment]
Hrm. As is, changing the Damage Type is only exposed to gear. Not particularly difficult to enable, just needs some coding. If it's a quick and dirty fix you're after, just make an accessory item and use the weaponbonus node.

**Comment by chummer5a** [comment]
Included in 5.197.
