### ISSUE TITLE
Infected characters cannot be saved

### ISSUE THREAD

**Issue by Maguillage** [chummer5a/chummer5a#4721]
**Describe the bug**
Characters that have an Infected quality selected throw an error when you attempt to save them.

**To Reproduce**
1. Create a new character
2. Assign an Infected quality
3. Attempt to save

**Screenshots**
![image](https://user-images.githubusercontent.com/91387479/156412719-b33e0142-61b8-4a50-802b-b9effbbcdb6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.222.0

**Additional context**
Also affects existing characters with an infected quality.
The issue wasn't present in 5.221.0

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
