### ISSUE TITLE
Crash at adding improvements

### ISSUE THREAD

**Issue by G0thm** [chummer5a/chummer5a#4722]
**Describe the bug**
Chummer 5.222 ist crashing when i add an improvement to a character.

**To Reproduce**
1. Go to 'Improvements'
2. Click on 'Add Improvement'
3. Select some improvement like initiative or attribute and OK

**Expected behavior**

**Screenshots**
![Chummer_Error](https://user-images.githubusercontent.com/47820377/156883288-cf8eff2c-02ce-4602-80d9-2aecc76c0cf8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Windows 11
 - Version 5.222

**Additional context**
In Version 5.221 the problem dont exist.

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightlies
