### ISSUE TITLE
Learning Stimulus nanoware does not reduce karma cost

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4723]
**Describe the bug**
Learning Stimulus nanoware does not reduce karma cost

**To Reproduce**
Buy it => increase skills

**Comment by DelnarErsike** [comment]
Learning Stimulus only decreases the cost of knowledge skills. Are you sure you tested this with knowledge skills?

**Comment by Stexinator** [comment]
Yeah thats it. It works as expected for knowledge skills
