### ISSUE TITLE
No rendering in print dialog

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#4726]
**Describe the bug**
When I want to print my character the print dialog doesn't render the sheets. It stops after loading the character with message "Erzeuge Blätter..." (Generating sheets?).

**To Reproduce**
1. Open Character
2.  Open print dialog
3. Wait unti CHar is loaded

**Expected behavior**
The characters sheets for printing is rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/42451897/157315062-d9c57b33-9cad-4b8b-b430-2f6b42a6d1d3.png)

**Character File**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chummer Version 5.222.25

**Additional context**
-

**Comment by DelnarErsike** [comment]
Fixed in a commit ef0373c58bff0c081c33dfb3e32a0524641f5bf9.
