### ISSUE TITLE
Opening Sourcebook PDF fails

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#4727]
**Describe the bug**
When I kclick on any reference to open an assigned PDF file in a configured PDF reader, the PDF reader can't open the PDF file.

It looks, like the filw path is prefixed by the program directory of Chummer5a (See screenshot, marked path. This is the error messake of SumatraPDF. Translation of "Fehler beim Öffnen von" -> "Error while opening")

**To Reproduce**
1. Assign a PDF Sourcebook file in configuration
2. Try to open the PDF by klicking a reference in GUI

**Expected behavior**
PDF reder starts and PDF is opened

**Screenshots**
![image](https://user-images.githubusercontent.com/42451897/157342334-54341aad-9de4-46d8-8093-19e9cb1da02d.png)

**Character File**
-
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chummer Version [e.g. 5.222.25]

**Additional context**
-

**Comment by DelnarErsike** [comment]
Make sure you have the correct PDF argument type selected in your Global Settings. It looks like you have your reader set to Sumatra PDF, but left your PDF argument type at Web Browser instead of switching to one of the Sumatra options.
