### ISSUE TITLE
Chummer crashes while adding lifestyle to char

### ISSUE THREAD

**Issue by DatenNirwana** [chummer5a/chummer5a#4728]
**Describe the bug**
CHummer crashes with an exception, when I try to add a lifestyle,

**To Reproduce**
1. Add Lifestyle (compare to screenshot)
2. Click 'OK'
3. See Exception ;-)

**Expected behavior**
The new Lifestlye is added to the char.

**Screenshots**
Create Lifestyle Dialog, with lifestyle I try to add:
![image](https://user-images.githubusercontent.com/42451897/157342951-5a4fab12-bb6e-4e26-8000-1276ce89fa48.png)

The exception (My display is to small to capture all):
![image](https://user-images.githubusercontent.com/42451897/157343083-d5fbb6cb-6df8-42f4-8aec-92796ba948ff.png)

**Character File**
- Tried with new char.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chummer Version 5.222.25

**Additional context**

**Comment by DelnarErsike** [comment]
Fixed in commit af1cccdfc16a959cb1f3a534ba7867c758a1be0b.
