### ISSUE TITLE
Machine Pistols are wack

### ISSUE THREAD

**Issue by Thelinil** [chummer5a/chummer5a#473]
Machine pistols are wack
![capture](https://cloud.githubusercontent.com/assets/13618570/10713727/6a09d9f4-7a9d-11e5-984c-410bd4a5684b.PNG)

**Comment by knightaries** [comment]
What version are you running?
Was this during character creation or was this in created mode?
Did you have any errors prior to the glitch? And what steps did you do for this to appear?

I tried recreating and couldn't

**Comment by HaikenEdge** [comment]
It got stealth patched this morning.

**Comment by chummer5a** [comment]
Stealth patched via auto-update. Manual release will be soonish.
