### ISSUE TITLE
Complex Forms Diffusion of [Matrix Attribute] and Infusion of [Matrix Attribute] can't be added to create file Technomancer

### ISSUE THREAD

**Issue by RowKHAN** [chummer5a/chummer5a#4730]
**Describe the bug**
When trying to add the Complex Forms Diffusion of [Matrix Attribute] and Infusion of [Matrix Attribute] neither are applied to the complex form list. Neither opens the selection box to choose a Matrix Attribute and neither are added to the Complex Forms & Sprites sheet on the character sheet. 

**To Reproduce**
1. Create a Technomancer
2. Go to "Complex Forms & Sprites"
3. Click "Add Complex Form"
4. Select either "Diffusion of [Matrix Attribute]" or "Infusion of [Matrix Attribute]"
5. Click either "Add & More" or "Ok"
6. See error

**Expected behavior**
Adding the Complex Forms Diffusion of [Matrix Attribute] or Infusion of [Matrix Attribute] should add them to the character sheet after opening a box to select the Matrix Attribute of the Complex Form.

**Screenshots**
Not applicable

**Character File**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Additional context**
None

**Comment by DelnarErsike** [comment]
Should be fixed in commit 2d2428a34e8633c58308b9b2eb58bc7c8ae9dacf (and therefore the most current Nightly).
