### ISSUE TITLE
Adding Accessories in Street Gear -> Gear does not adjust money instantly

### ISSUE THREAD

**Issue by TMoeser-Goe** [chummer5a/chummer5a#4736]
**Describe the bug**
When you add any accessories to any Gear in the Street Gear / Gear menue, the Nuyen Remaining Info does not update.

**To Reproduce**
1. Create new Char with standard setting
2. Street Gear
3. Add Gear (Metalink)
4. Add Accesory to Gear (Sim Module to Metalink)
5. Look at Nuyen Remaining and see Error

**Workaround**
6. Trigger Nuyen Update by Buying/Selling Gear
7. See that the Nuyen Remaining info has changed and now incorporates the bought accessory

**Expected behavior**
The Nuyen should update when an accesory is added or removed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58635904/157835149-f524ca17-4082-4d4b-96b0-3685ad4ea7db.png)
Here you see an example, Money should be 5 800 (For Metalink + Hotsim each 100)
but is 5 900.

**Desktop (please complete the following information):**
 - Win 10 
 - Version 5.222.0

**Comment by chummer5a** [comment]
Unable to replicate in nightlies. New milestone will be out within the next couple of days.
