### ISSUE TITLE
Crash on Add/Remove of Cyberware

### ISSUE THREAD

**Issue by BlueThing00** [chummer5a/chummer5a#4738]
**Describe the bug**
When adding/removing cyberware I have seen crashes with Chummer5.222.0.  I finally was able to make a simple reproduction case.

**To Reproduce**
1) Create a Sum to Ten Character (I used E-A-E-C-A)
2) Add Obvious Full Arm (Left)
3) Add Plugins (Armor 2, Customized Str 6, Customized AGI 6, Enhanced AGI 2)
4) Add another Obvious Full Arm
5) Chummer crashes and fails to create a crash report

**Expected behavior**
Chummer doesn't crash

**Screenshots**
![image](https://user-images.githubusercontent.com/21363819/158022241-68ac8420-8a8c-4d4d-8107-14f89987e51f.png)
![image](https://user-images.githubusercontent.com/21363819/158022208-ba28e2f9-0842-4399-b0f0-952da8955bed.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222.0

**Additional context**

**Comment by DelnarErsike** [comment]
Known issue, fixed in the Nightly

**Comment by BlueThing00** [comment]
Good to know.  Thanks!
