### ISSUE TITLE
Missing Gear Items

### ISSUE THREAD

**Issue by athwargamer** [chummer5a/chummer5a#474]
First off - Awesome work, you've saved me a lot of effort.

So, I've found that its not possible to add accessories to holdouts, but it means that it's not possible to add holsters and other weapon accessories that don't take up mounts on them either.

Either you there needs to be a short list of accessories that can be added from the weapon list, or a weapon accessories list in Gear

**Comment by Kyoto-Kid** [comment]
...looked through the ammo/gear listing and unable to find Drums for combat shotguns.

**Comment by chummer5a** [comment]
I'm currently going through some of the older tickets, I think the next one I tackle will be the whole mod/accessory situation. it's currently a bit of a mess.

**Comment by chummer5a** [comment]
Implemented in 5.177.
