### ISSUE TITLE
[WINE] Chummer crashes when trying to load characters

### ISSUE THREAD

**Issue by SlidingHorn** [chummer5a/chummer5a#4741]
**Describe the bug**
Title

**To Reproduce**
1. `wine Chummer5.exe`
2. Attempt to open a character, either by double clicking favorites or by File > Open
3. Crash

**Character example**
[blossom-career.txt](https://github.com/chummer5a/chummer5a/files/8301421/blossom-career.txt)

**Desktop (please complete the following information):**
 - OS: Arch 
 - Version 5.222.0.0

**Additional context**
Backtrace attached
[backtrace.txt](https://github.com/chummer5a/chummer5a/files/8297703/backtrace.txt)

**Comment by DelnarErsike** [comment]
This looks like a general Wine issue, as the crash was caused by a rendering call. We have zero control over the internal code of the rendering libraries used, so this isn't really a crash we can actually do anything about on our end.

**Comment by SlidingHorn** [comment]
Upon seeing your comment, my original thought was to blame a recent update to WINE. However, I downgraded to the previous version that had worked, and I'm getting the same problem with the difference being I get a *chummer* error message before the WINE crash dialog.

![screenshot-20220319230713](https://user-images.githubusercontent.com/6623121/159146426-1ddedaad-5c45-4167-8373-7924302b0da4.png)

I don't know if this makes any difference in your assessment of the issue or not. I do have post up on the WineHQ forum asking about it as well, so hopefully between here and there, I can get this figured out.

Regardless, thanks for your time and the effort you put into Chummer!
