### ISSUE TITLE
Character Creation with Quality: Infected: Vampire (Human) leads to 'Chummer5 encountered an error while saving the character error.

### ISSUE THREAD

**Issue by anonymica1** [chummer5a/chummer5a#4744]
**Describe the bug**
When creating or using an already existing character with Quality: Infected: Vampire (Human), this character cannot be saved any more and leads to 'Chummer5 encountered an error while saving the character error.

**To Reproduce**
1. Simply create a character ( in my case human mage) and add infected quality. 
2. Try to save and see "Chummer5 encountered an error while saving the character" Error

**Expected behavior**
In earlier Versions it was possible to save vampire characters. Since january i cannot save it anymore.
**Screenshots**
![image](https://user-images.githubusercontent.com/102066896/159336765-13035fd2-63b2-4e97-8f5d-bf1dd87831e9.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS:: Windows 10 / Windows 11
 - Version 10.0.22000 Build 22000

**Additional context**

**Comment by DelnarErsike** [comment]
Known issue to do with natural weapons, already fixed in the Nightlies.
