### ISSUE TITLE
No recoil compensation displayed for drone weapon mounts.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4753]
If you create a drone and add a weapon mount with a weapon you should be able to see the RC of the gun along with the other stats. In the spot where RC is normally shown is the fire mode perhaps this display is covering the RC?

**Comment by DelnarErsike** [comment]
AFAIK, vehicles do not use recoil rules, so showing RC is irrelevant.

**Comment by chummer5a** [comment]
> SR5 p. 176 Vehicle and Drone Mounted Weapons
> Vehicle and Drone Mounted Weapons Vehicle and Drone mounted weapons have the advantage of a sturdy platform from which to fire. The vehicle itself has enough mass to absorb the bulk of the recoil created by the weapon. Mounted weapons have Recoil Compensation equal to the Body of the vehicle plus any built in Recoil Compensation of the weapon.

**Comment by bulldogc** [comment]
Thanks that was the one I was trying to find as well !
