### ISSUE TITLE
Traditions do not respect 'Required' or 'Forbidden' operations

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4756]
**Describe the bug**
Traditions do not respect 'Required' or 'Forbidden' operations - example is 'Norse [Berserker]', which required Adept of Mystic Adept.

**To Reproduce**
Make a magician and assign the 'Norse [Berserker]' tradition - you shouldn't be able to, but you can.

**Expected behavior**
'Norse [ Berserker]' should not show in the list for non adept characters.

**Comment by chummer5a** [comment]
Core issue behind implementing this is that traditions are currently a dropdown; constantly re-evaluating that list would be quite expensive in UI performance. Easiest fix would be to change the dropdown to be a button that opens a new form for selection, possibly using the generic selectitem form, and a label that says the current name. Using that route, we would have to include a validity check for if the tradition is still allowed when completing the transition.
