### ISSUE TITLE
Drone armor isn't calculating mod points correctly.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4757]
As I understand the rules for it, the first 3 points of armor should be 0 MP and each addition should be +1 mp. This seems to be correct when increasing the armor via the customization, but the total MP used by the mods only increases by +1 every 3 armor increases.

**Comment by DelnarErsike** [comment]
Cannot replicate with the latest Nightly.

**Comment by bulldogc** [comment]
try the following with Nightly-v5.222.61

create new char with use drone mod rules enabled
add ares matilda to char
add armor rating 14 to the drone. 
This takes up 3 slots as expected in the description for the armor +3=0mp 2 mp for +2 more. but look at the total used mod slots on the drone level, that will remain at 1/8.
now up the armor to 15, this will case the total used mod slots to increase to 2. There seems to be some odd calc bug in the total mod slot used.

Also as i wrote this out I noted 2 second bug here. the slots that the armor mod itself uses doesn't refresh as you change rating, only if you click off and re-select it. Can replicate this by just changing the rating up or down, slots used doesn't change until you select something else then select the armor again.
