### ISSUE TITLE
Adept power: Authoritative Tone

### ISSUE THREAD

**Issue by cac666** [chummer5a/chummer5a#4758]
Dear Support,

You referred the Authoritative Tone adept power [in this thread](https://github.com/chummer5a/chummer5a/issues/1350l) about the Commanding Voice adept power, but unfortunately there is no Authoritative Tone in the program.

Best regards,
Krisz

**Comment by chummer5a** [comment]
It's in the Street Grimoire Errata book.

**Comment by cac666** [comment]
You are right!
I used "Toggle all Sourcebook On" button on Character Settings. I don't know why SG Errata turned off.
I enabled this book so Authoritative Tone is available now.
Sorry for the inattention!
