### ISSUE TITLE
Enhancement Cost

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#476]
According to Street Grimoire, the cost of learning an enhancement is the same as learning a new skill (2 Karma), but Chummer says it costs 5 Karma at the moment, even though it only subtracts 2 Karma. I tried looking in options, but apparently, that's not something that can be adjusted independently, so it's leading to some confusion, even though it's really a quality of life thing.

**Comment by chummer5a** [comment]
The actual reduction is correct, but the message string was using the new Spell int instead of the Enhancement one. Fixed in 5.177.
