### ISSUE TITLE
Two Cyberlimbs of the same kind crash the program

### ISSUE THREAD

**Issue by KitsuneOfKamis** [chummer5a/chummer5a#4762]
**Describe the bug**
If you install a cyberlimb (e.g. a leg) and then try to install the exact same kind for the other limb (e.g. left leg, then right leg with a visible cyberleg) then the system crashes.

**To Reproduce**
1. Make a new character
2. Go to Cyberware
3. Choose two Cyberlimbs of the exact same making (e.g. two visible cyberlegs)
4. The first installs no problem, the second throws an error
5. See Error

**Expected behavior**
You choose the second cyberlimb for the other 'bodyslot' and it installs

**Screenshots**

![Screenshot 2022-04-10 093727](https://user-images.githubusercontent.com/103354671/162607817-a62f59ba-f647-4764-b48a-7cdd03a557dd.png)

**Character File**
Not necessary. Reproducable with every new character in creation mode

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1 (Build: 19043.1586)

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightlies.
