### ISSUE TITLE
Tab, or button that lists devices currently flagged wireless enabled.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4763]
This is not an issue or anything, would just be nice for book keeping to be able to look at a list of stuff you have toggles wireless on. This could be used to help keep track of the number of slaves devices you have, and how many remain ect.  Maybe this could be a field added to the active commlink or something.

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/milestone/14?closed=1 Was a planned feature, needs someone to take ownership of it for implementation.
