### ISSUE TITLE
Cybersuite Evo Better than human causes crash

### ISSUE THREAD

**Issue by R4gn4rD4nn3skj0ld** [chummer5a/chummer5a#4766]
**Describe the bug**
using the Evo Better than Human cybersuite causes Chummer (5.222.0.0) to crash

**To Reproduce**
1. Create new character
2. Enable book Boston Lockdown in Character settings
3. click on cyberware and bioware
4. click on add cyberware
5. choose cybersuites in dropdown menu
6. check box to show objects above availability
7. click on Evo Better than Human
8. click on OK to add object

**Expected behavior**
Adding the cybersuite adds the corresponding components.

**Screenshots**
Screenshot of failed crash report attached
![github chummer crash](https://user-images.githubusercontent.com/103426991/162735637-54f6fbe4-50d2-4054-a5f2-d6c5ed9970f6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 5.222.0.0]

**Additional context**

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
