### ISSUE TITLE
Diffusion/Infusion of [Matrix Attribute] Not Applying

### ISSUE THREAD

**Issue by CapriciousDream** [chummer5a/chummer5a#4767]
**Describe the bug**
Both the Diffusion and Infusion complex forms will not add themselves to the sheet.

**To Reproduce**
1. Go to Complex Forms of a Technomancer Character
2. Click to add Diffusion/Infusion of [Matrix Attribute]
3. See error

**Expected behavior**
The complex form would allow you to choose a matrix attribute to affect with the ability, and after selection it would appear in the Complex Forms list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222.0

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
