### ISSUE TITLE
PDF Mugshots not sizing correctly

### ISSUE THREAD

**Issue by Aracino** [chummer5a/chummer5a#4770]
**Describe the bug**
On 5.222, if you add a mugshot it clips off of downloaded PDFs and doesn't size to fit in both the main mugshot area and secondary mugshot areas. In previous versions of chummer these sized to fit.

**To Reproduce**
1. Go to mugshots
2. Add a mugshot (doesn't matter if it's primary or not)
3. Download a PDF of your profile
4. Oversized pictures clip off the PDF and take up several pages.

**Expected behavior**
The image should scale to fit the area its in

**Screenshots**
![image](https://user-images.githubusercontent.com/26165932/163346257-defd030c-0462-49f8-a352-aea035f2087c.png)
![image](https://user-images.githubusercontent.com/26165932/163346334-559e899a-31b7-4dbf-85f2-3abfe39bd5c9.png)

**Character File**
The file doesn't matter, and I've heard reports from others having a similar issue

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 5.222

**Comment by Aracino** [comment]
Also appears to be the same in the 5.216 version. May be a windows 11 issue.

**Comment by DelnarErsike** [comment]
Can't seem to replicate this in the latest Nightly, so I'm closing this issue.
