### ISSUE TITLE
No recoil compensation displayed for drone weapon

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4773]
Wanted to reopen this one since the previous post got closed and never reopened once an answer was posted. See 
[Issue 4753](https://github.com/chummer5a/chummer5a/issues/4753) 
If you create a drone and add a weapon mount with a weapon you should be able to see the RC of the gun along with the other stats. In the spot where RC is normally shown is the fire mode perhaps this display is covering the RC? RC for the vehicle should be body+gun recoil per the section below for weapon mounts. Anthro drones wielding guns in hands likely use normal RC based on the "STR" equivalent of the drone. So likely body/3+gun recoil

SR5 p. 176 Vehicle and Drone Mounted Weapons
Vehicle and Drone Mounted Weapons Vehicle and Drone mounted weapons have the advantage of a sturdy platform from which to fire. The vehicle itself has enough mass to absorb the bulk of the recoil created by the weapon. Mounted weapons have Recoil Compensation equal to the Body of the vehicle plus any built in Recoil Compensation of the weapon.

**Comment by DelnarErsike** [comment]
Reopened the original issue and closing this one.
