### ISSUE TITLE
Auto-Generated Issue from Crash: ID 091f6990-8d14-498c-b393-076c4690ebe0

### ISSUE THREAD

**Issue by Hugsaeux** [chummer5a/chummer5a#4774]
### Environment
Crash ID: 091f6990-8d14-498c-b393-076c4690ebe0
Chummer Version: 5.222.65
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 4bfc5bff-ce86-4980-a7a7-da50ed2be674

### Expected behaviour
Adding cyber/bioware works.

### Actual behaviour
Each time after adding cyberarms/legs, chummer would take a long time for spinning icon to disappear from next to the mouse. After adding a cereberal booster, spinning wheel never went away. Tried closing chummer and got this issue.

### Steps to reproduce the behaviour
Create a new character and add ware. This is with the Neon Anarchy custom data. Not sure if that's necessary to replicate.

### Crash Description
Cannot access a disposed object.
Object name:

**Comment by DelnarErsike** [comment]
Should be fixed in 5.222.68.
