### ISSUE TITLE
Consistent crash when adding two cyberlimbs

### ISSUE THREAD

**Issue by Anon5342** [chummer5a/chummer5a#4776]
**Describe the bug**
Adding a pair of cyber limbs will crash Chummer.

**To Reproduce**
1. Make a new character using any rule set (tried Standard and Runnerhub Career Rules).
2. Click through character priorities with any settings.
3. Go the Cyberware & Bioware tab
5. Add two of any of the same type of limb (e.g. two obvious feet, two synthetic arms, two obvious legs).
6. Regardless of which order you attempt to add them (left vs. right), Chummer will crash. Notably, different types which take up the same sort of space will not cause a crash (e.g. synthetic full leg and an obvious full leg are fine, but two synthetic or two obvious full legs will cause a crash).

**Expected behavior**
The second limb to be added should default to the only possible side it can be on, and Chummer should not crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.222.0.0

**Comment by DelnarErsike** [comment]
Known issue, fixed in the Nightly
