### ISSUE TITLE
Chummer crashing when verifying data file

### ISSUE THREAD

**Issue by Tommycore** [chummer5a/chummer5a#4777]
### Environment
Crash ID: f936580b-4dd1-4e09-9dcd-fcd88de4535b
Chummer Version: 5.222.71
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: a5e86d9a-6fbd-41cd-ba52-0a282429ef26

### Expected behaviour
Verification of localised data files. A window popping up with missing strings or a message that all strings are present.

### Actual behaviour
Program crashes.

### Steps to reproduce the behaviour
1. Start Chummer
2. Open Zubehör>Optionen (Tools>Global Options) menu
3. Click `Verify Data File`

### Crash Description
Object reference not set to an instance of an object.
   at Chummer.XmlManager.Verify(String strLanguage, ICollection`1 lstBooks) in C:\projects\chummer\Chummer\Backend\Static\Managers\XmlManager.cs:line 2063
   at Chummer.EditGlobalSettings.

### Additional Commentary
- I'm using the German version of Chummer.
- The Crash Reporter mentions a zip archive with anonymized crash information. The link that is supposed to open the file location is grayed out and there is no zip file in my Chummer folder.
- I also don't have my Chummer installed on drive `C:`. Crash report says `C:\projects\chummer\Chummer\Backend\Static\Managers\XmlManager.cs:line 2063`.

**Comment by DelnarErsike** [comment]
Should be fixed in the latest Nightly.

**Comment by Tommycore** [comment]
Tested with Language set to German and confirmed: Clicking `Verify Data File` no longer crashes the app. Instead, a `results_de-de.xml` was written into the `lang` folder.
