### ISSUE TITLE
Additional Eye Sockets

### ISSUE THREAD

**Issue by Paperknight86** [chummer5a/chummer5a#4779]
The Cyberware "Additional Eye Sockets" seems to be misunderstood. There is a capacity given, but it doesn't make any sense to build it in an eye. These capacity costs seem to be for the case of imbuing it into a cyberskull or other cyberlimbs. Additional to that, does it make more sense to build a cyber eye into the socket instead of otherweise.

**Comment by chummer5a** [comment]
It's a bracket, so it costs capacity for whatever you might want to mount it in. Issue is that the basic cybereye system doesn't have a capacity cost, so it can't be flagged as a child of the eye mount itself.

**Comment by DelnarErsike** [comment]
As far as I'm aware, Chummer already allows you to add Additional Eye Mount to cyberlimbs, so I'm closing this issue.
