### ISSUE TITLE
buying enhancement for initiation

### ISSUE THREAD

**Issue by seppestuyck** [chummer5a/chummer5a#478]
in carreer mode
when i try to buy an enhancement for an initiation, chummer charges 5 karma while street grimoire p139
says its 2 karma

**Comment by HaikenEdge** [comment]
It actually only charges 2, but says it charges 5. It's a confusing quality-of-life issue.

**Comment by chummer5a** [comment]
Yeah, the spend message is using the wrong values. I'm reviewing that
section of code at the moment, it should be fixed in the next patch.

**Comment by seppestuyck** [comment]
ok, thanks :)

**Comment by chummer5a** [comment]
Fixed in 5.177.
