### ISSUE TITLE
Auto-Generated Issue from Crash: ID f37e942e-7c64-4ef0-aada-67f66fb180b7

### ISSUE THREAD

**Issue by Raitzo** [chummer5a/chummer5a#4780]
### Environment
Crash ID: f37e942e-7c64-4ef0-aada-67f66fb180b7
Chummer Version: 5.222.73
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: fcbec999-5508-4c09-a7ce-d69505bf4ebc

### Expected behaviour
To save the file
### Actual behaviour
It saves and crashes

### Steps to reproduce the behaviour
I have a almost ready character and pressed Ctrl S and it comes to this screen

### Crash Description
The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Chummer.CharacterRoster.

**Comment by DelnarErsike** [comment]
Do you happen to have the complete stacktrace instead of just the small part there at the bottom? Or maybe a crash dump?
