### ISSUE TITLE
Chummer5a.222.76 Fading resistance crashes in French

### ISSUE THREAD

**Issue by HySlagh** [chummer5a/chummer5a#4781]
**Describe the bug**
Chummer5a.222.76 crashes when saving the file if a Fading Type in french is selected.

**To Reproduce**
1. Open Shummer5a
2. Go to Options
3. Click on "English (en-US)" next to "Language:" and select "Français (fr-FR)"
4. Press OK, save the options and restart Shummer5a as asked by the application
5. Open Shummer5a again (in french this time)
6. Create a new Sheet ("Personnage" in french), to do so:
7. Select "Fichier"
8. Select "Nouveau personnage"
9. Press "OK" in the "Préférences de création" box that just appeared
10. Press "OK" in the "Préférences de création" box that just appeared
11. Go to "Sorts et esprits"
12. Select a "Tradition", either "[personnalisée]", "Chamanisme [traditionnel]" or "Tradition hermétique".
13. Below, select a type of Fading resistance (Résiste au Drain avec :), for exemple "VOL+ CHA"
14. Observe the value of the Fading resistance being at 0 next to VOL + CHA.
15. Save the file.
16. SEE ERROR, Chummer5a crashes.
17. When restarted, the Fading resistance type has been reset to nothing.

**Expected behavior**
Once "Chamanisme" is selected, the value of the VOL + CHA Fading resistance is automaticaly calculated. Chummer5a does not crash when the file is saved. The columns "Combat, Détection, Santé, Illusion and Manipulation" are created and already filled.

**Screenshots**
See example of configuration before crash. Here, when Chamanisme is selected, the Fading resistance is not calculated and the columns "Combat, Détection, Santé, Illusion and Manipulation" are not created.
![image](https://user-images.githubusercontent.com/88376842/164984657-9c1ba411-5ffe-4e10-9815-ef0531ee3774.png)

If you select "VOL + CHA" in the list.
![image](https://user-images.githubusercontent.com/88376842/164984678-42024197-204f-46c7-b1a3-937b162ad167.png)
Chummer5a.222.76 crashes here if you save the file.

Below, what should appears (taken from the Chummer5a.216.83 and/or Chummer5a.222.0). The fading resistance is automaticaly selected.
![image](https://user-images.githubusercontent.com/88376842/164984572-c15352a5-8c28-4be4-9fe3-2c31deb938d8.png)

**Character File**
No character file needed. The problem is repeatable with any character sheet.

**Desktop:**

- OS: Windows 10
- Chummer5a Version: 5.222.76 (also tested with V5.222.66, same results).

**Additional context**
The current bug does not apply with Chummer5a.222.0.

Thank you,
Feel free to ask me to perform more tests if you need.
Best regards,

Quentin

**Comment by ArchonMegalon** [comment]
Apart from thanking Delnar for fixing all the stuff and putting so much
effort into chummer I want to say to Quentin, that this is a fantastic bug
report. I wish all of them would be that detailed!
