### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by Rhodar21** [chummer5a/chummer5a#4784]
### Environment
Crash ID: 9c9eeb97-8dea-4cfd-bac3-85ddc857f737
Chummer Version: 5.214.0.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: a0730679-1273-4d11-977c-b5cbd3c64083

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment]
This is a very old version of Chummer, it's very likely that the cause of the crash has been fixed since.
