### ISSUE TITLE
Ares Matilda missing std equipment

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4786]
**Describe the bug**
Per the Std Upgrades block the Ares matilda should come with 2 riot shields, UB gren launcher, targeting autosoft and Std weapon mount. When added in chummer all of the above is added except for the std weapon mount.  A couple of "extra" mounts are installed to fit the 3 other stock weapons but there should be an additional empty mount as well. It is a little unclear which variant of the turret should be used here, but I would assume for consistency sake, use the "standard turret remote external" version similar to the steel Lynx

**Comment by DelnarErsike** [comment]
It's assumed that the standard weapon is where the underbarrel grenade launcher is mounted (the riot shields aren't mounted on any weapon mounts, it's just that Chummer works better if weapons like riot shields are put on weapon mounts instead of directly into the vehicle's inventory).
