### ISSUE TITLE
Attribute Improvement Causes Crash

### ISSUE THREAD

**Issue by picturetheory** [chummer5a/chummer5a#4787]
**Describe the bug**
When attempting to apply an Attribute or Attribute Level Improvement via the Improvements Tab, clicking OK after filling out the relevant info causes a crash.

**To Reproduce**
1. Open character in Career Mode
2. Go to the Improvements tab
3. Click Add Improvement
4. Select "Attribute" or "Attribute Level" for Improvement Type
5. Fill in relevant information (Name: "test", Selected Value: AGI, Value 1.00, Minimum 0, Maximum 0)
6. Click "OK"
7. Crash

**Expected behavior**
The character's AGI attribute is increased by 1.

**Screenshots**
[https://i.imgur.com/1hpOB2D.png](https://i.imgur.com/1hpOB2D.png
[10101.txt](https://github.com/chummer5a/chummer5a/files/8595440/10101.txt)
)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222.0

**Additional context**

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
