### ISSUE TITLE
Mortimer of london argentum coat wrong armor value?

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4794]
nightly chummer 5.222.94.0 is reporting the argentum coat as armor 14/+4 and should be 12/+4 unless I am missing an errata or something someplace.

**Comment by DelnarErsike** [comment]
Cannot reproduce with Full House (Point Buy) settings. Are you sure this is not caused by an amend in your enabled custom dataset?

**Comment by bulldogc** [comment]
This can be closed. Turns out i forgot i had gelpacks in the armor... My bad!!
