### ISSUE TITLE
Unable to print character

### ISSUE THREAD

**Issue by RedLion0** [chummer5a/chummer5a#480]
Any time I try to print my character, I'm getting an error. For some reason, it is only on this character, all my others work fine. Debug message is included in the pastebin.

http://pastebin.com/y03uhU7v

**Comment by joha4270** [comment]
Seems to be caused by one the weapons you have. Can you upload your sheet somewhere?

**Comment by RedLion0** [comment]
Oh. Weird. I don't have access to the sheet at the moment, but I just bought some boomerangs with cameras in them and some secure tech arm, leg, and torso plates. I'll try to upload the sheet when I can.

**Comment by RedLion0** [comment]
https://www.dropbox.com/s/63btcb3onokhx2u/Mister%20Grendel.chum5?dl=0

**Comment by RedLion0** [comment]
I deleted my nets, and was able to print my character.
