### ISSUE TITLE
Improper Lifestyle cost

### ISSUE THREAD

**Issue by GoldElite** [chummer5a/chummer5a#481]
When trying to purchase a Middle Lifestyle as a dwarf (+20% LifeStyle cost) with the Dangerous Area (-20% Lifestyle cost) and Special Work Area (+1000 nuyen) qualities, the lifestyle selection windows displays a correct price of 6000 nuyen per month. However, once purchased, the price is changed to 7200 nuyen (thus ignoring the Dangerous Area quality). 7200 nuyen are deducted from the character's funds.

**Comment by chummer5a** [comment]
Fixed in 5.177.
