### ISSUE TITLE
Drone suspension mod does nothing?

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4810]
To reproduce 
Add an ares matilda and note the handling
add suspension (drone) mod
notice no change to drone handling.

Based on RAW, it seems like when adding this mod 1 or 3 version should be chosen, each one providing a new base handling.

**Comment by chummer5a** [comment]
Fixed in https://github.com/chummer5a/chummer5a/commit/eca15b4172cef4ad70351c63240412788b2bcae2
