### ISSUE TITLE
Max Knowledge Skill Rating in Character Setting Cannot Go Up

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#4814]
**Describe the bug**
When in Character Settings, trying to raise Max Knowledge Skill Rating does nothing. If reduced, it cannot be raised.

**To Reproduce**
1. Go to ' Tools > Character Settings '
2. Click on the ' ^ ' button besides the Max Knowledge Skill Rating entry.

**Expected behavior**
Pressing the ^ for Max Knowledge Skill Rating should raise it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222.0

**Comment by DelnarErsike** [comment]
Issue should have been fixed in the Nightly a while ago.
