### ISSUE TITLE
underbarrel flamerthrower seems wrong.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4815]
Add a rifle then rightclick and add under barrel weapon.
select under barrel flamethrower.
The weapon that comes up is statted with some values that don't seem to exist in the book any place. This mod should be a mount that costs 200Y and add 2 to an attached flamerthrowers availability. You should then be able to add a weapon to that UB mod which attaches a flamethrower of  your choice.
See R&G pg 54 Firearm accessories and modifications table. UB flamethrower as flamerthrower +2 and as flamerthrower +200 for avail and cost. Incidentally this should be the same for the UB chainsaw since there is no "chainsaw" weapon but various different chainsaws that could be attached.

**Comment by chummer5a** [comment]
Probably need to rebuild how the accessory works to add a new property like 'allow underbarrel categories' that can include Chainsaws and such, modify the underbarrel selection prompt to check for those properties to add to the list, etc etc, make sure cost handler is included.

**Comment by bulldogc** [comment]
Small update to this, the "stats" that come up as described originally seem to be related to checking German data changes. With those not checked adding UB flamethrower or UB chainsaw costs a fixed 200 or 500 allowing someone to just buy the chainsaw or flamer and just noting its attached to weapon x. A better solution would be to allow it to be added directly to the UB mod as a gear item or something like that.
