### ISSUE TITLE
Shockpad not adding RC

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4823]
add a weapon, then add a folding stock, then a shock pad. The RC calculation seems to ignore the shockpad.

chummer version 5.222.111.0

**Comment by chummer5a** [comment]
Working as intended. Same RC Group. See RG 53 for a list of which accessories don't stack.

**Comment by bulldogc** [comment]
Interesting... Ok 2nd possible bug then, The same version is listing "stock" as a valid mod and points to the folding stock, this mod doesn't seem like it exists though and also does stack with shock pad, should I make up a new bug for that?
