### ISSUE TITLE
Nightly-v5.222.120 Crashing

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#4827]
I enabled all of the books, except the German ones, and the Houserules for allowing extra Positive and Negative Qualities at creation. Also the sub-rule under extra Negative Qualities at creation. I created a Dwarf, set my priorities, and chose the quality Infected Goblin. Chummer closed. I tried everything 2 more times, each time it crashed.

**Comment by chummer5a** [comment]
Closed by https://github.com/chummer5a/chummer5a/commit/deb49396f49cc8eeaaa3ef767dde303056b9d9cf
