### ISSUE TITLE
ranges.xml missing ranges for Carbines

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4829]
```
    <range>
      <name>Carbines</name>
      <min>0</min>
      <short>10</short>
      <medium>40</medium>
      <long>80</long>
      <extreme>150</extreme>
    </range>
```

Ares Stalwart, Colt M23A2, Izom Aztemis, and Krime AKM-SU97 all fall under `<category>Carbines</category>`, but this category does not have its ranges defined in ranges.xml

**Comment by chummer5a** [comment]
Implemented by https://github.com/chummer5a/chummer5a/commit/c1532dfac4191861b1911dafd76875bb7238fc5a
