### ISSUE TITLE
FIXED: Update to 5.222.134 to resolve - Nightly update has stopped working. 

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4830]
Nightly 5.222.132. I am unable to install/restart or clean reinstall via the updater.

![image](https://user-images.githubusercontent.com/86989917/174228718-29ce39ba-a4ca-4f38-868e-383fd8552c0e.png)

**Comment by chummer5a** [comment]
Know issue that was resolved in https://github.com/chummer5a/chummer5a/tree/Nightly-v5.222.134. Requires a manual update to replace the client.
