### ISSUE TITLE
Adding the last possible cyberarm or cyberleg (of identical type) causes Chummer to crash.

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#4831]
**Describe the bug**
Adding the last possible cyberarm or cyberleg (of identical type) to a character fails.

**To Reproduce**
1. Create new character, use setting "Standard". Pick any priorities. (Optional: Pick "Human/Nartaki" metatype)
2. Add cyberware "[Obvious/Synthetic] Full [Arm/Leg]" click "Add & More", pick either option from Left/Right prompt.
3. Add another "[Obvious/Synthetic] Full [Arm/Leg]" (same type and limb as before!), click "Add & More".
4. Chummer crashes.
5. Optional: If you picked "´Human/Nartaki", you can add up to three limbs of identical type (e.g. two Obvious Full Arms, one Obvious Right Arm), but Chummer will crash on adding a fourth.

**Expected behavior**
Chummer should add a second [obvious/synthetic] full arm/leg cyberlimb (if Nartaki: fourth arm).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222

**Additional context**
Adding cyberlimbs of different types (e.g. one obvious full arm and one synthetic full arm) works fine.

**Comment by DelnarErsike** [comment]
Fixed in the Nightly already.
