### ISSUE TITLE
Mysad PP is wonky with essence loss at chargen.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4838]
Chummer Ver 5.222.140

Make new char - I went with Full House - CBADE mysad human. Check Karma cost for increasing special attribs is not reduced with essence loss.

buy 6 PP
Buy 1 std sythetic full arm and 1 std synth full leg
essence/magic drops to 4 as expected, points spent on power points also drops to 4. and available power points drops to 2.

I would expect one of the 2 depending on how the rules are written. Either power points are still capped to 6, but available drops to 4 or points are capped to 4, with 4 avaliable.

**Comment by chummer5a** [comment]
Can't replicate the issue in nightlies, if I understand it correctly. Character with 4 ESS can have 4 power points and 4 MAG.

**Comment by bulldogc** [comment]
Reproduced in 5.22.156 with the following steps. create the above character.
add 6 power points.
add mentor spirit raven with adept power
add mentors mask
add synth full leg left
add synth full arm left
power points remaining on powers page shows 3/3 remaining 0 used.
points spent on common page = 4. 
Total power points remaining should be 7 not 3.

If you remove mentors mask, powerpoints on the powers tab reduce as expected to 2 (should be 4).
Looks like the essence loss on the powers page might be getting doubled somehow, I think it is calculating it using spent power points minus essence loss instead of just how many power points you bought. Likewise the bought points on the common page is factoring essence loss by dropping bought points from 6 to 4.

**Comment by ZeBlackbear** [comment]
Yeah I'm having the same issue. Using v5.222.0
Mystic adept, had 4 mag with 6 essence, bought 2 PP at first and got my adept powers using the 2 PP. I upped my PP to 3 and got cyberware, lowering ess to 5.25 so mag is 3 with PP at 3. but when I went to get more adept powers I found it still said 2 PP there.

Did a quick check and just made a fresh char to see, and yeah start with 4 Mag get 3 PP, assigned powers, got cyberware which lowered ess to 5.25, found adept power page displaying 2 PP with (-1.00) as the powers i assigned where still there.

**Comment by chummer5a** [comment]
Again, cannot replicate the issue as I understand it in current nightlies. Please provide a character, settings file and screenshots to show what you're seeing.

**Comment by bulldogc** [comment]
Created this save on 5.222.181 I have attached the save and the settings file that it uses.
![image](https://user-images.githubusercontent.com/86989917/182601978-8936c581-cadd-448d-ad0d-ca91296674c6.png)
[charfile.zip](https://github.com/chummer5a/chummer5a/files/9251029/charfile.zip)
Notice in the image, essence is 5, bought PP is 5(max that should be allowed) total PP is 4, and should be 5.

**Comment by DelnarErsike** [comment]
So this is kind of working as intended. The key is the house rule where Essence loss does not affect the karma cost of raising special attributes. This means that no matter how much of your special attributes you burn away, you do not get an effective discount on increases to your special attributes thereafter.

The miscommunication is that this extends to Mystic Adept PPs as well… which it should. Buying 5 Mystic Adept PPs' worth and getting 5 PPs despite having burned 1 MAG is an effective karma discount. You should have to buy 1 extra PPs' worth if you want to get 5 PPs. Chummer's issue is not that you aren't getting the right amount of PPs here, it's that it's both not letting you buy 6 PPs and not properly communicating that Mystic Adept PPs, being the extension of MAG that they are, are also covered by this house rule.
