### ISSUE TITLE
Child items in carrer mode can not get plugin

### ISSUE THREAD

**Issue by Stexinator** [chummer5a/chummer5a#4840]
Buy a sensor collor
Try to add visual enhancement to camera

**Comment by chummer5a** [comment]
Can't replicate in nightlies; sensor collar functionally has its capacity consumed by the camera and microphone, camera can add the vision enhancement, collar otherwise doesn't show as having a capacity. .

**Comment by Stexinator** [comment]
![weird](https://user-images.githubusercontent.com/69796777/178415781-c8ed4468-14d9-461e-b881-9556ae3deb74.gif)

I am on 5.222.159 and still can reproduce it
