### ISSUE TITLE
Cyberlimb optimization does not increase Accuracy for combat skills or base Limit for non-combat skills. ( 5.222.144)

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4841]
Per CF87, Cyberlimb Optimization, when taken in pairs, increases both the limit and dice pool for the chosen skill.
Expected behavior is that Accuracy is increased by 1 when Cyberlimb Optimization is taken for a combat skill and that for non-combat skills, a Limit Modifier be added to the Limits list
Neither of these is occurring in the current version of Chummer (v5.222.144)

**Comment by chummer5a** [comment]
Fixing the Accuracy is easy enough, but I don't think we actually directly link Limits to Skills in any way that would allow us to present the modified Limit.

**Comment by binnsr** [comment]
My thought was that it should reflect in the list like gear modifications do:
![image](https://user-images.githubusercontent.com/26882158/177584512-5009a6a7-6363-4caf-af90-50ab09af46a0.png)

**Comment by Teksura** [comment]
It'd be more useful to add it under the Weapons entry for combat skills specifically. 

![Screen Shot 2022-07-23 at 9 25 22 AM](https://user-images.githubusercontent.com/1766631/180613926-c2eb6abb-15a7-4ae0-ad01-83c4ab8c6a2c.png)
