### ISSUE TITLE
Print (STR+P) with career mode characters loads indefinitely and produces empty .pdf files

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4842]
Files in create mode work fine.
Tested in English and German.

Maybe we should introduce a unit test for this.

**Comment by chummer5a** [comment]
What weapon have they got that causes this? Where's it freeezing?

**Comment by JoschiGrey** [comment]
Small update:
Reapplying improvements solves this problem.

**Comment by DelnarErsike** [comment]
Then this is probably a save-specific legacy issue. As much as I don't like telling people to fix issues with Reapply Improvements, the alternative seems like it would be incredibly tedious and potentially cause its own issue. I'll close this for now.
