### ISSUE TITLE
Printing windows can't be closed 

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4845]
![image](https://user-images.githubusercontent.com/69921261/176933703-1d63cbbe-3fd4-4225-8df8-3d711623a3d4.png)
There is no "X" to close the print tab and no right-click context menu is available.

**Comment by DelnarErsike** [comment]
![image](https://user-images.githubusercontent.com/727731/183329979-51a4d917-a41e-458e-a556-5a02bec42ffd.png)

Cannot replicate. The black x below the window border x closes the print window, and a drop-down menu (show in the image) with a Close option can be accessed by clicking the icon in the left corner, just like with all other screens.
