### ISSUE TITLE
Chummer 5.222.0 crashes when adding a 2nd Obvious Full cyberarms

### ISSUE THREAD

**Issue by killertilapia** [chummer5a/chummer5a#4846]
**Describe the bug**
Chummer 5.222.0 crashes when adding two Obvious Full cyberarms.

**To Reproduce**
1. Create a character
2. Add two Obvious Full Arms cyberlimbs.

**Expected behavior**
We should be able to add two Obvious Full cyberarms.

**Screenshots**
![image](https://user-images.githubusercontent.com/5240924/177113736-69af2400-fa74-4ae1-92d1-237af818657c.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chummer 5.222.0.0

Additional Context:
Oddly enough, adding a cyberlimb leg or synthetic arm doesn't seem to trigger the crash.

**Comment by Yurek1** [comment]
I am having this issue with adding _**any**_ cyberware/bioware that's applied to individual limbs. Legs, arms, bioware claws... all of it.

**Comment by chummer5a** [comment]
This has been resolved in nightlies.
