### ISSUE TITLE
Chummer crashes when adding second cyber-arm

### ISSUE THREAD

**Issue by StreetCaptainOfPresidents** [chummer5a/chummer5a#4847]
**Describe the bug**
Chummer Crashes when adding a second cyberarm.

**To Reproduce**
1. Create new character sheet in Create mode
2. Go to Cyberware & Bioware
3. Add "Obvious Full Arm", select Left or Right
4. Attempt to add second Obvious Full Arm
5. Program crashes before being able to select side

**Expected behavior**
I expected to be able to have two Obvious Full Cyberarms. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108839599/177654044-c740b9cf-1c55-4d2f-821c-7bdf04aa402a.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1 (OS Build 19043.1766)

**Additional context**
[Chummer.2022-07-06_16-18-55.txt](https://github.com/chummer5a/chummer5a/files/9058969/Chummer.2022-07-06_16-18-55.txt)
[Chummer.2022-07-06_15-58-37.txt](https://github.com/chummer5a/chummer5a/files/9058970/Chummer.2022-07-06_15-58-37.txt)
[Chummer.2022-07-06_14-34-24.txt](https://github.com/chummer5a/chummer5a/files/9058971/Chummer.2022-07-06_14-34-24.txt)

**Comment by chummer5a** [comment]
Fixed in nightlies.
