### ISSUE TITLE
Crashing when I attempt to add two seperate Bioware Claws

### ISSUE THREAD

**Issue by Lwmons** [chummer5a/chummer5a#4851]
**Describe the bug**
After adding "Claws, Retractable(Hands)" to my character, it prompted me to choose a side to attach them to. I picked "Left". Upon attempting to add a second one for the Right side, the program crashes, without offering a prompt to choose the side

**To Reproduce**
1. Go to "Cyberware & Bioware"
2. Select "Add Bioware"
3. Select "Claws, Retractable (Hands)" and hit "OK"
4. Select "Left"
5. Select "Add Bioware"
6. Select "Claws, Retractable (Hands)" and hit "OK"

**Expected behavior**
After selecting the first claw and selecting the Left hand, I should have been able to do it again for the Right hand

**Screenshots**

**Character File**
[Catra.txt](https://github.com/chummer5a/chummer5a/files/9079967/Catra.txt)

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - Version 10.0.1.19044

**Additional context**
[Chummer.2022-07-10_14-48-25.txt](https://github.com/chummer5a/chummer5a/files/9079954/Chummer.2022-07-10_14-48-25.txt)

**Comment by chummer5a** [comment]
Fixed in nightlies.
