### ISSUE TITLE
Crashes when trying to enable Critter tab via Improvements in Career Mode

### ISSUE THREAD

**Issue by RowanTheFox** [chummer5a/chummer5a#4852]
**Describe the bug**
The latest stable release of Chummer 5 crashes when I try to enable to critter tab via Improvements in Career Mode. This happens on all character sheets. 

**To Reproduce**
1. Go to Improvements tab in Career mode
2. Click on Add Improvement
3. Scroll down to Enable Critter Tab on the drop-down menu

**Expected behavior**
Expected behavior was enabling of the Critter tab

**Screenshots**
![292608796_582068600108511_9015529943152296535_n](https://user-images.githubusercontent.com/109052972/178179743-f9177556-3aa5-4f59-a685-58b41a0ded61.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Additional context**
None

**Comment by chummer5a** [comment]
Resolved in nightlies.
