### ISSUE TITLE
Redliner and Cyber-Singularity Seeker not working properly.

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#486]
The program seems to recognize that it should be doing something to stats, but not actually adding anything in.

Redliner does properly subtract boxes, though.

https://drive.google.com/folderview?id=0B-mC2hIA5p-xbkNtOWNzRUhuc1E&usp=sharing (Not the most elegant way of sharing, but I tried one where I added Redliner in Career, didn't get the boost that I could see. Haven't tried adding Cyber Singularity in Career yet.)

**Comment by joha4270** [comment]
Fixed in 546958c, might be in the stealth fix if you use autoupdate, or the nightly. Otherwise it will be fixed by next version
