### ISSUE TITLE
career mode: nuyen are not added, crashes when giving income (nightly 5.222.161)

### ISSUE THREAD

**Issue by o8livion** [chummer5a/chummer5a#4865]
**Describe the bug**
when saving a marked as created and after throwing the dice, the amount of nuyen are not transfered. they are, however, listed in the "Karma and Nuyen" tab.
if i try to create an additional nuyen income, as soon as i press okay, chummer crashes.

**To Reproduce**
1. create new charakter
2. check "mark as created" box and save
3. put in any number for the starting nuyen diceroll

**Screenshots**
![nuyen bug 1](https://user-images.githubusercontent.com/14218286/179426259-41242447-a8c0-4ca0-b1e8-a8c065184b24.jpg)
![nuyen bug 2](https://user-images.githubusercontent.com/14218286/179426260-c8013917-500b-4947-ba55-5f77d9aaa5cf.jpg)

**Character File**
[Strike.zip](https://github.com/chummer5a/chummer5a/files/9128638/Strike.zip)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 5.222.161

**Additional context**
[o8livions standards.zip](https://github.com/chummer5a/chummer5a/files/9128640/o8livions.standards.zip)
![global settings](https://user-images.githubusercontent.com/14218286/179426373-5f6fbf4f-4012-43b2-b97e-311bf823ea32.jpg)
[chummer_crash_133025683812552049.log](https://github.com/chummer5a/chummer5a/files/9128644/chummer_crash_133025683812552049.log)

**Comment by DelnarErsike** [comment]
I believe this was fixed in 73257c963ce922ded914f4536cab4091200bbb7a.

**Comment by o8livion** [comment]
ok, yes, the health category spirit is there.
but sorry to put it out again: the tradition name is still missing =)
