### ISSUE TITLE
Discord Bot and Website

### ISSUE THREAD

**Issue by charmscale** [chummer5a/chummer5a#4867]
Would anyone who is working on this project mind if I made a discord bot and website combo that uses chummer files? Basically, the idea is that you'd be able to upload your chummer character sheet to the website, and then use commands in discord to roll skill checks, summon spirits, and stuff like that.

**Comment by ArchonMegalon** [comment]
We would not mind at all. If you want you can build upon this api from the
sinners-plugin inside of chummer.

https://chummer-beta.azurewebsites.net/swagger/index.html

Trying to revive it for a couple of weeks now. OAuth works already kinda...

**Comment by charmscale** [comment]
I'm building the discord bot first, but I'll be sure to check that out when I get to the website part.

**Comment by ArchonMegalon** [comment]
Chummer also implements an url-handler (thats what the chummer-controller with o and open is about, so you can directly open chummer from the website (or discord or whatever program points to chummer:://
