### ISSUE TITLE
selfmade spells (and spirits)

### ISSUE THREAD

**Issue by o8livion** [chummer5a/chummer5a#4868]
**Is your feature request related to a problem? Please describe.**
Hello! As in 4th edition there has been the rules to create own spells, and 5th edition is more or less 4th edition with successlimits, can you implement the option to crate own spells?

**Describe the solution you'd like**
The option to create a spell, like "Vacuum". As a manipulation, Areaeffect, LOS, the toolbox in fourth edition said (i think)...
Manipulation +2, Areaeffect +2, Manaspell -1, specific use -1 to -3. something like that, i am sorry, i lost my streetgrimoire 4th edition, otherwise i would be sure about the numbers. Yes, it would lead to OP spells, but it's always the GMs decision to allow it anyways.
As for spirits, i thought about giving them specific powers, like shape [element]...

**Describe alternatives you've considered**
Or to copy one existing spell and change the name and DV. For example "Inflict Desease" to "Force Diarrhea" or "Laxative" (1 time use, DV-3 instead of -2).

**Additional context**
One of the players thought loudly about a spell that would enforce capticves to "release" what they tried to hide by swallowing.

Thank you.

**Comment by chummer5a** [comment]
Custom content can be created using the customdata system. https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files The simplest route for creating new items is to find an item that's close to what you want to do in the data files and make a copy of it.
