### ISSUE TITLE
elemental weapon not working

### ISSUE THREAD

**Issue by JinstBF** [chummer5a/chummer5a#4869]
**Describe the bug**
The adept power elemental weapon is visible in the power list but choosing it results does nothing. (the required weapon focus is in the inventory, bound and also equipped.)

**To Reproduce**
1. Go to 'Street gear'
2. Click on 'Add Gear'
3. Search for 'weapon focus'
4. Click on focus and check box in the 'bonded foci' tab
5. Go to 'Adept Powers'
6. Click on 'Add Power'
7. Search for 'elemental weapon' and highlight it
8. Click on 'OK'
9. Nothing gets added

**Expected behavior**
The adept power should be added to the list of bought adept powers and should cost 0.5 Power Points

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.222.0

**Comment by chummer5a** [comment]
Resolved in nightlies.
