### ISSUE TITLE
Astral initiative?

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#487]
Unsure here because sample characters vary. The rules on page 314 (core book) says astral initiative dice is +2d6 (3d6) total. 
Sample character "street shaman" has 3d6, the "occult investigator" has 2d6. (Combat mage doesn't say)
See also discussion here:   http://forums.shadowruntabletop.com/index.php?topic=22486.0

Anyway; Chummer says Astral Initiative is 2xIntuition +2d6, I think it should be 2xIntuition +3d6.

Thank you for a fantastic character generator. I'm impressed every time I use it.

**Comment by Fightbackman** [comment]
No it is clearly definied as Intuituon +2d6.
Look at the pages about astral attributes.

**Comment by cfresquet** [comment]
Um, the chart on page 314 says:

Initiative Dice +2D6 (3D6 total)

**Comment by chummer5a** [comment]
Character Creation Chapter, p. 101: INT x 2 + 2d6
Initiative Attribute Chart, p. 159: INT x 2 + 2d6
Astral Attribute Table, p. 314: INT x 2 + 3d6

Until I get an errata or official clarification otherwise, I'm going to stick with 2d6.
