### ISSUE TITLE
Why have No Future and Krime Katalog been permitted for 5e Missions?

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#4870]
Why have No Future and Krime Katalog been permitted for 5e Missions in Nightly-v5.222.168?

The 5e SRM FAQ (last version is 1.3) section 1 lists the sourcebooks PERMITTED in Missions, if they are not listed the content cannot be used - No Future and Krime Katalog are not listed.

The 6e FAQ guide does list No Future and Krime Katalog - they are 6e missions sourcebooks not 5e. 

The default 5e Missions SRM rules should NOT permit  No Future and Krime Katalog - i any character that uses content from these books is not missions legal. If someone want to use these manuals they should create their own Customdata directory, and leave the default definition alone.

Please remove No Future and Krime Katalog from the standard Mission Rules.

**Comment by Lochabar** [comment]
It looks like this fix was back leveled in nightly 5.222.183. "No Future" and "Krime Catalog" are once again permitted for Missions and the separate customdata directory to activate them is no longer present.

**Comment by ArchonMegalon** [comment]
Guys, make your mind up... ;)

<img width="664" alt="image" src="https://user-images.githubusercontent.com/11421547/183244360-13600fbb-e662-4c87-8103-6ce62daec5d7.png">

**Comment by DelnarErsike** [comment]
Yup, the key point here is that the SRM Rules in Chummer5a are synced to 1.4, not 1.3, as shown by the rules' version number. And in the 1.4 Addendum, Krime Katalog and No Future are allowed, though some content from each of them is altered or banned.

**Comment by Lochabar** [comment]
The thing is, v1.4 is transferring to 6e
- amongst other things Neo-Tokyo rules are eliminated
- Section 4 states the setting is Seattle 2081
- Section 5 (Character Creation) has a link to Resources that open to the 6e page
- Appendix A eliminates Prime Runners and states "No, it’s not possible to carry (characters) from previous editions"

So v1.3 is the last set of rules for 5e. Mission rules should not be allowing 6e books into 5e.

**Comment by DelnarErsike** [comment]
As I said before, the latest rules for Shadowrun Missions for SR5e are the 1.4 Addendum for SR5e, not to be confused with the 1.4 FAQ for SR6e. I have attached the PDF that they've pinned to their official Discord server's channels.
[Missions_SR5_Guide_v1.4.pdf](https://github.com/chummer5a/chummer5a/files/9275053/Missions_SR5_Guide_v1.4.pdf)

Please leave this issue closed. As far as the admin of SRM are concerned, the 1.4 Addendum rules are the latest for SR5e, even if the nomenclature is confusing and the distribution of the Addendum rules has been less-than-stellar.
