### ISSUE TITLE
Prototype Materials not working correctly

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4872]
> This quality allows the player to take another rating of the Special Modifications quality, even if they already had reached the  max  rating  of  2. 

After taking the Prototype Materials quality, I am still not able to take a 3rd rating of Special Modifications. Looking at the data files, it appears that Prototype Materials is incorrectly providing the same bonus as Special Modifications itself rather than increasing the rating Limit of Special Modifications from 2 to 3.

**Comment by JoschiGrey** [comment]
Gonna be honest I don't like how this quality works.
I don't think a quality can modify the ranks of another quality atm.

The easy way to implement this is to just increase the Karma cost of the Prototype Materials by the cost of Special Modifications to directly include it.
This would work for most cases, but could be confusing to players who know how the quality works and expect it to cost 5 Karma.
