### ISSUE TITLE
Weapon Reach cap not being respected

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4873]
Core p. 186:

> Weapons with this feature have a Reach rating between 1 and 4.

While this does stack with natural reach such as that from a Troll or Elongated Limbs, Chummer incorrectly allows weapons modded via Special Modifications to have reach ratings greater than 4.

**Comment by chummer5a** [comment]
Hmm, I don't know if I agree with that read, but it's implementable. Recommend a new option that can either uncap it or set an integer. Ghetto workaround would be to do it in data with something like 

```xml
      <required>
        <allof>
          <weapondetails>
            <reach operation="lessthan">4</reach>
          </weapondetails>
        </allof>
        <oneof>
          <specialmodificationlimit>1</specialmodificationlimit>
        </oneof>
      </required>
```
