### ISSUE TITLE
Requesting support for the creation of Warformed and Chimeric critters

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4875]
**Is your feature request related to a problem? Please describe.**
It's frustrating trying to create chimeric or warformed critters in Chummer. There is no support for chimeric powers, and Warformed isn't even possible to do

**Describe the solution you'd like**

For Chimeric Critters, I think the ideal solution might be to add a bunch of Critter Powers and call them all Chimeric Enhancements. 

Warformed gets tricky because Critters are generated in Career mode, but The obvious answer of "Use existing Prototype Transhuman functionality" only works in Create. The best I can think is when creating the critter, turn on the metavariant dropdown so we can select Warformed there. This would generate the critter in a sort of create mode with ignore rules on so you can add the protorype transhuman stuff, and then save it into career.

**Describe alternatives you've considered**
I considered a way to add bioware in career mode and have it count towards Prototype Transhuman, but I don't know how viable that sort of change to the functionality of the existing thing even is.

**Comment by Stexinator** [comment]
They are added in the nightly

**Comment by Stexinator** [comment]
https://github.com/chummer5a/chummer5a/pull/4793

**Comment by Stexinator** [comment]
For the warform bonus you have to add
      <bonus>
        <biowareessmultiplier>90</biowareessmultiplier>
        <enabletab>
          <name>critter</name>
        </enabletab>
        <genetechcostmultiplier>80</genetechcostmultiplier>
        <genetechessmultiplier>90</genetechessmultiplier>
        <enabletab>
          <name>critter</name>
        </enabletab>
      </bonus>
      
  to a critter. You might also do it as a quality

**Comment by Teksura** [comment]
The awkward thing for Warformed is more the "1 essence worth of free Bioware" which doesn't really work in Career mode. Sure you can technically give them a 7th point of essence to be burned or just load them up with Essence Anti-hole, but that can have other issued with critters that have a Magic or Resonance score.

**Comment by Stexinator** [comment]
Magic or Resonance Critter cannot be Warformed

**Comment by Teksura** [comment]
> Magic or Resonance Critter cannot be Warformed

I just read through the entire section on Warformed critters and couldn't find anything to confirm this. Where did you find that rule?

**Comment by Stexinator** [comment]
Page 186 Ghost Hounds, first sentence. Thats how I read that

**Comment by Teksura** [comment]
> Page 186 Ghost Hounds. Thats how I read that

We're talking about Paracritters and Technocritters becoming Warformed. Paracritters and Technocritters are animals that can occur naturally in the wild without any intense breeding required to breed their awakened abilities into them. Nobody went and bred rats together until they came up with Devilrats.

Ghost Hounds are their own thing, specifically bread dogs (and only dogs, apparently) who have the Magic Sense or Astral Perception adept power. 

> In the text in front of the warcritter rules they distinguish between agumented, warform and paranormal critter P-176
p.174 distinguished warform from chimerics

I'm sorry, but I need a little more than "read the pages you just read and found nothing on".

**Comment by Stexinator** [comment]
P.174 Unlike chimerics, their DNA is only derived from their own species, but with the most desirable traits selected and weaknesses removed.
P.176 Time saved in training and the sheer effectiveness of their performance makes them among the most desirable of security animals, even compared to augmented or paranatural versions. 

Catalyst is well know for ambiguity, if you dont read it the way I do thats fine. Sometimes it is also hard to tell if this should just be fluff or be actual rules

**Comment by Teksura** [comment]
Had a thought for how Warformed could be added.

When using the New Critter option, add a textbox to "Create Warformed Critter".

When ticked, this generates a critter in Create mode, rather than career. 

Apply a quality: Warformed.

Warformed quality will:
- Apply Domesticated Critter Power
- Apply BiowareEssCost improvement with a value of 90.
- Apply genetechessmultiplier improvement with a value of 90.
- Apply genetechcostmultiplier with a value of 80.
- Enable Prototype Transhuman
- Apply necessary improvements to increase the metatype maximum of all attributes by 1.

The critter should also be given 2 Attribute points.


This leaves us with the issue of NuYen necessary to actually buy the Augmentations. While it is technically possible to just grant the critter an unreasonable amount of NuYen at chargen to cover this, I'm wondering if it is feasible to simply not care if the critter has negative money when it moves to career, or if the process can simple reset their NuYen to 0 when they enter Career, maybe by making that their starting cash so we have a record of how much it cost to make them in the first place.


I'm pretty confidant I can handle the XML side of it. But that's about it.

**Comment by Stexinator** [comment]
Hey, I cannot find, that all maximum attributes should be increased by 1

**Comment by Teksura** [comment]
> Hey, I cannot find, that all maximum attributes should be increased by 1

Howling Shadows page 176:

> The genetic stock they are created from represents the best of their breed, so two attributes are increased by 1 over the base species.

It is necessary to increase the maximum so you can actually *spend* those 2 attribute points, since critters are set to have their minimum and maximums equal their listed attributes.
