### ISSUE TITLE
Sort bars in Vehicle selection sorts values wrong.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4876]
If you goto add vehicle then browse, then click one of the fields to sort, it sorts multiple digit fields wrong.
For specific example
add vehicle
select boats
brows tab
click armor to sort by armor vlaue highest to lowest.
The it sorts 10 first than 12 14 ect. It might be sorting the fields as a string and not as an int possibly.

**Comment by chummer5a** [comment]
Implementing natural sort not so hard, but need to refactor how the binding works since datagridviews can't have custom sorting when directly bound.

**Comment by chummer5a** [comment]
https://gist.github.com/chummer5a/474b26380b0d111591fdd9d035689f8d works, but not sure how to fix the dgv sorting.
