### ISSUE TITLE
issues applying vampire quality

### ISSUE THREAD

**Issue by Malkleth** [chummer5a/chummer5a#4878]
Applying vampire to a human mage seems to cause issues. The list of critter powers is empty, probably an xml problem.

The only power listed is Terrorscape, which is also the only power with this:
"<quality>Infected: Vampire (Human)</quality>"

How would I go about fixing this? I can certainly do a PR easily enough if someone can tell me how these data entries should be laid out.

**Comment by chummer5a** [comment]
Infected optional powers are generally gained as qualities. Not sure why I built it that way originally, probably critter powers didn't support the requirements system at the time?

**Comment by Malkleth** [comment]
Not sure what is causing Chummer to fail when trying to save these files then, there's def. some kind of crash associated with that quality

**Comment by chummer5a** [comment]
There is a known crash with natural weapons in the milestone build that has since been patched in nightlies.

**Comment by Malkleth** [comment]
this seems to be resolved by the above fix
