### ISSUE TITLE
Crashes with adding second of same Cyberware

### ISSUE THREAD

**Issue by skybolt226** [chummer5a/chummer5a#4887]
There is a crash when you try to add a second identical Cyberware item. For example, if you have added a Synthetic Full Arm (left), then it will crash if you try to select another Synthetic Full Arm with the intention of putting it into the right arm slot. The program crashes after the "ok" button is pressed with the item selected out of the "Select Cyberware" menu.

Running version 5.222.0 on Windows 10, and happened to a friend on the same version/OS.

**Comment by JoschiGrey** [comment]
I think this is already fixed in the nightly builds.

**Comment by Reagent-52** [comment]
I'm experiencing this issue too but there's no option to update chummer. It's telling me it's fully up to date. Do i just need to redownload?

**Comment by skybolt226** [comment]
> I'm experiencing this issue too but there's no option to update chummer. It's telling me it's fully up to date. Do i just need to redownload?

Version 5.222.0 is the latest stable release, so chummer itself wouldn't let you update past that. The nightly builds are separate. You can get them in the releases section if you want them.
