### ISSUE TITLE
Red Mage IG options not available

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4890]
**Describe the bug**

RED MAGE RULES
•  Cannot summon Plant spirits.
•  Gain +2 to summon Beast Spirits.
•  At  initiate  grade  2,  may  learn  the  Attune 
Animal ritual as if they were an adept.
•  At  initiate  grade  4,  gains  the  Totem  Form 
(Animal) ability.

At IG2, a Red Mage Magician is unable to learn the Attune Animal ritual.

At IG4, a Red Mage Magician is unable to select the Totem Form Metamagic

**Comment by chummer5a** [comment]
Free bonuses granted by initiate grades needs some implementation work, easiest workaround would be to add it as a quality with prerequisites.
