### ISSUE TITLE
Cyberlimb Optimization In Modular Limbs Stuck on Select Skill Box

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4893]
**Describe the bug**
When you have Modular Limbs with Cyberlimb Optimization, attaching the modular second modular limb creates a popup asking you to select again the skill bonus of Cyberlimb Optimization. This box is impossible to dismiss, and causes Chummer to essentially lock up entirely.

**To Reproduce**

Create character with modular Cyberlimbs

Add Cyberlimb Optimization to each Limb, For the sake of example, let's select Unarmed Combat here.

In Career mode, attempt to equip the modular limb.

See Error.

**Expected behavior**

Ideally, attaching the limb should not create any popup at all asking about the Cyberlimb Optimization Skill selection. That information is already in the limb.

**Character File**
[Cyberlimb Optimization Test Character.chum5.zip](https://github.com/chummer5a/chummer5a/files/9356195/Cyberlimb.Optimization.Test.Character.chum5.zip)

**Desktop (please complete the following information):**
 - OS: OSX, via Wine

**Additional context**
The popup has actually been an issue for a while now, but it's only fairly recently that the popup no longer can be dismissed.

**Comment by chummer5a** [comment]
Flagging as a showstopper mostly as I think this is part of a larger issue with the bonus system causing forms to no longer respond to active thread.
