### ISSUE TITLE
Crash adding second cyberlimb

### ISSUE THREAD

**Issue by fjeneau9** [chummer5a/chummer5a#4897]
**Description**
Chummer 5 crashes when adding a second 'Obvious Full Arm' under 'Cyberware & Bioware.'

**To Reproduce**
Under 'Cyberware & Bioware tab
-> Add Cyberware
-> Choose 'Obvious Full Arm'
-> Select 'Left' or 'Right'
-> Add Cyberware
-> Choose 'Obvious Full Arm' a second time (crashes at this point)

**Expected behavior**
The window that asks you to choose left/right arm should have popped up

**Screenshots**
![image](https://user-images.githubusercontent.com/51454664/186167541-3b9050f1-ea29-4bab-b74a-9475791fa98d.png)

**Character File**
[streetSam.txt](https://github.com/chummer5a/chummer5a/files/9402791/streetSam.txt)

**Desktop:**
 - OS: Windows 10 Home - build 19043.1889
 - Chummer Version: build 222

**Comment by chummer5a** [comment]
Resolved in nightlies.
