### ISSUE TITLE
Karma Error

### ISSUE THREAD

**Issue by Eadinize** [chummer5a/chummer5a#4898]
The positive karma is at 3 by default despite there not being any Positive Qualities other than the racial Low-Light Vision from being an Elf
Im using Windows 1
![Screenshot (13)](https://user-images.githubusercontent.com/80430971/186479865-90c3e92f-2827-401e-b5c8-330213cab9d0.jpg)

**Comment by chummer5a** [comment]
Can't reproduce it. Please provide the file.

**Comment by DelnarErsike** [comment]
Closing this issue due to lack of response (and also because multiple milestone versions have come out since).
