### ISSUE TITLE
Wakyambi Intuition

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#490]
Elf variant wakyambi should have 2/7 Intuition. (page 104 Run faster).  They only get 1/7. Sucks a bit having to pay 12 karma and not getting the extra attribute point...

Thanks again for a fantastic character generator.

**Comment by chummer5a** [comment]
Fixed in 5.177. Otherwise you can grab the nightly build which should be arriving in the Releases page shortly.
