### ISSUE TITLE
Qi Focus (any known fix/workaround?)

### ISSUE THREAD

**Issue by marioinfinity** [chummer5a/chummer5a#4908]
**Describe the bug**
When adding a Qi Focus in gear, and bonding it, the calculation for times four doesn't translate to the Power under Adept Powers. It also seems to simply apply a negative PP Total as well. [see below on my note; i know this is been an issue so looking for a workaround/hack for it]

**To Reproduce**
1. Go to gear and add a qi focus; rank 4
2. Click on the bonded checkmark thing, and select like Pain Reducer
3. Go to Adept Powers and you will see Pain Reducer as level 1 with a negative PP total

**Expected behavior**
Pain Reducer is an easy one; .5pp/lvl - so a Qi focus of Power 2 should be level 1 and a power of 4 should be level 2

**Screenshots**

--------------------------->>>

I understand that Qi Focus / Powers (using google fu) has been broken for a while. Is there any fix for this thats somewhat creative?

Unlike gear, qualities, etc Adept Powers don't seem to have a "get for free" button so I can't even seem to - bypass - this problem. Is there a quick edit somewhere to let me make them free? That'd be a good hack to make them work.

Thanks

**Comment by chummer5a** [comment]
Unable to replicate in nightlies.
