### ISSUE TITLE
Karma error when breaking skill groups

### ISSUE THREAD

**Issue by VE6CPU** [chummer5a/chummer5a#491]
If I have a character with a skill group and I have both the check boxes under options/optional rules and house rules, then I break a skill group and add skill points to it, after I save a reload the character the karma calculation in the bottom left corner is wrong.  I'm running version 0.5.176 and can send a chum5 file if needed.

**Comment by joha4270** [comment]
Skills are broken, several issues mention the related problems, rewrite in progress...

**Comment by joha4270** [comment]
This should be fixed in the latest nightly
