### ISSUE TITLE
Unable to Print PDFs

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#4911]
**Describe the bug**
The PDF loads in the tab, but the buttons to print are grayed out, and mousing over them produces a hovering hourglass.

**Screenshots**
Below screenshots show comparison between 5.222.215 and 5.222.214. In the .114 build, the Print and Save as PDF buttons function as normal and function as expected. In .115 however, the buttons are grayed out and inaccessible. 

![Screen Shot 2022-09-09 at 11 23 47 AM](https://user-images.githubusercontent.com/1766631/189418762-c9bffa3f-147a-44e0-b622-e0378ab82063.png)
![Screen Shot 2022-09-09 at 11 25 59 AM](https://user-images.githubusercontent.com/1766631/189419081-de11351f-5547-4c23-842d-e644552d42e2.png)

**Desktop (please complete the following information):**
 - OSX Via Wine/Crossover

**Comment by Teksura** [comment]
Issue still present as of 5.222.231

**Comment by Teksura** [comment]
Requested Character Files:

[Trash Panda.chum5.zip](https://github.com/chummer5a/chummer5a/files/9622068/Trash.Panda.chum5.zip)
[Jinx.chum5.zip](https://github.com/chummer5a/chummer5a/files/9622073/Jinx.chum5.zip)


Trash Panda is done with the Chrome Company settings and amends, Jinx should be just default Full House.

**Comment by DelnarErsike** [comment]
Still can't replicate. Both when opening up the characters for printing after opening for editing and when opening them up directly for printing, the buttons work properly after the sheet is loaded in. Also note that while you noticed the difference between .214 and .215, there were no changes between those versions that affected any code used by the printing form in any way.

So between those things, I think this is a machine-specific bug here, potentially a Wine/CrossOver-specific one.

**Comment by hellesvik** [comment]
I have this issue on Linux using Wine.
## Workaround
A workaround for Wine is to use Winetricks -> "Select the Defaiult prefix" -> "Install a Windows DLL or component" -> Install Internet Explorer 8.  

Likely, installing Foxit or Adobe to the same Wine Prefix as Chummer is installed in will also work.

## Hypothesis
From [here](https://github.com/chummer5a/chummer5a/blob/761f566005c6c8da57ce471832c6dc7b5260d12a/Chummer/Forms/Utility%20Forms/CharacterSheetViewer.cs#L420), we see that wkhtmltopdf is used to print PDF by default, but the system will use either Microsoft Print to PDF, Adobe PDF or Foxit PDF instead if available.
Installing Internet Explorer 8 will include probably Microsoft Print to PDF to our Wine Prefix, then Chummer will use this to print the PDF.
