### ISSUE TITLE
Saving character as career sends them into negative karma

### ISSUE THREAD

**Issue by Malkleth** [chummer5a/chummer5a#4918]
**Describe the bug**
Saving character as career sends them into negative karma

**To Reproduce**
Load .chum5 pre-career provided
Save as career (5.222.215.0)

**Expected behavior**
Character has correct starting karma, or overspending reported correctly

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

[cam - bug report.zip](https://github.com/chummer5a/chummer5a/files/9591044/cam.-.bug.report.zip)

**Comment by Malkleth** [comment]
note that we used a custom xml file to build our characters on 1,000 karma

**Comment by DelnarErsike** [comment]
As of the build that will become 5.222.227, I cannot replicate this issue. Exporting the attached character into career mode does not alter their karma total compared to what they have at character creation. I used the Full House (Point Buy) setting and ticked the box to ignore character creation rules; the character had -261 karma in character creation, and after exporting to career mode, they have -261 karma.

**Comment by Malkleth** [comment]
I'll check it again when .227 is out, but I just replicated on .226

**Comment by DelnarErsike** [comment]
If you can replicate it with your special settings and I can't with Full House (Point Buy), it's likely something to do with the settings you're using. Please upload them.

**Comment by Malkleth** [comment]
To be clear all I did with this file is use the chummer settings to set the karma limit from 800 to 1000. However I have attached it regardless. Note that this wasn't my character, I replicated someone else's issue who did the same thing
[Full House Point Buy 1k.zip](https://github.com/chummer5a/chummer5a/files/9629637/Full.House.Point.Buy.1k.zip)

**Comment by DelnarErsike** [comment]
When loading the save with the current Nightly, Chummer says that the character is 13 over their allocated karma limit. There may have been something off about your Chummer install, if you're somehow getting it to show up as not over that limit. The way character settings work in Chummer right now means that I should see the exact same thing you do re: karma costs, and the only way that doesn't happen is if you have some external modifications to Chummer that I don't.

**Comment by Aturas** [comment]
![image](https://user-images.githubusercontent.com/38516277/192069863-2dc2ad74-25a8-4ece-bce9-885a02978a06.png)
Picture from Create Mode, 
![image](https://user-images.githubusercontent.com/38516277/192069909-f1012a51-567f-4c5f-8f1d-5698f735c1f7.png)
Going to Create, no other changes
[Cam the Ork v2.pdf](https://github.com/chummer5a/chummer5a/files/9637509/Cam.the.Ork.v2.pdf)
