### ISSUE TITLE
Improved Ability (skill) (Exotic Melee Weapon (Monofilament Whip)) not functional.

### ISSUE THREAD

**Issue by JohnBlack687** [chummer5a/chummer5a#492]
With 6 levels of the Adept Power: https://gyazo.com/140ad4aff84eab9bfb2a17fbdf675abf

And 8 Agility: https://gyazo.com/cddb203d9003c9422b444153aa79c4dc

I should have 20 dice in the whip, but instead it's as if the ability didn't take place: https://gyazo.com/930214587d81d5ee9a7aaeb9fd6ddeac

**Comment by JohnBlack687** [comment]
Also, I know the rule for Improved Ability states that you can't exceed current skill level * 1.5 for improvement, but this error still persists at all power ratings for the power.

**Comment by chummer5a** [comment]
There's an existing issue with skills and adept powers. It's currently getting rewritten; as is, I don't think Exotic weapon proficiency works with the improved ability power, due to the way it's formatted.
