### ISSUE TITLE
Ware in newest nightly (5.223.5) does not appear

### ISSUE THREAD

**Issue by AtrumChalybs** [chummer5a/chummer5a#4928]
When opening the cyberware or bioware purchasing screen, both are completely empty. This happens in both house ruled versions and using the Standard character settings file.
Character generation or career mode does not matter.
This now extends to 5.223.6 as well

**Comment by DelnarErsike** [comment]
Fixed in b8630d72a3c0dca9ab05ebb1a4fe1b4885097534.
