### ISSUE TITLE
Add option to Character Roster to group characters into custom groupings.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4930]
Would be nice to be able to create our own groupings in the character roster similar to the "favorite Characters" section but with custom fields so we can sort them by games we play in ect.

**Comment by chummer5a** [comment]
The current recommended method for this as-is is to configure a watch folder in Global Settings, and make subfolders for each campaign/folder you want, and put the characters into the appropriate folder. Feature expansion would probably be to have right-click/add functionality to assign the base folder or create a new folder and/or create the relevant folder inside the watch path. I don't really want to add multiple watch folders.

**Comment by bulldogc** [comment]
Yep that works just fine, didn't know that was in there thanks!
