### ISSUE TITLE
Accuracy Increase from Shooter (The Soldier) Paragon Not Reflected on Sheet

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4935]
When adding Paragon Shooter The soldier, it should apply a +1 to cybercombat dice, mention a +1 limit to cybercombat and al attack actions and -1 limit to compiling in the limits tab and apply a -2 dice to compiling skill. None seem to be getting applied.
Chummer 2.224

**Comment by DelnarErsike** [comment]
Everything besides the limit modifiers to ranged weapons should be applied now. As for the lack of accuracy modifications to those ranged weapons, this issue becomes an effective duplicate of #4841. I'm still keeping it open though to remember to add something in for this paragon should that issue get resolved.
