### ISSUE TITLE
Ammunition type selection

### ISSUE THREAD

**Issue by Jydaxprime** [chummer5a/chummer5a#4939]
Several ammunition a types are not allowing a firearms types selection and are defaulting to Exotic Ranged Weapons. Notably injection darts and DMSO rounds.

**Comment by DelnarErsike** [comment]
Working as intended. Injection Darts are special ammo for Parashield Dart Pistols and Parashield Dart Rifles. DMSO Rounds are special ammo for Ares S-III Super Squirts. All of these weapons are exotic ranged weapons.

**Comment by Jydaxprime** [comment]
Narcoject one ammo?

**Comment by Jydaxprime** [comment]
When using the buy more ammunition button for the narcoject one light pistol the ammunition is listed as injection darts which when buying in the gear tab don't give the option to be bought for light pistols ONLY for exotic ranged weapons.
