### ISSUE TITLE
Crash by creating a Seedrake

### ISSUE THREAD

**Issue by DoomlordSoul** [chummer5a/chummer5a#4952]
**Describe the bug**
First I thought it was a Similar problem like the Problem from Issue #4951 but it happens now with every Charackter creation typ that I try where I Try to add the Seedrake Quality.

**To Reproduce**
1. Start Chummer 5.224.0
2. Create a New Charackter (I tryed it with the Full House rules, first with Sum-To-Ten German and then with Pointbuy German)
3. Add Quality 'Drake (Seedrake)' and enter a Value for Wanted
4. Crash without a Report, if it makes a quick safe and you start to load it does it crash after loading

**Expected behavior**
That it doesn't crash

**Character File**
No File

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 21H2 19033.2130

**Comment by DelnarErsike** [comment]
Cannot seem to replicate this in the Nightly.

**Comment by DoomlordSoul** [comment]
I Have installed the Nightly V. 5.224.19 while waiting, it doesn't crash anymore but also it doesn't Load everything that it should, so there aren't any changes of the Attributes, it starts loading for a endless time (I can still make changes) It doesn't add the Drake Quality, only the Wanted Quality and it doesn't add any Critter abilitys you get from the Drake Quality. It doesn't even use the 75 Karma for creating one

**Comment by DoomlordSoul** [comment]
I can add some more informations because I made some more try and Error, I thought it was because of the Drake Quality, but it is a Combination out of two Qualitys, Drake and any Magic Quality (Magician, Mysticadept, Adept and Aspected magicians), My charackter that I try to make should be an Elf Mystic Adept Seedrake

**Comment by DelnarErsike** [comment]
I believe this was fixed in 1d1f71997f1012765874357788bee9765d637f30, then. Once 5.224.28 releases, please test and verify.

**Comment by DoomlordSoul** [comment]
It seems to work, got Mystical adept and Drake (Seedrake) without any problems. Only Problem I got is that my old Character that I used to try this in every other Version lets Chummer Crash but thats no real problem because I didn't made much with this character that I can't reproduce. Thanks for the Fix.

**Comment by DoomlordSoul** [comment]
After some more Test are there some new Problems, I can't Load any Character not just the First Version of the Character, If I make a new character, Save this character, close Chummer, restart it and try to load this character does it Crash. I added the Crash Report Even while it is in German.

{"_dicCapturedFiles":{},"_dicPretendFiles":{"exception.txt":"System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.InvalidOperationException: Der Stapel ist leer.\r\n   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   bei System.Collections.Generic.Stack`1.Peek()\r\n   bei Chummer.Character.<RefreshAttributeBindingsAsync>d__169.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\Character.cs:Zeile 0.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()\r\n   bei Chummer.Backend.Attributes.AttributeSection.<ResetBindingsAsync>d__59.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Attributes\\AttributeSection.cs:Zeile 1906.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei Chummer.Backend.Attributes.AttributeSection.<ResetBindingsAsync>d__59.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Attributes\\AttributeSection.cs:Zeile 1912.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei Chummer.Backend.Attributes.AttributeSection.<ResetBindingsAsync>d__59.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Attributes\\AttributeSection.cs:Zeile 1917.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()\r\n   bei Chummer.Backend.Attributes.AttributeSection.<ResetAsync>d__56.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Attributes\\AttributeSection.cs:Zeile 1837.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei Chummer.Backend.Attributes.AttributeSection.<ResetAsync>d__56.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Attributes\\AttributeSection.cs:Zeile 1849.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()\r\n   bei Chummer.Character.<ResetCharacterAsync>d__217.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\Character.cs:Zeile 11788.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei Chummer.Character.<ResetCharacterAsync>d__217.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\Character.cs:Zeile 11865.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   bei Chummer.Character.<LoadCoreAsync>d__206.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\Character.cs:Zeile 9683.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei Chummer.Character.<LoadCoreAsync>d__206.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\Character.cs:Zeile 9695.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Chummer.Program.<LoadCharacterCoreAsync>d__42.MoveNext() in C:\\projects\\chummer\\Chummer\\Program.cs:Zeile 1158.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Chummer.CharacterCache.<OnDefaultDoubleClick>d__110.MoveNext() in C:\\projects\\chummer\\Chummer\\Backend\\Characters\\CharacterCache.cs:Zeile 551.\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)\r\n   --- Ende der internen Ausnahmestapelüberwachung ---\r\n   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   bei System.Delegate.DynamicInvokeImpl(Object[] args)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)\r\n   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()\r\n   bei System.Windows.Forms.Control.WndProc(Message& m)\r\n   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\r\n   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\r\n   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)\r\n   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)\r\n   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)\r\n   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)\r\n   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)\r\n   bei System.Windows.Forms.Application.Run(Form mainForm)\r\n   bei Chummer.Program.Main() in C:\\projects\\chummer\\Chummer\\Program.cs:Zeile 534."},"_dicAttributes":{"visible-crash-id":"a09d738f-a45d-4133-bded-b646bd72cf70","visible-build-type":"RELEASE","commandline":"\"C:\\Users\\Ian\\Desktop\\RP\\Shadowrun\\Shadowrun 5\\Charakter\\Chummer5.224.22\\Chummer5.exe\" ","visible-version":"5.224.28","machine-name":"DESKTOP-T1FV879","current-dir":"C:\\Users\\Ian\\Desktop\\RP\\Shadowrun\\Shadowrun 5\\Charakter\\Chummer5.224.22","application-dir":"C:\\Users\\Ian\\Desktop\\RP\\Shadowrun\\Shadowrun 5\\Charakter\\Chummer5.224.22\\Chummer5.exe","os-type":"Microsoft Windows NT 10.0.19044.0","visible-error-friendly":"Ein Aufrufziel hat einen Ausnahmefehler verursacht.","visible-stacktrace":"   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   bei System.Delegate.DynamicInvokeImpl(Object[] args)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)\r\n   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)\r\n   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()\r\n   bei System.Windows.Forms.Control.WndProc(Message& m)\r\n   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\r\n   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\r\n   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)\r\n   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)\r\n   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)\r\n   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)\r\n   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)\r\n   bei System.Windows.Forms.Application.Run(Form mainForm)\r\n   bei Chummer.Program.Main() in C:\\projects\\chummer\\Chummer\\Program.cs:Zeile 534.","installation-id":"bcd64349-17f5-420d-b881-816d76948ab5","option-upload-logs-set":"OnlyMetric","chummer-ui-language":"de-de","chummer-cultureinfo":"de-DE","system-cultureinfo":"de-DE","machine-id":"00330-80000-00000-AA126","os-name":"Windows 10 Pro","system-info-DragFullWindows":"True","system-info-HighContrast":"False","system-info-MouseWheelScrollLines":"3","system-info-PrimaryMonitorSize":"{Width=1920, Height=1080}","system-info-VerticalScrollBarWidth":"17","system-info-HorizontalScrollBarHeight":"17","system-info-CaptionHeight":"23","system-info-BorderSize":"{Width=1, Height=1}","system-info-FixedFrameBorderSize":"{Width=3, Height=3}","system-info-VerticalScrollBarThumbHeight":"17","system-info-HorizontalScrollBarThumbWidth":"17","system-info-IconSize":"{Width=32, Height=32}","system-info-CursorSize":"{Width=32, Height=32}","system-info-MenuFont":"[Font: Name=Segoe UI, Size=12, Units=0, GdiCharSet=1, GdiVerticalFont=False]","system-info-MenuHeight":"20","system-info-PowerStatus":"System.Windows.Forms.PowerStatus","system-info-WorkingArea":"{X=0,Y=0,Width=1920,Height=1080}","system-info-KanjiWindowHeight":"0","system-info-MousePresent":"True","system-info-VerticalScrollBarArrowHeight":"17","system-info-HorizontalScrollBarArrowWidth":"17","system-info-DebugOS":"False","system-info-MouseButtonsSwapped":"False","system-info-MinimumWindowSize":"{Width=136, Height=39}","system-info-CaptionButtonSize":"{Width=36, Height=22}","system-info-FrameBorderSize":"{Width=4, Height=4}","system-info-MinWindowTrackSize":"{Width=136, Height=39}","system-info-DoubleClickSize":"{Width=4, Height=4}","system-info-DoubleClickTime":"500","system-info-IconSpacingSize":"{Width=114, Height=75}","system-info-RightAlignedMenus":"False","system-info-PenWindows":"False","system-info-DbcsEnabled":"False","system-info-MouseButtons":"5","system-info-Secure":"False","system-info-Border3DSize":"{Width=2, Height=2}","system-info-MinimizedWindowSpacingSize":"{Width=160, Height=28}","system-info-SmallIconSize":"{Width=16, Height=16}","system-info-ToolWindowCaptionHeight":"23","system-info-ToolWindowCaptionButtonSize":"{Width=22, Height=22}","system-info-MenuButtonSize":"{Width=19, Height=19}","system-info-ArrangeStartingPosition":"Hide","system-info-ArrangeDirection":"Left","system-info-MinimizedWindowSize":"{Width=160, Height=28}","system-info-MaxWindowTrackSize":"{Width=3860, Height=1100}","system-info-PrimaryMonitorMaximizedWindowSize":"{Width=1936, Height=1096}","system-info-Network":"True","system-info-TerminalServerSession":"False","system-info-BootMode":"Normal","system-info-DragSize":"{Width=4, Height=4}","system-info-ShowSounds":"False","system-info-MenuCheckSize":"{Width=15, Height=15}","system-info-MidEastEnabled":"False","system-info-NativeMouseWheelSupport":"True","system-info-MouseWheelPresent":"True","system-info-VirtualScreen":"{X=-1920,Y=0,Width=3840,Height=1080}","system-info-MonitorCount":"2","system-info-MonitorsSameDisplayFormat":"True","system-info-ComputerName":"DESKTOP-T1FV879","system-info-UserDomainName":"DESKTOP-T1FV879","system-info-UserInteractive":"True","system-info-UserName":"Ian","system-info-IsDropShadowEnabled":"True","system-info-IsFlatMenuEnabled":"True","system-info-IsFontSmoothingEnabled":"True","system-info-FontSmoothingContrast":"1200","system-info-FontSmoothingType":"2","system-info-IconHorizontalSpacing":"114","system-info-IconVerticalSpacing":"75","system-info-IsIconTitleWrappingEnabled":"True","system-info-MenuAccessKeysUnderlined":"False","system-info-KeyboardDelay":"1","system-info-IsKeyboardPreferred":"False","system-info-KeyboardSpeed":"31","system-info-MouseHoverSize":"{Width=4, Height=4}","system-info-MouseHoverTime":"400","system-info-MouseSpeed":"10","system-info-IsSnapToDefaultEnabled":"False","system-info-PopupMenuAlignment":"Right","system-info-IsMenuFadeEnabled":"True","system-info-MenuShowDelay":"400","system-info-IsComboBoxAnimationEnabled":"True","system-info-IsTitleBarGradientEnabled":"True","system-info-IsHotTrackingEnabled":"True","system-info-IsListBoxSmoothScrollingEnabled":"True","system-info-IsMenuAnimationEnabled":"True","system-info-IsSelectionFadeEnabled":"True","system-info-IsToolTipAnimationEnabled":"True","system-info-UIEffectsEnabled":"True","system-info-IsActiveWindowTrackingEnabled":"False","system-info-ActiveWindowTrackingDelay":"0","system-info-IsMinimizeRestoreAnimationEnabled":"False","system-info-BorderMultiplierFactor":"1","system-info-CaretBlinkTime":"530","system-info-CaretWidth":"1","system-info-MouseWheelScrollDelta":"120","system-info-VerticalFocusThickness":"1","system-info-HorizontalFocusThickness":"1","system-info-VerticalResizeBorderThickness":"4","system-info-HorizontalResizeBorderThickness":"4","system-info-ScreenOrientation":"Angle0","system-info-SizingBorderWidth":"1","system-info-SmallCaptionButtonSize":"{Width=22, Height=22}","system-info-MenuBarButtonSize":"{Width=19, Height=19}"},"_intProcessId":23400,"_uintThreadId":23820,"_ptrExceptionInfo":{"value":24107976}}

**Comment by DoomlordSoul** [comment]
Found a Temporary Solution, the Older Versions couldn't create a Drake with a Magical Class, but while I can create and save them on 5.224.28 but not open them there I can use 5.224.27 to Open the Characters to work with them until the new Problem is fixed.

**Comment by DoomlordSoul** [comment]
Okay Now After Downloading 5.224.31 and 5.224.30 I can tell that you Fixed every problem I had in 5.224.30 but added one more Problem on 5.224.31 you can't create any new charakter in the 31 version

**Comment by DelnarErsike** [comment]
That should be fixed in commit 2a90dd0fccf32334ce7fe2fa5b9dd87ace5e964c. If all related issues have been fixed, I'm closing this issue.
