### ISSUE TITLE
Masteries (Forbidden Arcana) don't understand skill groups, alternative traditions and translations

### ISSUE THREAD

**Issue by SuperMarauderGirl** [chummer5a/chummer5a#4953]
Hello,

me and some fellow players stumpled upon some wierd effect: Picking masteries from the qualities always prompts a message that the requirements aren't met yet, eventhough the skills are obviously there. After digging some xmls I found out that 
Prob1: the qualities.xml does not have entries for skill requirements when they are met by their respective skill group.

Prob2: if you use a translation some of the skills get saved with their translation into the chummer file. When checking for the skill the mastery compares the english string with the translated string, finds them to be different and claims the needed skills to be missing.

Example1: Puppet Master doesn't understand that Sorcery 6 does meet the requirement for Spellcasting 6 or Spellcasting 4 with Specialization in Manipulation
Example2: Puppet Master doesn't understand that Black Magic and Black Magic [alt] are the same tradition
Example3: Puppet Master doesn't understand that "Psychologie" is the german translation for "psychology"

Current Workaround: We removed all requirements of all the masteries and let the GM facecheck our chummer-files when picking a mastery

**Comment by chummer5a** [comment]
Incorrect, skill groups do count towards the rating. Psychology should be working correctly, was it picked from the dropdown or typed in?
