### ISSUE TITLE
Resist fade might not use augmented will

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4954]
When I add a will aug improvement for drugs, Resist fading value doesn't increase.

Create technomancer
add improvement for wil
notice that resist fade value doesn't increase.

**Comment by bulldogc** [comment]
Update, I tried adding cyber singularity seeker, that additional will does appear to update the fade resist. So the issue seems related to improvement type attribute selected value will value X

**Comment by DelnarErsike** [comment]
I believe this was incidentally fixed in 789cb2c4e15aed69e0cf0f70faba9cc934f9438e.
