### ISSUE TITLE
Chummer crash on character creation

### ISSUE THREAD

**Issue by Jydaxprime** [chummer5a/chummer5a#4956]
**Describe the bug**
Chummer crashes when upping Willpower

**To Reproduce**
1. Go to Create a new character, Magic priority C Apprentice, Health and Spirit of Man selections
2. Click on Willpower and attempt to raise number
3. Chummer crashes

**Expected behavior**
Willpower to be raised and chummer to not crash

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by DelnarErsike** [comment]
Already fixed in the Nightly.
