### ISSUE TITLE
Enhancement Suggestion: Character Portraits as URLs?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#496]
Any chance of adding an option for a URL for a character portrait in addition to a folder path?

**Comment by chummer5a** [comment]
Not particularly difficult to implement I suppose, just adds a small amount of busywork in the backend Mugshots are actually stored in the chum5 file as a binary-converted jpeg though, it wouldn't update dynamically or anything like that without a fair bit of extra work.
