### ISSUE TITLE
Raven Mentor Spirit for Adepts

### ISSUE THREAD

**Issue by Hippasos** [chummer5a/chummer5a#4960]
The Raven Mentor Spirit gives both described Adept Powers to an Adept instead of the choice of one of them.
In the English description text there is an 'and' at that point instead of the correct 'or'.
The German translation shows the text correctly but still the wrong behavior.

**Comment by chummer5a** [comment]
English says and, so that's what's in the data. If you have the German Data Changes customdata enabled, it should amend that behaviour.
