### ISSUE TITLE
Custom fit encumbrance option not working

### ISSUE THREAD

**Issue by Watermel0wned** [chummer5a/chummer5a#4969]
Checking the "Custom Fit (Stack) Does not Encumber " option on the Custom Data character settings doesnt seem to work.

**To Reproduce**
1. Enable Custom Fit Option on character data
2. Armor values dont change properly whenever i equip custom fit armor (Rheingold pro tec plus or Mortimer of London).
3. Editor still adds custom fit armor to the maximum threshold of possible bonus armor.

**Expected behavior**
Custom fit armor values should not add to encumbrance

**Comment by DelnarErsike** [comment]
That option is specifically for Armor Encumbrance. Armor Encumbrance and maximum possible armor gained from accessories are two different things. There is no way in Chummer5a to specifically exclude Custom Fit (Stack) from the armor accessory bonus limit but still keep that limit for other accessories.
