### ISSUE TITLE
Request: Add optional support for "provisional" errata.

### ISSUE THREAD

**Issue by Maguillage** [chummer5a/chummer5a#4970]
**Is your feature request related to a problem? Please describe.**
The folks in charge of errata have on more than one occasion posted stuff as "provisional" and left it to sit that way for ages, neither making it official nor retracting it.
For example, [the Run Faster errata regarding shapeshifters](https://forums.shadowruntabletop.com/index.php?topic=24596.msg464878#msg464878).
There's often no convenient way to add those changes to a sheet manually.

**Describe the solution you'd like**
Ideally, add support for "provisional" errata either through custom data entries packaged with chummer by default or as "houserules" to enable.

**Describe alternatives you've considered**
Alternatives would be either to do all the relevant custom data myself (which is moderately inconvenient since I have no idea how those work) or manually shove the relevant changes into a character sheet, which may not always be applicable.

**Comment by SRgithub5** [comment]
I'm willing to work on some of these, but I'm new to github, and I'd love links to the specific provisional errata. For instance the September 24th 2016 provisional errata for shifters to get Allergy (Silver, Severe), Dual Natured, Regeneration, and Vulnerability (Silver) sounds like something I would like to work on. Which sounds like something you were asking for.

**Comment by SRgithub5** [comment]
I'm willing to work on some of these, but I'm new to github. That September 24th 2016 provisional errata sounds like something I would like to work on.

**Comment by SRgithub5** [comment]
I do have questions though. Like the regeneration for infected and the regeneration from the core rule book are different. So I'm not sure which the shifters get. Maybe shifters were supposed to get a third kind and that was a factor in changing it from provisional.

**Comment by chummer5a** [comment]
Hmm? How are they different? Errata just shows they get Regeneration, I don't believe there's any callouts that it's particularly different.

**Comment by SRgithub5** [comment]
The core rulebook vampire for instance can't use cyberware, but regeneration is later modified to allow vampires to have delta ware. So I wasn't sure which regneration shapeshifters were supposed to have, but since it looks like chummer5a only immplements the modified delta ware friendly regneration I gave that version, even though the "source" section seems wrong.

**Comment by SRgithub5** [comment]
Fix submitted to the master branch, pull request placed. At least, if it isn't please tell me since I tried.

**Comment by SRgithub5** [comment]
The baseline Regeneration Power on page 400 of the 2nd printing of the core rulebook doesn't allow deltaware.

But page 134 of Run Faster allows Infected with Regeration to get new deltaware and maybe even to keep existing non deltaware with penalties and costs.

But I've never seen a mention of which kind of Regeneration the shapeshifters are supposed to get. The regular core rulebook one or the infected one. But I can make "Power, Regeneration" appear on your character sheet!

**Comment by SRgithub5** [comment]
The baseline Regeneration Power on page 400 of the 2nd printing of the core rulebook doesn't allow deltaware.

But page 134 of Run Faster allows Infected with Regeneration to get new deltaware and maybe even to keep existing non deltaware with penalties and costs.

But I've never seen a mention of which kind of Regeneration the shapeshifters are supposed to get. The regular core rulebook one or the infected one. But I can make "Power, Regeneration" appear on your character sheet!

**Comment by SRgithub5** [comment]
Whoops, added regeneration now
