### ISSUE TITLE
Typo: Narcoject gear is misspelled as Narcojet

### ISSUE THREAD

**Issue by Darkman309** [chummer5a/chummer5a#4971]
Narcoject and Narcoject Dazzler both are misspelled. Other instances for the weapons and ammo are correct.

    <gear>
      <id>875bf273-1a0d-4a42-80ab-6547d7a1235a</id>
      <name>Narcojet</name>
      <category>Toxins</category>
      <rating>0</rating>
      <source>SR5</source>
      <page>410</page>
      <avail>6R</avail>
      <cost>50</cost>
    </gear>

    <gear>
      <id>fb7465a7-4691-4647-a82c-a7b486fab34a</id>
      <name>Narcojet Dazzler</name>
      <category>Survival Gear</category>
      <rating>0</rating>
      <source>SL</source>
      <page>46</page>
      <avail>15R</avail>
      <cost>1000</cost>
    </gear>
![image](https://user-images.githubusercontent.com/66814711/211154518-f2cd0fa3-a5d4-4e47-b474-13f7affa3f24.png)

**Comment by SRgithub5** [comment]
Submitted

**Comment by DelnarErsike** [comment]
Merged and fixed.
