### ISSUE TITLE
Mentor Spirit Chaos

### ISSUE THREAD

**Issue by DoomlordSoul** [chummer5a/chummer5a#4977]
**Describe the bug**
I tried to add the Mentor Spirit Chaos to an Adept. But I didn't get the Bonus as it should have been.

**To Reproduce**
1. Create an Adept
2. Pick the Qualitie Mentor Spirit
3. Pick the Mentor Spirit Chaos
4. You get 1 level in Improved Potential for Free but don't get the Second level for free.

**Expected behavior**
That I get 2 Levels in Improved Potential, either 1 in two different or 2 in one Improved Potential for Free.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Version [21H2 19033.2130]

**Comment by chummer5a** [comment]
It should be giving you an additional power, Improved Potential (Chaos Mentor), which works around a limitation of the power itself.

**Comment by DoomlordSoul** [comment]
"2 free levels of Improved Potential (can be 2 levels for the same limit, or 1 level apiece to affect 2 different limits)" that is what it say, the Charakter has a Physical Limit of 6, when I chose that for Improved Potential Physical is all I get, a Physical Limit mod of 1 that it changes to 7, while it adds the power 1 time for free, normaly it should rise the limit by 2 and would add this power either two times or on second level for free, but it says to me it costs 0.5 on second level instead of 0, nothing more is added, just this with the cost of 0.5PP

**Comment by DelnarErsike** [comment]
Improved Potential is not a power that has ratings in the English books. In the German books, it does (see: #4664), so keep that in mind and how that relates to the German Data Changes custom dataset that you should have enabled if you are playing by the German books' altered rules.

**Comment by DoomlordSoul** [comment]
2 Things:
1.) I am using Full House Improved Sum To Ten German, so no it isn't working.
2.) Even while it is badly worded in the English version, is Improved Potential even there an 0.5 PP per Level thing, if it would be just one level they would have wrote it as "Cost: 0.5 PP" "Can be picked multiple times for each limit once." Best example for that is three Adept Powers above improved Potential with "Enhanced Accuracy (Skill)" that you can learn for multiple skills but only has one level.
So no it isn't completed because the German Rule set firstly doesn't work and the ability isn't in there as intended. And if you still keep on the point that it isn't like I said because the wording is "This power allows an adept to raise one of your inherent limits (Physical, Mental, or Social), specified when you buy the power, by 1. You may buy this power multiple times, once per inherent limit." then why can you level it, if level 2, 3, 4, 5 and so on is the same as level 1, why would they even add to the English version of Mentor Chaos that you can get Level 2 of this Power if it wouldn't do anything. Again it is just a bad Wording, they intended something else

**Comment by DoomlordSoul** [comment]
[Example.zip](https://github.com/chummer5a/chummer5a/files/10419953/Example.zip)
I added a Quick example Charakter still in creation, made in Nightly 5.225.31 as you can see if you use it, it will say that It is Full House (Sum-to-Ten Improved, German) and I added Mentor Spirit Chaos, added some point randomly to the Attributes to increase the limits some way up Physical Limit is at 7 without the adept Power, with it, it is at 8, the power is at level 2 (still costs 0.5 PP, first thing that is wrong, and the Limit should have been at 9)

**Comment by DoomlordSoul** [comment]
Oh and because you like to get some proofs here a Screenshot from Mentor Spirit Chaos from the English Street Grimoire: 
![Chaos](https://user-images.githubusercontent.com/28228200/212540831-b029d498-ac12-4365-8ae1-f05278359dbd.PNG)
As you can see even there it says you can get 2 levels on one Limit

**Comment by DoomlordSoul** [comment]
Just Downloaded the New Nightly 5.225.42, and there are way more bugs now, If I chose Mentor Spirit Chaos, (German Edition again) It asks me first time "Limit", I chose Physical, it Asks me again what Limit (but all I can chose is Mental or Social) First I klickt at nothing, didn't get Mentor Spirit, but it added one level Physical for 0.5 Points, I deleted it, chose it again and chose Physical and Mental get the Quality, get 2 levels in both Improved Potential have to pay 0.5 per Potential, and stil even while both are at level 2 did I just get 1 level per chosen Limit
