### ISSUE TITLE
submersions seem broken??

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4980]
**Describe the bug**
For some reason submersions over grade 1 don't seem to be working. Grade one seems to apply as expected. Grade 2 seems to happen but doesn't actually increase max magic, if you then buy an additional grade it is bought at grade 2 again.

**To Reproduce**
1. create raw technomancer with sum-10 std array but with techno instead of adept.
2. max out resonance
3. add bunch of karma
4. add sub grade 1, raise resonance to 7 to confirm it works. try to add echo
5. add 2nd sub grade. Grade 2 will appear, resonance is now locked at 7 and can't be increased, echo can still be added.
6. add 3rd sub grade. a 2nd grade 2 will appear, res still locked at 7, echo will be the same as the one selected at first grade 2.

This is happening for me with both 5.225.50 and 5.225.0

**Comment by bulldogc** [comment]
Almost feels like the code is adding submersion grade to the sheet the first time then fails to increment it after you add subsequent grades.

**Comment by Tzigamm** [comment]
Can confirm, grade 1 works as intended, grade 2 seems to be behaving somewhat weirdly and any grade after that appears as grade 2 and costs 16 karma

**Comment by DelnarErsike** [comment]
Could you try with the Nightly releasing in about 23 hours as of me writing this comment? I think I ended up fixing the issue, but I'm not sure.

**Comment by bulldogc** [comment]
This version seems better, I didn't extensively test but seems to work. It doesn't fix existing broken grade 2's though and undoing those fails. Will have to try and strip it out with a manual edit probably.

**Comment by bulldogc** [comment]
Confirmed working with minor fix if you already had a broken submersion. For anyone searching, edit your save and search for "<submersiongrade>X</submersiongrade>" and correct that to the right value, probably 2. then find 
"<improvementsource>Submersion</improvementsource>" and update the rating above that to the correct value (probably 2 as well).
