### ISSUE TITLE
Geneware price gets modified by previous grade selection.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4990]
Looks like although geneware correctly disables the grade selection, it doesn't actually reset the cost multiplier before it does. Because of this the price for geneware is getting multiplied by the previously selected grade.

To reproduce, open the bioware window and select damage compensators. Then select alpha grade. finally pick dareadrenaline.
The price should be 61000Y but is actually 73200Y.
When disabling the Grade selector, the code should likely also set the grade to standard first is my guess?

**Comment by DelnarErsike** [comment]
Should already be fixed in 5aaea8827526622a2fd460cda7455a55ed7eb919.
