### ISSUE TITLE
Linux/Wine Crash when ScrollableMessageBox opened: MB_GetString not implemented 

### ISSUE THREAD

**Issue by MachineMuse** [chummer5a/chummer5a#4995]
It seems that the function `MB_GetString` in `user32.dll` is not implemented in WINE (see https://github.com/wine-mirror/wine/blob/master/dlls/user32/user32.spec#L526 where it is a commented-out stub).

The only place this is used in the Chummer5a code is in [Chummer/Backend/Static/NativeMethods.cs](https://github.com/chummer5a/chummer5a/blob/master/Chummer/Backend/Static/NativeMethods.cs), specifically in the helper methods `GetSystemString`, which are then only used in [Chummer/Forms/ScrollableMessageBox.cs](https://github.com/chummer5a/chummer5a/blob/master/Chummer/Forms/ScrollableMessageBox.cs).

So whenever Chummer tries to create a ScrollableMessageBox, it crashes with this error:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.EntryPointNotFoundException: Unable to find an entry point
 named 'MB_GetString' in DLL 'user32.dll'.
```

Would it be possible to use a different method, or some other kind of workaround?

**Comment by Newbytee** [comment]
Wouldn't it be better to just implement this in Wine?

**Comment by Newbytee** [comment]
Also, do you have any easy reproduction steps?

**Comment by MachineMuse** [comment]
> Wouldn't it be better to just implement this in Wine?

Certainly, but I'm not a WINE dev and I have no idea how it would be done. Mysterious Windows system calls...

> Also, do you have any easy reproduction steps?

It's a bit tricky since the ScrollableMessageBox seems to be mainly used for error reporting, but the simplest way might be to open up a character file and try to add a Lifestyle with an empty string for the name (which will trigger [this line](https://github.com/chummer5a/chummer5a/blob/21f2b9361b9be769bf5ac60f44d2568db16bc0a2/Chummer/Forms/Selection%20Forms/SelectLifestyleAdvanced.cs#L751))

It will also happen if the settings file for that character can't be found.

You can also try to edit global settings without the necessary permissions (so that you get a `UnauthorizedAccessException`).

Or you can try to add a spell to a mage character in Create mode beyond their spell limit.

**Comment by MachineMuse** [comment]
Maybe the easiest solution would be to catch the exception and open a simpler error message box like in previous builds. I'll see if I can implement that.
