### ISSUE TITLE
Exception resulting from removing initation power in karmagen

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#50]
Version 5.159

Add an initiation grade in karmagen, add the invocation and then ally spirit metamagics. These go together.

If you try to remove the initiation grade that works fine. But if you try to remove the spell Ally Spirit an exception results.

I'm also politely requesting the ability to store more information about spirits. The important stuff like powers, grade, services and status as bound unbound or allied

**Comment by chummer5a** [comment]
Issue appears to be that the Spells list is not updated when Ally Spirit is removed; the spell itself is gone, but is now a null reference in the list. Should be a simple fix. 

The spirit list is intended mostly to be a quick reference; generally speaking you should create a separate Spirit NPC and link their chummer file. On that note though, the Spirit creator generates an exception.

**Comment by Neocyberman** [comment]
I'd imagine it does given that there are no rules for free spirit creation
in 5e.

But I am curious the steps you take to "make a spirit NPC". It doesnt seem
to be in the character creation.

**Comment by chummer5a** [comment]
Rituals and Spells are now properly removed from the list of tree nodes through an ugly series of for loops. Resolved in 5.160.

Spirits and Critters depend largely on Running Wild, an SR4 sourcebook. Strictly speaking should remove the options completely.
