### ISSUE TITLE
Bug - Firearms Accessories Showing for Unarmed Attack

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#500]
Step 1 - Right Click on Unarmed Attack in Weapons Menu
Step 2 - Click on 'Add Accessory'
Step 3 - Click on "Smartgun System, Internal'
Step 4 - Click on Okay. 

Looks like the list of accessories presented for unarmed attack are really meant for firearms. Should adding accessories to unarmed attack be an option? And if it should, should the firearms type accessories be available for selection?

![image](https://cloud.githubusercontent.com/assets/15821037/11216035/2d2b9914-8d17-11e5-9d42-8370688621bb.png)

**Comment by chummer5a** [comment]
Included in 5.179.
