### ISSUE TITLE
Improved Potential isn't able to improve my Limit more then one Time

### ISSUE THREAD

**Issue by DoomlordSoul** [chummer5a/chummer5a#5009]
**Describe the bug**
Created an Adept with Improved Potential (A Power that is meant to be leveled and to raise the Limit by 1 each level!) but still only get 1 point out of it no matter how high I level it

**To Reproduce**
1. Create a Character (no matter what Rules you are using)
2. Make him an Adept (Or Mysticaladept if you want)
3. Chose Improved Potential on Level 2
4. See how it only adds 1 Point

**Expected behavior**
With level 2 it should add 2 Points, with level 3 should it be 3 points and so on.
Even Jason Hardy who worked on this system is agreeing with me.

**Screenshots**
![Jason M  Hardy](https://github.com/chummer5a/chummer5a/assets/28228200/64416dd0-54ca-43aa-8e16-d69ddb8c08f3)

**Desktop (please complete the following information):**

 - Version 5.225.157

**Additional context**
Please listen to me, and show with a Reply that you listen to me.

**Comment by chummer5a** [comment]
Unable to replicate the issue. Taking the chaos mentor gives a level of improved potential, and a level of improved potential (chaos mentor) which provides the required limit increases. Did find an issue with the multi-level German Data Changes version, but otherwise no issues present.

**Comment by DoomlordSoul** [comment]
Can't Agree properly, right at the moment where I read this answer did I start Chummer V5.225.157 again and chose Full House Point Buy (not the german rule version) Picked Chaos Mentor Spirit and chose 2 times Physical as a Test, since the first try where I made one with 2 Physical improvements is this my typical way to go, and even while it states that both improvements are Physical does it add 1 Point in Physical and 1 in Social.

And you can still not level this power in the non German rule sets, while it is stated in the rules and by Jason M. Hardy that you can Level it.

the Example character where I added Chaos with 2 time Physical and Mental 1 time:
[Improved Potential test.zip](https://github.com/chummer5a/chummer5a/files/11464898/Improved.Potential.test.zip)

**Comment by chummer5a** [comment]
Ah, found the issue. Will be fixed in next nightly build.
