### ISSUE TITLE
Chummer not actually exiting when closed

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#5010]
5.225.144 When hitting the x to close out the app, chummer is remaining open in the task manager. The window closes and it appears closed but trying to start chummer again fails unless I kill the remaining chummer task in task manager. Noticed on windows 10.

**Comment by ArchonMegalon** [comment]
Probably something with the logging? We should maybe implement a hard time out after the close-signal to kill ourself of.

Can you check if this behaviour persists when you disable all logging?

**Comment by bulldogc** [comment]
I think I have logging currently disabled? "Use Logging" is unchecked in the global settings, do I need to toggle anything else as well?

**Comment by DelnarErsike** [comment]
I have seen this in the debug builds and I assumed that it was just a debug-specific thing. When in debug mode, it's very obvious that Chummer is waiting upon external `ApplicationInsights` code to execute and is hanging there.

**Comment by ArchonMegalon** [comment]
Thank you for the ping. It SHOULD stop after 30 seconds. 

@DelnarErsike: you changed quite a bit there. Need to work through that. Do we have any pattern, when this bug emerges?
For example I'm only hosting this application insights instance in central europe and it is not mirrored to other regions of the world (that would cost extra), so I think it may be possible for clients from asia or far away to take longer to upload the logs. 

But 30 seconds should clearly be enough. We could start a timersthread and send a Process.Kill() to ourselves after it expires. A bit hardcore, but should work...

**Comment by JoschiZ** [comment]
Interesting while implementing the hack in #5051 I also tried to determine the problem, but couldn't find much more than your previous observations that AI may be stalling somehow.
I didn't look any deeper than that, because we need to switch our AI implementation anyways and I hoped that that would fix it by happenstance.
