### ISSUE TITLE
Mystic Adepts Power Points not increasable in Career Mode

### ISSUE THREAD

**Issue by JochmannT** [chummer5a/chummer5a#5015]
**Describe the bug**
A mystic adept in career mode cannot improve their adept power points. The regarding buttons from Build mode are just not there.

**Expected behavior**
A button to increase the power points like in the build mode should be available.

**Screenshots**
![image](https://github.com/chummer5a/chummer5a/assets/84670696/da9c921a-1146-4569-9380-ff46ae3e94d5)

**Desktop (please complete the following information):**
 - OS: [Windows 10 PRO]
 - Version [19045.2965]

**Comment by chummer5a** [comment]
RAW, MysAds can only buy their starting power points during character creation.

**Comment by LNSmith458** [comment]
There is however a house rule option for allowing Mystic Adepts to buy power points during career mode.
![image](https://github.com/chummer5a/chummer5a/assets/4000095/4dd74d28-3fca-4a35-9b51-aed7a98070b3)

**Comment by DelnarErsike** [comment]
I completely forgot that option exists. Closing the issue.
