### ISSUE TITLE
Drone armor display doesn't update

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#5019]
5.225.179  Adding drone armor to a drone doesn't update the drones actual armor on the display.

**Comment by bulldogc** [comment]
To expand on this some, drone armor in general just seems to work wrong. Sometimes when adding it, it adds twice, other times ill buy rating 14 and it will place rating 9 in the drone. Stuff like that.

**Comment by chummer5a** [comment]
Seems to be resolved as of current commit.
