### ISSUE TITLE
Nested Locations?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#502]
How about making it so that you can have a location within another location.

Example: I'd like to store a gun in my safe which is located in a hidden compartment in my apartment.in Redmond. And then I'd like to store all of my other stuff in safe in a warehouse in Hong Kong.

**Comment by chummer5a** [comment]
Hrm. Not particularly difficult, just touches a lot of things.

**Comment by whatevs5** [comment]
Gear locations are one of my favorite things you guys have built into Chummer5a. I like a lot of detail for my gear management.

**Comment by whatevs5** [comment]
I'm not sure if you share my excitement for organizing gear, but I added suggestion #510 that could have a nice synergy with this.

**Comment by schultlp** [comment]
I would definitely love to see this implemented.
