### ISSUE TITLE
Critter Fail to Save on 'Full House'

### ISSUE THREAD

**Issue by asenright** [chummer5a/chummer5a#5025]
**Describe the bug**
When attempting to save a Critter, I got a crash-to-desktop in JavaScriptSerializer.

**To Reproduce**
1. Go to file -> New Critter
2. Select 'Full House'
3. Select Spirit of Man
4. Set Force to 3
5. Select OK
6. For the Power, choose Fear and hit ok. The character sheet should now be open
7. Select File -> Save As..., keep the type as .chum5,  and enter any filename.
App crashes irrecoverably here.

**Expected behavior**
Critter should save. 

**Screenshots**
Stack trace:
![image](https://github.com/chummer5a/chummer5a/assets/22029113/1a29f271-fc3d-498c-aac1-b34d726452e2)

**Character File**
Character file could not be saved due to this bug.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by chummer5a** [comment]
5.222 is quite an old build. Try updating to a newer release.

**Comment by DelnarErsike** [comment]
As there has been no response for over 3 months, I am closing this issue.
