### ISSUE TITLE
Mention of 'Infiltration', Should Now be 'Sneaking'?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#504]
When choosing a mentor spirit, the description for Cat mentions 'Inflitration'. I would imagine that this is a hangover from the original Chummer. The section of the application is:

Qualities > Positive > Mentor Spirit > Select a Mentor Spirit > Click on 'Cat' in the left hand menu

The following test shows at the top of the right hand side:

Advantage: +2 Dice to either Gymnastics or Infiltration Tests (choose one)

**Comment by chummer5a** [comment]
Funnily enough it actually does give the bonus for Sneaking, the previous dev just didn't update the description. Fixed in 5.177.

**Comment by whatevs5** [comment]
Thank you!
