### ISSUE TITLE
Custom Bioware Grades cannot be selected.

### ISSUE THREAD

**Issue by EmmjayXII** [chummer5a/chummer5a#5046]
A custom bioware grade from a custom data directory's amend_bioware file does not show up properly. Although the grade is searchable in the index, and thus has been loaded, when you attempt to purchase or upgrade bioware to that grade the grade is not shown in the UI and cannot be selected.

**Comment by JoschiZ** [comment]
Hey, I know you probably shared this in the Discord directly, but could you also attach the amend file or relevant parts of it that are not working?

**Comment by EmmjayXII** [comment]
Here you go.
