### ISSUE TITLE
Runnerhub Specific Settings?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#505]
Just wondering if it makes sense to create a group of settings for Runnerhub character generation. For Example, Runnerhub characters require priority builds, they don't allow specific books, they don't allow any mental and physical stats starting at 1, and they don't allow certain qualities. They also have specific contacts to choose from. Among other things.

The full list of their house rules is here: http://runnerhub.wikia.com/wiki/HouseRules_of_RunnerHub 

I mention it because they recommend that their players use Chummer5a, and they seem to have a certain level of popularity.

**Comment by joha4270** [comment]
To make a long story short, not even on the list. Creating a lot of custom rules are ugly right now and i don't even want to try and enforce some of the more subjective stuff. 

So, while I'm not going to close this outright, we are probably going to be working on Chummer6 before we start doing runnerhub specific things.
At least unless somebody else implements it.

**Comment by whatevs5** [comment]
Fair enough, thanks for reviewing.
