### ISSUE TITLE
Can't require qualities for vehicle mods.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#5058]
I am trying to set a vehicle mod that is only available when a quality is selected. The following doesn't work for it.
      <required>
            <characterquality>QUALNAME</characterquality>
      </required>
Topic was discussed some in discord here.
https://discord.com/channels/365227581018079232/945359128887447602/1159615383695798292

**Comment by chummer5a** [comment]
Implemented by https://github.com/chummer5a/chummer5a/commit/d4166fdce377ef0a584a140dc84f3aec41f1c959
