### ISSUE TITLE
Cyber Suites Are Blank

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#5061]
**Describe the bug**
Attempted to add a Cyber Suite today, but the menu came up blank when I went to add it. Tested on the latest nightly with no active amends on the Full House settings.

**Screenshots**
![Screenshot 2023-10-09 at 11 34 54 PM](https://github.com/chummer5a/chummer5a/assets/1766631/9efe3d62-5d00-48e1-95ad-d5cc6842e95b)

**Comment by Teksura** [comment]
Okay, so, to add more clarity to this as I have realized something.

Under the Special Menu, selecting Add Cyberware Suite produces the above blank menu. 

Selecting Add Cyberware produces the normal add cyberware option where Suites can be bought. 


I'm really not sure what the option in the Special menu is for now.

**Comment by DelnarErsike** [comment]
The form is for custom cybersuites.
