### ISSUE TITLE
Crashes when binding Qi-Focus and language is German

### ISSUE THREAD

**Issue by Darilon** [chummer5a/chummer5a#5068]
**Describe the bug**
When I try to bind the Qi-Focus in the attached character to "Improved Ability (Automatics)" Chummer crashes.
Note that it only crashes if I set the Language of Chummer to German. It seems to work if I set the language to English. 

I get a crash report that says:

Failed to create crash report because of an issue with the crash handler.
Chummer crashed with version: 5.225.322.0
Crash Handler crashed with exit code: -532462766
Crash information:
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentOutOfRangeException: Der Wert 1 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei Chummer.UI.Table.SpinnerTableCell`1.UpdateValue(Object newValue) in C:\projects\chummer\Chummer\Controls\Table\SpinnerTableCell.cs:Zeile 66.
   bei Chummer.UI.Table.TableView`1.<>c__DisplayClass20_0.<UpdateCell>b__0(TableCell x) in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:Zeile 336.
   bei Chummer.WinFormsExtensions.<>c__DisplayClass15_0`1.<DoThreadSafeAsync>b__1() in C:\projects\chummer\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:Zeile 492.
   bei Chummer.Utils.<>c__DisplayClass119_0.<<RunOnMainThreadAsync>b__0>d.MoveNext() in C:\projects\chummer\Chummer\Backend\Static\Utils.cs:Zeile 1318.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chummer.UI.Table.TableView`1.<UpdateCell>d__20.MoveNext() in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:Zeile 336.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Chummer.UI.Table.TableView`1.<CreateCell>d__22.MoveNext() in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:Zeile 362.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Threading.Tasks.ValueTask`1.get_Result()
   bei Chummer.UI.Table.TableView`1.<ItemsChanged>d__31.MoveNext() in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:Zeile 621.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.RunDialog(Form form)
   bei System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   bei Chummer.WinFormsExtensions.<>c__DisplayClass3_0.<ShowDialogSafe>b__0() in C:\projects\chummer\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:Zeile 58.
   bei Chummer.Utils.RunOnMainThread[T](Func`1 func, CancellationToken token) in C:\projects\chummer\Chummer\Backend\Static\Utils.cs:Zeile 1202.
   bei Chummer.WinFormsExtensions.ShowDialogSafe(Form frmForm, IWin32Window owner, CancellationToken token) in C:\projects\chummer\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:Zeile 58.
   bei Chummer.Forms.ScrollableMessageBox.Show(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defButton, MessageBoxOptions options) in C:\projects\chummer\Chummer\Forms\ScrollableMessageBox.cs:Zeile 46.
   bei Chummer.Program.<>c__DisplayClass27_0.<ShowScrollableMessageBox>b__0(Form x) in C:\projects\chummer\Chummer\Program.cs:Zeile 909.
   bei Chummer.WinFormsExtensions.<>c__DisplayClass19_0`2.<DoThreadSafeFunc>b__0() in C:\projects\chummer\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:Zeile 679.
   bei Chummer.Utils.<>c__DisplayClass108_0`1.<<RunOnMainThread>b__0>d.MoveNext() in C:\projects\chummer\Chummer\Backend\Static\Utils.cs:Zeile 1173.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   bei Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   bei Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   bei Chummer.Utils.RunOnMainThread[T](Func`1 func, JoinableTaskCreationOptions eOptions) in C:\projects\chummer\Chummer\Backend\Static\Utils.cs:Zeile 1168.
   bei Chummer.WinFormsExtensions.DoThreadSafeFunc[T1,T2](T1 objControl, Func`2 funcToRun) in C:\projects\chummer\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:Zeile 705.
   bei Chummer.Program.ShowScrollableMessageBox(Control owner, String message, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton) in C:\projects\chummer\Chummer\Program.cs:Zeile 909.
   bei Chummer.CommonFunctions.<ConfirmKarmaExpenseAsync>d__54.MoveNext() in C:\projects\chummer\Chummer\Backend\Static\CommonFunctions.cs:Zeile 1532.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Threading.Tasks.ValueTask`1.get_Result()
   bei Chummer.CharacterCareer.<treFoci_BeforeCheck>d__324.MoveNext() in C:\projects\chummer\Chummer\Forms\Character Forms\CharacterCareer.cs:Zeile 17303.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:Zeile 616.

**To Reproduce**
1. Switch the Language of Chummer to German and restart Chummer ![Screenshot 2023-10-24 161844](https://github.com/chummer5a/chummer5a/assets/36237757/fad4b41f-a2c7-4104-ab9f-e31d562613dc)
2. Load the attached Charakter
3. Go to Street Gear (Straßenausrüstung) and bind the Qi-Focus select Improved Ability (Automatics), in German Verbesserte Fertigkeit (Schnellfeuerwaffen). 
![Screenshot 2023-10-24 161936](https://github.com/chummer5a/chummer5a/assets/36237757/45b2e995-f62b-4230-b95f-4cd0e9b50269)
![Screenshot 2023-10-24 162013](https://github.com/chummer5a/chummer5a/assets/36237757/ee073f96-f81d-4562-9c2d-ffee3dabf8a4)
5. Then I get the error message:
![Screenshot 2023-10-24 162034](https://github.com/chummer5a/chummer5a/assets/36237757/a9cd80e9-4a88-4d37-94d6-f598d17aadde)

**Expected behavior**
I would expect that it mark the Qi-Focus as bound and apply the bonus to the Automatics skill.

**Character File**

[TNT_export.txt](https://github.com/chummer5a/chummer5a/files/13116684/TNT_export.txt)

**Desktop (please complete the following information):**
 - Windows 10
 - Version e.g. 5.225.322

**Additional context**
It seems to depend on the language setting of Chummer. If I set language to English it works. It crashes if I set language to German

**Comment by DelnarErsike** [comment]
Note for anyone else: this bug/crash in the current Nightly does not require having set the program's language to German.
