### ISSUE TITLE
Chummer crashes if I open a character for export and language is German

### ISSUE THREAD

**Issue by Darilon** [chummer5a/chummer5a#5069]
**Describe the bug**
If I try to open a character for export and the language of Chummer is set to German, Chummer crashes. It does not show any error message. it just "disappears". I can export all my characers if I set the language of Chummer to English. I can even export them with a German character sheet as long as the language of Chummer itself is English.

**To Reproduce**
1. Switch the language of Chummer to German. Note that exporting the Character with a German sheet does not trigger the crash when the language of Chummer itself is English.
![Screenshot 2023-10-24 161844](https://github.com/chummer5a/chummer5a/assets/36237757/d16cfc75-2ca6-4e84-ad95-7e7cf7c231bb)
2. Restart Chummer
3. Open the attached character for export

**Expected behavior**
It would show the JSON character data.

**Character File**
[TNT_export.txt](https://github.com/chummer5a/chummer5a/files/13116928/TNT_export.txt)

**Desktop (please complete the following information):**
 - Windows 10
 - Version 5.225.322

**Comment by DelnarErsike** [comment]
Cannot replicate in the current Nightly. Closing this issue unless/until something changes.
