### ISSUE TITLE
Strength Crashing

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#5071]
**Describe the bug**
When I adjust Strength on a new character, Chummer freezes and then crashes

**To Reproduce**
1. Start a new character
2. Click to adjust Strength up from 1
3. See error

**Expected behavior**
Strength to go up by 1 per click

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 19045.3570

**Additional context**
It was working fine when I used it a couple of weeks ago, but I'm not sure if it was working before this last update.

**Comment by DelnarErsike** [comment]
Cannot replicate with the current Nightly. There were issues in older Nightlies that could have caused this, but those issues should now be fixed.

**Comment by HarleeKnight** [comment]
Even with complete deletion and brand new install it keeps happening. It freezes every time I adjust Strength... very frustrating. Thanks anyways.
