### ISSUE TITLE
Adding drone armor doesn't update drone statblock

### ISSUE THREAD

**Issue by nickschurch** [chummer5a/chummer5a#5077]
Adding the drone modification 'Armor (Drone)' to a drone doesn't update the drones armor rating in its stat block.

**To Reproduce**
1. add a drone (I suggest a Horizon Noizquito; armor 0)
2. add a modification tot he drone, selecting 'Armor (Drone)'
3. view stat block.

**Expected behavior**
upgrading the drone armor should be reflected int he dron stat block, just like it is for upgrading the pilot, for example.

**Screenshots**
![image](https://github.com/chummer5a/chummer5a/assets/2212398/5d31fcf4-a50a-489b-b860-ba9110aca1e3)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 5.225.0.0

**Additional context**
It's not drone model specific.

**Comment by DelnarErsike** [comment]
Fixed in d96ab02f29a2a43924bcdcfd580d2db999dd17f6.
