### ISSUE TITLE
Vehicle Similar Models?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#508]
Just wondering if would be possible to add the similar models for vehicles as per page 462 of SR5?
If I'm reading the rules correctly, it's just a matter of adding the same vehicle entries but with different names.

**Comment by joha4270** [comment]
HELL NO

*deep breath*

Adding the same item 5 times, based on a single table located somewhere? No, definitely not happening.

For now you can use notes, and someday in the future we display arbitrary names for items, but that will have to suffice, unless you feel mucking around in the data files yourself. Change the id's, use a guid generator.

**Comment by whatevs5** [comment]
Was just looking to have the data files updated. If I send you the data files, will you add them to one of your releases?

**Comment by whatevs5** [comment]
I updated vehicles.xml. What's the best way to get it to you. Can't attach it here, .xml isn't supported.

**Comment by chummer5a** [comment]
Just pull out the vehicles you've added and put them in a .txt file. As an
aside, you can just put them into a custom_vehicles.xml file and keep it in
your data folder, means you don't have to rely on us to put the content in
and it won't get overwritten when we make upstream changes.

**Comment by whatevs5** [comment]
Perfect. I was worried about being overwritten later on if I modified my own files. Here's the txt. file. It has all of the vehicle nodes I added.

[vehicles.txt](https://github.com/chummer5a/chummer5a/files/34606/vehicles.txt)

**Comment by joha4270** [comment]
now place a 
"\<chummer\>\<vehicles\>" before that, a "\</vehicles\>\</chummer\>" after that and save it in the data directory as custom_vehicles.xml

Not going to make it into the main repo

**Comment by whatevs5** [comment]
cool, thanks for the help.
