### ISSUE TITLE
'Add Location' For Vehicles Possible Bug? 

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#509]
The 'Add Location' function for vehicles is requesting that I first select a vehicle to add a location to. Is that expected functionality? Just like in the Gear Section, I would have thought that 'Add Location' would be a way for me to indicate where the vehicle is, as opposed to the location of something stored in my vehicle. Once I assign a location to a vehicle, I'm not able to add anything to it, as far as I can tell. The new location also does not show up as a place to store gear or weapons in those respective gear menus.

![image](https://cloud.githubusercontent.com/assets/15821037/11158198/9e75c77a-8a24-11e5-9f77-340e7343ff6f.png)

![image](https://cloud.githubusercontent.com/assets/15821037/11158212/b1917ebc-8a24-11e5-90b1-1aa733a53217.png)

**Comment by chummer5a** [comment]
In this case the Location field is expected to be used for things like
'Back Seat' or 'Pintle Mount'. You should find that you can drag things
into the Location using a right-click drag.

**Comment by whatevs5** [comment]
Got it.Thank you kindly.
