### ISSUE TITLE
Adding Custom Spell Categories Doesn't Work

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#5096]
**Describe the bug**
Attempting to make use of the following amends file results in strange behavior:

[custom_spells.xml.zip](https://github.com/chummer5a/chummer5a/files/13827617/custom_spells.xml.zip)

**To Reproduce**
Load up above amends file, and open a character who can learn spells. Buy Aqua Fictus.

**Expected behavior**
Aqua Fictus should show up in an "Alchemical Compounds" header in both Chummer as well as the PDF.

**Observed Behavior**
Aqua Fictus does not show up in Chummer at all, and in fact the expected Alchemical Compound header doesn't show up.

In the PDF, it _does_ show up, under an "Unknown" header.

**Screenshots**
![Screenshot 2024-01-04 at 12 12 32 AM](https://github.com/chummer5a/chummer5a/assets/1766631/13445292-6a54-4c16-b773-346f98f8d2da)

**Character File**
[Trash Panda.chum5.zip](https://github.com/chummer5a/chummer5a/files/13827652/Trash.Panda.chum5.zip)

**Comment by chummer5a** [comment]
Need to fix the sheets still, probably needs a different implementation. Should work fine in the treenode view though.
