### ISSUE TITLE
[Bug] Adding Bioware results in a busy indicator and eventual freeze

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#5102]
**Describe the bug**
When doubleclicking on genetic optimization (willpower) it is added to the cyberware list and the program triggers a continuous "busy" indicator (the cursor has the spinning circle icon that never goes away), and Chummer5a's performance degrades rapidly and eventually becomes completely frozen.

**To Reproduce**
1. Create a new character using Sum-to-ten (see details below as to the character I have been creating)
2. Click on 'cyberware/bioware'
3. Click on "add bioware"
4. Pick a piece of bioware and add it by either double clicking or clicking add.
5. See that it appears on the bioware list.
6. See that my cursor now has a spinning circle icon on it.

At this point, I can still mouse over buttons and have them highlight. Likewise, I can click on tabs to switch tabs; but after 1-4 tab switches, or after clicking any button (such as to add another piece of cyberware, or switching tabs to common and clijcking on the "add a quality" button), the cursor switches from "regular cursor with the small spinning circle" to "full spinning circle" and Chummer5a becomes completely unresponsive. So long as it is in the lesser busy state I can still close it, but once it switches to the larger busy state, closing via the task-manager is the only option. 

Effectivley, once I try adding a piece of bioware, the program quickly becomes less and less responsive and is completley frozen within 1-5 actions. If I don't do anything other than move the mouse, it remains in this busy but still responsive state for several minutes until I eventually take some actions and progress into a frozen state. Chummer5a never recovers no matter how long I leave it sit.

**Expected behavior**
When I add a piece of bioware it adds it to the list, adds its effect, and then is completely responsive to do something else.

**Screenshots**
Can provide if desired, but don't have one currently.

**Character File**
This is encountered through the creation of a new character. I use the pre-provided "Sum-to-ten" option to create an Elf Magician with the D-A-A-E-D priorities, choosing Astral Combat and Arcana. (I use the same setup every time I create a test character to provide a consistent test setup)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.335.398f

**Additional context**
Initially ran into this using a sum-to-ten profile with lots of extra rules and most of the books while adding genetic optimization.  
I have subsequently encountered it when using the default provided sum-to-ten profile while adding other bioware, such as bone lacing.

**Comment by Zitchas** [comment]
I just downloaded the update to .400 with the "clean re-install" option (I typically always use the clean upgrade option).

On first testing, I could successfully add bioware, but then incurred the freeze when I went back to the common pane and tried to add "prototype transhuman". 

On subsequent testing, tried adding "Bio Tatoos" with "Dragon" as the entry text, and that triggered the same "busy but not quite frozen" indicator, which again lead to complete freeze after switching a few tabs or clicking on a button. Likewise, trying to add positive qualities also got the same result when I tried adding "Accident Prone".

**Comment by DelnarErsike** [comment]
This bug was supposed to be fixed in .400, but I forgot to write a few extra lines to make the fix work. Please wait until .401 comes out and try to see if you can replicate the issue there.

**Comment by Zitchas** [comment]
Thanks! I will test and confirm once 401 comes out. I can close this once I have tested it. 

Thanks for working on Chummer5a! Very much appreciated.

**Comment by Zitchas** [comment]
Yes, it looks like that problem is resolved. Thank you!
