### ISSUE TITLE
Allergen Tolerance can be applied repeatedly against different allergies or the same allergie. But I can choose it only once

### ISSUE THREAD

**Issue by Knakriktsur** [chummer5a/chummer5a#5103]
**Describe the bug**
Allergen Tolerance (Bodyshop around page 163 can be applied repeatedly against different allergies or the same allergie. But I can choose it only one time in chummer.

**To Reproduce**
1. Go to '...' Cyberware & Bioware
2. Click on '....' Add Bioware
3. Scroll down to '....' Allergen Tolerance and edd it.
4. See error ->repeat steps and try to add for another Allergen Tolerance but it doesn`t apper in list anymore.

**Expected behavior**
In the Bodyshop rule book description (around 163) it is written that can be applied repeatedly aginst different allergies or the same allergie. But I can choose it only one time in chummer.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.225.0.0]

There has been 2 other reports but it has not been fixed jet. Please fix, thank you very much and have a nice day :)
https://github.com/chummer5a/chummer5a/issues/4072
https://github.com/chummer5a/chummer5a/issues/4041

**Comment by Knakriktsur** [comment]
Hi, do you need any more informations? :)

**Comment by Knakriktsur** [comment]
Well after I checked char as created I could chose it. I loaded the backup in creation mode and it also worked. Hopefully it was not a layer 8 problem, I`ll test that when I have the time. Very strange.

**Comment by DelnarErsike** [comment]
This is kind of just the same problem as #4041, as the specific way Allergen Tolerance is(n't) implemented produces side effects such as this one. Closing the issue.
