### ISSUE TITLE
Thrown Weapons Don't Seem to Exist

### ISSUE THREAD

**Issue by TheHunted1** [chummer5a/chummer5a#5105]
The title pretty much covers the issue.
In the Street Gear, Weapons section, if you click "Add Weapon", none of the thrown weapons are an option that exists. There isn't even a category for them in the dropdown.
Tested this in both the latest Nightly as well as the official release.

**Comment by EmmjayXII** [comment]
Thrown weapons are bought as gear, in the gear tab, and their stats are automatically populated into the weapons tab.
