### ISSUE TITLE
Qualities not showing up...

### ISSUE THREAD

**Issue by BanjoKorde** [chummer5a/chummer5a#511]
Sorry if this has already been posted, but for some reason I'm getting some qualities just not showing up.
As far as I can tell, I'm not getting any qualities post Core Rulebook. This goes for both positive and negative in character gen or after creation.

Running Build 0.5.176 - checked for updates without any luck :( 
Not sure if I've just missed something, but maybe someone else is having this issue?

**Comment by HaikenEdge** [comment]
Have you been into options to turn on all the other books?

**Comment by BanjoKorde** [comment]
Oh my... Well, that's embarrassing. They were not turned on, and turning
them on most definitely worked :)

Thank you, you guys have done an amazing job with Chummer :)

Thanks again,

Ben

On Sat, Nov 14, 2015 at 3:56 PM, HaikenEdge <notifications@github.com>
wrote:

> Have you been into options to turn on all the other books?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chummer5a/chummer5a/issues/511#issuecomment-156641094>
> .
>



-- 
I have a bowler hat
