### ISSUE TITLE
[bug] During character creation, spending points on increasing an attribute does not result in increased attribute

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#5112]
**Describe the bug**
When I create a new character, I can spend attribute points on attributes, but the actual attribute doesn't increase.

**To Reproduce**
1. Create new character just stock default options,.
2. Click on arrow to spend a point improving an attribute.
3. Look at the attribute total and note it has not increased
4. Look at the karma summary pane to see that it has counted those points as spent.
5. Go to skills tab and look at a skill that uses that attribute, and note it still sees it as "1"

**Expected behavior**
When points are spent to increase an attribute; that the attribute total go up by 1.

**Screenshots**

**Character File**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 5.225.440 (upgraded to it via clean re-install)

**Additional context**
unknown

**Comment by Zitchas** [comment]
Follow-up investigation:

If I use the arrows in the karma column to use karma to increase the attribute by a point, it will suddenly recognize the expenditures of attribute points in that attribute. 

So after having gone down the list and added and removed a karma-improvement from each attribute, it has now calculated them all correctly.

**Comment by Knakriktsur** [comment]
Have the same issue, 5.225.440. In creation mode load a character. Lowering attributes (minus karma) the first click it didn't lower the pints to the right where the actual attribute point (adjusted by Bio/Cyberware) is. But it gave the points on the very right side in the Karma overview back. **Save and reload showed the correct value** at the right where the actual attribute pint (adjusted by Bio/Cyberware) is. So it seems not to live update them when you click a button to lower/raise attribute.

**Comment by Knakriktsur** [comment]
Also there might be an other issue like that. During creation (human) I set CHA to 1. Then I lower it to 0. On the Connections tap it says I have 6 of 6 points free. After reducing CHA from 1 to 0 (Human have a standard of 1) it should say you have 3 of 3 points available (Formula to calculate points CHA*3 is right though). But save and load dosen't update to 3 of 3 either.

**Comment by Zitchas** [comment]
Re-testing on 5.225.441, and the main reported issue here appears to be fixed: Spending points on increasing an attribute works immediately without any problems, and does not require fiddling with the karma to get it to update. 

One oddity is that one time when I was just testing adding and subtracting values on the karma side, I managed to get it into a situation where it said I had zero karma and zero points spent on raising Charisma, but had a final Charisma value of 2. I think I may have been clicking really quickly or something - I have not been able to replicate it. 

Trying to replicate the Contacts issue described by Knakriktsur, and I cannot replicate the problem. Raising and lowering Charisma to various values with either points or karma, or combination of both, and the "contact points" updates to give the correct amount consistently.

@Knakriktsur For your most recent testing, have you updated to 225.441?

**Comment by Knakriktsur** [comment]
I`m also on .441 now and it works BUT the connection Karma points do not update in 441, see post above. If there is no reaction to it I`ll make a separate post to keep tings clean :).

**Comment by Zitchas** [comment]
Hmmm... Yeah, might be worth separating it. Might be related, might not, I'm not a good enough decker to figure it out.

**Comment by Knakriktsur** [comment]
Hm, I did a test with a new char and the connection Karma adjusts fine. So there might be something wrong with that save or something else. I`ll look into it. If I can reproduce it I`ll create a new case :)

**Comment by Zitchas** [comment]
Alright. Since this seems to be solved, then, I'll just save them the effort and close it. :)
