### ISSUE TITLE
Addition to Char Sheet? Stats for different ammo types?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#512]
The entries for weapons on the character sheets show the number of extra clips, but not the impact of using the ammunition loaded into those spare clips. It would be nice to have a row of stats for each of the types of ammunition I've purchased for the weapon. Impact of silencers would be nice here also.

**Comment by chummer5a** [comment]
Try the Fancy Blocks sheet. You should see a list of the ammunition at the bottom of the Ranged Weapons that lists the DV/AP effects. Aside from that it'd be a matter of tinkering with the standard character sheet; not particularly hard, just tedious.

**Comment by whatevs5** [comment]
Awesome! Thanks! Closing ticket.
