### ISSUE TITLE
Submersion Grade stuck at 2

### ISSUE THREAD

**Issue by Saelvarath** [chummer5a/chummer5a#5127]
No matter how many times you add a new Submersion Grade, it will never advance past grade 2

**To Reproduce**
1. Create a Technomancer character with enough karma to submerge several times
2. Go to the 'Submersion' Tab and click 'Add Submersion Grade' three or more times
3. you will have Grade 1, Grade 2, Grade 2, Grade 2, Etc. if you Selected an Echo it will be copied across all Grade 2 entries. Each grade past 1 will cost 16 Karma, Resonance Score will not improve.

 

**Expected behavior**
Submersion Grade should rise sequentially

**Screenshots**
![image](https://github.com/chummer5a/chummer5a/assets/11372109/c9548456-63fa-4ef1-b20b-a43d9f7617dc)

**Desktop **
 - OS: Windows 10 Home
 - Chummer Version  5.225.0

**Additional context**
If you load a character was already above Grade 2, it may work as intended once, but after that every rank Purchased will be 2 and Max Resonance score will drop.
if you open a character you added a submersion grade to in 5.225.0 in 5.216.0 it will start to increment  your submersion grade normally, but it will still start at 2.

I have tried this with freshly generated character in a couple different setting files with the same results

**Comment by chummer5a** [comment]
This is resolved in nightly builds and will be implemented in the next milestone release.
