### ISSUE TITLE
Accessory Suggestion For Gear - License?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#513]
How about making it so that a license can be added to a weapon (or other piece of gear) as an accessory for easy management?

**Comment by Iridios** [comment]
Licenses are logically tied (in game) to a characters ID.  I usually attach them as an accessory to a characters commlink along with their fake SIN.  It is possible to have the license without having the weapon, and it is possible to have a license for other equipment.

The core rules only have rules for fake IDs and Licenses as gear and require the player to label what the license covers.  This is the functionality that Chummer provides.  I would think it would add confusion to add licenses as accessories to weapons.

**Comment by whatevs5** [comment]
Fair enough. Thanks for taking the time to review.

**Comment by chummer5a** [comment]
This is actually a thing you can do already! Options > General Tab >
Miscellaneous Tab > Licence Each Restricted Item.

**Comment by whatevs5** [comment]
I saw that setting and tried it, but I couldn't see what effect it had.  I tried adding an Ares Predator V, and didn't see any differences in the gear section. I also viewed the Shadowrun5 and Gamemaster Summary character sheets and didn't see it there either. Where would I see the impact of turning that setting on?

**Comment by chummer5a** [comment]
With that setting disabled, the dropbox loads from licenses.xml. With it
enabled, adding a fake licence will give you a text dropdown that lists
every Restricted item you have. If you want a licence attached to your guns
it'd have to be an accessory, but that's more or less just a matter of
copying the Fake Licence from gear.xml and dropping it into weapons.xml
under the accessories category.

**Comment by whatevs5** [comment]
Okay, I see what you mean. That's good to know. So you're basically managing license groups (like Private Investigator) vs. Licenses for Individual Weapons.

So to get the hierarchy right, I'd have to buy a commlink, add a fake sin to it, then add the licenses to the fake sin. I guess that's all of the license management in one place really. Thanks.
