### ISSUE TITLE
Shapeshifter Career Mode Crash

### ISSUE THREAD

**Issue by grillsoup** [chummer5a/chummer5a#5137]
Chummer crashes in the process of saving a Shapeshifter character into career mode

1. Create a Shapeshifter character (Doesn't matter the type or the associated metavariant)
2. Mark as created and save
3. Crash occurs after confirming starting nuyen

File I was using to test:
[ShifterCrash.txt](https://github.com/chummer5a/chummer5a/files/15172497/ShifterCrash.txt)

 - OS: Window 11
 - Version 5.225.496

This error does not occur in version 5.225.0

**Comment by DelnarErsike** [comment]
Could you attach the crash log json file?
