### ISSUE TITLE
Select a Spell > Add and More - Keep Last Open Category?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#514]
Currently it closes all spell category menus after I click the Add and More button in the Select a Spell menu. Just wondering if it would be possible to remember which categories I had open, and keep the selection box scrolled to the last spell I selected.

If that's not possible, how about changing the interface to allow selection of multiple spells at once. Maybe with checkboxes?

**Comment by chummer5a** [comment]
Implemented in 5.178.

**Comment by whatevs5** [comment]
Thanks! Very nice!
