### ISSUE TITLE
German Martial Arts missing Techniques

### ISSUE THREAD

**Issue by Saelvarath** [chummer5a/chummer5a#5140]
All Martial Arts introduced in State of the Art ADL are missing the Strike the Darkness Technique.

Additionally 
Esdo is missing Oaken Stance (vs Knockdown),
Sternschutz Tactical & Alpine Wrestling are missing Oaken Stance (vs Charges)

**Comment by Saelvarath** [comment]
Also, Martial Arts Styles and Techniques should cost 2500¥ and 1500¥ respectively

**Comment by DelnarErsike** [comment]
Alpine Wrestling, Esdo, and Sternschutz Tactical already have the Oaken Stance technique, which applies in general and is not bought with specificity the way it is with, e.g., Opposing Force.

I am unaware of any official rules that allow you to flatout purchase martial arts and/or techniques with nuyen.

**Comment by Saelvarath** [comment]
They are not showing up as options on any of my characters in either v5.225.0 or v5.216.0

According to the the  "Learning Martial Arts" sidebar in Run & Gun p.128 there is an _additional_ cost of 1500 nuyen to learn a new technique and 2500 nuyen for a new style.

I'm not seeing any changes to Oaken Stance in the Errata and both my copy of Run & Gun and a translation from the German Kampfkünste say that you only get one of the two effects of Oaken Stance, depending on Style. 
Jogo Du Pau also specifically gets both versions of Oaken Stance

![example](https://github.com/chummer5a/chummer5a/assets/11372109/34bb4723-f9ab-419c-9195-7175e8df13c5)
