### ISSUE TITLE
Submersion grade

### ISSUE THREAD

**Issue by sasquatch15431** [chummer5a/chummer5a#5152]
**Describe the bug**
Eseentially it happens sometimes when you try and have a character submerse as a technomahcer. Every grade past 1 results in an inability to go past grade 2 and an inability to ftuher raise resonsance. Now only further adding grade 2 submersions. without moving forwards to grade 3. 

**Expected behavior**
This is opposed to submersion supposed to be working subquentially.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]
[technomancer_rigger.zip](https://github.com/user-attachments/files/16683764/technomancer_rigger.zip)

**Additional context**

**Comment by DelnarErsike** [comment]
Fixed in d179491ec3c4371169f6667c92b7a89fe7d4e6a1.
