### ISSUE TITLE
Wrong armor calculation

### ISSUE THREAD

**Issue by KitsuneOfKamis** [chummer5a/chummer5a#5154]
Armor is not calculated properly when using Rheingold Pro Tec Plus Suit with Rheingold Pro Tec Plus Mantle with the Custom Fit.
Combining them should be 9 +3 for Mantle bonus when worn together = 12, but Armor is displayed as 11.

I tried it with a friend and it calculates correctly on the stable version for 5.225.0

**To Reproduce**
1. Got to Armor
2. Add Rheingold Pro Tec Plus Suit
3. Add Rheingold Pro Tec Plus Mantle
4. You are being asked for the armor set combo: Choose Rheingold Suit
5. Armor is displayed as 11.

**Expected behavior**
Armor should be displayed as 12. 9 from the Suit and a +3 bonus from the Mantle.

**Screenshots**
Screenshot attached
![Screenshot 2024-09-01 001838](https://github.com/user-attachments/assets/5fa86be5-0758-407e-88f0-aac1f1c71877)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.225.622

**Comment by chummer5a** [comment]
By default, Chummer caps bonus armour to your Strength value. There's an optional rule to override that behaviour.
