### ISSUE TITLE
Vehicles cannot be named

### ISSUE THREAD

**Issue by KitsuneOfKamis** [chummer5a/chummer5a#5155]
**Describe the bug**
When a vehicle menu is opened and you want to rename it, it shows an error and that a vehicle has to be chosen first.

**To Reproduce**
1. Add a vehicle
2. Right click the vehicle
3. Click Rename Vehicle
4. Error pops up

**Expected behavior**
Should be able to give vehicle/drone a new name

**Screenshots**
![Screenshot 2024-09-01 002311](https://github.com/user-attachments/assets/fe22aac7-5fba-4226-9ccd-b72d0ca70770)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 5.225.622

**Comment by FauxBerry** [comment]
Also having this issue. Seems to only happens in Career mode for me. Create mode vehicle renaming works just fine. 
Version 5.225.695
