### ISSUE TITLE
Please add the 'Numinous' Perception Specialization

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#516]
Do you guys feel like adding 'Numinous' as a Perception specialization? It's to specialize in perceiving magic, mentioned in SR5, 314. Even though it's mentioned on p314, it's not listed as a specialization in the skills section on Pg 133. That's probably why you guys haven't listed it in the drop down.

As a work around, I've been typing it in manually in the specialization field, just thought you may want to add it. It's a thing, I swear.

http://forums.shadowruntabletop.com/index.php?topic=18300.5;wap2
http://forums.dumpshock.com/lofiversion/index.php/t39006-250.html
http://archive.4plebs.org/tg/thread/35586381

**Comment by chummer5a** [comment]
Included in 5.179.
