### ISSUE TITLE
Language Skills Labeling

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#517]
Languages in the Knowledge Skill pick list are hard to find unless you know exactly what to look for.

Would it be possible to add a prefix of 'Language:' to the language skills in the Knowledge Skill pick list? The Area Knowledge group of Knowledge Skills are labelled in a similar fashion. Because they have that prefix, they're easier to find. I've updated  a copy of the skills.xml doc with the the suggested prefixes. Please see that below. I've also included an image for clarification. If anyone's feeling excited about languages, another option could be to have a drop down menu just for them.

[skills.txt](https://github.com/chummer5a/chummer5a/files/35681/skills.txt)

![image](https://cloud.githubusercontent.com/assets/15821037/11185861/dfcba0c6-8c4c-11e5-85f5-cf0730144d19.png)

**Comment by chummer5a** [comment]
Added in 5.178.

**Comment by whatevs5** [comment]
Hey guys, I appreciate the hard work. Just one thing about the recent change for languages. I see that you've appended each knowledge skill with (<type>). While I can see, and appreciate, the change the same problem described in my issue remains. The languages are still broken up because the menu items are displayed in alphabetical order.  I've updated a skills.xml file taken from Build 178 and prepended each language with 'Language: '. If you're open to it, please consider using these changes.

[skills.txt](https://github.com/chummer5a/chummer5a/files/43998/skills.txt)


![image](https://cloud.githubusercontent.com/assets/15821037/11400628/72b8ddac-935c-11e5-9899-ba8329ededd3.png)

**Comment by whatevs5** [comment]
This ties in with .#542
