### ISSUE TITLE
Unhandled Excpetion Errors when Purchasing Commlinmks/Cyberdecks (Build 177) 

### ISSUE THREAD

**Issue by Kyoto-Kid** [chummer5a/chummer5a#522]
Selecting any commlink for purchase results in an Unhandled Exception Error.

Clicking the "Continue" button on the Error Dialogue box places the Commlink in the character's Gear inventory but without any attributes and with a Device Rating of "0".

The Item Quantity field indicates a quantity of "10" and is "locked" (greyed out).

The error also pops up when purchasing any Cyberdeck.

**Comment by chummer5a** [comment]
Fixed in 5.178.
