### ISSUE TITLE
Quick Enhancement Suggestion 'Add Gear' for Speed Loaders

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#524]
1 - Browse to Weapons menu
2 - Add a Ruger Super Warhawk
3 - Right click on Ruger Super Warhawk, select add accessory > speed loader
4 - Right click on recently added speed loader, choose 'Add Gear'
5 - Get a 'Cannot Add Gear' popup.

Would it be possible to add the appropriate <allowgear> nodes to the speed loader weapon accessory? It would essentially be the same nodes that are present for the Spare Clip Weapon Accessory.

![image](https://cloud.githubusercontent.com/assets/15821037/11285576/313e5712-8ede-11e5-96f2-6b6828a1ce25.png)

**Comment by chummer5a** [comment]
Essentially irrelevant as of 5.179, as speed loaders and spare clips don't need to cache ammo.
