### ISSUE TITLE
Edge Currently Does not Subtract from Special Attributes

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#530]
While using Sum of X and Priority character creation systems, adding Edge in the Base Column doesn't remove a corresponding amount from the Special Attributes column. Points added to Magic and Resonance still subtract correctly, so I'm not sure what's happening there.

**Comment by chummer5a** [comment]
Nuts, I thought I fixed that.

**Comment by chummer5a** [comment]
Fixed in 5.178.
