### ISSUE TITLE
Weapon Mods causing errors

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#531]
Currently when adding weapons or mods to a character there are quite a few unhandled exceptions. These are caused by the Ares Predator V, Longbarrel, and Extended Clip, just to name a few.

**Comment by chummer5a** [comment]
There seems to have been an issue with the auto-updated version of the weapons.xml file. Could I get you to extract this file into your data file and see if it still happens? https://my.mixtape.moe/nosoiu.zip

**Comment by whatevs5** [comment]
I gave this a shot just a minute ago with 545 and 177. Seems to work okay in both versions.

**Comment by Verecoth** [comment]
Sorry, but I'm not downloading some random file with no way of knowing what's in it. I mean, I love to help, but I can't do that.

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/blob/master/Chummer/data/weapons.xml Copy that content into the weapons.xml file then.

**Comment by chummer5a** [comment]
fixed in 5.178.
