### ISSUE TITLE
Weapon Capacity and Load Type Nodes (Added and Attached)

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#532]
Please see attached a modified weapons.xml file from Nightly-v1.0.545 with nodes added specifically for ammo capacity and loading type, for each weapon.

[weapons_capacity_and_reload.txt](https://github.com/chummer5a/chummer5a/files/42002/weapons_capacity_and_reload.txt) (modified weapons.xml file)

Right now, it seems as though the reloading method for each weapon is identified in weapons.xml using the <ammo> node, specifically using (c), (m), (cy), (belt), or (m) other text notation. I'm guessing (please let me know if I'm wrong) that these values are for display to the user only and are not recognizable by Chummer in-app as specific values.

I've added magazine capacity and reload method(s) for each ranged weapon. Example:

			loadtypes
				               cylinder 9 cylinder
			loadtypes

Please discard if you feel there's no value in adding these nodes. I'm hoping that it will make some enhanced features simpler to implement down the road.

The values were taken from pg. 163 sr5. The total node values are below:
- clip
- cylinder
- magazine
- break
- muzzle
- belt
- drum
- bow
- internalsource

**Comment by whatevs5** [comment]
If anyone plans to use the modified .xml file. Please keep an eye on the following weapons. I don't yet have the books for them. Hopefully I got the node values right, but I have no way to confirm:

Ares Lancer MP Laser
Ares Archon Heavy MP Laser
Pain Inducer
Springfield Model 1855 Reproduction

**Comment by chummer5a** [comment]
There's some stuff that would break by using this, but it's mostly just a formatting issue. I'll look into fixing this up next time I'm fiddling with ammo.

**Comment by whatevs5** [comment]
Fair enough. I wasn't sure how you would need / want to have it in there. If you'd like, I can do the work to change the formatting in order to meet your needs. Please let me know if you'd like me to change the formatting and, if so, how I should format those nodes.

**Comment by whatevs5** [comment]
Just checked code in clsEquipment.cs. I'm wrong. You guys are checking the values in the ammo nodes and translating the text string in them to recognize the designations from pg. 163 sr5. Oh well, should have checked it before adding nodes. Thanks for reviewing.
