### ISSUE TITLE
[0.5.177] Edge increases are not subtracting special attribute points

### ISSUE THREAD

**Issue by mriswithe** [chummer5a/chummer5a#535]
Unsure if the specific steps are necessary, but this is how I got there. Basically edge increases aren't costing "Special" points.

In other news apparently I suck at markdown. See Priorities for evidence.
Steps to reproduce:

1. DL 0.5.177 from github releases
2. Select all sourcebooks except the two German books
3. Create new priority build character, standard
4. Priorities:

A Metatype - Human
B Attributes
C Magic - Magician
D Skills
E Money

5. Increase edge on under the "Base" column
6. Observe no change to "Special Attributes" on the right under build summary.
7. Increase Magic stat under the "Base" column
8. Observe special attributes available on right decreasing normally.

**Comment by chummer5a** [comment]
Yeah, there was a logic fail in the edge calculations. It's fixed in 5.178.

**Comment by mriswithe** [comment]
Cool, roll back to 5.176 for now then until 5.178 comes out?

**Comment by mriswithe** [comment]
AGH I SUCK AT GIT

**Comment by chummer5a** [comment]
5.178 *should* be out tonight, so it's up to you really.

**Comment by mriswithe** [comment]
Oh neato, thanks for the help! Will close this on purpose now. Unfortunately my programming experience is Python/Bash on Linux, so helping out on this project isn't that realistic for me. I appreciate the work you/the group does!
