### ISSUE TITLE
Changing Calendar Format

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#538]
I love the calendar for making notes in character about what happened during a sessions. But with each entry being a week if you go into any real detail it can become a MASSIVE entry.

Could there be a way to decide how much time passes for an entry? Like set it so each entry is 12 hours, one day, one week, etc?

I'm not sure how difficult this would be and I can't imagine it would be high on the priority list, but it would make me happy.

**Comment by chummer5a** [comment]
As is it would be a fairly decent amount of effort to rework, the current
structure is pretty rigid. I can look into it, but it won't be an urgent
priority.

**Comment by prismatic-mind** [comment]
An other way to make it would be a manual set of the date/time and duration.

When adding entry, we fill date and duration (optional).

The list would be a one line entry with date / title or first text line

The currently selected entry height would be increased to show all text (with a max line limit and while reducing other entries)
or
A pop up window like it is currently.

The "week" automatic calendar is quite painfull to use, we don't have usual calendar date with month and day.
And we would not need to add lots of empty lines.

=> More flexible and more user friendly :)

**Comment by chummer5a** [comment]
The simplest method is to just integrate a [calendar control](https://www.codeproject.com/kb/docview/winformscalendarview.aspx), provide the ability to fall back to text-only and create a shim to manage the existing calendar entries into whatever new structure we come up with for it to accommodate daily entries. There are some specific enhancements I'd like to implement that would make that slightly awkward or require another interface for adding calendar entries though, so I'd prefer to build something from scratch that ticks all the boxes without extra components.
