### ISSUE TITLE
Bug - Special Attributes not Updating

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#540]
Step 1 - Click create new character button 
Step 2 -Choose priorities: ACBDE, dwarf, talent adept 6 magic Click okay.
Step 3 - Change Edge from 1 to 6.

Bug - Special Attributes on right hand side not updating

![image](https://cloud.githubusercontent.com/assets/15821037/11398319/e3113798-934d-11e5-9bc0-329a22ad5062.png)

**Comment by chummer5a** [comment]
Is this in 5.177 or 5.178?

**Comment by whatevs5** [comment]
my bad. just tested 5.178. Couldn't replicate. Closing ticket. Thanks for the last category hold open when clicking 'Add & More' btw.
