### ISSUE TITLE
Build 178 Bug - PACKS Vehicles Price Wrong

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#541]
Step 1 - Click on 'Vehicles and Drones' Tab
Step 2 - Click on 'Add Vehicle'
Step 3 - Click on 'Yamaha Growler'. Click okay. price listed as 5,000.
Step 4 - Create new packs kit for vehicles, with growler.
Step 5 - Create new character. 
Step 6 - Add recently created PACKS kit for vehicle.
Step 7 - Click 'Vehicles and Drones' Tab. Price for Yamaha growler listed as 7k instead of 5k.

![image](https://cloud.githubusercontent.com/assets/15821037/11398981/5271f9e8-9352-11e5-918c-44ad0f1485b3.png)

**Comment by rabbitslayer4** [comment]
It looks like the cost for the growler is working but it is adding a 2000 charge for the sensor array where when creating the pack it doesn't include that cost originally. Is that correct?

**Comment by rabbitslayer4** [comment]
From what I see the add code when creating the character doesn't add the cost of the sensor array when initially adding the bike. But, when it comes in from the custom pack then it does calculate the sensor array's cost.

**Comment by chummer5a** [comment]
More or less, yeah. I haven't had a lot of time to take a look at the packs, I think there were some shortcuts taken originally with the data that don't work anymore.

**Comment by rabbitslayer4** [comment]
This should be resolved with the latest checkin and merge...

**Comment by joha4270** [comment]
Just to make sure, you are talking about #643 ?

**Comment by rabbitslayer4** [comment]
Yep

**Comment by joha4270** [comment]
Seeing as i just merged that one, i'm going to close it.

In the future, consider doing [this](https://help.github.com/articles/closing-issues-via-commit-messages/) instead. _sometimes_ i do it even if i try to remember it each time-
