### ISSUE TITLE
Knowledge Skill Labeling

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#542]
Maybe it's just me, but I feel like Knowledge skills should not be labeled by category with the exception of the Language skills because knowledge skills are fluid in terms of how a character views them; skills like Small Unit Tactics might be an interest skill for some characters, but for a soldier, that would be a professional skill, not an interest skill, and adding the category, the same way Police Procedure could be any variation of Academic, Interest, Professional or Street knowledge.

**Comment by whatevs5** [comment]
Don't we have the option to adjust that with the drop down menu beside the 'delete' button?

![image](https://cloud.githubusercontent.com/assets/15821037/11429128/a92cbddc-9441-11e5-8a26-d70cc410087b.png)

**Comment by HaikenEdge** [comment]
We do, but in the most recent update, each skill is followed by (Skill Type) in the name, which becomes a hassle when you have six or seven skills you have to delete the label from.

**Comment by whatevs5** [comment]
Ah. I see what you mean. Good point.

![image](https://cloud.githubusercontent.com/assets/15821037/11429574/e4237cae-9447-11e5-969f-9d8e946be95c.png)

**Comment by chummer5a** [comment]
It's a minor visual bug; if you reload the character it should change the name to the proper value. Works properly for me, is it not working for you?

**Comment by HaikenEdge** [comment]
It works. I generally just don't reload to check, because I just delete the label, which I find extraneous in the first place.

**Comment by chummer5a** [comment]
Mm, fair point. I might make it a global option to show it or not.
