### ISSUE TITLE
Special Attribute Points Do Not Seem Tied to Edge

### ISSUE THREAD

**Issue by irthinker** [chummer5a/chummer5a#543]
1. Started a character with Priority system, standard defaults.
2. Adjusted Edge
3. No change in Special Attributes, no constraint on ability to adjust Edge
4. If I start a Mundane Human with Priority D for race (3 Special Attribute points), I am able to add more than 3 points to Edge.

**Comment by irthinker** [comment]
Note: when I create a Magic character, points added to Magic rating DO have the expected coupling to Special Attributes points.

**Comment by HaikenEdge** [comment]
Are you running 0.5.178? It's been corrected in that version, but I don't think automatic updates is updating to that version, so it needs to be updated manually.

**Comment by irthinker** [comment]
I, and my group, used Chummer 5a for the first time this weekend.  We all downloaded the latest release, which was 5.177.  Thanks for the note, I will let my group know!
