### ISSUE TITLE
Can't Add Weapon Modds/Slotless Accessories

### ISSUE THREAD

**Issue by IamAlphaGeek** [chummer5a/chummer5a#551]
https://gyazo.com/55567052bb3fe94553a8e4efe14fde22

This Happens whenever you try to add a weapon accessory that doesn't have a designated slot or a weapon mod this window pops up.  Only recently started happening but it's pretty inconvenient.

Almost forgot, this happens in both creation and career mode, was not fixed by updating, and is a problem on all of mine and my roommate's computers.

**Comment by chummer5a** [comment]
Fixed in 5.178. https://github.com/chummer5a/chummer5a/releases/tag/5.178

**Comment by IamAlphaGeek** [comment]
Fixed the problem but a lot of the accessories and mods are no longer available.

**Comment by chummer5a** [comment]
Can you give me an example? Weapon you're working with, mod you're trying
to add, etc.

**Comment by IamAlphaGeek** [comment]
For example, I can't add Sling, Customized Look, Underbarrel Weight, or any of the Advanced Safety or Powered Disassembly mods/accessories.  There are probably others but those were things I was looking at.

**Comment by IamAlphaGeek** [comment]
On a Mossberg, sorry

**Comment by IamAlphaGeek** [comment]
https://gyazo.com/077a27f7a444a469292043704efb8e09

**Comment by IamAlphaGeek** [comment]
Please disregard all complaints, I'm just dumb.  It was just set to only the core.  Sorry about that.

**Comment by chummer5a** [comment]
Haha, I thought it might be something like that. No worries.
