### ISSUE TITLE
Issues in life modules with skill groups erasing previous individual skills

### ISSUE THREAD

**Issue by E-Strange** [chummer5a/chummer5a#553]
was making a decker, with UCAS general, Part of the Machine, Hacker Club and Community College (computer science).  all the skills added fine until I got the group skill from the community college, and it overwrote my computer skill back to 1.

**Comment by cchopps** [comment]
Just ran into this myself with a different skill group. added Shadow Work (Face) and it reset all the Influence Skills to 3.

**Comment by chummer5a** [comment]
Should be functioning properly in current builds.
