### ISSUE TITLE
Life Modules

### ISSUE THREAD

**Issue by cchopps** [chummer5a/chummer5a#554]
Nationality - CAS is missing Etiquette 1 from the Universal Skills (RF p.66)

Formative Years - White Collar - The Etiquette Specialization doesn't show up and if you add one it deducts karma.

Further Education - Military Academy is missing the Military Rank Quality

**Comment by E-Strange** [comment]
I have coded the Etiquette fix and Rank fix, but the specialization is beyond me so far.  I have ideas, will try to implement them and see if it works.

**Comment by cchopps** [comment]
Cool!

I stumbled across something else, but maybe it needs a new thread. If you are a Mystic Adept and choose Magical Education you are suppose to be able to choose to add 1 rank to either the Magician or Adept skill choices. That option was missing.

**Comment by OLStefan** [comment]
Part of #2000.
