### ISSUE TITLE
Special Points and Edge Issue

### ISSUE THREAD

**Issue by Mordoth1** [chummer5a/chummer5a#557]
I am using version .178 to create a character for Runnerhub using the Priority system.
I've created a human with race priority D, and used the special point for increasing MAG to 7 using the Exceptional Attribute Quality for MAG.

When I try to increase EDG using Karma during character creation, from 2 to 3, it calculates the cost as 16 Karma (instead of 15) in the Display on the right hand side, but in the running total of available karma at the bottom it displays something very weird, i.e. I had 36 karma available, increased EDG from 2 to 3, and then it said I had -29 Karma.  Another time, same scenario it then said I had -89 available karma.

Another another build, I had a human with 3 special points available, and spent 2 on MAG, and increased EDG by 1, but when I increased EDG, it didn't subtract it from the available special points in the right hand pane.

Both of these scenarios happened while I was creating a new character.

**Comment by chummer5a** [comment]
I can't replicate this; can you send me an affected character file?

**Comment by Mordoth1** [comment]
Sure, how do I get the file to you?

**Comment by chummer5a** [comment]
I generally use https://mixtape.moe/ for this sort of thing.

**Comment by Malkleth** [comment]
I am also having at least the second issue. Here is an affected file.

Note I sent this to a friend of mine who says it is working normally for him; on load he sees -x special points. For me, adding and removing Edge (magic is fine) does not alter the Special Points
[bugtest.zip](https://github.com/chummer5a/chummer5a/files/53044/bugtest.zip)



The difference was that I auto-updated and he downloaded a fresh version of chummer.

**Comment by chummer5a** [comment]
Autoupdater's broken, I'm rewriting it at the moment. Turns out there's a limitation on the number of files that can be downloaded from a Dropbox account in a day.
