### ISSUE TITLE
% to Pay in Lifestyles not working

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#558]
Was creating a character with a Trust Fund; when I went to add a lifestyle for the Trust Fund, I set it to 0% to pay, but it still subtracted the amount from the character's wealth.

**Comment by cchopps** [comment]
You have to use the Advanced Lifestyle option to select trust fund.

**Comment by chummer5a** [comment]
Trust Fund should actually automagically handle all of that for Advanced Lifestyles; I tend to ignore the basic ones, so I'll review that.

**Comment by HaikenEdge** [comment]
I generally avoid the advance lifestyles unless the GM specifically says they're in play, since Advanced Lifestyles is a variant rule. Furthermore, it was less the Trust Fund that was causing the error, but that, when I set the payment % to 0 for a basic lifestyle, it was still charging me the full price, which shouldn't be happening, regardless whether I had Trust Fund or not.

**Comment by chummer5a** [comment]
Fixed in 5.179.
