### ISSUE TITLE
Small Issue - Bust - a - Move Drone

### ISSUE THREAD

**Issue by xlorxpinnacle** [chummer5a/chummer5a#562]
Hello, thanks for your hard work.

In the Vehicles section, the Bust-a-Move drone is listed as availability 50 by chummer (which makes it impossible to take at character generation) but its real availability is --, which should be treated as zero. I was able to update the proper xml file, but I just thought that it could be updated for Chummer as a whole whenever the next update comes.

**Comment by chummer5a** [comment]
Ha! Fixed in 5.179. Release should be this weekend sometime.
