### ISSUE TITLE
Special Attributes not going down

### ISSUE THREAD

**Issue by VE6CPU** [chummer5a/chummer5a#563]
I'm using v0.5.177 (just auto updated).  I'm creating an edgeomancer type character.  I selected C for metatype so he has an extra 5 special points to use.  When I Base column to increase edge it still shows special attributes in the right hand pane as 5 of 5 not 0 of 5.  It won't let me put more then 5 extra into edge so that still works.  Does this even after I save and close Chummer5.

**Comment by VE6CPU** [comment]
Just an update.  I created a character with D for metatype and so only 3 special points when human.  It still allowed me to go to 7 edge and still showed 3 of 3 in the right hand pane.

**Comment by Skarablood** [comment]
Try manually updating to 5.178.

**Comment by chummer5a** [comment]
Resolved in 5.178 patch. Closed pending other information.

**Comment by VE6CPU** [comment]
The patch worked so that now it decreases special attributes when assigned to edge (haven't tried with a magic user).  But it doesn't save this information.  When I reload the character edge is back to the metahuman default and special attributes are at their full unallocated amount.  I am now using v5.179 from the nightly builds.
