### ISSUE TITLE
Integral weapon  accessories don’t take up mount locations.

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#566]
Thanks for Mod Slot System, please check this from Core Book Page 417 and add this to the System.

Mounts: There are several places where a weapon accessory can be 
attached to a firearm: underbarrel, barrel, or top-mount. Only one 
accessory can be attached to a particular mount. Integral accessories 
(those that come with the weapon) don’t take up mount locations.

Please check Foregrip Mount in Errata from Run and Gun.

P. 52, FOREGRIP MOUNT CLARIFICATION
The second sentence of the description of the foregrip 
should be changed to read as follows:
“It can be mounted on the Barrel or Underneath slots, and 
it can not be used on Pistols and Hold-outs.”

Link to the Errata:
http://cdn.shadowruntabletop.com/wp-content/uploads/2014/09/E-CAT27002E_RG-Errata.pdf?b979cc

And Big Thanks for your great work on Chummer5.

**Comment by chummer5a** [comment]
Foregrip will be fixed in 5.179. Integral weapons should already occupy the Internal slot by default, as they're not set to take up a mount.

**Comment by McRipolo** [comment]
At version 5.178 integral accessories (those that come with the weapon)block the slots for other accessories.

Example the Yamaha Raiden:
The weapon has a internal silencer, so you should be abel to add a gasvent 1-3, but you dont get it in the selection window.

**Comment by chummer5a** [comment]
Whups. Fixed in 5.179.
