### ISSUE TITLE
Some weapons appear as Chummer.listitem

### ISSUE THREAD

**Issue by TheRealNamikaze** [chummer5a/chummer5a#567]
I've tested this out on several computers, all with the current build (0.5.177).

When adding certain weapons (whether by searching for them or browsing for them) they show up as Chummer.listitem.  Specifically, the whole section of Machine Pistols has this bug.  Additionally, it results in an Unhandled Exception error when attempting to navigate to various weapons that show this bug.

I feel like this might be an error on my machines, something with the databases perhaps?

**Comment by HaikenEdge** [comment]
The current build is 0.5.178. You'll need to download it manually, because the automatic updater is currently broken.

**Comment by TheRealNamikaze** [comment]
Well that explains that.  Let me try the new version.  If that resolves the issue, I'll close the ticket.
