### ISSUE TITLE
style: background-color not printed

### ISSUE THREAD

**Issue by SEETechWolf** [chummer5a/chummer5a#568]
In the xsl when using background-color in the css style for the td tag the color is not printed.

It shows up in the preview Window but not on the actual print out.

As example in the original character sheet background-color ist used for the footer of a section.

**Comment by SEETechWolf** [comment]
I found a work arround:
-save as html 
-open in a web browser
-in print preview options choos "print backgroungd colors"
-then print

**Comment by chummer5a** [comment]
Technically speaking not a Chummer problem; open up Internet Explorer
and enable
background printing <https://support.microsoft.com/en-us/kb/296326>.  I'll
be including a shim to make it work independently of those settings at some
point, but I don't expect that to be until after the new year.

**Comment by SEETechWolf** [comment]
Thanks...
Just noticed that in this context
tr:nth-child(odd) {
    background: #eee
}
is not working in preview... is css3 not supported?

**Comment by chummer5a** [comment]
The Web Browser control uses your locally installed version of Internet
Explorer to render the page. Provided you have IE10+ installed, you should
have access to CSS3 in the character sheet.

**Comment by SEETechWolf** [comment]
Sadly this is not the case. I have IE11 installed.
See attached files.
Previe in Chummer and saved as HTML and opend in IE11.
![2015-12-07 17_12_15-charakter betrachter](https://cloud.githubusercontent.com/assets/16180461/11632166/22e51a6c-9d06-11e5-81e9-cd2b3e05cd95.png)
![2015-12-07 17_12_50-torsten rheinhardt - internet explorer](https://cloud.githubusercontent.com/assets/16180461/11632167/22e612dc-9d06-11e5-85e3-881ea8f5859d.png)

**Comment by chummer5a** [comment]
Well that's... interesting. Hrm. Can you send me the your sheet to test out?

**Comment by SEETechWolf** [comment]
Sure... how can I send it to you?
It's not allowed to attack here .xsl or .zip

**Comment by chummer5a** [comment]
Email it to chummer5isalive@gmail.com or upload it to https://mixtape.moe.

**Comment by SEETechWolf** [comment]
I mailed you the file.
If you do bugfixing in this part.. would it be possible to use the real print preview?
So one would see tha actual width of the page and the page breaks?
This would be a nice to have ;)
