### ISSUE TITLE
3 Little Issues

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#570]
Hello! 3 Things I've found

1) Ares Duelist does not add extra auto soft "This drone comes with a unique Rating 
3 Targeting (Swords) autosoft" SR5e 466
2) Vampire quality does not add the extra +1d6 initiative
3) Vampire quality also doesn't adjust the inherent limits for attributes.

**Comment by chummer5a** [comment]
Duellist fixed in 5.179. The modification to attributes I've just realised is going to be a nightmare, may need to do some terrible things to make that work.

**Comment by chummer5a** [comment]
Metatype Attribute Table: RF 153.

May need to alter the specificattribute improvement code to support setting a specific value, or create metatype-specific qualities. Alternatively, some kind of code to change the metatype independently of the standard Priority selection.
