### ISSUE TITLE
Invalid german translation for positive quality

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#576]
1. The german core rolebook lists a positive quality "Bewegungstalent" for 7 karma on page 84.
Chummer shows a positive quality "Natürlicher Athlet" with source SR5 but without page. The core rolebook does not list such a quality. Due to the same karma cost (7), I assume that this is the quality in question and it's german name translation is invalid.

2. The german core rulebook lists a positive quality "Natürliche Härte" for 10 karma on page 85.
Chummer shows a positive quality "Resistenz gegen Signalsptzen" with source SR5 but without page. The core rolebook does not list such a quality. Due to the same karma cost (10), I assume that this is the quality in question and it's german name translation is invalid.

**Comment by chummer5a** [comment]
Since I don't speak German, I'm going purely off what was put into de_data here. Natürlicher Athlet is the Natural Athlete quality, on page 75 of the English core rulebook.

Resistenz gegen Signalsptzen is the Natural Hardening quality, page 76 of the English core book.

**Comment by McRipolo** [comment]
"Natürliche Härte" is "Tough as Nails" in the german and englisch version of Chummer, is not translated yet.

**Comment by holgerschlegel** [comment]
I have no access to an english rulebook. But the german rulebook not contain positive qualities named "Natürlicher Athlet" and "Resitenz gegen Signalspitzen". Both names are looking like a word-by-word translations.

To make sure these are realy the same:

"Bewegungstalent" costs 7 karma and grants the character a +2 dice pool bonus to running and acrobatics.
"Natürliche Härte" costs 10 karma and grants the character a 1 point natural biofeedback filter commulative to others (programs or technomancher firewall).

**Comment by chummer5a** [comment]
Yup, that'll be them. I'll amend the data files for the next version.

**Comment by holgerschlegel** [comment]
I had also edited the de_data.xml file locally to "fix" that translations.
I also added/fixed the page informations for qualities from the german core rulebook.
And, I improved the translations for some skill specialisations - the one for which I'm sure ...

I'll create a pull request for that changes once ready.
