### ISSUE TITLE
Organizing Contacts and Limiting Tool Tip Width

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#581]
Two quick suggestion for enhancements. The first is the ability to change the order of your contacts. It becomes a jumbled mess as you continue to get more and more contacts, with the ones you use a lot, and the ones that are almost useless all just in the order they were added.

The second is limiting how wide the tool tip windows become. When writing out stuff like, describing your apartment, or giving some background to your contacts, the tool tip showing your notes will go all the way across your screen, making it rather difficult to read. It would be nice if I didn't have to have manual line breaks in my notes to avoid extra wide tiny text boxes.

**Comment by chummer5a** [comment]
Contact ordering will be included in 5.179 or the next nightly. Tooltip should make it in to 5.179 as well.
