### ISSUE TITLE
Bone Lacing Cyberware

### ISSUE THREAD

**Issue by Distort3d** [chummer5a/chummer5a#582]
Bone Lacing is supposed to increase body as well as armor and melee damage. Currently it only seems to increase armor and give the bonus to melee with no effect on body. The book has it as: 
"..It gives you extra Body
for resisting physical damage, a little Armor
(cumulative with other Armor, without
adding to Encumbrance), and changes
your unarmed combat damage, all
listed in the Bone Lacing table."

The book's chart has it listed as a +1/+2/+3 for body, armor, and melee damage for plastic/aluminum/titanium respectively. I tried adding and removing it a couple of times, use the re-apply option, and even tested it with a fresh character and it doesn't seem to apply the body increase.

**Comment by cfresquet** [comment]
Bone lacing doesn't add to the Body stat, it only adds to Body tests to resist physical damage.

So, for example, it does not add to addiction tests, adept drain tests, etc.

**Comment by chummer5a** [comment]
I'm going to put that into the notes for the cyberware. I swear bone lacing
is the most commonly raised non-issue to date
