### ISSUE TITLE
Deleting qualities in Advanced Lifestyles does not delete the quality

### ISSUE THREAD

**Issue by tzxazrael** [chummer5a/chummer5a#583]
when adding a quality to an advanced lifestyle, and then deleting it, the quality is not removed even tho it appears to be.

eg, add "cramped", then delete it. save lifestyle; "cramped" is still attached to lifestyle.

**Comment by chummer5a** [comment]
Mostly that's limited to Cramped; there's a logic fail due to some shared
names. Should be fixed in the next version.

**Comment by tzxazrael** [comment]
appears to be all qualities, to me... haven't tested exactly every one.
