### ISSUE TITLE
Skill Groups and Free Skills

### ISSUE THREAD

**Issue by TheRealNamikaze** [chummer5a/chummer5a#585]
Recently this scenario was presented and I ran it through Chummer.  Turns out that Chummer handles this scenario illegally.  The scenario is a mage character with Priority A Magic and Priority C skills.  The mage character chooses Spellcasting and Summoning for his free skill points.  Then he picks the Sorcery skill group for both of his skill group points.

Chummer currently puts the skills as: Counterspelling 2, Ritual Spellcasting 2, Spellcasting 5.  However, after speaking with a number of people about this, including some of the writers, it appears that this is not intended behavior.  One cannot add skill group points to a skill group that already has points in a skill that is part of that group.

A simple validation for this would be to check at the end of character creation if the skill levels in each skill group are equal.  However, to avoid confusion during character creation, it might be best if this was not allowed to happen at all.  Perhaps this could be implemented as the default setting, and let the current setting (allowing people to spend skill group points on skill groups that already have points in a skill) become a house rule?

**Comment by joha4270** [comment]
It was me who posted said reddit thread after i got in doubt. Entire code based on skills is getting rewritten and i know at least one other thing it handles incorrectly

**Comment by TheRealNamikaze** [comment]
Gotcha!  I didn't recognize the name but now I see.  :)  Would you prefer that I leave this here, or should we close it?

**Comment by joha4270** [comment]
It is nice having it here. Preferably i would have a nice fat citation i
can throw after whoever tells me it is handled wrong, but anything really.

**Comment by TheRealNamikaze** [comment]
I think that's why it'd be best to probably leave the option in place, but as a house rule?  Either way, no one sane would actually ever do this because it's a huge waste of very valuable skill group points.  When I talked with Michael Chandra about it, he said that he remembered someone asking this a LONG time ago of one of the oldtime freelancers, Aaron Pavao.  You might be able to find the post on the official SR forums, Aaron Pavao posts under Aaron.

**Comment by joha4270** [comment]
Will try, my google' fu is decent

**Comment by joha4270** [comment]
And about leaving it as an option, probably will. It should be easy enough.
