### ISSUE TITLE
Wine issue in latest release

### ISSUE THREAD

**Issue by thefoolofemmaus** [chummer5a/chummer5a#586]
Latest release is crashing for me in Wine, running under Arch. Build 5.139 works fine, but 5.173 and 5.178 both crash with the attached report.
[backtrace.txt](https://github.com/chummer5a/chummer5a/files/69672/backtrace.txt)

**Comment by joha4270** [comment]
Chummer upgraded to .NET 4.5.1 in 169?

Your backtrace file mentions XP, that don't support any version higher that .NET 4.0

You can manually try and compile #e138e77 for the LEGACY target, but support for that is removed in the current codebase.

**Comment by chummer5a** [comment]
I was kind of expecting that to happen, probably should have announced it a
bit more in the nightly changelog. It *should* work if you update your .net
version in wine, assuming you're not using an XP VM or something.
https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478

**Comment by thefoolofemmaus** [comment]
Thank you both for the fast updates! I installed winetricks dotnet45 and the latest release started right up.
