### ISSUE TITLE
Adept Power "Enhanced Accuracy" dont work

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#587]
Adept Power "Enhanced Accuracy" dont add 1 to the Accuracy of the weapon.

**Comment by chummer5a** [comment]
Can't replicate. Can you please provide an example of a selected power option and a weapon that doesn't get the bonus properly?

**Comment by McRipolo** [comment]
Ok, after a little testing, it works when Chummer is set to english, but when you change to one of the other languages, it does not work. Make a char with this Power and save it. Change the language load the Char again and +1 Accuracy disappears.

**Comment by chummer5a** [comment]
Fixed in 5.179.
