### ISSUE TITLE
Positive quality translation not used

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#590]
The translation for the positive quality "Resistance to Pathogens and Toxins" is not shown in the UI.

The file "qualities.xml" contains the 2 positive qualities with very similar (english) names "Resistance to Pathogens/Toxins" and "Resistance to Pathogens and Toxins".
The second one (with "and") is set to hide = yes. Both do not have an <id> as all other qualities have.

The existing translation files for german (de_data.xml) and french (fr_data.xml) contain an entry referring to the second form (with the "and" instead of "/") with an <id> tag and the value "5a21137b-dc82-4141-9151-84718e7485f9".

Just as a test, I deleted the first quality entry (with "/"), added the <id> tag to the second one (with "and") and removed the <hide> tag. After that, the quality shows up with the correct translation.
My problem is: I'm not sure if that is the correct way to solve the problem. Does that way has side effects I missed / do not know off?

**Comment by joha4270** [comment]
I have not been poking anywhere, so it might work, but in general, changing the guid's (you call em tags, buts let's use the proper names :smile: ) is not the best idea. 

Instead, try changing the id in the de_data and see if that works.

**Comment by holgerschlegel** [comment]
The de_data file contains the id "5a21137b-dc82-4141-9151-84718e7485f9" for the translation.
But the skills.xml file does not contain that id at all.
The corresponding entries in the skills.xml file does not contain any tag.

Btw.: What I called tag was the xml fragment "<id>...</id>". Maybe the even better name would be xml element. The content of that tag/element is the guid.

**Comment by joha4270** [comment]
Shows what i know. In my defence i have not been outside skills for a
while.


Still not completely visualise what you are doing, but to make it short: If
you are playing with qualities.xml, I'm unhappy and are going to need a
look at the code to ensure nothing breaks. If you are changing stuff in
de_data.xml, knock yourself out, nothing *should* depend on that except the
translation parts.

**Comment by holgerschlegel** [comment]
The changes on the qualities.xml are just for testing. And only in my local installation.
I will not commit there changed to anywhere.

The main problem I opened this issue for is that a skill translation that exists in the de_data.xml files is not used by the Chummer gui. And that happens for that one skill only, as fas as I can see. All other skill translations are shown as desired.

**Comment by joha4270** [comment]
Skill?

Are you meaning qualities or ?

**Comment by holgerschlegel** [comment]
Upps, sorry.
Yes, I meant qualities.

**Comment by chummer5a** [comment]
Well that was silly. Fixed in 5.179.
