### ISSUE TITLE
Free contact karma is set to cha*2 when it's cha*3

### ISSUE THREAD

**Issue by digitalpacman** [chummer5a/chummer5a#592]
From the book:

"Every character receives free Karma to spend on
their initial contacts. This Karma is equal to a Character’s
Charisma rating x 3."

I have an elf created with the newest version of chummer with 3 cha and I was only given 6 karma for contacts.

**Comment by cfresquet** [comment]
Did you check your setting in the Tools->Options->House Rules?  This calculation can be adjusted under the "Free Contact Points Equal to Charisma" option.....

**Comment by digitalpacman** [comment]
Why would it default to *2? Thats the main issue here. It's not a house
rule.

**Comment by joha4270** [comment]
Except that it doesn't, unless you have an old settings file that chummer
finds (installing in same directory?)

2015-12-23 21:38 GMT+01:00 Brad Laney <notifications@github.com>:

**Comment by HaikenEdge** [comment]
The default *is* already x3. The implication is that something in your settings is off.

**Comment by digitalpacman** [comment]
Okay.. that seemed to solve it. Thanks.
