### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by Tattvalis** [chummer5a/chummer5a#594]
Hoi chummers,

I'm no decker/hacker, but if the informarion I was able to get from the matrix is correct, it is possible to compile csproj's to android apk files, or build apk files ...
I bet there would be quite a bunch of runners out there appreciating an android port of the chummer tool ... I certainly would a lot!
Would it be possible for you to release n android port? (Only of course if that doesn't mean you'd have to recode the whole thing or such)
Hope you'll answer soon
Thanx in advance

Tattva

**Comment by joha4270** [comment]
Short answer: Yes

Long answer: No. While it might compile, the UI is not in any way going to
work on a phone and as the code currently works, redoing the UI is about as
much work as recreating chummer from scratch. On top of that there might be
some restrictions on file system access and a few things like that that
works on a desktop but are restricted on a phone. Last but not least, the
tool to compile a .csproj places a restriction on size if using the free
version, a limit chummer far exceeds.

I am hoping to do it someday, but at the present state of chummer, I don't
think i can have it working even if i did spend 6 months on it where i
worked on no other things. I have been trying to work toward a state where
it would be easier to do, but this is not a near future thing.

**Comment by Tattvalis** [comment]
I understand ... The UI incompatibility issue to mobile devices came to my mind just after I posted my thread. Well, it's too bad but unfortunately can't be changed atm. But thank you very much for your quick and detailed answer!
So my next question would be if anyone knows a real good xls file or website to assist creating a SR5 character... :)

**Comment by chummer5a** [comment]
Honestly the best bet would be finding the source for the Mobile Runner app
and updating it for fifth.

**Comment by joha4270** [comment]
There is this thing.
http://heyomae.github.io/

It only covers core and is not made with mobile in mind. Not sure if it
handles everything quite right.
Another solution would be running chummer on AWS workspace (
https://aws.amazon.com/workspaces/), wich is basically a desptop in the
cloud, that you display on yoru phone

**Comment by chummer5a** [comment]
Anyhoo, outside the scope of this project at present.
