### ISSUE TITLE
Weapon dice pool and specialization and translations

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#595]
The displayed dice pool for weapons does not take the specialization into account if the specialization is entered in a language other than English. It works if the specialization is given using the corresponding English value.

Example:
On the skills tab, the dice pool for pistols is shows as "13 (15)" with specialization "Halbautomatik". The value "Halbautomatik" has been chosen from the combobox. According to the de_data.xml file, it translates to "Semi-Automatics" in English.
The same character has a "Ares Predator V", which is a heavy pistol and should benefit from the above specialization. But the dice pool displayed on the weapon page is 13.
If I change the specialization for pistols to the English value "Semi-Automatics", the dice pool for the weapon is correctly displayed as "13 (15)".

**Comment by chummer5a** [comment]
Hrm, I can't replicate it. Can you please upload your .chum5 file somewhere or email it to chummer5isalive@gmail.com?

**Comment by McRipolo** [comment]
Same Problem with Swords and "Schwerter",
so it works when Chummer is set to english, but when you change to one of the other languages, it does not work.

**Comment by chummer5a** [comment]
Blaaa. Okay, I see what's going on here. When you first add the specialiastion, it's using a translated displayname in the field, but the actual name is still stored as the value. When you save it, the displayname overwrites as the value, so there's nothing for it to match up against. Shouldn't be a huge problem to fix, just a logic fail.

**Comment by holgerschlegel** [comment]
As it still does not work using the nightly build (v1.0.612), I did some more tests.
It looks like the check to apply the specialisation bonus is done against the (translated) category of the weapon, and not against the weapon specialisation value.

Example:
According to the weapons.xml file, the "Ares Predator V", is in the category "Heavy Pistols" (in german "Schwere Pistolen") and has the specialisation "Semi-Automatics" (in german "Halbautomatik".
If I specialize pistols to "Schwere Pistolen", the weapon dice pool is shows with the specialisation bonus. After changing the pistols specialisation back to "Halbautomatik", the dice pool is again shown without the specialisation bonus. According to my understanding, it should be the other way round.
