### ISSUE TITLE
Issue with books.xml 

### ISSUE THREAD

**Issue by thefoolofemmaus** [chummer5a/chummer5a#597]
This crash happens at different times, but consistently when trying to open a character sheet that has not been completed.

[backtrace.txt](https://github.com/chummer5a/chummer5a/files/71962/backtrace.txt)

[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/71959/chummerlog.txt)

**Comment by chummer5a** [comment]
Hrm. It's having trouble parsing your registry file, I think. Try opening up regedit, and expanding HKEY_CURRENTUSER\Software and deleting the Chummer5 folder.

**Comment by joha4270** [comment]
Now seeing the guy is running chummer under WINE, it might be something
else.

If it is possible to extract a copy of that node i would like copy.

**Comment by thefoolofemmaus** [comment]
If you can tell me how to extract a node, or point me towards instructions,
I would be happy to do so.

**Comment by joha4270** [comment]
Open regedit (i have not used WINE in years, so it might be named
wine-regedit or something)

You should see 5 folders named HKEY_$SOMETHING

Open the one named HKEY_LOCAL_MACHINE

A folder in there should be named SOFTWARE. Inside that one there should be
a folder named Chummer5

Right click said folder. Press "Export". Save file somewhere you can find
it.
Delete (or rename) the folder. Check if it works. Report back. Include the
contents of the file you saved before.

If you are worried about privacy you can put a @gmail behind my username
and send the file there.

**Comment by thefoolofemmaus** [comment]
The key was under LOCAL_USER, nothing for chummer under LOCAL_MACHINE. Deleting that key had no effect. I have included both the export and the JIT debug output.
[chum.txt](https://github.com/chummer5a/chummer5a/files/72847/chum.txt)
[JIT.txt](https://github.com/chummer5a/chummer5a/files/72848/JIT.txt)

**Comment by joha4270** [comment]
Okay, that is interesting. During loading of settings (some in registry, some in ./settings/settings.XML) it tries to read ./sheets/data/books.XML (both sheets and data live in the same folder...)

As a stopgap, try copying ./data/books.XML to ./sheets/data.xml 

I have a few ideas to what is happening, but without some more detailed logging they all reside in the category of how the hell did would that happen.

**Comment by chummer5a** [comment]
May have found something related to this; received a character that wouldn't load as part of #1025 that gave me an error about not being able to find books.xml in my desktop directory, as I'd deleted the settings file. Investigation revealed that we're using environment.currentdirectory in a few places that aren't sanitised to only be accessed by the application, such as when we're loading a character file. Might be related?
