### ISSUE TITLE
MaxNuyen through Karma in "Priority Mode"

### ISSUE THREAD

**Issue by nick-ta-mere** [chummer5a/chummer5a#599]
Hi,
if you create a character with the priorities system, you can convert a different amount of Karma to Nuyen. There is a bug which sets this to a hard coded 10 Karma instead of reading it from the gameplayoptions.xml

I fixed it for myself, but can't push the fix because I don't have the necessary rights.
The bug is in frmCreate.cs lines 593-597
I'll attach the fixed file. Fix is at 593-602
[frmCreate.zip](https://github.com/chummer5a/chummer5a/files/72684/frmCreate.zip)

**Comment by chummer5a** [comment]
Whups, I thought I fixed that ages ago. Amended in 5.179.
