### ISSUE TITLE
Dermal plating and orthoskin is incompatible with natural dermal alteration.

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#602]
Its me again ;-)

Dermal plating and orthoskin is incompatible with trolls natural dermal armor or other dermal alteration, at the moment chummer combines the armor bonus.

SR5 p.94

Similarly, orthoskin replaces the natural dermal deposits of a 
troll so he would no longer receive the +1 dermal armor 
from his natural skin hardness.

Same for the other metatyps with dermal alteration:
 
RF p.113 
DERMAL ALTERATION
Characters with this quality possess skin that looks and 
feels quite different from normal skin and has unique 
properties. Dermal Alteration is incompatible with any 
other natural or artificial skin modification.

**Comment by chummer5a** [comment]
To  be fair, orthoskin is terrible and nobody should take it anyway, Will be fixed/worked around in 5.179.

**Comment by McRipolo** [comment]
Nightly-v1.0.603:
Now is Bone density augmentation and mystic Armorist working with dermal plating and orthoskin anymore.
