### ISSUE TITLE
New printout idea

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#603]
It would be nice to have a printout with the notes entered in Chummer5.
I use notes to scrible down the relevant effect of qualities, bodyware, gears and so on.

I have no idea how XSL works, otherwise I would have tried to create such a printout by myself.

**Comment by chummer5a** [comment]
Tools > Options > General tab > Character and Printing sub-tab > Print Notes

That'll enable notes for most of the character sheets. I don't think Fancy Blocks supports it presently, but that'd just be a matter of finding the relevant fields and adding them in to the other sheet.

**Comment by holgerschlegel** [comment]
Thanks, I missed that option.

**Comment by holgerschlegel** [comment]
Sorry, have to reopen this.
That option enabled printing of notes on the main character sheets (and maybe others).
So, creating a separate sheet with the notes only (and a reference to what a note belongs to) should be not that hard.

But: I would like to have the character sheets without notes, and that new printout with notes.
It looks like the "print notes" option is handled by either passing the notes values to the print engine or delete it from the xml structure before the print engine.

I known, I can create a personal copy of the character sheet template and remove the notes related lines. Or change that option regarding on what I want to print.
Both ways are not that nice to work with.

Have I missed a way to reach my goal?
Or is it possible to move the "print notes" option to the print dialog?

**Comment by chummer5a** [comment]
Ohhh, you want a character sheet that's JUST the notes? Hrm. Yeah, that
would just be a separate character sheet. I'll mock something up, but
basically it'll just be a matter of removing the items you don't want from
the sheet in question and keeping the rest, then doing the formatting to
suit. I'll mock something up.

**Comment by holgerschlegel** [comment]
I'm relatively new to Shadowrun.
So, I'm using the notes fields for some short hints on how and when to use a gear. For example reloading speed/action for weapons, modifiers caused by weapon modes, or conditional bonuses from qualities.

Printing all the notes on the main character sheet blows it up to much. So I prefer to keep these additions on an extra piece of paper.

**Comment by Lochabar** [comment]
Suggest closing this issue as it seems to have been implemented by issue #1468 :
1) New "Notes" character sheet prints the Game Notes after any Character Notes.
2) New "Core" character sheets prints without any notes.

**Comment by holgerschlegel** [comment]
Yes, this can be closed.
