### ISSUE TITLE
Printout page break for limits block

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#604]
In the german character sheet, the page break switch for the limits block affects the css styles of the skills block.

In the german sheet file "Shadowrun 5 Base.xslt" on lines 614/615 the block id passed to the javascript functions "showhide" and "zalomit" should be "LimitsBlock" instead of "SkillsBlock". The corresponding english file is correct.

**Comment by chummer5a** [comment]
Fixed in 5.179.
