### ISSUE TITLE
Linguist quality doesn't apply Language skill purchase discount

### ISSUE THREAD

**Issue by columnFive** [chummer5a/chummer5a#605]
As it says in the title, taking Linguist during character creation ("Mark character as created" unchecked)  has no effect on the purchase cost or skill ranks awarded when putting either free knowledge skill points or karma into language skills.

**Comment by TheWyrmOuroboros** [comment]
Don't think it's supposed to, actually.

**Comment by joha4270** [comment]
> If this quality is purchased at character creation, the player purchases Language kill points at a 2-for-1 rate.    

**RF148**

Seems to me that it does...

**Comment by joha4270** [comment]
Fixed in the latest release
