### ISSUE TITLE
NullReferenceException when adding life style

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#608]
I still get the same exception as described in issue #545. I have tested it using the nightly build v1.0.594 set to language german. As it works if language is set to english, I assume that it is caused by an error in the german language file de_data.xml.

To produce it:
- set Chummer to german and restart it
- create a new character and directly go to add a lifestyle

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.frmSelectLifestyle.CalculateValues(Boolean blnIncludePercentage) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyle.cs:Zeile 309.
   bei Chummer.frmSelectLifestyle.frmSelectAdvancedLifestyle_Load(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyle.cs:Zeile 141.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The exception message translates to "Object reference not set to an instance of an object."

Pressing "Continue" in that dialog opens the dialog. If I select "medium" life style, I can add it to the character. Selecting "low" life style immediately causes another NullReferenceException.

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.frmSelectLifestyle.CalculateValues(Boolean blnIncludePercentage) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyle.cs:Zeile 309.
   bei Chummer.frmSelectLifestyle.cboLifestyle_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyle.cs:Zeile 172.
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
...

But I assume that the cause of this is the same as the cause for the first exception.

**Comment by chummer5a** [comment]
Combobox for lifestyles was using the name as the value improperly, so it couldn't look up the lifestyle from the xml files.
