### ISSUE TITLE
on Rigger 5.0

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#609]
Any idea when the new book's content will be added? Can't wait to pick up a few of those drones and start customizing my vehicles.

**Comment by McRipolo** [comment]
Rigger 5.0 is allready in the Chummer5 Nightly^^

**Comment by chummer5a** [comment]
It's all active in the nightly builds; properly release won't be for a little while yet, we want to have the skills finished before we make it available to the masses. 

If you're willing to tolerate theoretically-more-buggy code, just grab the latest Chummer.nightly.zip from https://github.com/chummer5a/chummer5a/releases and you should be golden.

**Comment by schultlp** [comment]
Alright. If I get the nightly and my GM sticks to the official release, will that cause crashes and errors when he tries to open the file?

**Comment by chummer5a** [comment]
Unfortunately yes, there have been a lot of changes made between the live and dev builds at this point, a decent amount of which is to support some of the weird shit that Rigger 5.0 added. The Reddit thread I pulled the content from should mostly work, but given the changes, you *may* run into compatibility issues. Should be fine though.

https://www.reddit.com/r/Shadowrun/comments/3xv4qp/rigger_50_chummer_files/
