### ISSUE TITLE
Ongoing Issue with adept powers and free powers (save/load information loss)

### ISSUE THREAD

**Issue by Godfrid** [chummer5a/chummer5a#615]
I have an adept character, with mentor spirit Cat who gives the light body 2 power. I also have 2 other level on this power, and if I change it it works in order, but after saving the character and reloading it the extra two spent levels are missing, and only the ones given by the spirit mentor are there.
This problem appears as soon as I try to make a character, it doesn't have to be put in career mode, a save and reload is all this information loss is needed to happen.

**Comment by Godfrid** [comment]
I tested it, and it still looks the same. However when I try to open the saved file, it still doesn't show the point only the free ones, but, when I just try to close it without modifying it, it still ask if I want to save it. So I think it changes the values when I load the save and that's why it asks if i want to save the modifications?

**Comment by chummer5a** [comment]
Can you upload your character file somewhere for me to take a look at? You are using the newest binary, yes? https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v1.0.615

**Comment by Godfrid** [comment]
Yes, the latest. Here is one in building process, and one older character. The later is in negative adept powers, we use, the adept way alternatively, and have some plus powers granted by her mentor. But as the new character shows, that is not the issue there.
https://drive.google.com/folderview?id=0BznKy122EAN3MEkyMXF1Q3FJbzA&usp=sharing
