### ISSUE TITLE
Cyberdeck attribute configuration not stored

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#620]
The cyberdeck attribute configurtation is reseted to default after switching to an other element in the equipments tree. Not a big problem, but irritating.

Example:
My character has a "Renraku Tsurugi" rating 3 cyberdeck. The deck default attribute configurations shown by Chummer is: 6, 5, 5, 3 (ASDF)
If I change it to 3, 5, 5, 6 and then navigate to an other equipment (e.g. a fake sin) and back to the cyberdeck, the attribute configuration shows is back to 6, 5, 5, 3.

**Comment by chummer5a** [comment]
Fixed as of Nightly-v1.0.616; technically it was saving the values properly, but everything was getting switched around in the back end. Anyway, should be good now.
