### ISSUE TITLE
Anti-Theft System

### ISSUE THREAD

**Issue by PjotrV** [chummer5a/chummer5a#621]
Adding Anti-Theft System to a vehicle gives an error. Chummer will continue but doesn't calculate vehicle cost correctly.
(Tested with Ares Venture and Hyundai Shin-Hyung)

**Comment by MatterL** [comment]
This happened to me as well upon attaching it to the GMC Bulldog, and it seems to occur no matter which version of the Anti-Theft System is installed. Chummer then gives an error message each time the car or mod is selected and as mentioned above fails to calculate cost and stats from then on.

**Comment by chummer5a** [comment]
Yeah, mods don't understand FixedValues. Will be fixed sometime today, most likely.

**Comment by chummer5a** [comment]
Fixed in current build.
