### ISSUE TITLE
Dealer Connection & Chameleon Coating

### ISSUE THREAD

**Issue by PjotrV** [chummer5a/chummer5a#622]
Two things that need fixing: 
- Dealer Connection quality doesn't give discount on vehicles
- Chameleon Coating cost is incorrect, according to R5 p167 it should be 1000*Body, calculated cost is twice that.

**Comment by chummer5a** [comment]
Fixed in commit [5b219b9](https://github.com/chummer5a/chummer5a/commit/5b219b9ce53130c2aac151eca1d4d48771c23cf1).
