### ISSUE TITLE
Advanced Lifestyle crashing when saving

### ISSUE THREAD

**Issue by HannoBoettcher** [chummer5a/chummer5a#623]
Hi there,

I'm using Version 5.179.0 of Chummer and try to add an advanced lifestyle to a charakter. I activated the RunFaster rulebook to be used in the option settings before I tried to add an advanced lifestyle (assuming that's necessary).

I can create an advanced lifestyle, select "medium", give it a name but not add any qualities to it. Then clicking "OK" does no harm and the lifestyle is showing up in the Overview. If I edit the lifestyle and add e.g. a public transportation and click "ok" afterwards I get the following crash (partly German, sorry):

------------------------
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Chummer.LifestyleQuality.Create(XmlNode objXmlLifestyleQuality, Character objCharacter, QualitySource objLifestyleQualitySource, TreeNode objNode) in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:Zeile 16538.
   bei Chummer.frmSelectLifestyleAdvanced.AcceptForm() in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyleAdvanced.cs:Zeile 381.
   bei Chummer.frmSelectLifestyleAdvanced.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectLifestyleAdvanced.cs:Zeile 147.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.127.1 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
Chummer5
    Assembly-Version: 5.179.0.0.
    Win32-Version: 5.179.0.
    CodeBase: file:///Z:/ownCloud/Rollenspiel/SR5/Chummer/Chummer5.exe.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.93.0 built by: NETFXREL2STAGE.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.79.0 built by: NETFXREL2.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

------------------------

This error also occurs in the case where I add the quality during creation.

Any suggestions what's going wrong there? Is it a bug? Or is the error sitting in front of the computer ;-).

Best regards,
Hanno

**Comment by joha4270** [comment]
Its telling you that there was an error in front of the computer when the
code related to lifestyles was written. (Yes it is a big :smile:)

Just to confirm, happens if you edit an lifestyle after you create it or do
i read it wrong?

**Comment by HannoBoettcher** [comment]
Am 08.01.2016 um 19:26 schrieb Johannes Elgaard:
> Its telling you that there was an error in front of the computer when the
> code related to lifestyles was written. (Yes it is a big :smile:)
>
> Just to confirm, happens if you edit an lifestyle after you create it 
> or do
> i read it wrong?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/chummer5a/chummer5a/issues/623#issuecomment-170081842>.
>
Hi there,

it happens in both cases. If you create it and add e.g. public 
transportation, garage (<4) and grid abo. Or if you create it "empty" 
and edit it to save qualities afterwards.

Hope this helps,

Yours,
Hanno

**Comment by joha4270** [comment]
It does help. This tells me that it is the quality that presents the issue
and not the act of editing it afterwards. Most of the work fixing a bug is
finding out what actually happens, not fixing it.

That said, no ETA on when a fix is coming. Currently playing around with
skills and won't mess too much with the rest of the application until that
is done.

**Comment by chummer5a** [comment]
That's.. odd. I'll look into it.
