### ISSUE TITLE
Weapon dice pool and specialization and translations

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#627]
It seems that the problem in ticked #595 is still not fixed.
I've tested it again using the nightly-v5.179.656 and created a new, nearly empty character for that.

The spec attributes in the weapons.xml and the .chum5 file of the character are equal. But the Chummer5 GUI still shows the base dicepool value without specialisation.

I've attached the .chum5 file to this post - packed into a zip file.
Opening this file with Chummer set to german, the skill tab shows the correct dice pool of "10 (12)" for both pistols and swords.
On the weapons tab for the Katana and the Ares Predator V, a dice pool of "10" is shows for both weapons.
According to the Chummer5 data files and my core rulebook, it should be "10 (12)" (or only "12") for both.

[TestSpecs.zip](https://github.com/chummer5a/chummer5a/files/89176/TestSpecs.zip)

**Comment by chummer5a** [comment]
This should be resolved in current builds.
