### ISSUE TITLE
Error occurs when opening older characters

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#629]
This is copied from the error that pops up:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmCreate.frmCreate_FormClosing(Object sender, FormClosingEventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 1501
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.656.0
    Win32 Version: 5.179.656
    CodeBase: file:///C:/Users/Matt/Desktop/Chummer.Nightly/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by bakaie** [comment]
I have been having the same issue.  I have a Rigger that i created with version 5.179.648.  I have tried several of the new version that have been released in the last few days.  The last version i ran was .657.  If i force close the app and open the same save file again with .648 it works with no errors.  Error txt is in the pastebin link.

http://pastebin.com/guhGUjdJ

Let me know if you have any questions or need any additional information.

**Comment by joha4270** [comment]
I'm going to need you guys to upload character sheets that displays this issue or diagnosing it could end up being hard...

**Comment by bakaie** [comment]
Here is a copy of one of the characters that is causing my issue.

Thanks.

[Frincisco-finished1.zip](https://github.com/chummer5a/chummer5a/files/90502/Frincisco-finished1.zip)

**Comment by AriMatt2** [comment]
https://drive.google.com/open?id=0B-mC2hIA5p-xX2h5cmpPWE01Y1U
https://drive.google.com/open?id=0B-mC2hIA5p-xaVJ0VEU4SVFDOU0

I have others, but I think these two are the most distant in terms of when they were made.

**Comment by chummer5a** [comment]
Should be resolved as of most recent build thanks to AMDX9's pull.
