### ISSUE TITLE
Language problems?

### ISSUE THREAD

**Issue by Oekie** [chummer5a/chummer5a#630]
I have a big problem with chummer 5.178
Everytime I try to add a lifestyle to a char I get this error message.
I had this problem in a older chummer version too and I thought it woud be fixed in this new version.
Anyway it could be a problem with the german language files because in english chummer runs without problems. Next problem I can't switch back to german because of the error message.
Is there a way to set the language fix on german in any datafile?

![error](https://cloud.githubusercontent.com/assets/16694214/12312058/5b575040-ba5c-11e5-81fe-8feabf58eab9.jpg)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmOptions.SaveGlobalOptions() in C:\projects\chummer5a\Chummer\frmOptions.cs:line 652
   at Chummer.frmOptions.SaveRegistrySettings() in C:\projects\chummer5a\Chummer\frmOptions.cs:line 671
   at Chummer.frmOptions.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\frmOptions.cs:line 50
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 0.5.178.0
    Win32 Version: 0.5.178.0
    CodeBase: file:///C:/Users/Oekie/Documents/Dokumente/Shadowrun/Chummer%205a/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by McRipolo** [comment]
Hi,  
use the "Erweiterter Lebenstil" from "Schattenläufer/ Run Faster" 
Is fixed in the Nightly-v5.179.650.

Ich hatte das selbe Problem. ;-)

**Comment by Oekie** [comment]
Ok thx, but the version is not running.
It's always starts with a empty update window and after I press restart the programm ended.

**Comment by McRipolo** [comment]
Skip update with  the X in the right Corner, than it starts

**Comment by Oekie** [comment]
Ohhh it's so obviously^^

**Comment by chummer5a** [comment]
So just to confirm, the issue you're having is that you can't load standard lifestyles, only the advanced ones?

**Comment by Oekie** [comment]
In the german version 5.178 it's not possible to at a standard lifestyles or advanced without an error in the german version 5.179.661 I have this problem not.

**Comment by chummer5a** [comment]
Righto, issue's effectively sorted then.
