### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by guruscott-meyer** [chummer5a/chummer5a#632]
Just downloaded the latest build (5.179) and the program has completely quit working.  It starts up to the chummer updater.  I hit download and it appears to be downloading, but after it's done and I hit restart it just starts up the updater again.  This goes on indefinitely unless I X out of it and then chummer itself starts up.  Then, I can't open any of my characters.  I try and get the following error:
I'm running Windows 10 with the latest .NET

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.SkillControl.RefreshControl() in C:\Users\Scott\Documents\GitHub\chummer5a\Chummer\Controls\SkillControl.cs:line 1137
   at Chummer.SkillControl.set_SkillCategory(String value) in C:\Users\Scott\Documents\GitHub\chummer5a\Chummer\Controls\SkillControl.cs:line 1035
   at Chummer.SkillControl.cboKnowledgeSkillCategory_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Scott\Documents\GitHub\chummer5a\Chummer\Controls\SkillControl.cs:line 331
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ListControl.set_SelectedValue(Object value)
   at Chummer.SkillControl.set_KnowledgeSkill(Boolean value) in C:\Users\Scott\Documents\GitHub\chummer5a\Chummer\Controls\SkillControl.cs:line 901
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in C:\Users\Scott\Documents\GitHub\chummer5a\Chummer\Character Creation\frmCreate.cs:line 786
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.106.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.0.0
    Win32 Version: 5.179.0
    CodeBase: file:///C:/Users/Scott/Documents/GitHub/chummer5a/Chummer/bin/Debug/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by chummer5a** [comment]
Turn off the automatic updates for now; I haven't coded the updater to handle the nightlies properly.

**Comment by guruscott-meyer** [comment]
That takes care of the updater problem, but I still can't open any of my existing characters.  I get that error and if I select continue most of the character is missing.  I can create new characters and that's it.

**Comment by chummer5a** [comment]
I think I broke something with the specialisations, I need to tinker with it a bit. In the interim, if you can upload an affected character file I'll be able to get a better idea of the problem.

**Comment by McRipolo** [comment]
Same Problem here, happened since Nightly-v5.179.651, so it is maybe a problem with active hardwires

**Comment by guruscott-meyer** [comment]
I'm at work right now, so I can't access my character files, but it seems to affect any character, even one I just created.

**Comment by McRipolo** [comment]
Hope that help:
https://www.dropbox.com/s/bx74kusck9qcnw2/Grog.chum5?dl=0

**Comment by guruscott-meyer** [comment]
I just pulled the most recent changes, still getting the same error, and can't access any of my existing characters.

**Comment by chummer5a** [comment]
AMDX9's pull request hasn't been approved yet, that's why. It's in test now to confirm nothing else goes shonky with it, but all seems okay at the moment.

**Comment by guruscott-meyer** [comment]
So how long does the process usually take?  I'd really like to have access to my character sheet by next weeks's game.  I already missed this week.

**Comment by chummer5a** [comment]
Depends on what the error is. If it's what I think it is, I'll have it
fixed ~12 hours from now.

**Comment by chummer5a** [comment]
Hokay, the pull request from AMDX9 worked fine, I'm able to load that character file in the equivalent of 5.179.664; please download the latest version and test.

**Comment by McRipolo** [comment]
Works for me

**Comment by guruscott-meyer** [comment]
Just tried it and I can confirm it works.  Thanks so much for fixing that.
