### ISSUE TITLE
Wireless management

### ISSUE THREAD

**Issue by maximestlaurent** [chummer5a/chummer5a#633]
As far as I know, wireless bonuses are not included in any character stats because there is no way to tell whether or not the character currently has access to the Matrix wirelessly. I suggest we take a page out of HeroLab's book and add an "Wireless On/Off" switch that adds and removes the wireless bonuses from different items on the character sheet.

**Comment by McRipolo** [comment]
Good idea, maybe show two Dice Pools one normal and one "Wifi on" Pool

**Comment by maximestlaurent** [comment]
I'd have to double check, but I believe the bonuses are not always Dice Pool related. Thus, I was thinking more along the line of simply adding and removing the bonuses where applicable based on whether the toggle is On or Off.

Something different would have to be done for a printed charcter sheet, though.

**Comment by chummer5a** [comment]
Yeah, I've been pondering how to handle this for a while now. It's somewhere at the back of the queue, behind the skill rewrite but ahead of shapeshifters.

**Comment by maximestlaurent** [comment]
Are the Wireless bonuses in the data? I can't seem to find them.

**Comment by chummer5a** [comment]
Nope; I'll have to build in functionality for it, probably something along
the lines of a <wireless /> flag that only enables it if it's present or
something.

**Comment by maximestlaurent** [comment]
If you need any help, I can contribute.

**Comment by chummer5a** [comment]
Will do; generally with this sort of thing I mock up enough to be reasonably sure the concept will work and then farm out the data-entry, so I'll update this when the time comes for that.

**Comment by chummer5a** [comment]
The backing code for wireless bonuses has been implemented. Additional required changes:
- [ ] Method for toggling Wireless in the UI
- [ ] Data entry for all items that have a wireless bonus with a mechanical effect

**Comment by maximestlaurent** [comment]
I've picked up Shadowrun recently, and see this issue is close to being done. As I commented before, I can help resolve this, so I'll get started on the data entry in the near future.

**Comment by maximestlaurent** [comment]
@chummer5a Has something been done for printed character sheets relating to this feature? I'm curious to see how we could display the Wireless bonuses in printed form.

**Comment by maximestlaurent** [comment]
I've just re-read the "Wireless" rule in Shadowrun 5, and there's something we didn't take into account: wireless can be blocked by noise. If the "effective" noise rating (once noise reduction has been taken into account) is higher than a device's rating, its wireless gets disabled. This means we can't simply have a "Wireless: OFF/ON" switch in the UI.

Do we want to have a "Wireless management" tab/widget which can take noise into account?

**Comment by chummer5a** [comment]
The idea I had was for the wireless toggle to be 'I *want* this to be on'. It would still have an enabled-disabled state based on the Noise and Noise Reduction available to the object, but given the occasional quirks with noise reduction, a separate panel might be necessary.

**Comment by maximestlaurent** [comment]
Is there a way to specify current noise in Chummer5a? I can't seem to find anything.

**Comment by chummer5a** [comment]
Currently no; it'd just be a pointless spinner with the current codebase.

**Comment by maximestlaurent** [comment]
I'm guessing a "Noise" panel would be good, as you suggested. It could simply be two spinners (noise, noise reduction) and an "effective noise", which would be used to enable/disable the wireless bonuses.

If the data for noise reduction is in the codebase, we might be able to calculate the player's noise reduction.
