### ISSUE TITLE
Striking callus give wrong bonus when added in odd quantity

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#634]
Striking callus give wrong bonus when added in odd number.

When add "rating/quantity" 2 or 4 they give the correct Bonus +1 or +2 P Damage to Unarmed Combat.

When add "rating/quantity" 1 or 3 they give the wrong Bonus +5 or +15 P Damage to Unarmed Combat, it should be +0 and +1 Damage to Unarmed Combat.

When adding more striking callus, the bonus is added, that wrong too.

**Comment by chummer5a** [comment]
Working as intended, as far as I can see. 
1 callus: no improvement.
2 calluses: STR+1P
3 calluses: STR+1P
4 calluses: STR+2P

**Comment by McRipolo** [comment]
I have test it with Nightly-v5.179.659 and 5.178:
new priority, abcde, dwarf, technomancer and add only the Bio Weapon und Bioware -> Bio Weapons->  Striking callus and it shows Unarmed Combat  18P
STR is 3, so it should bei 4P

**Comment by chummer5a** [comment]
Can't reproduce it; please upload an affected character file.

**Comment by McRipolo** [comment]
Affected character file:
https://www.dropbox.com/s/f84p29hdqbvldi4/Striking%20callus.chum5?dl=0

**Comment by chummer5a** [comment]
Hrm. Well, the improvment's definitely got a value of 15, but I can't see any way it could have GOTTEN that value, so that's odd.

**Comment by McRipolo** [comment]
Maybe a Problem with german OS / .Net?

**Comment by chummer5a** [comment]
I wouldn't think that's related; without any kind of guide to reproducing it though, I'm a bit stumped.
