### ISSUE TITLE
Attaching Character Sheets other than Chummer

### ISSUE THREAD

**Issue by schultlp** [chummer5a/chummer5a#636]
I'm not sure if this is a bug, or something that would need to be implemented, but I have a player with a pet blackberry cat, soon to be made into an inhabited familiar. Since there is no 5th Edition Running Wild, I wrote up a character sheet in Excel, and when I went to attach it in Chummer I got the following message: 

Data at the root level is invalid. Line 1, position 1

It would be nice to be able to attach an Excel, Word, or Adobe file to contacts and pets and what not for really nonstandard characters, or things that Chummer currently isn't capable of representing.

**Comment by chummer5a** [comment]
Yeah, Chummer's trying to read data from the file like the name and such. Shouldn't be a major hassle to set document linking up, I'll give it a crack.
