### ISSUE TITLE
Opening A Saved Charater

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#638]
When I open a saved character the program comes up with an error and shows no equipment that was saved.

**Comment by rabbitslayer4** [comment]
Do you have the character file in question?

**Comment by captroberts** [comment]
Yes I do. Here is the file.
Kent

**Comment by rabbitslayer4** [comment]
Did it not attach correctly?

**Comment by captroberts** [comment]
Lets try that again.

**Comment by chummer5a** [comment]
FYI, you can't attach files via email that aren't .zips. I usually find it easier to just upload the file somewhere.

**Comment by chummer5a** [comment]
Issue should be resolved as of nightly 5.179.664; could you please grab the latest file and confirm?

**Comment by captroberts** [comment]
That fixed the issue. You are a master at your trade sir. Thank you
