### ISSUE TITLE
"Metatype" lifestyle quality is not considered

### ISSUE THREAD

**Issue by maximestlaurent** [chummer5a/chummer5a#639]
When adding a lifestyle for a an Ork, a Dwarf or a Troll, the "Metatype" quality is added to the lifestyle with a different value for the three metatypes (+20%, +20% and +100%, respectively). While the quality is correctly factored into the lifestyle's price in the "Add lifestyle" dialog, it's ignored once it has been added.

**Comment by chummer5a** [comment]
Hrm, I thought I fixed that. Advanced lifestyle or standard?

**Comment by maximestlaurent** [comment]
Standard. I'd like to mention that this happened on the latest build, not the nightly build.

**Comment by maximestlaurent** [comment]
Issue was reproduced in latest nightly build (5.179.666)

**Comment by chummer5a** [comment]
Should be resolved in current builds.
