### ISSUE TITLE
Pushing new changes

### ISSUE THREAD

**Issue by rabbitslayer4** [chummer5a/chummer5a#641]
Hey All... I am new to Git and have some changes I want to push up. Committed and built on local machine. How do I push? I get a 403 (Forbidden) when trying to push to the master. Should I be doing something else?

(I have fixes for #178, #629, and possibly #638)

**Comment by chummer5a** [comment]
Uhh, I'm not too sure about how the pull request stuff works, I've never really had to do it. As far as I know you would commit it to your git fork, then create a pull request which I'd review and approve. Only Joha and I can do pushes to the main fork at the moment

**Comment by rabbitslayer4** [comment]
Ok cool. I just pushed up changes to my fork.
