### ISSUE TITLE
Support of fractional karma gains? (maybe optional)

### ISSUE THREAD

**Issue by zesstra** [chummer5a/chummer5a#642]
Good morning all...

I play in a campaign where fractional karma gains (e.g. 0.5) are used as well, which currently can't be entered in Chummer. I manage it mostly outside of Chummer and enter only whole numbers just before I spend karma. What is your view on allowing fractional karma gains?

**Comment by chummer5a** [comment]
It's... doable, I guess. Set the decimal as a separate variable, split the
entered karma, if we can make or a hundred or whatever out of it then add
to the karma amount... I'll have a think about it.

**Comment by Skarablood** [comment]
Fractional karma? Excuse the question, but (as a GM myself) is your GM on drugs?

**Comment by zesstra** [comment]
I agree, it is unusual. ;-)
However, there are some reasons. E.g. some members of our group are not the whole adventure present. Could be that someone has to skip one evening or leave after half an evening. Or the GM wants to give a small bonus for something.
But regardless of the background for it, the main question is IMHO,  how much effort it takes and if it has significant drawbacks...
So, thank you chummer5a for thinking about it. :-)

**Comment by joha4270** [comment]
Okay, we had a quick discussion and have decided to close this as it would increase  codebase complexity unnecessarily and confuse users who don't use that specific house rule, at the advantage of a small group.
