### ISSUE TITLE
Edge for Karma

### ISSUE THREAD

**Issue by Oekie** [chummer5a/chummer5a#646]
According to rules it is possible to buy edge with karma during the character creation.
But when I mark the character as createt chummer says I spent to many specialattributes points.
Is this a bug?

**Comment by joha4270** [comment]
I'm not aware of any bug there. Could you please provide steps to reproduce and/or a .chum5 file? Also would like the version of chummer where you are experiencing this.

**Comment by chummer5a** [comment]
I think there's a bug somewhere in the character validator that uses the wrong string; if you can upload your file somewhere we'll be able to confirm and hopefully fix it.

**Comment by Oekie** [comment]
Oh the problem must be fixed in Nightly-v5.179.669
Thx
