### ISSUE TITLE
Issue with Knowledge skills

### ISSUE THREAD

**Issue by dkroeni** [chummer5a/chummer5a#648]
I have some trouble with adding new Knowledge skills. Using the current version (0.5.178.0, German Language) i tried to add some new knowledge skills. I save the .chum, close and reload. Now some of the knowledge skills name have one character less than they should. The last character of the name is missing.
In older versions i even got a crash loading the character.

I tracked the issue, checked the chum file and found out that the Id's of the new skills always are always zero:
			<id>00000000-0000-0000-0000-000000000000</id>
This was causing the crashes in the older versions.

I am using a chummer with default settings, german language, and only "Shadowrun 5th edition" rules.
I create a new char, human, 800 points and add the first couple of knowledge skills and save it under
"test_firstSave.chum" (see attachment)
Then (after making a backup of this copy) i reload and save again and get this ("test_afterReload.chum").
The difference is not only the order of the skills but also the name (missing characters at the end)

[test_chums.zip](https://github.com/chummer5a/chummer5a/files/99776/test_chums.zip)

**Comment by chummer5a** [comment]
Should be fixed in the most recent build.
