### ISSUE TITLE
Infected Metatype Attribute Table

### ISSUE THREAD

**Issue by Erdur** [chummer5a/chummer5a#651]
The "Infected Metatype Attribute Table" dosent seem to be in use.
(during Character Crefon, and after Finishing Karma,Sum and Priority)

**Comment by Erdur** [comment]
PS: Hope i havent overlocked some Ticket and made a Duplecate.

**Comment by chummer5a** [comment]
Yeah, I'm an idiot and didn't code it properly. Needs to be redone.

**Comment by Erdur** [comment]
Can happen easy. (If done by me it would probably be a mixup with =/==, and my Job is Programming)

I had no time to look in the Code Jet, since i am currently Trying to Cobble together a Char.
(Its in the Morning at my lokation, and my Group will play soon.)

**Comment by chummer5a** [comment]
Roughly half done, though the sasquatch is annoying and offends me. Still, couple of days and should be done.
