### ISSUE TITLE
Magic + Essence loss seem to not work properly

### ISSUE THREAD

**Issue by anchoress** [chummer5a/chummer5a#664]
Chossing 'ware on an awwakened character seem to cost the wrong amounts of karma in karma generation.

A quick example:
Picking up the adept quality and raising magic to 6 costs 120 karma. Picking up 'ware for 2 essence afterwards lowers your max magic rating to 4. Lowering your magic rating from 6 to 4 (you have to do this manually) now giving you back 30 karma in this step. So the total costs are at 90 karma.
Buuut... if you pick up the 'ware first and choosing adept after that and raising magic to 4 again you pay only 80 karma.

So actually the order in which you pick up your 'ware or magic attribute makes a differnce, which should not be true.

Version: nightly 5.179.679

**Comment by chummer5a** [comment]
Should be fixed in the latest nightly; what's your current version?

**Comment by anchoress** [comment]
Like i wrote, i had this issue in the nightly 5.179.679 version. Does not occur in the latest official release, 5.178 (just tested the exact same example to be sure).

**Comment by TheWyrmOuroboros** [comment]
Something similar - after character generation, you still need to be able to gain a Magic quality.  5.178 allowed you to do so, but while 5.179.679 allows you to select and purchase the quality, if you have essence loss it generates, then eliminates, your magic attribute and does not allow you to buy it up (i.e. greyed out).  If you have an essence at or above 1.0000, it should put your magic at 1; after all, that's what you get for the money.

For a magic-less individual, cyberware should reduce the maximum magic you can acquire; for a person WITH magic, it should reduce maximum magic, but also only reduce current magic _when the cyber is implanted_.

**Comment by chummer5a** [comment]
This should be resolved in current nightlies. The burning out issue has been raised separately as #801.
