### ISSUE TITLE
Glamour limit increase visual duplication

### ISSUE THREAD

**Issue by LocasMaxis** [chummer5a/chummer5a#665]
Whenever you add a new Quality after taking the Glamour Quality the Glamour bonus on the Limits tab gets visually added again, but doesn't actually effect your social limit again. It clears up on reloading any afflicted sheet but when you have 30+ Glamour (+2) in your limit screen from messing around with Quality calculations it can get a little silly. Also thanks for all the great work you're doing on this program, such a big help in planning characters. Build is the 5.179.676 nightly build.

**Comment by LocasMaxis** [comment]
Follow up, seems to be a similar bug with the Fame bonus to social limit but instead its permanent to the sheet and but still only adds once for each quality taken after Fame, deleted or not. Side not deleting the Fame quality doesn't get rid of the single bonus that is applying. So this seems to be a problem with social limit increasing qualities though it could be more complex then that. Fame afflicted character sheet: https://my.mixtape.moe/imniyg.chum5 (Same chummer build as previous post.)

**Comment by chummer5a** [comment]
Hrm, I can't replicate the visual effect. Is it still happening for you in the most recent builds?
