### ISSUE TITLE
Rigger 5 vehicle mods still broken

### ISSUE THREAD

**Issue by Flip-Sandwich** [chummer5a/chummer5a#675]
The different weapon mount sizes still cost the same amount, 750 nuyen, though the larger ones should cost more, standard size 1500 and heavy 4000.

Handling, acceleration, and speed enhancements throw the following error:  http://pastebin.com/qWdF9Fdi
Update: Adding enhancements to drones, such as armor and such, also give the error.

In addition acceleration enhancement's second level cost is wrong as it should be 25000 instead of 2500. Also I think it needs to be based off the upgraded attribute, not sure, don't quote me on that.

In addition the drone armor enhancement calculation doesn't seem to be done correctly, I cannot seem to upgrade it further than 6, the restricted and forbidden grades aren't actually availability R or F either.

**Comment by AMDX9** [comment]
The different weapon mount sizes should have different costs but the R5 book does not specify a cost for the weapon mounts under the drone rules. I am working on trying to revamp the vehicle system, but  some of the information will still be broken until they release corrections. You can find a listing of other errors and ommisions [here](https://www.reddit.com/r/Shadowrun/comments/3xrxtw/rigger_5_errata_the_gathering/)

**Comment by Flip-Sandwich** [comment]
The error currently still occurs when you click on the vehicle or drone that you've modified, and when you try to print. You can however now add and change the rating of and click on the upgrade itself without throwing an error.

**Comment by chummer5a** [comment]
Can't replicate the crash for handling or speed, so I'm not sure what's going on there. Code looks right to me.

**Comment by Flip-Sandwich** [comment]
Yeah it seems to work now with the most recent version. Not sure what happened here either, this can probably be closed now.

**Comment by chummer5a** [comment]
Drone attribute enhancements are just... wrong. I'm going to need code support to get them implemented close to properly, let alone with the mod points system. Speed should be fixed in the latest build, I'll tinker with the other mods and see if I can get them working properly.
