### ISSUE TITLE
Lifestyle options from Run Faster

### ISSUE THREAD

**Issue by LocasMaxis** [chummer5a/chummer5a#678]
I'd love to see them added, the extra level of customization would be much appreciated. Though I assume it would require a rewrite of the lifestyle code. Also an option for roommates to add 10% increased lifestyle cost per roommate, as per the rules on SR5 p.371 would be nice.

**Comment by chummer5a** [comment]
Click on the arrow next to Add Lifestyle and select Add Advanced Lifestyle.
