### ISSUE TITLE
Karma cost for Special Attribute

### ISSUE THREAD

**Issue by jerhpk** [chummer5a/chummer5a#679]
Previous open version of a character was automatically updated to new version.  Now it is coming up with a 10 karma cost for a 0 point attribute: special attribute.  Will not allow character to move to created.
![spec karma cost](https://cloud.githubusercontent.com/assets/17105344/12870896/8e821a3e-cd28-11e5-8974-5591a1b0618b.png)

**Comment by chummer5a** [comment]
Nightly or release code? Can you upload the character file somewhere?

**Comment by jerhpk** [comment]
Sorry for the delay; just got out of work.  I was pretty sure it was .176
and just never saved when I first encountered it, so I updated and used
.178 - with the same issues.  (It also automatically says the same issue
for attributes, but if I add the quality "magician" and then delete it, the
attributes message of ": 10 Karma" goes away.

I will attempt to try to add then delete Aspected and Technomancer next,
but that'll have to wait until I get home.

Mobile at the moment, but if you head to /r/hubchargen, and look for the
character "Ricochet" (possibly second or third page by now), you'll find
the Google Drive folder with online copies.  I'd attach now, but the phone
is acting up.

**Comment by a-pestilence** [comment]
I wasn't sure If I should make a new issue or not, but a bug I've noticed falls under the same general topic.

If you're in priority character gen, add a point into your special attribute (edge is what i've been toying with), and then add either a cybernetic or bioware implant, it seems to skew the general karma cost of your special attributes.

ie. Add two points into edge with karma, which should cost 25 karma, and then add any implant causes  me to lose an addition 5 karma for whatever reason. Note, this is only for the first implant.

**Comment by chummer5a** [comment]
Generally if you're not sure whether an issue is linked or not, it's better
from our end if you raise a new issue and refer to the previous one. Makes
it easier for us to handle issue tracking through commits. Anyhoo, I'll
take a look into it. I have a suspicion I know what's going on.

**Comment by chummer5a** [comment]
Should be resolved in current nightlies.
