### ISSUE TITLE
Sum to 10 not using correct skills choice

### ISSUE THREAD

**Issue by CallidusD** [chummer5a/chummer5a#681]
In the current nightly (2/9/16) I have been trying to make a pc with DACBE priorities, but it keeps defaulting my skills back to the C rating priority and is missing the extra skill groups and skills available.

**Comment by chummer5a** [comment]
I'll take a look at what might be going on there, but why are you doing
standard priorities if you're doing sum to ten?

**Comment by CallidusD** [comment]
I honestly didn't notice. In addition, it is doing the same thing with normal priority gen. I have moved to a version before 5.179.698 for now.
