### ISSUE TITLE
House Rule - Don't double the costs of Qualities in Career Mode

### ISSUE THREAD

**Issue by Ryu2k** [chummer5a/chummer5a#687]
It doesn't work correctly for me. I can buy positive Qualities for the normal costs, but when i try to buy of negative ones, chummer doulbes the costs.

I use Chummer 5a - 0.5.178

**Comment by chummer5a** [comment]
Technically there's nothing wrong here, the house rule just doesn't double the purchasing cost. Will have a separate option for refunding in the next build.

**Comment by Ryu2k** [comment]
Ok, thanks. The flufftext of the options mentioned the buy off of negative Qualities, that has to be corrected, when there is an extra option. 

Also why refunding? When i try to buy off, as example, slow healer (3 Karma). It should cost with this option only 3 Karma to get rid of it, but it cost's 6.

**Comment by chummer5a** [comment]
Well that's essentially what it is; you're refunding the bonus karma you
got for taking the quality. You just have to pay more to refund it by
default. Anyway, will be fixed/added shortly.

**Comment by chummer5a** [comment]
Fixed in latest commit.
