### ISSUE TITLE
Infected Troll attributes

### ISSUE THREAD

**Issue by Malkard** [chummer5a/chummer5a#689]
Tried to create a troll ghoul with priority system:

-Created a Troll with priority system
-Put 5 points in BODY (10 total)
-Added Infected:Ghoul quality, choosing BOD and WIL for attribute increases
BOD remains at 10, should be 12.

I don't believe ghoul attribute bonuses are supposed to count as augmentations.
A quick and dirty solution is to change the minimum of the selected stats.  I tried it and it seems to be valid rulewise.  I also added attribute maximum modifications for the other stats.

The only thing I can't fix is the penalty to LOG and CHA. It should reduce their actual value (not just the maximum).  A workaround would be to leave out two attribute points, I'm not sure chummer would let me complete the character that way, though.  

I do not believe an attribute at 0 is valid in SR5.  If that is true, then removing two attribute points would simulate the fact that CHA and LOG start at 1 despite the ghoulish penalty.

Here is my suggested fix:
> 			<bonus>
				<selectattributes>
					<selectattribute>
						<attribute>BOD</attribute>
						<attribute>REA</attribute>
						<attribute>STR</attribute>
						<min>1</min>
					</selectattribute>
					<selectattribute>
						<attribute>BOD</attribute>
						<attribute>REA</attribute>
						<attribute>STR</attribute>
						<min>1</min>
					</selectattribute>
					<selectattribute>
						<attribute>WIL</attribute>
						<attribute>INT</attribute>
						<min>1</min>
					</selectattribute>
					<selectattribute>
						<attribute>WIL</attribute>
						<attribute>INT</attribute>
						<min>1</min>
					</selectattribute>
				</selectattributes>
				<enabletab>
					<name>critter</name>
				</enabletab>
				<armor>1</armor>
				<specificattribute>
					<name>BOD</name>
					<max>4</max>
				</specificattribute>
				<specificattribute>
					<name>REA</name>
					<max>2</max>
				</specificattribute>
				<specificattribute>
					<name>STR</name>
					<max>3</max>
				</specificattribute>
				<specificattribute>
					<name>INT</name>
					<max>1</max>
				</specificattribute>
				<specificattribute>
					<name>CHA</name>
					<max>-2</max>
				</specificattribute>
				<specificattribute>
					<name>LOG</name>
					<max>-1</max>
				</specificattribute>
			</bonus>

**Comment by chummer5a** [comment]
Right, I've got a better implementation for the attribute replacements, just pondering a way to handle the   stat reduction.
