### ISSUE TITLE
Wrong Price for Binoculars in custom PACKS Kits

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#691]
Step 1 - Create new character
Step 2 - Add binoculars to gear
Step 3 - Create new custom packs kit for gear
Step 4 - Add packs kit to another character

Cost of binoculars shows as 300$ plus 250$ for the image magnification enhancement. Price should be  50$ for binoculars and 0$ for image mag.

**Comment by chummer5a** [comment]
PACKs don't play nice with built-in gear, I think. Shouldn't be hard to fix.
