### ISSUE TITLE
City and Borough for Lifestyles?

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#692]
Is it a good idea to add some kind of input items for City and Borough to Lifestyles?

**Comment by chummer5a** [comment]
I'd think that would normally be covered by the Notes field, wouldn't it? There is a relatively large amount of unused space on the Lifestlyes tab so we could probably do something with it I suppose.

**Comment by whatevs5** [comment]
I was thinking that a drop down menu with applicable cities and boroughs (like the specializations drop down menu for the "Area Knowledge: Seattle"  knowledge skill) would make it easier for users to manage their lifestyles. If you were feeling really motivated, you could even set up a relationship between lifestyles and security ratings for each of the different boroughs.

**Comment by TheWyrmOuroboros** [comment]
I'd call that something for the Notes section - because honestly, if you have the right contacts, you can have Luxury-level everything in the middle of the Barrens, simply with a different explanation.

**Comment by ArchonMegalon** [comment]
Someone may actually be working on this... ;)

**Comment by chummer5a** [comment]
Implemented by @JoschiGrey
