### ISSUE TITLE
Problems with weapon lists

### ISSUE THREAD

**Issue by Irrigatus** [chummer5a/chummer5a#698]
Hi
Since the last update (5.177) i have trouble with some equipment lists.
For example the Ingram Smartgun doesn´t show up any longer instead i get the entry "Chummer.list.item"
clicking this i get an error and chummer crashes. Can someone help me with that, please?

Irrigatus

**Comment by chummer5a** [comment]
5.77 is an old build. Please update to 5.178 or later via http://github.com/chummer5a/chummer5a/releases.

**Comment by Irrigatus** [comment]
Thanks!  :)


Am 19.02.2016 um 00:46 schrieb Chummer 5 Is Alive:
