### ISSUE TITLE
Settings Panel cannot be closed when fontsize is at 125%

### ISSUE THREAD

**Issue by jurgendl** [chummer5a/chummer5a#700]
### Expected behaviour
button visible independent of font size, at least on 125% and 150%, scrollable settings pannel

### Actual behaviour
the button to save and close the settings panel is not visible on the bottum when Windows font size is at 125%, screen cannot be resized, nor scrolled

### Steps to reproduce the behaviour
set windows font size to 125%, open chummer, open settings

testen in:
Chummer.5.178
Chummer.Nightly.v5.179.712

**Comment by jurgendl** [comment]
![settings](https://cloud.githubusercontent.com/assets/11539040/13197724/ece8cca8-d7f5-11e5-8c6d-e0ee773b52be.png)

**Comment by Malkard** [comment]
Had the same issue.  That page has some weird auto layout code, so the button is outside the visible window.
A workaround is to hit <ENTER>.

**Comment by chummer5a** [comment]
Can't replicate it on Windows 10; the MoveControls code is mostly just preserving the correct sizes for translated text, so it shouldn't do anything too weird. What happens if you double-click on the Title bar at the top? It should expand to full screen, does that help at all?

**Comment by jurgendl** [comment]
expanding the window fullsize just gives you more whitespace on the bottom, no button

enter does work

**Comment by jurgendl** [comment]
PS I'm working on Windows 7 SP 1 Home edition
