### ISSUE TITLE
"Basic" Metamagics unchoosable

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#705]
### Masking and Flexible Signature cannot be choosen. either by full magicians or adepts( have not tested mystics). 
Chummer says do not meet requirements but do not list any criteria (and there should not be any?)
Issue 614 is about something similar and says partially resolved. 

### Steps to reproduce the behaviour:
 Take a magician or adept in career mode. Initiate. Try to add masking or flexible signature metamagic. (Does not even show until "show only metamagics I can take" is "unclicked").

Metamagics from Street grimoire (basic and advanced) is on wishlist too naturally.
Thanks for a wonderful character creator (at least 99.5% perfectly working :-)  )

**Comment by chummer5a** [comment]
That would be because you haven't taken the appropriate Art to unlock the Metamagic, or don't have the Houserule enabled that disables the Art requirement. Working as intended.

**Comment by drakir75** [comment]
Please list all requirements for metamagics in chummer. And please give me
a page number for rules reference, I can't find the Art requirement you
speak of. I have searched both Core rulebook and Street Grimoire.
And last, where in Chummer can I "take an Art"? Can't find that either.
  /Drakir

**Comment by drakir75** [comment]
Found it
