### ISSUE TITLE
Skillwires Essence not calculated properly

### ISSUE THREAD

**Issue by Blade98** [chummer5a/chummer5a#717]
### Expected behaviour
As per SR5 456, Skillwires are Rating x 0.1 for essence therefore adding Skillwires at Rating 1 should cost 0.1 essence. Addning Skillwires at Rating 2 should cost 0.2 essence

### Actual behaviour
When adding Skillwires at Rating 1, the essence cost is reported as 0.2. When adding Skillwires at Rating 2, the essence cost is reported as 0.4

### Steps to reproduce the behaviour
Add Skillwires into the Cyberware and Bioware tab

**Comment by HaikenEdge** [comment]
Corrected in https://github.com/chummer5a/chummer5a/pull/718 and awaiting merge.

**Comment by tcjennings** [comment]
This bug exists again in 5.204 and current master.

**Comment by chummer5a** [comment]
Not a bug now. It's in Chrome Flesh as being 0.2 per Rating.

**Comment by tcjennings** [comment]
Chrome Flesh has skill wires at 0.1 per rating on page 225 and 0.2 per rating on page 78 and again on page 222. Sigh. I guess 2 votes beats 1. Thanks.

**Comment by chummer5a** [comment]
[amend_skillwire_cyberware.zip](https://github.com/chummer5a/chummer5a/files/2849862/amend_skillwire_cyberware.zip)
If your GM's kosher with using the CRB version, you can use this to amend it.
