### ISSUE TITLE
Bone Lacing Augmentation not changing some stats

### ISSUE THREAD

**Issue by Blade98** [chummer5a/chummer5a#724]
### Expected behaviour
(Using 5.179.734) When adding Bone Lacing, an increase in the BOD stat should be present as well as per Bone Lacing Chart on Page 455. For example, If I had BOD 9 and got the plastics bone lacing, my BD should now be 10. an increase of the overall armor as well as STR to Unarmed attack should be present

### Actual behaviour
There is no change to BOD attribute or Unarmored Attack Skill. However, the armor stat is changed as expected.

### Steps to reproduce the behaviour
Add Bone Lacing and no changes are applied to reported attribute/skill

**Comment by HaikenEdge** [comment]
That's because, if you read the rules on page 454, it only gives Body for resisting physical damage, and doesn't actually improve your Body rating.

**Comment by joha4270** [comment]
I am somewhat tempted to change the issue template to say in all caps "BONELACING WORKS AS INTENDED"

**Comment by Blade98** [comment]
OK, sorry about that... I guess I misinterpreted that.

**Comment by joha4270** [comment]
It is not you who should be sorry. LOTS of people made that mistake, so the book is probably the problem and not the people.
Blame CGL editing

**Comment by Blade98** [comment]
BTW, I just wanted to let you guys know how awesome this app is and what a great job you all do to keep it up to date and making it better. It is really appreciated. 

Also, If I wanted to add a feature request, is there a specific section to put that in?

**Comment by joha4270** [comment]
Same place as you report bugs. But please take a few seconds to search to
make sure there isn't already a duplicate, either open or closed as "not
happening"
