### ISSUE TITLE
Cyberears Basic System Not Available

### ISSUE THREAD

**Issue by Blade98** [chummer5a/chummer5a#725]
### Expected behaviour
When trying to add earware augmentations, I should be able to select Cyberears as per the chart on Page 454. As with the Cybereyes Basic System, Sound Link is included for free.

### Actual behaviour
Cyberears is not available in the menu

**Comment by joha4270** [comment]
![image](https://cloud.githubusercontent.com/assets/4454884/13374276/e3a28cda-dd7f-11e5-8086-e0dea586d038.png)

Unable to reproduce

**Comment by Blade98** [comment]
OK guys, I'm really sorry about the non-issue bugs that I just reported. I'm not paying as much attention as I thought I was.
