### ISSUE TITLE
Custom Chargen (Priorities and Karma) - Feature Request

### ISSUE THREAD

**Issue by Blade98** [chummer5a/chummer5a#726]
Would i be possible to have a feature where when you start creating a character, you can modify the amounts in the priorities? For example, our GM recently had a campaign where he modified the starting cash priority from default to A-300,000 B-175,000, C-85,000, D-30,000 and E-6,000.

My question would be if there was a place that we can make these kind of changes (Not just for money, but all priorities)

Another thing he did was reduce the Karma from 25 to 20

Thanks again,

Blade98

**Comment by joha4270** [comment]
>Would i be possible to have a feature where when you start creating a
character, you can modify the amounts in the priorities? For example, our
GM recently had a campaign where he modified the starting cash priority
from default to A-300,000 B-175,000, C-85,000, D-30,000 and E-6,000.

>My question would be if there was a place that we can make these kind of
changes (Not just for money, but all priorities)

Look into the data folder. There should be a file named priorities.xml

Also take a look at [this](
http://chummergen.com/chummer/wiki/Custom%20Data%20Files.ashx)



>Another thing he did was reduce the Karma from 25 to 20

One day i'm tracking this down and make the karma amount box visible, but
something, somewhere plays with it and other stuff have been higher up
the priority list when it was only me it was bothering.

**Comment by Blade98** [comment]
Thanks for the answers, I'll definitely looks at that.
:)
