### ISSUE TITLE
Modification Slots for Vehicles

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#729]
Ran a search and couldn't find it in the forum/

### Expected behaviour
Vehicles should have a number of modification slots for each type of modification equal to its Body rating.

### Actual behaviour
Vehicles can only have a total number of modifications equal to its Body, regardless of the modification slot cost of the modifications or the type of modification.

### Steps to reproduce the behaviour
1. Open a character
2. In "Vehicles & Drones" tab, purchase a vehicle.
3. Add a number of modifications to the vehicle equal to its Body rating
4. Attempt to add another vehicle modification and receive message: "This item has reached its Capacity limit."

**Comment by AMDX9** [comment]
Rigger 5 modification rules are not currently implemented in Chummer. I am trying to revamp the vehicle system to support both the separate drone and vehicle modification rules that were introduced in Rigger 5, but until then you will probably need to track it separately.

**Comment by HaikenEdge** [comment]
Wilco. Thanks for the update.

**Comment by skarsol** [comment]
This is enabled now (or will be when the nightly is generated). There is no "Capacity limit" alert, but it shows that category slot going negative.

**Comment by trekkieyk** [comment]
I've found that this issue is still unfixed in [Nightly-v5.179.824](https://github.com/chummer5a/chummer5a/tree/Nightly-v5.179.824). I recommend reopening.

**Comment by skarsol** [comment]
@trekkieyk I'm unable to duplicate. It seems to be working fine for me with the drone options both on and off. Can you tell me how to duplicate what you're seeing?

**Comment by trekkieyk** [comment]
It's possible I ought to have opened a separate bug. In any case, vehicle modifications seem to be operating under both the vehicle and drone rules. The separate tracks for Body, Drivetrain, etc. which you added (thanks!) do act as expected, but the normal "Slots" item is still there, and you can't use more mod slots across all tracks than the Body, or you get the standard "This item has reached its Capacity limit" message.

You can repro by selecting a vehicle and filling or nearly filling one track, such as Body with Mechanical Arms (Articulated), and then trying to add mods on a different track, such as Weapon Mount Type (Standard) for Weapon. I've checked this on the Mirage and the Hound, but it should work for any vehicle. It repros with and without drone options enabled. Latest version I've checked is *.828.

**Comment by skarsol** [comment]
Oooh, I didn't purge the old Slots code because I didn't think it was actually doing anything. I'll take a look. I might need to add a check to still use the old Slots code if the Rigger 5 book isn't checked.

**Comment by skarsol** [comment]
Fixed in next Nightly.
