### ISSUE TITLE
Exotic ranged weapon

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#732]
The Ares Screech Rifle uses a power pack as "ammunition" - good for 10 blasts until it has to be recharged. Cannot actually "load" the weapon because Chummer5a gives the error message:

"You do not have any Exotic Ranged Weapon Ammunition remaining!"

Therefore Chummer5a cannot be used to keep track of used discharges during play.

**Comment by chummer5a** [comment]
Yeah, gonna have to add some code support for this one. Should be done sometime tomorrow.

**Comment by chummer5a** [comment]
I've added the peak-discharge ammo units. Power packs have been added as clip items, but that needs some work because of the way it's supposed to work. Anyway, this issue is resolved.
