### ISSUE TITLE
Notes added to equipment not printing

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#734]
Notes added to gear or vehicles are not printing even if "Print Notes" is checked under Options->Character and Printing

**Comment by chummer5a** [comment]
Depends on the sheet you use. Some of them aren't configured for it. Fancy Blocks uses them, but I don't think the default ones do. Low priority because I hate messing with XS, but a relatively easy fix if you'd like to take a look at implementing it yourself.

**Comment by Lochabar** [comment]
Forgot to close this issue.
