### ISSUE TITLE
Street Cred formula Chummer Help description

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#736]
The Street Cred calculation is "(Career Karma() / 10) - Burnt Street Cred()". So for a character with 219 karma, and 4 street cred burnt to remove 2 points of Notoriety, the calculation is "(219 / 10) - 4 = 21-4 = 17".

The Chummer Help for the actual calculation reads "(Career Karma() - Burnt Street Cred() ) / 10". So for the same character, according to the help, the calculation is (219 - 4) / 10 = 215/10 = 21".

The calculation by Chummer5a is correct, the help text needs correcting.

**Comment by chummer5a** [comment]
Fixed in an earlier commit.
