### ISSUE TITLE
Order of clothes table

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#741]
The clothes table is listed with the descriptor first, then the item. For example "Nice shirt" or "Good pants". This causes the individual items to be spread out through the display:

Good pants
Good shirt
Good shoes
Good skirt
Nice pants
Nice shirt

The rest of the tables list the descriptor second. For example "Shirt, nice" or "Pants, good", causing like items to be grouped together:

Pants, good
Pants, nice
Shirt, good
Shirt, nice.

**Comment by skarsol** [comment]
Not sure this is an issue. When you're adding clothing you're typically adding a full set of "Good" clothes, not multiple qualities of "Pants." What's the benefit of grouping by type instead of quality?

**Comment by chummer5a** [comment]
Yeah, that gear's pretty much a straight rip from the tables at the back of run faster. As a general rule we don't change gear names around.
