### ISSUE TITLE
Use of "Equipped"

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#742]
Each item of Gear has a check box "Equipped", presumably to able to print only those items actually on the character. However this does not seem to have been implemented; the character sheets prints all items listed under gear, including those where "Equipped" is not checked.

Can this be implemented?

**Comment by chummer5a** [comment]
Equipped is actually mostly used for calculating whether bonuses from gear should be applied. Skillsofts, for example. Wouldn't be particularly difficult to implement that into the character sheets, but I'm lousy with XSL design. Fancy Blocks has some support for it, I can see that much.
