### ISSUE TITLE
License change. Permission by all contributors?

### ISSUE THREAD

**Issue by Fightbackman** [chummer5a/chummer5a#751]
As far as i know not all of the contributers were asked for a license change. Espacialy the original developers have to give theire permission for a license change. Did some managed to do this legaly necessary stuff?

I also commited some kind of stuff but i didn't matter because I like Open Source an the GPL but others could make some trouble about this.

**Comment by joha4270** [comment]
This is not actually a license change. Chummer have always been GPL. Before now, that required a little digging to find out, but we (the development team) decided to work toward compliance.

**Comment by Fightbackman** [comment]
Ok this is realy cool. My last information was that it is public domain.
