### ISSUE TITLE
Shadowrun Lockdown

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#754]
Hi all, 

I cannot seem to find Shadowrun Lockdown on the list of available books. There is some crunch in the back such as Microwave guns and the ability for technos to go Dissonance and a few more.

**Comment by chummer5a** [comment]
Short version, nobody's submitted the content and I have higher priorities at the moment.

**Comment by OLStefan** [comment]
Closing this issu, beacause there are only 3 new Devices, none of which has a Price given, the two new weapons have no skill associated and the paragraph about Dissonance TMs has no implementable rules.
