### ISSUE TITLE
Knockout is Touch not LOS mislabled in Github

### ISSUE THREAD

**Issue by EzraTwitch** [chummer5a/chummer5a#757]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Steps to reproduce the behaviour

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

**Comment by chummer5a** [comment]
Spell is listed as touch in the rulebook. No errata provided.

**Comment by EzraTwitch** [comment]
True but it IS NOT listed as touch on chummer5.

**Comment by chummer5a** [comment]
You'll be using 5.178 or earlier then. https://github.com/chummer5a/chummer5a/releases Grab a nightly build.

**Comment by EzraTwitch** [comment]
Gotcha thanks.
