### ISSUE TITLE
Orthoskin and Bone Lacing not stacking

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#758]
This came up when I was making a Troll so I tried making a basic human (both with sum to ten). I got the same results.

Made human. Armor read 0
Added used titanium bone lacing. Armor read 3
Added rating 4 used orthoskin. Armor read 4

Made troll. Armor read 1
Added used titanium bone lacing. Armor read 4
Added rating 4 used orthoskin. No change to armor, still read 4

Made human. Armor read 0
Added standard aluminum bone lacing. Armor read 2
Added rating 3 standard orthoskin. Armor read 3

**Comment by HaikenEdge** [comment]
I replicated this in the latest Nightly version, but couldn't replicate it in 0.5.178, meaning it got broken somewhere between the latest stable release and the nightly ones.

**Comment by Nightghaunt** [comment]
Yeah I first found this using  5.179.758 so I got the latest 5.179.765 and got the same results.

**Comment by chummer5a** [comment]
Yeah, I was fiddling with precedence and broke it a bit. I'll try and get
it fixed in the next buld.
