### ISSUE TITLE
Hand Loads

### ISSUE THREAD

**Issue by Nightghaunt** [chummer5a/chummer5a#759]
I don't know if this has been brought up. I did a search and didn't find anything. 

Can we get a way to either purchase hand loaded ammo (+1DV or -1AP) or tag ammo as hand loaded (+1DV or -1AP)?

**Comment by chummer5a** [comment]
Yeah, I need to have a think about how to handle it. I really don't want to make Hand-Loaded versions of all the ammunition, but that's the only real way to implement it right now.

**Comment by Nightghaunt** [comment]
Hmmm, yeah and there's two different cost as well depending on if you hand loaded it or bought it hand loaded.

Can you handle it in some way similar to how you handle ammo gun type? By that I mean, you don't have separate ammo entries for each gun type but you are able to show what gun each type of ammo is for when bought. (I'm guessing there is some variable or table reference being used for this?) So you buy ammo as say, APDS, heavy pistol,  standard load or APDS, heavy pistol, self hand load, +1DV or APDS heavy pistol, bought hand load, -1AP etc. Then the DV or AP displayed is modified based on that variable or reference? Something like that?

There will be 5 different versions of each hand loadable (is that a word? lol) ammo:

Standard
Hand Load, Self, +1DV
Hand Load, Self, -1AP
Hand Load, Bought, +1DV
Hand Load, Bought, -1AP

 ...I don't know programing and am talking out my ass so don't be to hard on me. lol

**Comment by chummer5a** [comment]
Yeah, that's more or less the way I'd handle it. Not a huge fan of doing things that way, but it is what it is.

**Comment by skarsol** [comment]
Might be better to just allow ammo to take mods and make the hand loads into mods for ammo?

**Comment by chummer5a** [comment]
I'm not sure it'd play nice with the reloading mechanism, since that just
looks for stacks of the same gear ID. We'd probably have to separate ammo
into a subclass like commlinks to make it work.

**Comment by Lochabar** [comment]
To throw in another problem Mission play does not allow creation of your own hand loads.
From SRM Chicago FAQ 0.4 p59:

Will I be able to create my own hand loads? ​ (​ Hard Targets​ , pg. 189)
No, but they are available for purchase.

**Comment by Kyanor** [comment]
So any progress on this request?

**Comment by chummer5a** [comment]
Currently under discussion in the dev thread, actually. Still hashing out the best way to implement it.
