### ISSUE TITLE
Rigger interface

### ISSUE THREAD

**Issue by auerbalazs** [chummer5a/chummer5a#764]
### Chummer Version
5.179.742.0
### Expected behaviour
It is possible to add a rigger interface to a vehicle.
### Actual behaviour
Couldn't add rigger interface to a vehicle, cannot find in the Gear/modification list.
### Steps to reproduce the behaviour
1. Add a new vehicle
2. r-click add modification
3. Only weapon mounts shows (also manual operation is missing)

### Operating System
Win8

**Comment by auerbalazs** [comment]
I found it, I enabled rigger 5.0 and worked. Problem solved.

**Comment by AkiraSama** [comment]
Rigger interface is available in the Core Rulebook (pg. 461), shouldn't need to enable Rigger 5.0.

Still a problem in version 5.195.92.
