### ISSUE TITLE
Chummer incorrectly calculates karma expenditure when raising special attributes.

### ISSUE THREAD

**Issue by jim1701** [chummer5a/chummer5a#765]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Steps to reproduce the behaviour 1. Select a priority for Metatype that has special attribute points to expend but not so many that you can max out both magic and edge.  2.  Select a magic priority that allows for a awakened character but gives a magic attribute less than maximum.  3.  Proceed to the character generation screen and buy ware sufficient to reduce magic.  4.  Buy magic back using the special attribute points.  5.  Use any remaining special attribute points.  6. Raise edge  (or magic if possible) by using karma.  

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

**Comment by chummer5a** [comment]
This should be resolvedi n current nightly builds. We don't have an ETA on when the next full release will be, so if this is a blocking issue for you I'd suggest you try updating manually to a nightly build and go from there.
