### ISSUE TITLE
In Add Exotic Skill dialog, switching from Melee to Ranged does not update weapon list

### ISSUE THREAD

**Issue by Regenspaziergang** [chummer5a/chummer5a#768]
### Chummer Version
5.179.769
### Expected behaviour
In "Add exotic weapon" dialog, selecting "Ranged" from the upper dropdown list should update the weapon list, filling it with ranged weapons.
### Actual behaviour
The weapon list is not updated for ranged weapons. (The opposite seems to happen when program language is German; the ranged weapons are displayed first and switching to melee doesn't work.)
### Steps to reproduce the behaviour
In the "Skills" tab during character creation, click "Add Exotic Skill" and switch between "Ranged" and "Melee".

**Comment by Vexsaken** [comment]
Also throwing syringes are not there
