### ISSUE TITLE
Switching program language should work without restart

### ISSUE THREAD

**Issue by Regenspaziergang** [chummer5a/chummer5a#769]
### Chummer Version
5.179.769
### Expected behaviour
When selecting the program language in the Options dialog, the program changes its language to the selected one.
### Actual behaviour
The program language is not changed in the running instance; the program has to be restarted for the setting to go into effect.
### Steps to reproduce the behaviour
Select a language from the languages dropdown list in the Options dialog.
### Notes
Would be extremely helpful for multi-language teams or when one possessed source books of different languages. Would also help with filing issues in English when usually using a non-English setting.

**Comment by joha4270** [comment]
Eh. Probably not happening. 

I have some idea

**Comment by joha4270** [comment]
Probably not happening.

I might have a hack to make this mostly work, but i have the feeling it will be the source of some *really* interesting bugs so i'm a little reluctant.

Won't touch everything either, some labels are going to escape.

**Comment by joha4270** [comment]
Too many places that require flushing caches. Not happening

**Comment by Regenspaziergang** [comment]
I understand, Thanks for looking into it! <div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: Johannes Elgaard <notifications@github.com> </div><div>Datum: 16.04.16  15:43  (GMT+01:00) </div><div>An: chummer5a/chummer5a <chummer5a@noreply.github.com> </div><div>Cc: Regenspaziergang <felics_dombek@hotmail.com> </div><div>Betreff: Re: [chummer5a/chummer5a] Switching program language should work without restart (#769) </div><div>
</div>
Too many places that require flushing caches. Not happening

---
