### ISSUE TITLE
Possible Bug: Cannot save to career mode if contact cost higher then 7

### ISSUE THREAD

**Issue by ChristopherG84** [chummer5a/chummer5a#770]
##Required Fields
This was a basic Priority Build, Standart Runner.

I created a contact with 4 Connection, 5 Loyality rating.
I selected "Mark as created" and tried to save. Chummer denied that with the following message:
"You can not have a contact with more then 7 points at chargen".

However I could find no such rule in 5E.
The rule is that you can't have a contact with a connection rating higher then 6 at chargen. I could find no limit for Loyality (other then the usual 6) and no mention of any limit of the sum. So I asume even 6/6 is a valid contact, even though it sums to 12.

I got around it by marking the Contact as "free" and just letting the Contact points be lost.

**Comment by chummer5a** [comment]
A single contact may not have more than 7 Karma spent on them at character creation. Page 98, SR5 core.
