### ISSUE TITLE
Prime Runner 6x free contacts karma is not applied

### ISSUE THREAD

**Issue by rhockett94** [chummer5a/chummer5a#771]
### Chummer Version
5.179.769

### Expected behaviour
Prime Runners recieve 6x charisma free contacts karma instead of the usual 3, as per Alternate Gameplay rules on SR5, p64

### Actual behaviour
Prime Runners get the regular runner level of 3x charisma unless the "Free Contact Points Equal To Charisma" option in House Rules is checked.

### Steps to reproduce the behaviour
Make a Prime Runner character and see for yourself.

### Helpful Fields
I found this out attempting to resolve the problem myself.
gameplayoption.xml [Line 38] lists the free contact karma for each Alternate Gameplay rule.
This is set to six and it is not represented in the sheet.

### Operating System
Win10 x64

### Use of international language content
Default English

### Last known good version
None

### Link to affected character file
https://dl.dropboxusercontent.com/u/334984/chummer5/Shinzaemon%20completed.chum5

**Comment by chummer5a** [comment]
Currently Chummer expects that the contacts and karma multipliers will be set as part of the global options. Shouldn't be too much of a problem to override that if you're playing with specific campaign settings.

**Comment by rhockett94** [comment]
Perhaps a global automatic change per campaign? As in campaign specific settings files?

**Comment by chummer5a** [comment]
Generally speaking that's what the settings files are for though. I'll see about getting it implemented, shouldn't be a huge headache.
