### ISSUE TITLE
Increasing Edge Costs Additional Karma

### ISSUE THREAD

**Issue by leirynot** [chummer5a/chummer5a#777]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.178
### Expected behaviour
Attribute karma costs are set to 5x the value you're getting, so increasing edge from 1 to 2 in chargen should cost 10 karma.
### Actual behaviour
Increasing edge from 1 to 2 in character creation is costing 15 karma. The field that shows your special attribute points and how much karma you spend on special attributes says only 10 is spent. Additionally, this stops chummer from publishing characters into career mode because more than 10 karma was spent on special attributes.
### Steps to reproduce the behaviour
Make a new character using either priority or sum to ten, ensuring the metatype only starts with one edge, then clicking the button to increase edge with karma. Every time it takes 15 karma to increase edge to 2.
##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System
Windows 7
### Use of international language content
None

**Comment by chummer5a** [comment]
Should be fixed in current nightly builds.
