### ISSUE TITLE
Special Attributes

### ISSUE THREAD

**Issue by VE6CPU** [chummer5a/chummer5a#778]
Version: 5.179.769 Debug Build

Loading saved character when used a special attribute point on magic it should remember it was spent on magic.

Doesn't save that the point was spent on magic but puts it back in the pool so I have to increase it every time I load the character.

Create magic user (human in this case) and spend at least one special attribute point on magic.  Save character, exit program. load program, load character.  Magic will be at original and special attributes will show 1 of 1.

Arch Linux using Codeweavers (Windows 7 environment).  Also happens on a real Windows 10 machine at work.

Plain english

Not sure it's been awhile and I was just trying out a nightly build.

https://thebitbucket.ca/owncloud/index.php/s/HcBFSTgVVg59X4Q

**Comment by chummer5a** [comment]
Fixed in latest build.
