### ISSUE TITLE
Drone weapon mounts don't accept weapons

### ISSUE THREAD

**Issue by skarsol** [chummer5a/chummer5a#781]
### Chummer Version
5.179.769
### Expected behaviour
Right click "Add Weapon" allows a weapon to be added to a drone weapon mount.
### Actual behaviour
Pop-up saying Weapons can only be added to Weapon Mounts.
### Steps to reproduce the behaviour
Try to add a weapon to a drone weapon mount (IE: Large Weapon Mount (Drone))

**Comment by chummer5a** [comment]
Fixed in latest commit.
