### ISSUE TITLE
Adding armor to a drone replaces the exisiting armor

### ISSUE THREAD

**Issue by skarsol** [chummer5a/chummer5a#782]
### Chummer Version
5.179.769
### Expected behaviour
Adding 3 armor to a drone with 4 armor results in 7 armor
### Actual behaviour
Adding 3 armor to a drone with 4 armor results in 3 armor
### Steps to reproduce the behaviour
Add 3 armor to a MCT-Nissan Roto-drone

**Comment by SquadronROE** [comment]
Reproduced in 5.179.781. Armor (Drone) is in the Rigger 5.0 book, right? Want to make sure I check the reference before I flag this as a bug and try to fix it.

**Comment by skarsol** [comment]
Sorry, yes, R5:123. Looking at it though, it's a little complicated since the cost depends on the base armor already there. "Cost equals the upgraded Armor multiplied by the drone’s Body, then multiplied by 200. Increasing to an Armor of 15 on a Body 3 drone would cost (15 x 3) x 200, or 45 x 200, or 9,000 nuyen." I think #789 is the actual bug though. Looking at the case of the Roto-Drone, buying "Armor (Drone) (Rating 6) is priced correctly, and having the drone be set to 6 armor at that point is correct as well, but "Armor (Drone)" should let me go to 10, not 6, due to "Armor Restricted (Drone)" not being required till the *added* armor is greater than 6, not the total armor. 

The correct result can be obtained by adding "Armor (Drone) (Rating 6)" and "Armor (Drone) (Rating 4)" to result in Armor 10 and not Restricted, but that's clunky. So not sure if this qualifies as "bug" or not.

**Comment by skarsol** [comment]
So, going back through the rules, it appears I was mixing this with the Vehicle armor rules. :(

**Comment by SquadronROE** [comment]
So long as it's closed! I'll keep plugging away at that exception bug you
found, with the handling. :)
