### ISSUE TITLE
Free contact/knowledge skill points ignore augmented attributes

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#783]
### Chummer Version
5.179.775
### Expected behaviour
If you activate the free Conctact points and free Knowledge Skills, they should be calculated from the augmented attribute (e.g. CHA * 3 or INT+LOG * 2).
### Actual behaviour
Free contact/knowledge skill points are always calculated from the base attribute, disregarding any augmentations.
### Steps to reproduce the behaviour
Create new character (human).
Give him the bioware Cerebral/Cerebellum Booster and the Infected: Vampire quality (choose CHA twice as bonus attribute).
Free contact and knowledge skill points are still calculated from the unaugmented attribute.
### Operating System
Win7
### Use of international language content
No.
### Last known good version
None.
### Link to affected character file
https://my.mixtape.moe/jmwdqp.chum5

**Comment by chummer5a** [comment]
As far as I'm aware that's per RAW.
Attributes boosted by cyberware or bioware do not affect the calculation
for things such as points for Knowledge skills or Contacts. p95, SR5.

**Comment by Skarablood** [comment]
Well, that's dumb. Forget about the issue, then, but could it be implemented as a house rule/optional rule?

Also, something very minor that just came up and probably isn't even worth it's own issue: Responsive interface gear (Run & Gun p.86) was errata'ed to use up 4 Capacity slots in the armor and 2 Capacity slots in the helmet - Chummer still lists it as 2 Capacity slots in the armor and 1 Capacity slot in the helmet.
