### ISSUE TITLE
Jack of All Trades applies when using Karmagen

### ISSUE THREAD

**Issue by Ternega** [chummer5a/chummer5a#785]
### Chummer Version
5.179.775
### Expected behaviour
JOAT explicitly states that it shouldn't apply at gen
### Actual behaviour
JOAT applies if Karma gen is used
### Steps to reproduce the behaviour
Make new character, chose Karma gen, add JOAT to qualities and try to spend karma on skills.

JOAT description is in Run Faster, page 147.

**Comment by joha4270** [comment]
Actually reading the relevant quality told me i was looking at the wrong place. Already implemented on the newskills branch

No hard ETA for merge into master
