### ISSUE TITLE
Radar Sensor not available in Sensor Array

### ISSUE THREAD

**Issue by skarsol** [chummer5a/chummer5a#791]
### Chummer Version
5.179.781
### Expected behaviour
Radar Sensor (CF:81) should appear in the Sensor Functions list for Sensor Arrays.
### Actual behaviour
It does not. It appears to be only attainable as implanted Headware. This listing for this is more "legit" than the one for X-Ray (only mentioned as an option on a specific drone and has no rules that I can find) and X-Ray is included in Sensor Functions, so makes sense this should be there too.

**Comment by skarsol** [comment]
This didn't get fixed because of the way the different pull requests were structured. (My first time messing with pull requests). Unless that was intentional on your end?

**Comment by chummer5a** [comment]
Merging the pull request automatically closes any issues that reference it. Just one of those github things.
