### ISSUE TITLE
Burning out occuring at magic 0, not max magic 0

### ISSUE THREAD

**Issue by dezzmont** [chummer5a/chummer5a#801]
### Chummer Version

0.5.177

### Expected behaviour

Core rules 278 states that when your magic hits 0 you lose all ability to preform magic, but you are explicitly allowed to re-raise your magic up as long as your magic max was above 0. This means that if one burns out to magic 0 at gen they should exit gen with a magic of 0 but a max magic matching 6-essence.

### Actual behaviour

When one burns out to magic 0 at gen you can no longer raise magic again, and can't apply magic improvements to force max magic to the correct rating.

### Steps to reproduce the behaviour

Create a mage or adept with low magic

Burn out magic to 0 at gen, but keep max above 0

Complete the character.

### Link to affected character file

https://drive.google.com/file/d/0BxYk2R_-1GmzbHRDWTFrZWZ6ZjQ/view?usp=sharing

**Comment by chummer5a** [comment]
Thiiiis isn't going to be fun to rewrite. Shit.

**Comment by dezzmont** [comment]
Sorry for being the one person on earth crazy enough to want to do this.

**Comment by chummer5a** [comment]
Nah, it's all good. Just not something I'll be able to get to for a while.
