### ISSUE TITLE
Lifestyle Qualities do not modify cost correctly

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#803]
### Chummer Version
5.179.804
### Expected behavior
Lifestyle Qualities apply the modifier specified
### Actual behavior
Lifestyle Qualities apply 1% of the specified modifier (Cramped [10%] discounts 0.1%)
### Steps to reproduce the behavior
Add any quality to any lifestyle and OK the dialog
Cost displayed on the dialog is correct, cost displayed (and applied) is incorrect
### Operating System
Windows 10 Pro
### Last known good version
5.179.714 (Gods I haven't updated in so long)

**Comment by chummer5a** [comment]
Should be resolved in 5.179.808.
