### ISSUE TITLE
Rigger 5 Rule is not activated correctly

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#805]
### Chummer Version
5.179.804
### Expected behaviour
When enabling "Use Drone Modification Rules (R5 122)" on Optional Rules all vehicles and drones should switch to Rigger 5 style modding
### Actual behaviour
Rigger 5 style modding is always displayed in Creation mode but never in Career mode
The career mode validity check always assumes that Rigger 5 modding is disabled
### Steps to reproduce the behaviour
Create any character with a vehicle or drone
### Operating System
Windows 10 Pro
### Last known good version
This is the first version I have used with the Rigger 5 Mod Rule
### Link to affected character file
This is the character I made when I found this issue
I have set Ignore Creation Rules to get around the issue
The vehicle is valid under Rigger 5 mod rules but uses 7 slots on the standard system (Limit is 4)
http://puu.sh/oaFfd/9b98aeebe8.chum5

**Comment by skarsol** [comment]
I haven't looked at career mode at all for the Rigger 5 changes yet. Once I get the stat stacking working in #799 I'll try and port it all to career mode.
