### ISSUE TITLE
So, there's still an issue with special att loading when it's lowered

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#807]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version - 5.179.808
Although some were made under earlier versions

### Expected behaviour
Character with magic or resonance lowered below starting level should be able to be loaded.

### Actual behaviour
Error pops up and character doe not load properly. seems to load as a 400 karma, but not much works right.

### Steps to reproduce the behaviour
Create character with special attribute. Lower attribute by buying cyberware. Save. Try to load.

##Helpful Fields - Filled with contects of details box when error occurs.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '5' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 15092
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 557
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.808.0
    Win32 Version: 5.179.808
    CodeBase: file:///C:/Users/Matt/Desktop/Chummer.Nightly/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34285 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34283 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

### Operating System
Windows 7 Home Premium SP1
### Use of international language content
Yes, but not active at moment.
### Last known good version
None Known
### Link to affected character file
https://drive.google.com/open?id=0B-mC2hIA5p-xT3I5Ykc5Z2l2Y1U
https://drive.google.com/open?id=0B-mC2hIA5p-xRllBRFRidVFQYnc
Others if asked for.

**Comment by chummer5a** [comment]
Hrm, I can't replicate it in 179.808.

**Comment by AriMatt2** [comment]
Making log of tests.

Got and tried 179.805. Tester4 loads.
Got and tried 179.806. Loads.
Got and tried 179.807. Loads
Redownloaded 179.808 and put in different folder. Could not load Tester4. Same error.
Went to system settings. Checked for English local and deleted non-English keyboard settings.
Used previous install of 179.808. Could not load.
Got new installation, put on desktop as loose files. Could not load.

Deleted Tester4, got copy from Google Drive. Tried normal install. Could not load.
Suggestions on Chummer files or settings I should share?

**Comment by chummer5a** [comment]
I'm thinking it has to be something with your environment; what's your environment? Windows 7/8/10, .net version?

**Comment by AriMatt2** [comment]
Windows 7 Home, Service Pack 1. Looks like framework 4.5.2. I'm guessing I should try an upgrade.

**Comment by joha4270** [comment]
the NET 452 is fine, chummer is targeting 451
