### ISSUE TITLE
Black Market Pipeline Not Providing Discount

### ISSUE THREAD

**Issue by Karmal-Firefox** [chummer5a/chummer5a#809]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Steps to reproduce the behaviour: Just check the box. Also noticed that when typing in the category for the Black Market Pipeline a "." is added to the end. Unsure if it is connected.

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

**Comment by chummer5a** [comment]
Not all selection forms have been set up to process the black market discount properly. Will be fixed shortly.
