### ISSUE TITLE
edit & show ammount (when greater than 1) in gear when added as a plugin

### ISSUE THREAD

**Issue by jurgendl** [chummer5a/chummer5a#814]
### Chummer Version
Chummer.Nightly.v5.179.824

### Expected behaviour
(1) if you add something as a plugin, for example trauma patches to a medkit or ammo to a hard shell briefcase, it should be nice to see the amount added when more than 1
(2) you can't change the amount afterwards

### Actual behaviour
(1) the number doesn't show up when printed
(2) the amount is disabled

### Steps to reproduce the behaviour
add gear medikit, add as a plugin traume patches

### Last known good version
latests release to latest prerelease

**Comment by chummer5a** [comment]
Hrm, this is kind of working as intended. Plugins are generally expected to have a 1:1 relationship with their parent item. Allowing gear categories may work, but there are some issues with that. We may have to make some structural changes to just treat everything as a location.
