### ISSUE TITLE
print, save as html, mugshot, missing file

### ISSUE THREAD

**Issue by jurgendl** [chummer5a/chummer5a#817]
### Chummer Version
Chummer.Nightly.v5.179.769

### Expected behaviour
mugshot should be visible

### Actual behaviour
missing reference to file

### Steps to reproduce the behaviour
choose a image as mugshot, print, export to html

### proposed fix
use html inner image resource:
img src="src=\"data:image/png;base64,x"
where x is the base64 encoded image data like it is found in the character chummer file

**Comment by chummer5a** [comment]
Apparently we changed this a while back in order to prevent a legacy issue with Internet Explorer 8. Easiest fix is going to be changing the mugshot path for the appropriate XSL file. Replacing <img src="{mugshot}" /> with <img src="data:image/png;base64,{mugshotbase64}" /> will do the job.
