### ISSUE TITLE
Rigger oriented vehicle enhancements

### ISSUE THREAD

**Issue by skarsol** [chummer5a/chummer5a#820]
Breaking off portions of #163 from @BodieSullivan.

Advanced Vehicle Page
 I play riggers a lot and they involve a lot of intense inventory management. I am not sure the best way to implement this but would like to hear any ideas folks have.
•Designed for Riggers
•Have quick stats for driving and vehicle actions
•Better gear management
•Manage RCC, autosofts, and drones.

Open to comments as to what other people would like to see in making the vehicle page more useable for Riggers.

**Comment by chummer5a** [comment]
A bit of this was raised in #163 ages back; would definitely be nice to have everything in one place.
