### ISSUE TITLE
Damage Compensators don't correctly update Injury thresholds based on current damage

### ISSUE THREAD

**Issue by trekkieyk** [chummer5a/chummer5a#821]
### Chummer Version

5.179.828.0
### Expected behaviour

For a character with the Damage Compensators bioware, the threshold for Injury in the Condition Monitor sidebar should update in each track based on how many boxes are filled in the other.
### Actual behaviour

The threshold for Injury in each track remains static as the other track is updated.
### Steps to reproduce the behaviour

Give a character Damage Compensators.
Select the Condition Monitor sidebar.
Fill in any number of boxes in one of the damage tracks.
### Operating System

Windows 10
### Last known good version

None known
### Source

CRB pg. 460
### Caveat

It is possible that this was intentional, as the rules state that it is up to the player which boxes to ignore.

**Comment by chummer5a** [comment]
Tagged as fixed in skills rewrite. Will leave open until that branch is pushed to master.
