### ISSUE TITLE
Starting character skills showing as purchased with Karma rather than skill points 

### ISSUE THREAD

**Issue by Kyoto-Kid** [chummer5a/chummer5a#824]
I have been running into an issue whereby after I save a starting character file (not yet committed to Career Mode) and open it later, some skills show as being purchased with Karma instead of skill points.This doesn't affect all the skills the character has, but seems rather random as to which skills are.  All the characters this occurred to were built using the standard priority system 

Ver.178

Normally when opening a saved starting character file the skills selected should show values in the skill "Points" column 

The actual situation, when  a character file is re-opened, a number of the skills already purchased (with skill points) show a value in the "Karma" column (the character as a whole also has a Karma deficit) while the field in the "Points" column is "greyed out".  (see attached screen shot). 

None as  this appears to happen randomly and there seems no way to reproduce the error.  I've had several files corrupted like this.

OS: Win7 x64. SP1

![hannah error resize](https://cloud.githubusercontent.com/assets/13742681/14765767/894be2b6-09a5-11e6-8a9b-7c866063eb63.jpg)

**Comment by joha4270** [comment]
I would like a look at one file where this is happening. 

Otherwise, i'm laying the finishing touches on a total rewrite of skills, can you reproduce it in the build linked below?

https://github.com/chummer5a/chummer5a/releases/tag/newskills-rc-1

**Comment by chummer5a** [comment]
Closed pending reproduction on 5.180+.
