### ISSUE TITLE
Inspired (SAS) not working properly in karmagen, and sprites cost extra

### ISSUE THREAD

**Issue by distrakit** [chummer5a/chummer5a#828]
Using Chummer 5.179.844

These are both pretty small issues, but I figured I'd bring it up.

Inspired from Sail Away Sweet Sister should give a free specialization in Artisan. In karmagen it gives the +3 instead of +2 like it should, but it charges karma for the specialization. This also occurs if you select pay karma for the specialty in prioritygen, but that doesn't really matter.

Also, buying sprites as a technomancer should cost 1 karma per task, not the 2 that it charges, unless I'm missing something.

**Comment by chummer5a** [comment]
Ha! Yeah, that version of Inspired was written without the expectation that karmagen was a thing. Will have to rewrite it to work properly.

Sprites and spirits use the same karma cost, but the default value was set wrong. Check Options/Karma Costs for it, will probably be set to 2 instead of 1.

**Comment by distrakit** [comment]
Okay, thanks!
