### ISSUE TITLE
Penetrating Strike adept power does not affect 'Unarmed Attack' damage code in street gear

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#829]
##Required Fields
Taking penetrating strike adept power from street grimoire has no effect on Unarmed attack 'weapon'.

**Comment by Rinnolk** [comment]
Since the latest update the power affects the Unarmed Strike but lists the AP as a '+' value instead of a '-' 

Otherwise thanks for acting so quickly on this :)

**Comment by chummer5a** [comment]
Whups! I am an idiot. Fixed now.

**Comment by Rinnolk** [comment]
Thanks again
