### ISSUE TITLE
Martial Arts specialization not adding to total pool, and a suggestion for bonus reach from some martial arts.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#831]
### Expected behaviour

Unarmed Specialization (Martial Art) is supposed to add dice to the dicepool for unarmed weapons if you have a martial art learned.
Going on the latest Missions FAQ for this, pg 34-35
quote:
'In order to take a Martial Art as a Specialization, you must have the a Martial Arts style. Once you
have the style, you may then take the Specialization. The +2 bonus applies to attacks using the style or to those techniques you’ve learned within that style, but does not stack.
For example: Covon faces a tough opponent, a Yakuza physical adept. Covon already has
Carromeleg as a style and took it as a Specialization, so he decides to use it during this challenge. Both opponents start strictly hand to hand using Unarmed Combat. Covon gets to apply his +2 from his Carromeleg Specialization. During the fight, Covon has an opportunity to use his Counterstike technique for which he receives a +2 for his Specialization in Carromeleg. Note: he does not get +4. Unfortunately, the physical adept must have Killing Hands because his punches hurt. Covon pops out his cyberspur so he can hurt this guy right back. Covon loses the +2 from his Specialization because cyberimplant weapons are not an integral part of the Carromeleg (such as in Sangre Y Acero). Covon also failed to take a Specialization in Cyber Implants...a mistake he’s going to correct once he takes this adept down'
### Actual behaviour

The weapons (shock glove, unarmed attack, knucks, etc.) list the unspecialized dice. This is pretty minor, but it would be nice to see a fix.
### While on the topic of unarmed combat and martial arts

Reach for unarmed granted by the 'Kick Attack' MA technique is not applied to Unarmed Attack 'weapon'. 
While it's reasonably up for debate whether the bonus reach should apply universally to all attacks, or even to all weapons in the 'unarmed' category, maybe apply the reach bonus to 'Unarmed Attack', 'Knucks' and 'Plasteel Toe Boots'? Possibly a houserule/optional rule to add for this?
The rule from Run&Gun p. 139 states
'This technique provides +1 Reach to basic Unarmed Combat Actions'
So it should probably apply to most weapons from the unarmed category, and almost certainly to the Unarmed Attack 'weapon'.
### Steps to reproduce the behaviour

All tested within chargen with standard priority gen and the Jeet Kune Do MA.

**Comment by Vexsaken** [comment]
I also notice the same issue for grenade specialization Aero vs non Aero

**Comment by chummer5a** [comment]
Hrm. This could be tricksy to implement. Reach bonus is easy enough, but specialisations are keyed against the weapon name and category. As far as Chummer is concerned, Carromeleg isn't a weapon or a weapon category, so the bonus doesn't apply. Could possibly make a proxy unarmed weapon whenever a new martial art is added, but that would be a minor nightmare to maintain. 

Same problem with grenades, current logic dictates that you have to specialise by the specific name or probably 'ammunition'. Perhaps some shenanigans with a hidden name list?

**Comment by Imaduffus** [comment]
Hey there, as I understand Martial Arts can only be purchased with Karma and not as with spezialisation of the skill "unarmed combat". 
And if I understand correct, the adding of a martial art in chummer5 does not add 2 extra dice points in unarmed combat skill. 
When I select [Martial Art] as specialisation in skill tab, an extra skillpoint is being removed, that should not happen, when you purchased Martial Art with Karma.

Is there any chance to fix this issue? Or is there any bypass to display the correct dice pool for unarmed combat(Martial Art specialisation)?

**Comment by chummer5a** [comment]
That should be doable.

**Comment by Imaduffus** [comment]
That would be great, thanks for an awesome job by the way! 👍🏼

**Comment by Rinnolk** [comment]
Martial arts and martial arts specs are different things that are purchased separately. To learn a spec you need to learn the mart first. Learning a mart always costs 7 karma, and you get a free technique for the art. Speccing into a mart is done like with any other spec, and grants you either +2 dice when using a technique under the martial art or +2 dice as long as you fight in a way that is characteristic/representative of the mart (the latter is missions rules)

Just learning a mart does not add any dice or specs.
