### ISSUE TITLE
Ingram Valiant: wrong RC

### ISSUE THREAD

**Issue by bodison** [chummer5a/chummer5a#835]
### Chummer Version
Nightly-v5.179.851

### Expected behaviour
Ingram Valiant has RC of 2(3)
gas-vent 2 + shock pad on the stock
SR5 p430

### Actual behaviour
RC 7

**Comment by skarsol** [comment]
Looks like the data file is correct but it looks like recoil compensation is being doubled instead of uncompensated recoil.

**Comment by chummer5a** [comment]
Hrm. 1 point of recoil compensation from strength, 1 from the stock (Why is that on there? It's not in the stat block), 1 from the shock pad, 2 from the gas vent, then 2 base recoil compensation. Stripping off the stock and base recoil compensation should fix the problem.

**Comment by bodison** [comment]
The RC 2(3) means 2 from the gas-vent-2, one optional if you use the folding stock+shock pad. Right?

Chummer should show that and optionally the actual RC for the current character. Which would be at least 3(4), since one point RC is free for everybody.
