### ISSUE TITLE
Incorrect Calculation of Lifestyle Points/ monthly costs after removing Lifestyle Qualities

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#837]
### Chummer Version
5.179.848

### Expected behaviour
When removing a Lifestyle Quality (or asset etc.) spent Lifestyle points should be refunded and the monthly cost should be decreased, if it was increased by the quality.

### Actual behaviour
Removing a lifestyle quality does not refund spent Lifestyle points, so they are permanently lost. Same goes for increases of the onthly costs.

### Steps to reproduce the behaviour
1. Create a advanced Lifestyle
2. Select middle from the dropdown menu
3. Click the "Add Quality"-button
4. Select "Armory" from the menu
5. Select "Armory" in the Tree view
6. Click the "Delete Quality"-button

**Comment by OLStefan** [comment]
Corrected the issues in my local copy of the source code. If you could add me to the list of contributors, i could push my code for integration in the project.

**Comment by chummer5a** [comment]
As a general rule we prefer not to give contributor access until someone's
had a chance to review the quality of your code; you should be able to
create a pull request that I can approve, though.

**Comment by OLStefan** [comment]
Seemingly i can't create a pull request with my changes.

Locally, i commited my changes to a newly created branch advancedLifestyles.But i can't push the branch, so i can't create the pull request. Am i doning something incorrectly in this regard?

**Comment by joha4270** [comment]
You need to fork the repository on github, then push to that repository.

Once you have done that, you can create a pull request, from your
repository to this.
