### ISSUE TITLE
Cannot load saved NAGA character.

### ISSUE THREAD

**Issue by sstana** [chummer5a/chummer5a#840]
### Chummer Version
5.179.847.0

### Expected behaviour
Character should load from save file without problem

### Actual behaviour
When the character tries to load, Windows throws an unhandled exception error. Error message is: "Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'."

I choose Continue, and the character loads, but all calculated values are 0, all items, skills, stats, vehicles, etc, are lost.

### Steps to reproduce the behaviour
Create a Sum to Ten character with Naga as the selected race and priority C. Save character, load character. I have not tried other metasapient races or different priorities.

### Operating System
Windows 7

**Comment by chummer5a** [comment]
Can you upload the character file somewhere? I suspect it's an issue with movement, but I can't be sure until I see the file.

**Comment by sstana** [comment]
Would attaching it to a post here work? Let's give it a shot.
[Problem Character-NAGA.zip](https://github.com/chummer5a/chummer5a/files/261249/Problem.Character-NAGA.zip)

**Comment by chummer5a** [comment]
[Mage - Rigger (C1AMR-Naga).zip](https://github.com/chummer5a/chummer5a/files/261297/Mage.-.Rigger.C1AMR-Naga.zip)
Righto, found the problem. Fixed. Existing characters (IE yours) won't load properly, so here's a fixed one.

**Comment by sstana** [comment]
Great work (and I say this as a professional programmer), thank you.

 

-Sorin
