### ISSUE TITLE
Cyber-Singularity Seeker Broke

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#844]
##Required Fields

### Steps to reproduce the behaviour - Create character in chosen build type. Click add quality. Double click on Cyber-Singularity Seeker.

##Helpful Fields

### Link to affected character file
https://drive.google.com/open?id=0B-mC2hIA5p-xUHI1SlpIRHk5Mms

**Comment by OLStefan** [comment]
Already fixed in newest version. With a brand new character as well as your save file.
New version is just not available here because of problems with the automated building.

**Comment by OLStefan** [comment]
Fixed in Chummer 5.179.883
