### ISSUE TITLE
ASDF stat configuration not working

### ISSUE THREAD

**Issue by chucklemaster** [chummer5a/chummer5a#849]
### Chummer Version
Chummer Version 0.5.178

### Expected behaviour
the Attack/Sleaze/Data Proc/Firewall drop down boxes should be configurable.

### Actual behaviour
the drop down boxes reset whenever I navigate away from the device and back to it.

### Steps to reproduce the behaviour
1. purchase any cyberdeck or commlink
2. try to reconfigure the stats using the drop-down boxes.

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System
Windows 7

### Last known good version
none

**Comment by chummer5a** [comment]
Resolved in current nightly builds.
