### ISSUE TITLE
Followup to #846 (Karma-to-Nuyen limit): Loading a character with >200 Karma->Nuyen throws error

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#850]
### Chummer Version
5.179.891
### Expected behaviour
Loading characters that have been created in Karma build with "Ignore character creation rules" and have converted >200 Karma into Nuyen works.
### Actual behaviour
Doesn't work. Error:

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Wert 300 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
["The value 300 is invalid, should be between 'Minimum' and 'Maximum' etc." I tried to convert 300 Karma into Nuyen)]

Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:Zeile 212.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### Steps to reproduce the behaviour
Create character in Karma build  with "Ignore character creation rules" and have converted >200 Karma into Nuyen. Save, then try to load the character
### Use of international language content
German
### Link to affected character file
https://my.mixtape.moe/wleyfz.chum5

**Comment by OLStefan** [comment]
Fixed in latest commit, tested with maximmum Karma to Nuyen
