### ISSUE TITLE
Issue With Adepts/Perception

### ISSUE THREAD

**Issue by TempusRimeblood** [chummer5a/chummer5a#851]
Chummer Version 5.179.892

Expected behaviour
Character should have 6 ranks in Perception.

Actual behaviour
Character's Perception constantly drops to 2.

Steps to reproduce the behaviour
Create character as Physical Adept
Add quality "Mentor Spirit (Peacemaker)"
Add Adept Power "Improved Ability (Perception)" at Rank 3
Apply Perception Rank 6
Save character as Created
Observe that Perception has dropped to 2
##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Last known good version

Link to affected character file
https://drive.google.com/open?id=0Bx9RUpYz2ZxKZWtTdUVTSzBrTnM

**Comment by OLStefan** [comment]
fixed with the skills rewrite
