### ISSUE TITLE
Knowledge skill specializations

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#856]
### Chummer Version    
NewSkills release candidate v2

### Expected behaviour
Knowledge skill specializations should cost 1 knowledge skill point in creation mode

### Actual behaviour
Knowledge skill specializations are "free". Points are not reduced.

### Steps to reproduce the behaviour
Make a character (priority). Specialize in a knowledge skill.

### Operating System
Windows 10

**Comment by joha4270** [comment]
Fixed in 1a061de
