### ISSUE TITLE
Karma not spending and nuyen not gained.

### ISSUE THREAD

**Issue by scarletpooky** [chummer5a/chummer5a#861]
Two issues:
1) In Chargen for brand new characters: when spending karma to raise an attribute it doesn't actually spend any karma.

2) In Chargen for brand new characters: spending karma to gain nuyen spends the karma but doesn't add nuyen.

Chummer Version 5.180.1

**Comment by OLStefan** [comment]
Can't replicate your issues. I tested in both, Karma and Priority build and Karma and all values are adjusted just fine.

So please describe exactly how to replicate these issues.

**Comment by scarletpooky** [comment]
I found the cause.
There's an issue with overwritting old copies of Chummer, even though I told it to replace files. Not had a problem before but this time it caused problems.
A complete delete and fresh install worked.
