### ISSUE TITLE
Knowledge skill points

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#862]
Old issue back again?

### Chummer Version
5.180.0

### Expected behaviour
Knowledge skill specializations should cost a knowledge skill point in creation mode.
### Actual behaviour
Knowledge skill specializations are "free" in creation mode.
### Steps to reproduce the behaviour
Make a character. Buy a knowledge skill specialization.

### Operating System
Windows 10

### Last known good version
Can't remember.

**Comment by joha4270** [comment]
Whoops.
On the bright side, it does actually cost something, it just dosen't cause
an update to the remaining karma value. Try increasing and decreasing the
amount of karma you put in the skill rating as a workaround.

**Comment by House69** [comment]
In Character generation all knowlege skills are defualting to logic it appears. Regardless of whether it is an interest skill, street, language should be INT not auto default to LOG).
In Career Mode, when adding knowledge skills, The field is not allowing any skills to be chosen(Dropdown box or manual entry), as well as the left (+) button should be for additional points into the basic skill. Specialization On the right. (currently swapped)
