### ISSUE TITLE
MAG skills cannot be accessed by characters with a MAG rating.

### ISSUE THREAD

**Issue by Thelinil** [chummer5a/chummer5a#864]
### Chummer Version
5.180.3
### Behaviour
My chummer has a Magic rating of 6, but all skills under the "Attribute: MAG" category are invisible, as if they were mundane. This happens in Karmagen, Sum-to-10, and Priority builds. This also happens with Resonance and RES skills. This is probably because of the new skill system.

**Comment by joha4270** [comment]
I'm unable to reproduce this issue.

**Comment by chummer5a** [comment]
How did the character gain a magic rating? Are you just giving them magic via the Improvements system, or are you adding the appropriate quality for adept/technomancer/etc.?

**Comment by Curris** [comment]
I was able to recreate this.

Specifically, it happens to characters with the Mystic Adept quality.

Problem --> in the qualities.xml file, the quality for Mystic Adept is supposed to have a tag
<bonus>
        <unlockskills>Magician</unlockskills>
</bonus>

It doesn't have this. It is missing the unlockskills tag, and Magician is mispelled.

Once this is edited, Mystic Adepts can see the magical skills.

**Comment by Ookreson** [comment]
Someone already posted this, check out the latest nightly fix.

You have to remake a character ground up, changing priorities will only make the magic rating stack over and over again. Mine is stuck at 16 when I chose counterspelling and spellcasting as my specialties.
