### ISSUE TITLE
cannot edit "pages" value with translator.exe

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#866]
### Chummer Version
latest GitHub-files
### Expected behaviour
click on the "pages" field of - say - a spell, edit the page number, close translator.exe and it stays this way.
### Actual behaviour
click on the "pages" field, enter the page number, close translator.exe and the page-value is still empty.
### Steps to reproduce the behaviour
this is what I did:
- open translator.exe
- select "Edit Language File" -> Deutsch (DE)
- select "spells.xml" -> spells
- scroll down to (for example) "Detect Magic, Extended / Magie Entdecken, Erweitert"
- enter a value in the "page" field
(editing translations works perfectly though)

### Operating System
Windows 10

### Use of international language content
- de.xml, de_data.xml

### Last known good version
unknown

### Link to affected character file
-

**Comment by chummer5a** [comment]
Hrm, I can't replicate this. Is it not editing the de_data file itself, or is it not loading the altered page in Chummer?
