### ISSUE TITLE
Translated values for skills are not always used during character creation

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#867]
### Chummer Version
5.180.0

### Expected behaviour
Translated skills should be displayed with their translated values. For example the skill "Aeronautics Mechanic" should, if Chummer5 is set to german, always be displayed with the german term "Luftfahrtmechanik" and never as "Aeronautics Mechanic".

### Actual behaviour
During character creation the skills are shown in english even though Chummer5 is set to german. 

### Steps to reproduce the behaviour
- set Chummer5a´s language to any other language than english
- create a new character using the priority-system
- set magic to anything between A-D
- below "Based on your talent selection, you may choose [...]" the skills are not translated.

See attached image at the bottom of the post.

### Operating System
Windows 10

### Use of international language content
- 

### Last known good version
-

### Link to affected character file
Just create a new character, see Steps to reproduce.

![chummer5a](https://cloud.githubusercontent.com/assets/4673925/15636362/feef123c-25fb-11e6-8028-9516adbe6126.png)
screenshot

**Comment by chummer5a** [comment]
Righto, we'll have that fixed in the next patch. Have you come across any other instances where the English name is used instead of the localised displayname?

**Comment by HaukeW** [comment]
Not yet, I´ll keep an eye open.
