### ISSUE TITLE
Wrong pagenumber

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#868]
Not the most important but...
### Chummer Version
5.180.0
### Expected behaviour
Lifestyle pagenumber reference could be SR5 374 or maybe some page from run faster
### Actual behaviour
Source: SR5 369 which must be wrong for lifestyle

**Comment by OLStefan** [comment]
In my PDF file, the lifestyles from the core rulebook are on page 369

**Comment by drakir75** [comment]
Ok. But not in the printed one that I checked. Not a big problem anyway.

**Comment by OLStefan** [comment]
I think i got the one with some errata worked in, that would explain the page discrepancy

**Comment by drakir75** [comment]
I checked my pdf now. Lifestyles on same as yours, page 369. Checked a bit and the pdf is missing the fluff story "All the angles" (page 328-331 in my printed version). Mystery/problem solved. A bit irritating though.

**Comment by chummer5a** [comment]
You could use an override xml file to change the page numbers, I guess?
