### ISSUE TITLE
Mysad not showing magic skills.

### ISSUE THREAD

**Issue by jeoc42** [chummer5a/chummer5a#869]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version

5.180.0

### Expected behaviour

Mysads may see and purchase magic linked skills

### Actual behaviour

Mysads may not see and purchase magic linked skills

### Steps to reproduce the behaviour

Create a new mysad in 5.180.0

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System

Win 7

**Comment by jeoc42** [comment]
Testing with hotfix and all 3 ways of creating a character reveal the same result.

**Comment by Ookreson** [comment]
Unfortunately, I'm still getting this.

**Comment by joha4270** [comment]
On the nightly or on the hotfix?

**Comment by Ookreson** [comment]
Hotfix.
Installed, restarted chummer, made a mysad, opened mysad character that I had previously.

Both never showed up.

**Comment by joha4270** [comment]
Seeing that the hotfix was released before this issue was fixed, you might have a little more success if you try one of the nightlies

**Comment by Ookreson** [comment]
Aight, thanks.
