### ISSUE TITLE
Chummer will not launch

### ISSUE THREAD

**Issue by upwardthinking** [chummer5a/chummer5a#870]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version 
5.180.0

### Expected behaviour 
Open Application

### Actual behaviour 
Chummer opens blank updater window, green bar fills and turns to restart button, hit restart and chummer closes and will not reopen

### Steps to reproduce the behaviour 
Open latest version of Chummer.exe

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System 
Windows 10

**Comment by upwardthinking** [comment]
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/288749/chummerlog.txt)

**Comment by joha4270** [comment]
So, your log file claims 5.179.913.0

I would manually install the latest release and see if the issue persists

**Comment by upwardthinking** [comment]
I have downloaded the new file from scratch more times than I care to count and it hasn't helped, here's the log file from my attempt after doing that just now.
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/289682/chummerlog.txt)

**Comment by joha4270** [comment]
So i'm a bit unsure but i have 2 theories about what is happening. Either something is keeping a lock on the file preventing it from starting or it is a weird interaction between 32 and 64 bit. 

1. Try and kill any processes named "Chummer5.exe" or "CrashHandler.exe" that might remain alive. A full reboot should also accomplish this. Then try starting it again.

2. Attached is a few builds compiled with different options. One of those might fare differently
[anycpu.zip](https://github.com/chummer5a/chummer5a/files/289705/anycpu.zip)
[x64.zip](https://github.com/chummer5a/chummer5a/files/289704/x64.zip)

**Comment by upwardthinking** [comment]
Yeah I restarted and tried both builds and it's still happening.

**Comment by joha4270** [comment]
I'm blank for now. 

I'm going to come back and look at this, but all hypotheses i had have been shot down, so i have no idea what is happening.

**Comment by upwardthinking** [comment]
Thanks, just wanted to bring it to your attention, something I just noticed btw is that you can close the update window and chummer will launch as normal so there is a workaround. Just wanted to mention what it is trying to do.

**Comment by chummer5a** [comment]
Hrm. Check the Temp directory (copy %TEMP% into your explorer address bar),
is there a Chummer5.180.zip file?

**Comment by upwardthinking** [comment]
There's 5.180.0 and 5.180.5

**Comment by chummer5a** [comment]
Hrm. Might be working probably in current builds, we did some work to clean up how the update methods work.
