### ISSUE TITLE
Attached character crashes chummer 5.180 with or without hotfix

### ISSUE THREAD

**Issue by Malkleth** [chummer5a/chummer5a#871]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.180 and 5.180.5
### Expected behaviour
Character loads and, presumably converts to 5.180
### Actual behaviour
Chummer5 crashes with a blank crash report
### Steps to reproduce the behaviour
Simply load the file? 

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System
windows 10

### Last known good version
Works fine on 5.178
### Link to affected character file
[Morgan Tologar.zip](https://github.com/chummer5a/chummer5a/files/288918/Morgan.Tologar.zip)

**Comment by Malkleth** [comment]
Oddly, installing chummer, then hotfix, then running auto-updater solved this issue. Go figure?

**Comment by joha4270** [comment]
I have been looking a little at it the last 10 minutes, and can reproduce
it with 180, but not 180.5 so i'm 70% sure you didn't overwrite it with
hotfix.

On the other hand, i have no idea why it crashed...
