### ISSUE TITLE
In debt XV

### ISSUE THREAD

**Issue by joha4270** [chummer5a/chummer5a#872]
### Chummer Version
5.180.5

### Expected behaviour
"In debt XV" should be named  "Student debt"

### Actual behaviour
"In debt XV" is named "In debt XV"

### Steps to reproduce the behaviour
Create a new character.
Add "In Debt XV"

### Operating System
Windows 10

### Use of international language content
None

### Last known good version
None

**Comment by Git-me-outta-here** [comment]
:+1: rofl

**Comment by bodison** [comment]
:+1: rofl

**Comment by Skarablood** [comment]
Hah, you wish it was only 75k.

**Comment by OLStefan** [comment]
Glad to life in Germany, studying right now in university for only 340 €/semester
