### ISSUE TITLE
Translator.exe replaces the entire file it modifies

### ISSUE THREAD

**Issue by HaukeW** [chummer5a/chummer5a#874]
### Chummer Version
most recent Git-Pull

### Expected behaviour
Lines modified with translator.exe should be the only lines modified by translator.exe

### Actual behaviour
I modified some values in de.xml and de_data.xml with translator.exe. Git now shows all ~20.000 lines in de_data.xml as modified.

### Steps to reproduce the behaviour
- edit a language file with translator.exe
- push it to a Git-Repository

Here is the file in my Github-Repository: https://github.com/HaukeW/chummer5a/commit/3ef30a97396910fa26147c295d2a25a4a7b50732#diff-94366b3e0040e95fd887ed5e662c2152

### Operating System
Windows 10

### Last known good version
-

**Comment by OLStefan** [comment]
It may be that translator.exe formats the file differently, which git counts as changing all lines. The cause of that could be that the lang file right now is formatted with two spaces, where many tools format with a tab instead.

**Comment by HaukeW** [comment]
The strange thing is that de.xml is formatted with spaces and de_data.xml with tabs.

e.g. de.xml:

```
    <string>
      <key>String_DescPassive</key>
      <text>Passiv</text>
    </string>
```

e.g. de_data.xml:

```
			<power>
				<id>21768675-ea17-48f4-abdc-301c3441bf8c</id>
				<name>Quake</name>
				<page>219</page>
				<translate>Erdbeben</translate>
			</power>
```

Should this be changed so that it is consistant?

**Comment by chummer5a** [comment]
The translator essentially rebuilds the XML file from scratch whenever it saves the file, there's not a lot to be done about it there. We probably do need to standardise tab/spacing, but git isn't supposed to care about whitespace changes.
