### ISSUE TITLE
Chummer freezes when removing a specilization

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#876]
### Chummer Version
5.180.0

### Expected behaviour

When removing a speciliazation the program remains usable.

### Actual behaviour

When removing all characters from the specilization combobox, chummer is unusable until you enter some characters again.

### Steps to reproduce the behaviour
1. Create a new / load a character
2. Increase a skill
3. Put in some specilization
4. Remove the specilization

**Comment by Skarablood** [comment]
Something that is probably related to this bug:

Create a character with Karma build, raise one of his skills to, let's say 4. Chummer correctly subtracts 2, 4, 6 and 8 Karma from your pool. Then, add a specialization. Chummer will not subtract the 7 Karma here nor show the specialized dice pool in brackets. But, if you lower the skill back to 3, Chummer refunds 8 Karma back to your karma pool and suddenly the specialized dicepool in brackets shows up! And then, if you lower the skill back to 2, Chummer subtracts 1 Karma from your karma pool (probably refunding the 6 Karma for the level 3 skill, but subtracting the 7 Karma for the specialization)!

**Comment by Atsuga** [comment]
Same thing for me, when I add a specialisation, I cannot remove it. The cursor stays in the specialisation field. The only way to get out of that is to add a specialisation again to that skill.

**Comment by chummer5a** [comment]
Going to take a look at this tonight, see what can be done about it.
