### ISSUE TITLE
Laser Weapons

### ISSUE THREAD

**Issue by MedievalBunny** [chummer5a/chummer5a#882]
### Chummer Version
5.180

### Expected behaviour
Adding laser weapons to the gear list works.

### Actual behaviour
Adding a laser weapon to a character creates a pop-up error dialog box. The pop-up can be dismissed by clicking OK. This box reapers whenever the laser weapon is selected, or accessories are added to it. The pop-up box displays the following: 

"Unable to create crash report.
Make sure your system is connected to the internet"

The system is connected to the internet. 

Additionally, in Career Mode, attempting to add ammo to the laser weapon will cause an inescapable dialog box to appear. The box asks to select a weapon category for this ammunition, but the drop-down selection box is empty, it will not accept text entry, and OK cannot be clicked without a selection. 

### Steps to reproduce the behaviour
Create a new character. Go to the Weapons tab under Street Gear. Click on Add Weapon. Select any of the three available laser weapons. Click OK. 

Save the character in Career Mode. Navigate to the Street Gear and Weapons tab. Select the laser weapon (a Unable to create crash report pop-up will once again appear). Click on the "buy additional ammo for this weapon" button. Select "Ammo: Peak-Discharge Energy Units" and click on OK. Another Unable to create crash report pop-up will appear, click OK. You are now trapped in a "Select a Weapon Category for This Ammunition" box. 

### Operating System
Windows 10

**Comment by OLStefan** [comment]
Fixed with [6e1ea1d](https://github.com/chummer5a/chummer5a/commit/6e1ea1deeefb8ed62371f0669f40075bd57dd3f4)
