### ISSUE TITLE
Chummer does not tell the user, when the character was made using a different "ruleset"

### ISSUE THREAD

**Issue by nw2372** [chummer5a/chummer5a#884]
### Chummer Version
5.180.12

### Expected behaviour
Tell the user if the previous "ruleset" and the "new" ruleset differ (on character load)

### Actual behaviour
No information given.

### Steps to reproduce the behaviour
Create new Character
Add book-specfic stuff
change "ruleset"
reload character

### Use of international language content
english

### Last known good version
unknown

**Comment by chummer5a** [comment]
Books enabled in options?

**Comment by nw2372** [comment]
No, thanks.
The Character got made on an installation, that had them enabled and even had Gear from other books.
Recommondation: save the used books in the character file as well and tell the user to choose the "ruleset" on character load.

No matter the solution, chummer needs a feature, that tells the user of this "issue".
