### ISSUE TITLE
Unable to create AI using Priority-based character creation methods

### ISSUE THREAD

**Issue by abishaij1** [chummer5a/chummer5a#891]
### Chummer Version

Latest Stable - Latest Nightly
### Expected behavior

Being able to make a metavarient character
### Actual behavior

Crashes
### Steps to reproduce the behavior

Sum to Ten > Street Level > (Elf > Harvester) (B. Metatype > Elf >Banshee) (Troll > Ghoul) AI doens't show up on Sum to Ten at all.
Karma > AI > Xeno
### Operating System

Windows 7 - 64
### Use of international language content

Google Japanese IME
### Last known good version

???
### Link to affected character file

Can't make one.

I sent in crash dumps, wanted to make double sure though since this is a pretty big bug since you can't even get out the gate.

**Comment by OLStefan** [comment]
Crashes fixed in [a66ecc7](https://github.com/chummer5a/chummer5a/commit/a66ecc70aa5c2187c71156752846f8d9fd66c283).

AI still not selectable in Priority/ Sum to Ten
