### ISSUE TITLE
Mage created in stable release will not load in latest nightly

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#893]
### Chummer Version
Nightly v5.180.17

### Expected behaviour
Character created in stable release 0.5.178.0 can be opened in Nightly build.

### Actual behaviour
Opening a mage character created in stable version fails to load properly in nightly release.
Message window "Failed to create crash report. Make sure your system is connected to the internet."
(I am connected to the internet).
The character is partially loaded; no skills, no gear, no karma/nuyen history, no calendar. (Contacts are loaded.)

### Steps to reproduce the behaviour
Open a mage character created in stable version in latest nightly release.

### Operating System
Windows 8.1

### Use of international language content
No

### Last known good version
stable release 0.5.178.0

**Comment by chummer5a** [comment]
Can you upload the character file somewhere?

**Comment by Lochabar** [comment]
I used the GitHub function "Attach files by dragging & dropping, , or pasting from the clipboard." that showed the file was uploaded. Must be a problem there.

https://www.dropbox.com/s/wzpxyahh5y7ubd5/Beltane.chum5?dl=0
also the chummer log
https://www.dropbox.com/s/wgudiabak3xm3uk/chummerlog.txt?dl=0

**Comment by OLStefan** [comment]
Could you please try it in the latest nightly build? I have no problems opening that character on my computer.

**Comment by Lochabar** [comment]
Downloaded v5.180.23 and character still fails to load properly.

**Comment by OLStefan** [comment]
Did you unpack that version in an empty folder or just overrode you old version?

**Comment by Lochabar** [comment]
Into an empty folder.

**Comment by OLStefan** [comment]
Hmm, that's strange. I'll try to debug via error log then

**Comment by chummer5a** [comment]
Issue seems to have been caused by not having Street Grimoire loaded as a book. I've fixed the crash in the latest commit, but if you open Options and re-tick the boxes you should be good to go.
