### ISSUE TITLE
Cannot Print Infected Characters

### ISSUE THREAD

**Issue by nhoner** [chummer5a/chummer5a#894]
### Chummer Version
5.180.0
### Expected behaviour
Able to print Infected characters.
### Actual behaviour
Chummer crashes, throwing the error message "Object reference not set to an instance of an object."
### Steps to reproduce the behaviour
Created and attempted to print a vampire, a banshee, a harvester, a mutaqua, and a ghoul with the same results each time.

### Operating System
Windows 8
### Use of international language content
No.
### Last known good version
5.178
### Link to affected character file
https://drive.google.com/open?id=0B61nd1tDpX71czY5NTB1OGlmNFU

**Comment by nhoner** [comment]
Actually, I found what was causing the problem and how to fix it. When the Infected qualities added the natural weapons, they tag them as using the "Unarmed" skill, when it should say "Unarmed Combat". A quick find/replace in the qualities.xml data file that swapped "<useskill>Unarmed</useskill>" for "<useskill>Unarmed Combat</useskill>" fixed the issue.

**Comment by OLStefan** [comment]
Changed Unarmed to Unarmed Combat in Metatypes and Qualities.
