### ISSUE TITLE
Have to add Metamagic Art before being able to add Metamagic technique

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#895]
### Chummer Version
Stable v5.178.0

### Expected behaviour
When a mage initiates he should be able to add a Metamagic technique. As this is from the core rulebook there should not be additional criteria.

### Actual behaviour
Trying to add Flexible Signature is stopped with the message:

"You do not meet the requirements for this Metamagic. You must meet the all of the following criteria: One of: Flexible Signature" [meaning Flexible Signature ART]

If you add the Metamagic ART first then you can add the Metamagic technique.
This seems to be the wrong way round as in Street Grimoire p149, for the Flexible Signature ART, it states "When the magician initiates in to this art, she first learns the Flexible Signature metamagic."

### Steps to reproduce the behaviour
Initiate a mage. Try to add a metamagic technique.

### Use of international language content
No

### Last known good version
None. It occurs in the latest stable version and in the latest nightly.

**Comment by OLStefan** [comment]
As I understand is: You initiate into the Flexible Signature art (selecting it as your art in chummer) and then the first metamagic you select is the Flexible Signature Metamgic. And so not having the metamagic as a prerequisite of the art.

**Comment by Lochabar** [comment]
But the Metamagic Arts are more recent, having been introduced in Stolen Souls. Metamagic is from the core rulebook. And as I quoted:

Street Grimoire p149, for the Flexible Signature ART, it states "When the magician initiates in to this art, she first learns the Flexible Signature metamagic."

So the Art should have the dependency on metamagic, not the other way round.

**Comment by chummer5a** [comment]
No, what it's saying there is the first metamagic you have to learn after initiating into that art is Flexible Signature. You couldn't initiate with that art and then pick something else up.

**Comment by Lochabar** [comment]
Core rulebook p325:
"Every time you gain an initiative grade (including the first), you learn a metamagic."

I do not see anything in Street Grimoire that says Arts are required first. And the SRM Chicago Faq Ver 0.4 page 40, describes Initiation sequence as: 

For all other schools, once you initiate and take the required metamagic (see below), you are now in that school and may take additional rituals or enchantings via normal karma expenditure (Street Grimoire,​ pg. 139, Magic Arts Sidebar and ​ SR5​ , pg. 299, Learning Spells). In order to take additional metamagics within that school, you must initiate and meet any prerequisites for the metamagic.
­ Masking: Masking metamagic
­ Flexible Signature: Flexible Signature metamagic

**Comment by chummer5a** [comment]
If you're not using the Art-based initiation system included in Street
Grimoire, you should enable the House Rule to ignore Art requirements. As
is, those rules are stating that by taking that Art, you're required to
take the metamagic as your first metamagic. I'm not super pleased with the
implementation personally, but I haven't put much thought into a different
way of doing it yet.
