### ISSUE TITLE
Agility value in skill list of print output replaced with Body value while having set the language to German

### ISSUE THREAD

**Issue by McDie** [chummer5a/chummer5a#897]
### Chummer Version
5.180.0 as well as Nightly-v5.180.25

### Expected behaviour
Having set the language to German, you click on print, the printing output should feature that the attribute values in the action skill list next to the skill rating should be all correct like the print output with English language.

Example:

Character with Body 4 and Agility 5

English
SKILL NAME ..... POOL ... RTG .... ATT
Gymnastics ....... 7 .......... 2 .......... 5 (AGI)

German
SKILL NAME ..... POOL ... RTG .... ATT
Akrobatik ...........7 ........... 2 ......... 5 (GES)

### Actual behaviour
Having set the language to German, the Agility attribute value in the action skill list next to the skill rating of skills using Agility is consequently replaced by the Body value. However, the total Pool has still the correct value.

Example:

Character with Body 4 and Agility 5

SKILL NAME ..... POOL ... RTG .... ATT
Akrobatik .......... 7 ........... 2 ......... 4 (GES)

### Steps to reproduce the behaviour
Set the language to German in the program options. Restart. Create any character with distinct and unique attribute values in Body and Agility. Click on print. 

### Use of international language content
Using German language

### Last known good version
5.178

**Comment by chummer5a** [comment]
I imagine this is just the character sheets not knowing how to handle the ability to change the linked attribute, so it defaults to the first thing it can. I'll have a look into it.

**Comment by McDie** [comment]
Thanks!
