### ISSUE TITLE
Cannot remove specializations once they are selected in active skills

### ISSUE THREAD

**Issue by DrinkWholeMilk** [chummer5a/chummer5a#898]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.180
### Expected behaviour
Remove specialization
### Actual behaviour
No option to remove 
### Steps to reproduce the behaviour
Select a specialization and you will not be able to remove it
##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

**Comment by Skarablood** [comment]
Known issue (https://github.com/chummer5a/chummer5a/issues/876), has been fixed in the Nightly release.
