### ISSUE TITLE
Aged quality provides augmented extra. 

### ISSUE THREAD

**Issue by Kreyopresny** [chummer5a/chummer5a#901]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.180.0

### Expected behaviour
Aged gives a -1 to real and augmented limits

### Actual behaviour
Aged gives -1 to real limits and +1 to the augmented stat. 

### Steps to reproduce the behaviour
Add "Aged (Rating 1)" negative quality to a character and check the (Augmented) stat value, may only occur alongside custom or augmented cyberware? 

### Link to affected character file
https://drive.google.com/open?id=1ETwoW_Zc45KTCV51ZJXvI3eq_AbZBabaN5tNVpuFpzk

**Comment by OLStefan** [comment]
Can't replicate the issue and the provided link is for SR5 Notes, not a Chummer character file.

**Comment by Kreyopresny** [comment]
Shoot, sorry about the link mistake. This one should be right: https://drive.google.com/open?id=0B2Mfe_aZccS3MWNIRWJBVWlETDA
It’s in the augmented values on the Common tab. Tinkering around a bit more though, looks like I was wrong, it’s not the “Aged” quality, but the “Customized Agility” and “Customized Strength” enhancements on the 2 cyberarms not adding up right.

**Comment by OLStefan** [comment]
The Cyberlimb enhancements are adding up right: You have 2+2+2 (Torso + Legs) + 6+6 (Arms) = 18 / 5 = 3.6 => 3 Strength becuase this average is rounded down.

The only thing strange is that the Aged Quality is in the tooltip depite giving no benefit to the attributes.
