### ISSUE TITLE
Knowledge Skill Specializations do not subtract points.

### ISSUE THREAD

**Issue by JohnBlack687** [chummer5a/chummer5a#902]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.179.0

### Expected behaviour
When adding a specialization to a knowledge skill, a knowledge skill point should be subtracted.

### Actual behaviour
When adding a specialization to a knowledge skill, no knowledge skill point is subtracted.

### Steps to reproduce the behaviour
Choose a knowledge skill and select a specialization

### Link to affected character file
https://www.dropbox.com/s/nl8bhmjfvamlbxc/checkknowledgeskills.chum5?dl=0

**Comment by chummer5a** [comment]
Please update to 5.180, 5.179 is deprecated.
https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.180.33/Chummer.Nightly.zip
