### ISSUE TITLE
[5.180] Load a charakter's skills section crashs (career mode)

### ISSUE THREAD

**Issue by drseltsam83** [chummer5a/chummer5a#903]
### Chummer Version
5.180

### Expected behaviour
Skill section is loaded without crash.

### Actual behaviour
The charakter loads perfectly with Nightly-v5.179-800 and some versions before. If I open the charakter with 5.180 it fails as soon I switch to skill section. The charakter is already in career mode.

### Steps to reproduce the behaviour
Load attached charakter and switch to skill section.

### Link to affected character file
Exception and char file attached:
[char.zip](https://github.com/chummer5a/chummer5a/files/305638/char.zip)
[exception.txt](https://github.com/chummer5a/chummer5a/files/305634/exception.txt)

**Comment by joha4270** [comment]
This loads for me now in the latest nightly, please reopen this issue if the issue persists

**Comment by drseltsam83** [comment]
It still crashes for me with nightly v5.181.16 and v5.181.17.
Unfortunately I can't send information with crash agent either.
![image](https://cloud.githubusercontent.com/assets/19826108/16171604/4c706e76-3573-11e6-820e-64ec324675c7.png)
