### ISSUE TITLE
5.180 cant remove a spec of a skill in karma build mode 

### ISSUE THREAD

**Issue by Lexanius** [chummer5a/chummer5a#909]
### Chummer Version
5.180

### Expected behaviour
spec will removed

### Actual behaviour
When a spec field is empty cant focus a other field, only if it is filled

### Steps to reproduce the behaviour
choose skill
enter spec
remove spec by deleting the text

**Comment by OLStefan** [comment]
already fixec in latest build

**Comment by Lexanius** [comment]
but i have loaded the hotfix download today and try it out
It is not fixed.

**Comment by OLStefan** [comment]
Can't replicate the error on the latest nightly. Did you use a character save or did you try making a new character? If you used a save file, please upload it.
