### ISSUE TITLE
5.180 (german mode) choose german pdfs as source instead of english one

### ISSUE THREAD

**Issue by Lexanius** [chummer5a/chummer5a#910]
### Chummer Version
5.180

### Expected behaviour
Take the book from the selected language and fallback to the english one. 

### Actual behaviour
Open actually the english pdf when click on source (e.g. SR5 76)

**Comment by chummer5a** [comment]
Unless I'm misunderstanding what you're after, this should already be working. Items in de_data.xml should have a page reference that overrides the base page in the appropriate xml file. 

Can you provide an example of how it doesn't work?
