### ISSUE TITLE
Issue warning if character changes cannot be opened in earlier version

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#911]
### Chummer Version
Enhancement request

### Expected behaviour
You have a character created in a previous version of Chummer5a.

XML Schema changes that have been made between that previous version and the current one will prevent the character from being opened in the previous version.

Could a warning be issued when the character is opened? Along the lines of "Changes made to this character will prevent it from being opened in the Chummer5 version in which it was created".
Or when being saved "Saving this character will prevent it from being opened in the Chummer5 version in which it was created. Save changes or save as a different file?".

### Actual behaviour
You do not find out that a character cannot be opened in an earlier version until you try to open it in that earlier version.

**Comment by chummer5a** [comment]
Hrm. Generally speaking, all chummer updates are considered to be
destructive. Frankly I can't imagine a circumstance where you'd want to
stay on an earlier version, unless we've broken some specific bit of
functionality somehow. Shouldn't be too tricky to include a handler to warn
users that a file might have bugs or be unable to load, I suppose.
