### ISSUE TITLE
Two Bioware issues

### ISSUE THREAD

**Issue by AriMatt2** [chummer5a/chummer5a#913]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.180.43

### Expected behaviour
Supathyroid Gland and Muscle Augmentation should not stack. Prototype Transhuman should not persist if deleted.

### Actual behaviour
Supathyroid Gland and Muscle Augmentation stack. Bioware taken after deletion of Prototype Transhuman acts as if quality is still taken.

### Steps to reproduce the behaviour
Have goth Supathyroid Gland and Muscle Augmentation. At any point, take and then remove Prototype Transhuman. See common tab for first error, lower status bar for second.

### Link to affected character file
None made, error noticed during though experiment. Will make file on request.

**Comment by OLStefan** [comment]
Muscle Toner also shouldn't stack with Supathyroid Gland
