### ISSUE TITLE
Click a skill tab. chummer is end. 

### ISSUE THREAD

**Issue by wakiko** [chummer5a/chummer5a#914]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
Nightly-v5.180.44

### Expected behaviour
it clicks the tab of skill, the error message referred to as being unable to refer to it will come out of and end an object. 

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)
[針使い.zip](https://github.com/chummer5a/chummer5a/files/309481/default.zip)

I am a Japanese and am not familiar with English. I am sorry when it is hard to read. 

os windows7(64bit)
netflamework4.6

**Comment by chummer5a** [comment]
I think I know what was going on here, but it should be resolved in the latest nightly builds. Could you please test again?

**Comment by joha4270** [comment]
We have received reports that this issue is fixed in nighties. Unless or until we get contrary reports i'm going to close this issue.
