### ISSUE TITLE
Crash after short time

### ISSUE THREAD

**Issue by Berenion** [chummer5a/chummer5a#915]
Windows 7 64-bit
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/309696/chummerlog.txt) added logfile after last attempt at character creation

### Chummer Version
1.8.0.

### Expected behaviour
Open options or select metatype

### Actual behaviour
(Enter text here)Options crashes after a few seconds. CHaracter creation in standard priority crashes when selecting any race.

### Steps to reproduce the behaviour
(Enter text here)start program and click on tools, options and wait a few seconds./ Start new character, select standard, click on dwarf

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
Seems to be a crash related to the update check, which is odd. Could you please try disabling Automatic Updates and see if that helps?

**Comment by Berenion** [comment]
Tried disabling auto updates. Still crashes when viewing options (clicking on any sourcebook) or durring character creation. The crash occures with time (unless opening chummer and not doing anything) or with clicking on things.


Chummer log file is empty.

**Comment by SeanPGorman** [comment]
This used to happen on my old PC. I updated to most recent .net framework and issue never re-occurred. </suggestion>

**Comment by Berenion** [comment]
I have .NET 4.6.1

**Comment by chummer5a** [comment]
Is this still happening in the current versions?
