### ISSUE TITLE
Knowledge skills attribute

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#916]
Not entirely new. House69 mentions this in comments on my issue 862. (where my part seems fixed) 

### Chummer Version
5.180.41

### Expected behaviour
Street and Interest knowledge skills should be based on INTuition. They are only partially.

### Actual behaviour
All knowledge skills are default to LOGic after opening a saved character. And even if you change, Chummer changes it back when you save again. A bit irritating when saving to career. Then you can't change attributes on skills. 

### Steps to reproduce the behaviour
Buy a INT-based knowledge skill on a character in create mode. Save. Open.

Thank you for all the work on a mostly fantastic character generator.

**Comment by McDie** [comment]
Maybe the solution for #920 is also nearby, while fixing this.

**Comment by McDie** [comment]
Maybe the solution might be found by looking at Chummer/Backend/Skills/KnowledgeSkill.cs line 70 (or line 68ff. respectively):

public KnowledgeSkill(Character character) : base(character, (string)null)
		{
			AttributeObject = character.GetAttribute("LOG");
			AttributeObject.PropertyChanged += OnLinkedAttributeChanged;
			_type = "";
			SuggestedSpecializations = new List<ListItem>();
}

**Comment by joha4270** [comment]
So just for details, no it wasn't on line 70. What you found was a default that prevents everything blowing up if you tried to do anything with the skill

Nice to know you did some looking around tho.
