### ISSUE TITLE
New Magician at B crashes during gui loading

### ISSUE THREAD

**Issue by joha4270** [chummer5a/chummer5a#917]
### Chummer Version
b58c14edd48

### Expected behaviour
Can create magician

### Actual behaviour
Chummer crashes when trying to create a new magician

### Steps to reproduce the behaviour
Create new character. Select priority or sum10. 
Select magic b
Select Magician
Fill out rest
Press ok
Chummer crashes

I'm tired, will forget about this tomorrow.

**Comment by SeanPGorman** [comment]
Not just in priority system. Any mage, adept or aspected mage in life module system causes same

**Comment by OLStefan** [comment]
Orignial Issue is already resolved, looking into the Life Moduk issue

**Comment by OLStefan** [comment]
Gonna close this issue, because the problem concerning Life Moduel charcters is already reported as [#925](https://github.com/chummer5a/chummer5a/issues/925)
