### ISSUE TITLE
Crash on Character Load

### ISSUE THREAD

**Issue by celondon** [chummer5a/chummer5a#921]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behaviour
Chummer does not crash on loading an existing character

### Actual behaviour
Chummer crashes on loading an existing character

### Steps to reproduce the behaviour
1. Start Chummer
2. Click the Open File button
3. Select the linked character
4. Observe crash

### Link to affected character file
https://www.dropbox.com/s/ocrduz6knoxypc4/RedlineFinal.chum5?dl=0

**Comment by chummer5a** [comment]
Looks like it's not handling the exotic weapons skill from your Improved Ability power. Will need to do some shenanigans to fix it.

**Comment by celondon** [comment]
The initial bug is fixed, however the character now crashes chummer when the user selects the ADEPT POWERS tab. This is based on nightly build 5.181.29

**Comment by chummer5a** [comment]
Something borked with how the power controls are assigned, I'm looking into
it at the moment. Same bug as #954.
