### ISSUE TITLE
Chummer crashes when attempting Magic B Technomancer

### ISSUE THREAD

**Issue by JohnBlack687** [chummer5a/chummer5a#923]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behaviour
Create a technomancer with priorities Metatype D (Human), Attributes A, Magic B (Technomancer), Skills C, Resources E.

### Actual behaviour
Chummer crashes upon hitting OK.

### Steps to reproduce the behaviour
1. Create new character.
2. Plug in mentioned priorities.
3. Press okay.

### Link to affected character file
No character file could be created.

**Comment by OLStefan** [comment]
Already fixed in latest nightlies. ([#922](https://github.com/chummer5a/chummer5a/issues/922)
