### ISSUE TITLE
Chummer crashes as I select skills tab

### ISSUE THREAD

**Issue by DoStuffZ** [chummer5a/chummer5a#924]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
Version 5.181.3.0

### Expected behaviour
Selecting skills tab, list skills in system. Some with a point in them, as the ones the player bought.

### Actual behaviour
Selecting skills tab, get a notification - cannot create report and then a blank grey page.

### Steps to reproduce the behaviour
Open up supplied file, attempt to show skills.
I previously attempted to add some free post character creation knowledge skills. I (the GM) give my players certain knowledge skills relative to campaign. As I pressed add know skill, it showed a blank line with no input text boxes.

### Link to affected character file
[LeonDanWesternDone.zip](https://github.com/chummer5a/chummer5a/files/314156/LeonDanWesternDone.zip)

**Comment by joha4270** [comment]
Please verify if this issue still persists in 5.181.12 and reopen this issue if so.
