### ISSUE TITLE
Opening characters causes crash

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#925]
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/315405/chummerlog.txt)

[Jefftest - .txt](https://github.com/chummer5a/chummer5a/files/315146/Jefftest.-.txt)
[John - .txt](https://github.com/chummer5a/chummer5a/files/315144/John.-.txt)
[Nev-yn - .txt](https://github.com/chummer5a/chummer5a/files/315145/Nev-yn.-.txt)

Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
Upgraded to 180 then took nightly update 181

### Expected behaviour
Character open fine

### Actual behaviour
All characters, both pre-existing and new ones created since the update cause a crash. Crash reports were sent.

### Steps to reproduce the behaviour
Open any character

### Link to affected character file
None (it is all files)

**Comment by SeanPGorman** [comment]
Actually - only magically aware characters cause the crash. All my characters are made using life module system.

**Comment by OLStefan** [comment]
Non magic characters will load for you? When I try all Life Module characters crash and I am honestly surprised that Life Module charaters did load in previous versions

**Comment by SeanPGorman** [comment]
Hey Stefan. I might have made an assumption about previous characters I have made. I almost exclusively make magically aware characters and always using the life module system since it was released.

I think that build 178 worked. One difference is (assumption due to my memory failure) that the life modules selected did not used to appear in the qualities text box but they now do during creation.

I upgraded to 181 and still have the issue.

Thank you for your work.

**Comment by OLStefan** [comment]
Already found the issue, shoudl work in the latest nightly.

**Comment by SeanPGorman** [comment]
@OLStefan I downloaded https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.181.6 and I still get crashes on anything (new or existing) made with Life Modules.

Process: downloaded zip from above page. Copy and pasted everything in Zip to correct folder: c\chummer5

**Comment by SeanPGorman** [comment]
Fix agreed. Working as expected
