### ISSUE TITLE
Crash on New Technomancer

### ISSUE THREAD

**Issue by TitaniumTaz** [chummer5a/chummer5a#928]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behaviour
Character screen

### Actual behaviour
Chummer5a Crash Reporter - Value of '1' is not valid for 'Value'. Value should be between 'Minimum' and 'Maximum'

> "visible-crash-id"-"7581a91b-4465-4f6f-81fb-0371ffd37f60"
> "visible-build-type"-"RELEASE"
> "commandline"-""D:\Apps\Chummer5.181.0\Chummer5.exe" "
> "visible-version"-"5.181.0"
> "machine-id"-"00326-10000-00000-AA492"
> "machine-name"-"OSIRIS"
> "current-dir"-"D:\Apps\Chummer5.181.0"
> "application-dir"-"D:\Apps\Chummer5.181.0\Chummer5.exe"
> "visible-error-friendly"-"Value of '1' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
> Parameter name: Value"

### Steps to reproduce the behaviour
Priority build. Choose Technomancer in magician dropdown.
Have tried with Priorities A, B, and C
Have tried with Races Human, Elf, Dwarf, Orc

### Link to affected character file
No file generated.

**Comment by OLStefan** [comment]
Already fixed in latest nightlies

**Comment by TitaniumTaz** [comment]
Sorry, didn't see that. Grabbing .6

Thanks!
