### ISSUE TITLE
No Knowlege Points When Creating a Character

### ISSUE THREAD

**Issue by Shmythe** [chummer5a/chummer5a#929]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behavior
Gain Knowledge Points on character creation.

### Actual behavior
There doesn't seem to be a way to get more Knowledge Points.  Then instead of being 0 if you add a Specialization they go negative

### Steps to reproduce the behavior
You can add Intuition and Logic but the number of Knowledge points never goes up from 0.  Then go to Skills->Knowledge add Mafia add a Point then select Safe House then Professional and then you will get a result of -1 out 0 Knowledge points used.  We are using Karma Builds with a Karma of 820 and an Availability of 15.

### Link to affected character file
(Enter text here)
[The-Jerk-2.zip](https://github.com/chummer5a/chummer5a/files/317265/The-Jerk-2.zip)

**Comment by OLStefan** [comment]
Do you have activated the House Rule to get Knowledge Points in Karma Creation?

**Comment by Shmythe** [comment]
No.  We do not, but since it pulls score down from 0 when you add a specialization it keeps us from marking a character as created.
