### ISSUE TITLE
Character viewer/printing enhancement request

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#931]
I would like to suggest an enhancement to the way the character viewer and print sheets are supported.

Currently you have to modify an existing sheet for customizations. Alternativly, add new XSL files to pick up cloned/modified sheets.

There is some support for French and German sheets; they are supplied in a directory and, presumably, have to replace the existing, English, sheet.

I would like to suggest using three folders, searched one after another.
1) A testing folder; changes to sheets would be placed in this folder and picked up first by the character sheet viewer.
2) The appropriate language folder, corresponding to the language being used by Chummer5a; any alternative language sheets would be picked up from this folder. There would also be one for US, that would be used for any customized sheets.
3) The base folder; all the supplied sheets would be in this folder.

When the character viewer is used, search for the selected XSL sheet in the three folders, using the first one found. Any includes would then be pulled in from the folder in which they are present.

This method would avoid having to modify the supplied sheets and allow proper support of the various languages.

**Comment by chummer5a** [comment]
So what are you after, exactly? The code for displaying the sheets is largely just a filter. If you have the language enabled, it shows the appropriate language files in addition to the other sheets. I can MAKE it do shenanigans with overwriting files based on the folder structure, but I don't really see the point.

**Comment by Lochabar** [comment]
I would like it to select the first version of a sheet it finds in the list of files. So I can try changes to a sheet without having to copy/rename the base version.

I want to avoid having to save the base sheets in order to make use of a custom one. At the next upgrade I have to copy those I have modified and created to the new release. Not an arduous task, but it is frustrating.

Also, when making changes, I have to keep making a backup of a sheet before making the changes. If, after testing the modifications, I decide I don't want them, I have to delete the sheet and rename the backup.

**Comment by chummer5a** [comment]
To what end, though?The override code can't/won't handle replacing specific nodes of the XSL, so you'd still have to make a copy of the character sheet. At that point, why not just give it a new name and set it as your default sheet?

**Comment by Lochabar** [comment]
For example, I have copied "Shadowrun 5 Base" xslt to a new member. I then have to copy "Shadowrun 5" xls, "Shadowrun 5 (Grouped Skills by Name)" xls, and "Shadowrun 5 (Grouped Skills by Rating)" xls and modify the copies to include the new xslt member.

If I want an alternate to, say, the "ConditionMonitor" xsl file, I would need to copy/modify 4 xls files.

If I could put the "Shadowrun 5 Base" xslt member in a directory ahead of the supplied sheets, I would not need to copy/change the 3 "Shadowrun 5" xsl members, they would still be used (unchanged) from the base directory.

**Comment by chummer5a** [comment]
There's some existing code that might be doing what you want; try making a folder called omae in the sheets folder, put your stuff in there and see if that does what you want.

**Comment by Lochabar** [comment]
Created the folder, restarted Chummer, but no effect.

**Comment by Lochabar** [comment]
Finally realized that "omae" was not activated in Chummer. When did this become an option?
I'm certain I've see this in the Tools menu before, without ever activating it!

Anywho. Having activated omae, I created the omae folder and copied some of the xsl/xslt members to it. Clicked Print and the custom sheets appeared as "omae: Shadowrun 5" but when I tried printing, I got an abend.

Copied over the remaining members. This time I was able to use the "omae:" sheets.

Using omae does allow for an alternative set of print sheets. Unfortunately it is little better than copying/renaming the supplied base members, because you have to copy all the sheets that include, say, "Shadowrun 5 base" plus the other include "ConditionMonitor", into the omae folder. Ideally it would be necessary to only have "Shadowrun 5 base" in the omae folder and the supplied members would use it from omae in preference to the supplied base.

**Comment by chummer5a** [comment]
It's a new development, since Omae's character's mostly don't load we hid
it away. As for the omae thing, I was trying to determine whether that
would suit your needs more than anything else. It'll need some shenanigans
to get what you want to work without breaking the localisation filters.

**Comment by chummer5a** [comment]
Replacing the file to load is simple enough from my perspective, but I'm not sure if there's a way to dynamically replace the referenced include at runtime.

**Comment by Lochabar** [comment]
Closing this issue because of the changes I made to the character sheets that separated the print controls from the character sheet members, allowing the various languages to use the single common control.
