### ISSUE TITLE
Problems with German and an existing character

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#935]
### Chummer Version
Nightly 5.181.10

### Expected behaviour
Change language to German, restart Chummer, and be able to open an existing character (that was created in English).

### Actual behaviour
Chummer fails to load and produces the message "Failed to create crash report. Make sure your system is connected to the internet."

(I am connected to the internet).

### Steps to reproduce the behaviour
I was wanting to see if the character viewer would produce a German character sheet (as a follow up to issue 931).

I changed the language to German, restarted Chummer and tried to open a character created in English. Chummer gets upset.

Should Chummer be able to cope with a character created in one language and opened with Chummer set to a different language?

Note: after changing the language (no character loaded)
1) The language "Verify" and "Verify Data File" buttons are still in English. As is the "Life Modules available" check box.
2) When I clicked the verify button I got a long list of "Missing String" errors in the "Language File Contents" window.
3) Clicking Verify Data File button Chummer throws the "Failed to create crash report. Make sure your system is connected to the internet." window.

### Link to affected character file
https://www.dropbox.com/s/d3v0hhz8gw9ggd8/B.chum5?dl=0

**Comment by chummer5a** [comment]
Can't replicate it with that character in the current build. Chummer absolutely is intended to be language-agnostic, as everything is stored with English strings that are rendered to the client language by the application.

**Comment by Lochabar** [comment]
Here are screen shots.
1) After changing the language to German and restarting Chummer:
 https://www.dropbox.com/s/qzbaflm9trf2wdy/Chummer5a.1.png?dl=0

2) After clicking Verify
https://www.dropbox.com/s/ypj62878zc3l6o3/Chummer5a.2.png?dl=0

3) After clicking Verify data file
https://www.dropbox.com/s/365td2he86o6ku2/Chummer5a.3.png?dl=0

4) Trying to open the character
https://www.dropbox.com/s/e0ublmef2wbh54i/Chummer5a.4.png?dl=0

**Comment by chummer5a** [comment]
Can you please try this again in the latest builds and report back with the crash handler ID, if any? Old nightlies weren't including the crash handler.

**Comment by Lochabar** [comment]
Changed language to German. Restarted Chummer.
   https://www.dropbox.com/s/j2608bf44mgd1ld/try2-options.jpeg?dl=0
Notice that there is English text present

Clicked "Verify".
   https://www.dropbox.com/s/4n8qmhi1pwlrrrp/try2-verify.jpeg?dl=0
Notice that the window title is in English

Clicked "Verify Data File"
   https://www.dropbox.com/s/jzi5rthgx2ai6iz/try2-verify%20data.jpeg?dl=0

Unfortunately Chummer failed to create dump

**Comment by Lochabar** [comment]
Tried again using 5.181.52 but still failed.
ID created: afbd43de-720c-4fc9-93ed-d7e005fd9cc3, but the dump collector still failed.

https://www.dropbox.com/s/lujvxvous27f38c/try2-dump%20failure.jpeg?dl=0

**Comment by Lochabar** [comment]
Finally realized that "omae" was not activated in Chummer. When did this become an option?
I'm certain I've see this in the Tools menu before, without ever activating it!

Anywho. Having activated omae, I created the omae folder and copied some of the xsl/xslt members to it. Clicked Print and the custom sheets appeared as "omae: Shadowrun 5" but when I tried printing, I got an abend.

Copied over the remaining members. This time I was able to use the "omae:" sheets.

Using omae does allow for an alternative set of print sheets. Unfortunately it is little better than copying/renaming the supplied base members, because you have to copy all the sheets that include, say, "Shadowrun 5 base" plus the other include "ConditionMonitor", into the omae folder. Ideally it would be necessary to only have "Shadowrun 5 base" in the omae folder  and the supplied members would use it from omae in preference to the supplied base.

**Comment by Lochabar** [comment]
I have added the new English labels to the de.xml file. (Not translated.) And can now verify the file.

https://www.dropbox.com/s/jkd6tncx0g4kldl/de.xml?dl=0

However "Verify Data file" still abends. Sending of dump to developer still fails. Here is a zip of the error.
https://www.dropbox.com/s/gqh12mjd5l0u0qg/chummer_crash_131136826451706088.zip?dl=0
