### ISSUE TITLE
Colt Cobra TZ-120 has gas vent 2

### ISSUE THREAD

**Issue by Sceptically** [chummer5a/chummer5a#936]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.17

### Expected behaviour
It should not be possible to add a gas vent system (or, for that matter, any other barrel mounted accessory) to the Colt Cobra TZ-120, as it has one already built in.

### Actual behaviour
It's possible to add a barrel mount accessory to the Colt Cobra TZ-120. This includes installing a gas vent system, which then stacks with the built in system.

### Steps to reproduce the behaviour
Add weapon - submachine gun - Colt Cobra TZ-120
Add accessory - gas vent system

### Link to affected character file
(Enter text here)

**Comment by Sceptically** [comment]
That was quick, but I think it also needs the following, or you can still add another gas vent.
@@ -6128,7 +6128,6 @@
                        <cost>660</cost>
                        <allowaccessory>true</allowaccessory>
                        <accessorymounts>
-                               <mount>Barrel</mount>
                                <mount>Top</mount>
                        </accessorymounts>
                        <accessories>

**Comment by Skarablood** [comment]
Just small fixes in the weapons.xml, the Ingram Smartgun X had the same issue, because it was released before the advanced weapon modification rules came out. If you find other cases like this, tell me.

**Comment by Sceptically** [comment]
Will do. I've noticed that it's still possible to add a second gas vent system on these two guns (and probably others) which already have built-in gas vent systems. Should the barrel mount slot be removed for any guns which already come with something in that accessory slot?

**Comment by Skarablood** [comment]
Good question. Common sense dictates that those things should not be possible, but I don't know how the rules as written are.

**Comment by Sceptically** [comment]
I think it's arguable when it's an integral feature, but when the description says "barrel mounted" or "top mounted" to describe an accessory that comes standard, I'd argue that means that mount is used for that accessory. Which means the Ingram Smartgun is arguably all good, but the Colt Cobra already has both slots in use.
