### ISSUE TITLE
Cannot specify weapon type of a weapon focus

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#942]
### Chummer Version
5.181.14

### Expected behaviour
Adding a weapon focus allows the nature of the weapon focus (blades, clubs, etc.).

### Actual behaviour
Defaults to Unarmed Combat with no way to change it.

### Steps to reproduce the behaviour
Create a new magician.
Add a weapon focus.

### Link to affected character file
https://www.dropbox.com/s/gw69n2xo3ax142z/weapon%20focus.chum5?dl=0

https://www.dropbox.com/s/4deibdnxpk77e51/1%29%20add%20focus.jpeg?dl=0
https://www.dropbox.com/s/lu69ft2qfpbani7/2%29%20enter%20value.jpeg?dl=0
https://www.dropbox.com/s/gaptvmq2p60slsv/3%29%20created%20gear.jpeg?dl=0

**Comment by chummer5a** [comment]
Weapon foci are coded to prompt you to select an existing weapon; if there's only one choice, it automatically grabs that weapon. If you add another weapon, it'll give you a prompt like this:
![image](https://cloud.githubusercontent.com/assets/11448441/16176352/0c448e44-3650-11e6-9f65-1918dc330682.png)
