### ISSUE TITLE
Roto-drone & Friends In High Places

### ISSUE THREAD

**Issue by captroberts** [chummer5a/chummer5a#943]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version 
5.181.22

### Expected behaviour
Weapons mod for MCT-Nissan Roto-drone should be at 7 per the description in SR5 p466.
When the Friends In High Places quality is chosen, the contacts ratings should be pulled from the the new amount of points given. 

### Actual behaviour
The Roto-drone only has a 4 in Weapons mods. Friends In High Places pulls points from Karma points.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
Friends in high places explicitly state the contacts you add needs to have a connection of 8 or higher. When i consider that rule, friends in high places works for me, even if the UI for it is a little clunky.

**Comment by captroberts** [comment]
What about the Roto Drone?

**Comment by captroberts** [comment]
It is pulling the points from the wrong pool. The rules state that you get an additional Charisma x 4 in Karma for the contacts. It shows the additional points but it dose not draw from it.

**Comment by joha4270** [comment]
It does on mine. Please realize it is stated [Normal left]/[High left] of [normal total]/[high total] and that you need a connection of 8 or higher for it to draw from the friends in high places pool

**Comment by joha4270** [comment]
And about the Roto Drone, i haven't looked at it so i don't have any answers. This is why it says "New Issue" (Singular) not "New Issues" (Plural)

**Comment by captroberts** [comment]
Sorry, my bad on the Friends issue. Now I understand the whole thing. I apologize if I sounded like a jerk about the Roto-drone. This is a way better and easier system to use then the Lone Wolf version.

**Comment by joha4270** [comment]
its not you who should apologize, I wasn't exactly well mannered in my response.

It just all the minor details that adds up, I'm sorry you was the one i ended up venting at.

**Comment by captroberts** [comment]
It  is always the little things that add up quick. Please, enjoy the weekend and have a Happy 4th of July.
