### ISSUE TITLE
Armor Encumbrance

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#944]
### Chummer Version
5.181.19

### Expected behaviour
Armor encumbrance should lower Agility and Reaction even if they are augmented.

### Actual behaviour
If Agility and/or Reaction is augmented, armor encumbrance does not show on the _augmented_ attribute.
(My character had 28 armor and still 10 Agility) :-)

### Steps to reproduce the behaviour
Make character with low Strength and raise Agi and Rea at least some. (I did only priority). 
Augment Agility and/or Reaction in some way (does not matter if it is bioware or cyberware, or how much). Buy lots of armor that "stacks".
(Sleeping tiger+argentum coat+ballistic mask+swat helmet+Securetech PPP vitals kit+legs kit+arms kit)

### Thank you ###
To everyone who helps with making/augmenting this great character generator.

**Comment by chummer5a** [comment]
Right, found the problem. It's linked to precedence, which we use to group 'unique' improvements together. The problem is that the armorencumbrance improvement isn't linked to any of these groups, so if you take something like Move-By-Wire, it suppresses the Encumbrance for the linked attribute. Shouldn't be too hard to fix, just need to finagle some of the improvement manager's code.

**Comment by drakir75** [comment]
Adding a rules question. Is Chummer right in making "custom fit" armor that "stacks" i.e. Argentum coat not count towards encumbrance? I have not found the rules on this.
Put anothre way; If you have Strength 1, +4 from helmets/shields/whatever will encumber you but chummer is not encumbering someone with +4 armor from for example Argentum Coat. Is this right or wrong?

**Comment by joha4270** [comment]
Page 59 of Run & Gun has the rule Custom Fit (stack) that with a little good will supports this behavior. 

I'm sure i have seen it spelled out more clearly somewhere else, but i couldn't find it after 10 min search and it is late here so i gave up.
