### ISSUE TITLE
Changing priority selection removes MAG based skills

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#946]
### Chummer Version
5.181.25

### Expected behaviour
Using "Change Priority Selection" to change one of the magic based skills should make the change.

### Actual behaviour
All MAG skills are removed

### Steps to reproduce the behaviour
Create a new magician.
Select two magic skills.
Select "Change Priority Selection".
Change one of the magic skills.
Then the skills "shuffle" and magic based skills are gone.

### Link to affected character file
Initial creation - selected Arcana and Spellcasting: 
https://www.dropbox.com/s/c3ravqcyquqixbv/change%20selection%201.jpeg?dl=0

Initial set of skills: 
https://www.dropbox.com/s/w24qxs70vsvqold/change%20selection%202.jpeg?dl=0

Change priority - replace Arcana with Assensing
https://www.dropbox.com/s/6x0gc12ym0zuqu6/change%20selection%203.jpeg?dl=0

Magical skills gone:
https://www.dropbox.com/s/j0i0w69zw076zs4/change%20selection%204.jpeg?dl=0

**Comment by Sceptically** [comment]
I can confirm that this is a problem with v5.181.34 (which I didn't see previously due to not actually seeing anything in the skills tab in earlier builds I tried).

**Comment by chummer5a** [comment]
I know what's happening, its going to be a shit to fix though. Might have something tomorrow.

**Comment by Sceptically** [comment]
Just as a useful tip, reapplying improvements on the Special menu brings back the missing skills.
