### ISSUE TITLE
Omae character

### ISSUE THREAD

**Issue by auerbalazs** [chummer5a/chummer5a#949]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.26.0

### Expected behaviour
The chummer can open downloaded characters (via omae)

### Actual behaviour
The program crashes on open

### Steps to reproduce the behaviour
Download a character from omae (eg: Adam Jensen from enemy category)

### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
Seeing that Omae is outside our control and "Adam Jensen" is made with 4th edition of chummer, we don't have a way of fixing this issue.

After a quick discussion among me and @chummer5a we are going to put Omae behind a checkbox and show a warning that it might be unstable. The alternative is removing it completely.
