### ISSUE TITLE
File menu duplication of options

### ISSUE THREAD

**Issue by Sceptically** [chummer5a/chummer5a#953]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.
### Chummer Version

5.181.29
### Expected behaviour

The Save...Close entries in the File menu go away when all characters have been closed.
### Actual behaviour

The Save through Close entries in the File menu remain after all characters have been closed. When another character is created or opened and no other characters are already open, a new Save through Close section is created in the File menu. This can be repeated, resulting in as many duplicate Save through Close options in the File menu as you want.
### Steps to reproduce the behaviour

Open a character, then close the character. Open a character, then look at the file menu.
### Link to affected character file

(Enter text here)

**Comment by chummer5a** [comment]
Unable to replicate it in the current build. Not too sure what could be going wrong here; how're you closing the character?

**Comment by Sceptically** [comment]
I'm closing it by the File menu Close option.

I guess it's entirely possible this is related to running Chummer with Mono in Linux.

**Comment by chummer5a** [comment]
Could be, mono's fairly janky at times. Can you give me a screenshot of the
error? I'll have a poke around and see what I can do.

**Comment by Sceptically** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/20014797/16362764/2baf9d1c-3c0b-11e6-8f03-2ed0cc2dcf49.png)

**Comment by chummer5a** [comment]
Is this still happening?

**Comment by Sceptically** [comment]
I just checked with v5.190.0 (sometime between there and v5.191.0 chummer stopped loading in mono, I'll try to track down the exact nightly shortly), and it doesn't seem to be happening anymore.
