### ISSUE TITLE
Clicking adept power tab crashes chummer. Also some weird stuff with adept powers.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#954]
### Chummer Version
5.181.29

### Expected behaviour
Not crashing, heh. All previously bought powers to be there. The power point costs and remaining power points adding up.

### Actual behaviour
Clicking the adept powers tab crashes chummer. Some previously added powers are gone. There are more leftover power points shown than there should be.

### Steps to reproduce the behaviour
I have no idea, but I'm adding a link to the file. I think Improved sense power might be the culprit. Or maybe just those .25 pp powers in general. They keep popping up in the char file after I remove them, save, close the character and open the file again. In case something is not right with the charfile, the selected powers were: Nimble fingers, Flexibility 1, Improved Reflexes 2, Improved sense (2 times), rapid draw, Attribute boost AGI 2, Combat sense 1.

### Link to affected character file
https://drive.google.com/file/d/0B71WLpuGA0X4YTZpZC11UzJkdlU/view?usp=sharing

Having checked another file, made in an older version of chummer, the issue is also present there.
Here's the other file
 https://drive.google.com/file/d/0B71WLpuGA0X4ZEVoWm5TYnViR0k/view?usp=sharing

**Comment by Rinnolk** [comment]
Some further testing... adding powers sometimes causes chummer to crash. So far half the listed powers may crash chummer when you add them. Sometimes it crashes sometimes it doesn't.

**Comment by Rinnolk** [comment]
Also this... http://imgur.com/Y1iGEFb

**Comment by eeboaz** [comment]
I also see the crash when adding Improved Reflexes 2. Additionally, Improved Reflexes 3 does not subtract from power points for me. (I filed a crash report via the app before finding this.)

**Comment by joha4270** [comment]
For the second thing, it is _probably_ a Qi focus but most certainly an adept power that was removed without taking the improvement with it. 
Nobody have had time to find the root issue

**Comment by celondon** [comment]
Verified fixed in 5.181.34
