### ISSUE TITLE
Closing does not ask if character should be saved

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#956]
It appears that the fix for issue #899 has been back-leveled.

### Chummer Version
Nightly 5.181.30

### Expected behaviour
Having changed a character, closing the character file causes chummer ask if the changes should be saved.

### Actual behaviour
Character closure does not ask if changes should be saved, and they are not saved.

### Steps to reproduce the behaviour
Change a character, close the character file. The changes are not saved.

Repeat, except manually save the character before closing. This time, on reopen, the character changes are present.

**Comment by chummer5a** [comment]
Hrm, i can't replicate it. Odd. Code looks right, can't see anything that should be blocking it.

**Comment by Lochabar** [comment]
Just tried Nightly 5.181.31 and the program works correctly. Closing issue.
