### ISSUE TITLE
Question about Chummer override files

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#957]
How do the override files work?

Copied the weapons data file to a custom file, deleted all but the "ceramic/plasteel knife" definition and just changed the name to "ceramic knife". Starting chummer, the name is unchanged.

Does chummer match on the <id> tag?
or does it perhaps match on the <name> tag?

https://www.dropbox.com/s/32vc5441zq65meo/override_weapons.xml?dl=0

**Comment by joha4270** [comment]
So, in general, nobody wants to touch the override system with a 11 foot plasteel pole but looking at the code it seems to do it based on name.

Old but still the only documentation for data files can be found [here](http://www.chummergen.com/chummer/wiki/Custom%20Data%20Files.ashx)

**Comment by chummer5a** [comment]
Yeah, the override code comes from a loooong while back, before we started
using GUIDs as identifiers. Before any of us started working on it,
actually. No particular reason we can't make it do that, but I'm worried
about breaking existing overrides. There might be a shenanigansy way to
make it work with checking if the ID field exists, I guess.
