### ISSUE TITLE
Question: Adding new life modules

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#960]
I have Rigger 5.0 and I note that there are modules in it that are missing from the xml.

If I add them in a separate copy of the file, who has the source to check my work (4 eyes technique works better)?

**Comment by chummer5a** [comment]
If you raise it as a pull request or upload it here as a custom_lifemodules.xml file, I'll review before approving it.

**Comment by SeanPGorman** [comment]
This is a file with the additions:
Line 125 shows that the below selection is a member of an existing collection

Please review and then I will add to the existing file

[custom_lifemodules.txt](https://github.com/chummer5a/chummer5a/files/333656/custom_lifemodules.txt)

**Comment by SeanPGorman** [comment]
I have now created the xml file. Please get it here: https://www.dropbox.com/s/ew8qd4hqihzj1vm/custom_lifemodules.xml?dl=0

**Comment by SeanPGorman** [comment]
@chummer5a How can I help get this implemented? I don't know your protocol for adding GUIDs.

**Comment by chummer5a** [comment]
Nothing much needed to actually get it approved, I've just been busy with some other work and haven't had a chance to implement it. Realistically you just need to generate GUIDs for everything, which you can get from somewhere like https://www.guidgenerator.com.

**Comment by SeanPGorman** [comment]
@chummer5a oK - GUIDs created file in the original link updated.
