### ISSUE TITLE
Unexpected Advanced Lifestyle Behavior

### ISSUE THREAD

**Issue by SpaceTurtles** [chummer5a/chummer5a#963]
### Chummer Version
5.181.34

### Expected behaviour
Any Entertainments (Assets, Services, or Outings) added after utilizing all "free" LP slots should increase costs only by their advertised price for compatible lifestyles.  (HT, 140 - "I Ran Out of Points, But Want More Stuff")

### Actual behaviour
Any Entertainments (Assets, Services, or Outings) added after utilizing all "free" LP slots increase monthly costs by huge sums -- typically ¥5,000 (ex; adding "Swimming Pool" after using all LP increases costs by ¥5,000 rather than ¥100).

### Steps to reproduce the behaviour
Tested with Priority and Karma build.

Create a character, add an advanced lifestyle.  Choose "High", and add compatible entertainments of your choosing (for my purposes, I added "Obscure/Difficult to Find" quality for a total of 7 LP, then used those LP to get Armory [2], Gym [2], Shooting Range [2], and Drone Maids/Manservants [1] for free).  The monthly cost at this point should be ¥11,000.  When I add "Swimming Pool", the monthly cost becomes ¥16,000 instead of the expected ¥11,110 (110% of ¥10,100).

Tested also with "Medium" lifestyle - Bat Cave, Garage (Car, Body 5 or more), then added a Grid Subscription.  Cost/month spike from ¥5,000 to ¥10,000 from the subscription (nobody's service is worth that price, chummer).

It appears that if you have no LP remaining, adding any other Entertainment increases your monthly costs by a flat ¥5,000 Nuyen (I added 'Drone Maids', normally costing ¥7,000, after filling out LP elsewhere, and it only increased costs by ¥5,000).

### Link to affected character file
N/A

**Comment by OLStefan** [comment]
It seems i misread the rules about assets after 0 points from Hard Targets.

**Comment by SpaceTurtles** [comment]
Fair enough!  One other thing I forgot to mention in the above is that Grid subscriptions should automatically fill out depending on your lifestyle (the quality is for purchasing a grid subscription above your means).  This is under "Grid Subscription (Updated)" on HT 140, where it says that they're automatically available without spending points or cash depending on your Lifestyle;

Street: Public Grid
Squatter/Bolt Hole: Public Grid
Low/Traveler: Public Grid
Middle/Commercial: Public and Local Grid
High/Hospitalized: Public, Local, and a Global Grid
Luxury: Public, Local, and a Global Grid

Not sure how possible it is, but figured I'd point it out!

**Comment by OLStefan** [comment]
For the moment i just removed the extra 5,000 Nuyen cost per negative Lifestyle Point, because that was just a mistake on my side implementing that. 

Implementing it the way Hard Targets explains it would cost a lot more time.
