### ISSUE TITLE
Preservation &LOAD of a character is not made. 

### ISSUE THREAD

**Issue by wakiko** [chummer5a/chummer5a#965]
![error2](https://cloud.githubusercontent.com/assets/19861325/16362660/cba39178-3bef-11e6-80c1-cf6959564f9e.jpg)
![error3](https://cloud.githubusercontent.com/assets/19861325/16362661/d0ed29b4-3bef-11e6-8d6f-be5b7be23dc9.jpg)

Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
Nightly-v5.181.37

### Expected behaviour
I create a character. I operate preservation. Then, I crash. 
The above-mentioned screen comes out. 

### Actual behaviour
(Enter text here)
![erroer](https://cloud.githubusercontent.com/assets/19861325/16362657/c012ecb4-3bef-11e6-8208-d6d5c7f82dc4.jpg)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by joha4270** [comment]
So, your description is a little bit confusing.

Just to confirm, by preservation you mean save?

**Comment by chummer5a** [comment]
Does it crash in 5.181.36?

**Comment by joha4270** [comment]
Also, if you actually send the crash report we would have a better chance at diagnosing this issue. 
I would prefer if i got the followup id, but as that one is absent, proximate upload time or a nightly version is enough to narrow the search down to manageable

**Comment by McDie** [comment]
I tested it with nightly 5.181.35, no problem with saving a newly created character there. So the bug might have happened in 36 (which isn't in the release list anymore) or in 37. It still crashes while trying to save a newly created character in 39. I encountered it after creating a new character with priorities and immediately saving after that initial creation.

**Comment by wakiko** [comment]
it is clash in 5.181.37
i put chummerlog.sorry want to check
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/333670/chummerlog.txt)

**Comment by wakiko** [comment]
I used 5.181.41 but A situation does not change. 
Crash ID= 374ab08f-acad-4ce1-b514-fd037692c2b9

**Comment by joha4270** [comment]
I don't see any crashes with from 5.181.41 or 5.181.37 and no crash with an
id of 374ab08f-acad-4ce1-b514-fd037692c2b9

Are you sure you press send crash report and it doesn't say "error" in the
lower left corner?


On the other hand, i'm able to reproduce this on my system now, so the
report won't have a huge impact.

2016-06-27 15:46 GMT+02:00 wakiko <notifications@github.com>:

**Comment by wakiko** [comment]
I pushed the lower left button. 
id=06b80892-83af-493d-a7a8-fee86b13d6be
[attributes.txt](https://github.com/chummer5a/chummer5a/files/335019/attributes.txt)


[exception.txt](https://github.com/chummer5a/chummer5a/files/335021/exception.txt)

**Comment by wakiko** [comment]
Is this helpful to the solution in question?

**Comment by McDie** [comment]
In Version 55 I do not encounter any difficulties anymore. Saving works fine again.
