### ISSUE TITLE
Oni metatype not reducing starting karma

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#967]
### Chummer Version
5.181.35

### Expected behaviour
Oni metavariant is supposed to reduce the starting karma by 4. 

### Actual behaviour
Instead, Oni metavariant starts with 29 karma.

### Steps to reproduce the behaviour
Make an oni, observe the starting karma ammount.

**Comment by joha4270** [comment]
Oni metavariant states +4 karma, unlike every other metavariant that just shows a plain number.

Unless you can provide errata or a citation from an official catalyst game labs source we are going to keep assuming the +4 means you _get_ 4 karma for taking that metavariant.

**Comment by Rinnolk** [comment]
Oh, my bad, prio C actually lists a + value, duh. Every other 'additional karma cost' in the tables has no '+' ><
