### ISSUE TITLE
Active Hardwires do nothing on the skills screen

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#968]
### Chummer Version
5.181.39

### Expected behaviour
Active Hardwires are supposed to use their rating for the skill rating.

### Actual behaviour
The relevant skill is not affected at all in the skills tab.

### Steps to reproduce the behaviour
Add a r1-6 active hardwires for a skill with no (or small or whatever) rating, observe skill rating staying unchanged.

**Comment by joha4270** [comment]
Probably fixed this and closing in 5 minutes unless additional bugs show. Was because hardwires existed as 2 different entries and the skills checked for the first while the gear created the second.
