### ISSUE TITLE
Char file crashing, says there is an error for collecting crash information.

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#969]
### Chummer Version
5.181.42

Chummer crashes immediately when loading the attached file. 
Not sure what's wrong with this one really, apart from the file being tweaked in like 3 or so versions of chummer.

### Link to affected character file
[Made.zip](https://github.com/chummer5a/chummer5a/files/335318/Made.zip)

**Comment by chummer5a** [comment]
Looks like the character wasn't saved properly, it cuts off at the start of
the adept powers section. Not much we can do about it I'm afraid.

**Comment by Rinnolk** [comment]
It's cool, remade the guy. Just kinda hoped it could help work out any problems/bugs and prevent them from happening in the future.

**Comment by joha4270** [comment]
Sadly the bug happened before and if it is what i think, fixed again.

Before i unlock time travel in the skill tree, we cannot do more here
