### ISSUE TITLE
Feature request: add "Check/Uncheck All Sourcebooks" to the options.

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#971]
Especially when one often downloads the new nightlies, checking all the sourcebooks manually is a royal pain in the ass. A "Use All Sourcebooks" checkbox would make it a lot more comfortable.

**Comment by chummer5a** [comment]
Sure, that shouldn't be a problem. You could always copy the settings file
over though, I can't remember the last time we made a destructive change to
the options file.

**Comment by Skarablood** [comment]
Cool, thanks!

**Comment by chummer5a** [comment]
This has some issues related to the activation of the SR5 sourcebook; current code will force the options menu to close if it's activated. Not hard to fix per se, but annoying to work around.
