### ISSUE TITLE
Chargen

### ISSUE THREAD

**Issue by Shadow1128** [chummer5a/chummer5a#972]
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behaviour
In Chargen, I choose Priority > Standard then ok.  D Priority in Magic; Choose Aspected Magician > Choose Sorcery in magical skill group dropdown.

### Actual behavior
In Chargen, I choose Priority > Standard then ok.  D Priority in Magic; Choose Aspected Magician
Cannot Choose Sorcery, the drop down menu to choose a magical skill group is empty, and I cannot get passed this screen.  Hitting ok give me the error that I haven't chosen a magical skill group.

### Steps to reproduce the behavior
In Chargen, I pick Priority > Standard then ok.  D Priority in Magic; Choose Aspected Magician
Cannot Choose Sorcery, the drop down menu to choose a magical skill group is empty, and I cannot get past this screen.

### Link to affected character file
(Enter text here)

**Comment by OLStefan** [comment]
already fixed

**Comment by Shadow1128** [comment]
I'm confused. It's still doing it for me? How us it fixed



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by joha4270** [comment]
While i'm not involved in this issue, i believe it is fixed on the nightly
build and just hasn't made it to release yet.

**Comment by Shadow1128** [comment]
Oh ok thank you, that makes sense.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------
