### ISSUE TITLE
Increasing a Skill Group with karma after skill group points costs extra karma

### ISSUE THREAD

**Issue by damaleon** [chummer5a/chummer5a#975]
### Environment
Chummer Version: 5.181.51
Environment: Windows 7 Professional
Runtime: .NET 4.6.1 (if I'm reading my registry correctly)

### Expected behaviour
Increasing a skill group with karma on top of group points during creation should only cost the (new level X 5) karma per level added.

### Actual behaviour
Increasing with karma costs (new level X 5) + (last level X 5) for the first point. Adding additional points with karma costs the expected amount.
For example, putting 2 skill group points in Athletics and then increasing it with karma to 3 should cost 15 karma, but subtracts 25 (a second boost only costs an additional 20 karma). Putting 5 group points in Firearms and then boosting it to 6 with karma costs 55 instead of the expected 40.

### Steps to reproduce the behaviour
Create any Priority or Sum-to-Ten character, add skill group points to a skill group and then increase it with karma.

### Link to affected character file
[testing.chum5.txt](https://github.com/chummer5a/chummer5a/files/339792/testing.chum5.txt)

**Comment by joha4270** [comment]
Oh, damit.

At least i know exactly what is wrong, should have a fix up within the next half hour, unless something unexpected happens.
