### ISSUE TITLE
Data from override data file not being used

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#977]
### Environment
Chummer Version: Nightly 5.181.53
Environment: Windows 8.1
Runtime:  .NET 4.5.2

### Expected behaviour
Contents of override_armor, specifically names, replace values from armor file.

### Actual behaviour
Values from armor file are displayed unchanged.

Note: this seems to be a further example of issue #957.

### Steps to reproduce the behaviour
Create an override_armor file, changing the name of an entry.
Add "Clothing and Armor" - the entry still shows the original name.

**Comment by joha4270** [comment]
I'll need you to upload your override data file to realistically debug this

**Comment by Lochabar** [comment]
The problem was with my override file. Not an actual problem.
