### ISSUE TITLE
Legacy skill groups are not loaded

### ISSUE THREAD

**Issue by johusman** [chummer5a/chummer5a#978]
### Environment
Chummer Version: 5.181.56.0 Nightly build
Environment: Windows 7
Runtime: .NET 4.5.1

### Expected behaviour
Skill groups in the (not that) old XML format from version 0.5.178.0 should load fine.

### Actual behaviour
Skill group points are not loaded at all. Instead the points appear distributed on the individual skills the group is composed of, as if you had overcommitted there instead. This means that information about group configuration is lost. Also, since the application thinks that you have bought individual skills instead - which is more expensive - it shows a negative value for Active Skills, and refuses to move to Career Mode.

If I'm reading the code correctly, no attempt is even made to load from /character/skillgroups .

### Steps to reproduce the behaviour
Bump some skill groups in 0.5.178, save, and load the file in 5.181

**Comment by joha4270** [comment]
It is done this way as the underlying storage is changed and skills are really a product of skillgroup + skill levels now, unlike before where skillgroups/skills had a lot of logic to keep skills and their skillgroups in sync, something that is simpler now and more maintainable now.

Would be possible to fix, but i'm not sure i'm wanting to. It would make the conversion quite a lot more fragile and i place user data quite a lot higher than user convenience. 

Going to leave this open while i think about it, but probably won't fix.

**Comment by johusman** [comment]
While I agree that the new architecture for skills seems much more sensible, I don't quite see how doing some custom transformation of legacy data at file load time would compromise it. It's still totally fine to save in the new format; I'm just requesting that it should attempt to load the old properly (since it *does* corrupt user data as it is now).

If you choose not to fix it, I would at least request there be some kind of warning message at load time. It took us 30 minutes to find the root problem, and then more to find an older release which could load our characters properly, which is what we are using now.

I appreciate that this might be more complicated than I'm making it out to be, though.

**Comment by joha4270** [comment]
Just doing work on the save file _is_ possible, but not realistic or feasible at all. What you probably mean is load the data into memory and manipulate it from there. More feasible but it still requires you to recreate all the logic for linking skills to their skillgroups. 

From there, it should be easy enough to reduce skills and increase groups by the same amount, but i'm worried about edge cases. 

And finally, is it so hard to sort skills by group name and manually move skills to groups?

**Comment by Jedi-Wolf** [comment]
I ran into an error that I believe is from the same issue as this. Very similar steps, except its opening a character in 5.181 that was marked as complete in 5.178, instead of one that is still editable. In this case the skill groups are still listed with their correct values, but one of the skills within a taken skill group is wrong. The skill group of stealth was taken at a 2, but the sneaking skill from that group is listed as a 4. Nothing else is different (if the file is opened up in 5.178 again everything is fine).

Not a huge deal, we have a uncompleted version saved, so we'll just move that to 5.181 and correct any issues, but if there was no uncompleted version we would have to stick with 5.178 or have incorrect skill ratings.

**Comment by chummer5a** [comment]
Catlike previously had the wrong bonus applied; hitting Reapply Improvements might sort it.
