### ISSUE TITLE
Cannot edit Limit Value Modifier title

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#979]
### Environment
Chummer Version: Nightly 5.181.53
Environment: Windows 8.1
Runtime: .NET 4.5.2

### Expected behaviour
Be able to modify a limit modifier title. (Right click and Edit.)

### Actual behaviour
Cannot modify a limit modifier title. (Not the notes.)

### Steps to reproduce the behaviour
Add a limit modifier.

### Link to affected character file
Wanted to change the title from "except Intimidation" to "Except for Intimidation".

https://www.dropbox.com/s/ywmd36suwnwca6j/Limit%20modifier.jpeg?dl=0

**Comment by chummer5a** [comment]
Fixed in the latest commit.
