### ISSUE TITLE
House Rules > Free Contact Points text

### ISSUE THREAD

**Issue by skachm** [chummer5a/chummer5a#981]
### Environment
Chummer Version: 5.182.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Options > House Rules > Free Contact Points are calculated with augmented **CHA** values.

### Actual behaviour
Options > House Rules > Free Contact Points are calculated with augmented **LOG+INT** values.

But a side note: I don't think 5th ed. has a way to augment Charisma at character generation. (Tailored Pheromones, Commanding Voice, etc. all add bonus dice rather than increasing Charisma and you can't start with a sustained spell to boost it.)

**Comment by chummer5a** [comment]
Fixed in current nightlies.
