### ISSUE TITLE
Custom Knowledge Skills Career Mode

### ISSUE THREAD

**Issue by victorypuppet** [chummer5a/chummer5a#982]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182.0
Environment: Windows 7
Runtime: NET 4.5.1

### Expected behaviour
When adding a new custom Knowledge Skill in Career Mode I should be able to change the category of the knowledge skill to either Street, Interest, Academic, Language, or Professional. Also it should cost a point of karma to add the skill.

### Actual behaviour
When adding a new custom Knowledge Skill in Career Mode I am unable to change the category of the knowledge skill to either Street, Interest, Academic, Language, or Professional. Instead it is automatically a category that benefits from Logic. I am unsure which category specifically since it does not even state the category. Also Chummer doesn't deduct a point of karma to add the skill even though it adds it at rating 1.

Please find screenshot attached.
![capture](https://cloud.githubusercontent.com/assets/18119437/16537374/e848e49e-3fce-11e6-9657-862c03b1b126.JPG)

**Comment by prismatic-mind** [comment]
I have a problem with career mod while adding knowledge skills. For some reason, when i add a knowledge skill, it don't show up in the list and skill is not listed in karma expense.
If i add a second knowledge skill, the first one is shown but se second one is not.
I have 23 knowledge skills, and sadly i don't remember if the problem occur just in version 182. Previously, i added successfully som knowledge skills but not sure of the version used.
