### ISSUE TITLE
No Special Attribute Costs/ Not able to skill Groups in Karma System

### ISSUE THREAD

**Issue by Len1991** [chummer5a/chummer5a#985]
### Environment
Chummer Version: 5.182.63
Environment: Win 7
Runtime:  .NET 4.6.1

### Expected behaviour
Adding points to Magic lowers my Karma Pool / I can put Points into Skill Group

### Actual behaviour
I still got the Same amount of Karma/ I see it says Karma but there is no column under it where i can spend it

### Steps to reproduce the behaviour
Add points to MAG / Look in the Skill Tab

**Comment by joha4270** [comment]
This is 2 different issues and should be posted individually.
