### ISSUE TITLE
Not able to spend Karma on skill Groups

### ISSUE THREAD

**Issue by Len1991** [chummer5a/chummer5a#986]
### Environment
Chummer Version: 5.182.63
Environment: Win 7
Runtime:  .NET 4.6.1

### Expected behaviour
I see a column where i can spend points to Skill Groups

### Actual behaviour
I see the Title saying Karma, but there is no column beneath
### Steps to reproduce the behaviour
Look in the Skill Tab

**Comment by cchopps** [comment]
I am having a similar issue. The Skills Groups are visible, but everything is greyed out.
Same Chummer. 
Win7 (64) 
Net 4.6

![screenshot](https://cloud.githubusercontent.com/assets/16066653/16669609/1699acde-445c-11e6-8ba3-8b25c9589220.jpg)

**Comment by chummer5a** [comment]
Can't replicate it in current builds; can you please try updating and let me know how that goes? If it still doesn't work, please upload your character file.

**Comment by cchopps** [comment]
I just downloaded the newest build and have the same issue.


[Test.zip](https://github.com/chummer5a/chummer5a/files/360496/Test.zip)

**Comment by chummer5a** [comment]
Hrm, still can't replicate it. I can see the character's built with life modules, does it doe the same thing if you use priority or karmagen?

**Comment by cchopps** [comment]
It does. I had taken a quick peek at priority earlier and thought it was working but didn't pay close attention. On Priority, I can spend my Skill Group Points, but the column for karma expenditures is just missing. The heading is there but no column.

![chummer screenshot 2](https://cloud.githubusercontent.com/assets/16066653/16847298/e918d7e4-49b5-11e6-9213-0f66352b7cbc.jpg)

**Comment by Iridios** [comment]
If you go into Screen Resolution.  Then click on the link to "Make Text and Other Items Larger or Smaller"  I get the same result when I set it to 'Medium (125%).  Try setting it to 'Smaller' and then check the screen.

**Comment by cchopps** [comment]
Yep. That fixes it... though, I have old man eyes so that is kinda a bummer. Is there any way to adjust the columns (or however the UI works) so that everything could be visible on the 'Medium' setting? Adjusting the window size doesn't help.

Thank you!

**Comment by chummer5a** [comment]
Will have to take a look at MoveControls again, but I've never run into
these problems using Windows 10, for whatever that's worth.

**Comment by Iridios** [comment]
If I may offer a suggestion.  The skill specialization fields could probably be made shorter.  This would allow more space for other features to display.   Most players (that I am aware of) never take more than one specialization.  On the rare occasion that a player has more specializations than can be displayed maybe the field then can become a drop down field

**Comment by chummer5a** [comment]
That's not really the problem; it seems to be something to do with the styling on the button to add an exotic skill, but there's no reason it should behave that way that I can see. Until I can get access to a development VM that's running 7 I won't be able to do much to troubleshoot it.

**Comment by chummer5a** [comment]
[Debug.zip](https://github.com/chummer5a/chummer5a/files/399159/Debug.zip)
Can I get you to give this a shot? It's a bit uglier than the standard chummer UI since I've remove the ability to apply client styling to the main windows, but if it works then I know where the problem is.

**Comment by cchopps** [comment]
Nope. Still doing the same thing. I switched over to Win10, but still have custom scaling on via Display. I think Win 10 lets you adjust scaling for individual programs unlike Win7. I'll see how low it has to go for it to work.

**Comment by chummer5a** [comment]
Okay, I've tested this in Windows 7 and 10 with a variety of resolutions and DPI settings and can't reproduce it. I'm going to need some more detail to be able to look into this further; as far as I can see all of the code is configured properly, so it's got to be something environmental throwing it off.
