### ISSUE TITLE
What is the "Backstory" button?

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#987]
With a character in create mode, on the "Character Info" tab, there is a "Create Backstory button. Clicking it does nothing. And it is no longer present with a character in Career mode.

### Environment
Chummer Version: Nightly 5.182.63
Environment: Windows 8.1
Runtime: .NET 4.5.2

### Steps to reproduce the behaviour
Create a character. Select "Character Info" tab.

### Link to affected character file
Create mode: https://www.dropbox.com/s/k4kdkwpy8cb6zmp/Backstory%20%28create%20mode%29.jpeg?dl=0

Career mode: https://www.dropbox.com/s/9cyxvdokjxc3ikn/Backstory%20%28career%20mode%29.jpeg?dl=0

**Comment by joha4270** [comment]
For life modules, it writes a simple backstory for your character. Its a bug that it is visible for any other kind of create modes (karma/priority/sumtoten).
