### ISSUE TITLE
Crash via Updater when endpoints are unavailable

### ISSUE THREAD

**Issue by usernamestaken** [chummer5a/chummer5a#989]
### Environment
Chummer Version: 5.182.0
Environment: Server 2012 R2
Runtime: 4.0.30319

### Expected behaviour
Updater handles the error when a connection can not be made

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Filter out any of the netblocks used on an egress firewall/proxy and attempt to update

Fastly
Amazon AWS
Dropbox

**Comment by chummer5a** [comment]
Bleah, I thought that might happen.
