### ISSUE TITLE
Chummer crashes when attempting to create a magical character

### ISSUE THREAD

**Issue by PrecociouslyDigital** [chummer5a/chummer5a#991]
### Environment
Chummer Version: 5.181.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
A new character is created

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Create any non-mundane character

### Link to affected character file
N/A

**Comment by OLStefan** [comment]
Already fixed in latest stable release, next time try checking for a new version before reporting a bug.

**Comment by PrecociouslyDigital** [comment]
Sorry thanks.
