### ISSUE TITLE
Aspected Magician and Priority Menu

### ISSUE THREAD

**Issue by Armlessbastard** [chummer5a/chummer5a#992]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.812.0
Environment: Windows 7
Runtime:  .NET 4.6.1

### Expected behaviour
Selected Priority D for Magic Type (Adept/Aspected Magician), click scroll down and selected 'Aspected Magician'. Clicking second scroll selection to select variant (Spellcasting, Summoning, Alchemy) the select choice and create character.

### Actual behaviour
When attempting to select the choice of Aspected Magician ability (Spellcasting, summoning Alchemy) I recieve a blank selection screen, unable to select a category I am unable to continue to character sheet.

### Steps to reproduce the behaviour
Create new character, select aspected Magician and then select Aspected Magician category.

### Link to affected character file
None

**Comment by Armlessbastard** [comment]
I was able to do this on my laptop which is using Windows 8 - but the aspected magician didn't get his magic ratingx2 in Spells.

**Comment by radoslawg** [comment]
+1.
To reproduce:
1. Create new character
2. Build method: Priority, Standard
3. Select Magic or Resonance priority D (other priorities work)
4. Select "Aspected Magician - 2 Magic" from combobox.
5. Text appears: "Based on your talent selection, you may choose 1 magical skill group to start at rating 0" and combobox is empty. 
6. If Ok is pressed error shows up "You must select Skill/Skill Group before continuing." and I cannot proceed.
