### ISSUE TITLE
Very Slow During Item Purchase [Career Mode]

### ISSUE THREAD

**Issue by arcvalor** [chummer5a/chummer5a#997]
### Environment
Chummer Version: 5.182.0
Environment: Win 7
Runtime: 

### Expected behaviour
Purchases happen relatively quickly in career mode

### Actual behaviour
Purchases take 15-20s to finish processing

### Steps to reproduce the behaviour
Go into career mode
Buy stuff
Wait a very long time

**Comment by chummer5a** [comment]
Unable to replicate. What are you buying? Can you upload your character file?
